### ISSUE TITLE
请发行一个x86-generic版本吧

### ISSUE THREAD

**Issue by jzhou404** [pymumu/smartdns#10]
用 openwrt/LEDE 的32位版本， 请发行一个x86-generic版本吧？ 谢谢

**Comment by pymumu** [comment]
还有x86的，x86不是该淘汰了么？
什么硬件啊。

**Comment by jzhou404** [comment]
Atom N270

继续改造ATOM N270增加千兆口自制软路由
http://www.right.com.cn/forum/thread-329884-1-1.html

**Comment by osdu** [comment]
x86 软路由

**Comment by pymumu** [comment]
编译出对应的版本了，可以测试验证下。
