### ISSUE TITLE
最近迷上了APEX英雄，不过用smartdns玩很不稳定

### ISSUE THREAD

**Issue by cjameslynn** [pymumu/smartdns#100]
**问题现象**  
开启smartdns，玩APEX英雄。各种掉线卡顿
关掉smartdns，没问题了

**运行环境**
1. 固件型号  LEDE X64

2. 运营商  电信

**重现步骤**
1. 上游DNS配置：尝试过只配置一个dns也不行。

2. 访问的域名：APEX英雄，联机

**Comment by pymumu** [comment]
猜测可能是返回的ip地址不稳定，虽然ping快，但可能丢包

可以尝试ping游戏服务器看看，有没ping超时
或者用ignore-ip过滤掉慢的ip地址。
