### ISSUE TITLE
smartdns作为Adguard Home的上游服务器，开了过期缓存服务，但是响应时间间歇性大于1ms

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1001]
![image](https://user-images.githubusercontent.com/10081071/182804049-7c4a080d-9d37-4fd1-8cae-f3ca55630739.png)

**需求应用场景**
Adguard Home中获取smartdns已缓存域名的解析时间小于1ms，从图中可以看到，s1c.time.edu.cn这个域名是缓存了的，但是在几次响应时间为1ms以下之后，出现了超过3ms的响应时间，是缓存失效了么？我需要动哪些配置？

**建议的方案**
无

**设备信息**
1. 设备信息（CPU，厂家）  
7100u
smartdns r37 rc3

2. 固件信息
koolshare op 2.37

**Comment by yyysuo** [comment]
另外smartdns作为Adguard Home上游dns服务器返回过期缓存的情况下，如何设置Adguard Home的ttl呢？我试过设置Adguard Home的ttl为1ms，导致b站的验证码刷新不出来。

**Comment by yyysuo** [comment]
粘一下配置

server-name mydns
bind :6053
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 102400000
rr-ttl 30
rr-ttl-min 30
rr-ttl-max 30
log-size 64K
log-num 1
log-level error
server 10.10.10.1:55  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

**Comment by PikuZheng** [comment]
>serve-expired yes

建议同时配置 serve-expired-ttl

另外建议看一下smartdns的debug日志，adguard上来的查询请求究竟有没有走缓存，或是ttl已经超时了

**Comment by yyysuo** [comment]
> >serve-expired yes
> 
> 
> 
> 建议同时配置 serve-expired-ttl
> 
> 
> 
> 另外建议看一下smartdns的debug日志，adguard上来的查询请求究竟有没有走缓存，或是ttl已经超时了
> 
> 
> 
> 
看了一下，意思是过期缓存的最长超时时间，有点不明白什么意思啊，默认值是0，过期缓存的本意就是把ttl过期的结果返回给客户端，默认是0的话，不就等于把过期缓存的开关给关了么，我设置为3600秒，是不是意味着过期的dns结果会保留1个小时，1个小时之后过期的缓存会被清除么。

**Comment by ZYB14** [comment]
#694

**Comment by pymumu** [comment]
用dig命令看看吧

**Comment by yyysuo** [comment]
> 用dig命令看看吧
> 
> TTL那些，建议只保留rr-ttl-min 设置为rr-ttl-min 600

大佬好，正好dig了2次，第1次0ms，第2次4ms，再后多dig几次全是0ms了，但是我看dig的日志看不懂。



root@Openwrt:~# dig www.jd.com @10.10.10.100 -p 6053

; <<>> DiG 9.17.11 <<>> www.jd.com @10.10.10.100 -p 6053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22968
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 2048
;; QUESTION SECTION:
;www.jd.com.                    IN      A

;; ANSWER SECTION:
www.jd.com.             11      IN      CNAME   www.jd.com.gslb.qianxun.com.
www.jd.com.gslb.qianxun.com. 11 IN      CNAME   www.jdcdn.com.
www.jdcdn.com.          11      IN      CNAME   img2x-v6-sched.jcloudedge.com.
img2x-v6-sched.jcloudedge.com. 11 IN    A       27.36.125.3

;; Query time: 0 msec
;; SERVER: 10.10.10.100#6053(10.10.10.100) (UDP)
;; WHEN: Fri Aug 05 00:24:09 CST 2022
;; MSG SIZE  rcvd: 157

root@Openwrt:~# dig www.jd.com @10.10.10.100 -p 6053

; <<>> DiG 9.17.11 <<>> www.jd.com @10.10.10.100 -p 6053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51245
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 2048
;; QUESTION SECTION:
;www.jd.com.                    IN      A

;; ANSWER SECTION:
www.jd.com.             3       IN      CNAME   www.jd.com.gslb.qianxun.com.
www.jd.com.gslb.qianxun.com. 3  IN      CNAME   www.jdcdn.com.
www.jdcdn.com.          3       IN      CNAME   img2x-v6-sched.jcloudedge.com.
img2x-v6-sched.jcloudedge.com. 3 IN     A       27.36.125.3

;; Query time: 4 msec
;; SERVER: 10.10.10.100#6053(10.10.10.100) (UDP)
;; WHEN: Fri Aug 05 00:25:37 CST 2022
;; MSG SIZE  rcvd: 157

**Comment by pymumu** [comment]
没有问题，偶尔4ms是操作系统调度的执行dig命令的消耗。

**Comment by yyysuo** [comment]
> 没有问题，偶尔4ms是操作系统调度的执行dig命令的消耗。

多谢解惑。
