### ISSUE TITLE
[Feature Request] address项配置了v4地址时，对AAAA请求返回空

### ISSUE THREAD

**Issue by uid36216** [pymumu/smartdns#1006]
**需求应用场景**
用户配置host时，通常意味着对A请求返回指定IP，对AAAA请求返回空，不向上游查询。
例如，dnsmasq的配置项 **address=/doubleclick.net/127.0.0.1** 对A请求返回127.0.0.1，对AAAA请求返回NX DOMAIN
smartdns的配置项 **address /doubleclick.net/127.0.0.1** 会把AAAA请求向上游查询，造成DNS泄露。虽然这个例子的域名并不敏感。
目前想要防止这个例子中的DNS泄露，只能另外写一行 **address /doubleclick.net/#6**

**建议的方案**
考虑修改address配置项的逻辑，当指定IP的v4地址时，对AAAA请求返回空。反之，当指定IP为v6地址时，对A请求返回空。
或者允许在一行address配置项中同时指定：对v4返回所配置的地址，对v6返回空。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by PikuZheng** [comment]
`domain-rules /.apple.com/ -a #6 -a 1.2.3.4`

**Comment by uid36216** [comment]
好的
