### ISSUE TITLE
openwrt 分支: 22.03.0-rc6 内核: 5.15.49，安装smartdns release37后的问题反馈

### ISSUE THREAD

**Issue by digiw** [pymumu/smartdns#1007]
**问题现象**  
1. luci 界面smartdns无法显示运行状态，一直显示：正在收集数据...
2. 当启用重定向功能时，
  》 重定向53端口无效，测试显示：

nslookup -querytype=ptr smartdns
Server:         127.0.0.1
Address:        127.0.0.1:53

** server can't find smartdns: NXDOMAIN

  》当模式改为“作为dnsmasq的上游服务器” 时，测试有效，测试显示：
nslookup -querytype=ptr smartdns
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
smartdns        name = smartdns
-----------------------------------------
无论情况2是否生效，情况1始终这样；
对于情况2，重定向53端口无效，很迷惑，不知道似乎不是和固件用了firewall4（nftable）有关？请大佬诊断

**运行环境**
1. 固件型号：openwrt 分支: 22.03.0-rc6 内核: 5.15.49

4. 运营商 ：chinatelecom

5. smartdns来源以及版本：来自git官网的release 37 手动安装

6. 涉及的配置(注意去除个人相关信息)
   config smartdns
	option server_name 'smartdns'
	option port '6053'
	option tcp_server '1'
	option ipv6_server '1'
	option dualstack_ip_selection '1'
	option prefetch_domain '1'
	option serve_expired '1'
	option cache_size '1000000'
	option rr_ttl_min '300'
	option seconddns_port '6553'
	option seconddns_tcp_server '1'
	option seconddns_no_speed_check '0'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_ipset '0'
	option seconddns_no_rule_soa '0'
	option seconddns_no_dualstack_selection '0'
	option seconddns_no_cache '0'
	option force_aaaa_soa '0'
	option coredump '0'
	option enabled '1'
	option redirect 'dnsmasq-upstream'
	list old_redirect 'dnsmasq-upstream'
	list old_port '6053'
	list old_enabled '1'

**重现步骤**
1. 上游DNS配置。  

3. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
此文件内容不多，如下：
[2022-08-07 23:15:12,288][ERROR][            dns.c:1694] decode opt failed, 
[2022-08-07 23:16:02,146][ERROR][            dns.c:1694] decode opt failed, 
[2022-08-07 23:17:42,634][ERROR][            dns.c:1694] decode opt failed, 
[2022-08-07 23:20:26,986][ERROR][            dns.c:1694] decode opt failed, 
[2022-08-07 23:26:03,421][ERROR][            dns.c:1694] decode opt failed, 
[2022-08-07 23:30:28,221][ERROR][            dns.c:1694] decode opt failed, 

2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
猜测是有其他服务修改了重定向，参考这个检查一下 #898 #212 

不过有挺多报告重定向出问题的，建议不要这么用

**Comment by PikuZheng** [comment]
#649 #947

**Comment by digiw** [comment]
> 猜测是有其他服务修改了重定向，参考这个检查一下 #898 #212
> 
> 不过有挺多报告重定向出问题的，建议不要这么用

感谢！！我去看了#212 的内容，我是开启了smartdns中的ipv6相关功能的，只有重定向模式失败，而上游模式是正常的，且我这个固件启用了firewall4 nftables替代了iptables，
固件内的相关模块是 libip6tc2，和firewall4，所以比较怀疑是否与此相关。
