### ISSUE TITLE
树莓派raspberry lite版本 不能运行smartdns

### ISSUE THREAD

**Issue by xingshu1990** [pymumu/smartdns#1008]
**问题现象**  
执行
```
# systemctl enable smartdns
# systemctl start smartdns
```

执行systemctl status smartdns.service报错如图：
![1](https://user-images.githubusercontent.com/18671173/183345326-939a76d9-4903-4637-a92d-fbfd8c8592c6.jpg)

稍微编辑了内容后，报错如下
![3](https://user-images.githubusercontent.com/18671173/183345335-a7831372-2ed2-48ab-b18c-9e8c1332d0f1.jpg)
配置文件如下，自行将后缀改为.conf
[smartdns.txt](https://github.com/pymumu/smartdns/files/9278960/smartdns.txt)

journalctl -xe 报错如图：
![2](https://user-images.githubusercontent.com/18671173/183345330-005f3c54-024f-4eeb-98f0-7630292c98ee.jpg)

**运行环境**
1. 树莓派3b+ raspberry lite
getconf LONG_BIT：32
uname -a：Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux
uname -m：armv7l
cat /etc/os-release ：
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

2. 运营商  
电信

3. smartdns来源以及版本
来源：https://github.com/pymumu/smartdns
版本：smartdns.1.2022.04.05-2046.x86-linux-all.tar.gz

4. 涉及的配置(注意去除个人相关信息)

端口号：
![5](https://user-images.githubusercontent.com/18671173/183351361-199b336d-1662-4279-a748-b93420e82da6.jpg)

**重现步骤**
smartdns.conf文件中暂无设置上游DNS设置。  
  
按照教程输入：
```
$ tar zxf smartdns.1.2022.04.05-2046.x86-linux-all.tar.gz(已更改为标准 Linux 系统（x86）版本)
$ cd smartdns
$ chmod +x ./install
$ ./install -i
```
```
# nano /etc/smartdns/smartdns.conf
简单改了IP为5553 或8053等非53端口 53端口已经执行pihole
```
执行
```
# systemctl enable smartdns
# systemctl start smartdns
```

执行systemctl status smartdns.service报错如图：
![1](https://user-images.githubusercontent.com/18671173/183345326-939a76d9-4903-4637-a92d-fbfd8c8592c6.jpg)

稍微编辑了内容后，报错如下
![3](https://user-images.githubusercontent.com/18671173/183345335-a7831372-2ed2-48ab-b18c-9e8c1332d0f1.jpg)
配置文件如下，自行将后缀改为.conf
[smartdns.txt](https://github.com/pymumu/smartdns/files/9278960/smartdns.txt)

journalctl -xe 报错如图：
![2](https://user-images.githubusercontent.com/18671173/183345330-005f3c54-024f-4eeb-98f0-7630292c98ee.jpg)

原先安装过smartdns+adguard home，后面又重新格式化tf卡以后，重新安装了raspberry lite版本
然后就是怎么都不能安装smartdns了。
非程序员，所以不懂debug，只是平时爱好折腾一些软件，浅浅的知道梯子和使用梯子，
对github、smardns、linux等之类的东西，只限于可能会安装，可能会配置，未必能运行的阶段。

**Comment by PikuZheng** [comment]
架构错误，armv7请勿使用x86程序编译

**Comment by PikuZheng** [comment]
参考#232，请试试 arm-debian

**Comment by xingshu1990** [comment]
> 架构错误，armv7禁止使用x86程序

谢谢 原先钻牛角尖：树莓派lite版本，怎么说也是GNU/Linux，
ipk文件，有一张卡里刷的是 openwrt，所以觉得怎么着也不是ipk格式
于是就一直认定是要下载smartdns.1.2022.08.06-1602.x86-linux-all.tar.gz
然后有时候有些人就是不想多尝试其他方法，所以才一直没安装成功。
