### ISSUE TITLE
老毛子安装报错

### ISSUE THREAD

**Issue by Avantyjw** [pymumu/smartdns#101]
**设备信息**
1. 设备信息（CPU，厂家）  
MT7621
2. 固件信息
padavan

首先没找到sda1这个目录 我就丢tmp下了

其次 log如下
[RT-N56U_B1 /tmp]# opkg install smartdns.1.2019.02.16-2240.mipselsf.ipk                                                                                                                                                          
Unknown package 'smartdns'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package smartdns.

**Comment by Avantyjw** [comment]
期待出一个老毛子padavan的教程

**Comment by pymumu** [comment]
架构不支持，
试试这个smartdns.1.2019.02.16-2240.mipsel-3.4.ipk

**Comment by Avantyjw** [comment]
好了 装上了嘻嘻

**Comment by pymumu** [comment]
可以改一下模式，替换dnsmasq。
/opt/etc/smartdns/smartdns-opt.conf
```
SMARTDNS_WORKMODE="2"
```

这个改成2.

**Comment by Avantyjw** [comment]
改了 刚重启完试试看

**Comment by Avantyjw** [comment]
C:\Users\Avant>nslookup -querytype=ptr 0.0.0.0
服务器:  RT-N56U_B1.lan
Address:  192.168.123.1

*** RT-N56U_B1.lan 找不到 0.0.0.0.in-addr.arpa.: Non-existent domain 好像启动不正常

**Comment by Avantyjw** [comment]
不过我家是光猫直接拨号的 是不是有影响

**Comment by Avantyjw** [comment]
等于我的路由是二级路由

**Comment by pymumu** [comment]
看一下进程有没有启动。
还有看一下dnsmasq的配置文件的里面DNS服务器的port有没有被设置为0

另外，你访问的DNS服务器，要是smartdns那个路由器。

**Comment by Avantyjw** [comment]
我连着的是 装了smartdns的路由器

**Comment by pymumu** [comment]
1. 进程在不在
2. 看一下dnsmasq的配置里面有没port=0
  cat /etc/dnsmasq.conf

**Comment by pymumu** [comment]
还有一点，你的DNS服务器，配置的是不是路由器的IP。

**Comment by Avantyjw** [comment]
[RT-N56U_B1 /opt/home/admin]# /opt/usr/sbin/smartdns -h
Usage: smartdns [OPTION]...                                                                                                                                                                                                      
Start smartdns server.                                                                                                                                                                                                           
  -f            run forground.                                                                                                                                                                                                   
  -c [conf]     config file.                                                                                                                                                                                                     
  -p [pid]      pid file path                                                                                                                                                                                                    
  -S            ignore segment fault signal.                                                                                                                                                                                     
  -v            verbose screent.                                                                                                                                                                                                 
  -h            show this help message.                                                                                                                                                                                          
Online help: http://pymumu.github.io/smartdns                                                                                                                                                                                    
Copyright (C) Nick Peng <pymumu@gmail.com> 

这样是不是在运行

**Comment by Avantyjw** [comment]
cat /etc/dnsmasq.conf                                                                                                                                                                              
user=nobody
resolv-file=/etc/resolv.conf
no-poll
bogus-priv
no-negcache
clear-on-reload
bind-dynamic
interface=br0
listen-address=192.168.123.1
min-port=4096
cache-size=1536
addn-hosts=/etc/storage/dnsmasq/hosts
servers-file=/tmp/dnsmasq.servers
domain=lan
expand-hosts
dhcp-range=set:lan,192.168.123.2,192.168.123.244,255.255.255.0,86400
dhcp-option=tag:lan,3,192.168.123.1
dhcp-option=tag:lan,6,192.168.123.1
dhcp-option=tag:lan,15,lan
quiet-dhcp
dhcp-hostsfile=/etc/dnsmasq/dhcp
dhcp-leasefile=/tmp/dnsmasq.leases
dhcp-authoritative
tftp-no-fail
conf-file=/etc/storage/dnsmasq/dnsmasq.conf
conf-dir=/etc/storage/dnsmasq/dnsmasq.d

**Comment by Avantyjw** [comment]
电脑dns是自动获取 路由器获取到的dns是上级路由（光猫）的192.168.1.1

**Comment by pymumu** [comment]
ps命令看进程是否启动，你这看上去是没有启动。

你执行一下/opt/etc/init.d/S50smartdns restart命令后，

在看看nslookup那个命令能不能正常

**Comment by Avantyjw** [comment]
/opt/etc/init.d/S50smartdns restart
ps: invalid option -- a                                                                                                                                                                                                          
BusyBox v1.29.3 (2019-02-23 06:54:52 CST) multi-call binary.                                                                                                                                                                     
                                                                                                                                                                                                                                 
Usage: ps                                                                                                                                                                                                                        
                                                                                                                                                                                                                                 
Show list of processes                                                                                                                                                                                                           
                                                                                                                                                                                                                                 
        w       Wide output                                                                                                                                                                                                      
        l       Long output                                                                                                                                                                                                      
        T       Show threads                                                                                                                                                                                                     
cannot find dnsmasq                                                                                                                                                                                                              
ps: invalid option -- a                                                                                                                                                                                                          
BusyBox v1.29.3 (2019-02-23 06:54:52 CST) multi-call binary.

**Comment by pymumu** [comment]
你路由没有启动dnsmasq。或者dnsmasq启动失败了

那你用默认的模式把。

/opt/etc/smartdns/smartdns-opt.conf

里面那个改成1

再执行
/opt/etc/init.d/S50smartdns restart

nslookup看一下是否正常。

最后再重启路由器确认一下是不是正常。

**Comment by Avantyjw** [comment]
/opt/etc/init.d/S50smartdns restart
执行了没反应

**Comment by Avantyjw** [comment]
1 模式正常了
服务器:  smartdns
Address:  192.168.123.1

非权威应答:
0.0.0.0.in-addr.arpa    name = smartdns

**Comment by pymumu** [comment]
有问题再提交issue

**Comment by Masstone** [comment]
> 架构不支持，
> 试试这个smartdns.1.2019.02.16-2240.mipsel-3.4.ipk

大佬，哪些用padavan 哪些用3.4呢
我的设备固件是padavan，
但是opkg print_architecture                                                                                                                                                                                                                                                     
arch all 100
arch mipsel-3x 150
arch mipsel-3.4 160
