### ISSUE TITLE
 F大的75+O，手动删除SMARTDNS36，安装37包和LUCI文件，OP服务无显示。

### ISSUE THREAD

**Issue by iamyangyiok** [pymumu/smartdns#1011]
F大的75+O，手动删除SMARTDNS36，安装ARM-OPENWRAT  37包和LUCI文件，OP服务无显示。

但软件包中显示已安装0806版本和LUCI，但无法显示服务。

  | 软件包名称 | 版本
-- | -- | --
移除 | luci-app-smartdns | 1.2022.08.06-1602
移除 | smartdns | 1.2022.08.06-1602

**Comment by PikuZheng** [comment]
#992 已知  luci-app......ipk 在基于 coolsnowwolf 的 lede 菜单中不显示。请先卸载 luci-app......ipk，在确保没有 luci-app......ipk 的情况下新装 luci-app.....-compat-all.ipk。

**Comment by iamyangyiok** [comment]
> 

这样操作过，删除了：LUCI-APP ，再装的LUCI-APP-COMPAT一样没有显示

**Comment by iamyangyiok** [comment]
> #992 已知 luci-app......ipk 在基于 coolsnowwolf 的 lede 菜单中不显示。请先卸载 luci-app......ipk，在确保没有 luci-app......ipk 的情况下新装 luci-app.....-compat-all.ipk。
这样操作过，删除了：LUCI-APP ，再装的LUCI-APP-COMPAT一样没有显示

**Comment by PikuZheng** [comment]
> > 
> 
> 这样操作过，删除了：LUCI-APP ，再装的LUCI-APP-COMPAT一样没有显示

可以排除smartdns的问题。建议到openwrt那边反馈

**Comment by 4thanks** [comment]
openwrt的luci app ipk可以试试[https://op.dllkids.xyz/packages/x86_64/](https://op.dllkids.xyz/packages/x86_64/luci-app-smartdns_git-22.133.34391-1952137_all.ipk)

**Comment by iamyangyiok** [comment]
> openwrt的luci app ipk可以试试[https://op.dllkids.xyz/packages/x86_64/](https://op.dllkids.xyz/packages/x86_64/luci-app-smartdns_git-22.133.34391-1952137_all.ipk)

谢谢 我是ARM的

**Comment by 4thanks** [comment]
> 谢谢 我是ARM的

luci app是通用的

**Comment by iamyangyiok** [comment]
还是不成功

**Comment by iamyangyiok** [comment]
> > > 
> > 
> > 
> > 这样操作过，删除了：LUCI-APP ，再装的LUCI-APP-COMPAT一样没有显示
> 
> 可以排除smartdns的问题。建议到openwrt那边反馈

不知道[pymumu]大大会不会修复下，指望OP基本无望。 太想用新版SMTDNS了

**Comment by iamyangyiok** [comment]
> > > 
> > 
> > 
> > 这样操作过，删除了：LUCI-APP ，再装的LUCI-APP-COMPAT一样没有显示
> 
> 可以排除smartdns的问题。建议到openwrt那边反馈

不知道[pymumu]大大会不会修复下，指望OP基本无望。 太想用新版SMTDNS了

**Comment by PikuZheng** [comment]
> 
> 不知道[pymumu]大大会不会修复下，指望OP基本无望。 太想用新版SMTDNS了

有没有x86版的 我安装试一下

**Comment by iamyangyiok** [comment]
> > 不知道[pymumu]大大会不会修复下，指望OP基本无望。 太想用新版SMTDNS了
> 
> 有没有x86版的 我安装试一下

他也是基于L大的 源 做得ARM版

**Comment by PikuZheng** [comment]
> 他也是基于L大的 源 做得ARM版

那我只能说coolsnowwolf的无论是预编译还是我自编译，都是正常的  ╮（╯＿╰）╭

**Comment by PikuZheng** [comment]
> 他也是基于L大的 源 做得ARM版

是Lienol的代码吗？查了下Flippy只做arm的内核文件
什么F大L大，缩写根本查不到

**Comment by pymumu** [comment]
安装完成后，重启过系统吗？

**Comment by PikuZheng** [comment]
特地用 Lienol 的代码（https://github.com/Lienol/openwrt） 编译了一份，安装后菜单中立即有了，不需要重启
![剪贴板05](https://user-images.githubusercontent.com/12579522/184659801-cd33b911-6df7-41ba-87f2-0dff26286181.png)
![剪贴板06](https://user-images.githubusercontent.com/12579522/184659827-ca0e1604-3453-4523-8a7b-bef983256bf3.png)

**Comment by iamyangyiok** [comment]
> 特地用 Lienol 的代码（[https://github.com/Lienol/openwrt）](https://github.com/Lienol/openwrt%EF%BC%89) 编译了一份，安装后菜单中立即有了，不需要重启 ![剪贴板05](https://user-images.githubusercontent.com/12579522/184659801-cd33b911-6df7-41ba-87f2-0dff26286181.png) ![剪贴板06](https://user-images.githubusercontent.com/12579522/184659827-ca0e1604-3453-4523-8a7b-bef983256bf3.png)

我用的FILPPY的工arm固件，重启过2个LUCI都分别装过，没有。

**Comment by PikuZheng** [comment]
> 
> 我用的FILPPY的工arm固件，重启过2个LUCI都分别装过，没有。

查了下Flippy只做arm的内核文件，并不做系统

**Comment by iamyangyiok** [comment]
> 恩山有 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4076037&highlight=74%2BO

**Comment by iamyangyiok** [comment]
> > 我用的FILPPY的工arm固件，重启过2个LUCI都分别装过，没有。
> 
> 查了下Flippy只做arm的内核文件，并不做系统
介绍：https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4076037&highlight=74%2BO
下载：https://pan.baidu.com/s/1kbvtyxpcmniLKN_ziH-kqQ  提取码：jla9

**Comment by PikuZheng** [comment]
花了亿点时间，把 Flippy 内核跑起来了。取的 Flippy 的内核和 Lienol 的 OpenWrt 源，目测比上面网盘里的版本高一点。
同样是安装 smartdns 和 luci-....compat，菜单中立即有，无需重启。
![剪贴板07](https://user-images.githubusercontent.com/12579522/184785746-2b884022-9838-4243-aa63-17e7b885cc36.png)
![剪贴板08](https://user-images.githubusercontent.com/12579522/184785772-413f0dc1-f0a9-4d69-93b6-0d30b16aebf3.png)

**Comment by iamyangyiok** [comment]
> 花了亿点时间，把 Flippy 内核跑起来了。取的 Flippy 的内核和 Lienol 的 OpenWrt 源，目测比上面网盘里的版本高一点。 同样是安装 smartdns 和 luci-....compat，菜单中立即有，无需重启。 ![剪贴板07](https://user-images.githubusercontent.com/12579522/184785746-2b884022-9838-4243-aa63-17e7b885cc36.png) ![剪贴板08](https://user-images.githubusercontent.com/12579522/184785772-413f0dc1-f0a9-4d69-93b6-0d30b16aebf3.png)

感谢，这就奇怪了，我用的5.4核心OP 75+的，然不成是皮肤问题。你是卸了全部SMARTDNS和LUC重I安装的不，装的是LUCI是兼容模式的，还标准的。

**Comment by iamyangyiok** [comment]
> 花了亿点时间，把 Flippy 内核跑起来了。取的 Flippy 的内核和 Lienol 的 OpenWrt 源，目测比上面网盘里的版本高一点。 同样是安装 smartdns 和 luci-....compat，菜单中立即有，无需重启。 ![剪贴板07](https://user-images.githubusercontent.com/12579522/184785746-2b884022-9838-4243-aa63-17e7b885cc36.png) ![剪贴板08](https://user-images.githubusercontent.com/12579522/184785772-413f0dc1-f0a9-4d69-93b6-0d30b16aebf3.png)

哦 是装的兼容 LUCI，另我看你这个 SNMARTDNS 是0816的，我看下载只有0806的版本

**Comment by iamyangyiok** [comment]
刚又装了次，没有用。 一样没用显示LUCI

**Comment by iamyangyiok** [comment]
好消息，我换了个皮肤，重启有了。10分感谢

**Comment by iamyangyiok** [comment]
新发现 就是37重装，还是老的配置文件可能有问题，海外上不去。 在调整查找原因。

**Comment by PikuZheng** [comment]
> 好消息，我换了个皮肤，重启有了。10分感谢

换回去一样有

**Comment by 4thanks** [comment]
@PikuZheng 不好意思歪个楼，我看你仓库更新虚拟机的分支编译，能否指导一下如何添加armv7的的编译，目前arm通用版，不能在[immortalwrt-18.06-k5.4](https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06-k5.4)安装
```
pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package smartdns.
```
之前fork你的仓库谷歌搜索修改，没成功放弃了，只能等正式版别人更新好的makefile再编译。我的路由是星际宝盒ipq40xx-mobipromo_cm520-79f，cpu是arm_cortex-a7_neon-vfpv4，谢谢。

**Comment by PikuZheng** [comment]
那个是github action自动编译，我也是照抄别人的。

`opkg print-architecture`请，原则上cortex-a7应该使用arm的包，不能安装的话怀疑opkg配置问题

**Comment by 4thanks** [comment]
> 那个是github action自动编译，我也是照抄别人的。
> 
> `opkg print-architecture`请，原则上cortex-a7应该使用arm的包，不能安装的话怀疑opkg配置问题
```shell
root@ImmortalWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch arm_cortex-a7_neon-vfpv4 10
```
这是什么情况？arch和aarch64什么关系？又和arm什么关系？

**Comment by PikuZheng** [comment]
> 
> 还是arm_cortex-a7_neon-vfpv4的构架，GitHub action的arm通用版安装不了，不能随时测试新版本了。

[试试这个](https://github.com/PikuZheng/smartdns/releases/tag/v37.5-2) 如果可行的话。
目前设置为2小时检查一次这边的更新，然后自动编译。但docker、tag什么的还得手动搞

**Comment by 4thanks** [comment]
> [试试这个](https://github.com/PikuZheng/smartdns/releases/tag/v37.5-2) 如果可行的话。 目前设置为2小时检查一次这边的更新，然后自动编译。但docker、tag什么的还得手动搞

谢谢，测试了下，这下是能安装了，不过无法运行，在系统日志看到这个：
`Wed Aug 17 08:30:00 2022 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash`

**Comment by PikuZheng** [comment]
> 
> 谢谢，测试了下，这下是能安装了，不过无法运行，在系统日志看到这个： `Wed Aug 17 08:30:00 2022 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash`

说明启动后立即崩溃了。查看一下smartdns自身日志怎么说，或者开coredump

**Comment by 4thanks** [comment]
> 说明启动后立即崩溃了。查看一下smartdns自身日志怎么说，或者开coredump
日志和coredump都没有记录。
Google搜到这个[issues #17](https://github.com/kuoruan/openwrt-v2ray/issues/17)，麻烦大佬看看[openwrt-v2ray](https://github.com/kuoruan/openwrt-v2ray)自动编译yml有没有借鉴的

**Comment by PikuZheng** [comment]
> 日志和coredump都没有记录。 Google搜到这个[issues #17](https://github.com/kuoruan/openwrt-v2ray/issues/17)，麻烦大佬看看[openwrt-v2ray](https://github.com/kuoruan/openwrt-v2ray)自动编译yml有没有借鉴的

这方面我是半吊子水平，我这周末花点时间学习一下。另外您到我的项目下起issue吧，不在这里讨论了
