### ISSUE TITLE
release37 无法返回IPv6地址

### ISSUE THREAD

**Issue by yuxuan0107** [pymumu/smartdns#1012]
**问题现象**  
使用最新版本测试发现客户端无法接收到ipv6地址
1.尝试开启优先返回ipv6 无效
2.开启测速 开启优先返回v6 无效
3.最大返回ip数量设置为1 1-2项开启,无效
4.关闭最大返回ip数量 开启1-2 无效
5.关闭ip数量,开启测速 无效

**运行环境**
1. 固件型号  
x86
2. 运营商  
中国联通
3. smartdns来源以及版本
release37
4. 涉及的配置(注意去除个人相关信息)

server 117.50.177.205 -check-edns
server 223.5.5.5 -check-edns
server 202.102.128.68 -check-edns
server 202.102.134.68 -check-edns
server 119.29.29.29 -check-edns
server 1.2.4.8 -check-edns
server 114.114.114.114 -check-edns
server 52.80.52.52 -check-edns
server 123.125.81.6 -check-edns
server 223.6.6.6 -check-edns
server 210.2.4.8 -check-edns
server 114.114.115.115 -check-edns
server 140.207.198.6 -check-edns
server 202.102.152.3 -check-edns
server 202.102.154.3 -check-edns
server 117.50.10.10 -check-edns
bind [::]:53
bind-tcp [::]:53
cache-size 512000
cache-persist yes
cache-file /root/smartdns.cache
prefetch-domain yes
serve-expired yes
serve-expired-ttl 0
force-qtype-SOA 65 28
log-level warn
log-file /tmp/log/smartdns.log
log-size 128k
**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
www.cctv.com
www.iqiyi.com
www.youku.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
```
force-qtype-SOA 65 28
```
查询类型28就是AAAA记录，这里强制将AAAA记录查询返回不存在

**Comment by yuxuan0107** [comment]
经过测试发现 当force-qtype-SOA 65 28 开启时,无法返回ipv6

**Comment by yuxuan0107** [comment]
> ```
> force-qtype-SOA 65 28
> ```
> 
> 查询类型28就是AAAA记录（由RFC3596定义），这里强制将AAAA记录查询返回不存在，所以查询不会有ipv6结果

刚刚测试完,发现你也回复了,感谢回复
