### ISSUE TITLE
connection timed out; no servers could be reached和-exclude-default-group组dns请求泄露至default组

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1013]
**问题现象** 
smartdns运行一段时间（几个小时~1天）后，在主路由及局域网设备dig某些域名出现connection timed out; no servers could be reached错误，此时luci界面显示服务运行正常，其它域名解析正常，重启服务后问题消失，此问题曾多次出现，可复现，但是触发时机尚未发现。

此问题可能与https://github.com/pymumu/smartdns/issues/914 https://github.com/pymumu/smartdns/issues/836 相关。

dig 6053 7053 8055端口均出现错误
root@Openwrt:~#
root@Openwrt:~# dig +nocmd +noall +answer +ttlunits A encrypted-tbn3.gstatic.com @10.10.10.1  -p 8055
;; connection timed out; no servers could be reached
root@Openwrt:~# dig +nocmd +noall +answer +ttlunits A encrypted-tbn3.gstatic.com @10.10.10.1 -p 7053
;; connection timed out; no servers could be reached
root@Openwrt:~# dig +nocmd +noall +answer +ttlunits A encrypted-tbn3.gstatic.com @10.10.10.1 -p 6053
;; connection timed out; no servers could be reached

修改smartdns luci界面任意选项，保存并应用（重启smartdns）后问题消失
root@Openwrt:~# dig +nocmd +noall +answer +ttlunits A encrypted-tbn3.gstatic.com @10.10.10.1 -p 8055
encrypted-tbn3.gstatic.com. 3s  IN      A       142.250.66.46
root@Openwrt:~# dig +nocmd +noall +answer +ttlunits A encrypted-tbn3.gstatic.com @10.10.10.1 -p 7053
encrypted-tbn3.gstatic.com. 3s  IN      A       142.250.66.46
root@Openwrt:~# ^C
root@Openwrt:~# dig +nocmd +noall +answer +ttlunits A encrypted-tbn3.gstatic.com @10.10.10.1 -p 6053
encrypted-tbn3.gstatic.com. 3s  IN      A       142.250.66.46

DNS结构
![image](https://user-images.githubusercontent.com/10081071/183896077-3f78f8a8-5529-416e-8b09-effed2a4426a.png)

DNS分流由科学软件及openwrt的dns转发实现，smartdns仅提供服务，8055为国内dns服务端口，7053为国外组dns端口，6053未配置上游dns（怀疑为报错原因），未启用重定向。

default组未配置上游dns，系统或者koolss转发到8055和7053的dns请求，没有dns请求被转发到6053端口，但是6053端口却收到了发往7053及8055的dns请求，因为default组未配置上游dns，log文件中持续出现Send query to upstream server failed, total server number 0错误。

**运行环境**
1. 固件型号  
Openwrt Koolshare Router V2.37 r17471-8ed31dafdf 内核版本 5.4.108

2. 运营商  
山东联通

3. smartdns来源以及版本，此问题在Release 37及36中都存在
https://github.com/pymumu/smartdns/releases/download/Release37/smartdns.1.2022.08.06-1602.x86_64-openwrt-all.ipk

4. 涉及的配置(注意去除个人相关信息)
server-name smartdns
bind :6053
bind-tcp :6053
dualstack-ip-selection no
cache-size 100000000
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
bind :7053  -no-speed-check -group foreign -no-dualstack-selection -force-aaaa-soa
bind-tcp :7053  -no-speed-check -group foreign -no-dualstack-selection -force-aaaa-soa
server 10.10.10.100  -group domestic -exclude-default-group
server 119.29.29.29  -group domestic -exclude-default-group
server 119.28.28.28  -group domestic -exclude-default-group
server 10.10.10.100:1056  -group foreign -exclude-default-group
server-tls 8.8.8.8:853  -group foreign -exclude-default-group
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

**重现步骤**
1. 上游DNS配置。  
server 10.10.10.100  -group domestic -exclude-default-group
server 119.29.29.29  -group domestic -exclude-default-group
server 119.28.28.28  -group domestic -exclude-default-group
server 10.10.10.100:1056  -group foreign -exclude-default-group
server-tls 8.8.8.8:853  -group foreign -exclude-default-group

2. 访问的域名。  
encrypted-tbn3.gstatic.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

问题发生时手动清除了日志，错误发生服务不可用时，始终无新日志文件产生，重启smartdns后日志文件重新生成，日志中重新出现Send query to upstream server failed, total server number 0错误。

待问题再出现时再更新最后的日志文件

几个疑问：
1：如何获取到7053和8055端口的日志？日志级别更改为debug后，也没有这2个端口的日志
2：6053/7053/8055服务的dns缓存是合并还是分开的？因为目前所有组的dns请求都会发往default组6053，导致如果用6053做国内组，国外组dns请求也会发往6053，造成dns污染。如果用6053做国外组，则国内组dns请求也会发往6053，造成cdn问题，京东淘宝等服务被定位到国外，速度受到影响。

**Comment by pymumu** [comment]
server-group分支代码看看。

**Comment by yyysuo** [comment]
> server-group分支代码看看。

不是需要我看代码吧，今天继续实验，发现并不是所有的域名都解析不了，而是只有特定的域名无法再解析，无日志，其它域名是正常的。

**Comment by pymumu** [comment]
让你用那个分支的代码编译后验证，不是让你看代码。

**Comment by yyysuo** [comment]
> 让你用那个分支的代码编译后验证，不是让你看代码。

超纲了呀，没编译过ipk或者固件。

**Comment by PikuZheng** [comment]
> > 让你用那个分支的代码编译后验证，不是让你看代码。
> 
> 超纲了呀，没编译过ipk或者固件。

https://github.com/PikuZheng/smartdns/releases/tag/v37.1_server-group

**Comment by yyysuo** [comment]
> > > 让你用那个分支的代码编译后验证，不是让你看代码。
> > 
> > 
> > 超纲了呀，没编译过ipk或者固件。
> 
> https://github.com/PikuZheng/smartdns/releases/tag/v37.1_server-group

多谢大佬，我需要重点测试哪些问题？

**Comment by PikuZheng** [comment]
> > > > 让你用那个分支的代码编译后验证，不是让你看代码。
> > > 
> > > 
> > > 超纲了呀，没编译过ipk或者固件。
> > 
> > 
> > https://github.com/PikuZheng/smartdns/releases/tag/v37.1_server-group
> 
> 多谢大佬，我需要重点测试哪些问题？我提到的2个问题都修复了么？

不清楚，我只是用server-group代码编译了一份 :)

**Comment by yyysuo** [comment]
> 让你用那个分支的代码编译后验证，不是让你看代码。

用了[PikuZheng](https://github.com/PikuZheng)大佬编译的server-group分支的ipk，已经不会产生错误日志了，debug日志显示了分别向不同的group发送的dns请求的详细信息。暂时还未发现server fail及connection timed out; no servers could be reached错误，持续观察中。

**Comment by yyysuo** [comment]
> > > 让你用那个分支的代码编译后验证，不是让你看代码。
> > 
> > 
> > 超纲了呀，没编译过ipk或者固件。
> 
> https://github.com/PikuZheng/smartdns/releases/tag/v37.1_server-group

[2022.08.11-2837407846](https://github.com/PikuZheng/smartdns/releases/tag/2022.08.11-2837407846)

最新编译的版本也是server-group分支的吗？

**Comment by PikuZheng** [comment]
> [2022.08.11-2837407846](https://github.com/PikuZheng/smartdns/releases/tag/2022.08.11-2837407846)
> 
> 最新编译的版本也是server-group分支的吗？

master分支的，自动编译，我还没看是怎么回事
