### ISSUE TITLE
smartdns 37 总是将本地 hostname 解析为 127.0.0.1

### ISSUE THREAD

**Issue by felixonmars** [pymumu/smartdns#1014]
**问题现象**  
smartdns 37 总是将本地 hostname 解析为 127.0.0.1，即使这个 hostname 有其他公网解析结果。这导致网关机器的 hostname 设置为 FQDN 时内网无法用 FQDN 正确访问网关。

smartdns 36 及以前版本无此问题。

**运行环境**
1. 固件型号
n/a

2. 运营商  
n/a

3. smartdns来源以及版本
Arch Linux
smartdns 37

4. 涉及的配置(注意去除个人相关信息)
n/a

**Comment by felixonmars** [comment]
补充：这个行为甚至无法用 `address` 来绕过。

**Comment by PikuZheng** [comment]
啥意思，是查询形如 smartdns.lan 的a记录 还是查询本地ip的ptr记录？

**Comment by felixonmars** [comment]
> 啥意思，是查询形如 smartdns.lan 的a记录 还是查询本地ip的ptr记录？

查询 smartdns 所在机器 hostname 的 a 记录。

**Comment by PikuZheng** [comment]
建议修改系统 resolv.conf 以避免错误结果

**Comment by PikuZheng** [comment]
另一方面独立的 hostname 不符合dns规范。请使用形如 hostname.domain 之类的符合标准的查询

**Comment by pymumu** [comment]
没看懂，补充一下具体复现步骤

**Comment by felixonmars** [comment]
> 建议修改系统 resolv.conf 以避免错误结果

系统 resolv.conf 里只有
nameserver 127.0.0.1
指向 smartdns

> 另一方面独立的 hostname 不符合dns规范。请使用形如 hostname.domain 之类的符合标准的查询

原文中已经解释 hostname 设置为 FQDN 了，这就是符合 dns 规范的设置。

> 没看懂，补充一下具体复现步骤

设置本地 hostname 为 `router.example.com` 并 restart smartdns，此时通过 smartdns 解析这个域名一定会返回 127.0.0.1，即使该域名其实有正常对公网解析的 A 记录。

**Comment by pymumu** [comment]
当前版本修改了主机名解析功能，逻辑是：查询路由器主机IP时，会使用客户端请求的IP地址回应。这个是为了支持多网口设备。

如果你是在同一个机器内部请求，做二次转发，那确实会获取到127.0.0.1的地址。当前版本没有参数控制。

可以修改这里看看：
https://github.com/pymumu/smartdns/blob/9dfe51c5ed69b242bccac96f85d3dfdfa87e554a/src/dns_conf.c#L1861-L1863
把这几行删掉。

**Comment by felixonmars** [comment]
修改这里后确实问题解决了。我这里网关上有个前置的 dnsmasq（为了 https://github.com/pymumu/smartdns/issues/354），所以确实存在同一台机器上内部请求、二次转发的问题。

希望可以有一个选项控制 :)

**Comment by pymumu** [comment]
最新代码改了下优先级，优先响应address的配置结果。
还有一个办法是，二级dns使用局域网ip访问smartdns，而不用127.0.0.1

两种方法都可以尝试。

**Comment by pymumu** [comment]
有BUG，刚刚解决了一下，最新代码合入了

**Comment by felixonmars** [comment]
37.2 OK 了，感谢。
