### ISSUE TITLE
请问conf-file可以嵌套吗？

### ISSUE THREAD

**Issue by Mosney** [pymumu/smartdns#1023]
比如SmartDNS的配置文件中有一行

> conf-file /path/to/partial.conf

此`partial.conf`的内容中有一行是

> conf-file /path/to/another_partial.conf

那么`another_partial.conf`中的配置项会生效吗？

---
此问题是使用OpenWrt版luci界面配置时发现的，默认预设只有三个固定的`conf-file`，分别对应luci三个文本框

> conf-file /etc/smartdns/address.conf
> conf-file /etc/smartdns/blacklist-ip.conf
> conf-file /etc/smartdns/custom.conf

没有发现能额外添加`conf-file`的地方，如果在上面三个其中之一添加一行`conf-file /path/to/xxx.conf`形成嵌套，不知是否能正确地传递配置文件？

**Comment by PikuZheng** [comment]
可以在例如 /path/to/partial.conf 配置文件中引用其他配置文件，支持多层嵌套。
循环引用程序会报错，应避免。
可以直接在“自定义设置”框框里填入其他配置文件引用。例如我的
```
# Add custom settings here.
# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
log-level debug

# log-size k,m,g
log-size 10m

# log-file /var/log/smartdns.log
log-num 2

# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip/subnet]

conf-file /etc/smartdns/anti-ad-for-smartdns.conf
```

**Comment by PikuZheng** [comment]
> @PikuZheng 看到你的配置文件内容就多说一句题外话，我觉得anti-ad并不值得用，误杀太多并且还有私货疑虑，详见https://github.com/Mosney/anti-anti-AD

现在改用的[neodevpro/neodevhost/lite_smartdns.conf](https://github.com/neodevpro/neodevhost/)，因为我需要在几个smartdns之间同步配置，就沿用了之前的名字没改

**Comment by lalasou** [comment]
@PikuZheng 官方docker是哪个？

**Comment by PikuZheng** [comment]
> @PikuZheng 官方docker是哪个？

不知道啊，我自己打的
