### ISSUE TITLE
以 address 指定要返回的 IP 时，仅会匹配单一类型的 DNS 请求

### ISSUE THREAD

**Issue by KaraRyougi** [pymumu/smartdns#1025]
**问题现象**  
smartdns 以 address 指定返回地址时，不会匹配所有的请求。

**运行环境**
x86_64 Debian apt package

**配置**
```
bind [::]:53
cache-size 16384

server-tls 8.8.8.8 -host-name dns.google -tls-host-verify
server-tls 8.8.4.4 -host-name dns.google -tls-host-verify
server-tls 2001:4860:4860::8888 -host-name dns.google -tls-host-verify
server-tls 2001:4860:4860::8844 -host-name dns.google -tls-host-verify

speed-check-mode none

address /netflix.com/#10.1.1.1
address /netflix.net/#10.1.1.1
address /nflxext.com/#10.1.1.1
address /nflximg.com/#10.1.1.1
address /nflximg.net/#10.1.1.1
address /nflxso.net/#10.1.1.1
address /nflxvideo.net/#10.1.1.1
```

**重现步骤**
打开 Netflix App。
Netflix App 会同时发起类型为 A / AAAA / HTTPS 的请求。
smartdns 仅会对其中的 A 记录请求返回我们指定的地址，对于 AAAA 和 HTTPS 类型的请求依然转发并返回了上游的解析结果。

**Comment by pymumu** [comment]
address /xx/#6

或者直接关闭IPV6
force-qtype-SOA 28

**Comment by PikuZheng** [comment]
这个写法有问题。应该分成两行
```
address /netflix.com/#6
address /netflix.com/10.1.1.1
```
或用domain-rule改写
```
domain-rules /netflix.com/ -a 10.1.1.1 -a #6
```

**Comment by KaraRyougi** [comment]
我之前是没有加入 # 号的，发现会漏 HTTPS 和 v6 请求。加 # 是我理解错文档意思了。

我理解可以针对域名禁用 v6 或者对 v6 单独返回结果，但是 HTTPS 类型的请求依然需要被全局禁用，感觉不是很理想。

以及理论上说，当用户手动指定 address 时，意图应当是对所有请求返回指定结果吧。

**Comment by PikuZheng** [comment]
> 以及理论上说，当用户手动指定 address 时，意图应当是对所有请求返回指定结果吧。

考虑到https查询对ios的诸多干扰，我支持全局禁用。以及希望address或domain-rules能控制更多类型的结果。
不过理论上客户端对A AAAA PTR 等都是分开请求的（虽然查询默认是A+AAAA）之前还发现过客户端先查cname，然后拿cname查A的情况
