### ISSUE TITLE
如果多个server是相同IP，则会有BUG

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#1027]
环境：arm64，版本：smartdns 1.2022.08.18-2327
配置如下：
server-tls 223.5.5.5 -whitelist-ip
server-tls 223.5.5.5 -group cndns -exclude-default-group
domain-rules /m.cnbeta.com/ -nameserver cndns

whitelist-ip是国内全部IP段

问题描述：
m.cnbeta.com，这个域名正常解析出来的IP是国外的，如果按上面的配置，解析不出任何结果

如果把第一个server修改为223.6.6.6，那就可以出结果，所以问题就在于，如果有2个server的解析配置完全相同，就会有BUG

**Comment by PikuZheng** [comment]
```
server-tls 223.5.5.5 -whitelist-ip
server-tls 223.5.5.5 -group cndns -exclude-default-group
```
这么写相当于 
```
server-tls 223.5.5.5 -group cndns -exclude-default-group -whitelist-ip
```
没理解一个上游为啥会出现两个不同的配置

**Comment by PHCSJC** [comment]
@PikuZheng 是这样的，第二个server用来解析已知的国内域名，第一个server是用来解析未知域名，然后匹配IP，如果是国内IP就接受，如果是非国内IP，就放弃，后面再用8.8.8.8来解析

具体需求我前2天发了，你可以看看这#1022

**Comment by PikuZheng** [comment]
这种情况设计上是用第二dns服务器来处理的，即多端口多进程。
如果是我有这样的需求，我会给第二个server指定一个不存在的ip然后从路由器中把它重定向到223.5.5.5

**Comment by PHCSJC** [comment]
@PikuZheng 你这样可以是可以，我换成223.6.6.6不是更简单吗？

再就是，我描述的这个问题，也能算是一个BUG吧？其实如果把第1个和第2个的server位置掉换一下，就又能查出结果

server-tls 223.5.5.5 -group cndns -exclude-default-group
server-tls 223.5.5.5 -whitelist-ip

domain-rules /m.cnbeta.com/ -nameserver cndns

**Comment by PikuZheng** [comment]
>你这样可以是可以，换成223.6.6.6是不是更简单呢？

我知道 但如果这个服务器是自建的 只有一个ip，还是应该考虑解决方案
>其实如果把第1个和第2个的server位置掉换一下，就又能查出结果

也就是说只有第一行起作用了？之前我测试是如果有两行相同配置，后一行会覆盖前一行。。。

**Comment by PikuZheng** [comment]
有点迷。比如配置了
```
log-level debug
log-level info   <---此行生效

address /m.cnbeta.com/#6
address /m.cnbeta.com/1.2.3.4    <---同时生效

server-tls 223.5.5.5 -group cndns -exclude-default-group    <---第一行生效？
server-tls 223.5.5.5 -whitelist-ip
```

**Comment by PHCSJC** [comment]
我测试就确实只有第一行生效，要不你试试？

另外，我的核心需求在#1022，你可以抛开这个贴子，看看这个需求怎么实现？感谢！

**Comment by PikuZheng** [comment]
> 我测试就确实只有第一行生效，要不你试试？
> 
> 另外，我的核心需求在#1022，你可以抛开这个贴子，看看这个需求怎么实现？感谢！

已经试过了的确是这样，所以我说有点迷惑 -_-|

# 1022 早就看过了，暂时没什么思路，等有空我再想想

**Comment by crackerfly** [comment]
简单 设置个独立服务器 223.6.6.6 或者其他alidns 的DoT DoH给这个专用 并排除服务器组

**Comment by PHCSJC** [comment]
@crackerfly 是的，现在就是这么干的，这个帖子主要是来反馈这个BUG的

**Comment by pymumu** [comment]
同类型，同IP只有一条记录生效。第一条记录。
