### ISSUE TITLE
response-mode和speed-check-mode怎么搭配？

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#1028]
功能好像有重复
1.first-ping和speed-check-mode的tcp同时设置会怎样？
2.first-ping和speed-check-mode的none会怎样？
3.到底怎样是返回一个ip？怎样是返回多个？
4.第一次返回1个最快的，第二次又是从缓存里返回5个，这个意义是什么？
5.这2参数有什么搭配的规则吗？

**Comment by pymumu** [comment]
1. 只是测速方式的改变。
2. 这样设置后，等价fastest-response
3. 默认配置在缓存没有命中时，会返回一个IP。之后，缓存命中会返回多个IP。
4. 提供给下载软件，视频软件更多IP地址。
5. 默认配置已经是最佳。
