### ISSUE TITLE
建议 domain-rules 新增 关闭 serve-expired 或 no-cache 的参数

### ISSUE THREAD

**Issue by kousyougi** [pymumu/smartdns#1029]
**需求应用场景**
fakedns 跟 使用动态IP的状态

**建议的方案**
在使用fakedns的状况，开了serve-expired功能九成九使用上会卡卡的。
或是自己家里的动态IP，大概一天会换新IP一次以上。
如果使用serve-expired的话，几乎要第二次连线才会拿到正确的IP。
这种状况会宁愿解析慢、解析正确。也不想要用cache跟serve-expired。
目前是设定很多 bind:xx -no-speed-check -no-cache 上下游 来回避这个问题。

另外有一个关于设定檔的建议，
同一个group需要的server、ipset、speed-check、no-cache、serve-expired设定几乎都是一样的。
这些设定(speed-check、no-cache、serve-expired、ipset)，现在有的接在bind后面跟着bind走、有些接在server后面跟着server走、有的接在domain-rules后面，其实有点混乱。

希望所有的设定都跟group走。同一个group用哪些server、要不要speed-check、cache、serve-expired、ipset可以直接设定在group里面。

然后组名设定在server跟bind后面是[-group [group] ...]到domain-rules后面就变成[-nameserver [group] ...]，有点不直观，要查范例才能确认用法。

**Comment by pymumu** [comment]
后面有空想下方案

**Comment by jxph1123** [comment]
确实很多配置有重复，功能也差不多，看得晕晕的，建议配置整合一下，精简下，更有助于设置和使用。

**Comment by pymumu** [comment]
done
