### ISSUE TITLE
请求一份优化比较好的配置文件。

### ISSUE THREAD

**Issue by lhuanyun** [pymumu/smartdns#1033]
以前在armbian openwrt 上使用smartdns。
总是感觉自己的设置有些问题
…
smartdns 可以有一份优化好的开箱即用配置文件吗？
总觉这个软件没有默认的使用配置，只要是用不好就是自己的问题。
谢谢伟大的网友们！

**Comment by 4thanks** [comment]
作者说过默认就是最佳设置，只需往里加适合的dns服务器就可以。
每个人需求不一样，所谓优化比较好的配置也可能不适合，像我之前有一个胡乱配置太多太杂，大家觉得没必要，可它刚好解决我一个手游访问登录的问题，精简或其他的配置就是不行，反正够用就懒得优化了。

附作者之前在其他issue的配置供你参考[1016#issuecomment-1213071454](https://github.com/pymumu/smartdns/issues/1016#issuecomment-1213071454)

**Comment by lhuanyun** [comment]
> 作者说过默认就是最佳设置，只需往里加适合的dns服务器就可以。
> 
> 每个人需求不一样，所谓优化比较好的配置也可能不适合，像我之前有一个胡乱配置太多太杂，大家觉得没必要，可它刚好解决我一个手游访问登录的问题，精简或其他的配置就是不行，反正够用就懒得优化了。
> 
> 
> 
> 附作者之前在其他issue的配置供你参考[1016#issuecomment-1213071454](https://github.com/pymumu/smartdns/issues/1016#issuecomment-1213071454)

谢谢你，好朋友
