### ISSUE TITLE
请问怎么设置可以让双栈网址都返回ipv4 只有ipv6才返回ipv6

### ISSUE THREAD

**Issue by CSSZYF** [pymumu/smartdns#1034]
如题 移动的ipv6实在是太烂了 基本上国内的ipv6网站都打不开 但我又需要ipv6公网进行moonlight串流和远程管理路由器 不能关闭ipv6 有什么办法呢 双栈优选也试过 ipv6返回快 但只要是用ipv6访问的网站就打不开

**Comment by CSSZYF** [comment]
开启强制AAAA地址返回SOA之后 刷新了dns缓存等待生效之后 打不开的网站可以打开了 moonlight串流也正常可以用 就是ipv6的网站基本上是寄了 不过体验已经好太多了 如有其他更好的方法还望告知

**Comment by PikuZheng** [comment]
重复 #852

**Comment by PikuZheng** [comment]
顺便问一下如果配置了 `dualstack-ip-selection yes` 且设备自身没有 ipv6 ip，还会返回ipv6结果吗？

**Comment by CSSZYF** [comment]
那个我看到了 但需要设置的网站实在是太多了 经常遇到各种应用加载不出来 我又不可能一个一个去设置 所以pass掉

**Comment by CSSZYF** [comment]
> dualstack-ip-selection yes

会的 即使设备没有ipv6地址 依旧会返回ipv6结果

**Comment by CSSZYF** [comment]
> ping -6 [www.qq.com](http://www.qq.com) 看看有没有结果，没有的话，就是你的机器无法访问IPV6网络，看看有没有IPV6的路由，网关。

自然是有结果的 ping是都通的 是大部分返回v6的双栈网站都会打不开 只有小部分正常 所以才提出来标题这个问题

**Comment by pymumu** [comment]
是让你用IPV6ping外部地址，看你的网络IPV6是否正常。

**Comment by CSSZYF** [comment]
> 是让你用IPV6ping外部地址，看你的网络IPV6是否正常。
> 
> PING [www.qq.com(2402:4e00:1020:1404:0:9227:71ab:2b74](http://www.qq.com(2402:4e00:1020:1404:0:9227:71ab:2b74) (2402:4e00:1020:1404:0:9227:71ab:2b74)) 56 data bytes 64 bytes from 2402:4e00:1020:1404:0:9227:71ab:2b74 (2402:4e00:1020:1404:0:9227:71ab:2b74): icmp_seq=1 ttl=53 time=6.83 ms 64 bytes from 2402:4e00:1020:1404:0:9227:71ab:2b74 (2402:4e00:1020:1404:0:9227:71ab:2b74): icmp_seq=2 ttl=53 time=8.52 ms 64 bytes from 2402:4e00:1020:1404:0:9227:71ab:2b74 (2402:4e00:1020:1404:0:9227:71ab:2b74): icmp_seq=3 ttl=53 time=8.56 ms

正在 Ping ins-r23tsuuf.ias.tencent-cloud.net [2402:4e00:1900:1400:0:9227:71e8:2ccc] 具有 32 字节的数据:
来自 2402:4e00:1900:1400:0:9227:71e8:2ccc 的回复: 时间=23ms
来自 2402:4e00:1900:1400:0:9227:71e8:2ccc 的回复: 时间=23ms
来自 2402:4e00:1900:1400:0:9227:71e8:2ccc 的回复: 时间=23ms
来自 2402:4e00:1900:1400:0:9227:71e8:2ccc 的回复: 时间=23ms
ping了ping了 是正常 别的打不开的网站也ping的通 但就是打不开 所以说是破移动的问题

**Comment by pymumu** [comment]
你这可以先排查路由器是否配置了ip6table导致数据被转发。可以路由器上ip6tabale看看。
可以用在路由器上检查下

```
 wget --inet6-only http://www.qq.com
```

如果有结果，就是路由器设置问题，没有就是运营商问题，可以找运营商解决。

**Comment by PikuZheng** [comment]
> 你这可以先排查路由器是否配置了ip6table导致数据被转发。可以路由器上ip6tabale看看。

他的问题是想，强制双栈只返回ipv4。但我记得之前讨论过，如果smartdns自身双栈优选失败，就不会返回ipv6？

**Comment by pymumu** [comment]
> > 你这可以先排查路由器是否配置了ip6table导致数据被转发。可以路由器上ip6tabale看看。
> 
> 他的问题是想，强制双栈只返回ipv4。但我记得之前讨论过，如果smartdns自身双栈优选失败，就不会返回ipv6？

他的问题是，ipV6的ping是正常的，http无法访问。smartdns检查ipv6是可以通的，所以就会返回ipv6地址。

如果他明确http的v6无法访问，只能找运营商。
设置测速模式为tcp，也能规避，但这样和设置AAAA返回SOA没有差别，他本质问题可能是V6网络异常。

**Comment by CSSZYF** [comment]
> 

ip6tables -F
ip6tables -X
ip6tables -P INPUT ACCEPT
ip6tables -P OUTPUT ACCEPT
ip6tables -P FORWARD ACCEPT
防火墙设置有上述命令 因为用moonlight的时候发现ipv6被路由器防火墙拦截了 所以关闭掉了路由器的ipv6防火墙

**Comment by PikuZheng** [comment]
> 他的问题是，ipV6的ping是正常的，http无法访问。smartdns检查ipv6是可以通的，所以就会返回ipv6地址。
> 
> 如果他明确http的v6无法访问，只能找运营商。 设置测速模式为tcp，也能规避，但这样和设置AAAA返回SOA没有差别，他本质问题可能是V6网络异常。

不不不，这个原因是移动ipv6路由（bgp）很差，能通但不完全通。我用移动是关掉除主路由外的设备ipv6的

**Comment by CSSZYF** [comment]
> > 他的问题是，ipV6的ping是正常的，http无法访问。smartdns检查ipv6是可以通的，所以就会返回ipv6地址。
> > 如果他明确http的v6无法访问，只能找运营商。 设置测速模式为tcp，也能规避，但这样和设置AAAA返回SOA没有差别，他本质问题可能是V6网络异常。
> 
> 不不不，这个原因是移动ipv6路由（bgp）很差，能通但不完全通。我用移动是关掉除主路由外的设备ipv6的

然而我需要电脑和路由器有ipv6地址 所以没办法关闭电脑上的ipv6

**Comment by CSSZYF** [comment]
> > > 你这可以先排查路由器是否配置了ip6table导致数据被转发。可以路由器上ip6tabale看看。
> > 
> > 
> > 他的问题是想，强制双栈只返回ipv4。但我记得之前讨论过，如果smartdns自身双栈优选失败，就不会返回ipv6？
> 
> 他的问题是，ipV6的ping是正常的，http无法访问。smartdns检查ipv6是可以通的，所以就会返回ipv6地址。
> 
> 如果他明确http的v6无法访问，只能找运营商。 设置测速模式为tcp，也能规避，但这样和设置AAAA返回SOA没有差别，他本质问题可能是V6网络异常。

基本上就处于时通时不通 垃圾移动

**Comment by pymumu** [comment]
路由器上执行这个能通吗？

 wget --inet6-only http://www.qq.com

**Comment by CSSZYF** [comment]
> > > 你这可以先排查路由器是否配置了ip6table导致数据被转发。可以路由器上ip6tabale看看。
> > 
> > 
> > 他的问题是想，强制双栈只返回ipv4。但我记得之前讨论过，如果smartdns自身双栈优选失败，就不会返回ipv6？
> 
> 他的问题是，ipV6的ping是正常的，http无法访问。smartdns检查ipv6是可以通的，所以就会返回ipv6地址。
> 
> 如果他明确http的v6无法访问，只能找运营商。 设置测速模式为tcp，也能规避，但这样和设置AAAA返回SOA没有差别，他本质问题可能是V6网络异常。

speed-check-mode ping,tcp:80
speed-check-mode tcp:443,ping
请问测试这个怎么填 我这样填了之后没啥反应 虽然大部分情况下打不开国内的ipv6网站 但是个别网站还是用的上而且没问题的

**Comment by CSSZYF** [comment]
> 你的网络不要用ping模式看看

不知道是我设置问题还是什么 始终返回的是ipv6和ipv4两个结果 总是优先ipv6 网站依旧打不开

**Comment by jxph1123** [comment]
我的解析也基本是IPV6排第一位，难道IPV6天生比IPV4快。。。
