### ISSUE TITLE
各位大佬，麻烦看看我的配置有没问题，谢谢！

### ISSUE THREAD

**Issue by jxph1123** [pymumu/smartdns#1035]
我想实现的国内国外都用Doh和Dot方式查询，配置如下：
speed-check-mode ping,tcp:80,tcp:443

server-https https://223.5.5.5/dns-query
server-tls 223.5.5.5
server-https https://223.6.6.6/dns-query
server-tls 223.6.6.6
server-https https://dns.alidns.com/dns-query
server-tls dns.alidns.com
server-https https://1.12.12.12/dns-query
server-tls 1.12.12.12
server-https https://120.53.53.53/dns-query
server-tls 120.53.53.53
server-https https://doh.pub/dns-query
server-tls dot.pub
server-https https://doh.360.cn/dns-query
server-tls dot.360.cn

server-https https://1.1.1.1/dns-query -group word -exclude-default-group
server-tls 1.1.1.1 -group word -exclude-default-group
server-https https://1.0.0.1/dns-query -group word -exclude-default-group
server-tls 1.0.0.1 -group word -exclude-default-group
server-https https://cloudflare-dns.com/dns-query -group word -exclude-default-group
server-tls 1dot1dot1dot1.cloudflare-dns.com -group word -exclude-default-group
server-https https://dns.google/dns-query -group word -exclude-default-group
server-tls dns.google -group word -exclude-default-group

就分了个word是国外组，是ssr 5335用的，前面的是默认，各位大佬看看有无问题，我总感觉逻辑有点不对哇，有没有可以优化的地方，谢谢

**Comment by crackerfly** [comment]
1.重复的服务器没有任何意义
2.国外的服务器你确定smartDNS 能访问的到吗？比如 https://dns.google/dns-query ，你用电脑不走代理直接打开试试？
3.关于测速请翻贴，作者有适用场景说明

**Comment by jxph1123** [comment]
> 1.重复的服务器没有任何意义 2.国外的服务器你确定smartDNS 能访问的到吗？比如 https://dns.google/dns-query ，你用电脑不走代理直接打开试试？ 3.关于测速请翻贴，作者有适用场景说明
目前是可以正常上网的。
域名方式的DNS服务器，我的理解是刚开始访问不了的，所以我加了IP方式的DNS，不知道这样可以不。。。

**Comment by jxph1123** [comment]
> 1.重复的服务器没有任何意义 2.国外的服务器你确定smartDNS 能访问的到吗？比如 https://dns.google/dns-query ，你用电脑不走代理直接打开试试？ 3.关于测速请翻贴，作者有适用场景说明


目前这样能正常上网。
域名方式的DNS服务器我的理解是刚开始访问不了的，所以我加了IP方式的DNS服务器，后面是不是能正常访问域名方式的DNS服务器，不太清楚了，所以请教大佬，这个要怎么设置才科学。。

**Comment by PikuZheng** [comment]
word -> world （不影响使用
国内国外上游每组有两三个即可，重复添加没意义。此外223.5.5.5的https据说有问题，建议不要用

**Comment by jxph1123** [comment]
> word -> world （不影响使用 国内国外上游每组有两三个即可，重复添加没意义。此外223.5.5.5的https据说有问题，建议不要用


需不需要这样来操作下  server-https https://8.8.4.4/dnsquery -host-name dns.google
感谢~

**Comment by crackerfly** [comment]
**国内部分**
1.每家(BAT)公司的DNS服务最多只配置2个, 但同一种协议的只配置一个, 按公司分组;
2.整理每家(BAT)公司的业务域名, 做对应分组的分流;
3.阿里的建议只用 UDP, DoH 有问题;
4.腾讯的可以开启 EDNS;
5.避免打架, 默认组里建议只留一家公司的公共DNS+运营商的省级DNS

**国外部分**
1.国外部分可以直连的, 可以分流到“国外DNS”分组做解析;
2.国外部分不能直连的, 本地解析毫无意义, 应放在代理服务器做解析, 因为连接也是通过代理服务器转发的, 这里的工作机制请阅读相关软件所用内核的官方文档;
3.“国外DNS”分组的服务器, 首先要确保你能够不通过代理直接访问, 另外可以开启EDNS
---------

**补充说明**
比如“ https://dns.google/dns-query” 这个 , 它的服务器是8.8.8.8/8.8.4.4没错, 但我这边测试的结果如下:
- UDP、TCP、TLS 确实可以直接访问
- DoH会被运营商阻断无法连接, 即便我指定了 address /dns.google/8.8.8.8
所以你一定要先测试并确认其是否能够直接访问

**另外, 请务必仔细阅读 37.1 的发布说明**

**Comment by crackerfly** [comment]
以上, 如果你还不明白, 建议自己根据smartdns+ssr的工作机制画个数据流程图看一下 就明白了

**Comment by jxph1123** [comment]
> 以上, 如果你还不明白, 建议自己根据smartdns+ssr的工作机制画个数据流程图看一下 就明白了


感谢大佬，其实我要实现的很简单，复杂的也搞不了。
我就只想实现国内阿里、腾讯、360解析，国外谷歌、cloudflare，然后都用DOH和DOT就行了。

**Comment by jxph1123** [comment]
https://github.com/pymumu/smartdns/issues/887#issuecomment-1050826107

根据作者大佬的回复，我又优化了下。我默认值和国外组都留了一个IP形式的DNS，其余都是域名形式dns。我的理解是初次联网的时候，会通过IP形式的DNS解析到其余域名方式的DNS服务器地址，后面的网页解析就可以用域名地址了，不知道这个理解对不对。

#763 默认组：
server-tls 223.6.6.6   
server-https https://dns.alidns.com/dns-query
server-tls dns.alidns.com
server-https https://doh.pub/dns-query
server-tls dot.pub
server-https https://doh.360.cn/dns-query
server-tls dot.360.cn

#国外组：
server-tls 1.0.0.1 -group word -exclude-default-group 
server-https https://cloudflare-dns.com/dns-query -group word -exclude-default-group
server-tls 1dot1dot1dot1.cloudflare-dns.com -group word -exclude-default-group
server-https https://dns.google/dns-query -group word -exclude-default-group
server-tls dns.google -group word -exclude-default-group

**Comment by uid36216** [comment]
> > 以上, 如果你还不明白, 建议自己根据smartdns+ssr的工作机制画个数据流程图看一下 就明白了
> 
> 感谢大佬，其实我要实现的很简单，复杂的也搞不了。 我就只想实现国内阿里、腾讯、360解析，国外谷歌、cloudflare，然后都用DOH和DOT就行了。

这是不可能的，除非你有完整的国内域名列表或国外域名列表。

**Comment by crackerfly** [comment]
> > > 以上, 如果你还不明白, 建议自己根据smartdns+ssr的工作机制画个数据流程图看一下 就明白了
> > 
> > 
> > 感谢大佬，其实我要实现的很简单，复杂的也搞不了。 我就只想实现国内阿里、腾讯、360解析，国外谷歌、cloudflare，然后都用DOH和DOT就行了。
> 
> 这是不可能的，除非你有完整的国内域名列表或国外域名列表。

直接从代理软件的分流规则里复制就可以，至少涵盖了95%的日常使用范围

**Comment by crackerfly** [comment]
> > > 以上, 如果你还不明白, 建议自己根据smartdns+ssr的工作机制画个数据流程图看一下 就明白了
> > 
> > 
> > 感谢大佬，其实我要实现的很简单，复杂的也搞不了。 我就只想实现国内阿里、腾讯、360解析，国外谷歌、cloudflare，然后都用DOH和DOT就行了。
> 
> 这是不可能的，除非你有完整的国内域名列表或国外域名列表。

https://github.com/blackmatrix7/ios_rule_script

**Comment by PikuZheng** [comment]
> https://github.com/blackmatrix7/ios_rule_script

学到了 其实不用全部涵盖 大部分常用的涵盖了就行了 冷门网站用国内国外解析都是一样的

**Comment by felixonmars** [comment]
我自己有一个维护了很多年的国内域名列表，自己的用法是只把表里的用国内 DNS 解析：
https://github.com/felixonmars/dnsmasq-china-list/

（原本是维护给 dnsmasq 用的，可以用 make smartdns 生成 smartdns 版本。

**Comment by jxph1123** [comment]
谢谢各位大佬，我还得学习学习
