### ISSUE TITLE
openwrt官方的luci-app-smartdns是不是可以更新一下了 好久没动过了

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#1037]
RT

**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
这两周会将版本推送到openwrt官方。

**Comment by openips** [comment]
好的 很期待
