### ISSUE TITLE
cache-persist未设置的情况下，产生/tmp/smartdns.cache文件

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1039]
**问题现象**  
cache-persist未设置的情况下，产生/tmp/smartdns.cache文件。

固件型号
Openwrt Koolshare Router V2.37 r17471-8ed31dafdf 内核版本 5.4.108

运营商
山东联通

smartdns来源以及版本
[Release 37.2](https://github.com/pymumu/smartdns/releases/tag/Release37.2)

涉及的配置(注意去除个人相关信息)
server-name smartdns
bind :6053
bind-tcp :6053
dualstack-ip-selection no
cache-size 100000000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 1
log-size 64K
log-num 1
log-level error
force-qtype-SOA  28
bind :7053  -no-speed-check -group foreign -no-dualstack-selection -force-aaaa-soa
bind-tcp :7053  -no-speed-check -group foreign -no-dualstack-selection -force-aaaa-soa
server 10.10.10.100  -group domestic -exclude-default-group
server 119.29.29.29  -group domestic -exclude-default-group
server 119.28.28.28  -group domestic -exclude-default-group
server 10.10.10.100:1056  -group foreign -exclude-default-group
server-tls 8.8.8.8:853  -group foreign -exclude-default-group
server-tls 9.9.9.9:853  -group foreign -exclude-default-group
server-tls 1.1.1.1:853  -group foreign -exclude-default-group
server 10.10.10.200:1056  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

 /etc/smartdns/custom.conf：
#speed-check-mode tcp:443,tcp:80
speed-check-mode none
#cache-persist yes
#cache-file /tmp/smartdns.cache
bind :8055 -group domestic -force-aaaa-soa
bind-tcp :8055 -group domestic -force-aaaa-soa

重现步骤

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
配置文件说明第五行：
<html>
<body>


cache-persist | 是否持久化缓存 | 自动。当 cache-file 所在的位置有超过 128 MB 的可用空间时启用，否则禁用。 
-- | -- | -- 



</body>
</html>

**Comment by yyysuo** [comment]
不好意思，没注意到，抱歉。
