### ISSUE TITLE
升级到21后不断重启

### ISSUE THREAD

**Issue by apnic** [pymumu/smartdns#104]
升级到21后不断重启，一分钟要重启四到五次。
系统是armbian
[2019-03-02 04:54:37,516][ERROR][       smartdns.c:299 ] process exit with signal 7, code = 1, errno = 0, pid = -169204458, self = 20030, pc = 0x1fe38, addr = 0xf5ea2516, build(Mar  2 2019 11:41:39)

**Comment by pymumu** [comment]
发一下配置吧。

**Comment by apnic** [comment]
syslog里面大量这样的记录，已经快2M了
Mar  2 05:07:22 xxxxxxx kernel: [2094700.047758] Unhandled fault: alignment fault (0x92000061) at 0x00000000f5e98523
Mar  2 05:07:25 xxxxxxx systemd[1]: smartdns.service: Service hold-off time over, scheduling restart.
Mar  2 05:07:25 xxxxxxx systemd[1]: Stopped smart dns server.
Mar  2 05:07:25 xxxxxxx systemd[1]: Starting smart dns server...
Mar  2 05:07:25 xxxxxxx systemd[1]: smartdns.service: PID file /var/run/smartdns.pid not readable (yet?) after start: No such file or directory
Mar  2 05:07:25 xxxxxxx systemd[1]: Started smart dns server.
Mar  2 05:07:43 xxxxxxx kernel: [2094720.498110] cp15barrier_handler: 282 callbacks suppressed
Mar  2 05:07:43 xxxxxxx kernel: [2094720.504571] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x1ae9c
Mar  2 05:07:43 xxxxxxx kernel: [2094720.510057] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x1aeb8
Mar  2 05:07:43 xxxxxxx kernel: [2094720.515125] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x226cc
Mar  2 05:07:43 xxxxxxx kernel: [2094720.519933] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x226e8
Mar  2 05:07:43 xxxxxxx kernel: [2094720.524929] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x22714
Mar  2 05:07:43 xxxxxxx kernel: [2094720.530011] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x22734
Mar  2 05:07:43 xxxxxxx kernel: [2094720.534813] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x2274c
Mar  2 05:07:43 xxxxxxx kernel: [2094720.539814] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x22768
Mar  2 05:07:43 xxxxxxx kernel: [2094720.544592] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x227b4
Mar  2 05:07:43 xxxxxxx kernel: [2094720.549594] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x227d0
Mar  2 05:07:56 xxxxxxx kernel: [2094733.810434] cp15barrier_handler: 1320 callbacks suppressed
Mar  2 05:07:56 xxxxxxx kernel: [2094733.816865] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x1ae9c
Mar  2 05:07:56 xxxxxxx kernel: [2094733.823876] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x1aeb8
Mar  2 05:07:56 xxxxxxx kernel: [2094733.830687] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x226cc
Mar  2 05:07:56 xxxxxxx kernel: [2094733.837716] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x226e8
Mar  2 05:07:56 xxxxxxx kernel: [2094733.844428] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x22714
Mar  2 05:07:56 xxxxxxx kernel: [2094733.851419] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x22734
Mar  2 05:07:56 xxxxxxx kernel: [2094733.858143] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x2274c
Mar  2 05:07:56 xxxxxxx kernel: [2094733.865141] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x22768
Mar  2 05:07:56 xxxxxxx kernel: [2094733.871926] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x227b4
Mar  2 05:07:56 xxxxxxx kernel: [2094733.879006] "smartdns" (20602) uses deprecated CP15 Barrier instruction at 0x227d0

**Comment by apnic** [comment]
> 发一下配置吧。

`# dns server name, defaut is host name
# server-name, 
# example:
#   server-name smartdns
#

# Include another configuration options
# conf-file [file]
# conf-file blacklist-ip.conf

conf-file dns.conf
conf-file blacklist-ip.conf
conf-file adblock.conf
conf-file blocklist.conf

# dns server bind ip and port, default dns server port is 53.
# bind [IP]:port, udp server
# bind-tcp [IP]:port, tcp server
# example: 
#   IPV4: :53
#   IPV6  [::]:53
# bind-tcp [::]:53

bind :53
# bind [::]:53

# tcp connection idle timeout
# tcp-idle-time [second]

# dns cache size
# cache-size [number]
#   0: for no cache
cache-size 512

# prefetch domain
# prefetch-domain [yes|no]
# prefetch-domain yes

# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip/subnet]

# List of IPs that will be filtered when nameserver is configured -blacklist-ip parameter
# blacklist-ip [ip/subnet]

# List of IPs that will be ignored
# ignore-ip [ip/subnet]

# force AAAA query return SOA
# force-AAAA-SOA [yes|no]

# Enable IPV4, IPV6 dual stack IP optimization selection strategy
# dualstack-ip-selection-threshold [num] (0~1000)
# dualstack-ip-selection [yes|no]
# dualstack-ip-selection yes

# edns client subnet
# edns-client-subnet-ipv4 [ip/subnet]
# edns-client-subnet-ipv6 [ip/subnet]
# edns-client-subnet-ipv4 192.168.1.1/24

# ttl for all resource record
# rr-ttl: ttl for all record
# rr-ttl-min: minimum ttl for resource record
# rr-ttl-max: maximum ttl for resource record
# example:
# rr-ttl 300
# rr-ttl-min 60
# rr-ttl-max 86400

# set log level
# log-level: [level], level=error, warn, info, debug
# log-file: file path of log file.
# log-size: size of each log file, support k,m,g
# log-num: number of logs
log-level info
log-file /var/log/smartdns.log
log-size 64k
# log-num 2

# dns audit
# audit-enable: enable or disable audit [yes|no]
# audit-size size of each audit file, support k,m,g
# audit-file /var/log/smartdns-audit.log
# audit-size 128k
# audit-num 2

# remote udp dns server list
# server [IP]:[PORT] [-blacklist-ip] [-check-edns]
# default port is 53
#   -blacklist-ip: filter result with blacklist ip
#   -check-edns: result must exist edns RR, or discard result.
# server 8.8.8.8 -blacklist-ip -check-edns

# remote tcp dns server list
# server-tcp [IP]:[PORT] [-blacklist-ip]
# default port is 53
# server-tcp 8.8.8.8

# remote tls dns server list
# server-tls [IP]:[PORT] [-blacklist-ip] [-check-edns]
# default port is 853
# server-tls 8.8.8.8
# server-tls 1.0.0.1

# specific address to domain
# address /domain/[ip|-|-4|-6|#|#4|#6]
# address /www.example.com/1.2.3.4, return ip 1.2.3.4 to client
# address /www.example.com/-, ignore address, query from upstream, suffix 4, for ipv4, 6 for ipv6, none for all
# address /www.example.com/#, return SOA to client, suffix 4, for ipv4, 6 for ipv6, none for all

# specific ipset to domain
# ipset /domain/[ipset|-]
# ipset /www.example.com/block, set ipset with ipset name of block 
# ipset /www.example.com/-, ignore this domain`

**Comment by apnic** [comment]
排版怎么会这样呢？重发一次
# dns server name, defaut is host name
# server-name, 
# example:
#   server-name smartdns
#

# Include another configuration options
# conf-file [file]
# conf-file blacklist-ip.conf

conf-file dns.conf
conf-file blacklist-ip.conf
conf-file adblock.conf
conf-file blocklist.conf

# dns server bind ip and port, default dns server port is 53.
# bind [IP]:port, udp server
# bind-tcp [IP]:port, tcp server
# example: 
#   IPV4: :53
#   IPV6  [::]:53
# bind-tcp [::]:53

bind :53
# bind [::]:53

# tcp connection idle timeout
# tcp-idle-time [second]

# dns cache size
# cache-size [number]
#   0: for no cache
cache-size 5120

# prefetch domain
# prefetch-domain [yes|no]
# prefetch-domain yes

# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip/subnet]

# List of IPs that will be filtered when nameserver is configured -blacklist-ip parameter
# blacklist-ip [ip/subnet]

# List of IPs that will be ignored
# ignore-ip [ip/subnet]

# force AAAA query return SOA
# force-AAAA-SOA [yes|no]

# Enable IPV4, IPV6 dual stack IP optimization selection strategy
# dualstack-ip-selection-threshold [num] (0~1000)
# dualstack-ip-selection [yes|no]
# dualstack-ip-selection yes

# edns client subnet
# edns-client-subnet-ipv4 [ip/subnet]
# edns-client-subnet-ipv6 [ip/subnet]
# edns-client-subnet-ipv4 192.168.1.1/24

# ttl for all resource record
# rr-ttl: ttl for all record
# rr-ttl-min: minimum ttl for resource record
# rr-ttl-max: maximum ttl for resource record
# example:
# rr-ttl 300
# rr-ttl-min 60
# rr-ttl-max 86400

# set log level
# log-level: [level], level=error, warn, info, debug
# log-file: file path of log file.
# log-size: size of each log file, support k,m,g
# log-num: number of logs
log-level info
log-file /var/log/smartdns.log
log-size 64k
# log-num 2

# dns audit
# audit-enable: enable or disable audit [yes|no]
# audit-size size of each audit file, support k,m,g
# audit-file /var/log/smartdns-audit.log
# audit-size 128k
# audit-num 2

# remote udp dns server list
# server [IP]:[PORT] [-blacklist-ip] [-check-edns]
# default port is 53
#   -blacklist-ip: filter result with blacklist ip
#   -check-edns: result must exist edns RR, or discard result.
# server 8.8.8.8 -blacklist-ip -check-edns

# remote tcp dns server list
# server-tcp [IP]:[PORT] [-blacklist-ip]
# default port is 53
# server-tcp 8.8.8.8

# remote tls dns server list
# server-tls [IP]:[PORT] [-blacklist-ip] [-check-edns]
# default port is 853
# server-tls 8.8.8.8
# server-tls 1.0.0.1

# specific address to domain
# address /domain/[ip|-|-4|-6|#|#4|#6]
# address /www.example.com/1.2.3.4, return ip 1.2.3.4 to client
# address /www.example.com/-, ignore address, query from upstream, suffix 4, for ipv4, 6 for ipv6, none for all
# address /www.example.com/#, return SOA to client, suffix 4, for ipv4, 6 for ipv6, none for all

# specific ipset to domain
# ipset /domain/[ipset|-]
# ipset /www.example.com/block, set ipset with ipset name of block 
# ipset /www.example.com/-, ignore this domain

**Comment by pymumu** [comment]
贴文件

**Comment by pymumu** [comment]
看了下错误码，和指令相关，你的硬件不支持某些指令

**Comment by apnic** [comment]
> 贴文件
> 你的硬件是什么？用的哪个安装文件。

cpu是rk3328，系统是debian9
cat /proc/cpuinfo
processor       : 0
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv8 Processor rev 4 (v8l)
BogoMIPS        : 48.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

uname -a
Linux xxxxx 4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 #1 SMP Mon Oct 22 20:59:41 UTC 2018 aarch64 GNU/Linux

**Comment by Auska** [comment]
arm64 我的板子跑也是一样一会重启

**Comment by pymumu** [comment]
@Auska 发一下错误日志

**Comment by pymumu** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/2922076/smartdns.zip)

编译了不同时间的版本，有空帮忙验证一个，反馈一下哪个版本有问题，哪个没有

**Comment by apnic** [comment]
> @apnic @Auska
> [smartdns.zip](https://github.com/pymumu/smartdns/files/2922076/smartdns.zip)
> 
> 编译了不同时间的版本，有空帮忙验证一个，反馈一下哪个版本有问题，哪个没有

smartdns-2-21,smartdns-2-22-0频繁重启
smartdns-2-22-23，smartdns-2-24两三分钟重启一次

**Comment by pymumu** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/2922199/smartdns.zip)
这个测试一下

**Comment by apnic** [comment]
> [smartdns.zip](https://github.com/pymumu/smartdns/files/2922199/smartdns.zip)
> 这个测试一下

大约两分钟后开始频繁重启。

**Comment by pymumu** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/2922241/smartdns.zip)

这个呢。

**Comment by Auska** [comment]
测试结果相似 在R19版本发现是安装armhf运行就会出现大量错误日志 后选择放弃使用 安装到行x86上作为AdGuardHome的上游dns

**Comment by kang-mk** [comment]
21 LEDE软路由  稳的一比

**Comment by pymumu** [comment]
@Auska @apnic 
[smartdns.1.2019.03.03-0328.arm64.deb.zip](https://github.com/pymumu/smartdns/files/2922723/smartdns.1.2019.03.03-0328.arm64.deb.zip)

编译了一个arm64的版本，你们验证下看看吧。
arm64跑，armhf的场景，指令集不兼容的。

**Comment by apnic** [comment]
> @Auska @apnic
> [smartdns.1.2019.03.03-0328.arm64.deb.zip](https://github.com/pymumu/smartdns/files/2922723/smartdns.1.2019.03.03-0328.arm64.deb.zip)
> 
> 编译了一个arm64的版本，你们验证下看看吧。
> arm64跑，armhf的场景，指令集不兼容的。

无法启动，但系统是存在这个库文件的
find / -name libssl.so.1.1 
find: '/proc/1617/task/1617/net': Invalid argument
find: '/proc/1617/net': Invalid argument
/usr/lib/arm-linux-gnueabihf/libssl.so.1.1

Mar 03 19:44:07 xxxxxxx systemd[1]: smartdns.service: Unit entered failed state.
Mar 03 19:44:07 xxxxxxx systemd[1]: smartdns.service: Failed with result 'exit-code'.
Mar 03 19:44:09 xxxxxxx systemd[1]: smartdns.service: Service hold-off time over, scheduling restart.
Mar 03 19:44:09 xxxxxxx systemd[1]: Stopped smart dns server.
-- Subject: Unit smartdns.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit smartdns.service has finished shutting down.
Mar 03 19:44:09 xxxxxxx systemd[1]: Starting smart dns server...
-- Subject: Unit smartdns.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit smartdns.service has begun starting up.
Mar 03 19:44:09 xxxxxxx smartdns[790]: /usr/sbin/smartdns: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Mar 03 19:44:09 xxxxxxx systemd[1]: smartdns.service: Control process exited, code=exited status=127
Mar 03 19:44:09 xxxxxxx systemd[1]: Failed to start smart dns server.
-- Subject: Unit smartdns.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit smartdns.service has failed.
-- 
-- The result is failed.
Mar 03 19:44:09 xxxxxxx systemd[1]: smartdns.service: Unit entered failed state.
Mar 03 19:44:09 xxxxxxx systemd[1]: smartdns.service: Failed with result 'exit-code'.

**Comment by Auska** [comment]
arm64编译版本 正常
系统 armbian 
Linux orangepioneplus 4.20.12-sunxi64 #5.76.190228 SMP Thu Feb 28 21:44:01 CET 2019 aarch64 GNU/Linux

**Comment by pymumu** [comment]
@apnic 不是32位 linux？你用的什么系统？没支持的系统会有未知问题的

**Comment by apnic** [comment]
> @apnic 不是32位 linux？你用的什么系统？没支持的系统会有未知问题的

是32位的啊
getconf LONG_BIT
32

uname -a
Linux xxxxx 4.4.154-1124-rockchip-ayufan-ged3ce4d15ec1 #1 SMP Mon Oct 22 20:59:41 UTC 2018 aarch64 GNU/Linux

**Comment by pymumu** [comment]
你cpu是64位的，跑32位os，无法知道用什么编译器

**Comment by asnon** [comment]
> 21 LEDE软路由 稳的一比

兄弟是lede哪个版本的固件，我2.27用这个版本，只要v2重启或者切换线路。。然后smart dns就挂了。。要关闭打开一下才行。。

**Comment by kang-mk** [comment]
> > 21 LEDE软路由 稳的一比
> 
> 兄弟是lede哪个版本的固件，我2.27用这个版本，只要v2重启或者切换线路。。然后smart dns就挂了。。要关闭打开一下才行。。

SmartDNS和V2只能二选一，原因懒得解释了，我现在切换到SS去了，暂时不用V2了，如果想要V2配合SmartDNS的话，那就要用V2自带的SmartDNS，然后下载OPENWRTX64版本的IPK，解压出来，把二进制文件直接和V2自带的替换，这样也等于直接更新到2.1版本了，只是没有WEB界面了用起来是一样，选择哪种方案，就自我权衡吧

**Comment by asnon** [comment]
> > > 21 LEDE软路由 稳的一比
> > 
> > 
> > 兄弟是lede哪个版本的固件，我2.27用这个版本，只要v2重启或者切换线路。。然后smart dns就挂了。。要关闭打开一下才行。。
> 
> SmartDNS和V2只能二选一，原因懒得解释了，我现在切换到SS去了，暂时不用V2了，如果想要V2配合SmartDNS的话，那就要用V2自带的SmartDNS，然后下载OPENWRTX64版本的IPK，解压出来，把二进制文件直接和V2自带的替换，这样也等于直接更新到2.1版本了，只是没有WEB界面了用起来是一样，选择哪种方案，就自我权衡吧

好吧。。果然还是v2的问题。。我看看下，谢谢。
