### ISSUE TITLE
Lean LEDE luci-compat 的问题

### ISSUE THREAD

**Issue by WCJ23333** [pymumu/smartdns#1040]
**问题现象**  
luci-compat 的问题
1. 在luci界面里找不到dnsmasq-lease-file, force-aaaa-soa, force-https-soa的选项
2. 在luci第二DNS中勾选Force AAAA SOA会导致主DNS解析时Force AAAA SOA，取消勾选后主DNS和第二DNS都会解析AAAA记录

**运行环境**
lean master OpenWrt源码  `3302e26e94d8afd640f37eede9dc458add36ea49`

**smartdns来源以及版本**
Release 37.2源码编译、安装Release 37.2 ipk文件、最新master源码 `64e5b326cc53df1fec680cfa28ceec5d8a36fcbc`编译
都会出现此问题

**Comment by jxph1123** [comment]
作者好像没有改这个版本的

**Comment by pymumu** [comment]
lua的compat版本，openwrt已经不支持了，后面都是javascript版本的。
我这边也没有环境验证，后续compat版本会下线。应该尽快切换到javascript版本。

**Comment by pymumu** [comment]
openwrt官方的还没推送。

**Comment by jxph1123** [comment]
> lua的compat版本，openwrt已经不支持了，后面都是javascript版本的。 我这边也没有环境验证，后续compat版本会下线。应该尽快切换到javascript版本。


建议大佬还是保留lua版本的，lean，天灵等都还在更新lua版本，用户挺多的

**Comment by PikuZheng** [comment]
可能主要问题还是多个lede安装js版本后不出菜单

**Comment by jxph1123** [comment]
还是lua版的稳定，速度也快，也能支持新的openwrt版本吧

**Comment by LsnmxNB** [comment]
> 

这个应该再次喷lean大屌懒成这尿性，几年前说很多人让更新op的ui结构了，结果他还喷上游op的新ui是垃圾

**Comment by PikuZheng** [comment]
你们说的是coolsnowwolf还是lienol

**Comment by pymumu** [comment]
lua界面已经更新。后面界面可能不再更新。

**Comment by jxph1123** [comment]
> @jxph1123
> 
> 这个应该再次喷lean大屌懒成这尿性，几年前说很多人让更新op的ui结构了，结果他还喷上游op的新ui是垃圾

lua确实响应快点。估计后面还是得跟着官方走。。。先凑合用吧。。

**Comment by PikuZheng** [comment]
查了一下 lean的lede压根不支持javascript的luci2

**Comment by pymumu** [comment]
lua版本的界面，其需要路由设备生成网页后发送给前端。
js版本的界面，不需要路由生成页面，页面完全由浏览器生成，对硬路由和低端路由更加友好。
从性能上来说，js版本其实更加友好。但当前js还需要开发磨合。

openwrt社区，当前对于新增的UI界面，强制要求使用js版本，lua版本慢慢就会取消。
