### ISSUE TITLE
关于luci不显示及127.0.0.1:6053

### ISSUE THREAD

**Issue by mrwheat01** [pymumu/smartdns#1044]
**在openwrt上使用smartdns也好久了，一直感觉自己是正常使用，但这两个问题始终困扰着我。请求解答一下疑惑。**

**问题现象**  
1、卸载旧版本30并安装新版本37.2后，在软件中找不到smartdns，但是在软件包中可以看到luci和软件都已经安装，试过luci-all和luci-compat都不行。
2、路由器运行nslookup www.taobao.com 127.0.0.1:6053，提示nslookup: couldn't get address for '127.0.0.1:6053': not found

**运行环境**
1. 固件型号  
openwrt，esir编译版summer[2022]-x86-64高大全，做旁路由使用。

2. 运营商  

中国电信
3. smartdns来源以及版本

旧版本30，固件自带的，安装新版本37.2。

4. 涉及的配置(注意去除个人相关信息)

系统dns保持53没改，防火墙里注释掉了两行#iptables -t nat……--to-ports 53；smartdns里设置为作为dnsmasa的上游服务器，第二dns端口为7913，并在passwall里做了相关设置。adguardhome定义端口为54，上游dns指定为127.0.0.1，并设置里重定向53端口到AdGuardHome。

基本按照https://github.com/luckyyyyy/blog/issues/57#issue-1198960406进行设置的。
**重现步骤**
1. 上游DNS配置。  

本地运营商dns、阿里、腾讯，外地的google的dns。

![1](https://user-images.githubusercontent.com/106718443/187618587-babbccb0-448a-4c1f-8f03-2f4562c3d066.png)
![2](https://user-images.githubusercontent.com/106718443/187618625-91131af0-5523-4a1e-81ac-80e8cb2aa71b.png)
![3](https://user-images.githubusercontent.com/106718443/187618632-6d1c5d06-16fa-4dc0-8481-9ab7728d5533.png)
![4](https://user-images.githubusercontent.com/106718443/187618634-47f90591-0c76-4baf-b614-5142ad301bf3.png)
![5](https://user-images.githubusercontent.com/106718443/187618638-e4910240-4e11-4053-acdb-47c8098dcb10.png)
![6](https://user-images.githubusercontent.com/106718443/187618642-9af3e401-f488-42bb-9574-c9b1019c588f.png)
![7](https://user-images.githubusercontent.com/106718443/187618646-6104f3be-1234-4032-9aa5-ad81b2442ee0.png)
![8](https://user-images.githubusercontent.com/106718443/187618651-d87b2770-01c1-4c33-920c-d916a551b28f.png)
![9](https://user-images.githubusercontent.com/106718443/187618657-1f49016a-f75b-463b-9698-e7e121c6b8cd.png)
![10](https://user-images.githubusercontent.com/106718443/187618660-2da71070-fd3d-4e2f-bca8-d6ff9af52ef2.png)
![11](https://user-images.githubusercontent.com/106718443/187630292-fdabe7d7-c2bf-4c3c-842c-ff04787dc0b6.png)

**Comment by PikuZheng** [comment]
1. 已知coolsnowwolf及其衍生的lede系列编译不支持javascript版的luci（luci2），且**必须在确保没有 luci-app......ipk 的情况下新装 luci-app.....-compat-all.ipk 才可以**。参考 #992 #1011
2. nslookup 不支持指定服务器端口号，请使用dig或kdig
3. 配置逻辑问题，先是重定向53到54，此时dnsmasq的53不会生效，dnsmasq也不可能收到查询转发到6053。那么54的上游怎么配置的？passwall会不会劫持53端口的查询？究竟哪个应用会把查询转发给smartdns？

**Comment by mrwheat01** [comment]
> *luci的问题我再多试试。有结果了报回来。我试过你编译的版本，也是不显示。

> * nslookup 不支持指定服务器端口号，请使用dig或kdig

这个是我在这里看到的，但我一直不显示结果。用了好久，就很好奇是为什么。
https://github.com/xiaoqingfengATGH/HomeLede/wiki/无法上网排查宝典

> * 配置逻辑问题，先是重定向53到54，此时dnsmasq的53不会生效，dnsmasq也不可能收到查询转发到6053。那么54的上游怎么配置的？passwall会不会劫持53端口的查询？究竟哪个应用会把查询转发给smartdns？

这里漏了一句，adguardhome中设置为上游dns服务器为127.0.0.1。我再捋一捋，小白有点弄不清。

非常感谢您能给我的答复，也感谢您持续更新编译smartdns。

太难了，我只想在旁路由上好好的使用smartdns+passwall+Adg！

**Comment by PikuZheng** [comment]
> adguardhome中设置为上游dns服务器为127.0.0.1

哪个端口呢？如果也是53，会导致死循环，任何dns都不起作用

**Comment by 4thanks** [comment]
> 1. 已知coolsnowwolf及其衍生的lede系列编译不支持javascript版的luci（luci2），且**必须在确保没有 luci-app......ipk 的情况下新装 luci-app.....-compat-all.ipk 才可以**。参考 [esir、sirpdboy编译的openwrt卸载预装的smartdns手动安装37 RC2版本报错无法启动 #992](https://github.com/pymumu/smartdns/issues/992) [ F大的75+O，手动删除SMARTDNS36，安装37包和LUCI文件，OP服务无显示。 #1011](https://github.com/pymumu/smartdns/issues/1011)
> 
> 2. nslookup 不支持指定服务器端口号，请使用dig或kdig
> 
> 3. 配置逻辑问题，先是重定向53到54，此时dnsmasq的53不会生效，dnsmasq也不可能收到查询转发到6053。那么54的上游怎么配置的？passwall会不会劫持53端口的查询？究竟哪个应用会把查询转发给smartdns？

我也有这个问题，[immortalwrt-18.06-k5.4](https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06-k5.4)固件的主题皮肤也和默认编译luci不太兼容，安装无法显示。不过一般用之前编译的固件带的luci也能凑合用，就没特别在意。
大佬可以试试在 [#1021](https://github.com/pymumu/smartdns/issues/1021)基础上，也编译一遍luci版。

**Comment by crackerfly** [comment]
> > *luci的问题我再多试试。有结果了报回来。我试过你编译的版本，也是不显示。
> 
> > * nslookup 不支持指定服务器端口号，请使用dig或kdig
> 
> 这个是我在这里看到的，但我一直不显示结果。用了好久，就很好奇是为什么。 [https://github.com/xiaoqingfengATGH/HomeLede/wiki/无法上网排查宝典](https://github.com/xiaoqingfengATGH/HomeLede/wiki/%E6%97%A0%E6%B3%95%E4%B8%8A%E7%BD%91%E6%8E%92%E6%9F%A5%E5%AE%9D%E5%85%B8)
> 
> > * 配置逻辑问题，先是重定向53到54，此时dnsmasq的53不会生效，dnsmasq也不可能收到查询转发到6053。那么54的上游怎么配置的？passwall会不会劫持53端口的查询？究竟哪个应用会把查询转发给smartdns？
> 
> 这里漏了一句，adguardhome中设置为上游dns服务器为127.0.0.1。我再捋一捋，小白有点弄不清。
> 
> 非常感谢您能给我的答复，也感谢您持续更新编译smartdns。
> 
> 太难了，我只想在旁路由上好好的使用smartdns+passwall+Adg！

你这个链接里人家端口号前面是# 你用的是:

**Comment by 4thanks** [comment]
> 你这个链接里人家端口号前面是# 你用的是:

他是好几个问题在一起，我主要针对luci的兼容性

**Comment by pymumu** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/9462279/smartdns.zip)
可以验证下看看

如果安装compat包，要手工安装依赖
```
opkg install uci-compat 
```

还有，可以执行如下操作看看
```shell
/etc/init.d/uhttpd stop
rm -rf /tmp/luci-*
/etc/init.d/uhttpd start
```

**Comment by PikuZheng** [comment]
> [smartdns.zip](https://github.com/pymumu/smartdns/files/9462279/smartdns.zip) 可以验证下看看
> 
> 如果安装compat包，要手工安装依赖
> 
> ```
> opkg install uci-compat 
> ```
> 
> 还有，可以执行如下操作看看
> 
> ```shell
> /etc/init.d/uhttpd stop
> rm -rf /tmp/luci-*
> /etc/init.d/uhttpd start
> ```
> 
> 还有清空浏览器缓存，或者用隐私模式访问。

opkg install luci-compat
rm /tmp/luci-indexcache

再次说一下coolsnowwolf及其衍生的lede不支持luci2，安装js版luci在菜单中不显示，强制打开页面提示
```
No page is registered at '/admin/services/smartdns'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.
```

**Comment by mrwheat01** [comment]
来反馈一下，经测试，已成功安装smartdns37.2，luci正常显示。固件为esir的openwrt夏季高大全版。
非常感谢。
