### ISSUE TITLE
最新版本添加了去除dns_redirect，但停止smartdns不能恢复dns_redirect设置，导致不使用smartdns时网络不正常！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1048]
希望同步添加恢复dns_redirect功能。。。
![image](https://user-images.githubusercontent.com/45259624/187927897-837a329f-00f3-4cf9-8912-9fcde86f89b1.png)

**Comment by jxph1123** [comment]
不勾选这个也能上网吧，我试过

**Comment by zxlhhyccc** [comment]
> 不勾选这个也能上网吧，我试过

不能。。。我自己加上去了，停用后自动恢复dns_redirect。。。

**Comment by PikuZheng** [comment]
刚发现不止这个问题啊，如果smartdns的端口配置为53，那么开启smartdns后会设置dnsmasq端口为0，但停止smartdns后会清空dnsmasq的端口设置，造成其他应用与dnsmasq的端口冲突。

您那个pull也一样，本质上并没有恢复dnsmasq的配置，只是在smartdns停止时将dnsmasq配置为另一个值

**Comment by 58285474** [comment]
>  不勾选这个也能上网吧，我试过

可以上网，但是不会过滤了
