### ISSUE TITLE
希望可以有docker版本

### ISSUE THREAD

**Issue by ghostry** [pymumu/smartdns#105]
**需求应用场景**
使用docker可以快速安装,在各种linux,mac,Windows平台上面.

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by ghostry** [comment]
https://cloud.docker.com/repository/docker/ghostry/smartdns
我做了一个。不过用Ubuntu做底包感觉太大了，最好能用alpine。
我尝试用alpine没有成功。

**Comment by pymumu** [comment]
看了不错，支持。
