### ISSUE TITLE
大佬，请问要怎样才能把smartdns的最新源码编译进openwrt？

### ISSUE THREAD

**Issue by zmjjack** [pymumu/smartdns#1055]
**问题现象**  
目前我是用Lienol源码22.03版，git了最新的smartdns源码，编译出来却是老版本的smartdns和老的luci。请大佬帮忙解决！

**运行环境**

主机名 | OpenWrt
型号 | FriendlyElec NanoPi R4S
CPU信息 | ARMv8 Processor x 6 (600MHz 1008MHz, 46.9°C)
目标平台 | rockchip/armv8
固件版本 | OpenWrt 22.03-SNAPSHOT / LuCI 22.03 git-0d5ea54
内核版本 | 5.10.136

smartdns源码：https://github.com/pymumu/smartdns.git

**Comment by PikuZheng** [comment]
这个问题有点复杂，大体有以下几步：
1. 按正常编译流程直到执行完 `./scripts/feeds update -a`
2. 删除原有的 package/smartdns 文件夹中所有的内容
3. 将pymumu的smartdns的package/openwrt文件夹中所有内容复制到package/smartdns
4. 将pymumu的smartdns的src文件夹中所有内容复制到 package/smartdns/src
5. 执行`./scripts/feeds install -a -f`
6. 执行`make menuconfig`，选中必要的组件

**Comment by jxph1123** [comment]
> **问题现象** 目前我是用Lienol源码22.03版，git了最新的smartdns源码，编译出来却是老版本的smartdns和老的luci。请大佬帮忙解决！
> 
> **运行环境**
> 
> 主机名 | OpenWrt 型号 | FriendlyElec NanoPi R4S CPU信息 | ARMv8 Processor x 6 (600MHz 1008MHz, 46.9°C) 目标平台 | rockchip/armv8 固件版本 | OpenWrt 22.03-SNAPSHOT / LuCI 22.03 git-0d5ea54 内核版本 | 5.10.136
> 
> smartdns源码：https://github.com/pymumu/smartdns.git


luci直接把源码下载下去，手动替换原来的就行，意思原有LUCI里面啥内容，就用新的手动替换。。你是lua版和JS版，区分下就行

**Comment by zmjjack** [comment]
> 这个问题有点复杂，大体有以下几步：
> 
> 1. 按正常编译流程直到执行完 `./scripts/feeds update -a`
> 2. 删除原有的 package/smartdns 文件夹中所有的内容
> 3. 将pymumu的smartdns的package/openwrt文件夹中所有内容复制到package/smartdns
> 4. 将pymumu的smartdns的src文件夹中所有内容复制到 package/smartdns/src
> 5. 执行`./scripts/feeds install -a -f`
> 6. 执行`make menuconfig`，选中必要的组件

谢谢，我试试

**Comment by PikuZheng** [comment]
哦是要替换luci啊。。。luci有亿点点复杂，我得先试试

**Comment by zmjjack** [comment]
> 
如果有单独的luci-app-smartdns源码就比较方便了吧

**Comment by zmjjack** [comment]
> luci直接把源

最新的luci源码去哪里下载啊？

**Comment by zmjjack** [comment]
搞了一个上午，还是不能把最新的smartdns源码编译进openwrt中

**Comment by PikuZheng** [comment]
Lienol 的上午跑了一下好像不行，我下午再试试

**Comment by PikuZheng** [comment]
luci不能直接替换编译的，缺定义文件

**Comment by PikuZheng** [comment]
顺便问下你为啥不用编译好的ipk而一定要集成到固件里

**Comment by zmjjack** [comment]
> 顺便问下你为啥不用编译好的ipk而一定要集成到固件里
如果集成到固件里的，就可以时刻保持smartdns是最新版。如果不集成，每次编译好固件后，还要把原来老版的smartdns删除，然后再装编译好的ipk，有点麻烦。

**Comment by pymumu** [comment]
feed update之后。
修改如下文件：

1. smartdns主程序：

smartdns的makefile中修改如下项目：feeds/packages/net/smartdns/Makefile
```makefile
PKG_SOURCE_VERSION:=8532205844fbb9034a4473a02cfcda6584a203af
```

2. luci界面：
https://github.com/pymumu/luci-app-smartdns
更新了这个库，参照ReadMe操作。

**Comment by zmjjack** [comment]
> 

谢谢，晚上试搞下。

**Comment by jxph1123** [comment]
> feed update之后。 修改如下文件：
> 
> 1. smartdns主程序：
> 
> smartdns的makefile中修改如下项目：feeds/packages/net/smartdns/Makefile
> 
> ```makefile
> PKG_SOURCE_VERSION:=8532205844fbb9034a4473a02cfcda6584a203af
> ```
> 
> 2. luci界面：
>    https://github.com/pymumu/luci-app-smartdns
>    更新了这个库，参照ReadMe操作。

顶，感谢大佬，不用自己再搞一次了。

**Comment by zmjjack** [comment]
> > feed update之后。 修改如下文件：
> > 
> > 1. smartdns主程序：
> > 
> > smartdns的makefile中修改如下项目：feeds/packages/net/smartdns/Makefile
> > ```makefile
> > PKG_SOURCE_VERSION:=8532205844fbb9034a4473a02cfcda6584a203af
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. luci界面：
> >    https://github.com/pymumu/luci-app-smartdns
> >    更新了这个库，参照ReadMe操作。
> 
> 顶，感谢大佬，不用自己再搞一次了。

感谢感谢🙏
