### ISSUE TITLE
分享下openwrt下最新smart自己编译的源码

### ISSUE THREAD

**Issue by jxph1123** [pymumu/smartdns#1056]
直接加到你自己编译的目录里面。选择编译就行。
压缩包里面是LUA版本的luci，JS的类似，我没有弄。里面默认了我自己的配置，自行修改就是。
[smartdns.zip](https://github.com/pymumu/smartdns/files/9484215/smartdns.zip)

**Comment by zmjjack** [comment]
ok

**Comment by jxph1123** [comment]
大佬更新了最新的单独Luci，可以自己拉取编译了

**Comment by zmjjack** [comment]
兄弟，能不能分享个最新版的smartdns ipk给我，就是9月3日那个版本的。

**Comment by PikuZheng** [comment]
> 兄弟，能不能分享个最新版的smartdns ipk给我，就是9月3日那个版本的。

9月3日和9月1日的是一致的

**Comment by zmjjack** [comment]
> > 兄弟，能不能分享个最新版的smartdns ipk给我，就是9月3日那个版本的。
> 
> 9月3日和9月1日的是一致的 你要什么架构的版本

我用的是r4s，37.2.9好像没有r4s用的构架？

**Comment by zmjjack** [comment]
> > 兄弟，能不能分享个最新版的smartdns ipk给我，就是9月3日那个版本的。
> 
> 9月3日和9月1日的是一致的 你要什么架构的版本
r4s用的这种aarch64-openwrt

**Comment by PikuZheng** [comment]
> 我用的是r4s，37.2.9好像没有r4s用的构架？

37.2.8和37.2.9是一致的，1.2022.v37.2.8-openwrt有这个编译

**Comment by zmjjack** [comment]
> > 我用的是r4s，37.2.9好像没有r4s用的构架？
> 
> 37.2.8和37.2.9是一致的，1.2022.v37.2.8-openwrt有这个编译

好的，谢谢

**Comment by zmjjack** [comment]
@PikuZheng 
<img width="903" alt="截屏2022-09-07 21 00 19" src="https://user-images.githubusercontent.com/112772719/188884853-ef330123-2d5b-41fc-a778-45140a56d108.png">
<img width="915" alt="截屏2022-09-07 20 58 26" src="https://user-images.githubusercontent.com/112772719/188884889-426817d3-210b-41e6-bf1b-c3a4f7e5f58b.png">
红框里面的两个有什么不一样吗？大小相差好多。

**Comment by PikuZheng** [comment]
-openwrt 是动态链接编译的，需要系统自带c lib openssl等。文件较大的是静态链接编译

**Comment by zmjjack** [comment]
@PikuZheng 在r4s上安装 smartdns.1.2022.v37.2.10.aarch64-openwrt-all.ipk时，提示未能识别的安装包，安装不了。
<img width="903" alt="截屏2022-09-08 17 52 00" src="https://user-images.githubusercontent.com/112772719/189094066-7bf3ac12-4c93-47bc-92c3-b71c576baa4d.png">

**Comment by zmjjack** [comment]
固件版本是：
OpenWrt 22.03-SNAPSHOT / LuCI 22.03 git-0d5ea54


<br class="Apple-interchange-newline">

**Comment by PikuZheng** [comment]
> @PikuZheng 在r4s上安装 smartdns.1.2022.v37.2.10.aarch64-openwrt-all.ipk时，提示未能识别的安装包，安装不了。

架构错误，不应使用aarch64的包

**Comment by PikuZheng** [comment]
> 那我要用哪个安装包？

不知道，我只有x86_64和tilex

**Comment by zmjjack** [comment]
> #1055 是这个吗？目标平台 | rockchip/armv8 系统是32位的还是64位的？

是，64位的

**Comment by PikuZheng** [comment]
![image](https://user-images.githubusercontent.com/12579522/189106234-a30fff4e-0534-4154-b2ec-0f95bddd2286.png)
aarch64有三个，我也不知道应该是哪个 :smiling_face_with_tear:

**Comment by PikuZheng** [comment]
还有一种可能是系统配置错误，不接受任何架构的包

**Comment by zmjjack** [comment]
> ![image](https://user-images.githubusercontent.com/12579522/189106234-a30fff4e-0534-4154-b2ec-0f95bddd2286.png)
> aarch64有三个，我也不知道应该是哪个 🥲

好吧，我试下。

**Comment by PikuZheng** [comment]
#1011  进命令行执行 opkg print-architecture 看返回什么

**Comment by zmjjack** [comment]
> opkg print-architecture
返回的是这个：
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch aarch64_generic 10

**Comment by zmjjack** [comment]
> > 但是安装aarch64_generic构架的话，不会自动设置dnsmasq。
> 
> 为啥不会，都是同一个源码出来的
> 
> > 我现在用的是这个smartdns.1.2022.08.31-2206.aarch64-openwrt-all.ipk。
> 
> 这个是打包固件时集成的吗？把它卸载后能重新安装同一个版本吗？

不是固件集成，是另外安装的。删除后也可以重装

**Comment by PikuZheng** [comment]
搜不到这个包，能不能用7z之类的打开看一下里面 smartdns.1.2022.08.31-2206.aarch64-openwrt-all\.\control.tar.gz\control.tar\.\control 文件内的 Architecture 是什么

**Comment by zmjjack** [comment]
> 搜不到这个包，能不能用7z之类的打开看一下里面 smartdns.1.2022.08.31-2206.aarch64-openwrt-all.\control.tar.gz\control.tar.\control 文件内的 Architecture 是什么

这个文件应该是作者编译的，传你看看。[smartdns.zip](https://github.com/pymumu/smartdns/files/9527447/smartdns.zip)

**Comment by PikuZheng** [comment]
使用OSX编译的

Package: smartdns
Architecture: all

这个包自身没有指定架构，所以可以安装。。

**Comment by zmjjack** [comment]
> 使用OSX编译的
> 
> Package: smartdns Architecture: all
> 
> 这个包自身没有指定架构，所以可以安装。。

你能不能帮忙搞个不指定构架的包给我体验一下最新版

**Comment by PikuZheng** [comment]
最新版请使用 smartdns_1.2022.v37.2.10-1_aarch64_generic.ipk
这边是自动编译的，一般是更新后4小时内发布

**Comment by zmjjack** [comment]
> 最新版请使用 smartdns_1.2022.v37.2.10-1_aarch64_generic.ipk 这边是自动编译的，一般是更新后4小时内发布

smartdns_1.2022.v37.2.10-1_aarch64_generic.ipk这个装上后，设置53端口会和dnsmasq冲突，smartdns自动关闭。也就是说不会自动设置dnsmasq

**Comment by PikuZheng** [comment]
> smartdns_1.2022.v37.2.10-1_aarch64_generic.ipk这个装上后，设置53端口会和dnsmasq冲突，smartdns自动关闭。也就是说不会自动设置dnsmasq

@pymumu 证实在lede上，将smartdns和dnsmasq端口都配置为53时不会自动修改dnsmasq设置。可能的原因有：
1. 系统安装的包是dnsmasq，不是dnsmasq-full
2. dhcp.@dnsmasq[0].server 不存在
3. dnsmasq的端口号配置在 dhcp.@dnsmasq[0].port='53' 且默认没有这个项（没有时dnsmasq也启动为53

**Comment by zmjjack** [comment]
> > smartdns_1.2022.v37.2.10-1_aarch64_generic.ipk这个装上后，设置53端口会和dnsmasq冲突，smartdns自动关闭。也就是说不会自动设置dnsmasq
> 
> @pymumu 证实在lede上，将smartdns和dnsmasq端口都配置为53时不会自动修改dnsmasq设置。可能的原因有：
> 
> 1. 系统安装的包是dnsmasq，不是dnsmasq-full
> 2. dhcp.@dnsmasq[0].server 不存在
> 3. dnsmasq的端口号配置在 dhcp.@dnsmasq[0].port='53' 且默认没有这个项（没有时dnsmasq也启动为53

但是，安装smartdns.1.2022.08.31-2206.aarch64-openwrt-all.ipk的话，是会自动设置dnsmasq的，无问题。

**Comment by pymumu** [comment]
[smartdns-build.zip](https://github.com/pymumu/smartdns/files/9535150/smartdns-build.zip)

编译了一个版本，用这个验证下吧。

**Comment by zmjjack** [comment]
> [smartdns-build.zip](https://github.com/pymumu/smartdns/files/9535150/smartdns-build.zip)
> 
> 编译了一个版本，用这个验证下吧。

好的。

**Comment by VergilGao** [comment]
> [smartdns-build.zip](https://github.com/pymumu/smartdns/files/9535150/smartdns-build.zip)
> 
> 编译了一个版本，用这个验证下吧。

请问一下，可以在release的时候同步更新一下`openwrt-smartdns`这个仓库的Makefile么？我看到有在维护`luci-app-smartdns`，但是这个仓库init了之后就再也没有维护过了。

**Comment by PikuZheng** [comment]
> 请问一下，可以在release的时候同步更新一下`openwrt-smartdns`这个仓库的Makefile么？我看到有在维护`luci-app-smartdns`，但是这个仓库init了之后就再也没有维护过了。

为什么不用 smartdns/package/openwrt/Makefile

**Comment by VergilGao** [comment]
> > 请问一下，可以在release的时候同步更新一下`openwrt-smartdns`这个仓库的Makefile么？我看到有在维护`luci-app-smartdns`，但是这个仓库init了之后就再也没有维护过了。
> 
> 为什么不用 smartdns/package/openwrt/Makefile

我可能对openwrt的编译理解不太深，我看这个文件一直没有更新过

**Comment by zmjjack** [comment]
> [smartdns-build.zip](https://github.com/pymumu/smartdns/files/9535150/smartdns-build.zip)
> 
> 编译了一个版本，用这个验证下吧。

刚装上了，这个是可以正常使用的。
