### ISSUE TITLE
OpenWrt官方源码版本替换

### ISSUE THREAD

**Issue by hululu1068** [pymumu/smartdns#1057]
**需求应用场景**

OpenWrt官方源码收录了，但是版本比较旧，手动替换版本是否是这样

```
sed -i 's/1.2021.35/1.2022.37.2/g' feeds/packages/net/smartdns/Makefile
sed -i 's/f50e4dd0813da9300580f7188e44ed72a27ae79c/64e5b326cc53df1fec680cfa28ceec5d8a36fcbc/g' feeds/packages/net/smartdns/Makefile
sed -i 's/^PKG_MIRROR_HASH/#&/' feeds/packages/net/smartdns/Makefile
```

**设备信息**

固件信息  
OpenWrt v22.03.0

**Comment by PikuZheng** [comment]
参考 #1055 但是这个方法似乎是更新到最新release，并不是最新comment

**Comment by hululu1068** [comment]
下午测试了下，`./scripts/feeds`后替换掉`version`和`SHA`再编译就是指定版本了

<img width="279" alt="image" src="https://user-images.githubusercontent.com/68652362/189134332-6c5b8028-d8c6-45cd-a131-18ecf06f27c7.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/68652362/189134501-e7dd739a-45c6-42f9-bccb-f80953bcefba.png">

**Comment by naoki66** [comment]
PKG_MIRROR_HASH  这个能否告知怎么获得呢？  不想直接就注释掉了

**Comment by PikuZheng** [comment]
PKG_MIRROR_HASH:=SKIP

> PKG_MIRROR_HASH 这个能否告知怎么获得呢？ 不想直接就注释掉了

**Comment by openips** [comment]
sha256

**Comment by pymumu** [comment]
make package/feeds/packages/smartdns/download V=s
make package/feeds/packages/smartdns/check FIXUP=1 V=s

**Comment by zmjjack** [comment]
> make package/feeds/packages/smartdns/download V=s make package/feeds/packages/smartdns/check FIXUP=1 V=s

这两条命令是什么意思？

**Comment by pymumu** [comment]
最新代码已经合并到openwrt主干和22.02
