### ISSUE TITLE
最新源码如何设置才能让smartdns不对openwrt做任何修改，仅作为被动调用的DNS服务？

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1058]
**需求应用场景**
老版本的smartdns，重定向为无，开了7053、8055、6053共3个dns端口提供不同的dns服务，不会对openwrt进行任何修改。最新源码的smartdns取消了重定向的选项，默认勾选了自动设置dnsmasq，我就搞不清楚如果设置才能达到老版本的效果了。

**建议的方案**
无

**设备信息**
koolshare openwrt 2.37

**Comment by PikuZheng** [comment]
取消勾选 自动设置Dnsmasq ，保存并应用。然后去dnsmasq那边把 DNS 服务器端口 改回来，保存并应用？

**Comment by yyysuo** [comment]
> 取消勾选 自动设置Dnsmasq ，保存并应用。然后去dnsmasq那边把 DNS 服务器端口 改回来，保存并应用？

我最高安装过37.2.5，自动设置dnsmasq的勾是默认勾选的，dnsmasq的端口并没有被改掉，也没看出对系统做了哪些修改，有什么影响，估计是升级上来的，luci界面没有修改参数并保存应用，那个勾并没有生效吧？还是希望作者给出权威的解答。

**Comment by pymumu** [comment]
默认情况：
1. 53端口，会停止dnsmasq DNS服务，接管DNS。
2. 非53端口，会自动设置为Dnsmasq的上游，关闭2个禁止处理本地IP的配置。

升级情况：
1. 升级前重定向None，升级后保持原有模式不变。
2. 升级前53重定向，升级后，smartdns会运行在53端口，关闭dnsmasq的DNS服务。
3. 升级前是作为dnsmasq上游，升级后保持上游不变。

如果要和之前的None模式一致，设置非53端口，并且去勾选`自动设置dnsmasq`。

**Comment by yyysuo** [comment]
> 默认情况：
> 
> 1. 53端口，会停止dnsmasq DNS服务，接管DNS。
> 2. 非53端口，会自动设置为Dnsmasq的上游，关闭2个禁止处理本地IP的配置。
> 3. 非53端口，去勾选`自动设置dnsmasq`，之前版本重定向为None模式
> 
> 升级情况：
> 
> 1. 升级前重定向None，升级后保持原有模式不变。
> 2. 升级前53重定向，升级后，smartdns会运行在53端口，关闭dnsmasq的DNS服务。
> 3. 升级前是作为dnsmasq上游，升级后保持上游不变。
> 
> 如果要和之前的None模式一致，设置非53端口，并且去勾选`自动设置dnsmasq`。

感谢大佬解惑，已升级至[1.2022.v37.2.9](https://github.com/PikuZheng/smartdns/releases/tag/1.2022.v37.2.9)

**Comment by yyysuo** [comment]
> > 1.2022.v37.2.5
> > 修改了luci和luci-compat相关功能 !重要：据issue报告该版本有问题，建议保持37.2.2不要更新
> 
> > 1.2022.v37.2.7
> > 修正了luci相关问题。建议尽快自37.2.2及以后的版本更新至此版本。37.2.1可不更新，继续观望。
> > 非openwrt用户可不升级。
> 
> > 1.2022.v37.2.8
> > 进一步修改dnsmasq配置以解决冲突。建议尽快自37.2.2及以后的版本更新至此版本。37.2.1可不更新，继续观望。
> > 非openwrt用户可不升级。
> 
> 请更新到至少37.2.8
已更新到至少37.2.9
