### ISSUE TITLE
需要arm v8的ipk，用于斐讯N1

### ISSUE THREAD

**Issue by btyufe** [pymumu/smartdns#106]
**需求应用场景**
斐讯N1上的单臂路由,运行openwrt，没有可用的smartdns版本

**建议的方案**
增加N1上的openwrt可用的版本

**设备信息**
1. 设备信息（CPU，厂家）  
ARMv8 Processor rev 4 (v8l)，晶晨AML S905D
2. 固件信息
OpenWrt R9.2.14 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)

**Comment by pymumu** [comment]
openwrt并没有官方编译支持，也没有机器验证，近期不会提供，暂时可以用armbian的版本。

**Comment by btyufe** [comment]
请问能帮忙编译个arm64的IPK吗？deb无法安装

**Comment by ziyuedi** [comment]
> 
> 
> openwrt 并没有官方编译支持，也没有机器验证，近期不会提供，暂时可以用 armbian 的版本。

deb包中的arm64应为aarch64

**Comment by pymumu** [comment]
尝试Release 26静态编译版本把。
