### ISSUE TITLE
如何配置让所有的解析都写入ipset?

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#1061]
就是让所有的解析结果全部写入ipset，这个怎么配置呢？
再请教一个问题，如何将未知域名添加到ipset中，就是我不确定要访问哪个域名，但我希望解析后把它加到ipset中

**Comment by PikuZheng** [comment]
ipset /domain-set:alldomain/someipsetname
domain-set -name alldomain -type list -file alldomains

文件alldomains记录全球所有顶级域名，可以从icann获取（目前1487个）

”所有的解析结果全部写入ipset“和”将未知域名添加到ipset“有区别吗

**Comment by pymumu** [comment]
bind参数支持ipset设置。
