### ISSUE TITLE
domain-set 不生效

### ISSUE THREAD

**Issue by fcyf** [pymumu/smartdns#1069]
问题描述：
在配置文件里配置domain-set，无论是配合nameserver 还是address使用都不生效，查询的域名还是会走default group的dns。

smartdns版本：
37.2

相关配置文件：
/etc/smartdns/smartdns.conf
domain-set -name test -file /etc/smartdns/test.conf
address /domain-set:test/111.111.111.1

/etc/smartdns/test.conf
abc.com
def.com

测试
dig www.abc.com @127.0.0.1
root@localhost:/etc/smartdns# dig abc.com @127.0.0.1

; <<>> DiG 9.18.1-1ubuntu1.1-Ubuntu <<>> abc.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16521
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;abc.com.                       IN      A

;; ANSWER SECTION:
abc.com.                60      IN      A       54.230.21.9
abc.com.                60      IN      A       54.230.21.33
abc.com.                60      IN      A       54.230.21.101
abc.com.                60      IN      A       54.230.21.45

按配置预期返回的应该是111.111.111.1

**Comment by pymumu** [comment]
37.2不支持domain-set

**Comment by fcyf** [comment]
啊，那只有手动敲具体配置了，如
address /abc.com/111.111.111.1
nameserver /abc.com/server1 
nameserver /def.com/server1

**Comment by pymumu** [comment]
[smartdns-build.zip](https://github.com/pymumu/smartdns/files/9568204/smartdns-build.zip)

**Comment by fcyf** [comment]
这效率也太高了吧！
可以了
