### ISSUE TITLE
IPV6 is not ready, disable IPV6 features 为什么要这么做？

### ISSUE THREAD

**Issue by JarmoHu** [pymumu/smartdns#1072]
**需求应用场景**
作为校园网dns服务器，服务器只有一个固定ipv4，但是用户可以访问ipv4+ipv6.

**建议的方案**
手动设置，忽略本地没有ipv6，强制开启ipv6解析。

**Comment by PikuZheng** [comment]
禁用ipv6功能不影响向用户提供ipv6的查询结果。请注意区分”功能“和”查询“。

当本机没有可用的ipv6时，不进行ipv6的测速、双栈ip优选等功能，否则会出permission denied等错
