### ISSUE TITLE
dualstack-ip-selection-threshold值该设置多大才能更优先IPv4呢？

### ISSUE THREAD

**Issue by 4thanks** [pymumu/smartdns#1074]
目前的配置
```
cache-persist yes
cache-size 16384
dualstack-ip-selection yes                                                   
dualstack-ip-selection-threshold 15
prefetch-domain yes
serve-expired yes                                                            
serve-expired-ttl 345600
serve-expired-reply-ttl 1
serve-expired-prefetch-time 43200
force-qtype-SOA 65
speed-check-mode tcp:443,tcp:80,ping
```
`dualstack-ip-selection-threshold `这个值是针对ping ipv4返回的time还是IPv6返回的？还是两者同时测速返回低于这个值都会保留？
如果想更倾向优先IPv4，IPv6只是备用不想抢IPv4要怎么设置，参数值设置多少比较合适，**或更好设置？（结尾的提问）**

------
前因后果

#964 后折腾过mosdns、adguardhome，发现可能不是dns服务器多或少的问题，也不是分流的问题，在没魔法上网的情况上都差不多，很难上网站依然很难上。

这次重新用回adguardhome有意外发现，重定向53后发现局域网设备都是优先用IPv6请求解析连接（之前都是重定向dnsmasq上游）

![WX20220917-172038@2x](https://user-images.githubusercontent.com/63891627/190852548-83d73024-fa60-4eb8-90a0-9ce7abca0486.png)

如上内网的台式机和手机等都是优先走IPv6，刚开始以为这些奇怪IP不是内网的设备，按网络搜索设置只让局域网内请求
![WX20220917-184028@2x](https://user-images.githubusercontent.com/63891627/190852712-34d3e421-dc24-4164-aa08-0963510189ba.png)

结果火纹手游登陆成功率提高了，#964 提到过用smartdns上是能上，但需要经过一晚上的测速缓存，才能隔天登陆（但成功率也不高），这次纯IPv4只要半个小时到一个多小时就可以登陆，而且后续还蛮稳定的。抱着怀疑可能是之前缓存的因素，重启路由，也是在半个小时多后就能登陆了。为了验证到底是不是双路的问题，又试了禁用IPv6地址解析。
![WX20220917-184131@2x](https://user-images.githubusercontent.com/63891627/190852754-1bdaa0ed-6d82-47af-b593-469f3afe7fb5.png)

发现和只允许内网IPv4网段请求的效果差不多，路由重启后也差不是半个小时后可以登陆了。

经过以上不严谨的测试，大概判定是双路是IPv6优先的干扰。因为IPv6是公网IP，偶尔可以ddns远程回家，所以不太舍得全部禁用IPv6。虽然adguardhome 只允许内网IPv4请求也还能用，但实际使用及[IPv6 test - IPv6/4 connectivity and speed test ](https://ipv6-test.com/) 测试不太稳定。

**目前是adguardhome套娃模式，想问如果单smartdns怎么设置让内网更优先IPv4呢？** 所以就有开头的问题。

**Comment by PikuZheng** [comment]
ipv6服务、ipv6应答是两回事。禁用ipv6服务时客户端仍可能获得ipv6结果；禁用ipv6应答，客户端仍可用ipv6向smartdns发起请求。

但是上面的内容显然是把两者混淆了。所以不理解你究竟是不想让客户端使用ipv6发起dns请求，还是对于什么什么游戏不想让客户端获得ipv6结果。

如果是某些确定的域名只想用ipv4连接，那么只需要通过address规则屏蔽这些域名的ipv6结果。

至于ddns回来的问题涉及到ddns域名更新的ttl，又是第三件事了。

**Comment by 4thanks** [comment]
IPv6服务是要的，毕竟是公网可以ddns，但先弄懂双栈优先的问题。

以下是我大概意思（可能我的理解和表达不太对）

默认IPv4、IPv6双线时：
`IPv6请求→IPv6应答→IPv6连接` > `IPv6请求→IPv4应答→IPv4连接`；

在设置了“禁用IPv6应答”
`IPv4请求→IPv4应答→IPv4连接`

我想的/想实现的：
`IPv6请求→IPv4应答→IPv4连接` > `IPv6请求→IPv6应答→IPv6连接`；
（因为实际使用adguardhome显示是来自IPv6，只有在禁用IPv6地址解析或只允许客户端192.168.0.1/24时，客户端才是IPv4）

**Comment by PikuZheng** [comment]
IPv6服务和公网ddns没有任何关系啊，你要通过公网的ipv6地址访问smartdns吗？

>默认IPv4、IPv6双线时：
>IPv6请求→IPv6应答→IPv6连接 > IPv6请求→IPv4应答→IPv4连接；

不正确。如果没有特殊的禁用设置，IPV4服务和IPV6服务都会应答IPV4和IPV6的混合结果，用哪个连取决于终端
例：
```
C:\Users\Admin>nslookup www.bilibili.com.
。。。。
Non-authoritative answer:
Name:    a.w.bilicdn1.com
Addresses:  2408:872f:20:b::13
          2408:872f:20:b::14
          2408:872f:20:b::16
          2408:872f:20:b::15
          2408:872f:20:b::18
          2408:872f:20:b::17
          218.60.18.13
          218.60.18.17
          218.60.18.18
          218.60.18.14
          218.60.18.15
          218.60.18.16
Aliases:  www.bilibili.com
```

>在设置了“禁用IPv6应答”
>IPv4请求→IPv4应答→IPv4连接

这个”禁用IPV6应答“是指force-aaaa-soa吗？结果应该是无论ipv4服务还是ipv6服务，都会应答ipv4结果。
例：
```
C:\Users\Admin>nslookup www.baidu.com. fd00::96
服务器:  UnKnown
Address:  fd00::96

非权威应答:
名称:    www.a.shifen.com
Addresses:  110.242.68.3
          110.242.68.4
Aliases:  www.baidu.com
```

>IPv6请求→IPv4应答→IPv4连接 > IPv6请求→IPv6应答→IPv6连接

照这个看请求来源是ipv4还是ipv6不重要。问题是你想哪些域名屏蔽ipv6，哪些域名屏蔽ipv4

**Comment by 4thanks** [comment]
> > 默认IPv4、IPv6双线时：
> > IPv6请求→IPv6应答→IPv6连接 > IPv6请求→IPv4应答→IPv4连接；
> 
> 不正确。如果没有特殊的禁用设置，IPV4服务和IPV6服务都会应答IPV4和IPV6的混合结果，用哪个连取决于终端 例：

所以才想到`dualstack-ip-selection-threshold`这个可不可以让IPv4优先


> > IPv6请求→IPv4应答→IPv4连接 > IPv6请求→IPv6应答→IPv6连接
> 
> 照这个看请求来源是ipv4还是ipv6不重要。问题是你想哪些域名屏蔽ipv6，哪些域名屏蔽ipv4

如果是平常访问的网站还好，但手机上有点超出我能力，不知道一个app会请求哪些域名，然后把它们一个个验证过去。

**Comment by PikuZheng** [comment]
所以是要 ”双栈域名给出ipv4结果，纯ipv6网站给出ipv6结果“？

**Comment by 4thanks** [comment]
> 所以是要 ”双栈域名给出ipv4结果，纯ipv6网站给出ipv6结果“？

对，是这个意思，smartdns如何设置才能实现？

**Comment by PikuZheng** [comment]
Duplicate of #332 
参考 https://github.com/pymumu/smartdns/issues/332#issuecomment-585238669
https://github.com/pymumu/smartdns/issues/967#issuecomment-1159351363

**Comment by 4thanks** [comment]
> Duplicate of #332 参考 [#332 (comment)](https://github.com/pymumu/smartdns/issues/332#issuecomment-585238669) [#967 (comment)](https://github.com/pymumu/smartdns/issues/967#issuecomment-1159351363)

#332 两个都不勾选。我一直没勾选，全部取消，都在自定义配置里，也就是开头提到的。但我使用体验不是那么一回事，目前只有在adguardhome限制IPv6请求能改善一些。

```
root@ImmortalWrt:~# cat /etc/config/smartdns

config smartdns
	option server_name 'smartdns'
	option seconddns_no_speed_check '0'
	option seconddns_no_dualstack_selection '0'
	option seconddns_no_cache '0'
	option tcp_server '0'
	option seconddns_tcp_server '0'
	option ipv6_server '0'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_ipset '0'
	option seconddns_no_rule_soa '0'
	option dualstack_ip_selection '0'
	option prefetch_domain '0'
	option serve_expired '0'
	option force_aaaa_soa '0'
	option rr_ttl_min '300'
	option redirect 'none'
	option seconddns_port '7053'
	option coredump '0'
	option seconddns_force_aaaa_soa '0'
	option enabled '1'
	option resolve_local_hostnames '1'
	option port '6053'
	option auto_set_dnsmasq '0'
	option force_https_soa '0'
	list old_redirect 'none'
	list old_port '6053'
	list old_enabled '1'
```
#967 和我的情况相反，他是一定要IPv6，而且我的自定义配置也参考那个的

**Comment by PikuZheng** [comment]
就是要看你常用网站ipv4和ipv6的ping 差值来确定dualstack-ip-selection-threshold。要不就给ipv6的icmp出栈人为增加延迟，或直接丢包

**Comment by pymumu** [comment]
现在所有的设备都是优先有IPV6访问网站的，所以smartdns才会做双栈优选的功能。

如果想倾向使用IPV4，可以将dualstack-ip-selection-threshold调低，比如5ms，表示如果v6地址的ping时延-5ms > ipv4的时延迟。就会使用IPV4。

这个值目前是15ms，是我这里的经验值。
另外测速模式，我是用的默认，没有修改。

至于你说的那些需要特殊通道链接的网站，smartdns并不是魔法软件。smartdns更多还是对直接链接的网站做一定程度的辅助。

比如微软商店，PS商店等。

**Comment by 4thanks** [comment]
> 至于你说的那些需要特殊通道链接的网站，smartdns并不是魔法软件。smartdns更多还是对直接链接的网站做一定程度的辅助。
> 
> 比如微软商店，PS商店等。

这个道理懂得，所以才只问smartdns关于双栈优先dualstack-ip-selection-threshold值的测试，啰哩啰嗦一堆是方便于理解提问的缘由，这个测试方向其实也不太严谨，在有限的知识和经验推导得出改善的办法，也是自己强迫症。

> 现在所有的设备都是优先有IPV6访问网站的，所以smartdns才会做双栈优选的功能。
> 
> 如果想倾向使用IPV4，可以将dualstack-ip-selection-threshold调低，比如5ms，表示如果v6地址的ping时延-5ms > ipv4的时延迟。就会使用IPV4。
> 
> 这个值目前是15ms，是我这里的经验值。 另外测速模式，我是用的默认，没有修改。
> 

谢谢，这个数值我拿去折腾验证一下。

**Comment by LsnmxNB** [comment]
日前而言，我直接关闭主路由的ipv6,ipv6太多问题

**Comment by 4thanks** [comment]
> 日前而言，我直接关闭主路由的ipv6,ipv6太多问题

IPv4、6双栈测试只是我主观臆断的😂，算死脑筋钻牛角尖的玄学测试，不过adguardhome套娃smartdns中限制网内IPv4网段请求，综合体验还是不错
