### ISSUE TITLE
新版openwrt版出现DNS泄露问题

### ISSUE THREAD

**Issue by siren202101** [pymumu/smartdns#1077]
新版openwrt版出现DNS泄露问题，旧版没有这个问题，检测网址https://browserleaks.com/dns

**Comment by PikuZheng** [comment]
这个测试是啥意思，运营商截获明文dns信息不是正常的嘛

**Comment by PikuZheng** [comment]
运营商已经开始污染dot和doh了？

**Comment by siren202101** [comment]
只要打开SmartDns检测就会出现国内DNS，关掉就没有，旧版本也没有

**Comment by PikuZheng** [comment]
> 只要打开SmartDns检测就会出现国内DNS，关掉就没有，旧版本也没有

我是没理解这个检测的目的和检测结果如何解读。我家宽带用这个检测，结果有一大堆国内外ip，但看起来都是随机ip，既没有我正在使用的dns上游服务的ip，也没有其他我没在使用的dns服务器ip。

根据 https://www.dnsleaktest.com/what-is-a-dns-leak.html ， 大体意思是如果客户端和vpn服务端采用了隧道连接，此时客户端应通过隧道使用vpn服务端提供的dns，不应使用运营商（或其他dns服务器）提供的dns；如果此时客户端和vpn服务端之外的第三方获取到了dns请求信息，则判定为dns泄露。

按照这个说法，dns泄露应该是安全隧道连接和路由的故障，和smartdns没什么关西。

**Comment by cresky-github** [comment]
> > 只要打开SmartDns检测就会出现国内DNS，关掉就没有，旧版本也没有
> 
> 我是没理解这个检测的目的和检测结果如何解读。我家宽带用这个检测，结果有一大堆国内外ip，但看起来都是随机ip，既没有我正在使用的dns上游服务的ip，也没有其他我没在使用的dns服务器ip。
> 
> 根据 https://www.dnsleaktest.com/what-is-a-dns-leak.html ， 大体意思是如果客户端和vpn服务端采用了隧道连接，此时客户端应通过隧道使用vpn服务端提供的dns，不应使用运营商（或其他dns服务器）提供的dns；如果此时客户端和vpn服务端之外的第三方获取到了dns请求信息，则判定为dns泄露。
> 
> 按照这个说法，dns泄露应该是安全隧道连接和路由的故障，和smartdns没什么关西。

简单来说，
就是IP分流，策略不完美。

我让DNS走代理，比如美国节点，不会出现其它地区的NDS。

**Comment by PikuZheng** [comment]
>我让DNS走代理，比如美国节点，不会出现其它地区的DNS。

如何判定”不会出现其他地区的DNS“？如果dns请求通过代理到美国节点后，美国节点又向他的上游发起查询，这个怎么算？

感觉您是受到了”整机隔离方案“或”系统半隔离安全上网方案“的毒害

**Comment by PikuZheng** [comment]
> 每使用一个DNS，就显示IP及属地（国旗）。

dns 是递归查询，发起一个查询后势必要逐级经由dns服务器直到域名起始授权服务器。检测使用50个真实域名和50个不存在的域名（但不透露究竟是哪些域名）如何证实检测结果是产生在墙内还是墙外？

**Comment by pymumu** [comment]
看你分流是否正确。
如果你配置了国内的DNS服务器，smartdns会进行测速处理，这样国内的速度比国外快，就会选择国内的DNS结果了。
你可以把国内DNS上游去掉。或者正确配置nameserver分流。

**Comment by cresky-github** [comment]
> 看你分流是否正确。
> 如果你配置了国内的DNS服务器，smartdns会进行测速处理，这样国内的速度比国外快，就会选择国内的DNS结果了。
> 你可以把国内DNS上游去掉。或者正确配置nameserver分流。

采用IP分流，判断IP是不是World IP。
是，就走代理；
非，就直连。
也就是说，我把网络分为两个：直连（内网和国内）和代理。从而不用考虑测速的因素，只考虑IP属地。
DNS和域名组名相同，并排除默认组。DNS又按IP分流，进而保证域名解析走代理。
就不会泄漏了。

**Comment by pymumu** [comment]
你可以增加
```
nameserver /browserleaks.com/foreign
```
来验证，foreign设置国外TLS，HTTPS

**Comment by cresky-github** [comment]
> 你可以增加
> 
> ```
> nameserver /browserleaks.com/foreign
> ```
> 
> 来验证，foreign设置国外TLS，HTTPS

我的做法，非常简单：
geosite:cn为国内组，用国内DNS解析；
其余，为默认组（国外），用国外DNS解析。

**Comment by mokeyish** [comment]
@cresky-github 兄弟哪里有适用于 smartdns 的 geosite:cn 下载，v2ray 貌似不能用吧。

**Comment by PikuZheng** [comment]
> @cresky-github 兄弟哪里有适用于 smartdns 的 geosite:cn 下载，v2ray 貌似不能用吧。

https://github.com/Loyalsoldier/v2ray-rules-dat/blob/release/direct-list.txt

**Comment by cresky-github** [comment]
> @cresky-github 兄弟哪里有适用于 smartdns 的 geosite:cn 下载，v2ray 貌似不能用吧。

V2Ray 直接使用 geosite:cn。

SmartDNS 使用 其文本。
但，需按SmartDNS语法转写。

**Comment by mokeyish** [comment]
> SmartDNS 使用 其文本。 但，需按SmartDNS语法转写。

@cresky-github 
写了个转换的命令，不过有点慢

```shell
curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt\
    | grep -v 'regexp:' \
    | sed 's/full://'\
    | xargs -i -n1 echo nameserver /{}/china
```

**Comment by cresky-github** [comment]
> > SmartDNS 使用 其文本。 但，需按SmartDNS语法转写。
> 
> @cresky-github 写了个转换的命令，不过有点慢
> 
> ```shell
> curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt\
>     | grep -v 'regexp:' \
>     | sed 's/full://'\
>     | xargs -i -n1 echo nameserver /{}/china
> ```


可以参阅 #1109

**Comment by mokeyish** [comment]
> > > SmartDNS 使用 其文本。 但，需按SmartDNS语法转写。
> > 
> > 
> > @cresky-github 写了个转换的命令，不过有点慢
> > ```shell
> > curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt\
> >     | grep -v 'regexp:' \
> >     | sed 's/full://'\
> >     | xargs -i -n1 echo nameserver /{}/china
> > ```
> 
> 可以参阅 #1109


我好像只看到 删除 的，没有生成 smartdns 格式的。。


我上面写的是可以直接生成 smardns 格式的，输出重定向到文件就好。
<img width="335" alt="图片" src="https://user-images.githubusercontent.com/16131917/194701244-8c17c46a-a46d-440a-afa2-ff99d24b9d18.png">

**Comment by cresky-github** [comment]
> > > > SmartDNS 使用 其文本。 但，需按SmartDNS语法转写。
> > > 
> > > 
> > > @cresky-github 写了个转换的命令，不过有点慢
> > > ```shell
> > > curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt\
> > >     | grep -v 'regexp:' \
> > >     | sed 's/full://'\
> > >     | xargs -i -n1 echo nameserver /{}/china
> > > ```
> > 
> > 
> > 可以参阅 #1109
> 
> 我好像只看到 删除 的，没有生成 smartdns 格式的。。
> 
> 我上面写的是可以直接生成 smardns 格式的，输出重定向到文件就好。 <img alt="图片" width="335" src="https://user-images.githubusercontent.com/16131917/194701244-8c17c46a-a46d-440a-afa2-ff99d24b9d18.png">


看一下行数，
应该差不了多少的。

**Comment by mokeyish** [comment]
> > > > > SmartDNS 使用 其文本。 但，需按SmartDNS语法转写。
> > > > 
> > > > 
> > > > @cresky-github 写了个转换的命令，不过有点慢
> > > > ```shell
> > > > curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt\
> > > >     | grep -v 'regexp:' \
> > > >     | sed 's/full://'\
> > > >     | xargs -i -n1 echo nameserver /{}/china
> > > > ```
> > > 
> > > 
> > > 可以参阅 #1109
> > 
> > 
> > 我好像只看到 删除 的，没有生成 smartdns 格式的。。
> > 我上面写的是可以直接生成 smardns 格式的，输出重定向到文件就好。 <img alt="图片" width="335" src="https://user-images.githubusercontent.com/16131917/194701244-8c17c46a-a46d-440a-afa2-ff99d24b9d18.png">
> 
> 看一下行数， 删除了 regexp 后， 应该差不了多少的。
优化了一下，可以了
```shell
curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt | sed '/full:/d;/regexp:/d;s#\(\S*\)#nameserver /\1/china#'
```

**Comment by cresky-github** [comment]
> ```shell
> full:
> ```


/full:/d

是错误的处理方法，
正确的方法应该是 s/full://g;

**Comment by cresky-github** [comment]
> > > > > > SmartDNS 使用 其文本。 但，需按SmartDNS语法转写。
> > > > > 
> > > > > 
> > > > > @cresky-github 写了个转换的命令，不过有点慢
> > > > > ```shell
> > > > > curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt\
> > > > >     | grep -v 'regexp:' \
> > > > >     | sed 's/full://'\
> > > > >     | xargs -i -n1 echo nameserver /{}/china
> > > > > ```
> > > > 
> > > > 
> > > > 可以参阅 #1109
> > > 
> > > 
> > > 我好像只看到 删除 的，没有生成 smartdns 格式的。。
> > > 我上面写的是可以直接生成 smardns 格式的，输出重定向到文件就好。 <img alt="图片" width="335" src="https://user-images.githubusercontent.com/16131917/194701244-8c17c46a-a46d-440a-afa2-ff99d24b9d18.png">
> > 
> > 
> > 看一下行数， 删除了 regexp 后， 应该差不了多少的。
> > 优化了一下，可以了
> 
> ```shell
> curl https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt | sed '/full:/d;/regexp:/d;s#\(\S*\)#nameserver /\1/china#'
> ```

/full:/d

是错误的处理方法，
正确的方法应该是 s/full://g;

**Comment by mokeyish** [comment]
> > ```shell
> > full:
> > ```
> 
> /full:/d
> 
> 是错误的处理方法， 正确的方法应该是 s/full://g;

为什么？没明白，按行删除不行？

**Comment by cresky-github** [comment]
> > > ```shell
> > > full:
> > > ```
> > 
> > 
> > /full:/d
> > 是错误的处理方法， 正确的方法应该是 s/full://g;
> 
> 为什么？没明白，按行删除不行？


当然不能删除行，
那行有域名

**Comment by cresky-github** [comment]
![image](https://user-images.githubusercontent.com/52242290/194703034-d94b0de1-63d5-498d-9724-e908c0e0b5f3.png)


顺便多一嘴，
防止 DNS 泄漏，很简单，只用一个上游就行了，
国外组，别作死，用国内DNS

**Comment by pymumu** [comment]
新版本的话，用domain-set可以直接使用单行域名。
转换命令
```
grep -v full: direct-list.txt | grep -v "regexp" > direct-list-smartdns.txt
```

配置：
```
domain-set -n direct -f direct-list-smartdns.txt
nameserver /domain-set:direct/xxxx
```

**Comment by cresky-github** [comment]
> 新版本的话，用domain-set可以直接使用单行域名。 转换命令
> 
> ```
> grep -v "full:" direct-list.txt | grep -v "regexp:" > direct-list-smartdns.txt
> ```
> 
> 配置：
> 
> ```
> domain-set -n direct -f direct-list-smartdns.txt
> nameserver /domain-set:direct/xxxx
> ```



几时也来个 ip-set???

**Comment by mokeyish** [comment]
> > 新版本的话，用domain-set可以直接使用单行域名。 转换命令
> > ```
> > grep -v "full:" direct-list.txt | grep -v "regexp:" > direct-list-smartdns.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 配置：
> > ```
> > domain-set -n direct -f direct-list-smartdns.txt
> > nameserver /domain-set:direct/xxxx
> > ```
> 
> 几时也来个 ip-set???

新版的 nftables 已经不支持 ipset 了， ipset 是 iptables 的工具，觉得没必要 ipset 了。如果能直接支持 v2ray 的 geosite 那种格式是最直接的，v2ray 那个会定期更新。

**Comment by cresky-github** [comment]
> > > 新版本的话，用domain-set可以直接使用单行域名。 转换命令
> > > ```
> > > grep -v "full:" direct-list.txt | grep -v "regexp:" > direct-list-smartdns.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 配置：
> > > ```
> > > domain-set -n direct -f direct-list-smartdns.txt
> > > nameserver /domain-set:direct/xxxx
> > > ```
> > 
> > 
> > 几时也来个 ip-set???
> 
> 新版的 nftables 已经不支持 ipset 了， ipset 是 iptables 的工具，觉得没必要 ipset 了。如果能直接支持 v2ray 的 geosite 那种格式是最直接的，v2ray 那个会定期更新。


不是一回事，

domain-set是给域名表命名，
我说的的 ip-set，也是一样的逻辑，给IP表命名。

**Comment by mokeyish** [comment]
总结一下那就是
**旧版**

```shell
curl -s https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt \
    | sed 's/full://g;/regexp:/d;s#(\S*)#nameserver /\1/directIsp#' > /etc/smartdns/direct.conf
```
引用：
```conf
conf-file /etc/smartdns/direct.conf
```
**新版**
```shell
curl -s https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt \
    | sed 's/full://g;/regexp:/d' > /etc/smartdns/direct-list.txt
```
引用：
```conf
domain-set -n direct -f direct-list-smartdns.txt
nameserver /domain-set:direct/directIsp
```

**Comment by cresky-github** [comment]
> 总结一下那就是 **旧版**
> 
> ```shell
> curl -s https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt \
>     | sed 's/full://g;/regexp:/d;s#(\S*)#nameserver /\1/directIsp#' > /etc/smartdns/direct.conf
> ```
> 
> 引用：
> 
> ```
> conf-file /etc/smartdns/direct.conf
> ```
> 
> **新版**
> 
> ```shell
> curl -s https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt \
>     | sed 's/full://g;/regexp:/d' > /etc/smartdns/direct-list.txt
> ```
> 
> 引用：
> 
> ```
> domain-set -n direct -f direct-list-smartdns.txt
> nameserver /domain-set:direct/directIsp
> ```

这样写，是照顾不会 sed 的用户，
会用sed，还是直接写 nameserver /domain/group 形式方便。
