### ISSUE TITLE
smartdns无法启动

### ISSUE THREAD

**Issue by Sharelter** [pymumu/smartdns#1080]
**问题现象**  
首次配置后点击保存应用提示这个:
`RPC call to uci/delete failed with ubus code 4: Resource not found
  at handleCallReply (http://192.168.10.1/luci-static/resources/rpc.js?v=git-22.245.77528-487e58a:15:3)`

系统日志:
` Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash`

**运行环境**
1. 固件型号  
```
ramips/mt7621
OpenWrt 22.03.0 r19685-512e76967f / LuCI openwrt-22.03 branch git-22.245.77528-487e58a
OrayBox-X3A
```
4. smartdns来源以及版本
`opkg install smartdns`
```
Package: smartdns
Version: 1.2021.35-1
Depends: libc, libpthread, libopenssl1.1
Status: install ok installed
Architecture: mipsel_24kc
Conffiles:
 /etc/config/smartdns 6953c1cbf6737080b8933a6598afaadf2d0de14a6edfac582dc8879d6bacd9c2
 /etc/smartdns/address.conf bc2779f73c5cd22510cb5ae477d0f00463eb7f2bd73fe3264c73586f79025780
 /etc/smartdns/blacklist-ip.conf a0a6331a6f17151353d011c306ce3b5ef0f492a681b121d31e3d2c26058c8093
 /etc/smartdns/custom.conf f31dd67de7b422f8caa47696302ab540afc1c117a0925d9da79aa57c38d26d52
Installed-Time: 1663691810
```

**重现步骤**
1. 上游DNS配置。  

3. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  

`不存在该文件`
3. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录

`开启coredump后没有文件产生`

**Comment by 4thanks** [comment]
应该是安装版本不太对，建议用命令`opkg print-architecture`查看一下路由的cpu
然后到 https://downloads.openwrt.org/snapshots/packages/ 或 https://github.com/PikuZheng/smartdns/releases 下载对应的安装包再试试

**Comment by Sharelter** [comment]
Output of opkg print-architecture command:
```
arch all 1
arch noarch 1
arch mipsel_24kc 10
```

**Comment by PikuZheng** [comment]
不像架构问题。

**Comment by PikuZheng** [comment]
>1.2021.35-1

这个版本不对啊，现在openwrt那边都更新到37了

**Comment by PikuZheng** [comment]
我想起来了，这个版本的启动脚本有问题。改设置保存后需要重启整个路由器

**Comment by Sharelter** [comment]
THX, I flashed my openwrt to snapshot version, and now everything works :)
