### ISSUE TITLE
为什么使用DoH在dns服务端查看还会由未加密的请求？

### ISSUE THREAD

**Issue by junx964** [pymumu/smartdns#1081]
**问题现象**  
简要描述问题出现的现象
使用DoH时会有有未加密的请求
![image](https://user-images.githubusercontent.com/68261800/191939885-f319d64d-37c3-4d5f-a312-e069ce626fa7.png)
**运行环境**
1. 固件型号
 debian 11 arm64
2. 运营商  
   联通
3. smartdns来源以及版本 
在github下载的 smartdns 1.2022.08.28-1734
4. 涉及的配置(注意去除个人相关信息)
conf-file /etc/smartdns/apple.china.smartdns.conf                               
conf-file /etc/smartdns/bogus-nxdomain.china.smartdns.conf                      
conf-file /etc/smartdns/google.china.smartdns.conf                              
conf-file /etc/smartdns/accelerated-domains.china.smartdns.conf   
server x.x.x.x -group bootstrap                                           
nameserver /dns.domain.com/bootstrap 
bind 0.0.0.0:53 
server 172.20.1.1:5353 -group china -exclude-default-group 
server-https https://dns.domain.com/dns-query

**重现步骤**
1. 上游DNS配置。  
  AdGuardHome 开启DoH
3. 访问的域名。  
 任意国外域名

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。
  [2022-09-23 14:43:12,597][ERROR][      fast_ping.c:704 ] create icmp socket failed, Address family not supported by protocol

  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
进程正常

**Comment by PikuZheng** [comment]
> [2022-09-23 14:43:12,597][ERROR][ fast_ping.c:704 ] create icmp socket failed, Address family not supported by protocol

固件不好，smartdns没有以root用户身份运行

>server x.x.x.x -group bootstrap

没有从默认组排除，所有没有匹配到china组的将向此上游发送查询

**Comment by qiuxiangling** [comment]
> > [2022-09-23 14:43:12,597][ERROR][ fast_ping.c:704 ] create icmp socket failed, Address family not supported by protocol
> 
> 固件不好，smartdns没有以root用户身份运行
> 
> > server x.x.x.x -group bootstrap
> 
> 没有从默认组排除，所有没有匹配到china组的将向此上游发送查询

已解决， 感谢

**Comment by qiuxiangling** [comment]
> > [2022-09-23 14:43:12,597][ERROR][ fast_ping.c:704 ] create icmp socket failed, Address family not supported by protocol
> 
> 固件不好，smartdns没有以root用户身份运行
> 
> > server x.x.x.x -group bootstrap
> 
> 没有从默认组排除，所有没有匹配到china组的将向此上游发送查询

 [2022-09-23 14:43:12,597][ERROR][ fast_ping.c:704 ] create icmp socket failed, Address family not supported by protocol
这个问题 应该跟我本地ping 有关系
ping www.github.com
ping: socket: Address family not supported by protocol
PING github.com (20.27.177.113) 56(84) bytes of data.
有没有什么解决办法....

**Comment by PikuZheng** [comment]
> ping: socket: Address family not supported by protocol

刚注意到是debian，怀疑删掉了某些依赖库但没有完全删，建议用原版无改的试试

**Comment by jxph1123** [comment]
**我的最新版smartdns，设置6053端口，所有的DNS都为DOH和DOT，为啥DNS泄漏测试是这样的，是不是表示DOH失败？还有如何知道访问某网站用的哪个DNS解析？**


![FireShot Capture 308 - DNS Leak Test - BrowserLeaks - browserleaks com](https://user-images.githubusercontent.com/35351787/192687585-6762c1ca-e6ec-400c-9ab7-57bb5cb2a42c.png)

**Comment by pymumu** [comment]
看你doh，dot配置的什么地方ISP，如果配置了国内doh，dot那这结果就没问题

**Comment by jxph1123** [comment]
> 看你doh，dot配置的什么地方ISP，如果配置了国内doh，dot那这结果就没问题


默认组配置有阿里、360和腾讯的DOH/DOT，还有就是国外的DOH/DOT，都是用加密解析了，不知道为啥这个泄露测试还有那么多DNS服务器，而且好像显示的也不是我设置的DNS服务器。

**Comment by PikuZheng** [comment]
DNS泄露测试问题请在 #1077 讨论。个人认为这个测试缺乏必要参考信息，结果无法解读。

**Comment by cresky-github** [comment]
> **问题现象**  
> 简要描述问题出现的现象
> 使用DoH时会有有未加密的请求
> ![image](https://user-images.githubusercontent.com/68261800/191939885-f319d64d-37c3-4d5f-a312-e069ce626fa7.png)
> **运行环境**
> 1. 固件型号
>  debian 11 arm64
> 2. 运营商  
>    联通
> 3. smartdns来源以及版本 
> 在github下载的 smartdns 1.2022.08.28-1734
> 4. 涉及的配置(注意去除个人相关信息)
> conf-file /etc/smartdns/apple.china.smartdns.conf                               
> conf-file /etc/smartdns/bogus-nxdomain.china.smartdns.conf                      
> conf-file /etc/smartdns/google.china.smartdns.conf                              
> conf-file /etc/smartdns/accelerated-domains.china.smartdns.conf   
> server x.x.x.x -group bootstrap                                           
> nameserver /dns.domain.com/bootstrap 
> bind 0.0.0.0:53 
> server 172.20.1.1:5353 -group china -exclude-default-group 
> server-https https://dns.domain.com/dns-query
> 
> **重现步骤**
> 1. 上游DNS配置。  
>   AdGuardHome 开启DoH
> 3. 访问的域名。  
>  任意国外域名
> 
> **信息收集**  
> 1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。
>   [2022-09-23 14:43:12,597][ERROR][      fast_ping.c:704 ] create icmp socket failed, Address family not supported by protocol
> 
>   
> 2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
> 在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
> coredump文件在/tmp目录下
> 进程正常

adguard home，smartdns同内网，哪来的DoH？难道内网之间通过DoH通讯？

**Comment by pymumu** [comment]
用最新代码，有问题再open issue
