### ISSUE TITLE
`[  +0.032888] capability: warning: 'smartdns' uses 32-bit capabilities (legacy support in use)`

### ISSUE THREAD

**Issue by enihcam** [pymumu/smartdns#1082]
**问题现象**  
简要描述问题出现的现象
I see this `[  +0.032888] capability: warning: 'smartdns' uses 32-bit capabilities (legacy support in use)` in dmesg log. What does it mean? any chances to optimize?

**运行环境**
1. 固件型号  
x86-64 PC

2. 运营商  
N/A

3. smartdns来源以及版本
https://github.com/archlinux/svntogit-community/blob/packages/smartdns/trunk/PKGBUILD

4. 涉及的配置(注意去除个人相关信息)
basic config

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
It looks like you are running a 32-bit application on a 64-bit OS. This may be a compilation problem, or the program you are running is not the expected version.

**Comment by PikuZheng** [comment]
Why not just use debian's precompiled package (smartdns.....x86_64-debian-all.deb)?

**Comment by enihcam** [comment]
> Why not just use debian's precompiled package (smartdns.....x86_64-debian-all.deb)?

like other binaries, smartdns is packaged in archlinux convention, i.e. PKGBUILD.

if you open the link above, you'll see how it is compiled:
```bash
build() {
  cd smartdns-Release$pkgver/src
  make
}
```

**Comment by PikuZheng** [comment]
not really... Use static compiled version can avoid support library issues. also default config files and auto start scripts.

**Comment by pymumu** [comment]
Try latest code
