### ISSUE TITLE
这个表示时好时坏？

### ISSUE THREAD

**Issue by naoki66** [pymumu/smartdns#1083]
**问题现象**  
C:\Users\lm8>nslookup -querytype=ptr smartdns
服务器:  OpenWrt.lan
Address:  10.0.0.1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

C:\Users\l8>nslookup www.baidu.com
服务器:  OpenWrt.lan
Address:  10.0.0.1

非权威应答:
名称:    www.a.shifen.com
Address:  14.215.177.39
Aliases:  www.baidu.com

C:\Users\l8>nslookup www.baidu.com
服务器:  OpenWrt.lan
Address:  10.0.0.1

非权威应答:
名称:    www.a.shifen.com
Addresses:  112.80.248.76
          112.80.248.75
          183.232.231.173
Aliases:  www.baidu.com
C:\Users\lm8>nslookup -querytype=ptr smartdns
服务器:  OpenWrt.lan
Address:  10.0.0.1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

**运行环境**
1. 固件型号  lean x64
https://github.com/naoki66/NEW_LEDE_Actions/releases
2. 运营商  unicom

3. smartdns来源以及版本  官方最新38

4. 涉及的配置(注意去除个人相关信息)
https://github.com/naoki66/NEW_LEDE_Actions/blob/main/files/etc/config/smartdns
**重现步骤**
1. 上游DNS配置。  
https://github.com/naoki66/NEW_LEDE_Actions/blob/main/files/etc/config/smartdns
2. 访问的域名。  
 www.baidu.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
`nslookup -querytype=ptr` 后面应该跟一个IP地址

**Comment by pymumu** [comment]
如果是37之后的版本，用
nslookup smartdns
来检查是否生效。

**Comment by pymumu** [comment]
设置为dnsmasq上游看看，非53端口

还有看看进程是不是重启了

**Comment by PikuZheng** [comment]
看起来版本不正确，请使用 20220821 之后的版本

**Comment by PikuZheng** [comment]
> 这得到多个IP是表示未生效吗？

什么是“表示未生效”？

**Comment by crhope** [comment]
> 

好像新版本第一次查询时候会返回一个ip，第二次查询时会返回多个IP，所以现在不能用返回多少个IP来判断是否生效了

**Comment by crhope** [comment]
> C:\Users\Administrator>nslookup smartdns 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> 非权威应答: 名称: smartdns Addresses: ::1 127.0.0.1
> 
> C:\Users\Administrator>nslookup [www.baidu.com](http://www.baidu.com) 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> 非权威应答: 名称: [www.a.shifen.com](http://www.a.shifen.com) Addresses: 14.215.177.39 14.215.177.38 Aliases: [www.baidu.com](http://www.baidu.com)
> 
> C:\Users\Administrator>nslookup [www.qq.com](http://www.qq.com) 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> 非权威应答: 名称: ins-r23tsuuf.ias.tencent-cloud.net Addresses: 2402:4e00:1020:1404:0:9227:71a3:83d2 2402:4e00:1020:1404:0:9227:71ab:2b74 61.241.54.232 61.241.54.211 Aliases: [www.qq.com](http://www.qq.com)
> 
> C:\Users\Administrator>nslookup smartdns 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> 非权威应答: 名称: smartdns Addresses: ::1 127.0.0.1
> 
> 这得到多个IP是表示未生效吗？

好像新版本第一次查询时候会返回一个ip，第二次查询时会返回多个IP，所以现在不能用返回多少个IP来判断是否生效了

**Comment by zxlhhyccc** [comment]
> C:\Users\Administrator>nslookup smartdns 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> ## 非权威应答:
> 名称: smartdns
> Addresses: ::1
> 127.0.0.1
> C:\Users\Administrator>nslookup [www.baidu.com](http://www.baidu.com) 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> ## 非权威应答:
> 名称: [www.a.shifen.com](http://www.a.shifen.com)
> Addresses: 112.80.248.75
> 112.80.248.76
> Aliases: [www.baidu.com](http://www.baidu.com)
> C:\Users\Administrator>nslookup smartdns 服务器: OpenWrt.lan Address: 10.0.0.1
> 
> ## *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> 依旧时好时坏

我测试了好多遍，国内如果配置tls和https，貌似科学会不行。。。。

**Comment by pymumu** [comment]
用最新代码，有问题再open issue
