### ISSUE TITLE
openwrt 已经安装luci仍无法正常显示界面

### ISSUE THREAD

**Issue by snoopytl** [pymumu/smartdns#1085]
**问题现象**  
下载的最新的高大全固件，固件中编译了smartdns，但是存在问题，具体为将smartdns改为主dns后，点击启动无法启动，改回6053可以启动，但openwrt通过命令检查发现是运行的，可通过局域网win10 nslookup 得到多个IP地址，感觉smartdns并没有生效，所以卸载了，然后下载了最新版本的smartdns.1.2022.09.25-1116.x86-openwrt-all.ipk，和luci-app-smartdns.1.2022.09.25-1116.all-luci-all.ipk，安装后，在服务中并没有看到配置界面，请问怎么操作能恢复配置界面

**运行环境**
1. 固件型号  
bleach plus 20220918 @ OpenWrt R22.9.1 / LuCI Master (git-22.255.14339-1ee6726)
2. 运营商  
河北联通
3. smartdns来源以及版本
来源是github
smartdns.1.2022.09.25-1116.x86-openwrt-all.ipk，和luci-app-smartdns.1.2022.09.25-1116.all-luci-all.ipk
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
浏览器清除下缓存，或用隐私模式
检查smartdns是否失效，可以用nslookup smartdns.  新版本smartdns会返回多个ip

**Comment by snoopytl** [comment]
清除缓存、隐私模式都试过了，都不行，现在是没有luci配置界面很头疼
后来仔细阅读了changelog，知道了新版的会返回多个ip，如果方便的话加我微信吧iamkof

**Comment by PikuZheng** [comment]
重复 #992 #1011 #1040 #1044

**Comment by snoopytl** [comment]
问题解决，解决步骤如下
1.卸载所有smartdns相关
2.安装github上的smartdns.1.2022.09.25-1116.x86-openwrt-all.ipk
3.安装github上的luci-app-smartdns.1.2022.09.25-1116.all-luci-compat-all，兼容版，兼容版，兼容版
4.此时仍看不到的，可以通过换皮肤来刷，我是通过换皮就刷出来了

**Comment by PikuZheng** [comment]
> 此时仍看不到的，可以通过换皮肤来刷

不用换皮，ctrl f5 强制刷新浏览器即可

> 能显示了，但是无法运行，6053和53端口都不能运行，怎么解

看日志
