### ISSUE TITLE
可否独立每个组的缓存？

### ISSUE THREAD

**Issue by rampageX** [pymumu/smartdns#1086]
**需求应用场景**
通常用 smartdns 监听两个不同端口，分别查询国内，国外网址，（以获取 CDN 友好以及防污染的结果）。这里会有个问题，就是前端的分流软件（偶尔）出问题的时候，比如某个本应是国内组查询的地址分去了国外组查询，得到一个国外的地址，而 smartdns 会缓存下来，导致下一次即使是国内组查询也会返回这个国外的地址。
目前是开了两个独立的 smartdns 解决这个问题，但是这个就明显削弱了 smartdns 可以独自建立多个服务器监听的特性。

**建议的方案**
独立每一个组 Group 的缓存。

**Comment by PikuZheng** [comment]
重复 #1013 
已经在 20220811-2837407846 修正过了，现在的版本仍有这个问题吗？

**Comment by rampageX** [comment]
编译 git 最新的 smartdns 1.20220925-1747 版本，依然是这样。

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/tree/seprate-cache
拆分了查询缓存，可以试试。

**Comment by rampageX** [comment]
OK了

**Comment by yyysuo** [comment]
请现在https://github.com/pymumu/smartdns/tree/seprate-cache 这个分支是已经合并进主线了吗？也就是说目前缓存就是按组来区分的吗？

**Comment by Hotwill** [comment]
> 请现在https://github.com/pymumu/smartdns/tree/seprate-cache 这个分支是已经合并进主线了吗？也就是说目前缓存就是按组来区分的吗？

同问，目前需要分组缓存的功能，请问合并到master了吗？ @pymumu

**Comment by PikuZheng** [comment]
自v38.1.14（20221020）起，缓存已经按group拆分
