### ISSUE TITLE
openwrt无法启动smartdns

### ISSUE THREAD

**Issue by snoopytl** [pymumu/smartdns#1087]
在经历了#1085 后，能正常显示了，但怎么都无法启动smartdns，端口改成53或者6053都不行，请问该如何修改

**Comment by snoopytl** [comment]
日志里显示信息
Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by PikuZheng** [comment]
smartdns的日志呢

**Comment by snoopytl** [comment]
问题解决，原来是我装错了ipk，应该安装x86-64的ipk，我装成了x86的，所以报错
