### ISSUE TITLE
ipset hash:net同一个域名能同时保存IPv4 IPv6吗？

### ISSUE THREAD

**Issue by 4thanks** [pymumu/smartdns#1089]
```
ipset create abc hash:net family inet timeout 86400 maxelem 130050
ipset create abc6 hash:net family inet6 timeout 86400 maxelem 130050
```
smartdns测速模式下
```
ipset /abc.com/abc
ipset /abc.com/abc6
```

ipset list 查看abc和abc6，只有一个abc6集合有IP，smartdns是按**顺序**最后一个参数配置生效的？有没有方法同时存储IPv4和IPv6吗？

**Comment by PikuZheng** [comment]
>smartdns是按顺序最后一个参数配置生效的？

正确

**Comment by PikuZheng** [comment]
> 有没有方法同时存储IPv4和IPv6

有

**Comment by PikuZheng** [comment]
TMD今天网络质量太差了 请参考项目主页配置文件说明 ipset段，在同一行规则中将ipv4和ipv6指派两个不同的ipset

**Comment by 4thanks** [comment]
> TMD今天网络质量太差了 请参考项目主页配置文件说明 ipset段，在同一行规则中将ipv4和ipv6指派两个不同的ipset

```
ipset /abc.com/#4:abc,#6:abc6
```
这样？
