### ISSUE TITLE
出现占满系统缓存区的问题

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#109]
**问题现象**  
简要描述问题出现的现象
电脑休眠（断网）恢复后，
电脑无法上网，使用python调试的时候出现了
OSError: [WinError 10055] 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
**运行环境**
1. 固件型号  
win10
2. 运营商  
联通
**重现步骤**
1. 上游DNS配置。  
bind [::]:53
cache-size 512
prefetch-domain yes
dualstack-ip-selection yes
rr-ttl-min 120
log-level error
server 10.0.0.10
server 10.0.0.9
server 211.157.15.189
server 210.22.84.3
server 203.240.193.11
server-tcp 8.8.8.8
server-tcp 114.114.114.114
server-tcp 119.29.29.29

2. 访问的域名。  
休眠之前一大堆，因为查资料用了很多域名

**信息收集**  

[smartdns.log](https://github.com/pymumu/smartdns/files/2929901/smartdns.log)
可能的问题所在
prefetch-domain yes仍需优化
之前访问过很多域名，导致电脑无法联网的时候攒了巨量的连接，直接占满系统缓存区

**Comment by pymumu** [comment]
看日志，请求量并不大。
出问题的时候，看一下linux系统中smartdns进程的文件句柄数。

ls /proc/[pid]/fd -lh 

pid为smartdns的pid。

**Comment by rufengsuixing** [comment]
jie@DESKTOP-9MRBUTG:~$ sudo ls /proc/25/fd -lh
total 0
lrwx------ 1 root root 0 Mar  9 00:00 0 -> /dev/null
lrwx------ 1 root root 0 Mar  9 00:00 1 -> /dev/null
lrwx------ 1 root root 0 Mar  9 00:00 11 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 12 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 13 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 14 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 16 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 17 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 18 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 2 -> /dev/null
lrwx------ 1 root root 0 Mar  9 00:00 3 -> /run/smartdns.pid
l--------- 1 root root 0 Mar  9 00:00 4 -> /unknown
l--------- 1 root root 0 Mar  9 00:00 5 -> /unknown
lrwx------ 1 root root 0 Mar  9 00:00 6 -> /unknown
l--------- 1 root root 0 Mar  9 00:00 7 -> /unknown
l-wx------ 1 root root 0 Mar  9 00:00 8 -> /var/log/smartdns.log
lrwx------ 1 root root 0 Mar  9 00:00 9 -> /unknown
结束其他进程能让电脑短时间内可以上网不报溢出错误
结束了smartdns并修改回dns设置，在长时间测试中没有出现溢出错误

**Comment by rufengsuixing** [comment]
有没可能是这个导致的,我找不到1.0.0的openssl库于是用了这个代替
ln -s ./libssl.so.1.0.2 ./libssl.so.1.0.0
ln -s ./libcrypto.so.1.0.2 ./libcrypto.so.1.0.0

**Comment by pymumu** [comment]
应该不会有关系，把prefetch关闭呢？

**Comment by NV3S** [comment]
https://github.com/Dreamacro/clash/issues/140
遇到了可能类似的问题，发生问题时候，cache-size从512->1024，运行了3个小时候左右出现了问题。

**Comment by NV3S** [comment]
> ## [Dreamacro/clash#140](https://github.com/Dreamacro/clash/issues/140)
> 遇到了可能类似的问题，发生问题时候，cache-size从512->1024，运行了3个小时候左右出现了问题。
> 查询windows文档[https://kb.vmware.com/articleview?docid=1003292&lang=zh_CN]发现报错可以用netstat -nao | find /i "estab" /c查看连接总数（最大限制2000个），打算重现下。

后来重现了，看smartdns的debug日志还在正常解析，但wsl的宿主系统已经报socket满了。
https://github.com/Dreamacro/clash/issues/140#issuecomment-475145837 clash的开发者回复
我还没试把prefetch关了看看，不知道 @rufengsuixing 试了没有

**Comment by pymumu** [comment]
@NV3S
出问题的时候，到WSL系统里面，看一下smartdns的文件句柄数。

先ps看一下smartdns的pid。
再ls /proc/[pid]/fd/ -l

**Comment by NV3S** [comment]
> @NV3S
> 出问题的时候，到WSL系统里面，看一下smartdns的文件句柄数。
> 
> 1. 查一下WSL中smartdns是否有句柄泄漏。
> 
> ```
> 先ps看一下smartdns的pid。
> 再ls /proc/[pid]/fd/ -l
> ```
> 1. 在windows里面执行netstat看一下数量最多的连接是什么
> 
> ```shell
> netstat
> ```
> 
> 3.如果上面都没找到问题，再看一下下面的工具：
> 如果目录下面文件句柄数量不多，但windows还是报资源不足的话。
> 到任务管理器里面->性能->打开资源监视器。
> 到网络里面，看一下那个服务占用了文件句柄数。

好的 我把配置环境恢复了重新一下抓一下看看，然后来更新

**Comment by NV3S** [comment]
重现问题后，看了wsl句柄如下：
`sean@SEAN-X1-Carbon:~$ sudo ls /proc/12/fd/ -l
total 0
lrwx------ 1 root root 0 Mar 26 14:36 0 -> /dev/null
lrwx------ 1 root root 0 Mar 26 14:36 1 -> /dev/null
lrwx------ 1 root root 0 Mar 26 14:36 10 -> 'socket:[24583]'
lrwx------ 1 root root 0 Mar 26 14:36 11 -> 'socket:[26532]'
lrwx------ 1 root root 0 Mar 26 14:37 12 -> 'socket:[26590]'
lrwx------ 1 root root 0 Mar 26 14:36 13 -> 'socket:[24244]'
lrwx------ 1 root root 0 Mar 26 14:37 14 -> 'socket:[26539]'
lrwx------ 1 root root 0 Mar 26 14:36 15 -> 'socket:[22231]'
l-wx------ 1 root root 0 Mar 26 14:36 16 -> /var/log/smartdns.log
lrwx------ 1 root root 0 Mar 26 14:36 17 -> 'socket:[24720]'
lrwx------ 1 root root 0 Mar 26 14:37 18 -> 'socket:[26540]'
lrwx------ 1 root root 0 Mar 26 14:37 19 -> 'socket:[26553]'
lrwx------ 1 root root 0 Mar 26 14:36 2 -> /dev/null
lrwx------ 1 root root 0 Mar 26 14:37 20 -> 'socket:[26542]'
lrwx------ 1 root root 0 Mar 26 14:36 21 -> 'socket:[35]'
lrwx------ 1 root root 0 Mar 26 14:37 22 -> 'socket:[26613]'
lrwx------ 1 root root 0 Mar 26 14:36 23 -> 'socket:[26437]'
lrwx------ 1 root root 0 Mar 26 14:36 24 -> 'socket:[26440]'
lrwx------ 1 root root 0 Mar 26 14:36 3 -> /run/smartdns.pid
lrwx------ 1 root root 0 Mar 26 14:36 4 -> 'socket:[26531]'
l--------- 1 root root 0 Mar 26 14:36 5 -> 'anon_inode:[eventpoll]'
l--------- 1 root root 0 Mar 26 14:36 6 -> 'anon_inode:[eventpoll]'
lrwx------ 1 root root 0 Mar 26 14:36 7 -> 'socket:[22]'
l--------- 1 root root 0 Mar 26 14:36 8 -> 'anon_inode:[eventpoll]'
lrwx------ 1 root root 0 Mar 26 14:36 9 -> 'socket:[25392]'`

windows里，看资源监视器，网络的TCP连接里，发现smartdns进程开了很多端口去连接若干远程ip的80口
重启smartdns无果，重启了系统。

**Comment by NV3S** [comment]
我补一下我的配置
```

# dns server name, defaut is host name
# server-name, 
# example:
server-name sean_smartdns


# Include another configuration options
# conf-file [file]
conf-file blacklist-ip.conf

# dns server bind ip and port, default dns server port is 53.
# bind [IP]:port, udp server
# bind-tcp [IP]:port, tcp server
# example: 
#   IPV4: :53
#   IPV6  [::]:53
# bind-tcp [::]:53

bind [::]:53

# tcp connection idle timeout
# tcp-idle-time [second]

# dns cache size
# cache-size [number]
#   0: for no cache
cache-size 2048

# prefetch domain
# prefetch-domain [yes|no]
prefetch-domain yes

# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip/subnet]

# List of IPs that will be filtered when nameserver is configured -blacklist-ip parameter
# blacklist-ip [ip/subnet]

# List of IPs that will be ignored
# ignore-ip [ip/subnet]

# force AAAA query return SOA
# force-AAAA-SOA [yes|no]

# Enable IPV4, IPV6 dual stack IP optimization selection strategy
# dualstack-ip-selection-threshold [num] (0~1000)
# dualstack-ip-selection [yes|no]
dualstack-ip-selection no

# edns client subnet
# edns-client-subnet [ip/subnet]
# edns-client-subnet 192.168.1.1/24
# edns-client-subnet [8::8]/56

# ttl for all resource record
# rr-ttl: ttl for all record
# rr-ttl-min: minimum ttl for resource record
# rr-ttl-max: maximum ttl for resource record
# example:
# rr-ttl 600
rr-ttl-min 120
# rr-ttl-max 86400

# set log level
# log-level: [level], level=fatal, error, warn, notice, info, debug
# log-file: file path of log file.
# log-size: size of each log file, support k,m,g
# log-num: number of logs
log-level debug
# log-file /var/log/smartdns.log
# log-size 128k
# log-num 2

# dns audit
# audit-enable: enable or disable audit [yes|no]
# audit-enable yes
# audit-size size of each audit file, support k,m,g
# audit-file /var/log/smartdns-audit.log
# audit-size 128k
# audit-num 2

# remote udp dns server list
# server [IP]:[PORT] [-blacklist-ip] [-check-edns] [-group [group] ...] [-exclude-default-group]
# default port is 53
#   -blacklist-ip: filter result with blacklist ip
#   -check-edns: result must exist edns RR, or discard result.
#   -group [group]: set server to group, use with nameserver /domain/group.
#   -exclude-default-group: exclude this server from default group.
# server 8.8.8.8 -blacklist-ip -check-edns -group g1 -group g2
server 8.8.8.8 -check-edns
server 8.8.4.4 -check-edns
#server 1.1.1.1 -check-edns 
server 1.0.0.1 -check-edns
#server 9.9.9.9 -check-edns
server 149.112.112.112 -check-edns
server 208.67.220.220 -check-edns 
server 208.67.222.222 -check-edns
server 180.76.76.76 -check-edns -blacklist-ip
server 223.6.6.6 -blacklist-ip
server 114.114.114.114 -blacklist-ip
server 119.29.29.29 -blacklist-ip
server 1.2.4.8 -blacklist-ip


# remote tcp dns server list
# server-tcp [IP]:[PORT] [-blacklist-ip] [-group [group] ...] [-exclude-default-group]
# default port is 53
# server-tcp 8.8.8.8
# server-tcp 8.8.4.4
# server-tcp 114.114.114.114
# server-tcp 1.0.0.1
# server-tcp 208.67.222.123

# remote tls dns server list
# server-tls [IP]:[PORT] [-blacklist-ip] [-spki-pin [sha256-pin]] [-group [group] ...] [-exclude-default-group]
#   -spki-pin: TLS spki pin to verify.
# Get SKPI with this command:
#    echo | openssl s_client -connect '[ip]:853' | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
# default port is 853
server-tls 8.8.8.8
server-tls 8.8.4.4
server-tls 118.89.110.78
#server-tls 1.1.1.1
server-tls 1.0.0.1


# specific nameserver to domain
# nameserver /domain/[group|-]
# nameserver /www.example.com/office, Set the domain name to use the appropriate server group.
# nameserver /www.example.com/-, ignore this domain

# specific address to domain
# address /domain/[ip|-|-4|-6|#|#4|#6]
# address /www.example.com/1.2.3.4, return ip 1.2.3.4 to client
# address /www.example.com/-, ignore address, query from upstream, suffix 4, for ipv4, 6 for ipv6, none for all
# address /www.example.com/#, return SOA to client, suffix 4, for ipv4, 6 for ipv6, none for all

# enable ipset timeout by ttl feature
#ipset-timeout yes

# specific ipset to domain
# ipset /domain/[ipset|-]
# ipset /www.example.com/block, set ipset with ipset name of block 
# ipset /www.example.com/-, ignore this domain
```

**Comment by pymumu** [comment]
吧日志文件发一下看看。/var/log/smartdns.log
是正常使用的时候，这样的，还是断网后这样的？

**Comment by NV3S** [comment]
> 吧日志文件发一下看看。/var/log/smartdns.log
> 是正常使用的时候，这样的，还是断网后这样的？

抱歉，当时没存，现在我看刷掉了，如果再重现我补一下log。
https://github.com/pymumu/smartdns/issues/109#issuecomment-475153788
之前我看过日志，后台还在正常跑

**Comment by pymumu** [comment]
根据你查的链接情况，应该是tcp测速的时候，资源泄露。

所以，你出问题的时候，是什么时候？断网的时候？

**Comment by NV3S** [comment]
> 根据你查的链接情况，应该是tcp测速的时候，资源泄露。
> 
> 所以，你出问题的时候，是什么时候？断网的时候？

笔记本休眠恢复后，和题主说的一样
`**休眠之前一大堆**，因为查资料用了很多域名`

**Comment by pymumu** [comment]
那可能是因为你开启了域名预获取，休眠后，smartdns完全停止了。
机器唤醒后，大量域名需要prefetch，导致短时间内大量连接请求，
你配置了2000个cache，最大可能发送2000个请求。

请求太多，导致资源消耗完。

这里可能要做一个优化，发现时间变化太多，直接丢弃所有缓存不做检测。

**Comment by NV3S** [comment]
> 那可能是因为你开启了域名预获取，休眠后，smartdns完全停止了。
> 机器唤醒后，大量域名需要prefetch，导致短时间内大量连接请求，
> 你配置了2000个cache，最大可能发送2000个请求。
> 
> 请求太多，导致资源消耗完。
> 
> 这里可能要做一个优化，发现时间变化太多，直接丢弃所有缓存不做检测。

好的。不具备这个层面的知识，无法给出建议了，等优化版本测试。

**Comment by pymumu** [comment]
你可以先关闭prefetch功能在用用看。

**Comment by pymumu** [comment]
@NV3S @rufengsuixing 
Release 23增加了唤醒后，强制情况缓存，避免突发域名查询导致链接过多。
有空获取一下Release 23 验证下看看。

**Comment by NV3S** [comment]
今天获取更新了验证一下，配置里把prefetch开启，cache是512。

**Comment by pymumu** [comment]
还有问题再reopen issue。
