### ISSUE TITLE
lede版本1.2022.38-1，53端口，第二组上游DNS设置问题

### ISSUE THREAD

**Issue by fxljay** [pymumu/smartdns#1090]
lede版本1.2022.38-1，53端口，第二组上游DNS设置
tls://dns.google
tls://1dot1dot1dot1.cloudflare-dns.com
无法正常解析
设置8.8.8.8:853和1.1.1.1:853正常
是什么原因

**Comment by PikuZheng** [comment]
重复 #524 #567 #672 #857

**Comment by zxlhhyccc** [comment]
> lede版本1.2022.38-1，53端口，第二组上游DNS设置 tls://dns.google tls://1dot1dot1dot1.cloudflare-dns.com 无法正常解析 设置8.8.8.8:853和1.1.1.1:853正常 是什么原因

tls的格式错误
