### ISSUE TITLE
第二dns停用IPV6地址解析无效

### ISSUE THREAD

**Issue by ChenStormstout** [pymumu/smartdns#1091]
**问题现象**  
第二dns停用IPV6地址解析无效

**运行环境**
1. 固件型号  openwrt 5.15.69

2. 运营商  中国联通

3. smartdns来源以及版本 BleachWrt高大全自带

4. 涉及的配置(注意去除个人相关信息)

![image](https://user-images.githubusercontent.com/19796806/192588626-f5079ea2-ae20-48d1-af24-a40e7a8e8d9d.png)

**重现步骤**
1. 上游DNS配置。  
![image](https://user-images.githubusercontent.com/19796806/192588826-7d5c2b37-0ac7-4816-80de-6e6391ea2b80.png)

2. 访问的域名。  
www.google.com

**信息收集**  
![image](https://user-images.githubusercontent.com/19796806/192589087-aebe5ec1-6336-4c58-93ac-29756830573b.png)
/var/log/smartdns.log 仅ERROR等级，无有用信息。
同时注意到force_aaaa_soa同时影响主dns和第二dns

**Comment by PikuZheng** [comment]
能否测一下8月31日之前的版本（37.2.4或更早）是否也有此问题？

**Comment by pymumu** [comment]
用的版本uci和主程序配套的吗？
不用release的配套版本验证看看？

**Comment by PikuZheng** [comment]
> 用的版本uci和主程序配套的吗？ 不用release的配套版本验证看看？

> 旧版本无问题

8月31日的版本修改了 force_aaaa_soa 的行为，配置这个参数后实际是启用了 force-qtype-SOA 28。作为全局参数，第二dns服务器可能没有对seconddns_force_aaaa_soa 做正确处理。

**Comment by MilesPoupart** [comment]
这个问题有解决吗 近期也遇到了第二服务器停用IPv6但还能解析到v6地址的现象

**Comment by PikuZheng** [comment]
> 这个问题有解决吗 近期也遇到了第二服务器停用IPv6但还能解析到v6地址的现象

我这测试是正常的

**Comment by MilesPoupart** [comment]
> > 这个问题有解决吗 近期也遇到了第二服务器停用IPv6但还能解析到v6地址的现象
> 
> 我这测试是正常的

我的主要配置，环境是lean源码编译的openwrt
![image](https://user-images.githubusercontent.com/32707318/216503423-5505970c-6c8c-4d7b-bbdc-66cf18c7d07c.png)
部分DNS服务器的配置是
![image](https://user-images.githubusercontent.com/32707318/216504113-cd698845-b429-4c88-812b-eb4239b3f607.png)
smartdns版本用openwrt官方的38.1和本仓库release下载的40版本（升级后有重启系统）都尝试了
![image](https://user-images.githubusercontent.com/32707318/216503919-ecea2123-36f3-4d64-a19d-4e9ae1ba7eec.png)
向第二dns服务器查询google.com和api.telegram.com都有返回ipv6的结果，这个是正常的现象吗？或者如果想要第二服务器不解析ipv6这样配置是正确的吗？谢谢！

**Comment by pymumu** [comment]
发一下这个文件的内容：cat /var/etc/smartdns/smartdns.conf

**Comment by MilesPoupart** [comment]
> cat /var/etc/smartdns/smartdns.conf

$ cat /var/etc/smartdns/smartdns.conf
```
server-name China
prefetch-domain yes
serve-expired yes
cache-size 2048
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
force-qtype-SOA  65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind [::]:6053
bind-tcp [::]:6053
bind [::]:5335  -no-speed-check -group Overseas -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa -no-dualstack-selection -no-cache -force-aaaa-soa
server 223.5.5.5  -group China
server 223.6.6.6  -group China
server 180.76.76.76  -group China
server 101.226.4.6  -group China
server 218.30.118.6  -group China
server 123.125.81.6  -group China
server 140.207.198.6  -group China
server 114.114.114.114  -group China
server 114.114.115.115  -group China
server 119.29.29.29  -group China
server 1.2.4.8  -group China
server 210.28.129.251  -group China
server 210.28.129.252  -group China
server-tls 8.8.8.8  -group Overseas -exclude-default-group
server-tcp 8.8.8.8  -group Overseas -exclude-default-group
server-tcp 8.8.4.4  -group Overseas -exclude-default-group
server-tls 9.9.9.9  -group Overseas -exclude-default-group
server-tcp 208.67.222.222  -group Overseas -exclude-default-group
server-tls 208.67.222.222  -group Overseas -exclude-default-group
server-tcp 208.67.220.220  -group Overseas -exclude-default-group
server-tls 208.67.220.220  -group Overseas -exclude-default-group
server-tls 1.1.1.1  -group Overseas -exclude-default-group
server 221.131.143.69  -group China
server 112.4.0.55  -group China
domain-set -name domain-forwarding-list -file /etc/smartdns/domain-forwarding.list
domain-rules /domain-set:domain-forwarding-list/
domain-set -name domain-block-list -file /etc/smartdns/domain-block.list
domain-rules /domain-set:domain-block-list/ --address #
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
```

**Comment by pymumu** [comment]
这个规则`-no-rule-soa`和`-force-aaaa-soa`冲突。二选一吧。

**Comment by MilesPoupart** [comment]
> 这个规则`-no-rule-soa`和`-force-aaaa-soa`冲突。二选一吧。

问题解决了 感谢！

**Comment by PikuZheng** [comment]
> 我关闭了-no-rule-soa之后就无法访问外网了请问是为什么？

你有配置忽略规则形如 address /域名/#

**Comment by ZacharyRen77** [comment]
没有，可是我看上面的配置文件不也没有吗

**Comment by ZacharyRen77** [comment]
> > 我关闭了-no-rule-soa之后就无法访问外网了请问是为什么？
> 
> 你有配置忽略规则形如 address /域名/#

没有，可是我看上面配置的不也没有吗？
