### ISSUE TITLE
关于ping测速的疑问

### ISSUE THREAD

**Issue by wtfr-dot** [pymumu/smartdns#1093]
**问题现象**  
简要描述问题出现的现象
在不修改默认的测速模式下，不定时有来自于网关的失败ICMP包响应，修改默认测速模式，去除ping模式后不再出现。另外，去除ping测速后在解析的结果里同样有fastping测速，这正常吗？是因为上游服务器有udp查询的原因吗？
![QQ截图20220928130857](https://user-images.githubusercontent.com/81218740/192697155-dea7f6e9-6ea7-4468-89f9-b04c15385354.jpg)

**运行环境**
1. 固件型号  
基于lean的自编译固件
![QQ截图20220928133517](https://user-images.githubusercontent.com/81218740/192696039-87d82124-a63b-43f1-ba48-c0e89b13a34d.jpg)

2. 运营商  
中国联通，光猫桥接，pppoe公网ip
中国移动，光猫路由，DHCP获取局域网ip
3. smartdns来源以及版本
拉取最新comment编译

4. 涉及的配置(注意去除个人相关信息)
passwall启用了smartdns国内分流解析，国外解析指向路由器7913端口，passwall自动生成了passwall_proxy组，在smartdns配置的第二服务器中指定了这个组
![QQ截图20220928135122](https://user-images.githubusercontent.com/81218740/192698578-a887f7eb-6202-4893-abdd-a893e961ca4e.jpg)

![QQ截图20220928134150](https://user-images.githubusercontent.com/81218740/192697015-1b51708d-5fd3-4064-bf61-f0fe015541e2.jpg)
![QQ截图20220928133849](https://user-images.githubusercontent.com/81218740/192697711-d5f05bf6-2da5-4978-b3c1-1e18fd1e9908.jpg)
![QQ截图20220928132010](https://user-images.githubusercontent.com/81218740/192697794-1ab551c1-59fa-44d4-a680-f8ad0b80315d.jpg)
![QQ截图20220928132400](https://user-images.githubusercontent.com/81218740/192697831-586feb96-e129-4557-8c74-a3d2ef211ab6.jpg)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
无特定域名

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
请检查 response-mode 配置

**Comment by cncqcyc** [comment]
> 请检查 response-mode 配置



> 请检查 response-mode 配置

我将response-mode改为除firstping以为的另外两种模式，开启speed-check-mode ping,tcp:80,tcp:443，还是会出现来自网关192.168.100.1上ICMP3:0的错误信息，而且是同一秒内出现了20几条，只要将ping模式去掉错误信息就没有了

**Comment by PikuZheng** [comment]
response-mode 可以解释在 speed-check-mode none 时仍有ping的现象。但是现在我没理解上面的网络拓扑。192.168.100.1是哪个？看起来是smartdns的ping包到192.168.100.1后，被icmp prohibited了。如果这是个华为，请检查一下攻击防护的配置。1秒二十多条很可能是触发了。

**Comment by cncqcyc** [comment]
> response-mode 可以解释在 speed-check-mode none 时仍有ping的现象。但是现在我没理解上面的网络拓扑。192.168.100.1是哪个？看起来是smartdns的ping包到192.168.100.1后，被icmp prohibited了。如果这是个华为，请检查一下攻击防护的配置。1秒二十多条很可能是触发了。

192.168.100.1是路由器网关，我把wan口和lan口自定的dns服务器地址也指了到网关上，路由器是自编译x86软路由，防火墙设置如下：
![QQ截图20220928163328](https://user-images.githubusercontent.com/81218740/192730764-28de7131-f08b-4e99-99f9-dc8684f5a7ce.jpg)
![QQ截图20220928163448](https://user-images.githubusercontent.com/81218740/192730886-6d3fc2f7-3627-458c-bc88-53a4d137bc4d.jpg)

**Comment by cncqcyc** [comment]
> > 192.168.100.1是路由器网关
> 
> 192.168.100.1是这个x86路由器还是路由器的网关？

192.168.100.1是x86路由器网关，整个网络只有这一个软路由，其它无线路由器都是AP模式

**Comment by cncqcyc** [comment]
> > 192.168.100.1是路由器网关
> 
> 192.168.100.1是这个x86路由器还是路由器的网关？

我想我找到问题了，应该是zerotier这个组件引起的，把它停止运行就恢复正常了，感谢您的解答

**Comment by cncqcyc** [comment]
> 我想起来了，icmp type faild, 3:0 是断网了，后面 recv ping packet from 192.168.100.1 failed. 是断网位置，说明 192.168.100.1 上行接口路由丢失了

从错误信息来看是网络不可达，但是实际上网络都是通的，刚刚我想了一下是不是zerotier这个vpn引起的，然后把它停止运行后，错误信息消失了
