### ISSUE TITLE
MediaTek MT7620 SoC/MIPS 24KEc V5.0 无法安装smartdns IPK

### ISSUE THREAD

**Issue by speeedturtle** [pymumu/smartdns#11]
luci-app-smartdns.1.2018.08.07-0021.all.ipk  
smartdns.1.2018.08.07-0021.mipsel.ipk         
smartdns.1.2018.08.07-0021.mipsel_24kec_dsp.ipk

以上三个文件都尝试了下到本地安装，一律失败。

[YOUKU-L1 /opt/home/admin]# cat /proc/cpuinfo
system type             : MediaTek MT7620 SoC
processor               : 0
cpu model               : **MIPS 24KEc V5.0**
BogoMIPS                : 391.16
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
ASEs implemented        : mips16 dsp
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

[YOUKU-L1 /opt/home/admin]# wget https://github.com/pymumu/smartdns/releases/download/Beta8/smartdns.1.2018.0
8.07-0021.mipsel.ipk
Connecting to github.com (13.250.177.223:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.160.163:443)
smartdns.1.2018.08.0 100% |************************************************************| 55514   0:00:00 ETA
[YOUKU-L1 /opt/home/admin]# ls
smartdns.1.2018.08.07-0021.mipsel.ipk            v2ray-linux-mipsle.zip
smartdns.1.2018.08.07-0021.mipsel_24kec_dsp.ipk  v2ray-v3.33-linux-mipsle
[YOUKU-L1 /opt/home/admin]# opkg install smartdns.1.2018.08.07-0021.mipsel
Unknown package 'smartdns.1.2018.08.07-0021.mipsel'.
Collected errors:
 * opkg_install_cmd: Cannot install package smartdns.1.2018.08.07-0021.mipsel.
[YOUKU-L1 /opt/home/admin]# opkg install luci-app-smartdns.1.2018.08.07-0021.all.ipk
Collected errors:
 * wfopen: luci-app-smartdns.1.2018.08.07-0021.all.ipk: No such file or directory.
 * pkg_init_from_file: Failed to extract control file from luci-app-smartdns.1.2018.08.07-0021.all.ipk.
[YOUKU-L1 /opt/home/admin]# wget https://github.com/pymumu/smartdns/releases/download/Beta8/luci-app-smartdns
.1.2018.08.07-0021.all.ipk
Connecting to github.com (52.74.223.119:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.162.227:443)
luci-app-smartdns.1. 100% |************************************************************|  5039   0:00:00 ETA
[YOUKU-L1 /opt/home/admin]# opkg install luci-app-smartdns.1.2018.08.07-0021.all.ipk 
Installing luci-app-smartdns (1.2018.08.07-0021) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-smartdns:
 *      smartdns * 
 * opkg_install_cmd: Cannot install package luci-app-smartdns.
[YOUKU-L1 /opt/home/admin]# opkg update
Downloading http://bin.entware.net/mipselsf-k3.4/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
[YOUKU-L1 /opt/home/admin]# opkg upgrade
[YOUKU-L1 /opt/home/admin]# ls
luci-app-smartdns.1.2018.08.07-0021.all.ipk      v2ray-linux-mipsle.zip
smartdns.1.2018.08.07-0021.mipsel.ipk            v2ray-v3.33-linux-mipsle
smartdns.1.2018.08.07-0021.mipsel_24kec_dsp.ipk
[YOUKU-L1 /opt/home/admin]#

**Comment by pymumu** [comment]
根据你的日志，安装的步骤不正确，下载的版本也不正确。
选择哪个文件安装，请看帮助中的说明。
还有安装命令也请看帮助。
先安装smartdns，在安装luci-app-smartdns。

谢谢。

**Comment by speeedturtle** [comment]
1， smartdns.1.2018.08.07-0021.mipsel.ipk
2， smartdns.1.2018.08.07-0021.mipsel_24kec_dsp.ipk
3， luci-app-smartdns.1.2018.08.07-0021.all.ipk
以上3个文件都尝试过安装了，安装顺序从1到3。 装不上。

我用的是优酷路由宝L1，系统用荒野无灯改的华硕潘多拉。CPU如下。 
system type : MediaTek MT7620 SoC
processor : 0
cpu model : MIPS 24KEc V5.0

**Comment by pymumu** [comment]
你到软件包安装源那里看看你的配套的名字是哪个啊
具体步骤指导里写了

**Comment by pymumu** [comment]
你的日志里，只看到安装luci-app-smartdns
没看到安装smartdns

**Comment by pymumu** [comment]
详细按指导操作下吧
