### ISSUE TITLE
bind :53并不能只绑定ipv4的53，和[::]:53效果一致

### ISSUE THREAD

**Issue by 523860169** [pymumu/smartdns#110]
OpenWrt cc15.05.1，smartdns用的最新版，smartdns设置为默认的dns服务器，自带的dnsmasq设置了别的端口。
[具体配置](https://drive.google.com/open?id=1Md7daEDJOUAl6LRtL37oIMw12U-HJ5G-
)
无论是设置为`bind :53`还是`bind [::]:53`，ipv4和ipv6的dns都可用，且网络信息里都只能获取到ipv6的dns，无法发现ipv4的dns
![default](https://user-images.githubusercontent.com/6436073/53874220-ee324c80-403c-11e9-83e6-a33634396f19.png)
![default](https://user-images.githubusercontent.com/6436073/53874367-40736d80-403d-11e9-8bcf-bd8d8f074b87.png)
但是当dnsmasq设置为主dns（使用53端口），smartdns作为上游时（`bind :5353`），网络信息里ipv4和ipv6的dns却都能正常获取到
![default](https://user-images.githubusercontent.com/6436073/53874885-5b92ad00-403e-11e9-8237-14e3575d0324.png)

**Comment by pymumu** [comment]
dnsmasq修改端口后，会停止发送DNS信息，所以dnsmasq中要增加配置项
```
dhcp-option=lan,6,192.168.1.1
dhcp-option=lan,option6:23,[::]
```
lan，和IP地址根据你的实际情况配置。

**Comment by 523860169** [comment]
好了，谢谢
