### ISSUE TITLE
勾选“停用HTTPS地址解析”相关问题

### ISSUE THREAD

**Issue by bi4tms** [pymumu/smartdns#1100]
smartdns里面如果勾选“停用HTTPS地址解析”，DNS服务器中添加的“https://dns.google/dns-query”是否还起作用，需要删掉吗

**Comment by PikuZheng** [comment]
停用HTTPS地址解析 指 当客户端发送类型为65的dns请求时，直接向客户端答复soa。与上游配置无关。

**Comment by ywyha** [comment]
> 停用HTTPS地址解析 指 当客户端发送类型为65的dns请求时，直接向客户端答复soa。与上游配置无关。
请问大佬，这个设置勾选或者不勾选都是在什么场景下使用啊，能举下例子吗？
完全搞不懂解析本地主机名和停用HTTPS地址解析这两个设置的作用，我看是默认勾选的

**Comment by PikuZheng** [comment]
> 请问大佬，这个设置勾选或者不勾选都是在什么场景下使用啊，能举下例子吗？
> 完全搞不懂解析本地主机名和停用HTTPS地址解析这两个设置的作用，我看是默认勾选的


这要从IETF标准说起 https://datatracker.ietf.org/doc/draft-ietf-dnsop-svcb-https/00/?include_text=1 如果不能理解技术细节，建议保持默认值不要动
