### ISSUE TITLE
nslookup -querytype=ptr smartdns找不到，但是有解析日志，请问是设置成功了吗

### ISSUE THREAD

**Issue by crhope** [pymumu/smartdns#1103]
**问题现象**  
openwrt本机运行nslookup -querytype=ptr smartdns返回name=smartdns

路由器底下的win终端nslookup -querytype=ptr smartdns或者nslookup smartdns都返回找不到

但是开启audit-enable yes后，查看日志有解析请求记录的

那请问是设置开成功了吗？

**运行环境**
1. openwrt(bleach plus 20220914 @ OpenWrt R22.9.1 / LuCI Master (git-22.255.14339-1ee6726)  

2. 电信

3. smartdns来源以及版本   37.2-9

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
重复 #1083

nslookup -querytype=ptr 后面应该跟一个IP地址，或给定其他指针信息。参考 https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-set-querytype

>nslookup smartdns都返回找不到

什么是”返回找不到“？是找不到dns服务器还是找不到smartdns对应的ip？

**Comment by crhope** [comment]
> 

C:\Users\rayho>nslookup -querytype=ptr smartdns
服务器:  OpenWrt.lan
Address:  192.168.2.1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

**Comment by crhope** [comment]
> 重复 #1083
> 
> nslookup -querytype=ptr 后面应该跟一个IP地址，或给定其他指针信息。参考 https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-set-querytype
> 
> > nslookup smartdns都返回找不到
> 
> 什么是”返回找不到“？是找不到dns服务器还是找不到smartdns对应的ip？

C:\Users\rayho>nslookup -querytype=ptr smartdns
服务器:  OpenWrt.lan
Address:  192.168.2.1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

**Comment by crhope** [comment]
> 重复 #1083
> 
> nslookup -querytype=ptr 后面应该跟一个IP地址，或给定其他指针信息。参考 https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-set-querytype
> 
> > nslookup smartdns都返回找不到
> 
> 什么是”返回找不到“？是找不到dns服务器还是找不到smartdns对应的ip？

C:\Users\rayho>nslookup -querytype=ptr smartdns
服务器:  OpenWrt.lan
Address:  192.168.2.1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

C:\Users\rayho>nslookup smartdns
服务器:  OpenWrt.lan
Address:  192.168.2.1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

**Comment by PikuZheng** [comment]
Windows会给DNS请求附加默认域的DNS后缀。nslookup smartdns命令实际行为是 nslook smartdns.lan。

在Windows上使用nslookup查询主机名称，请在主机名后面加“.”。详情请参考MSDN的说明。

**Comment by crhope** [comment]
所以请问如果日志中能看到有解析的请求记录，是否就可以判断smartdns已经生效设置成功了？

**Comment by PikuZheng** [comment]
> 所以请问如果日志中能看到有解析的请求记录，是否就可以判断smartdns已经生效设置成功了？

只能证明smartdns正确运行。还需要证实客户端正确配置了使用smartdns。

**Comment by crhope** [comment]
> > 所以请问如果日志中能看到有解析的请求记录，是否就可以判断smartdns已经生效设置成功了？
> 
> 只能证明smartdns正确运行。还需要证实客户端正确配置了使用smartdns。

这就奇怪了，保证路由器下其他终端没有访问A网站的情况下，win终端访问A网站在日志当中能看到日志请求的，但是nslookup -querytype=ptr smartdns依然是找不到 smartdns: Non-existent domain

**Comment by crhope** [comment]
之前直接在openwrt运行nslookup -querytype=ptr smartdns是能返回smartdns        name = smartdns.

**Comment by crhope** [comment]
真的很奇怪，之前直接在openwrt运行nslookup -querytype=ptr smartdns是能返回smartdns name = smartdns.只是在路由器下的win终端返回smartdns: Non-existent domain，但是smartdns-audit.log上能看到win终端的请求解析日志
在什么设置都没有更改的情况下重启路由器后，在openwrt后台运行nslookup -querytype=ptr smartdns也返回返回smartdns: Non-existent domain了，但是查看smartdns-audit.log依然能看到win的请求解析日志

**Comment by PikuZheng** [comment]
再说一遍，Linux上nslookup和Windows上nslookup是两个不同的命令，虽然命令相同，但行为不同。不应该直接比较二者的结果
