### ISSUE TITLE
升级38版本后，自定义设置 anti-ad-for-smartdns.conf 广告过滤失效

### ISSUE THREAD

**Issue by zsbstephen** [pymumu/smartdns#1105]
RT，广告过滤是借助隔壁家这个项目实现的：
https://github.com/privacy-protection-tools/anti-AD

37和之前的版本在 /etc/smartdns/custom.conf 里面添加 conf-file /etc/smartdns/anti-ad-for-smartdns.conf 无效，在luci网页页面将conf-file /etc/smartdns/anti-ad-for-smartdns.conf添加到自定义设置才生效，实测可以屏蔽广告域名响应。但是升级38版本之后就失效了，重启openwrt或者smartdns还是失效。

**Comment by zsbstephen** [comment]
Update: 卸载smartdns并重新安装后，问题解决。

**Comment by zsbstephen** [comment]
Update：更新之后，需要进去luci设置界面，去掉“域名预加载”、“缓存过期服务”、“缓存过期服务”、“自动设置Dnsmasq” 4个选项勾选，点保存&应用，再重新勾选上，然后重新点保存&应用，广告过滤方才生效。

**Comment by PikuZheng** [comment]
js版的luci好像需要保存两次才能生效

**Comment by jkle112** [comment]
之前用SMARTDNS來過濾廣告和DNS分流，都出現了問題。
廣告過濾文件包過大，運行出問題，有停止的風險，或者速度變慢，或者內存消耗更大。
DNS分流是自己按照官方要求編寫規則，但是體積達到一定程度，界面就顯示空白了。
最後還是放棄，用其他方法了。
