### ISSUE TITLE
EDNS问题求解

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#1108]
> server-https https://dns.google/dns-query -group b -check-edns
> edns-client-subnet 大阪IP

emmmm，更新了新版，听闻支持EDNS了，对于我这种使用科学又买便宜小鸡（广播IP）的人简直福音

还没测，先提个问题

目前小鸡有大阪、东京、洛杉矶，三个都是广播IP不是原生，google的dns识别没错，但是我还配置了别的上游服务器，比如opendns似乎就把东京的小鸡识别成俄罗斯，目前设备里配置默认大阪，如果大阪挂了会自动切，这时候不太好整了就，我已经配置了edns到大阪，如果切到TYO了还好，如果切到LA了，那返回的IP一定就绕路……

国外的上游我也用了几个，包括谷歌，CF，IBM，OPENDNS

我现在能想到的解决方案，除了在设备里剔除LA（毕竟大阪和TYO也算比较近…），似乎没其他了

有大佬指路吗？各位大佬都是什么解决方案啊？花钱买99.9999%在线率小鸡这种方案就不要提了，谢谢啊

**Comment by PikuZheng** [comment]
-check-edns 需要在编译时额外指定参数，参考 #1060

我edns指定了一个oracle tokyo的（与vps网段无关）。实际使用发现google指向印度，github指向日本，cloudflare指向欧洲。至于绕路的问题，绕美到日或绕日到美都是多了几十毫秒，对我实际使用没有影响。

**Comment by qwerttvv** [comment]
> -check-edns 需要在编译时额外指定参数，参考 #1060
> 
> 我edns指定了一个oracle tokyo的（与vps网段无关）。实际使用发现google指向印度，github指向日本，cloudflare指向欧洲。至于绕路的问题，绕美到日或绕日到美都是多了几十毫秒，对我实际使用没有影响。

多谢大佬指点，那我就先不折腾了就

等啥时候实在没事干又手痒再说了
