### ISSUE TITLE
还是有极小机率出现瞬间就打不开域名的情况

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#111]
smartdns.1.2019.03.02-1141.mipsel_1004kc_dsp

[smartdns.zip](https://github.com/pymumu/smartdns/files/2942723/smartdns.zip)

刚打开“hot.cnbeta.com”时FF马上就出现“找不到服务器”了。
不限上边CB的域名，也不只这一次，只是这次刚好开了debug日志后就来了。

**Comment by pymumu** [comment]
你配置的上游，UDP服务部分返回了Server Failure, 这个错误表示服务器异常。部分超时。
TLS因为建立连接耗时，虽然获取到结果，但是没来得及返回。

发一下你的配置信息吧。

可能你的网络有DNS劫持。你可以配置一些非标端口的服务器。

**Comment by ztjal** [comment]
[conf.zip](https://github.com/pymumu/smartdns/files/2944785/conf.zip)

我全部都用非标准端口的。
看了你的解释，我有个想法，增加个“等待时间”设定吧，默认就是原来的1秒，让用户自己设定，可能2-3秒体验更好。

**Comment by pymumu** [comment]
用处不大，windows默认情况就是1s超时。

你的问题应该是上游为什么会返回Server Failure.
是否可能网络质量不佳？

**Comment by ztjal** [comment]
网络质量问题不大，电信百兆，能满速的。
这种情况出现时都是UDP的集体挂掉，感觉主机那边肯定是没事的，问题就是中间了，这个不是我们能解决的事了，放弃。
现在只好加多个233666开反回答伪造吧。
又想到问题，增加一个fallback专用的设定，就像dnscrypt-proxy的fallback_resolver那样，这个fallback就别走优选流程了，普通地传答数据就好了。

**Comment by pymumu** [comment]
是不是电信强制pppoe断开导致，你看看那段时间有没有pppoe重新连接的日志

**Comment by ztjal** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/2948182/smartdns.zip)

再传个日志，感觉是程序的问题，“bbs.pcbeta.com”解释失败刷了好几次才正常，但“同时”其它都解释成功了。

**Comment by pymumu** [comment]
你不要用5353，换一个端口看看

**Comment by Auska** [comment]
[smartdns.log](https://github.com/pymumu/smartdns/files/2948278/smartdns.log)
有时候解析也会出现同时超时 感觉很奇怪

**Comment by pymumu** [comment]
@Auska 
你这个是TCP的DNS连接超时，应该某几个DNS你的网络链接不稳定。

**Comment by pymumu** [comment]
@ztjal 
[smartdns.1.2019.03.09-2120.mipsel_1004kc_dsp.ipk.zip](https://github.com/pymumu/smartdns/files/2948408/smartdns.1.2019.03.09-2120.mipsel_1004kc_dsp.ipk.zip)

增加了重试机制，你测试下看看。

**Comment by pymumu** [comment]
@ztjal 增加了重试机制，验证下看看。
[smartdns.1.2019.03.09-2214.mipsel_1004kc_dsp.ipk.zip](https://github.com/pymumu/smartdns/files/2948465/smartdns.1.2019.03.09-2214.mipsel_1004kc_dsp.ipk.zip)

**Comment by ztjal** [comment]
在用0309，这次用了6个非标准的UDP和5个TLS

**Comment by ghostry** [comment]
我这网络特别差，
我用dig同时从上游和smartDNS请求解析。
8.8.8.8可以在1394ms返回结果，
smartDNS虽然返回的很快，大概400+MS，但是都是空值，重试多次，直到几秒后才能取到解析，取到解析的话Query time: 0 msec。
是否可以在某个时间，如果不能取到测速结果，就先返回一个解析，ttl设置小点，等测速结果出现了再修改。

**Comment by pymumu** [comment]
@ghostry 
目前版本DNS请求最大超时时间500ms左右，下个版本增加重试机制，1500ms超时。

**Comment by ghostry** [comment]
```
$ dig blog.ghostry.cn @192.168.1.1 -p 6053

; <<>> DiG 9.11.3-1ubuntu1.5-Ubuntu <<>> blog.ghostry.cn @192.168.1.1 -p 6053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 53022
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;blog.ghostry.cn.		IN	A

;; Query time: 1592 msec
;; SERVER: 192.168.1.1#6053(192.168.1.1)
;; WHEN: Sat Mar 16 08:22:58 CST 2019
;; MSG SIZE  rcvd: 33

$ dig blog.ghostry.cn @192.168.1.1 -p 6053

; <<>> DiG 9.11.3-1ubuntu1.5-Ubuntu <<>> blog.ghostry.cn @192.168.1.1 -p 6053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26239
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;blog.ghostry.cn.		IN	A

;; ANSWER SECTION:
blog.ghostry.cn.	300	IN	A	47.52.253.230

;; Query time: 1574 msec
;; SERVER: 192.168.1.1#6053(192.168.1.1)
;; WHEN: Sat Mar 16 08:23:06 CST 2019
;; MSG SIZE  rcvd: 64

```
3.15版，测试了6个域名，4个可以一次解析，2个需要两次。
配置了10个上游dns。

**Comment by pymumu** [comment]
现在最大1500ms，超过就失败了，
感觉你的网络时延特别大，这么多上游都响应不及时。

**Comment by ghostry** [comment]
是延时特别大,我ping了三十几个dns,延时在1000到3000之间.1800左右的比较多.

**Comment by fonlan** [comment]
你这时延也太夸张了吧，是不是开了全局科学上网导致所有流量都先到国外绕一圈啊？

**Comment by ghostry** [comment]
> 你这时延也太夸张了吧，是不是开了全局科学上网导致所有流量都先到国外绕一圈啊？

不,这个运营商的问题,叫什么sky的.

**Comment by ztjal** [comment]
从0309到0315感觉不错，没再出现过了，先close吧。
