### ISSUE TITLE
js版本修改ttl值和缓存大小，保存并应用出现RPC错误：

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1110]
![image](https://user-images.githubusercontent.com/45259624/194567894-407b8470-ac1f-4732-ab58-bda7dd86d663.png)

![image](https://user-images.githubusercontent.com/45259624/194569136-941f0ae8-a38a-4031-8cc9-3fb91a47c6d7.png)

**Comment by PikuZheng** [comment]
证实存在此问题，但是点击”保存并应用“可以正确配置 @pymumu

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/commit/6c800ea12fd759dcdbdc88aa0a7d1615ce8a9145
