### ISSUE TITLE
如何固定访问appstore的DNS为223.5.5.5

### ISSUE THREAD

**Issue by snoopytl** [pymumu/smartdns#1112]
我是使用openclash和smartdns一起使用的，openclash 代理走的是127.0.0.1#7053，对应我smartdns的国外分组，127.0.0.1#6053，对应的是国内的分组
问题：我使用ios设备下载缓慢，将自动dns改成手动的223.5.5.5后下载速度才正常
请问如何设置只允许223.5.5.5来负责解析访问appstore的流量呢

**Comment by PikuZheng** [comment]
53端口谁负责的？配置规则将**以下后缀**的域名转发到国内组（127.0.0.1#6053
```
.mzstatic.com
.akadns.net
.apple.com
.cdn-apple.com
.aaplimg.com
.apple-mapkit.com
.edgekey.net
```

**Comment by snoopytl** [comment]
53端口是openwrt在用，在openwrt的dhcp/dns选项里，DNS转发到127.0.0.1#7874（这个端口是openclash的），然后openclash里是自动设置 Dnsmasq 的上游服务器，openclash 代理走的是127.0.0.1#7053，对应我smartdns的国外分组，127.0.0.1#6053，对应的是国内的分组

**Comment by cresky-github** [comment]
> 我是使用openclash和smartdns一起使用的，openclash 代理走的是127.0.0.1#7053，对应我smartdns的国外分组，127.0.0.1#6053，对应的是国内的分组 问题：我使用ios设备下载缓慢，将自动dns改成手动的223.5.5.5后下载速度才正常 请问如何设置只允许223.5.5.5来负责解析访问appstore的流量呢


域名 和 DNS 的组名相同，并排除默认组。

就行了

**Comment by PikuZheng** [comment]
> openclash里是自动设置 Dnsmasq 的上游服务器，openclash 代理走的是127.0.0.1#7053，对应我smartdns的国外分组，127.0.0.1#6053，对应的是国内的分组

那在clash做规则，把这些域名指向国内分组。

用smartdns处理也可以，但是不确定这几个域名会被clash分到哪个组。理论上在国外组添加域名规则，把这些域名用223.5.5.5作为上游也可以
