### ISSUE TITLE
新版已经支持 dnsmasq-lease-file ，但还少了定义本地域名后缀的小功能

### ISSUE THREAD

**Issue by mokeyish** [pymumu/smartdns#1113]
smartdns 非常棒的一个软件

**需求应用场景**
新版已经支持 dnsmasq-lease-file ，但还少了定义本地域名后缀的小功能，如图

<img width="745" alt="图片" src="https://user-images.githubusercontent.com/16131917/194698234-8a2e2c30-3d7b-4881-a460-b897c19c3ae7.png">

**建议的方案**
实现上述场景建议的方案。

**Comment by PikuZheng** [comment]
重复 #861
