### ISSUE TITLE
新版本 luci-i18n-smartdns-zh-cn 报错

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1114]
安装提示 uci :pares error (EOF with unterminated ') at line 23,byte 27

应该是格式错误

**Comment by PikuZheng** [comment]
自己编译的？考虑 po2lmo 转换出错了

**Comment by lalasou** [comment]
不是啊  拉的官方源里面的啊
https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/
这里的 我昨晚刚安装的
@pymumu

**Comment by lalasou** [comment]
并且 自定义配置 还有 黑名单如果内容多了（也不是太多 ）  会保存不了

**Comment by PikuZheng** [comment]
我刚在线安装的 没发现问题 黑名单多 是有多少行？

**Comment by lalasou** [comment]
> 我刚在线安装的 没发现问题 黑名单多 是有多少行？



刚刚我又试了一遍  看图片

![image](https://user-images.githubusercontent.com/7440313/194749928-c682d02d-5076-4600-93c9-1a8db57bc1d7.png)

**Comment by PikuZheng** [comment]
。。。这个是安装成功后才出现的提示啊，哪个uci配置文件的问题吧，需要逐个检查 /etc/config/ 里的文件，看哪个的23行有个单引号

**Comment by pymumu** [comment]
```
for x in /etc/config/*; do uci show "${x##*/}" >/dev/null || echo "$x is broken"; done
```
看看那个文件错了。

**Comment by lalasou** [comment]
膜拜大佬
