### ISSUE TITLE
能否过滤掉一些ping值太低的结果？

### ISSUE THREAD

**Issue by pexcn** [pymumu/smartdns#1116]
**需求应用场景**
如果局域网设置了只要不是国内IP就走透明代理，而且DNS都返回了国外IP，这样用tcp测速的时候，可能是碰到了透明代理网关，就会测得1ms

**建议的方案**
希望可以加一个选项，作用是当测速的IP延迟低于某个值的时候，丢弃这些结果。默认值2ms

**Comment by pymumu** [comment]
```
正在 Ping ins-r23tsuuf.ias.tencent-cloud.net [121.14.77.221] 具有 32 字节的数据:
来自 121.14.77.221 的回复: 字节=32 时间=2ms TTL=55
```

我这里腾讯都是2ms了。要看看其他方案。

**Comment by pexcn** [comment]
> 我这里腾讯都是2ms了。要看看其他方案。

@pymumu 额，那默认就不开启这个特性？我的意思是能否加一个选项，可以让用户设置一个毫秒数的值，如果测出来的延迟低于这个值，就丢弃这个结果

**Comment by pexcn** [comment]
不过刚刚又想了一下，似乎用不太到这个选项，主要是 smartdns 我只用来作为 chinadns-ng 的上游😄

**Comment by yyysuo** [comment]
如果smartdns作为有缓存的本地上游dns的下游的话，这样就没法用了。
