### ISSUE TITLE
关于 speed-check-mode 默认值的疑问

### ISSUE THREAD

**Issue by pexcn** [pymumu/smartdns#1118]
README 中显示 `speed-check-mode` 的默认值是 `无`，而我开启详细日志后发现输出的日志和手动设置为以下值的输出是一样的
```ini
speed-check-mode ping
```
所以默认值是这样吗？
```ini
speed-check-mode ping,tcp:80,tcp:443
```
参考的是
https://github.com/pymumu/smartdns/blob/8523f26c621d535ac1f13970196ef53b4483fcdf/src/dns_conf.c#L89-L94

如果是的话，能否更新一下 README 呢？

**Comment by pexcn** [comment]
另外根据作者的经验，是推荐优先 ICMP 测速还是 TCP 测速呢？国内的网站是否有比较多禁 ping 的网站呢？

**Comment by pymumu** [comment]
我这边设备是华硕路由器，用的都是默认值，只调整了过期缓存时长，和开启了prefetch。
一般情况默认应该是足够了，不用特别的调整。

readme后面刷新。

**Comment by openips** [comment]
tcp 443 80更准确

**Comment by yyysuo** [comment]
我起用用first ping

**Comment by PikuZheng** [comment]
speed-check-mode 和 response-mode 都在影响测速。比如同时设 speed-check-mode none 和 response-mode first-ping ，最终结果是不是相当于 speed-check-mode ping ？希望更新文档时能同时说明一下 @pymumu

**Comment by openips** [comment]
我用的是 response-mode fastest-ip

**Comment by itKelis** [comment]
我觉得使用tcp ping的解析速度没有icmp快

**Comment by yuxuan0107** [comment]
> 

我也是有同样的感觉

**Comment by yuxuan0107** [comment]
> 
我也有同样感觉

**Comment by yuxuan0107** [comment]
> 我觉得使用tcp ping的解析速度没有icmp快

我也有同样感觉
