### ISSUE TITLE
dnsmasq-lease-file 指令生效不及时，基本上要等一分钟以后

### ISSUE THREAD

**Issue by lxf1992521** [pymumu/smartdns#1119]
**问题现象**  
dnsmasq-lease-file 指令生效不及时，当 /var/lib/misc/dnsmasq.leases 文件有改动后，差不多要等一分钟后，对应的 DHCP 的主机名解析才会生效

**运行环境**
1. 固件型号  
Ubuntu 16.04 x86_64
dnsmasq 2.79

2. 运营商  
不涉及

3. smartdns来源以及版本
smartdns 1.2022.09.25-1116
下载自 github releases 页面

4. 涉及的配置(注意去除个人相关信息)
cache-size 10000
cache-persist no
tcp-idle-time 30
speed-check-mode none
force-AAAA-SOA yes
force-qtype-SOA 65
prefetch-domain yes
serve-expired yes
serve-expired-ttl 0
dnsmasq-lease-file /var/lib/misc/dnsmasq.leases
dualstack-ip-selection no
bind 127.0.0.1:53
server-https https://223.5.5.5/dns-query

**Comment by PikuZheng** [comment]
dnsmasq-lease-file 是每半分钟读取一次 并不是实时的

**Comment by lxf1992521** [comment]
了解了，谢谢作者的辛苦创作！

不过希望还是能升级为实时监听生效，用户体验更好些

**Comment by zxlhhyccc** [comment]
> 4\. /var/lib/misc/dnsmasq.leases

我路由上路径/var/lib/misc/dnsmasq.leases都没有dnsmasq.leases这个文件。。。
