### ISSUE TITLE
升级koolshare的op 2.3.0后无法启动

### ISSUE THREAD

**Issue by alepennyq** [pymumu/smartdns#112]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
koolshare的openwrt 2.3.0
2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
ldd /usr/sbin/smartdns看一下吧。

可能是openssl不兼容。

**Comment by alepennyq** [comment]
/lib/ld-musl-x86_64.so.1 (0x7f7d5c1e2000)
Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/sbin/smartdns)
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/sbin/smartdns)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f7d5c1ce000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f7d5c1e2000)
Error relocating /usr/sbin/smartdns: X509_NAME_get_text_by_NID: symbol not found
Error relocating /usr/sbin/smartdns: SSL_get_error: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_write: symbol not found
Error relocating /usr/sbin/smartdns: SSLv23_client_method: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_malloc: symbol not found
Error relocating /usr/sbin/smartdns: SSL_free: symbol not found
Error relocating /usr/sbin/smartdns: EVP_DecodeBlock: symbol not found
Error relocating /usr/sbin/smartdns: SSL_set_fd: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_num_locks: symbol not found
Error relocating /usr/sbin/smartdns: X509_get_subject_name: symbol not found
Error relocating /usr/sbin/smartdns: ERR_reason_error_string: symbol not found
Error relocating /usr/sbin/smartdns: SHA256_Init: symbol not found
Error relocating /usr/sbin/smartdns: OPENSSL_cleanse: symbol not found
Error relocating /usr/sbin/smartdns: SSL_library_init: symbol not found
Error relocating /usr/sbin/smartdns: SSL_get1_session: symbol not found
Error relocating /usr/sbin/smartdns: SSL_read: symbol not found
Error relocating /usr/sbin/smartdns: SSL_SESSION_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_new: symbol not found
Error relocating /usr/sbin/smartdns: OPENSSL_add_all_algorithms_noconf: symbol not found
Error relocating /usr/sbin/smartdns: SSL_shutdown: symbol not found
Error relocating /usr/sbin/smartdns: EVP_cleanup: symbol not found
Error relocating /usr/sbin/smartdns: ERR_free_strings: symbol not found
Error relocating /usr/sbin/smartdns: SSL_CTX_new: symbol not found
Error relocating /usr/sbin/smartdns: SSL_get_peer_certificate: symbol not found
Error relocating /usr/sbin/smartdns: SSL_ctrl: symbol not found
Error relocating /usr/sbin/smartdns: i2d_X509_PUBKEY: symbol not found
Error relocating /usr/sbin/smartdns: SHA256_Final: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_set_id_callback: symbol not found
Error relocating /usr/sbin/smartdns: X509_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_connect: symbol not found
Error relocating /usr/sbin/smartdns: SSL_CTX_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_load_error_strings: symbol not found
Error relocating /usr/sbin/smartdns: SSL_set_session: symbol not found
Error relocating /usr/sbin/smartdns: SHA256_Update: symbol not found
Error relocating /usr/sbin/smartdns: ERR_get_error: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_set_locking_callback: symbol not found

**Comment by pymumu** [comment]
缺少openssl 1.0.0的库，你需要安装1.0.0的库。

**Comment by alepennyq** [comment]
具体怎么安装？麻烦告知，谢谢

**Comment by RodmanWang** [comment]
请问openssl 1.0.0的库哪里可以下载，我搜了下找不到，谢谢

**Comment by cjameslynn** [comment]
看来我还是不升级了

**Comment by alepennyq** [comment]
包名是libopenssl吗？

**Comment by pymumu** [comment]
libssl

**Comment by fonlan** [comment]
有没有可能做成自动检测的？系统里装的是什么版本就调用什么版本的？

**Comment by pymumu** [comment]
@fonlan 
理论可以，curl命令获取github上的下载信息， opkg获取架构，两个匹配下载。

但curl命令，并不是路由器默认都带的，所以可能即使做了，也不能全部用，反而更加麻烦。

**Comment by fonlan** [comment]
> @fonlan
> 理论可以，curl命令获取github上的下载信息， opkg获取架构，两个匹配下载。
> 
> 但curl命令，并不是路由器默认都带的，所以可能即使做了，也不能全部用，反而更加麻烦。

我的意思是自动检测已安装的openssl是1.0.0的还是1.0.2的从而实现自动加载对应的版本？或者当找不到libssl.so.1.0.0但是找到了libssl.so.1.0.2是否可以通过创建软连接的方式解决？

**Comment by pymumu** [comment]
@alepennyq @fonlan @cjameslynn @RodmanWang 
一般都是配套固件来编译smartdns的，openwrt目前主干版本目前是libssl1.0.0的库，所以smartdns用的也是1.0.0的库。
1.1.1的库一般是不能用在1.0.0上，可能不兼容，不建议降级使用。
但1.0.x应该是通用的，可以创建符号链接来使用。

另外，koolshare可能升级了比较新的版本，从而导致不能用，可以看一下koolshare的软件库里面有没有libssl 1.0.0的库。

如果没有的话，可以到这里下载安装尝试。
```
https://downloads.openwrt.org/releases/18.06.2/packages/x86_64/base/libopenssl_1.0.2q-1_x86_64.ipk
```

**Comment by cjameslynn** [comment]
> https://downloads.openwrt.org/releases/18.06.2/packages/x86_64/base/libopenssl_1.0.2q-1_x86_64.ipk

正在执行软件包管理器
错误
Collected errors:
 * wfopen: https://downloads.openwrt.org/releases/18.06.2/packages/x86_64/base/libopenssl_1.0.2q-1_x86_64.ipk: No such file or directory.
 * pkg_init_from_file: Failed to extract control file from https://downloads.openwrt.org/releases/18.06.2/packages/x86_64/base/libopenssl_1.0.2q-1_x86_64.ipk.
opkg install 命令失败，代码 255。

**Comment by yuhuangniu** [comment]
> @alepennyq @fonlan @cjameslynn @RodmanWang
> 一般都是配套固件来编译smartdns的，openwrt目前主干版本是libssl1.0.0的库，所以smartdns用的也是1.0.0的库。
> 1.1.1的库一般是不能用在1.0.0上，可能不兼容，不建议降级使用。
> 但1.0.x应该是通用的，可以创建符号链接来使用。
> 
> 另外，koolshare可能升级了比较新的版本，从而导致不能用，可以看一下koolshare的软件库里面有没有libssl 1.0.0的库。
> 
> 如果没有的话，可以到这里下载安装尝试。
> 
> ```
> https://downloads.openwrt.org/releases/18.06.2/packages/x86_64/base/libopenssl_1.0.2q-1_x86_64.ipk
> ```

你上面给的下载地址已经失效，我又找了一个新地址
`https://downloads.openwrt.org/releases/18.06.1/packages/x86_64/base/libopenssl_1.0.2r-1_x86_64.ipk`
麻烦请在本项目的release 页面也把新地址替换过去。
