### ISSUE TITLE
使用新版不会用了...怎么设置国内网站返回都是多个ip

### ISSUE THREAD

**Issue by smdx** [pymumu/smartdns#1122]
**问题现象**  
使用新版怎么设置国内网站返回都是多个ip，国外能正常返回单个ip。请问要怎么设置？谢谢

**运行环境**
1. 固件型号  
OpenWrt R22.10.10 / LuCI Master (git-22.279.28429-0cb5c5c)

2. 运营商  
中国电信

3. smartdns来源以及版本
1.2022.38-1

**重现步骤**
1. 上游DNS配置。  
![Screenshot-2022-10-15_211830](https://user-images.githubusercontent.com/9279217/195988511-cfb7885e-c8d0-4356-aefb-8a9ef2e3e79f.jpg)
![Screenshot-2022-10-15_211920](https://user-images.githubusercontent.com/9279217/195988553-4b74b7ae-faca-4e02-8201-94c5363724af.jpg)

2. 访问的域名。  
www.baidu.com
www.163.com
www.google.com

![Screenshot-2022-10-15_211408](https://user-images.githubusercontent.com/9279217/195988958-be7008c7-638d-4a6b-a01f-a8cbf6b13841.jpg)

![Screenshot-2022-10-15_212313](https://user-images.githubusercontent.com/9279217/195988962-ec98e90a-6096-4682-91eb-25dbc09b6d6d.jpg)

设置端口为6053

![Screenshot-2022-10-15_213431](https://user-images.githubusercontent.com/9279217/195989298-49879f54-a8b6-440d-870f-1c6ad63f3af4.jpg)

![Screenshot-2022-10-15_213439](https://user-images.githubusercontent.com/9279217/195989301-bdf92848-01a9-4e64-894e-ee5dae501fea.jpg)

![Screenshot-2022-10-15_213452](https://user-images.githubusercontent.com/9279217/195989306-64cb404b-3783-4270-8d0a-f40b7f40b022.jpg)
![Screenshot-2022-10-15_213507](https://user-images.githubusercontent.com/9279217/195989311-7032673f-5885-4c60-ba7a-32e06c08c0db.jpg)

**Comment by zxlhhyccc** [comment]
> **问题现象** 使用新版怎么设置国内网站返回都是多个ip，国外能正常返回单个ip。请问要怎么设置？谢谢
> 
> **运行环境**
> 
> 1. 固件型号
>    OpenWrt R22.10.10 / LuCI Master (git-22.279.28429-0cb5c5c)
> 2. 运营商
>    中国电信
> 3. smartdns来源以及版本
>    1.2022.38-1
> 
> **重现步骤**
> 
> 1. 上游DNS配置。
>    ![Screenshot-2022-10-15_211830](https://user-images.githubusercontent.com/9279217/195988511-cfb7885e-c8d0-4356-aefb-8a9ef2e3e79f.jpg)
>    ![Screenshot-2022-10-15_211920](https://user-images.githubusercontent.com/9279217/195988553-4b74b7ae-faca-4e02-8201-94c5363724af.jpg)
> 2. 访问的域名。
>    [www.baidu.com](http://www.baidu.com)
>    [www.163.com](http://www.163.com)
>    [www.google.com](http://www.google.com)
> 
> ![Screenshot-2022-10-15_211408](https://user-images.githubusercontent.com/9279217/195988958-be7008c7-638d-4a6b-a01f-a8cbf6b13841.jpg)
> 
> ![Screenshot-2022-10-15_212313](https://user-images.githubusercontent.com/9279217/195988962-ec98e90a-6096-4682-91eb-25dbc09b6d6d.jpg)
> 
> 设置端口为6053
> 
> ![Screenshot-2022-10-15_213431](https://user-images.githubusercontent.com/9279217/195989298-49879f54-a8b6-440d-870f-1c6ad63f3af4.jpg)
> 
> ![Screenshot-2022-10-15_213439](https://user-images.githubusercontent.com/9279217/195989301-bdf92848-01a9-4e64-894e-ee5dae501fea.jpg)
> 
> ![Screenshot-2022-10-15_213452](https://user-images.githubusercontent.com/9279217/195989306-64cb404b-3783-4270-8d0a-f40b7f40b022.jpg) ![Screenshot-2022-10-15_213507](https://user-images.githubusercontent.com/9279217/195989311-7032673f-5885-4c60-ba7a-32e06c08c0db.jpg)

me too....

**Comment by PikuZheng** [comment]
有好几处会影响返回ip数量。可能需要配置
```
response-mode fastest-response
speed-check-mode none
max-reply-ip-num 10
```

**Comment by smdx** [comment]
> 

在自定义加上这几项测试还是返回多个ip

**Comment by PikuZheng** [comment]
> 在自定义加上这几项测试还是返回多个ip

是我语文问题。。这样设置国内网站返回就是多个ip没问题吧

**Comment by PikuZheng** [comment]
上面三个设置都会影响返回ip数量。看你要通过哪种方法限制了

**Comment by pymumu** [comment]
> > 
> 
> 
> 
> 在自定义加上这几项测试还是返回多个ip

37之后的版本就是这样的，这个是功能

当前返回多ip相比37之前版本对容错，视频软件，下载软件更加友好。并且ip列表中的第一个ip仍然是最快的那个，大部分软件使用的是第一个ip，访问速度仍然是最快的。

这个逻辑是首次查询返回一个最快ip，并同时缓存时延迟和最快ip相近的ip，后面从缓存中查询时就会返回多个ip了，ip列表的第一个是最快ip

此功能开启测速和缓存才生效，可通过max-reply-ip-num控制

**Comment by smdx** [comment]
> 上面三个设置都会影响返回ip数量。看你要通过哪种方法限制了

明白了，感谢

**Comment by smdx** [comment]
> > > 
> > 
> > 
> > 在自定义加上这几项测试还是返回多个ip
> 
> 37之后的版本就是这样的，这个是优化查询结果的功能
> 
> 当前返回多ip相比37之前版本对容错，视频软件，下载软件更加友好。并且ip列表中的第一个ip仍然是最快的那个，大部分软件使用的是第一个ip，访问速度仍然是最快的。
> 
> 这个逻辑是首次查询返回一个最快ip，并同时缓存时延迟和最快ip相近的ip，后面从缓存中查询时就会返回多个ip了，ip列表的第一个是最快ip
> 
> 此功能开启测速和缓存才生效，可通过max-reply-ip-num控制

原来如此,明白了。感谢解答

**Comment by wnju** [comment]
我试过了，默认情况下：第一组DNS是只返回1个IP的，第二组DNS返回多个IP

**Comment by wnju** [comment]
我试过了，默认情况下：第一组DNS是只返回1个IP的，第二组DNS返回多个IP
如果在附加参数加上speed-check-mode none：第一组DNS和第二组DNS返回多个IP
如果想要国内IP返回多个IP，国外IP返回1个IP的话，可以把国内IP绑定到第二组DNS，国外IP绑定到第一组DNS

**Comment by wnju** [comment]
测试结果：
![微信截图_20240614005623](https://github.com/pymumu/smartdns/assets/95446235/ea28dac6-f8ce-480a-af15-5a90205a464e)
