### ISSUE TITLE
配置单个域名 address 后仍然会返回上游 DNS 服务器中的 IPv6 结果

### ISSUE THREAD

**Issue by TGSAN** [pymumu/smartdns#1123]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
OpenWrt R22.2.2 / LuCI Master (git-21.335.48743-5f363d9)

2. 运营商  
上海电信

3. smartdns来源以及版本
Github Release 38

4. 涉及的配置(注意去除个人相关信息)
```
speed-check-mode ping,tcp:80,tcp:443
dualstack-ip-selection yes
force-qtype-SOA 65
```
勾选了：TCP服务器、IPV6服务器、双栈IP优选、解析本地主机名、停用HTTPS地址解析

**重现步骤**
1. 上游DNS配置。  
在`域名地址`中配置 address
```
address /assets1.xboxlive.com/1.2.3.4
```

2. nslookup assets1.xboxlive.com

结果：
```
PS C:\Windows\System32> nslookup assets1.xboxlive.com
服务器:  smartdns
Address:  240e:38a:1f2b:b700::1

非权威应答:
名称:    assets1.xboxlive.com.c.footprint.net
Addresses:  2001:1900:2382:2005::1fe
          1.2.3.4
Aliases:  assets1.xboxlive.com
```

按照配置应只返回地址 1.2.3.4，但是实际返回了 1.2.3.4 和原始的 IPv6 解析结果

**Comment by PikuZheng** [comment]
ipv4和ipv6本质上是两次查询。address /assets1.xboxlive.com/#6 请
