### ISSUE TITLE
如何让有ipv4和ipv6的域名只返回ipv6。

### ISSUE THREAD

**Issue by snfcx** [pymumu/smartdns#1125]
**需求应用场景**
请描述需求应用的场景和方式。

电脑设置了ipv6优先的是软件还是使用了ipv4的地址，想让dns返回的时候就只返回ipv6屏蔽ipv4.
![Uploading Snipaste_2022-10-20_12-46-15.png…]()

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  
新3
2. 固件信息
op

**Comment by snfcx** [comment]
> 地址 /域名/#4

我有设置#4或者#6但是他们都没有变化。可以请帮我看看哪里配置错了吗？谢谢
![image](https://user-images.githubusercontent.com/55078254/196909238-2a53cba1-a57b-4122-919d-8fd2d904d38d.png)
![image](https://user-images.githubusercontent.com/55078254/196909448-58ec4f45-715c-4a4c-b443-1f42f42a1af3.png)

**Comment by pymumu** [comment]
建议是开启双战优选。
稍微激进的话，可以
```
# 双栈允许强制IPV6.
dualstack-ip-allow-force-AAAA yes 
dualstack-ip-selection-threshold 5
```

也可以强制关闭整个IPV4
```
force-qtype-SOA 1
```

**Comment by Jiew-KueJwiaeng** [comment]
> address /域名/#4

您好，我尝试用这种方法，但目前 address 规则会自动向下匹配，导致无AAAA记录的子域会无法返回结果。比如 address /cloud.tencent.com/#4 会导致 ping.cloud.tencent.com 报 ERR_NAME_NOT_RESOLVED 。
有能让 address 匹配纯字符串或其它方法吗？

**Comment by PikuZheng** [comment]
address /ping.cloud.tencent.com/-

**Comment by siren202101** [comment]
> 建议是开启双战优选。 稍微激进的话，可以
> 
> ```
> # 双栈允许强制IPV6.
> dualstack-ip-allow-force-AAAA yes 
> dualstack-ip-selection-threshold 5
> ```
> 
> 也可以强制关闭整个IPV4
> 
> ```
> force-qtype-SOA 1
> ```

这个命令怎么在官网的配置指导中没有呢？还有多少命令是没有公布出来的？
dualstack-ip-allow-force-AAAA yes
