### ISSUE TITLE
树莓派更新后无法启动

### ISSUE THREAD

**Issue by weijin04** [pymumu/smartdns#1128]
**问题现象**  
简要描述问题出现的现象
更新38.1 后无法启动
**运行环境**
1. 固件型号  
Raspberry Pi 2  Model B v1.2 - ARM Cortex-A53 with 1G RAM
2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
下载smartdns.1.2022.10.20-2312.arm-debian-all.deb安装后执行 systemctl start smartdns，返回
<img width="567" alt="截屏2022-10-21 14 55 35" src="https://user-images.githubusercontent.com/57230828/197212880-0a7d5ef6-c0bb-4850-9cc0-83cf92b0189c.png">

journalctl -xe 返回
<img width="626" alt="截屏2022-10-21 14 58 38" src="https://user-images.githubusercontent.com/57230828/197213554-8e460246-ae0d-41f0-a23d-f23f6f7caaa9.png">

ldd /usr/sbin/smartdns返回
<img width="175" alt="截屏2022-10-21 15 00 27" src="https://user-images.githubusercontent.com/57230828/197213990-95281506-989c-4306-80d5-8a70e69983fd.png">

重新下载smartdns.1.2022.09.25-1116.arm-debian-all.deb安装后执行 systemctl start smartdns，程序正常启动

**Comment by PikuZheng** [comment]
duplicate of #1127

**Comment by PikuZheng** [comment]
顺便请教一下树莓派是哪个架构（以下是选项
```
armeb-eabi 
armeb-eabihf 
armel-eabi 
armel-eabihf 
arm-eabi 
arm-eabihf 
armv5l-eabi 
armv5l-eabihf 
armv6-eabi 
armv6-eabihf 
armv7l-eabihf 
armv7m-eabi 
armv7r-eabihf
```

**Comment by pymumu** [comment]
已经更新

**Comment by weijin04** [comment]
> 

The ARM Cortex-A7 MPCore is a 32-bit microprocessor core licensed by [ARM Holdings](https://en.wikipedia.org/wiki/ARM_Holdings) implementing the [ARMv7-A architecture](https://en.wikipedia.org/wiki/ARM_architecture#AArch32) announced in 2011.

**Comment by weijin04** [comment]
> 顺便请教一下树莓派是哪个架构（以下是选项
> 
> ```
> armeb-eabi 
> armeb-eabihf 
> armel-eabi 
> armel-eabihf 
> arm-eabi 
> arm-eabihf 
> armv5l-eabi 
> armv5l-eabihf 
> armv6-eabi 
> armv6-eabihf 
> armv7l-eabihf 
> armv7m-eabi 
> armv7r-eabihf
> ```

The ARM Cortex-A7 MPCore is a 32-bit microprocessor core licensed by [ARM Holdings](https://en.wikipedia.org/wiki/ARM_Holdings) implementing the [ARMv7-A architecture](https://en.wikipedia.org/wiki/ARM_architecture#AArch32) announced in 2011.
