### ISSUE TITLE
Release 38.1 is NOT static built, CANT run on linux with musl like: apline

### ISSUE THREAD

**Issue by honwen** [pymumu/smartdns#1129]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
> Alpine Linux 3.16 x86_64

> Alpine Linux is a super lightweight Linux distribution that's useful for Docker containers.

refer: https://hub.docker.com/_/alpine

2. 运营商  
> null

3. smartdns来源以及版本

https://github.com/pymumu/smartdns/releases/tag/Release38.1 : NOT works

https://github.com/pymumu/smartdns/releases/tag/Release38  : works

4. 涉及的配置(注意去除个人相关信息)
> null

**重现步骤**
> null

**信息收集**  
```
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/bin/smartdns)
Error relocating /usr/bin/smartdns: _Unwind_GetIP: symbol not found
Error relocating /usr/bin/smartdns: _Unwind_Backtrace: symbol not found
```

**Comment by PikuZheng** [comment]
duplicate of #1127

**Comment by itning** [comment]
麻烦提供个静态编译版本呗

**Comment by pymumu** [comment]
已经更新

**Comment by 4thanks** [comment]
> 已经更新

求更新
https://github.com/pymumu/openwrt-smartdns
https://github.com/pymumu/luci-app-smartdns

**Comment by pymumu** [comment]
那两个库没精力更新了。请直接到openwrt官方代码仓获取代码。

**Comment by honwen** [comment]
> 已经更新

tested ok. tks
