### ISSUE TITLE
关于google play 的问题

### ISSUE THREAD

**Issue by ZiPenOk** [pymumu/smartdns#113]
如何设置 才能让services.googleapis.cn解析到正确ip

已经设置国外dns , 现在解析出来play无法链接,应该是被解析到了国内谷歌服务器ip

**Comment by pymumu** [comment]
cn域名肯定会解析到国内的。
你可以用address参数指定其ip地址。
``
address /services.googleapis.cn/[ip]
``
ip可以用services.googleapis.com的。

**Comment by ZiPenOk** [comment]
> cn域名肯定会解析到国内的。
> 你可以用address参数指定其ip地址。
> `address /services.googleapis.cn/[ip]`
> ip可以用services.googleapis.com的。

address /services.googleapis.cn/[216.58.200.234]
我这么设置后,怎么还是不行 ?

**Comment by pymumu** [comment]
后面中括号要去掉。

**Comment by ZiPenOk** [comment]
> 后面中括号要去掉。
> 
> address /services.googleapis.cn/216.58.200.234

我是先去掉括号试的,然后加括号试的,也清理了缓存,重启了dnsmasq和smartdns服务,解析出来都还是国内IP203.208.40.119

**Comment by pymumu** [comment]
直接dit到smartdns查询下看看，address的话是直接指定域名的IP地址，smartdns是立即返回这个地址的。

**Comment by ZiPenOk** [comment]
> 直接dit到smartdns查询下看看，address的话是直接指定域名的IP地址，smartdns是立即返回这个地址的。

怎么做? 我小白

**Comment by pymumu** [comment]
dig services.googleapis.cn -p 6053 @[samrtdns ip]

**Comment by ZiPenOk** [comment]
> dig services.googleapis.cn -p 6053 @[samrtdns ip]
这样子,直接是返回我指定的国外IP

**Comment by ZiPenOk** [comment]
我是作为dnsmasq上游,,,应该是有效的啊,我默认nslookup 查询google.com 是返回单个有效IP

**Comment by pymumu** [comment]
是怕你有前端dns缓存了结果

**Comment by ZiPenOk** [comment]
pdnsd的锅

**Comment by ChenSmallX** [comment]
> pdnsd的锅

请问一下，如何处置pdnsd才可以正确配置呢？
