### ISSUE TITLE
N1/玩客云 Docker中单独安装smartdns

### ISSUE THREAD

**Issue by FrankLiangCN** [pymumu/smartdns#1133]
我测试的是 https://hub.docker.com/r/pikuzheng/smartdns，以及其它版本

目的是想在docker中单独安装运行smartdns，跟openwrt分离

之后采用下面的命令安装
docker run -itd --restart=always --privileged --name smartdns pikuzheng/smartdns /sbin/init

查log有下面的异常can't run '/sbin/openrc': No such file or directory

网上没有找到相关解决方案，查询可能跟alpine相关，之后就不知道怎么解决这个异常

请问一下有没有哪个smartdns版本可以在N1/玩客云 Docker中单独安装运行？

**Comment by PikuZheng** [comment]
官方的docker也不行嘛？什么架构的？

**Comment by PikuZheng** [comment]
另外为啥要运行  /sbin/init ？是要进去对image做什么修改嘛？

**Comment by FrankLiangCN** [comment]
> 官方的docker也不行嘛？什么架构的？
N1是ARMv8，玩客云是ARMv7
先刷了Armbian，再装docker

**Comment by FrankLiangCN** [comment]
> 另外为啥要运行 /sbin/init ？是要进去对image做什么修改嘛？

不加 /sbin/init，出现load config failed的错误提示，完全不能运行，加了，至少系统显示这个容器可以运行，网上没有搜到相关的信息，现在不知道怎么能让smartdns正常运行起来，还请指教一下，谢谢！

**Comment by PikuZheng** [comment]
哦，我这个容器没默认配置文件。配置文件应该在/etc/smartdns，把这个目录映射出去，配置写好放里就行了（默认启动配置文件是/etc/smartdns/smartdns.conf）。查了一下openrc是keepalived用的。容器用dockerd，不需要这玩意，默认没这个组件

**Comment by FrankLiangCN** [comment]
> 哦，我这个容器没默认配置文件。配置文件应该在/etc/smartdns，把这个目录映射出去，配置写好放里就行了（默认启动配置文件是/etc/smartdns/smartdns.conf）。查了一下openrc是keepalived用的。容器用dockerd，不需要这玩意，默认没这个组件

之前是把配置文件直接放入/etc/smartdn，也会提示无法加载配置，现在映射目录后，可以运行了，感谢你的答复支持，此问题可以关闭了
