### ISSUE TITLE
希望可以增加Windows版本

### ISSUE THREAD

**Issue by KelvinSoh8** [pymumu/smartdns#1135]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
OpenWrt太难折腾了，能不能增加Windows版本，直接安装后使用呢?目前使用WSL很占用系统资源，希望可以增加Windows本地版，直接安装的exe运行，还是其他方案也可以，软路由我都折腾怕了

**设备信息**
1. 设备信息CPU X86-64

2. 固件信息Windows 10/11

**Comment by PikuZheng** [comment]
重复 #739

**Comment by PikuZheng** [comment]
![image](https://user-images.githubusercontent.com/12579522/197524132-e9e753b3-1a26-49f8-97b9-ad28cfc568b4.png)
单跑smartdns 用大概180M内存吧 觉得可以接受

**Comment by miku1958** [comment]
@PikuZheng 请问一下cygwin 要怎么配置才能编译, 我直接跑这个会有大量的致命错误
./package/build-pkg.sh --platform linux --arch x86-64

**Comment by PikuZheng** [comment]
> @PikuZheng 请问一下cygwin 要怎么配置才能编译, 我直接跑这个会有大量的致命错误，platform改成windows也不行
> ./package/build-pkg.sh --platform linux --arch x86-64

没用过，不过猜测是缺少依赖库尤其openssl

**Comment by miku1958** [comment]
@PikuZheng 你在前面的回复不是跑成功了吗

**Comment by pymumu** [comment]
https://github.com/mokeyish/smartdns-rs/tree/0.1.2
有人开发了rust版本的smartdns，支持windows，可以尝试。
