### ISSUE TITLE
当resolve_local_hostnames设置为不解析本地主机名时，页面配置文件里还是解析路径，见截图！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1137]
路径：/tmp/etc/smartdns/smartdns.conf
![image](https://user-images.githubusercontent.com/45259624/197810297-d4171736-d555-4549-9de1-3b1b6a3087e5.png)
另外，force-qtype-SOA  28 65在配置文件里永远存在，比如有苹果设备，就需要关闭解析65。

**Comment by PikuZheng** [comment]
在我实践中 resolve-local-hostnames 不配置时 resolve-file 不起作用

**Comment by PikuZheng** [comment]
force-qtype-SOA 对应界面的 停用IPV6地址解析 和 Force HTTPS SOA. 我两个都不勾选，就没有 force-qtype-SOA 28 65
