### ISSUE TITLE
麻烦满足一下几个小需求

### ISSUE THREAD

**Issue by onion83** [pymumu/smartdns#114]
**需求应用场景**

1. 禁止返回 AAAA 记录，全局关闭 IPv6
2. 作为标准dns代理，提供关闭测速功能。解锁黑盒，明确测速的方式，如 imcp / tcp ，并提供超时选项
3. nameserver 功能扩展

**建议的方案**

1. 添加全局 `disable-ipv6` 选项，当为 true 时候，忽略 AAAA 等记录，dualstack-ip-selection 等相关功能自动关闭。
2. 添加全局 `speedtest` 选项，当为 false 时，禁止全部测速功能，直接返回上游记录。
    添加全局 `speedtest-mode `选项，参数为 imcp|tcp[80]|both|auto
    添加全局 `speedtest-timeout` 选项，默认为 10ms
3. 扩展 `nameserver` 功能 , `nameserver /domain/[group|-, disable-ipv6, disable-speedtest]`
    其中 disable-ipv6 忽略 AAAA 记录， disable-speedtest 禁用测速，直接返回上游记录
` nameserver /.google.com/free,disable-ipv6, disable-speedtest` 或者
` nameserver /.google.com/free,1,0` 当字段为空时候，以全局配置为准。

**Comment by pymumu** [comment]
第一点：禁止AAAA地址，已经有选项，配置下列选项即可：
```
force-AAAA-SOA yes
```
第二点，全局关闭功能与smartdns设计初衷不符，所以后续只会提供特定域名的测试控制，不会提供全局关闭接口。

第三点的应用场景是什么。

**Comment by onion83** [comment]
首先，再次感谢回复。

对于二，其实如果用户指定关闭全局测速，说明必然有起使用意图。

场景1：假设有域名 cdn.abc.com 上游返回两条A记录，1.1.1.1 和 2.2.2.2 如果用 icmp 测速 1.1.1.1 确实比 2.2.2.2 快，但是很不幸 1.1.1.1 的 80 端口挂了/服务器负载过高。此时优选结果 **只有** 1.1.1.1 ，如果 按传统的思路，返回两个A记录，客户还有活的机会没，虽然可能体验不佳（如下载量比较大的 Apple Store）做得好的客户端，程序自身也能根据多个 IP 再做一次应用层的优选（如下载测速），如果 smartdns 只返回一个的 IP 话，我觉得就剥夺了应用的权利了。

场景2: 某些网络、服务器屏蔽了 icmp 协议 或者服务根本不在 80 端口，此时所有的测速工作其实都白白浪费 CPU和网络。

结论：对于 dns 解析 **最优解** 其实很难定义和实现的，作为 dns 既要快又要准确实有难度，如果用户确实想关，还是让它关掉吧，能够同时现实  udp/tcp/tls 上游服务器的支持已经很棒了。

第三：基本理由同二，对某些域名特殊处理，保持一定的灵活性吧。

**Comment by pymumu** [comment]
ICMP+TCP 80测速，其实已经覆盖了99以上的场景了，所以绝大部分应该可以收到好的效果。
对于场景一说到的IP失效的情况，确实会出现，后面考虑返回两个IP，速度快的排在前面。

对于极个别域名，可以采取配置的方式关闭测速，但这个目前只考虑指定域名，这里也是泛域名指定。

**Comment by BraveSail** [comment]
> ICMP+TCP 80测速，其实已经覆盖了99以上的场景了，所以绝大部分应该可以收到好的效果。
> 对于场景一说到的IP失效的情况，确实会出现，后面考虑返回两个IP，速度快的排在前面。
> 
> 对于极个别域名，可以采取配置的方式关闭测速，但这个目前只考虑指定域名，这里也是泛域名指定。

请问这里的测速机制是什么？我本地网络是双栈，我现在路由器上部署了透明代理，并且是[绕过局域网及大陆]模式，dns选择了使用本机xxxx端口服务，smartdns开启了ICMP+TCP 80测速，这样的话，经过我多次测试客户机在访问境外网站的时候仍然会通过ipv6访问。但是实际上通过ipv4访问的话（梯子不支持ipv6）延迟会从150ms+降低到40ms，是否测速的时候没有走透明代理测速？

**Comment by ixmu** [comment]
> 第一点：禁止AAAA地址，已经有选项，配置下列选项即可：
> 
> ```
> force-AAAA-SOA yes
> ```
> 
> 推荐是直接用dualstack-ip-selection，此功能会同时请求AAAA, A地址。 如果发现A地址比AAAA地址快，会禁止AAAA请求，并缓存A记录。
> 
> 等PC再次请求A记录的时候，直接从缓存中获取记录。
> 
> 所以，设计上，优先的效率、效果远远好于完全禁止。 除非是某些特定域名的出国上网，如果是这种情况，可以配置那些域名的AAAA地址，返回SOA，配置如下
> 
> ```
> address /google.com/#6
> ```
> 
> 第二点，全局关闭功能与smartdns设计初衷不符，所以后续只会提供特定域名的测试控制，不会提供全局关闭接口。
> 
> 第三点的应用场景是什么。

-6 忽略ipv6
#6 返回SOA
两者什么差别吗？
