### ISSUE TITLE
smartdns运行一段时间后会监听多个UDP端口

### ISSUE THREAD

**Issue by mmmiii33** [pymumu/smartdns#1140]
SmartDNS版本：smartdns 1.2022.10.22-1309

smartdns运行一段时间后会监听多个UDP端口，重启后恢复，只监听53

root@HomeCenter:~# netstat -nulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:58288           0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:38844           0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:35063           0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:48218           0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:52362           0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:56555           0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:48523           0.0.0.0:*                           25971/smartdns      
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           13384/netdata       
udp        0      0 0.0.0.0:53              0.0.0.0:*                           25971/smartdns      
udp        0      0 0.0.0.0:67              0.0.0.0:*                           8541/dhcpd          
udp6       0      0 ::1:8125                :::*                                13384/netdata

**Comment by PikuZheng** [comment]
之前也有一个issue反馈发现其他端口的，但一时找不到了。我自己从没遇到过这种情况（openwrt和alpine）。
你用的是什么系统哪个版本的？配置中是只监听了53端口吗？

**Comment by PikuZheng** [comment]
我想起来了，你这是配置了udp协议的上游，由于udp是无状态的，必须通过监听端口的方式来接受回复

**Comment by pymumu** [comment]
发送请求到上游也需要端口号的，这个是客户端端口号，你可以数一下数量上是不是和你配置的udp上游一致。

**Comment by mmmiii33** [comment]
> 我想起来了，你这是配置了udp协议的上游，由于udp是无状态的，必须通过监听端口的方式来接受回复。 你这个查询没有状态，试试用 ` netstat -anlp | grep smartdns`

root@HomeCenter:/etc/openvpn/client# netstat -nulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:37102           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:45793           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:43136           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:43686           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:52018           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:36095           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:44578           0.0.0.0:*                           15974/smartdns      
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           13384/netdata       
udp        0      0 0.0.0.0:53              0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:67              0.0.0.0:*                           8541/dhcpd          
udp        0      0 0.0.0.0:57468           0.0.0.0:*                           15974/smartdns      
udp6       0      0 ::1:8125                :::*                                13384/netdata       
root@HomeCenter:/etc/openvpn/client# 
root@HomeCenter:/etc/openvpn/client# netstat -anlp | grep smartdns
udp        0      0 0.0.0.0:37102           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:45793           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:43136           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:43686           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:52018           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:36095           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:44578           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:53              0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:57468           0.0.0.0:*                           15974/smartdns      
raw        0      0 0.0.0.0:1               0.0.0.0:*               7           15974/smartdns      
raw6       0      0 :::58                   :::*                    7           15974/smartdns

**Comment by mmmiii33** [comment]
> 发送请求到上游也需要端口号的，这个是客户端端口号，你可以数一下数量上是不是和你配置的udp上游一致。

是的，除去53端口的，与上游DNS数量一样，配置了8个UDP上游DNS。

root@HomeCenter:/etc/openvpn/client# netstat -nulp | grep smartdns
udp        0      0 0.0.0.0:50573           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:38866           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:43136           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:39649           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:52018           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:36095           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:44662           0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:53              0.0.0.0:*                           15974/smartdns      
udp        0      0 0.0.0.0:57468           0.0.0.0:*                           15974/smartdns
