### ISSUE TITLE
网易新闻app端加载图片缓慢

### ISSUE THREAD

**Issue by quango-web** [pymumu/smartdns#1141]
主路由openwrt 5.4 
手机使用wifi接入网络
单一现象描述：smartdns-37之后的版本（包括38.1）,除在luci界面设置几个DNS地址外其他采用默认设置，在使用手机网易APP客户端会出现图片或者视频缩略图无法加载的状况，且使用越久越厉害。但退回到36.1老版本即使用非常正常。难道是Release 37之后版本内置有去广告图片过滤功能造成的？

以上描述的特定现象不敢确认是smartdns造成的，所以发此向作者及见多识广的大佬们求教指正。

**Comment by PikuZheng** [comment]
> 难道是Release 37之后版本内置有去广告图片过滤功能造成的

没有！（大声

这个问题我记得在很多年前我遇到过。你看看微博app是不是加载图片和视频都很缓慢（但是文字内容正常，而且pc上网页微博正常

**Comment by pymumu** [comment]
关闭过期缓存试一下。
```
serve-expired no
```

**Comment by quango-web** [comment]
> > 难道是Release 37之后版本内置有去广告图片过滤功能造成的
> 
> 没有！（大声
> 
> 这个问题我记得在很多年前我遇到过。你看看微博app是不是加载图片和视频都很缓慢（但是文字内容正常，而且pc上网页微博正常

微博不会，安卓系统下的其他媒体程序试了都不会，唯独网易新闻app加载图片时如便秘，手机快速往下拉时就会出现大量灰框，然后一张一张缓慢载入图片，有些则直接加载不了
![Screenshot_20221028_145631_NetEase News](https://user-images.githubusercontent.com/75406123/198706309-642599aa-d13a-415f-b4b3-8d19bf4304bf.jpg)
![Screenshot_20221028_145815_NetEase News](https://user-images.githubusercontent.com/75406123/198706386-802ef376-96e9-4d3a-81ab-4bc129d63adf.jpg)

**Comment by quango-web** [comment]
> 关闭过期缓存试一下。
> 
> ```
> serve-expired no
> ```

我试试看

**Comment by lalasou** [comment]
用默认设置 只添加  上游  和测速模式  其他不用试试    大概率解决问题

**Comment by quango-web** [comment]
> 关闭过期缓存试一下。
> 
> ```
> serve-expired no
> ```
![2022 10 29-13_31_17](https://user-images.githubusercontent.com/75406123/198815693-7586bd49-f59a-4aba-acbc-695f0a51bb6f.jpg)

反馈作者：因为openwrt的设置是用老备份覆盖，在smartdns的luci界面自定义有-speed-check-mode tcp:443--这个测速参数，删除后网易app就恢复正常了。
我使用Hello World插件默认dns解析端口5335，smartdns在luci界面启用第一服务器设置为Dnsmasq的上游服务器，端口也是5335。填入两组国内dns-udp 119.29.29.29 ,223.5.5.5，两组国外https://8.8.8.8/dns-query，https://1.1.1.1/dns-query

请作者大佬帮忙指导一下是什么原因？谢谢！

**Comment by lalasou** [comment]
有些 只有80  并没有 443


speed-check-mode tcp:80,tcp:443,ping

感觉还是这样好些

**Comment by PikuZheng** [comment]
> 反馈作者：因为openwrt的设置是用老备份覆盖，在smartdns的luci界面自定义有-speed-check-mode tcp:443--这个测速参数，删除后网易app就恢复正常了。
> 我使用Hello World插件默认dns解析端口5335，smartdns在luci界面启用第一服务器设置为Dnsmasq的上游服务器，端口也是5335。填入两组国内dns-udp 119.29.29.29 ,223.5.5.5，两组国外[https://8.8.8.8/dns-query，https://1.1.1.1/dns-query](https://8.8.8.8/dns-query%EF%BC%8Chttps://1.1.1.1/dns-query)

tcp/443 测速，代理抢答，造成连接国外比连接国内快的假象。

**Comment by quango-web** [comment]
> 
> tcp/443 测速，代理抢答，造成连接国外比连接国内快的假象。

请教大佬，应该如何在smartdns使用测速参数时避免代理抢答，谢谢。

**Comment by LsnmxNB** [comment]
> > tcp/443 测速，代理抢答，造成连接国外比连接国内快的假象。
> 
> 请教大佬，应该如何在smartdns使用测速参数时避免代理抢答，谢谢。

区分国内外分别指定上游的功能不太完善，等吧

**Comment by PikuZheng** [comment]
对国外的域名不测速不就行了

**Comment by pymumu** [comment]
用最新代码看看
