### ISSUE TITLE
Feature request - 能否添加速度检测失败后将解析结果添加ipset或nftset

### ISSUE THREAD

**Issue by kulongwangzhi85** [pymumu/smartdns#1143]
**感谢作者分享这么好的软件**

**需求应用场景**
速度检测模块，由于网络原因，测速失败后，将解析结果添加ipset或nftset

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by kulongwangzhi85** [comment]
该功能可以在后台，维护缓存时触发。不必在第一次请求时触发。

**Comment by pymumu** [comment]
[Done](https://pymumu.github.io/smartdns/config/ipset-nftset/)
