### ISSUE TITLE
1.2022.10.22-1309.all-luci-compat-all.ipk 安装不了

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#1144]
**问题现象**  

root@OpenWrt:~# cd /tmp
root@OpenWrt:/tmp# opkg install luci-app-smartdns.1.2022.10.22-1309.all-luci-com
pat-all.ipk
Installing luci-app-smartdns (1.2022.10.22-1309) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-smartdns:
 *      luci-compat
 * opkg_install_cmd: Cannot install package luci-app-smartdns.
root@OpenWrt:/tmp#

**运行环境**
1. 固件型号  

内核版本	4.14.176

--------

smartdns安装的是这个版本
smartdns.1.2022.10.22-1309.mipsel-openwrt-all.ipk

--------

luci可以正常安装的版本
luci-app-smartdns.1.2022.04.05-2046.all-luci-compat-all.ipk，及比之前更旧的。
luci-app-smartdns.1.2022.08.28-1734.all-luci-compat-all.ipk

测试过不能安装的版本（报同样的错误）
luci-app-smartdns.1.2022.09.25-1116.all-luci-compat-all.ipk
luci-app-smartdns.1.2022.10.22-1309.all-luci-compat-all.ipk

**Comment by PikuZheng** [comment]
> * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-smartdns:
> * ```
>    luci-compat
>   ```

缺少依赖包：luci-compat。

**Comment by ztjal** [comment]
成了，因为以前编译固件时没加luci-compat，上
https://archive.openwrt.org/releases/18.06.0/packages/mipsel_24kc/luci/
下了个luci-compat_git-19.318.37269-ca98eae-1_all.ipk
装上没报错，再装luci-app-smartdns.1.2022.10.22-1309.all-luci-compat-all.ipk就没问题了。
