### ISSUE TITLE
smartdns - 1.2022.38.1-1  默认配置返回dns问题

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1147]
现在有点搞不清默认配置返回dns数量问题了

配置如下

server-name smartdns
prefetch-domain yes
serve-expired yes
cache-size 4096000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind [::]:53
bind-tcp [::]:53
server 223.5.5.5  
server-tls 1.1.1.1  
server-tls edns.apad.pro  
server-tls 1.12.12.12  
speed-check-mode tcp:80,tcp:443,ping
force-qtype-SOA 65

这样 
nslookup production.cloudflare.docker.com
只返回了一个dns  
用223.5.5.5   返回4个v4 ip  3个v6 ip
不是说新版本会调整顺序返回多个dns吗
默认配置下也没有返回v6地址啊

**Comment by lalasou** [comment]
神奇的事情来了

我把pppoe   自定义dns  223.5.5.5
然后 重启 
smartdns  正常返回多ip 和v6了


可以复现
内网没有其他劫持53


nslookup  smartdns   正常返回路由器ip

设置的 mini ttl   也有显示

**Comment by kulongwangzhi85** [comment]
max-reply-ip-num参数修改下试试

**Comment by lalasou** [comment]
不写max-reply-ip-num 
默认就是上游数量  ？？

speed-check-mode ping,tcp:80,tcp:443
speed-check-mode tcp:80,tcp:443,ping
发现这两种写法 返回的ip数量不一样  😅
搞不懂了

**Comment by PikuZheng** [comment]
参考一下 #1122 首次返回ip数量和之后返回ip数量是两个事情了 具体看看你想要控制哪个数量

**Comment by lalasou** [comment]
> 参考一下 #1122 首次返回ip数量和之后返回ip数量是两个事情了 具体看看你想要控制哪个数量

@PikuZheng 
那么
默认max-reply-ip-num值是多少？配置文件没说
如果 max-reply-ip-num保持默认
response-mode 保持默认
那么   过了首次查询 之后 
返回的是多ip还是单ip

怎么样设置 会同时返回v6地址
把双栈优选关了？

**Comment by PikuZheng** [comment]
> 默认max-reply-ip-num值是多少？配置文件没说

8
> 如果 max-reply-ip-num保持默认 response-mode 保持默认 那么 过了首次查询 之后 返回的是多ip还是单ip

多
 
> 怎么样设置 会同时返回v6地址 把双栈优选关了？

对
