### ISSUE TITLE
返回ip 疑问❓

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1151]
现在有点搞不清默认配置返回dns数量问题了

配置如下

server-name smartdns
prefetch-domain yes
serve-expired yes
cache-size 4096000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind [::]:53
bind-tcp [::]:53
server 223.5.5.5  
server-tls 1.1.1.1  
server-tls 208.67.222.222
server-tls 1.12.12.12  
speed-check-mode ping,tcp:80,tcp:443
force-qtype-SOA 65

#下面这几个我看大佬这样写的 
serve-expired-ttl 345600
serve-expired-prefetch-time 43200
serve-expired-reply-ttl 2

然后 
nslookup production.cloudflare.docker.com
刚开始一段时间  v4 v6都返回并排序 这没问题
但是  过一段时间后  只有v4没有v6了  
smartdns reload  也没用
用223.5.5.5   还是返回4个v4 ip  3个v6 ip
这是什么情况 
我有点搞不懂了

![image](https://user-images.githubusercontent.com/7440313/200130331-aef27648-4082-4e7d-8874-a490671e4e42.png)

求助大佬们
@pymumu

**Comment by lalasou** [comment]
并且 

serve-expired-reply-ttl 2
这样后 第一次访问  ttl2
再访问  返回ip会排序 返回 ttl=minittl

问题；如果首次访问返回ttl2 马上刷新
ttl2  能不能把所有返回ip 测速排序
如果不能是不是 需要等到下一个 minittl才是按测速排序？


也就是说 真正按测速排序的ip 是在一个minittl之后了

**Comment by pymumu** [comment]
域名第一次请求的时候会返回一个最快ip地址，后续缓存后有可能返回多个ip，具体看网络情况

默认开启了双栈优选，如果ipv6远比ipv4慢时，只会返回v4地址

具体返回多少IP，要看你当前的网络情况

你可以打开info log看查询ip的结果情况

**Comment by lalasou** [comment]
> 域名第一次请求的时候会返回一个最快ip地址，后续缓存后有可能返回多个ip，具体看网络情况
> 
> 默认开启了双栈优选，如果ipv6远比ipv4慢时，只会返回v4地址
> 
> 具体返回多少IP，要看你当前的网络情况
> 
> 你可以打开info log看查询ip的结果情况

好的
