### ISSUE TITLE
电信用户 电信官方网址经常解析不了？

### ISSUE THREAD

**Issue by sxml** [pymumu/smartdns#1153]
**问题现象**  
简要描述问题出现的现象

很奇怪 电信宽带用户  
SmartDNS 其他网址没事 唯独电信网址  经常打不开

频繁解析应答到本机 为什么？

非权威应答:
名称:    www.189.cn
Addresses:  ::1
          127.0.0.1

非权威应答:
名称:    cloud.189.c
Addresses:  ::1
          127.0.0.1

**运行环境**
1. 固件型号  

最新版本

2. 运营商  

电信

3. smartdns来源以及版本

编译

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

自动设置Dnsmasq  DNS 转发 127.0.0.1#6053

2. 访问的域名。  

唯独电信网址 www.189.cn cloud.189.cn

![2](https://user-images.githubusercontent.com/4932232/200180313-ebea5cb3-1b73-4e29-999e-52963206c437.jpg)

非常奇怪 我什么也没动 又自己好了 时好时坏 是什么问题？？？？

![6](https://user-images.githubusercontent.com/4932232/200180347-b15d6e5c-871a-4958-823b-f93c198c024a.png)

smrtdns.log日志

[smartdns.log](https://github.com/pymumu/smartdns/files/9946194/smartdns.log)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
日志级别是error，没有有意义的内容。
建议从上游中去掉运营商自有dns。

**Comment by sxml** [comment]
> 等级是自有的，没有任何日志内容。

哎 吐血 原来是 服务器名称 当成分组 写 cn  结果 cn域名都解析不了  www.189.cn  cloud.189.cn
换成其他就好了 

![BaiduShurufa_2022-11-8_2-47-11](https://user-images.githubusercontent.com/4932232/200392033-99f82c66-3d97-4fe9-ac55-ad7a6270efa7.png)

**Comment by pymumu** [comment]
升级最新代码
