### ISSUE TITLE
请问是否可以支持使用效果观测

### ISSUE THREAD

**Issue by helloworlde** [pymumu/smartdns#1154]
**需求应用场景**
您好，请问 SmartDNS 如何观测使用效果；在使用过程中有一些困惑，SmartDNS 通过测速找到最快的 IP值返回，但是对于具体的效果，如有多少是测速更快的，有多少是缓存命中的，以及提升了多少访问速度都是黑盒的；

我的使用场景是在 OpenWrt 中使用 SmartDNS；在实际测试中，使用以下三条访问路径：

1. 客户端-> Dnsmasq -> OpenClash -> SmartDNS -> 上游服务器(阿里云)
2. 客户端 -> SmartDNS -> 上游服务器(阿里云)
3. 客户端 -> 阿里云

实际多次测试发现三条路径的平均查询时间分别为 10ms/8ms/2ms 左右

**建议的方案**
建议借鉴 [blocky](https://0xerr0r.github.io/blocky/prometheus_grafana/)，增加观测能力，方便了解真正的使用效果

**设备信息**
1. 设备信息（CPU，厂家）  
CPU: Intel N5105
硬件：畅网微控工控机

4. 固件信息
系统：OpenWrt x86_64 版本 21

**Comment by PikuZheng** [comment]
可以将debug日志喂给Prometheus之类的统计分析软件处理。

记录统计信息将占用大量系统资源，建议不要这么做。

**Comment by PikuZheng** [comment]
如果只是要记录客户端到smartdns的延迟，或smartdns到上游的延迟，可以考虑在路由器上做traffic flow记录分析。

在日常使用中，smartdns作为单一的dns服务，客户端不会向其他dns服务器发出重复请求并比较应答速度；smartdns测速获取到的最快ip，也没法和默认ip比较连接速度（原则上上游dns都应做好cdn优化，返回即为最快）。所以这个“提升效果”怎么观测得到？如果做了额外的连接用于比较速度，是不是反而增加了网络开销影响了正常上网？
