### ISSUE TITLE
大佬们好，开启smartdns后无法访问搭建的ddns地址

### ISSUE THREAD

**Issue by zasl** [pymumu/smartdns#1159]
**需求应用场景**
请描述需求应用的场景和方式。

只有移动宽带，可以用ipv6地址ddns从外部访问
openwrt已经关闭特殊软件，只开启smartdns和一个dns服务器。
本机开启smartdns，本机搭建的ddns无法获取到地址，在另外一台机器的ddns其他设备从外部可以访问，但是本机开启smartdns无法访问和ping通，关闭smartdns后可以正常访问本机搭建ddns的地址和另一个机器ddns的地址。

请问各位大佬我该如何做。

<img width="414" alt="屏幕截图 2022-11-08 102207" src="https://user-images.githubusercontent.com/17813691/200462099-85c8aa34-cec9-40ec-91c8-0a6dd4bd1303.png">

<img width="395" alt="屏幕截图 2022-11-08 102442" src="https://user-images.githubusercontent.com/17813691/200462148-5bef143b-c49c-4a8c-b9fc-a3f36d7f5c68.png">

[smartdns.log](https://github.com/pymumu/smartdns/files/9957178/smartdns.log)
[smartdns.txt](https://github.com/pymumu/smartdns/files/9957189/smartdns.txt)
[custom.conf.txt](https://github.com/pymumu/smartdns/files/9957190/custom.conf.txt)

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息
openwrt 22.03

**Comment by PikuZheng** [comment]
没看懂你的问题。从日志来看可能有两个问题，一是互联网时通时断。二是应该关闭双栈ip优选。

**Comment by zasl** [comment]
> 没看懂你的问题。从日志来看可能有两个问题，一是互联网时通时断。二是应该关闭双栈ip优选。

谢谢大佬的回复，我开启smartdns后，无法访问我其他设备和本机的ddns，无法ping通液无法访问，关闭后可以正常访问其他设备和本机的ddns服务，能确保网络没有发生网络时通时断，双栈ip优选功能在另一个openwrt固件上也是开启的并且没有问题。我现在去关闭试一下。麻烦大佬还能想到是其他问题吗？nslookup 指定dns的方式是可以正常返回信息，移动宽带只有ipv6是公网。

**Comment by PikuZheng** [comment]
> <img alt="1" width="407" src="https://user-images.githubusercontent.com/17813691/200466709-b21b783a-6a69-4085-be13-a4fbf8b9fa4a.png">

单看这个图，ipv6能解析能访问且域名没有对应的ipv4地址。哪里不对了？

**Comment by zasl** [comment]
> > <img alt="1" width="407" src="https://user-images.githubusercontent.com/17813691/200466709-b21b783a-6a69-4085-be13-a4fbf8b9fa4a.png">
> 
> 单看这个图，ipv6能解析能访问且域名没有对应的ipv4地址。哪里不对了？

但是这样我直接ping我的ddns域名是无法ping通的，关闭smartdns后是可以ping通的，我需要做哪些调整吗？

**Comment by pymumu** [comment]
可能查询A地址的时候返回了SERVFAIL

强制让IPv4返回SOA看看

address /xx.xx/#4

**Comment by PikuZheng** [comment]
怀疑你关闭smartdns后ping通的是ipv4的ip（内网）。ping ipv6地址请用`ping6`

**Comment by zasl** [comment]
> 可能查询A地址的时候返回了SERVFAIL
> 
> 强制让IPv4返回SOA看看
> 
> address /xx.xx/#4

非常感谢提供帮助，在增加规则后好像是正常了。再测试一段时间看看，非常感谢。

另外请问如果不设置为53端口，重启后执行nslookup -querytype=ptr smartdns 显示的是我本地宽带供应商的dns，但是smartdns网页面显示运行中，只能关闭保持再开启保存才能启用，用53端口好像重启就正常了，这种情况我应该需要如何设置？

**Comment by zasl** [comment]
> 怀疑你关闭smartdns后ping通的是ipv4的ip（内网）。ping ipv6地址请用`ping6`

非常感谢，按照pymumu大佬的方法好像是解决了，还需要再长时间观察一些，谢谢大佬

**Comment by PikuZheng** [comment]
> 如果不设置为53端口，重启后执行nslookup -querytype=ptr smartdns 显示的是我本地宽带供应商的dns，但是smartdns网页面显示运行中，只能关闭保持再开启保存才能启用，用53端口好像重启就正常了

问下你用的是哪个版本

**Comment by zasl** [comment]
> > 如果不设置为53端口，重启后执行nslookup -querytype=ptr smartdns 显示的是我本地宽带供应商的dns，但是smartdns网页面显示运行中，只能关闭保持再开启保存才能启用，用53端口好像重启就正常了
> 
> 问下你用的是哪个版本

应该是openwrt软件包里面的最新版，前面以为固件问题一直在刷，但是应该是那个版本。刚刷完固件，等会我再尝试一下。

**Comment by PikuZheng** [comment]
建议用release的38.1试试 https://github.com/pymumu/smartdns/releases/tag/Release38.1

**Comment by 58285474** [comment]
> > > 如果不设置为53端口，重启后执行nslookup -querytype=ptr smartdns 显示的是我本地宽带供应商的dns，但是smartdns网页面显示运行中，只能关闭保持再开启保存才能启用，用53端口好像重启就正常了
> 
> > 
> 
> > 问下你用的是哪个版本
> 
> 
> 
> 应该是openwrt软件包里面的最新版，前面以为固件问题一直在刷，但是应该是那个版本。刚刷完固件，等会我再尝试一下。
> 
> 
> 
> 当时的情况是执行nslookup -querytype=ptr smartdns后显示宽带提供的默认dns，把smartdns关闭保存后再执行会显示的是127.0.0.1 和 127.0.01：53 的信息，再保存运行后会显示127.0.0.1 同时会给出smartdns正确运行的显示。

这个情况就是我说的重启后失效，要“重启smartdns”或者“再次点保存应用”，nslookup -querytype=ptr smartdns才会正确smartdns正确运行的显示。
