### ISSUE TITLE
是否可以增加旁路dns解析

### ISSUE THREAD

**Issue by chenchao0925** [pymumu/smartdns#116]
**需求应用场景**
我目前使用电信的iptv，但是由于更改了dns，导致播放节目出错，通过抓包，发现盒子无法正确解析本省的服务器地址和获取AAAA及SOA信息，导致盒子注册设备，播放视频提示认证错误。

**建议的方案**
能否增加，针对某客户端IP不进行dns代理，而强制他直接使用某个dns进行相关解析。

**设备信息**
使用的事LEDE operwrt 2.29版本、酸酸乳2.2.0 和smatdns2.1版本

**Comment by pymumu** [comment]
两个建议：
1. 直接在设备上配置固定DNS。
2. 让某些域名使用特定DNS解析？（FAQ的6，域名分流）

**Comment by ghostry** [comment]
DNSmasq好像有按域名走dns。

**Comment by pymumu** [comment]
@ghostry 
smartdns也支持按域名走不同DNS，也就是DNS分流。（安装指导FAQ的6节有细节说明。）

**Comment by chenchao0925** [comment]
感谢二位的回复，我再在设备上测试一下。

**Comment by chenchao0925** [comment]
> @ghostry
> smartdns也支持按域名走不同DNS，也就是DNS分流。（安装指导FAQ的6节有细节说明。）

我抓包发现，IPTV会进行多次AAAA和SOA的回复，引导盒子到多个不同的服务器进行相关注册和取视频流，我再IPTV抓到的包内至少就发现了不下10个服务器的域名，如果按照DNS分流，需要对所有域名进行统计和添加，不是太方便，所以说如果可能，还是建议能够增加基于源的DNS分流。
PS：楼主大大你的头像是不是小霸王的打鸭子，哈哈

**Comment by pymumu** [comment]
根据IP源转发DNS的请求的主要场景感觉不是特别多。

你的这个情况，IPTV上设置运营商的DNS服务器应该就可以了。

P.S.  是打鸭子，；-）
