### ISSUE TITLE
YouTube无法显示视频缩略图，但是视频正常

### ISSUE THREAD

**Issue by renhaimm** [pymumu/smartdns#1160]
**问题现象**  
YouTube无法显示视频缩略图，但是视频正常

**运行环境**
1. 固件型号  
openwrt X86 esir旁路由佛跳墙v6版本

2. 运营商  
湖北移动

3. smartdns来源以及版本
3.8.1，github

4. 涉及的配置(注意去除个人相关信息)
config smartdns
	option server_name 'smartdns'
	option port '6053'
	option tcp_server '1'
	option serve_expired '1'
	option cache_size '100000'
	option resolve_local_hostnames '1'
	option rr_ttl_min '600'
	option seconddns_port '6553'
	option seconddns_tcp_server '1'
	option seconddns_no_rule_ipset '0'
	option coredump '0'
	option prefetch_domain '0'
	option force_https_soa '0'
	option seconddns_enabled '1'
	option seconddns_server_group 'passwall_proxy'
	option seconddns_no_speed_check '1'
	option seconddns_no_rule_nameserver '1'
	option seconddns_no_rule_soa '1'
	option seconddns_no_dualstack_selection '1'
	option seconddns_no_cache '1'
	option auto_set_dnsmasq '1'
	option enabled '1'
	option ipv6_server '1'
	option dualstack_ip_selection '1'
	option force_aaaa_soa '0'
	option seconddns_force_aaaa_soa '1'
	option seconddns_no_rule_addr '0'
	option old_port '6053'

config server
	option type 'udp'
	option ip '211.137.58.20'
	option port '53'
	option name 'isp-cn'
	option server_group 'cn'
	option blacklist_ip '0'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name 'isp-cn'
	option ip '211.137.64.163'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name 'ali-cn'
	option ip '223.5.5.5'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name 'ali-cn'
	option ip '223.6.6.6'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name 'pod-cn'
	option ip '119.29.29.29'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name '114-cn'
	option ip '114.114.114.115'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name '114-cn'
	option ip '114.114.115.115'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'udp'
	option name 'cnnic-cn'
	option ip '1.2.4.8'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'tls'
	option name 'cloud-gw'
	option ip '1.1.1.1'
	option port '853'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'tls'
	option name 'cloud-gw'
	option ip '1.1.1.2'
	option port '853'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'tls'
	option name 'google-gw'
	option port '853'
	option ip '8.8.4.4'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'tls'
	option name 'google-gw'
	option port '853'
	option ip '8.8.8.8'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'tls'
	option name 'open-gw'
	option ip '208.67.220.220'
	option port '853'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option type 'tls'
	option name 'open-gw'
	option ip '208.67.222.222'
	option port '853'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'
	option enabled '1'

config server
	option enabled '1'
	option type 'udp'
	option name 'aliv6'
	option ip '2400:3200::1'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'

config server
	option enabled '1'
	option type 'udp'
	option name 'podv6'
	option ip '2402:4e00::'
	option port '53'
	option server_group 'cn'
	option addition_arg '-exclude-default-group'

config server
	option enabled '1'
	option type 'udp'
	option name 'baiduv6'
	option ip '2400:da00::6666'
	option port '53'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'

config server
	option enabled '1'
	option name 'googlev6'
	option ip '2001:4860:4860::8888'
	option port '853'
	option type 'tls'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'

config server
	option enabled '1'
	option name 'cloudv6'
	option ip '2606:4700:4700::1111'
	option port '853'
	option type 'tls'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'

config server
	option enabled '1'
	option name 'openv6'
	option ip '2620:0:ccc::2'
	option port '853'
	option type 'tls'
	option server_group 'passwall_proxy'
	option addition_arg '-exclude-default-group'

**重现步骤**
1. 上游DNS配置。  
dnsmasq转发6053

2. 访问的域名。  
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/39937083/200473480-0d2d15cf-22f2-4ddf-81bc-1598b5e708fa.png">

<img width="370" alt="image" src="https://user-images.githubusercontent.com/39937083/200473524-262da741-a439-4312-8d5e-1bcaa8e3679a.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/39937083/200474556-217734e8-1018-4b60-a5c8-b036760f4f2d.png">

已尝试添加到passwall的代理规则里，无效
<img width="512" alt="image" src="https://user-images.githubusercontent.com/39937083/200474302-a44eb340-807f-4385-8b18-4d8a4549a5ac.png">
添加到路由hosts里也无效
<img width="531" alt="image" src="https://user-images.githubusercontent.com/39937083/200474388-75c05bed-68d8-4a17-985b-a6176c6a0737.png">

请教各位大神，此问题如何处理？
**信息收集**  
[smartdns.log](https://github.com/pymumu/smartdns/files/9957552/smartdns.log)

**Comment by PikuZheng** [comment]
域名应答为127.0.0.1问题，请将运营商dns从上游列表中删掉。

**Comment by renhaimm** [comment]
是smartdns里配置的上游列表吗？已删除运营商dns，问题还在啊

**Comment by PikuZheng** [comment]
抱歉刚才没仔细看你的配置，首先passwall_proxy组内不能有udp的dns，这个'baiduv6'是不行的。

其次smartdns是dnsmasq的上游，那么i.ytimg.com是怎么送到第二dns服务器组的？如果是走了端口6053，那么这个cn组里也不能有被污染的dns上游，阿里百度和所有udp/53都是不行的。

建议你开debug日志，看这个127.0.0.1究竟是哪个上游返回的

**Comment by renhaimm** [comment]
两组dns，一组是通过dnsmasq转发127.0.0.1#6053，另一组是通过passwall设置dns转发127.0.0.1:6553过来的。
cn组也不能有udp吗？全部只能用doh和dot？debug日志如何开，我在openwrt里没看到有这个选项

**Comment by PikuZheng** [comment]
> 一组是通过dnsmasq转发127.0.0.1#6053，另一组是通过passwall设置dns转发127.0.0.1:6553过来的

没懂，i.ytimg.com是怎么送到第二dns服务器组的？

> debug日志如何开

自定义配置里面可以改log级别

**Comment by renhaimm** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/39937083/200500492-3998f115-928f-419a-a288-7843ad3fcaba.png">
谢谢大神解答，根据你说的dns污染这个方向，我找到原因了，我一直以为那个ipv6的地址是我的旁路由的地址，刚刚我才发现那个居然是运营商的ipv6的dns，我到主路由里找到ipv6获取dns的开关关闭后，就好了
