### ISSUE TITLE
openwrt  没看到有38.4啊

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1161]
![image](https://user-images.githubusercontent.com/7440313/200530896-2dcda8ce-8373-4cc7-9fc2-3eb20b8953c3.png)
大佬没看到 38.4啊 只有[smartdns_1.2022.38.1-1_aarch64_cortex-a53.ipk](https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/smartdns_1.2022.38.1-1_aarch64_cortex-a53.ipk)

新版本 udp  回源问题解决吗
@pymumu

**Comment by PikuZheng** [comment]
稳定版才会推送到openwrt那边去。此前请自己编译试用 🤣 作者的说明在这里 https://github.com/pymumu/smartdns/issues/1096#issuecomment-1261094570

顺便推销一波我的编译，一般这边更新4小时内自动编译https://github.com/PikuZheng/smartdns/releases

**Comment by lalasou** [comment]
好的
