### ISSUE TITLE
有没有大佬 搭配个grafana可视化出来

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1163]
这样就好多了

**Comment by mokeyish** [comment]
这个是不是也不错，把.dns 查询日志采集来，可视化
https://github.com/vectordotdev/vector

**Comment by iamyangyiok** [comment]
> 这个是不是也不错，把.dns 查询日志采集来，可视化 https://github.com/vectordotdev/vector

写个教程吧 3Q 好人一生平安
