### ISSUE TITLE
nftset似乎没有作用？

### ISSUE THREAD

**Issue by phoenixxie0** [pymumu/smartdns#1165]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. openwrt fw4 nftable

2. 运营商  

3. smartdns来源以及版本
最新git commit 
4. 涉及的配置(注意去除个人相关信息)
配置文件中设置了
`nftset /docker.com/#4:inet#filter#gfwlist`

nftable设置
`
table inet filter {
        set gfwlist {
                type ipv4_addr
                flags interval,timeout
                timeout 7d3h8m45s
        }
}
`

主机用dig docker.com后，查看表内无新增ip地址，依然为空。

**Comment by pymumu** [comment]
默认没有编译此特性。

make WITH_NFTSET=1

**Comment by phoenixxie0** [comment]
openwrt编译的时候，是在packages/net/smartdns/Makefile里加入TARGET_CFLAGS += WITH_NFTSET=1么？

**Comment by PikuZheng** [comment]
> openwrt编译的时候，是在packages/net/smartdns/Makefile里加入TARGET_CFLAGS += WITH_NFTSET=1么？

我是这么改的 https://github.com/pymumu/smartdns/commit/e925b04e9c51b5e68ecd227606c9f396ab59389b

**Comment by openips** [comment]
> > openwrt编译的时候，是在packages/net/smartdns/Makefile里加入TARGET_CFLAGS += WITH_NFTSET=1么？
> 
> 我是这么改的 https://github.com/pymumu/smartdns/commit/e925b04e9c51b5e68ecd227606c9f396ab59389b

玩的挺溜

**Comment by phoenixxie0** [comment]
加入MAKE_FLAGS+= WITH_NFTSET=1会提示
Package smartdns is missing dependencies for the following libraries:
libnftables.so.1
看来还得再修改修改

**Comment by zxlhhyccc** [comment]
> > openwrt编译的时候，是在packages/net/smartdns/Makefile里加入TARGET_CFLAGS += WITH_NFTSET=1么？
> 
> 我是这么改的 [e925b04](https://github.com/pymumu/smartdns/commit/e925b04e9c51b5e68ecd227606c9f396ab59389b)

你这样子改编译报错：
![image](https://user-images.githubusercontent.com/45259624/201830210-bdac315d-615a-4b5e-a64f-86accb58a3bb.png)

**Comment by zxlhhyccc** [comment]
> 加入MAKE_FLAGS+= WITH_NFTSET=1会提示 Package smartdns is missing dependencies for the following libraries: libnftables.so.1 看来还得再修改修改

根据上面@PikuZheng 大佬的修改，将大佬的改为override CFLAGS += -DFEATURE_DWITH_NFTSET=1即可编译过去，你可以测试一下问题解决了没有

**Comment by kulongwangzhi85** [comment]
debian下加什么都可以编译成功，但都无效。

**Comment by phoenixxie0** [comment]
> debian下加什么都可以编译成功，但都无效。 update: 要用git clone，不要用下载页面的

这里说的是修改makefile。openwrt系统

**Comment by kulongwangzhi85** [comment]
> > debian下加什么都可以编译成功，但都无效。 update: 要用git clone，不要用下载页面的
> 
> 这里说的是修改makefile。openwrt系统

根本不用修改，git clone下来后，执行作者的那条命令 make WITH_NFTSET=1

**Comment by phoenixxie0** [comment]
> > > debian下加什么都可以编译成功，但都无效。 update: 要用git clone，不要用下载页面的
> > 
> > 
> > 这里说的是修改makefile。openwrt系统
> 
> 根本不用修改，git clone下来后，执行作者的那条命令 make WITH_NFTSET=1

起您看清楚编译环境，谢谢

**Comment by phoenixxie0** [comment]
> debian下加什么都可以编译成功，但都无效。 update: 要用git clone，不要用下载页面的 update: **操作系统**
> 
> ```
>  dpkg -l | grep nftable
> ii  libnftables-dev:amd64         0.9.8-3.1
> ii  libnftables1:amd64            0.9.8-3.1
> ii  libnftnl11:amd64              1.1.9-1
> ii  nftables                      0.9.8-3.1 
> ```
> 
> **smartdns.conf**
> 
> ```
> nftset /www.baidu.com/#4:inet#mangle#direct2,#6:-
> ```
> 
> ```
> [2022-11-15 19:52:57,656][FATAL][           util.c:1198] Stack:
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #01: 0x5603916b77b7 () from /usr/sbin/smartdns+0x217b7
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #02: 0x56039169c9fb () from /usr/sbin/smartdns+0x69fb
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #03: 0x7fa29fe03140 () from /lib/x86_64-linux-gnu/libpthread.so.0+0x13140
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #04: 0x7fa29fc9d319 () from /lib/x86_64-linux-gnu/libc.so.6+0x15e319
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #05: 0x7fa29fba7f76 () from /lib/x86_64-linux-gnu/libc.so.6+0x68f76
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #06: 0x7fa29fbb99c6 () from /lib/x86_64-linux-gnu/libc.so.6+0x7a9c6
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #07: 0x7fa29fb92e52 __snprintf() from /lib/x86_64-linux-gnu/libc.so.6+0x53e52
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #08: 0x5603916b60a1 () from /usr/sbin/smartdns+0x200a1
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #09: 0x5603916b6db8 () from /usr/sbin/smartdns+0x20db8
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #10: 0x5603916a78a3 () from /usr/sbin/smartdns+0x118a3
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #11: 0x5603916aad5f () from /usr/sbin/smartdns+0x14d5f
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #12: 0x5603916ac1c1 () from /usr/sbin/smartdns+0x161c1
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #13: 0x56039169e18c () from /usr/sbin/smartdns+0x818c
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #14: 0x7fa29fdf7ea7 () from /lib/x86_64-linux-gnu/libpthread.so.0+0x7ea7
> [2022-11-15 19:52:57,656][FATAL][           util.c:1210] #15: 0x7fa29fc3ba2f clone() from /lib/x86_64-linux-gnu/libc.so.6+0xfca2f
> [2022-11-15 19:52:57,660][DEBUG][     dns_client.c:2208] recv tcp packet from 1.12.12.12, len = 103
> ```

加不加参数当然都能编译成功， 没有参数就不带nftables功能呀。

**Comment by pymumu** [comment]
用最新代码看看，修正了一个BUG，去除了libnftable依赖，默认编译就支持nftable

**Comment by pymumu** [comment]
发配置，发log

**Comment by phoenixxie0** [comment]
`log-level debug`
`log-size 128k`
`log-file /var/log/smartdns.log`
`audit-enable yes`
`audit-file /var/log/smartdns-audit.log`
`nftset-debug yes`
`nftset /docker.com/#4:inet#filter#gfwlist,#6:-`

![image](https://user-images.githubusercontent.com/1797318/201974039-5232ab75-e3bb-4fb4-9038-03fd931ce6df.png)

nftables配置
`table inet filter {
        set gfwlist {
                type ipv4_addr
                flags interval,timeout
                timeout 7d3h8m45s
        }
}`

**Comment by kulongwangzhi85** [comment]
> 发配置，发log

在debian中已经成功插入到nftables 集合了。谢谢大佬

**Comment by phoenixxie0** [comment]
inet类型的表已经能够成功添加IP，但是ip类型的表，似乎还是有点问题

**Comment by pymumu** [comment]
@phoenixxie0 修正了一下。

**Comment by kulongwangzhi85** [comment]
> @phoenixxie0 修正了一下。

能否对nftset也设置白名单与黑名单设置

**Comment by phoenixxie0** [comment]
> 

白名单黑名单的意思是？

**Comment by phoenixxie0** [comment]
> > @phoenixxie0 修正了一下。
> 
> 能否对nftset也设置白名单与黑名单设置

白名单黑名单的意思是？

**Comment by phoenixxie0** [comment]
> @phoenixxie0 修正了一下。

OK了，已经能够将地址加入到set了。但是目前发现加入的的地址是地址段，掩码好像有点问题，不知道是nftables的问题还是smartdns的问题，抽时间调试以下才知道

**Comment by kulongwangzhi85** [comment]
> > > @phoenixxie0 修正了一下。
> > 
> > 
> > 能否对nftset也设置白名单与黑名单设置
> 
> 白名单黑名单的意思是？

nftset集合中有fakeip地址段，我设置有nftset的domain-set，想使用默认分组来解析，当不知为何有些域名会得到fakeip的ipv6的地址，也就是国外分组的地址。
而且我明确设置domain-set的集合排除国外分组（就是不知道语法对不对）

目前用nftables规则来规避这个问题，不影响使用。

```
domain-set -name proxylist -type list -file /etc/smartdns/proxy-list.txt
domain-rules /domain-set:proxylist/ -c none -n v2ray
domain-set -name mygfwset -type list -file /etc/smartdns/mygfw.txt
domain-rules /domain-set:mygfwset/ -c none  -n v2ray

domain-set -name directset -type list -file /etc/smartdns/google-cn.txt
domain-set -name directset-1 -type list -file /etc/smartdns/direct-list.txt
domain-set -name directset-2 -type list -file /etc/smartdns/apple-cn.txt
domain-set -name directset-3 -type list -file /etc/smartdns/mydirect.txt
domain-rules /domain-set:directset/ -n -v2ray
domain-rules /domain-set:directset-1/ -n -v2ray
domain-rules /domain-set:directset-2/ -n -v2ray
domain-rules /domain-set:directset-3/ -n -v2ray

nftset /domain-set:directset/#4:inet#mangle#direct2,#6:inet#mangle#direct2-6
nftset /domain-set:directset-1/#4:inet#mangle#direct2,#6:inet#mangle#direct2-6
nftset /domain-set:directset-2/#4:inet#mangle#direct2,#6:inet#mangle#direct2-6
nftset /domain-set:directset-3/#4:inet#mangle#direct2,#6:inet#mangle#direct2-6
```
