### ISSUE TITLE
在不连节点的前提下，”smartdns“有没有办法改善“github”这类“半墙类”网页的连通性

### ISSUE THREAD

**Issue by wzy105** [pymumu/smartdns#1169]
已经设置测试模式了 ”speed-check-mode tcp:443,tcp:80,ping“，网页不应该是必定打得开吗？为什么github还经常打不开，要过两三分钟再刷新。
下面是我的配置，还请老师们指点迷津！

#------domestic---------------
server 223.6.6.6:53 -group cn -exclude-default-group
server 114.114.115.115:53 -group cn -exclude-default-group
server 119.6.6.6:53 -group cn -exclude-default-group
server 223.5.5.5:53 -group cn -exclude-default-group
server 121.4.4.75:53 -group cn -exclude-default-group
server-tls 1.12.12.12:853 -group cn -exclude-default-group

#------------------foreign----------------------------------------------
server-https https://146.112.41.2/dns-query -group gfw
server-https https://103.2.57.6/dns-query -group gfw
server-https https://9.9.9.10/dns-query -group gfw
server-https https://101.102.103.104/dns-query -group gfw
#-----------------------------------------------------------------
force-qtype-SOA 65
speed-check-mode tcp:443,tcp:80,ping
#国内域名 命中走"group cn"
conf file /etc/smartdns/rules/chinalist.conf

**Comment by PikuZheng** [comment]
问：你配置github和gitusercontent走国内还是国外组

**Comment by wzy105** [comment]
> 问：你配置github和gitusercontent走国内还是国外组

走的国外组

**Comment by Xymmh** [comment]
根本原因：因为能ping通或者tcping通并不代表能打开

**Comment by cresky-github** [comment]
只能走代理，
smartdns的作用是获得“正确”的IP，获得“正确”的IP之后，smartdns无能为力。

**Comment by wzy105** [comment]
> 根本原因：因为能ping通或者tcping通并不代表能打开

原来如此，我还以为tcp80、443是测试http https能不能打开的意思😂。
  为什么会出现这种间断性打不开的情况呢，有没有解决的方法

**Comment by wzy105** [comment]
> 只能走代理， smartdns的作用是获得“正确”的IP，获得“正确”的IP之后，smartdns无能为力。

github没被墙吧？（应该），为什么有时会打不开😭🙈

**Comment by Xymmh** [comment]
【Github 越来越难上去了， TMD 到底是怎么回事？】
https://www.v2ex.com/t/761558

**Comment by cresky-github** [comment]
> > 只能走代理， smartdns的作用是获得“正确”的IP，获得“正确”的IP之后，smartdns无能为力。
> 
> github没被墙吧？（应该），为什么有时会打不开😭🙈



为什么要考虑墙不墙的？

明明有更好线路不走，又是为何？

**Comment by wzy105** [comment]
> > > 只能走代理， smartdns的作用是获得“正确”的IP，获得“正确”的IP之后，smartdns无能为力。
> > 
> > 
> > github没被墙吧？（应该），为什么有时会打不开😭🙈
> 
> 为什么要考虑墙不墙的？
> 
> 明明有更好线路不走，又是为何？

因为学习smart和adghome已经花费了很多时间😂😂

**Comment by wzy105** [comment]
> > > 只能走代理， smartdns的作用是获得“正确”的IP，获得“正确”的IP之后，smartdns无能为力。
> > 
> > 
> > github没被墙吧？（应该），为什么有时会打不开😭🙈
> 
> 为什么要考虑墙不墙的？
> 
> 明明有更好线路不走，又是为何？

这样看来搞dns是真有点鸡肋🙈

**Comment by cresky-github** [comment]
> > > > 只能走代理， smartdns的作用是获得“正确”的IP，获得“正确”的IP之后，smartdns无能为力。
> > > 
> > > 
> > > github没被墙吧？（应该），为什么有时会打不开😭🙈
> > 
> > 
> > 为什么要考虑墙不墙的？
> > 明明有更好线路不走，又是为何？
> 
> 因为学习smart和adghome已经花费了很多时间😂😂



看来，你对DNS理解有误，
DNS，作用是把域名解析成IP，也就是一个翻译。

以后的事是线路的事，DNS已经完成了工作。

**Comment by PikuZheng** [comment]
> github没被墙吧？（应该），为什么有时会打不开😭🙈

不是所有的节点都被墙。如果解析到新加坡那边，和amazon aws在一起就是会被墙。

墙有几种不同的行为，最常见的是给TCP连接发RST包。但是在RST之前，TCP连接已握手，测速已经完成了。
