### ISSUE TITLE
mydomain.com:xxxx的dns请求出现_xxxx.mydomain.com记录，大量https类型的dns请求，大量addr.arpa请求

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1170]
smartdns作为Adguard Home的上游dns，用PikuZheng大佬编译的最新版本的smartdns，从38.1.x开始，在Adguard Home的日志记录中出现了以下3种奇怪的dns请求记录

1：_xxxx.mydomain.com，其中mydomain是我自己的域名，xxxx是我npm的端口号，之前从来没有出现过，
比如访问mysubdomain.mydomain.com:8654，Adguard Home中dns查询记录既有mysubdomain.mydomain.com的记录，也有_8654.mydomain.com的记录。
2：出现了大量HTTPS类型的dns请求，之前只有ios相关的域名才有此类型的dns请求，现在大量常规的域名也出现了https类型的请求。
3：出现了大量lb._dns-sd._udp.0.10.10.10.in-addr.arpa类型的dns请求，之前从来没有出现过，其中10.10.10.0是我的内网IP段。

在更新了v38.1.11版本后，1、2现象消失，3还在，有大佬能帮忙解答一下这是什么情况吗，我刚刚装回了v38.1.10版本后，也不会出现1、2现象的dns请求了，所以目前只有3类型的截图。

![image](https://user-images.githubusercontent.com/10081071/202403653-0f2615c4-7067-4448-bcda-373232fd8252.png)

**Comment by PikuZheng** [comment]
这是ptr类型的DNS记录查询啊 作为DNS来说是常见且正常的 要不你还是看看哪个应用程序在做这些查询吧

**Comment by pymumu** [comment]
这些是DNS发现服务的请求，看看是哪些客户的发送的请求。

**Comment by yyysuo** [comment]
抓到了
首先是google的dns请求，同时有一个https类型的和普通的
![image](https://user-images.githubusercontent.com/10081071/202466667-41f890b3-57d9-40df-b500-bac61edd2026.png)


github也有
![image](https://user-images.githubusercontent.com/10081071/202466785-138a3b5a-3a84-46a9-a928-ba2fe07865e2.png)

电报的
![image](https://user-images.githubusercontent.com/10081071/202466875-baa132c5-1ac5-4cdf-b786-afe69c89832a.png)


我自己域名的解析记录，其实是同一时间同一域名的解析
![image](https://user-images.githubusercontent.com/10081071/202467076-3f084fad-0738-434a-acd0-62fda6f6a2e2.png)

**Comment by yyysuo** [comment]
都是我一台docker机器的访问请求，想起来了，这些请求全是我的笔记本通过wirguard连接100docker这台机器回到家后产生的dns请求。

**Comment by yyysuo** [comment]
![image](https://user-images.githubusercontent.com/10081071/202478013-eccf50f9-1719-44b5-b2fa-e080433bc025.png)

看dns日志问题能发现一些奇怪的东西。

**Comment by PikuZheng** [comment]
有没有可能，这几个程序做了流量特征伪装。或者自身一些检测功能。

近期一个升级是，之前查询上游失败的，会超时（没有应答）。现在是透传了上游的查询失败信息，会产生应答记录。总之看起来是正常的dns查询-应答，不太可能是smartdns软件问题

**Comment by yyysuo** [comment]
> 有没有可能，这几个程序做了流量特征伪装。或者自身一些检测功能。
> 
> 近期一个升级是，之前查询上游失败的，会超时（没有应答）。现在是透传了上游的查询失败信息，会产生应答记录。总之看起来是正常的dns查询-应答，不太可能是smartdns软件问题

同意，只是看不懂这些请求，并不确定这些dns请求是不正常的。发出来只是想学习讨论一下。
