### ISSUE TITLE
smartdns解析返回的ipv4/ipv6地址不全，或者缺失ipv6地址

### ISSUE THREAD

**Issue by wolonggl** [pymumu/smartdns#1171]
**问题现象**  

smartdns做主dns使用，监听53端口，分了3组域名解析组，分别为china/foreign, 分别对应国内组，国外组；
上游DNS分别为 114.114.114.114和8.8.8.8/tcp
8.8.8.8通过v2ray重定向到墙外服务器解析；

有时候通过 nslookup测试无法解析到ipv6地址，但是通过 nslookup -vc www.google.com 8.8.8.8 可以正常解析ipv4/ipv6地址
过段时间可能又恢复了

**运行环境**
openwrt x86

2. 运营商  

3. smartdns来源以及版本
Release38.1-19

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
foreign关闭测速和双栈优选
