### ISSUE TITLE
日志里经常会出现 recv ping packet from 192.xxx.xxx.xxx failed.

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#1172]
**问题现象**  
日志里经常会出现：
`icmp type faild, 3:0`
`recv ping packet from 192.xxx.xxx.xxx failed.`

**运行环境**
1. 固件型号  
`Linux OpenWrt 5.15.79 #0 SMP Thu Nov 17 19:36:57 2022 x86_64 GNU/Linux`
`docker version 20.10.17`
2. 运营商  
四川电信
3. smartdns来源以及版本
Github 最新源码(#ad4c2144da034701cb957ae682b784ad0e73b4ef)自行编译

![1](https://user-images.githubusercontent.com/38558065/202855380-c4923eb9-60c5-439b-aec5-8e7cb0c67621.png)

**Comment by pymumu** [comment]
这个是debug日志，可以忽略。
很多这个log吗？

**Comment by devioa** [comment]
> 这个是debug日志，可以忽略。 很多这个log吗？

不算是很多，但是出现挺频繁的，想问下出现这个是什么原因吗，如果有必要我可以troubleshooting

**Comment by pymumu** [comment]
tcpdump icmp看看吧
这个有些机器上会出现，不知道原因

**Comment by devioa** [comment]
> tcpdump icmp看看吧 这个有些机器上会出现，不知道原因

tcpdump提示端口不可达，同时看了下日志，确实tcpdump出现`ICMP 192.168.1.200 udp port xxxxx unreachable`的时候
日志就出现`icmp type faild, 3:0` `recv ping packet from 192.xxx.xxx.xxx failed.`
![1](https://user-images.githubusercontent.com/38558065/202878600-61f858e4-93fc-4cfa-a654-880f737d8067.png)

**Comment by pymumu** [comment]
优化了一下log打印。
