### ISSUE TITLE
master最新代码cache-file参数失效

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#1173]
**问题现象**  
代码使用commit bea238e7ae1966894ba26d755320415127531a26
cache参数
```
cache-persist yes
cache-file /tmp/smartdns.cache
```
**运行环境**
1. 固件型号  
X64

**重现步骤**
1、配置完毕cache参数 正确启动smartdns
2、ls /tmp/ 没有任何smartdns相关文件

**Comment by pymumu** [comment]
进程安全退出才会保存cache

**Comment by quango-web** [comment]
路由 openwrt
改放置路径：cache-file /var/cache/smartdns.cache，使用几天可见文件体积逐渐增大，但是重启路由后又变回48B的默认体积，请教作者大佬是否正常。

**Comment by openips** [comment]
果然如此

**Comment by pymumu** [comment]
> 路由 openwrt 改放置路径：cache-file /var/cache/smartdns.cache，使用几天可见文件体积逐渐增大，但是重启路由后又变回48B的默认体积，请教作者大佬是否正常。

/var目录是非持久化的。
你可以指定到/etc/smartdns/smartdns.cache
