### ISSUE TITLE
nftset功能出现奇怪的地址段。

### ISSUE THREAD

**Issue by phoenixxie0** [pymumu/smartdns#1174]
**问题现象**  
简要描述问题出现的现象
nftset在生成对应表中elements的时候，本应该是单个地址，却出现地址段。
nftset功能出现奇怪的地址段。
**运行环境**
OpenWrt
1. smartdns来源以及版本
git last commit 

4. 涉及的配置(注意去除个人相关信息)

**信息收集**  
![image](https://user-images.githubusercontent.com/1797318/202905292-cf913929-0b22-4126-a8bf-3bdf500331a2.png)
![image](https://user-images.githubusercontent.com/1797318/202905300-ecd16242-6e57-4b0f-ac80-9d88e643261f.png)

**Comment by phoenixxie0** [comment]
![image](https://user-images.githubusercontent.com/1797318/202905343-34897093-2587-413a-914c-83e6c511a9f8.png)
运行dig命令，应该解析到的只有8.8.8.8和8.8.4.4.
并且smartdns日志也显示只有这两条地址
![image](https://user-images.githubusercontent.com/1797318/202905460-ed652c4b-f3ac-41e6-beb6-2217213b45d0.png)
但是nftables内却出现
![image](https://user-images.githubusercontent.com/1797318/202905493-3be22482-1708-4668-aa43-c339a131b2ca.png)
在解析过一部分域名后，会使得表内几乎涵盖所有IP段。导致在利用gfwlist匹配流量的时候，会几乎把所有地址都转发了

**Comment by pymumu** [comment]
为什么要用interval？，smartdns只会添加一个ip，不会添加ip段

**Comment by phoenixxie0** [comment]
> 为什么要用interval？，smartdns只会添加一个ip，不会添加ip段

哦哦哦，发现了，原来是这样啊。本来我也没有使用interval。是因为想设置一些ip段，比如tg的地址段。

**Comment by pymumu** [comment]
最新代码修正了这种情况。
