### ISSUE TITLE
如何直接用本地另一个dns服务器返回连接

### ISSUE THREAD

**Issue by 4thanks** [pymumu/smartdns#1175]
openwrt同时有mosdns和smartdns，smartdns作为dnsmasq上游，之前有段时间捣鼓mosdns发现个别国外网站比较容易连接，现在换回smartdns用相似dns配置比较难或小概率，不知道是不是因为测速还是双栈的影响或其他原因。

```
server 127.0.0.1:5533 -group mosdns -exclude-default-group
domain-rules /example.com/ -c none -n mosdns -d no
```
以上配置好像不太行，另外觉得[0498521](https://github.com/pymumu/smartdns/commit/04985216a877f3a674953ac22a11bb5c2c026e7d)分组缓存后的版本好像解析变慢了，不知道是不是错觉，退会之前的版本就好很多。

**Comment by PikuZheng** [comment]
我记得dnsmasq可以指定单个域名转发给特定的上游服务器。
用smartdns，可能有edns消息丢失的问题

**Comment by pymumu** [comment]
你的配置没看出问题。应该是正确工作的。
可以看一下debug日志，看看example.com的请求是否发送到5533端口。

拆分缓存后，缓存都是分开的，可以保持所有绑定端口的缓存开启。

**Comment by pymumu** [comment]
不会

**Comment by yyysuo** [comment]
套娃就好了啊，把mosdns作为smartdns上游，我是Adguard Home-》smartdns-》mosdns-》Adguard Home

**Comment by 4thanks** [comment]
> 套娃就好了啊，把mosdns作为smartdns上游，我是Adguard Home-》smartdns-》mosdns-》Adguard Home

😂我这个也是套娃，所以问问请求返回有没有干扰或丢失

**Comment by yyysuo** [comment]
> > 套娃就好了啊，把mosdns作为smartdns上游，我是Adguard Home-》smartdns-》mosdns-》Adguard Home
> 
> 😂我这个也是套娃，所以问问请求返回有没有干扰或丢失

我这个架构，可以通过最下游的Adguard Home看出来，没什么丢失啊。
另外我架构上面写错了，是：Adguard Home-》mosdns-》smartdns-》Adguard Home

**Comment by rampageX** [comment]
> > 我记得dnsmasq可以指定单个域名转发给特定的上游服务器。 用smartdns，可能有edns消息丢失的问题
> 
> 搜了下，但好像不支持端口号？
> 
> ```
> server=/cn/114.114.114.114
> ```

server=/cn/114.114.114.114#5353

**Comment by 4thanks** [comment]
> > 假如`-group mosdns -exclude-default-group`排除分组解析失败后，还会继续向deault默认组请求解析吗？
> > 
>  不会

```
server 114.114.114.114
server 127.0.0.1:5533 -group mosdns
domain-rules /example.com/ -c none -n mosdns -d no

```
以上如果不加`-exclude-default-group`，是不是example.com优先走mosdns再向default组请求解析？
