### ISSUE TITLE
请问对于空ip的解析是怎么处理的呢

### ISSUE THREAD

**Issue by Bitcion** [pymumu/smartdns#1176]
最近发现binance.com很多国内dns的污染方式是返回空ip
如果在这个dns解析组里加入一个有ip的响应，是自动忽略掉空ip的响应吗

希望是这么处理的，最好还忽略空ip的缓存（缓存也没啥意义）

**Comment by PikuZheng** [comment]
最新版是透传上游错误码。如果上游有IP应答，那么就按照测速缓存什么的流程走一遍。
空域名缓存是已知bug，忘了修没修了

**Comment by Bitcion** [comment]
> 一半以上的上游都返回0.0.0.0的话，才会返回0.0.0.0给客户端，否则该结果丢弃。

补充个其他问题：
在adguardhome中，屏蔽ipv6是两条记录，比如
||v2ex.com^$dnstype=AAAA
||v2ex.com^$dnstype=~A|~CNAME

似乎smartdns只是舍弃了aaaa，另一条是不是没有处理？我把adguardhome也加到上游dns了，看不到aaaa记录，似乎能到另一条的记录

**Comment by pymumu** [comment]
cname是别名，屏蔽广告用

**Comment by pymumu** [comment]
ios的这个问题和cname没有关系，这个是HTTPS记录，配置下面的选项屏蔽。
```
force-qtype-SOA 65
``

**Comment by Bitcion** [comment]
> force-qtype-SOA 65

感谢，另外这个可以写到bind 中生肖吧？我的需求只是把国外解析屏蔽v6

**Comment by pymumu** [comment]
这个不是屏蔽ipv6，是屏蔽ios设备的https记录
屏蔽ipv6用force-soa-AAAA

**Comment by Bitcion** [comment]
> 这个不是屏蔽ipv6，是屏蔽ios设备的https记录
> 屏蔽ipv6用force-soa-AAAA

我目的就是屏蔽国外解析的ipv6，所以把force-soa-AAAA force-qtype-SOA 65 都写进国外分组的bink了。我看了下文档，好像用force-qtype-SOA 65 28 只有这一条也能实现屏蔽ipv6？

我是拿dns分流的，直连用ipv6，分流用ipv4透明代理

**Comment by pymumu** [comment]
```
domain-rule /domain/  -address #6 -group oversea -speed-check-mode none
force-qtype-SOA
```
