### ISSUE TITLE
来自 ::1 的回复: 时间<1ms

### ISSUE THREAD

**Issue by majahgg** [pymumu/smartdns#1177]
打不开52破解了！！！！

C:\Users\Administrator>ping www.52pojie.cn

正在 Ping www.52pojie.cn [::1] 具有 32 字节的数据:
来自 ::1 的回复: 时间<1ms
来自 ::1 的回复: 时间<1ms
来自 ::1 的回复: 时间<1ms
来自 ::1 的回复: 时间<1ms

之前一直在用ipv4+ipv6正常
现在同样的配置升级了新的openwrt固件smartdns的新版本，52破解和恩山等个别站进不去了！
是固件问题还是smartdns问题？求解决！

smartdns停用IPV6地址解析 52破解和恩山等个别站可以进去了，但个人需要ipv6解析,不想停用IPV6地址解析 。

**Comment by zxlhhyccc** [comment]
> 打不开52破解了！！！！
> 
> C:\Users\Administrator>ping [www.52pojie.cn](http://www.52pojie.cn)
> 
> 正在 Ping [www.52pojie.cn](http://www.52pojie.cn) [::1] 具有 32 字节的数据: 来自 ::1 的回复: 时间<1ms 来自 ::1 的回复: 时间<1ms 来自 ::1 的回复: 时间<1ms 来自 ::1 的回复: 时间<1ms
> 
> 之前一直在用ipv4+ipv6正常 现在同样的配置升级了新的openwrt固件smartdns的新版本，52破解和恩山等个别站进不去了！ 是固件问题还是smartdns问题？求解决！
> 
> smartdns停用IPV6地址解析 52破解和恩山等个别站可以进去了，但需要用个人需要ipv6解析,不想停用IPV6地址解析 。

应该是你的配置问题。。。我IP4没问题。。。

**Comment by pymumu** [comment]
这个域名应该没有V6地址

打开debug看看这个v6地址那里来的

**Comment by lalasou** [comment]
28.1没问题 就 这个github上的 最新的貌似会有..
