### ISSUE TITLE
-no-cache可以用在server 上吗

### ISSUE THREAD

**Issue by Bitcion** [pymumu/smartdns#1178]
看介绍是用在bind上的
比如两个上游dns，可信与不可信混用，然后指定不可信不缓存。
这样第一次一般用速度更快的不可信，结果也可能被污染。但是因为并行又指定不缓存，第二次就默认用可信的缓存了，这样有速度又不怕污染

**Comment by PikuZheng** [comment]
逻辑上是对的，但是实际上客户端会缓存第一次查询的结果，在第一次查询结果ttl超时前，不会发起第二次查询

**Comment by pymumu** [comment]
用black-ip-list和white-ip-list应用到server上。

**Comment by Bitcion** [comment]
> 逻辑上是对的，但是实际上客户端会缓存第一次查询的结果，在第一次查询结果ttl超时前，不会发起第二次查询

多设备就好了呀，ios缓存访问失败，接力其他设备就行了呀

**Comment by Bitcion** [comment]
> 用black-ip-list和white-ip-list应用到server上。
那server 能用 no catch嘛
黑白名单已经在用了，我是想在国内dns组里加个dot的dns，尽量用他的缓存。原因是有说国内dns对type65支持不够好的，然后65好像对ipv6又支持挺好的，我想让国内流量尽量用v6

**Comment by PikuZheng** [comment]
> 用black-ip-list和white-ip-list应用到server上。

我这边一些污染。会把网站解析到facebook上。如果用了blacklist，可能导致facebook无法访问。我觉得blacklist还是要慎用。

> 我是想在国内dns组里加个dot的dns，尽量用他的缓存

那就是大缓存的阿里喽。但是对于ip变化了的情况，阿里比较消极。

> 多设备就好了呀，ios缓存访问失败，接力其他设备就行了呀

啥意思，比如我要用手机开facebook，由于污染打不开。然后此时我要换个手机开facebook，直到ttl超时后再把手机换回去？

**Comment by Bitcion** [comment]
> 
> 啥意思，比如我要用手机开facebook，由于污染打不开。然后此时我要换个手机开facebook，直到ttl超时后再把手机换回去？

对呀，开个玩笑。
实际上开关wifi，或者换个新号。ios设备上的私有地址开关，清理缓存很方便的

**Comment by PikuZheng** [comment]
> 实际上开关wifi，或者换个新号。ios设备上的私有地址开关，清理缓存很方便的，ttl不是很大的问题

这倒是，关WiFi重连就好了。Windows倒是麻烦点，要敲命令。但终归还是多了一步，耽误了几秒钟时间。要是用chrome的话估计要近一分钟了。

其实blacklist设计初衷就是从结果中排除污染IP。如果污染的IP有迹可循，用blacklist更直接好用。

**Comment by cresky-github** [comment]
> > 实际上开关wifi，或者换个新号。ios设备上的私有地址开关，清理缓存很方便的，ttl不是很大的问题
> 
> 这倒是，关WiFi重连就好了。Windows倒是麻烦点，要敲命令。但终归还是多了一步，耽误了几秒钟时间。要是用chrome的话估计要近一分钟了。
> 
> 其实blacklist设计初衷就是从结果中排除污染IP。如果污染的IP有迹可循，用blacklist更直接好用。

Windows，禁用缓存就好了
