### ISSUE TITLE
安装时 报dirname缺参数

### ISSUE THREAD

**Issue by kyleli666** [pymumu/smartdns#1179]
**问题现象**  
安装时 报“dirname缺参数”

**运行环境**
1. Ubuntu 22.04

3. smartdns来源以及版本： smartdns.1.2022.10.22-1309.x86_64-linux-all.tar.gz

**重现步骤**
1. 按照readme标准linux安装步骤安装
2. 执行./install -i 时报错 “dirname缺参数”

**信息收集**  
1. 已发现问题所在
    install脚本的`get_systemd_path()`中，```SERVICE_PATH="`systemctl show $service | grep FragmentPath | awk -F'=' '{print $2}'`"```，无法得到正确的结果。 ```systemctl show $service ```输出的这个service缺少`FragmentPath`属性，但有似乎类似的`Where`属性
3. 我个人的方法如下，不知是否合适推广
    将上述语句改为如下后，可以安装成功：
    ```SERVICE_PATH="`systemctl show $service | grep -E "FragmentPath|Where" | awk -F'=' '{print $2}'`"```

**Comment by kyleli666** [comment]
和 Ubuntu 20.04 对比了一下，应该时不同的service内容不一样，可能不是Ubuntu 22.04特有的问题

**Comment by pymumu** [comment]
我容器跑了22.04验证时OK的。

你用bash -i ./install -i执行下，把log发一下

**Comment by kyleli666** [comment]
> 我容器跑了22.04验证时OK的。
> 
> 你用bash -i ./install -i执行下，把log发一下

应该不是Ubuntu22.04特有的问题，只是恰巧在我的Ubuntu22.04里，安装脚本选择到了一个systemd service不巧没有FragmentPath属性，但是有Where属性。

**Comment by pymumu** [comment]
发一下具体unit的内容

**Comment by pymumu** [comment]
优化了一下，可以验证看看。

**Comment by kyleli666** [comment]
> 优化了一下，可以验证看看。

可以了。前两个查找方式都是空，用了最后一种，囧。

**Comment by kyleli666** [comment]
@pymumu 非常抱歉，上次没有完整测试。今天重装之后发现提示“cannot find systemd path”
感觉原因是install脚本get_systemd_path()里最后这个if条件不需要“!”，删去后安装成功。
```
	SERVICE_PATH="/lib/systemd/system"
	if [ ! -d "$SERVICE_PATH" ]; then
		echo "$SERVICE_PATH"
		return 0
	fi
```
非常抱歉

**Comment by pymumu** [comment]
修正了
