### ISSUE TITLE
开启 重定向53端口到 smartdns 导致 ShadowSocksR Plus+ 失效。

### ISSUE THREAD

**Issue by vvyoko** [pymumu/smartdns#118]
**问题现象**  
作为dnsmasq上游 失效于是选择 重定向53端口到 smartdns
结果 导致 ShadowSocksR Plus+ 失效。
ShadowSocksR Plus+设置如图：两种DNS解析方式都无效
https://i.loli.net/2019/03/19/5c90674999be9.png

**运行环境**
1. 固件型号  
K2P PandoraBox 19.02 2019-02-01-git-93f2639a7 / LuCI Master (git-19.026.77036-498ca21)

2. 运营商  
中国电信

**重现步骤**
1. 上游DNS配置。  
config server
	option enabled '1'
	option type 'udp'
	option ip '119.29.29.29'
	option name 'Dnspod'
	option blacklist_ip '1'

config server
	option enabled '1'
	option type 'udp'
	option ip '180.76.76.76'
	option name '百度'
	option blacklist_ip '1'

config server
	option enabled '1'
	option type 'udp'
	option ip '114.114.114.114'
	option name '114'
	option blacklist_ip '1'

config server
	option enabled '1'
	option type 'udp'
	option name '清华'
	option ip '101.6.6.6'
	option blacklist_ip '1'
	option server_group 'Tsinghua'
	option check_edns '0'

config server
	option enabled '1'
	option ip '1.1.1.1'
	option name 'CloudFlare'
	option type 'tls'
	option check_edns '1'

config server
	option enabled '1'
	option ip '8.8.4.4'
	option name 'google'
	option type 'tls'
	option check_edns '1'
	
	config server
	option enabled '1'
	option ip '8.8.8.8'
	option name 'google'
	option type 'tls'
	option check_edns '1'

config server
	option enabled '1'
	option ip '9.9.9.9'
	option name 'IBM'
	option type 'tls'
	option check_edns '1'

2. 访问的域名。  
任意不可访问域名如 google twitter

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by vvyoko** [comment]
日志好像没传上来，传个Firefox sendhttps://send.firefox.com/download/3e96325a52/#LVKFJUzgNyGYR_c_hyPcwg

**Comment by pymumu** [comment]
你的问题原因不是很清楚。

但建议你，配合某些软件用的话，要搞清楚DNS解析流程，IP发送流程。
如果不通，可以将重定向功能关闭，将smartdns设置为主DNS的上游。

**Comment by shikkoku** [comment]
你要把smartdns的本地端口改成5335重定向改成无，并且SSR+设置成使用本地5335端口服务。

**Comment by JameryP** [comment]
> 你要把smartdns的本地端口改成5335重定向改成无，并且SSR+设置成使用本地5335端口服务。

这样不走ssr的不是用不到smartdns了吗

**Comment by shikkoku** [comment]
> > 你要把smartdns的本地端口改成5335重定向改成无，并且SSR+设置成使用本地5335端口服务。
> 
> 这样不走ssr的不是用不到smartdns了吗

用得到的，你大可以自己检验一下结果。
