### ISSUE TITLE
用" -exclude-default-group"隔离后，默认组的设置还对其有效吗

### ISSUE THREAD

**Issue by wzy105** [pymumu/smartdns#1180]
![image](https://user-images.githubusercontent.com/117211092/204127934-1fd3675d-2c54-4f25-bbdf-9e7cd0501fb3.png)

**Comment by PikuZheng** [comment]
"默认组的设置" 是什么？配置方法里没有针对上游服务器组的配置

**Comment by cnclg** [comment]
@PikuZheng 你编译的1.17版本，有带edns,有不带的，有什么区别？谢谢！

**Comment by wzy105** [comment]
> "默认组的设置" 是什么？配置方法里没有针对上游服务器组的配置

'默认组的设置“就是图里的常规设置

**Comment by wzy105** [comment]
> @PikuZheng 你编译的1.17版本，有带edns,有不带的，有什么区别？谢谢！

哎兄弟你这”打广告“打的贼6呀（狗头）

**Comment by wzy105** [comment]
> "默认组的设置" 是什么？配置方法里没有针对上游服务器组的配置
 
 “默认组设置”就是图里的”常规设置“。
例如a组加了”-exclude-default-group”，那么”常规设置“里的配置对a组还生效吗

 还有如果自定义设置里加了“speed-check-mode ping,tcp:80”，但是第二DNS服务器有设置了跳过测速，那哪个设置会生效呢？

                                                                                
                                                                              还望老师傅指点迷津

![image](https://user-images.githubusercontent.com/117211092/204133955-18f2b0f9-bd89-45c8-b75a-df5520a13bcf.png)

**Comment by PikuZheng** [comment]
> @PikuZheng 你编译的1.17版本，有带edns,有不带的，有什么区别？谢谢！

！重要 自本编译起，增加“check-edns”静态编译，对应启用 server .... -check-edns的版本。选用此版本须在对应 server 参数中增加 -check-edns 后，edns-client-subnet 方能生效（普通版本edns-client-subnet对所有server生效）。参见https://github.com/pymumu/smartdns/issues/1060 。同时 docker 增加 tag:check-edns 标签对应此版本。

**Comment by PikuZheng** [comment]
> '默认组的设置“就是图里的常规设置

估计你看了最终生成的配置文件就明白了。“默认组”和“第二服务器组”对应的是侦听端口和全局设置。exclude-default-group是“上游服务器组”的设置，二者没太大关联。可以简单的理解为，“上游服务器组”是smartdns作为dns客户端向上级查询时的配置。“默认组”和“第二服务器组”是smartdns作为dns服务端针对终端设备的配置（不完全是





> 例如a组加了”-exclude-default-group”，那么”常规设置“里的配置对a组还生效吗

这两个地方都叫“组”，但是不同的“组”，具体看最终生成的配置文件。默认在 /var/etc/smartdns/smartdns.conf



> 还有如果自定义设置里加了“speed-check-mode ping,tcp:80”，但是第二DNS服务器有设置了跳过测速，那哪个设置会生效呢？

都生效

**Comment by icons88** [comment]
还有第二组不设置跳过缓存会不会造成DNS和默认组污染呢？

**Comment by PikuZheng** [comment]
> 还有第二组不设置跳过缓存会不会造成DNS和默认组污染呢？

新版已经纠正了这个问题
