### ISSUE TITLE
请问“转换成smartdns格式”的自动脚本怎么写

### ISSUE THREAD

**Issue by wzy105** [pymumu/smartdns#1184]
之前已经在网上找到脚本了，但是”这个脚本“只能把域名前后都有字的转换成smdns的格式。
                         
              “这个脚本”如下：把 server=/domain/114.114.114.114 转成 nameserver /domain/china

sed -i "s/^server=\/\(.*\)\/[^\/]*$/nameserver \/\1\/china/g;/^nameserver/!d" /tmp/smartdns/china.conf 2>/dev/null

------------------------
 如果是把 domain 转换成 nameserver /domain/group  ，应该怎么写这串代码呢 ！？

**Comment by PikuZheng** [comment]
建议用Emeditor，可以纵向选择编辑文本
![image](https://user-images.githubusercontent.com/12579522/205215877-bf7d7845-04f7-45ab-9b3c-457d8b061008.png)
按住alt然后 框选出前半部分，之后直接键入 nameserver 即可
![image](https://user-images.githubusercontent.com/12579522/205215991-c01e2479-5ca0-4e71-8d5b-6a3f3d745db5.png)

也可用查找替换功能，Emeditor支持正则表达式查找替换
![image](https://user-images.githubusercontent.com/12579522/205216412-f17b9aa9-bd80-4883-848f-3ac00db164d3.png)
查找替换输入框后面有个 > 按钮，可以给出一些正则表达式规则提示
![image](https://user-images.githubusercontent.com/12579522/205216537-d755a543-81a7-4eaa-bdab-935cc8390ecd.png)

图省事也可以用现成的单一域名文本，然后在domain-set中引用

**Comment by hpcex** [comment]
```
#!/bin/bash

wget -qO- https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf | \
    sed "s|^server=\(.*\)/[^/]*$|nameserver \1/inside|" > /etc/smartdns/china_domain.conf

wget -qO- https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/bogus-nxdomain.china.conf | \
    sed "s|=| |" > /etc/smartdns/china_bogus.conf
    
wget -qO- https://cdn.jsdelivr.net/gh/hectorm/hmirror/data/adguard-simplified/list.txt | \
	sed "/./{s/^/address \//;s/$/\/#/}" > /etc/smartdns/adguard.conf

systemctl restart smartdns
```

**Comment by liangshixing** [comment]
单独搞到一个文件里，用domain-set来导入：
```
domain-set -name greatlist -file /etc/smartdns/great.list
nameserver /domain-set:greatlist/greatgroup
```

**Comment by wzy105** [comment]
> 单独搞到一个文件里，用domain-set来导入：
> 
> ```
> domain-set -name greatlist -file /etc/smartdns/great.list
> nameserver /domain-set:greatlist/greatgroup
> ```

👍👍👍，感谢各位师傅们
