### ISSUE TITLE
有无办法实现除了某几个域名可以返回AAAA记录，其他完全禁止IPV6 AAAA记录解析？

### ISSUE THREAD

**Issue by wuyish** [pymumu/smartdns#1185]
**问题现象**  
有无办法实现除了某几个域名可以返回AAAA记录，其他完全禁止IPV6 AAAA记录解析？

**Comment by pymumu** [comment]
改了下，最新代码，配置如下即可允许特定域名查询IPV6
```
address /domain/-
```

**Comment by wuyish** [comment]
好的，那我下载最新的源码安装一下。
现在高校有IPv6活跃度考核，但是IPv6带宽有限，只能通过这种方式解决。

**Comment by pymumu** [comment]
nameserver /domain/upstreamgroup

**Comment by wuyish** [comment]
> 下载源码重新编译？

好的。用的是ubuntu系统，源码已经下载了，有重新编译的教程吗？
