### ISSUE TITLE
最新版本存在无法打开github网站的BUG

### ISSUE THREAD

**Issue by Eay5** [pymumu/smartdns#1189]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
OpenWrt R22.12.1 / LuCI Master (git-22.339.26541-ba1f838)
2. 运营商  
电信
3. smartdns来源以及版本
[smartdns.1.2022.12.04-2030.x86_64-openwrt-all.ipk](https://github.com/pymumu/smartdns/releases/download/Release39/smartdns.1.2022.12.04-2030.x86_64-openwrt-all.ipk)
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  
114.114.114.114
114.114.115.115
223.5.5.5
180.76.76.76
2. 访问的域名。  
https://github.com/
![image](https://user-images.githubusercontent.com/37044424/205939363-70992cd1-4bd6-4c47-af68-42127fd328d3.png)
![image](https://user-images.githubusercontent.com/37044424/205939427-4f112060-9f89-4e6c-bb0c-b54e3aa3bf4b.png)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[smartdns.log](https://github.com/pymumu/smartdns/files/10167311/smartdns.log)

**Comment by PikuZheng** [comment]
请先证实github.com和gitusercontent.com解析到哪个IP了。部分IP是直连不通的。

**Comment by Eay5** [comment]
![image](https://user-images.githubusercontent.com/37044424/205940546-47963fab-63b3-4f76-acc9-4c85904f77e3.png)

**Comment by rampageX** [comment]
```
上游DNS配置。
114.114.114.114
114.114.115.115
223.5.5.5
180.76.76.76
```

你这上游一个防污染的都没有；

`182.43.124.6` 这个 IP 是中国贵州的，都上反诈中心的数据库了。

**Comment by PikuZheng** [comment]
看起来终端没有使用smartdns作为dns服务器

**Comment by Eay5** [comment]
最新编译的，可以打开，刚刚测试了一下[smartdns.1.2022.v39.0.2.x86_64-openwrt.ipk](https://github.com/PikuZheng/smartdns/releases/download/1.2022.v39.0.2/smartdns.1.2022.v39.0.2.x86_64-openwrt.ipk)

**Comment by lalasou** [comment]
？   
![image](https://user-images.githubusercontent.com/7440313/206231158-093af361-0bca-447c-9144-82191717fbef.jpeg)直接跑反诈中心去了

**Comment by HiGarfield** [comment]
要解决这个的话，可以专门设置一个防污染组，组内所有上游服务器都设置为海外的DoT或者DoH解析。然后把github相关的所有域名使用防污染组进行解析。

**Comment by PikuZheng** [comment]
> ？   
> ![image](https://user-images.githubusercontent.com/7440313/206231158-093af361-0bca-447c-9144-82191717fbef.jpeg)直接跑反诈中心去了

卧槽
