### ISSUE TITLE
能否支持 ECS 功能

### ISSUE THREAD

**Issue by Old-Pussy** [pymumu/smartdns#119]
自定义 ECS 的 IP

**Comment by pymumu** [comment]
支持ECS的场景时什么？
ECS主要应用场景是远端DNS缓存服务器，比如8.8.8.8这种，用于递归查询的时候，将客户机IP地址上报给上游，上游返回客户机最佳IP地址，ECS对客户机是没有用的。

smartdns运行在近端，类似客户机，即使将自己IP地址报上去，这个IP地址和通信使用的IP时一样的。
增加ECS只是重复了客户端IP信息，上报ECS没有任何价值，用户写错IP地址的话，还会导致返回的IP更差。

这个东西似乎也只对本地解析，代理访问网络有用。
但如果代理的话，直接使用代理解析DNS就好，不需要本地smartdns解析。

之前本来打算增加ECS，但没有明确应用场景，所以功能目前没有实现。
可以说一下你的场景。

**Comment by Old-Pussy** [comment]
@pymumu 我使用 smartdns 作为 chinadns 的上游，smartdns直连香港的 dns-over-tls 服务器，中间并不经过代理。但是我访问国外 IP 时需要经过代理。我想能不能将国外代理服务器的 IP 地址作为 ECS 信息发送给香港的 DNS 服务器。

**Comment by lix5027** [comment]
我也有需求ecs的场景,比如我是一个大内网,用smartdns做主dns,大概200-500人规模,因为不能保证ss的连接持续有效,很有可能因为不稳定,还有切换线路的时刻的dns查询,去往国外的端口没有走ss,而是走国内访问的,导致不是最优结果,我也希望有ecs,可以指定ip,来保持dns的最佳结果

**Comment by pymumu** [comment]
细化说明一下使用方法，ecs之前看过，对近端的dns没有多大用途，ecs主要使用在递归dns和权威dns间，本地dns应用的话查询时间会变长

**Comment by lix5027** [comment]
实际应用场景如下:
smartdns只作为单位内部dns. dns服务器有自己的ss线路出去专门查询污染域名
内网大概有200-500用户,用户自己有单独策略路由出访国内外线路

也就是smartdns的出国线路,和内网用户的出国线路不是同一条.

smartdns的x86 openwrt,做dns使用.

有时候会遇到smartdns的出国线路不稳定,或者切换其他ssr节点的时候,导致瞬间解析出错(因为内网用户很多,几乎每秒都有大量查询).所以希望无论smartdns server的ssr线路是否稳定,都可以通过DOH,DOT方式获取最近的正确地址.(ssr全部以香港节点为主,我的ecs会指定一个香港出口ip)

**Comment by pymumu** [comment]
按域名分流了吗？

**Comment by lix5027** [comment]
按域名分流了, china-domain 走的nameserver china,还有包括edu的,ssr的
配置如下

server 202.106.195.68 -group china -blacklist-ip
server 114.114.115.115 -group china -blacklist-ip
server 223.6.6.6 -group china -blacklist-ip
server 210.2.4.8 -group china -blacklist-ip
server 166.111.8.28 -group ts -blacklist-ip -exclude-default-group
server-tls 8.8.4.4 -group ss -blacklist-ip
server-tcp 208.67.222.222:5353 -group ss -blacklist-ip -exclude-default-group
server-https https://1.1.1.1/dns-query -group ss -blacklist-ip
server-tls 1.0.0.1 -group ss -blacklist-ip
server-tls 80.80.80.80 -group ss -blacklist-ip
server-tls 185.222.222.222 -group ss -blacklist-ip

conf-file /etc/smartdns/gfw_list.conf
conf-file /etc/smartdns/chinadomain.conf
nameserver /.edu/ts

**Comment by pymumu** [comment]
blacklist只应该对污染的服务器加，tls的国外dns不用加

**Comment by PHCSJC** [comment]
借这个话题，请教下ecs怎么开启呢？文档里没看到，只提了支持ecs。
