### ISSUE TITLE
双栈环境CNAME解析不遵循域名规则

### ISSUE THREAD

**Issue by cwbsw** [pymumu/smartdns#1192]
**问题现象**  
```
In  IP 127.0.0.1.45961 > 127.0.0.1.53: 36675+ A? pbs.twimg.com. (31)
Out IP 10.10.10.10.50307 > 1.1.1.1.53: 1+ [1au] A? pbs.twimg.com. (42)
In  IP 1.1.1.1.53 > 10.10.10.10.50307: 1 2/0/1 CNAME dualstack.twimg.twitter.map.fastly.net., A 146.75.112.159 (110)
In  IP 127.0.0.1.53 > 127.0.0.1.45961: 36675 2/0/1 CNAME dualstack.twimg.twitter.map.fastly.net., A 146.75.112.159 (110)
In  IP 127.0.0.1.42099 > 127.0.0.1.53: 28594+ AAAA? dualstack.twimg.twitter.map.fastly.net. (56)
Out IP 192.168.1.10.51829 > 223.5.5.5.53: 2+ [1au] AAAA? dualstack.twimg.twitter.map.fastly.net. (67)
In  IP 223.5.5.5.53 > 192.168.1.10.51829: 2 1/0/1 AAAA 2a04:4e42:1a::159 (95)
In  IP 127.0.0.1.53 > 127.0.0.1.42099: 28594 1/0/1 AAAA 2a04:4e42:1a::159 (95)
```
可以看到查询`pbs.twimg.com`的A记录时正确应用了规则，得到了一个A记录和CNAME，客户端继续查询该CNAME的AAAA记录时，域名规则没有生效。

**运行环境**
smartdns 1.2022.12.04-2030 x64

**Comment by pymumu** [comment]
也就是规则文件里面，并没有对应cname的规则。当第一次用域名查询时是正常的。
第二次如果用cname查询的话，因为没有规则，就会查询所有上游。
之前版本因没有拆分缓存，会缓解此问题，但即使上个版本，直接cname的域名查询匹配不到规则也会有异常的。

但客户端一般都不会使用cname来查询的，都是直接使用主域名。nslookup例外。你可以确认下是不是用nslookup测试的。
正常APP，浏览器都应该是没有问题的。

但如果担心，可以临时用下面办法规避，避免返回cname：

```
force-no-CNAME yes
```

但客户端如果一开始就直接拿到cname来访问，上面参数也是无用的。保险的办法就是将cname配置的规则文件里面。

**Comment by cwbsw** [comment]
> 这个问题根源是规则文件里面，并没有对应cname的规则。当第一次用域名查询时是正常的。 第二次如果用cname查询的话，因为没有规则，就会查询所有上游。 之前版本因没有拆分缓存，会缓解此问题，但即使上个版本，一开始直接用cname域名查询，匹配不到规则也会有异常的。
> 
> 但正常情况客户端不会使用cname来查询的，都是直接使用主域名。 nslookup例外。你可以确认下是不是用nslookup测试的。 正常APP，浏览器都应该是没有问题的。
> 
> 但如果担心，可以临时用下面办法规避，避免返回cname：
> 
> ```
> force-no-CNAME yes
> ```
> 
> 但客户端如果一开始就直接拿到cname来访问，上面参数也是无用的。保险的办法就是将cname配置的规则文件里面。

看来是不同客户端行为不一样，Twitter App就总是会查询CNAME，但Chrome就不会。

`force-no-CNAME yes`似乎不起作用，smartdns总是会返回CNAME记录。

**Comment by cwbsw** [comment]
`force-no-CNAME yes`还产生了别的副作用，加上这个选项之后nftset规则会失效。


> 这个因应用程序而异。我自己用起来，（安卓）个别app（比如bilibili）第一次查出个cname后，之后都拿cname去查ip，到smartdns是匹配了cname的规则。还有的app是从某个网页（https）拿到地址，再用这个地址去连接（比如youtube）。 我认为将对应的cname也写到规则中是比较好的做法。

可能确实都得写到规则里。

**Comment by pymumu** [comment]
停止服务后，删除缓存文件，再启动服务。
rm /tmp/smartdns.cache

**Comment by cwbsw** [comment]
> 停止服务后，删除缓存文件，再启动服务。 rm /tmp/smartdns.cache

已经设置了`cache-persist no`。

**Comment by pymumu** [comment]
[smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/10186374/smartdns-x86_64.zip)
应该是关闭测速了，那个参数不生效，修改了一下，可以大概验证下看看。

**Comment by cwbsw** [comment]
> 应该是关闭测速了，那个参数不生效，修改了一下，可以大概验证下看看。 [smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/10186830/smartdns-x86_64.zip)

之前确实关闭测速了，现在这个版本配置了`force-no-CNAME`就不会再返回CNAME了，也可以正确应用nftset规则了，`bind :53 -no-speed-check -no-dualstack-selection`也没问题。

**Comment by cwbsw** [comment]
> > 应该是关闭测速了，那个参数不生效，修改了一下，可以大概验证下看看。 [smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/10186830/smartdns-x86_64.zip)
> 
> 之前确实关闭测速了，现在这个版本配置了`force-no-CNAME`就不会再返回CNAME了，但是似乎还是会跳过nftset规则。

有缓存就不会更新nftset规则吧，这样的话就没问题了。

**Comment by cwbsw** [comment]
> 应该是关闭测速了，那个参数不生效，修改了一下，可以大概验证下看看。 [smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/10186830/smartdns-x86_64.zip)

10186830这个版本用了一段时间应该没啥问题，可以合并到master吗？

**Comment by PikuZheng** [comment]
> 10186830这个版本用了一段时间应该没啥问题，可以合并到master吗？

是说nfset的问题吗？我看12月10日的版本已经提交在master

**Comment by cwbsw** [comment]
> > 10186830这个版本用了一段时间应该没啥问题，可以合并到master吗？
> 
> 是说nfset的问题吗？我看12月10日的版本已经提交在master

是说force-no-cname的问题，不过结果一样，是我眼瞎了……
