### ISSUE TITLE
双栈网站ipv4优先，如何设置？？

### ISSUE THREAD

**Issue by kitkw** [pymumu/smartdns#1194]
看了多个相关lssues 但还是没看懂...。
例如这个网站 address /nivod.tv/#6
是不是直接添加到 “自定义设置”就好？但设置后没有效果...还是返回IPV6
（双栈IP优选  ipv6服务器  也试过打开  还是不行）

这网站需要梯子  但IPV6不经过梯子.......
![屏幕截图 2022-12-09 212415](https://user-images.githubusercontent.com/31963066/206713072-8aa3404c-5ea4-40d3-9c76-ed96d4c4f961.png)
![屏幕截图 2022-12-09 212521](https://user-images.githubusercontent.com/31963066/206713080-ad85c5a2-c685-4cc6-a096-d7e236e49615.png)

![屏幕截图 2022-12-09 213957](https://user-images.githubusercontent.com/31963066/206715194-1237414f-6cdf-4953-bbb0-fdd748df14fe.png)
![屏幕截图 2022-12-09 213925](https://user-images.githubusercontent.com/31963066/206715214-df1ea5a2-5144-4b86-a692-5151d5cf8772.png)

**Comment by pymumu** [comment]
配置没错，确保重启生效。

**Comment by kitkw** [comment]
> 配置没错，确保重启生效。

重启路由？

**Comment by PikuZheng** [comment]
问题在于终端设备正确使用了smartdns没有。很多情况下，终端设备（优先）选用的ipv6 dns服务器地址并不是smartdns

**Comment by kitkw** [comment]
> 问题在于终端设备正确使用了smartdns没有。很多情况下，终端设备（优先）选用的ipv6 dns服务器地址并不是smartdns

我用的是openclash  
兼容模式
本地DNS骑劫
指向smartdns了
我的节点套的是CF  ipv6  
在第二DNS服务器里 ，如果打勾“停用IPV6地址解析” 所有节点不通，取消打勾所有节点正常。
说明指向正常应该是在用smartdns
![屏幕截图 2022-12-09 233735](https://user-images.githubusercontent.com/31963066/206738599-163a8cc5-e7ac-46a8-b9c0-3b2968f0118d.png)

**Comment by PikuZheng** [comment]
你pc有自己的ipv6地址，如果是用ipv6 dns 根本不过路由器。劫了个寂寞

**Comment by kitkw** [comment]
> 你pc有自己的ipv6地址，如果是用ipv6 dns 根本不过路由器。劫了个寂寞

所以要怎样搞？求指点

**Comment by PikuZheng** [comment]
> 所以要怎样搞？求指点

我这都是猜测，需要你先自查是不是这个情况，比如看看smartdns的日志，有没有收到pc发来的查询请求；比如在pc上用nslookup测试看是哪个DNS服务器应答了。

**Comment by kitkw** [comment]
> > 所以要怎样搞？求指点
> 
> 我这都是猜测，需要你先自查是不是这个情况，比如看看smartdns的日志，有没有收到pc发来的查询请求；比如在pc上用nslookup测试看是哪个DNS服务器应答了。

不会看日志
![image](https://user-images.githubusercontent.com/31963066/206842613-eb0687f8-6ac6-4d50-afe9-ded13733c6d1.png)

**Comment by kitkw** [comment]
> > > 所以要怎样搞？求指点
> > 
> > 
> > 我这都是猜测，需要你先自查是不是这个情况，比如看看smartdns的日志，有没有收到pc发来的查询请求；比如在pc上用nslookup测试看是哪个DNS服务器应答了。
> 
> 不会看日志。这是主路由，好像没过软路由192.168.50.2
 ![image](https://user-images.githubusercontent.com/31963066/206842613-eb0687f8-6ac6-4d50-afe9-ded13733c6d1.png)

**Comment by PikuZheng** [comment]
那你看看这个192.168.50.1是怎么来的，把它改成50.2

**Comment by jxph1123** [comment]
你说的泥巴吧？那个播放有很多地址，把我的加上：
address /mudvod.tv/#6
address /nbyy.tv/#6
address /nbys.tv/#6
address /nbys1.tv/#6
address /newpppp.com/#6
address /biggggg.com/#6
address /nivod.tv/#6

如果还有IPV6，证明你的smartdns没有生效，我的是正常的。

![image](https://user-images.githubusercontent.com/35351787/206946426-8e5f0784-155d-4535-b050-34bb91a2a8b4.png)

**Comment by kitkw** [comment]
> 你说的泥巴吧？那个播放有很多地址，把我的加上： address /mudvod.tv/#6 address /nbyy.tv/#6 address /nbys.tv/#6 address /nbys1.tv/#6 address /newpppp.com/#6 address /biggggg.com/#6 address /nivod.tv/#6
> 
> 如果还有IPV6，证明你的smartdns没有生效，我的是正常的。
> 
> ![image](https://user-images.githubusercontent.com/35351787/206946677-0ab0aa23-2c4d-4954-9bd6-a8450320839e.png)

怎样直接指向smartdns的？我都是指向整个路由...
我现在能让它经过代理了（openclash:骑劫DNS），但nslookkup到的不是真实地址，而且也会做成PING不到 任何网站....
![屏幕截图 2022-12-11 024135](https://user-images.githubusercontent.com/31963066/206978512-0208c5ba-435b-4cd6-b02d-3e9af02d645a.png)

**Comment by kitkw** [comment]
> > 你说的泥巴吧？那个播放有很多地址，把我的加上： address /mudvod.tv/#6 address /nbyy.tv/#6 address /nbys.tv/#6 address /nbys1.tv/#6 address /newpppp.com/#6 address /biggggg.com/#6 address /nivod.tv/#6
> > 如果还有IPV6，证明你的smartdns没有生效，我的是正常的。
> > ![image](https://user-images.githubusercontent.com/35351787/206946677-0ab0aa23-2c4d-4954-9bd6-a8450320839e.png)
> 
> 怎样直接指向smartdns的？我都是指向整个路由... 我现在能让它经过代理了（openclash:骑劫DNS），但nslookkup到的不是真实地址，而且也会做成PING不到 任何网站....
但网络正常，只是不能PING。。。
 ![屏幕截图 2022-12-11 024135](https://user-images.githubusercontent.com/31963066/206978512-0208c5ba-435b-4cd6-b02d-3e9af02d645a.png)

**Comment by PikuZheng** [comment]
> ![屏幕截图 2022-12-11 024135](https://user-images.githubusercontent.com/31963066/206978512-0208c5ba-435b-4cd6-b02d-3e9af02d645a.png)

单看这张图，pc使用了192.168.50.2 作为dns服务器。但是50.2的53端口是哪个在提供服务？这个服务并没有把smartdns作为它的上级，而是直接用运营商dns（或其他上游dns服务）走出去了

**Comment by kitkw** [comment]
> > ![屏幕截图 2022-12-11 024135](https://user-images.githubusercontent.com/31963066/206978512-0208c5ba-435b-4cd6-b02d-3e9af02d645a.png)
> 
> 单看这张图，pc使用了192.168.50.2 作为dns服务器。但是50.2的53端口是哪个在提供服务？这个服务并没有把smartdns作为它的上级，而是直接用运营商dns（或其他上游dns服务）走出去了

已经指向了  上面也有提到
https://user-images.githubusercontent.com/31963066/206738599-163a8cc5-e7ac-46a8-b9c0-3b2968f0118d.png

**Comment by huojinming-1997** [comment]
> 你说的泥巴吧？那个节目放了很多地址，把我的加上： 地址/mudvod.tv/ #6 地址/nbyy.tv/ #6 地址/nbys.tv/ #6 地址/nbys1.tv/ #6 地址/newpppp.com/ #6 地址/biggggg.com/ #6 地址/nivod.tv/ #6
> 
> 如果还有 IPV6，证明你的 smartdns 没有有效，我的是正常的。
> 
> ![图片](https://user-images.githubusercontent.com/35351787/206946677-0ab0aa23-2c4d-4954-9bd6-a8450320839e.png)

感谢大佬啊解决了我一直的疑问，之前只找到了nivod.tv mudvod.tv这两个域名但还是出现无法访问的问题，现在加上大佬你给出的几个域名就成功了，之前一直怀疑是不是域名加少了还是smartdns不起作用从而产生深度的自我怀疑，还想请教一下如何能快速获取这些网站全部域名呢？希望大佬有空能赐教一下

**Comment by kitkw** [comment]
> 你说的泥巴吧？那个播放有很多地址，把我的加上： address /mudvod.tv/#6 address /nbyy.tv/#6 address /nbys.tv/#6 address /nbys1.tv/#6 address /newpppp.com/#6 address /biggggg.com/#6 address /nivod.tv/#6
> 
> 如果还有IPV6，证明你的smartdns没有生效，我的是正常的。
> 
> ![image](https://user-images.githubusercontent.com/35351787/206946677-0ab0aa23-2c4d-4954-9bd6-a8450320839e.png)

感谢提醒！
之前smartdns没搞成功。
现在直接用Dnsmasq 搞定。
vi /jffs/configs/dnsmasq.conf.add   #不同设备路径可能不一定

server=/nivod.tv/8.8.8.8
server=/mudvod.tv/8.8.8.8
server=/nbyy.tv/8.8.8.8
server=/nbys.tv/8.8.8.8
server=/nbys1.tv/8.8.8.8
server=/newpppp.com/8.8.8.8
server=/biggggg.com/8.8.8.8
address=/nivod.tv/::
address=/mudvod.tv/::
address=/nbyy.tv/::
address=/nbys.tv/::
address=/nbys1.tv/::
address=/newpppp.com/::
address=/biggggg.com/::

service restart_dnsmasq
