### ISSUE TITLE
39版，下载“更多”点不开，后面的都无法显示。请修理

### ISSUE THREAD

**Issue by iamyangyiok** [pymumu/smartdns#1195]
39版，下载“show all 28 assets”点不开，后面的都无法显示。请修理

**Comment by iamyangyiok** [comment]
> 试试点击一下标题
> 
> ![image](https://user-images.githubusercontent.com/12579522/206855574-e3f67db7-7842-4e1a-9aca-376e8ae98d56.png)

这个可以 感谢

**Comment by PikuZheng** [comment]
github证实这是他们网站的bug并且不打算修复
https://github.com/orgs/community/discussions/41339

**Comment by yyysuo** [comment]
> github证实这是他们网站的bug并且不打算修复 https://github.com/orgs/community/discussions/41339

硬气。
