### ISSUE TITLE
load certificate from /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs failed.

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#1196]
**问题现象**  
载入SSL证书失败，我看了下`Dockerfile`，会不会是因为`busybox`没有`ca-certificates`导致的？
这个问题倒是可以通过挂载宿主机的`/etc/ssl`解决

**运行环境**
1. 固件型号  
`Linux OpenWrt 5.15.81 #0 SMP Wed Dec 7 18:12:24 2022 x86_64 GNU/Linux`
`docker version 20.10.17`

2. 运营商
四川电信

3. smartdns来源以及版本
Github 最新源码(#1cde3f7335589b9e24f447e6744925b411221649)自行编译

![1](https://user-images.githubusercontent.com/38558065/206860674-be09f348-3d1f-4d6e-94a9-6798a0939a0a.png)

**Comment by PikuZheng** [comment]
再次给alpine打个广告 https://github.com/PikuZheng/smartdns/blob/master/Dockerfile.alpine

**Comment by devioa** [comment]
> 再次给alpine打个广告 https://github.com/PikuZheng/smartdns/blob/master/Dockerfile.alpine

你好，这个fork有什么不同呢

**Comment by PikuZheng** [comment]
> 
> 你好，这个fork有什么不同呢

1. alpine自带openssl，无需额外编译
2. 运行环境基于alpine，实践证明在mikrotik等环境也能运行
