### ISSUE TITLE
log-num 与 audit-num 与 README 描述不符

### ISSUE THREAD

**Issue by wenxuanjun** [pymumu/smartdns#1198]
**问题现象**

在 README 中，`log-num` 与 `audit-num` 的值可以等于 0，但根据：

https://github.com/pymumu/smartdns/blob/1cde3f7335589b9e24f447e6744925b411221649/src/tlog.c#L1707

如果 `maxlogcount` 为 0，则会被设置为 `TLOG_LOG_COUNT`。

此外，`log-num` 的默认值是 8：

https://github.com/pymumu/smartdns/blob/1cde3f7335589b9e24f447e6744925b411221649/src/dns_conf.c#L107

**建议的方案**

允许将 `log-num` 与 `audit-num` 设置为 0 以停用日志归档功能，并更新 README。

**Comment by pymumu** [comment]
done

**Comment by wenxuanjun** [comment]
谢谢
