### ISSUE TITLE
建议适配Android设备

### ISSUE THREAD

**Issue by RC1844** [pymumu/smartdns#120]
**需求应用场景**
因为学校禁止自建WiFi（禁止多设备用同一ip），所以路由只能给电脑用，而手机只能连学校的WiFi

**建议的方案**
建议适配Android系统（注意不是安卓 ，滑稽），最好能做成magisk模块（酷安老哥会喜欢的）

**设备信息**
主流arm架构armeabi-v7a、arm64-v8a

2. 固件信息
Android8.1
Android9.0

酌情可以只编译二进制文件

**Comment by pymumu** [comment]
andriod这个之前有人提过了，smartdns需要一些root权限才能做的事情，比如绑定53端口，和ping。
andriod并没有开放这些权限。
唯一可行的就是做成VPN组件，再将DNS请求转发处理，ping也能检查，但这样又和其他VPN软件冲突。作为DNS软件不太合适。

**Comment by RC1844** [comment]
> andriod这个之前有人提过了，smartdns需要一些root权限才能做的事情，比如绑定53端口，和ping。
> andriod并没有开放这些权限。
> 唯一可行的就是做成VPN组件，再将DNS请求转发处理，ping也能检查，但这样又和其他VPN软件冲突。作为DNS软件不太合适。

噢，好的了解

**Comment by Aefer** [comment]
使用 Release 26 Special 中的 smartdns.1.2019.06.21-2337.aarch64-debian-all.deb 提取出文件可以在 Android 上运行，但是大量报 ssl 依赖错误和 unix socks 错误（几分钟日志文件累计到数十M）
（暂时没有设备，具体日志稍后提供）

**Comment by Aefer** [comment]
之前尝试用Release 26 Special做了一个magisk模块，在酷安上发布（测试不足就发布了），反响也不错，但由于这些问题无法解决，只能删除。

**Comment by RC1844** [comment]
你提供日志也什么用呀，这要么在源码改（作者暂时不打算开源），要么补足依赖（可以看依赖表）

**Comment by pymumu** [comment]
静态编译版本只依赖内核，不依赖其他任何库。理论上可以在安卓下运行。
但smartdns需要使用raw socket测速，不然测速功能会生效，
这块需要验证后才知道有什么问题。

另外，下个版本可以完全将测速功能关闭，返回最早回应的DNS结果。

**Comment by RC1844** [comment]
为什么关闭测速？？？可否做成两个模式，换其他测试方式可否？

**Comment by Aefer** [comment]
> 还有 smartdns 不会上传任何用户数据，如果发现有数据上传，请确认是否下载了正确的版本。
可能因为发送了大量的请求
> 静态编译版本只依赖内核，不依赖其他任何库。理论上可以在安卓下运行。
然而的确报了 ssl lib error
> 另外，下个版本可以完全将测速功能关闭，返回最早回应的 DNS 结果。
这个方案没有解决问题，而且失去了 smartdns 的精髓

**Comment by pymumu** [comment]
ssl错误可以发一下截图看看。

这里说的关闭测速： 指的是可配置，包括配置测速模式，甚至关闭，默认肯定是开启测速的。

还有可以配置启用多个端口，支持特定端口的请求关闭测速，比如53端口的查询测速，6053端口的不测速，并且将请求发送到特定可信的上游。

可以留下配套的固件信息给你个版本试用验证看看。

**Comment by pymumu** [comment]
[smartdns.1.2019.08.03-0254.aarch64-debian-all.deb.zip](https://github.com/pymumu/smartdns/files/3463806/smartdns.1.2019.08.03-0254.aarch64-debian-all.deb.zip)

试试这个把。

配置测速模式：
speed-check-mode tcp:80
speed-check-mode ping,tcp:443

支持，[ping|tcp:port|none|,]

bind参数增加功能，bind可以配置多个。
-no-speed-check支持强制关闭测速。
-group支持配置查询组，和nameserver功能类似。

**Comment by Aefer** [comment]
日志例如：
[2019-08-04 16:01:12,047][ERROR][     dns_client.c:2286] send query to 8.8.4.4 failed, Socket not connected, type: 1
怀疑是劫持本机DNS到smartdns的iptables规则导致了无限循环，连接数超出了linux限制，不是程序本身问题
以及，不加 -f 参数时不能用相对路径

**Comment by pymumu** [comment]
可以设置路由规则，将这目的地为上游DNS的请求放行。
或者本地绑定端口，对本地特定端口的请求放行（但现在还不支持绑定本地端口。）

后台执行不支持相对路径，因为后台执行调用了 daemon接口，哪个接口默认会更改当前路径为/的。

**Comment by Aefer** [comment]
目前启动脚本是这样的：（$MODDIR 是模块安装目录）
$MODDIR/system/xbin/smartdns -p $MODDIR/smartdns.pid
iptables -t nat -A OUTPUT -p udp -d 119.29.29.29 --dport 53 -j ACCEPT
iptables -t nat -A OUTPUT -p udp -d 114.114.114.114 --dport 53 -j ACCEPT
iptables -t nat -A OUTPUT -p udp -d 180.76.76.76 --dport 53 -j ACCEPT
iptables -t nat -A OUTPUT -p udp -d 223.5.5.5 --dport 53 -j ACCEPT
iptables -t nat -A OUTPUT -p udp ! -d 127.0.0.1 --dport 53 -j DNAT --to-destination 127.0.0.1
iptables -t nat -A OUTPUT -p tcp ! -d 80.80.80.80 --dport 53 -j DNAT --to-destination 127.0.0.1

配置文件：
server 119.29.29.29 -blacklist-ip -check-edns -group China
server 114.114.114.114 -blacklist-ip -check-edns -group China
server 180.76.76.76 -blacklist-ip -check-edns -group China
server 223.5.5.5 -blacklist-ip -group China
server-tcp 101.6.6.6:5353 -group foreign -group China -group secure
server-tcp 208.67.222.222:5353 -group foreign -group secure
server-tls 8.8.8.8 -host-name dns.google -group foreign -group secure
server-tls 101.101.101.101 -group foreign -group secure
server-https https://ea-dns.rubyfish.cn/dns-query -host-name ea-dns.rubyfish.cn -group foreign -group secure -group China
server-https https://cloudflare-dns.com/dns-query -host-name cloudflare-dns.com -http-host cloudflare-dns.com -group foreign -group secure
server-https https://dns.233py.com/dns-query -host-name dns.233py.com -group foreign -group secure -group China
server-https https://9.9.9.10/dns-query -group foreign -group secure

**Comment by pymumu** [comment]
iptables -t nat -A OUTPUT -p udp ! -d 127.0.0.1 --dport 53 -j DNAT --to-destination 127.0.0.1
这条规则似乎是导致问题的。

smartdns自己其实也是客户端的，所以要想办法区分。
这里有一个iptable按PID的规则，如果设备支持的话，可以将smartdns的pid加入到排除列表里面。
如果不行的话，我后面可以增加设置绑定本地端口的配置，这样iptable就可以指定哪些端口可以放行。

另外测速模式，在没root权限的情况下，可以选择只用tcp测试。
speed-check-mode tcp:80

**Comment by Aefer** [comment]
有 root 权限（不然 iptables 是怎么加的）
试过 UID 匹配，会导致返回包 ip 地址为本机 ip 地址而不是请求地址（127.0.0.1）

**Comment by pymumu** [comment]
抽空在安卓盒子上跑了一下，静态编译版本是完全可以运行的，没有任何问题。
所以，应该是iptable配置不合理。

一个方案是，直接将安卓系统里面的DNS设置成127.0.0.1，smartdns直接启动在53端口上。
我自己验证了一下，这个方案是可以的，可以用setprop来修改系统默认dns
```
setprop net.dns1 127.0.0.1
setprop net.dns2 127.0.0.1
```

**Comment by Aefer** [comment]
pid 文件和 log 已处理
net.dns 在网络连接变化时会被覆盖（而且有些厂商和不同版本用 net.网络接口名.dns ?)

**Comment by pymumu** [comment]
https://www.zhihu.com/question/26437966
看看这个，我没试验过网络变化是什么情况。

**Comment by pymumu** [comment]
设置备用DNS服务器
默认的是连接网络时自动获取ISP分配的DNS服务器，一般是分配两个，执行
getprop net.dns1
getprop net.dns2
即可查询。可以在/system/build.prop里添加
net.dns3=8.8.8.8
net.dns4=8.8.4.4
即可把8.8.8.8和8.8.4.4设置为第3、4号DNS服务器。这样做主要是为了修复中国联通网络下默认DNS服务器屏蔽DOMAINCONTROL.COM系列NS和HE.NET系列NS造成的部分网站无法访问问题，同时保留其他网络环境（包括局域网环境）的默认DNS服务器可用。

还有这个

**Comment by Aefer** [comment]
> 
> 
> https://www.zhihu.com/question/26437966
> 看看这个，我没试验过网络变化是什么情况。

这些方法上面都提到过
smartdns 会自动获取本机 DNS 并作为上游吗？

**Comment by pymumu** [comment]
不会，除非完全没有配置任何DNS。

**Comment by Aefer** [comment]
iptables 还是比较可行的方案
但是上面的 iptables 规则并没有看出什么问题
或许是需要 ip:53 ?

**Comment by pymumu** [comment]
用iptable要考虑如果避免smartdns的请求被iptable控制，因为smartdns本身也是dns客户端。
你的iptable规则里面，要将smartdns配置文件中的所有上游DNS加入。否则就会进入循环状态
但这样也有问题，就是如果andriod系统配置了上述任何一个IP地址，那么iptable将不生效，不会将请求转发给smartdns。

所以，我觉得还是直接修改系统dns靠谱，唯一的问题就是网络重新连接的时候。
如果有通知机制，那是最好，在网络状态变化的时候设置dns，这类工具也是有的，比如dns changer
或者可以写一个脚本，循环查询dns是否设置为本地，没有就设置。

**Comment by x4455** [comment]
尝试了一下，Android的iptables不支持pid规则 ~~至少在我这里不行，我这ip6tables还没nat表~~ ，于是改用uid规则 :relieved:

[smartdns-Android](https://github.com/x4455/smartdns-Android)，这是一个Magisk模块 :relieved:
目前还需要进行测试 ~~works on my machine~~ :expressionless:
