### ISSUE TITLE
qq邮箱登录非常困难，请问怎么解决？！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1204]
配置如下：
```
# 关闭 prefetch-domain 和 serve-expired
prefetch-domain no
serve-expired no
# 有网友说，开起这两个，重新获取IP时会无视分组。如果你遇到污染，可以尝试关闭。

# 关闭 IPv6 解析 和 双栈优选
force-AAAA-SOA no
dualstack-ip-selection no
# IPv6 由于优先级较高，可能导致不可知的问题
# 如果你需要国内的 IPv6，这里自行 # 注释掉
# 或者考虑使用 address 参数，强制某地址返回 IPv4 或者 IPv6

log-level info
log-file /var/log/smartdns/smartdns.log
log-size 1m
log-num 2

speed-check-mode tcp:80,ping

server 101.6.6.6:5353
server 202.38.93.153:5353
server 202.141.162.123:5353
server 202.141.178.13:5353
server [2001:da8::666]:5353
server 208.67.222.222:5353 -group oversea -exclude-default-group
server 208.67.220.220:5353 -group oversea -exclude-default-group

server-tcp 1.0.0.1 -group oversea -exclude-default-group
server-tcp 8.8.4.4 -group oversea -exclude-default-group
server-tcp 149.112.112.112 -group oversea -exclude-default-group
server-tcp 2606:4700:4700::1001 -group oversea -exclude-default-group

server-tls 115.159.131.230 -host-name dns.rubyfish.cn
server-tls dns.rubyfish.cn
server-tls 1.1.1.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -group oversea -exclude-default-group
server-tls 2606:4700:4700::1111 -host-name 1dot1dot1dot1.cloudflare-dns.com -group oversea -exclude-default-group
server-tls 1dot1dot1dot1.cloudflare-dns.com -group oversea -exclude-default-group
server-tls 8.8.8.8 -host-name dns.google -group oversea -exclude-default-group
server-tls dns.google -group oversea -exclude-default-group

server-https https://202.38.93.153/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
server-https https://202.141.178.13/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
server-https https://[2001:da8:d800:931::153]/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
server-https https://neatdns.ustclug.org/resolve
server-https https://rubyfish.cn/dns-query
server-https https://i.233py.com/dns-query
server-https https://9.9.9.9/dns-query -group oversea -exclude-default-group
server-https https://dns9.quad9.net/dns-query -group oversea -exclude-default-group
server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group oversea -exclude-default-group
server-https https://doh.opendns.com/dns-query -group oversea -exclude-default-group

# 国内 DNS 
# bind: 6054 -group china
# server 223.6.6.6 -group china
# server 114.114.114.114 -group china
# 国外DNS
# bind: 7054 -group oversea
````

**Comment by PikuZheng** [comment]
qq邮箱登陆在哪一步困难？可以用浏览器调试看看连接速度，确定问题出在哪一个域名上。

也不排出登陆时几个域名走了不同的路由，导致服务器端觉得是不安全（反正我每次登陆都需要短信验证码

**Comment by lalasou** [comment]
> 配置如下：
> 
> ```
> 
> # 关闭 prefetch-domain 和 serve-expired
> 
> prefetch-domain no
> 
> serve-expired no
> 
> # 有网友说，开起这两个，重新获取IP时会无视分组。如果你遇到污染，可以尝试关闭。
> 
> 
> 
> # 关闭 IPv6 解析 和 双栈优选
> 
> force-AAAA-SOA no
> 
> dualstack-ip-selection no
> 
> # IPv6 由于优先级较高，可能导致不可知的问题
> 
> # 如果你需要国内的 IPv6，这里自行 # 注释掉
> 
> # 或者考虑使用 address 参数，强制某地址返回 IPv4 或者 IPv6
> 
> 
> 
> log-level info
> 
> log-file /var/log/smartdns/smartdns.log
> 
> log-size 1m
> 
> log-num 2
> 
> 
> 
> speed-check-mode tcp:80,ping
> 
> 
> 
> server 101.6.6.6:5353
> 
> server 202.38.93.153:5353
> 
> server 202.141.162.123:5353
> 
> server 202.141.178.13:5353
> 
> server [2001:da8::666]:5353
> 
> server 208.67.222.222:5353 -group oversea -exclude-default-group
> 
> server 208.67.220.220:5353 -group oversea -exclude-default-group
> 
> 
> 
> server-tcp 1.0.0.1 -group oversea -exclude-default-group
> 
> server-tcp 8.8.4.4 -group oversea -exclude-default-group
> 
> server-tcp 149.112.112.112 -group oversea -exclude-default-group
> 
> server-tcp 2606:4700:4700::1001 -group oversea -exclude-default-group
> 
> 
> 
> server-tls 115.159.131.230 -host-name dns.rubyfish.cn
> 
> server-tls dns.rubyfish.cn
> 
> server-tls 1.1.1.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -group oversea -exclude-default-group
> 
> server-tls 2606:4700:4700::1111 -host-name 1dot1dot1dot1.cloudflare-dns.com -group oversea -exclude-default-group
> 
> server-tls 1dot1dot1dot1.cloudflare-dns.com -group oversea -exclude-default-group
> 
> server-tls 8.8.8.8 -host-name dns.google -group oversea -exclude-default-group
> 
> server-tls dns.google -group oversea -exclude-default-group
> 
> 
> 
> server-https https://202.38.93.153/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
> 
> server-https https://202.141.178.13/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
> 
> server-https https://[2001:da8:d800:931::153]/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
> 
> server-https https://neatdns.ustclug.org/resolve
> 
> server-https https://rubyfish.cn/dns-query
> 
> server-https https://i.233py.com/dns-query
> 
> server-https https://9.9.9.9/dns-query -group oversea -exclude-default-group
> 
> server-https https://dns9.quad9.net/dns-query -group oversea -exclude-default-group
> 
> server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group oversea -exclude-default-group
> 
> server-https https://doh.opendns.com/dns-query -group oversea -exclude-default-group
> 
> 
> 
> # 国内 DNS 
> 
> # bind: 6054 -group china
> 
> # server 223.6.6.6 -group china
> 
> # server 114.114.114.114 -group china
> 
> # 国外DNS
> 
> # bind: 7054 -group oversea
> 
> ````

只配置上游dns  其他不设置试试
感觉没问题
