### ISSUE TITLE
是否可以添加一个mac版本的docker？

### ISSUE THREAD

**Issue by AsteriskZuo** [pymumu/smartdns#1206]
想要在mac （m1）上使用该功能，奈何docker接触不多，像对我们这样的小白来说，有个docker镜像应该会更加容易。
请推出一个 mac版本的docker吧。

或者实在没有时间或者其他原因来实现，也请提供一些更加具体详细实用的说明或者建议吧。非常感谢。

**Comment by PikuZheng** [comment]
m1是什么架构的？受openssl和基础镜像限制，docker只能提供 amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, riscv64, s390x 架构（请从中选一个
