### ISSUE TITLE
[Feature request] Bootstrap resolvers

### ISSUE THREAD

**Issue by phantomcraft** [pymumu/smartdns#1207]
I'm trying to setup a Tor middlebox with DoH in SmartDNS side but I can't.

As I could see, SmartDNS uses 1.1.1.1:53@UDP as a bootstrap resolver, but inside the Tor sandbox I have only TCP connectivity, so I can't resolve the domain name in DoH (https://cloudflare-dns.com/dns-query)

Options to set the default bootstrap resolvers, beint it over UDP or TCP, would be a good idea to solve this issue.

**Comment by phantomcraft** [comment]
After studying the configuration file a little more I discovered how, shame on me, sorry:

```
bind 127.0.0.1:53 -group blah

speed-check-mode none
force-qtype-SOA 65
log-level info

server-tcp one.one.one.one:53 -group blah
server-tcp 114.114.114.114:53
```

Bind port should be bonded to the resolver in form a domain, SmartDNS will automatically use the ungrouped resolver as fallback.

Interesting design.

Closing.

**Comment by PikuZheng** [comment]
> As I could see, SmartDNS uses 1.1.1.1:53@UDP as a bootstrap resolver

not really, use system default dns (like /etc/resolv.conf).

read #567 fyi

**Comment by phantomcraft** [comment]
@PikuZheng 

Sorry I was wrong, I wrote that because I've seen a DNS packet going out the network interface here.

I will use this scheme from now on:

```
server 8.8.8.8 -group bootstrapdns
server 1.1.1.1
server google.dns
nameserver /google.dns/bootstrapdns
```
