### ISSUE TITLE
创建的文件权限不正确

### ISSUE THREAD

**Issue by PikuZheng** [pymumu/smartdns#1208]
**问题现象**  
smartdns创建的文件，权限为640。预期为644，或应遵循上层文件夹权限值。
```
root@OpenWrt:~# ls /var/log/smartdns.log -l
-rw-r-----    1 root     root        541282 Dec 20 17:02 /var/log/smartdns.log
```

由于普通用户无读取权限，导致nginx等不能以root权限运行的应用无法读取审计日志。

**运行环境**
openwrt 和 docker 均有此问题，其他环境未测试

**Comment by pymumu** [comment]
默认就是640的权限。这个没有提供选项修改权限。
可能提供一个选项修改权限。

**Comment by pymumu** [comment]
增加了两个设置文件权限的选项。默认情况是安全的。
