### ISSUE TITLE
是否可以增加对DNS over HTTPS的支持

### ISSUE THREAD

**Issue by gitgayhub** [pymumu/smartdns#121]
**需求应用场景**
现在几家国外的DNS服务商都支持DNS over HTTPS了，请问smartdns是否可以增加对DoH的支持。目前我的解决方案是在本地跑了几个DoH代理在不同端口作为smartdns的上游DNS

**Comment by pymumu** [comment]
DOH已经有原型功能，但配置还没有合适的设计思路，后面会正式支持。

另外DOH目前有两种实现，一种是json格式，一种是wired格式。
json格式不在RFC规范中，wireformat格式已经在RFC规范中了。
json： https://developers.cloudflare.com/1.1.1.1/dns-over-https/json-format/
wireformat：https://developers.cloudflare.com/1.1.1.1/dns-over-https/wireformat/

所以，smartdns只会支持wireformat格式的DoH。

**Comment by gitgayhub** [comment]
@pymumu 这么晚了还这么快回复issue，辛苦了。如果需要人测试的话可以在issue中@我，很乐意效劳

**Comment by gitgayhub** [comment]
刚测试了下，可惜google不支持wireformat，cloudflare，quad9，国内的geekdns和ruby fish都支持

**Comment by pymumu** [comment]
google支持可能会晚一些。json格式只适合应用通过json调用。smartdns在json转wireformat的话，太过于复杂和性能消耗太多。

**Comment by pymumu** [comment]
@gitgayhub  
release 23已经支持DOH，麻烦验证一下

**Comment by gitgayhub** [comment]
@pymumu 
已安装使用上，谢谢！
测试DoH和DoT速度无异
