### ISSUE TITLE
反馈一个问题，看看如何解决

### ISSUE THREAD

**Issue by LisonFan** [pymumu/smartdns#1211]
先说问题，`api.smoot.apple.cn` 没有结果

原因：
我给 `china-site` 配置了一个 `domain-set`，同时也定义了一个 `nameserver`，规则如下：`domain-rules /domain-set:china-site/ -nameserver china -speed-check-mode ping,tcp:80,tcp:443`

`group` 为 `china` 的 DNS 设置了 `whitelist-ip`，`whitelist-ip` 为大陆 IP list

解析 `api.smoot.apple.cn` 这个域名命中了 `china-site` 规则，但是这个域名使用任何地方的 DNS 解析出来的都是非大陆 IP

`group` 为 `china` 的 DNS 又设置了白名单，会丢弃非大陆 IP 的结果，导致解析结果是空的

这种情况是不是可以把这个域名交给默认组来解析？而不是直接空解析呢

**Comment by PikuZheng** [comment]
没懂，额外添加一行将这个域名指向别的组可行不

**Comment by PikuZheng** [comment]
给默认组加个组名，比如 -group moren
然后将这个什么apple.cn指派给这个组，用domainhset或nameserver规则都行

**Comment by pymumu** [comment]
国外的server-tls, server-https不配置黑白名单。

**Comment by pymumu** [comment]
感觉应该不会，黑白名单只对设置过的server生效，没设置过的是不会应用的。

**Comment by pymumu** [comment]
用你发的配置。api.smoot.apple.cn这个域名可以解析。

**Comment by pymumu** [comment]
最简单就是从CN组里面忽略 nameserver /xxx.com/-
