### ISSUE TITLE
求助：luci下应该如何设置域名规则

### ISSUE THREAD

**Issue by liangshixing** [pymumu/smartdns#1215]
**问题现象**  
更新了最新版本，没看明白域名规则如何设置。界面里面只是显示域名规则尚无任何配置，但也不知道怎么配置

<img width="431" alt="image" src="https://user-images.githubusercontent.com/8481414/209252633-9b07a31f-570c-400f-8186-6f9a75f8bc93.png">

**运行环境**
1. 固件型号  
openwrt 2203
2. 运营商  
中国联通
3. smartdns来源以及版本
luci-app-smartdns - 1.2022.v39.0.8
smartdns - 1.2022.v39.0.8-1

**Comment by pymumu** [comment]
可能是升级导致的问题，执行下面的命令后刷新页面

```
uci add smartdns domain-rule
uci commit smartdns

```

**Comment by liangshixing** [comment]
> 可能是升级导致的问题，执行下面的命令后刷新页面
> 
> ```
> uci add smartdns domain-rule
> uci commit smartdns
> ```

嗯，这样就好了。实测有效
