### ISSUE TITLE
新版本的日志中显示很多网络错误，虽然可能不影响使用！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1217]
![image](https://user-images.githubusercontent.com/45259624/209455980-4d68012f-5827-4c0d-82d0-8d9eda86e482.png)

**Comment by PikuZheng** [comment]
这个应该是连接某个上游服务器失败。应该是影响使用的。
如果日志可以记录是连接哪里失败了，会更有意义。

**Comment by zxlhhyccc** [comment]
> 这个应该是连接某个上游服务器失败。应该是影响使用的。 如果日志可以记录是连接哪里失败了，会更有意义。

貌似找到原因了，我的网络无IPV6，添加了IPV6的dns问题。。。。
