### ISSUE TITLE
termux运行无反应无现象

### ISSUE THREAD

**Issue by Bill50han** [pymumu/smartdns#1218]
**问题现象**  
termux尝试运行自编译版与release版（aarch64，tsu root环境），无任何输出，查后台进程与端口占用均无smartdns。

**运行环境**
1. 固件型号  
红米k40s，miui13.0.11 内核4.19.157

2. 运营商  
联通

3. smartdns来源以及版本
自编译版与release版均尝试过

4. 涉及的配置(注意去除个人相关信息)
bind [::]:53
bind :53
bind :12853 -no-rule-addr

server-https https://cloudflare-dns.com/dns-query --host-name -
server-https https://doh.opendns.com/ --host-name -

server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/

conf-file /sdcard/1proxconf/dns2phone.conf
---
dns2phone.conf：
address /*.pixiv.net/192.168.0.102 
address /以及其他域名/192.168.0.102 

**重现步骤**
1. 上游DNS配置。  
server-https https://cloudflare-dns.com/dns-query --host-name -
server-https https://doh.opendns.com/ --host-name -

server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/

2. 访问的域名。  
nginx做了一个本地的stream代理，测试访问失败

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

termux root环境没有/var目录

**Comment by PikuZheng** [comment]
建议查看系统日志（logcat

就我所知目前smartdns并不支持安卓系统（缺少支撑库或运行环境问题。可以参考一下这个编译 https://github.com/x4455/smartdns-Android/
