### ISSUE TITLE
不支持使用域名作为dns server

### ISSUE THREAD

**Issue by gitgayhub** [pymumu/smartdns#122]
**问题现象**  
配置文件中使用域名作为dns server，会被程序忽略，例如

server-tls ndns.233py.com:853 为无效配置

手动改为IP后生效

server-tls 114.115.240.17:853

**运行环境**
1. smartdns.1.2019.03.15-2307.arm64.deb

**重现步骤**
1. server-tls wdns.233py.com:853

2. 访问的域名。  
www.jd.com

**Comment by pymumu** [comment]
理论上是可以支持域名作为DNS配置的，但首要条件是路由器内部的DNS要配置正确。（wan口）
可以通过ping命令来检查。
ping ndns.233py.com
ping命令能正确解析IP地址的话，smartdns也应该没有问题。
如果不能，就要配置好路由器内部的DNS

**Comment by gitgayhub** [comment]
抱歉我之前可能因为查询结果被运营商抢答了，便以为配置没生效，又测试了下没有问题
