### ISSUE TITLE
server 设置多IP展开为多服务器

### ISSUE THREAD

**Issue by xuefer** [pymumu/smartdns#1225]
**需求应用场景**
server fqdn.example.com

**建议的方案**
1. 对于一个域名fqdn.example.com对应多个IP的，建议展开为多个 server, 每个IP一个
2.  (可选) 建议新增 -4 -6 选项在前面，server -4 fqdn.example.com, server -6 fqdn.example.com
目前只展开为一个，比较可惜，依然需要自己写脚本自动生成

**设备信息**
略

**Comment by PikuZheng** [comment]
说起来我更希望上游域名可以定期重新解析（针对上游域名对应ip不固定的情形），而不是死守程序启动时解析出的ip。

**Comment by PikuZheng** [comment]
另外问一下，一个dns服务商一个域名对应的多个不同ip，解析结果应该是一致的，反复添加（不同的ip）似乎没有必要啊

**Comment by xuefer** [comment]
我不太清楚，不过似乎是针对不同地区返回不同的dns server IP。通常不会反复变化
etienne.ns.cloudflare.com
kira.ns.cloudflare.com

比如 dns.google 至少返回2个IP。估计这辈子都不会看到变化，可人家就是2个IP一个域名。实现本贴这个功能，仅仅是书写便利性、配置更易懂、更优雅吧，我其实也是蛮惊讶smartdns竟然支持 server 后面直接写name的

**Comment by PikuZheng** [comment]
> 我不太清楚，不过似乎是针对不同地区返回不同的dns server IP。通常不会反复变化
> etienne.ns.cloudflare.com
> kira.ns.cloudflare.com
> 
> 比如 dns.google 至少返回2个IP。估计这辈子都不会看到变化，可人家就是2个IP一个域名。实现本贴这个功能，仅仅是书写便利性、配置更易懂、更优雅吧，我其实也是蛮惊讶smartdns竟然支持 server 后面直接写name的

那似乎…没有必要。考虑到程序启动前额外需要配置一个DNS服务器将域名解析为IP。我建议配置文件上使用单一IP，不要用域名。
即使使用域名，解析为单一IP也是满足使用的，反复添加一个服务商的不同IP并没有什么意义（而且如果缺乏优化，可能产生负向作用）。

**Comment by xuefer** [comment]
那就不加吧。

不过我倒是知道 ntpd 采用 1.cn.pool.ntp.org  2.cn.pool.ntp.org 这样的形式来实现获取多个ip作为多个server，但是这个前提是 ntp.org 本身在这规划内所以才有 1 2 3 4 等子域名。而更高级的  chrony ntpd 则直接写一个 cn.pool.ntp.org 产生多个 server 设置

**Comment by xuefer** [comment]
说说我的场景吧。我的一些动态域名挂在 cloudflare 下。所以我自己访问这些域名宁愿直接查询cloudflare域名服务器，理由很多：更新更快。如果使用isp服务器或者其他的，就会造成需要多等好几个缓存失效、阻断、污染等问题，部分服务器还强制提高了ttl所以不如直接查cloudflare。

但是访问cloudflare服务器ip时，部分ip可能会因为众所周知的原因而无法访问，因此添加一个服务商的多个 dns server ip 是明智的做法

**Comment by PikuZheng** [comment]
> 说说我的场景吧。我的一些动态域名挂在 cloudflare 下。所以我自己访问这些域名宁愿直接查询cloudflare域名服务器，理由很多：更新更快。如果使用isp服务器或者其他的，就会造成需要多等好几个缓存失效、阻断、污染等问题，部分服务器还强制提高了ttl所以不如直接查cloudflare。
> 
> 但是访问cloudflare服务器ip时，部分ip可能会因为众所周知的原因而无法访问，因此添加一个服务商的多个 dns server ip 是明智的做法

并不是。。。cf自定义IP可能更有意义。我这边cf默认是给两个欧洲的IP，体验很糟糕。后来强制（用dstnat重定向）到美西，速度非常好而且不会被ban。你可以看看隔壁的cf自选ip项目，或v2ex的相关讨论。

**Comment by PikuZheng** [comment]
> 那就不加吧。smartdns 如果对 server ip也是做过测速挑选的话，确实可不必加
> 

也不是不行，但是要做额外的设置，其实挺麻烦的
