### ISSUE TITLE
缓存大小不设置为0的话，即使开了测速也会返回多个IP

### ISSUE THREAD

**Issue by a904055262** [pymumu/smartdns#1226]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
lean lede
2. 运营商  
电信
3. smartdns来源以及版本
就你这里的最新代码编译的
4. 涉及的配置(注意去除个人相关信息)
只要高级设置里面的缓存设置不设置为0的话，即使开了测速也会返回多个IP。

**重现步骤**
1. 上游DNS配置。  
114
119
2. 访问的域名。  
www.baidu.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
预期行为，如果只要一个IP可以通过max-reply-ip限制

**Comment by a904055262** [comment]
> 预期行为，如果只要一个IP可以通过max-reply-ip限制

那为什么缓存大小会影响这个行为？？

**Comment by pymumu** [comment]
大部分软件只会使用第一个ip，单下载类软件或视频播放软件会需要多ip
smartdns针对这种情况做了优化，不再只返回一个IP，而是返回
1.第一个IP是最快ip
2.其他IP和第一个ip速度差一点，但数量上会比较多。

**Comment by jxph1123** [comment]
多IP没问题的，特殊是视频播放，你会发现多IP播放速度会快很多。
