### ISSUE TITLE
额外的服务器参数 -exclude-default-group与按钮从默认组中排除哪一个优先级高？

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1227]
下图中的配置，从默认组中排除的设置是生效的么？

![image](https://user-images.githubusercontent.com/10081071/210259933-b515bb75-0a60-453d-9072-19c1c2d89881.png)

**Comment by PikuZheng** [comment]
那个勾的结果就是 -exclude-default-group。不勾就是没有。既勾又填额外的结果就是` -exclude-default-group -exclude-default-group`。可以看 /var/etc/smartdns/smartdns.conf 最终生成的配置文件以这个为准

**Comment by pymumu** [comment]
一样效果
