### ISSUE TITLE
抖音经常卡顿

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1228]
大佬们  抖音经常卡顿怎么办  
配置文件如下

server-name smartdns
prefetch-domain yes
serve-expired yes
cache-size 6096000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind [::]:53
bind-tcp [::]:53
server 223.5.5.5  
server-tls 1.12.12.12  
speed-check-mode ping,tcp:80,tcp:443
force-qtype-SOA 65
serve-expired-ttl 604800
serve-expired-prefetch-time 43200

**Comment by PikuZheng** [comment]
建议从代理和分流方向着手，比如路由跟踪一下。单看以上配置没什么问题。

顺便说一下抖音涉及到的域名有
.douyincdn.com
.pstatp.com
.douyinvod.com
.douyinliving.com
 也不排出是ipv6的问题，可以试试将这些域名强制走ipv4

**Comment by lalasou** [comment]
> 建议从代理和分流方向着手，比如路由跟踪一下。单看以上配置没什么问题。
> 
> 
> 
> 顺便说一下抖音涉及到的域名有
> 
> .douyincdn.com
> 
> .pstatp.com
> 
> .douyinvod.com
> 
> .douyinliving.com
> 
>  也不排出是ipv6的问题，可以试试将这些域名强制走ipv4

怎么只让抖音强制走v4
其他还需要v6

**Comment by PikuZheng** [comment]
用地址规则 `address /douyincdn.com/#6 ` 或域名规则 域名集合之类的 但是相关域名你得自己搜集一下 我上面那些不一定完整

**Comment by pymumu** [comment]
多增加几个上游，比如114，运营商dns

**Comment by lalasou** [comment]
> 多增加几个上游，比如114，运营商dns

加运营商dns  污染太严重
有段时间 github 直接返回::1

**Comment by pymumu** [comment]
Smartdns会尽量避免回环地址的，可以多配置几个国内的，可以不用担心

**Comment by lalasou** [comment]
> Smartdns会尽量避免回环地址的，可以多配置几个国内的，可以不用担心，对于明确ip不正确的域名走分流

好的  
主要抖音相关域名有哪些
先加个运营商dns这样用吧

**Comment by pymumu** [comment]
114, 运营商，8.8.8.8多加几个。
ipv4，ipv6开启双栈优选就可以了。

smartdns默认只要配置上游就行，特殊需求的域名走分流用安全的DNS查询通道关闭测速就可以了。

**Comment by liuweiGL** [comment]
检查`广告屏蔽`中的域名列表，我这边是 mon.zijieapi.com 跟 mcs.zijieapi.com 被屏蔽了。抖音页面发送请求失败一直在疯狂重试，虽然 h2 协议能多路复用但浏览器对数量好像还是有限制的，致使其他资源受影响

**Comment by PikuZheng** [comment]
> 检查`广告屏蔽`中的域名列表，我这边是 mon.zijieapi.com 跟 mcs.zijieapi.com 被屏蔽了。抖音页面发送请求失败一直在疯狂重试，虽然 h2 协议能多路复用但浏览器对请求量好像还是有限制的，致使其他资源受影响

这两个域名在ublock的easyprivacy中很久了。应该是和这两个域名无关的。
已知mcs.zijieapi.com用于日志上报，屏了就屏了

**Comment by liuweiGL** [comment]
跟域名无关，主要是页面一直在重试失败的请求导致其他资源加载受影响，资源加载慢了不就感觉卡卡的

**Comment by mengxianbo** [comment]
- GEOIP,CN,DIRECT,no-resolve
