### ISSUE TITLE
因为运营商的抢答，不应再使用任何未加密的方式进行DNS查询

### ISSUE THREAD

**Issue by gitgayhub** [pymumu/smartdns#123]
本人宽带为电信，测试直接在53端口进行常规未加密DNS查询，无论使用的是国外还是国外的任何DNS服务器，所有结果都会被本地运营商抢答，而不只是部分被墙的域名

证明如下
## 1，使用国外9.9.9.9，延迟为200ms以上
`ping 9.9.9.9`
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.
64 bytes from 9.9.9.9: icmp_seq=1 ttl=51 time=224 ms

`kdig @9.9.9.9 www.gov.cn`
;; Received 168 B
;; From 9.9.9.9@53(UDP) in 9.5 ms

查询结果在9ms后返回。再使用DNS over TLS查询

`kdig +tls @9.9.9.9 www.gov.cn`
;; Received 104 B
;; From 9.9.9.9@853(TCP) in 694.9 ms
690ms后返回正确结果

## 2，使用国内ruby fish的DNS ea-dns.rubyfish.cn测试

`ping ping ea-dns.rubyfish.cn`
PING ea-dns.rubyfish.cn (118.89.110.78) 56(84) bytes of data.
64 bytes from 118.89.110.78 (118.89.110.78): icmp_seq=1 ttl=51 time=41.5 ms

使用53端口查询www.jd.com的域名
`kdig @ea-dns.rubyfish.cn www.jd.com`
返回的IP和使用本地运营商DNS返回的IP为同一个本地CDN的IP，延迟在10ms以内

使用DNS over TLS查询www.jd.com，范围的IP为另一个省份的IP，延迟50ms
`kdig +tls @ea-dns.rubyfish.cn www.jd.com`

## 3， 使用任意随机IP作为DNS服务器，同样会被抢答返回查询结果（这个我也震惊了）

`kdig @12.34.56.78 www.gov.cn`
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 50085
;; Flags: qr rd ra; QUERY: 1; ANSWER: 7; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; www.gov.cn.                  IN      A

;; ANSWER SECTION:
www.gov.cn.             133     IN      CNAME   www.gov.cn.qingcdn.com.
www.gov.cn.qingcdn.com. 536     IN      CNAME   zgovweb.v.qingcdn.com.
zgovweb.v.qingcdn.com.  99      IN      A       IP REMOVED

;; Received 168 B
;; Time 2019-03-25 03:18:23 HKT
;; From 12.34.56.78@53(UDP) in 7.9 ms

## 4，使用本地未分配的局域网网段IP作为DNS服务器，仍然会被抢答返回查询结果

` kdig @192.168.6.1 www.gov.cn`
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 21230
;; Flags: qr rd ra; QUERY: 1; ANSWER: 7; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; www.gov.cn.                  IN      A

;; ANSWER SECTION:
www.gov.cn.             300     IN      CNAME   www.gov.cn.qingcdn.com.
www.gov.cn.qingcdn.com. 250     IN      CNAME   zgovweb.v.qingcdn.com.
zgovweb.v.qingcdn.com.  72      IN      A      IP REMOVED

;; Received 168 B
;; Time 2019-03-25 03:39:01 HKT
;; From 192.168.6.1@53(UDP) in 8.4 ms

Traceroute 192.168.6.1

```
目标IP: 192.168.6.1

 1	192.168.2.1    	   0 ms	   0 ms	   0 ms	局域网	*	router	
 2	192.168.1.1    	   0 ms	   0 ms	   0 ms	局域网	*	光猫	
 3	100.64.0.1     	   3 ms	   3 ms	   4 ms	共享地址	AS28571	电信内网网关
 4	xx.xx.xx.xx   	   3 ms	   3 ms	   8 ms	中国 XX 电信	ASXXXX	电信公网IP
 5	192.168.6.1    	   2 ms	   2 ms	   3 ms	局域网	*		

```
DNS在经过本地唯一个公网IP后便被劫持，延迟2ms

## 结论
无论是否国外域名，无论是否被墙域名，无论使用的是哪一个DNS，哪一个IP，本地运营商都会在本地对53端口的常规DNS查询进行抢答。

如果不开启加密协议（目前smartdns只支持DNS over TLS)，在配置文件中添加再多的DNS服务器也没有任何意义，结果都只有唯一一个

**Comment by pymumu** [comment]
对于你的需求，参考FAQ的4+6
https://github.com/pymumu/smartdns#faq
如果仅仅是防止抢答，可以设置DNS服务器标志位-check-edns

另外smartdns设置有IP优选机制，在配置了多个信任DNS服务器的情况下，大部分情况，即使被抢答，也会返回正确的IP地址。

**Comment by gitgayhub** [comment]
开启edns参数并不能返回正确结果，只会得到解析错误的Error提示
```
 kdig +edns @114.114.114.114 www.gov.cn
;; ERROR: malformed reply packet from 114.114.114.114@53(UDP)
```
抢答设备在本地网关，刚出光猫便被抢答了，如果不使用加密协议查询DNS，即使设置无数多个DNS服务器也只能得到唯一的一个结果

**Comment by pymumu** [comment]
Check-Edns是设置到smartdns配置里面的，看参数说明吧

**Comment by gitgayhub** [comment]
使用TCP查询目前还未被本地运营商抢答

 ```
kdig +tcp @114.114.114.114 twitter.com
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 44869
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; twitter.com.                 IN      A

;; ANSWER SECTION:
twitter.com.            42      IN      A       93.46.8.89

;; Received 45 B
;; Time 2019-03-25 13:08:39 HKT
;; From 114.114.114.114@53(TCP) in 33.6 ms

```

如果使用国外的DNS查询特定域名会得到错误提示

```
kdig +tcp @8.8.8.8 twitter.com
;; WARNING: can't receive reply from 8.8.8.8@53(TCP)
;; WARNING: failed to query server 8.8.8.8@53(TCP)

```

**Comment by gitgayhub** [comment]
> Check-Edns是设置到smartdns配置里面的，看参数说明吧

请问对某个dns server设置了check-edns，是应该会从该dns server得到正确的解析结果，还是只是会忽略该dns server返回的被污染的结果

我用dig +edns参数已经不能正常解析，smartdns是否还可以使用edns得到结果

**Comment by gitgayhub** [comment]
> 请问对某个dns server设置了check-edns，是应该会从该dns server得到正确的解析结果，还是只是会忽略该dns server返回的被污染的结果
> 
> 我用dig +edns参数已经不能正常解析，smartdns是否还可以使用edns得到结果

回答我自己的问题，经测试

server 8.8.8.8 -check-edns
和dig +tls @8.8.8.8 返回的是同一个正确的IP

抱歉了

不过还是建议只使用加密协议查询DNS

**Comment by ghostry** [comment]
有些不明白,想要只使用加密协议查询dns ,不配置server参数就行了吧,还需要改程序?
可以只写server-tcp和server-tls

**Comment by gitgayhub** [comment]
> 有些不明白,想要只使用加密协议查询dns ,不配置server参数就行了吧,还需要改程序?
> 可以只写server-tcp和server-tls

是的，这个issue只是写给用户看的，建议用户不要再配置未加密的方式查询DNS

**Comment by pymumu** [comment]
tcp也是不安全的，只有tls安全。后面增加https也是安全的。
