### ISSUE TITLE
最新版本出现奇怪报错，但使用无影响

### ISSUE THREAD

**Issue by chengzixqq** [pymumu/smartdns#1230]
**问题现象**  
简要描述问题出现的现象
正常使用时出现的错误，使用无影响，但一直报错
**运行环境**
**1. 固件型号** 
 OpenWrt R22.4.18
**2. 运营商**  
中国移动
**3. smartdns来源以及版本** 
来源： @PikuZheng  版本：40.0.4
**4. 涉及的配置(注意去除个人相关信息)**
![image](https://user-images.githubusercontent.com/104790283/211026793-8b5abb3d-3a30-4ff2-ad08-415503725617.png)
![image](https://user-images.githubusercontent.com/104790283/211026565-dbd5c34a-4f74-499c-b155-e488d53ce556.png)
![image](https://user-images.githubusercontent.com/104790283/211026600-af290da5-19f8-4487-8637-015c1caf5836.png)

**5.自定义配置**
#端口
bind [::]:53
bind-tcp [::]:53
bind [::]:784
bind-tcp [::]:784
bind [::]:853
bind-tcp [::]:853
#clash DNS port
bind [::]:7874
bind-tcp [::]:7874
#日志
log-level error
log-file /etc/smartdns/log/smartdns.log
log-size 16M
log-num 16
#审计
audit-enable no
audit-file /etc/smartdns/log/smartdns-audit.log
audit-size 16M
audit-num 16
#测速
speed-check-mode tcp:80,tcp:443,ping
#缓存
cache-size 1048576
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
prefetch-domain yes
serve-expired yes
serve-expired-ttl 60
serve-expired-reply-ttl 10
dualstack-ip-selection yes
force-qtype-SOA 65
#首次查询响应
response-mode fastest-response
#TCP 链接空闲超时时间
tcp-idle-time 100000

**6.信息收集 隐私信息已经打码**
文件：[smartdns.log](https://github.com/pymumu/smartdns/files/10360719/smartdns.log)

**Comment by PikuZheng** [comment]
是谁在at我🤭先盲猜一个端口绑定失败，已经躺下了，明早再看日志

**Comment by PikuZheng** [comment]
大致看了一下日志分为1月2日15点前和15点后至今。1月2日15点前应该是设备自身ipv6断开了。之后是连接到 192.168.1.167和192.168.1.178和2409:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx时连接意外断开，或者被中间防火墙之类的阻断了

**Comment by pymumu** [comment]
ip v6引发的log
先确认网络是否支持ipv6
如不支持，吧ipv6上游去掉

**Comment by pymumu** [comment]
看错误码，是你openwrt系统无法访问IPV6
