### ISSUE TITLE
请问最新版本用“阿里dot”还会查询错误吗

### ISSUE THREAD

**Issue by wzy105** [pymumu/smartdns#1233]
我看38及之前的更新说明，说用阿里dot会查询错误，现在解决了吗

**Comment by PikuZheng** [comment]
我不用阿里的原因是阿里（doh、dot、udp）有一个巨大的缓存，在缓存超时前ip都不会递归更新，导致（尤其是ddns）在soa报告ip变化后无法及时获取到正确的结果。

dot我之前使用时没有发现有问题。doh据说有问题但之前大致搜索了下没找到准确的说法。

**Comment by wzy105** [comment]
> 我不用阿里的原因是阿里（doh、dot、udp）有一个巨大的缓存，在缓存超时前ip都不会递归更新，导致（尤其是ddns）在soa报告ip变化后无法及时获取到正确的结果。
> 
> dot我之前使用时没有发现有问题。doh据说有问题但之前大致搜索了下没找到准确的说法。

所以 rr-ttl-reply-max 可以让阿里的缓存过期吗？

很无奈，只有阿里有四川出口速度比dnspod要快不少

**Comment by wzy105** [comment]
> 我不用阿里的原因是阿里（doh、dot、udp）有一个巨大的缓存，在缓存超时前ip都不会递归更新，导致（尤其是ddns）在soa报告ip变化后无法及时获取到正确的结果。
> 
> dot我之前使用时没有发现有问题。doh据说有问题但之前大致搜索了下没找到准确的说法。

所以 rr-ttl-reply-max 可以让阿里的缓存过期吗？

很无奈，只有阿里有四川出口速度比dnspod要快不少

**Comment by pymumu** [comment]
查询错误是阿里的问题，不是smartdns问题。
刚刚测试，阿里的DNS over TCP仍然有问题，不建议使用。DNS over TLS没有问题，可以使用。

**Comment by PikuZheng** [comment]
> 所以 rr-ttl-reply-max 可以让阿里的缓存过期吗？

不能，你没法控制阿里的服务器配置

> 很无奈，只有阿里有四川出口速度比dnspod要快不少

阿里快的原因是因为它大缓存，在有缓存的情况下直接从缓存返回所以快。dnspod是要一直递归查询到SOA，所以比阿里慢。
对于一个域名的首次查询（阿里没有缓存过的情况下），我记得曾测试过，在我这里dnspod（走腾讯云北京的独立ip）略快。

考虑到smartdns的本地缓存和预读功能，我认为解析准确性（及时更新）比解析速度更重要。而且相比之下那不到0.5秒的额外延迟可以忍受。

> 阿里的DNS over TCP仍然有问题

是说TCP/53吗？也不排出运营商污染

**Comment by 15108428326** [comment]
想问下阿里的DNS over TCP是啥问题

**Comment by PikuZheng** [comment]
> 想问下阿里的DNS over TCP是啥问题

大致翻了一下阿里没有公开文件说明223.5.5.5和223.6.6.6支持dns over tcp。

根据[RFC5966（已废弃）](https://www.rfc-editor.org/rfc/rfc5966)，dns over tcp仅用作服务器间的区域复制传输（已废弃，[RFC7766](https://www.rfc-editor.org/rfc/rfc7766)要求tcp也要像udp一样应答查询），我怀疑阿里云公共dns压根就不支持dns over tcp。

**Comment by 15108428326** [comment]
但是我这阿里的doh与dot都能返回解析结果，倒是腾讯doh频繁502错误，360doh偶尔有502错误

**Comment by PikuZheng** [comment]
> 腾讯doh频繁502错误，360doh偶尔有502错误

腾讯的502是去年上半年的事情了，我记得他们后来增加服务器解决了这个问题

**Comment by 15108428326** [comment]
现在还是一样的问题，感觉没改善啊

**Comment by pymumu** [comment]
DNS over TCP就是走tcp的查询。对应的配置项为server-tcp
server-tls使用阿里DNS应该没有问题。
