### ISSUE TITLE
请问大佬，smartdns最新版分流LUCI界面分流要怎么设置？

### ISSUE THREAD

**Issue by zmjjack** [pymumu/smartdns#1238]
LUCI界面的分流看了说明文件，还是没弄懂。要怎么设置分流才能配合PW好好工作。

**Comment by pymumu** [comment]
一、基本设置
1. 下载页面设置需要分流的域名列表。(格式为一行一个域名，需要分流的域名)
2. 设置上游服务器，设置国外的DOT，DOH等服务器，并设置`服务器组`：比如oversea。可选勾选‘从默认组中排除’
3. 域名规则->域名分流设置：
    * 设置`域名分组`，名称为第二步的名称：比如'oversea'
    * 选择`跳过测速`
    * 选择`停用IPV6地址解析`
    * 选择`域名列表文件`，文件为第一步设置的自动下载的文件，此文件为需要分流的域名列表。
 
二、透明代理：
如果smartdns运行在主路由上，那么可以使用TPROXY对TCP或UDP进行透明代理。下面举例对TCP进行透明转发，其中的[ipsetname]是IP集合的名称，比如可以设置`oversea`：
1. 设置ipset集合
`ipset create [ipsetname] hash:net timeout 600`
2. iptable设置对应ipset集合中域名的TCP请求使用TPROXY重定向转发到本机1080的转发程序。
`iptables -t nat -I PREROUTING -p tcp -m set --match-set [ipsetname] dst -j REDIRECT --to-ports 1080`
3. smartdns设置页面的`域名分流设置`->`ipset名称`设置为上述步骤中[ipsetname]的名称，比如`oversea`
4. 在主路由的1080端口，开启TPROXY转发程序。
5. 应用smartdns设置。
6. 结束。

对于udp，nfttable也是类似的步骤，上述透明代理github上有现成的脚本，PW也有类似的能力

**Comment by zmjjack** [comment]
谢谢

**Comment by czzonet** [comment]
新版有分流了吗 那个版本？

目前用pw进行分流的工作的 即通过gfwlist和自定义黑白名单 做的还是不错的

设置只需要指定smartdns为dnsmasq的上游用于国内和转发7054第二组服务器用于国外

@pymumu

**Comment by zmjjack** [comment]
> 新版有分流了吗 那个版本？
> 
> 目前用pw进行分流的工作的 即通过gfwlist和自定义黑白名单 做的还是不错的
> 
> 设置只需要指定smartdns为dnsmasq的上游用于国内和转发7054第二组服务器用于国外
> 
> @pymumu

这是最新版:https://github.com/pymumu/smartdns/releases/tag/Release40

**Comment by yyysuo** [comment]
> 一、基本设置
> 
> 1. 下载页面设置需自动下载的要分流的域名列表文件（也可上传）。(格式为一行一个域名，需要分流的域名)
> 2. 设置上游服务器，设置国外的DOT，DOH等服务器，并设置`服务器组`：比如oversea。可选勾选‘从默认组中排除’
>    也可以设置一个上游服务器，通过代理走转发程序，设置`服务器组`用于专门分流查询，这样查询DNS的出口和数据出口一样，DNS结果的亲和度和更好。
> 3. 域名规则->域名分流设置：
>    
>    * 设置`域名分组`，名称为第二步的名称：比如'oversea'
>    * 选择`跳过测速`
>    * 选择`停用IPV6地址解析`
>    * 选择`域名列表文件`，文件为第一步设置的自动下载的文件，此文件为需要分流的域名列表。
>    * 对于临时个别要分流的域名，可以在`域名列表`文本框中输入。
> 
> 二、最简单的按域名的透明代理：
> 
> 如果smartdns运行在主路由上，那么可以使用REDIRECT模式对TCP进行透明代理。下面举例对TCP进行透明转发，其中的[ipsetname]是IP集合的名称，比如可以设置`oversea`：
> 
> 1. shell命令，创建pset集合
>    `ipset create [ipsetname] hash:net timeout 600`
> 2. shell命令，iptable设置对应ipset集合中域名的TCP请求使用TPROXY重定向转发到本机1080的转发程序。
>    `iptables -t nat -I PREROUTING -p tcp -m set --match-set [ipsetname] dst -j REDIRECT --to-ports 1080`
> 3. smartdns设置页面的`域名分流设置`->`ipset名称`设置为上述步骤中[ipsetname]的名称，比如`oversea`
> 4. 在主路由的1080端口，开启REDIRECT模式的转发程序。
> 5. 应用smartdns设置。
> 6. 结束。
> 
> 对于udp，nfttable也是类似的步骤，上述透明代理github上有现成的脚本，PW也有类似的能力，只要选择好转发模式，和设置好正确的ipset名称或nftset名称即可。
> 
> 原理上，smartdns和转发软件的结合点，为ipset名称或nftset名称，那两个参数和转发软件匹配就可以做到按需转发。 dnsmasq也是类似的工作方式。

passwall和ssrp都用了blacklist和whitelist这2个ipset，对应的是luci界面中的强制代理和强制直连的ip和域名，是不是可以直接利用这2个ipset，那么就不用再自己另外再创建ipset，添加防火墙规则了吧。
