### ISSUE TITLE
请问edns client subnet的基本使用方法

### ISSUE THREAD

**Issue by GuiDeJuShi** [pymumu/smartdns#1239]
**问题现象**  
作者大大好，各位大佬好。在issue里搜了几遍，对该软件edns client subnet的基本使用方法仍然不太清楚，特来请教。
我没有多线路、没有科学，没有任何插件和代理。就一条联通宽带，V4V6都是公网IP，光猫桥接，路由器拨号并负责DHCP。专门用一台旧电脑安装openwrt 22.03.3官方原版系统、安装1.2023.01.02-1537版本的smartdns作为DNS服务器。路由器IP是192.168.51.1，DNS服务器IP是192.168.51.2以及一个fe80开头的本地v6地址。我应该怎样配置edns client subnet参数，以便正确地、效果最好地使用该软件的edns client subnet功能，使得尽量解析到距离我最近，延迟最低、传输速度最快的IP地址？谢谢

**运行环境**
1. 固件型号  
x64电脑
2. 运营商  
河南联通，V4V6都是公网IP
3. smartdns来源以及版本
GitHub的Release40
4. 涉及的配置(注意去除个人相关信息)
edns-client-subnet

**重现步骤**
1. 上游DNS配置。  
server 119.29.29.29:53
server 180.76.76.76:53
server 223.5.5.5:53
server 123.125.81.6:53
server 117.50.10.10:53
server 1.2.4.8:53
server 202.102.224.68:53
server 8.8.8.8:53
server 9.9.9.9:53
server 208.67.222.222:53
2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by kiligone** [comment]
你这没必要用ecs，直接运营商分配的dns做上游就完事了

**Comment by GuiDeJuShi** [comment]
收到，谢谢各位大佬！

**Comment by yuxuan0107** [comment]
如果要使用的话，请问应该如何配置？感谢

**Comment by PikuZheng** [comment]
> 如果要使用的话，请问应该如何配置？感谢

1. 编译时开启edns功能
2. 上游服务器增加 -check-edns 参数
