### ISSUE TITLE
LEDE版如果web界面与conf文件一起配置  按哪个走？

### ISSUE THREAD

**Issue by clonedpig** [pymumu/smartdns#124]
在LEDE上web界面配置了，然后在/etc/smartdns/处的conf文件也配置了，最后插件是按哪个优先？
目前如果删除web界面的dns服务器，插件就失效了，页面打不开。

**Comment by pymumu** [comment]
openwrt下的配置/etc/smartdns/smartdns.conf文件没有用，只是例子和配置说明。
smartdns使用的是/var/etc/smartdns/smartdns.conf文件，并且这个文件是由/etc/config/smartdns配置生成的。

如果要自定义配置信息，请修改/etc/smartdns/custom.conf
这个文件被/var/etc/smartdns/smartdns.conf包含了。

如果需要自己加其他配置文件，可以用
```
conf-file /path/to/config
```
来单独指定。

相同配置项生效顺序是最后的配置生效，如
```
bind 55
bind 53
```

那么bind 53生效。

**Comment by VanDeAnna** [comment]
> openwrt下的配置/etc/smartdns/smartdns.conf文件没有用，只是例子和配置说明。
> smartdns使用的是/var/etc/smartdns/smartdns.conf文件，并且这个文件是由/etc/config/smartdns配置生成的。

作者你好，还想请教一下
1、/var/etc/smartdns/smartdns.conf 
里面默认配置了3个附加配置
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
这3个附加配置文件是和网页端是关联的，
但为何 /var/etc/smartdns/ 下，还有3个相同名称的配置文件？
而且这3个配置文件，与 /etc 的那3个配置似乎并不关联。
/var/etc/smartdns/ 下的这三个同名配置文件是否也生效？
如果生效，/etc 和 /var/etc 配置有冲突时，哪个优先级高？

2、卸载后安装 SmartDNS，如果
/var/etc/smartdns/address.conf
/var/etc/smartdns/blacklist-ip.conf
/var/etc/smartdns/custom.conf
/etc/config/smartdns
这4个文件不事先删除，会提示
Collected errors:
 * resolve_conffiles: Existing conffile /etc/smartdns/address.conf is different from the conffile in the new package. The new conffile will be placed at /etc/smartdns/address.conf-opkg.
 * resolve_conffiles: Existing conffile /etc/smartdns/blacklist-ip.conf is different from the conffile in the new package. The new conffile will be placed at /etc/smartdns/blacklist-ip.conf-opkg.
 * resolve_conffiles: Existing conffile /etc/smartdns/custom.conf is different from the conffile in the new package. The new conffile will be placed at /etc/smartdns/custom.conf-opkg.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/smartdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/smartdns-opkg.
报错后会创建同名文件并在文件后加上-opkg，且与原配置共存在相同文件夹，对使用是否有影响？

3、 /etc/config/smartdns 这个配置文件
保存的是一些网页端配置的参数，是否也是网页端配置好后传递给
/var/etc/smartdns/smartdns.conf

4、附加文件中再继续添加 conf-file 的附加文件参数，是否生效？
例如在 /etc/smartdns/custom.conf 下再添加
conf-file /etc/smartdns/myconfig.conf
则这个 myconfig.conf 是否生效？

问题有点多，望能一解心中疑惑，打扰了

**Comment by pymumu** [comment]
1. 这个应该是个BUG，原因应该是之前开发版本使用了/var/etc/smartdns下的文件，后面界面改回去了 ，但安装程序没有该回去导致。后面修改后，可以手工删掉。

2. 这个是用了保证smartdns升级，卸载时保留配置使用的，只是告警，可以忽略。
配置文件webui或手工修改后，和安装包中的默认文件不一致，卸载时，会保留这些文件。
当再次安装新的smartdns时，老的配置文件存在，就告警提示了，安装包中的文件，改名xxx-opkg。

3. /var/etc/smartdns/smartdns.conf这个文件就是使用/etc/config/smartdns生成的。

4.生效，可以增加多个，没有限制。

**Comment by VanDeAnna** [comment]
还想问一下，WinSCP 上路由，修改并保存 /etc/smartdns/custom.conf 的配置后
新的配置，SmartDNS 是即刻生效，还是每隔一段时间读取配置后生效，或者需要重启服务才生效？

**Comment by pymumu** [comment]
要手工重启服务。

**Comment by kang-mk** [comment]
server-name smartdns
bind [::]:6053
bind-tcp [::]:6053
dualstack-ip-selection yes
prefetch-domain yes
cache-size 2048
rr-ttl-min 300
log-size 64K
log-num 1
log-level error
server 223.5.5.5  
server 223.6.6.6  
server 119.29.29.29  
server 8.8.8.8  
server 8.8.4.4  
server 117.50.10.10  
server 117.50.20.20  
server 180.76.76.76  
server 114.114.114.114  
server 114.114.115.115  
server 101.101.101.101  
server 101.102.103.104  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf



/var/etc/smartdns下面的配置文件里面是这个    WEB设置前面添加的DNS服务器名称是在什么地方存着了

**Comment by pymumu** [comment]
服务器名称只是界面帮助记忆用的，不会写如smartdns的配置文件。
只记录到/etc/config/smartdns中供界面显示使用。

**Comment by kang-mk** [comment]
看到了，那如果LEDE重装之后恢复SMARTDNS配置是应该恢复/etc/config/smartdns   还是  /var/etc/smartdns
还是要两个一起恢复？

**Comment by pymumu** [comment]
/etc/config/smartdns 
如果有自定义配置，或屏蔽广告，还需要恢复
/etc/smartdns/address.conf
/etc/smartdns/blacklist-ip.conf
/etc/smartdns/custom.conf

**Comment by kang-mk** [comment]
OK,明白，就是现在的配置文件有点乱，下一版本如果可以集中一下就更好了

**Comment by pymumu** [comment]
之前打算把配置都移动到/var/etc/smartdns下的，但有些人已经使用了/etc/smartdns的自定义配置功能。
所以有个开发版本安装做了copy，将/etc/smartdns的自定义文件，移动到/var/etc/smartdns。
但后面发现无法保证所有情况下保留自定义的配置，有情况会导致配置覆盖还原。
配置被覆盖，会很多人骂的。所以，还是保持原状兼容了。

后面会将
1. 
/etc/smartdns/smartdns.conf改名，改成/etc/smartdns/smartdns.sample
不直接使用/etc/smartdns/custom.conf，是因为openwrt规范是这样的，比如dnsmasq，配置都在/var/etc目录下。

2. 
修改开发版本遗留的将/etc/smartdns/目录文件复制到/var/etc/smartdns/的BUG。

所以，如果后面备份的话，需要备份如下文件（如果后自定义文件，还有备份自定义文件）
/etc/config/smartdns
/etc/smartdns/address.conf
/etc/smartdns/blacklist-ip.conf
/etc/smartdns/custom.conf

**Comment by VanDeAnna** [comment]
上次忘记问了，LEDE 网页端，点击“保存并应用”，是否会重启 SmartDNS 的服务？
如果不重启服务，网页端的配置岂不是要开关一次“启用”或用其他方法重启 SmartDNS，才能读取(尤其是自定义的）新的配置？

**Comment by pymumu** [comment]
点击保存后，smartdns会重启的。
