### ISSUE TITLE
域名文件功能无法使用

### ISSUE THREAD

**Issue by chengzixqq** [pymumu/smartdns#1240]
**问题现象**  
简要描述问题出现的现象
我在域名地址中使用配置文件无效果,必须手动添加进域名地址才能使用
**运行环境**
1. 固件型号  

1. LEDE R23.1.1

2. smartdns来源以及版本
40.0
4. 涉及的配置(注意去除个人相关信息)
address /domain-set:bilibili/#6    

#域名文件内信息：
acg.tv
acgvideo.com
animetamashi.cn
animetamashi.com
anitama.cn
anitama.net
b23.tv
bigfun.cn
bili22.cn
bili2233.cn
bili23.cn
bili33.cn
biliapi.com
biliapi.net
bilibili.cc
bilibili.com
bilibili.net
bilibili.tv @!cn
bilibiligame.cn
bilibiligame.co
bilibiligame.net
bilibilipay.cn
bilibilipay.com
bilicdn1.com
bilicdn2.com
bilicdn3.com
bilicdn4.com
bilicdn5.com
biligame.co
biligame.com
biligame.net
biligo.com
biliintl.com @!cn
bilivideo.cn
bilivideo.com
bilivideo.net
dreamcast.hk
hdslb.com
hdslb.org
im9.com
maoercdn.com
mincdn.com
yo9.com
upos-hz-mirrorakam.akamaized.net

**重现步骤**
![image](https://user-images.githubusercontent.com/104790283/212397563-0f5ae5ab-f140-4c59-ab6a-fd041cfabab0.png)

**Comment by PikuZheng** [comment]
> bilibili.tv @!cn

这个写法不行的
截图少了一行
