### ISSUE TITLE
openwrt下使用cache-persist一个小问题，另外能否在luci页面增加一个定时重启smartdns的选项啊？

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#1242]
smartdns相关设置
```
cache-persist yes
cache-file /usr/smartdns.cache
```

如果发送reboot命令给openwrt，smartdns就相当于killall了，实际并没有保存缓存文件

那比如我定时重启openwrt，就需要在计划任务里加一个重启smartdns的任务，比如
```
25 5 * * * reboot
20 5 * * * /etc/init.d/smartdns restart
```
这样就在重启路由器之前重启了smartdns，保存了缓存文件，然后重启路由以后启动smartdns时候就可以载入这个缓存了

我在想有没有更好的解决方案保存和载入这个缓存啊？

或者至少在luci能不能增加一个定时重启的选项，这样免去手工去弄计划任务的麻烦，使用更方便

**Comment by PikuZheng** [comment]
也许可以试试 /etc/init.d/smartdns stop && reboot

**Comment by PikuZheng** [comment]
另外问一下你的openwrt是哪个编译什么版本，我试了一下我的reboot时 smartdns是正常退出了（重启后看cache文件日期是已经保存了

**Comment by PikuZheng** [comment]
```
root@OpenWrt:/etc/smartdns# ls -lh smartdns.cache
-rw-r-----    1 root     root        1.3M Jan 16 09:04 smartdns.cache
root@OpenWrt:/etc/smartdns# reboot

....此处重启，中间省略

 -----------------------------------------------------
 OpenWrt 22.03.0, r19685-512e76967f
 -----------------------------------------------------
root@OpenWrt:~# ls -lh /etc/smartdns/smartdns.cache
-rw-r-----    1 root     root        1.3M Jan 16 09:04 /etc/smartdns/smartdns.cache
root@OpenWrt:~#

```
有没有一种可能，你的cache文件不在持久存储上

**Comment by PikuZheng** [comment]
先停止smartdns，删cache文件。然后重启（smartdns自动启动了），此时没有cache文件。再重启，也没有cache文件。这中间一定是哪里出了问题。可能openwrt在关机或重启时并没有等待procd任务完成？

**Comment by pymumu** [comment]
smartdns的重启脚本没有注册到系统服务。修改了一下，luci界面也增加了一个参数配置开关，可以获取验证看看。

**Comment by liangshixing** [comment]
> > smartdns的重启脚本没有注册到系统服务。修改了一下，luci界面也增加了一个参数配置开关，可以获取验证看看。

没看到这个开关啊？

<img width="591" alt="image" src="https://user-images.githubusercontent.com/8481414/212800218-2a93f14d-7e45-41bd-a46a-d60fc8bc9d17.png">

**Comment by liangshixing** [comment]
> 

rm -rf /tmp/luci-modulecache/*
rm /tmp/luci-indexcache*

好像也没效果

**Comment by pymumu** [comment]
把你自定义的cache-file配置删除看看，默认放到/etc/smartdns/smartdns.cache

**Comment by pymumu** [comment]
> > > smartdns的重启脚本没有注册到系统服务。修改了一下，luci界面也增加了一个参数配置开关，可以获取验证看看。
> 
> 
> 
> 没看到这个开关啊？
> 
> 
> 
> <img width="591" alt="image" src="https://user-images.githubusercontent.com/8481414/212800218-2a93f14d-7e45-41bd-a46a-d60fc8bc9d17.png">
> 
> 

清空浏览器缓存

**Comment by pymumu** [comment]
ls /etc/rc.d |grep smartdns

**Comment by PikuZheng** [comment]
```
root@OpenWrt:~# ls -l /etc/rc.d |grep smartdns
lrwxrwxrwx    1 root     root            18 Dec 23 09:45 S19smartdns -> ../init.d/smartdns
lrwxrwxrwx    1 root     root            18 Sep 29 14:27 S99smartdns -> ../init.d/smartdns
```
😥

**Comment by pymumu** [comment]
可能是你们直接替换脚本了，替换脚本的话，执行下面命令，生成重启链接。
```
/etc/init.d/smartdns enable
```

**Comment by PikuZheng** [comment]
> /etc/init.d/smartdns enable

多了一个 K1smartdns

覆盖安装的

**Comment by pymumu** [comment]
升级安装我在22.03上验证是正常的。

**Comment by PikuZheng** [comment]
> 生成的文件，应该是K82smartdns。

是我文件乱套了😭

>重启后cache文件时间还是路由重启以后的，

莫非是你的smartdns在系统启动时还会重启一次？

**Comment by yyysuo** [comment]
> 把你自定义的cache-file配置删除看看，默认放到/etc/smartdns/smartdns.cache

大佬，我跟[qwerttvv](https://github.com/qwerttvv)的情况一模一样，
/tmp/etc/smartdns/smartdns.conf相关配置为：
cache-persist yes
cache-file /etc/smartdns/smartdns.cache

conf-file /etc/smartdns/custom.conf中相关配置为：
cache-file /usr/smartdns.cache

执行命令如下：
root@Openwrt100:~# ls /etc/rc.d |grep smartdns
K82smartdns@
S19smartdns@

root@Openwrt100:~# ls -l /etc/rc.d |grep smartdns
lrwxrwxrwx    1 root     root            18 Mar 21 00:24 K82smartdns -> ../init.d/smartdns*
lrwxrwxrwx    1 root     root            18 Mar 21 00:24 S19smartdns -> ../init.d/smartdns*

实际的效果是缓存文件保存在了/usr/smartdns.cache，重启会丢失，我现在应该怎么做才是正确的呢？

**Comment by PikuZheng** [comment]
> 实际的效果是缓存文件保存在了/usr/smartdns.cache，重启会丢失，版本是https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.14-OpenWrt
> 我现在应该怎么做才是正确的呢？我目前把conf-file /etc/smartdns/custom.conf中的内容注释掉，使用/etc/init.d/smartdns restart命令重启了一下服务，这样就可以了吗？
> 

中间已经改了若干个版本了。。在custom里配置正确路径就可以了。后配置的会覆盖前配置的。
启动停止脚本不用管。

**Comment by yyysuo** [comment]
> > 实际的效果是缓存文件保存在了/usr/smartdns.cache，重启会丢失，版本是https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.14-OpenWrt
> > 我现在应该怎么做才是正确的呢？我目前把conf-file /etc/smartdns/custom.conf中的内容注释掉，使用/etc/init.d/smartdns restart命令重启了一下服务，这样就可以了吗？
> 
> 中间已经改了若干个版本了。。在custom里配置正确路径就可以了。后配置的会覆盖前配置的。 启动停止脚本不用管。

我用您编译的最新版本，实际上还是出现无法保存的问题，并不是每次重启都无法保存。

**Comment by PikuZheng** [comment]
> 实际上还是出现无法保存的问题，并不是每次重启都无法保存。

完全无法理解 🤣

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/config/cache/
