### ISSUE TITLE
pavadan 开启smartdns后，不能登录路由器后台

### ISSUE THREAD

**Issue by octopus2181** [pymumu/smartdns#1243]
**问题现象**  
简要描述问题出现的现象
pavadan 开启smartdns后，不能登录内网的路由器后台（192.168.2.1）
除了不能访问路由器后台（192.168.2.1），其他都是域名解析都没有问题，
nslookup -querytype=ptr smartdns，显示
Server:         192.168.2.1
Address:        192.168.2.1#53
但是Non-authoritative answer显示错误
具体记不清了，登录不了路由器。

**Comment by PikuZheng** [comment]
不能登陆时报什么错误？此时ssh是好的吗？

**Comment by chenzhen2181** [comment]
路由器没开启ssh，所以也登不进去

**Comment by chenzhen2181** [comment]
刚重启了下路由器，可以登陆了‘不好意思
