### ISSUE TITLE
smartdns会自动清除自定义计划任务

### ISSUE THREAD

**Issue by wyjtm** [pymumu/smartdns#1245]
**问题现象**  
smartdns会在安装配置后自动清除所有用户自定义计划任务
也会在路由重启后自动清除所有用户自定义计划任务，并在计划任务里只写入 0 5 * * * /etc/init.d/smartdns updatefiles

**运行环境**
1. 固件型号  OpenWrt 22.03.2 

2. 运营商  

3. smartdns来源以及版本
https://openwrt.org/zh/start

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
代码逻辑上，只会清除smartdns脚本相关的计划任务，不会清空其他不相关的任务。

提供cron内容和复现过程以便明确问题。

**Comment by wyjtm** [comment]
> 代码逻辑上，只会清除smartdns脚本相关的计划任务，不会清空其他不相关的任务。
> 
> 请确认是否有其他软件清空，或提供cron内容和复现过程以便明确问题。

请问该怎么提供cron

**Comment by PikuZheng** [comment]
> 请问该怎么提供cron

系统 - 计划任务 这个框框里，清空前配置了哪些项目？大概过多久发现里面内容清空了？

![image](https://user-images.githubusercontent.com/12579522/213841929-460147a9-6ec5-4dc3-a97a-53f876f2e01b.png)

**Comment by wyjtm** [comment]
> > 请问该怎么提供cron
> 
> 系统 - 计划任务 这个框框里，清空前配置了哪些项目？大概过多久发现里面内容清空了？
> 
> ![image](https://user-images.githubusercontent.com/12579522/213841929-460147a9-6ec5-4dc3-a97a-53f876f2e01b.png)

目前在安装smartdns之前只配置了
0 4 * * * sleep 5 && touch /etc/banner && reboot

这条重启命令

前几天才更新了22.03.2 什么都没装只只是在发issues的前一天装上[Release 40]并配置好启用  第二天准备弄下upnp发现路由没有自动重启过 联网时间超过24h，发现不对头才注意到命令没了

因为是之前只安装过smartdns，我重置路由又装一遍发现确实是在配置完smartdns在启用后 我自己的计划任务重启命令就没了
计划任务里会只剩下一行0 5 * * * /etc/init.d/smartdns updatefiles
不确定是配置完smartdns启用了后才被覆盖还是配置途中就被覆盖了，所以都写上了

**Comment by PikuZheng** [comment]
![image](https://user-images.githubusercontent.com/12579522/213870592-f1aa29a2-161b-4465-8601-7cc4308c820f.png)
试了几次我这是好的。猜测是你的系统有特殊的文件系统？可以在重置后配置smartdns前看一下 这个文件夹有啥
```
ls -l /etc/crontabs
```

**Comment by InoryLwc** [comment]
这个是因为你的openwrt有定时重启的插件，它会检测定时任务的reboot命令。定时重启关闭时，会删除reboot相关的任务。

**Comment by tycn888** [comment]
请问加：计划任务的时间可以自定义吗？
大家都是自动设置为5:00更新下载，例如广告拦截，域名清单等，感觉不太好呀。

**Comment by PikuZheng** [comment]
> 请问加：计划任务的时间可以自定义吗？
> 大家都是自动设置为5:00更新下载，例如广告拦截，域名清单等，感觉不太好呀。

系统 - 计划任务 可以自己改时间啊

**Comment by tycn888** [comment]
> > 请问加：计划任务的时间可以自定义吗？
> > 大家都是自动设置为5:00更新下载，例如广告拦截，域名清单等，感觉不太好呀。
> 
> 系统 - 计划任务 可以自己改时间啊

会被自动还回去，还是变为5：00。

**Comment by pymumu** [comment]
用最新代码看看
