### ISSUE TITLE
nslookup themoviedb.org返回多个ip地址

### ISSUE THREAD

**Issue by rongcc1985** [pymumu/smartdns#1248]
**问题现象**  
国内网站正常，nslookup baidu或qq都只返回一个地址
国外的谷歌、youtube也只返回一个地址。

themoviedb.org在浏览器可以正常打开，但返回的地址如下：

服务器:  rongcc
Address:  127.0.0.1

非权威应答:
名称:    themoviedb.org
Addresses:  13.32.99.70
          13.32.27.13
          13.32.27.125
          13.32.27.95
          13.32.99.105
          13.32.27.42
          13.32.99.99

**运行环境**
1. 固件型号  
wsl-1，ubuntu
2. 运营商  
广西电信
3. smartdns来源以及版本
smartdns.1.2023.01.02-1537.x86_64-linux-all.tar.gz
4. 涉及的配置(注意去除个人相关信息)
在默认配置的最后增加了
server 119.29.29.29
server 8.8.8.8

PS：我的初始诉求是想让群晖的jellyfin可以使用smartdns完成themoviedb的刮削（我之前是翻墙来刮削的），但没有成功。于是在wsl里测试看看themoviedb是什么情况。结果才发现nslookup返回的地址数量不对。

**重现步骤**
1. 上游DNS配置。  
server 119.29.29.29
server 8.8.8.8
2. 访问的域名。  
themoviedb.org

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
无

**Comment by PikuZheng** [comment]
预期行为，如果只要一个IP可以通过max-reply-ip限制

**Comment by PikuZheng** [comment]
参考 #1226
