### ISSUE TITLE
关于first-ping测速机理的理解，不知是不是这样

### ISSUE THREAD

**Issue by GuiDeJuShi** [pymumu/smartdns#1249]
**问题现象**  
文档中对response mode中默认的first-ping模式的解释看了还不太懂，自己琢磨了一下，不知是不是这样——解析结果中最早ping通的IP？也就是在这个模式下，各上游服务器反馈结果后，本软件同时ping这些结果，把第一个收到ping返回的数据的服务器地址反馈给请求查询的客户端？不知是不是这样？谢谢！

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
半年前改了response-mode功能后，我一直认为这个参数不甚明确。作者的解释在这里 https://github.com/pymumu/smartdns/issues/999#issuecomment-1200576715

根据我实际使用的体验，我认为 response-mode 只影响在缓存没有命中时 smartdns 对下游查询的应答行为。但是作用效果，response-mode 和 speed-check-mode 共同影响，应 结合起来分析。

**Comment by PikuZheng** [comment]
response-mode 和 speed-check-mode 相互作用参考 https://github.com/pymumu/smartdns/issues/1028#issue-1345875307
