### ISSUE TITLE
请问windows10里如何配置才能跑起来

### ISSUE THREAD

**Issue by clonedpig** [pymumu/smartdns#125]
你好，我在window10 商店里安装了ubuntu，也安装了smartdns在D盘根目录。

请问conf文件里的DNS服务器和本地连接里的DNS服务器分别填写啥才能跑起来？

目前的情况是：

1）两端都填写路由器分配的ip，如 192.168.2.49，跑不通，网页无法打开；

2）两端都填写127.0.0.1，也跑不通。

3）conf里填写 192.168.2.49， 本地连接里填写dns服务器为127.0.0.1 也跑不通

**Comment by pymumu** [comment]
参考这里操作吧
https://github.com/pymumu/smartdns#windows-10-wsl%E5%AE%89%E8%A3%85wsl-ubuntu

**Comment by clonedpig** [comment]
作者你好，就是按这里的说明进行操作，但是跑不通。不太明白conf里和 本地连接里 dns 服务器该怎么设置。

**Comment by pymumu** [comment]
1. smartdns.conf里面增加上游DNS地址。
配置参数参考：
https://github.com/pymumu/smartdns#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0
主要配置server即可，配置完双击restart.bat重启smartdns

2. 修改windows默认DNS服务器为127.0.0.1 
https://support.microsoft.com/zh-cn/help/15089/windows-change-tcp-ip-settings

**Comment by LazyZhu** [comment]
目前windows使用太麻烦了.
@pymumu cygwin应该可以直接编译的吧(mingw麻烦点需要改源码)

**Comment by pymumu** [comment]
@LazyZhu 
cygwin不会支持，wsl操作步骤只是方式和cgywin不同，步骤数目都是差不多的，差不多都是6步。
你仔细看一下wsl的安装指导吧，
https://github.com/pymumu/smartdns#windows-10-wsl%E5%AE%89%E8%A3%85wsl-ubuntu

这里有一个一键安装的，@rufengsuixing 写的。
https://github.com/pymumu/smartdns/issues/107

**Comment by LazyZhu** [comment]
@pymumu ?
你这是没用过cgywin吧, 除了开发者编译需要安装cgywin环境,用户是不用安装其他东西的,建议Google下吧.

**Comment by pymumu** [comment]
支持cygwin不是你认为的那么简单，cygwin接口和Linux并不兼容。有很多代码要修改的。
smartdns为了轻量化高性能，使用了很多Linux特有的API，比如epolll，netfilter，ping API，这些API cygwin并不支持，要支持的话，改造工作量很大，这都已经偏离smartdns的初衷了。

WSL占用空间虽然比cygwin多，但其他没有问题，也有一键安装脚本。使用上并不复杂。
并且WSL兼容更多Linux应用，可玩性更高。

所以，不会考虑支持cygwin，macOS也不会支持。

**Comment by pymumu** [comment]
指导中已经说明如何在WSL中使用，请参考，有问题再提交issue。
