### ISSUE TITLE
只填写DoT\DoH地址无法联网

### ISSUE THREAD

**Issue by Linkdaimaou** [pymumu/smartdns#1250]
设备：openwrt 5.15.85 (x86)

smartdns版本：luci-app-smartdns.1.2023.01.02-1537.all-luci-compat-all
                          smartdns.1.2023.01.02-1537.x86_64-openwrt-all
                           设置转发6053端口

问题：op拨号成功已取得IP地址，在只填写DoT\DoH 的情况下打不开网页，但是添加一个udp（例如：百度dns 180.76.76.76）重新应用就可以恢复正常。在openwrt实时信息里也能看到DoT\DoH正常解析到地址。

DoT\DoH国内国外的地址都填上了，阿里\腾讯\谷歌\Cloudflare
![1674501520364](https://user-images.githubusercontent.com/118063404/214130050-20e6007d-83e3-46f3-848b-5044a7a237ae.png)

**Comment by PikuZheng** [comment]
重复 #567 #524 #613 #677 #887 #949 #1036 #1207

**Comment by Linkdaimaou** [comment]
谢谢

**Comment by Linkdaimaou** [comment]
> 复原[#567 ](https://github.com/pymumu/smartdns/issues/567) [#524 ](https://github.com/pymumu/smartdns/issues/524) [#613 ](https://github.com/pymumu/smartdns/issues/613) [#677 ](https://github.com/pymumu/smartdns/issues/677) [#887 ](https://github.com/pymumu/smartdns/issues/887) [#949 ](https://github.com/pymumu/smartdns/issues/949) [#1036 ](https://github.com/pymumu/smartdns/issues/1036) #1207

谢谢

**Comment by jxph1123** [comment]
填一个IP地址形式的DoT\DoH都行，不一定非要UDP

**Comment by Linkdaimaou** [comment]
谢谢

________________________________
发件人: jxph1123 ***@***.***>
发送时间: 2023年1月29日 11:14
收件人: pymumu/smartdns ***@***.***>
抄送: Linkdaimaou ***@***.***>; Author ***@***.***>
主题: Re: [pymumu/smartdns] 只填写DoT\DoH地址无法联网 (Issue #1250)


填一个IP地址形式的DoT\DoH都行，不一定非要UDP

―
