### ISSUE TITLE
上游若使用 180.76.76.76则会引起浏览器随机 ERR_QUIC_PROTOCOL_ERROR 或者 PR_CONNECT_RESET_ERROR 错误(主要是谷歌类网站如搜索和youtube，未在其他网站遇到)

### ISSUE THREAD

**Issue by skygunner** [pymumu/smartdns#1252]
**问题现象**  
Pihole使用smartdns作为upstream DNS， 访问谷歌系网站会间歇性出现 ERR_QUIC_PROTOCOL_ERROR 或者 PR_CONNECT_RESET_ERROR

**运行环境**
1. Version:
1.2023.01.02-1537 running on Pihole/Armbian  

2. ISP:
Aussie Broadband/Australia 

3. smartdns来源以及版本
Github download

4. 涉及的配置(注意去除个人相关信息)
bind [::]:7053
server 8.8.4.4
server 1.1.1.1
server 8.8.8.8
server 119.29.29.29
server 223.6.6.6
server 114.114.114.114
server 180.76.76.76
server 101.226.4.6
server 123.125.81.6
server 223.5.5.5
server-tcp 8.8.4.4
server-tcp 1.1.1.1
server-tcp 119.29.29.29
server-tcp 223.6.6.6
server-tls 8.8.4.4
server-tls 1.1.1.1
cache-size 16384
rr-ttl-min 600
prefetch-domain yes
serve-expired yes
dualstack-ip-selection yes
force-qtype-SOA 65
log-file /var/log/smartdns/smartdns.log
log-level info

**重现步骤**
1. 上游DNS配置。  
如上。
Client->Pohole->SmartDNS running on localhost#7053

2. 访问的域名。  
访问谷歌系域名，如谷歌搜索， Youtube，会间歇性出现此错误。 其它网站似乎未报错。
Chrome/Firefox一样。 电脑和手机一样。 

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by skygunner** [comment]
I guess maybe the reason is the project is not support QUIC yet

**Comment by PikuZheng** [comment]
代理问题，只要谷歌域名解析到谷歌ip了就和smartdns无关

**Comment by skygunner** [comment]
> 代理问题，只要谷歌域名解析到谷歌ip了就和smartdns无关

没有使用代理服务器呀

**Comment by PikuZheng** [comment]
> > 代理问题，只要谷歌域名解析到谷歌ip了就和smartdns无关
> 
> 没有使用代理服务器呀

我的错。。。没注意到是肉翻。如果去掉smartdns，pi-hole直接对接上游服务器，还会有这样的故障吗？

**Comment by pymumu** [comment]
是不是配置了国内dns导致？可以去掉看看

**Comment by skygunner** [comment]
去掉了国内的DNS服务器， 正在测试之中

**Comment by skygunner** [comment]
测试了一个月结果：

上游若使用 180.76.76.76则会引起浏览器随机 ERR_QUIC_PROTOCOL_ERROR 或者 PR_CONNECT_RESET_ERROR 错误(主要是谷歌类网站如搜索和youtube，未在其他网站遇到)

这个是百度的DNS吧。 不知道是smartdns的缺陷，还是百度搞鬼。 

而测试过程中用了几个星期阿里的223.5.5.5则没有任何问题

**Comment by pymumu** [comment]
应该是百度返回的ip有问题，smartdns不会自己生成ip，可以查下有问题的ip归属地

**Comment by devioa** [comment]
`QUIC`的原因，我在国内有时候也会这样
目前`QUIC/HTTP3`还是草案不是很稳定
并且现在没有多少DNS服务器可以响应`SVCB/HTTPS`记录（国内好像就腾讯DNSPod+和国外的Cloudflare支持）
可以在`chrome://flags/`或者`edge://flags/`里搜索quic相关特性并禁用
