### ISSUE TITLE
华硕AX 11000无法安装

### ISSUE THREAD

**Issue by ykhuazai** [pymumu/smartdns#1253]
**问题现象**  
简要描述问题出现的现象
已将smartdns.1.2023.01.02-1537.arm-optware-all.ipk文件放在u盘根目录
ipkg install smartdns.1.yyyy.MM.dd-REL.mipsbig.ipk运行该命令一直提示-sh: ipkg: not found
**运行环境**
1. 固件型号  
koolcenter的梅林改版 388.1_rog
2. 运营商  
电信
3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
啥意思，缺Download Master组件？建议在固件那边询问
