### ISSUE TITLE
domain-set的选择逻辑

### ISSUE THREAD

**Issue by unicser** [pymumu/smartdns#1254]
对于同一个域名位于不同的domain-set中，不同的domain-set通过domain-rule指定了不同上游nameserver，这种场景下似乎对于这个域名只会选择其中一个domain-set，有没有可能指定其中的一个domain-set为高优先级？譬如多个domain-set中其中一个是自动维护的（如自动下载gfw list），另一个手动维护的希望有更高的优先级，不走前面的gfw list

**Comment by PikuZheng** [comment]
我测试是根据载入先后顺序，先载入的生效

**Comment by unicser** [comment]
> 我测试是根据载入先后顺序，后载入的生效

看了下配置文件说明，似乎没有选项指定载入先后顺序，是否有可供参考的配置文件写法

**Comment by PikuZheng** [comment]
参考 #128

**Comment by unicser** [comment]
测试了一下，对于相同配置而言，譬如下面的配置，确实是最后出现的生效，因为domain-rules /domain-set:114-list/属于重复配置。
```
server 114.114.114.114 -group 114ns -exclude-default-group
domain-set -n 114-list -t list -f /tmp/114-list.txt
domain-rules /domain-set:114-list/ -n 114ns -speed-check-mode none

server 223.5.5.5 -group alins -exclude-default-group
domain-set -n ali-list -t list -f /tmp/ali-list.txt
domain-rules /domain-set:114-list/ -n alins -speed-check-mode none

server 119.29.29.29 -group dnspod -exclude-default-group
domain-set -n dnspod-list -t list -f /tmp/dnspod-list.txt
domain-rules /domain-set:114-list/ -n dnspod -speed-check-mode none
```


但是如果把配置改为下面的设置时，这时候domain-rules并没有重复配置，三个list文件中都存在baidu.com，这时候去解析www.baidu.com确选择了alins，多次重启smartdns进程也未观察到变化。所以看起来ali-list.txt总是最后加载的，但是不知道加载顺序的逻辑。我期望的是能找到某种方法来控制其中的优先级。
```
server 114.114.114.114 -group 114ns -exclude-default-group
domain-set -n 114-list -t list -f /tmp/114-list.txt
domain-rules /domain-set:114-list/ -n 114ns -speed-check-mode none

server 223.5.5.5 -group alins -exclude-default-group
domain-set -n ali-list -t list -f /tmp/ali-list.txt
domain-rules /domain-set:ali-list/ -n alins -speed-check-mode none

server 119.29.29.29 -group dnspod -exclude-default-group
domain-set -n dnspod-list -t list -f /tmp/dnspod-list.txt
domain-rules /domain-set:dnspod-list/ -n dnspod -speed-check-mode none
```

**Comment by 4thanks** [comment]
印象中没有优先级，如果有相同的配置，靠后的会覆盖之前，仅执行一次。

**Comment by pymumu** [comment]
domain-set这里代码是hashmap，顺序随机。

最新代码修改了一下逻辑，保证顺序读取和生效。

**Comment by unicser** [comment]
> domain-set这里代码是hashmap，顺序随机。
> 
> 最新代码修改了一下逻辑，保证顺序读取和生效。

谢谢，看来这个问题已经解决了。

**Comment by InspoOnU** [comment]
> domain-set这里代码是hashmap，顺序随机。
> 
> 最新代码修改了一下逻辑，保证顺序读取和生效。

如果越靠后优先级越高，是不是去广告的address规则要放在其他规则的后面呢？
