### ISSUE TITLE
address 能否为一个域名指定多个IP？

### ISSUE THREAD

**Issue by ddd-zero** [pymumu/smartdns#1256]
因为有一个域名想指定到日本的cdn上，但只指定一个ip怕该IP失效后会影响使用，所以想为该域名多指定几个。
使用address 尝试了几种写法都不生效。是不是不支持指定多个IP

**Comment by PikuZheng** [comment]
不支持，后设置的会覆盖前设置的。
我是用其他dns服务器处理这事的
