### ISSUE TITLE
新版smartdns下，passwall里怎么没有smartdns分流选项了？！！！！！

### ISSUE THREAD

**Issue by Xymmh** [pymumu/smartdns#1257]
非常难受呜呜呜

**Comment by cncqcyc** [comment]
是passwall那边改了，跟smartdns无关，其实没有这个选项也没有关系，设置方式没什么太大的改变

**Comment by Xymmh** [comment]
> 是passwall那边改了，跟smartdns无关，其实没有这个选项也没有关系，设置方式没什么太大的改变

根本不会设置了呜呜呜

**Comment by cncqcyc** [comment]
> > 是passwall那边改了，跟smartdns无关，其实没有这个选项也没有关系，设置方式没什么太大的改变
> 
> 根本不会设置了呜呜呜

smartdns这边设置方法不需要改变，passwall那边建议开启chinadns-ng，远程dns还是跟原来一样指向smartdns的第二服务器

**Comment by Xymmh** [comment]
> > > 是passwall那边改了，跟smartdns无关，其实没有这个选项也没有关系，设置方式没什么太大的改变
> > 
> > 
> > 根本不会设置了呜呜呜
> 
> smartdns这边设置方法不需要改变，passwall那边建议开启chinadns-ng，远程dns还是跟原来一样指向smartdns的第二服务器

我原来根本就没有开启smartdns的第二服务器，passwall直接选择smartdns分流，选择Requery DNS by UDP，远程DNS设置为1.1.1.1，同时smartdns将第一服务器（用来解析正常域名）配置好即可愉快使用

**Comment by Xymmh** [comment]
感觉之前是passwall丢给smartdns一个配置文件，域名解析由smartdns完成。现在没了smartdns分流以后，即使我配置passwall Requery DNS by TCP，远程DNS设置为1.1.1.1，虽然可以正常使用，但nslookup会发现一个 :: 的IPv6地址，说明现在域名解析由passwall完成，且passwall的IPv6屏蔽功能没smartdns做的好

**Comment by Xymmh** [comment]
非常讨厌，怎么才能恢复原来呢！！！

**Comment by cncqcyc** [comment]
你原来的设置，远程dns（国外）解析根本没有通过smartdns，是passwall内你选的的1.1.1.1解析的，只是因为原来的passwall有smartdns选项，passwall会生成一个域名规则的文件，里面会把国内dns解析给了smartdns，远程dns还是自身内解析

**Comment by Xymmh** [comment]
你说的不对，原来那个配置文件直接让smartdns创建了一个新DNS组并且排除了默认组，通过1.1.1.1解析我选择的代理规则里的所有域名，其实就相当于直接开启了第二DNS服务器。现在反而要自己开启第二DNS服务器，非常烦人

**Comment by cncqcyc** [comment]
你的理解有误，原来那个配置文件是passwall生成的一个空dns组，而且是固定的passwall_proxy组名，smartdns没有产生任何新的dns组，smartdns后来改了加载规则还因为这个问题曾经有一段时间很多人因为设置问题在使用passwall出了错

**Comment by zmjjack** [comment]
> 你的理解有误，原来那个配置文件是passwall生成的一个空dns组，而且是固定的passwall_proxy组名，smartdns没有产生任何新的dns组，smartdns后来改了加载规则还因为这个问题曾经有一段时间很多人因为设置问题在使用passwall出了错

那现在没有smartdns分流选项，要怎么设置？关键是要让smartdns为主dns，也就是53端口。

**Comment by cncqcyc** [comment]
> > 你的理解有误，原来那个配置文件是passwall生成的一个空dns组，而且是固定的passwall_proxy组名，smartdns没有产生任何新的dns组，smartdns后来改了加载规则还因为这个问题曾经有一段时间很多人因为设置问题在使用passwall出了错
> 
> 那现在没有smartdns分流选项，要怎么设置？关键是要让smartdns为主dns，也就是53端口。

smartdns推出作为主dns后的一段时间里我曾经尝试过，但在使用一段时间后会有点问题，所以一直是用第二服务器的方式，没再研究这个问题，初步理解，如果你要smartdns做主dns，它占用53端口，passwall的远程dns也得转发到53端口，这时国内国外的dns解析都通过53端口，你得在smartdns这里分流，需要你自己写域名规则，而这个东西原来passwall帮你写好了的，如果使用第二服务器组就不存在这个问题，因为passwall直接进行了分流

**Comment by zmjjack** [comment]
看来没有PW分流选项后，设置上还是有很大变化的。

**Comment by cncqcyc** [comment]
如果之前用第二服务器组的话设置没什么变化，smartdns这里反而简单了，国内组不用单独取名，直接默认组，国外组里设置排除默认组就自然分流了

**Comment by zmjjack** [comment]
用smartdns其实就是想让它代替dnsmasq，作为主dns。现在看来如果要配合PW，那就不能设为主dns了。

**Comment by cncqcyc** [comment]
> 用smartdns其实就是想让它代替dnsmasq，作为主dns。现在看来如果要配合PW，那就不能设为主dns了。

这跟设smartdns为主dns其实不冲突，开启第二服务器组也不影响主dns，但你只使用53端口就必须得自己设置分流，如果你再绑定另外一个端口，那实际上就是开启第二服务器组，你看passwall的日志就会明白，它有警告，分流严重依赖dnsmaq，设置错误会导致分流失败，所以设置很关键，默认国内或者白名单dns由dnsmaq解析，可信dns要么由passwall内置的dns解析，要么发送到其它端口通过第三方dns解析

**Comment by PikuZheng** [comment]
为什么不试试在passwall那边提issue呢

**Comment by love768952693** [comment]
> > 用smartdns其实就是想让它代替dnsmasq，作为主dns。现在看来如果要配合PW，那就不能设为主dns了。
> 
> 这跟设smartdns为主dns其实不冲突，开启第二服务器组也不影响主dns，但你只使用53端口就必须得自己设置分流，如果你再绑定另外一个端口，那实际上就是开启第二服务器组，你看passwall的日志就会明白，它有警告，分流严重依赖dnsmaq，设置错误会导致分流失败，所以设置很关键，默认国内或者白名单dns由dnsmaq解析，可信dns要么由passwall内置的dns解析，要么发送到其它端口通过第三方dns解析 passwall的源码里专门有针对乱设dns的保护措施，主要是保护dnsmasq的设置，所以你如果不用dnsmasq可能会带来潜在的风险

大佬解惑了我多年来的疑问了，每次smartdns设置为53端口时，passwall哪怕设置了第二组DNS，或是国外DNS时，在使用GFW列表模式时，不能科学上网。。。。。。

**Comment by jxph1123** [comment]
用ssr plus吧，可以直接用smartdnds设置5335端口解析

**Comment by pymumu** [comment]
没用过pass-wall，可以设计下

也可以参考readme，faq的13简单搭建

**Comment by xiaorouji** [comment]
可以先尝鲜一下 [luci-smartdns-new-version](https://github.com/xiaorouji/openwrt-passwall/tree/luci-smartdns-new-version) 分支，注意smartdns版本要最新的 [Release 41 RC1](https://github.com/pymumu/smartdns/releases/tag/Release41-RC1)

**Comment by jxph1123** [comment]
> 如果之前用第二服务器组的话设置没什么变化，smartdns这里反而简单了，国内组不用单独取名，直接默认组，国外组里设置排除默认组就自然分流了

我就是这个设置的，反而更简单了，看passwall的日志，就是根据GFW规则，国内的走默认组6053，国外的走第二服务器5335了，不知道我的理解对不对。
![image](https://user-images.githubusercontent.com/35351787/223379926-f2dee23c-d09b-475b-b87c-9fe7f34c7f66.png)
![image](https://user-images.githubusercontent.com/35351787/223380140-dbaf7db6-872d-4a5d-b101-3fb349852f01.png)
![image](https://user-images.githubusercontent.com/35351787/223380286-cc4f3112-6c71-4f63-9921-1b144012ebde.png)
![image](https://user-images.githubusercontent.com/35351787/223380399-d564cb03-b5d7-40e2-beba-22be41c7c639.png)

**Comment by cncqcyc** [comment]
建议用passwall的luci-smartdns-new-version分支，只需在smartdns这边设置好国内分组和国内dns上游服务器，不需要启用第二dns服务器，也不需要设置可信dns服务器，而是由passwall那里代替设置了，设置更加简单了，也不会出错。
![image](https://user-images.githubusercontent.com/81218740/223384001-e9bce14a-22fe-4539-8279-18a9d547baaf.png)

**Comment by jxph1123** [comment]
我的理解luci-smartdns-new-version这个版本，国外组变成passwall自己解析了，国内组用得smartdns，而我需要国外组也由smartdns解析。

**Comment by cncqcyc** [comment]
不是这样的，passwall这边设置的dns服务器实际就是smartdns这边的第二服务器组，大佬防止设置错误帮着设置了，通过附加配置文件给到smartdns，新版smartdns和smartdns分支的passwall通过proxy-server的socks通讯的，跟原来的设置不一样

**Comment by pymumu** [comment]
可以让passwall修改smartdns的luci配置，这样会比较好，避免配置冲突。

**Comment by jxph1123** [comment]
> 不是这样的，passwall这边设置的dns服务器实际就是smartdns这边的第二服务器组，大佬防止设置错误帮着设置了，通过附加配置文件给到smartdns，新版smartdns和smartdns分支的passwall通过proxy-server的socks通讯的，跟原来的设置不一样



> 可以让passwall修改smartdns的luci配置，这样会比较好，避免配置冲突。

哦，明白了，我以为远程DNS是passwall自己解析了，原来还是要传到smartdns。

**Comment by jxph1123** [comment]
我想问下，用新版的luci-smartdns-new-version和用老板本的自己配置的第二服务器，达到的效果和结果有没有区别，谢谢~~

![image](https://user-images.githubusercontent.com/35351787/223432378-58e63926-762f-48f3-899d-f0277b35a284.png)
![image](https://user-images.githubusercontent.com/35351787/223432055-da0a3711-bd42-4a1e-8ec1-a2502fda8dc8.png)

**Comment by cncqcyc** [comment]
实际上好几个版本以前这样设置都需要自己改一下源码才好使，新版更不推荐这样设置了。
这是luci-smartdns-new-version版本生成的配置文件，里面的几个server就是passwall里选择的远程dns列表，就相当于smartdns第二服务器里自己设的海外dns，它已经设置成排除默认组了，并归到passwall_proxy组里
![image](https://user-images.githubusercontent.com/81218740/223443239-ab4bbf99-84e0-47a3-ae12-6dc1f55c1e5e.png)

**Comment by cncqcyc** [comment]
> 我想问下，用新版的luci-smartdns-new-version和用老板本的自己配置的第二服务器，达到的效果和结果有没有区别，谢谢~~
> 
> _**新版本：**_
> 
> ![image](https://user-images.githubusercontent.com/35351787/223432378-58e63926-762f-48f3-899d-f0277b35a284.png)
> 
> **_老板本：_**
> 
> ![image](https://user-images.githubusercontent.com/35351787/223432055-da0a3711-bd42-4a1e-8ec1-a2502fda8dc8.png)

效果基本上没什么区别，第二服务器组里的那几个选项，禁止测速默认是开启的，双栈优选里因为ipv6对代理并不友好，passwall默认也过滤了，但也可以代理，cache一般也是启用的，其它就没有什么可设置的了

**Comment by jxph1123** [comment]
> 建议用passwall的luci-smartdns-new-version分支，只需在smartdns这边设置好国内分组和国内dns上游服务器，不需要启用第二dns服务器，也不需要设置可信dns服务器，而是由passwall那里代替设置了，设置更加简单了，也不会出错。 smartdns这边设置 ![image](https://user-images.githubusercontent.com/81218740/223385292-17eb320a-a5b1-4531-9216-7c18c13aa0f1.png) passwall的设置 ![image](https://user-images.githubusercontent.com/81218740/223384001-e9bce14a-22fe-4539-8279-18a9d547baaf.png)

我想请教下，用luci-smartdns-new-version，国内分组cn需要设置排除默认组？谢谢

**Comment by cncqcyc** [comment]
smartdns里的上游dns服务器只要不设置排除默认组，它们都是默认组的成员，而不管它们自身原来属于哪个组，passwall已经把海外dns服务器排除了默认组，所以国内组就不要再排除默认组了，否则smartdns的默认组里的成员为空，那就会出现一个问题：因为gfw和chnlist等名单都有对应的服务器组解析，在这里是cn组和passwall_proxy组，但是有很多名单外的dns解析没有对应的上游dns服务器解析，这时smartdns就会采用默认组里的成员来解析，如果默认组里成员为空，就无法进行解析了

**Comment by jxph1123** [comment]
> smartdns里的上游dns服务器只要不设置排除默认组，它们都是默认组的成员，而不管它们自身原来属于哪个组，passwall已经把海外dns服务器排除了默认组，所以国内组就不要再排除默认组了，否则smartdns的默认组里的成员为空，那就会出现一个问题：因为gfw和chnlist等名单都有对应的服务器组解析，在这里是cn组和passwall_proxy组，但是有很多名单外的dns解析没有对应的上游dns服务器解析，这时smartdns就会采用默认组里的成员来解析，如果默认组里成员为空，就无法进行解析了

研究了下，luci-smartdns-new-version分流很好用，受passwall的“当使用中国列表外时的默认DNS：选择直连还是远程“这个启发，我国内组CN设置排除默认组，然后默认组只留了一个1.0.0.1，这样在gfw和chnlist名单外的dns解析采用1.0.0.1解析，这样就达到了防止DNS泄漏的目的了。毕竟名单外的也不多，速度基本没影响。
![image](https://user-images.githubusercontent.com/35351787/224488903-13163e0e-c274-4f88-aba7-a0b96fa287c2.png)

**_目前我的设置，感觉很完美了：_**

_**passwall：**_

![image](https://user-images.githubusercontent.com/35351787/224488937-e2e78bd0-abc3-4af9-b350-454203d37626.png)

![image](https://user-images.githubusercontent.com/35351787/224489269-c73a02a0-a0b9-4d6e-83b2-31ece2c3b7bc.png)


**_smartdns设置（只需要默认组和第一组）：_**

```
# Add custom settings here.

# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
log-level info

# log-size k,m,g
log-size 512k

# log-file /var/log/smartdns.log
# log-num 2

# List of hosts that supply bogus NX domain results
# bogus-nxdomain [ip/subnet]

#speed-check-mode tcp:443,tcp:80,ping

#bootstrap
server-https https://223.6.6.6/dns-query -bootstrap-dns 

#默认组
server-https https://cloudflare-dns.com/dns-query -group
server-tls 1dot1dot1dot1.cloudflare-dns.com -group

#国内组
server-https https://dns.alidns.com/dns-query -group cn -exclude-default-group
server-tls dns.alidns.com -group cn -exclude-default-group
server-https https://doh.pub/dns-query -group cn -exclude-default-group
server-tls dot.pub -group cn -exclude-default-group
server-https https://doh.360.cn/dns-query -group cn -exclude-default-group
server-tls dot.360.cn -group cn -exclude-default-group
```

**Comment by cncqcyc** [comment]
> > smartdns里的上游dns服务器只要不设置排除默认组，它们都是默认组的成员，而不管它们自身原来属于哪个组，passwall已经把海外dns服务器排除了默认组，所以国内组就不要再排除默认组了，否则smartdns的默认组里的成员为空，那就会出现一个问题：因为gfw和chnlist等名单都有对应的服务器组解析，在这里是cn组和passwall_proxy组，但是有很多名单外的dns解析没有对应的上游dns服务器解析，这时smartdns就会采用默认组里的成员来解析，如果默认组里成员为空，就无法进行解析了
> 
> **研究了下，luci-smartdns-new-version分流很好用，受passwall的“当使用中国列表外时的默认DNS：选择直连还是远程“这个启发，我国内组CN设置排除默认组，然后默认组只留了一个cloudflare，这样在gfw和chnlist名单外的dns解析采用cloudflare解析，这样就达到了防止DNS泄漏的目的了。毕竟名单外的也不多，速度基本没影响。** ![image](https://user-images.githubusercontent.com/35351787/224488903-13163e0e-c274-4f88-aba7-a0b96fa287c2.png)
> 
> **_目前我的设置，感觉很完美了：_**
> 
> _**passwall：**_
> 
> ![image](https://user-images.githubusercontent.com/35351787/224488937-e2e78bd0-abc3-4af9-b350-454203d37626.png)
> 
> ![image](https://user-images.githubusercontent.com/35351787/224489269-c73a02a0-a0b9-4d6e-83b2-31ece2c3b7bc.png)
> 
> **_smartdns设置（只需要配置默认组和第一组）：_**
> 
> ```
> # Add custom settings here.
> 
> # set log level
> # log-level [level], level=fatal, error, warn, notice, info, debug
> log-level info
> 
> # log-size k,m,g
> log-size 512k
> 
> # log-file /var/log/smartdns.log
> # log-num 2
> 
> # List of hosts that supply bogus NX domain results
> # bogus-nxdomain [ip/subnet]
> 
> #speed-check-mode tcp:443,tcp:80,ping
> 
> #bootstrap
> server-https https://223.6.6.6/dns-query -bootstrap-dns 
> 
> #默认组
> server-https https://cloudflare-dns.com/dns-query -group
> server-tls 1dot1dot1dot1.cloudflare-dns.com -group
> 
> #国内组
> server-https https://dns.alidns.com/dns-query -group cn -exclude-default-group
> server-tls dns.alidns.com -group cn -exclude-default-group
> server-https https://doh.pub/dns-query -group cn -exclude-default-group
> server-tls dot.pub -group cn -exclude-default-group
> server-https https://doh.360.cn/dns-query -group cn -exclude-default-group
> server-tls dot.360.cn -group cn -exclude-default-group
> ```

你这种把国内组排除默认组，将1.0.0.1设为默认组成员的方式其实passwall的分流设置里就可以实现，在luici的默认设置里选择vps节点而不是直连就达到了名单外的dns走代理的效果

**Comment by jxph1123** [comment]
> 你这种把国内组排除默认组，将1.0.0.1设为默认组成员的方式其实passwall的分流设置里就可以实现，在luici的默认设置里选择vps节点而不是直连就达到了名单外的dns走代理的效果

你说的是哪里设置，passwall没找到哇

**Comment by cncqcyc** [comment]
> > 你这种把国内组排除默认组，将1.0.0.1设为默认组成员的方式其实passwall的分流设置里就可以实现，在luici的默认设置里选择vps节点而不是直连就达到了名单外的dns走代理的效果
> 
> 你说的是哪里设置，passwall没找到哇

分流总节点里设置，自己设置各个分流节点，其中的直连相当于国内访问，proxy就是代理，默认就是除所有自定义设置外的连接方式，可以选直连或代理，选代理相当于你设置的效果，并且更好，然后tcp节点那里选分流总节点就启用了分流设置

**Comment by jxph1123** [comment]
> 分流总节点里设置，自己设置各个分流节点，其中的直连相当于国内访问，proxy就是代理，默认就是除所有自定义设置外的连接方式，可以选直连或代理，选代理相当于你设置的效果，并且更好，然后tcp节点那里选分流总节点就启用了分流设置

好的谢谢，好久空了研究下。

**Comment by jxph1123** [comment]
> 分流总节点里设置，自己设置各个分流节点，其中的直连相当于国内访问，proxy就是代理，默认就是除所有自定义设置外的连接方式，可以选直连或代理，选代理相当于你设置的效果，并且更好，然后tcp节点那里选分流总节点就启用了分流设置

好的谢谢，好久空了研究下。之前默认版本的负载均衡有问题，如果自己设置smartdns第二组，负载均衡掉线不重连。。后面用luci-smartdns-new-version这个版本负载均衡就没问题了。

**Comment by lifei6671** [comment]
> 我想问下，用新版的luci-smartdns-new-version和用老板本的自己配置的第二服务器，达到的效果和结果有没有区别，谢谢~~
> 
> _**新版本：**_
> 
> ![image](https://user-images.githubusercontent.com/35351787/223432378-58e63926-762f-48f3-899d-f0277b35a284.png)
> 
> **_老板本：_**
> 
> ![image](https://user-images.githubusercontent.com/35351787/223432055-da0a3711-bd42-4a1e-8ec1-a2502fda8dc8.png)

你的这个版本是自己编译的吗？

**Comment by jxph1123** [comment]
> 你的这个版本是自己编译的吗？
对，自己编译的

**Comment by jxph1123** [comment]
> 你的这个版本是自己编译的吗？


对，自己编译的

**Comment by jxph1123** [comment]
> 分流总节点里设置，自己设置各个分流节点，其中的直连相当于国内访问，proxy就是代理，默认就是除所有自定义设置外的连接方式，可以选直连或代理，选代理相当于你设置的效果，并且更好，然后tcp节点那里选分流总节点就启用了分流设置


大佬，用过passwall的负载均衡吗，现在情况是节点恢复了，负载均衡没恢复，新版本也不行，碰到过吗，应该是我买的那个服务端节点换IP了，但是域名加密等其他都没变，就是负载均衡不恢复，必须重启passwall才行。是我哪里设置不对吗，困扰我好几天了，passwall反馈了，作者没回应。
[https://github.com/xiaorouji/openwrt-passwall/issues/2367](url)

**Comment by jxph1123** [comment]
> 分流总节点里设置，自己设置各个分流节点，其中的直连相当于国内访问，proxy就是代理，默认就是除所有自定义设置外的连接方式，可以选直连或代理，选代理相当于你设置的效果，并且更好，然后tcp节点那里选分流总节点就启用了分流设置


大佬，用过passwall的负载均衡吗，现在情况是节点恢复了，负载均衡没恢复，新版本也不行，碰到过吗，应该是我买的那个服务端节点换IP了，但是域名加密等其他都没变，就是负载均衡不恢复，必须重启passwall才行。是我哪里设置不对吗，困扰我好几天了，passwall反馈了，作者没回应。
https://github.com/xiaorouji/openwrt-passwall/issues/2367

**Comment by threerog** [comment]
所以有大佬总结出最新版的passwall+smartdns的配置方案了吗
有的话 回复一个联系方式 有偿求教

**Comment by uixsj** [comment]
> 建议用passwall的luci-smartdns-new-version分支，只需在smartdns这边设置好国内分组和国内dns上游服务器，不需要启用第二dns服务器，也不需要设置可信dns服务器，而是由passwall那里代替设置了，设置更加简单了，也不会出错。 smartdns这边设置 ![image](https://user-images.githubusercontent.com/81218740/223385292-17eb320a-a5b1-4531-9216-7c18c13aa0f1.png) passwall的设置 ![image](https://user-images.githubusercontent.com/81218740/223384001-e9bce14a-22fe-4539-8279-18a9d547baaf.png)

大佬，这样设置的情况下怎么套个adg，我现在pw和smartdns跟你一样的设置，adg那边重定向53到adg，但是国外组的不经过adg

**Comment by ceozero** [comment]
> 建议用passwall的luci-smartdns-new-version分支，只需在smartdns这边设置好国内分组和国内dns上游服务器，不需要启用第二dns服务器，也不需要设置可信dns服务器，而是由passwall那里代替设置了，设置更加简单了，也不会出错。 smartdns这边设置 ![image](https://user-images.githubusercontent.com/81218740/223385292-17eb320a-a5b1-4531-9216-7c18c13aa0f1.png) passwall的设置 ![image](https://user-images.githubusercontent.com/81218740/223384001-e9bce14a-22fe-4539-8279-18a9d547baaf.png)

请问现在可以直接把6053改成53替代dnsmasq么？因为之前替换的话，passwall就走不了dnsmasq分流了。

**Comment by sxml** [comment]
新passwall分支 luci-smartdns-dev  没有了passwall_proxy组？
