### ISSUE TITLE
在标准的ubuntu中如何安装

### ISSUE THREAD

**Issue by zxjack** [pymumu/smartdns#126]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. ubuntu 64虚拟机，下载了smartdns.1.2019.03.15-2307.x86_64.tar.gz，如何安装呢？

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
指导这块遗漏了
下载解压后，执行
```
./install -i
```
安装

卸载执行
```
./install -u
```

其他操作和linux管理服务一样。

**Comment by takeru94** [comment]
另外要注意一下，ubuntu18.04里面要把系统解析127.0.0.53关掉
`sudo systemctl disable systemd-resolved`
否则你怎么设置都没用

**Comment by zxjack** [comment]
还要改一下install的权限，要不会报错

**Comment by pymumu** [comment]
指导中已经增加说明。
