### ISSUE TITLE
关于非测速模式下上游服务器的选择逻辑疑问

### ISSUE THREAD

**Issue by Hscpro** [pymumu/smartdns#1260]
当smartdns在第二服务器上设置非测速模式下既 `speed-check-mode none` 假设上游设置两个或多个DNS服务器，当请求时smartdns是如何选择上游服务器的？

**需求应用场景**
故障切换。

**建议的方案**
假设上游设置两个或多个DNS服务器
```
1.1.1.1
8.8.8.8
```
默认转发到1.1.1.1，当1.1.1.1故障时转发到8.8.8.8进行解析。

**Comment by PikuZheng** [comment]
取决于 `response-mode` 配置。请参阅#1028
