### ISSUE TITLE
查询 服务已经启用了，为什么  返回两个呢，广告规则命中的也是返回两行。

### ISSUE THREAD

**Issue by zhaozhejun** [pymumu/smartdns#1261]
**问题现象**  
查询 服务已经启用了，为什么  返回两个呢，广告规则命中的也是返回两行。
root@OPLForN1:~#  nslookup -querytype=ptr smartdns
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
smartdns        name = smartdns

root@OPLForN1:~#  nslookup www.baidu.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 220.181.38.149
Name:   www.a.shifen.com
Address: 220.181.38.150

Non-authoritative answer:

root@OPLForN1:~#  nslookup 001union.com
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:

Non-authoritative answer:

root@OPLForN1:~#

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by zhaozhejun** [comment]
server-name smartdns
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 300
log-size 64K
log-num 1
log-level error
force-qtype-SOA  28 65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind :53
bind-tcp :53
server-https https://223.5.5.5/dns-query  
domain-set -name domain-forwarding-list -file /etc/smartdns/domain-forwarding.list
domain-rules /domain-set:domain-forwarding-list/ 
domain-set -name domain-block-list -file /etc/smartdns/domain-block.list
domain-rules /domain-set:domain-block-list/ --address #
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

[smartdns.log](https://github.com/pymumu/smartdns/files/10552934/smartdns.log)

**Comment by PikuZheng** [comment]
>查询 服务已经启用了，为什么 返回两个呢，广告规则命中的也是返回两行。

看不懂你的问题是什么。如果要限制返回的ip数量，请使用`max-reply-ip-num`

> domain-rules /domain-set:domain-block-list/ --address #

这行写法有误，请参阅[配置文件说明](https://github.com/pymumu/smartdns#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E)
