### ISSUE TITLE
ipv4 53端口重定向失败怎么解决？

### ISSUE THREAD

**Issue by Mokenfly** [pymumu/smartdns#1263]
设置重定向53端口到smartdns一直显示失败，关闭防火墙也没用。

**Comment by pymumu** [comment]
按照issue模板补充相关的信息。

**Comment by TeleOcean** [comment]
在openwrt已经关闭Trobo ACC的DNS缓存的情况下，设置如图的重定向选项，无论是选择这两个里面的任何一个，都会设置失败。
![Uploading IMG_20230205_132955.jpg…]()
