### ISSUE TITLE
性能测试问题

### ISSUE THREAD

**Issue by xiaotudoubaba** [pymumu/smartdns#1264]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。
1. 1台2H4G centos 7.6服务器,1台压力测试服务器(安装了queryperf)
2. 部署了smartdns.1.2020.09.08-2235.x86-linux-all.tar.gz
3. 配置文件
```
server-name smartdns1
bind [::]:53
cache-size 0
log-level debug
log-size 100M
#  配置上游解析DNS
server 61.132.163.68  -group china
server 202.96.128.86 -group china
server 202.96.134.133 -group china
server 202.101.224.69 -group china
server 222.172.200.68 -group china
server 202.106.0.20 -group china
server 210.22.70.3 -group china
# 国内DNS
server 223.5.5.5 -group alibaba -exclude-default-group
server 223.6.6.6 -group ailbaba  -exclude-default-group
server 119.29.29.29  -group tencent  -exclude-default-group
server 180.76.76.76  -group baidu  -exclude-default-group
# 国外DNS
server 1.1.1.1 -blacklist-ip -group foreign -exclude-default-group
server 80.80.80.80 -blacklist-ip -group foreign -exclude-default-group
server 8.8.8.8 -blacklist-ip -group foreign -exclude-default-group
# 指定域名IP地址
#address /www.baidu.com/14.215.177.39
audit-enable yes
```
4. 在测试机生成测试文件(只测试www.google.com, 复制800W条)
5. 在测试机执行压测,
```
queryperf -s xxx.xxx.xxx.xxx -d querytest_600W.txt -T 50000
```

压测结果
```
queryperf -s xxx.xxx.xxx.xxx -d querytest_400W.txt -T 50000

DNS Query Performance Testing Tool
Version: $Id: queryperf.c,v 1.12 2007/09/05 07:36:04 marka Exp $

[Status] Processing input data
[Status] Sending queries (beginning with 103.65.41.79)
[Status] Testing complete

Statistics:

  Parse input file:     once
  Ended due to:         reaching end of file

  Queries sent:         8000000 queries
  Queries completed:    7765898 queries
  Queries lost:         234102 queries
  Queries delayed(?):   0 queries

  RTT max:              0.763319 sec
  RTT min:              0.012480 sec
  RTT average:          0.061284 sec
  RTT std deviation:    0.067548 sec
  RTT out of range:     0 queries

  Percentage completed:  97.07%
  Percentage lost:        2.93%

  Started at:           Mon Feb  6 11:36:22 2023
  Finished at:          Mon Feb  6 11:46:08 2023
  Ran for:              585.311346 seconds

  Queries per second:   13267.977894 qps
  Total QPS/target:     13668.337030/50000 qps
```
压力测试`13267.977894`qps, 之前说大压力情况下可以达到5w,
通过nmon测试,cpu,内存,网络均未达到瓶颈,请问压力测试方面,还需要做什么调整吗.

**Comment by PikuZheng** [comment]
> 4\. 只测试www.google.com, 复制800W条

假设google走foreign组，那么每次请求会同时向 1.1.1.1  80.80.80.80  8.8.8.8 发送请求，按照默认配置，应答后对每个测速，再返回给客户端。
所以可能速度瓶颈在于向上游请求的网速。

单说smartdns服务压力的话，应考虑有缓存的情况。

**Comment by xiaotudoubaba** [comment]
@PikuZheng 
对上游请求的网速有可能影响, 请问如何可以减小上游的瓶颈呢.
看之前作者说明能达到5W, 想了解下怎么测试.

**Comment by pymumu** [comment]
之前测试方法是用一台机器跑bind9，缓存数据，用另外一台跑smartdns测试。

你的配置使用了公网DNS，瓶颈在访问公网DNS上了。

你可以跑起来看看smartdns的CPU占用率情况。

**Comment by xiaotudoubaba** [comment]
> 之前测试方法是用一台机器跑bind9，缓存数据，用另外一台跑smartdns测试。
> 
> 你的配置使用了公网DNS，瓶颈在访问公网DNS上了。
> 
> 你可以跑起来看看smartdns的CPU占用率情况。

您好,感谢您回复, 是说用bind9作为smartdns的上游服务器吗?  bind9 开启缓存dns, 这样就不存在访问公网DNS的瓶颈是吗?

**Comment by pymumu** [comment]
是，主要原因还有时延

**Comment by pymumu** [comment]
今天测试了一下，单核2.4G CPU。目前能压测到41000左右。

多核心对性能提升不大，看代码是server处理请求只能单核处理。这里改了下多线程并发后，性能成倍提升了，但dnsperf返回了queryid不匹配的错误。猜测可能是并发量太大queryid反转重复了。

个人家庭使用这些性能应该足够了。这种性能支持1000台左右的服务器查询应该是没有问题的。
如果要支持更多，就要用多线程模式。

多线程模式的代码，刚刚提交到multi-thread-server，有兴趣可以验证看看。
但这个多线程模式的代码没有验证，可能有严重BUG。

**Comment by xiaotudoubaba** [comment]
我测试单机情况, 上游是公网的dns,  使用dnsperf来做测试,  Queries per second:   23382.504156 qps
可能是是公网dns原因,  我觉得连接公网dns感觉会相对真实一些, 

请教下作者, smartdns能否支持集群部署? 比如加上nginx负载均衡,  
我测试了nginx做负载均衡测试, 搭建2台smartdns, nginx在前端做负载,感觉性能还变低了.

**Comment by PikuZheng** [comment]
> 我测试单机情况, 上游是公网的dns, 使用dnsperf来做测试, Queries per second: 23382.504156 qps 可能是是公网dns原因, 我觉得连接公网dns感觉会相对真实一些,
> 
> 请教下作者, smartdns能否支持集群部署? 比如加上nginx负载均衡, 我测试了nginx做负载均衡测试, 搭建2台smartdns, nginx在前端做负载,感觉性能还变低了.

nginx用的stream吗？正常情况下nginx要连接完成后才能转发，耽误不少时间。
我家有三个独立的smartdns，之前用keepalived做过主备，现在是有mikrotik负责主备转发。早期试过随机转发到其中一个，但分散流量似乎没有什么益处，反倒导致缓存命中降低了。

**Comment by pymumu** [comment]
> 我测试单机情况, 上游是公网的dns, 使用dnsperf来做测试, Queries per second: 23382.504156 qps 可能是是公网dns原因, 我觉得连接公网dns感觉会相对真实一些,
> 
> 请教下作者, smartdns能否支持集群部署? 比如加上nginx负载均衡, 我测试了nginx做负载均衡测试, 搭建2台smartdns, nginx在前端做负载,感觉性能还变低了.

可以把log关掉，性能会提高一些。
smartdns本身不具备分布式能力，多个smartdns运行的话是没有问题的。

另外，nginx转发的话，应该是tcp，tcp需要建立链接这些都会耗时，还有如PikuZheng所说，缓存命中率会下降。

**Comment by mokeyish** [comment]
@xiaotudoubaba 也帮忙测下我写的这个 https://github.com/mokeyish/smartdns-rs

现在还是以功能覆盖实现为主，没去想那些，想多了反而没进展了。线程数量是在这写死的 4 个
https://github.com/mokeyish/smartdns-rs/blob/c8845a3abde88aafcb98f209dc53153dd9166b7d/src/main.rs#L188
不过也想看看，到底性能如何。

**Comment by mokeyish** [comment]
Rust 是安全第一，其次才是性能，不知道跟 c 版比差多少。

**Comment by maojianyou** [comment]
> 今天测试了一下，单核2.1G CPU。目前能压测到41000左右。性能相比之前下降，可能是smartdns增加了多个业务逻辑导致。
> 
> 多核心对性能提升不大，看代码是server处理请求只能单核处理。这里改了下多线程并发后，性能成倍提升了，但dnsperf返回了queryid不匹配的错误。猜测可能是并发量太大queryid反转重复了。
> 
> 个人家庭使用这些性能应该足够了。这种性能支持1000台左右的服务器查询应该是没有问题的。 如果要支持更多，就要用多线程模式。
> 
> 多线程模式的代码，刚刚提交到multi-thread-server分支，有兴趣可以验证看看。 但这个多线程模式的代码没有验证，可能有严重BUG。

目前最新版本 smartdns.1.2024.06.12-2222.x86_64-linux-all.tar.gz ,并发测试，最大能到多少？ 不考虑硬件，CPU是多核多线程，内存也比较大，比如32G或者64G，固态硬盘，这个最大并发有测试过能到多少不
