### ISSUE TITLE
如何配置仅第二服务器force-AAAA-SOA，即关闭ipv6解析

### ISSUE THREAD

**Issue by Sn0r1axi** [pymumu/smartdns#1266]
bind-tcp  :7324 -group oversea -no-speed-check force-AAAA-SOA
bind  :7324 -group oversea -no-speed-check force-AAAA-SOA

如此加到bind参数后测试无效

**Comment by devioa** [comment]
你这用法就不对，正确配置应该是这样的：
```
bind :1 -no-rule-soa
bind :2 -group gfwlist -no-speed-check
force-AAAA-SOA yes
```
默认强制AAAA返回SOA，但是第一服务器不受SOA规则限制。
这样就能保留第一服务器的AAAA解析，但是第二服务器的AAAA请求返回SOA

**Comment by Sn0r1axi** [comment]
> 你这用法就不对，正确配置应该是这样的：
> 
> ```
> bind :1 -no-rule-soa
> bind :2 -group gfwlist -no-speed-check
> force-AAAA-SOA yes
> ```
> 
> 默认强制AAAA返回SOA，但是第一服务器不受SOA规则限制。 这样就能保留第一服务器的AAAA解析，但是第二服务器的AAAA请求返回SOA

那第一dns服务器的tcp绑定后面需要加上-no-rule-soa吗？

**Comment by devioa** [comment]
> > 你这用法就不对，正确配置应该是这样的：
> > ```
> > bind :1 -no-rule-soa
> > bind :2 -group gfwlist -no-speed-check
> > force-AAAA-SOA yes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 默认强制AAAA返回SOA，但是第一服务器不受SOA规则限制。 这样就能保留第一服务器的AAAA解析，但是第二服务器的AAAA请求返回SOA
> 
> 那第一dns服务器的tcp绑定后面需要加上-no-rule-soa吗？

你想哪个`bind`不受SOA规则限制就加在哪个`bind`后面

**Comment by Sn0r1axi** [comment]
> > > 你这用法就不对，正确配置应该是这样的：
> > > ```
> > > bind :1 -no-rule-soa
> > > bind :2 -group gfwlist -no-speed-check
> > > force-AAAA-SOA yes
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 默认强制AAAA返回SOA，但是第一服务器不受SOA规则限制。 这样就能保留第一服务器的AAAA解析，但是第二服务器的AAAA请求返回SOA
> > 
> > 
> > 那第一dns服务器的tcp绑定后面需要加上-no-rule-soa吗？
> 
> 你想哪个`bind`不受SOA规则限制就加在哪个`bind`后面

已成功配置 感谢！
