### ISSUE TITLE
屏蔽ipv6

### ISSUE THREAD

**Issue by Mikaelpeng** [pymumu/smartdns#1267]
请问我想要屏蔽 某一组服务的ipv6 我该怎么写.  🙏

**Comment by pymumu** [comment]
```
address /xxx.com/#6
```

也可以配合
domain-set指定域名组
```
domain-set -name block -file /path/to/domain.list
address /domain-set:block/ -address #6
```

**Comment by sxml** [comment]
不支持域名通配符 ？

**Comment by PikuZheng** [comment]
> 不支持域名通配符 ？

不支持#792 https://github.com/pymumu/smartdns/issues/580#issuecomment-678563074

**Comment by Mikaelpeng** [comment]
> ```
> address /a.com/#6
> address /b.com/#6
> ```
> 
> 也可以配合 domain-set指定域名组
> 
> ```
> domain-set -name block -file /path/to/domain.list
> address /domain-set:block/ -address #6
> ```
> 
> /path/to/domain.list中内容：
> 
> ```
> a.com
> b.com
> ```
> 
> openwrt的话，安装luci界面，直接界面中配置屏蔽ipv6
🙏 感谢大佬
