### ISSUE TITLE
smartdns的本地服务端口号没设置为53，也会自动配置为主dns

### ISSUE THREAD

**Issue by YuChenDayCode** [pymumu/smartdns#1269]
**需求应用场景**
    op的smartdns+adguardhome使用时，adg为主dns(端口5553)，smartdns为adg的dns服务器。smartdns的端口设置为6054，重启防火墙后，DHCP/DNS的`DNS转发`会被设置为6054。
   也不确定是smartdns问题还是op问题， 麻烦大佬

**设备信息**
1. 设备信息（CPU，厂家）  
   - N1 
2. 固件信息
   - Openwrt 6.1.2-flippy-80+
   - luci-app-smartdns  1.2022.40-1

**Comment by pymumu** [comment]
高级设置里面去勾选`自动设置dnsmasq`选项。
