### ISSUE TITLE
采用geosite.dat数据进行dns分组

### ISSUE THREAD

**Issue by weiping** [pymumu/smartdns#1274]
**需求应用场景**
采用与v2ray、xray、trojan-go兼容的域名数据geosite.dat进行dns server分组，可以这样定义分组：
server x.x.x.x -geosite:cn -geosite:google-cn
server x.x.x.x -geosite:geolocation-!cn
server x.x.x.x -geosite:gfw
等等

**建议的方案**
可以用v2ray维护的数据，也可以用第三方加强的数据，如：https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by pymumu** [comment]
不会支持特定格式数据。

分流的方法，请看ReadME的FAQ的6节，如果有文本list域名列表文件，可以使用FAQ 13结的域名集合。

如果使用openwrt，可以支持域名列表文件自动下载。

**Comment by jxph1123** [comment]
smartdns是DNS辅助工具，你要把他搞成翻墙辅助工具吗，虽然他有这个能力

**Comment by cncqcyc** [comment]
可以使用passwall，最新的luci-smartdns-new-versionl分支可按照smartdns格式生成分流文件作为附加文件加载
