### ISSUE TITLE
luci勾选排除默认组配置文件生成exclude-default-group和手填额外参数-exclude-default-group少了“-”

### ISSUE THREAD

**Issue by 58285474** [pymumu/smartdns#1275]
**问题现象** 
luci勾选排除默认组配置文件生成exclude-default-group和手填额外参数-exclude-default-group少了“-” 少了这个“-”号请问还生效吗

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本40.24

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
重复#1227
如果填在“额外的服务器参数”里，应该有“-”，即`-exclude-default-group`

**Comment by 58285474** [comment]
> 重复#1227
> 
> 如果填在“额外的服务器参数”里，应该有“-”，即`-exclude-default-group`

我明白您说的，但是我额外参数没填写，只勾选排除默认，确实配置文件里没有“-”所以才提问![image](https://user-images.githubusercontent.com/28937186/220239872-ce7de663-3588-4dc8-b891-81b793a098ff.png)

**Comment by pymumu** [comment]
这个配置是openwrt的管理配置，不是给smartdns进程用的。实际配置可以看如下内容：

```
cat /var/etc/smartdns/smartdns.conf
```

**Comment by yyysuo** [comment]
实际测试了一下，无论是luci界面勾选从默认组中排除，还是加-exclude-default-group参数，生成的实际生效的/var/etc/smartdns/smartdns.conf中，格式都是带横杠的  server-tls 8.8.8.8  -exclude-default-group

**Comment by 58285474** [comment]
> 实际测试了一下，无论是luci界面勾选从默认组中排除，还是加-exclude-default-group参数，生成的实际生效的/var/etc/smartdns/smartdns.conf中，格式都是带横杠的  server-tls 8.8.8.8  -exclude-default-group 

抱歉，这个确实是我的盲区了，我参考了etc/config/smartdns的配置，正确的应该如您所说实际生效的/var/etc/smartdns/smartdns.conf中
