### ISSUE TITLE
开启cache后domain-rulse -rr-ttl-min异常

### ISSUE THREAD

**Issue by w22gb8** [pymumu/smartdns#1276]
Release 40和最新commits，domain-rulse下-rr-ttl-min或-rr-ttl设置参数无效，返回ttl值一直为2和1，关闭cache后正常

更新：不是domain-rulse独有的问题，将response-mode设置为fastest-response并开启cache时所有域名第一次查询都返回ttl 2。

了解了下，这貌似是默认功能，关闭speed-check-mode后，response-mode：fastest-ip和first-ping相当于关闭response-mode，但是fastest-response第一次查询还是将ttl设置为2。

建议response-mode添加参数none可以关闭此功能，对不用测速的人来说这功能没啥用，反而让人迷惑。

**Comment by PikuZheng** [comment]
这个ttl是过期缓存来的吧，ttl缓存没过期的域名也会这样吗？要不试试在domain-rule中加上-no-serve-expired

**Comment by w22gb8** [comment]
> 这个ttl是过期缓存来的吧，ttl缓存没过期的域名也会这样吗？要不试试在domain-rule中加上-no-serve-expired

有添加此参数，有无一样。

**Comment by pymumu** [comment]
开启测速的情况下，首次查询，返回ttl为2是正常的。
返回ttl=2目的是告诉客户端2s后再次查询，等再次查询后，缓存中会是速度最快的IP，TTL应该是上游的值。并且IP数量会有多个，更好支持下载，视频软件。

如果要按照上游的结果返回，关闭测速即可。
```
speed-check-mode none
``

如果是第二次查询结果，仍然返回ttl=1，那么提供相关的log。
