### ISSUE TITLE
cname目标域名domain-rules无效

### ISSUE THREAD

**Issue by w22gb8** [pymumu/smartdns#1277]
cname目标域名不走domain-rules定义的服务器，如下面配置文件dst.com解析不走dstgroup，当源域名和目标域名为二级域名且主域名相同时走dstgroup。
```
domain-rules /dst.com/ -nameserver dstgroup
cname /src.com/dst.com
```

**Comment by pymumu** [comment]
请按照issue模板提交issue。补充相关的log。
