### ISSUE TITLE
请教一下-exclude-default-group 的用法，一直搞不太懂

### ISSUE THREAD

**Issue by gforce1206** [pymumu/smartdns#1278]
鄙人是某站的小up，想做期smartdns+adg+ssr的视频，所以想弄清楚一些细节，请大佬指导一下，-exclude-default-group 现在R40-1已经有“从默认服务器组排除”的选项，我分了两个服务组，一个domestic，一个foreign，并在“下载文件”处订阅了foreign和domestic的域名文件，foreign设置在第二DNS服务器，绑定5335端口，所属上游服务器已经勾选“从默认服务器组排除”，domestic没有自定义绑定端口，我看网上有些设置需要自定义给国内组绑定端口，转交给adg做解析，然后还需要“从默认服务器组排除”，按我理解foreign服务组排除出默认服务器，是专门给ssr请求域名解析用的，国内的域名请求是到6053，然后再根据域名列表，交给domestic解析，最后给到adg，不知道这样理解对不对，还有个小问题，现在R40-1第二服务组可以不勾选"跳过cache"了吗？我看污染问题好像修复了，感谢感谢！
![smartdns2](https://user-images.githubusercontent.com/72802453/220496253-f36445a6-2ff8-4c02-a551-23e0a2ec04b4.PNG)
![smartdns1](https://user-images.githubusercontent.com/72802453/220496266-4e7e3546-933a-4578-af7a-86bc8d60158d.PNG)
![smartdns4](https://user-images.githubusercontent.com/72802453/220496272-ae913b19-ad58-40a9-9b73-bad5cec6c1e5.PNG)
![smartdns3](https://user-images.githubusercontent.com/72802453/220496279-df0e590b-1936-44e0-a3bf-27722304f082.PNG)

**Comment by pymumu** [comment]
最新版本luci简化了所有配置，大致思路是对于有特殊需求的域名走分流组，其他非特殊需求的走测速。
对于分流组，配置配置采用的是：
  1. 使用特定的DNS查询组。
     - -exclude-default-group告诉smartdns，非特殊域名查询时，不要使用这个DNS服务器。   如果没设置这个参数，则非特殊域名查询也会使用此DNS服务器。
     - 这里，也可以配置proxy，让DNS查询通过代理出去，这样分流域名的亲和性会更好。 
  2. 对应域名查询时，关闭测速，关闭IPV6
     - 走分流的请求，测速没有意义。所以要关闭。
     - 关闭IPV6是因为目前大部分代理软件都不支持IPV6
  3. 查询到的结果，放入ipset/或nftset中提供给代理软件使用。

其他的，可以配置自动下载AD屏蔽文件，在分流的其他页面设置广告屏蔽。

**Comment by gforce1206** [comment]
> 最新版本luci简化了所有配置，如无特殊需求，无需使用第二DNS服务器。 分流大致思路是：对于有特殊需求的域名走分流组；其他非特殊需求的走测速。 对于分流组，配置方法是：
> 
> 1. 使用特定的DNS查询组。在DNS上游配置TAB
>    
>    * 使用TLS，HTTPS，或通过代理查询。
>    * -exclude-default-group告诉smartdns，非特殊域名查询时，不要使用这个DNS服务器。   如果没设置这个参数，则非特殊域名查询也会使用此DNS服务器。
>    * 这里，也可以配置proxy，让DNS查询通过代理出去，这样分流域名的亲和性会更好。
> 2. 对应特殊需求域名查询时，关闭测速，关闭IPV6：在DNS分流配置TAB。
>    
>    * 走分流的请求，测速没有意义。所以要关闭。
>    * 关闭IPV6是因为目前大部分代理软件都不支持IPV6
>    * 特殊需求的域名，可在界面配置自动下载更新。
> 3. 查询到的结果，放入ipset/或nftset中提供给代理软件使用：DNS分流配置TAB可以增加ipset名称。
>    
>    * 具体iptable如何配置，可以参考ReadMe FAQ的14节
> 4. 另外，还有测速失败自动加入ipset的功能，配置参数是ipset-no-speed。这个后面会加入luci界面。
> 
> 次方法采用的是白名单分流，只有需求域名的才走分流。
> 
> 其他的，可以配置自动下载AD屏蔽文件，在分流的其他页面设置广告屏蔽。 还有，推荐使用javascript版本的luci（非compat版本），那个会更完善。
> 
> 另外也可以使用这个看看：[xiaorouji/openwrt-passwall#2261](https://github.com/xiaorouji/openwrt-passwall/issues/2261)

感谢开发者大佬的回复，只是我用的域名列表分流，不是ip规则分流，还是有点不太理解，得消化一下，见谅见谅
