### ISSUE TITLE
wiki添加luci界面配置说明，统一后台生成的配置文件格式

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1279]
仅建议，供参考。
1：在wiki中添加dot doh在luci界面中的配置格式要求。
2：luci排除默认组按钮与额外参数-exclude-default-group统一成一个，填入-exclude-default-group时，luci自动勾选。
3：无论luci中上游服务器是否指定端口，后面生成的配置文件均添加端口号，目前默认时配置文件无端口号。
4：在wiki中添加可以添加的额外参数及功能说明。

**Comment by yyysuo** [comment]
其实也可以在wiki里面强调一下，如果上游服务器未排除出默认组，进入smartdns任何分组的请求，都会发送到默认组中未排除的上游dns服务器。

**Comment by pymumu** [comment]
ReadMe中大部分都有，FAQ部分。

wiki暂时没精力弄。

**Comment by yyysuo** [comment]
> ReadMe中大部分都有，FAQ部分。
> 
> `排除默认组按钮`与`额外参数`两个互斥的。有些参数界面上没开放的，可以在`额外参数`，`额外参数`可以配置多个参数。 `排除默认组按钮`只是用的比较多，才放到luci选项的。
> 
> wiki暂时没精力弄。

感谢大佬回复，仅建议。
