### ISSUE TITLE
增加优先级配置

### ISSUE THREAD

**Issue by ziyuedi** [pymumu/smartdns#128]
**需求应用场景**
对于相同配置可以更好的管理。

**建议的方案**
1、忽略配置优先，例如
`nameserver /example.com/-`
优先于
`nameserver /example.com/server`
和
`nameserver /example.com/#`
2、增加配置文件优先级设置，在conf-file中指定或在配置文件中指定，配置文件中指定优先。
配置相同时优先级更高的配置文件中的配置生效，优先级相同时，相同域名忽略配置优先；如果还不能确定，则后读取的优先。

**Comment by pymumu** [comment]
所有域名相关的配置（address，nameserver，nxdomain等）都是子域名优先，和文件、顺序无关。

conf-file只是包含文件，没有优先级概念

**Comment by ziyuedi** [comment]
> 和文件、顺序无关。

但是在其他issue中提到过相同配置（相同域名）后读取优先，
例如当`nameserver /example.com/#`
在 `nameserver /example.com/server`之前时
`nameserver /example.com/server`生效
> conf-file 只是包含文件，没有优先级概念

所以希望增加优先级配置项

**Comment by pymumu** [comment]
重复的都是按后出现的为准的，LUCI的很多配置都依赖这个。

所以，对于重复的记录，建议手工排查。
