### ISSUE TITLE
smartdns的ipset功能如何与ssr plus的ipset相互配合？

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1280]
ssrp在/etc/ssrplus目录下有gfw_list.conf及gfw_base.conf配置文件

其中gfw_list.conf内容大致如下：
server=/samebags.com/127.0.0.1#5335
ipset=/samebags.com/gfwlist

gfw_base.conf内容大致如下：
ipset=/91smartyun.pt/gfwlist

问题：是不是在smartdns luci的界面-域名分流设置-IPset名称中填入gfwlist，服务器组选自己定义的国外组，就可以和ssrp配合了呢？

![image](https://user-images.githubusercontent.com/10081071/220504542-c32e66ef-d0cd-4296-8b3d-ec83ef7251b3.png)

**Comment by yyysuo** [comment]
我以为上面选了服务器组，那么通过这个服务器组查询的所有dns请求，都会自动写入指定的ipset，我的理解是否正确呢？

**Comment by pymumu** [comment]
不支持你说的这种方式。

这里你直接将域名列表加载进去，然后配置ipset名称就可以了。

参考：https://github.com/pymumu/smartdns/issues/1278#issuecomment-1439311111

**Comment by yyysuo** [comment]
> 不支持你说的这种方式。
> 
> 这里你直接将域名列表加载进去，然后配置ipset名称就可以了。
> 
> 参考：[#1278 (comment)](https://github.com/pymumu/smartdns/issues/1278#issuecomment-1439311111)

感谢大佬回复，学习了一下，按我的理解，在smartdns里面设置的ipset名称，应该就是科学软件使用的ipset名称，smartdns本身是不会去创建ipset的，只会添加条目。假如填入的ipset名称不存在，smartdns会创建么？

另外，对于已经通过其它插件分流的情况，能否实现一下我提到使用方式的，希望进入foreign这个端口的dns请求，无论是否有域名列表，都加入指定的ipset，可以在服务器组下面加一个选定的组全部加入ipset的选项。
