### ISSUE TITLE
域名分流配置 luci 的相关问题

### ISSUE THREAD

**Issue by lintaozi** [pymumu/smartdns#1281]
- 不支持多组分流 luci 只能配置单组的分流策略 组间互斥 无法同时配置
- 上传文件不支持清除 只支持替换（包括下载文件处的上传）
- 上传文件不支持通过文件路径引用下载文件（包括域名分流和域名屏蔽 尤其是域名分流  luci 文字备注可以引用下载文件 但无法配置 只能上传文件）

**Comment by pymumu** [comment]
1. luci域名规则可以设置多组规则。使用javascript版本的luci（非compat版本）
    没理理解你说的规则互斥是什么意思？
2.  删除文件是luci上传控件的能力，升级固件。建议是使用openwrt官方22.03.
3. 高级设置中的`包含配置文件`可以指定文件路径。但格式必须是smartdns的配置文件格式。

**Comment by lintaozi** [comment]
> 1. luci域名规则可以设置多组规则。使用javascript版本的luci（非compat版本）
>    没理理解你说的规则互斥是什么意思？
> 2. 删除文件是luci上传控件的能力，升级固件。建议是使用openwrt官方22.03.
> 3. 高级设置中的`包含配置文件`可以指定文件路径。但格式必须是smartdns的配置文件格式。

@pymumu 
1. 看起来是我使用 compat 版的原因
2. 看起来是我的固件版本过低的原因，另外请教下，这部分配置是都写入了 etc/config/smartdns.conf 里了吧，如果直接去对应路径删掉上传文件 然后再配置文件中删除对应的配置 是不是就手动还原
3. 高级设置中的包含配置文件那块儿没问题，但是域名分流和域名屏蔽可以也手动指定文件路径么 就是用下载文件定时更新的那些
4. 另外请教下，下载文件处设定的文件名，是保存的文件名、还是 domain-set 中的 -name

**Comment by cncqcyc** [comment]
借楼请教一个问题：passwall生成的附加配置文件里有一个自定义的服务器组passwall_proxy，smartdns能根据附加配置文件将服务器加入passwall_proxy组：
proxy-server socks5://127.0.0.1:1070 -name passwall-proxy-server
server tls://1.1.1.1 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
server tls://8.8.4.4 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
server tls://9.9.9.9 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
server tls://208.67.222.222 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
log里可以看见成功加入了passwall_proxy组
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 223.5.5.5:853, type: tls
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 1.12.12.12:853, type: tls
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 114.114.114.114:53, type: tcp
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 180.76.76.76:53, type: udp
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 1.2.4.8:53, type: udp
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 1.1.1.1:853, type: tls
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 8.8.4.4:853, type: tls
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 9.9.9.9:853, type: tls
[2023-02-22 20:12:50,306][ INFO][     dns_client.c:1123] add server 208.67.222.222:853, type: tls

[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:556 ] send query to group passwall_proxy
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:3281] send query to server 208.67.222.222
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:2052] tls server 208.67.222.222 connecting.
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:3281] send query to server 9.9.9.9
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:2052] tls server 9.9.9.9 connecting.
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:3281] send query to server 8.8.4.4
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:2052] tls server 8.8.4.4 connecting.
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:3281] send query to server 1.1.1.1
[2023-02-22 20:14:53,122][DEBUG][     dns_client.c:2052] tls server 1.1.1.1 connecting.

现在问题是：luci的分流设置选项里没有passwall_proxy组名字，是程序设计不能加载外部文件的组名还是compat版的luci问题，我编译的是compat版本

**Comment by pymumu** [comment]
应该是直接生成的配置文件，没有修改luci配置，所以luci界面看不到。
你可以发一下/etc/config/smartdns看看。

**Comment by cncqcyc** [comment]
是的，passwall那边直接生成的配置文件作为附加文件，没有修改luci，第二服务器组名称是passwall_proxy，但我没有启用，而且里面没有组成员，在passwall那边选择上游服务器，通过它的配置文件附加进来的。

/etc/config/samrtdns的内容
config smartdns
	option server_name 'smartdns'
	option serve_expired '1'
	option resolve_local_hostnames '1'
	option auto_set_dnsmasq '1'
	option force_aaaa_soa '1'
	option force_https_soa '1'
	option rr_ttl_min '600'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_ipset '0'
	option seconddns_no_rule_soa '0'
	option seconddns_no_cache '0'
	option coredump '0'
	option speed_check_mode 'tcp:443,tcp:80'
	option tcp_server '0'
	option ipv6_server '0'
	option dualstack_ip_selection '0'
	option cache_size '10000'
	option rr_ttl_max '86400'
	option rr_ttl_reply_max '3600'
	option seconddns_port '7913'
	option seconddns_tcp_server '0'
	option seconddns_server_group 'passwall_proxy'
	option seconddns_no_dualstack_selection '1'
	option seconddns_force_aaaa_soa '1'
	option enable_auto_update '1'
	option enabled '1'
	option prefetch_domain '1'
	list conf_files 'anti-ad-for-smartdns.conf'
	list conf_files '/etc/smartdns/conf.d/bogus-nxdomain-smartdns.conf'
	option seconddns_no_speed_check '1'
	option seconddns_no_rule_nameserver '0'
	option port '53'
	option old_port '53'
	option old_enabled '1'
	option old_auto_set_dnsmasq '1'

config domain-rule
	option force_aaaa_soa '1'
	option server_group 'cn'
	option no_speed_check '0'

config server
	option enabled '1'
	option name 'ali'
	option ip '223.5.5.5'
	option port '853'
	option type 'tls'
	option exclude_default_group '0'
	option blacklist_ip '1'
	option no_check_certificate '0'
	option spki_pin 'ZwR21gnCMTzsM6VWtnb/azufgYegWWuhE9reP5tamWU='
	option addition_arg '-check-edns'
	option server_group 'cn'

config server
	option enabled '1'
	option name 'teccent'
	option ip '1.12.12.12'
	option port '853'
	option type 'tls'
	option exclude_default_group '0'
	option blacklist_ip '1'
	option no_check_certificate '0'
	option spki_pin '5TIMjgyMhA0qmPdK+AM9LX6vNI/9EPBydh/ZXdfcYmI='
	option addition_arg '-check-edns'
	option server_group 'cn'

config server
	option enabled '1'
	option name '114'
	option ip '114.114.114.114'
	option type 'tcp'
	option exclude_default_group '0'
	option blacklist_ip '1'
	option server_group 'cn'

config server
	option enabled '1'
	option type 'udp'
	option name 'baidu'
	option ip '180.76.76.76'
	option exclude_default_group '0'
	option blacklist_ip '1'
	option server_group 'cn'
config server
	option enabled '1'
	option type 'udp'
	option name 'cnnic'
	option ip '1.2.4.8'
	option exclude_default_group '0'
	option blacklist_ip '1'
	option server_group 'cn'

config download-file
	option name 'anti-ad-for-smartdns.conf'
	option url 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf'
	option type 'config'
	option desc 'anti-AD for SmartDNS'

passwall的设置

![image](https://user-images.githubusercontent.com/81218740/220649703-618fd96a-5d35-4988-a949-2e6fcd03a83d.png)

passwall生成的附加配置文件

proxy-server socks5://127.0.0.1:1070 -name passwall-proxy-server
server tls://1.1.1.1 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
server tls://8.8.4.4 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
server tls://9.9.9.9 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
server tls://208.67.222.222 -group passwall_proxy -exclude-default-group -proxy passwall-proxy-server
domain-set -name passwall-gfwlist-list -file /tmp/etc/passwall_tmp/smartdns_default_gfwlist.list
domain-rules /domain-set:passwall-gfwlist-list/ -nameserver passwall_proxy -speed-check-mode none -address #6 -ipset #4:gfwlist
domain-set -name passwall-chnlist-list -file /tmp/etc/passwall_tmp/smartdns_default_chnlist.list
domain-rules /domain-set:passwall-chnlist-list/ -nameserver cn -ipset #4:chnroute,#6:chnroute6
