### ISSUE TITLE
1: applet not found

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#1283]
**问题现象**  
日志里频繁出现：
`1: applet not found`

**运行环境**
1. 固件型号  
`Linux OpenWrt 6.1.12 #0 SMP PREEMPT_DYNAMIC Thu Feb 16 01:28:24 2023 x86_64 GNU/Linux`
`docker version 20.10.17`

2. 运营商  
四川电信

3. smartdns来源以及版本
Github 最新源码(#c5ca3ccf43316c3962c602560adbaa193309175f)自行编译
![Snipaste_2023-02-22_19-10-18](https://user-images.githubusercontent.com/38558065/220604079-585f9f52-66b9-4e89-a09c-c6d072721dc9.png)

**Comment by PikuZheng** [comment]
可以看一下完整的日志？默认在 /var/log/smartdns.log

**Comment by devioa** [comment]
> 可以看一下完整的日志？默认在 /var/log/smartdns.log

因为我看日志上下文没有太大关联性所以没有发全，就是随机出现的
这里放3个日志截图可参考：
![1](https://user-images.githubusercontent.com/38558065/220619729-38d60c5f-77aa-46f7-8364-42803e0d065e.png)
![2](https://user-images.githubusercontent.com/38558065/220619733-0e165019-3997-4b31-a40a-ca74b11e231f.png)
![3](https://user-images.githubusercontent.com/38558065/220619738-8586a95b-3cf8-40aa-81a9-001c76fc23b6.png)

**Comment by devioa** [comment]
> 首先您这个potainer版本过旧。其次这个是容器控制台日志，所有进程都往这写日志，看格式也不像是smartdns产生的，考虑容器内还运行了别的进程，或是计划任务。
> 
> 建议配置将smartdns日志写入文件，然后观察文件。

最新Portainer Business Edition 2.17.1，拉的就是本库的dockerfile编译出来的，不可能有其它进程和计划任务
