### ISSUE TITLE
log打包问题

### ISSUE THREAD

**Issue by cncqcyc** [pymumu/smartdns#1284]
**问题现象**  
简要描述问题出现的现象
我设置的log文件大小4096k，文件个数为2个，现在发现log打包出现问题，log文件大小到达上限后无法打包
**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本
最新源码编译
4. 涉及的配置(注意去除个人相关信息)
# Add custom settings here.
# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
# log-level error
log-level debug
# log-size k,m,g
# log-size 128k
log-size 4096k
# log-file /var/log/smartdns.log
# log-num 2
log-file /var/log/smartdns/smartdns.log
log-num 1

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
![image](https://user-images.githubusercontent.com/81218740/220637205-38a68e9f-45e7-4a1e-b5d9-cbfa529080a0.png)

**Comment by pymumu** [comment]
最新代码已经修正。
