### ISSUE TITLE
address: only target subdomains but not the base domain

### ISSUE THREAD

**Issue by TCB13** [pymumu/smartdns#1285]
Hello,

Is there a way to ignore and/or reply with SOA only for subdomains? It would be good to be able to set a rule like the following that would only target subdomains of a given domain and not the domain itself.  

````
address /*.example.com/#
````

This is useful when a LAN domain is a FQDN and we don't want to leak queries to the outside.

Example:
````
test.example.com > SOA
xyz.example.com > SOA
example.com > query to DNS servers

Thank you.

**Comment by TCB13** [comment]
> `address /example.com/#` is valid for `example.com` and `*.example.com`

That's the problem. I need a rule that is valid for `*.example.com` but not valid for `example.com`...

**Comment by PikuZheng** [comment]
yes.
maybe /.example.com/ should match ^.+\.example\.com$ and /example.com/ should match ^example\.com$  ?

**Comment by TCB13** [comment]
> yes. maybe /.example.com/ should match ^.+.example.com$ and /example.com/ should match ^example.com$ ?

That's what I'm looking for. :)

**Comment by pymumu** [comment]
1. main and sub domain
```  
example.com
```

2. only main domain: 
```
|example.com
```

3. only sub domain: 
```
.example.com
```

4. No parent rules.
```
-example.com
```

**Comment by pymumu** [comment]
@TCB13 
Your current needs can be configured as follows.

> Example:
> 
> ```
> test.example.com > SOA
> xyz.example.com > SOA
> example.com > query to DNS servers
> 
> Thank you.
> ```

configuration:

```
address /test.example.com/#
address /xyz.example.com/#
```

**Comment by TCB13** [comment]
> @TCB13 Your current needs can be configured as follows.
> 
> > Example:
> > ```
> > test.example.com > SOA
> > xyz.example.com > SOA
> > example.com > query to DNS servers
> > 
> > Thank you.
> > ```
> 
> configuration:
> 
> ```
> address /test.example.com/#
> address /xyz.example.com/#
> ```

@pymumu That only works for specific sub-domains, I was looking for wildcard.

Thank you.

**Comment by pymumu** [comment]
> > @TCB13 Your current needs can be configured as follows.
> > > Example:
> > > ```
> > > test.example.com > SOA
> > > xyz.example.com > SOA
> > > example.com > query to DNS servers
> > > 
> > > Thank you.
> > > ```
> > 
> > 
> > configuration:
> > ```
> > address /test.example.com/#
> > address /xyz.example.com/#
> > ```
> 
> @pymumu That only works for specific sub-domains, I was looking for wildcard.
> 
> Thank you.

It's not that easy. This rule is a matrix. Currently supported options are
address, nameserver, ipset, speed-check...About 12, if combined with the above 4 domain name rules,
Then the total number of rules that need to be create in memory is 12*4=48.

This requirement requires a detailed design.

**Comment by pymumu** [comment]
However, in most cases, maybe we just want to block specific domain name, is it enough to just implement the domain rules for the `address` option?

**Comment by TCB13** [comment]
> However, in most cases, maybe we just want to block specific domain name, is it enough to just implement the domain rules for the `address` option?
> 
> example
> 
> ```
> address /example.com/# -exclude-main-domain
> ```

That might work, but it depends on how it is implemented. Consider this:

```
address /example.com/# -exclude-main-domain  > will exclude 'example.com' and reply SOA to 'xyz.example.com'
address /router.example.com/# -exclude-main-domain  > what will happen here? Ideally exclude 'router.example.com' and reply SOA to 'xyz.router.example.com'
````
`-exclude-main-domain` should exclude what is inside `/ /`. So with works with domains and subdomains was well. 

What you suggested in https://github.com/pymumu/smartdns/issues/1285#issuecomment-1443625805 is way more flexible tho.

Thank you.

**Comment by PikuZheng** [comment]
> 1. main and sub domain name
> ```  
> example.com
> ```
> 
> 2. only main domain name 
> ```
> |example.com
> ```
> 
> 3. only sub domain name
> ```
> .example.com
> ```
> 
> 4. No parent rules.
> ```
> -example.com
> ```

这种可以用于domain-list吗？之前试过.开头的在domain-list会不起作用

**Comment by pymumu** [comment]
> > 1. main and sub domain name
> > 
> > ```
> > example.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. only main domain name
> > 
> > ```
> > |example.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. only sub domain name
> > 
> > ```
> > .example.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. No parent rules.
> > 
> > ```
> > -example.com
> > ```
> 
> 这种可以用于domain-list吗？之前试过.开头的在domain-list会不起作用

还不支持这种写法，只是设计。

**Comment by PikuZheng** [comment]
> 还不支持这种写法，只是设计。

目前看只需要区分主域名和子域名，比如.开头的匹配子域名，不带.的匹配主域名。同时匹配主域名和子域名可以写两行，实际应用上这种数量可能不多

**Comment by pymumu** [comment]
已经支持，具体用法参考帮助

**Comment by chummumm** [comment]
// 通配
*-a.example.com 
// 仅匹配子域名
*.example.com
// 仅匹配主域名
-.example.com
这种写法在openwrt的luci-app-smartdns里面似乎不生效

**Comment by PikuZheng** [comment]
> // 通配 *-a.example.com // 仅匹配子域名 *.example.com // 仅匹配主域名 -.example.com 这种写法在openwrt的luci-app-smartdns里面似乎不生效

请检查smartdns版本，域名匹配需要v43.0.20或更高版本

**Comment by chummumm** [comment]
root@OpenWrt:~# smartdns -v
smartdns 1.2023.43
这个版本可以么

**Comment by chummumm** [comment]
-.example.com测试不太行，话说op官方源怎么编译最新版smartdns呀
