### ISSUE TITLE
关于domain-rules -delete，不知道是bug还是我对该设定的理解有误

### ISSUE THREAD

**Issue by o0HalfLife0o** [pymumu/smartdns#1286]
**问题现象**  
domain-set设置域名相关规则后需要对该域名部分子域名做白名单处理，
比如对`google.com`设置`-rr-ttl 1`，但`dl.google.com`除外，
在使用domain-set的delete功能后，连续dig得到的结果ttl都是1，而不是默认设置的最低600

**smartdns来源以及版本**
41rc3

**涉及的配置(注意去除个人相关信息)**
gfw.txt
`google.com`

direct-list.txt
`dl.google.com`

custom.conf
```
rrl-ttl-min 600
domain-set -name gfw -type list -file /etc/smartdns/domain-set/gfw.txt
domain-rules /domain-set:gfw/ -c none -n fakedns -no-serve-expired -rr-ttl 1
domain-set -name direct -type list -file /etc/smartdns/domain-set/direct-list.txt
domain-rules /domain-set:direct/ -delete
domain-rules /domain-set:direct/ -n chn
```

**Comment by PikuZheng** [comment]
```
domain-rules /domain-set:direct/ -delete
domain-rules /domain-set:direct/ -n chn
```
同一条规则 应该写在同一行 即
```
domain-rules /domain-set:direct/ -delete -n chn
```

但是我觉得你遇到的问题应该是今天另一个issue提到的，无法区分 *.google.com 和 google.com 的问题

**Comment by PikuZheng** [comment]
我感觉是写了两条 后一条覆盖了前一条

**Comment by PikuZheng** [comment]
在我的理解 domain-rule /www.google.com/ 和 domain-rule /google.com/ 是两条不同的规则。所以 domain-rule /www.google.com/ -delete 并不会使得 domain-rule /google.com/ 匹配不到。

理论上子域名应该单独写入匹配规则，使新的规则覆盖旧的。或许可以试试
`domain-rules /domain-set:direct/ -c ping -n chn -rr-ttl 600` ?

**Comment by PikuZheng** [comment]
> @PikuZheng smartdns的规则比如address, nameserver等都是后一条覆盖前一条做例外白名单，所以看到domain-rules -delete删除对应的规则，就以为是把多个规则的例外白名单简写成-delete 域名匹配的问题，如果正则太废资源，那[限制域名匹配范围扩大](https://github.com/pymumu/smartdns/issues/1236#issuecomment-1439460040)应该比现在的匹配方式更省资源，也可以解决很多问题，比如[#1285 (comment)](https://github.com/pymumu/smartdns/issues/1285#issue-1595477740) ，也不知道@pymumu 会不会考虑

相同规则（ domain-rule /google.com/）才会后一条覆盖前一条，所以设计上 -delete应该删相同规则（我没看源码，猜测的）。
 domain-rule /google.com/， domain-rule /www.google.com/ 是两条，实践上是按照顺序匹配的（先子域名再主域名最后根域名）。
所以 domain-rule /www.google.com/ -delete 后，domain-rule /google.com/ 还在并且是生效状态。

**Comment by pymumu** [comment]
-delete是删除对应域名的所有规则

**Comment by choyri** [comment]
@pymumu 嗨，我遇到了和楼主一样的问题，参考配置如下：

```
domain-set -name overseas -file gfw.txt
domain-rules /domain-set:overseas/ -nameserver overseas -speed-check-mode none -rr-ttl 10 -no-cache -address #6

domain-set -name whitelist -file ./conf.d/google-china.txt
domain-rules /domain-set:whitelist/ -nameserver default
```

`gfw.txt` 里包含了 `google.com`，而 `google-china.txt` 里包含了 `dl.google.com`；预期是希望白名单走默认 NS，但我发现会命中多条规则：

```
[ INFO][     dns_server.c:5270] RULE-MATCH, type: 0, domain: dl.google.com, rule: google.com.
[ INFO][     dns_server.c:5270] RULE-MATCH, type: 8, domain: dl.google.com, rule: dl.google.com.
[ INFO][     dns_server.c:5270] RULE-MATCH, type: 10, domain: dl.google.com, rule: google.com.
[ INFO][     dns_server.c:5270] RULE-MATCH, type: 14, domain: dl.google.com, rule: google.com.
```

虽然白名单是走了默认 NS，可是还额外应用了一些非预期的规则：不测速、修改 TTL……

在 Issues 区中搜了很久还是没找到解决方案，请问这个问题有办法解决吗 🥲

关键词：子域名 规则 优先级
