### ISSUE TITLE
请问目前用的esir高大全固件，只能装compat的luci，有啥办法才能不换固件装javascript版本的luci呢

### ISSUE THREAD

**Issue by 58285474** [pymumu/smartdns#1288]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by PikuZheng** [comment]
根源在于coolsnowwolf（即lean版openwrt），作者积极排斥js的luci。这导致基于coolsnowwolf的修改版（包括lienol、Flippy、esir）
可以考虑根据源码自己补足编译。总体来说不是smartdns能解决的问题。建议在openwrt那边开issue问。
参考 https://github.com/pymumu/smartdns/issues/992 https://github.com/pymumu/smartdns/issues/1011 https://github.com/pymumu/smartdns/issues/1040 https://github.com/pymumu/smartdns/issues/1044 #1085

**Comment by jxph1123** [comment]
smartdns大佬有compat更新，找找，自己编译也行

**Comment by 58285474** [comment]
> smartdns大佬有compat更新，找找，自己编译也行

谢谢，我一直用compat没啥问题，主要想用javascript版本的luci，功能不一样，而且不会编译，工作太忙了，都是忙里偷闲玩这个
