### ISSUE TITLE
请求软件源仓库添加对redmi ax6的支持

### ISSUE THREAD

**Issue by digiw** [pymumu/smartdns#1290]
**需求应用场景**
[请描述需求应用的场景和方式。](https://downloads.openwrt.org/releases/) 发现v22.03的op库对于ipq8071a 的cpu没有支持，

**建议的方案**
   请求添加软件库支持，非常感谢！！！

**设备信息**
1. 设备信息（CPU，厂家）  
    redmi ax6 ipq8071a

2. 固件信息
   OpenWrt v22.03.3

**Comment by PikuZheng** [comment]
这个系统是什么架构的？

执行 `opkg print-architecture`看返回什么

**Comment by digiw** [comment]
> 这个系统是什么架构的？
> 
> 执行 `opkg print-architecture`看返回什么

返回内容如下：
arch all 1
arch noarch 1
arch aarch64_cortex-a53 10

**Comment by PikuZheng** [comment]
有的
![image](https://user-images.githubusercontent.com/12579522/221393993-e4302234-c660-4e6e-9156-da38be013b9b.png)

**Comment by digiw** [comment]
> 有的 ![image](https://user-images.githubusercontent.com/12579522/221393993-e4302234-c660-4e6e-9156-da38be013b9b.png)

感谢指点，我在op界面的配置opkg中，自定义内容里加上了下面两行：
src/gz openwrt_luci https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/
src/gz openwrt_packages https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/

重新更新后，刷出了一些其他软件包的更新，但没能刷出 r41 rc3这个最新版本的更新，请大佬帮忙看看，我哪里姿势不对？

**Comment by PikuZheng** [comment]
openwrt仓库的版本会落后这边。rc是“备选发布”的意思，不是正式版

**Comment by digiw** [comment]
> openwrt仓库的版本会落后这边。rc是“备选发布”的意思，不是正式版

理解了，非常感谢！：））
