### ISSUE TITLE
华硕AX86u启动了但是感觉没有应用上

### ISSUE THREAD

**Issue by CasenChan** [pymumu/smartdns#1293]
**需求应用场景**
请描述需求应用的场景和方式。
启动了但是感觉没有应用上，目前想搭配shellclash一起用，但是不太会设置。

**设备信息**
1. 设备信息（CPU，厂家）  
华硕AX86u
用的包是这个
[smartdns.1.2023.02.22-2200.aarch64-optware-all.ipk](https://github.com/pymumu/smartdns/releases/download/Release41-RC3/smartdns.1.2023.02.22-2200.aarch64-optware-all.ipk)
2. 固件信息
梅林 388.1

用教程中的命令显示
Cxcasen@RT-AX86U-2508:/tmp/home/root# nslookup -querytype=ptr smartdns
BusyBox v1.25.1 (2022-12-07 22:57:55 CST) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS serve

nslookup命令显示，我也不知道命令用的对不对。
Cxcasen@RT-AX86U-2508:/tmp/home/root# nslookup www.baidu.com
Server:    202.96.134.133
Address 1: 202.96.134.133 ns.szptt.net.cn

Name:      www.baidu.com
Address 1: 14.215.177.38
Address 2: 14.215.177.39

S50smartdns status却显示在running状态
Cxcasen@RT-AX86U-2508:/tmp/home/root# /opt/etc/init.d/S50smartdns status
smartdns is running

请问下shellclash里面需要设置些什么吗

**Comment by PikuZheng** [comment]
请提供smartdns的配置，尤其是监听在哪个端口，有哪些上游服务器

**Comment by CasenChan** [comment]
server-name smartdns
bind [::]:53 
cache-size 32768
force-qtype-SOA 65
log-level info
speed-check-mode ping,tcp:80
dualstack-ip-selection yes
server 223.6.6.6
server 119.29.29.29
server-https https://dns.alidns.com/dns-query
server-https https://doh.pub/dns-query
prefetch-domain yes

上游服务器 shellclash算不算，但是shellclash我还没start

**Comment by CasenChan** [comment]
> 请提供smartdns的配置，尤其是监听在哪个端口，有哪些上游服务器

server-name smartdns
bind [::]:53
cache-size 32768
force-qtype-SOA 65
log-level info
speed-check-mode ping,tcp:80
dualstack-ip-selection yes
server 223.6.6.6
server 119.29.29.29
server-https https://dns.alidns.com/dns-query
server-https https://doh.pub/dns-query
prefetch-domain yes

上游服务器 shellclash算不算，但是shellclash我还没start

**Comment by PikuZheng** [comment]
您这smartdns配置里没有clash啊 一般情况下clash会劫持dns请求 配置上clash是smartdns的下游
```
Cxcasen@RT-AX86U-2508:/tmp/home/root# nslookup [www.baidu.com](http://www.baidu.com/)
Server: 202.96.134.133
```
这个202.96.134.133应该是reslov.conf里的 和smart或clash或别的什么都无关

**Comment by PikuZheng** [comment]
smartdns自身的运行状态建议看smartdns的日志，默认在/var/log/smartdns.log
另外测试时
```
Cxcasen@RT-AX86U-2508:/tmp/home/root# nslookup [www.baidu.com](http://www.baidu.com/)
Server: 202.96.134.133
Address 1: 202.96.134.133 ns.szptt.net.cn
```
表明这个optware自身是不使用自身的dns服务作为dns服务器的，这个测试没意义

**Comment by CasenChan** [comment]
> smartdns自身的运行状态建议看smartdns的日志，默认在/var/log/smartdns.log
> 
> 另外测试时
> 
> ```
> 
> Cxcasen@RT-AX86U-2508:/tmp/home/root# nslookup [www.baidu.com](http://www.baidu.com/)
> 
> Server: 202.96.134.133
> 
> Address 1: 202.96.134.133 ns.szptt.net.cn
> 
> ```
> 
> 表明这个optware自身是不使用自身的dns服务作为dns服务器的，这个测试没意义

嗷嗷好的 我自己研究下哈

**Comment by CasenChan** [comment]
> 您这smartdns配置里没有clash啊 一般情况下clash会劫持dns请求 配置上clash是smartdns的下游

大佬，这个配置的话是在smartdns的配置里面配么，该怎么配呢

**Comment by CasenChan** [comment]
当前基础DNS：114.114.114.114, 223.5.5.5
FallbackDNS：1.0.0.1, 8.8.4.4
多个DNS地址请用“|”或者“, ”分隔输入
必须拥有本地根证书文件才能使用dot/doh类型的加密dns
-----------------------------------------------
 1 修改基础DNS
 2 修改Fallback_DNS
 3 重置DNS配置
 4 一键配置加密DNS
 5 hosts优化：  	已开启	————调用本机hosts并劫持NTP服务
 6 Dnsmasq转发：	未开启	————不推荐使用
 7 禁用DNS劫持：	未禁用	————取消劫持局域网53端口
 0 返回上级菜单

clash里面的DNS劫持我没开，是需要开启吗

**Comment by CasenChan** [comment]
PS C:\Users\Cxcas> nslookup www.baidu.com
Server:  smartdns
Address:  240e:3ba:3039:1200::1

Non-authoritative answer:
Name:    www.a.shifen.com
Addresses:  14.215.177.38
          14.215.177.39
Aliases:  www.baidu.com

PS C:\Users\Cxcas> nslookup www.google.com
Server:  smartdns
Address:  240e:3ba:3039:1200::1

Non-authoritative answer:
Name:    www.google.com
Addresses:  2001::68f4:2e47
          162.125.1.8

我这是成功了么？

**Comment by PikuZheng** [comment]
> PS C:\Users\Cxcas> nslookup [www.baidu.com](http://www.baidu.com) Server: smartdns Address: 240e:3ba:3039:1200::1
> 
> Non-authoritative answer: Name: [www.a.shifen.com](http://www.a.shifen.com) Addresses: 14.215.177.38 14.215.177.39 Aliases: [www.baidu.com](http://www.baidu.com)
> 
> PS C:\Users\Cxcas> nslookup [www.google.com](http://www.google.com) Server: smartdns Address: 240e:3ba:3039:1200::1
> 
> Non-authoritative answer: Name: [www.google.com](http://www.google.com) Addresses: 2001::68f4:2e47 162.125.1.8
> 
> 我这是成功了么？

客户端的dns看起来是smartdns，但是国外域名被污染了。
