### ISSUE TITLE
配置里有nameserver /vivo.com/cn，请问当访问http://wifi.vivo.com.cn/generate_204时会用 cn组里的域名服务器吗？

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#1295]
我设置log-level info但没有发现解析的服务器

**Comment by PikuZheng** [comment]
不会。
需要log-level debug。

**Comment by zhouhm** [comment]
多谢回复！我把debug打开再试试

**Comment by devioa** [comment]
nameserver是采用的后缀匹配模式，你访问`http://wifi.vivo.com.cn/generate_204`查询到的后缀是`vivo.com.cn`而不是`vivo.com`，所以不会走`cn`组查询，你应该添加或改为`nameserver /vivo.com.cn/cn`

**Comment by zhouhm** [comment]
多谢提醒！我把log-level debug打开了在日志里还是看不到所用的dns服务器
