### ISSUE TITLE
完全替代 dnsmasq

### ISSUE THREAD

**Issue by Hill-98** [pymumu/smartdns#1296]
是否考虑做到类似 https://openwrt.org/docs/guide-user/base-system/dhcp_configuration#replacing_dnsmasq_with_odhcpd_and_unbound 中和 unbound 类似的功能，也就是可以搭配任意 dhcp 服务器使用，比如自定义本地域。

还有一点就是完全解析 IPv6 SLAAC 地址，这一点无论是 unbound 还是 dnsmasq 做的都不太行，我觉得可以读取 OpenWrt 的 IPv6 邻居表，然后匹配 MAC 地址，再用 MAC 地址匹配 IPv4 DHCP 里的主机名。

**Comment by PikuZheng** [comment]
自定义本地域的问题我提了好几次，正向查找区域可以用address来配置，但添加后没有对应的ptr记录。后来用 dnsmasq-lease-file 这个功能实现了，就是杜撰配置文件麻烦些。
但是MX、SRV、TXT等记录目前还是只能转发，不能直接配置相应的值。
SLAAC是说将本地主机名解析为ipv6地址吗？

**Comment by Hill-98** [comment]
SLAAC 指同时支持正向和反向查询，因为像 dnsmasq 只能查询到通过 DHCPv6 获取的地址，以及反向查询时也只支持 DHCPv6 的地址，像是 SLAAC 无状态获取的 IPv6 地址无论是查询主机名还是 PTR 都查不出来。

unbound 里有个 dns64_slaac 功能，好像是根据 IPv4 的 MAC 地址查询相关的 SLAAC 地址，但是测试下来感觉还是不太行。

**Comment by jxph1123** [comment]
你们玩得好高端，完全看不懂。。

**Comment by Hill-98** [comment]
@pymumu 类似我发的那篇文档，里面讲述了如何使用 odhcpd 和 unbound 替换掉 dnsmasq，我的意思能不能用 odhcpd + smartdns 替换掉 dnsmasq。

如果能做到的同时，增强下 IPv6 SLAAC 解析就更好了，我现在用的是 OpenWrt 21.02，不知道最新的 OpenWrt 有没有改善 IPv6 SLAAC 解析。

**Comment by Hill-98** [comment]
好吧，我刚刚逻辑没有说通顺，DNS 要解析本地域或反向解析 PTR 需要读取 DHCP 租约文件，SmartDNS 现在只支持 dnsmasq 格式的租约文件，并不支持 odhcpd 的租约文件。我觉得使用 `ubus call dhcp ipv4leases` 获取租约可能会更合适。

第二点就是 IPv6 SLACC 的问题，因为租约文件里只会存在 DHCPv6 客户端，但是像 Android 这类用 SLAAC 获取 IPv6 地址的话，想反向解析出地址对应的主机名是不能单靠租约的，可以考虑加强下这方面。

**Comment by pymumu** [comment]
其实mdns就可以了。

avahi-resolve -n xxxx.local -4
avahi-resolve -n xxxx.local -6

**Comment by Hill-98** [comment]
支持 mdns 的软件不多，这个需求可能还得靠 OpenWrt 上游努力，我也在考虑自己写一个专注于 OpenWrt 的本地主机名和 PTR  
解析的 DNS 服务器。

**Comment by PikuZheng** [comment]
dnsmasq分两部分：dns转发和dhcp服务。
本地域名解析实际上是dhcp服务器去dns服务器动态修改记录。
作为dns条件转发，smartdns做得很好。但是并不能像bound、unbound、Windows的dns服务器那样宣告一个起始授权并提供a记录以外的其他记录。这一点dnsmasq也是没有实现的，本地主机解析只是既作为dns服务又作为dhcp服务的便利。
