### ISSUE TITLE
不缓存不测速，dns查到16个ipv4 ip和8个ipv6 ip并给16个ipv4结果和8个ipv6结果；测速缓存后，只给3个ipv4 ip和1个ipv6 ip，难道不应该也是16个ipv4和8个ipv6吗？

### ISSUE THREAD

**Issue by moruiris** [pymumu/smartdns#1297]
**问题现象**  
简要描述问题出现的现象
1，不缓存不测速，dns查到16个ipv4 ip和8个ipv6 ip并给16个ipv4结果和8个ipv6结果；
2，测速缓存后，只给3个ipv4 ip和1个ipv6 ip，难道不应该也是16个ipv4和8个ipv6吗？

**运行环境**
1. 固件型号  
x86-64
2. 运营商  
移动
3. smartdns来源以及版本
最新版本
4. 涉及的配置(注意去除个人相关信息)
默认测速缓存配置

**重现步骤**
1. 上游DNS配置。  
223.5.5.5
2. 访问的域名。  
www.bilibili.com

*************************************************
1，情况1（不缓存不测速不限制ip数量）16个ipv4和8个ipv6
*************************************************
root@openwrt-pang:~# nslookup www.bilibili.com 223.5.5.5
Server:		223.5.5.5
Address:	223.5.5.5:53

Non-authoritative answer:
www.bilibili.com	canonical name = a.w.bilicdn1.com
Name:	a.w.bilicdn1.com
Address: 112.13.92.202
Name:	a.w.bilicdn1.com
Address: 117.169.96.199
Name:	a.w.bilicdn1.com
Address: 112.13.92.203
Name:	a.w.bilicdn1.com
Address: 112.13.92.196
Name:	a.w.bilicdn1.com
Address: 223.111.250.53
Name:	a.w.bilicdn1.com
Address: 112.13.92.195
Name:	a.w.bilicdn1.com
Address: 223.111.250.57
Name:	a.w.bilicdn1.com
Address: 223.111.250.56
Name:	a.w.bilicdn1.com
Address: 223.111.250.55
Name:	a.w.bilicdn1.com
Address: 223.111.250.54
Name:	a.w.bilicdn1.com
Address: 112.13.92.199
Name:	a.w.bilicdn1.com
Address: 117.169.96.198
Name:	a.w.bilicdn1.com
Address: 117.169.96.200
Name:	a.w.bilicdn1.com
Address: 111.48.57.46
Name:	a.w.bilicdn1.com
Address: 111.48.57.45
Name:	a.w.bilicdn1.com
Address: 111.48.57.44

Non-authoritative answer:
www.bilibili.com	canonical name = a.w.bilicdn1.com
Name:	a.w.bilicdn1.com
Address: 2409:8c38:c40:100::241
Name:	a.w.bilicdn1.com
Address: 2409:8c28:202:8::196
Name:	a.w.bilicdn1.com
Address: 2409:8c28:202:8::199
Name:	a.w.bilicdn1.com
Address: 2409:8c28:202:8::203
Name:	a.w.bilicdn1.com
Address: 2409:8c38:c40:100::243
Name:	a.w.bilicdn1.com
Address: 2409:8c4c:c00:9::22
Name:	a.w.bilicdn1.com
Address: 2409:8c38:c40:100::242
Name:	a.w.bilicdn1.com
Address: 2409:8c28:202:8::202

*************************************************
2，情况2（缓存测速但不限制ip数量,也不双栈优选）
*************************************************
①第一次查询，给最快一个IP，正确
root@openwrt-pang:~# nslookup www.bilibili.com
Server:		127.0.0.1
Address:	127.0.0.1:53

Non-authoritative answer:
www.bilibili.com	canonical name = a.w.bilicdn1.com
Name:	a.w.bilicdn1.com
Address: 111.48.57.44

Non-authoritative answer:
www.bilibili.com	canonical name = a.w.bilicdn1.com
Name:	a.w.bilicdn1.com
Address: 2409:8c38:c40:100::241
②第二次查询，命中缓存，返回3个ipv4 ip，一个ipv6 ip（按道理应该返回情况1的所有ip，为什么不是这样的结果）
root@openwrt-pang:~# nslookup www.bilibili.com
Server:		127.0.0.1
Address:	127.0.0.1:53

Non-authoritative answer:
www.bilibili.com	canonical name = a.w.bilicdn1.com
Name:	a.w.bilicdn1.com
Address: 111.48.57.44
Name:	a.w.bilicdn1.com
Address: 111.48.57.46
Name:	a.w.bilicdn1.com
Address: 111.48.57.45

Non-authoritative answer:
www.bilibili.com	canonical name = a.w.bilicdn1.com
Name:	a.w.bilicdn1.com
Address: 2409:8c38:c40:100::241

**Comment by PikuZheng** [comment]
max-reply-num=？我记得默认是8

**Comment by moruiris** [comment]
> max-reply-num=？我记得默认是8

没有设置和设置16 都是上面那样的结果
另外我测试了一下，设置1 可以得到1个结果；设置2可以得到2个结果；设置3 可以得到3个结果；一但设置超过4，就还是3个

**Comment by moruiris** [comment]
> 这个配置是指最多允许多少个IP，不是说一定要给那么多IP，默认配置最多8个IP。
> 
> 开启缓存和测速后，会丢弃速度慢的地址，这样就可能不足8个。甚至只有1个地址。
> 
> 你可以对比这些IP的ping值

ok 理解了
