### ISSUE TITLE
PikuZheng大佬提供个基于Openwrt 最新 release 版本的ipk吧

### ISSUE THREAD

**Issue by liangshixing** [pymumu/smartdns#1299]
@PikuZheng 
当前openwrt build是基于snapshots sdk 构建的，近期snapshots的openssl已经是3.0.8了，就导致编译出来的版本用不了了。

**Comment by PikuZheng** [comment]
我晕，这块不熟，等我研究研究

**Comment by PikuZheng** [comment]
修改sdk为release 22.03.3

**Comment by liangshixing** [comment]
赞

**Comment by liangshixing** [comment]
root@OpenWrt:~# opkg install smartdns_1.2023.v41.rc3.6-1_x86_64.ipk
Multiple packages (smartdns and smartdns) providing same name marked HOLD or PREFER. Using latest.
Upgrading smartdns on root from 1.2023.v41.rc3.5 to 1.2023.v41.rc3.6-1...
Removing obsolete file /etc/smartdns/domain-forwarding.list.
Removing obsolete file /etc/smartdns/smartdns.conf.
Removing obsolete file /etc/smartdns/domain-block.list.
Not deleting modified conffile /etc/smartdns/domain-forwarding.list.
Not deleting modified conffile /etc/smartdns/domain-block.list.
Configuring smartdns.
Collected errors:
 * file_sha256sum_alloc: Failed to open file /etc/smartdns/domain-forwarding.list: No such file or directory.
 * file_sha256sum_alloc: Failed to open file /etc/smartdns/domain-block.list: No such file or directory.
 * resolve_conffiles: Existing conffile /etc/config/smartdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/smartdns-opkg.

好像还有些问题？
