### ISSUE TITLE
ipset的白名单规则“-”能否支持根据ip匹配

### ISSUE THREAD

**Issue by 523860169** [pymumu/smartdns#130]
谷歌部分域名解析到北京203.208段，如果不添加白名单就会导致连接速率较慢，且浪费流量，比如
```
fonts.googleapis.com
redirector.gvt1.com
safebrowsing.googleapis.com
ssl.google-analytics.com
```
这些算好的，但是还有一部分是比较麻烦，比如
```
r11---sn-2x3eln7e.gvt1.com
r11.sn-2x3eln7e.gvt1.com
```
这种只能发现一个加一个白名单，而且既然北京的都集中在203.208.32.0-203.208.63.255，何不直接针对这个网段设置白名单，也省去了一直无法完善域名白名单的麻烦
另外，虽然像fonts.googleapis.com添加白名单了，但是也不知道哪天会不会又直接解析到美国，所以还是根据ip来给白名单比较稳一点

**Comment by pymumu** [comment]
ignore-ip配置支持段，看一下配置参数的帮助吧

**Comment by pymumu** [comment]
google的域名最好用分流功能

**Comment by 523860169** [comment]
202.141.162.123:5353
101.6.6.6:5353
208.67.220.220:5353
可是这些都很好用啊，如果谷歌不能用这些解析，那响应时间会慢很多

**Comment by pymumu** [comment]
ignore-ip配置忽略北京的ip

**Comment by 523860169** [comment]
不想忽略，因为响应挺快的，不希望哪天翻墙软件临时波动也影响到其他正常的网站

**Comment by pymumu** [comment]
那就不明白你想做什么了

**Comment by 523860169** [comment]
我想要的效果是当fonts.googleapis.com解析到203.208段这个白名单ip地址时，不翻墙，但是解析到非白名单ip地址时走翻墙。类似这个效果
ipset=/fonts.google.com/proxylist
ipset=/203.208.43.21/-

**Comment by pymumu** [comment]
你应该优先国内dns解析这个域名，这样就会优先返回北京IP了

**Comment by 523860169** [comment]
我现在用的规则就已经是能返回北京ip了，但是gvt1.com、googlevideo.com、googleapis.com的子域名都是有的返回北京IP有的返回美国IP，而我要的效果就是当他返回北京IP时不走代理，返回美国IP时走代理

**Comment by pymumu** [comment]
现在没法支持，dnsmasq也应该不支持

ipset值能针对域名，无法针对ip

唯一能做的就是ignore IP支持安域名过滤

**Comment by 523860169** [comment]
好吧，那只能以后再看看了

**Comment by pymumu** [comment]
或者是fallback机制，检测不通时在设置规则

**Comment by 523860169** [comment]
算了，如果太麻烦的话就不折腾了
