### ISSUE TITLE
支持读取`hosts`文件

### ISSUE THREAD

**Issue by uiolee** [pymumu/smartdns#1304]
**需求应用场景**

我在openwrt路由器上使用smartdns,并在`/etc/hosts`中配置一些特定的域名和ip，经测试smartdns似乎并没有读取hosts文件。

hosts文件
```hosts
# hosts
192.168.1.1 jfgiaosfjfjdaioiowefjwqjfosadzixjvanf.cn
114.118.7.161 pool.ntp.org
114.118.7.163 pool.ntp.org
```

nslookup
```cmd
c:\>nslookup pool.ntp.org 192.168.1.1
服务器:  smartdns
Address:  192.168.1.1

非权威应答:
名称:    pool.ntp.org
Address:  111.230.189.174

c:\>nslookup jfgiaosfjfjdaioiowefjwqjfosadzixjvanf.cn
服务器:  smartdns
Address:  192.168.1.1

*** smartdns 找不到 jfgiaosfjfjdaioiowefjwqjfosadzixjvanf.cn: Non-existent domain
```

**建议的方案**

我不知道是我配置错误、还是smartdns没有这个功能、还是有特别的原因所以不打算支持这个功能。

**设备信息**

1. 设备信息（CPU，厂家）  

Xiaomi Mi Router CR6606
MediaTek MT7621

2. 固件信息

OpenWrt 22.03.3
smartdns 1.2022.38.1

**Comment by PikuZheng** [comment]
请使用address配置

**Comment by devioa** [comment]
address /jfgiaosfjfjdaioiowefjwqjfosadzixjvanf.cn/192.168.1.1
address /pool.ntp.org/114.118.7.161
address /pool.ntp.org/114.118.7.163

**Comment by Hua-Au-Yeung** [comment]
配置已经支持`hosts-file /etc/hosts`

date: 2025/03/25

**Comment by uiolee** [comment]
https://github.com/pymumu/smartdns/commit/c95efa5ccf845c1ab95eaac16ff83b734eec4674

Sounds great! Thanks you!
