### ISSUE TITLE
`rr-ttl-reply-max` 没生效？还是我理解不对？

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#1305]
**问题现象**  
`rr-ttl-reply-max`配置的60，但是很多的应答还是`rr-ttl-min`配置的600或者非预期的TTL

**运行环境**
1. 固件型号  
openwrt_x86 docker

2. 运营商  
四川电信

3. smartdns来源以及版本
60a3719ec739be2cc1e11724ac049b09a75059cb

4. 涉及的配置(注意去除个人相关信息)
```
serve-expired-reply-ttl 5
rr-ttl-min 600
rr-ttl-max 7200
rr-ttl-reply-max 60
```
![Snipaste_2023-03-05_18-39-20](https://user-images.githubusercontent.com/38558065/222955645-26966281-6cbd-45e9-9106-39c979f0d46c.png)

**Comment by pymumu** [comment]
cache的处理上有问题，修改了一下。

**Comment by devioa** [comment]
> cache的处理上有问题，修改了一下。

是还没提交吗？我这看主线commit还是昨天的

**Comment by pymumu** [comment]
提交了

**Comment by devioa** [comment]
> 提交了

我刚刚发现首次查询的域名应答的TTL也是`rr-ttl-min`配置的600，这也是预期行为吗？

**Comment by pymumu** [comment]
有问题，晚上改一下。

**Comment by yxmyxmyyy** [comment]
我也遇到这个问题，我设置的域名为120ttl，但是smartdns在默认情况下都是600ttl
