### ISSUE TITLE
请问指定某个域名不解析ipv6的问题

### ISSUE THREAD

**Issue by roycho93** [pymumu/smartdns#1306]
作者你好，请问在“域名地址”栏目中，自定义加上address /google.com/#6这一行的话,是只有google.com这个域名不走ipv6解析，还是所有二级以及多级域名都不走ipv6解析呢？如果不是，是否address /*.google.com/#6这样可以达到我所描述的效果？谢谢

**Comment by PikuZheng** [comment]
`address /google.com/#6` = `^.*\.google\.com$` 包含主域名和子域名

**Comment by devioa** [comment]
只要后缀是`google.com`的AAAA记录都返回SOA
