### ISSUE TITLE
有个问题求解答

### ISSUE THREAD

**Issue by AXBNG** [pymumu/smartdns#1308]
openwrt路由，smartdns设置为53端口自动设置dnsmasq，一切正常，但是有一个问题很奇怪。

裸连github经常打不开，但是在电脑端nslookup github.com之后，再次访问就能打开了。请问这是什么原因，还是哪里设置的问题？

**Comment by PikuZheng** [comment]
怀疑电脑没走smartdns，检查电脑配置的ipv6 dns的可用性

**Comment by AXBNG** [comment]
> 怀疑电脑没走smartdns，检查电脑配置的ipv6 dns的可用性

好的我看看
