### ISSUE TITLE
建议nameserver支持多个组

### ISSUE THREAD

**Issue by Aefer** [pymumu/smartdns#131]
**需求应用场景**
可以更灵活地配置dns服务器

**建议的方案**
nameserver支持多个组，
例如`nameserver /example.com/home,office`

**Comment by pymumu** [comment]
现在多组是设置到DNS服务器上的，也就是`-group`可以指定多次 。

如果只是设置域名通过几个特定DNS服务器查询的话，可以通过设置DNS服务器属于多个组来实现。

而不是nameserver指定多个组。

**Comment by ziyuedi** [comment]
> 现在多组是设置到DNS服务器上的，也就是`-group`可以指定多次 。
> 如果只是设置域名通过几个特定DNS服务器查询的话，可以通过设置DNS服务器属于多个组来实现。
> 
> 而不是nameserver指定多个组。

多个组可以更简单地细分，而不是指定一大堆`-group`
比如我想给某个网站增加一个dns服务器解析

**Comment by pymumu** [comment]
你应该换个思路理解这个分组，group写baidu，360这样的名称是没有意义的。
你应该将server分类，比如secure，unsecure。
对应的，域名是否应该用secure解析，还是unsecure解析。
这才是正确的用法。

**Comment by ziyuedi** [comment]
> 你应该换个思路理解这个分组，group写baidu，360这样的名称是没有意义的。
特定域名特定server可以减少解析时间/增加解析准确性。

**Comment by pymumu** [comment]
那同时支持多个组之后消耗很多资源检测

**Comment by pymumu** [comment]
目前不考虑支持此功能。
