### ISSUE TITLE
请问使用nameserver设置分流规则时是否支持通配符？

### ISSUE THREAD

**Issue by zbc258** [pymumu/smartdns#1310]
比如我想设置国内地址的分流规则，能否使用形如：
nameserver /*.cn/domestic
来过滤所有域名以cn结尾的网址？

**Comment by PikuZheng** [comment]
nameserver /cn/domestic

**Comment by PikuZheng** [comment]
重复 #792  #1285 #1306 https://github.com/pymumu/smartdns/issues/1295#issuecomment-1449921900 https://github.com/pymumu/smartdns/issues/580#issuecomment-678563074
