### ISSUE TITLE
以后会把缓存放redis吗 像mosdns那样命中率也许会高些吧，现阶段怎么永久保存缓存？

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1314]
serve-expired-ttl 0
是不是就永久保存缓存？

希望能添加redis 类似保存方式
openwrt 重启就没了

**Comment by PikuZheng** [comment]
serve-expired-ttl 0 就没缓存了吧？TTL值越大，缓存越久。
但是dns记录又不是一直不变的，总要需要有个ttl使记录过期。
开预读不断的刷新，可能情况好一点

**Comment by lalasou** [comment]
> serve-expired-ttl 0 就没缓存了吧？TTL值越大，缓存越久。
> 但是dns记录又不是一直不变的，总要需要有个ttl使记录过期。
> 开预读不断的刷新，可能情况好一点

这样估计命中率不高啊

**Comment by pymumu** [comment]
进程在重启的时候，会将缓存持久化到硬盘上。重启的时候读取。
前提是没有关闭缓存持久化功能。

**Comment by lalasou** [comment]
> 进程在重启的时候，会将缓存持久化到硬盘上。重启的时候读取。
> 
> 前提是没有关闭缓存持久化功能。

问题 一般openwrt都是直接重启或者关机了 这样的应该保存不了吧


还有个问题 我试了下 大部分情况下 3天 cache才不到20m   
那个持久化缓存空间大小限制可不可以取消

**Comment by pymumu** [comment]
最新版本重启都会持久话的。缓存大小cache-size参数控制。

20M的话，一般都有20W域名了。

**Comment by liangxyz** [comment]
> serve-expired-ttl 0

我看教程，serve-expired-ttl 0 是默认值，应该是永不超时的意思啊

**Comment by mokeyish** [comment]
redis 没必要吧，内存够的话，还放 redis，反而更慢了，还是放内存好，Ip 缓存又不怎么占空间。

**Comment by lalasou** [comment]
> redis 没必要吧，内存够的话，还放 redis，反而更慢了，还是放内存好，Ip 缓存又不怎么占空间。

主要是一些储存空间小的设备
默认 持久缓存目录需要一百多兆才能开启

我感觉大部分硬路由很少有flash 剩余一百多兆的吧
放内存重启就没了
