### ISSUE TITLE
domain-set增加geosite域名匹配规则支持

### ISSUE THREAD

**Issue by weiping** [pymumu/smartdns#1316]
**需求应用场景**
domain-set增加geosite域名匹配规则文件支持，例如；
domain-set -name google -type geosite -file /jffs/configs/google.txt

域名规则有以下几种匹配方式:
以 domain: 开头，域匹配。e.g: domain:google.com 会匹配自身 google.com，以及其子域名 www.google.com, maps.l.google.com 等。
以 full: 开头，完整匹配。e.g: full:google.com 只会匹配自身。
以 keyword: 开头，关键字匹配。e.g: keyword:google.com 会匹配包含这个字段的域名，如 google.com.hk, www.google.com.hk。
以 regexp: 开头，正则匹配。e.g: "regexp:\\.goo.*\\.com$" 匹配 "www.google.com" 或 "fonts.googleapis.com"，但不匹配 "google.com"。

如果没有指定匹配方式，默认为域匹配。

匹配方式按如下顺序生效: full > domain > regexp > keyword。
相同匹配方式的规则按如下顺序生效:
domain 规则: 子域名优先。比如如果同时存在规则 google.com 和 com。 www.google.com 会优先匹配 google.com，然后 com。
regexp 和 keyword 规则生效顺序为规则导入的顺序。

**建议的方案**
域匹配和完整匹配在smartdns已经支持，需要考虑增加关键字匹配和正则匹配的支持，关键字匹配可以作为正则匹配的一个特例处理。

**Comment by lintaozi** [comment]
重复 #1274
