### ISSUE TITLE
GL.iNet GL-SF1200 CPU: SF19A2890 MIPS可能魔改了，无法安装SmartDNS

### ISSUE THREAD

**Issue by KelvinSoh8** [pymumu/smartdns#1320]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  GL.iNet GL-SF1200 CPU: SF19A2890 MIPS可能魔改了

2. 固件信息GL.iNet 官方自带的OpenWrt 18.06 r0-d5ed025 

无法正常使用opkg install安装
其他架构版本我都试了，无法安装

GL.iNet官方软件源也不自带smartdns

GL.iNet SF1200无线路由器使用国产了矽昌siflower SF19A28 CPU
看上去好像是mips架构，可是mipsel和mips无法成功安装
网上搜了发现是经过了魔改了

网上搜索找到了GL.iNet提供的GL-SF1200无线路由器（矽昌siflower SF19A28 CPU）
完整源代码https://github.com/gl-inet/openwrt

我自己技术不够，无法成功完成编译
只能希望smartdns开发者或其他有能力的开发者帮忙编译

**Comment by PikuZheng** [comment]
这个系统是什么架构的？

执行 opkg print-architecture看返回什么

**Comment by pymumu** [comment]
release页面下载下载

https://github.com/pymumu/smartdns/releases/download/Release41/smartdns.1.2023.03.04-1125.mips-openwrt-all.ipk

https://github.com/pymumu/smartdns/releases/download/Release41/luci-app-smartdns.1.2023.03.04-1125.all-luci-compat-all.ipk

**Comment by AnyoeDove** [comment]
如果有人搜到这的话 虽然系统中显示的架构是mips_sf19a28 事实上能用的是mipsel
