### ISSUE TITLE
证书文件存在时程序无法启动

### ISSUE THREAD

**Issue by PikuZheng** [pymumu/smartdns#1321]
**问题现象**  
购买的可信证书，证书文件存在时程序无法启动

**运行环境**
1. 固件型号  
docker alpine

2. 运营商  
无关

3. smartdns来源以及版本
当前最新版本自动编译（docker hub）

4. 涉及的配置(注意去除个人相关信息)
```
bind-tls [::]:853
bind-cert-file /etc/smartdns/cert.pem
bind-cert-key-file /etc/smartdns/cert.key
```
其中cert.pem和cert.key是从阿里云购买的ssl证书文件。文件有读取权限（644）。

**重现步骤**

**信息收集**  
```
/ # /usr/sbin/smartdns -f -x -p - -S
create cert failed.
init failed.
```
没有dump文件产生

**Comment by pymumu** [comment]
fixed
