### ISSUE TITLE
还是希望SmartDNS能有个WEB面板

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#1323]
**需求应用场景**
`INFO`级别的日志记录也不是很详细（或者说不是我想看到的），`DEBUG`级别的话，请求太多刷得又太快根本看不清（`docker logs -f`）

**建议的方案**
类似`AdGuardhome`那样的，有查询日志和概况统计，能直观反馈具体处理过程和响应详情

**Comment by zxlhhyccc** [comment]
同意。。。

**Comment by pymumu** [comment]
使用audit log，WebUI暂时没精力。

**Comment by devioa** [comment]
> 使用audit log，WebUI暂时没精力。

我是docker部署的，要检查审计日志比较麻烦，有没有可能实现让审计日志输出到`docker logs`或者把smartdns的默认日志输出为审计日志？

**Comment by PikuZheng** [comment]
> > 使用audit log，WebUI暂时没精力。
> 
> 我是docker部署的，要检查审计日志比较麻烦，有没有可能实现让审计日志输出到`docker logs`或者把smartdns的默认日志输出为审计日志？

1. 修改启动参数为 `/usr/sbin/smartdns -f` （从默认中去掉-x）
2. 配置
```
audit-enable yes
audit-SOA yes
audit-num 1
audit-file /proc/self/fd/1
```

**Comment by devioa** [comment]
> > > 使用audit log，WebUI暂时没精力。
> > 
> > 
> > 我是docker部署的，要检查审计日志比较麻烦，有没有可能实现让审计日志输出到`docker logs`或者把smartdns的默认日志输出为审计日志？
> 
> 1. 修改启动参数为 `/usr/sbin/smartdns -f` （从默认中去掉-x）
> 2. 配置
> 
> ```
> audit-enable yes
> audit-SOA yes
> audit-num 1
> audit-file /proc/self/fd/1
> ```

OK成功了，不过还是期待WebUI

**Comment by mokeyish** [comment]
好主意，拿 adguardhome 的前端代码改出一个来😂

**Comment by zxlhhyccc** [comment]
> luci添加日志显示功能，省的ssh进去查看

能否在luci添加日志显示功能，省的ssh进去查看。。。。

**Comment by ZYB14** [comment]
期待

**Comment by hjkl950217** [comment]
期待+1
