### ISSUE TITLE
nameserver 和 whitelist-ip的问题

### ISSUE THREAD

**Issue by InspoOnU** [pymumu/smartdns#1327]
配置如下
domain-rules /domain-set:CHN/ -nameserver CN -speed-check-mode ping
server-https https://1.12.12.12/dns-query -group CN -whitelist-ip
其中CN代表国内域名，白名单IP是国内IP

比如访问sglong.wechat.com，命中了 nameserver CN 规则，但是由于返回的IP不在whitelist-ip内，smartdns丢弃了查询CN的结果。
之前的版本只要命中了nameserver，就会无视IP规则。指定了nameserver应该就默认这个DNS不会这个域名，似乎之前的逻辑更合理些。

**Comment by PikuZheng** [comment]
就我所知无论是否命中nameserver，都不会无视-whitelist-ip。
之前版本与现在版本的重大区别是，之前版本的域名表是个排序数列，重复的策略随机选一个生效。现在严格按照配置文件撰写顺序，后一个会覆盖掉前一个。所以如果配置没变，不如看看是哪些重复的策略导致了以前生效

**Comment by InspoOnU** [comment]
> 就我所知无论是否命中nameserver，都不会无视-whitelist-ip。 之前版本与现在版本的重大区别是，之前版本的域名表是个排序数列，重复的策略随机选一个生效。现在严格按照配置文件撰写顺序，后一个会覆盖掉前一个。所以如果配置没变，不如看看是哪些重复的策略导致了以前生效

这几天又排查了一下，发现对于同一个server，不能同时指定group和whitelist-ip。
否则一个域名命中nameserver并发往该group组查询后，如果返回IP没命中whitelist-ip，则会返回空解析。

**Comment by PikuZheng** [comment]
> server-https https://1.12.12.12/dns-query -group CN -whitelist-ip

我认为group和whitelist是”and“关系是正确的，不应改成”or“

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/config/ip-rule/
