### ISSUE TITLE
使用了response-mode fastest-response 一些域名会返回0.0.0.0

### ISSUE THREAD

**Issue by ilafz** [pymumu/smartdns#1328]
能否过滤掉0.0.0.0的回应 使用返回真实ip的结果

**Comment by ilafz** [comment]
好像解决了 在自定义里面添加了ignore-ip 0.0.0.0

**Comment by PikuZheng** [comment]
重复 https://github.com/pymumu/smartdns/issues/1176#issuecomment-1322294406 不如调查一下上游为啥会给出个0

**Comment by ilafz** [comment]
运营商的dns 会这样 其他上游服务器都返回正常

**Comment by pymumu** [comment]
最新代码应该修正了此问题。
