### ISSUE TITLE
下个版本把response-mode选项加到LUCI界面中吧

### ISSUE THREAD

**Issue by iamyangyiok** [pymumu/smartdns#1329]
**需求应用场景**
下个版本把response-mode  模式 选项加到LUCI界面中吧。这样配置起来更方便

另问下response-mode 开启 ，是否先要把测速模式打开。还是说，不用开，只用开 response-mode也行

**Comment by zxlhhyccc** [comment]
> **需求应用场景** 下个版本把response-mode 模式 选项加到LUCI界面中吧。这样配置起来更方便
> 
> 另问下response-mode 开启 ，是否先要把测速模式打开。还是说，不用开，只用开 response-mode也行

不是已经加到luci了吗？

**Comment by iamyangyiok** [comment]
> 

我没看到啊

**Comment by iamyangyiok** [comment]
> > **需求应用场景** 下个版本把response-mode 模式 选项加到LUCI界面中吧。这样配置起来更方便
> > 另问下response-mode 开启 ，是否先要把测速模式打开。还是说，不用开，只用开 response-mode也行
> 
> 不是已经加到luci了吗？

我LUCI没看到啊

**Comment by iamyangyiok** [comment]
> response-mode 影响的是未被缓存的域名首次查询，和测速配置相对独立。参考[#1249 (comment)](https://github.com/pymumu/smartdns/issues/1249#issuecomment-1399657463)
> 
> ![image](https://user-images.githubusercontent.com/12579522/225222742-1962ee39-6596-495c-8d5b-832718dddec7.png)

感谢， 那就是这两个模式独立的，另请教下 response-mode 是不是不能关缓存，关了就失效了。

**Comment by PikuZheng** [comment]
关缓存 first ping 和 fastest response 肯定是可以的。fastest ip 不确定。
缓存单位是记录数量（个）
