### ISSUE TITLE
希望提供openrc的支持

### ISSUE THREAD

**Issue by chieve-bale** [pymumu/smartdns#1336]
希望提供openrc的支持
在alpine，无法正常加入开机自启，需手动service smartdns start
service restart也会发生启动失败

**Comment by pymumu** [comment]
linux系统直接下载对应架构的tar.gz包，安装方式参考安装指导。

**Comment by chieve-bale** [comment]
alpine:~# /etc/init.d/smartdns stop
Stop smartdns server success.
alpine:~# /etc/init.d/smartdns start
start smartdns server failed.
alpine:~# rc-update add smartdns boot
 * rc-update: smartdns already installed in runlevel `boot'; skipping
alpine:~# rc-update add smartdns
 * rc-update: smartdns already installed in runlevel `default'; skipping
alpine:~# rc-status -a
Runlevel: default
 networking                                                                                                                                      [  started  ]
 AdGuardHome                                                                                                                         [  started 12:07:33 (0) ]
 crond                                                                                                                                           [  started  ]
 local                                                                                                                                           [  started  ]
Runlevel: boot
 bootmisc                                                                                                                                        [  started  ]
 syslog                                                                                                                                          [  started  ]
 networking                                                                                                                                      [  started  ]
Runlevel: nonetwork
Runlevel: sysinit
Runlevel: shutdown
 killprocs                                                                                                                                       [  stopped  ]
 savecache                                                                                                                                       [  stopped  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed/wanted
 localmount                                                                                                                                      [  started  ]
Dynamic Runlevel: manual
正常安装，但是无法添加开机自启
alpine:~# service smartdns start
start smartdns server success.

**Comment by chieve-bale** [comment]
> alpine:~# /etc/init.d/smartdns stop Stop smartdns server success. alpine:~# /etc/init.d/smartdns start start smartdns server failed. alpine:~# rc-update add smartdns boot
> 
> * rc-update: smartdns already installed in runlevel `boot'; skipping
>   alpine:~# rc-update add smartdns
> * rc-update: smartdns already installed in runlevel `default'; skipping
>   alpine:~# rc-status -a
>   Runlevel: default
>   networking                                                                                                                                      [  started  ]
>   AdGuardHome                                                                                                                         [  started 12:07:33 (0) ]
>   crond                                                                                                                                           [  started  ]
>   local                                                                                                                                           [  started  ]
>   Runlevel: boot
>   bootmisc                                                                                                                                        [  started  ]
>   syslog                                                                                                                                          [  started  ]
>   networking                                                                                                                                      [  started  ]
>   Runlevel: nonetwork
>   Runlevel: sysinit
>   Runlevel: shutdown
>   killprocs                                                                                                                                       [  stopped  ]
>   savecache                                                                                                                                       [  stopped  ]
>   Dynamic Runlevel: hotplugged
>   Dynamic Runlevel: needed/wanted
>   localmount                                                                                                                                      [  started  ]
>   Dynamic Runlevel: manual
>   正常安装，但是无法添加开机自启
>   alpine:~# service smartdns start
>   start smartdns server success.

不知道为什么，重启了无数次然后就正常了
