### ISSUE TITLE
希望支持geosite

### ISSUE THREAD

**Issue by Bitcion** [pymumu/smartdns#1339]
为了实现ipv6与翻墙共存，需要屏蔽被墙域名的ipv6请求（否则有概率返回页面无法访问）
已经用了gfwlist文件，但感觉还是不全。现在很多都会有geosite文件，只要能支持geosite格式就好

**Comment by lintaozi** [comment]
重复 [#1274](https://github.com/pymumu/smartdns/issues/1274) #1316
