### ISSUE TITLE
套娃架构下完全相同的dns请求同时到达smartdns时可能存在问题-应大佬要求单独开issue

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1340]
关联issue：
#1337 

**问题现象**  
上游是同一个Adguard Home，所以从2个mosdns发到smartdnsdns的完全相同的dns请求几乎是同时到达smartdns的，2个mosdns都会有错误日志，把其中1个mosdns去掉，保留的mosdns就完全不会出现错误日志，关于此错误日志，mosdns的FAQ里面解释为上游dns不可用：
https://github.com/IrineSistiana/mosdns/issues/98

![image](https://user-images.githubusercontent.com/10081071/226240355-98a73ef9-0977-4acc-a045-6bf71ff4c436.png)

**运行环境**
1. 固件型号  
koolshare 2.37 内核5.4.108
2. 运营商  
济南联通 

4. smartdns来源以及版
https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.7

5. 涉及的配置(注意去除个人相关信息)

[smartdns_config.txt](https://github.com/pymumu/smartdns/files/11013457/smartdns_config.txt)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

[smartdns1.log](https://github.com/pymumu/smartdns/files/11013463/smartdns1.log)
[smartdns3.log](https://github.com/pymumu/smartdns/files/11013465/smartdns3.log)
[主路由mosdns log.txt](https://github.com/pymumu/smartdns/files/11013466/mosdns.log.txt)
[mosdns V5.txt](https://github.com/pymumu/smartdns/files/11013467/mosdns.V5.txt)
[smartdns0.log](https://github.com/pymumu/smartdns/files/11013468/smartdns0.log)

**Comment by pymumu** [comment]
[2023-03-20 10:34:17,670][ INFO][     dns_server.c:5228] query server api.miwifi.com from 10.10.10.100, qtype: 28
[2023-03-20 10:34:17,670][DEBUG][     dns_client.c:566 ] send query to group domestic
[2023-03-20 10:34:17,670][DEBUG][     dns_client.c:3306] send query to server 10.10.10.100
[2023-03-20 10:34:17,670][DEBUG][     dns_client.c:3306] send query to server 223.5.5.5
[2023-03-20 10:34:17,670][DEBUG][     dns_client.c:3306] send query to server 202.102.128.68

你这个环回查询了，10.10.10.100查询smartdns，smartdns再到10.10.10.100查询？

**Comment by pymumu** [comment]
最新代码改了一个地方，看看有没有用。

**Comment by yyysuo** [comment]
> 最新代码改了一个地方，看看有没有用。

不会编译，等PikuZheng的自动编译出来我试一下。

**Comment by yyysuo** [comment]
> 最新代码改了一个地方，看看有没有用。

感谢大佬，问题已经解决
https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.14-OpenWrt

**Comment by yyysuo** [comment]
> hhh，你什么网络环境要这么套娃😂

普通的联通家宽，搞dns就是玩啊，本来就完全没必要折腾dns，实际架构要复杂得多，我都懒得更新架构图了，本来用方案2，然后把方案1dnsmasq换成mosdns v5，两个方案并行了。
![image](https://user-images.githubusercontent.com/10081071/226407327-bc435ca5-9a11-4210-af30-5668f2d5f292.png)



再总结一下我现在在用dns方案的优点，

1：运行几天之后，所有的dns查询，响应时间都在1ms以下，可以说在dns查询上，基本不消耗时间。
2：缓存在路由重启后不消失（借用smartdns的永久缓存功能）。
3：封禁网站方便，直接在Adguard Home日志界面点拦截按钮就行。
4：Adguard Home的日志界面非常漂亮实用，可以清晰的看到局域网内所有设备的dns查询记录及统计，还可以按国内国外分别统计（多个adgh）
5：mosdns可以做到让国外域名有ipv4地址的情况下，不返回ipv6地址，如果网站只有ipv6地址，则返回ipv6地址。
6：mosdns按geosite分流，解决某些科学插件dns只有gfwlist分流的尴尬。
7：可以只开启国内域名的edns，国内域名针对cdn进行优化（国外Adguard Home启用edns，国外域名不用启用edns，谷歌dns自带edns）。

**Comment by yyysuo** [comment]
> hhh，你什么网络环境要这么套娃😂

对了，还有一个优点，就是排查问题超级方便。
