### ISSUE TITLE
可以把SMARTDNS丢内存/tmp跑不

### ISSUE THREAD

**Issue by iamyangyiok** [pymumu/smartdns#1344]
可以把SMARTDNS丢内存/tmp跑不，我看进程记录 SMARTDNS反复执行读取比如多，在想能不能把主程序丢内存执行，DB文件也丢内存中这样运行速度是不是更快些，后期可以设一个重启时保存，不保存运行记录也行，开机重新载入配置，可以不。

**Comment by iamyangyiok** [comment]
后期能加入一个内存模式也不错。

**Comment by yyysuo** [comment]
有啥意义，本来不就是在内存里面跑的吗？

**Comment by PikuZheng** [comment]
没有日志读写就是纯内存了

**Comment by pymumu** [comment]
log-num 0
关闭日志

**Comment by iamyangyiok** [comment]
> 

感谢

**Comment by iamyangyiok** [comment]
> 没有日志读写就是纯内存了

感谢

**Comment by abolast** [comment]
可以，我就是把smartdns-arm丢内存里跑的

**Comment by iamyangyiok** [comment]
> 可以，我就是把smartdns-arm丢内存里跑的

你的思路是什么样的 参考下
