### ISSUE TITLE
请问大佬如何实现自动设置缓存？

### ISSUE THREAD

**Issue by zmjjack** [pymumu/smartdns#1345]
最新代码增加自动设置缓存功能，但是要怎么设置才能实现？

**运行环境**
1. 固件型号  
OpenWrt SNAPSHOT r22346-e026a65af1 / LuCI Master git-23.074.82619-6ad6a24
2.smartdns来源以及版本
smartdnsv41.0.15

**Comment by pymumu** [comment]
不用管，把cache-size配置参数注释掉。

**Comment by zmjjack** [comment]
> 不用管，把cache-size配置参数注释掉。

luci界面也要把缓存数值删掉吗

**Comment by pymumu** [comment]
luci cache-size留空就可以

**Comment by zmjjack** [comment]
> luci cache-size留空就可以

收到。谢谢
