### ISSUE TITLE
与v2ray冲突

### ISSUE THREAD

**Issue by cyouhi** [pymumu/smartdns#135]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
PandoraBox 19.02 2019-02-01-git-93f2639a7 / LuCI Master (git-19.026.77036-498ca21)
2. 运营商  
电信

出现问题：
在同一台路由下安装V2RAY和SMARTDNS同时开启后，SMARTDNS不管是作为DNSMASQ的上游还是重定向都会导致V2RAY对谷歌全家桶代理失败，SMARTDNS能正确解析出无污染的IP，但就是不能访问，在V2RAY的访问日志里查看发现本地主机并没有与V2RAY通信，而作为旁路进行使用就完全正常，

**Comment by pymumu** [comment]
不清楚v2ray的使用方法，没用过。
smartdns只能解析IP地址，没有其他功能。
如果是类似proxy等软件的话，可能要浏览器中配置对应的代理服务。
或配合iptable，ipset来支持。

**Comment by rufengsuixing** [comment]
v2ray 开启域名嗅探

**Comment by pymumu** [comment]
可能用v2ray的时候走了v2ray提供的DNS服务了。

**Comment by cyouhi** [comment]
回答3楼的，挂在路由上的没看到有那个功能
回答mumu，测试了一下应该是开启v2ray时候app会用8.8.8.8走代理先解析www.google.com得到正确IP后会把IP加入到ipset gfwlist列表中，然而用旁路或者设置成dnsmasq上游非53端口后就正常了
