### ISSUE TITLE
多个上游查询，可以设置成非并发查询么

### ISSUE THREAD

**Issue by pmkol** [pymumu/smartdns#1350]
看了下文档，貌似多个上游时，是会并发查询的，是否有相关配置可以设置成先后查询

例如我将2个上游设置为
```
server 8.8.8.8
server 8.8.4.4
```
是否可以实现优先其中一个DNS查询，当超时后再去查询另外一个DNS？

**Comment by PikuZheng** [comment]
没理解这么做的目的，等一个超时了再去查另一个，岂不是大大增加了延迟？

**Comment by GuiDeJuShi** [comment]
> 没理解这么做的目的，等一个超时了再去查另一个，岂不是大大增加了延迟？

其实这和我提出的一个需求有点联系——不同服务商的DNS自然是并发查询，这没得说，也是SMARTDNS的价值所在；但是，同一服务商的几个首选和备用DNS地址，如果能事先测速、优选各自最快的地址，然后进行并发查询，岂不是查询速度更快了。
参考：https://github.com/pymumu/smartdns/issues/1236#issuecomment-1465115988

**Comment by PikuZheng** [comment]
如果将上游配置为域名，在程序启动时是会测速的。可以参考 bootstrap-dns 配置（41.0.3新增功能）。
连接上游超时后，会强制断开重连（41rc3.3新增功能）

**Comment by PikuZheng** [comment]
单就阿里和腾讯来讲，我是完全弃用阿里的，因为我觉得它的查询结果不可靠。。。尤其我严重依赖ddns。
单就腾讯的六个ip来讲，我只取其中两个，是指定了ip并发用的。。。到现在没觉得有什么不妥，也就是流量双倍了，不过（100m家宽）可以接受。
