### ISSUE TITLE
不同smartdns的缓存是否可以移植？

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1351]
**需求应用场景**
追加一个2个问题：
问题1：
smartdns开了2个端口 8055国内组和5555国外组，这2个组的缓存是否是独立的呢？比如某个域名错误的进入了8055国内组，配置正确后域名进入5555国外组，应该不会受到8055组缓存的影响吧？

问题2：
比如问题1中smartdns是A，如果把A产生的缓存文件配置到smartdns B，这个B开的端口有3个，且端口号或者组名与A不同，那么缓存文件是否能够载入和生效呢？

原问题：
esxi下把主路由copy出来一份，所以2个虚拟机是完全一致的配置，包括smartdns版本，但是我在关闭smartdns后，把虚拟机A生成的smartdns.cache复制到虚拟机B，第1次启动smartdns后，缓存文件没变，不确定是否载入，重启smartdns后缓存就变成几十K大小了，这表明可能载入是不成功的。可否允许缓存移植，是否有什么限制，可以去掉吗？

**Comment by PikuZheng** [comment]
同版本是可以的。
以下测试过程：
A 机
```
root@OpenWrt:~# /etc/init.d/smartdns stop
root@OpenWrt:~# tail -n 10 /var/log/smartdns.log
[2023-03-28 08:47:22,337][ INFO][       smartdns.c:529 ] smartdns exit...
[2023-03-28 08:47:22,338][DEBUG][     dns_client.c:1188] server 94.140.14.141 closed.
[2023-03-28 08:47:22,338][DEBUG][     dns_client.c:1188] server 162.14.21.178 closed.
[2023-03-28 08:47:22,338][DEBUG][     dns_client.c:1188] server 120.53.80.136 closed.
[2023-03-28 08:47:22,338][DEBUG][     dns_client.c:1188] server 120.53.53.53 closed.
[2023-03-28 08:47:22,338][DEBUG][     dns_client.c:1188] server 1.12.12.12 closed.
[2023-03-28 08:47:22,338][DEBUG][     dns_client.c:1188] server 45.32.229.227 closed.
[2023-03-28 08:47:22,339][DEBUG][     dns_client.c:1188] server 45.159.48.165 closed.
[2023-03-28 08:47:22,341][DEBUG][      dns_cache.c:863 ] write cache file /etc/smartdns/smartdns.cache
[2023-03-28 08:47:22,342][DEBUG][      dns_cache.c:898 ] wrote total 326 records.
root@OpenWrt:~# ls -l /etc/smartdns/smartdns.cache
-rw-r--r--    1 root     root        159193 Mar 28 08:47 /etc/smartdns/smartdns.cache
```
将A的cache复制到B机
![image](https://user-images.githubusercontent.com/12579522/228099717-308e74f2-460a-4ec6-ab7c-9791f3073be7.png)
启动B机的smartdns，过一会儿停止
```
root@OpenWrt:~# /etc/init.d/smartdns start
root@OpenWrt:~# /etc/init.d/smartdns stop
root@OpenWrt:~# ls -l /etc/smartdns/smartdns.cache
-rw-r--r--    1 root     root        162781 Mar 28 08:59 /etc/smartdns/smartdns.cache
```
可见文件增长了

**Comment by pymumu** [comment]
目前文件校验比较严格，用的是源码文件的时间戳

**Comment by yyysuo** [comment]
/tmp/etc/smartdns/smartdns.conf内容：
server-name smartdns
prefetch-domain yes
serve-expired yes
cache-size 100000000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 1
log-size 64K
log-num 1
log-level error
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind [::]:6053 
bind-tcp [::]:6053 
bind [::]:5555  -no-speed-check -group foreign -no-dualstack-selection
bind-tcp [::]:5555  -no-speed-check -group foreign -no-dualstack-selection
server 202.102.128.68  -group domestic -exclude-default-group 
server-tls 223.5.5.5  -group domestic -exclude-default-group
server-tls 8.8.8.8  -group foreign -exclude-default-group
server-tls 1.1.1.1  -group foreign -exclude-default-group
server-tls 8.8.4.4  -group foreign -exclude-default-group
server-tls 1.12.12.12  
server 10.10.10.100:3053  -group domestic -exclude-default-group
server 10.10.10.100:1056  -group foreign -exclude-default-group
server 10.10.10.100:2053  
domain-set -name domain-forwarding-list -file /etc/smartdns/domain-forwarding.list
domain-rules /domain-set:domain-forwarding-list/ 
domain-set -name domain-block-list -file /etc/smartdns/domain-block.list
domain-rules /domain-set:domain-block-list/ --address #
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

custom.conf内容
bind :8055 -group domestic
bind-tcp :8055 -group domestic
serve-expired-ttl 259200000
serve-expired-prefetch-time 21600

[40.1.5](https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.15-OpenWrt)
缓存文件
[smartdns.zip](https://github.com/pymumu/smartdns/files/11085455/smartdns.zip)

导入过程：
关闭smartdns
root@OpenWrt:~# /etc/init.d/smartdns stop
通过winscp上传缓存文件到/etc/smartdns/smartdns.cache 

root@OpenWrt:~# /etc/init.d/smartdns start
等待1分钟
root@OpenWrt:~# /etc/init.d/smartdns stop

结果：缓存文件被覆盖，只剩下几十K的小文件。

**Comment by yyysuo** [comment]
哪些情况在缓存文件存在的情况下，缓存不会载入呢，其实只要载入了，保存的时候肯定没问题的吧。

**Comment by PikuZheng** [comment]
> 哪些情况在缓存文件存在的情况下，缓存不会载入呢

版本不同、架构不同、编译时间不同，就不会载入

**Comment by yyysuo** [comment]
> > 哪些情况在缓存文件存在的情况下，缓存不会载入呢
> 
> 版本不同、架构不同、编译时间不同，就不会载入

这些限制能去吗，毕竟这些缓存是会自动更新的，追新版本经常丢缓存，感觉挺难受。

**Comment by PikuZheng** [comment]
。。但是ip不是一成不变的啊，总要更新的

**Comment by PikuZheng** [comment]
的确有几个版本是不同的。。

**Comment by yyysuo** [comment]
> 的确有几个版本是不同的。。

那40.1.5及之后的结构是相同的么，判断一下如果结构相同，就允许载入，把编译时间之类的限制去掉行不行，感觉用编译时间限制好奇怪。

**Comment by pymumu** [comment]
没什么奇怪，就是省事，避免出问题导致进程crash，这样做100%没问题，也减少管理兼容问题的工作量。

另外，不是编译时间，是文件修改时间。

**Comment by pymumu** [comment]
并且cache是可重复生成的，没必要投入太多精力在兼容性处理上。

**Comment by PikuZheng** [comment]
> 另外，不是编译时间，是文件修改时间。

也就是说smartdns主程序文件修改时间戳一致就可以尝试读取是吧（版本是否匹配另说

**Comment by pymumu** [comment]
一般情况下dns_cache.c文件修改的话，有概率涉及的文件格式。

但这里有个问题是，文件修改时间，提交到代码库后，在copy文件的过程中，可能丢失原来的时间戳，就会导致即使同一个版本，也会重新加载。

**Comment by yyysuo** [comment]
> 其实，主要还是懒
> 
> 认为一直保留cache文件没有必要。

我觉得按照smartdns的设计，其实算是一个主动的dns小系统了，这个小系统，能够保持家庭网络环境内dns的新鲜度，能够后台主动更新常用域名，能够提供准确快速的ip，路由运行一段时间后，能够使dns查询速度维持在0.0x ms。重点是主动，预取功能很重要，缓存数据库的稳定也很重要，反正这个数据库是自我更新的。

**Comment by yyysuo** [comment]
> 简单改了一下代码，手工判断是否变更版本。

测试了一下 https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.22-OpenWrt
使用的是 https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v41.0.15 生成的缓存，上面的楼层里面上传过文件。

升级后重启smartdns，缓存文件还是被重置了。

**Comment by yyysuo** [comment]
> 其实，主要还是懒
> 
> 认为一直保留cache文件没有必要。

有幸和大佬有同一个毛病。

**Comment by pymumu** [comment]
用最新版本生成cache文件，最新版本cache和之前版本不兼容。

**Comment by yyysuo** [comment]
> 用最新版本生成cache文件，最新版本cache和之前版本不兼容。

我猜有可能是这样的，希望以后新版的cache都是相互兼容的。

**Comment by pymumu** [comment]
没精力弄这个，这个相当于数据格式转换，cache不是什么重要数据，不会为了这个搞太多修改。
现在这个修改方法已经避免不必要的不兼容，在格式不变化的情况下，是没有问题的。

**Comment by yyysuo** [comment]
> 没精力弄这个，这个相当于数据格式转换，cache不是什么重要数据，不会为了这个搞太多修改。 现在这个修改方法已经避免不必要的不兼容，在格式不变化的情况下，是没有问题的。

目前的逻辑是怎么样的呢？什么情况下缓存会被重置呢？

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/blob/582cdfb879067b3f3c8827edfb6efe54e2b7aaf9/src/dns_cache.c#L792

**Comment by yyysuo** [comment]
> https://github.com/pymumu/smartdns/blob/582cdfb879067b3f3c8827edfb6efe54e2b7aaf9/src/dns_cache.c#L792

大佬实在是太高看我了，看了一下这一块的代码，好像是如果缓存文件是有效的，只要cache_file.version没有变化就会载入对吧。

**Comment by yyysuo** [comment]
追加一个2个问题：
问题1：
smartdns开了2个端口 8055国内组和5555国外组，这2个组的缓存是否是独立的呢？比如某个域名错误的进入了8055国内组，配置正确后域名进入5555国外组，应该不会受到8055组缓存的影响吧？

问题2：
比如问题1中smartdns是A，如果把A产生的缓存文件配置到smartdns B，这个B开的端口有3个，且端口号或者组名与A不同，那么缓存文件是否能够载入和生效呢？

**Comment by lalasou** [comment]
还是觉着如果smartdns能支持外部数据库缓存更好
很多设备 比较小
