### ISSUE TITLE
windows nslookup显示服务器unknow

### ISSUE THREAD

**Issue by Peterzhangnoise** [pymumu/smartdns#1352]
**问题现象**  
在使用windows nslookup检查自定义域名解析时，服务器那里总显示unknow,查了下似乎是反向解析的问题。
smartdns怎么配置反向解析，或者说是否支持该功能
![image](https://user-images.githubusercontent.com/70377914/228121547-a0a1136b-7355-494d-8f9a-4f7e7619078a.png)

**运行环境**
1. 固件型号  
原版op 21.02.5

2. 运营商  
电信
3. smartdns来源以及版本
op 21.02.5官方源 opkg直装

**Comment by PikuZheng** [comment]
请升级至38.0.9或更高版本。

**Comment by zxlhhyccc** [comment]
我使用windows nslookup不加dns无法显示。。。

**Comment by PikuZheng** [comment]
> 我使用windows nslookup不加dns无法显示。。。

容器运行是没有的。如果服务端是openwrt，应该有

**Comment by Peterzhangnoise** [comment]
我升级到了最新，还是unknow

**Comment by Peterzhangnoise** [comment]
> ![image](https://user-images.githubusercontent.com/12579522/228191825-2d949c11-4997-4bea-9083-ffdb51e707d3.png) 请看一下 这个框框里是什么

填的是OpenWrt

**Comment by Peterzhangnoise** [comment]
> shell中执行下面命令看看：
> 
> ```shell
> uci -q set dhcp.@dnsmasq[0].rebind_protection=0
> uci -q set dhcp.@dnsmasq[0].domainneeded=0
> uci commit dhcp
> /etc/init.d/dnsmasq reload
> ```

一样的，我这其实是旁路由，我把旁路由的dhcp都关了

**Comment by Peterzhangnoise** [comment]
我自己又折腾了一会，因为我53端口是Adguard,我在adguard中添加了一个私人反向 DNS 服务器后，短时间内请求正常，快速请求两下ptr就找不到了，看不懂是哪里的问题了

![image](https://user-images.githubusercontent.com/70377914/228304041-1d396d22-8dc3-4d88-b6f7-a733a996897f.png)

**Comment by okfate** [comment]
在你的Adguard私人反向DNS服務器中加入127.0.0.1:【smartdns設置的國內端口號】，就可以解決你的問題了。
