### ISSUE TITLE
nftset没有重新添加

### ISSUE THREAD

**Issue by moondigi** [pymumu/smartdns#1353]
debian 11 kernel 5.10.0-20-amd64
smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build: Mar  4 2023 11:26:35)

```
domain-set -name gfwlist -file /smartdns/gfwlist.conf
domain-rules /domain-set:gfwlist/ -nameserver gfwlist -speed-check-mode none -address #6 -nftset #4:ip#smartdns#gfwlist
```

平时使用中有时候会重新载入nftables规则，载入的时候会将已有的nftset清除掉
查询dns的时候smartdns从cache里面快速返回记录，但是没有检查nftset里面这条记录有没有被清除

想让smartdns重新触发添加的话，需要删除cache文件并重新运行smartdns（又或者等过期？），在domain-rules后加-no-cache无效
感觉这种重新触发添加的方法动作太大而且损失了已有缓存，有什么办法能应对这种情况吗？

**Comment by pymumu** [comment]
可以在重启smartdns后，新来的请求，即使命中cache，也设置ipset，这样就没有问题了，也不会消耗太多性能。

**Comment by moondigi** [comment]
打算弃用ipset只用nftset，不知道能否加个检测nftset是否存在的功能，或者重启后将cache里nftset的记录清掉
