### ISSUE TITLE
OP 22.3 Luci界面不显示

### ISSUE THREAD

**Issue by iamyangyiok** [pymumu/smartdns#1355]
**问题现象**  
简要描述问题出现的现象
LEAN的OPENWRT 22.3版，下的SMARTDNS官网的41安装包，上传LUCI-SMARTDNS-COMPAT-ALL.IPK安装，提示Unknown package 'luci-app-smartdns'无法安装。用LUCI-SMARTDNS-ALL.IPK可以安装，但界面无法显示，CACHE 清理过也不行。

**Comment by iamyangyiok** [comment]
COMPAT的LUCI包反复下了几次都提示无法识别

**Comment by zxlhhyccc** [comment]
应该是缺少了rpcd的josn文件。。。。

**Comment by iamyangyiok** [comment]
> 应该装哪个依赖包

**Comment by iamyangyiok** [comment]
> 应该是缺少了rpcd的josn文件。。。。

应该是装哪个依赖

**Comment by iamyangyiok** [comment]
> 应该是缺少了rpcd的josn文件。。。。

我把关于RPCD的都装了 有5个 还是不行 还是报COMPAT那个包 不识别

**Comment by PikuZheng** [comment]
lean只能用compat。提示unknown感觉像包下载不完整

**Comment by iamyangyiok** [comment]
> lean只能用compat。提示unknown感觉像包下载不完整

我下了几次 ，手机下 电脑上 ，我等下再试下，截图你，

**Comment by iamyangyiok** [comment]
> 完整的错误提示可以截图吗？下面应该还有别的错误信息
Unknown package 'luci-app-smartdns'
文件名 | 修改时间 | 属性 | 文件大小 | 移除 | 安装
-- | -- | -- | -- | -- | --

luci-app-smartdns.1.2023.01.02-1537.all-luci-compat-all.ipk | 2021-01-01 20:21:25 | rw-r--r-- | 12.4 kB |   |  
luci-app-smartdns.1.2023.03.04-1125.all-luci-compat-all.ipk | 2021-01-01 20:19:49 | rw-r--r-- | 13.8 kB

系统日志/
Fri Jan  1 20:19:52 2021 daemon.err uhttpd[1623]:  * pkg_hash_check_unresolved: cannot find dependency smartdns for luci-app-smartdns
Fri Jan  1 20:19:52 2021 daemon.err uhttpd[1623]:  * pkg_hash_check_unresolved: cannot find dependency luci-compat for luci-app-smartdns
Fri Jan  1 20:19:52 2021 daemon.err uhttpd[1623]:  * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-smartdns found, but incompatible with the architectures configured
Fri Jan  1 20:19:52 2021 daemon.err uhttpd[1623]:  * opkg_install_cmd: Cannot install package luci-app-smartdns.
Fri Jan  1 20:21:28 2021 daemon.err uhttpd[1623]: Collected errors:
Fri Jan  1 20:21:28 2021 daemon.err uhttpd[1623]:  * pkg_hash_check_unresolved: cannot find dependency smartdns for luci-app-smartdns
Fri Jan  1 20:21:28 2021 daemon.err uhttpd[1623]:  * pkg_hash_check_unresolved: cannot find dependency luci-compat for luci-app-smartdns
Fri Jan  1 20:21:28 2021 daemon.err uhttpd[1623]:  * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-smartdns found, but incompatible with the architectures configured
Fri Jan  1 20:21:28 2021 daemon.err uhttpd[1623]:  * opkg_install_cmd: Cannot install package luci-app-smartdns.

**Comment by iamyangyiok** [comment]
> 完整的错误提示可以截图吗？下面应该还有别的错误信息

更新下  我上面的有操作错，当时没装程序。我后来因为SMARTDNS主程序没装，报日志缺依赖，RK3588的CPU，我装的AARCH64-OPENWRT主程序包也报Unknown package ，装ARM程序包能装上，但COMPAT-LUCI还是报Unknown package
‘luci-app-smartdns'

**Comment by iamyangyiok** [comment]
> > 完整的错误提示可以截图吗？下面应该还有别的错误信息
> 
> 更新下 我刚上面的有操作错，没装主程报日志缺依赖，后来先装程序，RK3588的CPU，我装的AARCH64-OPENWRT主程序包也报Unknown package ，装ARM-OPENWRT主程序包能装上，但装COMPAT-LUCI还是报Unknown package ‘luci-app-smartdns'

系统日志：
Wed Mar 29 20:22:19 2023 daemon.err uhttpd[1660]: Collected errors:
Wed Mar 29 20:22:19 2023 daemon.err uhttpd[1660]:  * pkg_hash_check_unresolved: cannot find dependency luci-compat for luci-app-smartdns
Wed Mar 29 20:22:19 2023 daemon.err uhttpd[1660]:  * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-smartdns found, but incompatible with the architectures configured
Wed Mar 29 20:22:19 2023 daemon.err uhttpd[1660]:  * opkg_install_cmd: Cannot install package luci-app-smartdns.

**Comment by zxlhhyccc** [comment]
> > 完整的错误提示可以截图吗？下面应该还有别的错误信息
> 
> 更新下 我刚上面的有操作错，没装主程报日志缺依赖，后来先装程序，RK3588的CPU，我装的AARCH64-OPENWRT主程序包也报Unknown package ，装ARM-OPENWRT主程序包能装上，但装COMPAT-LUCI还是报Unknown package ‘luci-app-smartdns'

你看一下有没有这个文件：/usr/share/rpcd/acl.d)/luci-app-smartdns.json，没有的话加上去即可！

**Comment by pymumu** [comment]
1.  没有安装smartdns的主程序。下载smartdns.ipk包安装。
2. 没有luci-compat包，两种可能，一，你的固件是18.x及之前版本。二。你没有安装luci-compat包。
    安装luci-compat包
    或者：安装这里面的包：https://github.com/pymumu/smartdns/issues/1302

**Comment by iamyangyiok** [comment]
> 1. 没有安装smartdns的主程序。下载smartdns.ipk包安装。
> 2. 没有luci-compat包，两种可能，一，你的固件是18.x及之前版本。二。你没有安装luci-compat包。
>    安装luci-compat包
>    或者：安装这里面的包：[openwrt5.4132内核安装提示缺少5.15内核xxx依赖，但使用貌似正常，请问需要升级5.15内核吗？ #1302](https://github.com/pymumu/smartdns/issues/1302)

是的 我后复现时 先没装主程序，但是先装AARHCH64的主程序也提示  Unknown package 'luci-smartdns'，并不是安装的LUCI。

**Comment by pymumu** [comment]
smartdns主程序安装包不会依赖luci，你可能弄错了文件；

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/install/openwrt/

**Comment by iamyangyiok** [comment]
> 
确实没有 ，我找的另个正常ARM路由的这文件复制进去的，也不显示，装LUCI-COMPAT还是报
Unknown package 'luci-app-smartdns'

> 

可能还真是内核的问题 我这个RK3588 目前只 有.5

> 1. 没有安装smartdns的主程序。下载smartdns.ipk包安装。
> 2. 没有luci-compat包，两种可能，一，你的固件是18.x及之前版本。二。你没有安装luci-compat包。
>    安装luci-compat包
>    或者：安装这里面的包：[openwrt5.4132内核安装提示缺少5.15内核xxx依赖，但使用貌似正常，请问需要升级5.15内核吗？ #1302](https://github.com/pymumu/smartdns/issues/1302)

我估计还真是可能 你说

> 1. 没有安装smartdns的主程序。下载smartdns.ipk包安装。
> 2. 没有luci-compat包，两种可能，一，你的固件是18.x及之前版本。二。你没有安装luci-compat包。
>    安装luci-compat包
>    或者：安装这里面的包：[openwrt5.4132内核安装提示缺少5.15内核xxx依赖，但使用貌似正常，请问需要升级5.15内核吗？ #1302](https://github.com/pymumu/smartdns/issues/1302)

可能还真是你说的这个问题 我那个rk3588 目前只有5.10的核心  5.14 都赶不上

**Comment by iamyangyiok** [comment]
> 1. 没有安装smartdns的主程序。下载smartdns.ipk包安装。
> 2. 没有luci-compat包，两种可能，一，你的固件是18.x及之前版本。二。你没有安装luci-compat包。
>    安装luci-compat包
>    或者：安装这里面的包：[openwrt5.4132内核安装提示缺少5.15内核xxx依赖，但使用貌似正常，请问需要升级5.15内核吗？ #1302](https://github.com/pymumu/smartdns/issues/1302)

装了你说的那个版本就出来了，感谢！另有个问题请教下 像RK3399 RK3588 到底是装AARCH64还是ARM的版本呢

**Comment by pymumu** [comment]
uname -a看

**Comment by iamyangyiok** [comment]
> uname -a看

-m 看了 是arrch64 ,现在LUCI显示了，但又有个新问题 ：） 就是LUCI  好像不可控，点开就显示SMARTDNS 运行状态，但停用 还是显示运行状态。

**Comment by jxph1123** [comment]
Lean的你自己编译的吗,我也是用的lean的源码,把smartdns自己编译进去,没有任何问题啊.

**Comment by iamyangyiok** [comment]
> Lean的你自己编译的吗,我也是用的lean的源码,把smartdns自己编译进去,没有任何问题啊.

不是 的，我3588没有源，

**Comment by iamyangyiok** [comment]
只能来了 等老大问问 我现在就急这个  没法用SMARTDNS
