### ISSUE TITLE
开启Full cone NAT会导致smartdns失效

### ISSUE THREAD

**Issue by ilxp** [pymumu/smartdns#1358]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

如题，关闭Full cone NAT  则samrtdns有效。以前的版本没有此问题。

**Comment by iamyangyiok** [comment]
说清什么样无效了，是程序不能启动 还是DNS变了

**Comment by PikuZheng** [comment]
可能和端口绑定有关，试试不勾选绑定到设备

**Comment by ilxp** [comment]
没有勾选。就是nslookup  www.baidu.com   返回是2个ip。

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/faq/#smartdnsip
