### ISSUE TITLE
最新代码在lede的openwrt上crash

### ISSUE THREAD

**Issue by GreatMichaelLee** [pymumu/smartdns#1359]
**问题现象**  
简要描述问题出现的现象 : 最新代码在lede openwrt启动时crash起不来，之前无此现象。（配置未作任何变化）

**运行环境**
1. x86平台+LEDE仓库最新代码+本仓库最新代码（https://github.com/pymumu/smartdns/commit/582cdfb879067b3f3c8827edfb6efe54e2b7aaf9)

2. 运营商  
电信+移动
3. smartdns来源以及版本
本仓库截至发本贴时的最新commit
4. 涉及的配置(注意去除个人相关信息)
有需要再贴

**重现步骤**
1. 上游DNS配置。  
双服务器，国内+国外，均采用DoH,国内用阿里腾讯DoH,国外Cloudflare DoH
2. 访问的域名。  
无，LEDE启动smartdns init的时候，系统log既提示smartdns crash 6次后退出了，但手工restart后又能起来

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**openwrt log:**
Fri Mar 31 14:56:36 2023 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 1 seconds since last crash

**smartdns core dump文件：**
[smartdns_coredump.zip](https://github.com/pymumu/smartdns/files/11119784/smartdns_coredump.zip)

**配套的bin文件：**
[smartdns.zip](https://github.com/pymumu/smartdns/files/11119865/smartdns.zip)

**smartdns debug level log:**
[smartdns_debug_log.txt](https://github.com/pymumu/smartdns/files/11119787/smartdns_debug_log.txt)

**Comment by PikuZheng** [comment]
请试试以下操作
1. 停止smartdns
2. 删除缓存文件（默认在/etc/smartdns/smartdns.cache）
3. 启动smartdns

**Comment by pymumu** [comment]
try lastest code.

**Comment by GreatMichaelLee** [comment]
> 请试试以下操作
> 
> 1. 停止smartdns
> 2. 删除缓存文件（默认在/etc/smartdns/smartdns.cache）
> 3. 启动smartdns

没有这个文件....

**Comment by GreatMichaelLee** [comment]
> try lastest code.

好的，我试试，晚点反馈

**Comment by GreatMichaelLee** [comment]
> > try lastest code.
> 
> 好的，我试试，晚点反馈

测了一天，重启了好几次，没发现再crash了，应该是解决了。
