### ISSUE TITLE
是否支持自动代理分流

### ISSUE THREAD

**Issue by MvsCode** [pymumu/smartdns#136]
**需求应用场景**
请描述需求应用的场景和方式。
应用于老毛子路由器中，目前使用重定向DNS和dnsproxy解析科学上网，问题有两个：1.每次ss重启，或者宽带重连，DNS必定被污染需要ipconfig/flushdns才能正常；2.打开国内网站有时会失败，需要重新刷新网页
**建议的方案**
实现上述场景建议的方案。
各DNS的快慢比较在毫秒之差，不是太大延迟，体验就不太差别
主要希望拥有的功能：
1. 解决DNS污染问题，开了科学上网，DNS真的很容易被污染
2.实现类似Auto-proxy-pac的模式，很多时候在路由器上不到的域名，在手机开代理就能上，不是特意在添加代理域名，希望这种DNS模式可以自动识别需要代理的域名或者ip，自动识别国内直连域名或者ip，我看到在去年的issue中也提到这个需求，现在已经支持了吗
**设备信息**
1. 设备信息（CPU，厂家）  
 MTK MT6721A 斐讯k2p
2. 固件信息
Padavan
毕竟路由器性能内存有限，不是像软路由，开发版pi，希望如果可以，尽量把运行内存降到最低，谢谢

**Comment by pymumu** [comment]
proxy功能目前暂时不会考虑加入，原因不好描述。
