### ISSUE TITLE
我开了广告过滤，对smartdns解析性能有没有影响

### ISSUE THREAD

**Issue by jxph1123** [pymumu/smartdns#1360]
如题，有点好奇，多了接近7万条过滤规则，会对smartdns造成压力吗？会有多大影响，我之前是直接用的dnsfilter，规则是dnsmasq处理的，我在想用smartdns过滤会不会比dnsmasq高点

**Comment by PikuZheng** [comment]
根据我的使用经验，处理速度和cpu速度有关。对于家用和小规模商用环境，性能下降水平可以接受。参考#1337

**Comment by jxph1123** [comment]
> dnsmasq

因为之前用的dnsmasq，也要处理7万条，我就感觉smartdns应该效率比dnsmasq高点
