### ISSUE TITLE
关于配置文件中的resolv-file疑问

### ISSUE THREAD

**Issue by sdddhhll** [pymumu/smartdns#1364]
大神您好：
我发现配置文件中有个配置叫做：resolv-file，但是我没有找到任何关于这个配置项的说明，我发现这个文件中存放的是运营商的DNS。我做了一下测试：
1.启动smartdns然后删除所有的上游服务器，我发现仍然能够正确的解析域名地址。
2.删除所有的上游服务器，然后将resolv-file=/tmp/resolv.conf.d/resolv.conf.auto   resolv.conf.auto文件中的内容清空，然后就无法解析域名了。
3.清空resolv.conf.auto文件内容，smartdns中增加一个上游服务器并启用，就可以正确解析域名了。
我想问大神，resolv-file的具体工作原理。
A.如果我在smartDNS中配置并启用了上游服务器，是否还会向这个文件中的DNS发送域名查询请求？
B.如果不会的话是不是他是用来存放备用DNS的，也就是当smartdns中上有服务器都禁用的时候，为了保障用户正常解析域名，就启用这个文件中的DNS服务器?
C.如果会的话是不是就意味着所有的域名查询都会走这个文件中的DNS？

**Comment by PikuZheng** [comment]
resolv.conf 是指这个文件自身所在的计算机需要dns解析时去找哪个dns服务器，相当于windows网卡属性中的“使用下面的dns服务器地址”
![image](https://user-images.githubusercontent.com/12579522/229728734-e418956b-e429-4100-bc22-0dc21c99a74c.png)

这个文件自身和smartdns没什么关系，建议去了解一下linux网络方面的知识。

但是。如果smartdns配置了域名的上游服务器，在smartdns启动时必须先将上游的域名解析为ip，会使用本机配置的dns服务器，即resolv.conf。现在有bootstrap-dns设置了，可以不走系统dns

**Comment by PikuZheng** [comment]
大致翻了一下代码没发现这个参数有什么用

**Comment by sdddhhll** [comment]
> 大致翻了一下代码没发现这个参数有什么用

好的  谢谢大神回复，我也翻了一下源代码，也没有发现具体用处。 最后 祝你们工作和生活愉快。

**Comment by pymumu** [comment]
smartdns在未配置任何dns服务器时，会使用/etc/resolv.conf中的dns服务器，用于支持正常解析。

这个参数是设置这个文件的路径，openwrt和linux路径不同，路径由脚本自动配置。

这个参数用户基本不用关注，没必要修改。当然也就没写帮助

**Comment by sdddhhll** [comment]
> smartdns在未配置任何dns服务器时，会使用/etc/resolv.conf中的dns服务器，用于支持正常解析。
> 
> 这个参数是设置这个文件的路径，openwrt和linux路径不同，路径由脚本自动配置。
> 
> 这个参数用户基本不用关注，没必要修改。当然也就没写帮助

谢谢，我明白了，您回复的和我测试的结果现象一致。
