### ISSUE TITLE
关于 -exclude-default-group的参数不知道我的理解是否有误？

### ISSUE THREAD

**Issue by liangxyz** [pymumu/smartdns#1368]
简单写一下我的配置如下所示：
bind [::]:5353
bind [::]:5354 -group out -no-speed-check
server 222.172.200.68
server-https https://xxx.com/xxx -group out
server-tls 8.8.4.4 -group out -exclude-default-group

对于-exclude-default-group这个参数，我目前的理解是，如果加了该参数，就只响应5354端口传进来group out组的查询，如果没加该参数，会同时响应5353和5354端口传进来的默认组和out组查询？
比如server-https https://xxx.com/xxx -group out 该服务器是不是会同时响应5353和5354端口的查询？
而server-tls 8.8.4.4 -group out -exclude-default-group只会响应5354端口的查询？

**Comment by pymumu** [comment]
是这样的。

**Comment by PikuZheng** [comment]
> 对于-exclude-default-group这个参数，我目前的理解是，如果加了该参数，就只响应5354端口传进来group out组的查询，如果没加该参数，会同时响应5353和5354端口传进来的默认组和out组查询？

应该是这样的，但总觉得哪里不对

>比如server-https https://xxx.com/xxx -group out 该服务器是不是会同时响应5353和5354端口的查询？

会

>而server-tls 8.8.4.4 -group out -exclude-default-group只会响应5354端口的查询？

对

**Comment by liangxyz** [comment]
谢谢各位解答，懂了，感谢你们分享如此好用的程序，祝好
