### ISSUE TITLE
replay raw packet to client failed.

### ISSUE THREAD

**Issue by qianchen36** [pymumu/smartdns#1369]
**问题现象**  
访问第二DNS时，概率出现replay raw packet to client failed.刷屏，处理器占用走高且内存溢出

**运行环境**
1. 固件型号  
[stupidloud/nanopi-openwrt](https://github.com/stupidloud/nanopi-openwrt) 2022-12-31
（编译自immortalwrt、lede）
2. 运营商 
教育网/中国电信
3. smartdns来源以及版本 
固件自带软件源1.2022.38-1
4. 涉及的配置(注意去除个人相关信息)
passwall设置远程DNS为SmartDNS第二DNS服务器所在端口
TCP服务器启用
服务器组passwall_proxy
端口6553
跳过测速、Nameserver、address、ipset

**重现步骤**
1. 上游DNS配置。  
passwall_proxy服务器组下只有两个
均为DoT访问1.1.1.1和8.8.8.8的853端口，passwall设置这两个ip走代理
额外的服务器参数-exclude-default-group
2. 访问的域名。  
任意

**信息收集**  
暂无，日志一直刷replay raw packet to client failed.

**Comment by PikuZheng** [comment]
这两个不同的问题。日志那个问题请升级到39.0.2或更高版本。内存耗尽一般是由于查询循环，如果passwall将dns查询送给smartdns，又劫持了smartdns向上游查询，则发生此问题。

**Comment by qianchen36** [comment]
> 这两个不同的问题。日志那个问题请升级到39.0.2或更高版本。内存耗尽一般是由于查询循环，如果passwall将dns查询送给smartdns，又劫持了smartdns向上游查询，则发生此问题。

刚刚升级到41，还在观察，暂时没出问题
 
我的理解：
1. Passwall匹配到是需要代理的域名，把DNS解析发送给SmartDNS（不需要代理的走主DNS，响应快，需要代理的走第二DNS，防污染）
2. SmartDNS以DoT方式直接向指定IP的上游DNS查询，因为直接给定IP所以并不需要再解析上游DNS的域名
3. SmartDNS向上游查询的请求进入Passwall，Passwall匹配是需要代理的IP，不需要解析，直接把请求发给Xray节点上
为什么会出现循环呢......
Passwall那边给的示例仅提到过如果SmartDNS不忽略Nameserver规则的话会造成循环

**Comment by qianchen36** [comment]
Passwall那边现在正在做新版本SmartDNS的适配
