### ISSUE TITLE
从Release 22升级到Release 23，出现网页无法打开，需要重启防火墙。

### ISSUE THREAD

**Issue by btyufe** [pymumu/smartdns#137]
**问题现象**  
从Release 22升级到Release 23后，出现网页无法打开，需要重启一下openwrt防火墙

**运行环境**
1. 固件型号  
OpenWrt R9.3.7 By Lean / LuCI Master (git-18.296.11678-2bbc1e3) 内核4.9.161
2. 运营商  
电信
**重现步骤**
Release 22，使用正常。
设置为：
1.smartdns设置
![1](https://user-images.githubusercontent.com/44253577/55531511-33e64180-56dd-11e9-90c1-04cdef249f8b.PNG)
2.防火墙自定义规则会出现2条53端口的规则
![2](https://user-images.githubusercontent.com/44253577/55531521-48c2d500-56dd-11e9-9e89-31420495bb9c.PNG)
3.DHCP/DNS中的转发设置
![3](https://user-images.githubusercontent.com/44253577/55531534-5e37ff00-56dd-11e9-93ab-203622b8e49f.PNG)
4.LAN口设置
![lan1](https://user-images.githubusercontent.com/44253577/55531546-6f810b80-56dd-11e9-8444-651e3a564105.PNG)
5.LAN口的DHCP设置
![lan-dhcp](https://user-images.githubusercontent.com/44253577/55531554-7871dd00-56dd-11e9-854d-37ef977557ac.PNG)
6.WAN口设置
![wan](https://user-images.githubusercontent.com/44253577/55531565-8293db80-56dd-11e9-9b6c-437f5dd28b10.PNG)

昨天升级为Release 23，设置没有变动。当时上网一切都正常
今天上午出现电脑和手机网页打不开，在OPENWRT上用网络诊断一切都正常。电脑用nslookup也返回正常的IP地址，就是打不开网页
后来发现：
1.如果在openwrt重启一下防火墙，网页可以正常打开了。
2.把openwrt重启，网页又打不开了，重启防火墙，网页又可以打开。
3.最后没办法，把smartdns的“重定向”和DHCP/DNS中的DNS转发先关掉再重新设置，把防火墙自定义规则那2条删除又加上去。目前暂时正常了。

另外问个问题：53端口和6053端口的转发如果同时开启会有冲突吗？

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传co
[smartdns.log](https://github.com/pymumu/smartdns/files/3041763/smartdns.log)
redump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
smartdns不会去修改自定义配置，那个自定义配置你要检查一下
你选择的工作模式是重定向，smartdns会设置iptable规则，将53重定向到6053，但不是去修改配置，而是iptable命令设置的

**Comment by pymumu** [comment]
wan口dns最好用运营商的

**Comment by btyufe** [comment]
LAN，WAN的DNS设置是参考koolshare的教程来设置的，这些设置在前一个版本中使用正常。昨天晚上升级到23版本后，今天上午出现问题的。
设置成重定向工作模式时，DNS转发设置成127.0.0.1#6053，其实是多余的，对吗？

**Comment by pymumu** [comment]
relase 23相比release22 只增加https协议，并没有其他额外修改。

你的问题原因就是第2个，配置里面有iptable，这个不是smartdns设置的。

**Comment by btyufe** [comment]
感谢pymumu大大。
