### ISSUE TITLE
请问serve-expired-prefetch-time是否可以设为0（到期立即预读），以及这样设置后结果如何返回

### ISSUE THREAD

**Issue by GuiDeJuShi** [pymumu/smartdns#1370]
请问如果打开serve-expired并添加serve-expired-prefetch-time 0的设置，缓存中的结果是否可在TTL到期的瞬间立刻预读，然后再到期再预读，一直循环下去？
然后请问在这种情况下，客户端是否还会收到TTL=3的老结果？也就是说，这样设置后，是否客户端每次查询都能得到预读后的未到期结果，而不是先得到TTL=3的过期结果，然后服务器再预读，下次查询才得到新结果？

**Comment by PikuZheng** [comment]
首先不是所有缓存都会预读。其次预读是在ttl超时前而不是超时后。
如果把缓存改的足够大并且开启预读，理论上所有域名都有ttl不超时的缓存。但是这将显著增加网络流量，可能会有不良效果。
这块我建议默认设置不要动。
