### ISSUE TITLE
有一个复杂环境使用遭遇的问题，已经好几年了，今天提出来希望可以得到解决

### ISSUE THREAD

**Issue by tobycroft** [pymumu/smartdns#1371]
**需求应用场景**
请描述需求应用的场景和方式。

我使用smartdns是因为smartdns有一个我觉得非常好的功能，就是测速，这个国内环境使用其实是没有什么问题的，随着ipv6的上线，现在很多网站的ipv6的响应速度都比原来快了很多，所以现在纯国内上网，使用ipv6体验有的时候会更好

那么对于国际上网而言，例如google提供的服务器地址，虽然会根据你所在的地方进行ping，但是在开启了ipv6功能后，测速变得很尴尬，举例子，比如我在开启ipv6的情况下，并且将ipv6优选阈值开的比较正常，就是如果ipv4比较快就实用ipv4，然后测速只开80和443

这个时候，有一定的概率，解析youtube的“流媒体地址”，那个网址，会优选到ipv6，而且使用时间长一点后，就会一直跳ipv6，但是因为你懂的原因，这个ipv6不仅慢，而且大多数是无法联通的，所以不知道为什么测速会测出这个来

然后如果将测速模式里面加入“ping”这个功能，那就更乱套了，甚至可能google本身也会解析成ipv6的地址，这样就无法使用了。

因为我的服务器的地址提供，一部分是来自本地的dns，还有一部分是来自vps自身的dns解析，所以这里面就会涉及解析出ipv6的情况

我目前是将force-aaaa-soa打开的，完全不使用ipv6，但是这也不是个办法，所以我还是希望未来可以解决这个问题的

**建议的方案**
实现上述场景建议的方案。

所以我希望可以在smartdns中加入几个功能

1.服务器的配置选项里面，可以加入force-aaaa，将force-aaaa-soa的配置下放到每一个server，有些server我希望他可以返回解析的ipv6地址，但是有些地址我不允许它返回ipv6
2.因为Ipv6地址众多，虽然可以使用黑名单机制，但是毕竟连原vps都在回传ipv6，而且不同的网站不固定，设定黑名单难度就很大，之前试过，甚至会影响到正常的解析，最后就放弃了
3.独立测速功能，像是国内的server dnsip，就使用ping和tcp检测，国外的server-tcp dnsip ，可以单独配置只使用tcp检测，降低故障率

**设备信息**
1. 设备信息（CPU，厂家）  
x86 E5

3. 固件信息
无

**Comment by tobycroft** [comment]
其实前几年使用的时候，还可以使用dual-stack来稍微抑制一下，如果出现了就重启下smartdns就好，但是今年以来这种情况越来越频繁了，所以最后实在没办法开了force-aaaa-soa

**Comment by tobycroft** [comment]
@pymumu

**Comment by PikuZheng** [comment]
为什么不针对谷歌系所有域名禁用ipv6（也就二百来个

**Comment by onion83** [comment]
其实可以用 domain-rules 解决，鉴于因为很多用户都是使用 iptables redir 来做境外流量转发，tcp 测速反而会不准确且**增加暴露风险**，这种场景干脆就不要测了。另外全局建议配置 max-reply-ip-num 3 以上避免单ip卡死，很多网站还是使用多条 A 记录做负载均衡的。

> domain-rules /youtube.com/ -nameserver free -speed-check-mode none -address #6

当然还有一种更灵活的做法是将 bind[-tcp|tls] 中的 force-aaaa-soa 下放到 server[-tcp/tls/https] 中，语法

> server 8.8.4.4 -group free -exclude-default-group --force-aaaa-soa
> server 1.0.0.1 -group free -exclude-default-group --force-aaaa-soa
> server 208.67.222.222 -group free -exclude-default-group --force-aaaa-soa

**Comment by tobycroft** [comment]
> 为什么不针对谷歌系所有域名禁用ipv6（也就二百来个

实际使用中会发现不仅仅是谷歌的，FB那些的也会跳，twitch那些也会跳，一个一个找一个个加就太累了，其实如果使用测速的话，像百度这样的，他其实会导致的结果是国外的服务器测速测试结果比国内的还快，比如我这边正常是解析14开头的百度地址，但是smartdns会直接使用163.开头的国外的地址，这样就让速度更加慢了，又因为是解析了国外的地址，所以默认就走了路由，但是走到路由后路由域名匹配又给他打回国内线，所以就有部分流量需要在内网走两个设备才能继续，这样就不太好了，其实我提的这个，在我这边这个配置的环境中，实际使用起来非常爽，因为也是直接路由负载的，所以非外网流量是不走路由的，大大增强了性能，但也因为如此，如果IP解析有问题，就很麻烦

**Comment by pymumu** [comment]
有些IP地址是半阻断状态，也就是ping不通，但是tcp 80，443会成功，或者是ping有时通，tcp不行，这样就会导致你的问题。

建议方案就是对这些域名白名单管理，对指定域名禁用IPV6。
域名列表github上应该比较容易找到。
配置具体看：https://pymumu.github.io/smartdns/config/forwarding-with-ipset/

但你说的baidu解析不正确，这个要提供相关的log，我这里是没有这种问题的。
一个可能性的情况是，163开头的IP地址被放到了TPROXY中，这样导致了虚假的链接速度。

对于分流，建议还是采用白名单模式，没必要所有流量都走转发。大部分网站直连接效果也是不错的。

**Comment by PikuZheng** [comment]
> 实际使用中会发现不仅仅是谷歌的，FB那些的也会跳，twitch那些也会跳，一个一个找一个个加就太累了

这个有现成的叫gfwlist

**Comment by tobycroft** [comment]
> 有些IP地址是半阻断状态，也就是ping不通，但是tcp 80，443会成功，或者是ping有时通，tcp不行，这样就会导致你的问题。
> 
> 建议方案就是对这些域名白名单管理，对指定域名禁用IPV6。 域名列表github上应该比较容易找到。 配置具体看：https://pymumu.github.io/smartdns/config/forwarding-with-ipset/
> 
> 但你说的baidu解析不正确，这个要提供相关的log，我这里是没有这种问题的。 一个可能性的情况是，163开头的IP地址被放到了TPROXY中，这样导致了虚假的链接速度。
> 
> 对于分流，建议还是采用白名单模式，没必要所有流量都走转发。大部分网站直连接效果也是不错的。

分流采用的是非国内地址模式，因为有很多地址不再list里面，这个模式效果会比较好，而且其实大多数的服务器都在美国英国俄罗斯这些国家，所以单独对这几个处理即可，但是那个ipv6啊，有些是能访问的，ping很好，但是速度极慢，几乎没有流量的状态，常见的就是在tw和yt，有些地址因为阻断的原因，所以确实是可以屏蔽掉的走ipv4，但是有些ipv6也确实能访问，但是速度很慢，这个时候如果按照测速走，因为ipv4可能是不行的，但是ipv6是行的，至少ping是行的，所以就会被优选，gfwlist这个我试过，在这列表里面的全部走特殊dns，这个我已经做了，效果是不错的，但是就会经常走ipv6就这个问题

**Comment by tobycroft** [comment]
> 我自己是gfwlist一概禁ipv6

我也是设定了部分的list

类似：

nameserver /.xxxxxx.com/v2

这样的，但是这类的域名，我看教程在nameserver后面没有跟着别的配置了，我不知道能不能
nameserver /.xxxxxx.com/v2 -force-aaaa-soa 这样去写，如果可以的话其实也解决了我这个ipv6的问题

**Comment by PikuZheng** [comment]
> > 我自己是gfwlist一概禁ipv6
> 
> 我也是设定了部分的list
> 
> 类似：
> 
> nameserver /.xxxxxx.com/v2
> 
> 这样的，但是这类的域名，我看教程在nameserver后面没有跟着别的配置了，我不知道能不能
> nameserver /.xxxxxx.com/v2 -force-aaaa-soa 这样去写，如果可以的话其实也解决了我这个ipv6的问题

请使用domain-set
