### ISSUE TITLE
operation not supported error, dev loop0, sector 49152 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 2

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1373]
**问题现象**  
smartdns工作时，openwrt日志中出现大量如下错误，不工作就不会出现错误：
Fri Apr 14 04:59:31 2023 kern.err kernel: [ 1175.651216] operation not supported error, dev loop0, sector 230784 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 2
Fri Apr 14 04:59:31 2023 kern.err kernel: [ 1175.651626] operation not supported error, dev loop0, sector 230576 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 2
Fri Apr 14 04:59:31 2023 kern.err kernel: [ 1175.652018] operation not supported error, dev loop0, sector 230544 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 2
Fri Apr 14 04:59:31 2023 kern.err kernel: [ 1175.652458] operation not supported error, dev loop0, sector 229384 op 0x3:(DISCARD) flags 0x0 phys_seg 1 prio class 2

**运行环境**
1. 固件型号  
以下内核smartdns工作时均出现错误日志，不工作不出现日志。
koolshare 2.37 内核5.4.108
ImmortalWrt v21.02.5 内核5.4.236
OpenWrt R23.4.1 / LuCI Master (git-23.102.51528-077696d) 内核6.1.23

2. 运营商  
山东联通

3. smartdns来源以及版本
所有smartdns版本

4. 涉及的配置(注意去除个人相关信息)
server-name smartdns
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 100000000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 1
log-size 64K
log-num 1
log-level error
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind [::]:6053 
bind-tcp [::]:6053 
bind [::]:5555  -no-speed-check -group foreign -no-dualstack-selection
bind-tcp [::]:5555  -no-speed-check -group foreign -no-dualstack-selection
server 202.102.128.68  -group domestic -exclude-default-group 
server-tls 223.5.5.5  -group domestic -exclude-default-group
server-tls 8.8.8.8  -group foreign -exclude-default-group
server-tls 1.1.1.1  -group foreign -exclude-default-group
server-tls 8.8.4.4  -group foreign -exclude-default-group
server-tls 1.12.12.12  
server 10.10.10.100:3053  -group domestic -exclude-default-group
server 10.10.10.100:1056  -group foreign -exclude-default-group
server 10.10.10.100:2053  
domain-set -name domain-forwarding-list -file /etc/smartdns/domain-forwarding.list
domain-rules /domain-set:domain-forwarding-list/ 
domain-set -name domain-block-list -file /etc/smartdns/domain-block.list
domain-rules /domain-set:domain-block-list/ --address #
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

custom.conf：
log-level fatal
bind :8055 -group domestic
bind-tcp :8055 -group domestic
serve-expired-ttl 259200000
serve-expired-prefetch-time 21600

**重现步骤**
1. 上游DNS配置。  
见配置文件
2. 访问的域名。  
未知

**信息收集**  
此问题困扰我3年多，几乎尝试了网上所有的解决方案，下面资料供大佬参考，不知道是否有用。
https://lore.kernel.org/all/20211028041513.GD4821@dread.disaster.area/T/

**Comment by PikuZheng** [comment]
打听一下是什么硬件出现这个问题

**Comment by yyysuo** [comment]
> 打听一下是什么硬件出现这个问题，内存有多少，存储有多少

7100u的小主机，装了esxi，上面提及的openwrt都是虚拟在esxi下面的，内存我一般给2G，看使用率，足够用了。

**Comment by pymumu** [comment]
那个log似乎是因为mount的loop设备不支持某个功能的log

但smartdns没有这些操作，只有log文件和cache文件会写盘，但我看你配置都关闭了

不清楚你是怎么mount磁盘的，可以发一下cat /proc/mounts看看

另外就是不要用loop

**Comment by PikuZheng** [comment]
new infomation。。。squashfs不能挂载在scsi或sata，必须挂载在ide，然后一切正常。
![image](https://user-images.githubusercontent.com/12579522/231916812-3c84fdfc-bf93-46e4-bfd8-56d9b4d44bef.png)

![image](https://user-images.githubusercontent.com/12579522/231916692-2cbf9b50-a98a-4354-85ae-b21c630e7289.png)

我自己的ext4是一直挂载在scsi的

**Comment by yyysuo** [comment]
> new infomation。。。squashfs不能挂载在scsi或sata，必须挂载在ide，然后一切正常。 ![image](https://user-images.githubusercontent.com/12579522/231916812-3c84fdfc-bf93-46e4-bfd8-56d9b4d44bef.png)
> 
> ![image](https://user-images.githubusercontent.com/12579522/231916692-2cbf9b50-a98a-4354-85ae-b21c630e7289.png)
> 
> 我自己的ext4是一直挂载在scsi的

大佬费尽了，对于已经正常运行的虚拟机，我目前的设置是这样的
![image](https://user-images.githubusercontent.com/10081071/231923694-131d4137-d3e2-47dc-b9ae-f1ef6df04df5.png)

是否改成这样就可以了呢？还是说需要重新安装openwrt才可以？
![image](https://user-images.githubusercontent.com/10081071/231923773-15357e82-f7e7-4e59-aeb0-518482851ac4.png)

另外，其它插件都没有这个问题，为什么smartdns有这个问题呢，在smartdns侧修改代码能解决这个问题么？

**Comment by PikuZheng** [comment]
> 是否改成这样就可以了呢？还是说需要重新安装openwrt才可以？

可以直接改。关机，改，开机。

> 另外，其它插件都没有这个问题，为什么smartdns有这个问题呢，在smartdns侧修改代码能解决这个问题么？

我第一张图是原版img什么软件都没安装，可见开机就有报错的。

**Comment by PikuZheng** [comment]
建议还是用ext4 img，以后空间扩容，或挂载到其他系统上读写文件都很方便。

**Comment by yyysuo** [comment]
> > 是否改成这样就可以了呢？还是说需要重新安装openwrt才可以？
> 
> 可以直接改。关机，改，开机。
> 
> > 另外，其它插件都没有这个问题，为什么smartdns有这个问题呢，在smartdns侧修改代码能解决这个问题么？
> 
> 我第一张图是原版img什么软件都没安装，可见开机就有报错的。

esxi中更改scsi为ide，提示成功，但是再次重新编辑时，看到的选项还是scsi，不知道是啥情况。

**Comment by PikuZheng** [comment]
> esxi中更改scsi为ide，提示成功，但是再次重新编辑时，看到的选项还是scsi，不知道是啥情况。

换用谷歌浏览器

**Comment by yyysuo** [comment]
> > esxi中更改scsi为ide，提示成功，但是再次重新编辑时，看到的选项还是scsi，不知道是啥情况。
> 
> 换用谷歌浏览器

就是用的chrome最新版本，估计是esxi的版本有关系。我是6.7 update 3，前一阵子因为不能创建新的虚拟机，打了个补丁：
https://blog.csdn.net/wuhao0015/article/details/123772442

**Comment by PikuZheng** [comment]
> 就是用的chrome最新版本，估计是esxi的版本有关系。我是6.7 update 3

我家里两个6.7u3，从没遇到问题啊

，前一阵子因为不能创建新的虚拟机，打了个补丁：
> https://blog.csdn.net/wuhao0015/article/details/123772442
> 
> 现在的问题是能编辑，能保存，保存也提示成功，然后再编辑看到之前的保存其实无效的。

啊这 人家是6.5的补丁
要不你直接ssh进去，修改vmx文件吧

**Comment by yyysuo** [comment]
> > 就是用的chrome最新版本，估计是esxi的版本有关系。我是6.7 update 3
> 
> 我家里两个6.7u3，从没遇到问题啊
> 
> ，前一阵子因为不能创建新的虚拟机，打了个补丁：
> 
> > https://blog.csdn.net/wuhao0015/article/details/123772442
> > 现在的问题是能编辑，能保存，保存也提示成功，然后再编辑看到之前的保存其实无效的。
> 
> 啊这 人家是6.5的补丁 要不你直接ssh进去，修改vmx文件吧

我也搞不懂，一个19年的bug为什么现在还没解决，我打了补丁也确实解决了问题，看来也造成了新的问题。

**Comment by PikuZheng** [comment]
我6.7从来没bug过。。。也没单独安装什么补丁。现在版本是19997733，也就是去年7月的版本。
看了一下确实是EOL了，不过我还没计划升7.0GA
![image](https://user-images.githubusercontent.com/12579522/232287049-cbc03eff-b17f-4227-8d00-cc97ff19d061.png)


说起来你可以新建一个虚拟机，然后挂载这个现有硬盘到ide吗

**Comment by yyysuo** [comment]
> 

感谢，这个思路真是绝妙，应该是可以的，只需要把所有快照删除整合一下磁盘，然后新建一个配置一模一样的虚拟机，使用整合之后的磁盘，再改成IDE至少可以在esxi的界面看到ide改成功了，切换的话我还没试，等家人都睡了再切换测试，到时候再反馈。

**Comment by yyysuo** [comment]
这个ide模式和scsi性能上有差异？

**Comment by PikuZheng** [comment]
> 这个ide模式和scsi性能上有差异？

都是模拟盘，只不过模拟的总线不同而已

**Comment by yyysuo** [comment]
> > 这个ide模式和scsi性能上有差异？
> 
> 都是模拟盘，只不过模拟的总线不同而已

方案可行，已经转换固件为IDE模式，目前看来确实是没有错误日志了。

**Comment by yyysuo** [comment]
> > 这个ide模式和scsi性能上有差异？
> 
> 都是模拟盘，只不过模拟的总线不同而已


这种设置也是可以的。
![image](https://user-images.githubusercontent.com/10081071/232936452-3d1ba4c2-9f03-4dd8-9d12-72f7affe6169.png)
