### ISSUE TITLE
cname directive cannot resolve alias when target is a subdomain of source

### ISSUE THREAD

**Issue by gnought** [pymumu/smartdns#1374]
SmartDns version: smartdns 1.2023.04.12-1110

After putting the below line, smartdns won't resolve duckduckgo.com.
```
cname /duckduckgo.com/safe.duckduckgo.com
```

**Comment by PikuZheng** [comment]
duckduckgo.com include safe.duckduckgo.com
```
cname /duckduckgo.com/safe.duckduckgo.com
cname /safe.duckduckgo.com/-
```
try it please

**Comment by gnought** [comment]
adding a line could solve both `duckduckgo.com` and `safe.duckduckgo.com`, but the cname alias breaks.
```
cname /safe.duckduckgo.com/-
```

**Comment by gnought** [comment]
Here is a working example
```
cname /www.bing.com/strict.bing.com
```
`dig` will return
```
www.bing.com.		300	IN	CNAME	strict.bing.com.
strict.bing.com.	300	IN	A	204.79.197.220
```

**Comment by pymumu** [comment]
Try lastest code.

**Comment by gnought** [comment]
`dig` now returns correct records. Thanks for the quick fix. @pymumu 
```
duckduckgo.com.		300	IN	CNAME	safe.duckduckgo.com.
safe.duckduckgo.com.	300	IN	A	20.43.161.151
```
