### ISSUE TITLE
Smart DNS被绕过？

### ISSUE THREAD

**Issue by 57382** [pymumu/smartdns#1375]
**问题现象**  
无法强制应用路由器的SmartDNS

**运行环境**
OpenWrt官方正式版和SmartDNS官方正式版

**重现步骤**
1-在路由器配置SmartDNS为主DNS  
2-Windows设置一个无效的DNS，例如GitHub的ip
3-打开百度.com测试，显示DNS查询失败

**信息收集**  
![DNS](https://user-images.githubusercontent.com/81396211/232665904-3948a9b9-6aa2-4957-9f6e-0019e4e0fb75.PNG)
这是否证明当前SmartDNS没有上述截图中的强制路由器DNS解析？
我用截图中的软件测试，Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，说明确实劫持了DNS，强制应用了路由器的DNS
**有没有办法让SmartDNS也实现这种行为？避免SmartDNS被系统或程序内部设置的DNS绕过，确保所有DNS都是SmartDNS解析的**

**Comment by 57382** [comment]
最好提供一个选项，强制或非强制

**Comment by PikuZheng** [comment]
强制所有本地设备使用路由器dns 是在路由器上使用iptables将所有udp/53 重定向到自身。

Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，很可能是因为走了ipv6 dns

**Comment by 57382** [comment]
> 强制所有本地设备使用路由器dns 是在路由器上使用iptables将所有udp/53 重定向到自身。
> 
> Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，很可能是因为走了ipv6 dns。另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用。

“很可能是因为走了ipv6 dns”，**绝对不可能，IPv6的DNS我也改成了GitHub的IPv6的ip**
"另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用"，**绝对不可能**

**Comment by cresky-github** [comment]
> **问题现象** 无法强制应用路由器的SmartDNS
> 
> **运行环境** OpenWrt官方正式版和SmartDNS官方正式版
> 
> **重现步骤** 1-在路由器配置SmartDNS为主DNS 2-Windows设置一个无效的DNS，例如GitHub的ip 3-打开百度.com测试，显示DNS查询失败
> 
> **信息收集** ![DNS](https://user-images.githubusercontent.com/81396211/232665904-3948a9b9-6aa2-4957-9f6e-0019e4e0fb75.PNG) 这是否证明当前SmartDNS没有上述截图中的强制路由器DNS解析？ 我用截图中的软件测试，Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，说明确实劫持了DNS，强制应用了路由器的DNS **有没有办法让SmartDNS也实现这种行为？避免SmartDNS被系统或程序内部设置的DNS绕过，确保所有DNS都是SmartDNS解析的**

强制？

NAT 53端口就行了。
关键是主路由，可以NAT

**Comment by lifei6671** [comment]
> > 强制所有本地设备使用路由器dns 是在路由器上使用iptables将所有udp/53 重定向到自身。
> > Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，很可能是因为走了ipv6 dns。另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用。
> 
> “很可能是因为走了ipv6 dns”，**绝对不可能，IPv6的DNS我也改成了GitHub的IPv6的ip** "另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用"，**绝对不可能**

Chrome浏览器有内置的dns，你看下是不是使用了内置的dns。

**Comment by 57382** [comment]
> > > 强制所有本地设备使用路由器dns 是在路由器上使用iptables将所有udp/53 重定向到自身。
> > > Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，很可能是因为走了ipv6 dns。另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用。
> > 
> > 
> > “很可能是因为走了ipv6 dns”，**绝对不可能，IPv6的DNS我也改成了GitHub的IPv6的ip** "另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用"，**绝对不可能**
> 
> Chrome浏览器有内置的dns，你看下是不是使用了内置的dns。



> > > 强制所有本地设备使用路由器dns 是在路由器上使用iptables将所有udp/53 重定向到自身。
> > > Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，很可能是因为走了ipv6 dns。另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用。
> > 
> > 
> > “很可能是因为走了ipv6 dns”，**绝对不可能，IPv6的DNS我也改成了GitHub的IPv6的ip** "另外当所有设置的dns服务器都不可用时，windows可能还会随机发现一个dns服务器用"，**绝对不可能**
> 
> Chrome浏览器有内置的dns，你看下是不是使用了内置的dns。

![D](https://user-images.githubusercontent.com/81396211/232981179-175fe756-cc78-4ff5-9b27-983b81a48796.PNG)
我知道这个设置，早就关闭了。是关闭测试的。
https://github.com/aarond10/https_dns_proxy
希望SmartDNS可以像上面的软件包一样，**一键设置强制，避免被绕过**

**Comment by zxlhhyccc** [comment]
> > **问题现象** 无法强制应用路由器的SmartDNS
> > **运行环境** OpenWrt官方正式版和SmartDNS官方正式版
> > **重现步骤** 1-在路由器配置SmartDNS为主DNS 2-Windows设置一个无效的DNS，例如GitHub的ip 3-打开百度.com测试，显示DNS查询失败
> > **信息收集** ![DNS](https://user-images.githubusercontent.com/81396211/232665904-3948a9b9-6aa2-4957-9f6e-0019e4e0fb75.PNG) 这是否证明当前SmartDNS没有上述截图中的强制路由器DNS解析？ 我用截图中的软件测试，Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，说明确实劫持了DNS，强制应用了路由器的DNS **有没有办法让SmartDNS也实现这种行为？避免SmartDNS被系统或程序内部设置的DNS绕过，确保所有DNS都是SmartDNS解析的**
> 
> 强制？
> 
> NAT 53端口就行了。 关键是主路由，可以NAT

luci的配置界面有这些吗？

**Comment by cresky-github** [comment]
> > > **问题现象** 无法强制应用路由器的SmartDNS
> > > **运行环境** OpenWrt官方正式版和SmartDNS官方正式版
> > > **重现步骤** 1-在路由器配置SmartDNS为主DNS 2-Windows设置一个无效的DNS，例如GitHub的ip 3-打开百度.com测试，显示DNS查询失败
> > > **信息收集** ![DNS](https://user-images.githubusercontent.com/81396211/232665904-3948a9b9-6aa2-4957-9f6e-0019e4e0fb75.PNG) 这是否证明当前SmartDNS没有上述截图中的强制路由器DNS解析？ 我用截图中的软件测试，Windows设置DNS为GitHub的ip，实测可以打开百度.com，DNS解析正常，说明确实劫持了DNS，强制应用了路由器的DNS **有没有办法让SmartDNS也实现这种行为？避免SmartDNS被系统或程序内部设置的DNS绕过，确保所有DNS都是SmartDNS解析的**
> > 
> > 
> > 强制？
> > NAT 53端口就行了。 关键是主路由，可以NAT
> 
> luci的配置界面有这些吗？

不保证，主路由也不一定是 Openwrt
