### ISSUE TITLE
smartdns ubuntu 22.04 启动 无法开启 dot

### ISSUE THREAD

**Issue by liushiqi1001** [pymumu/smartdns#1376]
**问题现象**  
简要描述问题出现的现象
1、我想用smart 启动DOT，但是无论怎么配置，853端口都无法bind ，日志里面也没有报错
2、事实上pem key，我用openssl 生成，并在配置文件中设置，但是似乎没有调用，也没有在/etc/smartdns/目录下面创建

**运行环境**
1. 固件型号  
ubuntu 22.04 LTS
2. 运营商  

3. smartdns来源以及版本      

       smartdns 1.2023.03.04-1125

4. 涉及的配置(注意去除个人相关信息)
```shell
bind-tls 0.0.0.0:853

server-tls 1.1.1.1
server-tls 8.8.8.8
server-tls dns.twnic.tw
server-https https://cloudflare-dns.com/dns-query
server-https https://dns.google/dns-query
server-https https://dns.twnic.tw/dns-query


log-level debug
log-file /var/log/smartdns/smartdns.log
```

**Comment by liushiqi1001** [comment]
而且我觉得document也有问题

![image](https://user-images.githubusercontent.com/28683522/232740039-aa410801-e1e6-4fe3-9527-91e3ebe49392.png)

**Comment by liushiqi1001** [comment]
启动日志，日志级别已经是 debug 了 ，配置文件用的就是上面问题描述中问题4中的内容
![image](https://user-images.githubusercontent.com/28683522/232740619-e93b9aec-056d-4c8a-a9ea-d368b153dca6.png)

**Comment by PikuZheng** [comment]
tls 服务器需要 41.0.12（20230316）或更高版本

**Comment by liushiqi1001** [comment]
谢谢 我试试
