### ISSUE TITLE
bootstrap dns 怎么用

### ISSUE THREAD

**Issue by wzy105** [pymumu/smartdns#1377]
server 114.114.115.115 -bootstrap-dns -exclude-default-group
  是这样吗？要加 -exclude-default-group 和默认组隔离开吗

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/config/bootstrap-dns/

**Comment by wzy105** [comment]
> https://pymumu.github.io/smartdns/config/bootstrap-dns/

看了，

server 1.2.3.4 -bootstrap-dns #（这里不加 -exclude-default-group 会进入到默认组解析吗） 

server dns.server # 这个不明白

**Comment by jxph1123** [comment]
不是说了吗，-bootstrap-dns只解析DNS服务器，防止刚开机DNS全是设置的域名服务器的时候，解析不到地址。
不加 -exclude-default-group 也不会进入到默认组，只解析DNS服务器。

**Comment by sdddhhll** [comment]
> 不是说了吗，-bootstrap-dns只解析DNS服务器，防止刚开机DNS全是设置的域名服务器的时候，解析不到地址。 不加 -exclude-default-group 也不会进入到默认组，只解析DNS服务器。

我最近也在测试楼主说的情况，发现结果和您说的有出入，如果这样配置了 server 114.114.114.114 -bootstrap-dns  是会进入默认组的，所有的DNS都会进行解析，不仅仅是域名的DNS。测试证明server 114.114.114.114 -bootstrap-dns 和server 114.114.114.114 结果一模一样。
测试过程
1.先关闭所有DNS服务器解析，保证所有的DNS都无法正常解析：
![image](https://user-images.githubusercontent.com/12165004/236762748-5a6d9085-42ce-4355-a20e-92466178f0b2.png)
2.只开启114udp服务器，且这个服务器已经被设置了-bootstrap-dns参数
![image](https://user-images.githubusercontent.com/12165004/236762916-cf2dc583-38cb-40a7-8840-c33679bc42a6.png)
![image](https://user-images.githubusercontent.com/12165004/236763085-c3557622-0ee2-425e-a00d-e2306af00ea2.png)
![image](https://user-images.githubusercontent.com/12165004/236763140-93444c45-41b8-4d91-a549-40d40b24ad1d.png)
发现所有的域名都可以解析了。
目前看来好像-bootstrap-dns 参数没有发挥应有的作用。建议使用官网的第二种方法解决上述问题，也就是下面的方法：

# 配置bootstrap DNS
server 1.2.3.4 -group bootstrap-dns
nameserver /dns.server/bootstrap-dns
# 此服务器将使用1.2.3.4解析
server dns.server

**Comment by pymumu** [comment]
你指定了group cn，这样所有cn后缀的域名都会用对应的服务器查询。

这个bootstrap-dns默认就不要用。
