### ISSUE TITLE
开启测速后， ipv6解析不到地址

### ISSUE THREAD

**Issue by aries1998** [pymumu/smartdns#1379]
**问题现象**  
只要默认开启测速功能， ipv6就解析不到结果， ipv4正常， bind配置no-speed-check关闭测速就一切正常.

**运行环境**
1. 固件型号  
ubuntu 22  x86
2. 运营商  
移动
3. smartdns来源以及版本
smartdns 1.2023.03.04-1125

4. 涉及的配置(注意去除个人相关信息)
bind :1500
proxy-server socks5://127.0.0.1:6081 -name socks5
server-tls 8.8.8.8 -group oversea -proxy socks5

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
任何域名解析ipv6

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。        

日志没有任何异常

2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/config/dualstack/

**Comment by aries1998** [comment]
> https://pymumu.github.io/smartdns/config/dualstack/

双栈优选我其实是打开的，就是有点奇怪，理论上测速和优选难道不是一样的逻辑么，ping,tcp 80/443。  按我的情况来说打开双栈优选应该解析ipv6也有问题，但实际没问题，只要关了测速

**Comment by nrjycyd** [comment]
和你一样都是Ubuntu环境，只要bind配置no-speed-check关闭测速就可以访问ipv6，很奇怪
