### ISSUE TITLE
需要轻量化的正则支持（或者其它方案？）

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#138]
**需求应用场景**
最近4个数字的域名问题大家都知道了吧，单纯屏蔽那个域名当然没问题，但问题是不止那个域名，还有一堆……把那一堆都写进配置里感觉不可行，正则写几个字就能解决的问题为什么要写一堆东西？

**建议的方案**
添加一个正则支持，或者内置一个域名分析功能做成开关。
支持白名单。

**Comment by pymumu** [comment]
没理解你说的是什么。

**Comment by ztjal** [comment]
例如
address /\.([0-9]{4})\.com/#

**Comment by pymumu** [comment]
目前不会考虑支持正则式，因为：
1.  smartdns运行在路由器上，CPU性能一般都很差。现在用的算法是专门针对字符串的。时间复杂度是log（N），在路由器这种设备上处理上几万条规则，也只要1ms。
2. 如果用正则式，那么就必须将所有规则全部过滤一遍，时间复杂度会变成log（N^2）
处理上万条规则，可能就要近1s钟，这种算法性能会比较差。
3. 并且正则式还有匹配误杀的情况。

所以，目前不会考虑支持正则式。

**Comment by LEXUGE** [comment]
> 目前不会考虑支持正则式，因为：
> 
>     1. smartdns运行在路由器上，CPU性能一般都很差。现在用的算法是专门针对字符串的。时间复杂度是log（N），在路由器这种设备上处理上几万条规则，也只要1ms。
> 
>     2. 如果用正则式，那么就必须将所有规则全部过滤一遍，时间复杂度会变成log（N^2）
>        处理上万条规则，可能就要近1s钟，这种算法性能会比较差。
> 
>     3. 并且正则式还有匹配误杀的情况。
> 
> 
> 所以，目前不会考虑支持正则式。

正则确实比较慢，但是 log(n^2) = 2*log(n) ，一秒钟这个说法太过于粗糙了
