### ISSUE TITLE
自定义解析ip问题

### ISSUE THREAD

**Issue by llccool1** [pymumu/smartdns#1380]
例如我把123.com这个域名解析到,3个不同的ip
在自定义配置里这样写3条
address /123.com/1.1.1.1
address /123.com/1.1.1.2
address /123.com/1.1.1.3
自nslookup查询的时候,只会返回最后一条,也就是1.1.1.3
我想请问用nslookup查询解析到的ip,如何让他返回速度最快的一条,而不是一直返回最后一条,该如何配置?

**Comment by pymumu** [comment]
address目前只支持一个IP地址

**Comment by pymumu** [comment]
最新代码已经支持多个IP，可以验证下看看。

**Comment by llccool1** [comment]
@pymumu 我在openwrt下看的是1.2023.41-1,这个版本,升级最新的不让我升,提示Not downgrading package smartdns on root from 1.2023.41-1 to 1.2023.05.07-1641.
翻译一下就是未将root下的smartdns包从1.2023.41-1降级到1.2023.05.07-1641
请问怎么才能安装最新版本

**Comment by PikuZheng** [comment]
> @pymumu 我在openwrt下看的是1.2023.41-1,这个版本,升级最新的不让我升,提示Not downgrading package smartdns on root from 1.2023.41-1 to 1.2023.05.07-1641. 翻译一下就是未将root下的smartdns包从1.2023.41-1降级到1.2023.05.07-1641 请问怎么才能安装最新版本

先卸载旧的

**Comment by llccool1** [comment]
@pymumu 请问这个配置能备份吗?卸载掉再装的话配置是不是丢失

**Comment by pymumu** [comment]
卸载后配置会保留

**Comment by llccool1** [comment]
@pymumu 卸载掉,安装了最新版本.在自定义配置里填入
address /123.com/1.1.1.1,1.1.1.2
用nslookup返回的结果
C:\Users\Administrator>nslookup 123.com
服务器:  smartdns
Address:  240e:3a1:342d:db50::fca

*** smartdns 找不到 123.com: Non-existent domain

而只填入
address /123.com/1.1.1.1
用nolookup返回
C:\Users\Administrator>nslookup 123.com
服务器:  smartdns
Address:  240e:3a1:342d:db50::fca

非权威应答:
名称:    123.com
Address:  1.1.1.1


smartdns版本显示1.2023.05.07-1641

**Comment by PikuZheng** [comment]
> smartdns版本显示1.2023.05.07-1641

多个ip需要6月15日之后的版本

**Comment by llccool1** [comment]
@PikuZheng 我看的最新的发行版就是5月7日的,最新版给我个连接好吗

**Comment by PikuZheng** [comment]
> @PikuZheng 我看的最新的发行版就是5月7日的,最新版给我个连接好吗

需要用最新代码自己编译，或者等release，或者用我编译的（但是版本号命名和官方不同）https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v42.0.10
