### ISSUE TITLE
想问问关于Openwrt里如何写缓存地址

### ISSUE THREAD

**Issue by lretro-ok** [pymumu/smartdns#1381]
我是用的Openwrt改版istoreos安装的Smartdns插件
（求大佬解救一下
目前自定义设置内为
_________________
# Add custom settings here.
# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
# log-level error
# cache-size 10000000
# cache-persist yes
# cache-file /SmartDNS/Cache
# serve-expired yes
# serve-expired-prefetch-time 21600
# serve-expired-ttl 259200
# serve-expired-reply-ttl 3
# log-num 0
# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip/subnet]
_______________
我的问题主要是 cache-file /SmartDNS/Cache 这个设定我不知道是否正确，我目前分区信息是创建了一个为nvme0n1p4（/dev/SmartDNS）的分区 挂载点自设为/SmartDNS，请问这样子我上面的cache-file设定是否正确？）我目前似乎没有看见缓存文件 请问我该怎么做😿

**Comment by PikuZheng** [comment]
可以的。
关闭smartdns时缓存文件才会写入。或者重启一下smartdns

**Comment by lretro-ok** [comment]
不好意思...我目前情况是重启几次系统仍然没有看见出现缓存文件 真的不会是我的缓存目录设置错误吗？求救求救（我目前尝试过使用 /mnt/nvme0n1p4/Cache 仍然无法解决 这个地方我真的不会设定....）

**Comment by abolast** [comment]
你要不是尝试写成 /path/smartdns.cache ，然后htop杀死smartdns后再启动，看看文件生成了没有
