### ISSUE TITLE
设置数据包标记so-mark的作用是什么？

### ISSUE THREAD

**Issue by sdddhhll** [pymumu/smartdns#1388]
各位大神，能简单介绍一下[-set-mark]：设置数据包标记so-mark的作用和使用场景么？我没有找到使用的相关说明，非常感谢。

**Comment by PikuZheng** [comment]
set-mark 可以给单个数据报的ip包头增加一个标记，该标记可以被iptables识别，常用于流量标记（限速？）、nat、过滤标记（阻断？）等。

**Comment by sdddhhll** [comment]
> set-mark 可以给单个数据报的ip包头增加一个标记，该标记可以被iptables识别，常用于流量标记（限速？）、nat、过滤标记（阻断？）等。

谢谢
