### ISSUE TITLE
支持ECH Encrypted Client Hello

### ISSUE THREAD

**Issue by 57382** [pymumu/smartdns#1389]
关于ECH的介绍：
https://blog.cloudflare.com/encrypted-client-hello/
https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/

Firefox开启：
about:config
network.dns.echconfig.enabled
network.dns.use_https_rr_as_altsvc

Chrome开启：
chrome://flags
encrypted-client-hello
use-dns-https-svcb-alpn

ECH必须和DOH配合才能运行

**Comment by pymumu** [comment]
代码已经ready，等42发布后，合入。

**Comment by ZYB14** [comment]
了解了一下，这个ech需要你访问的网站也支持啊

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/tree/https-svcb

原型版本，可以获取验证看看。

**Comment by ztjal** [comment]
现在的Release 43支持这个吗？
