### ISSUE TITLE
指定特定域名的多个IP时返回最优

### ISSUE THREAD

**Issue by ylx2016** [pymumu/smartdns#139]
**需求应用场景**
请描述需求应用的场景和方式。
UsbEAm Hosts Editor v3.47会提供多个IP，提取多个IP后按配置指定多个IP到某同一个域名，防止万一某个ip节点挂了自动切换到别的
**建议的方案**
实现上述场景建议的方案。
根据填入的多个ip 就像从多个dns那边获取一样 从中选择延迟最低的
例子：
address /uplaypc-s-ubisoft-ww.cdn.ubi.com/218.75.225.19
address /uplaypc-s-ubisoft-ww.cdn.ubi.com/222.138.6.83
address /uplaypc-s-ubisoft-ww.cdn.ubi.com/188.43.72.73
测试延迟后最终返回的是218.75.225.19
UsbEAm Hosts Editor功能截图
https://i.loli.net/2019/04/05/5ca71b34b3ce7.png

**Comment by pymumu** [comment]
看这个是不是一个通用需求吧，
现在暂时可以通过配合dnsmasq作为上游+hosts来解决你的问题

**Comment by ylx2016** [comment]
其他game boy/girl 看到了顶我

**Comment by JDex623** [comment]
希望可以做成多个同时选优 address /uplaypc-s-ubisoft-ww.cdn.ubi.com/218.75.225.19;222.138.6.83;188.43.72.73
