### ISSUE TITLE
Smartdns不生效

### ISSUE THREAD

**Issue by AIMancer** [pymumu/smartdns#1390]
**问题现象**  
开启常规设置，自动设置为dnsmasq上游，nslookup baidu.com总是返回2个ip

**运行环境**
1. 固件型号  
Openwrt 22.03.3

2. smartdns来源以及版本
opkg安装

3. 涉及的配置
两层NAT。软路由做主路由，有个二级路由器开启了dhcp

cat tmp/etc/smartdns/smartdns.conf

server-name smartdns
dualstack-ip-selection no
serve-expired yes
cache-size 10000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
force-qtype-SOA  28 65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind :6053
server 114.114.114.114  -group cn 
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

**重现步骤**
1. 上游DNS配置。  
114.114.114.114 UDP

2. 访问的域名。  
nslookup www.baidu.com

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/faq/#smartdnsip
