### ISSUE TITLE
domain-set 能否给多个配置文件起同样的名字

### ISSUE THREAD

**Issue by hpcex** [pymumu/smartdns#1391]
请问domain-set里面能否给不同的配置文件起同样的名字呢？如下面的配置。
两个域名表，都叫cn.

domain-set -name cn -type list -file /opt/smartdns/china.conf
domain-set -name cn -type list -file /opt/smartdns/china_me.conf
nameserver /domain-set:cn/china

**Comment by pymumu** [comment]
应该是可以，可以测测看

**Comment by hpcex** [comment]
![image](https://user-images.githubusercontent.com/2332112/236668499-551b1911-f134-425d-83d3-fb6b9f8c9fd5.png)

做了两个假域名，分别放在两个conf里，结果没问题，都去了china组解析。
