### ISSUE TITLE
最新版在ubuntu23.04系统中无法使用

### ISSUE THREAD

**Issue by zbc258** [pymumu/smartdns#1392]
**问题现象**  
在ubuntu23.04系统（x64平台）安装最新版smartdns后无法正常解析，使用nslookup查看，提示：
;; communications error to ::1#53: connection refused
;; communications error to ::1#53: connection refused
;; communications error to ::1#53: connection refused
;; communications error to 127.0.0.1#53: connection refused
;; no servers could be reached

**Comment by PikuZheng** [comment]
考虑是ufw限制

**Comment by pymumu** [comment]
发log, /var/log/smartdns/smartdns.log

**Comment by zbc258** [comment]
> 
log里的报错均为：
[2023-05-08 19:34:35,904][ERROR][     dns_server.c:6718] bind service [::]:53 failed, Address in use
[2023-05-08 19:34:35,904][ERROR][     dns_server.c:7108] create server socket failed.
[2023-05-08 19:34:35,904][ERROR][       smartdns.c:528 ] start dns server failed.

**Comment by zbc258** [comment]
> 考虑是ufw限制

似乎不是，关了ufw之后还是这样

**Comment by pymumu** [comment]
1. 检查配置文件中，是不是有多个bind [::]:53 
2. netstat -anp | grep 53检查53端口是否被其他进程占用。

**Comment by zbc258** [comment]
> 1. 检查配置文件中，是不是有多个bind [::]:53
> 2. netstat -anp | grep 53检查53端口是否被其他进程占用。

解决了，谢谢大佬。
就是bind[::]:53和bind-tcp[::]:53同时加上引起冲突了。
