### ISSUE TITLE
新的智能混合测速模式

### ISSUE THREAD

**Issue by 57382** [pymumu/smartdns#1396]
当前有两种测速模式，最快返回ip的DNS测速模式，以及网站域名最小ping的测速模式，
可以融合这两种测速模式，兼具两者的优点，同时消除缺点：
对于初次连接，没有本地缓存的域名，先用最快返回ip的DNS返回的ip，与此同时对域名的其它多个ip进行ping测速，
之后在后台静默无感知的把之前的ip替换成这个新的最小ping的ip，这么做既避免了首次连接的延迟，又能以最小ping进行后续的访问。
可以把这个新的智能混合测速模式作为默认的模式。

**Comment by PikuZheng** [comment]
现在就是这么干的啊？first-response参数
