### ISSUE TITLE
domain-rules 对应域名集合无法打开 双栈优选 与 测速，走默认组解析的域名无法对上述两个功能的状态进行更改

### ISSUE THREAD

**Issue by saybeking** [pymumu/smartdns#1397]
bind [::]:53
bind-tcp [::]:53

server-https https://xxxxxxxxxxxxxxx

domain-set -name domainsabc -file /etc/smartdns/domains.conf
nameserver /domain-set:domainsabc/groupname
server 114.114.114.114 -group groupname -exclude-default-group -bootstrap-dns
server 223.5.5.5 -group groupname -exclude-default-group -bootstrap-dns
server 114.114.115.115 -group groupname -exclude-default-group -bootstrap-dns

在路由中使用，代替dnsmasq直接接管 53 端口。

domains.conf 里面的域名走 groupname 组服务器解析，不属于 domains.conf 的域名走默认组服务器。
我想让 domains.conf 之外的域名关闭 双栈优选 与 测速模式，domains.conf 之内的域名启用 双栈优选 与 测速模式，发现无法实现。

因为：1、53 端口开启 双栈优选 与 测速模式，则 domains.conf 之外的域名无法关闭 双栈优选 与 测速模式。2、53 端口关闭 双栈优选 与 测速模式，则 domains.conf 之内的域名无法开启 双栈优选 与 测速模式。

上面的第一种情况可以这样解决------如果能对 domain-set:domainsabc 取 补集，则可以通过 domain-rules /domain-set:domainsabc补集/ -c none -d no 来把 domains.conf 之外域名关闭 双栈优选 与 测速模式。
上面的第二种情况可以这样解决------给 domain-rules  增加打开 双栈优选 与 测速模式的功能，比如说 domain-rules /domain-set:domainsabc/ -c ping,tcp:80,tcp:443 -d yes 可以生效，就可以了。目前是只能关闭，不能打开。

**Comment by saybeking** [comment]
希望可以对域名集合取反，或者令 domain-rules 不只可以关闭 双栈 与 测速，也可以在关闭的情况下打开。这样就可以实现白名单或黑名单模式了。

**Comment by PikuZheng** [comment]
> domains.conf 里面的域名走 groupname 组服务器解析

可能不会生效，由于上游有bootstrap标记

> 我想让 domains.conf 之外的域名关闭 双栈优选 与 测速模式

改全局参数 speed-check-mode 和 dualstack-ip-selection

> domains.conf 之内的域名启用 双栈优选 与 测速模式

改 domain-rules的speed-check-mode 和 dualstack-ip-selection

**Comment by saybeking** [comment]
我测试了一下。

>> 可能不会生效，由于上游有bootstrap标记
> 
> 虽然有bootstrap标记，但是可以生效。
> 
> > 改全局参数 speed-check-mode 和 dualstack-ip-selection
>> 改 domain-rules的speed-check-mode 和 dualstack-ip-selection
> 
> 全局设置 speed-check-mode none         dualstack-ip-selection no   ,然后 domain-rules 设置 -speed-check-mode ping,tcp:80,tcp:443 -dualstack-ip-selection yes 确实是可以打开这两个功能的。我的猜想是 domain-rules 无法对 bind 里面功能的状态进行改变，而可以对全局功能设置进行改变。

我的问题已经解决了，谢谢您的回复。
