### ISSUE TITLE
域名作为dns server时使用smartdns本身解析

### ISSUE THREAD

**Issue by Aefer** [pymumu/smartdns#140]
**需求应用场景**
保证解析到的dns server最快，在DOH中很有用（DOH大部分需使用域名）

**建议的方案**
当server配置项为域名时，先初始化smartdns，然后如果smartdns可用，则使用smartdns解析dns服务器的域名。当只有域名dns服务器时，使用系统dns解析。

**Comment by kangyu1230** [comment]
+1 
如果系统中只有SmartDNS作为DNS服务器（例如有科学软件因透明代理需要全局劫持53端口），SmartDNS配置文件中有DOH就无法启动，建议DOH域名可先用配置文件中其他server进行解析。

**Comment by pymumu** [comment]
Release 25新增域名延迟解析，避免启动失败。
