### ISSUE TITLE
对 no-rule-addr 参数的测试结果，请大佬看看这算不算 bug

### ISSUE THREAD

**Issue by saybeking** [pymumu/smartdns#1400]
** 问题 **
bind 的 -no-rule-addr 可以跳过 address /sohu.com/127.0.0.1 这样的规则，却不能跳过 address /baidu.com/# 和 domain-rules /163.com/ -address # 这样的规则。
---
** 配置 **
```
server-name smartdns
serve-expired yes
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level debug
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
force-qtype-SOA  65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto


address /baidu.com/#
domain-rules /163.com/ -address #
address /sohu.com/127.0.0.1


server 114.114.114.114
server 114.114.115.115
bind [::]:5000
bind [::]:5001 -no-rule-addr
```
---
通过 5000 端口运行 dig 命令，163 和 baidu 无结果，sohu 返回 127.0.0.1.
通过 5001 端口运行 dig 命令，163 和 baidu 仍然无结果，sohu 返回真实 IP 123.125.116.28
得出上面的结论

**Comment by pymumu** [comment]
-no-rule-addr是指忽略address选项的规则。

**Comment by saybeking** [comment]
> -no-rule-addr是指忽略address选项的规则。

谢谢您的回复。我以为是让配置文件中 address 相关行失去作用呢看来我错了。这个参数具体是什么作用看了 wiki 好多遍也不能理解，google 之后也没有找到模板。能不能麻烦这里贴上三五句代码，挻好奇到底什么用途。
