### ISSUE TITLE
找不到smartdns.conf

### ISSUE THREAD

**Issue by DDXDB** [pymumu/smartdns#1406]
**问题现象**  
根据官网描述无法在/etc/smartdns/找到smartdns.conf

**运行环境**
固件型号  
OpenWrt 22.03.5 r20134-5f15225c1e
smartdns来源以及版本
OpenWrt 官方仓库，1.2022.38.1-1

**Comment by PikuZheng** [comment]
openwrt版本不存在文件/etc/smartdns/smartdns.conf

**Comment by zmjjack** [comment]
smartdns.conf文件在/tmp/etc/smartdns/
