### ISSUE TITLE
请问这项目能和pi hole配合使用吗？

### ISSUE THREAD

**Issue by thb007** [pymumu/smartdns#141]
**需求应用场景**
支持pi hole(https://github.com/pi-hole)
*建议的方案**
配合pi hole一起使用

**设备信息**
1. 树莓派官方系统

**Comment by arfaWong** [comment]
我觉得应该可以吧。我现在是 smartdns 和 adguardhome 配合使用。
adguardhome 和 pi hole 差不多，也是有广告过滤，dns 解析，dhcp 功能。

**Comment by thb007** [comment]
> 我觉得应该可以吧。我现在是 smartdns 和 adguardhome 配合使用。
> adguardhome 和 pi hole 差不多，也是有广告过滤，dns 解析，dhcp 功能。

你的会污染吗？我的用一会就被污染，reboot后又好了，但是用不了多久又被污染。

**Comment by arfaWong** [comment]
@thb007 没有污染。用的 https://github.com/pymumu/smartdns/issues/74#issuecomment-457824440 的配置。
