### ISSUE TITLE
某个域名只会返回NXDOMAIN

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#1412]
smartdns来源以及版本

smartdns.1.2023.05.07-1641.mipsel-openwrt-all

**重现步骤**
1. 上游DNS配置。  

https:
https://223.5.5.5/dns-query
https://223.6.6.6/dns-query
https://1.12.12.12/dns-query
https://120.53.53.53/dns-query

udp:
8.8.4.4

3. 访问的域名。  

cm.mediav.com

-------------------------------------------

domain-set -name domains_china -file /home/smartdnscus/domains.china.conf
domain-rules /domain-set:domains_china/ -nameserver IPV4CHN

“mediav.com”是列表文件里边的其中的一行。

-------------------------------------------

debug日志，持久化缓存 为关闭。

> [2023-05-21 17:14:45,224][DEBUG][     dns_server.c:5390] query cm.mediav.com from 192.168.8.2, qtype: 1, id: 3059
> [2023-05-21 17:14:45,224][ INFO][     dns_server.c:3871] RULE-MATCH, type: 0, domain: cm.mediav.com, rule: mediav.com
> [2023-05-21 17:14:45,224][ INFO][     dns_server.c:3871] RULE-MATCH, type: 8, domain: cm.mediav.com, rule: mediav.com
> [2023-05-21 17:14:45,224][DEBUG][     dns_server.c:1874] reply cm.mediav.com qtype: 1, rcode: 0, reply: 1
> [2023-05-21 17:14:45,224][ INFO][     dns_server.c:994 ] result: cm.mediav.com, qtype: 1, rtcode: 3
> [2023-05-21 17:14:45,224][ INFO][     dns_server.c:1929] result: cm.mediav.com, client: 192.168.8.2, qtype: 1, id: 3059, group: IPV4CHN, time: 0ms

-------------------------------------------

dig自己的会失败

>root@OpenWrt:~# dig @192.168.8.11 -p 53 cm.mediav.com

> ; <<>> DiG 9.11.2-P1 <<>> @192.168.8.11 -p 53 cm.mediav.com
> ; (1 server found)
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 44440
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;cm.mediav.com.                 IN      A
> 
> ;; AUTHORITY SECTION:
> cm.mediav.com.          30      IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
> 
> ;; Query time: 1 msec
> ;; SERVER: 192.168.8.11#53(192.168.8.11)
> ;; WHEN: Sun May 21 17:24:23 CST 2023
> ;; MSG SIZE  rcvd: 104

-------------------------------------------

但是直接dig人家的是成功的，就算4条8也是正常的。

>root@OpenWrt:~# dig @223.5.5.5 -p 53 cm.mediav.com

> 
> ; <<>> DiG 9.11.2-P1 <<>> @223.5.5.5 -p 53 cm.mediav.com
> ; (1 server found)
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32089
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1408
> ;; QUESTION SECTION:
> ;cm.mediav.com.                 IN      A
> 
> ;; ANSWER SECTION:
> cm.mediav.com.          12      IN      CNAME   max.mdvdns.qhcdn.com.
> max.mdvdns.qhcdn.com.   12      IN      A       180.163.247.134
> 
> ;; Query time: 5 msec
> ;; SERVER: 223.5.5.5#53(223.5.5.5)
> ;; WHEN: Sun May 21 17:26:14 CST 2023
> ;; MSG SIZE  rcvd: 89

**Comment by PikuZheng** [comment]
请检查 anti-ad-for-smartdns.conf

**Comment by ztjal** [comment]
> 请检查 anti-ad-for-smartdns.conf

没有设置，/etc/smartdns/内没有该文件。
所有的相关文件里只有自定的domains.china.conf里有一行mediav.com外，没有其它任何相关设置。

**Comment by PikuZheng** [comment]
> [2023-05-21 17:14:45,224][ INFO][ dns_server.c:3871] RULE-MATCH, type: 0, domain: cm.mediav.com, rule: mediav.com
> [2023-05-21 17:14:45,224][ INFO][ dns_server.c:3871] RULE-MATCH, type: 8, domain: cm.mediav.com, rule: mediav.com

匹配到两条规则，肯定不止一处

**Comment by ztjal** [comment]
> > [2023-05-21 17:14:45,224][ INFO][ dns_server.c:3871] RULE-MATCH, type: 0, domain: cm.mediav.com, rule: mediav.com
> > [2023-05-21 17:14:45,224][ INFO][ dns_server.c:3871] RULE-MATCH, type: 8, domain: cm.mediav.com, rule: mediav.com
> 
> 匹配到两条规则，肯定不止一处

认真查了address.conf，找到了，引用另外一个位置上的列表文件了，我应该集中整理一下……
