### ISSUE TITLE
域名缓存个数过大后反应迟钝

### ISSUE THREAD

**Issue by kantkong** [pymumu/smartdns#1414]
**问题现象**  
域名查询结果缓存个数 cache-size 设置大于8192（如10240），使用一段时间后，查询反应速度非常慢。

**运行环境**
1. 固件型号 ：Padavan 4.4，D-link 882

2. 运营商  ：移动

3. smartdns来源以及版本：固件自带，release38.1

4. 涉及的配置(注意去除个人相关信息)
   域名查询结果缓存个数设置为10240，其他持久化缓存都关闭，TTL等用默认值。

**Comment by PikuZheng** [comment]
是不是开预读了 请考虑设备性能问题

**Comment by kantkong** [comment]
> 是不是开预读了 请考虑设备性能问题
 [域名预先获取功能] 这个也关闭，只是开了china的白名单和黑名单

**Comment by pymumu** [comment]
发log

**Comment by yyysuo** [comment]
> 是不是开预读了 请考虑设备性能问题

预计对性能的要求很高吗，我几个月下来，缓存里面积累了大约3万条记录，按作者大佬的设计，估计每秒都有几十条dns过期缓存更新请求。

**Comment by PikuZheng** [comment]
> 预计对性能的要求很高吗，我几个月下来，缓存里面积累了大约3万条记录，按作者大佬的设计，估计每秒都有几十条dns过期缓存更新请求。预取本来是提高dns过期缓存的准确度的，如果增加了路由的负载，导致正常的dns请求排队，是不是就不合算了？如何衡量存在大量过期缓存的情况下，预取功能的最终结果是否是正面的？

我家里的场景下不会有那么多缓存，内存用量一直在100M多一点。但是压力测试时曾发现6万多端口占满以致无法有新建连接。
我认为需要关注CPU、内存用量和端口打开数量。多个DNS查询时是并发的，不是排队，要么成功，要么超时。

**Comment by iamyangyiok** [comment]
7621 性能不足，就要搞这多了

**Comment by iamyangyiok** [comment]
7621 性能不足，就不要搞这多了。把缓存设小点，
