### ISSUE TITLE
建议luci的界面比照luci-app-openclash增加更新luci和二进制的功能！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1416]
目前luci和源码更新后，如需最新的版本，必须再次编译或者卸载再重新安装，目前很多人并不愿意重新编译，而卸载再重新安装很麻烦。如果增加按架构更新luci和二进制功能，起码能更好的使用smartdns新增功能。

**Comment by crackerfly** [comment]
不接受建议

**Comment by zxlhhyccc** [comment]
> 不接受建议

你是原作者大佬么？

**Comment by crackerfly** [comment]
> 

我不是,  但是
- openclash 是 luci only软件, luci是充分必要环境
- smartdns 是 全平台软件, luci只是锦上添花的东西,  可有可无,  甚至作者自己都几乎不用luci

**Comment by openips** [comment]
二进制就是core 本来就是单独更新的

**Comment by crackerfly** [comment]
> > 二进制就是core 本来就是单独更新的
> 
> 这个我是知道的，我的意思是通过luci直接更新不是更好吗？

并不，没有意义

**Comment by pymumu** [comment]
[easy-smartdns.zip](https://github.com/pymumu/smartdns/files/11594902/easy-smartdns.zip)

自动安装配置的脚本，写了一半，可以参考改改。
