### ISSUE TITLE
特定组的域名通过smartdns解析后相应ip不能加进nftset或ipset

### ISSUE THREAD

**Issue by niclau** [pymumu/smartdns#1417]
**问题现象**  
如标题所示，初次使用smartdns和nftables，望多多指教

**运行环境**
1. 固件型号  
nanopi r5c
ImmortalWrt 23.05-SNAPSHOT r26406-8a272a9fc8

2. 运营商  
中国电信
3. smartdns来源以及版本
opkg install smartdns luci-app-smartdns
smartdns - 42-1

4. 涉及的配置(注意去除个人相关信息)
自行新增以下nftables规则：

```
table ip nat {
        set gfwlist_set {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { 1.1.1.1, 8.8.8.8 } #手动添加1.1.1.1 8.8.8.8
        }

        chain prerouting {
                type nat hook prerouting priority dstnat; policy accept;
                meta l4proto tcp ip daddr @gfwlist_set redirect to :1080
        }

        chain output {
                type nat hook output priority -100; policy accept;
                meta l4proto tcp ip daddr @gfwlist_set redirect to :1080
        }
}
```
smartdns配置：
```
root@ImmortalWrt:~# cat /var/etc/smartdns/smartdns.conf
server-name smartdns
cache-size 20000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl 3600
rr-ttl-min 5
log-size 64K
log-num 1
log-level error
cache-persist no
force-qtype-SOA  65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind :6053@br-lan
bind :6053@lo
server-tcp 8.8.8.8  -group gfw -exclude-default-group
server-tcp 1.1.1.1  -group gfw -exclude-default-group
server 223.5.5.5
server 119.29.29.29
domain-set -name domain-block-list -file /etc/smartdns/domain-block.list
domain-rules /domain-set:domain-block-list/ --address #
domain-set -name domain-rule-list-cfg07524b -file '/etc/smartdns/domain-set/gfw.conf'
domain-rules /domain-set:domain-rule-list-cfg07524b/  -nameserver gfw -speed-check-mode none -nftset '#4:ip#nat#gfwlist_set'
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
```

gfw.conf使用gfwlist2smartdns生成，内容类似这样：
nameserver /.google.com/GFW  
nameserver /.google.co.ma/GFW
nameserver /.google.com.af/GFW
nameserver /.google.com.ag/GFW
nameserver /.google.com.ai/GFW

**重现步骤**
1. 上游DNS配置。  
server-tcp 8.8.8.8  -group gfw -exclude-default-group
server-tcp 1.1.1.1  -group gfw -exclude-default-group
server 223.5.5.5
server 119.29.29.29

2. 访问的域名。  
所有gfw.conf中的域名，如google.com等，解析的IP正确，但相应IP没有加进nftset
root@ImmortalWrt:~# dig +short @127.0.0.1 -p 6053 www.google.com
142.251.42.228

经查看1.1.1.1已重定向到透明代理
root@ImmortalWrt:~# curl https://1.1.1.1/cdn-cgi/trace
fl=65xxxxx
h=1.1.1.1
ip=104.28.x.x
ts=16850xxxxxx
visit_scheme=https
uag=curl/8.0.1
colo=EWR
sliver=010-ewr13
http=http/2
loc=US
tls=TLSv1.3
sni=off
warp=on
gateway=off
rbi=off
kex=X25519

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
没能从/var/log下找到smartdns log

3. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
请先证实ip list存在，如果不存在，需要手动建好

**Comment by niclau** [comment]
> 请先证实ip list存在，如果不存在，需要手动建好

谢谢，找到原因了，gfw.conf里只能有域名。
