### ISSUE TITLE
请问怎么编译 openwrt arm32 的二进制文件啊

### ISSUE THREAD

**Issue by saybeking** [pymumu/smartdns#1418]
`bash package/build-pkg.sh --platform linux --arch x86-64  --static` 没问题，可以得到 linux 下可以运行的二进制文件。
`bash package/build-pkg.sh --platform openwrt --arch <[arm|arm32]>  --static`  可以生成 ipk 文件,运行`tar xvf *.ipk`解压后找到名为 smartdns 的二进制文件，上传到 openwrt 下无法运行。
google 也没有找到正确的编译方法。

---
编译系统：
Debian 11 (bullseye)
openssl version: 1.1.1n  15 Mar 2022

---
测试运行系统：
❯ cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.2'
DISTRIB_TARGET='mvebu/cortexa9'
DISTRIB_ARCH='arm_cortex-a9_vfpv3-d16'

**Comment by pymumu** [comment]
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a9/packages/smartdns_1.2023.42-1_arm_cortex-a9.ipk
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a9/luci/luci-app-smartdns_1.2023.42_all.ipk
https://downloads.openwrt.org/snapshots/packages/arm_cortex-a9/luci/luci-i18n-smartdns-zh-cn_git-23.141.77221-8a2ace1_all.ipk

**Comment by PikuZheng** [comment]
在arm架构的系统上才能直接用这个命令编译，否则需要x86系统下的aem架构交叉编译工具。
最简单的方法是用别人编译好的（看看我的）。或者拿qemu跑个arm的系统。

**Comment by saybeking** [comment]
> 在arm架构的系统上才能直接用这个命令编译，否则需要x86系统下的aem架构交叉编译工具。 最简单的方法是用别人编译好的（看看我的）。或者拿qemu跑个arm的系统。

谢谢您和作者的回复，我已经安装了 [arm 交差编译套件](https://snapshots.linaro.org/gnu-toolchain/13.0-2022.11-1/arm-linux-gnueabihf/gcc-linaro-13.0.0-2022.11-x86_64_arm-linux-gnueabihf.tar.xz)并正确配置的环境变量，并且已经安装了 `libssl-dev` 软件包, `ls /usr/include/openssl/` 也能看到软件包包含的头文件。但是，执行 `bash package/build-pkg.sh --platform openwrt --arch arm --cross-tool arm-linux-gnueabihf- --static` 会报如下错误，说找不到上述头文件，请问该如何解决啊？

```
dns_client.c:43:10: fatal error: openssl/err.h: 沒有此一檔案或目錄
   43 | #include <openssl/err.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
smartdns.c:36:10: fatal error: openssl/err.h: 沒有此一檔案或目錄
   36 | #include <openssl/err.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
util.c:38:10: fatal error: openssl/crypto.h: 沒有此一檔案或目錄
   38 | #include <openssl/crypto.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<內建>：smartdns.o] 錯誤 1
make[1]: *** 正在等待未完成的作業....
make[1]: *** [<內建>：dns_client.o] 錯誤 1
make[1]: *** [<內建>：util.o] 錯誤 1
dns_server.c:40:10: fatal error: openssl/err.h: 沒有此一檔案或目錄
   40 | #include <openssl/err.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [<內建>：dns_server.o] 錯誤 1
make[1]: 離開目錄「/home/userx/Documents/github/smartdns/src」
make: *** [Makefile:29：SMARTDNS_BIN] 錯誤 2
make: 離開目錄「/home/userx/Documents/github/smartdns」
make smartdns failed
```

**Comment by pymumu** [comment]
交叉编译工程缺少openssl，你安装的libssl-dev，估计是装到了HOST上，不能用的。

另外编译static程序，不要用glibc，glibc有部分函数是不支持静态编译的，会有问题。
如果要编译静态程序，可以用crosstool-ng来编译，用musl。也可以这里下载musl的交叉工具链https://musl.cc/

然后用交叉工具链编译openssl，将生成的libssl.a和libcrypto.a复制到工具链的usr/lib目录中，openssl的头文件复制到usr/include目录中

然后再编译smartdns。

当然最好就直接用已经编译好的。
非静态编译的用openwrt官网提供的，静态编译的用https://github.com/pymumu/smartdns/releases/tag/Release42

**Comment by saybeking** [comment]
利用搜索引擎，找到了很多相关资料，用来参考尝试了几把交叉编译都没能成功。对于我这种不懂编程的人，自己编译成本太高，不想继续折腾了。还是选择用op官方或者作者大大编译好的二进制文件省心省力。
