### ISSUE TITLE
rock pi4 按照报错

### ISSUE THREAD

**Issue by thb007** [pymumu/smartdns#142]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
root@linaro-alip:/home/linaro# uname -a
Linux linaro-alip 4.4.154-78-rockchip-00017-g625c2b2 #2 SMP Thu Mar 28 20:07:37 CST 2019 aarch64 GNU/Linux

root@linaro-alip:/home/linaro# tar zxf smartdns.1.2019.04.02-0832.x86_64.tar.gz
root@linaro-alip:/home/linaro# cd cd smartdns
bash: cd: too many arguments
root@linaro-alip:/home/linaro# cd smartdns
root@linaro-alip:/home/linaro/smartdns# ls
LICENSE  ReadMe.md  ReadMe_zh-CN.md  etc  install  package  src  systemd
root@linaro-alip:/home/linaro/smartdns# chmod +x ./install
root@linaro-alip:/home/linaro/smartdns# ./install -i
install: creating directory '/etc/smartdns'
'src/smartdns' -> '/usr/sbin/smartdns'
'etc/smartdns/smartdns.conf' -> '/etc/smartdns/smartdns.conf'
'etc/default/smartdns' -> '/etc/default/smartdns'
'etc/init.d/smartdns' -> '/etc/init.d/smartdns'
'systemd/smartdns.service' -> '/lib/systemd/system/smartdns.service'
Synchronizing state of smartdns.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable smartdns
Created symlink /etc/systemd/system/smartdns.service → /lib/systemd/system/smartdns.service.
Job for smartdns.service failed because the control process exited with error code.
See "systemctl status smartdns.service" and "journalctl -xe" for details.
root@linaro-alip:/home/linaro/smartdns# systemctl status smartdns.service
● smartdns.service - smart dns server
   Loaded: loaded (/lib/systemd/system/smartdns.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-04-08 22:20:47 CST; 388ms ago
  Process: 3066 ExecStart=/usr/sbin/smartdns $SMART_DNS_OPTS (code=exited, status=203/EXEC)

**Comment by pymumu** [comment]
你应该获取arm的版本，你安装的这个是x86-64的。
用树莓派的那个试试吧
