### ISSUE TITLE
请问有没有清除smartdns解析结果缓存的指令啊？

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#1421]
在一些特殊条件下，系统会有个别被污染的解析结果，想清理一下缓存

**Comment by PikuZheng** [comment]
https://github.com/pymumu/smartdns/issues/1404#issuecomment-1547160353

**Comment by pymumu** [comment]
先停止smartdns，然后删除cache文件。
默认情况下，cache文件在
/etc/smartdns/smartdns.cache
/tmp/smartdns.cache
/var/cache/smartdns/smartdns.cache

**Comment by 4thanks** [comment]
> 先停止smartdns，然后删除cache文件。 默认情况下，cache文件在 /etc/smartdns/smartdns.cache /tmp/smartdns.cache /var/cache/smartdns/smartdns.cache

难怪我删/etc/smartdns/smartdns.cache，重启之后又有一样大小cache，原来有3个地方。
我是关掉持久化缓存，删/etc/smartdns/smartdns.cache，然后再开启持久化缓存，cache才是从0开始。
