### ISSUE TITLE
使用smartdns之后 clash报文大量error，都是iOS推送的ip

### ISSUE THREAD

**Issue by NoWayda** [pymumu/smartdns#1423]
马赛克涂掉的是PPPoE wan口获取到的ip地址。
![7aa9ef8533d8b198a78da7aa9a8d4dc](https://github.com/pymumu/smartdns/assets/95454929/092c8003-7386-4df9-88ce-368b5033f862)

**Comment by NoWayda** [comment]
关闭tcp之后问题依旧，求大佬们赐教~

**Comment by PikuZheng** [comment]
17.57.145.x 看起来ip是正确的，但连接被墙了（connect reset）？

**Comment by NoWayda** [comment]
我是刚开始捣鼓的新手，原理啥的还没太清晰。但是用了很多方法，关闭IPv6，关闭TCP，openclash全都用直连，都没有解决。。不用smartdns，或者用mosdns就都没有问题。纯猜的话，是不是smartdns把iOS推送的域名解析到了国外，所以被墙了？

**Comment by PikuZheng** [comment]
> openclash全都用直连，都没有解决。

要不先试试全都用不直连？

**Comment by NoWayda** [comment]
> > openclash全都用直连，都没有解决。
> 
> 要不先试试全都用不直连？

好像都匹配到others或者漏网之鱼，都是80端口。然后others全都用proxy的话好像没有这些错误了。

**Comment by NoWayda** [comment]
还有一个情况就是其他的手机APP请求显示的都是192.168.*（就是手机的内网ip），只有苹果的推送请求是wan口的ip。全都用proxy就没有问题了。smartdns我已经尽量精简了，只设置了一个国内dns。

**Comment by cresky-github** [comment]
这个问题，其实很简单。
smartdns出去的流量，用geoip:cn判定一下。
geoip:cn，直连
其余，走代理。

**Comment by NoWayda** [comment]
> 这个问题，其实很简单。 smartdns出去的流量，用geoip:cn判定一下。 geoip:cn，直连 其余，走代理。

我用mosdns先分流了，只有国内的才转到smartdns解析，不知道为啥还是这样。如果不是smartdns的问题我就先不管了，但是实验了好多排列组合，都是启用smartdns就这样，所以来求教一下~

**Comment by pymumu** [comment]
国外的查询如果走代理，关掉测速。

**Comment by cresky-github** [comment]
> > 这个问题，其实很简单。 smartdns出去的流量，用geoip:cn判定一下。 geoip:cn，直连 其余，走代理。
> 
> 我用mosdns先分流了，只有国内的才转到smartdns解析，不知道为啥还是这样。如果不是smartdns的问题我就先不管了，但是实验了好多排列组合，都是启用smartdns就这样，所以来求教一下~

只用smartdns就行了

**Comment by cresky-github** [comment]
还有一点：
国外域名用8888之类国外DNS解析，完全是多余的，不必要的。

**Comment by openips** [comment]
dns污染不是常事吗 不配置几个国外非udp的dns 怎么对比

**Comment by yyysuo** [comment]
观察到了与题主完全相同的现象。
dns路径：Adguard Home-》openclash（nameserver与fallback均为mosdns）-》mosdns（分流）-》对接smartdns国内国外2个端口

此问题也可能与机场的clash配置文件有关，我用奶昔的配置文件有此问题，用魅影的配置文件就没问题。

**Comment by NoWayda** [comment]
> 观察到了与题主完全相同的现象。 dns路径：Adguard Home-》openclash（nameserver与fallback均为mosdns）-》mosdns（分流）-》对接smartdns国内国外2个端口
> 
> 此问题也可能与机场的clash配置文件有关，我用奶昔的配置文件有此问题，用魅影的配置文件就没问题。

我有两个问题没搞清楚，为什么数据请求是从wan口出去的，不是从手机ip出去的。再就是你可以试一试，路径里面没有smartdns好像就没有这个问题。

**Comment by yyysuo** [comment]
> > 观察到了与题主完全相同的现象。 dns路径：Adguard Home-》openclash（nameserver与fallback均为mosdns）-》mosdns（分流）-》对接smartdns国内国外2个端口
> > 此问题也可能与机场的clash配置文件有关，我用奶昔的配置文件有此问题，用魅影的配置文件就没问题。
> 
> 我有两个问题没搞清楚，为什么数据请求是从wan口出去的，不是从手机ip出去的。再就是你可以试一试，路径里面没有smartdns好像就没有这个问题。

我就是试过了，才说遇到了与你完全相同的问题啊，把smartdns去掉就不会有warn类型的日志了。源IP是wan口公网ip，连接是公网ip的80端口，查了一下ip归属，也确实是苹果公司的美国ip，不知道为什么连接会被拒绝。

这个问题的性质目前还是无法确定的，小白乱猜有可能是smartdns发送dns请求的时候处理方式跟mosdns不一样？他们全都是在主路由的wan区域。或者说是产生了dns污染？其实获取到的apple公司的美国ip是不可用的？比如这个IP 17.36.202.136.

**Comment by yyysuo** [comment]
使用smartdns时的openclash日志
[TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:48472 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: i/o timeout
[TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:41958 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused
[TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:50658 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused | dial tcp 17.36.202.159:80: connect: connection refused

不使用smartdns的openclash日志
[TCP] 10.10.10.100:39640 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT]
[TCP] 10.10.10.100:39860 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT]

**Comment by NoWayda** [comment]
> 使用smartdns时的openclash日志 [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:48472 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: i/o timeout [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:41958 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:50658 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused | dial tcp 17.36.202.159:80: connect: connection refused
> 
> 不使用smartdns的openclash日志 [TCP] 10.10.10.100:39640 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT] [TCP] 10.10.10.100:39860 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT]

我也糊涂了。。哈哈，但是好像用楼上大哥说的，配置几个国外非udp的dns，情况会好一些，估计就是污染了吧，但是用smartdns才会被污染吗？

**Comment by yyysuo** [comment]
> > 使用smartdns时的openclash日志 [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:48472 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: i/o timeout [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:41958 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:50658 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused | dial tcp 17.36.202.159:80: connect: connection refused
> > 不使用smartdns的openclash日志 [TCP] 10.10.10.100:39640 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT] [TCP] 10.10.10.100:39860 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT]
> 
> 我也糊涂了。。哈哈，但是好像用楼上大哥说的，配置几个国外非udp的dns，情况会好一些，估计就是污染了吧，但是用smartdns才会被污染吗？

我配置的有国外的dot，不管用。

**Comment by pymumu** [comment]
分流没那么困难，不要想太复杂。

1. 先配置好默认的DNS服务，国内，国外的都可以配置。开启过期缓存等基本能力（默认配置）
2. 需要将分流的域名，整理成一个列表，使用domain-set加载
3. 将上述列表中的域名使用domain-rules，设置规则：
   * -nameserver使用特定的DNS服务器，DOH，DOT等，如果要使用UDP协议，最好走代理，一般就不要直连。
   * -speed-check-mode关闭测速。
   * -address禁用IPV6地址。
4. 如果要配合透明代理使用，上述规则增加ipset或nftset设置。

一个参考：（电信适用）
```
server 223.5.5.5
server 114.114.114.114
server 1.0.0.1 -check-edns -group oversea -drop-packet-latency 30
server 8.8.8.8 -check-edns -group oversea -drop-packet-latency 30
server 9.9.9.9 -check-edns -group oversea -drop-packet-latency 30
server 101.102.103.104 -check-edns -group oversea -drop-packet-latency 30
server-https https://doh.sb/dns-query -group oversea -host-name -
domain-set -name oversea-domain -file /path/to/domain/list.txt
domain-rules /domain-set:oversea-domain/ -ipset oversea-domain -c none -nameserver oversea
ipset-timeout yes
```

/path/to/domain/list.txt自行配置。

文档：
https://pymumu.github.io/smartdns/config/forwarding-with-ipset/

**Comment by openips** [comment]
> > 使用smartdns时的openclash日志 [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:48472 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: i/o timeout [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:41958 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:50658 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused | dial tcp 17.36.202.159:80: connect: connection refused
> > 不使用smartdns的openclash日志 [TCP] 10.10.10.100:39640 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT] [TCP] 10.10.10.100:39860 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT]
> 
> 我也糊涂了。。哈哈，但是好像用楼上大哥说的，配置几个国外非udp的dns，情况会好一些，估计就是污染了吧，但是用smartdns才会被污染吗？

openclash里面把nameserver配置为smartdns fallback和default-nameserver全部删除  SMARTDNS里面国内的用udp 国外的用非udp 亲测很稳

**Comment by NoWayda** [comment]
> > > 使用smartdns时的openclash日志 [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:48472 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: i/o timeout [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:41958 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused [TCP] dial 🍎 Apple (match DomainSuffix/apple.com) 我的公网IP:50658 --> p43-buy.itunes.apple.com:80 error: dial tcp 17.36.202.136:80: connect: connection refused | dial tcp 17.36.202.159:80: connect: connection refused
> > > 不使用smartdns的openclash日志 [TCP] 10.10.10.100:39640 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT] [TCP] 10.10.10.100:39860 --> p43-buy.itunes.apple.com:443 match DomainSuffix(apple.com) using 🍎 Apple[DIRECT]
> > 
> > 
> > 我也糊涂了。。哈哈，但是好像用楼上大哥说的，配置几个国外非udp的dns，情况会好一些，估计就是污染了吧，但是用smartdns才会被污染吗？
> 
> openclash里面把nameserver配置为smartdns fallback和default-nameserver全部删除 SMARTDNS里面国内的用udp 国外的用非udp 亲测很稳

其实一直用的也很稳，速度也挺快，就是不知道clash这些错误报文到底是咋回事，奇怪的是只用smartdns才会有，来学习一下，如果不看报文啥事没有，用的挺好。

**Comment by pymumu** [comment]
发出问题的时候，smartdns对应的log

**Comment by yyysuo** [comment]
破案了，是smartdns的测速行为导致smartdns程序本身从路由的wan域（公网IP）连接apple公司在美国ip的80或者443端口，而不是每个IP的这2个端口都是可用的。openclash默认代理了路由本身流量的tcp 80和tcp 443，因为smartdns的测速连接会出现在openclash的日志当中，所以这个日志是正常的。
如果不想要这个日志，有如下解决方案
1：把测速模式改为自定义，写ping（无法评价对优选ip的影响），或者改为none（无）。
2：openclash不代理路由本身流量（不建议）

**Comment by NoWayda** [comment]
> 破案了，是smartdns的测速行为导致smartdns程序本身从路由的wan域（公网IP）连接apple公司在美国ip的80或者443端口，而不是每个IP的这2个端口都是可用的。openclash默认代理了路由本身流量的tcp 80和tcp 443，因为smartdns的测速连接会出现在openclash的日志当中，所以这个日志是正常的。
> 如果不想要这个日志，有如下解决方案
> 1：把测速模式改为自定义，写ping（无法评价对优选ip的影响），或者改为none（无）。
> 2：openclash不代理路由本身流量（不建议）

好顶赞 非常感谢🙏

**Comment by cresky-github** [comment]
> 破案了，是smartdns的测速行为导致smartdns程序本身从路由的wan域（公网IP）连接apple公司在美国ip的80或者443端口，而不是每个IP的这2个端口都是可用的。openclash默认代理了路由本身流量的tcp 80和tcp 443，因为smartdns的测速连接会出现在openclash的日志当中，所以这个日志是正常的。
> 如果不想要这个日志，有如下解决方案
> 1：把测速模式改为自定义，写ping（无法评价对优选ip的影响），或者改为none（无）。
> 2：openclash不代理路由本身流量（不建议）



换句话说，就是DNS没走代理所致？

**Comment by yyysuo** [comment]
> 
不准确。这个错误最直接的原因就是smartdns向上游dns查询某个域名，获得了一些ip，然后根据smartdns配置的测速模式与首次响应模式去测速，连接80端口时被拒绝了，这些IP是否走代理，是根据openclash的分流规则确定的；至于dns请求时是否走了代理，这取决于上游公共dns是ip还是域名，这些ip和域名命中了哪个分流规则。

**Comment by cresky-github** [comment]
> > 
> 不准确。这个错误最直接的原因就是smartdns向上游dns查询某个域名，获得了一些ip，然后根据smartdns配置的测速模式与首次响应模式去测速，连接80端口时被拒绝了，这些IP是否走代理，是根据openclash的分流规则确定的；至于dns请求时是否走了代理，这取决于上游公共dns是ip还是域名，这些ip和域名命中了哪个分流规则。



其实，国外组用1111，8888，9999...之类的real-DNS解析是完全没有必要的，是多余的。用fak-DNS(clash-DNS)就好了。

由于是内网，1ms内就得到国外组域名解析结果。

**Comment by NoWayda** [comment]
> > 
> 
> 不准确。这个错误最直接的原因就是smartdns向上游dns查询某个域名，获得了一些ip，然后根据smartdns配置的测速模式与首次响应模式去测速，连接80端口时被拒绝了，这些IP是否走代理，是根据openclash的分流规则确定的；至于dns请求时是否走了代理，这取决于上游公共dns是ip还是域名，这些ip和域名命中了哪个分流规则。

这个域名是哪个域名，我想把他放到mosdns远程不测速里面，这样不影响其他又不会有这种warn

**Comment by yyysuo** [comment]
> > > 
> > 
> > 
> > 不准确。这个错误最直接的原因就是smartdns向上游dns查询某个域名，获得了一些ip，然后根据smartdns配置的测速模式与首次响应模式去测速，连接80端口时被拒绝了，这些IP是否走代理，是根据openclash的分流规则确定的；至于dns请求时是否走了代理，这取决于上游公共dns是ip还是域名，这些ip和域名命中了哪个分流规则。
> 
> 这个域名是哪个域名，我想把他放到mosdns远程不测速里面，这样不影响其他又不会有这种warn

这个测试行为是smartdns的行为，为什么要在mosdns里面设置规则呢。另外不建议自己手撸规则，这种域名也不只是ios有，也不只是只有1类，手撸不现实，还是那句话，用openclash的话，smartdns就不建议测速了，openclash自己的设置和分流规则会影响到smartdns ，不好梳理这些影响。

**Comment by openips** [comment]
加个http测速就行了 tcp测速代理后不准确
