### ISSUE TITLE
求助：能否对domain-set取反，或者对没有可用server的请求返回SOA

### ISSUE THREAD

**Issue by PMExtra** [pymumu/smartdns#1424]
**需求应用场景**
我的使用场景比较特殊，在一个严格审计的网络环境中，通过smatdns作为DNS服务器，管理可以被解析的白名单域名（防止用户通过DNS查询传出数据，当用户拥有一个域名的时候，通过将NS指向特定的服务器，然后将数据载荷作为前缀进行域名查询就可能制造意外的数据外泄）。

也就是，我设置了一个 domain-set 其中存储了白名单域名，只有这些域名会通过特定的通道发出公网查询，其余域名均匹配不上任何可用的server从而解析失败。

但是，客户端对于解析失败的域名可能多次重试，从而导致页面长时间卡顿。也对DNS服务器制造了不必要的压力，日志中会产生大量的 `Send query to upstream server failed, total server number 0`。

**建议的方案**
1. 支持对domain-set取反，即不匹配某个domain-set时执行规则，例如假设以 `-` 表示取反：
```
nameserver /domain-set:allowed/internetdns
address /domain-set:-allowed/#
```

2. 默认对于 `tatal server number 0` 这种情况返回SOA，或者允许配置这种情况下的响应方式，从而避免客户端重复发起请求。

**设备信息**
无关

**Comment by ArchGuyWu** [comment]
附议，我做DNS解锁也有这需求

**Comment by pymumu** [comment]
```
force-qtype-SOA 1,2,3,4,28
address /domain-set:allowed/-
```

这样，但qtype要屏蔽1~65535，按目前的代码，只能写1，2，3，。。。65535.
你可以先验证看看，如果OK的话，force-qtype-SOA 后面可以增加range，也就是单写1-65535就可以。

**Comment by PMExtra** [comment]
```
address /domain-set:allowed/-
```
没太懂这个代码的效果，文档中所说的“**忽略**”是什么意思，是指所有全局配置都对这个domain-set不起作用吗？

**Comment by PMExtra** [comment]
https://github.com/pymumu/smartdns/blob/f5c8d3ce579a0aff8ac2c23d7cd6e1e380ea2ad6/src/dns_server.c#L578-L581
噢，全局搜了下 `DOMAIN_FLAG_ADDR_IGN` 似乎只影响 `force-qtype-SOA` ，这个设计有点奇怪，文档也没有说清楚。
不过我之前对于 `allowed` 之中的 `28 33 65` 还是要做 SOA 的。

按照您建议的这个方案，好像会没办法指定 `allowed` 列表中的 `force-qtype-SOA` 。

**Comment by pymumu** [comment]
address /domain-set:allowed/-4

只允许IPV4的查询。

**Comment by pymumu** [comment]
改了下代码，force-qtype-SOA支持range的写法。

force-qtype-SOA 1-65535

占用内存大约1M。

**Comment by ArchGuyWu** [comment]
> address /domain-set:allowed/-4
> 
> 只允许IPV4的查询。
> 
> https://pymumu.github.io/smartdns/config/block-ipv6/
> 
> 目前没有针对单个域名设置qtype SOA。单个域名只有A，AAAA记录可以设置SOA。

假如我设置了force-qtype-SOA 1,28，然后在配置里指定了address和cname项，那这两项还能使用吗？

**Comment by pymumu** [comment]
可以

**Comment by ArchGuyWu** [comment]
> 可以

确实，感谢
