### ISSUE TITLE
请教个问题我在内网用centos搭建了一个服务，其它机器用了DNS打开不了网页

### ISSUE THREAD

**Issue by langbinlee** [pymumu/smartdns#1425]
**问题现象**  
我在内网用centos搭建了一个smardns服务后，其它机器用了这个DNS打开不了网页

**运行环境**
1. 固件型号  
无
2. 运营商  
电信
3. smartdns来源以及版本
最新
4. 涉及的配置(注意去除个人相关信息)
默认配置

有没有人帮忙解决一下

**Comment by pymumu** [comment]
发log

**Comment by langbinlee** [comment]
> 发log

是防火墙的问题。防火墙禁止了UDP端口，只开放了TCP的。但是有一个疑问。我只开TCP的也用不了。只能用udp的端口吗？

**Comment by PikuZheng** [comment]
问下你的其他机器支持tcp dns吗
