### ISSUE TITLE
发现一个奇怪的现象

### ISSUE THREAD

**Issue by saybeking** [pymumu/smartdns#1429]
配置：双栈优选没有去配置默认打开，测速没有用选项去配置保持默认。
去除这个 `dualstack-ip-allow-force-AAAA yes` 选项，`dig mirrors.rockylinux.org` 得到结果：

```
mirrors.rockylinux.org. 596     IN      CNAME   rockylinux.map.fastly.net.
rockylinux.map.fastly.net. 596  IN      A       199.232.198.132
rockylinux.map.fastly.net. 596  IN      A       199.232.194.132
```
`dig rockylinux.map.fastly.net` 得到结果：

```
rockylinux.map.fastly.net. 536  IN      A       199.232.198.132
rockylinux.map.fastly.net. 536  IN      A       199.232.194.132
```

---

加上 `dualstack-ip-allow-force-AAAA yes` 选项，`dig mirrors.rockylinux.org` 得到结果：

```
mirrors.rockylinux.org. 3       IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
```
可以看到解析失败了，但是查询其它没有 cname 的纯 ipv4 域名可以解析出来。上面这个纯 ipv4 域名多了 cname ，就解析失败啦。

---

**Comment by PikuZheng** [comment]
```
nslookup mirrors.rockylinux.org. 11.20.3.171
....
非权威应答:
名称:    rockylinux.map.fastly.net
Addresses:  2a04:4e42:87::644
          146.75.94.132
Aliases:  mirrors.rockylinux.org
```
可能有其他规则，禁止了该域名的ipv6；dualstack-ip-allow-force-AAAA 禁止了该域名的ipv4，最终导致该域名没结果

**Comment by saybeking** [comment]
> 可能有其他规则，禁止了该域名的ipv6；dualstack-ip-allow-force-AAAA 禁止了该域名的ipv4，最终导致该域名没结果

没有其它规则禁止该域名的 ipv6 啊， `dualstack-ip-allow-force-AAAA`  文档中解析是:
>“允许纯IPV6地址。smartdns默认情况下总是会返回IPV4地址，原因时某些软件不具备IPV6的访问能力，但如果确实需要使用纯IPV6地址，可以设置允许smartdns仅优选IPV6。“

我理解的是，开启 `dualstack-ip-allow-force-AAAA` ,如果域名只有 ipv6 当然使用 ipv6,域名同时有ipv6和ipv4使用ipv6,只有ipv4使用ipv4.     
是不是我理解错了，文档想表达的应该是，开启 `dualstack-ip-allow-force-AAAA` ，要么只能获取到 Ipv6 地址，要么就无法获取到地址。

但测试的结果是开启这个选项，有的域名可以获得 ipv4 地址，有的域名无法获得地址。关选项后，之前不能解析了也变得能正常解析了。

**Comment by pymumu** [comment]
参数的意思就是是否开启强制ipv6优选。也就是当ipv6速度比ipv4好时，是否强制客户端使用ipv6。

实现上，开启这个开关后，当ipv6比ipv4要快的时候，查询A记录的时，就会返回SOA

但是有少部分软件，不支持ipv6，强制启用这个参数，就可能导致那些软件上不了网。
