### ISSUE TITLE
没有可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录，以及subnet问题？

### ISSUE THREAD

**Issue by otaku0721** [pymumu/smartdns#1431]
**问题现象**  
![9a83cad44d71eb1efea979ff7548f05](https://github.com/pymumu/smartdns/assets/23144521/61b89404-7aa4-4551-afcc-2f35faf890a9)
很久之前就发现这个问题了，当时是指定了两个dns服务器，一个获取猪宽dns，但是屏蔽掉返回移动的ip
一个获取电信的。
之前还是用缓存的时候，就会在一些域名上报“没有可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录”，我就很奇怪，将缓存改为0后又能获取到地址了
现在不用缓存了，今天被我抓到故障了
从上图中，我可以肯定这两个IP都是由223.5.5.5这个dns产生的，因为猪宽不会返回这两个地址。
但是前两次获取到的IP就是subnet取得的IP，下面这个bsg.w.bilicdn1.com的IP就是不附带subnet获得的IP，然后继续nslookup后就直接“没有可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录”了
会不会是subnet参数有问题？
而且“没有可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录”似乎会进缓存
简单点描述就是subnet好像有时候会失效，而且
“没有可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录”也会进入缓存
![82d4f96fcd234d4b561397cbaf4cd56](https://github.com/pymumu/smartdns/assets/23144521/eb6c8209-069e-4a38-9903-aec88eaaeb27)
**而且我现在好奇一件事就是“没有可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录”这故障究竟是223.5.5.5产生的，还是smartdns本身的问题？**
如果猪宽返回了移动的地址就会过滤掉，在访问223.5.5.5没有拿到地址的情况下才应该会触发这个问题
但是我尝试过配置多个dns（223.5.5.5 223.6.6.6 223.6.6.5，开启subnet），均会产生这个问题
所有223.5.5.5,223.6.6.6,223.6.6.5都是TCP查询，猪宽有udp dns劫持
因为这个故障很难复现，通常要运行一个多小时才有故障，加上路由器flash少，所以没办法抓日志

**运行环境**
1. 固件型号  
XDR6088 Openwrt

2. 运营商  
珠江宽频（走电信线路不是联通）

3. smartdns来源以及版本
https://github.com/PikuZheng/smartdns
版本无关，即便官方仓库版本亦有此问题

4. 涉及的配置(注意去除个人相关信息)
缓存0 最快IP 防火墙直接nat劫持到smartdns

**重现步骤**
1. 上游DNS配置。  
设置了两个dns服务器，一个是猪宽自己的DNS（黑名单使能，黑名单为移动IP，防止返回移动的IP）
一个是223.5.5.5 通过subnet指定电信IP

2. 访问的域名。  
不确定，哪一个域名都可能出现这个问题

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
发debug log

**Comment by pymumu** [comment]
另外，你可以看看这个：
https://www.cnblogs.com/followyourheart/p/openwrt_dns_rebinding_attacks_protection.html

可以windows出问题的时候，用其他设备看看能否正常访问。可以用ldig命令查询下看看。

**Comment by otaku0721** [comment]
![image](https://github.com/pymumu/smartdns/assets/23144521/2e475de9-279d-4f61-a8a1-29b34e15f003)
![image](https://github.com/pymumu/smartdns/assets/23144521/06a60002-f2d2-4786-981a-ac5d397e959b)
![image](https://github.com/pymumu/smartdns/assets/23144521
![image](https://github.com/pymumu/smartdns/assets/23144521/12621227-496f-4f1b-afbe-21996afe6857)
/c0f624f1-6520-4438-a359-1cd9a68f5f02)

**Comment by pymumu** [comment]
如果可以插u盘的话，可以插一个U盘，将log输出到U盘上。

**Comment by pymumu** [comment]
看得吃力，发配置文件把/var/etc/smartdns/smartdns.conf

**Comment by otaku0721** [comment]
> 看得吃力，发配置文件把/var/etc/smartdns/smartdns.conf

附加配置在上面那个zip文件里
server-name smartdns
speed-check-mode ping,tcp:443,tcp:80
dualstack-ip-selection no
prefetch-domain yes
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level error
response-mode first-ping
cache-persist no
force-qtype-SOA  28 65
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
bind :666 
bind-tcp :666 
server 202.96.128.166  -group zjsm2 -blacklist-ip 
server-tcp 223.5.5.5  -subnet 119.134.111.0/24
server 116.199.0.200  -group zjsm -exclude-default-group 
domain-set -name domain-block-list -file /etc/smartdns/domain-block.list
domain-rules /domain-set:domain-block-list/ --address #
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
面，但是我看了一眼好像主要的配置都不在里面

**Comment by otaku0721** [comment]
我尽可能抓一下日志

**Comment by pymumu** [comment]
看你的配置，有可能是这样得：
1 server 202.96.128.166 有ip黑名单，ip在黑名单里面得时候，就丢弃了记录。
2. 如果这时候server-tcp 223.5.5.5，查询失败，那么就没有结果了。

nslookup看到得，也就是那个错误。

具体有log的话，就可以更加明确。

可以开启audit-log，限制大小在128K，那个量会比较少，出问题的时候，看一下对应域名的结果。

**Comment by otaku0721** [comment]
> Owner

就是这个问题，我现在把日志保存在tmp目录试试
但是我不太清楚为什么会出现这些问题，尤其是上面那张图subnet甚至还失效了

**Comment by otaku0721** [comment]
> 看你的配置，有可能是这样的： 1 server 202.96.128.166 有ip黑名单，ip在黑名单里面得时候，就丢弃了记录。 2. 如果这时候server-tcp 223.5.5.5，查询失败，那么就没有结果了。
> 
> nslookup看到得，也就是那个错误。
> 
> 具体有log的话，就可以更加明确。
> 
> 可以开启audit-log，限制大小在128K，那个量会比较少，出问题的时候，看一下对应域名的结果。 你也可以把黑名单去掉，看看问题是否还有。

去除黑名单是没问题的

**Comment by pymumu** [comment]
那应该就是某段时间，没有可用IP地址了。

不清楚你用黑名单做什么？一般情况下都是不需要使用的。

特殊域名查询，分流用DOT，DOH查询就可以了。大部分域名都可以配置运营商，阿里的DNS就可以。

**Comment by otaku0721** [comment]
[smartdns1.log](https://github.com/pymumu/smartdns/files/11747742/smartdns1.log)
相关域名：i1.hdslb.com
otaku@ubuntu:~$ dig i1.hdslb.com 192.168.255.1

; <<>> DiG 9.16.1-Ubuntu <<>> i1.hdslb.com 192.168.255.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24614
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;i1.hdslb.com.			IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jun 14 08:26:20 PDT 2023
;; MSG SIZE  rcvd: 41

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64767
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;192.168.255.1.			IN	A

;; Query time: 44 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Jun 14 08:26:20 PDT 2023
;; MSG SIZE  rcvd: 42

**Comment by otaku0721** [comment]
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:5382] query i1.hdslb.com from 192.168.255.253, qtype: 1, id: 50987
[2023-06-14 23:20:05,306][DEBUG][     dns_client.c:3484] send query to server 223.5.5.5
[2023-06-14 23:20:05,306][DEBUG][     dns_client.c:3484] send query to server 202.96.128.166
[2023-06-14 23:20:05,306][ INFO][     dns_client.c:3850] request: i1.hdslb.com, qtype: 1, id: 38844, group: default
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:5347] recv query packet from 192.168.255.253, len = 30, type = 0
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:5359] request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 30, id = 51508, tc = 0, rd = 1, ra = 0, rcode = 0
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:5382] query i1.hdslb.com from 192.168.255.253, qtype: 65, id: 51508
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:4967] unsupported qtype: 65, domain: i1.hdslb.com
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:1863] reply i1.hdslb.com qtype: 65, rcode: 0, reply: 1
[2023-06-14 23:20:05,306][ INFO][     dns_server.c:1918] result: i1.hdslb.com, client: 192.168.255.253, qtype: 65, id: 51508, group: default, time: 0ms
[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:4557] force qtype 65 soa

**提示[2023-06-14 23:20:05,306][DEBUG][     dns_server.c:4967] unsupported qtype: 65, domain: i1.hdslb.com**

**Comment by pymumu** [comment]
大概看了一下，基本就是刚刚说的原因，223.5.5.5没有返回任何结果，运营商那个又在黑名单里面，导致没有可用ip

223.5.5.5的tcp查询是有问题的，或者说是不支持pipeline模式，你用腾讯的dns看看吧

**Comment by otaku0721** [comment]
多次实验后确定是223.5.5.5的tcp查询出现问题，非SmartDNS问题，感谢解答
