### ISSUE TITLE
SmartDNS周期性的查询dns.pub域名

### ISSUE THREAD

**Issue by Jingye-Xia** [pymumu/smartdns#1432]
**问题现象**  
SmartDNS本身会周期性的查询dns.pub域名，但是并未设置dns.pub为上游服务器，请问这是否是正常现象？

**运行环境**
1. 固件型号  
docker
2. 运营商  
电信
3. smartdns来源以及版本
pikuzheng/smartdns 1.2023.v42.0.7
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
有没有可能是你的下游在查询

**Comment by Jingye-Xia** [comment]
> 有没有可能是你的下游在查询

找到原因了：
IMAGE LAYERS
HEALTHCHECK &{["CMD-SHELL" "test `nslookup dns.pub 127.0.0.1 |grep answer |wc -l` -gt 0"] "5m0s" "0s" "0s" '\x00'}

**Comment by PikuZheng** [comment]
> > 有没有可能是你的下游在查询
> 
> 找到原因了：
> IMAGE LAYERS
> HEALTHCHECK &{["CMD-SHELL" "test `nslookup dns.pub 127.0.0.1 |grep answer |wc -l` -gt 0"] "5m0s" "0s" "0s" '\x00'}

我的镜像hhhhh
