### ISSUE TITLE
Failed to execute cbi dispatcher target for entry '/admin/services/smartdns'

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1433]
**问题现象**  
smartdns luci无法打开，报如下错误
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/smartdns'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: /usr/lib/lua/luci/model/cbi/smartdns/smartdns.lua:1: unexpected symbol
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:477: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

**运行环境**
1. 固件型号  
openwrt 内核 6.1.34
2. 运营商  
联通
3. smartdns来源以及版本
https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v42.0.10
[luci-app-smartdns.1.2023.v42.0.10.luci-compat-all.ipk](https://github.com/PikuZheng/smartdns/releases/download/1.2023.v42.0.10/luci-app-smartdns.1.2023.v42.0.10.luci-compat-all.ipk)
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
重复 #513 #271 
luci-app-smartdns...-compat 需要 luci-compat 包，opkg install luci luci-base luci-compat 请

**Comment by yyysuo** [comment]
> 重复 #513 #271 luci-app-smartdns...-compat 需要 luci-compat 包，opkg install luci luci-base luci-compat 请

前几个版本升级一直没问题的呀。

**Comment by yyysuo** [comment]
重新安装了一遍竟然可以了，估计弄错版本了。

**Comment by pymumu** [comment]
为什么不用js版本？
lua版本只是给18.0x系统用的

**Comment by yyysuo** [comment]
> 为什么不用js版本？ lua版本只是给18.0x系统用的

装不上啊，好像lean源码的固件都装不上，装上了不显示。
