### ISSUE TITLE
对于一些域名，当过滤后的  CND IP 确实是 ping 最低，但其实不是下载最快的

### ISSUE THREAD

**Issue by TomatoFryEggs** [pymumu/smartdns#1434]
比如：iosapps.itunes.apple.com

这种情况一般是怎么处理？

目前是指定了 DNS 。

**Comment by pymumu** [comment]
用ignore-ip选项，忽略速度慢的IP地址。

**Comment by TomatoFryEggs** [comment]
> 用ignore-ip选项，忽略速度慢的IP地址。

你有意思是说我遇到一个然后添加一个进来是吗？

**Comment by pymumu** [comment]
一般是一个网段，可以直接设置整个网段。
