### ISSUE TITLE
PikuZheng大佬最新编译的x86 openwrt版本，运行经常出现问题： kern.info kernel: [352139.424327] smartdns[568]: segfault at 988 ip 

### ISSUE THREAD

**Issue by liangxyz** [pymumu/smartdns#1436]
**问题现象**  
smartdns在openwrt x86上运行崩溃，系统日志显示 kern.info kernel: [352139.424327] smartdns[568]: segfault at 988 ip 00007f53ed921a91 sp 00007f53edd36560 error 6 in smartdns[7f53ed8c1000+33a000] likely on CPU 5 (core 5, socket 0)
Sun Jun 25 22:34:04 2023 kern.info kernel: [352139.424709] Code: 48 8b 85 d8 ce ff ff 8b 80 64 04 00 00 89 45 a4 c7 45 c0 00 00 00 00 48 8d 85 e0 ce ff ff 48 89 c7 e8 28 5a 00 00 48 8b 45 f8 <48> c7 80 60 08 00 00 00 00 00 00 48 8b 45 f8 48 83 c0 48 48 89 c7

**运行环境**
1. 固件型号  
ZUIKE_X7s build 2023.01.14 @ OpenWrt R23.1.1 / LuCI Master (git-23.006.42151-6e6effe)
2. 运营商  
中国电信
3. smartdns来源以及版本
PikuZheng大佬最新编译的x86 openwrt版本：smartdns.1.2023.v42.0.10.x86_64-openwrt.ipk 1.67MB
4. 涉及的配置(注意去除个人相关信息)
# https://github.com/pymumu/smartdns/blob/master/etc/smartdns/smartdns.conf
bind [::]:53
#bind [::]:54 -group out -no-speed-check

# dns cache size
# cache-size [number]
#   0: for no cache
cache-size 102400
cache-persist yes
#cache-file /root/smartdns/smartdns.cache

dualstack-ip-selection no
max-reply-ip-num 25
cache-persist no
prefetch-domain yes
serve-expired no
#serve-expired-prefetch-time 21600
#serve-expired-ttl 259200
#serve-expired-reply-ttl 30
response-mode fastest-response
speed-check-mode tcp:443,ping
#rr-ttl-min 60
#rr-ttl-max 3600
#force-qtype-SOA 65
#force-AAAA-SOA yes
log-console yes
log-num 1
log-level info
log-size 16k

server 127.0.0.1:1052
#server-tcp 223.5.5.5 
#server-https https://doh.apad.pro/dns-query -group out
#server-https https://dns.cooluc.com/dns-query
#server-tls 8.8.4.4 -group out -exclude-default-group
#server-tls 9.9.9.12 -group out -exclude-default-group

#address /dns.google/8.8.4.4

#   -proxy [proxy-name]: use proxy to connect to server.
#   proxy-server socks5://user:pass@1.2.3.4:1080 -name proxy
#   proxy-server http://user:pass@1.2.3.4:3128 -name proxy

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传[coredump.zip](https://github.com/pymumu/smartdns/files/11860065/coredump.zip)信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

[smartdns.log](https://github.com/pymumu/smartdns/files/11860066/smartdns.log)
[coredump.zip](https://github.com/pymumu/smartdns/files/11860067/coredump.zip)

**Comment by PikuZheng** [comment]
日志不完整，建议改大一些。
以现有信息来看很难定位问题。不过segfault是去年6月的版本的已知bug，您确定正确安装了最新版本？

**Comment by liangxyz** [comment]
> 日志不完整，建议改大一些。 以现有信息来看很难定位问题。不过segfault是去年6月的版本的已知bug，您确定正确安装了最新版本？

确定安装了最新版呀
![搜狗截图20230626215630](https://github.com/pymumu/smartdns/assets/8108927/4e289e53-d393-4877-8c2a-879c2faaa955)

**Comment by pymumu** [comment]
最新代码看看
