### ISSUE TITLE
请教address如何配置2个地址并且指定IPV6?

### ISSUE THREAD

**Issue by hjkl950217** [pymumu/smartdns#1438]
非常抱歉使用issue来提问请教，但是看了很久很久的配置文档都没有看明白如何配置。 我也尝试过多种组合，都失败，特请教一波。

我的疑问：
1.有一个地址aaa.com想要在内网配置dns解析
2. 有2个地址，分别为`fe80::fff1”和“192.168.5.190`
3. 希望一条address能搞定（看文档似乎支持一个address写多个地址），在配置时指定清楚`#4`。
4.如果一条不能搞定，2条也行（IPV4 IPV6分开）

如果直接写2条`address /aaa.com/fe80::fff1`这种可以顺利响应，但似乎不是最好的配置。

我发现`address /gtxck.dynv6.net/192.168.50.190#4`这样的配置是无法识别到的，但文档上的语法又是这样

**Comment by PikuZheng** [comment]
`address /gtxck.dynv6.net/fe80::fff1,192.168.50.190`

**Comment by PikuZheng** [comment]
额，试了几次发现ipv6要写在ipv4的前面，否则ipv6会产生奇怪的展开。不知是设计成这样还是bug @pymumu
```
address /gtxck.dynv6.net/fe80::fff1,::192.168.50.190,192.168.50.190
非权威应答:
名称:    gtxck.dynv6.net
Addresses:  fe80::fff1
          ::192.168.50.190
          192.168.50.190
----正确

address /gtxck.dynv6.net/::192.168.50.190,192.168.50.190,fe80::fff1
非权威应答:
名称:    gtxck.dynv6.net
Addresses:  ::192.168.50.190
          fe80::c0a8:32be
          192.168.50.190
----最后一个的错了

address /gtxck.dynv6.net/192.168.50.190,fe80::fff1,::192.168.50.190
非权威应答:
名称:    gtxck.dynv6.net
Addresses:  fe80::101:101:101:101
          ::101:101:101:101
          192.168.50.190
----ipv6都错了
```

**Comment by pymumu** [comment]
修改了一下。

**Comment by hjkl950217** [comment]
> `address /gtxck.dynv6.net/fe80::fff1,192.168.50.190`
> 
> 我这试了是可行的。如果不行考虑是不是开了双栈ip优选

确实开启了双栈优选，顺序这个我试试了，确实如此。。我一直以为是我写法不对

**Comment by hjkl950217** [comment]
> 修改了一下。 42及之前版本的话，配置ipv4和ipv6，可以两个address配置项。
> 
> ```
> address /gtxck.dynv6.net/fe80::fff1
> address /gtxck.dynv6.net/192.168.50.190
> ```

感谢大佬修改！
