### ISSUE TITLE
Issue: Error when adding address

### ISSUE THREAD

**Issue by rapdodge** [pymumu/smartdns#1440]
Dear developers,

I've was adding `address` configuration. And I've adding multiple IPs, but, It's has error. For the comparison, I've adding two different domain.

![image](https://github.com/pymumu/smartdns/assets/33513626/4e18ec97-746d-468c-9423-8ef4b0e04431)

![image](https://github.com/pymumu/smartdns/assets/33513626/0b58e3ae-f40f-4141-9445-c0ec5e8f6e77)

The error is just on the `address` for akamaized.net. Which is has more than 1 IP address.

**Comment by PikuZheng** [comment]
Multiple address require v42.0.8 or more. You are using v42.0.5 or earlier.

**Comment by rapdodge** [comment]
> Multiple address require v42.0.8 or more. You are using v42.0.5 or earlier.

I'm using https://github.com/pymumu/smartdns/releases/tag/Release42 Release42, latest version are available on the github release, i need to compile myself?

**Comment by PikuZheng** [comment]
> I'm using https://github.com/pymumu/smartdns/releases/tag/Release42 Release42, latest version are available on the github release, i need to compile myself?

correct
