### ISSUE TITLE
办公室只能用公司的DNS服务器，禁止访问运营商或公共DNS，笔记本（WSL）如何自动判断和共存

### ISSUE THREAD

**Issue by GuiDeJuShi** [pymumu/smartdns#1443]
**需求应用场景**
我笔记本电脑在WSL中安装了smartdns，配置了本地运营商的和一些公共DNS作为上游服务器。但我的办公室网络只允许用公司的DNS服务器，禁止访问运营商或公共DNS。于是在办公室，smartdns就无法工作（除非把公司的DNS服务器添加为上游服务器）。而若把电脑带出公司，使用其它网络（例如家中、手机热点或公司外面），又能正常使用smartdns。
所以我就提议，能不能设计一种方法，自动同时满足办公室内、办公室外的使用需求。即自动判断，如果我在公司，就自动把上游服务器切换为公司DNS，或者干脆关闭smartdns；如果我不在公司，就正常按之前的配置使用smartdns。

引申：能否实现自动检测网络运营商，并自动切换部分上游服务器？因为笔记本、便携路由器这种设备在外面移动，会不定时地连接不同运营商的网络，而不同运营商在本地的DNS显然是不一样的，有的公共DNS不同运营商的地址也是不同的。如果能判断并自动切换，就完美了，比如：连接中国联通网络时，上游服务器自动用本地联通的DNS和DNS派的联通服务器123.125.81.6，连接电信或移动网络时，就相应自动切换为本地电信/移动的DNS以及DNS派的电信/移动服务器101.226.4.6，并可以设置一个保底的other或else选项，如果上述条件都不满足（比如连接一些小运营商），自动用默认的服务器。

**建议的方案**
通过判断一定的条件（判断依据如电脑连接的无线名称、IP段、网关主机名等），自动切换上游服务器或自动启停smartdns。
引申：通过判断smartdns所在的网络运营商，自动切换上游服务器。

**设备信息**
1. 设备信息（CPU，厂家）  
i7-11700H，win11系统，WSL1

2. 固件信息
@PikuZheng 大大编译的1.2023.v42.0.15

**Comment by PikuZheng** [comment]
可以同时配置办公室dns和其他dns作为上游。smartdns是同时向上游发起dns查询，其中一个上游不可用时不会有影响的。

**Comment by GuiDeJuShi** [comment]
> 可以同时配置办公室dns和其他dns作为上游。smartdns是同时向上游发起dns查询，其中一个上游不可用时不会有影响的。

其他设置均不变、只添加办公室DNS的前提下，对查询和反馈的耗时也没有任何影响喽？

**Comment by PikuZheng** [comment]
另外一般情况下办公室dns是禁udp/53和tcp/853，不太可能将全球的doh都禁了。比较常见的做法是劫持udp/53重定向到内网服务器，这样无论配置哪个上游，事实应答的都是内网的dns服务器。如果没有其他限制，在内网环境应该是可以用https dns上游的。

使用smartdns的主要目的是ip优选（测速）和抗污染，我认为使用运营商dns并且在不同网络环境下切换不同运营商的dns与该目的背道而驰。

> 其他设置均不变、只添加办公室DNS的前提下，无论是在公司还是不在公司，对查询和反馈的耗时也都没有任何影响喽？

在公网环境下增加了一个办公室的dns，实际工作中相当于多了一个不可用的上游，会产生一些warn的日志，没有其他影响。

**Comment by GuiDeJuShi** [comment]
> 另外一般情况下办公室dns是禁udp/53和tcp/853，不太可能将全球的doh都禁了。比较常见的做法是劫持udp/53重定向到内网服务器，这样无论配置哪个上游，事实应答的都是内网的dns服务器。如果没有其他限制，在内网环境应该是可以用https dns上游的。
> 
> 使用smartdns的主要目的是ip优选（测速）和抗污染，我认为使用运营商dns并且在不同网络环境下切换不同运营商的dns与该目的背道而驰。
> 
> > 其他设置均不变、只添加办公室DNS的前提下，无论是在公司还是不在公司，对查询和反馈的耗时也都没有任何影响喽？
> 
> 在公网环境下增加了一个办公室的dns，实际工作中相当于多了一个不可用的上游，会产生一些warn的日志，没有其他影响。

收到，谢谢，另外请问，若不同的DNS服务器查询耗延时不同，是否影响smartdns的反馈速度？例如可能本地运营商的最快，国内公共次之，国外DNS更慢。smartdns设置为fastest-response模式

**Comment by PikuZheng** [comment]
> smartdns设置为fastest-response模式

fastest-response时，在缓存中没有结果时取首个应答的上游，对结果测速（如果配置了speed check）并反馈。其他应答的上游的结果会一并合并结果测速并计入缓存。在缓存中有结果时，会返回所有上游中测速最快的。

所以一方面fastest-response是加快了域名首次查询的应答速度（比如本地运营商应答最快，那么就取本地运营商的结果），另一方面查询结果放到所有上游来看，解析到的ip可能不是测速最快的结果。

**Comment by GuiDeJuShi** [comment]
> > smartdns设置为fastest-response模式
> 
> fastest-response时，在缓存中没有结果时取首个应答的上游，对结果测速（如果配置了speed check）并反馈。其他应答的上游的结果会一并合并结果测速并计入缓存。在缓存中有结果时，会返回所有上游中测速最快的。
> 
> 所以一方面fastest-response是加快了域名首次查询的应答速度（比如本地运营商应答最快，那么就取本地运营商的结果），另一方面查询结果放到所有上游来看，解析到的ip可能不是测速最快的结果。

好的，那么根据我在其他issue里看到的回答，fastest-response模式下配合打开prefetch-domain域名预先获取、cache-persist持久化缓存，是否仅在终端第一次查询时反馈最先应答的上游服务器的结果（但不一定测速最快），之后全部收到应答并测速完成后，smartdns就会向客户端反馈测速最快的结果了？

> 使用smartdns的主要目的是ip优选（测速）和抗污染，我认为使用运营商dns并且在不同网络环境下切换不同运营商的dns与该目的背道而驰。
了解，我提出自动筛选和切换服务器，主要是为了排除掉我不需要的服务器，比如我连在联通的网络上，我认为不需要向电信、移动的服务器再查询。这样的目的是为了节约总体的查询和测速时间，同时减少并发量和连接数。不知我这个担心是否有必要、对smartdns的效率或性能是否有能察觉到的影响。
也就是说，另一个极端是，不管我在哪，我把公司的DNS服务器、本省移动、联通、电信的服务器，国内外主要公共DNS的首选、备用IPV4、IPV6服务器全部设置进入，fastest-response、prefetch-domain、cache-persist以及双栈优选全都打开，是否会显著降低查询和测速的耗时、增加机器和网络性能压力？

**Comment by PikuZheng** [comment]
> 在终端第一次查询时反馈最先应答的上游服务器的结果（但不一定测速最快），之后全部收到应答并测速完成后，smartdns就会向客户端反馈测速最快的结果了？

正确的

> 我连在联通的网络上，我认为不需要向电信、移动的服务器再查询。这样的目的是为了节约总体的查询和测速时间，同时减少并发量和连接数。

正确的

> 另一个极端是，不管我在哪，我把公司的DNS服务器、本省移动、联通、电信的服务器，国内外主要公共DNS的首选、备用IPV4、IPV6服务器全部设置进入，fastest-response、prefetch-domain、cache-persist以及双栈优选全都打开，是否会显著降低查询和测速的速度、增加机器和网络性能压力？

正确的，网速和流量问题不大，但并发连接数必须考虑，尤其WSL这种nat式的，需要把主机和虚拟机并发同时考虑，加上测速时产生的连接，大量并发极可能出现端口号用尽的情况。作者建议[国内外加起来“总数建议在 10 个左右”](https://pymumu.github.io/smartdns/faq/#_2)。我自己是采用单一doh.pub作为国内上游，这样就无需考虑多个上游结果合并、最快应答是不是最优ip、二次测速等问题。

**Comment by GuiDeJuShi** [comment]
> 正确的，网速和流量问题不大，但并发连接数必须考虑，尤其WSL这种nat式的，需要把主机和虚拟机并发同时考虑，加上测速时产生的连接，大量并发极可能出现端口号用尽的情况。作者建议[国内外加起来“总数建议在 10 个左右”](https://pymumu.github.io/smartdns/faq/#_2)。我自己是采用单一doh.pub作为国内上游，这样就无需考虑多个上游结果合并、最快应答是不是最优ip、二次测速等问题。

收到。我没有科学的需求，就是单纯在墙内做DNS解析结果优选，也不需要分流之类的。所以为了控制并发连接数，我现在对于家里的路由器等固定线路、地点的设备，会用ping、dns benchmark、dns jumper这类测速手段先测一下解析延时，在同一个服务商的主要、备用服务器里选择一个最快的做上游服务器。我想如果smartdns是否值得加入测速功能，测试DNS服务器本身的延迟和解析速度，对上游服务器进行优选
