### ISSUE TITLE
如果打开去广告的功能，广告过滤日志写在哪里？

### ISSUE THREAD

**Issue by rangdengdashi** [pymumu/smartdns#1444]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by devioa** [comment]
所以最好的方案还是有个WEB面板😋

**Comment by pymumu** [comment]
```
audit-enable yes
audit-SOA yes
```

**Comment by cresky-github** [comment]
> 



> ```
> audit-enable yes
> audit-SOA yes
> ```



能解释一下 audit-SOA 吗？
貌似没有文档啊

**Comment by pymumu** [comment]
记录回应soa的请求
