### ISSUE TITLE
增加对特定域名设置 DNS 查询的最大转发次数

### ISSUE THREAD

**Issue by Chen-j-l** [pymumu/smartdns#1445]
**需求应用场景**
在个人多地组网后常用的访问通常是直接ip访问，但是dnsmasq本身是能够通过 主机名.lan 的方式访问本地主机，设置转发后就能访问异地主机，但是两台openwrt设置/lan/域名相互转发给对方，会无限循环转发。可以将多地lan域名更改为lan1、lan2、lan3等，但对于移动设备来说就不是很友好了。

**建议的方案**
增加对特定域名设置 DNS 查询的最大转发次数的功能，即DNS报文中TTL字段。

**设备信息**
OpenWrt 22.03.5 x86_64/FriendlyElec NanoPi R2S/Xiaomi Redmi Router AX6S

**Comment by GreatMichaelLee** [comment]
我有同样的场景和问题，我有两个异地网断，本地都设成xxxxx.com，经常莫名其妙看到把一个外部域名加上xxxxx.com拼接之后反复查询

**Comment by PikuZheng** [comment]
应该建一个本地域名的权威根来避免递归查询

**Comment by GreatMichaelLee** [comment]
> 应该建一个本地域名的权威根来避免递归查询

大佬，怎么建立权威根啊？

**Comment by CallMeR** [comment]
感觉这个需求和 Dnsmasq 的本地域名查询有点类似，Dnsmasq 可以指定本地域名，比如 domain.local ，然后只要后缀是 domain.local 的查询，都只会在 Dnsmasq 中查询，不会 forward 到上游服务器。
