### ISSUE TITLE
address 配置单域名多IPv4

### ISSUE THREAD

**Issue by zhongjyyy** [pymumu/smartdns#1446]
**问题现象**  
address 配置单域名多IPv4，service smartdns status 提示 address 行错误。
address /www.a.com/1.2.3.4,5.6.7.8

由于1.2.3.4 可能会失效，希望返回所有IP的解释，或者返回最优IP （ping）。

**运行环境**
1. 固件型号  
ubuntu 20.04 LTS
2. 运营商  

3. smartdns来源以及版本
github release 42 deb
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
重复#1440
多个 address 需要 v42.0.8 或更高版本

**Comment by zhongjyyy** [comment]
thks

**Comment by zhongjyyy** [comment]
thks
