### ISSUE TITLE
最新的源码编译安装,进程总是会挂掉.

### ISSUE THREAD

**Issue by ziojacky** [pymumu/smartdns#1448]
运行的环境是debian 11 x86 64位,用最新的源码编译安装后,总是会出现进程挂掉的概率,用的Release 42就不会,具体错误日志如下：

[FATAL] [ smartdns.c:608 ] process exit with signal 11, code = 2, errno = 0, pid = 804586868, self = 759, pc = 0x34b6ffc0, addr = 0x7ff53002c0f8, build(Jul 15 2023 09:50:42 x86_64)

[FATAL][ util.c:1382] Stack:

[FATAL][ util.c:1394] #01: 0x5569311c12a7 () from /usr/local/bin/smartdns+0x2b2a7

[FATAL][ util.c:1394] #02: 0x55693119f33b () from /usr/local/bin/smartdns+0x933b

[FATAL][ util.c:1394] #03: 0x7ff536686140 () from /lib/x86_64-linux-gnu/libpthread.so.0+0x13140

[FATAL][ util.c:1394] #04: 0x7ff53002c0f8 () from (null)+0x7ff53002c0f8

**Comment by pymumu** [comment]
编译debug版本，-s启动，将异常后的coredump和二进制文件发出来

**Comment by pymumu** [comment]
要不然，可以用42之后的提交，二分法找一下是哪个提交会挂掉

**Comment by ziojacky** [comment]
怎么编译debug的版本呢?

**Comment by PikuZheng** [comment]
删持久缓存试试（停止进程，删缓存文件，再开启

**Comment by ziojacky** [comment]
> 编译debug版本，-s启动，将异常后的coredump和二进制文件发出来

这个启动选项是无效的?

invalid option -- 's'

**Comment by pymumu** [comment]
大写S

如果你会gdb的话，直接编译debug版本
make DEBUG=1
然后gdb启动，出问题的时候gdb中执行 bt命令

**Comment by ziojacky** [comment]
> coredump

coredump是哪些文件?

目前已经运行在debug模式下，如果等下进程死掉的时候，我把文件发出来.

**Comment by ziojacky** [comment]
> 编译debug版本，-s启动，将异常后的coredump和二进制文件发出来

coredump是哪些文件?

目前已经运行在debug模式下，如果等下进程死掉的时候，我把文件发出来.

**Comment by pymumu** [comment]
最新代码改了一个可能的地方，也可以测试下。

**Comment by ziojacky** [comment]
> 最新代码改了一个可能的地方，也可以测试下。

用新代码运行了两天目前没有挂掉的迹象了,但是记录响应有时候似乎有点问题,客户端会半天得不到记录导致网页很久才能打开.
