### ISSUE TITLE
请问能够docker化么大佬

### ISSUE THREAD

**Issue by zanzhz1101** [pymumu/smartdns#145]
**需求应用场景**
普遍丝用

**建议的方案**
将此项目daocker化

**Comment by pymumu** [comment]
https://github.com/ghostry/docker-smartdns
https://github.com/Leoyzen/docker-smartdns
https://github.com/leitbogioro/Deploy_SmartDNS

搜了一下，有github盆友做的，供参考。

**Comment by zanzhz1101** [comment]
okok我看看
