### ISSUE TITLE
请问PikuZheng大佬release的OpenWrt版和普通版，在OpenWrt系统上有区别吗

### ISSUE THREAD

**Issue by GuiDeJuShi** [pymumu/smartdns#1450]
GL.inet MT3000路由器（联发科MT7981B处理器），Lean的Qwrt R23.7.1版固件，1.2023.v42.0.18-OpenWrt中的smartdns_1.2023.v42.0.18-1_aarch64_cortex-a53.ipk、1.2023.v42.0.18中的smartdns.1.2023.v42.0.18.aarch64-openwrt.ipk，这两个文件都能安装运行，请问 @PikuZheng 大大，这两个有区别吗，随便用哪个都可以，还是？

**Comment by PikuZheng** [comment]
文件较小的是动态链接编译，编译时使用的openwrt编译工具，系统中需要安装对应的 openssl 等依赖包。文件较大的是静态链接编译，编译时使用的标准musl c工具。
一些openwrt使用特殊的cpu型号，只能用对应的openwrt版本。如果都能正常工作，建议使用静态链接编译的版本。

**Comment by GuiDeJuShi** [comment]
> 文件较小的是动态链接编译，编译时使用的openwrt编译工具，系统中需要安装对应的 openssl 等依赖包。文件较大的是静态链接编译，编译时使用的标准musl c工具。 一些openwrt使用特殊的cpu型号，只能用对应的openwrt版本。如果都能正常工作，建议使用静态链接编译的版本。

收到，谢谢。目前安装的是静态版，之前42.0.15动态版会crash，42.0.18静态版不会了。

**Comment by PikuZheng** [comment]
> @PikuZheng 是不是还不支持23.05以上版本，openssl1.1没了鸭

之前是因为用openssl3编译，有issue说不支持，后来才换成1.1的。你是说现在的release在23.05以上用不了吗？

**Comment by PikuZheng** [comment]
> 静态版能用，想用动态版

试试这个 https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v42.0.21-OpenWrt-openssl3

**Comment by PikuZheng** [comment]
> > 试试这个 https://github.com/PikuZheng/smartdns/releases/tag/1.2023.v42.0.21-OpenWrt-openssl3
> 
> 不行，是3.0.10吗

在  OpenWrt SNAPSHOT r23685-7e7eb5312d / LuCI Master git-23.158.78004-23a246e    Kernel Version | 5.15.123
试了是能运行起来，对应的 libopenssl3  3.0.9-3
