### ISSUE TITLE
openwrt无法解析部分纯ipv6域名

### ISSUE THREAD

**Issue by Chen-j-l** [pymumu/smartdns#1453]
**问题现象**  
在ping纯ipv6域名时，test6.ustc.edu.cn可以解析成地址，ipv6home.dynv6.net若不加上-6参数不能解析成地址。
若在配置中加上address /ipv6home.dynv6.net/#4则可以不需要-6参数就能解析成地址。
以下是nslookup的差异
/*************************************/
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   test6.ustc.edu.cn
Address: 2001:da8:d800::40

Non-authoritative answer:
/*************************************/
Server:         127.0.0.1
Address:        127.0.0.1:53

Non-authoritative answer:
Name:   ipv6home.dynv6.net
Address: 2409:8a5e:be10:62f0:58af:8fdb:1812:e24d

** server can't find ipv6home.dynv6.net: SERVFAIL
/*************************************/
以上情况是在openwrt 22.03.x中出现，在使用wireguard解析域名时发现不能解析成地址，从而无法启动接口。windows不会出现这个情况。
若直接将dns服务器指定为223.5.5.5，也不会出现这种情况。

**Comment by PikuZheng** [comment]
有没有可能是你开了双栈ip优选

**Comment by Chen-j-l** [comment]
> 有没有可能是你开了双栈ip优选

都试过了，dualstack-ip-allow-force-AAAA yes这个也试过了，都是一样的情况，不知道是不是dynv6那边要做什么操作

**Comment by Chen-j-l** [comment]
result: test6.ustc.edu.cn, qtype: 1, SOA

result ipv6home.dynv6.net, qtype: 1, rtcode: 2

看日志，估计应该是这个问题

**Comment by pymumu** [comment]
你这个域名查询AAAA记录，有概率上游返回NXDOMAIN

```
root@raspberrypi:/home/pi# dig ipv6home.dynv6.net -t AAAA @223.5.5.5

; <<>> DiG 9.16.42-Debian <<>> ipv6home.dynv6.net -t AAAA @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24796
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1408
;; QUESTION SECTION:
;ipv6home.dynv6.net.            IN      AAAA

;; Query time: 275 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: Fri Jul 28 11:40:49 HKT 2023
;; MSG SIZE  rcvd: 47

````
