### ISSUE TITLE
最新40.0.20打不开hub.docker.com换回Release 42（2023.05.07-1641）却能打开

### ISSUE THREAD

**Issue by 58285474** [pymumu/smartdns#1457]
**问题现象**  
简要描述问题出现的现象
40.0.20打不开hub.docker.com在配置文件不变的情况下，换回Release 42（2023.05.07-1641）却能打开，而且再电脑或者wan口关闭ipv6的情况下就可以丝丝顺滑的打开hub.docker.com，nslookup hub.docker.com返回的只有ipv6地址，配置已经上传如下
![smartdns配置](https://github.com/pymumu/smartdns/assets/28937186/a703c87d-531f-45e9-b4e4-cc330029f0ed)

**运行环境**
1. 固件型号  
openwrt 
2. 运营商  

3. smartdns来源以及版本
40.0.20
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
hub.docker.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by 58285474** [comment]
> **问题现象** 简要描述问题出现的现象 40.0.20打不开hub.docker.com在配置文件不变的情况下，换回Release 42（2023.05.07-1641）却能打开，而且再电脑或者wan口关闭ipv6的情况下就可以丝丝顺滑的打开hub.docker.com，nslookup hub.docker.com返回的只有ipv6地址，配置已经上传如下 ![smartdns配置](https://user-images.githubusercontent.com/28937186/257725918-a703c87d-531f-45e9-b4e4-cc330029f0ed.png)
> 
> **运行环境**
> 
> 1. 固件型号
>    openwrt
> 2. 运营商
> 3. smartdns来源以及版本
>    40.0.20
> 4. 涉及的配置(注意去除个人相关信息)
> 
> **重现步骤**
> 
> 1. 上游DNS配置。
> 2. 访问的域名。
>    hub.docker.com
> 
> **信息收集**
> 
> 1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。
> 2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。
>    在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
>    coredump文件在/tmp目录下

看了一下 测速模式选择无就可以打开了

**Comment by PikuZheng** [comment]
的确有这个问题，我还不知道是怎么回事

**Comment by PikuZheng** [comment]
> 我的也是ipv6问题，关闭ipv6一切正常，能说下“强制返回ipv4并将对应的ip翻墙”具体怎么操作吗？还有这只是目前发现的一个网站，应该还有很多类似情况，后续看能否修复吧！

address /docker.com/#6
过不过墙就是另一件事了

**Comment by noahge0923** [comment]
我是返回的ipv4，但是就是打不开hub.docker.com

**Comment by PikuZheng** [comment]
> 我是返回的ipv4，但是就是打不开hub.docker.com

去掉中转 客户端直接用smartdns
