### ISSUE TITLE
为什么开启smartdns后解析服务器总是到外地去了？

### ISSUE THREAD

**Issue by naskater** [pymumu/smartdns#1458]
我的配置如下：
config smartdns
	option seconddns_port '5335'
	option server_name 'smartdns'
	option ipv6_server '0'
	option dualstack_ip_selection '0'
	option prefetch_domain '1'
	option seconddns_tcp_server '1'
	option seconddns_no_dualstack_selection '1'
	option seconddns_no_cache '1'
	option force_aaaa_soa '1'
	option seconddns_force_aaaa_soa '1'
	option speed_check_mode 'ping,tcp:80,tcp:443'
	option cache_persist '0'
	option force_https_soa '1'
	option rr_ttl_min '600'
	option rr_ttl_max '3600'
	option tcp_server '0'
	option cache_size '10000'
	option serve_expired '1'
	option resolve_local_hostnames '0'
	option response_mode 'fastest-ip'
	option seconddns_server_group 'foreign'
	option enabled '1'
	option seconddns_no_speed_check '1'
	option port '6053'
	option auto_set_dnsmasq '1'
	option bind_device '0'
	option seconddns_enabled '1'
	option old_port '6053'
	option old_enabled '1'
	option old_auto_set_dnsmasq '1'

config server
	option type 'udp'
	option server_group 'china'
	option blacklist_ip '0'
	option enabled '1'
	option name '联通'
	option ip '218.104.111.122'

config server
	option type 'udp'
	option name '114'
	option ip '114.114.114.114'
	option blacklist_ip '0'
	option server_group 'china'
	option enabled '1'

config server
	option type 'udp'
	option name '腾讯'
	option ip '119.29.29.29'
	option blacklist_ip '0'
	option server_group 'china'
	option enabled '1'

config server
	option type 'udp'
	option server_group 'china'
	option blacklist_ip '0'
	option name '阿里'
	option ip '223.5.5.5'
	option enabled '1'

config server
	option type 'udp'
	option server_group 'china'
	option blacklist_ip '0'
	option name '电信'
	option ip '202.103.24.68'
	option enabled '0'

config server
	option name 'google https'
	option ip 'https://dns.google/dns-query'
	option type 'https'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option addition_arg '-exclude-default-group'
	option enabled '0'
	option server_group 'foreign'
	option exclude_default_group '0'
	option port '443'

config server
	option name 'OpenDNS'
	option ip 'https://doh.opendns.com/dns-query'
	option type 'https'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option addition_arg '-exclude-default-group'
	option enabled '0'
	option server_group 'foreign'
	option exclude_default_group '0'
	option port '443'

config server
	option enabled '1'
	option name 'google tls'
	option ip 'tls://dns.google'
	option port '853'
	option type 'tls'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option addition_arg '-exclude-default-group'
	option server_group 'foreign'
	option exclude_default_group '0'

config domain-rule
	option no_speed_check '1'
	option force_aaaa_soa '1'

config server
	option enabled '1'
	option name 'Cloudflare DoH'
	option ip 'https://cloudflare-dns.com/dns-query'
	option type 'https'
	option exclude_default_group '0'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option addition_arg '-exclude-default-group'
	option server_group 'foreign'
	option port '443'

config server
	option name '谷歌'
	option ip '8.8.8.8'
	option port '53'
	option type 'tcp'
	option exclude_default_group '0'
	option blacklist_ip '0'
	option addition_arg '-exclude-default-group'
	option enabled '1'
	option server_group 'foreign'

config server
	option name '谷歌'
	option ip '8.8.8.8'
	option port '853'
	option type 'tls'
	option exclude_default_group '0'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option addition_arg '-exclude-default-group'
	option enabled '1'
	option server_group 'foreign'

config server
	option name 'One Dns'
	option ip '1.1.1.1'
	option port '53'
	option type 'tcp'
	option exclude_default_group '0'
	option blacklist_ip '0'
	option addition_arg '-exclude-default-group'
	option enabled '0'
	option server_group 'foreign'

config server
	option name 'One Dns'
	option ip '1.1.1.1'
	option port '853'
	option type 'tls'
	option exclude_default_group '0'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option addition_arg '-exclude-default-group'
	option enabled '1'
	option server_group 'foreign'

![Sn1](https://github.com/pymumu/smartdns/assets/22311485/cf32e03c-0b6b-4768-a338-3a89fee2c55b)
![2](https://github.com/pymumu/smartdns/assets/22311485/2864eebe-0c67-4ba4-b049-7c262edfdadf)

只要开启smartdns就会解析到广州联通，我是武汉联通。关闭smartdns解析地址就固定在武汉，属于正常。固件是openwrt，只开启了smartdns和Alist，不知道问题出在哪里。请教一下各位大神，如何解决？

**Comment by PikuZheng** [comment]
删掉腾讯的上游试试

**Comment by naskater** [comment]
> 

删除腾讯后解析地址又在北京和湖南长沙两者之间反复横跳

**Comment by PikuZheng** [comment]
> 在北京和湖南长沙两者之间反复横跳

删掉阿里的试试

**Comment by naskater** [comment]
> > 在北京和湖南长沙两者之间反复横跳
> 
> 删掉阿里的试试

我只有设置武汉市联通自己的dns，解析结果才是武汉市，添加任何一个第三方dns服务器就会解析到外地

**Comment by naskater** [comment]
> 所以。。。结果符合预期？ 公共dns的分布式服务原理上就会导致出口不会是你所在的运营商

原来如此，非常感谢！

**Comment by yoshyv** [comment]
公共dns都是这样。一共也没几个出口。
改运营商自己dns不然就用支持ecs的dns+subnet配置伪造出口地址。
