### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by rcyggdra** [pymumu/smartdns#1459]
**问题现象**  
无法运行

**运行环境**
1. 固件型号  
AR7241 @ OpenWrt 18.06.9

2. 运营商  

3. smartdns来源以及版本
smartdns.1.2023.05.07-1641.arm-openwrt-all.ipk

勾选一直无法运行，也无进程，试着敲打命令：
```
root@OpenWrt:~# /usr/sbin/smartdns -f -x -c /etc/smartdns/smartdns.conf -p /var/
run/smartdns.pid
/usr/sbin/smartdns: line 1: syntax error: unexpected word (expecting ")")

```

**Comment by PikuZheng** [comment]
架构错误，[AR7241需要mips](https://www.lan23.ru/forum/attachment.php?attachmentid=25940&d=1502374718)

**Comment by rcyggdra** [comment]
> 架构错误，[AR7241需要mips](https://www.lan23.ru/forum/attachment.php?attachmentid=25940&d=1502374718)

我知道错了，刚才看到恩山那边的帖子才看见，感谢回复，终于可以用了！
