### ISSUE TITLE
padavna安装时出现Segmentation fault

### ISSUE THREAD

**Issue by zanzhz1101** [pymumu/smartdns#146]
[zhang /opt/home/admin]# opkg install http://192.168.123.153/shared//smartdns.1.2019.03.15-2307.mipsel-3.4.ipk
Downloading http://192.168.123.153/shared//smartdns.1.2019.03.15-2307.mipsel-3.4.ipk
Segmentation fault
**运行环境**
padavan 荒野无灯
mt7621 newifi-d2

试过了mipsel-3.4.ipk/mipsbig.ipk/mipselsf.ipk
环境试过了optware/entware

**Comment by pymumu** [comment]
ldd /opt/usr/sbin/smartdns看看是不是依赖的openssl不正确。

**Comment by zanzhz1101** [comment]
是安装时出现的

**Comment by pymumu** [comment]
安装完的时候，会自动启动，应该还是启动的时候报错的。

**Comment by zanzhz1101** [comment]
不，，，其实是根本就没开始安装

**Comment by pymumu** [comment]
很有可能是版本不对，按指导获取下对应版本吧

**Comment by zanzhz1101** [comment]
大概也许可能是entware环境的问题，重新换了个就可以了

**Comment by zhudan** [comment]
> entware
你安装的哪个包？K2P hiboy的固件始终安装不上，跟你的问题应该是一致的
