### ISSUE TITLE
请教一下tls和https上游服务器的正确填写方法

### ISSUE THREAD

**Issue by chris7395328** [pymumu/smartdns#1461]
**问题现象**  
在设置上有服务器的时候，tls和https服务器填写都要重复填一次server-tls 和server-https
比如：server-tls server-tls 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group -proxy sock5 才能生效
填：server-tls 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group -proxy sock5 会显示解析失败
非tls和https的没有这个问题，想知道什么原因

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

**Comment by PikuZheng** [comment]
![image](https://github.com/pymumu/smartdns/assets/12579522/783ef093-9630-4ef9-b73d-9bfc1fc8cae5)
我的配置是这么写的

**Comment by PaTTeeL** [comment]
同问，比如
```
server-https 1.1.1.1
server-https https://1.1.1.1
server-https https://1.1.1.1/dns-query
```
上面三种写法哪几种是对的？

**Comment by PaTTeeL** [comment]
同样想问问，比如
```
server-https dns.alidns.com
server-https https://dns.alidns.com
server-https https://dns.alidns.com/dns-query
server-https 223.5.5.5
server-https https://223.5.5.5
server-https https://223.5.5.5/dns-query
```
这六种写法哪几种是可以被smartdns读取并可以正确工作的？

**Comment by PikuZheng** [comment]
> 这六种写法哪几种是可以被smartdns读取并可以正确工作的？

就我所知（当前最新版）这些写法都行

**Comment by PaTTeeL** [comment]
> > 这六种写法哪几种是可以被smartdns读取并可以正确工作的？
> 
> 就我所知（当前最新版）这些写法都行

今天在家里的openwrt上试了一下，版本smartdns 1.2022.38.1
域名的三种写法貌似是可以的，纯IP的doh要写全网址，少https和少路径都不行，不是报403就是报502错误
