### ISSUE TITLE
smartdns日志目前可以按大小分割验证无异常，是否可以支持按天分割或者小时分割

### ISSUE THREAD

**Issue by maojianyou** [pymumu/smartdns#1467]
**需求应用场景**
在smartdns大量日志需要保存的时候，为了方便后续日志排查，能否支持按日志时间来分割，这样后续如果使用linux命令过滤某天或某小时的日志的文件，立马就可以过滤出来，方便查看，不需要同时排查几个文件，比如3G一个文件，可能时间上跨度3个3G过滤，这样即使用awk grep也非常慢，所以能否支持按时间切割日志，然后gzip压缩
![image](https://github.com/pymumu/smartdns/assets/55315920/ae94f38a-f56c-4475-bdf8-c8853949ecbf)

**Comment by pymumu** [comment]
按时间归档可能会打爆日志文件。

当前文件名是有结束时间的。

**Comment by maojianyou** [comment]
看起来是不规律时间归档，比如中午12:00切割一次，晚上18: 00切割一次，凌晨00:00切割一次，有规律的归档会好很多

**Comment by yoshyv** [comment]
有这需求直接用journalctld
非要用rsyslog的话改logrotate配置

**Comment by cresky-github** [comment]
> 有这需求直接用journald，现在反正都是systemd 非要用rsyslog的话改logrotate配置



意思是说，smartdns不用设置，直接查询系统日志？

**Comment by pymumu** [comment]
新版本支持输出到syslog

log-syslog yes

开启
