### ISSUE TITLE
[v43 regression] IPv6 is disabled but still ping in ICMPv6

### ISSUE THREAD

**Issue by enihcam** [pymumu/smartdns#1472]
**问题现象**  
简要描述问题出现的现象
> IPv6 is disabled but still `[fast_ping.c:1033] create icmp socket failed, Address family not supported by protocol`

**运行环境**
1. 固件型号  
> Archlinux

2. 运营商  
> N/A

3. smartdns来源以及版本
> v43, archlinux official repo

4. 涉及的配置(注意去除个人相关信息)
> unchanged since v42, `-force-aaaa-soa` is specified for all binds.

**重现步骤**
1. 上游DNS配置。  
> N/A

2. 访问的域名。  
> N/A

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

`smartdns[302]: [2023-08-14 19:48:10,425][ERROR][      fast_ping.c:1033] create icmp socket failed, Address family not supported by protocol`

**Comment by pymumu** [comment]
Are there any functional issues? 
If ipv6 is not available, smartdns will disable IPv6 related functions. and there will also be a log message.

```
IPV6 is not ready, disable IPV6 features
```

**Comment by enihcam** [comment]
> Are there any functional issues?

no, the error is simply annoying. well, if everything works, this message should be a `WARN` instead of `ERROR`, right?

> If ipv6 is not available, smartdns will disable IPv6 related functions. and there will also be a log message.
> 
> ```
> IPV6 is not ready, disable IPV6 features
> ```

i didn't see such a message.

**Comment by PikuZheng** [comment]
I'd like to know if you're running smartdns with root user (or someone with permissions

**Comment by enihcam** [comment]
I've changed the log level from `error` to `fatal` since the error messages has nothing serious.

issue closed.
