### ISSUE TITLE
希望有docker官方smartdns镜像

### ISSUE THREAD

**Issue by gexiaopeng** [pymumu/smartdns#1474]
目前在docker官方仓库虽然有 ghostry/smartdns:latest ，但最近更新时间是2022-04-18 17:12:22，使用以后，感觉性能也不好。
希望能在docker官方仓库上传最新smartdns镜像，这样方便安装使用。

请问，爱快软路由怎么样安装最新的smartdns版本？ （目前我是在爱快的docker上安装ghostry/smartdns:latest，但性能不好）
另外，我不想在爱快软路由上安装openwrt然后再安装smartdn，虽然openwrt可以安装最新的smartdns，但这样太复杂了，维护也麻烦。

**Comment by Shargye** [comment]
pikuzheng/smartdns，爱快直接拉取镜像，然后把工作目录映射出来，搞定。

**Comment by gexiaopeng** [comment]
> pikuzheng/smartdns，爱快直接拉取镜像，然后把工作目录映射出来，搞定。

另外一个 pymumu/smartdns 是不官方的？

**Comment by PikuZheng** [comment]
> > pikuzheng/smartdns，爱快直接拉取镜像，然后把工作目录映射出来，搞定。
> 
> 另外一个 pymumu/smartdns 是不官方的？

官方只有稳定版。我是根据最新代码自动编译的。
不追新功能的话还是建议用官方稳定版。

**Comment by storezhang** [comment]
> > > pikuzheng/smartdns，爱快直接拉取镜像，然后把工作目录映射出来，搞定。
> > 
> > 
> > 另外一个 pymumu/smartdns 是不官方的？
> 
> 官方只有稳定版。我是根据最新代码自动编译的。 不追新功能的话还是建议用官方稳定版。

可以推送到除dockerhub外的吗，比如腾讯ccr或者阿里云，dockerhub现在访问不太理想

**Comment by PikuZheng** [comment]
> 可以推送到除dockerhub外的吗，比如腾讯ccr或者阿里云，dockerhub现在访问不太理想

`ccr.ccs.tencentyun.com/pikuzheng/smartdns`
