### ISSUE TITLE
address支持多IP的问题

### ISSUE THREAD

**Issue by yoshyv** [pymumu/smartdns#1475]
**问题现象**  
address参数支持多IP地址。多个IP之间如果有空格便无法空格后的地址

**运行环境**
1. 固件型号  
x86_64 linux
2. 运营商  

3. smartdns来源以及版本
release 43
4. 涉及的配置(注意去除个人相关信息)
address /fhnfile.oss-cn-shenzhen.aliyuncs.com/120.241.13.244, 39.108.31.34
speed-check-mode ping,tcp:80,tcp:443

请问能支持下多个IP之间用空格隔开吗？去掉空格的话能正常解析多IP记录，但是全部挤在一起看起来太乱了。

另外这里如果添加多个IP的话，会根据测速返回不同顺序吗？
阿里的OSS几个解析记录都添上后。反复用 `host fhnfile.oss-cn-shenzhen.aliyuncs.com` 查询，结果的顺序貌似不是依据测速结果而更像是round robin。有办法这里也根据测速返回最快的结果在最上面吗？

最后请教下测速排序的问题。（并非手动添加address的记录。）
如果在国外解析国内站点，可能随机解析到三大运营商一个，用ping或者tcp:443排序的话，都可能测速瞬间结果比较理想，实际上因为丢包体验很差的情况。尤其是到电信，延迟比联通移动可能低但是丢包厉害。如果可能的话，能添加个丢包率判断结果的优劣的选项么？

谢谢

**Comment by pymumu** [comment]
用，号是因为domain-rule支持多个选项


觉得配置长可以用\来换行

**Comment by yoshyv** [comment]
我的意思是逗号后面加空格的问题，类似涉及的配置里面给的样子。
英文标点后面正常都是需要空格的。没空格挤在一起也会很乱。

address如果多个地址的话完全不会测速，是直接round robin吗？这样会连接到哪个IP就是随机的了？

最后的测速排序问题，可能添加个丢包的权重吗？毕竟丢包率是最影响体验的要素。

**Comment by pymumu** [comment]
现在是RoundRobin算法。

因代码问题，空格目前不能加。
比如下面的配置
address /a.com/1.1.1.1, 1.1.1.2
转换到domain-rules
domain-rules -a 1.1.1.1, 1.1.1.2 -ipset a
domain-rules在处理上，是用空格区分多个参数的，上述配置，将会导致1.1.1.2无法正常处理。因为这部分代码是公用的。

丢包的问题，目前没有好的解决方案。
唯一可能的方案是，检测的时候，连续发送多个测速请求，最后看测速请求返回的数量。
但这样会增加延迟。

**Comment by yoshyv** [comment]
也就是目前没法解决空格问题么？

丢包问题可能类似返回IP结果，先返回最先响应的结果后台ping多少个包，或者tcp connect看看会不会超时吗？

**Comment by pymumu** [comment]
为什么那么在意空格？

担心不好看可以用换行

addreds /a.com/1.2.3.4,\
               1.2.3.5,\
               1.2.3.6

**Comment by yoshyv** [comment]
因为空格类似逗号，乍一眼分不清几个IP在哪隔开的。

将来可能给address多个IP添加测速么？现实中可能填入多个解析的结果，只有个别速度快，但是需要其他慢的在故障时备用。

**Comment by PikuZheng** [comment]
空格是配置文件的一级分隔符。逗号是二级分隔符。建议考虑配置时支持引号，把", "作为一个整体来处理。

host导致ip轮询是客户端应用决定的（大部分应用只采用第一个ip，视频客户端之类的可能会采用ip轮询）。这种情况下建议用 max-ip-reply-num 限制返回ip的数量。

**Comment by PikuZheng** [comment]
address多个ip测速排序问题可以考虑采用第二服务器多做一次查询

**Comment by pymumu** [comment]
一个回旋方法：

```
bind [::]:53 -no-rule-addr
bind [::]:1053 -group addr
server 127.0.0.1:1053 --exclude-default-group -group addr 
address /a.com/\
        1.2.3.4,\
        5.6.7.8,\
        7.8.9.10,\
        11.12.13.14,\
        1.1.1.1
nameserver /a.com/addr
```

大致的思路：
53端口的请求跳过address规则。
1053端口处理address的规则。

address指定IP地址列表。
nameserver设置对应的域名用自身1053端口的服务请求。
