### ISSUE TITLE
在Passwall2启动后使用nslookup -querytype=ptr smartdns命令验证无法通过

### ISSUE THREAD

**Issue by smdx** [pymumu/smartdns#1476]
**问题现象**  
Passwall2 插件在启动后会删除相关防火墙规则以及清空并关闭相关程序和缓存，然后使用nslookup -querytype=ptr smartdns命令验证smartdns是否正常就无法通过了。这样影响smartdns正常运行吗？

smartdns端口设置6053

Passwall2 插件启动前：
![Screenshot-2023-08-20_142705](https://github.com/pymumu/smartdns/assets/9279217/e5f31ceb-d191-40b4-8a9c-b546ee3c511f)

Passwall2 插件启动后：
![Screenshot-2023-08-20_143153](https://github.com/pymumu/smartdns/assets/9279217/f3c1ce78-8321-4098-9579-b905200d7ea3)

**运行环境**
1. 固件：OpenWrt R23.7.7 / LuCI Master (git-23.226.38647-7acf7ff)

2. 运营商：电信

3. smartdns来源以及版本：kenzok8/openwrt-packages仓库、luci-app-smartdns 1.2023.42-1

**Comment by PikuZheng** [comment]
建议参考#1257

**Comment by smdx** [comment]
> 建议参考#1257

感谢回复，我把smartdns设置53端口然后在DHCP/DNS手动设置转发后没问题了。
