### ISSUE TITLE
日志文件权限设置不生效

### ISSUE THREAD

**Issue by ListenV** [pymumu/smartdns#1479]
**问题现象**  
日志文件权限设置644不生效

**运行环境**
1. x86-64 Debian

2. 移动

3. 来源：GitHub Release下载的最新 `smartdns.1.2023.08.11-1937.x86_64-debian-all.deb`

个人配置：

```
log-level notice
log-file /var/log/smartdns/smartdns.log
log-size 128k
log-num 2
log-file-mode: 644
```

日志全部删除后，重新启动SmartDNS后，生成的日志文件：

```
sky03@Debian /v/l/smartdns> ll
.rw-r----- root root 925 B Sat Aug 26 09:45:06 2023  smartdns.log
```

**Comment by PikuZheng** [comment]
`log-file-mode 644`请，按语法规范填写配置

**Comment by ListenV** [comment]
好吧，眼瞎了

**Comment by ListenV** [comment]
配置文件格式错误时，如果能给个提示就更好了
