### ISSUE TITLE
smartdns探测ip连接数问题

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#148]
**问题现象**  
简要描述问题出现的现象
smartdns 同一个ip连接数为什么那么多

**运行环境**
1. 固件型号  
windows release 24
2. 运营商  
联通
**重现步骤**
1. 上游DNS配置。  
bind [::]:53
cache-size 512
prefetch-domain yes
dualstack-ip-selection yes
rr-ttl-min 120
log-level error
server 10.0.0.10
server 10.0.0.9
server 211.157.15.189
server 210.22.84.3
server 203.240.193.11
server-tcp 8.8.8.8
server-tcp 114.114.114.114
server-tcp 119.29.29.29
2. 访问的域名。  

**信息收集**  
[新建文本文档.txt](https://github.com/pymumu/smartdns/files/3133749/default.txt)

**Comment by pymumu** [comment]
windows吗？到smartdns的fd目录下看看文件句柄数是否正常

wsl中执行下面马命令看看文件句柄数
ls -l /proc/[pid]/fd

Pid为smartdns
