### ISSUE TITLE
访问国外ip的网站，网页需要刷新一下才打开

### ISSUE THREAD

**Issue by Aodi** [pymumu/smartdns#1480]
**问题现象**  

使用smartdns之后，第一次访问国外ip的网站，经常会出现访问失败，然后刷新一次就能打开了，据我观察，国内ip的网站没问题。
我的使用场景是smartdns+ssrp，ssrp使用第二dns服务器，开启缓存预获取+过期缓存，配置基本就是理解配置流程之后再来配置的。
最开始怀疑是过期缓存返回ttl=0的无效的ip导致，但把过期缓存关掉之后还是一样。
求助大家帮忙分析是什么原因

**Comment by PikuZheng** [comment]
一般情况下，这是由于翻墙使用了静态域名列表和动态ip表

**Comment by PikuZheng** [comment]
首次使用域名连接时，对应的ip不在翻墙ip表中，就连不上

**Comment by Aodi** [comment]
> 首次使用域名连接时，对应的ip不在翻墙ip表中，就连不上
@PikuZheng  表示没有特别的理解，我的ssr配置的就是简单的“绕过大陆ip”，也就是绕过的是静态ip列表，并没有使用域名列表。首次连接时，解析到的ip应该不是大陆ip，是可以走到代理才对。
另外，有些不需要翻墙的网站，比如使用cloudflare的pt网站，也会出现首次打不开的情况。

**Comment by PikuZheng** [comment]
有没有测试过首次解析得到的ip是什么ip？网站能正常连接后，隔多长时间重新打开还会有首次连接不上的情况？

**Comment by Aodi** [comment]
> 有没有测试过首次解析得到的ip是什么ip？网站能正常连接后，隔多长时间重新打开还会有首次连接不上的情况？

在手机浏览器上有个诊断信息，看到解析到的ip似乎是正确的，正常访问时也是这个ip。间隔时间有点没规矩，比如今天，电脑上打开github出现了一次，后面正常，过了半小时，手机上第一次打开也出现了。正好手机做了截图。
![Uploading Screenshot_2023-08-28-23-40-56-897_com.android.browser.jpg…]()

**Comment by Aodi** [comment]
![Screenshot_2023-08-28-23-40-56-897_com android browser](https://github.com/pymumu/smartdns/assets/19473876/0579a92b-c293-4807-b33a-5da8a6ea07f4)

**Comment by PikuZheng** [comment]
单看图片是两个不同的问题，第一个拒绝访问是被墙了。第二个empty response猜测是ip不好

**Comment by pymumu** [comment]
看最新代码是否还有问题，有问题再reopen issue。
