### ISSUE TITLE
AX86U安装后无法启动

### ISSUE THREAD

**Issue by theskyQQ** [pymumu/smartdns#1482]
**问题现象**  
AX86U安装后
执行
smartdns -h
正常

执行
smartdns -f
显示load config failed.

执行
/opt/etc/init.d/S50smartdns enable
/opt/etc/init.d/S50smartdns restart
之后没反应

**运行环境**
1. 固件型号  

路由器固件是梅林改388.2.2
安装的smartdns.1.2023.08.11-1937.arm-optware-all.ipk

2. 运营商  

3. smartdns来源以及版本

smartdns.1.2023.08.11-1937.arm-optware-all.ipk

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
`/opt/usr/sbin/smartdns -c /opt/etc/smartdns/smartdns.conf -p /var/run/smartdns.pid -f -x`

**Comment by theskyQQ** [comment]
> `/opt/usr/sbin/smartdns -c /opt/etc/smartdns/smartdns.conf -p /var/run/smartdns.pid -f -x`

非常感谢

**Comment by PikuZheng** [comment]
所以有什么报错提示吗？

**Comment by theskyQQ** [comment]
> 所以有什么报错提示吗？

没有报错，输入完就成功启动了，但我也不知道有没有用上，输入nslookup -querytype=ptr smartdns会出现

**Comment by theskyQQ** [comment]
> 所以有什么报错提示吗？
没有，输入完就成功启动了，但我也不知道有没有用上smartdns,输入nslookup -querytype=ptr smartdns会提示这样的东西(从别人的issue抄的一样格式的，我的我没复制)

```
BusyBox v1.25.1 (2022-12-07 22:57:55 CST) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS serve
```

但在电脑上ping www.baidu.com的延迟比之前是降低了20ms的，电脑上nslookup www.baidu.com显示出来的也没有smartdns而是阿里的

**Comment by PikuZheng** [comment]
`nslookup -querytype=ptr smartdns` 这个是windows的命令

**Comment by theskyQQ** [comment]
> `nslookup -querytype=ptr smartdns` 这个是windows的命令

C:\Users\CGG>nslookup -querytype=ptr smartdns
服务器:  public1.alidns.com
Address:  2400:3200::1

*** public1.alidns.com 找不到 smartdns: Non-existent domain

**Comment by theskyQQ** [comment]
`/opt/etc/init.d/S50smartdns status`
显示
`smartdns is running `
但感觉还是有问题，昨天能打开的网站今天突然就打不开了，pc上执行`nslookup -querytype=ptr smartdns`显示
```
C:\Users\CGG>nslookup -querytype=ptr smartdns
服务器: public1.alidns.com
Address: 2400:3200::1

*** public1.alidns.com 找不到 smartdns: Non-existent domain
```

**Comment by theskyQQ** [comment]
> `nslookup -querytype=ptr smartdns` 这个是windows的命令

`/opt/etc/init.d/S50smartdns status` 显示 `smartdns is running` 
但感觉还是有问题，昨天能打开的网站今天突然就打不开了，pc上执行`nslookup -querytype=ptr smartdns`显示

```
C:\Users\CGG>nslookup -querytype=ptr smartdns
服务器: public1.alidns.com
Address: 2400:3200::1

*** public1.alidns.com 找不到 smartdns: Non-existent domain
```

**Comment by pymumu** [comment]
可能iptable规则丢失了，改用主DNS模式。
https://pymumu.github.io/smartdns/install/entware/

搜工作模式`SMARTDNS_WORKMODE `

**Comment by theskyQQ** [comment]
> 

改完后手机可以正常访问之前打不开的网站了，pc还是不行而且`nslookup -querytype=ptr smartdns`还显示的和之前一样

**Comment by theskyQQ** [comment]
重启了电脑后也可以打开网站了，目前就`nslookup -querytype=ptr smartdns`还是
```
服务器:  public1.alidns.com
Address:  2400:3200::1

*** public1.alidns.com 找不到 smartdns: Non-existent domain
```

**Comment by theskyQQ** [comment]
> 可能iptable规则丢失了，改用主DNS模式。 https://pymumu.github.io/smartdns/install/entware/
> 
> 搜工作模式`SMARTDNS_WORKMODE `

过了一天手机和电脑又都打不开特定网站了，好奇怪

**Comment by PikuZheng** [comment]
> 重启了电脑后也可以打开网站了，目前就`nslookup -querytype=ptr smartdns`还是
> 
> ```
> 服务器:  public1.alidns.com
> Address:  2400:3200::1
> 
> *** public1.alidns.com 找不到 smartdns: Non-existent domain
> ```

这是走阿里的ipv6 dns了，根本没经过路由器

**Comment by theskyQQ** [comment]
> > 重启了电脑后也可以打开网站了，目前就`nslookup -querytype=ptr smartdns`还是
> > ```
> > 服务器:  public1.alidns.com
> > Address:  2400:3200::1
> > 
> > *** public1.alidns.com 找不到 smartdns: Non-existent domain
> > ```
> 
> 这是走阿里的ipv6 dns了，根本没经过路由器

请问有办法同时开启ipv6和smartdns吗

**Comment by PikuZheng** [comment]
在电脑上禁用ipv6 dns
