### ISSUE TITLE
OpenWRT上配置了server也会默认加载系统DNS

### ISSUE THREAD

**Issue by hululu1068** [pymumu/smartdns#1483]
**问题现象**  
按照官方WIKI，不指定`server`的情况下才会加载`resolv.conf`
但是看了下执行文件，即使配置了`server`也会加载系统DNS
<img width="705" alt="2023-08-28_22-26-29" src="https://github.com/pymumu/smartdns/assets/68652362/07f75e5a-c782-49fa-a10c-b56216f993c1">

<img width="611" alt="2023-08-28_22-24-51" src="https://github.com/pymumu/smartdns/assets/68652362/8e876741-8e3a-4fb4-9151-2c6d491d7585">

**运行环境**
OpenWRT x86_64
SmartDNS  - 1.2023-v42

smartdns来源以及版本
Commits on Jul 28, 2023

**一些建议**
1. OpenWRT平台上是否可以去掉`默认自动加载resolv.conf`，以便DNS解析不经过运营商的DNS；
2. 是否可以增加一个参数，指定`Bootstrap DNS`为`resolv.conf`。如`bootstrap-dns /tmp/resolv.conf.d/resolv.conf.auto`

3. 日志配置依然会加载默认配置，但实际如果`custom`中有相关配置会覆盖掉。

**踩坑建议**
我搭配passwall2使用，如果配置了`nftset `会与passwall2的nftset冲突，表现为缓存一段时间后命中的ip会打不开。
建议在wiki中标注下，防止有同类的情况发生，影响用户体验。

<img width="774" alt="image" src="https://github.com/pymumu/smartdns/assets/68652362/ce0c30a8-81a0-4905-a89d-a21000b6273a">

**Comment by hululu1068** [comment]
不知道会不会把指定`server`的功能加上🫡🫡🫡
https://github.com/pymumu/smartdns/issues/1236#issuecomment-1697009659

**Comment by PikuZheng** [comment]
>按照官方WIKI，不指定server的情况下才会加载resolv.conf

但是看了下代码文件，的确是没有指定server的情况下才会加载resolv.conf https://github.com/pymumu/smartdns/blob/c39a7b9b415aff8ef86d92094d0c64012704bdff/src/smartdns.c#L495

>日志配置依然会加载默认配置，但实际如果custom中有相关配置会覆盖掉。

没懂，smartdns.conf 里的日志配置来源是gui界面中的日志配置；custom.conf 里如果也写了相同的配置，custom.conf里的优先（严格按照配置文件载入顺序

**Comment by hululu1068** [comment]
> > 按照官方WIKI，不指定server的情况下才会加载resolv.conf
> 
> 但是看了下代码文件，的确是没有指定server的情况下才会加载resolv.conf
> 
> https://github.com/pymumu/smartdns/blob/c39a7b9b415aff8ef86d92094d0c64012704bdff/src/smartdns.c#L495
> 
> > 日志配置依然会加载默认配置，但实际如果custom中有相关配置会覆盖掉。
> 
> 没懂，smartdns.conf 里的日志配置来源是gui界面中的日志配置；custom.conf 里如果也写了相同的配置，custom.conf里的优先（严格按照配置文件载入顺序

大概搞清楚了。  
默认只检测变量`dns_conf_server_num`，如果不在`smartdns.conf`中配置`server`,只在`custom.conf`配置，那么变量的值就是`0`，就会加载`resolv.conf`的系统DNS。

**Comment by hululu1068** [comment]
目前解决的办法：
直接在`WAN`和`WAN6`口上`取消自动获取DNS`，这样`resolv.conf`就是空的。避免了使用ISP的DNS.
