### ISSUE TITLE
windows版本配置键domain-rules的-no-cache 无效

### ISSUE THREAD

**Issue by gexiaopeng** [pymumu/smartdns#1484]
我在windows10运行 smartdns-x86_64-pc-windows-msvc 版本，提示 domain-rules的-no-cache 属性无效。
那请问我怎么样让某些特定的域名不缓存，比如DDNS? （Linux正常）
运行结果:
![1](https://github.com/pymumu/smartdns/assets/7857056/a73b0725-4277-4ab4-afc4-ae943611f999)

配置：
![2](https://github.com/pymumu/smartdns/assets/7857056/88a5bc90-e363-4c84-bcd7-ce896f2441af)

**Comment by PikuZheng** [comment]
smartdns-x86_64-pc-windows-msvc 不是这个项目吧？

**Comment by gexiaopeng** [comment]
> smartdns-x86_64-pc-windows-msvc 不是这个项目吧？

我下载的就是这个版本。

![33](https://github.com/pymumu/smartdns/assets/7857056/75e4f9e9-a08c-4048-8537-3ae36563f71d)

**Comment by gexiaopeng** [comment]
> smartdns-x86_64-pc-windows-msvc 不是这个项目吧？

在 https://github.com/mokeyish/smartdns-rs  下载的，这里有专门的windows版本，我的问题应该发到那里。

**Comment by gexiaopeng** [comment]
> 最近比较忙，有时间凑空看看

麻烦把 serve-expired-prefetch-time  ，cache-checkpoint-time  属性也加上吧，现在windows版本这两个键不支持。
![QQ截图20230831091510](https://github.com/pymumu/smartdns/assets/7857056/28b97b28-4391-47b6-bb87-0bef00c39944)
