### ISSUE TITLE
Centos7使用google的DOH时找不到证书

### ISSUE THREAD

**Issue by omaidb** [pymumu/smartdns#1485]
**问题现象**  
简要描述问题出现的现象
RHEL8当使用Google的DOH时，获取不到IP地址解析，log中的WARN显示找不到证书
```shell
[2023-08-30 06:25:09,560][ WARN][     dns_client.c:949 ] load certificate from /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs failed.
```

**运行环境**
1. Centos7 ,RHEL8 或oracle Linux8

2. 运营商 ：all

3. smartdns来源以及版本 
smartdns.1.2023.08.11-1937.x86_64-linux-all.tar.gz

4. 涉及的配置(注意去除个人相关信息)
```shell
server-name IBM-DNS
bind []:53
server-https https://dns.google/dns-query
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
serve-expired	yes
prefetch-domain yes
force-AAAA-SOA no
force-qtype-SOA 65 28 128-256
log-level info
log-file /var/log/smartdns/smartdns.log
log-size 128K
log-num 2
log-console yes
```

**重现步骤**
1. 上游DNS-DOH配置。  
```shell
server-https https://dns.google/dns-query
```

2. 访问的域名。  
```shell
dig x.com
```

**信息收集**  
```shell
[2023-08-30 06:25:09,560][ WARN][     dns_client.c:949 ] load certificate from /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs failed.
```
# 原因分析
Centos7和RHEL8默认没有`/etc/ssl/certs/ca-certificates.crt`这个证书文件，但是有`/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`这个证书文件。

本地的DNS服务还没有正常运行，而`/etc/resolv.conf`中配置的DNS是`127.0.0.1`，导致无法解析到`dns.google`这个`上游DOH域名`，从而无法正常从`上游DOH`中获取数据。

# 解决办法

防止Centos7中的smartdns提示上游DOH: dns.google的域名无法正常解析,在`/etc/hosts`中添加内容,这样可以从本地hosts直接解析。
```shell
8.8.8.8 dns.google
8.8.4.4 dns.google
```
<img width="1212" alt="image" src="https://github.com/pymumu/smartdns/assets/18365223/8e34f9e1-a25f-4e84-90b4-57ef2475d723">

## 创建ca-certificates.crt证书软链接
创建ca-certificates.crt证书软链接
```shell
# 创建/etc/ssl/certs/ca-certificates.crt证书软链接
ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/ca-certificates.crt
```
然后这个`WARN`解决了。

# 建议
建议将解决办法递归优化到install步骤中。
1. 在install时就创建好这个证书软链接
2. 对于常用的DOH域名，内置一个类似hosts的配置文件，用来手动指定，防止上游DOH解析失败

# 问题2:
考虑兼容性问题，例如：WIndows是否会遇到该问题， Ubuntu是否会遇到该问题。

**Comment by PikuZheng** [comment]
有没有可能这是操作系统的问题
`yum install ca-certificates`

**Comment by omaidb** [comment]
> 有没有可能这是操作系统的问题 `yum install ca-certificates`

软件包 ca-certificates-2022.2.54-74.el7_9.noarch 已安装并且是最新版本

**Comment by pymumu** [comment]
有配置可以指定证书路径
