### ISSUE TITLE
关于端口分流的问题,无法设置默认组排除

### ISSUE THREAD

**Issue by kyon777** [pymumu/smartdns#1487]
本人环境 上游DNS   3个国内分组cn(设置默认组排除)   3个国外分组gw(设置了默认组排除)
自定义设置添加以下官网代码
bind :7053 -group cn
bind :8053 -group gw

这么设置死活无法解析,这是为啥?搞不懂了  
如果我把cn组(国内DNS)从默认分组排除的勾取消掉,就能正常解析了.

加不加那两行代码都没区别. 
我现在是正常用的,但是我就想较真下这个端口分流的问题,因为一开始就是按官网的文件设置,走了不少弯路(官网是全部加入排除的).

**Comment by PikuZheng** [comment]
想知道如果一个域名既不在cn组又不在gfw组，你的配置是怎么处理的。

单看描述文字一头雾水，最好还是能把完整的配置文件发上来

**Comment by pymumu** [comment]
分流搞那么复杂干嘛？

将指定域名列表使用对应服务器查询不就可以了？

```
# 设置上游服务器
server-tls x.x.x.x -group oversea 
# 添加域名列表，格式为一行一个域名
domain-set -name public-domain-list -file /path/to/public/domain/list
# 设置对应域名列表的规则。
domain-rules /domain-set:public-domain-list/ -ipset public  -nftset #4:ip#table#set -c none -address #6 -nameserver oversea 
```

/path/to/public/domain/list的内容。

```
aaa.com
bbb.com
```

https://pymumu.github.io/smartdns/config/forwarding-with-ipset/

如果是LUCI的话，可以参考这个说明https://github.com/pymumu/smartdns/releases/tag/feature-dns-forwarding

**Comment by kyon777** [comment]
> 分流搞那么复杂干嘛？
> 
> 将指定域名列表使用对应服务器查询不就可以了？
> 
> ```
> # 设置上游服务器
> server-tls x.x.x.x -group oversea 
> # 添加域名列表，格式为一行一个域名
> domain-set -name public-domain-list -file /path/to/public/domain/list
> # 设置对应域名列表的规则。
> domain-rules /domain-set:public-domain-list/ -ipset public  -nftset #4:ip#table#set -c none -address #6 -nameserver oversea 
> ```
> 
> domain-rules的具体参数，要看你配合什么软件使用。
> 一般都是关闭测速，关闭IPV6，设置上游查询组为DOH, DOT类型的组。或者使用socks5代理查询的组。
> 
> /path/to/public/domain/list的内容。
> 
> ```
> aaa.com
> bbb.com
> ```
> 
> https://pymumu.github.io/smartdns/config/forwarding-with-ipset/
> 
> 如果是LUCI的话，可以参考这个说明https://github.com/pymumu/smartdns/releases/tag/feature-dns-forwarding
> 
> 

大佬 我就是想问下端口分流现在是怎么用的，最新版本。我是配合ad.home的。你这个答案感觉更麻烦吖，命令操作，还要去找域名列表。不能geoip:cn么。

**Comment by PikuZheng** [comment]
> 大佬 我就是想问下端口分流现在是怎么用的，最新版本。我是配合ad.home的。你这个答案感觉更麻烦吖，命令操作，还要去找域名列表。不能geoip:cn么。

bind :7053 -group cn
bind :8053 -group gw

这个是没错的，所有送到端口7053的会走cn上游，8053走gw上游。但是有两个问题你没有说，一是谁在53负责转发到对应端口，二是上游组和默认组如何配置的。

根据你说的现象，我猜测你需要增加一个bootstrap

**Comment by jxph1123** [comment]
还有一个你没有设置既不在CN又不在GW列表里的，走哪里呢？就是默认组必须要有一个。

**Comment by cresky-github** [comment]
纯靠端口，是不能分组的

分组，最终还是得靠域名表实现

**Comment by kyon777** [comment]
> > 大佬 我就是想问下端口分流现在是怎么用的，最新版本。我是配合ad.home的。你这个答案感觉更麻烦吖，命令操作，还要去找域名列表。不能geoip:cn么。
> 
> bind :7053 -group cn bind :8053 -group gw
> 
> 这个是没错的，所有送到端口7053的会走cn上游，8053走gw上游。但是有两个问题你没有说，一是谁在53负责转发到对应端口，二是上游组和默认组如何配置的。
> 
> 根据你说的现象，我猜测你需要增加一个bootstrap

![AD-HOME](https://github.com/pymumu/smartdns/assets/56829505/526c8164-d3dc-40ed-8949-495f3b449246)
![passwall](https://github.com/pymumu/smartdns/assets/56829505/ada8b8e5-0d1b-48ad-b25c-d53832d6de85)
![smdns-1](https://github.com/pymumu/smartdns/assets/56829505/5dbba3d4-b5dd-43b8-a158-e94efdd8dd3f)
![SMDNS-2](https://github.com/pymumu/smartdns/assets/56829505/1855e3b7-915c-4034-a58b-94eeba9b71d2)
![SMDNS-3](https://github.com/pymumu/smartdns/assets/56829505/9c5ad83a-dc92-4869-b397-15f0b9a30d16)

我是AD-HOME接管53端口,所有域名先去adhome.然后adhome再去smdns,passwall就走gw分组. 监听了端口,这样也还要域名分组吗? passwall这时候还不能先于smdns工作? 感觉精力用完了!! 求根据我的情况指点下,底层机制我是不懂他怎么走的. 我目前没设置域名列表,用着挺正常,但是我也不知道他是不是统一走的cn分组!

**Comment by kyon777** [comment]
如果一定要域名分组,也就是我还要去找国内的域名列表?干 工作量嘎嘎感人

**Comment by cresky-github** [comment]
> 如果一定要域名分组,也就是我还要去找国内的域名列表?干 工作量嘎嘎感人

国外/国内 域名表都行，二者选其一就行了。

域名表，网上有大把，随便找。比较权威的是geosite

**Comment by jxph1123** [comment]
用passwall smartdns版本的，分流的事情他帮你干了。

**Comment by PikuZheng** [comment]
> ![AD-HOME](https://user-images.githubusercontent.com/56829505/266397679-526c8164-d3dc-40ed-8949-495f3b449246.jpg)

单看这个图，是同时向国内外组发送dns查询请求了，没分流

**Comment by cresky-github** [comment]
> 
> > ![AD-HOME](https://user-images.githubusercontent.com/56829505/266397679-526c8164-d3dc-40ed-8949-495f3b449246.jpg)
> 
> 单看这个图，是同时向国内外组发送dns查询请求了，没分流
> 
> 



所以，有些行为让人觉得很迷惑。

本来，很简单的事，就加载一个域名表就能了事。

**Comment by kyon777** [comment]
搞了这么久，大概也知道原理了，反正就是要域名列表，域名列表自己去找！现在我这么设置 passwall ping google确实降了100多ms，将就用吧，不折腾列表了！smartdns的设置就不是面向小白的！
