### ISSUE TITLE
请问如何设置https协议类型的DNS？

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#149]
说明里边找不到例子，不如就以 https://cloudflare-dns.com/dns-query ，这个为例子吧？

**Comment by pymumu** [comment]
下面是配置说明：
# remote https dns server list
# server-https https://[host]:[port]/path [-blacklist-ip] [-spki-pin [sha256-pin]] [-group [group] ...] [-exclude-default-group]
#   -spki-pin: TLS spki pin to verify.
# default port is 443
# server-https https://cloudflare-dns.com/dns-query

例子：
server-https https://cloudflare-dns.com/dns-query

可以增加配置选项，-blacklist-ip, -spki-pin等。具体看ReadMe中的配置参数
注意，如果配置host为域名，则要求路由器本身的DNS要能正常工作。
否则可以改配置为IP地址。后面加-host-name指定主机名，配置如下：
server-https https://104.16.248.249/dns-query -host-name cloudflare-dns.com

**Comment by ztjal** [comment]
你这样的配置是添加在“自定义设置”吧，但如果是在以luci的界面里边添加到“上游服务器”时如何设置？

**Comment by pymumu** [comment]
选择类型https，把网址贴到host那一栏就可以了

**Comment by ztjal** [comment]
找到问题了，真是只能用IP的形式去填，如果只直填https://cloudflare-dns.com/dns-query的话，启动后报错说找不到cloudflare-dns.com然后smartdns自己就down了。（这里改进一下？）
ip填https://104.16.248.249/dns-query
HTTP主机填cloudflare-dns.com
这样才正常。
thx pymumu.
