### ISSUE TITLE
很诡异的问题，关于国内dns排除组国外dns为默认组问题！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#1490]
不配置自定义设置的情况下：
1、如果在luci界面配置国内dns为排除组，国外dns为默认组，国内组端口设置为53或其他端口，第二服务器端口配置为5335，如果不启动科学插件，无论是仅启用国内组还是国内和国外组全部启用，国内网络不通；
2、如果在luci界面配置国内dns为默认组，国外dns为排除组，国内组端口设置为53或其他端口，第二服务器端口配置为5335，科学插件无论是否启动，以及是否仅启用国内组还是国内和国外组全部启用，国内网络均正常；
请问这是什么原因？

**Comment by PikuZheng** [comment]
猜测你的代理劫持了dns或者和“代理自身”有关，具体要看开启前后的iptables。很可能关闭代理插件后，没有复位这些规则导致不通

**Comment by jxph1123** [comment]
理解下默认组，第一个国外dns为默认组，由于不启动科学插件，你的DNS是不通的，同时由于不启动科学插件，你的DNS请求根本不知道是国外，还是国内的，所以都是走的默认组解析。但是默认组DNS又不通，所以你上不了网。
第二个一样道理，国内dns为默认组，DNS请求全部走的默认组，所以你能上网。
所以martdns要配合科学插件区分国内国外，或者你自己手动给他列表区分国内还是国外，要不然都是走默认组。

**Comment by zxlhhyccc** [comment]
> 理解下默认组，第一个国外dns为默认组，由于不启动科学插件，你的DNS是不通的，同时由于不启动科学插件，你的DNS请求smartdns根本不知道是国外，还是国内的，所以都是走的默认组解析。但是默认组DNS又不通，所以你上不了网。 第二个一样道理，国内dns为默认组，DNS请求全部走的默认组，所以你能上网。 所以martdns要配合科学插件区分国内国外，或者你自己手动给他列表区分国内还是国外，要不然都是走默认组。

我其实已经是在给了smartdns域名列表，国内的列表和国外的列表，但是无效，只能考虑你理解的原因。

**Comment by zxlhhyccc** [comment]
> 猜测你的代理劫持了dns或者和“代理自身”有关，具体要看开启前后的iptables。很可能关闭代理插件后，没有复位这些规则导致不通

其实我根本未启动科学插件，哪里来的代理？

**Comment by zxlhhyccc** [comment]
> [1487](https://github.com/pymumu/smartdns/issues/1487) 你的跟我差不多,你可以看下我的设置,把端口监听了就行,如果你不监听端口,也不设置域名,都是走默认的!

按你的操作就是不设置自定义情况下，国内和国外均默认组？

**Comment by kyon777** [comment]
> > [1487](https://github.com/pymumu/smartdns/issues/1487) 你的跟我差不多,你可以看下我的设置,把端口监听了就行,如果你不监听端口,也不设置域名,都是走默认的!
> 
> 按你的操作就是不设置自定义情况下，国内和国外均为默认组？这个情况下与国内为默认组国外排除组没啥区别吧？
> 
> @kyon777 请问你最后解决了吗？如何解决的？能否发个你的配置，谢谢！

反正就是要域名列表，域名列表自己去找！我这个1487连接点进去就是我的设置，我是监听了端口，没有默认分组

**Comment by nxtreaming** [comment]
一两百毫秒级的优化确实没有意义，有墙存在了，对200毫秒的优化无感，这是技术人员自己感觉良好的优化，实际对用户体验没什么影响。

**Comment by nxtreaming** [comment]
为了毫秒级的优化，向多个upstream查询导致系统不稳定，这种收益不大。

**Comment by zxlhhyccc** [comment]
> 为了毫秒级的优化，向多个upstream查询导致系统不稳定，这种收益不大。

主要是解决dns泄漏问题。。。。

**Comment by cresky-github** [comment]
> > 为了毫秒级的优化，向多个upstream查询导致系统不稳定，这种收益不大。
> 
> 主要是解决dns泄漏问题。。。。



你用什么代理工具？
