### ISSUE TITLE
两个分组解析到的IP是一样的

### ISSUE THREAD

**Issue by WangNian007** [pymumu/smartdns#1491]
**问题现象**  
简要描述问题出现的现象
两个分组一个国内dns一个国外dns，解析到的ip是一样的饿

**运行环境**
1. 固件型号  
OpenWrt R23.8.23 / LuCI Master (git-23.232.27390-0a00628)
2. 运营商  
移动
3. smartdns来源以及版本
1.2023.42-1 源码编译
4. 涉及的配置(注意去除个人相关信息)
server-name smartdns

bind :6153 -group cn
bind-tcp :6153 -group cn

bind :6253 -group us -no-speed-check -no-cache
bind-tcp :6253 -group us -no-speed-check -no-cache

speed-check-mode ping,tcp:80,tcp:443

#force-AAAA-SOA yes

#force-qtype-SOA 65

serve-expired-reply-ttl 30

cache-size 40960

cache-file /etc/smartdns/smartdns.cache

dnsmasq-lease-file /var/lib/misc/dnsmasq.leases

rr-ttl-min 60
rr-ttl-max 86400

log-size 1M
log-num 2
log-file /etc/smartdns/smartdns.log

server-https https://doh.pub/dns-query -group cn
server-https https://dns.alidns.com/dns-query -group cn
server-https https://223.5.5.5/dns-query -group cn
server 223.5.5.5 -group cn
server 223.6.6.6 -group cn
server 180.76.76.76 -group cn
server 221.131.143.69 -group cn

server-https https://dns.google/dns-query -group us -exclude-default-group
server-https https://dns.quad9.net/dns-query -group us -exclude-default-group
server-https https://dns.cloudflare.com/dns-query -group us -exclude-default-group
server-https https://1.1.1.1/dns-query -group us -exclude-default-group
server 8.8.8.8 -group us -exclude-default-group
server 8.8.4.4 -group us -exclude-default-group
server 208.67.222.222 -group us -exclude-default-group

address /home.lan/192.168.1.1
![image](https://github.com/pymumu/smartdns/assets/116576935/1ee9caf8-fa96-4e20-afa2-1db52f0f8799)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
www.google.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
具体需要开debug日志看这两个结果怎么来的。我猜是运营商劫持

**Comment by hpcex** [comment]
域名是goole.com ?是不是少打了个g ?

**Comment by PikuZheng** [comment]
> 域名是goole.com ?是不是少打了个g ?

```
C:\Users\Administrator>nslookup www.goole.com. 223.6.6.6
服务器:  public2.alidns.com
Address:  223.6.6.6

非权威应答:
名称:    www.goole.com
Address:  217.160.0.201
```

好眼力

**Comment by WangNian007** [comment]
> > 域名是goole.com ?是不是少打了个g ?
> 
> ```
> C:\Users\Administrator>nslookup www.goole.com. 223.6.6.6
> 服务器:  public2.alidns.com
> Address:  223.6.6.6
> 
> 非权威应答:
> 名称:    www.goole.com
> Address:  217.160.0.201
> ```
> 
> 好眼力
感谢大佬
