### ISSUE TITLE
指定子域名解析问题求助

### ISSUE THREAD

**Issue by BAIYU2023** [pymumu/smartdns#1492]
指定子域名解析求助:
smartdns 版本 1.2023.08.11-1937

配置如下:
bind :2053 -no-speed-check -group cndns
bind-tcp :2053 -no-speed-check -group cndns

server 114.114.114.114
server 223.5.5.5
server-tcp 114.114.114.114
server 10.10.10.10
server-tcp 10.10.10.10
server 223.6.6.6 -group cndns -exclude-default-group

nameserver /mail.tclet.com/cndns

求助问题说明：
1.10.10.10.10 属于集团内部dns服务器，与smartdns互通。
2. 通过以上配置文件发现mail.tclet.com从总部dns 10.10.10.10 获取了内网IP 10.10.10.1 
3. 要求是子域名 mail.tclet.com 域名指向 223.6.6.6解析 ，其它所有tclet.com的子域名（如:erp.tclet.com......）指向总部10.10.10.10解析
求助详细配置命令。谢谢！

**Comment by PikuZheng** [comment]
上面写法是正确的，有没有可能是集团劫持了udp/53
