### ISSUE TITLE
Linux 系统怎么样升级不影响DNS服务？

### ISSUE THREAD

**Issue by gexiaopeng** [pymumu/smartdns#1494]
我的系统是CentOS，怎么样无缝升级不影响原来的smartdns服务？（几秒影响也可以接受）

**Comment by PikuZheng** [comment]
再准备一台临时的，等升级完再迁回来。
或者打keepalived之类的ha。

CentOS升级，就算是只重启，也不止几秒钟

**Comment by gexiaopeng** [comment]
> 再准备一台临时的，等升级完再迁回来。 或者打keepalived之类的ha。
> 
> CentOS升级，就算是只重启，也不止几秒钟

这样不是很友好，最好在install脚本里有update选项，这个也是一般应用升级的常规做法

**Comment by pymumu** [comment]
直接卸载重装，配置都会保留的，smartdns重启一般都在1s内。

**Comment by gexiaopeng** [comment]
> 直接卸载重装，配置都会保留的，smartdns重启一般都在1s内。

但是卸载需要时间，这个不止几秒吧。最好安装的时候能覆盖主程序，保留配置，这样影响就小一些。

**Comment by gexiaopeng** [comment]
或者install增加 reinstall功能，重新安装（如果已经安装，覆盖主程序），同时保留配置文件。

**Comment by gexiaopeng** [comment]
> 直接卸载重装，配置都会保留的，smartdns重启一般都在1s内。

卸载重装以后，/etc/default/smartdns 文件被覆盖了，我设置了SMART_DNS_OPTS=  -c /etc/smartdns/smartdns2.conf

**Comment by pymumu** [comment]
程序没多大的，卸载安装1s内。

**Comment by pymumu** [comment]
如果是tar包的话，执行
./install -u
./install -i

**Comment by gexiaopeng** [comment]
> 如果是tar包的话，执行 ./install -u ./install -i

如果我在其他服务器安装好以后，把/usr/sbin/smartdns 文件复制过来 覆盖老的可以吗？

**Comment by pymumu** [comment]
卸载加安装的时间：
```
time (./install -u && ./install -i)

real    0m1.634s
user    0m0.093s
sys     0m0.025s
```

**Comment by PikuZheng** [comment]
>Linux 系统怎么样升级不影响DNS服务？

。。。我以为你的问题是要升级整个操作系统

**Comment by PikuZheng** [comment]
> 如果我在其他服务器安装好以后，把/usr/sbin/smartdns 文件复制过来 覆盖老的可以吗？

直接下载对应的运行文件，覆盖掉原文件就可以了。不需要在其他环境下再安装一遍

**Comment by liangxyz** [comment]
> > 如果我在其他服务器安装好以后，把/usr/sbin/smartdns 文件复制过来 覆盖老的可以吗？
> 
> 直接下载对应的运行文件，覆盖掉原文件就可以了。不需要在其他环境下再安装一遍

大佬你好，请问你编译的smartdns，后缀带edns的是什么版本啊？有什么作用？

**Comment by PikuZheng** [comment]
带edns的支持配置`server..... -check-edns`，用于校验上游dns服务器的edns附加信息。如果edns信息不匹配或上游不支持edns，将丢弃该查询结果

**Comment by liangxyz** [comment]
> 带edns的支持配置`server..... -check-edns`，用于校验上游dns服务器的edns附加信息。如果edns信息不匹配或上游不支持edns，将丢弃该查询结果

感谢解答，看来一般用不带edns的就行了

**Comment by CallMeR** [comment]
> 或者install增加 reinstall功能，重新安装（如果已经安装，覆盖主程序），同时保留配置文件。

reinstall 功能 +1

**Comment by pymumu** [comment]
最新代码./install -U
