### ISSUE TITLE
域名地址设置带通配符的域名禁止解析ipv6地址无效

### ISSUE THREAD

**Issue by lwb1978** [pymumu/smartdns#1498]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
 ImmortalWrt  6.1
2. 运营商  

3. smartdns来源以及版本
43
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
比如我要禁止解析microsoft.com或者他的子域名解析ipv6地址，在域名地址中设置：
address /“星号”-a.microsoft.com/#6 或者 address /“星号”.microsoft.com/#6 或者 address /-.microsoft.com/#6
都无效，用nslookup仍然可以解析到ipv6地址，如果去掉通配符的话就可以成功禁止：
address /microsoft.com/#6

**Comment by PikuZheng** [comment]
大致测了一下这里似乎的确有问题的@pymumu

**Comment by pymumu** [comment]
最新代码修正了。
