### ISSUE TITLE
请问小米路由HD IPQ8064 使用哪个版本

### ISSUE THREAD

**Issue by lixiangjing233** [pymumu/smartdns#15]
如题

**Comment by pymumu** [comment]
请看指导页面的下载章节的说明。



CPU架构可在路由器管理界面找到，查看方法： 登录路由器，点击System->Software，点击Configuration Tab页面，在opkg安装源中可找到对应软件架构，下载路径中可找到，如下，架构为ar71xx

src/gz chaos_calmer_base http://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/packages/base

请在Release页面下载：此处下载

**Comment by pymumu** [comment]
opkg info zlib | grep Architecture

看这个命令输出。
根据这个输出的结果选择安装包。

**Comment by lixiangjing233** [comment]
蟹蟹

**Comment by lixiangjing233** [comment]
试着安装了一下 报错but incompatible with the architectures configured 应该是CPU架构不对 IPQ8064是Krait 300架构的 望后期跟进支持

**Comment by pymumu** [comment]
opkg list列出已经安装的软件包，在找任意一个软件包执行opkg info，看一下Archetecture.

**Comment by pymumu** [comment]
那应该是无法支持的。安装包格式都不同。

**Comment by lixiangjing233** [comment]
![qq 20180827120130](https://user-images.githubusercontent.com/42439782/44639882-f5730080-a9f0-11e8-821e-8a5db48b6712.png)
唉 可是还是哪个版本的软件包都装不上  incompatible with the architectures configured 难受了
