### ISSUE TITLE
希望可以支持alpine

### ISSUE THREAD

**Issue by ghostry** [pymumu/smartdns#150]
**需求应用场景**
docker方式使用,alpine更小

**建议的方案**
支持alpine系统

**设备信息**
1. 设备信息（CPU，厂家）  
x86_64
2. 固件信息

当我
```
docker run --rm -it alpine:edge sh
apk add openssl
wget https://github.com/pymumu/smartdns/releases/download/Release24/smartdns.1.2019.04.25-2140.x86_64.tar.gz
tar zxvf smartdns.1.2019.04.25-2140.x86_64.tar.gz
/smartdns/src/smartdns
```
我会得到一个
`sh: /smartdns/src/smartdns: not found`
文件是存在的,不知道为什么会得到这个.

**Comment by AeolusC** [comment]
https://github.com/Leoyzen/docker-smartdns
我看到这位用的alpine
这东西要openssl 1.0.X 
alpine 3.9以上含3.9的版本是不行的

**Comment by ghostry** [comment]
> https://github.com/Leoyzen/docker-smartdns
> 我看到这位用的alpine
> 这东西要openssl 1.0.X
> alpine 3.9以上含3.9的版本是不行的

这个很好.谢了
