### ISSUE TITLE
Source IP DNS Query > Different Upstream DNS Resolver

### ISSUE THREAD

**Issue by TCB13** [pymumu/smartdns#1500]
Hello,

Consider I've Smartdns (10.0.0.1:53) on a network (10.0.0.0/24) with multiple devices acting as their DNS server. Is there a way to specific a different DNS server group to be used to answer queries of a specific machine eg. 10.0.0.25?

What I want is to have all computers resolving DNS to 1.1.1.1 but ONE specific machine use another upstream server eg. 208.67.222.222.

Thank you.

**Comment by PikuZheng** [comment]
I don't quite understand, but why not configure the dns server to 208.67.222.222 on this computer

**Comment by TCB13** [comment]
> I don't quite understand, but why not configure the dns server to 208.67.222.222 on this computer

Because it is multiple computers it would be better to have centralizes control on smartdns server. 

Groups are very useful why not make them consider the source IP of the DNS query as well?

**Comment by PikuZheng** [comment]
maybe you can use a firewall to redirect dns requests from a specific ip to another server port.

or waiting for the future #1247

**Comment by TCB13** [comment]
> maybe you can use a firewall to redirect dns requests from a specific ip to another server port.
> 
> or waiting for the future #1247

That's what I've been doing. Thanks for letting me know about #1247 that would close this.

**Comment by pymumu** [comment]
Try latest code

https://pymumu.github.io/smartdns/en/config/client-rule/

**Comment by TCB13** [comment]
> Try latest code
> 
> https://pymumu.github.io/smartdns/en/config/client-rule/

https://pymumu.github.io/smartdns/en/config/domain-address/

Thank you very much!
