### ISSUE TITLE
请问全局测速开关与域名规则中的测速开关的关系是什么？

### ISSUE THREAD

**Issue by xshzr** [pymumu/smartdns#1502]
请问一下，全局设置speed-check-mode none的情况下，在domain-rules里配置的测速选项 -speed-check-mode tcp:443,tcp:80，还能生效吗？实测好像不行？

我的需求是：domain-rules里的域名列表单走一个组需要测速，其他未归类域名走默认组，而默认组不测速。但服务器组又不支持测速开关设置？

另外顺便问问如果服务器组使用了-subnet参数，相当于查询EDNS，是否就没有必要测速了？

**Comment by PikuZheng** [comment]
> 全局设置speed-check-mode none的情况下，在domain-rules里配置的测速选项 -speed-check-mode tcp:443,tcp:80

我一直是这样用的，我记得这样是可以的



> 如果服务器组使用了-subnet参数，相当于查询EDNS，是否就没有必要测速了

我是同时用的，原因是edns和测速不是一回事，上游觉得你最佳的实际不一定是最佳的
