### ISSUE TITLE
添加了TCP测速，但是解析得到的IP，端口都不通

### ISSUE THREAD

**Issue by dshipeng** [pymumu/smartdns#1506]
**问题现象**  
目前想要通过多个上游DNS服务器源，拿到一个最优IP去访问。目前配置测速模式是ping,tcp:80,tcp:443

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  
server 223.87.238.22
server 183.230.98.97
server 180.76.76.76
server 202.141.162.123
server 101.6.6.6
force-qtype-SOA 65
log-level debug
force-AAAA-SOA yes

2. 访问的域名。  
p16-oec-va.ibyteimg.com
解析到的IP：184.50.87.17

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by dshipeng** [comment]
![image](https://github.com/pymumu/smartdns/assets/13672773/e291b39b-48fc-400a-b108-a145e23b231a)
我配置修改成tcp:443,tcp:80好像也不行啊，还是会解析到443端口不通的IP

**Comment by CallMeR** [comment]
你这是解析到了 443 不通的域名所以就回退监测 80 了吧。

**Comment by PikuZheng** [comment]
connect refused也是应答，算在测速内

**Comment by PikuZheng** [comment]
connect refused也是应答，算在测速内

**Comment by PikuZheng** [comment]
tcp测速只是计算握手时间
