### ISSUE TITLE
`ddns-domain`响应的 IP 是回环地址`127.0.0.1`

### ISSUE THREAD

**Issue by devnakx** [pymumu/smartdns#1507]
![image](https://github.com/pymumu/smartdns/assets/38558065/cf20eca8-e5a9-41e2-b13c-9d17f4cafdd5)
我是 docker 容器运行的，但容器网络模式是`host`
按理来说应该是获取WAN口的IP地址吧，但实际返回的却是`127.0.0.1`

**Comment by PikuZheng** [comment]
所以你的容器获取到主机同网段ip地址没有

**Comment by devioa** [comment]
> 所以你的容器获取到主机同网段ip地址没有

怎样验证？
