### ISSUE TITLE
关于`edns-client-subnet`的疑问，配置后带`-proxy`参数的 server 也会在请求时发送客户端子网信息吗？

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#1508]
按理说应该不会发送吧，毕竟我都通过代理服务器查询了，再发送客户端子网那不是又回到了原点？

**Comment by PikuZheng** [comment]
edns-client-subnet 是全局参数，所有上游都会带上edns信息。
如果想几个上游带几个上游不带，请指定`-subnet`
