### ISSUE TITLE
新版在 没有配置上游服务器的前提下也可以上网冲浪

### ISSUE THREAD

**Issue by huoyubaba** [pymumu/smartdns#1509]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
openwrt23.05
2. 运营商  

3. smartdns来源以及版本
最新最新版
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
没有配置上游时，会取系统dns（resolv.conf

**Comment by huoyubaba** [comment]
请问大佬 ，下载网络文件命令是什麽 自动更新的命令怎么写

**Comment by CallMeR** [comment]
> 请问大佬 ，下载网络文件命令是什麽 自动更新的命令怎么写

仅供参考：

```bash
$ sudo crontab -e
```

```bash
0 5 * * * /usr/bin/wget -q --tries=10 --retry-connrefused --random-wait https://anti-ad.net/anti-ad-for-smartdns.conf -O /etc/smartdns/anti-ad-smartdns.conf

30 5 * * * /usr/bin/systemctl restart smartdns.service
··
