### ISSUE TITLE
asus ac1900p Merlin固件entware下无法安装

### ISSUE THREAD

**Issue by ggllioio** [pymumu/smartdns#151]
**问题现象**  
asus ac1900p 在原版Merlin固件entware环境下无法安装。

**运行环境** 

Model | RT-AC1900P
Firmware Version | 384.11_beta2
Firmware Build | Thu May 2 19:59:12 UTC 2019 merlin@b043583

`# uname -a`
`Linux RT-AC1900P-B2E8 2.6.36.4brcmarm #1 SMP PREEMPT Thu May 2 16:07:52 EDT 2019 armv7l ASUSWRT-Merlin`

通过Merlin固件自带entware-setup.sh 装上entware环境。
没有ipkg命令，使用opkg安装会报错：
`# cd /tmp/mnt/sda1/`
`# opkg install smartdns.1.2019.04.25-2140.arm.ipk`
`Segmentation fault`

**Comment by ggllioio** [comment]
装了libopenssl，还是报错。
`# opkg install libopenssl`
`Package libopenssl (1.1.1a-2) installed in root is up to date.`
`/tmp/mnt/sda1# opkg install smartdns.1.2019.04.25-2140.arm.ipk`
`Segmentation fault`

**Comment by pymumu** [comment]
openssl要1.0.x的版本。

**Comment by ggllioio** [comment]
ent的源里边没有1.0版本，不过看了下固件自带的openssl。
正常应该不用手动安装就行吧。
`# open`
`openssl    openssl11  openvpn`
`# openssl version`
`OpenSSL 1.0.2r  26 Feb 2019`
`# openssl11 version`
`OpenSSL 1.1.1b  26 Feb 2019`

这是entware的包。
`# opkg list-installed`
...
libopenssl - 1.1.1a-2
...

**Comment by pymumu** [comment]
ldd /opt/usr/sbin/smartdns
看一下什么输出。

**Comment by ggllioio** [comment]
`# ldd /opt/usr/sbin/smartdns`
`-sh: /opt/usr/sbin/smartdns: not found`

`# ls /opt/`
`bin    etc    home   lib    root   sbin   share  tmp    usr    var`
`# ls /opt/usr/`
`lib/    share/`

`# ls /tmp/mnt/sda1/entware/`
`bin    etc    home   lib    root   sbin   share  tmp    usr    var`

好像没有这个目录

**Comment by pymumu** [comment]
应该都没有安装成功。
确认一下entware是不是配套的把。
比如，安装一个entware库中已有命令，执行安装的命令看看能不能成功。

**Comment by ggllioio** [comment]
执行已有命令可以成功的，比如libopenssl - 1.1.1a-2这个和htop，就是直接通过
opkg update
opkg install htop
opkg install libopenssl
安装上的。

**Comment by pymumu** [comment]
看情况是指令集不支持导致，需要对应的编译环境才可以运行。

请把entware的库路径发一下。

**Comment by ggllioio** [comment]
抱歉刚看到，entware路径：
http://bin.entware.net/armv7sf-k2.6/Packages.gz

**Comment by ggllioio** [comment]
ac68u应该也是这个，毕竟固件都是同一个

**Comment by lalasou** [comment]
求编译啊
armv7   
软件源http://pkg.entware.net/binaries/armv7/Packages.html
不能用啊 
斐讯k3 
这个用的还是比较多的  求配套 求指导 大佬

**Comment by pymumu** [comment]
尝试Release 26静态编译版本把。
