### ISSUE TITLE
日志输出到终端不生效log-console yes

### ISSUE THREAD

**Issue by ixmu** [pymumu/smartdns#1514]
**问题现象**  
log-console yes
日志输出到终端不生效

**运行环境**
debian12
smartdns 0811版本
配置文件中设置了参数log-console yes

**Comment by pymumu** [comment]
我这测试是好的。

log-console yes

可以看一下进程的1，2文件句柄是什么？

lsof -p [pid]

**Comment by ixmu** [comment]
> lsof -p [pid]

`
SmartDNS:~# lsof -p 17962
1       /bin/busybox    0       /dev/pts/0
1       /bin/busybox    1       /dev/pts/0
1       /bin/busybox    2       /dev/pts/0
366     /bin/busybox    0       socket:[12983724]
366     /bin/busybox    1       /dev/null
366     /bin/busybox    2       /dev/null
366     /bin/busybox    3       /var/log/messages
393     /bin/busybox    0       /dev/null
393     /bin/busybox    1       /dev/null
393     /bin/busybox    2       /dev/null
393     /bin/busybox    3       socket:[12983753]
439     /usr/sbin/sshd  0       /dev/null
439     /usr/sbin/sshd  1       /dev/null
439     /usr/sbin/sshd  2       /dev/null
439     /usr/sbin/sshd  3       socket:[12983822]
439     /usr/sbin/sshd  4       socket:[12983824]
445     /bin/busybox    0       /dev/console
445     /bin/busybox    1       /dev/console
445     /bin/busybox    2       /dev/console
446     /bin/busybox    0       /dev/tty1
446     /bin/busybox    1       /dev/tty1
446     /bin/busybox    2       /dev/tty1
447     /bin/busybox    0       /dev/tty2
447     /bin/busybox    1       /dev/tty2
447     /bin/busybox    2       /dev/tty2
448     /bin/busybox    0       /dev/tty1
448     /bin/busybox    1       /dev/tty1
448     /bin/busybox    2       /dev/tty1
448     /bin/busybox    10      /dev/tty
2875    /bin/busybox    0       /dev/tty1
2875    /bin/busybox    1       /dev/tty1
2875    /bin/busybox    2       /dev/tty1
2875    /bin/busybox    3       /var/log/smartdns/smartdns.log.pending (deleted)
17962   /usr/sbin/smartdns      0       /dev/null
17962   /usr/sbin/smartdns      1       /dev/null
17962   /usr/sbin/smartdns      2       /dev/null
17962   /usr/sbin/smartdns      3       /run/smartdns.pid
17962   /usr/sbin/smartdns      4       socket:[95546956]
17962   /usr/sbin/smartdns      5       anon_inode:[eventpoll]
17962   /usr/sbin/smartdns      6       anon_inode:[eventfd]
17962   /usr/sbin/smartdns      7       anon_inode:[eventpoll]
17962   /usr/sbin/smartdns      8       socket:[95529670]
17962   /usr/sbin/smartdns      9       socket:[95529671]
17962   /usr/sbin/smartdns      10      socket:[95529672]
17962   /usr/sbin/smartdns      11      /var/log/smartdns/smartdns.log
17962   /usr/sbin/smartdns      12      anon_inode:[eventfd]
17962   /usr/sbin/smartdns      13      anon_inode:[eventpoll]
17962   /usr/sbin/smartdns      14      anon_inode:[eventfd]
17962   /usr/sbin/smartdns      15      socket:[95546957]
17962   /usr/sbin/smartdns      16      socket:[95546958]
17962   /usr/sbin/smartdns      17      socket:[95546959]
17962   /usr/sbin/smartdns      18      socket:[95546960]
17962   /usr/sbin/smartdns      19      socket:[95546962]
18074   /usr/sbin/sshd  0       /dev/null
18074   /usr/sbin/sshd  1       /dev/null
18074   /usr/sbin/sshd  2       /dev/null
18074   /usr/sbin/sshd  3       /dev/ptmx
18074   /usr/sbin/sshd  4       socket:[99271797]
18074   /usr/sbin/sshd  6       socket:[99271813]
18074   /usr/sbin/sshd  7       /dev/ptmx
18074   /usr/sbin/sshd  8       /dev/ptmx
18076   /bin/busybox    0       /dev/pts/3
18076   /bin/busybox    1       /dev/pts/3
18076   /bin/busybox    2       /dev/pts/3
18076   /bin/busybox    10      /dev/tty
`

**Comment by PikuZheng** [comment]
可以考虑配置 `log-file /proc/self/fd/1`

**Comment by PikuZheng** [comment]
或者可能smartdns以服务方式运行，可能拿不到当前用户的控制台。先试试前台运行看日志输出是否正确？

**Comment by ixmu** [comment]
> 或者可能smartdns以服务方式运行，可能拿不到当前用户的控制台。先试试前台运行看日志输出是否正确？

应该是这样的，我以服务的方式运行
