### ISSUE TITLE
删除后无法自动生成缓存文件

### ISSUE THREAD

**Issue by BlueDolphin9527** [pymumu/smartdns#1515]
smartdns 1.2023.42，Sirpdboy编译的X86-64版本固件，内核为6.1.52。
smartdns删除缓存文件后，除非重启openwrt，否则不会重新生成缓存文件。

**Comment by PikuZheng** [comment]
预期行为。缓存文件只有在关闭smartdns时才会写入存储。如果想不时的保存一次，请使用`cache-checkpoint-time`指定保存间隔时间

**Comment by BlueDolphin9527** [comment]
![image](https://github.com/pymumu/smartdns/assets/62049321/02df0c48-fa65-4c8b-b781-84b60e8ecb15)
![image](https://github.com/pymumu/smartdns/assets/62049321/3adc0af7-9418-4cb4-887b-d2e90e9cd597)
![image](https://github.com/pymumu/smartdns/assets/62049321/7929d33b-3e8e-413b-a80b-209f1da4597d)
我在custom.conf里配置了每6小时保存一次，并且指定保存位置，可是现在软路由工作2天多了，在这个位置里仍未找到缓存文件。

**Comment by PikuZheng** [comment]
`cache-file /etc/smartdns`
存在同名文件夹，没法作为文件写入啊

**Comment by BlueDolphin9527** [comment]
我之前成功了，在这个文件夹里看到了缓存文件，就是删除后才没再看到的。我现在改到其它位置试试。

**Comment by BlueDolphin9527** [comment]
> `cache-file /etc/smartdns` 存在同名文件夹，没法作为文件写入啊

一个是文件夹，一个是文件，这样同名不行吗？缓存不应该是smartdns.cache?

**Comment by PikuZheng** [comment]
> 一个是文件夹，一个是文件，这样同名不行吗？

啥文件系统都不能这样啊

**Comment by BlueDolphin9527** [comment]
> > 一个是文件夹，一个是文件，这样同名不行吗？
> 
> 啥文件系统都不能这样啊

好吧，现在还没有，我等到明天再看下。
