### ISSUE TITLE
下载广告屏蔽规则，文件位置在哪？

### ISSUE THREAD

**Issue by BlueDolphin9527** [pymumu/smartdns#1516]
smartdns 1.2023.42，Sirpdboy编译的X86-64版本固件，内核为6.1.52。
根据提示，这些文件应该在/etc/smartdns/conf.d/下，但并未找到，却可以在高级设置包含配置文件里直接通过文件名引用，而非路径+文件名。包含配置文件下面的提示语为“包含配置文件，路径为/etc/smartdns/conf.d，或自定义配置文件路径，可以从下载页”，可以看到这些文件应该是在/etc/smartdns/conf.d/下的。我搜索文件名，在/tmp/下找到了这三个广告屏蔽文件名，但是却是空的，里面什么规则都没有，奇怪的是，通过nslooup这三个广告屏蔽规则里的域名，却都屏蔽了。请帮忙排查一下。
重启OP后只有第一个规则正常。
![image](https://github.com/pymumu/smartdns/assets/62049321/bb6cf7bd-77dd-43bc-98d5-aa3e38f32103)
![image](https://github.com/pymumu/smartdns/assets/62049321/80773b52-6d36-4354-84ff-ecbecc11bb28)
![image](https://github.com/pymumu/smartdns/assets/62049321/0fe4254e-8e8d-4b0d-8432-f26d65927bf8)

**Comment by tycn888** [comment]
![image](https://github.com/pymumu/smartdns/assets/77333646/a7220b3c-1090-4227-b9e3-8ae7c7359b97)
更新会出错，不知道怎么回事？有时候可以下载，之后就不行了。

**Comment by PikuZheng** [comment]
要不要考虑一下openwrt自身的dns是不是一直可用的

**Comment by tycn888** [comment]
> 要不要考虑一下openwrt自身的dns是不是一直可用的

感谢回复，原来把openwrt的 DNS设置成127.0.0.1了，删除就好了。

**Comment by hwliu11** [comment]
在自定义设置加上 conf-file /etc/smartdns/conf.d/anti-ad-for-smartdns.conf就起作用了，更新在计划任务加一条下载重启smartdns

**Comment by iamyangyiok** [comment]
> conf-file /etc/smartdns/conf.d/anti-ad-for-smartdns.conf

你好 请教下这个CONF 怎么写ANTI -AD进去

**Comment by PikuZheng** [comment]
> > conf-file /etc/smartdns/conf.d/anti-ad-for-smartdns.conf
> 
> 你好 请教下这个CONF 怎么写ANTI -AD进去

上面讨论的是下载现成的anti-ad（别人写好并公开在网站上的
