### ISSUE TITLE
请教下各位大佬，我在openwrt中已经安装了软件包，但在服务中还是看不到是为什么呀

### ISSUE THREAD

**Issue by zxbzxb180** [pymumu/smartdns#1517]
**问题现象**  
请教下各位大佬，我在openwrt中已经安装了软件包，但在服务中还是看不到是为什么呀？

**运行环境**
1. 固件版本
OpenWrt R21.7.1.100

![image](https://github.com/pymumu/smartdns/assets/50437772/b2def7a8-c8c2-4d98-bc7f-c2d1e9e68c7e)

**Comment by PikuZheng** [comment]
重复 https://github.com/pymumu/smartdns/issues/992 https://github.com/pymumu/smartdns/issues/1011 https://github.com/pymumu/smartdns/issues/1040 https://github.com/pymumu/smartdns/issues/1044 #1085

**Comment by zxbzxb180** [comment]
感谢

**Comment by kevingekun** [comment]
请问最后咋解决的

**Comment by dushoufoxin** [comment]
我的也是安装了ddns-go后能看到安装成功但是不显示。openwrt的bug
