### ISSUE TITLE
能否增加arm v5的openwrt支持

### ISSUE THREAD

**Issue by nivrrex** [pymumu/smartdns#152]
路由器是linksys的EA4500 V1版，固件是官方openwrt 18.06.2
无法安装smartdns，查询后发现路由器的CPU是Marvell的88F6282，arm v5的
而目前smartdns仅支持arm v7及以上版本
咨询下后期是否会增加arm v5的openwrt支持？还是没有这个计划？

**Comment by pymumu** [comment]
opkg print_architecture
这个命令输出是什么

**Comment by nivrrex** [comment]
arch all 1
arch noarch 1
arch arm_xscale 10

**Comment by pymumu** [comment]
现在不支持，没有编译环境。准备编译环境可能需要一段时间。
看下个版本能不能加进去吧。

**Comment by nivrrex** [comment]
好的，感谢

**Comment by lalasou** [comment]
armv7 下载哪一个  我下载 arm  安装不了

**Comment by pymumu** [comment]
[hello.zip](https://github.com/pymumu/smartdns/files/3272746/hello.zip)

麻烦验证一下这个能否执行。

**Comment by pymumu** [comment]
尝试Release 26静态编译版本把。
