### ISSUE TITLE
希望增加个日志功能

### ISSUE THREAD

**Issue by lizhiwei8061** [pymumu/smartdns#1523]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  
x86
2. 固件信息

**Comment by openips** [comment]
有日志

**Comment by lizhiwei8061** [comment]
前端没法查看把 只能去后端查看

**Comment by zxlhhyccc** [comment]
> 前端没法查看把 只能去后端查看

我明天来试试在前端添加一个日志功能！

**Comment by zxlhhyccc** [comment]
请各位大佬提意见，谢谢！

**Comment by pymumu** [comment]
审计日志放到界面上可能更有价值。

运行日志，只有在调试的时候，才会使用。

**Comment by zxlhhyccc** [comment]
> 审计日志放到界面上可能更有价值。
> 
> 运行日志，只有在调试的时候，才会使用。

大佬，一般情况下不会使用审计日志吧？反正我没使用过哦

**Comment by pymumu** [comment]
最新版本可以输出日志到系统日志
