### ISSUE TITLE
ddns handling

### ISSUE THREAD

**Issue by IgorBai** [pymumu/smartdns#1524]
Hi. 
Please provide some hints how to handle ddns better. E.g. my friend router has a ddns address “ddnsname.provider.com”. And that provider’s dns address is “dns.provider.com”. To faster obtain the updated IPs my smartdns shouldn’t inquire the local ISP but ask that “dns.provider.com” instead, right? So which commands are needed to make “dns.provider.com” the primary/sole dns server for “ddnsname.provider.com”, and also how to switch off dns cache for this “ddnsname.provider.com” domain?

P.S. I’ve tried some changes in /etc/config/smartdns and Luci like the one below, they didn’t work for me:
<pre><code>config domain-rule    
     option domain_rules /ddns.com/ --no-serve-expired
</code></pre>

**Comment by PikuZheng** [comment]
I didn't understand but for ddns domain names, no-cache is a better option. You also need to choose an upstream server that does not have TTL expiration cache.
In addition, if the domain name corresponds to a local intranet address, you can specify it using a static address.

**Comment by PikuZheng** [comment]
make a group, use dynv6.com as upstream and assign the ddns hostname to this group
