### ISSUE TITLE
能自定义配置文件路径吗？需要用什么启动命令修改呢

### ISSUE THREAD

**Issue by lkxlzx** [pymumu/smartdns#1528]
**需求应用场景**
自定义配置文件路径
**建议的方案**

添加启动参数 -v 
**设备信息**
我需要做一个DNS工具包的docker 合集，需要统一配置文件路径

**Comment by pymumu** [comment]
smartdns -h可以看到命令行参数。

**Comment by PikuZheng** [comment]
https://github.com/PikuZheng/smartdns/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0

**Comment by lkxlzx** [comment]
谢谢搞定了
