### ISSUE TITLE
smartdns使用DoH问题

### ISSUE THREAD

**Issue by chinadna25556** [pymumu/smartdns#1529]
**问题现象**  
今天在smartdns里面添加上游服务器为DoH
发现不能解析
然后又换回udp的dns

**重现步骤**
1. https://120.53.53.53/dns-query  
2. 协议类型 https

**Comment by PikuZheng** [comment]
刚试了我这里是正常的

**Comment by chinadna25556** [comment]
> 刚试了我这里是正常的

你好，能截图下怎么设置的吗？除了填写https的解析地址外，下面的主机名之类的需要填写吗？新版本好像不需要填写端口号了，我昨天在列表里面强制填写443也不行。

**Comment by PikuZheng** [comment]
我是直接写在配置文件里的，不用一行一行又填又选的。如果是在luci里逐行填，在ip里填`https://120.53.53.53/dns-query`就行了，名称和端口都不需要填。类型是https，服务器组看自己需求

**Comment by tycn888** [comment]
> 我是直接写在配置文件里的，不用一行一行又填又选的。如果是在luci里逐行填，在ip里填`https://120.53.53.53/dns-query`就行了，名称和端口都不需要填。类型是https，服务器组看自己需求

我测试用htyps：//域名：端口号 也是可以的。
