### ISSUE TITLE
希望 address.conf 支持外部导入配置功能

### ISSUE THREAD

**Issue by kangyu1230** [pymumu/smartdns#153]
**需求应用场景**
我用的是Koolshare OpenWRT，了解到SmartDNS可通过address.conf支持广告屏蔽功能，写了个脚本将hosts文件转换为address.conf匹配的格式（address /ad.com/#）,
但条目非常多，近一万条，后台保存重启服务没有问题，但在Luci界面配置SmartDNS会非常卡，经常把uhttpd卡死，只得ssh重启uhttpd，进而无法在Luci界面保存配置。
希望address.conf支持外部导入配置功能，这样在address.conf中只需要添加一条导入/包含的语句，而且可以避免Luci界面中加载太多内容导致崩溃。谢谢。

**建议的方案**
可以参考Nginx或Caddy，类似于“include /etc/smartdns/my_address.conf” 或 “import /etc/smartdns/my_config/*”

**设备信息**
1. 设备信息（CPU，厂家）  
	Intel CPU
2. 固件信息
	Koolshare OpenWRT mod 2.26

**Comment by pymumu** [comment]
smartdns目前支持使用自定义路径配置，参数为
```shell
conf-file [path]
```
可以在custom配置页面指定address.conf路径，类似如下语句
```
conf-file /etc/smartdns/my_address.conf
```

**Comment by kangyu1230** [comment]
感谢~
