### ISSUE TITLE
域名列表和IP列表集合配置疑问求解

### ISSUE THREAD

**Issue by kaowul** [pymumu/smartdns#1539]
server 223.5.5.5 -whitelist-ip
#8.8.8.8已经通过上级路由独立线路不存在污染可能
server 8.8.8.8  -group gfw-dns  
#国内IP地址列表
ip-set -name all_china_ip -file /home/smartdns/all_china_ip.conf
ip-rules ip-set:all_china_ip -whitelist-ip
#Gfw_List域名使用gfw-dns解析，禁用测速
domain-set -name gfw_domain -type list -file /home/smartdns/gfw_domain.conf
domain-rules /domain-set:gfw_domain/ -nameserver gfw-dns -speed-check-mode none

all_china_ip.conf 每行一个IP，gfw_domain.conf每行一个域名
把IP和域名独立文件是为了方便维护
这样配置测均无效，是语法有错误？

这样配置的目的是想实现：解析结果为国内IP的通过白名单IP直接返回给client，gfw域名列表内的只使用国外dns获取结果。
这样配置可以实现防污染解析？

**Comment by kaowul** [comment]
通过现在最新源码编译问题得到解决。

 /home/smartdns/smartdns -v
smartdns 1.2023.08.11-1937 
这个版本 ip-set部分无法生效

**Comment by PikuZheng** [comment]
> 遇到类似问题，测试发现比如对于百度的ip `36.155.132.55` 通过`ip-rules 36.128.0.0/10 -whitelist-ip`加入whitelist-ip无法生效，但是通过`whitelist-ip 36.128.0.0/10`可以生效 在我的理解中这应该是等价的吧 whitelist-ip不支持ip-set，因此无法把一个ip-set加入whitelist-ip
> 
> smartdns版本： ![图片](https://user-images.githubusercontent.com/46527539/280666795-245e3a1a-1ff0-4b2c-aeae-d8643d85a4c9.png)

ip-rules 需要43.0.8（20230907）或更高版本

**Comment by LostAttractor** [comment]
> > 遇到类似问题，测试发现比如对于百度的ip `36.155.132.55` 通过`ip-rules 36.128.0.0/10 -whitelist-ip`加入whitelist-ip无法生效，但是通过`whitelist-ip 36.128.0.0/10`可以生效 在我的理解中这应该是等价的吧 whitelist-ip不支持ip-set，因此无法把一个ip-set加入whitelist-ip
> > smartdns版本： ![图片](https://user-images.githubusercontent.com/46527539/280666795-245e3a1a-1ff0-4b2c-aeae-d8643d85a4c9.png)
> 
> ip-rules 需要43.0.8（20230907）或更高版本

草，希望`openwrt-smartdns`尽快更新，以及希望文档中标明这些比较新的特性需要的最低版本（
以及希望`luci-app-smartdns`尽快支持设置doh目标的ip，不然如果所有dns都是doh，必须设置bootstrap-dns，非常诡异（

**Comment by kaowul** [comment]
这个项目非常优秀，为作者点赞。
当然“文档中能标明这些比较新的特性需要的最低版本/日期）“是一个不错的想法。

ps：刚开始我为了省事下载的预编译文件，反复测试均发现无法成功。后来git clone编译测试成功，才意识到可能是版本更新的新特性。如果文档中能注明一下该新功能的添加的日期就很好啦。

**Comment by PikuZheng** [comment]
>以及希望luci-app-smartdns尽快支持设置doh目标的ip，不然如果所有dns都是doh，必须设置bootstrap-dns，非常诡异（

大部分doh可以直接使用ip代替域名使用，具体取决于服务器端证书配置。以及可以在luci中使用ip，并在额外的服务器参数中指定域名

>但是看起来我配置ip-rules没有报错？这是否构成一个issues

只要配置文件语法合规就不报错

**Comment by pymumu** [comment]
最新代码，对不支持的参数，打印warning日志。

**Comment by Shargye** [comment]
> 这个项目非常优秀，为作者点赞。 当然“文档中能标明这些比较新的特性需要的最低版本/日期）“是一个不错的想法。
> 
> ps：刚开始我为了省事下载的预编译文件，反复测试均发现无法成功。后来git clone编译测试成功，才意识到可能是版本更新的新特性。如果文档中能注明一下该新功能的添加的日期就很好啦。

https://github.com/pymumu/smartdns/issues/1545#issue-1986190562

**Comment by cresky-github** [comment]
其实，
根本用不着 IP集合的。
只需 域名集合就行了。
域名集合解析返回结果，不论是什么一概接受就是了。
