### ISSUE TITLE
server-tls 是否支持 server-tls [1dot1dot1dot1.cloudflare-dns.com]:853 ？

### ISSUE THREAD

**Issue by Zhijie327** [pymumu/smartdns#154]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。
server-tls [1dot1dot1dot1.cloudflare-dns.com]:853
server-tls [dns.google]:853
**设备信息**
1. 设备信息（CPU，厂家）  
Raspberry Pi 3B+
2. 固件信息

**Comment by pymumu** [comment]
可以这样配置，条件是树莓派自己的dns服务要有效，否则会导致smartdns启动失败。

**Comment by Zhijie327** [comment]
了解了
