### ISSUE TITLE
若使用DoH的上游DNS，启动时在成功查询到DoH的上游DNS的IP之前，产生的查询会得到SOA并加入缓存

### ISSUE THREAD

**Issue by LostAttractor** [pymumu/smartdns#1542]
**问题现象**  
SmartDNS在启动时，如果使用上游服务器使用DoH，需要先解析目标服务器的ip，才能建立连接
这就会导致在启动和成功添加上游服务器的这段时间，会有一段真空期，我这边添加了很多上游，国外的上游都是DoH，解析这些服务器的ip得有差不多得有接近5秒
如果在在5秒内产生任何dns查询，因为没有上游，会返回SOA或`0.0.0.0`
如果只是返回SOA倒也没啥问题，但是这个SOA会被缓存下来，导致缓存到期之前一直没法正确解析结果

我这里举个例子，我这边配置了把所有国内ip添加倒了whitelist-ip，然后所有国内DNS使用`-whitelist-ip`，也就是只允许国内DNS服务器返回国内ip地址，一定程度防止污染，国外DNS则不设置任何东西
```
ip-set -name cn -file /etc/smartdns/ip-set/geoip-cn.conf
# Let some DNS servers return only these ips
ip-rules ip-set:cn -whitelist-ip

#国内DNS的例子
server 180.76.76.76  -group cn -whitelist-ip
server 114.114.114.114  -group cn -whitelist-ip
server 1.2.4.8  -group cn -whitelist-ip

#国外DNS的例子
server-https cloudflare-dns.com/dns-query -group worldwide
server-https dns.google/dns-query -group worldwide
server-https dns.quad9.net/dns-query -group worldwide
```

然后在没有缓存的情况下启动smartdns，并在1秒后请求一个域名，如下
```
root@OpenWrt ~# /etc/init.d/smartdns start && sleep 1 && dig lostattractor.net -p 6053

; <<>> DiG 9.18.19 <<>> lostattractor.net -p 6054
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33878
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;lostattractor.net.		IN	A

;; Query time: 69 msec
;; SERVER: 127.0.0.1#6053(127.0.0.1) (UDP)
;; WHEN: Mon Nov 06 18:03:08 UTC 2023
;; MSG SIZE  rcvd: 35
```
因为上面说了给国内DNS设置了仅允许返回国内的ip的白名单，我还设置了UDP的国内上游DNS，所以如果域名返回的是国内ip的话，这些UDP的上游DNS可以正常查询，不会出现问题，所以这边复现需要是返回的是一个非中国ip，比如上面的`lostattractor.net`返回的是一个香港ip，**不清楚如果全部上游DNS都是DoH是否还可以复现这个问题（可能有特别的策略？）**

运行后，这是日志
```
[DEBUG][     dns_server.c:5577] recv query packet from 127.0.0.1, len = 58, type = 0
[DEBUG][            dns.c:1939] opt type 10
[DEBUG][     dns_server.c:5589] request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 58, id = 60866, tc = 0, rd = 1, ra = 0, rcode = 0
[DEBUG][     dns_server.c:5612] query lostattractor.net from 127.0.0.1, qtype: 1, id: 60866
[DEBUG][     dns_client.c:3492] send query to server 1.2.4.8
[DEBUG][     dns_client.c:3492] send query to server 114.114.114.114
[DEBUG][     dns_client.c:3492] send query to server 180.76.76.76
[ INFO][     dns_client.c:3859] request: lostattractor.net, qtype: 1, id: 57728, group: default
[DEBUG][     dns_client.c:2325] recv udp packet from 1.2.4.8, len: 62, ttl: 64, latency: 4
[DEBUG][     dns_client.c:1711] qdcount = 1, ancount = 1, nscount = 0, nrcount = 0, len = 62, id = 57728, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 4096
[DEBUG][     dns_client.c:1723] domain: lostattractor.net qtype: 1  qclass: 1
[DEBUG][     dns_server.c:3626] query result from server 1.2.4.8:53, type: 0
[DEBUG][     dns_server.c:2965] domain: lostattractor.net TTL: 104 IP: 47.243.164.28
[DEBUG][     dns_client.c:2325] recv udp packet from 114.114.114.114, len: 62, ttl: 64, latency: 10
[DEBUG][     dns_client.c:1711] qdcount = 1, ancount = 1, nscount = 0, nrcount = 0, len = 62, id = 57728, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 1232
[DEBUG][     dns_client.c:1723] domain: lostattractor.net qtype: 1  qclass: 1
[DEBUG][     dns_server.c:3626] query result from server 114.114.114.114:53, type: 0
[DEBUG][     dns_server.c:2965] domain: lostattractor.net TTL: 36 IP: 47.243.164.28
[DEBUG][     dns_client.c:2325] recv udp packet from 180.76.76.76, len: 51, ttl: 64, latency: 11
[DEBUG][     dns_client.c:1711] qdcount = 1, ancount = 1, nscount = 0, nrcount = 0, len = 51, id = 57728, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 0
[DEBUG][     dns_client.c:1723] domain: lostattractor.net qtype: 1  qclass: 1
[DEBUG][     dns_server.c:3626] query result from server 180.76.76.76:53, type: 0
[DEBUG][     dns_server.c:2965] domain: lostattractor.net TTL: 255 IP: 47.243.164.28
[DEBUG][     dns_client.c:1495] result: lostattractor.net, qtype: 1, has-result: 1, id 57728
[ INFO][     dns_server.c:2162] result: lostattractor.net, qtype: 1, rtt: -0.1 ms, 0.0.0.0
[DEBUG][     dns_server.c:1916] reply lostattractor.net qtype: 1, rcode: 0, reply: 1
[DEBUG][     dns_server.c:1338] cache lostattractor.net qtype: 1 ttl: 600
[ INFO][     dns_server.c:1971] result: lostattractor.net, client: 127.0.0.1, qtype: 1, id: 60866, group: default, time: 11ms
[DEBUG][     dns_server.c:1916] reply lostattractor.net qtype: 1, rcode: 0, reply: 0
[DEBUG][     dns_server.c:1338] cache lostattractor.net qtype: 1 ttl: 600
```

可以看到三个国内的DNS都返回了正确IP `47.243.164.28` 但是因为不是国内IP被过滤掉了
```
[ INFO][     dns_server.c:2162] result: lostattractor.net, qtype: 1, rtt: -0.1 ms, 0.0.0.0
```
可以看到最终得出的结果是`0.0.0.0`，并加入了缓存，实验发现，如果开了双栈优选，0.0.0.0就会变成SOA，同样加入缓存
```
[ INFO][     dns_server.c:2159] result: lostattractor.net, qtype: 28, SOA
```

但是这似乎不是问题，因为在没有上游时返回0.0.0.0或者SOA是预期中的事情，但加入缓存似乎不是一个合适的选择
SmartDNS在启动时，对于DoH会先`add pending server`，然后对于非DoH会`add server`，然后DoH服务器的地址会通过Bootstrap DNS或直接已经`add server`了的上游DNS来返回，返回后`add server`，如果`add pending server`查询失败，则会retry

* 上述叫法是因为日志里就是这么打印的

我认为可能有两个比较好的解决方案，第一是可以在`add pending server`成功解析上游DNS或失败进入retry阶段之前不进行加入缓存的行为，第二是在这个阶段，我认为或许还不应该对外提供查询服务

其次是，这还诞生了一个连带的问题，在不设置Bootstrap DNS的情况下，假如我们设置一个DoH的DNS，一个只允许返回这个DoH的DNS的IP的UDP的DNS（通过whitelist），和另外一个DoH的DNS
```
# 一个DoH的DNS (8.8.8.8)
server-https dns.google/dns-query

# 一个只允许返回这个DoH DNS的IP的DNS
server 8.8.8.8  -whitelist-ip
ip-rules 223.5.5.5 -whitelist-ip

# 另一个DoH的DNS
server-https cloudflare-dns.com/dns-query
```
这时启动，会先添加`223.5.5.5`这个DNS，pending `dns.google` 和 `cloudflare-dns.com`，都会用UDP的这个DNS解析（`223.5.5.5`），`dns.google`解析出`8.8.8.8`后允许返回，`cloudflare-dns.com`被阻止了返回，并都会加入cache
而现在`cloudflare-dns.com`的pending会retry，预期中的行为是通过刚刚add的`dns.google`解析出结果，成功retry，但是因为cache里的`cloudflare-dns.com`是`0.0.0.0`或SOA，retry不会成功，直到缓存过期

这个连带问题的影响比想象的要广，比如说我刚刚上面的例子，设置了国内的DoH DNS和UDP DNS，并且只信任这些DNS返回的中国IP，而国外DNS的IP是国外IP，于是我要么设置一个Bootstrap DNS，要么我可以给其中的一个DoH的DNS设置成通过IP连接，但是直接设置IP看起来很怪，那我可能会想要通过`-host-ip`来设置，而如果通过这种方法设置，还是会出现一个先pending在add的过程，那这时同时一起查询的没设置`-host-ip`的国外DNS的域名，就会被缓存是`0.0.0.0`或是SOA，并因此无法retry

而通过让全部`add pending server`成功或retry之前产生的查询不加入缓存便可以解决问题
当然，我认为读取持久化缓存的时候也应该忽略这些上游DoH DNS的地址（pending的server）的缓存
或者，`add pending server`产生的查询应该忽略缓存，这样更彻底

**运行环境**
1. 固件型号  
OpenWRT主线，commit hash `f6e35efbfe1d62463035770e7a61e3e830a82159`

3. smartdns来源以及版本
luci-app-smartdns commit hash `d27afad8e67cfee2c73833ded460fb27b27863e1` (1.2023.43)
smartdns `1.2023.42`和最新的`7bfb4e070a018cf38a3c977793eb4150d1b620c9`均可复现

**Comment by pymumu** [comment]
从你的描述看，是预期行为。

47.243.164.28这个IP属于非白名单地址，被过滤了，所以无可用IP地址，返回了空的结果。
其他DOH的域名，也是同样的问题，解析除的地址，因为没有在白名单地址内，被过滤掉了。

解决方案就是添加可信的bootstrap DNS，或者使用-host-ip明确指定IP地址，可以直接使用IP地址形式的DOT或DOH。

**Comment by LostAttractor** [comment]
> 从你的描述看，是预期行为。
> 
> 47.243.164.28这个IP属于非白名单地址，被过滤了，所以无可用IP地址，返回了空的结果。 其他DOH的域名，也是同样的问题，解析除的地址，因为没有在白名单地址内，被过滤掉了。
> 
> 解决方案就是添加可信的bootstrap DNS，或者使用-host-ip明确指定IP地址，可以直接使用IP地址形式的DOT或DOH。

使用`-host-ip`指定地址也不行，因为即使制定了ip，也会经历pending再add，这一瞬间也无dns可用。
`Bootstrap DNS`是一个好办法，但是也没办法解决在创建与DoH的DNS服务器的连接时产生的DNS查询被加入缓存，我认为这一段时间应当特判
在启动过程中尝试解析DoH的DNS服务器的地址这个时间，不应该对外提供查询或至少不加入缓存，我家里跑了一些延迟监控，频率比较高，启动SmartDNS的时候，几乎一定会有一些解析请求，导致SOA/`0.0.0.0`的结果被加入缓存

**Comment by LostAttractor** [comment]
先不考虑过滤的情况，如果全部DNS服务器都是DoH，那启动时如果产生查询也会导致问题，而且必须设置Bootstrap DNS，通过给某个DoH服务器设置`-host-ip`是不可用的，因为这么做也会产生pending，启动的瞬间就产生SOA的缓存了

**Comment by pymumu** [comment]
正常情况下，如果上游查询失败，会返回SERVFAIL的，SERVFAIL是不会进行缓存的。
你这个场景是因为你把所有国外IP都过滤了，按照过滤行为，返回空地址，而不是SERVFAIL，这样就导致了结果被缓存。
这个和DNS pending过程没有关系。

即使缓存了错误结果，那么对应结果TTL超时后，默认10分钟，再次请求结果是可以恢复的。

**Comment by kaowul** [comment]
这个问题和我描述的类似，要还是白名单丢弃的内容被缓存了。导致不会重试超时的其他dns服务器解析。https://github.com/pymumu/smartdns/issues/1552#issuecomment-1809409834
