### ISSUE TITLE
关于测速模式相关的文档过于模糊

### ISSUE THREAD

**Issue by LostAttractor** [pymumu/smartdns#1543]
**需求应用场景**

https://pymumu.github.io/smartdns/config/check-speed-mode/

该页面的文档写的过于云里雾里，完全没有理清 ”测速模式“ 和 ”响应模式“ 的关系，看完这篇文档后，不免有几个问题

1: `response-mode`设置为`first-ping` 时是根据 `speed-check-mode` 决定测速方法的吗？文档说 `first-ping` 返回的是 `DNS上游最快查询时延+ping时延最短`的，但却有个`speed-check-mode`选项，文档中说这是`smartdns速度检测模式`，但是是什么时候的测速，这里的`ping`算测速吗？如果确实`首次请求`就只看`ping`时延，那 `speed-check-mode` 是只对于创建缓存生效？

还是说 `first-ping` 返回的是 `DNS上游最快查询时延+TCP响应时延（测速时延）最短`的？毕竟ICMP包没法被代理，用TCP来测速是非常必要的。
如果是，那文档应该写明是 `DNS上游查询时延+测速返回总耗时最短`，测速模式由`speed-check-mode`决定，不应该出现`ping`字眼（或至少做解释），不然真的看不懂，以及 `first-ping` `fastest-ip` `fastest-response` 的取名实在是让人不知所以...
如果是`first-speedcheck-respone` `fastest-speedcheck` `first-dns-response`，那可读性会好很多

2: 如果`first-ping`是 `DNS上游查询时延+测速返回总耗时最短`，如果 `speed-check-mode` 设置为 `None`，那是不是就是 `DNS上游查询时延最短`，和 `fastest-response` 等价？如果是，感觉需要写明

3 文档中写`smartdns默认使用了优化方案`，我看默认设置就是 `first-ping` + `speed-check-mode` 设置为 `None`，那默认的优化方案就是`fastest-response`？

总之，这篇文档看完完全不能理解 smartdns 的测速行为，希望能够优化一下文档（

**建议的方案**
优化文档，其他还有很多读起来非常困难的内容，也有很多功能重复（如`whitelist-ip`和`ip-rules -whitelist`），这些都需最好要写明

**Comment by pymumu** [comment]
明确一点，一个软件开发出来，不是要各种配置才能工作的。
smartdns默认情况下，就已经是大多数场景下的最佳状态，在没弄清楚参数作用的情况下修改配置选项，可能导致软件效果大打折扣。

你说的重复功能并不是重复，软件本身也不是一天开发完成的，有一些历史配置是需要兼容的，而不是完全放弃原有的兼容性。
address, whitelist-ip等这些独立的配置选项的作用就是快速的完成单个域名、ip规则的设置。对于批量域名、ip，才会用到domain-set或ip-set。

对于测速模式和响应模式是两个不同的概念，一个是对网速测试的模式，也就是icmp ping，tcp-ping:80 tcp-ping:443
一个是结果的回应方式，主要是用来减少第一次查询等待的。

文档是按我的理解方式写的，如果有更好的描述，欢迎提交PR。文档仓库：https://github.com/pymumu/smartdns/tree/doc

**Comment by LostAttractor** [comment]
> 你说的重复功能并不是重复，软件本身也不是一天开发完成的，有一些历史配置是需要兼容的，而不是完全放弃原有的兼容性。
> address, whitelist-ip等这些独立的配置选项的作用就是快速的完成单个域名、ip规则的设置。对于批量域名、ip，才会用到domain-set或ip-set。

非常抱歉，可能我的表达不是特别好
首先，我并没有想表达我们应该立刻移除那些老旧的功能，我自己在做一些发行版的维护，例如在[NixOS社区](nixos.org)，我们的做法是，首先我们会兼容老的配置方法，并且在日志中提醒你可以换到新的写法，并且我们的文档会写明新的写法，写明功能相同或有何不同，并且提醒你切换，例如：
![图片](https://github.com/pymumu/smartdns/assets/46527539/401a7d49-69f9-407c-bd45-caefed3d565d)

其次是`whitelist-ip`，`address`等简写配置，并不是说不应该有这种语法糖，而是如果它是一个语法糖，应当在文档里写明它代表了什么，行为是什么，区别是什么。

> smartdns默认情况下，就已经是大多数场景下的最佳状态，在没弄清楚参数作用的情况下修改配置选项，可能导致软件效果大打折扣。
对，但是问题是，文档的用途就是告诉大家"配置的作用“，如果你看了对应的文档，没办法理解我这么做会带来什么效果，那这个文档就不如直接读代码

> 对于测速模式和响应模式是两个不同的概念，一个是对网速测试的模式，也就是icmp ping，tcp-ping:80 tcp-ping:443

emmmm，tcp-ping???? ,我看了一下，大概就是尝试进行虚假的握手，收到SYN回复后不发ACK，这很好理解，但是把这个称作ping是不是有点奇怪（没别的意思）

> 一个是结果的回应方式，主要是用来减少第一次查询等待的。
嗯？但是回应方式中的三种模式有两种都和测速方式有关吧，如果没办法发icmp，那显然就没办法做到返回最快的ip和返回第一个跑完测速流程的ip
而且文档中也没有出现tcp-ping这种字眼，那也就是说所以first-ping的行为是我说的这样？

> 文档是按我的理解方式写的，如果有更好的描述，欢迎提交PR。文档仓库：https://github.com/pymumu/smartdns/tree/doc

我是非常希望给这个项目提交PR的，因为我很喜欢这个项目，我喜欢这个项目使用C来编写所带来的高性能，但是如果我不理解这个项目是怎么工作的，那我显然没办法给这个项目的文档提交PR
所以smartdns的行为是我描述的这样吗？~~或者还是说我应该自己读代码~~

**Comment by pymumu** [comment]
测速模式，就是字面意思，即配置检测与本网络的链接速度，可配置有icmp ping，tcp测试。
比如查询a.com的A记录为1.2.3.4， 4.5.6.7，那么smartdns会使用配置的模式，检测本网络到1.2.3.4, 4.5.6.7速度。筛选出速度快的IP，丢弃到慢的IP。

那个表格里面测速模式“无”描述错误了，默认的测速模式是ping,tcp:80,tcp443,后续会修改。

响应模式，获取到上游查询结果后，对结果的处理方式。
    first-ping，就是将第一个测速模式获得的结果，返回给客户端。
    fastest-ip，就是将最快的IP地址返回给客户端。
    fastest-response，就是最快的上游结果，这里并没有进行测速。测速会在返回结果给客户端之后。

为方便理解，这里将对应的查询时间分为如下：
smartdns查询上游时间：T1, ...TM，TN， 假设T1为最快的响应时间，TM为一个中位值
smartdns测速时间：P1,...PM,PN，假设P1为最快响应时间，PM为一个中位值。
客户端等待时间为Q

则 
first-ping的等待时间Q1=T1 + PM，
fastest-ip的等待时间Q2=TM + P1,
fastest-response的等待时间Q3=T1,

效果上：客户端查询等待时间Q的顺序为Q3 < Q1 < Q2，结果效果排序Q2 > Q1 > Q3.

**Comment by PikuZheng** [comment]
在我实际使用中，我发现影响测速方法的除了speed-check-mode，还有response-mode、domain-rules，cache等。参数间互相作用与影响也很难用文档来说明。

此外还有一些写死在代码内的参数与算法在影响结果，根据文档配置后结果不符合预期的也有很多讨论如 #1488 #1455 #1028 #999

但就实际使用体验而言，除非配置或搭配（与其他软件协同）上有逻辑问题或冲突，无论选取哪种测速或应答模式，查询结果都大同小异，也不必纠结几毫秒的时间差。

**Comment by lalasou** [comment]
所以  fastest-response模式
才是最佳 无感体验？

**Comment by PikuZheng** [comment]
> 所以  fastest-response模式
> 才是最佳 无感体验？
> 

fastest-response相当于首次查询一个域名时不测速，此时能不能拿到优选IP就要看最快上游是否给力了

**Comment by lalasou** [comment]
> > 所以  fastest-response模式
> > 才是最佳 无感体验？
> > 
> 
> fastest-response相当于首次查询一个域名时不测速，此时能不能拿到优选IP就要看最快上游是否给力了

上游有阿里 dns  应该不会太慢，基本上和单设置阿里dns差不多
那样用户体验起来基本上没有第一次卡顿了，和运营商dns差不多了   后面再访问就是测速之后的了
从体验感来说这是很不错的

**Comment by huangth1992** [comment]
> 测速模式，就是字面意思，即配置检测与本网络的链接速度，可配置有icmp ping，tcp测试。 比如查询a.com的A记录为1.2.3.4， 4.5.6.7，那么smartdns会使用配置的模式，检测本网络到1.2.3.4, 4.5.6.7速度。筛选出速度快的IP，丢弃到慢的IP。
> 
> 那个表格里面测速模式“无”描述错误了，默认的测速模式是ping,tcp:80,tcp443,后续会修改。
> 
> 响应模式，获取到上游查询结果后，对结果的处理方式。 first-ping，就是将第一个测速模式获得的结果，返回给客户端。 fastest-ip，就是将最快的IP地址返回给客户端。 fastest-response，就是最快的上游结果，这里并没有进行测速。测速会在返回结果给客户端之后。
> 
> 为方便理解，这里将对应的查询时间分为如下： smartdns查询上游时间：T1, ...TM，TN， 假设T1为最快的响应时间，TM为一个中位值 smartdns测速时间：P1,...PM,PN，假设P1为最快响应时间，PM为一个中位值。 客户端等待时间为Q
> 
> 则 first-ping的等待时间Q1=T1 + PM， fastest-ip的等待时间Q2=TM + P1, fastest-response的等待时间Q3=T1,
> 
> 效果上：客户端查询等待时间Q的顺序为Q3 < Q1 < Q2，结果效果排序Q2 > Q1 > Q3.

"fastest-ip的等待时间Q2=TM + P1"
从这句话的解释来看，并没有等待所有IP测速完之后再选择？
请问这是有什么特殊策略吗？
另外，没有命中缓存时，首次查询根据response-mode的返回的各种响应结果中，ttl有特意调小吗？
@pymumu
