### ISSUE TITLE
关于通过openwrt配置页面生成的配置文件的问题

### ISSUE THREAD

**Issue by Shargye** [pymumu/smartdns#1544]
[package/openwrt/files/etc/init.d/smartdns](https://github.com/pymumu/smartdns/blob/f1debd08784eca2a4faef1c0cf3f88bba77be531/package/openwrt/files/etc/init.d/smartdns#L317)此文件的第317行，”address“键名前有两个”-“，想问下作者是否是错误？是否对配置文件有影响？

**Comment by PikuZheng** [comment]
根据c++语言的规范，一个-和两个-是一样的。主要是通过空格来拆分不同的参数。

**Comment by Shargye** [comment]
感谢回答我的疑惑，因为我看到其他的都是使用一个“-”表示参数（无论长短名称），唯独这里使用了两个“-”，所以才好奇（强迫症）来问一下。
