### ISSUE TITLE
我看文档里面有相关bind-tls功能，但我该如何测试是否实现

### ISSUE THREAD

**Issue by maojianyou** [pymumu/smartdns#1546]
**问题现象**  
smartdns里面支持tls功能，也就是httpdns功能，但我测试的时候，怎么验证这个功能是正常的
比如访问页面使用httpdns解析一个域名v2.kwaicdn.com
![image](https://github.com/pymumu/smartdns/assets/55315920/6d80c339-8951-468e-92b0-c03a8fba7fc4)

**运行环境**
1. 固件型号  
   xen虚拟机
2. 运营商  
    电信

3. smartdns来源以及版本
smartdns 1.2023.08.11-1937

4. 涉及的配置(注意去除个人相关信息)
bind [::]:53  -no-speed-check -force-aaaa-soa
bind-tls [::]:53
#tcp空闲
tcp-idle-time 120

**重现步骤**
1. 上游DNS配置。  
server 8.8.8.8
server 8.8.4.4
server-https https://dns.google/dns-query
2. 访问的域名。  
v2.kwaicdn.com

**信息收集**  
主要表达的是smartdns支持httpdns怎么实现验证测试，使用这个DNS解析

**Comment by PikuZheng** [comment]
tls dns和https dns是两个不同的东西。
tls dns可以用kdig工具测试。

**Comment by maojianyou** [comment]
> tls dns和https dns是两个不同的东西。 tls dns可以用kdig工具测试。
安装kdig后，可以解析，目前用的比较多的是https dns 使用tls dns有啥意义，感觉用途不太广吧，测试jie结果
![1699593570025](https://github.com/pymumu/smartdns/assets/55315920/bb74ce60-8011-47f8-a817-f197bd630d5a)
所以能否实现支持httpdns解析不

**Comment by PikuZheng** [comment]
http dns和https dns都不支持。另外http dns又不加密，有意义吗

**Comment by maojianyou** [comment]
> http dns和https dns都不支持。另外http dns又不加密，有意义吗

可以防止DNS污染及劫持，httpdns跟httpsdns都有意义，后续增加这方面功能不，国内CDN都有支持httpdns

**Comment by maojianyou** [comment]
> http dns和https dns都不支持。另外http dns又不加密，有意义吗

好像kdig没有windows版本，如果是我电脑还有其他工具可以检测解析dns tls不？

**Comment by PikuZheng** [comment]
windows 可以用 [dnslookup](https://github.com/ameshkov/dnslookup/) 或 [dog](https://github.com/ameshkov/dnslookup/)，但命令行语法上比较复杂

**Comment by pymumu** [comment]
简单增加了DOH

**Comment by maojianyou** [comment]
> windows 可以用 [dnslookup](https://github.com/ameshkov/dnslookup/) 或 [dog](https://github.com/ameshkov/dnslookup/)，但命令行语法上比较复杂

![image](https://github.com/pymumu/smartdns/assets/55315920/add9d19d-69a7-4ae2-86c1-1389e13d358a)
貌似证书受限制，支持httpdns就好了

**Comment by PikuZheng** [comment]
自签证书需要将ca加到本地受信任根证书列表中
