### ISSUE TITLE
小小白有几个问题请教下，谢谢！！

### ISSUE THREAD

**Issue by aaqomo** [pymumu/smartdns#1550]
我的设备是斐讯N1，AdGuardHome接管53端口-->Dnsmasq5337-->SmartDNS6053.翻墙passwall-->SmartDNS第二组5335。

虽然用了SmartDNS差不多两年了，但仍然是小白，最近闲着无事，又在折腾DNS了，现在有几个问题求教一下大佬：

1.是否至少要有一个默认组?我都排除默认组后不能正常解析了，国内国外都一样。???
2.如果全部都不排除默认组，而是设置了按端口访问（本地端口6053为bind :6053 -group gn，第二组为bind :5335 -group gw）是不是到端口6053的数据就只好走gn组？会不会出现使用gn组解析谷歌的情况？
3.第2条的设置是否有必要（本地端口6053，第二DNS服务器5335，是否有必要加bind :6053 -group gn这样的参数？)

谢谢！！！

折腾的主要目的是翻墙的时候防止DNS泄露，虽然现在passwall+SmartDNS可以轻松实现（ipleak.com和dnsleaktest.com网址测试没有国内的服务器），但是我比较极端，想试试能不能全部用加密DNS，全部排除默认组，不知道SmartDNS能不能实现。

**Comment by PikuZheng** [comment]
1. 可以没有默认组，但必须保证你所访问的所有网址都能匹配到特定的组

**Comment by PikuZheng** [comment]
2. 没有匹配到规则的网址会向所有没有从默认组排除的上游发起请求。如果一个上游不能接受未匹配的网址，它应该从默认组中排除。

**Comment by PikuZheng** [comment]
3 bind :6053 -group gn 表示所有经6053口进来的查询都走gn组，此时默认组没有意义

**Comment by aaqomo** [comment]
N1刷个全新固件试验。dnsmasq的53口转发到smartdns的6053，上游设置两个服务器（阿里223.5.5.5和电信202.96.134.133）都从默认组排除，服务组都是gn，自定义设置加了bind :6053 -group gn参数，没开第二服务组，没开passwall，但是所以的网址都无法解析。麻烦问下可能是哪里的问题？

**Comment by pymumu** [comment]
直接smartdns分流请求，https://pymumu.github.io/smartdns/config/forwarding-with-ipset/

**Comment by aaqomo** [comment]
谢谢！！
看了下链接，对于没有专业知识的我来说，理解和设置都比较困难。
其实我只是想知道是不是必须有默认组而已。
