### ISSUE TITLE
为什么smartdns插件开启，会有广告劫持？

### ISSUE THREAD

**Issue by YaoYYw** [pymumu/smartdns#1551]
**问题现象**  
smartdns插件安装在x403和237固件，访问部分xx网站会DNS劫持跳转到其他XX网站，明显有劫持。关闭插件，不会出现类似情况。

**运行环境**
1. 红米AX6000

2. 湖南电信  

3. smartdns来源以及版本  官网不同版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
一般是运营商劫持。是不是使用了udp的上游？

**Comment by YaoYYw** [comment]
为什么pppoe拨号默认的DNS服务没有被劫持？电信拨号获取的DNS服务是什么协议连接？ 用了smartdns插件UDP连接电信默认的DNS服务器都会有广告劫持？？  连接协议有什么区别？ 如果有区别，为什么会被针对成功？如何防范解决？

**Comment by PikuZheng** [comment]
建议查看b站相关科普视频。
为了防止dns劫持，必须使用可信的上游dns服务器并使用加密dns服务作为上游，比如dns over tls，dns over https。

**Comment by YaoYYw** [comment]
湖南电信pppoe拨号可以获取ipv4/6 dns，可以正常上网没有广告劫持。就是看的B站视频，smartdns插件设置ipv4公共dns或者只设置电信默认ipv4 dns服务器，tcp/udp协议，都会被劫持。如何解决？ smartdns填ipv6 dns服务器地址？ 走udp协议还是其他？ 
我这种网络情况应该比较有代表性吧，ISP网络中间人劫持，可能本地网络网管做的小动作，如何避免解决？ 网上的教程大多都是ipv4 公共dns走udp，会出问题，需要大神们帮忙更新解决教程。。   谢谢~

**Comment by PikuZheng** [comment]
为了防止dns劫持，必须使用可信的上游dns服务器并使用加密dns服务作为上游，不能使用udp。

**Comment by YaoYYw** [comment]
现在在电脑上设置同样的DNS服务器，未加密协议。过一两天就知道本地ISP是否有劫持dns的情况。反正PPPOE电信拨号，不用smartdns插件一点问题没有，我再多观察几天
