### ISSUE TITLE
防污染dns，启用白名单过滤后，解析结果逻辑问题求解。

### ISSUE THREAD

**Issue by kaowul** [pymumu/smartdns#1552]
先说说我的配置逻辑：通过国内dns（223.5.5.5）启用白名单，只接受白名单ip（解析结果为国内的IP）。国外dns（8.8.8.8）通过专线连接避免被污染，设置有 gfw域名表 只通过8.8.8.8解析。正常情况下解析结果都OK。
当某个域名 i不在 gfw域名表时，会同时发送给223.5.5.5和8.8.8.8解析，由于223.5.5.5启用了白名单结果会丢弃（解析结果为非白名单内IP），此时如果8.8.8.8出现解析超时/失败。smartdns就会返回DNS_PROBE_FINISHED_NXDOMAIN给客户端。故障就出现了，就算8.8.8.8恢复正常，该域名也仍然会返回DNS_PROBE_FINISHED_NXDOMAIN给客户端，必须重启smartdns才能恢复正常。

下面是我的配置

```
bind-tcp [::]:53 
bind [::]:53 

server 223.5.5.5  -group china -whitelist-ip
server-tls 8.8.8.8 -group gfw-dns

speed-check-mode ping,tcp:443,tcp:80
#speed-check-mode none

cache-size 102400
cache-persist no
cache-file /home/smartdns/dns.cache
cache-checkpoint-time 86400
prefetch-domain yes

serve-expired yes
serve-expired-prefetch-time 21600
serve-expired-ttl 259200
serve-expired-reply-ttl 3

force-qtype-SOA 65
dualstack-ip-selection no
dualstack-ip-selection-threshold 20
dualstack-ip-allow-force-AAAA no
max-reply-ip-num 10
response-mode fastest-response
#response-mode first-ping

#国内IP地址列表，白名单表格
ip-set -name all_china_ip -type list -file /home/smartdns/all_china_ip.conf
ip-rules ip-set:all_china_ip -whitelist-ip

#Gfw_List域名使用gfw-dns解析，禁用测速 -speed-check-mode none -no-cache
domain-set -name gfw_domain -type list -file /home/smartdns/gfw_domain.conf 
domain-rules /domain-set:gfw_domain/ -nameserver gfw-dns  -speed-check-mode none -no-cache
```

我怀疑问题是因为223.5.5.5开启了白名单，由于另外一个dns服务器解析失败，就没有地址返回给客户端。这个结果也存入了缓存。导致就算8.8.8.8恢复了正常解析请求也不会重发。

除了禁用缓存，通过配置有合适的方法解决这个问题？

**Comment by PikuZheng** [comment]
建议增加上游数量

**Comment by kaowul** [comment]
示例配置里我精简了配置，实际上境外dns我配置了多个，但是由于线路波动/部分冷门域名查询超时（plati.io）。就会出现描述中的故障。配置多个上游境外dns故障仍然存在。问题是否可以考虑在缓存逻辑方面解决。

**Comment by PikuZheng** [comment]
> 示例配置里我精简了配置，实际上境外dns我配置了多个，但是由于线路波动/部分冷门域名查询超时（plati.io）。就会出现描述中的故障。配置多个上游境外dns故障仍然存在。问题是否可以考虑在缓存逻辑方面解决。

不会啊 一个查询超时不影响其他上游结果也不会被缓存
所有上游都超时也不应该是NXDOMAIN

**Comment by PikuZheng** [comment]
额 你这个DNS_PROBE_FINISHED_NXDOMAIN 很可能是所有国外上游都超时且结果都不在国内上游的白名单中 故障时还是调查一下网络问题吧

**Comment by kaowul** [comment]
问题主要还是由于白名单丢弃的结果被缓存了。境外dns又超时导致。

**Comment by kaowul** [comment]
https://github.com/pymumu/smartdns/issues/1542 这位朋友描述了类似的情况。白名单丢弃的内容被缓存。未启用白名单的dns又超时。结果就和解析预期出现了差异。

**Comment by pymumu** [comment]
最新代码优化了缓存机制，对失败的结果不在长时间缓存。
