### ISSUE TITLE
版本 1.2023.v43.0.33-1_aarch64_cortex-a53 无法启动

### ISSUE THREAD

**Issue by crackerfly** [pymumu/smartdns#1554]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
OpenWRT官方镜像 23.05.0

2. 运营商  
/

3. smartdns来源以及版本
https://github.com/PikuZheng/smartdns/releases/
1.2023.v43.0.33-OpenWrt-openssl3 版本

[smartdns_1.2023.v43.0.33-1_aarch64_cortex-a53.ipk](https://github.com/PikuZheng/smartdns/releases/download/1.2023.v43.0.33-OpenWrt-openssl3/smartdns_1.2023.v43.0.33-1_aarch64_cortex-a53.ipk)

[luci-app-smartdns.1.2023.v43.0.33.luci-all.ipk](https://github.com/PikuZheng/smartdns/releases/download/1.2023.v43.0.33/luci-app-smartdns.1.2023.v43.0.33.luci-all.ipk)

4. 涉及的配置(注意去除个人相关信息)

https://github.com/pymumu/smartdns/issues/1501

**重现步骤**
从 1.2023.v43.0.18-OpenWrt-openssl3 版本开始使用 openssl3 版本
之前版本直至上一版本 v43.0.32都正常, 更新至v43.0.33版本后无法启动

**信息收集**  
出门太急没来得及复制日志...... 抱歉

**Comment by PikuZheng** [comment]
证实是编译问题。稍等。

**Comment by PikuZheng** [comment]
纠正了，请使用 v43.0.34 编译（luci不必更新）

**Comment by crackerfly** [comment]
> 纠正了，请使用 v43.0.34 编译（luci不必更新）

感谢大佬!!!!
