### ISSUE TITLE
smartdns不支持cname域名解析结果，解析只有A记录IP地址

### ISSUE THREAD

**Issue by maojianyou** [pymumu/smartdns#1556]
**需求应用场景**
请描述需求应用的场景和方式。
smartdns不支持cname域名解析结果，解析只有A记录IP地址，但bind是支持的，这个功能能否实现
![image](https://github.com/pymumu/smartdns/assets/55315920/4fe8e310-4db0-4180-8011-29b6c01546f6)

**Comment by PikuZheng** [comment]
```
C:\Users\Admin>nslookup www.baidu.com
服务器:  UnKnown
Address:  11.20.3.171

非权威应答:
名称:    www.a.shifen.com
Addresses:  2408:871a:2100:3:0:ff:b025:348d
          2408:871a:2100:2:0:ff:b09f:237
          110.242.68.4
          110.242.68.3
Aliases:  www.baidu.com
```
支持。

**Comment by PikuZheng** [comment]
```
C:\Users\Admin>nslookup -qt=cname www.baidu.com
服务器:  UnKnown
Address:  11.20.3.171

非权威应答:
www.baidu.com   canonical name = www.a.shifen.com
```

也支持cname类型的查询

**Comment by maojianyou** [comment]
> ```
> C:\Users\Admin>nslookup www.baidu.com
> 服务器:  UnKnown
> Address:  11.20.3.171
> 
> 非权威应答:
> 名称:    www.a.shifen.com
> Addresses:  2408:871a:2100:3:0:ff:b025:348d
>           2408:871a:2100:2:0:ff:b09f:237
>           110.242.68.4
>           110.242.68.3
> Aliases:  www.baidu.com
> ```
> 
> 支持。

![image](https://github.com/pymumu/smartdns/assets/55315920/2812650d-3178-4295-8928-8bcab5f665ec)
为啥我这个不支持，是不是要开启那个功能，或者关闭了那个功能
![image](https://github.com/pymumu/smartdns/assets/55315920/b42aae10-4c1c-4cd3-b996-eda22a7378a0)
配置哪里要jia加吗？很奇葩我的这个没有cname记录

**Comment by maojianyou** [comment]
> ```
> C:\Users\Admin>nslookup www.baidu.com
> 服务器:  UnKnown
> Address:  11.20.3.171
> 
> 非权威应答:
> 名称:    www.a.shifen.com
> Addresses:  2408:871a:2100:3:0:ff:b025:348d
>           2408:871a:2100:2:0:ff:b09f:237
>           110.242.68.4
>           110.242.68.3
> Aliases:  www.baidu.com
> ```
> 
> 支持。

看了配置支持，我关闭了force-no-CNAME yes，刚改成no可以了，但有个问题，好像日志没有显示cname域名
日志配置
#审计日志输出
audit-enable yes
audit-SOA yes
audit-num 6
audit-file /var/log/smartdns/smartdns-audit.log
audit-size 3G
![image](https://github.com/pymumu/smartdns/assets/55315920/69229746-fa53-4c92-a6d8-9dffec5bb44b)

**Comment by maojianyou** [comment]
> ![image](https://user-images.githubusercontent.com/56712217/283141141-21dc760a-90d8-460c-9b4b-9cfc75ae8be8.png
看了配置加了force-no-CNAME yes 这个原因，改成no可以了，但貌似日志没打印cname记录

**Comment by PikuZheng** [comment]
> > ```
> > C:\Users\Admin>nslookup www.baidu.com
> > 服务器:  UnKnown
> > Address:  11.20.3.171
> > 
> > 非权威应答:
> > 名称:    www.a.shifen.com
> > Addresses:  2408:871a:2100:3:0:ff:b025:348d
> >           2408:871a:2100:2:0:ff:b09f:237
> >           110.242.68.4
> >           110.242.68.3
> > Aliases:  www.baidu.com
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 支持。
> 
> 看了配置支持，我关闭了force-no-CNAME yes，刚改成no可以了，但有个问题，好像日志没有显示cname域名 日志配置 #审计日志输出 audit-enable yes audit-SOA yes audit-num 6 audit-file /var/log/smartdns/smartdns-audit.log audit-size 3G ![image](https://user-images.githubusercontent.com/55315920/283368875-69229746-fa53-4c92-a6d8-9dffec5bb44b.png)

查询类型是1，也就是A记录。cname查询类型是5

**Comment by maojianyou** [comment]
> > > ```
> > > C:\Users\Admin>nslookup www.baidu.com
> > > 服务器:  UnKnown
> > > Address:  11.20.3.171
> > > 
> > > 非权威应答:
> > > 名称:    www.a.shifen.com
> > > Addresses:  2408:871a:2100:3:0:ff:b025:348d
> > >           2408:871a:2100:2:0:ff:b09f:237
> > >           110.242.68.4
> > >           110.242.68.3
> > > Aliases:  www.baidu.com
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 支持。
> > 
> > 
> > 看了配置支持，我关闭了force-no-CNAME yes，刚改成no可以了，但有个问题，好像日志没有显示cname域名 日志配置 #审计日志输出 audit-enable yes audit-SOA yes audit-num 6 audit-file /var/log/smartdns/smartdns-audit.log audit-size 3G ![image](https://user-images.githubusercontent.com/55315920/283368875-69229746-fa53-4c92-a6d8-9dffec5bb44b.png)
> 
> 查询类型是1，也就是A记录。cname查询类型是5

我的意思是日志没有cname日志，比如我解析www.baidu.com正常日志应该打印www.a.shifen.com. 然后加IP地址
![image](https://github.com/pymumu/smartdns/assets/55315920/aa5573b5-15e4-4fe9-b6b5-500029f308ae)
类似这样的日志，显示A记录的保护cname记录

**Comment by PikuZheng** [comment]
emmmmm明白了但我主张不加，审计日志里多了一项处理起来太麻烦。
但是试了查询类型是5（cname），审计日志里也没有记录查询结果

**Comment by maojianyou** [comment]
> 

是啊，正常应该把全部解析结果，包含一级cname，二级cname都加入日志，这样就可以确定是从那个CDN节点获取的资源，还有一个问题，这个貌似没有针对源用户IP分组策略

**Comment by PikuZheng** [comment]
> 还有一个问题，这个貌似没有针对源用户IP分组策略

没有这个功能，置顶中建议增加的功能有这一项
但是很多环境下smartdns都是被一级转发过来的。拿不到来源ip。

目前为止，如果是多网段，可以通过绑定不同的网口监听来实现不同的上游查询组；也可使用iptables之类的通过来源地址将dns查询转发到不同的监听端口

**Comment by maojianyou** [comment]
> > 还有一个问题，这个貌似没有针对源用户IP分组策略
> 
> 没有这个功能，置顶中建议增加的功能有这一项 但是很多环境下smartdns都是被一级转发过来的。拿不到来源ip。
> 
> 目前为止，如果是多网段，可以通过绑定不同的网口监听来实现不同的上游查询组；也可使用iptables之类的通过来源地址将dns查询转发到不同的监听端口

主要是分组用户侧的源IP增加视图，比如私网10.10.10.10这个用户，走上游策略走质量好的上游dns，另外一部分走上游质量不好的调度策略

**Comment by maojianyou** [comment]
> emmmmm明白了但我主张不加，审计日志里多了一项处理起来太麻烦。 但是试了查询类型是5（cname），审计日志里也没有记录查询结果

这个日志功能可以新增cname也记录到日志里面不，我看bind都有详细的日志，可以记录当时命中那个cdn域名资源，好通过日志收集cdn域名
