### ISSUE TITLE
关于多个上游server的问题

### ISSUE THREAD

**Issue by happy42779** [pymumu/smartdns#1559]
大佬们好，

想请问下，关闭测速后，当有多个上游服务器可以使用的时候，默认的行为是什么？ 
1. 仍然同时向全部发送请求？
2. 按配置顺序请求进行请求，失败后换下一个？

我在想smartdns能否做到类似failover的功能。 
目前我的域名使用的是cndomain 用 domestic，然后其他默认overseas。但有时网络不稳定，overseas失连了后得手动先把默认dns改回来。 

感谢！

**Comment by PikuZheng** [comment]
取决于response-mode设置。
仍会向所有上游发出请求。
不同上游应答的不同结果，是否合并取决于cache-size

**Comment by happy42779** [comment]
> 取决于response-mode设置。 仍会向所有上游发出请求。 不同上游应答的不同结果，是否合并取决于cache-size

那可请问可否有计划添加这个功能，当有多个上游存在时，可以按他们的配置顺序设置优先级，后面的座位前面的failover？

**Comment by PikuZheng** [comment]
有建议。但目前是并发查询（failover拖慢速度啊

**Comment by happy42779** [comment]
> 有建议。但目前是并发查询（failover拖慢速度啊

是的，如果默认是这种行为的话，某些情况下却是会拖慢速度。但如果可以给选项来配置到底是用并发还是选择顺序优先级的话，那就太好了。可用性就更高一些了。
