### ISSUE TITLE
openwrt x64无法运行

### ISSUE THREAD

**Issue by qqwas** [pymumu/smartdns#156]
**问题现象**  
简要描述问题出现的现象
程序无法运行
daemon.info procd: Instance smartdns::smartdns s in a crash loop 7 crashes, 0 seconds since last crash
直接运行smartdns
Error loading shared library libssl.so.1.0.0: No such file or directory (needed by ./smartdns)
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by ./smartdns)
Error relocating ./smartdns: X509_NAME_get_text_by_NID: symbol not found
Error relocating ./smartdns: SSL_get_error: symbol not found
Error relocating ./smartdns: CRYPTO_free: symbol not found
Error relocating ./smartdns: SSL_write: symbol not found
Error relocating ./smartdns: SSLv23_client_method: symbol not found
Error relocating ./smartdns: CRYPTO_malloc: symbol not found
Error relocating ./smartdns: SSL_free: symbol not found
Error relocating ./smartdns: EVP_DecodeBlock: symbol not found
Error relocating ./smartdns: SSL_set_fd: symbol not found
Error relocating ./smartdns: CRYPTO_num_locks: symbol not found
Error relocating ./smartdns: X509_get_subject_name: symbol not found
Error relocating ./smartdns: ERR_reason_error_string: symbol not found
Error relocating ./smartdns: SHA256_Init: symbol not found
Error relocating ./smartdns: OPENSSL_cleanse: symbol not found
Error relocating ./smartdns: SSL_library_init: symbol not found
Error relocating ./smartdns: SSL_get1_session: symbol not found
Error relocating ./smartdns: SSL_read: symbol not found
Error relocating ./smartdns: SSL_SESSION_free: symbol not found
Error relocating ./smartdns: SSL_new: symbol not found
Error relocating ./smartdns: OPENSSL_add_all_algorithms_noconf: symbol not found
Error relocating ./smartdns: SSL_shutdown: symbol not found
Error relocating ./smartdns: EVP_cleanup: symbol not found
Error relocating ./smartdns: ERR_free_strings: symbol not found
Error relocating ./smartdns: SSL_CTX_new: symbol not found
Error relocating ./smartdns: SSL_get_peer_certificate: symbol not found
Error relocating ./smartdns: SSL_ctrl: symbol not found
Error relocating ./smartdns: i2d_X509_PUBKEY: symbol not found
Error relocating ./smartdns: SHA256_Final: symbol not found
Error relocating ./smartdns: CRYPTO_set_id_callback: symbol not found
Error relocating ./smartdns: X509_free: symbol not found
Error relocating ./smartdns: SSL_connect: symbol not found
Error relocating ./smartdns: SSL_CTX_free: symbol not found
Error relocating ./smartdns: SSL_load_error_strings: symbol not found
Error relocating ./smartdns: SSL_set_session: symbol not found
Error relocating ./smartdns: SHA256_Update: symbol not found
Error relocating ./smartdns: ERR_get_error: symbol not found
Error relocating ./smartdns: CRYPTO_set_locking_callback: symbol not found

**运行环境**
1. 固件型号  
OpenWrt SNAPSHOT r9945-bc85640
路由器libopenssl版本为libopenssl1.1 - 1.1.1b-5

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
请参考说明
```
注意：如使用Koolshare Lede 2.3.0及之后版本，请安装openssl1.0.0系统库，安装文件从下面页面中获取：
https://downloads.openwrt.org/releases/18.06.2/packages/x86_64/base/
找到libopenssl_1.0.2XXXX_x86_64.ipk并安装下载，XXXX为版本号。
```

**Comment by pymumu** [comment]
尝试Release 26静态编译版本把。
