### ISSUE TITLE
问一下大佬，现在最新源码已经支持DOT,DOH服务器了，是不是说现在就不用设置Bootstrap DNS了？

### ISSUE THREAD

**Issue by zmjjack** [pymumu/smartdns#1561]
问一下大佬，现在最新源码已经支持DOT,DOH服务器了，是不是说现在就不用设置Bootstrap DNS了？

**Comment by PikuZheng** [comment]
最新代码支持的是smartdns作为doh服务器，其他终端可以使用doh协议向smartdns发起查询。

bootstrap是smartdns向上游dns服务器发起查询时用的，此时smartdns是dns客户端。

对于smartdns来说，一个是server配置，一个是client配置，没什么相关性。

总之，这个问题前提条件不成立，不存在一个“是/否”的答案

**Comment by zmjjack** [comment]
ok，了解。
