### ISSUE TITLE
openwrt固件使用最近源码编译后的smartdns无法启动

### ISSUE THREAD

**Issue by wtfr-dot** [pymumu/smartdns#1563]
**问题现象**  
简要描述问题出现的现象
更新最近源码编译后发现smartdns无法启动，系统log里出现提示：
Tue Nov 21 16:25:02 2023 local1.err smartdns: domain set file /etc/smartdns/domain-forwarding.list not readable. No such file or directory 
Tue Nov 21 16:25:02 2023 local1.warn smartdns: process config failed at '/var/etc/smartdns/smartdns.conf:33'.

Tue Nov 21 16:25:08 2023 local1.err smartdns: domain set file /etc/smartdns/domain-forwarding.list not readable. No such file or directory 
Tue Nov 21 16:25:08 2023 local1.warn smartdns: process config failed at '/var/etc/smartdns/smartdns.conf:33'.

Tue Nov 21 16:25:13 2023 local1.err smartdns: domain set file /etc/smartdns/domain-forwarding.list not readable. No such file or directory 
Tue Nov 21 16:25:13 2023 local1.warn smartdns: process config failed at '/var/etc/smartdns/smartdns.conf:33'.

Tue Nov 21 16:25:18 2023 local1.err smartdns: domain set file /etc/smartdns/domain-forwarding.list not readable. No such file or directory 
Tue Nov 21 16:25:18 2023 local1.warn smartdns: process config failed at '/var/etc/smartdns/smartdns.conf:33'.

Tue Nov 21 16:25:24 2023 local1.err smartdns: domain set file /etc/smartdns/domain-forwarding.list not readable. No such file or directory 
Tue Nov 21 16:25:24 2023 local1.warn smartdns: process config failed at '/var/etc/smartdns/smartdns.conf:33'.

Tue Nov 21 16:25:29 2023 local1.err smartdns: domain set file /etc/smartdns/domain-forwarding.list not readable. No such file or directory 
Tue Nov 21 16:25:29 2023 local1.warn smartdns: process config failed at '/var/etc/smartdns/smartdns.conf:33'.
Tue Nov 21 16:25:29 2023 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash

Tue Nov 21 16:25:33 2023 daemon.info procd: Instance sing-box::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

错误提示里面的第33行配置是：domain-set -name domain-forwarding-list -file /etc/smartdns/domain-forwarding.list
domain-forwarding.list这个文件我一直没有，之前的版本没有这个错误提示，也能正常运行，现在更新的源码是强制要读取这个文件才行吗？

**运行环境**
1. 固件型号  
openwrt22.03
2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
https://github.com/pymumu/smartdns/pull/1555 修正了这个问题。证实你用的是最新代码？

**Comment by wtfr-dot** [comment]
> #1555 修正了这个问题。证实你用的是最新代码？

今天下午编译的最新代码，前两天编译的都有这个问题，而且都是这个comment之后的

**Comment by wtfr-dot** [comment]
> #1555 修正了这个问题。证实你用的是最新代码？

你这个是解决使用openwrt sdk编译环境的问题吗，我是Ubuntu22.04里编译的openwrt

**Comment by PikuZheng** [comment]
> 今天下午编译的最新代码，前两天编译的都有这个问题，而且都是这个comment之后的

https://github.com/pymumu/smartdns/commit/d54d7cf80a3c5a3ad87222656d0d4b83772d6b94 这个提交强制了当文件不存在时停止运行。但是这个list文件，只有openwrt在默认情况下会引用（由luci生成的配置文件引用）。 #1555把这两个list文件加到打包列表了，所以即使以前没有这个文件，安装新版时也会增加一份空文件使得运行时不会报错。
如果你只是更新运行文件而不是整个ipk，是的，会有不运行的问题。

**Comment by PikuZheng** [comment]
创建文件是在ipk中配置，由opkg实施的，具体取决于你的安装方法（而不是编译方法）

**Comment by wtfr-dot** [comment]
> 创建文件是在ipk中配置，由opkg实施的，具体取决于你的安装方法（而不是编译方法）

我是直接编译进固件的，打包安装是系统的动作，刚刚用最新源码编译固件已经正常工作了
