### ISSUE TITLE
请问配置方式的问题。

### ISSUE THREAD

**Issue by aaqomo** [pymumu/smartdns#1565]
请问：

是否所有的配置都可以在“自定义设置”里，以命令行参数的形式配置？

想实现的目的是，配置好以后重刷固件直接拷贝过去就行。

谢谢！！

**Comment by PikuZheng** [comment]
可以。

**Comment by aaqomo** [comment]
能不能推荐个基础的设置？拷贝过去直接就能用的。

**Comment by CallMeR** [comment]
> 能不能推荐个基础的设置？拷贝过去直接就能用的。

需求不明确，自然没有直接就能用的配置，smartdns 文档里有写，基本上只需要加上上游 dns 服务器就能用了。

当然，这也是最基本的用法。

**Comment by aaqomo** [comment]
就最基本的，
比如我在“自定义设置”里输入了
bind [::]:6053
那么在“基础设置”里、
还用不用勾选“启用”？

**Comment by PikuZheng** [comment]
> 就最基本的，
> 比如我在“自定义设置”里输入了
> bind [::]:6053
> 那么在“基础设置”里、
> 还用不用勾选“启用”？

需要勾选“启用”但不需要填写“绑定端口”

**Comment by aaqomo** [comment]
> > 就最基本的，
> > 比如我在“自定义设置”里输入了
> > bind [::]:6053
> > 那么在“基础设置”里、
> > 还用不用勾选“启用”？
> 
> 需要勾选“启用”但不需要填写“绑定端口”

感谢回复！！！
就是说除了”启用“要勾选，其他都可以在”自定义设置“里设置。
谢谢。
