### ISSUE TITLE
nslookup -querytype=ptr smartdns运行后服务器显示二级路由的名字而不是smartdns

### ISSUE THREAD

**Issue by 58285474** [pymumu/smartdns#1566]
**问题现象**  
nslookup -querytype=ptr smartdns运行后服务器显示子路由的名字而不是smartdns
![image](https://github.com/pymumu/smartdns/assets/28937186/d3b992f4-e493-42ec-960e-bd4b5946e5c7)
如果断开二级路由就一切正常
![image](https://github.com/pymumu/smartdns/assets/28937186/82f2c90e-9687-4d65-bd9a-280580cb720a)

两台设备都是openwrt同一个固件 smartdns装在一级路由也就是主路由上
**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
预期行为。
windows在dns查询时默认会附加dns后缀，在二级路由下查询 nslookup -qt=ptr smartdns 时，实际是在查询 smartdns.lan.。若二级路由下没有以smartdns.lan命名的主机，则返回nxdomain。

**Comment by 58285474** [comment]
> 预期行为。
> 
> windows在dns查询时默认会附加dns后缀，在二级路由下查询 nslookup -qt=ptr smartdns 时，实际是在查询 smartdns.lan.。若二级路由下没有以smartdns.lan命名的主机，则返回nxdomain。

nslookup -qt=ptr smartdns我这是在主路由下查询的，二级路由下没有设备只是用来运行docker用，如何避免呢？

**Comment by PikuZheng** [comment]
> nslookup -qt=ptr smartdns我这是在主路由下查询的

那我上面说的不对。

**Comment by PikuZheng** [comment]
也就是说，当你开了192.168.0.50这台路由器时，windows进行dns查询，走这个ip是50的openwrt了。关掉这个50后，dns查询走主路由（正常）。是这样吗？

**Comment by 58285474** [comment]
> 也就是说，当你开了192.168.0.50这台路由器时，windows进行dns查询，走这个ip是50的openwrt了。关掉这个50后，dns查询走主路由（正常）。是这样吗？

对的，再详细说下，主路由192.168.5.1二级路由192.168.5.50，开了二级路由就是50的，关了就是一级的，但是出国一切都正常，我猜测是不是二级路由也是53端口的原因，因为我smartdns端口是53

**Comment by PikuZheng** [comment]
你的电脑从二级路由获取了一个ipv6地址和一个ipv6 dns地址。由于Windows的ipv6优先策略，它走ipv6 dns了，没用主路由的那个。
这可以解释所有症状，但只是我的猜测。

**Comment by rampageX** [comment]
Windows 下面要加 .

`nslookup -querytype=ptr smartdns.`
