### ISSUE TITLE
luci界面log文件打不开，提示无权限

### ISSUE THREAD

**Issue by wtfr-dot** [pymumu/smartdns#1567]
**问题现象**  
简要描述问题出现的现象
luci界面增加了查看log日志的功能，但是点查看时提示没有权限。
![image](https://github.com/pymumu/smartdns/assets/81218740/95ba0061-3465-4aeb-9173-b637ecf1b9a8)

**运行环境**
1. 固件型号  
openwrt22.03
2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by lizhiwei8061** [comment]
我的也是

**Comment by zxlhhyccc** [comment]
查看一下“smartdns-call”这个文件权限是否为0755，请把权限改为0755试试！
路径：/usr/libexec/

**Comment by lizhiwei8061** [comment]
> 查看一下“smartdns-call”这个文件的执行权限是否为0755，请把权限改为0755试试！ 路径：/usr/libexec/

这可以解决问题
