### ISSUE TITLE
请问一下我这个是生效了么

### ISSUE THREAD

**Issue by lizhiwei8061** [pymumu/smartdns#1568]
**问题现象**  
都说生效nslookup 只返回一个ip，我这是为啥这样，问一下
![Snipaste_2023-11-26_12-19-18](https://github.com/pymumu/smartdns/assets/121220591/793372a7-0565-4f40-9fe5-384a112011c5)

**运行环境**
1. 固件型号  
x86
2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
只有一个是过去式了，返回多个是正确的。
请把你的smartdns bind从0.0.0.0改成 ::0

**Comment by lizhiwei8061** [comment]
> 只有一个是过去式了，返回多个是正确的。 请把你的smartdns bind从0.0.0.0改成 ::0

感谢 我的bind现在是[::]
