### ISSUE TITLE
更改配置后失效

### ISSUE THREAD

**Issue by nameless3721** [pymumu/smartdns#157]
简要描述问题出现的现象
更换重定向或禁用再启用的等操作会失效
**运行环境**
1. 固件型号  
OpenWrt R9.5.1 By Lean / LuCI Master 18.06
 
要去启动项重启smartdns 才会恢复工作
smartdns还没恢复正常的时候查询dns都会这样
nslookup baidu.com
服务器:  UnKnown
Address:  10.0.0.1

DNS request timed out.
    timeout was 2 seconds.
*** UnKnown 找不到 baidu.com: No response from server

**Comment by pymumu** [comment]
更新Release25测试看看

**Comment by nameless3721** [comment]
可能和固件油管用潘多拉的就没这个问题  用lean自己编译的就还是这样 切换配置一瞬间正常查询到多试几次就还是DNS request timed out.
timeout was 2 seconds.
*** UnKnown 找不到 baidu.com: No response from server

**Comment by pymumu** [comment]
可能有DNS冲突了，建议是将smartdns配置为其他主DNS的上游。
