### ISSUE TITLE
DNS支持反向解析吗，比如我解析一个IP地址，可以得出域名不

### ISSUE THREAD

**Issue by maojianyou** [pymumu/smartdns#1572]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by PikuZheng** [comment]
1. 缓存里有，可以
2. address定义的域名对应ip，可以ptr反查
3. 不符合上面两项的，透传给上游查询，是否有结果取决于上游

**Comment by maojianyou** [comment]
> 1. 缓存里有，可以
> 2. address定义的域名对应ip，可以ptr反查
> 3. 不符合上面两项的，透传给上游查询，是否有结果取决于上游

![image](https://github.com/pymumu/smartdns/assets/55315920/f405a845-0b5f-484b-b1f8-67f95c24df69)

![image](https://github.com/pymumu/smartdns/assets/55315920/31a872cf-4bba-4ad3-90ba-6deb2a5bbd33)

指定了不行

**Comment by PikuZheng** [comment]
![image](https://github.com/pymumu/smartdns/assets/12579522/670b40fa-799d-4b00-a96b-28f55a895ef0)
也不是完全不行。。。这里有点bug

**Comment by PikuZheng** [comment]
好像是先从缓存里取了，如果缓存里错误的过期了，address指定的才生效

**Comment by pymumu** [comment]
https://pymumu.github.io/smartdns/config/domain-address/

最后的那一小节

**Comment by PikuZheng** [comment]
> https://pymumu.github.io/smartdns/config/domain-address/
> 
> 最后的那一小节

是这样的，但是对于持久缓存中已有的记录，好像没有覆盖掉
