### ISSUE TITLE
需要根据gfwlist中的域名生成双栈ipset，但是smartdns只支持生成单栈ipset，且不支持运行两个smartdns实例，没有办法有效分流。

### ISSUE THREAD

**Issue by GlockerYoung** [pymumu/smartdns#1574]
**需求应用场景**
因为xbox大量需要直连国外IP，走代理反而慢，且需要ipv4/6双栈，需要根据gfwlist中的域名生成双栈ipset，但是smartdns只支持生成单栈ipset，且不支持运行两个smartdns实例，没有办法有效分流。

**建议的方案**
我在openwrt23.05上成功实现了多拨的双栈，就差代理分流的双栈了，拥抱IPV6了。

**设备信息**
1. 设备信息（CPU，厂家）  
newwifi-d2
2. 固件信息
openwrt d-team 23.05

**Comment by GlockerYoung** [comment]
该学习下nftables了。

**Comment by GlockerYoung** [comment]
一个ipset只是能是ipv6或者是ipv4，我用nftset搞好了。

**Comment by GlockerYoung** [comment]
/usr/bin/v2ray/v2ray_nft_tproxy.sh
`#!/bin/sh
ip rule add fwmark 0x1 table 0x104 
ip route add local 0.0.0.0/0 dev lo table 0x104
ip -6 rule add fwmark 0x106 table 0x106 
ip -6 route add local ::/0 dev lo table 0x106

nft -f /usr/bin/v2ray/v2ray_nft_tproxy.conf
`

/usr/bin/v2ray/v2ray_nft_tproxy.conf
`table ip v2ray { 
	set gfwlist { 
		type ipv4_addr; flags interval; 
	} 

	chain PREROUTING {
		type filter hook prerouting priority filter; policy accept;
		meta mark 0x000000ff return
		meta l4proto { tcp, udp } ip daddr @gfwlist meta mark set 0x00000001 tproxy to :10807 accept
	}

	chain OUTPUT {
		type route hook output priority filter; policy accept;
		meta mark 0x000000ff return
		meta l4proto { tcp, udp } ip daddr @gfwlist meta mark set 0x00000001 accept
	}	
}

table ip6 v2ray { 
	set gfwlist { 
		type ipv6_addr; flags interval; 
	} 

	chain PREROUTING {
		type filter hook prerouting priority filter; policy accept;
		meta mark 0x000000ff return
		meta l4proto { tcp, udp } ip6 daddr @gfwlist meta mark set 0x00000106 tproxy to :10807 accept
	}

	chain OUTPUT {
		type route hook output priority filter; policy accept;
		meta mark 0x000000ff return
		meta l4proto { tcp, udp } ip6 daddr @gfwlist meta mark set 0x00000106 accept
	}		
}
`

在domain-set中nftset的选项中填:
`#4:ip#v2ray#gfwlist,#6:ip6#v2ray#gfwlist`

**Comment by GlockerYoung** [comment]
不知为何我用从iptables中移来的
```
iifname "br-lan" meta skuid != 65534
```
反面不能正常转发，有高手给看看吗？


```
table ip v2ray { 
	set gfwlist { 
		type ipv4_addr; flags interval; 
	} 

	chain PREROUTING {
		type filter hook prerouting priority filter; policy accept;
		meta mark 0x000000ff return
		iifname "br-lan" meta skuid != 65534 meta l4proto { tcp, udp } ip daddr @gfwlist meta mark set 0x00000104 tproxy to :10807 accept
	}

	chain OUTPUT {
		type route hook output priority filter; policy accept;
		meta mark 0x000000ff return
		iifname "br-lan" meta skuid != 65534 meta l4proto { tcp, udp } ip daddr @gfwlist meta mark set 0x00000104 accept
	}	
}

table ip6 v2ray { 
	set gfwlist { 
		type ipv6_addr; flags interval; 
	} 

	chain PREROUTING {
		type filter hook prerouting priority filter; policy accept;
		meta mark 0x000000ff return
		iifname "br-lan" meta skuid != 65534 meta l4proto { tcp, udp } ip6 daddr @gfwlist meta mark set 0x00000106 tproxy to :10807 accept
	}

	chain OUTPUT {
		type route hook output priority filter; policy accept;
		meta mark 0x000000ff return
		iifname "br-lan" meta skuid != 65534 meta l4proto { tcp, udp } ip6 daddr @gfwlist meta mark set 0x00000106 accept
	}		
}

```

**Comment by GlockerYoung** [comment]
为避免回环，我在v2ray的配置文件中的outbound部分中的streamSettings
加上了
```
"streamSettings": {
	"sockopt": {
	  "mark": 255
	}
}
```

**Comment by pymumu** [comment]
ipset支持ipv4，ipv6同时设置

```
ipset /a.com/#4:ipsetv4,#6:ipsetv6
```

如果ipset集合同时设置了支持ipv4和ipv6。那ipset参数后面写一个名称，smartdns会分开设置。

https://pymumu.github.io/smartdns/configuration/

**Comment by GlockerYoung** [comment]
多谢。
