### ISSUE TITLE
需求功能： proxy-dnssec、dns over quic (openssl 3.2.0)

### ISSUE THREAD

**Issue by Potterli20** [pymumu/smartdns#1579]
https://github.com/pymumu/smartdns/issues/1236#issuecomment-1838135552

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/issues/1570

**Comment by pymumu** [comment]
没有计划支持dns-sec，dns-sec并不能避免污染和隐私泄漏。

**Comment by pymumu** [comment]
关闭测速和cache，可能就能达到你想要的。

**Comment by pymumu** [comment]
最新代码，关闭测速后会启用proxy dnssec

**Comment by pymumu** [comment]
![image](https://github.com/pymumu/smartdns/assets/3275997/735d93a7-f459-4ea4-b8ca-6664d398e7c4)

验证了，没有问题。

```
speed-check-mode none
```

缓存是开启的。
