### ISSUE TITLE
smartdns不解析域名

### ISSUE THREAD

**Issue by kiligone** [pymumu/smartdns#1580]
**问题现象**  
用smartdns解析不了msedgeextensions.sf.tlu.dl.delivery.mp.microsoft.com这个域名，别的都没问题，就是不解析这个域名
返回*** Can't find msedgeextensions.sf.tlu.dl.delivery.mp.microsoft.com: No answer
用dig命令指定用阿里的dns还是Google的dns都能解析出来，指定本地的smartdns就解析不出来。
我现在不知道是我的配置问题，还是smartdns的问题了。

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by lalasou** [comment]
我这边正常
![image](https://github.com/pymumu/smartdns/assets/7440313/16c6130b-27dd-4751-9317-2c4e916aae61)

**Comment by PikuZheng** [comment]
可能结果被黑名单，也可能用了国外dns且开了双栈ip优选，也可能你的上游不好（将ipv6查询应答为soa）且使用了旧版smartdns。
另外楼上两位正常的，为啥我这有ipv6结果

**Comment by pymumu** [comment]
看看是不是域名被配置广告屏蔽了

**Comment by kiligone** [comment]
问题解决了，是我的配置的问题，有一条忽略这个域名返回结果的配置
