### ISSUE TITLE
新增的DNS记录SOA响应被缓存，导致其TTL远超预期

### ISSUE THREAD

**Issue by Mosney** [pymumu/smartdns#1581]
**问题现象**  

自己托管在cloudflare的域新增一个记录，

1. 立刻查询，此时记作T+00:00:00，返回SOA，TTL=252
2. T+00:02:00 cloudflare与google的dns均已经能查询到A记录，此时返回SOA的上游大部分TTL<600，偶有几个上游TTL<1200
3. 到T+00:27:00期间不时查询，smartdns一直返回SOA，此时手动查询大部分上游已经可以返回正确的A记录，遂将smartdns的log等级切换为debug，观察到smartdns没有请求上游一直在使用缓存的SOA结果做响应
4. T+00:46:00 smartdns终于首次返回了正确的结果，日志中可以看到本次查询请求了上游 `[DEBUG][     dns_client.c:3492] send query to server` 

也就是说新增的记录在smartdns的缓存影响下会将SOA记录缓存46分钟之久，远超最大TTL 1200秒，即使大部分上游都正确响应后过了足足19分钟smsartdns才再次请求上游。

相关issue：#1319 

**可能的解决方案：**  

- 修改配置：
1. 设置`rr-ttl-max`限制所有记录的最大TTL
2. 降低`cache-size`让后来的记录将此SOA缓存清除

上述两种解决方案都有其副作用，有点因小舍大的感觉

- smartdns逻辑修改：
SOA等可被视作错误/不存在的响应不去缓存

**运行环境**
1. 固件型号  
OpenWrt 23.05 x86_64 
6. 运营商  
不相关
7. smartdns来源以及版本
GitHub release 43
8. 涉及的配置(注意去除个人相关信息)
```
server-name smartdns
speed-check-mode none
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 10000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 64K
log-num 1
log-level debug
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
resolv-file /tmp/resolv.conf.d/resolv.conf.auto
```

[2023-12-05 00:05:24,354][DEBUG][     dns_client.c:3492] send query to server

**Comment by PikuZheng** [comment]
1.2022.v39.0.4
将DNS SOA记录的TTL设为30（这样真的好吗，根据RFC1033，SOA的TTL由起始授权机构自主决定，目前.com是86400，.cn是21600

所以是30秒。
19分钟应该是哪里出问题了。

**Comment by PikuZheng** [comment]
还有就是，SOA应答不是一个“查询错误”

**Comment by PikuZheng** [comment]
这里定义的 https://github.com/pymumu/smartdns/blob/11d92a67a17e28e420b1dece4e502adf49d9e404/src/dns_server.c#L63
但是解释不了你遇到的“46分钟”现象

**Comment by pymumu** [comment]
看你的配置，你把测速关了，SOA的结果是直接透传了上游返回的结果，用的超时时间也是上游给的超时时间。

**Comment by PikuZheng** [comment]
> 看你的配置，你把测速关了，SOA的结果是直接透传了上游返回的结果，用的超时时间也是上游给的超时时间。

文档最好能标注一下哪些功能是依赖缓存，哪些依赖测速

**Comment by CallMeR** [comment]
给缓存加个是否缓存 soa 的开关？
