### ISSUE TITLE
我也遇到了 SRV没有正常返回的问题，从#957 中查看需要将is_result_discard=1改为is_result_discard=0 但是我在最新版的代码里面没有找到

### ISSUE THREAD

**Issue by maoxiaomo** [pymumu/smartdns#1583]
**问题现象**  
简要描述问题出现的现象

      我也遇到了 SRV没有正常返回的问题，和#957遇到了相同的问题。从[#957](https://github.com/pymumu/smartdns/issues/957) 中查看需要修改将is_result_discard=1改为is_result_discard=0 但是我在最新版的代码里面没有找到。

**运行环境**
1. centos 7   

2. 运营商  
    原生网络

3. smartdns来源以及版本
     使用的版本为[smartdns.1.2023.08.11-1937.x86_64-linux-all.tar.gz](https://github.com/pymumu/smartdns/releases/download/Release43/smartdns.1.2023.08.11-1937.x86_64-linux-all.tar.gz)

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  
172.16.100.20

2. 访问的域名。  
  类型 srv _ldap._tcp.dc._msdcs.local.com

**Comment by PikuZheng** [comment]
#957 已经有永久修改了，没discard这个代码了https://github.com/pymumu/smartdns/commit/09dc2e9275c7a589b4a2bb280bdba617937ab3ef#diff-593ced5c0d2c1e50378c33c17cd07cac9c6ba0856e3919474081ef40c68155abL2409

**Comment by maoxiaomo** [comment]
![微信图片_20231207150303](https://github.com/pymumu/smartdns/assets/79297978/a5acbaf3-3265-4645-9c87-41077e4515b6)


我使用Wireshark抓到了数据包。 100.66 是smartdns服务器。

**Comment by PikuZheng** [comment]
> 我上游是有多个DNS服务器的，但是把内网的域名划分了office分组，只有指定的域名才去office，通过查看日志信息，发现请求有成功去到office组。这是本地的错误信息。 ![image](https://private-user-images.githubusercontent.com/79297978/288690915-2ba599d9-7ec7-4515-a44b-f0d07792f173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Mzg5MTUsIm5iZiI6MTcwMTkzODYxNSwicGF0aCI6Ii83OTI5Nzk3OC8yODg2OTA5MTUtMmJhNTk5ZDktN2VjNy00NTE1LWE0NGItZjBkMDc3OTJmMTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA4NDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTQ2NmZkMTExNWVjMDRmMzEzYjZlYTM3YzAxYzY5N2JhMjAzNzY0YjliNDVmZDE0M2YzMWIzMTdjNjIwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LtXCxFQGKW0O_6OLEiCiHcdbmfexFCuO66XZW8cW8Eo)
> 
> 但是我排查这个问题的时候发现，如果上游服务器不划分分组，smartdns就可以正确返回结果。

你 这是分别查询域名“srv”的ip和域名“_ldap._tcp.........”的A+AAAA记录

**Comment by maoxiaomo** [comment]
我的分组配置信息如下：

vim smartdns.conf
conf-file office.conf
server 172.16.100.20 office -exclude-default-group

vim office.conf
nameserver /XXXXX.com/office


是不是我配置信息出现了错误   导致了这个问题发生

**Comment by maoxiaomo** [comment]
我现在的痛点是上游DNS如果设置了分组客户端和AD域控服务器通讯就会异常。 不设置分组，这个故障就会消失，通讯就会恢复正常。

**Comment by PikuZheng** [comment]
> ![image](https://github.com/pymumu/smartdns/assets/79297978/4a52e1c8-97d2-4826-9bc2-aff8cee8fa18)
> 
> 这是刚才打印的日志
> 
> 

看不出来，规则匹配在解析前。图中是解析后

**Comment by maoxiaomo** [comment]
我重新修改了语法，问题重新复现了一下。应该就是语法设置错误引起的，当前已经没有问题了

**Comment by pymumu** [comment]
最新代码尝试支持srv记录，可以验证看看
