### ISSUE TITLE
求教一个问题，为啥从第二端口进来的 DNS 请求有必要再次请求默认 dns 组

### ISSUE THREAD

**Issue by CallMeR** [pymumu/smartdns#1584]
**问题现象**    

举一个比较极端的栗子，假设公司内部有一个私有云使用的域名 `good.cloud`  

然后内部服务的服务器也会将 `hostname` 注册到这个域名下

由于历史原因，无法替换 `good.cloud` ，且 `good.cloud` 这个域名其实是一个可以被公网解析的域名  

此时公司主 DNS 用了 smartdns ，配置参考如下：

```conf
bind [::]:53
bind-tcp [::]:53

bind [::]:6053 -no-dualstack-selection -force-aaaa-soa -group goodcloud
bind-tcp [::]:6053 -no-dualstack-selection -force-aaaa-soa -group goodcloud

server 119.29.29.29
server 223.5.5.5

server 10.23.0.1 -exclude-default-group -group goodcloud
```

按照现有 smartdns 处理顺序，

- 从 53 端口进入的 dns 请求，会使用前两个解析 

- 从 6053 端口进入的 dns 请求，实际上会使用全部服务器进行解析

的确，可以加入 `nameserver /good.cloud/goodcloud` 这样的规则让 dns 解析行为符合预期，但真实环境可能更加复杂  

看文档中的描述，第二 dns 端口的设计初衷是为了 dns 分流，那么是基于什么样的考虑，从第二 dns 端口进入的请求还需发往默认组

我测试了一下这种写法，结果是，public 组似乎变成了新的默认组

```conf
bind [::]:53 -group public
bind-tcp [::]:53 -group public

bind [::]:6053 -no-dualstack-selection -force-aaaa-soa -group goodcloud
bind-tcp [::]:6053 -no-dualstack-selection -force-aaaa-soa -group goodcloud

server 119.29.29.29 -exclude-default-group -group public
server 223.5.5.5 -exclude-default-group -group public

server 10.23.0.1 -exclude-default-group -group goodcloud
```

所以求教一个问题，为啥从第二端口进来的 DNS 请求有必要再次请求默认 dns 组

**Comment by PikuZheng** [comment]
第一种写法是对的。但是设计上不应该跑到默认组去。
smartdns功能和逻辑上也有一些历史遗留问题。
也不排除查询时进来的端口不对（被劫持或被转发了？）
试试这样的配置：
```
bind [::]:53
bind-tcp [::]:53

bind [::]:6053 -force-aaaa-soa -group goodcloud
bind-tcp [::]:6053 -force-aaaa-soa -group goodcloud

server 119.29.29.29 -group public
server 223.5.5.5 -group public

server 10.23.0.1 -exclude-default-group -group goodcloud
```

第二种配置方式不完全对，按照第二种的逻辑，不需要6053口：
```
bind [::]:53
bind-tcp [::]:53

server 119.29.29.29
server 223.5.5.5

server 10.23.0.1 -exclude-default-group -group goodcloud

domain-rules /good.cloud/ -a #6 -n goodcloud
```
（在 force aaaa soa情况下没必要指定 no-dualstack-selection）

**Comment by CallMeR** [comment]
> 第一种写法是对的。但是设计上不应该跑到默认组去。 smartdns功能和逻辑上也有一些历史遗留问题。 也不排除查询时进来的端口不对（被劫持或被转发了？） 试试这样的配置：
> 
> ```
> bind [::]:53
> bind-tcp [::]:53
> 
> bind [::]:6053 -force-aaaa-soa -group goodcloud
> bind-tcp [::]:6053 -force-aaaa-soa -group goodcloud
> 
> server 119.29.29.29 -group public
> server 223.5.5.5 -group public
> 
> server 10.23.0.1 -exclude-default-group -group goodcloud
> ```
> 
> 第二种配置方式不完全对，按照第二种的逻辑，不需要6053口：
> 
> ```
> bind [::]:53
> bind-tcp [::]:53
> 
> server 119.29.29.29
> server 223.5.5.5
> 
> server 10.23.0.1 -exclude-default-group -group goodcloud
> 
> domain-rules /good.cloud/ -a #6 -n goodcloud
> ```
> 
> （在 force aaaa soa情况下没必要指定 no-dualstack-selection）

感谢指出配置文件中多余的配置项，不过我的测试环境中该服务器没有设置 dns redirect

在写这个 issue 之前，我也翻看了好多相关的已有 issue ， 最类似的是这个 https://github.com/pymumu/smartdns/issues/1368

> > 对于-exclude-default-group这个参数，我目前的理解是，如果加了该参数，就只响应5354端口传进来group out组的查询，如果没加该参数，会同时响应5353和5354端口传进来的默认组和out组查询？
> 
> 应该是这样的，但总觉得哪里不对
> 
> > 比如server-https [https://xxx.com/xxx -group](https://xxx.com/xxx%C2%A0-group) out 该服务器是不是会同时响应5353和5354端口的查询？
> 
> 会
> 
> > 而server-tls 8.8.4.4 -group out -exclude-default-group只会响应5354端口的查询？
> 
> 对

看到这个，我感觉这个是一直都存在的现象

**Comment by jxph1123** [comment]
应该不会，加-exclude-default-group的目的就是跳过默认组，如果加了还走默认 dns，那这个参数有啥用。。。

**Comment by pymumu** [comment]
预期行为不是这样，提供相关的debug log吧
还有确保升级最新版本

**Comment by PikuZheng** [comment]
> 不过我的测试环境中该服务器没有设置 dns redirect

是的我的疑问就是这个，我猜测这些请求没有正确的到6053口，那么哪个前置负责转发特定域名到6053？

**Comment by CallMeR** [comment]
找到问题了，本机上游 DNS 的服务器的 DNS 列表中存在本机地址，所以某些情况下会把 DNS 请求重新发回到本机，这样造成了 DNS 循环请求。
