### ISSUE TITLE
Is SmartDNS possible installed on OS X Mojave?

### ISSUE THREAD

**Issue by jiangzp85** [pymumu/smartdns#159]
**需求应用场景**
Is SmartDNS possible installed on OS X Mojave? I wanna use Smart_#$#$DNS as local dns directly install on my MBP, I tried to install via x86_xxx.tgz but failed.

Any idea?
**建议的方案**
none

**设备信息**
MBP Mojave

2. 固件信息

**Comment by pymumu** [comment]
Does not support macos, only supports linux, such as router, raspberry pi, WSL

**Comment by jiangzp85** [comment]
> Does not support macos, only supports linux, such as router, raspberry pi, WSL

Thanks a lot for your reply, i will try install SD on my another Linux-based server, thanks a lot for your great job~~

**Comment by ghostry** [comment]
```
brew cask install docker
docker run -d -p 53:53/udp --restart=always --name gsmartdns -v ~/.gsmartdns:/smartdns ghostry/smartdns
```
