### ISSUE TITLE
如果 上游doh ip地址变动了 并没有更新

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1592]
我发现 上游用的doh 域名形式
但是 偶尔 cdn ip会变动
smartdns只是报错 但是并没有更新ip

**Comment by PikuZheng** [comment]
重复#1138

**Comment by lalasou** [comment]
cdn 的话  变动很正常
虽然也不是经常变动

**Comment by PikuZheng** [comment]
是的这个问题也困扰我。。。自架上游的情形，有时一个不可用希望能自动切到另一个

**Comment by lalasou** [comment]
算了 就这吧  
不知道 Chrome 浏览器的doh  这种情况怎么处理的
