### ISSUE TITLE
能不能增加一个可以指定上游dns服务器只查询a或者aaaa记录?

### ISSUE THREAD

**Issue by ziojacky** [pymumu/smartdns#1594]
配置文件里一般使用server指定上游dns服务器,但是没有办法单独指定这个上游服务器查询a还是aaaa,配置选项里force-AAAA-SOA这个只能应用于全局,能不能添加一个功能可以单独指定server的查询记录只能是a或者aaaa?

**Comment by pymumu** [comment]
有什么用？

**Comment by ziojacky** [comment]
> 有什么用？

主要是想过滤掉那些被墙和海外的域名返回AAAA记录。

**Comment by PikuZheng** [comment]
有一定作用。如果是按端口分流的，那么这部分上游服务器可能需要只返回a记录。

**Comment by pymumu** [comment]
1. bind 支持过滤IPV6， -force-aaaa-soa
2. domain-rules 支持指定域名过滤IPV6，`-address #6`

**Comment by wangyi2005** [comment]
whitelist-ip 0.0.0.0/0
blacklist-ip 0.0.0.0/0

server 2001:4860:4860::6464 -blacklist-ip
server 运营商dns  -whitelist-ip

**Comment by RichardLuo0** [comment]
> 1. bind 支持过滤IPV6， -force-aaaa-soa
> 2. domain-rules 支持指定域名过滤IPV6，`-address #6`

我请求重开一下这个issue 我现在的情况是有一个dns只支持ipv4 如果向他请求aaaa记录的话就会过一段时间timeout，这种情况下我想直接让smartdns对于这一个server就不要去查aaaa记录了
