### ISSUE TITLE
多个 domain-set 同名，效果是叠加，还是覆盖？

### ISSUE THREAD

**Issue by cresky-github** [pymumu/smartdns#1598]
# 域名集 BLOCK，DNS 黑名单
domain-set -name BLOCK -type list -file "/www/domain/block.txt"
domain-set -name BLOCK -type list -file "/etc/smartdns/tiktok.txt"
domain-set -name BLOCK -type list -file "/bash/data/geosite/geosite_qihoo360.txt"
address /domain-set:BLOCK/#

类似这样配置，三个文件是否同时生效？
还是最后一个文件生效？

**Comment by PikuZheng** [comment]
我就是这样用的，据我观察是叠加生效

**Comment by cresky-github** [comment]
经实验，
不是叠加，是覆盖。
即，最后一个文件生效。

domain-set / address 指令成组使用。也就是一对一使用。

**Comment by cresky-github** [comment]
再次实验，确认是叠加生效的。
