### ISSUE TITLE
中文文档中有错别字

### ISSUE THREAD

**Issue by nnzmj** [pymumu/smartdns#1599]
**问题现象**  
https://pymumu.github.io/smartdns/config/dualstack/
在“配置指导”——“双栈优选”——“配置步骤”——“3. 允许纯IPv6地址”中 原因“**时**”某些软件不具备IPV6的访问能力，字面理解应该为“是”。估计输入法敲错了
![callback_smartdns](https://github.com/pymumu/smartdns/assets/31726009/b87ed68b-b59c-45ef-8f2d-455a58f765a0)

**Comment by pymumu** [comment]
感谢支持问题，已经修正。

后续如果文档问题，欢迎修正，对应的文档代码库：https://github.com/pymumu/smartdns/tree/doc
