### ISSUE TITLE
询问一下筛选最快DNS查询结果的逻辑和原理

### ISSUE THREAD

**Issue by q741451** [pymumu/smartdns#160]
如何知道某个DNS服务器返回的IP是快IP的？如果本地路由器有挂代理，有个对外访问的路由表怎么办？
某些域名是适合走代理DNS查询的结果，然后通过代理访问。某些IP适合国内CDN走直连。对于这些情况的处理逻辑是什么？
我问的好像有点含糊不清( ╯□╰ )。

**Comment by pymumu** [comment]
目前smartdns没有对代理做支持，无法支持代理优选。
如果需要走代理的域名建议直接address设置。

**Comment by ghostry** [comment]
这个需求，smartDNS放到透明代理后边，就可以了。

**Comment by johnspiin** [comment]
> 这个需求，smartDNS放到透明代理后边，就可以了。

请问如何放，要怎么设置呢？

**Comment by ghostry** [comment]
> > 这个需求，smartDNS放到透明代理后边，就可以了。
> 
> 请问如何放，要怎么设置呢？

方法很多了,比如openwrt的话,恩山有很多教程.如果自身也走透明代,smartdns就可以放到自身,自身不走代理的话,就放到一个二级设备上面.主要就是让规则能应用到smartdns.这样它测出来的线路也是符合规则的.
