### ISSUE TITLE
当返回的IP结果全部不可联通时，此时的优选返回逻辑是怎么样？

### ISSUE THREAD

**Issue by giveup** [pymumu/smartdns#1600]
**问题现象**  
例如Google.com，返回的无论是IPv4还是IPv6，应该全部是不可联通的。
如果使用代理去测速的话，那么无论是配置了socks还是http，应该都不支持icmp去测速。
对于这些域名，是否完全关闭优选测速是比较好的选择。

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
测速全不通，则按原样返回结果。
测速的作用是排序，不是筛选。

是的，这个场景中没有必要测速。
