### ISSUE TITLE
openwrt pppoe 获取ipv6地址比v4要慢 大概3～6s 左右

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1603]
openwrt pppoe 获取ipv6地址比v4要慢 大概3～6s 左右 smartdns 没获取到v6  会有错误日志 

我在手动重启dropbear时顺便也把smartdns reload 一下

这种操作是否必要  还是不用管他smartdns会自适应

怎么避免

**Comment by lalasou** [comment]
暂时这样解决吧
新建脚本  并chnod +x
![image](https://github.com/pymumu/smartdns/assets/7440313/ef440cab-9c98-42ab-aa91-a5cff9c727c7)

**Comment by PikuZheng** [comment]
180秒测一次，可用后ipv6相关功能会恢复
https://github.com/pymumu/smartdns/blob/master/src/dns_server.c#L61
