### ISSUE TITLE
设置自动保存缓存 edns 会丢失

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1605]
设置的自动保存缓存文件
会发现一段时间后  edns 没了

![image](https://github.com/pymumu/smartdns/assets/7440313/2bfec95d-2941-441f-82a4-4cca115620b7)

dig o-o.myaddr.google.com  TXT

**Comment by lalasou** [comment]
手动 reload 两次后又有了

![image](https://github.com/pymumu/smartdns/assets/7440313/c83f737e-9c39-4771-9a3e-92839b4a7964)

**Comment by PikuZheng** [comment]
回退到42.0.13或更早版本能解决吗

**Comment by pymumu** [comment]
edns是配置在smartdns的配置文件里面，还是说下游查询的时候带的edns

如果是下游查询的时候带的edns，如果你查的时候没有带edns，那么缓存数据就会被刷新成不带edns的。
如果是配置在smartdns里面的edns，不应该出错。

**Comment by lalasou** [comment]
> edns是配置在smartdns的配置文件里面，还是说下游查询的时候带的edns
> 
> 
> 
> 如果是下游查询的时候带的edns，如果你查的时候没有带edns，那么缓存数据就会被刷新成不带edns的。
> 
> 如果是配置在smartdns里面的edns，不应该出错。

在配置文件里的
客户端 直接 dig o-o.myaddr.google.com  TXT

relod 以后 正常 但是一段时间后就没有了
应该是  设置的那个 自动保存缓存后

**Comment by pymumu** [comment]
应该不会，配置文件里面的，都是强制生效的。

最好能找到重现步骤和日志。

**Comment by lalasou** [comment]
路由器  空间比较小  我尽量提供日志

**Comment by lalasou** [comment]
也有可能是我上游问题  我再测试下

**Comment by PikuZheng** [comment]
不是，写入缓存里的应该是上游应答的edns信息吧？不应该是配置中你发出去的。
如果有的上游应答中没有edns，而恰好这个上游命中了某些规则（比如最快应答，那么缓存里应该也没edns

**Comment by pymumu** [comment]
或者你可以用最新代码看看有没有问题。

**Comment by lalasou** [comment]
> 不是，写入缓存里的应该是上游应答的edns信息吧？不应该是配置中你发出去的。
> 
> 如果有的上游应答中没有edns，而恰好这个上游命中了某些规则（比如最快应答，那么缓存里应该也没edns

大概就是你说的这个意思了

**Comment by lalasou** [comment]
> 或者你可以用最新代码看看有没有问题。
> 
> 
> 
> 另外，如果你配置了多个上游，如同PikuZheng所说，可能某个上游不支持edns，但返回结果较快，那么这时候的缓存就没有edns。

已解决  排查 有个上游 不支持edns😓
