### ISSUE TITLE
有ipv6的情况下,本地v6地址无效

### ISSUE THREAD

**Issue by jerry56578** [pymumu/smartdns#161]
**运行环境**
koolshare openwrt 2.31 
移动宽带
CPU:J1900直接安装openwrt

v4ip: 10.0.0.1
v6ip:2409:xxxx:xxxx:xxxx::1
v6ip:fd7a:xxxx:xxxx:xxxx::1

**问题现象**  
路由器分配的默认dns服务器ip是fd7a:xxxx:xxxx:xxxx::1,nslookup qq.com显示结果无效,但是电脑指定dns服务器为2409:xxxx:xxxx:xxxx::1是后服务生效.这是问题1

问题2
在上面电脑已经指定dns服务器为2409:xxxx:xxxx:xxxx::1基础上重启路由器,然后更换已变动的v6ip为2409:yyyy:yyyy:yyyy::1,这时nslookup qq.com 2409:yyyy:yyyy:yyyy::1无效(而nslookup qq.com 10.0.0.1是有效的),必须关闭smartdns然后再打开,nslookup qq.com 2409:yyyy:yyyy:yyyy::1才会生效.

总结我的问题主要是fd7a:xxxx:xxxx:xxxx::1无效,最后关闭IPV6服务器,关闭双栈IP优选,nslookup qq.com默认都会走ipv6设置的地址.
我无法确认是否路由器对v6ip分配的设置错误而导致的,所以只好在这里提问

**信息收集**  
[smartdns.log](https://github.com/pymumu/smartdns/files/3228313/smartdns.log)

**Comment by pymumu** [comment]
1. ping一下fd7a:xxxx:xxxx:xxxx::1看看能不能通。
2. 工作模式选择的什么，时重定向还是，作为DNSMASQ的上游，更换一下看看。

**Comment by jerry56578** [comment]
1. ping fd7a:xxxx:xxxx:xxxx::1一直都是通的
2. 上面无效的模式是重定向 ,作为dnsmasq上游效果是这样的
C:\Users\E3v3>nslookup qq.com fd7a:xxxx:xxxx:xxxx::1
服务器:  Openwrt.lan
Address:  fd7a:xxxx:xxxx:xxxx::1

非权威应答:
名称:    qq.com
Address:  111.161.64.40

不知道是否算是有效?

**Comment by pymumu** [comment]
重定向的情况，在IPV6场景下可能无效，因为路由器固件可能不支持ip6table。

所以，你的网络，用模式2就好。

**Comment by jerry56578** [comment]
明白了,谢谢
