### ISSUE TITLE
server-tls和server-https中-host-name参数问题

### ISSUE THREAD

**Issue by HX-Technology-LLC** [pymumu/smartdns#1611]
**问题现象**  
简要描述问题出现的现象
server-tls和server-https中使用-host-name 把名称设置为- 发送的tls连接中的client hello 仍然发送了sni扩展,但名称为-
**运行环境**
1. 固件型号  
hiboy padavan
2. 运营商  
所有运营啥均出现
3. smartdns来源以及版本
padavan自带 使用smartdns-v输出的参数为smartdns 1.20221004-0022
4. 涉及的配置(注意去除个人相关信息)
server-https dns.google -host-name -
server-https one.one.one.one -host-name -
**重现步骤**
1. 上游DNS配置。  
server-https dns.google -host-name -
server-https one.one.one.one -host-name -
2. 访问的域名。  
不重要

**Comment by pymumu** [comment]
用最新代码
