### ISSUE TITLE
address /netflix.com/-6 依然正常返回AAAA

### ISSUE THREAD

**Issue by Mosney** [pymumu/smartdns#1612]
**问题现象**  

`address /netflix.com/-6` 依然正常返回AAAA
只有使用 `address /netflix.com/#6` 才可以在查询AAAA时返回SOA，以达到忽略这些地址AAAA记录的目的

文档中是说-表示忽略，按我的理解就是drop AAAA查询结果，但是实际看起来并不是。
| 键名 | 功能说明 | 默认值 | 可用值/要求 | 举例 |
| :--- | :--- | :--- | :--- | :--- |
| address | 指定域名 IP 地址 | 无 | address /[*\|-.]domain/[ip1[,ip2,...]\|-\|-4\|-6\|#\|#4\|#6] <br />- 表示忽略 <br /># 表示返回 SOA <br />4 表示 IPv4 <br />6 表示 IPv6 <br /> * 开头表示通配<br />- 开头表示主域名<br /> `*` 和 `-` 只能在域名开头，其他位置不生效。| address /www.example.com/1.2.3.4<br />address /www.example.com/::1 <br />address /example.com/1.2.3.4,5.6.7.8 <br /> address /\*-a.example.com/ <br /> address /\*.example.com/ <br > address /-.example.com/|

**运行环境**
1. 固件型号  
 OpenWrt 23.05.0 (r23497-6637af95aa)
2. 运营商  
无关
3. smartdns来源以及版本
GitHub release
1.2023.08.11-1937
4. 涉及的配置(注意去除个人相关信息)
```
server-name smartdns
speed-check-mode tcp:443,tcp:80,ping
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 10000
dnsmasq-lease-file /tmp/dhcp.leases
rr-ttl-min 600
log-size 500k
log-num 1
log-level info
cache-persist no
...
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
```
**重现步骤**
配置`-6`
```
# /etc/smartdns/address.conf
address /netflix.com/-6
```
`-6`结果：
```
❯ dig -p 6053 +short aaaa www.netflix.com
apiproxy-website-nlb-prod-1-bcf28d21f4bbcf2c.elb.us-west-2.amazonaws.com.
2600:1f14:62a:de85:d7:e7a1:8f7d:f6f5
```
配置`#6`
```
# /etc/smartdns/address.conf
address /netflix.com/#6
```
`#6`结果：
```
❯ dig -p 6053  aaaa www.netflix.com

; <<>> DiG 9.16.45 <<>> -p 6053 aaaa www.netflix.com
...
;; QUESTION SECTION:
;www.netflix.com.               IN      AAAA

;; AUTHORITY SECTION:
www.netflix.com.        30      IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
...

```

**Comment by PikuZheng** [comment]
-表示忽略这条规则。比如先配置了 address /com/#6 ，再配置 address /netflix.com/-6 ，那么除了netflix.com外的其他所有以com结尾的域名都会不返回ipv6
