### ISSUE TITLE
smartdns命令行更新到最新版本

### ISSUE THREAD

**Issue by omaidb** [pymumu/smartdns#1614]
**需求应用场景**
smartdns出了新版本，要将本地的smartdns升级到最新版本

**建议的方案**
执行`smartdns update`一条命令自动将smartdns升级为最新版本

**设备信息**
1. Centos7
2. Ubuntu20.04

**Comment by CallMeR** [comment]
`./install -u && ./install -i `

:)

**Comment by PikuZheng** [comment]
你是否在寻找： install -U
https://github.com/pymumu/smartdns/blob/8e8b2465365bab29c763f202b3d0bf2b41d3fc02/package/linux/install#L250
