### ISSUE TITLE
自动更新建议

### ISSUE THREAD

**Issue by 2dogtwo** [pymumu/smartdns#1615]
当前smartdns下载文件放在/tmp下，建议放进单独文件夹
每次下载文件前删除该文件夹，以防止已存在文件导致无法下载
我是添加了广告过滤自动下载更新后，点了一下更新文件，但并未下载成功，scp连接查看，有下载文件，但不完整，过了一天再次查看，这个不完整的文件依然存在，相应更新规则也无法生效，暂不知道这个文件是不是有进程占用导致没有删除，我重启路由器重新刷固件了

**Comment by pymumu** [comment]
done
