### ISSUE TITLE
你们 阿里doh  经常500错误不

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1616]
ernal Server Error
[2024-01-08 16:06:49,228][ WARN][     dns_client.c:2545] http server query from 223.5.5.5:443 failed, server return http code : 500, Internal Server Error

很多这个错误
但是dot就几乎没有

但是 dot 实测明显比doh慢些

**Comment by lalasou** [comment]
server-tls 8.8.8.8:853 -spki-pin 'KicaYAUsDUiRnHoOswhQPuVe/zLyxrwvGWn3sqMLy+k=' -subnet 39.12.77.0/24
server-https https://223.5.5.5/dns-query -spki-pin 'ZwR21gnCMTzsM6VWtnb/azufgYegWWuhE9reP5tamWU=' -subnet 39.12.77.0/24
server-https https://abc.com/dns-query -spki-pin 'YJzXqVUkIx43Cb7FHNL9/AUiyFTDHKF90=' -host-name abc.com -tls-host-verify abc.com


这个上游配置没什么格式错误吧（域名替换了）

**Comment by PikuZheng** [comment]
理论上dot首次连接快，doh连续查询快
不用阿里，但有没有可能是触发了阿里的限制？

**Comment by lalasou** [comment]
> 理论上dot首次连接快，doh连续查询快
> 
> 不用阿里，但有没有可能是触发了阿里的限制？

大佬用什么？


话说 是不是 tcp 没有连接保持
算了 用dot吧  就是dot慢点

**Comment by PikuZheng** [comment]
我用腾讯云东北（主要是阿里的过期缓存，对我依赖的ddns不友好

**Comment by lalasou** [comment]
> 我用腾讯云东北（主要是阿里的过期缓存，对我依赖的ddns不友好

腾讯云东北？
分享下

那应该也有其他地区吧   华中？

**Comment by PikuZheng** [comment]
> 腾讯云东北？ 分享下
> 
> 那应该也有其他地区吧 华中？

https://github.com/PikuZheng/smartdns/wiki/%E8%87%AA%E7%94%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%A4%87%E4%BB%BD 最后两行，而且只有doh

没有其他地区，其他地区都是120.53.53.53和1.12.12.12
