### ISSUE TITLE
smartdns 编译请求

### ISSUE THREAD

**Issue by fox85** [pymumu/smartdns#162]
你好，请问能不能根据以下这份SDK编译一份ipq806x架构的smartdns呢？谢谢你

git clone https://github.com/gl-inet/sdk.git

我已经尝试了目前你预先编译好的 ipk 包，安装后均无法运行在gl-inet的含QSDK私有驱动的OpenWrt固件上，而哥写的smartdns尚未开源，还望你能帮忙用以上SDK编译一份，他们家的SDK编译也是非常简单，把makefile丢进去package后执行make就可以编译了，感激！  

我亦在恩山论坛作了回帖，请求帮忙，谢谢！
https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=331558&pid=4026644

**Comment by pymumu** [comment]
opkg print_architecture

这个命令输出什么。

**Comment by fox85** [comment]
就是ipq806x 的，gl-inet的固件是基于CC 15.05.1的

**Comment by fox85** [comment]
> opkg print_architecture
> 
> 这个命令输出什么。

arch 是 ipq806x 的，gl-inet的固件是基于OpenWrt CC 15.05.1的， 我尝试用了你预编译好的arm_cortex-a15_neon-vfpv4.ipk  和 arm_cortex-a7_neon-vfpv4.ipk
都是运行不起来的

**Comment by pymumu** [comment]
arm的没有15.05的版本，只有18.06

**Comment by fox85** [comment]
> arm的没有15.05的版本，只有18.06

是阿，所以要用他们家的SDK才能编译呢
git clone https://github.com/gl-inet/sdk.git

**Comment by pymumu** [comment]
那个sdk看了，缺少openssl，无法编译。
编译环境要重搞的话，需要一段时间。+

**Comment by fox85** [comment]
> 那个sdk看了，缺少openssl，无法编译。
> 编译环境要重搞的话，需要一段时间。
> 如果能用18.06，建议升级18.06
> 15.0x的，后面不打算支持了。

谢谢哥！ 
你说到的缺少openssl，我用这个SDK能编译成功带openssl依赖的相关的程序，比如说openvpn-openssl， libwebsockets-openssl 等，所以应该不缺吧？ 不知道我理解的对不对？ 期待哥的解答！

其实我不是不想升级18.06，是因为他们家官方固件是含qsdk驱动的，如果用openwrt 18.06，就没有办法用含QSDK无线驱动的功能了。 所以如果可以的情况下，还请哥你能帮忙编译这个架构的SMARTDNS。
smartdns的功能还是很赞的，我目前用着unbound代替，感觉smartdns在结果返回耗时上，比unbound要快得多！

**Comment by zanzhz1101** [comment]
我觉得你是不是可以考虑下pandorabox。。。。http://downloads.pangubox.com:6380/

> > 那个sdk看了，缺少openssl，无法编译。
> > 编译环境要重搞的话，需要一段时间。
> > 如果能用18.06，建议升级18.06
> > 15.0x的，后面不打算支持了。
> 
> 谢谢哥！
> 你说到的缺少openssl，我用这个SDK能编译成功带openssl依赖的相关的程序，比如说openvpn-openssl， libwebsockets-openssl 等，所以应该不缺吧？ 不知道我理解的对不对？ 期待哥的解答！
> 
> 其实我不是不想升级18.06，是因为他们家官方固件是含qsdk驱动的，如果用openwrt 18.06，就没有办法用含QSDK无线驱动的功能了。 所以如果可以的情况下，还请哥你能帮忙编译这个架构的SMARTDNS。
> smartdns的功能还是很赞的，我目前用着unbound代替，感觉smartdns在结果返回耗时上，比unbound要快得多！

**Comment by fox85** [comment]
> 我觉得你是不是可以考虑下pandorabox。。。。http://downloads.pangubox.com:6380/
> 
我在用的路由器型号是GL-B1300，CPU是IPQ4018，pandorabox的SDK应该不适用的

**Comment by fox85** [comment]
> opkg print_architecture
> 
> 这个命令输出什么。

login as: root
root@192.168.181.1's password:


BusyBox v1.25.1 (2019-01-10 15:04:51 CST) built-in shell (ash)

     MM           NM                    MMMMMMM          M       M
   $MMMMM        MMMMM                MMMMMMMMMMM      MMM     MMM
  MMMMMMMM     MM MMMMM.              MMMMM:MMMMMM:   MMMM   MMMMM
MMMM= MMMMMM  MMM   MMMM       MMMMM   MMMM  MMMMMM   MMMM  MMMMM'
MMMM=  MMMMM MMMM    MM       MMMMM    MMMM    MMMM   MMMMNMMMMM
MMMM=   MMMM  MMMMM          MMMMM     MMMM    MMMM   MMMMMMMM
MMMM=   MMMM   MMMMMM       MMMMM      MMMM    MMMM   MMMMMMMMM
MMMM=   MMMM     MMMMM,    NMMMMMMMM   MMMM    MMMM   MMMMMMMMMMM
MMMM=   MMMM      MMMMMM   MMMMMMMM    MMMM    MMMM   MMMM  MMMMMM
MMMM=   MMMM   MM    MMMM    MMMM      MMMM    MMMM   MMMM    MMMM
MMMM$ ,MMMMM  MMMMM  MMMM    MMM       MMMM   MMMMM   MMMM    MMMM
  MMMMMMM:      MMMMMMM     M         MMMMMMMMMMMM  MMMMMMM MMMMMMM
    MMMMMM       MMMMN     M           MMMMMMMMM      MMMM    MMMM
     MMMM          M                    MMMMMMM        M       M
       M
 ---------------------------------------------------------------
   For those about to rock... (Chaos Calmer, r48067)
 ---------------------------------------------------------------
root@GL-B1300:~# opkg print_architecture
arch all 1
arch noarch 1
arch ipq806x 10

**Comment by pymumu** [comment]
后面有空，我专门给你一个版本吧。但后续不会发布。
因为15.01太老了。

**Comment by fox85** [comment]
> 后面有空，我专门给你一个版本吧。但后续不会发布。
> 因为15.01太老了。

感激大佬！

**Comment by fox85** [comment]
> 后面有空，我专门给你一个版本吧。但后续不会发布。
> 因为15.01太老了。

虽然是基于CC 15.01.1 ，不过他家的固件针对内核也升级到了4.4.60，内核也不算是太老吧，哈哈：）
root@GL-B1300:~# uname -a
Linux GL-B1300 4.4.60 #7 SMP PREEMPT Wed Jan 2 14:10:33 CST 2019 armv7l GNU/Linux

**Comment by pymumu** [comment]
看一下你固件里面openssl是什么版本的。

**Comment by fox85** [comment]
> 看一下你固件里面openssl是什么版本的。

root@GL-B1300:~# openssl version
OpenSSL 1.0.2h  3 May 2016

**Comment by zanzhz1101** [comment]
http://downloads.pangubox.com:6380/pandorabox/19.04/targets/qualcomm/ipq40xx/

**Comment by pymumu** [comment]
[smartdns.1.2019.06.11-0010.arm_cortex-a7_neon-vfpv4.ipk.zip](https://github.com/pymumu/smartdns/files/3272850/smartdns.1.2019.06.11-0010.arm_cortex-a7_neon-vfpv4.ipk.zip)

看看能不能用把。

**Comment by fox85** [comment]
> [smartdns.1.2019.06.11-0010.arm_cortex-a7_neon-vfpv4.ipk.zip](https://github.com/pymumu/smartdns/files/3272850/smartdns.1.2019.06.11-0010.arm_cortex-a7_neon-vfpv4.ipk.zip)
> 
> 看看能不能用把。

感谢大佬！

已测试，需要首先配置一下软件源
arch all 100
arch arm_cortex-a7_neon-vfpv4 200
arch ipq806x 300

然后可以正常安装，但运行时就出错了，提示如下
root@GL-B1300:/# smartdns
/usr/sbin/smartdns: can't load library 'libc.so.0'

**Comment by fox85** [comment]
> [smartdns.1.2019.06.11-0010.arm_cortex-a7_neon-vfpv4.ipk.zip](https://github.com/pymumu/smartdns/files/3272850/smartdns.1.2019.06.11-0010.arm_cortex-a7_neon-vfpv4.ipk.zip)
> 
> 看看能不能用把。

给大佬汇报以下~~

如果安装了之后，进入/lib/再如以下创建软链接
root@GL-B1300:/lib# ln -s libuClibc-1.0.14.so libc.so.0

再执行 smartdns -f -v
出错的提示如下：
root@GL-B1300:/lib# smartdns -f -v
/usr/sbin/smartdns: can't resolve symbol 'pthread_create'

**Comment by pymumu** [comment]
这个编译是用的pandoraxbox编译的。
GL-B1300的工具链下载经常断线，要重新制作工具链

**Comment by fox85** [comment]
多谢大佬!    
大佬如果遇到墙外断线问题，有需要的话我可以提供代理的~~

**Comment by pymumu** [comment]
[smartdns.1.2019.06.19-2342.arm-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/3307076/smartdns.1.2019.06.19-2342.arm-openwrt-all.ipk.zip)

测试下看看能不能用把，静态编译，体积稍大。

**Comment by fox85** [comment]
> [smartdns.1.2019.06.19-2342.arm-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/3307076/smartdns.1.2019.06.19-2342.arm-openwrt-all.ipk.zip)
> 
> 测试下看看能不能用把，静态编译，体积稍大。

thanks 大佬， it works like a charm!!!
