### ISSUE TITLE
smartdns.cache  有什么办法知道缓存了多少个域名吗  或者能输出缓存的域名吗

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1621]
smartdns.cache  
有什么办法知道缓存了多少个域名吗  或者能输出缓存的域名吗

**Comment by pymumu** [comment]
```
/usr/sbin/smartdns --cache-print smartdns.cache
```

**Comment by lalasou** [comment]
👌 谢谢

**Comment by lalasou** [comment]
![image](https://github.com/pymumu/smartdns/assets/7440313/23708d01-25ff-4517-a40a-a80ea1f784fc)


提示 错误
/usr/sbin/smartdns: unrecognized option: -
load config failed.

**Comment by lalasou** [comment]
版本   smartdns 1.2023.08.11-1937
github 下载的最新版

**Comment by PikuZheng** [comment]
--cache-print 需要至少 v43.0.7

**Comment by lalasou** [comment]
> --cache-print 需要至少 v43.0.7

好吧  我下载的Release 43  ...
@pymumu 大佬要不要更新下Release 版本
