### ISSUE TITLE
ip-set:cloudflare-ipv4 -ip-alias  后面可以跟域名不？

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1624]
ip-set:cloudflare-ipv4 -ip-alias  后面可以跟域名不？（这个域名还会更新并不是获取dns结果后不动了）
比如 有个域名做好了cf优选 并且经常更新最快的ip
我把cf域名 查询ip 直接替换为这个域名返回结果可以不
或者如何实现

**Comment by pymumu** [comment]
不可以
