### ISSUE TITLE
用阿里的域名地址作为bootstrap，解析其他域名服务器失败。

### ISSUE THREAD

**Issue by jxph1123** [pymumu/smartdns#1626]
用阿里的域名地址233.5.5.5和233.6.6.6作为bootstrap，所有其他域名服务器都解析不了，换成腾讯的就可以了，这是阿里的问题还是smartdns问题？
`server-https https://233.5.5.5/dns-query -bootstrap-dns`

smartdns用的这个版本：[79c5e0aa76a7db7c92a88bb03213993a205d8da3](https://github.com/pymumu/smartdns/commit/79c5e0aa76a7db7c92a88bb03213993a205d8da3)

**Comment by PikuZheng** [comment]
建议开debug日志看看

**Comment by jxph1123** [comment]
好像又可以了，难道是间歇性抽风。。。

**Comment by lalasou** [comment]
> 好像又可以了，难道是间歇性抽风。。。

对  偶尔  doh 会连不上也不知道是限制了还是怎么
dot可用

**Comment by jxph1123** [comment]
> > 好像又可以了，难道是间歇性抽风。。。
> 
> 对 偶尔 doh 会连不上也不知道是限制了还是怎么 dot可用

确实，我把dot也加进bootstrap了

**Comment by PikuZheng** [comment]
![image](https://github.com/pymumu/smartdns/assets/12579522/151f1385-1941-4a67-bb94-f4d6f2bd96f7)
可用性应该是好的 除非触发了使用频率限制什么的

**Comment by lalasou** [comment]
> ![image](https://github.com/pymumu/smartdns/assets/12579522/151f1385-1941-4a67-bb94-f4d6f2bd96f7)
> 
> 可用性应该是好的 除非触发了使用频率限制什么的

不过dot 很少或者一般没事，就这个doh 经常抱故障

这个是什么 adg ？ 求分享  🥺求分享

**Comment by PikuZheng** [comment]
> 这个是什么 adg ？ 求分享 🥺求分享

Uptime Kuma

**Comment by lalasou** [comment]
> > 这个是什么 adg ？ 求分享 🥺求分享
> 
> 
> 
> Uptime Kuma

我以为 有大佬 给smartdns 做适配ui了呢😂
