### ISSUE TITLE
member access within misaligned address

### ISSUE THREAD

**Issue by reggae5821** [pymumu/smartdns#1629]
**问题现象**  
简要描述问题出现的现象

https://github.com/pymumu/smartdns/blob/54b4dcd65ee3b44f05446ae36a77c83f11bc374d/src/util.c#L143

`sockaddr_storage*` need a 8-byte aligned address, but `sockaddr* addr` is not at the 8-byte aligned address, which can cause a ub. 

<img width="613" alt="image" src="https://github.com/pymumu/smartdns/assets/156600806/599b7c9e-668f-44b5-b52d-1f71a2cc50ef">

**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
done
