### ISSUE TITLE
armv7  求指导求配套

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#163]
求编译啊
armv7
软件源http://pkg.entware.net/binaries/armv7/Packages.html
不能用啊
斐讯k3
这个用的还是比较多的 求配套 求指导 大佬

**Comment by pymumu** [comment]
[hello.zip](https://github.com/pymumu/smartdns/files/3272739/hello.zip)

麻烦验证一下这个程序能否执行。

**Comment by lalasou** [comment]
大佬 能回复受宠若惊 
试了下 不能执行   armv7求适配 求适配求适配😀

**Comment by pymumu** [comment]
[smartdns.1.2019.06.19-2342.arm-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/3307067/smartdns.1.2019.06.19-2342.arm-optware-all.ipk.zip)

帮忙测试下看看能不能用把

**Comment by lalasou** [comment]
可以 运行  ps 有进程

[K3 /tmp/media/nand]# nslookup -querytype=ptr 0.0.0.0BusyBox v1.25.1 (2017-02-12 00:56:19 CST) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server


luci 不能用  不知道咋设置了  求解

**Comment by lalasou** [comment]
[K3 /tmp/media/nand]# nslookup baidu.com 192.168.2.1
Server:    192.168.2.1
Address 1: 192.168.2.1 p.to

Name:      baidu.com
Address 1: 220.181.38.148
Address 2: 123.125.114.144
不懂怎么设置了 
小白 求教程😅

**Comment by lalasou** [comment]
下面是ps启动进程

2008 admin     3496 S    /opt/usr/sbin/smartdns -c /opt/etc/smart
 9397 admin      772 S    /usr/sbin/dnsmasq -n -i br0 -i br1 -r /t

**Comment by lalasou** [comment]
我看 s50smartdns 提示 dnsmasq找不到  我修改了一下 
还有其他错误

K3 /tmp/media/nand/etc/init.d]# ./S50smartdns restart
ps: invalid option -- 'a'
BusyBox v1.30.1 () multi-call binary.

Usage: ps

Show list of processes

        w       Wide output
cannot find dnsmasq
cat: can't open '/var/run/smartdns.pid': No such file or directory
smartdns not running.
ps: invalid option -- 'a'
BusyBox v1.30.1 () multi-call binary.

Usage: ps

Show list of processes

        w       Wide output
cannot find dnsmasq



小白 还是不行     等大佬教吧

**Comment by pymumu** [comment]
[S50smartdns.zip](https://github.com/pymumu/smartdns/files/3310862/S50smartdns.zip)
替换一下这个文件，并将/opt/etc/smartdns/smartdns-opt.conf中的SMARTDNS_WORKMODE改成2

**Comment by pymumu** [comment]
尝试Release 26静态编译版本把。

**Comment by lalasou** [comment]
新版本 26   安装提示
opkg install smartdns.1.2019.06.21-2337.arm-op
tware-all.ipk 
Upgrading smartdns on root from 1.2019.06.19-2342 to 1.2019.06.21-2337...
//opt/lib/opkg/info/smartdns.prerm: line 3: /opt/etc/init.d/S50smartdns: not found
Collected errors:
 * pkg_run_script: package "smartdns" prerm script returned status 127.
 * prerm_upgrade_old_pkg: prerm script for package "smartdns" failed
 * opkg_install_cmd: Cannot install package smartdns.


我替换 s50试试

**Comment by pymumu** [comment]
卸载之前的，再安装看看。

**Comment by lalasou** [comment]
替换也不行

**Comment by lalasou** [comment]
提示分段错误                                          
[K3 /tmp/media/nand]# opkg install smartdns.1.2019.06.21-2337.arm-op
tware-all-1.ipk 
提示 Segmentation fault

**Comment by pymumu** [comment]
看上去可能是指令集不支持。
你用的什么固件？

**Comment by pymumu** [comment]
[smartdns.1.2019.06.23-2138.arm-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/3317907/smartdns.1.2019.06.23-2138.arm-optware-all.ipk.zip)

试一下这个把，把之前的卸载掉。

**Comment by lalasou** [comment]
斐讯 k3 官root固件 tb的  
估计leden或者 梅林应该可以用  
只能刷机了
