### ISSUE TITLE
使用“客户端规则”时遇到了问题，请教一下。

### ISSUE THREAD

**Issue by LisonFan** [pymumu/smartdns#1634]
我的需求是默认情况下禁止`IPv6`解析，`force-AAAA-SOA yes`
通过 `group-begin` `group-end` `conf-file *.conf -g xxx` 来限制特定几个 `IP` 开启 `IPv6` 解析

`规则组`的配置如下
```
client-rules 1.1.1.1
client-rules 2.2.2.2
client-rules 3.3.3.3

force-AAAA-SOA no
```

按照我的理解，应该只会覆盖默认规则中的 `force-AAAA-SOA`，但是实际上不在 `default group` 的规则全都不生效了

我该如何实现仅针对个别 `IP` 开启 `IPv6` 解析的情况下，其他规则照常生效？

**Comment by pymumu** [comment]
force-AAAA-SOA 会集成上一层组的配置

```
force-AAAA-SOA yes

group-begin client
client-rules 192.168.1.1
force-AAAA-SOA no
group-end

```

但是如果用的是force-qtype-SOA屏蔽的，目前只能通过如下方式恢复，force-AAAA-SOA no不会生效。

```
address -6
```

**Comment by pymumu** [comment]
就是这样设计的
