### ISSUE TITLE
某些域名没有ipv6结果

### ISSUE THREAD

**Issue by xqdoo00o** [pymumu/smartdns#1636]
**问题现象**  
dig raw.githubusercontent.com AAAA @127.0.0.1
结果是SOA
dig raw.githubusercontent.com AAAA @8.8.8.8
结果正常

**运行环境**
1. 固件型号  

2. 运营商  
甲骨文
3. smartdns来源以及版本
Release 43, Github release deb.
4. 涉及的配置(注意去除个人相关信息)
server 8.8.8.8
server 8.8.4.4

**重现步骤**
1. 上游DNS配置。  
8.8.8.8
8.8.4.4
2. 访问的域名。  
raw.githubusercontent.com

**Comment by PikuZheng** [comment]
建议开debug日志，看看这个soa怎么来的

**Comment by xqdoo00o** [comment]
dualstack-ip-selection no
就没问题了
