### ISSUE TITLE
有没有类似DNSMASQ的address功能 可以自定义域名ip的地方

### ISSUE THREAD

**Issue by wosl2001** [pymumu/smartdns#164]
有没有类似DNSMASQ的address功能 可以自定义域名ip的地方

最好FAQ里面给出个完整的配置案例 谢谢

**Comment by pymumu** [comment]
参考这里

https://github.com/pymumu/smartdns#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0

**Comment by wosl2001** [comment]
谢谢
