### ISSUE TITLE
云编译lede openwrt时使用懒人脚本更新smartdns版本不一致

### ISSUE THREAD

**Issue by smdx** [pymumu/smartdns#1641]
**问题现象**  
各位大佬好，在GIthub云编译lede openwrt时使用懒人脚本更新smartdns版本不一致，另外添加了
https://github.com/kenzok8/small-package 仓库，在执行懒人脚本去已经使用rm命令删除了仓库的smartdns，
在懒人脚本执行前执行了 ./scripts/feeds update -a，懒人脚本后执行./scripts/feeds install -a。
但是编译好的固件smartdns版本不相同，请问那里出了问题？怎么解决？谢谢
![2024-01-22_085500](https://github.com/pymumu/smartdns/assets/9279217/06268f8a-50cb-4952-9030-71c609414e7e)

懒人脚本在yml流程中执行
```
    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        chmod +x $GITHUB_WORKSPACE/scripts/Del-Packages.sh
        $GITHUB_WORKSPACE/scripts/Del-Packages.sh
        
    - name: Update SmartDNS
      run: |
        WORKINGDIR="$GITHUB_WORKSPACE/openwrt/feeds/packages/net/smartdns"
        mkdir $WORKINGDIR -p
        rm $WORKINGDIR/* -fr
        curl -s -L --retry 6 https://github.com/pymumu/openwrt-smartdns/archive/master.zip -o $WORKINGDIR/master.zip
        unzip $WORKINGDIR/master.zip -d $WORKINGDIR
        mv $WORKINGDIR/openwrt-smartdns-master/* $WORKINGDIR/
        rmdir $WORKINGDIR/openwrt-smartdns-master
        rm $WORKINGDIR/master.zip
        LUCIBRANCH="lede"
        WORKINGDIR="$GITHUB_WORKSPACE/openwrt/feeds/luci/applications/luci-app-smartdns"
        mkdir $WORKINGDIR -p
        rm $WORKINGDIR/* -fr
        curl -s -L --retry 6 https://github.com/pymumu/luci-app-smartdns/archive/${LUCIBRANCH}.zip -o $WORKINGDIR/${LUCIBRANCH}.zip
        unzip $WORKINGDIR/${LUCIBRANCH}.zip -d $WORKINGDIR
        mv $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}/* $WORKINGDIR/
        rmdir $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}
        rm $WORKINGDIR/${LUCIBRANCH}.zip
        
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
```

smartdns 版本：
luci-app-smartdns	  1.2023.43-1
luci-i18n-smartdns-zh-cn  1.2023.43-1
smartdns	          1.2023.42-1

openwrt版本：
[Powered by LuCI Master (git-24.019.37088-cdf2b69)](https://github.com/coolsnowwolf/luci) / OpenWrt R24.1.13

**Comment by PikuZheng** [comment]
建议到脚本那边问。
我是这么干的 https://github.com/PikuZheng/smartdns/wiki/%E9%80%9A%E8%BF%87%E4%BD%BF%E7%94%A8%E6%9C%AC%E5%9C%B0%E6%BA%90%E7%9A%84%E6%96%B9%E6%B3%95%E4%B8%BA%E5%B0%86smartdns%E9%9B%86%E6%88%90%E5%88%B0openwrt%E5%9B%BA%E4%BB%B6%E5%86%85

**Comment by PikuZheng** [comment]
> curl -s -L --retry 6 https://github.com/pymumu/openwrt-smartdns/archive/master.zip -o $WORKINGDIR/master.zip
>         unzip $WORKINGDIR/master.zip -d $WORKINGDIR

这是另一个项目啊 它写死了程序版本是1.2023.42 https://github.com/pymumu/openwrt-smartdns/blob/476046c91e100a57f1d88b25ebbd1f32c064b59c/Makefile#L9 所以实际编译出来的 也不知道到底是哪个版本了（只不过版本号是1.2023.42

**Comment by smdx** [comment]
> > curl -s -L --retry 6 https://github.com/pymumu/openwrt-smartdns/archive/master.zip -o $WORKINGDIR/master.zip
> > unzip $WORKINGDIR/master.zip -d $WORKINGDIR
> 
> 这是另一个项目啊 它写死了程序版本是1.2023.42 https://github.com/pymumu/openwrt-smartdns/blob/476046c91e100a57f1d88b25ebbd1f32c064b59c/Makefile#L9 所以实际编译出来的 也不知道到底是哪个版本了（只不过版本号是1.2023.42

看来用错脚本了 :disappointed_relieved:

**Comment by smdx** [comment]
WORKINGDIR="$GITHUB_WORKSPACE/openwrt/feeds/packages/net/smartdns"
        mkdir $WORKINGDIR -p
        rm $WORKINGDIR/* -fr
        curl -s -L --retry 6 https://github.com/pymumu/smartdns/archive/master.zip -o $WORKINGDIR/master.zip
        unzip $WORKINGDIR/master.zip -d $WORKINGDIR
        mv $WORKINGDIR/smartdns-master/* $WORKINGDIR/
        rmdir $WORKINGDIR/smartdns-master
        rm $WORKINGDIR/master.zip
        LUCIBRANCH="lede"
        WORKINGDIR="$GITHUB_WORKSPACE/openwrt/feeds/luci/applications/luci-app-smartdns"
        mkdir $WORKINGDIR -p
        rm $WORKINGDIR/* -fr
        curl -s -L --retry 6 https://github.com/pymumu/luci-app-smartdns/archive/${LUCIBRANCH}.zip -o $WORKINGDIR/${LUCIBRANCH}.zip
        unzip $WORKINGDIR/${LUCIBRANCH}.zip -d $WORKINGDIR
        mv $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}/* $WORKINGDIR/
        rmdir $WORKINGDIR/luci-app-smartdns-${LUCIBRANCH}
        rm $WORKINGDIR/${LUCIBRANCH}.zip
修改后在云编译时出错，在openwrt测试脚本提示
rmdir: '/root/openwrt/feeds/packages/net/smartdns/smartdns-master': Directory not empty
好像有几个隐藏的文件没移动到目标目录
