### ISSUE TITLE
返回ip数量问题  恩山域名

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1644]
开启了域名预读和缓存 并且设置了多个上游dns 并且设置了 返回域名个数25

那么www.right.com.cn 这个域名不同dns 返回ip 不同 那么smartdns会排序返回所有ip

但是  只返回了一个不可用ip

手动测试  
223.5.5.5:853  已经返回正确域名一个
8.8.4.4:853  返回ip 4个其中包含和阿里一样的可用ip

这样应该返回全部ip啊

上游配置删除部分    配置文件如下  不知道是我哪里配置错了吗
大佬帮忙看看  @PikuZheng @pymumu 
`
server-name smartdns
bind [::]:53
serve-expired yes
serve-expired-ttl 2592000
prefetch-domain yes
serve-expired-prefetch-time 21600
dualstack-ip-selection yes
dualstack-ip-selection-threshold 25
max-reply-ip-num 30
cache-size 32768
cache-checkpoint-time 43200
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
force-qtype-SOA 65
rr-ttl-min 600
log-level warn
log-num 1
log-size 64K
mdns-lookup yes
response-mode first-ping
speed-check-mode ping,tcp:443,tcp:80
dnsmasq-lease-file /tmp/dhcp.leases
resolv-file /tmp/resolv.conf.d/resolv.conf.auto

server-tls 8.8.4.4:853 -spki-pin 'dt62L3fioBWsybJVDcZTHdpbcYRplCeuhNoUHHW/xVc=' -subnet 39.148.77.0/24
server-tls 223.5.5.5:853 -spki-pin 'pa14rFR/bBJ25OSjCswaXu6YKWgQ2BDY5jhRRicqeik=' -subnet 39.148.77.0/24

`

手动测试如图
<img width="652" alt="image" src="https://github.com/pymumu/smartdns/assets/7440313/2d28aaa5-23f1-4ea8-987c-510091acf77a">

**Comment by PikuZheng** [comment]
~我先上个厕所~

**Comment by lalasou** [comment]
> ~我先上个厕所~
> 
> 

😂

**Comment by pymumu** [comment]
返回多IP的一个规则是，这些IP的ping速度相差不大，如果差别比较大，那只会返回最快的一个。

你可以ping那几个IP看看。

**Comment by lalasou** [comment]
> 返回多IP的一个规则是，这些IP的ping速度相差不大，如果差别比较大，那只会返回最快的一个。
> 
> 
> 
> 你可以ping那几个IP看看。

哦 原来是这样 
117.149.203.70 33ms  
220.185.184.16 44ms
123.129.227.53 26ms

谢谢大佬
