### ISSUE TITLE
用的最新版为什么配置文件正确 log错误

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1645]
![image](https://github.com/pymumu/smartdns/assets/7440313/760da06e-546d-4806-921b-62b1318bfccd)

如图  这种错误
但是  就像  

server-tls 8.8.4.4:853 -spki-pin 'C/iP7TJjNGrKfiAceyigH86TPtABfgjP4VdUCpVlvoI=' -check-edns -no-check-certificate
这样写也没错啊

**Comment by zxlhhyccc** [comment]
> server-tls 8.8.4.4:853 -spki-pin 'C/iP7TJjNGrKfiAceyigH86TPtABfgjP4VdUCpVlvoI=' -check-edns -no-check-certificate
> 这样写也没错啊

很正常，我以前的配置没问题，同样的配置在最新版本就有问题

**Comment by lalasou** [comment]
> > server-tls 8.8.4.4:853 -spki-pin 'C/iP7TJjNGrKfiAceyigH86TPtABfgjP4VdUCpVlvoI=' -check-edns -no-check-certificate
> 
> > 这样写也没错啊
> 
> 
> 
> 很正常，我以前的配置没问题，同样的配置在最新版本就有问题

我把 上游配置删成这样不报错了  server-tls 8.8.4.4:853 -k
但是 这个提醒  smartdns.log  没出现  系统日志出现了
我smartdns日志是这样设置的啊
log-level warn
弄晕了

**Comment by pymumu** [comment]
你编译的代码不支持“-check-edns”参数，删掉。

**Comment by lalasou** [comment]
> 你编译的代码不支持“-check-edns”参数，删掉。
> 
> 
> 
> 之前代码不支持的参数没有报错，当前代码对不支持的参数报错处理。
> 
> 但那个错误提示，因为musl库的问题，提示可能不太直观。

我说下载的 @PikuZheng 他的openwrt最新版 
😥

我要不要换成你仓库最后那个版本
或者大佬 要不要更新一个稳定版  好久没更新了

**Comment by pymumu** [comment]
还有几个问题等验证。可能年前会发一版。

**Comment by PikuZheng** [comment]
> 
> 我说下载的 @PikuZheng 他的openwrt最新版 
> 😥
> 
> 我要不要换成你仓库最后那个版本
> 或者大佬 要不要更新一个稳定版  好久没更新了

-check-edns 需要带-edns后缀的版本，不过以我观察，这个没什么用

spki那个base64 不加引号试试 我记得配置上是不支持引号的

**Comment by pymumu** [comment]
-check-edns对国外udp服务器使用，可以避免污染。

**Comment by lalasou** [comment]
好的 

@pymumu 坐等更新一版

**Comment by lalasou** [comment]
> 
> > 
> > 我说下载的 @PikuZheng 他的openwrt最新版 
> > 😥
> > 
> > 我要不要换成你仓库最后那个版本
> > 或者大佬 要不要更新一个稳定版  好久没更新了
> 
> -check-edns 需要带-edns后缀的版本，不过以我观察，这个没什么用
> 
> spki那个base64 不加引号试试 我记得配置上是不支持引号的

我试了一下 加不加都行   但是我还是去掉了😅
