### ISSUE TITLE
ImmortalWRT上无法将端口设置为53

### ISSUE THREAD

**Issue by imEgo** [pymumu/smartdns#1646]
**问题现象**  
在ImmortalWRT上无法将端口设置为53，“本地端口”设置为53，勾选“自动设置Dnsmasq”选项，保存应用后日志提示无法绑定53端口，netstat查看53依然被dnsmasq占用。请问如何配置才能替代dnsmasq作为默认DNS

**运行环境**
1. 固件型号  
ImmortalWRT 23.05分支
2. 运营商  
电信
3. smartdns来源以及版本
ImmortalWRT 23.05分支编译
4. 涉及的配置(注意去除个人相关信息)
```
config smartdns
        option server_name 'smartdns'
        option dualstack_ip_selection '1'
        option prefetch_domain '1'
        option serve_expired '1'
        option tcp_server '1'
        option seconddns_tcp_server '0'
        option port '53'
        option ipv6_server '0'
        option seconddns_port '5335'
        option seconddns_server_group 'fq_dns'
        option seconddns_enabled '1'
        option enabled '1'
        option cache_size '20000'
        option rr_ttl '3600'
        option rr_ttl_min '5'
        option auto_set_dnsmasq '1'
        option bind_device '1'
        option cache_persist '1'
        option resolve_local_hostnames '1'
        option force_https_soa '1'
        option old_port '53'
        option old_enabled '1'
        option old_auto_set_dnsmasq '1'

config domain-rule

config server
        option enabled '1'
        option name 'GoogleDNS'
        option ip '8.8.8.8'
        option type 'udp'
        option server_group 'Overseas'
        option port '53'

config server
        option enabled '1'
        option name '114DNS'
        option ip '114.114.114.114'
        option port '53'
        option type 'udp'
        option server_group 'CN'
```

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
为啥不手动把dnsmasq端口改成非53

**Comment by imEgo** [comment]
> 为啥不手动把dnsmasq端口改成非53

额，确实可以，但是看到UI配置里的描述，想知道这个底层是如何实现的，而且这个feature在我这边的确不能正常生效

**Comment by PikuZheng** [comment]
证实该问题存在

**Comment by PikuZheng** [comment]
有点怪啊 在我这不是设置端口问题 而是直接崩溃了
```
Thu Jan 25 17:28:40 2024 kern.info kernel: [ 1653.259810] smartdns[10400]: segfault at 25 ip 00007fc2911e57f4 sp 00007fc2916719c0 error 6 in smartdns[7fc29114e000+353000]
Thu Jan 25 17:28:40 2024 kern.info kernel: [ 1653.264737] Code: 4c ff ff ff 48 8b 45 f8 89 d1 48 8d 15 90 b9 20 00 48 89 c7 b8 00 00 00 00 e8 16 58 1f 00 89 45 ec 8b 45 ec 89 c2 48 8b 45 f0 <66> 89 50 25 48 8d 85 60 ff ff ff be 80 00 00 00 48 89 c7 e8 74 7c
Thu Jan 25 17:28:40 2024 daemon.info procd: Instance smartdns::smartdns s in a crash loop 7 crashes, 5 seconds since last crash
```

**Comment by PikuZheng** [comment]
> > 为啥不手动把dnsmasq端口改成非53
> 
> 额，确实可以，但是看到UI配置里的描述，想知道这个底层是如何实现的，而且这个feature在我这边的确不能正常生效

通过启动脚本实现的 https://github.com/pymumu/smartdns/blob/master/package/openwrt/files/etc/init.d/smartdns

**Comment by imEgo** [comment]
因为我在测试ImmortalWRT在LXC里的稳定性，没有配置lan，我定位了一下问题是```uci  get network.lan.ipaddr```获取为空，导致init.d脚本里hostip为空直接跳过了后续dnsmasq设置，等后续我完整配置下环境再来测试反馈吧

具体脚本代码如下：
```
set_main_dns()
{
	local hostip
	hostip="$(uci -q get network.lan.ipaddr)"
	dnsmasq_port="$(uci -q get dhcp.@dnsmasq[0].port)"
	[ -z "$dnsmasq_port" ] && dnsmasq_port="53"
	
	[ -z "$hostip" ] && return
```

**Comment by imEgo** [comment]
> > > 为啥不手动把dnsmasq端口改成非53
> > 
> > 
> > 额，确实可以，但是看到UI配置里的描述，想知道这个底层是如何实现的，而且这个feature在我这边的确不能正常生效
> 
> 通过启动脚本实现的 https://github.com/pymumu/smartdns/blob/master/package/openwrt/files/etc/init.d/smartdns

感谢，刚才看了下源码找到实现方式了

**Comment by PikuZheng** [comment]
空的问题我考虑过，但是我试了不空也报错

**Comment by pymumu** [comment]
Crash问题看看能不能提供复现方法，提供gdb调用栈

**Comment by snday** [comment]
我的也有这个问题

**Comment by imEgo** [comment]
> 因为我在测试ImmortalWRT在LXC里的稳定性，没有配置lan，我定位了一下问题是`uci get network.lan.ipaddr`获取为空，导致init.d脚本里hostip为空直接跳过了后续dnsmasq设置，等后续我完整配置下环境再来测试反馈吧
> 
> 具体脚本代码如下：
> 
> ```
> set_main_dns()
> {
> 	local hostip
> 	hostip="$(uci -q get network.lan.ipaddr)"
> 	dnsmasq_port="$(uci -q get dhcp.@dnsmasq[0].port)"
> 	[ -z "$dnsmasq_port" ] && dnsmasq_port="53"
> 	
> 	[ -z "$hostip" ] && return
> ```

添加br-lan后，功能测试正常，可以正常替代dnsmasq绑定到53端口

**Comment by PikuZheng** [comment]
> Crash问题看看能不能提供复现方法，提供gdb调用栈

猜测是跨版本更新时持久缓存文件不兼容
