### ISSUE TITLE
请教一些配置的逻辑问题

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#1649]
问题1
如果配置文件里仅一个bind，比如
bind 127.0.0.1:53@lo  -no-dualstack-selection
dualstack-ip-selection yes
那么这样儿的话双栈测速是开还是关？类似的几个别的配置；例如force-aaaa-soa呢？如果有两个bind分组，一个加了no-dualstack-selection一个没加呢？

问题2
当启用了max-reply-ip-num以及dualstack-ip-selection，比如
bind 127.0.0.1:53@lo 
dualstack-ip-selection yes
speed-check-mode tcp:443,tcp:80,ping
max-reply-ip-num 44
因为在开发并且启用max-reply-ip-num之前是只返回一个ip的，无论v4还是v6，那现在max-reply-ip-num 44的话，是返回全部按照速度（排除很慢的）排序的v4和v6吗？如果同时配置了bind 127.0.0.1:53@lo -force-aaaa-soa那还会返回v6地址吗？

**Comment by PikuZheng** [comment]
> 问题1 如果配置文件里仅一个bind，比如 bind 127.0.0.1:53@lo -no-dualstack-selection dualstack-ip-selection yes 那么这样儿的话双栈测速是开还是关？类似的几个别的配置；例如force-aaaa-soa呢？

关，以bind为准

>如果有两个bind分组，一个加了no-dualstack-selection一个没加呢？

一个关一个开，关的口进来的查询关，开的口进来的查询开

> 问题2 当启用了max-reply-ip-num以及dualstack-ip-selection，比如 bind 127.0.0.1:53@lo dualstack-ip-selection yes speed-check-mode tcp:443,tcp:80,ping max-reply-ip-num 44 因为在开发并且启用max-reply-ip-num之前是只返回一个ip的，无论v4还是v6，那现在max-reply-ip-num 44的话，是返回全部按照速度（排除很慢的）排序的v4和v6吗？

不一定（条件不足以推导

>如果同时配置了bind 127.0.0.1:53@lo -force-aaaa-soa那还会返回v6地址吗？

不一定（取决于版本），设计上这样配置应该没有v6结果

**Comment by PikuZheng** [comment]
> 问题2的逻辑我自己试明白了，另外我发现max-reply-ip-num不设置的话，默认值应该是8，文档里

max-reply-ip-num默认8正确，在这里定义的
https://github.com/pymumu/smartdns/blob/04972bd2438322dabe0c8e00f13ff17868326310/src/dns_conf.h#L61

**Comment by PikuZheng** [comment]
> 关了缓存开测速的话max-reply-ip-num不起作用了，开着缓存的话改了参数就算重启服务，查询之前的域名结果也是缓存里的，不会给出按新的参数配置重新查询的结果

正确的，max-reply-ip-num只对缓存起作用（而且这个文档里没写
我是说关持久缓存
