### ISSUE TITLE
Google DOT 返回不同的证书

### ISSUE THREAD

**Issue by Aefer** [pymumu/smartdns#165]
**问题现象**  
`echo | openssl s_client -connect '[ip]:853' | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64`
有时返回
```
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = dns.google
verify return:1
DONE
ByIIIvpYNMvmVtpaBLG2YnYvnqVtjNiDcCGNyplvOLQ=
```
有时返回
```
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = dns.google
verify return:1
DONE
lQXSLnWzUdueQ4+YCezIcLa8L6RPr8Wgeqtxmw1ti+M=
```
导致 smartdns 证书校验错误
**运行环境**
1. 运营商  
各大运营商，包括国外，都测试过
**重现步骤**
1. 上游DNS配置。  
8.8.8.8

**解决方法**
增加多个 SPKI 设置

btw, `Get SKPI with this command` 打错了

**Comment by pymumu** [comment]
DOT没有这样定义的，都是一个IP对应一个SPKI。
并且我测试了我的网络，8.8.8.8， 8.8.4.4都是返回第一个。不会出现不同。

有可能你的网络有劫持

**Comment by Aefer** [comment]
这种情形再次出现，在国外VPS上也试过，已排除劫持。
这次是
’Jp5kpZ2TOwtX2ZO5mGMQV9mNkgyNgl9fJBuraLpcqd4=‘
和
’ISsZ9q4TJg9wg69JMBaNK6qctGo15lJcHxTfLaqsVVk=‘

**Comment by Aefer** [comment]
建议允许指定过期时间，用一点安全性换取便利。

**Comment by pymumu** [comment]
SPKI没用这样的用法，看了google网站，google说明是用证书校验，没有支持用SPKI。
所以当前只能将SPKI校验去掉。
后面版本考虑增加证书CN检查， 可以不用SPKI。
