### ISSUE TITLE
rr-ttl-min对first-ping有影响吗？

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#1650]
如果first-ping是对最快反应的上游结果测速而不等待其余上游立即进行应答，直接将结果发给客户端，那发送的这个结果ttl是多少啊，多久之后会重新请求最终所有上游测速之后最终结果啊？

那比如上述返回地址的ttl应该是5，如果在设置了rr-ttl-min=600，会是啥结果呢？是600之后重新请求还是5秒啊？

**Comment by PikuZheng** [comment]
rr-ttl-min=600会导致缓存ttl=600。
我记得它只对缓存起作用，不确定

**Comment by PikuZheng** [comment]
不应该私自改ttl啊 ttl应该由域名所有者自主决定。
但是，假设一个dns服务器拿到某个域名的ttl=600并缓存，那么在10秒后应该从缓存取结果并给下游应答ttl=590。
