### ISSUE TITLE
双栈域名的解析结果只返回IPV4地址，其他情况正常返回

### ISSUE THREAD

**Issue by jklolixxs** [pymumu/smartdns#1654]
# **需求应用场景**
### 目前ipv4路由在很多时候，要优于ipv6的路由，并且如果设备启用ipv6，检测到访问目标支持ipv6，则会直接使用ipv6通讯而放弃ipv4，在这种情况下，则会劣化网络体验

# **建议的方案**
#### 2. 对于纯ipv4或者纯ipv6域名，不做处理，返回对应的IP地址  
> 这是我目前能想到的最好的解决方法了

# **设备信息**
## 1. 设备信息（CPU，厂家）  
 - 只要支持smartdns就行

## 2. 固件信息
 - 只要支持smartdns就行

**Comment by wood6s** [comment]
有解决方案了吗，我也十分需要这个功能
