### ISSUE TITLE
cache-checkpoint-time是不是设定了最小时间？

### ISSUE THREAD

**Issue by BlueDolphin9527** [pymumu/smartdns#1656]
**问题现象**  
smartdns的cache-checkpoint-time设置为1200，也就是每20分钟保存一次，但实测是失效的，并不会定时保存。而设置21600，即每6小时保存一次就生效了。所以就怀疑您是不是设定了最小的保存时间？低于这个时间，这行配置就失效了。

**运行环境**
1. 固件型号  
Intel(R) Celeron(R) N4500 @ 1.10GHz x86/64

2. 运营商  
安徽阜阳移动

3. smartdns来源以及版本
realease 1.2023.v43.0.97

**Comment by PikuZheng** [comment]
默认值是1天
https://github.com/pymumu/smartdns/blob/af3435138ff32d0590d58088071c32675bebad5d/src/dns_conf.h#L63
最小值是2分钟
https://github.com/pymumu/smartdns/blob/af3435138ff32d0590d58088071c32675bebad5d/src/dns_server.c#L8372
但如果此时cache正在被读写，就会跳过
https://github.com/pymumu/smartdns/blob/af3435138ff32d0590d58088071c32675bebad5d/src/dns_server.c#L8380

**Comment by BlueDolphin9527** [comment]
好的，谢谢解答。
