### ISSUE TITLE
DOT服务端突然不能用了

### ISSUE THREAD

**Issue by LQY0606** [pymumu/smartdns#1658]
**问题现象**  
简要描述问题出现的现象
       在OpenWrt路由器上使用，用的单ipv6公网ddns做的dot和doh服务端，用了半个月一直正常。
       今天在安卓手机上，数据网络下私人DNS突然就就不能用了，但连着路由器WIFI可以使用，连别人热点也不能用。但doh正常使用。
        853端口也是通的，把OpenWrt后台放在853端口也能正常访问。
        请问大佬可能是什么原因引起的？
**运行环境**
1. 固件型号  
openwrt
2. 运营商  

3. smartdns来源以及版本
43.0.99
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
盲猜853被运营商封了

**Comment by LQY0606** [comment]
> ~盲猜853被运营商封了~ 先看一下设置里的端口绑定或ip绑定吧

[smartdns.txt](https://github.com/pymumu/smartdns/files/14159699/smartdns.txt)
这是我的配置文件，应该没问题啊，在手机上用软件连接doh服务端是正常的。
![Screenshot_20240205_101629_app intra](https://github.com/pymumu/smartdns/assets/91514324/ddc70156-3dd4-4e93-b663-b08ddd6cf7f2)

**Comment by LQY0606** [comment]
> 测了下是通的 你说不好用的时候 有一端是移动吗 ![Screenshot_20240205_125833_org.toremote.rdpdemo.jpg](https://private-user-images.githubusercontent.com/12579522/302179832-1021544d-5ea0-4324-95a9-5da9f003b8ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTEyNTIsIm5iZiI6MTcwNzExMDk1MiwicGF0aCI6Ii8xMjU3OTUyMi8zMDIxNzk4MzItMTAyMTU0NGQtNWVhMC00MzI0LTk1YTktNWRhOWYwMDNiOGFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA1MjkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNGEzZjU1YTY5ODBlMTdhZWE0ODQzNTk1NWY2YmIyYmIxNzc5MzkxNTFmNTQzMmI5YTZmZDFmMzMwNzRiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-LSjeZ7QxO1u7mOp3Jp7wKgmgA8k6EG_dUzZRC3G84)

是的，手机用数据网，在设置里打开私人DNS用dot就不能上网，连着路由器WiFi就正常。但是用软件用doh在数据网还是WiFi都是正常的。
这种情况这两天才出现，之前十几天是正常的，就很迷惑。

**Comment by LQY0606** [comment]
> 测了下是通的 你说不好用的时候 有一端是移动吗 ![Screenshot_20240205_125833_org.toremote.rdpdemo.jpg](https://private-user-images.githubusercontent.com/12579522/302179832-1021544d-5ea0-4324-95a9-5da9f003b8ac.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTE3NjAsIm5iZiI6MTcwNzExMTQ2MCwicGF0aCI6Ii8xMjU3OTUyMi8zMDIxNzk4MzItMTAyMTU0NGQtNWVhMC00MzI0LTk1YTktNWRhOWYwMDNiOGFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA1Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTEyYzRiZWJkOWU5MDRjN2RmMmVjOGUxMzFmMzYyMGQ2ZTZiMjcxYTE2YTQwYTM0NTdkNDFmZjg4YTVlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aLe57L6KQZ7Fhnm1hBQO24AAVvitPlTV1zrNtKoCJU)

![Screenshot_20240205_133733_com android settings](https://github.com/pymumu/smartdns/assets/91514324/15527cdf-76c5-4a6e-a9ad-bf644d1ccb47)
![Screenshot_20240205_133713_com android settings](https://github.com/pymumu/smartdns/assets/91514324/a8d43d53-4569-401a-b22a-414f331a0573)
一个数据网不正常，一个连路由器WiFi就正常。
但连别人热点也不能用。

**Comment by PikuZheng** [comment]
换成联通卡试试

**Comment by LQY0606** [comment]
> ~换成联通卡试试~ ~试了移动或联通卡都不行~ 试了我这移动或联通都行，但是移动会慢一些，联通表现相对正常。用的华为p40pro（鸿蒙4.0），双卡纯4G。 应该是运营商的锅，你试试看是不是ipv6有问题

我也是鸿蒙4.0，不过我是电信卡，路由宽带是移动的。手机卡ipv6没问题，宽带只有ipv6公网，手机用4G访问openwrt后台是通的，同一个域名。doh也是通的，只有dot不通。太奇怪了，前几天还好好的。

**Comment by PikuZheng** [comment]
反复试了几次，应该是对vivi6这个域名自身的解析问题。
1. 开WiFi，开加密dns，一切正常。此时开数据，关WiFi，也是正常的（安卓对vivi6自身的ip有缓存
2. 此时关加密dns，关流量，开关几次WiFi（清dns缓存），开加密dns，开流量，此时不正常，提示无法访问私人dns
3. 多等了一会儿啥也没动（三五分钟？）又正常了

**Comment by LQY0606** [comment]
> 反复试了几次，应该是对vivi6这个域名自身的解析问题。
> 
>     1. 开WiFi，开加密dns，一切正常。此时开数据，关WiFi，也是正常的（安卓对vivi6自身的ip有缓存
> 
>     2. 此时关加密dns，关流量，开关几次WiFi（清dns缓存），开加密dns，开流量，此时不正常，提示无法访问私人dns
> 
>     3. 多等了一会儿啥也没动（三五分钟？）又正常了

果然是域名解析的问题，花五块钱弄翻了一个腾讯的域名，正常了。
感谢大佬！
