### ISSUE TITLE
新版本 使用ip-alias CDN IP加速 同时设置ipv6 ipv4 但是只返回v4 

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1667]
新版本 使用ip-alias CDN IP加速 同时设置ipv6 ipv4 但是只返回v4 
我看了下 不应该啊
是不是设置ip-alias  还会测速？  能不能设置ip-alias 不再测速直接返回设置的v4 和v6

**Comment by PikuZheng** [comment]
分开设置v4v6呢 按理说v4只能alias v4，v6只能alias v6

**Comment by lalasou** [comment]
> 分开设置v4v6呢 按理说v4只能alias v4，v6只能alias v6



按照示例文档设置的，经过一个minittl + 3 成功返回

之前的缓存没删
![image](https://github.com/pymumu/smartdns/assets/7440313/24e238e2-8d24-4ece-a3b1-0b6a3ff41085)
