### ISSUE TITLE
多ip监听问题

### ISSUE THREAD

**Issue by PikuZheng** [pymumu/smartdns#167]
**问题现象**  
当一个端口绑定多个ipv4的情况下，只有主ip才返回查询结果，额外ip查询超时

root@OpenWrt:~# ip add
1: lo……
4: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 00:23:45:67:89:ab brd ff:ff:ff:ff:ff:ff
    inet 172.17.2.101/24 brd 172.17.2.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet 172.17.2.100/24 scope global secondary br-lan
       valid_lft forever preferred_lft forever
……

C:\Users\Admin>nslookup www.google.com 172.17.2.100
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  172.17.2.100
DNS request timed out.
    timeout was 2 seconds.
^C
C:\Users\Admin>nslookup www.google.com 172.17.2.102
服务器:  smartdns
Address:  172.17.2.102
非权威应答:
名称:    www.google.com
Address:  216.58.197.100

**运行环境**
1. 固件型号 
OpenWrt 18.06.2 r7676-cddd7b4c77
smartdns	1.2019.05.21-2250
2. 运营商  
无关

**重现步骤**
1. 上游DNS配置。  
无关
2. 访问的域名。  
无关

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
----此文件不存在
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
----进程正常

**Comment by pymumu** [comment]
现在只能选择绑定全局还是特定IP。

如果想所有IP地址都能请求，那配置 bind :53

**Comment by PikuZheng** [comment]
> 现在只能选择绑定全局还是特定IP。
> 
> 如果想所有IP地址都能请求，那配置 bind :53

如果配置bind :53那么额外ip查询超时（重启smartdns无效）。
如果配置bind ip:53则进程在ip不存在时崩溃。
hmmm可能是因为这个额外ip是在smartdns启动后通过vrrp动态产生的

**Comment by pymumu** [comment]
全局绑定就对了，新增的IP也应该可以查询的。除非有iptable限制了
:53

**Comment by PikuZheng** [comment]
没有启用iptables，从netstat看监听确实是0.0.0.0:53。但实际使用上就是不应答。
重定向选“无”或“重定向53端口到SmartDNS”，无改善。

现在变通方法是启用Dnsmasq，重定向选“作为dnsmasq的上游服务器”。但实际使用上延迟明显增加了。。

**Comment by pymumu** [comment]
绑定全局，新加IP重启后能不能生效？

[::]:53

**Comment by PikuZheng** [comment]
重启smartdns服务后查询仍无应答（DNS request timed out.）。不过端口是通的（telnet 172.17.2.100 53）

**Comment by pymumu** [comment]
可能还是路由规则限制了，全局绑定的话，新增IP也是没有问题的。

**Comment by PikuZheng** [comment]
问题应该出在单接口配置了同网段多个ip上。发送请求到 secondary ip 应该是没问题的，但smartdns向上级查询后返回可能是从primary ip 出去的，导致客户端觉得来源不同，丢弃了。
