### ISSUE TITLE
Handshake with 223.5.5.5 failed, Connection reset by peer

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1673]
Handshake with 223.5.5.5 failed, Connection reset by peer
很多这种错误
如下图

![image](https://github.com/pymumu/smartdns/assets/7440313/52ec0aee-6177-4bb9-aa1a-9ca7b42463b7)

**Comment by lalasou** [comment]
server-tls 223.5.5.5:853 -k
上游这样配置  和证书没关系了吧

**Comment by PikuZheng** [comment]
rst是中间有防火墙拦截了 先测一下路由表吧？

**Comment by lalasou** [comment]
> rst是中间有防火墙拦截了 先测一下路由表吧？

路由器 桥接
防火墙  全接受 （和关了差不多吧）
![image](https://github.com/pymumu/smartdns/assets/7440313/fcd3d8f3-593d-4628-86a2-6dca3385a996)

**Comment by PikuZheng** [comment]
用移动宽带大致测了一下，每一次路由都不同，感觉是移动抽风
另外请求量过大时阿里会黑名单（移动这种共用ip出口的，会累积所有共用用户的使用量

**Comment by lalasou** [comment]
> 用移动宽带大致测了一下，每一次路由都不同，感觉是移动抽风
> 另外请求量过大时阿里会黑名单（移动这种共用ip出口的，会累积所有共用用户的使用量

好吧 就这样先用着吧

**Comment by lalasou** [comment]
so   去掉subnet  edns-client-subnet 即可
