### ISSUE TITLE
[请教] 关于IPv6上游服务器的添加

### ISSUE THREAD

**Issue by QYG2297248353** [pymumu/smartdns#1675]
我想知道IPV6的DNS如何添加
![image](https://github.com/pymumu/smartdns/assets/56836951/d87cffd0-3d0e-4635-98ca-08b3e7702667)

Google Public DNC
2001:4860:4860:8888
Google Public DNC
2001:4860:4860:8844
Cloudflare Public DNS
2606:4700:4700:1111
Cloudflare Public DNS
2606:4700:4700:1001
以及国内的
IPv6公共DNS
240c::6666
IPv6公共DNS
240c::6644

以上启用任何一个都会出现启动失败

**Comment by PikuZheng** [comment]
就我所知这是2023年1月版本的一个bug。楼主确定用的是最新版，且luci版本与主程序版本匹配？

**Comment by QYG2297248353** [comment]
> 就我所知这是2023年1月版本的一个bug。楼主确定用的是最新版，且luci版本与主程序版本匹配？

安装的版本

软件包名称 | 版本 | 大小（.ipk） | 描述
-- | -- | -- | --
luci-app-smartdns | git-24.332.56186-e54339b | ~15.25 KiB | Provides Luci for smartdns
luci-i18n-smartdns-zh-cn | git-24.021.51964-7947f2b | ~5.52 KiB | Translation for luci-app-smartdns - 简体中文 (Chinese Simplified)

![image](https://github.com/pymumu/smartdns/assets/56836951/1158093c-8317-478d-a8ac-055153dec0f0)

OpenWrt版本
![image](https://github.com/pymumu/smartdns/assets/56836951/a4dcb7e0-b9bd-452a-9574-380bd3ee5f8b)

开启Google IPv6 DNS 异常日志
![image](https://github.com/pymumu/smartdns/assets/56836951/6f1a0334-2fb4-4ae5-9972-356bc2f80d79)

**Comment by PikuZheng** [comment]
smartdns版本呢？
看日志是设备自身没有ipv6

**Comment by QYG2297248353** [comment]
> ip地址格式写错了，少：
> 
> 2001:4860:4860::8844

谢谢，确实是，是之前的文章写错了，复制错了，在官网找到正确的地址替换正常了
