### ISSUE TITLE
可能是一个bug

### ISSUE THREAD

**Issue by bboysoulcn** [pymumu/smartdns#1676]
**问题现象**  
当我开启了持久化缓存
然后进行一次dns查询比如nslookup www.example.com,之后发现这个域名没有任何解析记录，于是我去添加自定义解析，比如

cname /www.example.com/www.baidu.com

之后重启服务器，之后nslookup www.example.com 会发现服务器继续返回没有任何解析记录，只有先关闭smartdns然后删除缓存文件，然后启动这一条解析才可以生效

**运行环境**

3. smartdns来源以及版本

最新版本

**Comment by PikuZheng** [comment]
是这样的，缓存的是a记录，要缓存过期了cname才能生效
