### ISSUE TITLE
log大小由哪个配置文件文件生效？

### ISSUE THREAD

**Issue by Anyfc** [pymumu/smartdns#168]
**问题现象**  
/var/log/smartdns.log 文件不受控制一直在增大

**运行环境**
1. OpenWrt   

2. 运营商  

**重现步骤**
1. 
/var/etc/smartdns/smartdns.conf 内容：
![Snipaste_2019-06-10_23-59-06](https://user-images.githubusercontent.com/9066926/59208509-c9b9b380-8bdb-11e9-9d24-6880111de7e4.png)

luci自定义配置：
![Snipaste_2019-06-10_23-59-39](https://user-images.githubusercontent.com/9066926/59208548-d8a06600-8bdb-11e9-88bf-e3405d0d4667.png)

log体积已经远远超过了上面两个的设置大小
![Snipaste_2019-06-10_23-53-29](https://user-images.githubusercontent.com/9066926/59208188-2d8fac80-8bdb-11e9-907d-9a42437131ae.png)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
会使用最后出现的配置。排在前面的配置会被后面的配置覆盖。
看看你conf-file指定的配置文件中有没有日志配置。

**Comment by Anyfc** [comment]
@pymumu conf-file指定的配置文件中是有日志配置，但都是128K，不过刚刚去看了下，日志大小又正常了，另外，发现
1、luci下有时候无法关闭smartdns，要手动kill进程才可以
2、有时候修改了配置，重启smartdns，进程是起来了，但DNS解析没有起作用，要重启路由器才行。
这两个问题怎么排查？

**Comment by pymumu** [comment]
你用的什么固件？koolshare 的LEDE？

**Comment by Anyfc** [comment]
@pymumu lean源码编译的OpenWrt

**Comment by pymumu** [comment]
怀疑你的固件里面已经包含了smartdns，但配置，启动方法不同，可以排查下
