### ISSUE TITLE
domain-set 域名集合支持一条指令一个名称定义多个域名集合文件路径(可以用,来分割)

### ISSUE THREAD

**Issue by lxf1992521** [pymumu/smartdns#1680]
**需求应用场景**
有多个来自不同源的 ad 文件域名列表，我都想定义到 ad domain-set 中，方便后续统一处理。

但是现在 domain-set 只支持一次定义一个文件，当有多个同类型的集合文件时，需要定义多次且生成多个 domain-set 名称，不是很方便。

当然也有人认为可以将多个同类型的集合文件合并，生成一个文件，这也是一种思路，但是会增加额外的工作。

**建议的方案**
domain-set 支持一次定义多个同类型的集合文件，例如下面这种形式：
`domain-set -name ad -file /etc/smartdns/ad-1.txt,/etc/smartdns/ad-2.txt`

或者通过增加一个 domain-set 的 type 类型：lists
`domain-set -name ad -type lists -file /etc/smartdns/ad-1.txt,/etc/smartdns/ad-2.txt`

个人倾向于第一种，比较方便，但第二种更加规范。

**设备信息**
无

**Comment by PikuZheng** [comment]
？domain-set可以多个文件指向同一个集合名称啊

**Comment by PikuZheng** [comment]
参考 #1598

**Comment by lxf1992521** [comment]
测试了下，确认是叠加生效！赞

可否更新下官网文档，找了一圈没有发现网站上对 domain-set 叠加的说明。

**Comment by PikuZheng** [comment]
> @lxf1992521 有什么好用的规则分享下😊 误杀高不

推荐这个 https://github.com/neodevpro/neodevhost

**Comment by lalasou** [comment]
> > @lxf1992521 有什么好用的规则分享下😊 误杀高不
> 
> 
> 
> 推荐这个 https://github.com/neodevpro/neodevhost

好的 我试试
一直用客户端adb p
怕误杀🥲
