### ISSUE TITLE
保存测速失败的域名到文件

### ISSUE THREAD

**Issue by giveup** [pymumu/smartdns#1682]
**需求应用场景**
目前是clash+smartdns组合，smartdns监听两个端口，分别对应国内国外，clash采用黑名单模式（即在某个列表的域名才会发给国外dns查询且该域名才会使用代理），需要手工维护具体哪些域名无法连通。如果smartdns能输出测速失败的域名到文件，就可以比较自动化处理这个过程，同时建议提供阈值选项，该域名对应的IP连续多次测速失败才会保存到文件。

**建议的方案**
实现上述场景建议的方案。
无

**设备信息**
1. 设备信息（CPU，厂家） 
任意 

3. 固件信息
无

**Comment by PikuZheng** [comment]
重复#1143
没记错的话在v40.0.16就有这个功能了

**Comment by PikuZheng** [comment]
但是这个阀值问题，做阀值势必增加统计功能，增加程序大小和延迟。
所有测速失败都写入文件的话，又不好区分是真正失败还是封单个端口的。

增加自主统计域名的比较好的方法是，由包过滤防火墙（或终端应用）将打开网页时收到tcp rst的域名加入列表。但这会使首次连接失败，必须刷新一下网页（也比等配置文件重载的好
