### ISSUE TITLE
建议speed-check-mode中增加http ping模式

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#1684]
**需求应用场景**
科学上网情况下 tcp检测模式响应值来自vps节点而不是出口网关本身，因此检测值不正确 http 检测才能得到出口网关对于解析结果IP的真实响应

**建议的方案**
可以参考https://github.com/fever-ch/http-ping/tree/v1.2.4 或者 https://github.com/folkertvanheusden/httping 增加http ping类似的功能 得到解析结果的响应值

**Comment by openips** [comment]
其实http测试才更加准确

**Comment by dawxy** [comment]
这种情况是不是建议直接在vps安装 smartdns 来测速，我理解你本地解析出来的dns不一定会被vps使用的（一版配置下代理转发时会再做一次dns解析的）

**Comment by ruinstoriel** [comment]
同需求，本地的tcp 测速会被代理，syn 瞬间返回，测不准。vps 不接受域名，只接收ip。ping 又无法被代理。只能关闭测速了。不过确实有这个需求。
