### ISSUE TITLE
conf-file 支持多参数吗

### ISSUE THREAD

**Issue by soffchen** [pymumu/smartdns#169]
如果支持，是
```
conf-file /etc/smartdns/a.conf
conf-file /etc/smartdns/b.conf
```
还是
```conf-file /etc/smartdns/a.conf /etc/smartdns/b.conf```

这样可以更好分拆配置，比如一个 hosts.conf 用来处理 /etc/hosts，一个 dnsmasq-chia-list.conf 用来指定国内域名到国内 nameservers 组

**Comment by pymumu** [comment]
多行的那个

**Comment by soffchen** [comment]
> 多行的那个

谢谢，这就好办了
