### ISSUE TITLE
老是崩溃

### ISSUE THREAD

**Issue by Xymmh** [pymumu/smartdns#1691]
**问题现象**  
当打开新网页较为频繁时，DNS服务老是崩溃，导致无法打开网页，除非重启smartdns服务。

每次崩溃时Openwrt系统日志里显示：
Fri Mar  1 23:21:46 2024 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 7 crashes, 1522 seconds since last crash

同时可能伴有
Fri Mar  1 23:05:57 2024 kern.info kernel: [990016.737899] TCP: request_sock_TCPv6: Possible SYN flooding on port 53. Sending cookies.  Check SNMP counters.
这样的提示

已尝试将Openwrt防火墙设置内的SYN flood防御关闭，仍然会出现此问题

**运行环境**
1. 固件型号  
ImmortalWrt 23.05.1 r27304-31bc47589e / LuCI openwrt-23.05 branch git-23.313.50115-e3df634
2. 运营商  
校园网
3. smartdns来源以及版本
Github上下载的Release 45 smartdns-x86_64

**重现步骤**
随机出现在打开新网页的情况下，推测是解析任务比较重的情况下

**Comment by pymumu** [comment]
你这是dnsmasq crash不是smartdns问题。

你可以将smartdns设置为主dns看看。或者升级dnsmasq。

**Comment by Xymmh** [comment]
有道理，已经升级了几个可能导致dnsmasq崩溃的软件，我再观察一下看看

**Comment by Xymmh** [comment]
果然是dnsmasq的问题
