### ISSUE TITLE
编译失败了，求助下

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#1694]
- name: Checkout code
        uses: actions/checkout@main
        with:
          repository: pymumu/smartdns
          ref: master
          submodules: recursive

      - name: x86_64
        if: matrix.arch != 'aarch64_cortex-a53' && matrix.arch != 'mipsel_24kc'
        run: |
          chmod +x package/build-pkg.sh
          ./package/build-pkg.sh --platform linux --arch ${{ matrix.arch }} --outputdir bin/packages/${{ matrix.arch }}/packages_ci/

      - name: Makefile
        if: matrix.arch != 'x86_64'
        run: |
          $SHA_smartdns = (curl -sSL https://api.github.com/repos/pymumu/smartdns/commits/master | jq -r '.sha')
          echo "SHA_smartdns=$SHA_smartdns" >> $env:GITHUB_ENV
          mv package/openwrt openwrt-smartdns
          cd openwrt-smartdns
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$(date +\"1.%Y.%m.%d-%H%M\")/" Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$SHA_smartdns/" Makefile
          
      - name:  openwrt
        if: matrix.arch != 'x86_64'
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-openwrt-${{ matrix.arch == 'aarch64_cortex-a53' && '22.03' || (matrix.arch == 'mipsel_24kc' && '23.05') }}
          FEEDNAME: packages_ci
          PACKAGES: openwrt-smartdns
          NO_REFRESH_CHECK: true

log没啥有用的，仨平台都失败了，大佬瞅瞅哪里错了…

**Comment by PikuZheng** [comment]
最近两次我用的git action也编译失败，还没研究原因。猜测是openwrt的交叉编译工具有变动
