### ISSUE TITLE
路由器潘多拉固件如何检测转发服务是否配置成功？

### ISSUE THREAD

**Issue by adaaaaaa** [pymumu/smartdns#17]
nslookup -querytype=ptr 127.0.0.1
这个命令查询不了。。。
代码：
[root@PandoraBox_7D29:/root]#nslookup -querytype=ptr 127.0.0.1
BusyBox v1.24.1 (2018-07-27 11:01:34 UTC) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server

**Comment by pymumu** [comment]
windows nslookup命令下检测。不要再路由器内部检测。
