### ISSUE TITLE
编译需求

### ISSUE THREAD

**Issue by zhangxiaoliangzxl** [pymumu/smartdns#170]
**设备信息**
1. PHICOMM K3 
目前编译的openwrt1806的arm包都无法运行
smartdns.1.2019.05.21-2250.arm.ipk解压执行文件--help可以输出， 但无法在openwrt1806下正常运行

2. 固件信息
openwrt1806

**Comment by pymumu** [comment]
报什么错误？启动一下进程看看吧
smartdns -f -v
参数。

**Comment by zhangxiaoliangzxl** [comment]
> 报什么错误？启动一下进程看看吧
> smartdns -f -v
> 参数。

/usr/sbin/smartdns: can't resolve symbol 'SSL_load_error_strings'
[2019-06-14 09:10:17,496][NOTICE][       smartdns.c:244 ] smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build:Apr 25 2019 21:42:12)

另外查看本地端口并没有监听

**Comment by pymumu** [comment]
你系统中缺少openssl 1.0.x的库，要安装一下。

**Comment by m73Tu** [comment]
希望尽快更新到libopenssl1.1，snapshot版本中ipk基本都迁移至1.1，无法安装1.0.2版本

**Comment by zhangxiaoliangzxl** [comment]
> 你系统中缺少openssl 1.0.x的库，要安装一下。

看了下代码，是openssl版本问题，openwrt1806用的1.1.1, 有些api废弃了，希望编个openssl1.1.1的，因为其它软件有依赖

**Comment by pymumu** [comment]
看了1806正式release版本依然是openssl1.0.2版本。
除非是snapshot版本。

smartdns支持正式的release版本，openwrt 19年的版本出来的话，就会配套。

最近会出一个特别版本，会将c库，ssl库静态编译。
