### ISSUE TITLE
从系统读取ip以配置edns

### ISSUE THREAD

**Issue by giveup** [pymumu/smartdns#1702]
**需求应用场景**
对于有动态IP的用户，每次拨号后IP会发生变化。
按我的理解，IP变化后，归属地不变，不会对CDN有太多影响，但实际测试下来，偶尔会出现CDN返回的IP慢。（这其实是上游dns的锅），希望可以优化为动态获取当前的IP并作为edns去优化。

**建议的方案**
动态获取系统IP作为edns

**设备信息**
1. 设备信息（CPU，厂家）  
无
2. 固件信息
无

**Comment by pymumu** [comment]
edns是服务端用的，这个一般都不用配

**Comment by PikuZheng** [comment]
你说的场景无需指定edns，除非你在用匿名代理
