### ISSUE TITLE
推荐去广告规则AWAvenue-Ads-Rule 但是没有smartdns版本

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1704]
推荐去广告规则
https://github.com/TG-Twilight/AWAvenue-Ads-Rule

**Comment by zxlhhyccc** [comment]
使用sed命令转换一下适配smartdns格式就可以了

**Comment by lalasou** [comment]
谢谢 好的 我试试

**Comment by lalasou** [comment]
sed -i '1,20d;s/^127\.0\.0\.1\s\+\(.*\)/address \/\1\/#/g' AWAvenue-Ads-Rule-hosts.txt

下载AWAvenue-Ads-Rule-hosts.txt操作更方便些

**Comment by lalasou** [comment]
'curl -sL -o ad.txt https://ghproxy.net/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt && sed -i '1,20d;s/^127\.0\.0\.1\s\+\(.*\)/address \/\1\/#/g' ad.txt'

**Comment by lalasou** [comment]
```
curl -sL -o ad.txt https://ghproxy.net/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt && sed -i '1,20d;s/^127\.0\.0\.1\s\+\(.*\)/address \/\1\/#/g' ad.txt
```

**Comment by PikuZheng** [comment]
我看它提供纯域名格式啊 没法直接抛给domain-set用吗 https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/main/Filters/AWAvenue-Ads-Rule-AdClose.txt

**Comment by lalasou** [comment]
> 我看它提供纯域名格式啊 没法直接抛给domain-set用吗 https://github.com/TG-Twilight/AWAvenue-Ads-Rule/blob/main/Filters/AWAvenue-Ads-Rule-AdClose.txt

不清楚 评价挺好的  刚试用
用 AWAvenue-Ads-Rule-hosts.txt 改了下

**Comment by PikuZheng** [comment]
它这个只有500多行啊 真的行吗 用了几天感觉不灵啊

**Comment by lalasou** [comment]
> 它这个只有500多行啊 真的行吗 用了几天感觉不灵啊

好吧 看介绍 对手机端貌似更合适

我加载几个呢  也不知道到底哪个起作用了
