### ISSUE TITLE
荒野无灯padavan 内置的smart 1.03问题

### ISSUE THREAD

**Issue by ntgeralt** [pymumu/smartdns#171]
你好，我使用环境是广东移动光纤，发现
荒野无灯padavan 内置的smartdns 1.03

208.67.222.222:443,    203.80.96.10 
这两个dns 不仅tcp还是udp特殊端口，似乎已完全无法正常解析google。
我不知道是设置、旧版本问题，还是dns ip 被劫持，这里反馈下

**Comment by pymumu** [comment]
不是一个东西，功能完全不同，名字相同而已。
