### ISSUE TITLE
域名规则求助

### ISSUE THREAD

**Issue by rcyggdra** [pymumu/smartdns#1714]
1. 设备信息（CPU，厂家）  
Xiaomi Mi Router 3G
ramips/mt7621

2. 固件信息
OpenWrt 23.05.3

我使用通配符不能返回指定地址，如下：
```
address /-.hitomi.la/88.80.31.197
address /*.hitomi.la/23.237.54.194
``` 

只能通过这种形式返回地址
```
address /hitomi.la/88.80.31.197
address /atn.hitomi.la/23.237.54.194
address /btn.hitomi.la/23.237.54.194
address /ltn.hitomi.la/23.237.54.194
address /aa.hitomi.la/23.237.54.194
address /ba.hitomi.la/23.237.54.194
```

下面规则也是同样问题
```
address /*s.sankakucomplex.com/208.100.24.254
address /*v.sankakucomplex.com/143.244.49.183
``` 
写成下面那样才行……
```
address /s.sankakucomplex.com/208.100.24.254
address /is.sankakucomplex.com/208.100.24.254
address /v.sankakucomplex.com/143.244.49.183
address /iv.sankakucomplex.com/143.244.49.183
```
其他域名用通配符也无法返回指定地址……
是我写错还是其他问题？

**Comment by PikuZheng** [comment]
配置文档指导应该 `address /-.hitomi.la/88.80.31.197` ，测试实际需要 `address /-hitomi.la/88.80.31.197` 才生效 @pymumu

**Comment by rcyggdra** [comment]
![PixPin_2024-03-30_13-13-30](https://github.com/pymumu/smartdns/assets/8652464/a754250e-a4b9-41de-a316-dd07aad9429b)
结果不理想，暂时只能像hosts那样一个域名一行了。

**Comment by PikuZheng** [comment]
> 结果不理想，暂时只能像hosts那样一个域名一行了。

您这什么版本，通配符需要v43.0.20或更高

**Comment by rcyggdra** [comment]
> 您这什么版本，通配符需要v43.0.20或更高
你这么一说，我是在软件包直接下载的……
smartdns	1.2023.42-1
没想到官方源不是最新版……

**Comment by rcyggdra** [comment]
更新到smartdns 1.2024.02.08-0828
问题解决，多谢解答。

**Comment by pymumu** [comment]
目前这种写法不支持，看看后面怎么优化。
