### ISSUE TITLE
关于ip-alias，指定了cf v4映射，但是想屏蔽cf v6，请问有办法吗

### ISSUE THREAD

**Issue by j4Uq** [pymumu/smartdns#1715]
ip-set -name cloudflare-ipv4 -file /etc/smartdns/ip-set/cloudflare-ipv4.txt
ip-rules ip-set:cloudflare-ipv4 -ip-alias *.*.*.*

**Comment by PikuZheng** [comment]
也优选一个ip呗 我用了一段时间觉得还行
或者把ipv6段加到ignore-ip

**Comment by lalasou** [comment]
cf v6 也是绝配啊 干嘛屏蔽啊   找到好的v6地址香得很，  v2eX  还有好些网站  免翻 多好啊
