### ISSUE TITLE
APT仓库内的软件版本已过时

### ISSUE THREAD

**Issue by TioaChan** [pymumu/smartdns#1725]
**问题现象**  
执行`smartdns -v`查看版本为
```
# smartdns -v
smartdns 35+dfsg-1
```

实际上从Release中下载到的版本为
```
smartdns -v
smartdns 1.2024.02.08-0828 (Release43-141-g9ee27e7)
```

**运行环境**
Ubuntu 22.04.4 LTS

我说看了一天文档为什么`客户端规则`不起作用

**Comment by wzssyqa** [comment]
这是发行版的规则。发布了之后，只进行重要功能和安全修复。一般不会升级大版本。

**Comment by pymumu** [comment]
ubuntu的不知道谁在维护

**Comment by TioaChan** [comment]
了解了 感谢回复
