### ISSUE TITLE
双栈优选能否强制指定IPv6

### ISSUE THREAD

**Issue by moremorefaito** [pymumu/smartdns#1728]
**需求应用场景**
IPv4和IPv6运营商不同，对于绝大多数境外网站，IPv6的QoS好很多。
由于我所在网络环境的特殊性，对于如 docs.ray.io, www.rabbitmq.com 等大量合法境外网站，IPv4 QoS严重（时延可能更短但速率非常低），IPv6则可以秒开。需求：对于同时有IPv6(AAAA)和IPv4(A)记录的域名，优先/只返回IPv6(AAAA)记录，以供Firefox连接。对于只有IPv4(A)记录域名，则返回IPv4(A)记录。

**建议的方案**
目前关闭双栈优选时，似乎会停止返回IPv6结果。
设置了 `dualstack-ip-allow-force-AAAA yes` 后看到Firefox的解析记录 (`about:networking#dns`) 仍然为IPv4/IPv6混搭。
通过某种字段，提供只选用IPv6的选项。
若已有相关设置字段，烦请原谅并指出。谢谢！

**设备信息**
此建议与设备本身无关，但我目前使用Debian系发行版。

**Comment by PikuZheng** [comment]
停用双栈优选后应同时提供A记录和AAAA记录。大部分终端（比如windows，android）都会优先使用ipv6。可以用 ping 域名测试。
如果是确定的域名要禁用ipv4，可以使用 address限制。

**Comment by PikuZheng** [comment]
> 目前我无法想明白：为什么将SmartDNS封装为本地DoH可以解决这个问题。

猜测是走ipv6 dns了 没走smartdns

**Comment by Xymmh** [comment]
校园网？我用了这么长时间，没发现关闭双栈优选后出现不返回AAAA记录的情况。目前只返回ipv6单栈地址风险太大，终端的ipv6连接稳定性很可能没ipv4那么稳，而且浏览器都是默认先走ipv6。
