### ISSUE TITLE
是否支持指定域名通过哪个dns访问

### ISSUE THREAD

**Issue by JDex623** [pymumu/smartdns#173]
**问题现象**  
是否支持指定域名通过哪个dns访问 ?
address 命令是指定,某个域名通过哪个IP访问吗?类似hosts?
**运行环境**
1. centos7

**Comment by JDex623** [comment]
配置了

**Comment by JDex623** [comment]
配置了

**Comment by JDex623** [comment]
配置了
server 8.8.8.8 -group test -exclude-default-group
server-tcp 8.8.8.8 -group test -exclude-default-group
server-tls 8.8.8.8 -group test -exclude-default-group
nameserver /.jd.com/test
nameserver /.youku.com/test
好像都不生效 上面DNS改过好几个 解析都一样

**Comment by pymumu** [comment]
是这样配置，怎么确认没生效的？

**Comment by JDex623** [comment]
smartdns用作dns服务器  用户机 nslookup解析 不走指定的DNS去解析

**Comment by pymumu** [comment]
这个意思是走对应的dns解析， -exclude-default-group表示的是，未指定namserver的域名不使用此DNS解析。

你上面的配置，意思是jd.com用8.8.8.8的三种协议解析。

**Comment by pymumu** [comment]
IP不一样，原因是：即使8.8.8.8，三种协议其实是3个不同的服务器，返回的IP不一定相同。可以只保留UDP的验证。

配置同一个DNS服务器，三种协议，一般没有意义。

**Comment by JDex623** [comment]
也就是说server 8.8.8.8 -group test  这样就可以指定group里面的域名使用8.8.8.8 去解析吗? 不需要使用-exclude?

**Comment by pymumu** [comment]
对， -exclude-default-group表示的是，未指定namserver的域名不使用此DNS解析。
