### ISSUE TITLE
immortalwrt23.05.1安装smartdns失败

### ISSUE THREAD

**Issue by wzlps** [pymumu/smartdns#1731]
**问题现象**  
安装smartdns一直失败，无论是通过opkg源还是在github下载完整包用Opkg install命令安装都失败。

**运行环境**
1. 固件型号：immortalwrt 23.05.1  

2. 运营商 ：中国移动

3. smartdns来源以及版本：opkg官方源/github

4. 涉及的配置(注意去除个人相关信息)：在安装过程

**重现步骤**
1. 上游DNS配置：不涉及。  

2. 访问的域名：不涉及。  

**信息收集**  
安装信息显示：

root@ImmortalWrt:~# opkg install smartdns.1.2024.02.08-0828.aarch64-openwrt-all.ipk
Installing smartdns (1.2024.02.08-0828) to root...
Configuring smartdns.
Collected errors:
 * pkg_get_installed_files: Failed to open //usr/lib/opkg/info/luci-i18n-routerdog-zh-cn.list: No such file or directory.
 * pkg_get_installed_files: Failed to open //usr/lib/opkg/info/app-meta-routerdog.list: No such file or directory.
 * pkg_get_installed_files: Failed to open //usr/lib/opkg/info/luci-lib-taskd.list: No such file or directory.
 * pkg_get_installed_files: Failed to open //usr/lib/opkg/info/luci-app-store.list: No such file or directory.
 * pkg_get_installed_files: Failed to open //usr/lib/opkg/info/routergo.list: No such file or directory.
 * pkg_get_installed_files: Failed to open //usr/lib/opkg/info/luci-app-routerdog.list: No such file or directory.
 * resolve_conffiles: Existing conffile /etc/config/smartdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/smartdns-opkg.
 * resolve_conffiles: Existing conffile /etc/smartdns/domain-block.list is different from the conffile in the new package. The new conffile will be placed at /etc/smartdns/domain-block.list-opkg.

**Comment by PikuZheng** [comment]
>Installing smartdns (1.2024.02.08-0828) to root...
>Configuring smartdns.

单看这两行，安装成功完成了。

下面看起来是一些其他ipk的报错（routerdog？routergo？）
最后两行是说smartdns是覆盖安装，有旧的配置文件保留了。

**Comment by wzlps** [comment]
> > Installing smartdns (1.2024.02.08-0828) to root...
> > Configuring smartdns.
> 
> 单看这两行，安装成功完成了。
> 
> 下面看起来是一些其他ipk的报错（routerdog？routergo？） 最后两行是说smartdns是覆盖安装，有旧的配置文件保留了。

可是我正常配置文件后，仍无法启动，显示查看系统日志，但是系统日志没有任何显示。

**Comment by PikuZheng** [comment]
默认日志在 /var/log/smartdns.log
系统日志没有的话一般是架构错误运行不起来

**Comment by wzlps** [comment]
我选择重刷了其他固件了并且也解决了这个问题，谢谢，本Issus可以关闭了
