### ISSUE TITLE
HTTP 400 Bad Request for DOH ordns.he.net

### ISSUE THREAD

**Issue by TCP3ACK** [pymumu/smartdns#1733]
Hi, 

The DOH of he.net (https://ordns.he.net/dns-query) returns code 400 for smartdns. However it's normal while using `dig @ordns.he.net +https example.com`

**Comment by PikuZheng** [comment]
non-compliant ?
![image](https://github.com/pymumu/smartdns/assets/12579522/42e9b51c-c2b6-4829-987a-b870740c2fc4)

**Comment by pymumu** [comment]
Currently, smartdns does not support http/2, and ordns.he.net DNS server requires http/2 causing DOH to become unavailable.
Smartdns will add http2 protocol support in the future.

**Comment by pymumu** [comment]
already support http2
