### ISSUE TITLE
openwrt安装后，不同网段无法生效。请问怎么设置？

### ISSUE THREAD

**Issue by proudofbinge** [pymumu/smartdns#174]
我用openwrt搭建了一个smartdns服务器，ip地址为：10.5.5.2/24
当为使用 10.5.5.0/24网段的pc将dns指向smartdns时一切正常。
非10.5.5.0/24网段的pc dns指向smartdns时，不生效。
请问该如何解决呢？
[smartdns.log](https://github.com/pymumu/smartdns/files/3314127/smartdns.log)

**Comment by proudofbinge** [comment]
我把日志内容直接贴出来吧

[2019-06-20 15:56:44,981][ERROR][      fast_ping.c:376 ] sendto 2a03:8600::dd, id 9, Permission denied
[2019-06-20 17:21:10,292][ERROR][      fast_ping.c:376 ] sendto 2606:4700:10::6814:f28, id 25, Permission denied
[2019-06-21 18:46:44,415][ERROR][      fast_ping.c:376 ] sendto 2606:4700:10::6814:f28, id 23, Permission denied

**Comment by pymumu** [comment]
应该是防火墙导致的，检查你的防火墙配置把。

**Comment by proudofbinge** [comment]
> 应该是防火墙导致的，检查你的防火墙配置把。

在防火墙自定义规则里加了下面命令。
iptables -t filter -I OUTPUT -s 10.5.5.5 -j ACCEPT
iptables -t filter -I INPUT -d 10.5.5.5 -j ACCEPT
iptables -t filter -I FORWARD -j ACCEPT
然后手动重启firewall服务
/etc/init.d/firewall restart
iptables -L 查看已生效。

**Comment by pymumu** [comment]
你可以将防火墙完全关闭测试下看看。smartdns没有这些限制。

**Comment by proudofbinge** [comment]
> 你可以将防火墙完全关闭测试下看看。smartdns没有这些限制。

多谢多谢，关闭防火墙，可以了。

**Comment by LsnmxNB** [comment]
让后人少走弯路，我折腾了好久，如果是OpenWrt 不单单关闭关闭防火墙就可以，还需要DHCP/DNS下
重绑定保护   丢弃 RFC1918 上行响应数据 

仅本地服务   仅在网卡所属的子网中提供 DNS 服务。
这两个通通关闭才能在不同网段使smartdns提供服务

openwrt如何关掉防火墙
阻止防火墙服务开机自动启动/禁止
/etc/init.d/firewall stop

/etc/init.d/firewall disable

![Snipaste_2021-07-12_18-35-14](https://user-images.githubusercontent.com/42826027/125273915-f2519180-e2fc-11eb-9e31-a1ed67642b5b.png)
