### ISSUE TITLE
开启缓存后，如果某个域名被污染了，即使修改了该域名的 domain-rules 规则，也无法快速更新缓存文件中的被污染域名结果

### ISSUE THREAD

**Issue by lxf1992521** [pymumu/smartdns#1740]
**需求应用场景**
对于当前的 smartdns 缓存方案，如果某个域名被污染了，在手动修改 domain-rules 后重启 samrtdns，也只能被动等待域名 TTL 到期重新更新，或者更激进的就是删除整个缓存文件。

**建议的方案**
能否实现命令行参数/配置文件，直接修改/更新缓存文件中某个域名的缓存信息，让其快速更新生效新的 domain-rules，获取到正确的 DNS 解析结果

**Comment by war2wow** [comment]
domain-rules /server.xxxx.com/ -no-cache
domain-rules /www.xxxx.com.cn/ no-cache

对于已缓存过的域名，即便设置no-cache并重启服务，也不会清理域名对应的缓存。同需求手动清理指定域名缓存

**Comment by naoki66** [comment]
要是luci上面能添加一个类似passwall的清空 NFTSET按钮能一键清除cache就好了

**Comment by lxf1992521** [comment]
看起来 smartdns 内部并没有很好的处理 DNS 缓存污染的问题，我准备停掉缓存持久化，并在需要的时候重启 smartdns 来解决缓存污染问题。
