### ISSUE TITLE
domain-rules的group参数问题

### ISSUE THREAD

**Issue by Archeb** [pymumu/smartdns#1741]
**需求应用场景**
我观察到最近我更新之后我的group设置全部失效了，我本来是用
```
domain-rules /example.com/ -g china
```
这种格式去设置分组的，查阅文档之后发现 https://pymumu.github.io/smartdns/configuration/ 里面 `domain-rules` 指令已经不再有 group 这个参数了，但是 https://pymumu.github.io/smartdns/config/domain-rule/ 这篇文档里面却仍然保留着。这会给用户带来很大的误解。

**建议的方案**
修改文档

**Comment by PikuZheng** [comment]
代码仍存在group的处理啊
https://github.com/pymumu/smartdns/blob/07c13827bb523519a638214ed7ad76180f71a40a/src/dns_conf.c#L4897-L4908

**Comment by Archeb** [comment]
> 代码仍存在group的处理啊
> 
> https://github.com/pymumu/smartdns/blob/07c13827bb523519a638214ed7ad76180f71a40a/src/dns_conf.c#L4897-L4908

😂 我的意思是不管咋样这两页文档里面肯定有一个是多了或者缺了参数的，至少要让他们同步。

**Comment by PikuZheng** [comment]
我怀疑你说的是nameserver组。group是给配置文件分组用的。

**Comment by PikuZheng** [comment]
新版本采用 group-begin 和 group-end 给配置分组。但是配置上还是会兼容旧的写法，domain-rules 的 group应该是好用的

**Comment by Archeb** [comment]
> 我怀疑你说的是nameserver组。group是给配置文件分组用的。

我又去认真看了下，确实是我理解有误，我是想给某个域名指定用的nameserver组，应该用nameserver参数，现在没有问题了，感谢。
