### ISSUE TITLE
配置文件支持相对路径

### ISSUE THREAD

**Issue by storezhang** [pymumu/smartdns#1749]
**需求应用场景**
在不同设备之间通过nfs共享配置时，遇到配置文件在不同设备上路径不同的问题

**建议的方案**
配置支持相对路径

**设备信息**
无

**Comment by pymumu** [comment]
已经支持

**Comment by storezhang** [comment]
> 已经支持

我测试下来好像是不支持的呢，如果是相对路径，相对的是配置文件的路径吗？

**Comment by storezhang** [comment]
> 已经支持

上午测试方式错了，已ok
