### ISSUE TITLE
6月21日的最新版本，日志记录的日期时间不正确

### ISSUE THREAD

**Issue by fox85** [pymumu/smartdns#176]
**问题现象**  
6月21日的最新版本，无论是审计日志或程序日志，记录的日期时间都不正确

测试了在arm及X86的架构下，都有这个情况出现。
系统时间是正确的，GMT+8的时区，然而日志里面记录的时间却会有-8个小时的偏差

**Comment by pymumu** [comment]
是静态编译c库，导致的时区未正确获取。

可以先在smartdns的启动脚本里面，加如下语句规避：
```shell
export TZ=GMT-8
```
