### ISSUE TITLE
1.建议查询时可以选择源地址. 2. 增加关闭测试最优IP的功能

### ISSUE THREAD

**Issue by rodge-liu** [pymumu/smartdns#177]
**需求应用场景**。
1.建议查询时可以选择源地址.
　　我的路由器的是多个出口,并且是出口是通过内部IP来互相的.公网的IP是绑定在内部的loop 口的内部上网是通过SNAT转换为LOOP 口来实现．如果要无法指定源地址的话，就必须根据我填的上层查询的服务器(如１１４.１１４.１１４.１１４)增加多个ＮＡＴ来实现．导至配置起来很乱．

２.增加关闭测试最优IP的功能
　根据你的设定，你是使用ＩＣＭＰ和ＴＣＰ　８０　端口来检测．
　而我的环境如上面１如讲是如果不做ＳＮＡＴ，路由器根据本身是ＩＰ是无法检查的．
    同时在多线电信的路由器上．通过一条电信线测试来最优，可能是未必另一条电信线路上最好的结果．
　并且如果国内域名　电信／联通厂商提供的ＤＮＳ，一般已是ＣＤＮ厂商已特别针对过了．差１０／２０ms ,对使用者根本无多大关系．
　而对于我这种用户来说，国内的域名在大规模条目的ipset和域名分组中　实现比dnsmasq更好性能和更好的稳定性．
  而国外域名，通过ECS 加 HTTP DNS ,DNS TLS 查询国外公共DNS．实现无污染的结果．

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
后面增加吧。
测试的用途不仅仅是时间差异，而是在配置多个上游的情况下，选择最佳。
如果只是上国内网络，用运营商的就可以了。

**Comment by cjjdaq** [comment]
本来也是先提增加这个关闭ip优选的功能，没想到已经有人提了
