### ISSUE TITLE
目前看文档提供给用户侧支持DoT、DoH还有H3 和 DoQ目前暂不支持，想咨询一下如何验证

### ISSUE THREAD

**Issue by maojianyou** [pymumu/smartdns#1776]
**问题现象**  
比如我监听了 853 端口也就是用户侧的DoT,然后也监听了DoH，证书默认，后续也可以申请域名形式；
# DOT 服务器
bind-tls 0.0.0.0:853@eth0
bind-tls [::]:853@eth0
bind-tls :853@eth0

# DOH 服务器
bind-https 0.0.0.0:443@eth0
bind-https [::]:443@eth0
bind-https :443@eth0

bind-cert-file smartdns-cert.pem
bind-cert-key-file smartdns-key.pem

上游DNS
server 8.8.8.8

本机IP smartdns
192.168.1.1  

用户侧 可以是linux也可以是windows或者手机安卓，IOS
192.168.1.3 

我如何在用户侧上面验证192.168.1.1 的DoT 跟DoH 验证流程是否能解析；

**Comment by PikuZheng** [comment]
dot用kdig，doh用浏览器

**Comment by geol** [comment]
我试了下doh服务器，smartdns没有监听对应端口，做为dns服务器也没有响应。

**Comment by PikuZheng** [comment]
smartdns的doh我一直在用，路线是 用户--(udp)--mikrotik--(doh)--smartdns--(dot和doh)--
由于smartdns的doh不可用时mikrotik会计错误日志。观察我的smartdns的doh一直是好的。

**Comment by geol** [comment]
> smartdns的doh我一直在用，路线是 用户--(udp)--mikrotik--(doh)--smartdns--(dot和doh)--
> 由于smartdns的doh不可用时mikrotik会计错误日志。观察我的smartdns的doh一直是好的。

我doh开不起来都，openwrt上的，如我上面说的。dot倒是能开起来，但是远程手机用小火箭测试时，发现它仅仅尝试了下就回滚使用默认dns。

**Comment by PikuZheng** [comment]
> 我doh开不起来都，openwrt上的，如我上面说的。dot倒是能开起来，但是远程手机用小火箭测试时，发现它仅仅尝试了下就回滚使用默认dns。

建议换端口号
尝试了下就回滚 可能是网不通
