### ISSUE TITLE
有一个奇怪的DNS应答，请看看这种能否过滤

### ISSUE THREAD

**Issue by fox85** [pymumu/smartdns#178]
查询上游DNS特定的域名，比如202.96.128.86，结果会如下

C:\Users\PC71006>nslookup www.pornhub.com 202.96.128.86
服务器:  cache-a.guangzhou.gd.cn
Address:  202.96.128.86

非权威应答:
非权威应答:
名称:    www.pornhub.com

结果完全是空的，这样会导致smartdns在以此DNS为上游的情况下，也返回空的结果。

请问smartdns是否可以针对此种结果作特殊的处理？

如果需要，我可以发个DNS抓包结果的附件给你邮箱分析一下，谢谢大佬~~~~

**Comment by pymumu** [comment]
配置几个tls，httpdns试试看吧。

小心伤身啊。
