### ISSUE TITLE
32GB of DoH traffic? 

### ISSUE THREAD

**Issue by bcookatpcsd** [pymumu/smartdns#1780]
![image](https://github.com/user-attachments/assets/47c03cbe-ad27-4f11-81f7-17876e6fc530)

```
server tls://x-hagezi-normal.freedns.controld.com:853 -k
server https://freedns.controld.com/p2 -k
server tls://kronos.plan9-dns.com:853 -k
server https://nyc01.dnscry.pt/dns-query -k
server tls://nyc01.dnscry.pt:853 -k
server https://dns.nextdns.io/dnscrypt-proxy -k

cache-size 65535
cache-persist no
prefetch-domain yes

rr-ttl 600
rr-ttl-max 2400
```

Screenshot is from an OpenWRT router (ethernet only no wifi), uptime 7 days.. 

SmartDNS is a docker container on 192.168.88.250 

Household with 50ish devices..
 
![image](https://github.com/user-attachments/assets/b28594f3-219e-4fa7-9404-8932cc473564)

One PC gamer, two into tiktok, one netfilix/tv watcher at night, and someone keeping everyone off the web ;) 

Open to suggestions..

**Comment by pymumu** [comment]
Any debug log?

**Comment by bcookatpcsd** [comment]
Did not have enabled.. will enable and share

fwiw: the two controld domains is the same host.. just the https was using all the bandwidth

**Comment by bcookatpcsd** [comment]
[smartdns.log](https://github.com/user-attachments/files/16295724/smartdns.log)
[smartdns-audit.log](https://github.com/user-attachments/files/16295731/smartdns-audit.log)

I had recreated the container not realizing there was a '/var/log/smartdns/' in the container.. 

Please let me know if there is nothing of value in there..

**Comment by pymumu** [comment]
From the log, it appears that only three upstream servers were added, which is different from the configuration. No other issues were observed.

[2024-07-19 00:23:29,328][DEBUG][     dns_client.c:3855] send query to server 76.76.2.11:853
[2024-07-19 00:23:29,328][DEBUG][     dns_client.c:3855] send query to server 207.246.87.96:853
[2024-07-19 00:23:29,328][DEBUG][     dns_client.c:3855] send query to server 84.33.245.10:853

**Comment by PikuZheng** [comment]
> recv query packet from 127.0.0.1

There is a prefix dns server on the same device as smartdns , which only forwards part of the query to smartdns.
 You should investigate issues with that prefix dns server.

**Comment by bcookatpcsd** [comment]
stopped using docker.. haven't seen it happen.. 

also.. 

rebuilt for Alpine linux (musl) x86-64

```
git clone https://github.com/pymumu/smartdns.git
git fetch --all
git tag -l
git checkout Release46 --force
./package/build-pkg.sh --platform linux --arch x86_64
src/smartdns -v

smartdns 1.2024.07.20-2217 (Release46)

 ldd src/smartdns
        /lib/ld-musl-x86_64.so.1 (0x7fd42cf94000)
        libssl.so.3 => /lib/libssl.so.3 (0x7fd42cd46000)
        libcrypto.so.3 => /lib/libcrypto.so.3 (0x7fd42c800000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fd42cf94000)

```

running in s6.. I've not been able to make it happen again..
