### ISSUE TITLE
如何理解address配置项末尾的-参数？

### ISSUE THREAD

**Issue by ZqinKing** [pymumu/smartdns#1782]
一直以为“#”规则标识SOA响应，“-”代表该域名规则忽略响应。
实际配置还是拿到了响应。遂检查了一下配置项说明。
- 表示忽略此规则

这个忽略此规则，应该如何理解？从现象看，配置此项后针对次域名连IPv6解析禁用这些都不生效了。
如果想对某些域名不响应，应该如何配置？

**Comment by PikuZheng** [comment]
没有不响应的规则配置。不响应属于查询错误的一种，可能导致客户端向其他dns服务器发起重试。
“-”表示从当前配置中减掉一行。比如同时设置
```
address /baidu.com/#
address /www.baidu.com/-
```
会导致www.baidu.com正常解析，其他以baidu.com结尾的域名返回soa

**Comment by ZqinKing** [comment]
> 没有不响应的规则配置。不响应属于查询错误的一种，可能导致客户端向其他dns服务器发起重试。 “-”表示从当前配置中减掉一行。比如同时设置
> 
> ```
> address /baidu.com/#
> address /www.baidu.com/-
> ```
> 
> 会导致www.baidu.com正常解析，其他以baidu.com结尾的域名返回soa

谢谢，看明白了。有业务需要，网内有特殊网安设备，会一直扫描所有IP，向所有设备发送随机生成前缀的DNS请求。有点类似DGA那种。所以想要忽略掉相关域名的解析。
