### ISSUE TITLE
建议增加Hosts额外配置

### ISSUE THREAD

**Issue by xiaoxinpro** [pymumu/smartdns#179]
**需求应用场景**
自带的域名过滤功能性能不行，我只添加了8000行屏蔽域名OpenWrt就卡住不动了
Hosts文件更方便维护

**建议的方案**
类似与dnsmasq增加Hosts文件路径配，或增加大文本框直接输入Hosts脚本。

**设备信息**
1. 设备信息（CPU，厂家）  
J1900主板
2. 固件信息
Powered by LuCI openwrt-18.06 branch (git-18.228.31946-f64b152) / OpenWrt 18.06.1 r7258-5eb055306f

**Comment by soffchen** [comment]
J1900 没那么烂吧

```
# cat /etc/smartdns/accelerated-domains.china.conf  | wc -l
62661
```

一点儿压力都没有

**Comment by fonlan** [comment]
应该指的是luci界面的性能跟不上，SmartDns本身性能没问题

**Comment by pymumu** [comment]
luci处理文件能力有限，对于比较大的文件，建议使用
```shell
conf-file
``` 
包含外部文件。
