### ISSUE TITLE
测速模式配置优先级的问题

### ISSUE THREAD

**Issue by fl0w1nd** [pymumu/smartdns#1790]
如果在全局配置中关闭了测速，例如：speed-check-mode: none，而在域名规则中开启了测速，那么全局配置会覆盖域名规则中的配置吗？

**Comment by PikuZheng** [comment]
取决于版本

**Comment by PikuZheng** [comment]
当配置全局 `speed-check-mode none` 时：
43.0.91及之后的版本使用`domain-rule`配置的测速规则会起作用；
43.0.90及之前版本ipv4会测速，ipv6不测速。

38.1.16及之前版本，domain-rule 配置的测速规则不起作用，无论全局`speed-check-mode`如何设置。
