### ISSUE TITLE
可否考虑增加日志以标准的syslog发送到日志服务器功能

### ISSUE THREAD

**Issue by hel2o** [pymumu/smartdns#180]
**需求应用场景**
日志不想存储在本地，而是想统一发送到日志服务器上

**建议的方案**
增加日志以标准的syslog发送到日志服务器功能

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
后面增加把。

**Comment by hel2o** [comment]
期待
