### ISSUE TITLE
这个参数值 意思是？dualstack-ip-selection-threshold

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#1800]
默认10 是如果ipv4 比ipv6 慢10  还是ipv6比ipv4慢10 ？

**Comment by PikuZheng** [comment]
都有可能
哪个慢就丢弃哪个

**Comment by lalasou** [comment]
@pymumu   这个参数大小是什么

**Comment by PikuZheng** [comment]
> @pymumu 这个参数大小是什么

你是说取值范围吗？最小0最大1000

https://github.com/pymumu/smartdns/blob/75649b623519dda99b772342bbbe625a45234864/src/dns_conf.c#L5982-L5983

**Comment by lalasou** [comment]
> > @pymumu 这个参数大小是什么
> 
> 
> 
> 你是说取值范围吗？最小0最大1000
> 
> 
> 
> https://github.com/pymumu/smartdns/blob/75649b623519dda99b772342bbbe625a45234864/src/dns_conf.c#L5982-L5983

不是 取值范围
是这个参数  大小意义是什么 
比如  v4比v6快10   还是什么

**Comment by lalasou** [comment]
其实  还是想要有一会参数  比如ipv4优先
或者ipv6优先

我翻了翻  看很多人也是需要这个功能

**Comment by PikuZheng** [comment]
> 是这个参数 大小意义是什么
> 比如 v4比v6快10 还是什么

正确的。就是ipv4和ipv6测速的速度差值如果超过这个threshold，则丢弃较慢的那个

**Comment by lalasou** [comment]
双栈有困扰的  建议设置为5



有效

**Comment by devioa** [comment]
> 都有可能 哪个慢就丢弃哪个

不对吧，不是 ipv6 比 ipv4 慢于这个参数值就丢掉 ipv6 吗？
正常情况下应该是同时返回 ipv6 和 ipv4 的，因为客户端一般默认 ipv6 优先
设置`dualstack-ip-allow-force-AAAA yes`才会只返回 ipv6 吧

**Comment by lalasou** [comment]
> > 都有可能 哪个慢就丢弃哪个
> 
> 
> 
> 不对吧，不是 ipv6 比 ipv4 慢于这个参数值就丢掉 ipv6 吗？
> 
> 正常情况下应该是同时返回 ipv6 和 ipv4 的，因为客户端一般默认 ipv6 优先
> 
> 设置`dualstack-ip-allow-force-AAAA yes`才会只返回 ipv6 吧

配置步骤

使用dualstack-ip-selection配置启用双栈优选


dualstack-ip-selection yes
如需要倾向使用IPV6，则可以使用dualstack-ip-selection-threshold进行阈值调整


dualstack-ip-selection-threshold 10
注意：

单位为ms，两个IP地址的速度阈值大于配置值时，才会进行优选。
允许纯IPV6地址。

smartdns默认情况下总是会返回IPV4地址，原因是某些软件不具备IPV6的访问能力，但如果确实需要使用纯IPV6地址，可以设置允许smartdns仅优选IPV6。


dualstack-ip-allow-force-AAAA yes
