### ISSUE TITLE
1.2024.v46.0.7-1.2024.v46.0.9上游设置为doh且经过socks5时，解析限速到大约10次/S

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#1805]
20241119更新：应该不是smartdns的问题，当执行一些dns泄露测试时，比如 https://browserleaks.com/dns ，瞬间大量向上游dns请求8888或者223没有缓存的小众域名，8888、223本身也会rcode 2，不知道smartdns默认的向上游请求的超时时间是多少，因为没有缓存，上游dns服务器递归的时间也非常长，有可能超过3s。

**问题现象**  
上游设置为doh且经过socks5时，解析限速到大约10次/S，[Release 46]是没有问题的(https://github.com/pymumu/smartdns/releases/tag/Release46)

**运行环境**
1. 固件型号  
QWRT R24.6.1 / LuCI Master (git-24.141.58422-8db02ef) 6.8.12
2. 运营商  
中国联通
3. smartdns来源以及版本  1.2024.v46.0.7-1.2024.v46.0.9，更早的版本没有测试。
https://github.com/PikuZheng/smartdns/releases

4. 涉及的配置(注意去除个人相关信息)
server-name smartdnsfallback
dualstack-ip-selection no
serve-expired yes
cache-persist yes
prefetch-domain yes
cache-size 1000000
speed-check-mode none
response-mode fastest-response
log-size 64K
log-num 1
log-level error
audit-size 64K
audit-num 1
serve-expired-ttl 259200
serve-expired-reply-ttl 3
cache-checkpoint-time 3600
cache-file /etc/smartdnsfallback/smartdns.cache
bind :6688
bind-tcp :6688 
proxy-server socks5://127.0.0.1:7891 -name socks5
server-https https://8.8.8.8/dns-query -proxy socks5 -subnet 123.232.157.1/24

**重现步骤**
1. 上游DNS配置。  
proxy-server socks5://127.0.0.1:7891 -name socks5
server-https https://8.8.8.8/dns-query -proxy socks5 -subnet 123.232.157.1/24

2. 访问的域名。  
https://browserleaks.com/dns
此域名会并发100次/S以上的dns查询，前10次左右会成功，后面的全部rcode 2了。
**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
超过10会什么错误？

**Comment by yyysuo** [comment]
> 2\. rcode 2

rcode 2 SERVFAIL

**Comment by pymumu** [comment]
发配置和log把，这块没改过什么
