### ISSUE TITLE
测速模式和响应模式参数配置优先级问题

### ISSUE THREAD

**Issue by giveup** [pymumu/smartdns#1807]
**问题现象**  
和#https://github.com/pymumu/smartdns/issues/1790 类似，例如对于测速，共有三处地方可配置。
全局 `speed-check-mode none`
端口 `[-no-speed-check]：停用测速`
域名规则 `domain-rules /example.com/ -speed-check-mode none`
在配置文档均有说明https://pymumu.github.io/smartdns/config/check-speed-mode/ 但是没有提到优先级。
我的理解是域名规则优先级最高。
使用的配置如下
```
全局 speed-check-mode none
端口 bind :54@lo  -no-speed-check
域名 domain-rules address /*.github.io/  speed-check-mode tcp:443,ping
```

```shell
root@AX6S:/etc/openclash# smartdns --cache-print  /etc/smartdns/smartdns.cache  | grep 'github.io'
domain: pymumu.github.io, qtype: 1, rcode: 0, ttl: 600, speed: -0.1ms, result: 185.199.108.153, 185.199.111.153, 185.199.109.153, 185.199.110.153
domain: pymumu.github.io, qtype: 65, rcode: 0, ttl: 600, speed: -0.1ms
```
从缓存结果来看都是-0.1，似乎测速并没有生效。
类似的还有响应模式等参数的配置优先级。

**运行环境**
1. 固件型号 
OpenWrt 23.05.4
  
2. 运营商  

3. smartdns来源以及版本 smartdns 1.2024.v46.0.9

4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
github.io

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
建议开debug日志看看这个域名有没有命中规则

**Comment by PikuZheng** [comment]
>Sun Aug 25 23:29:50 2024 user.info smartdns: RULE-MATCH, type: 11, domain: pymumu.github.io, rule: github.io.
Sun Aug 25 23:29:50 2024 user.info smartdns: result: pymumu.github.io, client: 127.0.0.1, qtype: 1, id: 21188, group: oversea, time: 1ms

单看这个 貌似只设置了 namerserver /github.io/oversea，没有针对这个域名设置测速规则

**Comment by PikuZheng** [comment]
> serve-expired-ttl 604800\ndomain-rules /*.github.io/  speed-check-mode tcp:443,ping -response-mode fastest-ip

语法错

**Comment by PikuZheng** [comment]
（用手机回的 打字比较慢
```
speed-check-mode none
domain-rules /*.github.io/ -nameserver oversea -speed-check-mode tcp:443 -response-mode fastest-ip
```

**Comment by PikuZheng** [comment]
> custom.conf如下
> 
> ```
> serve-expired-ttl 604800
> domain-rules /*.github.io/  speed-check-mode tcp:443,ping -response-mode fastest-ip
> ```
> 
> 请问这样算正确设置吗？@PikuZheng

你这个少减号（如果不是复制到github少了的话）

> ```
> speed-check-mode none
> bind :54@br-lan  -no-speed-check -no-dualstack-selection -force-aaaa-soa -group oversea
> conf-file /etc/smartdns/custom.conf
> ```

此处不应有 -no-speed-check ，这个会导致所有测速规则跳过

**Comment by PikuZheng** [comment]
> 也就是优先级上，全局>端口>大于Domain rule。

反了，全局 < domain rule < -no-speed-check
全局和domain rule都是用来选择一种测速方法
-no-speed-check是强制不测速，而不是选择一种测速方法
