### ISSUE TITLE
google.com / google.com.hk随机无法打开或证书错误，标准配置文件也有问题

### ISSUE THREAD

**Issue by gzelvis** [pymumu/smartdns#181]
我第一次写了30分钟，Github弹出个了什么框，点了个no thanks都没了。 现在好想哭。。。。。。

这次长话短说吧，。。不行我先哭一会。。。妈蛋，真的打了很久

=============================================

用了smartdns后，www.google.com 或 www.google.com.hk 一会是前者一会是后者随机加载不开，或者加载了后显示证书不对（证书不对的时候一般是显示 31.x IP），加载不了的时候一般显示61.x 。某些需要55的页面随机1秒能加载完的，页面出来了但浏览器Tab那里还在转圈要7-8秒后才能结束（正常时候应该1秒就load完了然后可以点页面刷新）

Release 26版smartdns，Openwrt Koolshare mod V2.29 r7707-6f685d297b，直接使用53端口，没做dnsmasq上游，没做转发，出国用clash，配置文件如下

config smartdns
	option server_name 'smartdns'
	option port '53'
	option tcp_server '1'
	option dualstack_ip_selection '0'
	option coredump '0'
	option prefetch_domain '1'
	option enabled '1'
	option ipv6_server '0'
	option redirect 'none'
	option cache_size '8192'
	option rr_ttl '900'
	option rr_ttl_min '300'
	list old_redirect 'none'
	list old_port '53'
	list old_enabled '1'

config server
	option enabled '1'
	option ip '8.8.8.8'
	option port '853'
	option type 'tls'
	option name '8.8.8.8'
	option server_group '55'

config server
	option enabled '1'
	option name '8.8.4.4'
	option ip '8.8.4.4'
	option port '853'
	option type 'tls'
	option server_group '55'

config server
	option enabled '1'
	option name '1.1.1.1'
	option ip '1.1.1.1'
	option port '853'
	option type 'tls'
	option server_group '55'

config server
	option enabled '1'
	option name '1.0.0.1'
	option ip '1.0.0.1'
	option port '853'
	option type 'tls'
	option server_group '55'

config server
	option enabled '1'
	option type 'udp'
	option name '119.29.29.29'
	option ip '119.29.29.29'
	option port '53'
	option server_group 'cn'

config server
	option enabled '1'
	option type 'udp'
	option name '180.76.76.76'
	option ip '180.76.76.76'
	option port '53'
	option server_group 'cn'

config server
	option enabled '1'
	option type 'udp'
	option name '223.5.5.5'
	option ip '223.5.5.5'
	option port '53'
	option server_group 'cn'

config server
	option enabled '1'
	option name '208.67.222.222'
	option ip '208.67.222.222'
	option port '443'
	option type 'tcp'
	option server_group '55'

config server
	option enabled '1'
	option name '208.67.220.220'
	option ip '208.67.220.220'
	option port '443'
	option type 'tcp'
	option server_group '55'

问题2： 以上是最新版smartdns在LEDE菜单那里用程序添加的DNS后自动生成的配置参数，在这里无论是手动加入还是套用外部conf文件，只要有

address /Home/10.0.0.1,

nameserver /www.google.com/ss,       
nameserver /www.google.com.hk/ss,    
nameserver /google.com/ss , 

blacklist-ip 4.36.66.178
blacklist-ip 8.7.198.45
blacklist-ip 31.13.75.17
blacklist-ip 37.61.54.158
blacklist-ip 46.82.174.68
blacklist-ip 59.24.3.173

这种语句，LEDE的smartdns配置界面就无法显示正常参数（参数位置全是空白css错乱）并且smartdns无法加载运行（结尾逗号要不要加也都试过了，一样）

尝试用 /etc/smartdns/smartdns.conf 旧版配置语句来改，也是无法执行，只有上面这个可以运行，但无法加 address / nameserver / blacklist-ip 语句 （github下载最新版smartdns）

初步怀疑无法打开google或者有时候加载速度过慢是国内几个公共dns被“误导”，解决办法是国内DNS加blacklist-ip，国外的因为都是TLS或者TCP，edns不用了，但用 cn / 55 分组来让特殊域名之用国外DNS解析。可配置文件无法添加blacklist 和 nameserver ，所以无法尝试这种解决办法

还请官方给出标准的配置模板以供参考，感谢

**Comment by pymumu** [comment]
1. nameserver后面写的是ss，但option server_group后面是“55”，这里不一致，另外域名的www可以去掉。
2.这个可能是LEDE LUCI的BUG，openwrt15.0的我验证没有问题。可以先将这项信息写到一个独立的配置文件中。然后用conf-file包含进来规避。这样缺点是没法界面配置。可以先试试。

**Comment by gzelvis** [comment]
55是我故意那么打的

我已经试过把 address 和 nameserver 放在 /etc/smartdns/address.conf .然后用 conf-file 来include，问题是只要一这样， LUCI界面只要显示参数的地方就空白（CSS错乱），然后其实后台我看过Smartdns是没执行的（应该是程序出错无法运行）。 你的意思是，正常了来说在 /etc/config/smartdns 这个配置文件里，我的那堆正常配置下 直接加 nameserver=/google.com/ss 是应该能正常执行的吗？

那我真的不知道该如何理解我目前遇到的这个问题了。或者，你能否提供一个旧版的 配置文件的标准参考模板来看看？

感谢你的回答

**Comment by pymumu** [comment]
后面有“，”是什么原因。配置举例：

server 114.114.114.114 -group cn -blacklist-ip
server-tls 8.8.8.8 -group foreign

address /home/1.1.1.1

nameserver /google.com.hk/foreign
nameserver /google.com/foreign

blacklist-ip 8.7.198.45/24
