### ISSUE TITLE
能否查看该解析取自于哪个上游DNS服务器

### ISSUE THREAD

**Issue by QLozin** [pymumu/smartdns#1813]
Hi~There

这个需求可能比较小众

最近在改自己个人域名的DNS解析, 从CF转移到DNSpod来回设置

意外发现有时候解析不不正确, 但是直接使用 `dig @1.1.1.1  ...` 又因为在内网环境经常连不上

因此想知道当前smartdns提供的解析记录来自哪个上游服务器方便我判断问题在哪

检查了审计日志, 似乎只提供了来自哪个组

```txt
... speed: 11.1ms, group default, result ...
```

如果你知道如何进一步查阅, 请告诉我, 谢谢 )

**Comment by PikuZheng** [comment]
可以开debug日志看。
不过我盲猜一个运营商抢答~

**Comment by QLozin** [comment]
> 可以开debug日志看。 不过我盲猜一个运营商抢答~

感谢你的回答

我重新查阅了 [配置指导](https://pymumu.github.io/smartdns/faq/#_3) 里面提到的关于审计日志的配置中没有找到配置日志等级的字段, 我尝试直接使用 `audit-level debug` 但是报错了 
```txt
unsupported config at '/etc/smartdns/smartdns.conf:18'.
```

关于抢答, 我的上游DNS服务都使用了DOH地址, 应该不会被抢答吧 (大概?)

另外,我的smartdns是docker部署的.

感谢你的回答, 期待进一步的帮助.

**Comment by PikuZheng** [comment]
是日志，不是审计日志

**Comment by QLozin** [comment]
[参考](https://www.right.com.cn/FORUM/thread-8280388-1-1.html) 在 `smartdns.conf` 里添加
```txt
log-level debug
log-file smartdns.log
log-size 64k
log-num 1
```
即可开启DEBUG日志, 然后可以直接访问文件或者 `docker logs smartdns`
