### ISSUE TITLE
subnet 跨运营商设置不生效

### ISSUE THREAD

**Issue by libra1010** [pymumu/smartdns#1818]
**问题现象**  
简要描述问题出现的现象
server 61.139.2.69 -group dxdns -exclude-default-group -subnet [182.148.184.232]
server 218.6.200.139 -group dxdns -exclude-default-group -subnet [182.148.184.232]
指定域名（open.shenzhenair.com）使用  dxdns 分组解析
后面的subnet 尝试更换了 多个四川电信IP地址，使用的是移动宽带请求
期望返回电信IP，但是一直返回的是移动IP

**运行环境**
1. 固件型号  
UBUNTU 24
2. 运营商  
四川移动
3. smartdns来源以及版本
apt
4. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  
server 61.139.2.69 -group dxdns -exclude-default-group -subnet [182.148.184.232]
server 218.6.200.139 -group dxdns -exclude-default-group -subnet [182.148.184.232]
server 114.114.114.114 -group dxdns -exclude-default-group -subnet [182.148.184.232]
server 223.5.5.5 -gropu dxdns -exclude-default-group -subnet [182.148.184.232]
2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
Subnet没有中括号，是cidr地址

另外不确定ubuntu版本是否支持，建议最新版本

**Comment by libra1010** [comment]
thanks 我测试一下

> Subnet没有中括号，是cidr地址
> 
> 另外不确定ubuntu版本是否支持，建议最新版本
