### ISSUE TITLE
cname 配置报错

### ISSUE THREAD

**Issue by Ryu-Z** [pymumu/smartdns#1826]
**问题现象**  
简要描述问题出现的现象
nslookup a.baidu.com
;; Question section mismatch: got www.baidu.com/A/IN
;; Question section mismatch: got www.baidu.com/A/IN
**运行环境**
1. 固件型号  

2. 运营商  

3. smartdns来源以及版本
smartdns 0.8.5 mac 
4. 涉及的配置(注意去除个人相关信息)
cname /a.baidu.com/www.baidu.com

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
cname 需要版本 v40.0.20 或更高

**Comment by Ryu-Z** [comment]
> cname 需要版本 v40.0.20 或更高

mac arm 版本的smartdns, 我是直接brew install smartdns 安装的
刚刚更新了brew upgrade smartdns
但是最新的版本号显示: smartdns 0.8.7 🕙 Tue Sep 17 07:08:41 UTC 2024

**Comment by Ryu-Z** [comment]
大概了解了,我的是mac版本的smartdns, 是单独的一个仓库

**Comment by PikuZheng** [comment]
@mokeyish 估计这事归你管

**Comment by mokeyish** [comment]
应该已经修复了 https://github.com/mokeyish/smartdns-rs/issues/385

只是没发布版本而已，可以去 Actions 那下载 nightly build 版本。

**Comment by Ryu-Z** [comment]
edy@ryu smartdns-aarch64-apple-darwin % smartdns --version
smartdns 0.8.7 🕙 Thu Sep 26 17:42:20 UTC 2024
edy@ryu smartdns-aarch64-apple-darwin % nslookup a.baidu.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com.
Name:   www.a.shifen.com
Address: 220.181.38.149
Name:   www.a.shifen.com
Address: 220.181.38.150
感谢已经修复了, @PikuZheng , @mokeyish , 可以关闭这个issue了
