### ISSUE TITLE
k2p的老毛子，下载那个版本

### ISSUE THREAD

**Issue by jjss520** [pymumu/smartdns#183]
下载的smartdns.1.2019.05.21-2250.mipselsf.ipk
opkg install smartdns.1.2019.05.21-2250.mipselsf.ipk后，后报错
Unknown package 'smartdns'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package smartdns.

**Comment by pymumu** [comment]
smartdns.1.2019.05.21-2250.mipsel-3.4.ipk
smartdns.1.2019.06.21-2337.mipsel-optware-all.ipk
