### ISSUE TITLE
添加-subnet参数的问题

### ISSUE THREAD

**Issue by qishking** [pymumu/smartdns#1840]
**问题现象**  
简要描述问题出现的现象
## 我想添加-subnet参数，遇到一些问题：
1. 我只想添加这一行配置：```server-https dns.google/dns-query -subnet 94.0.0.0/12```
    - **另外**：IP需要加掩码吗，还是直接一个IP就完了?

2. 该修改哪个配置文件：
    - 修改```/etc/smartdns/smartdns.conf```（这个文件里面配置与luci上显示不一致） ,还是···/var/etc/smartdns/smartdns.conf```（service smartdns info 显示在用这个路径）? 
    - 为什么修改完以后，重启服务后修改就会还原？

**运行环境**
1. 固件型号  
    - openwrt最新版
3. 运营商  

4. smartdns来源以及版本
    - github上release 最新版

6. 涉及的配置(注意去除个人相关信息)

**重现步骤**
1. 上游DNS配置。  

3. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传(注意去除个人相关信息)。  
3. 如进程异常，请将coredump功能开启，上传coredump信息文件，同时上传配套的smartdns进程文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
1. 加不加都行
2. 都不对，应该加在 额外的服务器参数

![image](https://github.com/user-attachments/assets/c6ee5c82-b6fc-4f2e-8a03-0d5cdedc1494)

**Comment by qishking** [comment]
> 1. 加不加都行
> 
>     2. 都不对，应该加在 额外的服务器参数
> 
> 
> ![image](https://private-user-images.githubusercontent.com/12579522/378070819-c6ee5c82-b6fc-4f2e-8a03-0d5cdedc1494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzE0NzcsIm5iZiI6MTcyOTQzMTE3NywicGF0aCI6Ii8xMjU3OTUyMi8zNzgwNzA4MTktYzZlZTVjODItYjZmYy00ZjJlLThhMDMtMGQ1Y2RlZGMxNDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYTM0Yjc3ZjFiN2JiMDU0MzE1ZGZmNWJjNzdiZmUyZDM5MjY5NzI3MjFhNzBjNjllN2E3MDU3ZGY1MDJjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HMbh03KUPkzrRO7ykCSXIeBSazTlJKClbDSqR1eufEs)

可以了，谢谢！原来在这个地方.
