### ISSUE TITLE
gfw域名走国外的dns

### ISSUE THREAD

**Issue by promayijz** [pymumu/smartdns#187]
请问能否把gfw的域名写在一个文件里用conf-file包含，然后制定这个文件里的所有域名做国外的dns服务器

**Comment by VanDeAnna** [comment]
> 请问能否把gfw的域名写在一个文件里用conf-file包含，然后制定这个文件里的所有域名做国外的dns服务器

https://pymumu.github.io/smartdns/#配置参数

**Comment by promayijz** [comment]
这个文档之前就看了，只看到有IP list的参数，没有提到域名的。所以发邮件来问问
  

  
  

  
  
>

**Comment by VanDeAnna** [comment]
> 这个文档之前就看了，只看到有IP list的参数，没有提到域名的。所以发邮件来问问

你，要不要再仔细看看？

conf-file | 附加配置文件 | 无 | 文件路径 | conf-file /etc/smartdns/smartdns.more.conf


nameserver | 指定域名使用server组解析 | 无 | nameserver /domain/[group\|-], group为组名，-表示忽略此规则，配套server中的-group参数使用 | nameserver /www.example.com/office


gfwlist 自己想办法转换一下就能变成 nameserver /domain/[group] 这种形式了

**Comment by promayijz** [comment]
可以了。谢谢

**Comment by promayijz** [comment]
可以了。谢谢
