### ISSUE TITLE
Padavan版本一点小小的bug

### ISSUE THREAD

**Issue by B3A78CD7B8BCCA3F52CD5ABFF552D** [pymumu/smartdns#188]
padavan  Entware 自带的 busybox 的 ps工具，没有ax附加参数，选择替代dnsmasq模式会报错

软件非常优秀，希望有朝一日能在op/lede编译列表中看到并编译该工具  : )

**Comment by pymumu** [comment]
[S50smartdns.zip](https://github.com/pymumu/smartdns/files/3388658/S50smartdns.zip)
这个新版本应该是已经修正了，可以替换这个文件试试看。

**Comment by B3A78CD7B8BCCA3F52CD5ABFF552D** [comment]
您似乎只是删除了前两个"ps ax"，第三个和第四个仍然存在
$CMD="`ps ax | grep " dnsmasq" ...

**Comment by pymumu** [comment]
是兼容不同固件的，你只要功能正常就可以了

**Comment by Aefer** [comment]
Pandorabox +1
