### ISSUE TITLE
无法退出smartdns

### ISSUE THREAD

**Issue by JDex623** [pymumu/smartdns#189]
**问题现象**  
/etc/init.d/smartdns stop  
提示已经停止 但smartdns的进程一直卡在后台
kill进程后不断自动生成进程
有什么好办法解决吗?
有时候想退出smartdns换bind使用 
每次都要强制退出 好麻烦

**运行环境**
cenos 7
![image](https://user-images.githubusercontent.com/51685007/61168243-ae94e780-a57d-11e9-8e18-6b16403eee5c.png)

**Comment by pymumu** [comment]
systemctl stop smartdns

**Comment by JDex623** [comment]
/etc/init.d/smartdns 那这里的配置文件是不是有问题呢

**Comment by pymumu** [comment]
那个是兼容非systemd系统用的

**Comment by JDex623** [comment]
大佬 有你的联系方式吗 有点问题想问问

**Comment by JDex623** [comment]
或者我就直接问吧  
我设置了几个dns
server 1.1.1.1
server 8.8.8.8
server 114.114.114.114
server ....
server x.x.x.x
怎么觉得如果第一条DNS出现问题的时候
后面的都不好使一样
感觉这个默认使用的是第一条
其他都不生效一样
当我注释掉第一条之后 dns解析就正常了
这个情况你看下  现在用的是 最新的版本 25 26版本都试过了 都是这样的情况

**Comment by pymumu** [comment]
1.1.1.1我也一直在用，没有你说的问题。
是否是你的网络1.1.1.1是假的，返回了一些错误信息，导致后续解析未继续。

可以将smartdns的debug日志打开，将出问题时对应的log贴一下看看。
另外，可以尝试用server-tls 1.1.1.1。

国外的不建议用udp协议。

**Comment by JDex623** [comment]
不不不,1.1.1.1 没故障  我上面是做个例子
况且我也不会用1.1.1.1  用也是用1.0.0.1

**Comment by pymumu** [comment]
打开debug日志，将出问题时的日志发一下。
