### ISSUE TITLE
关于本软件dns服务端口监听的问题

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#190]
**问题现象**  
[router /opt/home/admin]# netstat -nlp | grep smartdns
udp        0      0 0.0.0.0:15552           0.0.0.0:*                           22612/smartdns
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           22612/smartdns
udp        0      0 :::41792                :::*                                22612/smartdns
udp        0      0 :::8053                 :::*                                22612/smartdns
udp        0      0 :::61865                :::*                                22612/smartdns
udp        0      0 :::9461                 :::*                                22612/smartdns
raw        0      0 0.0.0.0:1               0.0.0.0:*               1           22612/smartdns
raw        0      0 :::58                   :::*                    58          22612/smartdns
**运行环境**
1. 固件型号  
老毛子
2. 运营商  
移动

我想知道除了我手动设定的8053端口，其他的端口是用来干什么的，对于路由器固件来说，默认是阻止wan口的input的，防火墙是否需要打开对应的端口来保证软件功能的正常运行？

**Comment by pymumu** [comment]
udp除8053外，其他是和上游dns通信的端口，配置看应该是2个ipv4,3个ipv6的上游。
raw的那两个是用于ipv6，Ipv4，ping速度检测的。

大部分情况不用关心防火墙问题。
ping ipv6的那个要注意，如果防火墙限制ping的话，就要打开。可以在设备中ping一下v6的地址，看看正不正常。
