### ISSUE TITLE
能否帮助编译一个r6300v2路由可用的entware版本？

### ISSUE THREAD

**Issue by chuangdi** [pymumu/smartdns#192]
**需求应用场景**
使用已编译好的静态版本提示illegal argument，无法使用。需要用专用toolchain编译可用版本。

**建议的方案**
使用toolchain：https://github.com/RMerl/asuswrt-merlin/tree/master/release/src-rt-6.x.4708/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3

**设备信息**
1. r6300v2

2. 固件信息
entware

**Comment by pymumu** [comment]
你装的时静态编译arm的么？应该可以才对。

**Comment by chuangdi** [comment]
装过了，不能用显示illegal srgument。

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/releases/download/Release25/smartdns.1.2019.05.21-2250.arm.ipk

试一下这个把。

**Comment by chuangdi** [comment]
谢谢我先试试看。

**Comment by chuangdi** [comment]
装不上去。显示错误：
Unknown package 'smartdns'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package smartdns.

**Comment by pymumu** [comment]
ipkg print_architecture
这个命令输出什么。

**Comment by chuangdi** [comment]
opkg print_architecture
arch all 1
arch noarch 1
arch armv7soft 10

**Comment by pymumu** [comment]
把这个复制到路由器中，手工执行一下看看能否启动。

https://github.com/pymumu/smartdns/files/3475732/smartdns.zip

```
smartdns -f -x -c [config] -p xx.pid
```

**Comment by chuangdi** [comment]
终于可以运行了，太好了，感谢。
