### ISSUE TITLE
希望能够支持多线检测服务器速度

### ISSUE THREAD

**Issue by colinhd8** [pymumu/smartdns#193]
今天看到这个项目，感觉就是我一直在找的想要的一个功能，但初看下来，貌似缺了点东西，所以提出点建议大家讨论下（貌似还没人提过比较具体的场景）。
**需求应用场景**
1.通过访问多个上游DNS来获取结果，并对结果进行测速，这点很好。但如果出口是有多线呢？理论上用联通的DNS解析的结果，用联通出口去测速，用电信的DNS解析的结果，用电信出口去测速，这个应该是最理想的。

**建议的方案**
1.可以在指定上游DNS时同时指定用来测速的源IP或者是源端口。这里举个smartdns和路由不在同一个机器上的例子。
1)上游服务器指定电信A，联通B
2)smartdns所在机器分配多个IP，IPA和IPB（或者不分配多个IP，而是在测速时指定不同的源端口）
3)测速电信A返回的结果时，指定源IP为IPA
4)测速联通B返回的结果时，指定源IP为IPB
5)在路由上设置策略路由，源IP为IPA时走电信出口，源IP为IPB时走联通出口。
6)smartdns知道应该用哪个出口访问哪个IP后，同时告知路由器，让它生成一个动态路由，后续
客户端实际访问这个IP时，路由也知道该走哪个出口。（方法比如有用一个特定的源端口及目标线路的源IP访问一下最快的IP，路由探测到源IP和源端口的组合后就会为这个最快的IP生成一个动态的策略路由。以上想法通过routeros都是实际可行的，如果smartdns和路由是一个机器的话，比如运行在op上，通过ipset应该更容易）

**Comment by pymumu** [comment]
方案还有细想一下。

但先看看有多少人希望这个功能把。

**Comment by colinhd8** [comment]
嗯，好的，如果有想法还可以再交流下。不过我觉得支持多线，才更有意义一点。否则用运营商DNS解析出来的IP一般情况下是最快的。

另外再补充一点，如果性能上可以接受，可以考虑对于每个解析回来的IP，用所有可用的出口IP都测速一遍（相当于出口IP和解析回来的IP作笛卡尔积），这样结果应该是最全的。

**Comment by pymumu** [comment]
现在主要是对国外网站有帮助，国内的话，用运营商的足够了。

**Comment by colinhd8** [comment]
嗯，这倒是。不过感觉国外的话，更应该用多线去探测下，谁是最快的。

**Comment by pymumu** [comment]
国外没那么大的差别，一般都是固定的那几个出口。
