### ISSUE TITLE
[请问] SmartDNS配置上游服务器的默认端口是什么

### ISSUE THREAD

**Issue by yykhysn** [pymumu/smartdns#195]
请问配置上游DNS服务器时，不指定端口的default端口是什么？

udp 53
tcp 53
tls 853
https 443

是这样的吗，还是别的端口号？

**Comment by pymumu** [comment]
对，不指定就是默认，就是你列的那些

**Comment by yykhysn** [comment]
请问Https服务器要如何配置？
        比如Quad9的Https服务器，就在ip处写上https://dns.quad9.net/dns-query?吗？

通用情形，我如何知道所配置的某个上游服务器是否正确？日志是否记录？

        感谢！

**Comment by pymumu** [comment]
最简单就是
```
server-https https://dns.quad9.net/dns-query
```
其他参数的话，根据需要配置。

**Comment by yykhysn** [comment]
请问openwrt的配置文件是在什么地方？

我通过Web Luci进行的配置，但/etc/smartdns/smartdns.conf只有什么都没配置，初始时全是注释说明的内容。

**Comment by fonlan** [comment]
你执行ps | grep smartdns就知道配置文件在哪儿了

**Comment by yykhysn** [comment]
非常感谢你们热心的回答。

除了Https外，所有其它类型的服务器配置也可以写host/域名形式吗，比如：
        UDP类型：server resolver1.opendns.com
        TLS类型：server-tls dns.google

IPv6的服务器这样写对吗，server [2400:da00::6666]

非常感谢！

**Comment by pymumu** [comment]
可以支持host和域名的形式，但要注意至少要保留一个IP地址的配置，否则就无法解析自己的域名了。
ipv6是那样配置。
