### ISSUE TITLE
smartdns在斐讯k3上不能运行,使用/usr/sbin/smartdns -h后输出信息，请大佬分析，谢谢！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#197]
![D8DDCD26B7E316EFC749BB2BBEBA2C91](https://user-images.githubusercontent.com/45259624/62424915-c3d9dd80-b707-11e9-9f7b-87b836468281.jpg)

**Comment by kkkgo** [comment]
你这个看不到有用的信息，你-c指定配置文件再-x看看输出吧

**Comment by zxlhhyccc** [comment]
> 你这个看不到有用的信息，你-c指定配置文件再-x看看输出吧

大佬重新编译了一个，搞定了，可以运行。。。。感谢大佬！
