### ISSUE TITLE
cache-size最大值是多少？能不能指定某些域名不缓存？

### ISSUE THREAD

**Issue by kkkgo** [pymumu/smartdns#198]
**需求应用场景**
希望知道cache-size的最大大小，比如dnsmasq官方说的是10000；
另外dnsmasq有no-negcache参数，对无结果的域名不缓存，不知道smartdns是否有这个功能/机制？
smartdns是否有限制并发呢？或者如何测试性能呢？
还有个需求就是希望有一些域名不缓存，直接转发到某台服务器（因为希望局域网内的一些域名修改后实时生效），转发是可以设置，如何设置这些域名不缓存呢？

**建议的方案**
实现上述场景建议的方案。暂无

**设备信息**
1. 设备信息（CPU，厂家）  
x86_64，E5 2680 8G
2. 固件信息

**Comment by pymumu** [comment]
1.
cache-size的意义是缓存的域名个数，不是内存大小，这点和dnsmasq不同。
cache-size单个域名占用内存在600字节左右，自己可以根据设备空闲内存计算设置最大值。
smartdns目前不会对没有结果的域名缓存，所以也没有这样的配置开关。

2.
对于并发，因为smartdns是异步的，只会启动4个固定的线程，这一块不用担心。
唯一要注意的是内存，大并发下，如果大量域名上游没有及时响应是需要占用内存的，一个请求大约1K内存，最长响应时间1s，只要考虑这1s内没有及时处理的请求数即可。
一般情况下，大压力应该能跑到5w qps，可能占用内存50M左右。
对于家用来说，smartdns完全是轻负载的。

3.
对于特定域名不缓存，现在版本无法完全支持，但可以通过特殊配置大致达到你的要求，采用域名分流功能，大致方案可以参考FAQ的6
https://github.com/pymumu/smartdns#faq

通过将对于后缀的域名，转发到特定的上游DNS。
cache时间那个，可以调整最大TTL时间，比如60s，让cache在60s内超时，时间可以缩短，也算是准实时了。
smartdns的cache时有超时机制的，超时时间采用的是DNS的TTL，通过rr-ttl-max参数可以配置最大时间。

但下个版本会支持一个新功能。
就是启动一个特殊查询端口，这个端口的请求，可以不缓存，不响应规则，转发给特定上游。

**Comment by kkkgo** [comment]
ttl好像是全局设置，不针对指定域名？新功能是要用非53端口才可以吗？

**Comment by pymumu** [comment]
新功能是另外一个端口或IP地址。

**Comment by kkkgo** [comment]
嗯，了解了。谢谢热心解答。

**Comment by pymumu** [comment]
或者，你可以在特定上游DNS那里，修改DNS的TTL时间，让域名快速超时。

一般无法做到即使生效的，因为客户端软件是先解析域名后拿到IP地址，IP地址会一直使用一段时间的。

**Comment by kkkgo** [comment]
还有个问题，预读取描述说到即将过期的时候会去读取，这个即将过期是多少时间呢？

**Comment by pymumu** [comment]
ttl过期的前3秒

**Comment by Ben56** [comment]
> cache-size的意义是缓存的域名个数，不是内存大小，这点和dnsmasq不同。 cache-size单个域名占用内存在600字节左右，自己可以根据设备空闲内存计算设置一个合理值。 smartdns目前不会对没有结果的域名缓存，所以也没有这样的配置开关。
> 
> 
> 对于并发，因为smartdns是异步的，只会启动4个固定的线程，这一块不用担心。 唯一要注意的是内存，大并发下，如果大量域名上游没有及时响应是需要占用内存的，一个请求大约1K内存，最长响应时间1s，只要考虑这1s内没有及时处理的请求数即可。 一般情况下，大压力应该能跑到5w qps，可能占用内存50M左右。 对于家用来说，smartdns完全是轻负载的。 另外，即使加了海量的域名规则，由于采用了高效的匹配算法，对性能基本无影响。域名匹配这一块，测试算法10w条规则，1ms的处理时间。
> 
> 
> 对于特定域名不缓存，现在版本无法完全支持，但可以通过特殊配置大致达到你的要求，采用域名分流功能，大致方案可以参考FAQ的6 https://github.com/pymumu/smartdns#faq
> 
> 通过将对应后缀的域名，转发到特定的上游DNS。 cache时间那个，可以调整最大TTL时间，比如60s，让cache在60s内超时，时间可以缩短，也算是准实时了。 smartdns的cache时有超时机制的，超时时间采用的是DNS的TTL，通过rr-ttl-max参数可以配置最大时间。
> 
> 但下个版本会支持一个新功能。 就是启动一个特殊查询端口，这个端口的请求，可以不缓存，不响应规则，转发给特定上游。

请问这个新功能做好了吗?我在最新版里好像没有找到

**Comment by PikuZheng** [comment]
> 请问这个新功能做好了吗?我在最新版里好像没有找到

快三年过去了。。。完全不缓存可以用bind的-no-cache参数

**Comment by Ben56** [comment]
> > 请问这个新功能做好了吗?我在最新版里好像没有找到
> 
> 快三年过去了。。。完全不缓存可以用bind的-no-cache参数

谢谢回答,还有个问题想请教一下
服务器端可以不用 53
但客户端一般必须用 53，因为没法告诉客户端不用 53,除了在客户机和服务器中间再加一个dns服务器转发还有别的方案吗?

**Comment by PikuZheng** [comment]
> 服务器端可以不用 53
> 但客户端一般必须用 53，因为没法告诉客户端不用 53,除了在客户机和服务器中间再加一个dns服务器转发还有别的方案吗?

端口映射
