### ISSUE TITLE
希望添加个安卓的二进制下载

### ISSUE THREAD

**Issue by cjjdaq** [pymumu/smartdns#2]
希望添加个安卓的二进制下载

**Comment by pymumu** [comment]
这个需求可能暂时无法满足。
andriod架构和标准linux不同，并且没有这个功能需要root权限，andriod下没法满足权限要求。
类似，andriod下的host文件也是没权限修改的，除非root手机，但这给手机带来安全问题。

所以，我的建议是：  
路由器开通DDNS服务，在路由器上安装vpn服务器。安卓手机安装VPN客户端。
然后手机VPN到路由器的网络，这样就可以使用smartdns解析，也有安全保障。

**Comment by cjjdaq** [comment]
主要是不支持监听tcp端口，安卓udp over tcp到路由上的dnsmasq,上级是smartdns,但不支持tco监听，所以暂时用不了

**Comment by pymumu** [comment]
dnsmasq上游是可以用udp的，可以试试

**Comment by cjjdaq** [comment]
在dnsmasq里使用server=/.bing.com/127.0.0.1#7910的方式，7910为smartdns的监听端口。所以无法强制udp。tcp请求，它就tcp到smartdns的tcp

**Comment by pymumu** [comment]
smartdns在设计上，是最前端的服务器，所以没考虑支持tcp查询。
smartdns要是放在后端，就失去了加速的意义。
所以，smartdns的配置，是支持将路由器默认的53端口，转发到smartdns服务器的，替换原有dnsmsaq的位置。
唯一差别就是和chinaDNS共存，这个场景，chinaDNS要在smartdns前面。

你的场景，dnsmasq主要用了什么功能？广告过滤？address参数，smartdns也是支持的。

**Comment by cjjdaq** [comment]
用的koolshare的固件，里面的ss插件和v2ray插件都是针对dnsmasq的，改为smartdns为主dns需要改动的东西比较多，而且貌似当前也不支持ipset，想改也没有办法的。smart的加速无非就是多ip的时候选择rts最小的。至于缓存交给谁是无所谓的。我的场景是安卓53udp->pdnsd(tcp_only)->ss-->openwrt->dnsmasq->国内直接114，国外用dnscrypt-proxy，现在是想把国内直接114替换为smartdns，只要smartdns支持tcp监听即可。

**Comment by pymumu** [comment]
考虑到smartdns是运行在近端的服务，tcp暂时不考虑支持。
但ipset，server参数，后面会规划进去。

**Comment by cjjdaq** [comment]
那么请关闭吧

**Comment by pymumu** [comment]
增加ipset，server功能。 
https://github.com/pymumu/smartdns/issues/3
