### ISSUE TITLE
查询贴吧IP错误

### ISSUE THREAD

**Issue by guaguagaga** [pymumu/smartdns#20]
大佬你好！
发现贴吧ip查询错误，解析到香港去了！

nslookup tieba.baidu.com
服务器:  Openwrt.lan
Address:  192.168.3.1
非权威应答:
名称:    post.n.shifen.com
Address:  103.235.46.139
Aliases:  tieba.baidu.com

当前IP | 103.235.46.139
地理位置 | 中国香港  baidu.com

**Comment by pymumu** [comment]
看一下你dns吧，
原理上返回的是最快的ip
但如果上游伪造ip，并且速度最快，那就会返回这个伪造IP了

所以
1.看上游dns是不是可信
2.将伪造ip加入不信任列表（bogus-nxdomain)

**Comment by pymumu** [comment]
我试了一下这个ip，贴吧是可以正常访问的，看上去应该是贴吧的cdn ip
，应该没什么问题

**Comment by pymumu** [comment]
https://www.abuseipdb.com/Whois/103.235.46.139
这里可以看到是百度的ip

**Comment by guaguagaga** [comment]
关键是很慢。。。

**Comment by pymumu** [comment]
ipv6错误可以不用关心。

如果想禁用的话，把DHCP里面IPV6前缀去掉。
