### ISSUE TITLE
Edgerouter lite路由器的系统应该用哪个安装？

### ISSUE THREAD

**Issue by JunShine** [pymumu/smartdns#200]
EdgerouterLite路由器，MIPS架构的，2.0x固件，应该是Debian系统吧。好像没有？没有opkg命令不能安装ipk呢

**Comment by kkkgo** [comment]
你把openwrt的ipk的下载下来解压，把解压出来的smartdns文件传上去就能运行了

**Comment by JunShine** [comment]
OK可以运行了，谢谢！
