### ISSUE TITLE
斐讯K3 Merlin固件下不能正常运行

### ISSUE THREAD

**Issue by Genkin** [pymumu/smartdns#204]
**问题现象**  
按照教程安装 Release 26 Special成功后重启，dns不响应。尝试过修改配置打开 log 却没有文件输出。
后又更换 Release 25，发现怎么调配置，dns 都为华硕本身，并且 log 不输出
1. 固件型号  
基于Asus RT-AC3100 固件移植的 3.0.0.4.384_K3_B4 Merlin
2. 运营商  
cmcc

1. 上游DNS配置。  
server-tls 1.0.0.1
2. 访问的域名。

**Comment by pymumu** [comment]
先检查进程在不在，然后再看工作模式是否配置能工作，可以切换工作模式看看。

**Comment by zxlhhyccc** [comment]
> **问题现象**
> 按照教程安装 Release 26 Special成功后重启，dns不响应。尝试过修改配置打开 log 却没有文件输出。
> 后又更换 Release 25，发现怎么调配置，dns 都为华硕本身，并且 log 不输出
> 
> 1. 固件型号
>    基于Asus RT-AC3100 固件移植的 3.0.0.4.384_K3_B4 Merlin
> 2. 运营商
>    cmcc
> 3. 上游DNS配置。
>    server-tls 1.0.0.1
> 4. 访问的域名。

不要安装了，你可以编译一个能运行的smartdns，我有可以运行的二进制文件

**Comment by zxlhhyccc** [comment]
> **问题现象**
> 按照教程安装 Release 26 Special成功后重启，dns不响应。尝试过修改配置打开 log 却没有文件输出。
> 后又更换 Release 25，发现怎么调配置，dns 都为华硕本身，并且 log 不输出
> 
> 1. 固件型号
>    基于Asus RT-AC3100 固件移植的 3.0.0.4.384_K3_B4 Merlin
> 2. 运营商
>    cmcc
> 3. 上游DNS配置。
>    server-tls 1.0.0.1
> 4. 访问的域名。

pymumu 大佬提供的可以运行的二进制文件。。。

**Comment by paldier** [comment]
静态编译版本有问题，arm下会报Illegal instruction

**Comment by pymumu** [comment]
[smartdns.1.2019.09.20-2058.arm-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/3636005/smartdns.1.2019.09.20-2058.arm-optware-all.ipk.zip)
先试试看把。

**Comment by paldier** [comment]
这个版本正常
