### ISSUE TITLE
请求提供 MIPS64 架构下的 Debian 包

### ISSUE THREAD

**Issue by helixzz** [pymumu/smartdns#205]
**需求应用场景**
UBNT EdgeRouter 系列路由器采用 Cavium Octeon 系列处理器。
其系统 “EdgeOS” 基于 Vyatta 构建，底层本质上是 Debian。
举例，EdgeOS 1.x -> 基于 Debian Wheezy。

**建议的方案**
请 Release 发版本时考虑增加对 mips 下的 deb 包。

**设备信息**
1. 设备信息（CPU，厂家）  
cpu model : Cavium Octeon III V0.2  FPU V0.0
isa : mips1 mips2 mips3 mips4 mips5 mips64r2

2. 固件信息
Linux *** 3.10.107-UBNT #1 SMP Tue Nov 20 18:32:51 UTC 2018 mips64 GNU/Linux

**Comment by pymumu** [comment]
[smartdns.1.2019.09.27-0015.mips-debian-all.deb.zip](https://github.com/pymumu/smartdns/files/3658816/smartdns.1.2019.09.27-0015.mips-debian-all.deb.zip)
没有mips64位的编译器，这个是32位的，你试试看能否用把。
