### ISSUE TITLE
server 8.8.8.8 -group test 写在哪个配置文件下？

### ISSUE THREAD

**Issue by cyouhi** [pymumu/smartdns#206]
luci 界面，域名地址下面写server 8.8.8.8 -group test，nameserver /.tk/test，本机nslookup：Name or service not known

/etc/config/smartdns下面写
config server
option enabled '1'
option name '1.0.0.1'
option ip '1.0.0.1'
option port '853'
option type 'tls'
option server_group 'test'

以上两种方式均无效，openwrt上去nslookup都是Name or service not known

**Comment by pymumu** [comment]
是这样配置的，具体参考
https://github.com/pymumu/smartdns#faq的6点

**Comment by cyouhi** [comment]
嗯，关键是不懂写在哪个conf文件下

Nick Peng <notifications@github.com>于2019年9月20日 周五21:07写道：

**Comment by pymumu** [comment]
界面上的所有配置最终都会聚合到一起的。所以挑选任何一个写都可以

nslookup都是Name or service not known
这个错误，你应该先排查smartdns是否正常工作，然后再看分流是否正常。
