### ISSUE TITLE
smartdns服务停止运行

### ISSUE THREAD

**Issue by Masstone** [pymumu/smartdns#207]
**问题现象**  
简要描述问题出现的现象
smartdns非人为触发停止运行

**运行环境**
1. 固件型号  
Koolshare LEDE 2.3.2
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
udp
119.29.29.29
192.168.88.1(路由lanip 内网域名需要)
10.237.28.10（内网需要）
tls
118.89.110.78:853 
1.1.1.1:853
8.8.8.8:853
https
https://cloudflare-dns.com/dns-query
https://dns.rubyfish.cn/dns-query

2. 访问的域名。  
未知

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[coredump.zip](https://github.com/pymumu/smartdns/files/3656090/coredump.zip)

**Comment by pymumu** [comment]
[smartdns.1.2019.09.26-2349.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/3658705/smartdns.1.2019.09.26-2349.x86_64-openwrt-all.ipk.zip)
尝试一下这个把。
