### ISSUE TITLE
对speed-check-mode算法的疑问

### ISSUE THREAD

**Issue by supppig** [pymumu/smartdns#209]
**需求应用场景**
    今天碰到一个奇怪的问题，因为路由正在调试单IP限速，多了很多变量，所以定位问题用了一个下午，晕死。。。
    问题是这样的，广州电信用的默认DNS，在某些域名上存在故障。如今天的www.iqiyipic.com这个域名，广州电信DNS返回一个ping很低的IP，但是这个IP用 “curl https://www.iqiyipic.com” 会timeout，而114DNS会返回一个ping相当高点的IP，但是curl能返回正确结果。
    正巧smartdns今天更新了一个speed-check-mode，我觉得非常不错，但是对于算法没有明确说。所以想问问开发者。

如以下场景，对一个域名的解析，返回A、B和C这3个IP，

speed-check-mode设置为：tcp:80,tcp:443,ping 
如果ABC的数据如下：

IP | Tcp80 | Tcp443 | ping
-- | -- | -- | --
A | 超时 | 超时 | 20
B | 50 | 55 | 40
C | 60 | 35 | 30

    那么，smartdns会返回哪个IP呢？
另外我还想问一下，对于我的设置tcp:80,tcp:443,ping ，对于域名是2个tcp和1个ping同时异步并发检测，还是先尝试tcp80,有结果后立即返回，都不成功就继续尝试tcp443，失败继续ping，还是用什么其他算法呢？

**设备信息**
1. newifi2 D1 （MT7621， mipsle）  

2. LEDE

**Comment by pymumu** [comment]
目前只支持配置两个，是先用第一个，第一个失效才使用第二个。

对于明确想忽略某些IP地址，可以使用
ignore-ip 1.2.3.4/16

**Comment by supppig** [comment]
感谢解答。
那我改改配置。。。
这软件越来越强大了，谢谢开发者~~~
另我也不知道具体有哪些域名会失效，这问题有点烦。。。貌似应该是服务器的缓存cdn出了问题。

**Comment by yykhysn** [comment]
speed-check-mode ping,tcp:none  是不做tcp测速吗

**Comment by pymumu** [comment]
speed-check-mode none
才是不做测速

**Comment by yyysuo** [comment]
> 目前只支持配置两个，是先用第一个，第一个失效才使用第二个。
> 
> 对于明确想忽略某些IP地址，可以使用
> ignore-ip 1.2.3.4/16

您好，想请教一下，现在支持3个检测方式了吗？如果配置了3个，会发生什么问题？

**Comment by pymumu** [comment]
最多两个生效，后门的都是不生效的。上述设置，只是用tcp连接，ping是失效的。

**Comment by realconnor** [comment]
> speed-check-mode none
> 才是不做测速

那在none模式下，是相当于dnsmasq的allserver，并发请求，取最先返回的结果；还是轮询？

**Comment by zhaoliang1224** [comment]
> 

我也想知道，现在最新版本是否支持三个测试。
