### ISSUE TITLE
smartdns崩溃，不产生日志

### ISSUE THREAD

**Issue by j853864523** [pymumu/smartdns#210]
**问题现象**  
/var/log/smrtdns.log文件不存在
路由器系统日志显示
Sat Nov  2 22:47:59 2019 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash
Sat Nov  2 22:50:41 2019 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash
Sat Nov  2 22:54:54 2019 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash
Sat Nov  2 23:13:20 2019 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash
**运行环境**
架构 | MediaTek MT7621 ver:1 eco:3 x 4
固件版本 | OpenWrt R9.10.10 / LuCI Master (git-19.290.35777-337b74d)
内核版本 | 4.14.149
使用最11.02版本的smartdns 
2. 运营商 
移动 
**重现步骤**
1. 上游DNS配置。  
server-name smartdns
bind :6053
cache-size 1024
rr-ttl-min 600
rr-ttl-max 86400
log-size 64K
log-num 1
log-level error
server-tcp 114.115.240.175:9090  
server 119.29.29.29  
server 117.50.10.10  
server 1.2.4.8  
server 223.5.5.5  
server 180.76.76.76  
server 1.0.0.1  
server 8.8.8.8  
server 9.9.9.9  
server 208.67.220.220  
server 185.222.222.222  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

2. 访问的域名。  
未知
**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
无smartdns.log文件
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
看看程序安装对版本没有
执行下面命令，看看有没有输出。
/usr/sbin/smartdns -v

**Comment by j853864523** [comment]
/usr/sbin/smartdns: line 1: syntax error: unexpected "("

**Comment by j853864523** [comment]
sorry，好像是版本安装错了，换路由器了，结果好像还按照之前的架构选择的安装包
