### ISSUE TITLE
OpenWrt上的SmartDNS如果使用“重定向53端口...”模式，路由器本身ip无法联网

### ISSUE THREAD

**Issue by RodmanWang** [pymumu/smartdns#212]
OpenWrt x86
如果使用“重定向53端口...”模式，其他设置都没问题了，ip6tables-mod-nat也安装了，但路由器本身ip无法联网，路由器下连接的机器都可以了，这样导致路由本身无法更新插件和校队时间等，请教怎么弄，谢谢，水平较差，帮忙指导下，谢谢大佬！

**Comment by pymumu** [comment]
ip6tables -t nat -A PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $SMARTDNS_PORT 
ip6tables -t nat -A PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $SMARTDNS_PORT 
重定向就这两个iptable规则，你可以查看下看看有没有配置到系统中

不行的话，使用作为dnsmasq的上游应该没有问题，效果上是差不多的。

**Comment by RodmanWang** [comment]
好的，谢谢
