### ISSUE TITLE
使用systemd启动服务时出现Can't open PID file /run/smartdns.pid

### ISSUE THREAD

**Issue by zlowly** [pymumu/smartdns#213]
**问题现象**  
当使用较大的smartdns.conf配置文件时（文件超过32k），systemd启动smartdns的日志中会出现无法打开PID文件的出错信息
systemd[1]: Starting smart dns server...
systemd[1]: smartdns.service: Can't open PID file /run/smartdns.pid (yet?) after start: No such file or directory
systemd[1]: Started smart dns server.
但并不影响域名解析功能的正常使用。而使用原来缺省smartdns.conf没有此问题。

**运行环境**
1. 固件型号  
x86_64
archlinux

**重现步骤**
1. 根据gfwlist配置出含大量域名的nameserver和ipset的conf配置  

2. systemctl start smartdns.service

**Comment by pymumu** [comment]
[smartdns.1.2019.11.07-0001.x86_64-all.tar.gz](https://github.com/pymumu/smartdns/files/3815470/smartdns.1.2019.11.07-0001.x86_64-all.tar.gz)
可以验证下看看。

**Comment by zlowly** [comment]
已验证smartdns.1.2019.11.07-0001.x86_64-all.tar.gz这个版本没有出现此错误信息了。
