### ISSUE TITLE
指定域名解析IP崩溃的时候，可以调用上游DNS继续解析

### ISSUE THREAD

**Issue by hailuoahaheng** [pymumu/smartdns#214]
测试了一下，如果通过address指定了某个域名的解析（已知解析出来的IP访问速度最佳），但是当此解析IP无法访问的时候，发现所配置的上游DNS此时也不能解析这个域名，仍用特指解析记录。因此想着：是否可以：优先匹配特指解析记录，一旦解析IP出现问题，从上游DNS中寻找最佳解析IP

**Comment by pymumu** [comment]
不会做这个需求。
