### ISSUE TITLE
Arch Linux 无法安装

### ISSUE THREAD

**Issue by nncy** [pymumu/smartdns#215]
**问题现象**  
在Arch linux 系统无法安装。显示i:
install: failed to access '/etc/init.d': No such file or directory
**运行环境**
Arch Linux
**信息收集**  
![smartdns](https://user-images.githubusercontent.com/19932520/68356804-441c3e80-014e-11ea-8f48-77caa1f9cca5.png)

**Comment by pymumu** [comment]
[smartdns.1.2019.11.07-2257.x86_64-all.tar.gz](https://github.com/pymumu/smartdns/files/3820237/smartdns.1.2019.11.07-2257.x86_64-all.tar.gz)
测试下看看把

**Comment by nncy** [comment]
已安装，测试正常，谢谢
