### ISSUE TITLE
TCP查询能否通过socks代理

### ISSUE THREAD

**Issue by Anyfc** [pymumu/smartdns#217]
**需求应用场景**
请描述需求应用的场景和方式。
目前使用的是clash在N1上做旁路由，smartdns在OpenWrt上做clash上游DNS，OpenWrt本身没有代理，smartdns里使用8888的tls，虽然能用，但是没有使用到clash上的代理，就有可能造成smartdns解析出来的ip离代理服务器过远。

**建议的方案**
实现上述场景建议的方案。
建议：增加socke5之类的，将8888或其他国外的DNS通过隧道转发出去
例如将8888通过 clash上的Socks5， 转发出去
**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by lemoeo** [comment]
我也有这个需求，最近通过搜索，好像可以通过iptables转发来实现将本机流量转发到Clash，但是这样将会有个问题，就是Clash出去的流量就会被转发给它自己，就会造成回环。解决办法也有几种，比如给Clash的流量打上mark，本机转发的时候就屏蔽掉带mark标记的；另一种办法就是Clash用一个单独的用户比如clashuser运行，Iptables转发本地流量的时候屏蔽掉clashuser用户的流量。好像是这么回事，具体我也不太明白，感觉实现起来也挺麻烦的。如果可以在SmartDNS中设置 http / socks 代理就比较方便了

**Comment by pymumu** [comment]
最新代码已经支持。
