### ISSUE TITLE
smartdns能否防劫持防污染

### ISSUE THREAD

**Issue by garypang13** [pymumu/smartdns#218]
请问smartdns是否能防劫持防污染,同时添加了国内DNS以及TLS,TCP协议的国外DNS,在查询被污染的域名时smartdns能否返回正确的ip. 谢谢

**Comment by pymumu** [comment]
发一下配置
/etc/config/smartdns

还有：
/var/etc/smartdns/smartdns.conf

**Comment by garypang13** [comment]
> 发一下配置
> /etc/config/smartdns
> 
> 还有：
> /var/etc/smartdns/smartdns.conf
> 
> DNS上游服务器，至少需要配置一个IP地址的DNS，其他都可以是域名。

感谢,https,tls无效问题已经解决了,升级到最新版,使用https协议 服务器Ip需要加上https://,使用域名需要至少配置一个有效的IP地址的DNS,
关于防劫持防污染问题,不知道smartdns是否有相关筛选机制,还是只能通过分组分流解决,谢谢.

**Comment by pymumu** [comment]
搜索历史issue
