### ISSUE TITLE
使用smartdns访问google.com返回被污染的dns解析

### ISSUE THREAD

**Issue by nivrrex** [pymumu/smartdns#219]
**问题现象**  
使用smartdns访问google.com返回被污染的dns解析

**运行环境**
1. 固件型号  
Release 27 Special

2. 运营商  
移动

**重现步骤**
1. 上游DNS配置。  
cat /var/etc/smartdns/smartdns.conf 
server-name smartdns
bind :6053
cache-size 10000
rr-ttl-min 300
log-size 64K
log-num 1
log-level error
server 114.114.115.115  -group china -blacklist-ip -check-edns
server 223.6.6.6  -group china -blacklist-ip -check-edns
server 210.2.4.8  -group china -blacklist-ip -check-edns
server-tcp 8.8.4.4  -group fanqiang -blacklist-ip 
server-tcp 208.67.222.222:5353  -group fanqiang -blacklist-ip 
server-tcp 1.0.0.1  -group fanqiang -blacklist-ip 
server-tcp 80.80.80.80  -group fanqiang -blacklist-ip 
server-tcp 185.222.222.222  -group fanqiang -blacklist-ip 
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

cat /etc/config/smartdns 

config smartdns
        option enabled '1'
        option server_name 'smartdns'
        option ipv6_server '0'
        option dualstack_ip_selection '0'
        option prefetch_domain '0'
        option rr_ttl_min '300'
        option coredump '0'
        option redirect 'redirect'
        option port '6053'
        option tcp_server '0'
        option cache_size '10000'
        option seconddns_port '7053'
        option seconddns_tcp_server '1'
        option seconddns_no_speed_check '0'
        option seconddns_no_rule_addr '0'
        option seconddns_no_rule_nameserver '0'
        option seconddns_no_rule_ipset '0'
        option seconddns_no_rule_soa '0'
        option seconddns_no_dualstack_selection '0'
        option seconddns_no_cache '0'
        list old_redirect 'redirect'
        list old_port '6053'
        list old_enabled '1'

config server
        option enabled '1'
        option blacklist_ip '1'
        option ip '114.114.115.115'
        option server_group 'china'
        option name '114 DNS'
        option type 'udp'
        option addition_arg '-check-edns'

config server
        option enabled '1'
        option blacklist_ip '1'
        option type 'udp'
        option ip '223.6.6.6'
        option name 'ali DNS'
        option server_group 'china'
        option addition_arg '-check-edns'

config server
        option enabled '1'
        option blacklist_ip '1'
        option type 'udp'
        option name 'CNNIC DNS'
        option ip '210.2.4.8'
        option server_group 'china'
        option addition_arg '-check-edns'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Google DNS'
        option ip '8.8.4.4'
        option type 'tcp'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option type 'tcp'
        option name 'Open DNS'
        option ip '208.67.222.222'
        option port '5353'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Cloudflare DNS'
        option ip '1.0.0.1'
        option type 'tcp'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Freenom DNS'
        option ip '80.80.80.80'
        option type 'tcp'

config server
        option enabled '1'
        option blacklist_ip '1'
        option name 'DNS.sb DNS'
        option ip '185.222.222.222'
        option server_group 'fanqiang'
        option type 'tcp'

2. 访问的域名。  
www.google.com

问题描述：
dig www.google.com
没有返回正常的google.com域名ip地址，而是返回了
31.13.69.129
69.171.227.37
这种应该是被污染的ip
但是如果使用dig www.google.com @8.8.8.8 +tcp，则可以返回正常的ip地址
请问是我的配置有问题，还是其它原因？

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
优先使用tls或https，check-edns不要对国内配置，国内的应用ip黑名单

**Comment by nivrrex** [comment]
cat /etc/config/smartdns 

config smartdns
        option enabled '1'
        option server_name 'smartdns'
        option ipv6_server '0'
        option dualstack_ip_selection '0'
        option prefetch_domain '0'
        option coredump '0'
        option redirect 'redirect'
        option port '6053'
        option tcp_server '0'
        option seconddns_port '7053'
        option seconddns_tcp_server '1'
        option seconddns_no_speed_check '0'
        option seconddns_no_rule_addr '0'
        option seconddns_no_rule_nameserver '0'
        option seconddns_no_rule_ipset '0'
        option seconddns_no_rule_soa '0'
        option seconddns_no_dualstack_selection '0'
        option seconddns_no_cache '0'
        option cache_size '0'
        option rr_ttl_min '0'
        list old_redirect 'redirect'
        list old_port '6053'
        list old_enabled '1'

config server
        option enabled '1'
        option blacklist_ip '1'
        option ip '114.114.115.115'
        option server_group 'china'
        option name '114 DNS'
        option type 'udp'

config server
        option enabled '1'
        option blacklist_ip '1'
        option type 'udp'
        option ip '223.6.6.6'
        option name 'ali DNS'
        option server_group 'china'

config server
        option enabled '1'
        option blacklist_ip '1'
        option type 'udp'
        option name 'CNNIC DNS'
        option ip '210.2.4.8'
        option server_group 'china'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Google DNS'
        option ip '8.8.4.4'
        option type 'tls'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Open DNS'
        option ip '208.67.222.222'
        option port '5353'
        option type 'tcp'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Cloudflare DNS'
        option ip '1.0.0.1'
        option type 'tls'

config server
        option enabled '1'
        option blacklist_ip '1'
        option server_group 'fanqiang'
        option name 'Freenom DNS'
        option ip '80.80.80.80'
        option type 'tls'

config server
        option enabled '1'
        option blacklist_ip '1'
        option name 'DNS.sb DNS'
        option ip '185.222.222.222'
        option server_group 'fanqiang'
        option type 'tls'

cat /var/etc/smartdns/smartdns.conf 
server-name smartdns
bind :6053
cache-size 0
rr-ttl-min 0
log-size 64K
log-num 1
log-level error
server 114.114.115.115  -group china -blacklist-ip 
server 223.6.6.6  -group china -blacklist-ip 
server 210.2.4.8  -group china -blacklist-ip 
server-tls 8.8.4.4  -group fanqiang -blacklist-ip 
server-tcp 208.67.222.222:5353  -group fanqiang -blacklist-ip 
server-tls 1.0.0.1  -group fanqiang -blacklist-ip 
server-tls 80.80.80.80  -group fanqiang -blacklist-ip 
server-tls 185.222.222.222  -group fanqiang -blacklist-ip 
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

还是会出来随机的被污染IP地址
69.171.235.16
31.13.71.7
这些

**Comment by pymumu** [comment]
blackip要配置地址范围，还有要确保tls的那几个能正常工作

**Comment by nivrrex** [comment]
是我失误了，上次卸载软件时，把blacklist-ip.conf文件删除了，导致返回的污染ip未能识别，重新添加后，基本上解析的就是正确的ip地址了

分享下我收集的blacklist地址吧

cat /etc/smartdns/blacklist-ip.conf 
# Add IP blacklist which you want to filtering from some DNS server here.
# The example below filtering ip from the result of DNS server which is configured with -blacklist-ip.
# blacklist-ip [ip/subnet]
# blacklist-ip 254.0.0.1/16
blacklist-ip 4.36.66.178
blacklist-ip 8.7.198.45
blacklist-ip 31.13.64.1
blacklist-ip 31.13.64.33
blacklist-ip 31.13.64.49
blacklist-ip 31.13.65.1
blacklist-ip 31.13.65.17
blacklist-ip 31.13.65.18
blacklist-ip 31.13.66.1
blacklist-ip 31.13.66.23
blacklist-ip 31.13.66.6
blacklist-ip 31.13.68.1
blacklist-ip 31.13.68.22
blacklist-ip 31.13.69.129
blacklist-ip 31.13.69.160
blacklist-ip 31.13.69.33
blacklist-ip 31.13.69.86
blacklist-ip 31.13.70.1
blacklist-ip 31.13.70.20
blacklist-ip 31.13.71.23
blacklist-ip 31.13.71.7
blacklist-ip 31.13.72.1
blacklist-ip 31.13.72.17
blacklist-ip 31.13.72.23
blacklist-ip 31.13.72.34
blacklist-ip 31.13.72.54
blacklist-ip 31.13.73.1
blacklist-ip 31.13.73.17
blacklist-ip 31.13.73.23
blacklist-ip 31.13.74.1
blacklist-ip 31.13.74.17
blacklist-ip 31.13.75.17
blacklist-ip 31.13.75.18
blacklist-ip 31.13.76.16
blacklist-ip 31.13.76.8
blacklist-ip 31.13.77.33
blacklist-ip 31.13.77.55
blacklist-ip 31.13.78.65
blacklist-ip 31.13.78.66
blacklist-ip 31.13.79.1
blacklist-ip 31.13.79.17
blacklist-ip 31.13.80.1
blacklist-ip 31.13.80.17
blacklist-ip 31.13.81.1
blacklist-ip 31.13.81.17
blacklist-ip 31.13.82.1
blacklist-ip 31.13.82.17
blacklist-ip 31.13.82.23
blacklist-ip 31.13.83.1
blacklist-ip 31.13.83.16
blacklist-ip 31.13.83.8
blacklist-ip 31.13.84.1
blacklist-ip 31.13.84.16
blacklist-ip 31.13.84.8
blacklist-ip 31.13.85.1
blacklist-ip 31.13.85.16
blacklist-ip 31.13.85.8
blacklist-ip 31.13.86.1
blacklist-ip 31.13.86.16
blacklist-ip 31.13.86.8
blacklist-ip 31.13.97.245
blacklist-ip 31.13.97.248
blacklist-ip 37.61.54.158
blacklist-ip 46.82.174.68
blacklist-ip 59.24.3.173
blacklist-ip 64.13.192.74
blacklist-ip 64.13.192.76
blacklist-ip 64.13.232.149
blacklist-ip 64.33.88.161
blacklist-ip 64.33.99.47
blacklist-ip 64.66.163.251
blacklist-ip 65.104.202.252
blacklist-ip 65.160.219.113
blacklist-ip 66.45.252.237
blacklist-ip 66.220.146.94
blacklist-ip 66.220.147.11
blacklist-ip 66.220.147.44
blacklist-ip 66.220.147.47
blacklist-ip 66.220.149.18
blacklist-ip 66.220.149.32
blacklist-ip 66.220.149.99
blacklist-ip 66.220.151.20
blacklist-ip 66.220.152.17
blacklist-ip 66.220.152.28
blacklist-ip 66.220.155.12
blacklist-ip 66.220.155.14
blacklist-ip 66.220.158.32
blacklist-ip 67.15.100.252
blacklist-ip 67.15.129.210
blacklist-ip 67.228.37.26
blacklist-ip 67.228.74.123
blacklist-ip 67.228.102.32
blacklist-ip 67.228.126.62
blacklist-ip 67.228.221.221
blacklist-ip 67.228.235.91
blacklist-ip 67.228.235.93
blacklist-ip 69.63.176.143
blacklist-ip 69.63.176.15
blacklist-ip 69.63.176.59
blacklist-ip 69.63.178.13
blacklist-ip 69.63.180.173
blacklist-ip 69.63.181.11
blacklist-ip 69.63.181.12
blacklist-ip 69.63.184.14
blacklist-ip 69.63.184.142
blacklist-ip 69.63.184.30
blacklist-ip 69.63.186.30
blacklist-ip 69.63.186.31
blacklist-ip 69.63.187.12
blacklist-ip 69.63.189.16
blacklist-ip 69.63.190.26
blacklist-ip 69.171.224.12
blacklist-ip 69.171.224.40
blacklist-ip 69.171.224.85
blacklist-ip 69.171.225.13
blacklist-ip 69.171.227.37
blacklist-ip 69.171.228.20
blacklist-ip 69.171.228.74
blacklist-ip 69.171.229.11
blacklist-ip 69.171.229.28
blacklist-ip 69.171.229.73
blacklist-ip 69.171.230.18
blacklist-ip 69.171.232.21
blacklist-ip 69.171.233.24
blacklist-ip 69.171.233.33
blacklist-ip 69.171.233.37
blacklist-ip 69.171.234.18
blacklist-ip 69.171.234.29
blacklist-ip 69.171.234.48
blacklist-ip 69.171.235.101
blacklist-ip 69.171.235.16
blacklist-ip 69.171.235.64
blacklist-ip 69.171.237.16
blacklist-ip 69.171.237.26
blacklist-ip 69.171.239.11
blacklist-ip 69.171.240.27
blacklist-ip 69.171.242.11
blacklist-ip 69.171.242.30
blacklist-ip 69.171.244.11
blacklist-ip 69.171.244.12
blacklist-ip 69.171.244.15
blacklist-ip 69.171.245.49
blacklist-ip 69.171.245.53
blacklist-ip 69.171.245.84
blacklist-ip 69.171.246.9
blacklist-ip 69.171.247.20
blacklist-ip 69.171.247.32
blacklist-ip 69.171.247.71
blacklist-ip 69.171.248.112
blacklist-ip 69.171.248.128
blacklist-ip 69.171.248.65
blacklist-ip 72.14.205.104
blacklist-ip 72.14.205.99
blacklist-ip 74.86.118.24
blacklist-ip 74.86.12.172
blacklist-ip 74.86.12.173
blacklist-ip 74.86.142.55
blacklist-ip 74.86.151.162
blacklist-ip 74.86.151.167
blacklist-ip 74.86.17.48
blacklist-ip 74.86.226.234
blacklist-ip 74.86.228.110
blacklist-ip 74.86.235.236
blacklist-ip 74.86.3.208
blacklist-ip 75.126.115.192
blacklist-ip 75.126.124.162
blacklist-ip 75.126.135.131
blacklist-ip 75.126.150.210
blacklist-ip 75.126.164.178
blacklist-ip 75.126.2.43
blacklist-ip 75.126.215.88
blacklist-ip 75.126.33.156
blacklist-ip 78.16.49.15
blacklist-ip 88.191.249.182
blacklist-ip 88.191.249.183
blacklist-ip 88.191.253.157
blacklist-ip 93.46.8.89
blacklist-ip 128.121.126.139
blacklist-ip 159.106.121.75
blacklist-ip 169.132.13.103
blacklist-ip 173.252.73.48
blacklist-ip 173.252.100.21
blacklist-ip 173.252.100.32
blacklist-ip 173.252.102.16
blacklist-ip 173.252.102.241
blacklist-ip 173.252.103.64
blacklist-ip 173.252.110.21
blacklist-ip 174.36.196.242
blacklist-ip 174.36.228.136
blacklist-ip 174.37.54.20
blacklist-ip 174.37.154.236
blacklist-ip 174.37.175.229
blacklist-ip 192.67.198.6
blacklist-ip 199.16.156.40
blacklist-ip 199.16.156.7
blacklist-ip 199.16.158.190
blacklist-ip 199.59.148.14
blacklist-ip 199.59.148.140
blacklist-ip 199.59.148.209
blacklist-ip 199.59.148.97
blacklist-ip 199.59.149.136
blacklist-ip 199.59.149.244
blacklist-ip 199.59.150.11
blacklist-ip 199.59.150.49
blacklist-ip 202.106.1.2
blacklist-ip 202.181.7.85
blacklist-ip 203.98.7.65
blacklist-ip 203.161.230.171
blacklist-ip 205.186.152.122
blacklist-ip 207.12.88.98
blacklist-ip 208.43.170.231
blacklist-ip 208.43.237.140
blacklist-ip 208.56.31.43
blacklist-ip 208.101.21.43
blacklist-ip 208.101.48.171
blacklist-ip 208.101.60.87
blacklist-ip 209.36.73.33
blacklist-ip 209.145.54.50
blacklist-ip 209.220.30.174
blacklist-ip 211.94.66.147
blacklist-ip 213.169.251.35
blacklist-ip 216.221.188.182
blacklist-ip 216.234.179.13
blacklist-ip 243.185.187.39

**Comment by lalasou** [comment]
这个ip 是怎么来的？




> 是我失误了，上次卸载软件时，把blacklist-ip.conf文件删除了，导致返回的污染ip未能识别，重新添加后，基本上解析的就是正确的ip地址了
> 
> 
> 
> 分享下我收集的blacklist地址吧
> 
> 
> 
> cat /etc/smartdns/blacklist-ip.conf 
> 
> # Add IP blacklist which you want to filtering from some DNS server here.
> 
> # The example below filtering ip from the result of DNS server which is configured with -blacklist-ip.
> 
> # blacklist-ip [ip/subnet]
> 
> # blacklist-ip 254.0.0.1/16
> 
> blacklist-ip 4.36.66.178
> 
> blacklist-ip 8.7.198.45
> 
> blacklist-ip 31.13.64.1
> 
> blacklist-ip 31.13.64.33
> 
> blacklist-ip 31.13.64.49
> 
> blacklist-ip 31.13.65.1
> 
> blacklist-ip 31.13.65.17
> 
> blacklist-ip 31.13.65.18
> 
> blacklist-ip 31.13.66.1
> 
> blacklist-ip 31.13.66.23
> 
> blacklist-ip 31.13.66.6
> 
> blacklist-ip 31.13.68.1
> 
> blacklist-ip 31.13.68.22
> 
> blacklist-ip 31.13.69.129
> 
> blacklist-ip 31.13.69.160
> 
> blacklist-ip 31.13.69.33
> 
> blacklist-ip 31.13.69.86
> 
> blacklist-ip 31.13.70.1
> 
> blacklist-ip 31.13.70.20
> 
> blacklist-ip 31.13.71.23
> 
> blacklist-ip 31.13.71.7
> 
> blacklist-ip 31.13.72.1
> 
> blacklist-ip 31.13.72.17
> 
> blacklist-ip 31.13.72.23
> 
> blacklist-ip 31.13.72.34
> 
> blacklist-ip 31.13.72.54
> 
> blacklist-ip 31.13.73.1
> 
> blacklist-ip 31.13.73.17
> 
> blacklist-ip 31.13.73.23
> 
> blacklist-ip 31.13.74.1
> 
> blacklist-ip 31.13.74.17
> 
> blacklist-ip 31.13.75.17
> 
> blacklist-ip 31.13.75.18
> 
> blacklist-ip 31.13.76.16
> 
> blacklist-ip 31.13.76.8
> 
> blacklist-ip 31.13.77.33
> 
> blacklist-ip 31.13.77.55
> 
> blacklist-ip 31.13.78.65
> 
> blacklist-ip 31.13.78.66
> 
> blacklist-ip 31.13.79.1
> 
> blacklist-ip 31.13.79.17
> 
> blacklist-ip 31.13.80.1
> 
> blacklist-ip 31.13.80.17
> 
> blacklist-ip 31.13.81.1
> 
> blacklist-ip 31.13.81.17
> 
> blacklist-ip 31.13.82.1
> 
> blacklist-ip 31.13.82.17
> 
> blacklist-ip 31.13.82.23
> 
> blacklist-ip 31.13.83.1
> 
> blacklist-ip 31.13.83.16
> 
> blacklist-ip 31.13.83.8
> 
> blacklist-ip 31.13.84.1
> 
> blacklist-ip 31.13.84.16
> 
> blacklist-ip 31.13.84.8
> 
> blacklist-ip 31.13.85.1
> 
> blacklist-ip 31.13.85.16
> 
> blacklist-ip 31.13.85.8
> 
> blacklist-ip 31.13.86.1
> 
> blacklist-ip 31.13.86.16
> 
> blacklist-ip 31.13.86.8
> 
> blacklist-ip 31.13.97.245
> 
> blacklist-ip 31.13.97.248
> 
> blacklist-ip 37.61.54.158
> 
> blacklist-ip 46.82.174.68
> 
> blacklist-ip 59.24.3.173
> 
> blacklist-ip 64.13.192.74
> 
> blacklist-ip 64.13.192.76
> 
> blacklist-ip 64.13.232.149
> 
> blacklist-ip 64.33.88.161
> 
> blacklist-ip 64.33.99.47
> 
> blacklist-ip 64.66.163.251
> 
> blacklist-ip 65.104.202.252
> 
> blacklist-ip 65.160.219.113
> 
> blacklist-ip 66.45.252.237
> 
> blacklist-ip 66.220.146.94
> 
> blacklist-ip 66.220.147.11
> 
> blacklist-ip 66.220.147.44
> 
> blacklist-ip 66.220.147.47
> 
> blacklist-ip 66.220.149.18
> 
> blacklist-ip 66.220.149.32
> 
> blacklist-ip 66.220.149.99
> 
> blacklist-ip 66.220.151.20
> 
> blacklist-ip 66.220.152.17
> 
> blacklist-ip 66.220.152.28
> 
> blacklist-ip 66.220.155.12
> 
> blacklist-ip 66.220.155.14
> 
> blacklist-ip 66.220.158.32
> 
> blacklist-ip 67.15.100.252
> 
> blacklist-ip 67.15.129.210
> 
> blacklist-ip 67.228.37.26
> 
> blacklist-ip 67.228.74.123
> 
> blacklist-ip 67.228.102.32
> 
> blacklist-ip 67.228.126.62
> 
> blacklist-ip 67.228.221.221
> 
> blacklist-ip 67.228.235.91
> 
> blacklist-ip 67.228.235.93
> 
> blacklist-ip 69.63.176.143
> 
> blacklist-ip 69.63.176.15
> 
> blacklist-ip 69.63.176.59
> 
> blacklist-ip 69.63.178.13
> 
> blacklist-ip 69.63.180.173
> 
> blacklist-ip 69.63.181.11
> 
> blacklist-ip 69.63.181.12
> 
> blacklist-ip 69.63.184.14
> 
> blacklist-ip 69.63.184.142
> 
> blacklist-ip 69.63.184.30
> 
> blacklist-ip 69.63.186.30
> 
> blacklist-ip 69.63.186.31
> 
> blacklist-ip 69.63.187.12
> 
> blacklist-ip 69.63.189.16
> 
> blacklist-ip 69.63.190.26
> 
> blacklist-ip 69.171.224.12
> 
> blacklist-ip 69.171.224.40
> 
> blacklist-ip 69.171.224.85
> 
> blacklist-ip 69.171.225.13
> 
> blacklist-ip 69.171.227.37
> 
> blacklist-ip 69.171.228.20
> 
> blacklist-ip 69.171.228.74
> 
> blacklist-ip 69.171.229.11
> 
> blacklist-ip 69.171.229.28
> 
> blacklist-ip 69.171.229.73
> 
> blacklist-ip 69.171.230.18
> 
> blacklist-ip 69.171.232.21
> 
> blacklist-ip 69.171.233.24
> 
> blacklist-ip 69.171.233.33
> 
> blacklist-ip 69.171.233.37
> 
> blacklist-ip 69.171.234.18
> 
> blacklist-ip 69.171.234.29
> 
> blacklist-ip 69.171.234.48
> 
> blacklist-ip 69.171.235.101
> 
> blacklist-ip 69.171.235.16
> 
> blacklist-ip 69.171.235.64
> 
> blacklist-ip 69.171.237.16
> 
> blacklist-ip 69.171.237.26
> 
> blacklist-ip 69.171.239.11
> 
> blacklist-ip 69.171.240.27
> 
> blacklist-ip 69.171.242.11
> 
> blacklist-ip 69.171.242.30
> 
> blacklist-ip 69.171.244.11
> 
> blacklist-ip 69.171.244.12
> 
> blacklist-ip 69.171.244.15
> 
> blacklist-ip 69.171.245.49
> 
> blacklist-ip 69.171.245.53
> 
> blacklist-ip 69.171.245.84
> 
> blacklist-ip 69.171.246.9
> 
> blacklist-ip 69.171.247.20
> 
> blacklist-ip 69.171.247.32
> 
> blacklist-ip 69.171.247.71
> 
> blacklist-ip 69.171.248.112
> 
> blacklist-ip 69.171.248.128
> 
> blacklist-ip 69.171.248.65
> 
> blacklist-ip 72.14.205.104
> 
> blacklist-ip 72.14.205.99
> 
> blacklist-ip 74.86.118.24
> 
> blacklist-ip 74.86.12.172
> 
> blacklist-ip 74.86.12.173
> 
> blacklist-ip 74.86.142.55
> 
> blacklist-ip 74.86.151.162
> 
> blacklist-ip 74.86.151.167
> 
> blacklist-ip 74.86.17.48
> 
> blacklist-ip 74.86.226.234
> 
> blacklist-ip 74.86.228.110
> 
> blacklist-ip 74.86.235.236
> 
> blacklist-ip 74.86.3.208
> 
> blacklist-ip 75.126.115.192
> 
> blacklist-ip 75.126.124.162
> 
> blacklist-ip 75.126.135.131
> 
> blacklist-ip 75.126.150.210
> 
> blacklist-ip 75.126.164.178
> 
> blacklist-ip 75.126.2.43
> 
> blacklist-ip 75.126.215.88
> 
> blacklist-ip 75.126.33.156
> 
> blacklist-ip 78.16.49.15
> 
> blacklist-ip 88.191.249.182
> 
> blacklist-ip 88.191.249.183
> 
> blacklist-ip 88.191.253.157
> 
> blacklist-ip 93.46.8.89
> 
> blacklist-ip 128.121.126.139
> 
> blacklist-ip 159.106.121.75
> 
> blacklist-ip 169.132.13.103
> 
> blacklist-ip 173.252.73.48
> 
> blacklist-ip 173.252.100.21
> 
> blacklist-ip 173.252.100.32
> 
> blacklist-ip 173.252.102.16
> 
> blacklist-ip 173.252.102.241
> 
> blacklist-ip 173.252.103.64
> 
> blacklist-ip 173.252.110.21
> 
> blacklist-ip 174.36.196.242
> 
> blacklist-ip 174.36.228.136
> 
> blacklist-ip 174.37.54.20
> 
> blacklist-ip 174.37.154.236
> 
> blacklist-ip 174.37.175.229
> 
> blacklist-ip 192.67.198.6
> 
> blacklist-ip 199.16.156.40
> 
> blacklist-ip 199.16.156.7
> 
> blacklist-ip 199.16.158.190
> 
> blacklist-ip 199.59.148.14
> 
> blacklist-ip 199.59.148.140
> 
> blacklist-ip 199.59.148.209
> 
> blacklist-ip 199.59.148.97
> 
> blacklist-ip 199.59.149.136
> 
> blacklist-ip 199.59.149.244
> 
> blacklist-ip 199.59.150.11
> 
> blacklist-ip 199.59.150.49
> 
> blacklist-ip 202.106.1.2
> 
> blacklist-ip 202.181.7.85
> 
> blacklist-ip 203.98.7.65
> 
> blacklist-ip 203.161.230.171
> 
> blacklist-ip 205.186.152.122
> 
> blacklist-ip 207.12.88.98
> 
> blacklist-ip 208.43.170.231
> 
> blacklist-ip 208.43.237.140
> 
> blacklist-ip 208.56.31.43
> 
> blacklist-ip 208.101.21.43
> 
> blacklist-ip 208.101.48.171
> 
> blacklist-ip 208.101.60.87
> 
> blacklist-ip 209.36.73.33
> 
> blacklist-ip 209.145.54.50
> 
> blacklist-ip 209.220.30.174
> 
> blacklist-ip 211.94.66.147
> 
> blacklist-ip 213.169.251.35
> 
> blacklist-ip 216.221.188.182
> 
> blacklist-ip 216.234.179.13
> 
> blacklist-ip 243.185.187.39
> 
>

**Comment by PikuZheng** [comment]
> 这个ip 是怎么来的？

探测穷举法，参考 https://zh.wikiversity.org/wiki/%E9%98%B2%E7%81%AB%E9%95%BF%E5%9F%8E%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%BC%93%E5%AD%98%E6%B1%A1%E6%9F%93IP%E5%88%97%E8%A1%A8

**Comment by lalasou** [comment]
意思  这些ip 是不正确的 nas返回需要丢弃？
还是这些ip正确的 但是国内无法访问？


我看维基上列表很多   都加上吗

**Comment by PikuZheng** [comment]
可能你需要先理解一下dns污染的原理。
在gfw发现udp/53且匹配了特定的域名时，会从上述列表中随机选择一个ip发给客户端。客户端会先收到这个错误的ip，后收到指dns上游服务器发送的应答。在此前提下，若将上述错误ip列入黑名单丢弃，便可等到后收到的上游服务器应答，至于后收到的结果是否正确则取决与上游服务器。
此外由于列表中很多都是fb等真实的ip，若完全黑名单则会对访问fb等造成困难。
如果你的上游都是dot或doh或其他方式（比如不使用53端口），便不会收到这个错误ip，无需关心这些。
