### ISSUE TITLE
LEDEX86 作为一个旁路由 怎么使用呢?

### ISSUE THREAD

**Issue by hbmask** [pymumu/smartdns#22]
LEDEX86 作为一个旁路由 怎么使用呢?
作为LEDEX86 我只有一个lan口没有网口
IPv4 上游
协议: 静态地址
地址: 192.168.5.254
子网掩码: 255.255.255.0
网关: 192.168.5.1
DNS 1: 192.168.5.254
已连接: 0h 21m 31s

可以这样使用么,没有wan口.

**Comment by pymumu** [comment]
dhcp里面配置dns服务器为smartdns就可以了
