### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by roy827** [pymumu/smartdns#220]
**问题现象**  
小白，无法启动smartdns，勾选启动后一直显示为为“未运行”

系统日志显示：

“Mon Nov 11 10:49:16 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:19 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:22 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:25 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:28 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:31 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:34 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:49:37 2019 daemon.err uhttpd[1959]: uci: Entry not found
Mon Nov 11 10:51:26 2019 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash”

**运行环境**
1. 主机名	OpenWrt
主机型号	Phicomm N1 / ARMv8 Processor rev 4 (v8l)
固件版本	OpenWrt R9.10.24 / LuCI Master (git-19.299.52050-0b735ea)
内核版本	4.18.7-aml-s9xxx  

2. 运营商  unicom

**重现步骤**
1. 上游DNS配置， 谷歌 8.8.8.8
                              114.114.114.114。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。 (没有这个文件)

**Comment by pymumu** [comment]
要装对配套设备cpu的版本

**Comment by roy827** [comment]
> 要装对配套设备cpu的版本

我装的aarch64_generic，按教程系统里看过

**Comment by pymumu** [comment]
执行/usr/sbin/smartdns -h看看有没有输出

**Comment by RealKiro** [comment]
> 执行/usr/sbin/smartdns -h看看有没有输出

![image](https://user-images.githubusercontent.com/33367701/69803150-42f2a480-1216-11ea-8b04-e5bcc860f412.png)

- Newifi3(MTK7621)正常运行，但是X86_64不运行

**Comment by pymumu** [comment]
看x86报什么错误

**Comment by RealKiro** [comment]
> 看x86报什么错误

![image](https://user-images.githubusercontent.com/33367701/69844287-7c72f080-12a6-11ea-9f78-e66668d6f8b4.png)

终端命令没报错，替换过二进制也不运行

**Comment by RealKiro** [comment]
> 看x86报什么错误
谢谢🙏，已正常，是我的问题
