### ISSUE TITLE
Padavan 安装失败

### ISSUE THREAD

**Issue by lbwstco** [pymumu/smartdns#221]
**问题现象**  
简要描述问题出现的现象
安装出错
![image](https://user-images.githubusercontent.com/6779378/68575440-0b120000-04a7-11ea-9f77-6a09f7d6b207.png)
u盘opt已挂载，使用entware

**运行环境**

路由器系统：Padavan 3.4.3.9-099_9-11-6
路由器硬件：小米路由器3 (MT7620A)
安装版本： smartdns.1.2019.11.02-1102.mipsel-openwrt-all.ipk

**Comment by pymumu** [comment]
要装optware的那个包，不是openwrt的

**Comment by lbwstco** [comment]
@pymumu optware报错如下
![image](https://user-images.githubusercontent.com/6779378/68577236-a0fb5a00-04aa-11ea-9674-2861ac3eacb9.png)

**Comment by pymumu** [comment]
看看/opt/usr/sbin目录下有没有smartdns

安装都没成功

**Comment by zhudan** [comment]
> 看看/opt/usr/sbin目录下有没有smartdns
> 
> 安装都没成功

/opt/usr/都没有sbin目录，他这个也是老毛子的固件

**Comment by pymumu** [comment]
自己创建/opt/usr/sbin/目录，再安装看看把
