### ISSUE TITLE
启用域名预加载，加速域名响应速度。 

### ISSUE THREAD

**Issue by wclmgcd** [pymumu/smartdns#222]
启用域名预加载，加速域名响应速度?这个是不是相当于unbound的在dns缓存结果过期前自动刷新？每个人常用的网站只有几十个，unbound的这个功能相当实用，直接把常用的网站结果缓存在本地，大大加快了网页速度。如果不是，可不可以加上这个功能

**Comment by pymumu** [comment]
prefetch-domain yes
可以启用域名预加载，此功能会在TTL过期前3s刷新。
每个刷新的域名会有对应的刷新次数，访问越多的域名会持续刷新。

**Comment by wclmgcd** [comment]
k3.重启路由后，虽然smartdns以启动，top也能查看到进程，但无法工作，联网失败，必须重启smartdns才可以

**Comment by pymumu** [comment]
可能是重定向规则被覆盖了，改成作为dnsmasq上游

**Comment by wclmgcd** [comment]
> 可能是重定向规则被覆盖了，改成作为dnsmasq上游
就是设置成dnsmasp的上游，我在启动项添加了一条命令，可以了
