### ISSUE TITLE
请求提供非静态编译版本

### ISSUE THREAD

**Issue by 0064Unknown** [pymumu/smartdns#225]
**需求应用场景**
部分rom容量较小路由器，静态编译版本塞不下

**建议的方案**
请求提供非静态编译版本

**设备信息**
1. 设备信息（CPU，厂家）  
CPU:ramips-mt7621
架构:mipsel_24kc  
设备:斐讯k2p
ROM Size:16MB
2. 固件信息
openwrt 18.06

**Comment by pymumu** [comment]
openwrt什么版本

**Comment by 0064Unknown** [comment]
> 
> 
> openwrt什么版本

应该是18.06吧 https://github.com/coolsnowwolf/lede

**Comment by pymumu** [comment]
[smartdns.1.2019.11.26-2346.mips_24kc.ipk.zip](https://github.com/pymumu/smartdns/files/3892695/smartdns.1.2019.11.26-2346.mips_24kc.ipk.zip)
