### ISSUE TITLE
dns污染问题

### ISSUE THREAD

**Issue by liyiranlab** [pymumu/smartdns#228]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
OpenWrt 19.07.0-rc1
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
配置移动211.139.5.29等国内dns
2. 访问的域名。  
www.google.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
应该DNS污染导致，打不开www.google.com主页，重启后跟换国内较慢dns才成功再次打开www.google.com主页；还有不知道怎么和v2瑞共同使用，正因为v2瑞dns太慢才使用想smartdns，结果不知如何设置

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/search?p=1&q=%E6%B1%A1%E6%9F%93&type=Issues

**Comment by MasterThrone** [comment]
为什么不用DOH或者DOT呢?
想用普通的UDP DNS还不如用V2的TProxy,用V2的DNS功能.
