### ISSUE TITLE
如何根据dnsmasq的ipset参数控制dns分流？

### ISSUE THREAD

**Issue by 0064Unknown** [pymumu/smartdns#229]
在dnsmasq.d中配置了某list的ipset规则，如何让这一ipset使用指定dns group？（不使用nameserver参数）
规则这样写有问题吗：
server [ip] -ipset [某list] -group [group]

**Comment by pymumu** [comment]
不支持这种写法。
smartdns本身支持ipset，可以使用ipset规则设置。
```
ipset /address/[ipsetname]
```
