### ISSUE TITLE
建议将第一服务器和第二服务器的上游dns独立

### ISSUE THREAD

**Issue by pV-nRT** [pymumu/smartdns#230]
新版本引入了第二服务器功能，确实很好用，配合L大的某插件，在dns解析方式中选择“使用本机端口5335的dns服务”，将第二服务器的端口改为5335就可以用smartdns来智能选择dns返回的地址了。

但是建议将第一服务器和第二服务器的上游dns独立出来，第一服务器填写纯国内dns，第二服务器填写纯海外dns。

这样可以避免访问国内网站时用海外dns去解析，导致有时候直接使用节点的延迟比国内的延迟低时，返回了海外ip去访问国内网站的情况出现。（国内使用长城、移动宽带这种延迟高的宽带，海外是澳门、香港这种延迟比较低的节点）

**Comment by pymumu** [comment]
第二dns使用-group参数即可
‘’‘
bind [:53] -group foreign
server 8.8.8.8 -group foreign
’‘’

具体可看参数说明
group是可以指定多个的

**Comment by pV-nRT** [comment]
多谢提醒，-group参数确实可以分流

**Comment by aglent** [comment]
> 
> 
> 第二dns使用-group参数即可
> ‘’‘
> bind [:53] -group foreign
> server 8.8.8.8 -group foreign
> ’‘’
> 
> 具体可看参数说明
> group是可以指定多个的

第二DNS服务器 我设置了服务器组为海外
那么第一DNS服务器仍然是全部dns服务器都在工作吗？

**Comment by aglent** [comment]
> 
> 新版本引入了第二服务器功能，确实很好用，配合L大的某插件，在dns解析方式中选择“使用本机端口5335的dns服务”，将第二服务器的端口改为5335就可以用smartdns来智能选择dns返回的地址了。
> 
> 但是建议将第一服务器和第二服务器的上游dns独立出来，第一服务器填写纯国内dns，第二服务器填写纯海外dns。
> 
> 这样可以避免访问国内网站时用海外dns去解析，导致有时候直接使用节点的延迟比国内的延迟低时，返回了海外ip去访问国内网站的情况出现。（国内使用长城、移动宽带这种延迟高的宽带，海外是澳门、香港这种延迟比较低的节点）

Lede插件通过5335端口使用smartdns的第二组服务器  是不是还要设置smartdns重定向到dnsmasq？
能否具体解释下 如果要访问google.com  要经过哪些流程才能最终到达代理服务器
我自己还不是很明白 总觉得域名被送到smartdns后 是所有的dns服务器并发解析 得到正确海外IP之后 根据ssr插件的IP分流表 走代理服务器 这样的话 好像ssr插件并没有用到5335端口？
谢谢！

**Comment by wclmgcd** [comment]
> 
> 
> > 新版本引入了第二服务器功能，确实很好用，配合L大的某插件，在dns解析方式中选择“使用本机端口5335的dns服务”，将第二服务器的端口改为5335就可以用smartdns来智能选择dns返回的地址了。
> > 但是建议将第一服务器和第二服务器的上游dns独立出来，第一服务器填写纯国内dns，第二服务器填写纯海外dns。
> > 这样可以避免访问国内网站时用海外dns去解析，导致有时候直接使用节点的延迟比国内的延迟低时，返回了海外ip去访问国内网站的情况出现。（国内使用长城、移动宽带这种延迟高的宽带，海外是澳门、香港这种延迟比较低的节点）
> 
> Lede插件通过5335端口使用smartdns的第二组服务器 是不是还要设置smartdns重定向到dnsmasq？
> 能否具体解释下 如果要访问google.com 要经过哪些流程才能最终到达代理服务器
> 我自己还不是很明白 总觉得域名被送到smartdns后 是所有的dns服务器并发解析 得到正确海外IP之后 根据ssr插件的IP分流表 走代理服务器 这样的话 好像ssr插件并没有用到5335端口？
> 谢谢！

小白一个，说错了希望理解
L大的ssp的固件里，分流是在dnsmasq，把被墙的域名发送到5335端口，是文件/etc/dnsmasq.ssr/gfw_base.conf，里这个server=/.google.com/127.0.0.1#5335，1.如果是ssp自己解析它调用自带的pdnsd把5335的解析用tcp的方式通过ssp的代理隧道发送出去解析，解析出来的地址离代理服务器最近，有一定加速作用    2.如果5335端口使用smartdns的第二组服务器，那就是直接到smartdns的第二组服务器，（也可以设置通过ssp的代理隧道发送出去解析，达到加速的目的）
所以访问google.com---dnsmasq--分流5335端口---pdnsd/smartdns解析，因为是dnsmasq首先分流，所以可以不设置smartdns重定向到dnsmasq。    但设置smartdns重定向到dnsmasq是采用的第一组6053的dns，可以加速国内的网址，还是建议设置
附上我的设置：

config smartdns
	option server_name 'smartdns'
	option port '6053'
	option tcp_server '1'
	option prefetch_domain '1'
	option seconddns_port '5335'
	option seconddns_tcp_server '1'
	option seconddns_server_group 'fanqiang'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_soa '0'
	option coredump '0'
	option seconddns_enabled '1'
	option rr_ttl_max '43200'
	option redirect 'dnsmasq-upstream'
	option seconddns_no_speed_check '1'
	option seconddns_no_dualstack_selection '1'
	option seconddns_no_cache '1'
	option seconddns_no_rule_ipset '0'
	option rr_ttl_min '300'
	option enabled '1'
	option ipv6_server '1'
	option dualstack_ip_selection '1'
	list old_redirect 'dnsmasq-upstream'
	list old_port '6053'
	list old_enabled '1'

config server
	option enabled '1'
	option blacklist_ip '1'
	option type 'udp'
	option name '114'
	option ip '114.114.114.114'
	option port '53'

config server
	option enabled '1'
	option blacklist_ip '1'
	option name 'zkd'
	option ip '202.141.176.93'
	option port '5353'
	option type 'tcp'

config server
	option enabled '1'
	option blacklist_ip '1'
	option name 'GeekDNS'
	option ip 'https://ndns.233py.com/dns-query'
	option port '443'
	option type 'https'

config server
	option enabled '1'
	option server_group 'fanqiang'
	option name 'google'
	option ip '8.8.8.8'
	option port '853'
	option type 'tls'

config server
	option enabled '1'
	option server_group 'fanqiang'
	option name 'cf'
	option ip '1.1.1.1'
	option port '853'
	option type 'tls'

**Comment by aglent** [comment]
> 
> 
> > > 新版本引入了第二服务器功能，确实很好用，配合L大的某插件，在dns解析方式中选择“使用本机端口5335的dns服务”，将第二服务器的端口改为5335就可以用smartdns来智能选择dns返回的地址了。
> > > 但是建议将第一服务器和第二服务器的上游dns独立出来，第一服务器填写纯国内dns，第二服务器填写纯海外dns。
> > > 这样可以避免访问国内网站时用海外dns去解析，导致有时候直接使用节点的延迟比国内的延迟低时，返回了海外ip去访问国内网站的情况出现。（国内使用长城、移动宽带这种延迟高的宽带，海外是澳门、香港这种延迟比较低的节点）
> > 
> > 
> > Lede插件通过5335端口使用smartdns的第二组服务器 是不是还要设置smartdns重定向到dnsmasq？
> > 能否具体解释下 如果要访问google.com 要经过哪些流程才能最终到达代理服务器
> > 我自己还不是很明白 总觉得域名被送到smartdns后 是所有的dns服务器并发解析 得到正确海外IP之后 根据ssr插件的IP分流表 走代理服务器 这样的话 好像ssr插件并没有用到5335端口？
> > 谢谢！
> 
> 小白一个，说错了希望理解
> L大的ssp的固件里，分流是在dnsmasq，把被墙的域名发送到5335端口，是文件/etc/dnsmasq.ssr/gfw_base.conf，里这个server=/.google.com/127.0.0.1#5335，1.如果是ssp自己解析它调用自带的pdnsd把5335的解析用tcp的方式通过ssp的代理隧道发送出去解析，解析出来的地址离代理服务器最近，有一定加速作用 2.如果5335端口使用smartdns的第二组服务器，那就是直接到smartdns的第二组服务器，（也可以设置通过ssp的代理隧道发送出去解析，达到加速的目的）
> 所以访问google.com---dnsmasq--分流5335端口---pdnsd/smartdns解析，因为是dnsmasq首先分流，所以可以不设置smartdns重定向到dnsmasq。 但设置smartdns重定向到dnsmasq是采用的第一组6053的dns，可以加速国内的网址，还是建议设置
> 附上我的设置：
> 
> config smartdns
> option server_name 'smartdns'
> option port '6053'
> option tcp_server '1'
> option prefetch_domain '1'
> option seconddns_port '5335'
> option seconddns_tcp_server '1'
> option seconddns_server_group 'fanqiang'
> option seconddns_no_rule_addr '0'
> option seconddns_no_rule_nameserver '0'
> option seconddns_no_rule_soa '0'
> option coredump '0'
> option seconddns_enabled '1'
> option rr_ttl_max '43200'
> option redirect 'dnsmasq-upstream'
> option seconddns_no_speed_check '1'
> option seconddns_no_dualstack_selection '1'
> option seconddns_no_cache '1'
> option seconddns_no_rule_ipset '0'
> option rr_ttl_min '300'
> option enabled '1'
> option ipv6_server '1'
> option dualstack_ip_selection '1'
> list old_redirect 'dnsmasq-upstream'
> list old_port '6053'
> list old_enabled '1'
> 
> config server
> option enabled '1'
> option blacklist_ip '1'
> option type 'udp'
> option name '114'
> option ip '114.114.114.114'
> option port '53'
> 
> config server
> option enabled '1'
> option blacklist_ip '1'
> option name 'zkd'
> option ip '202.141.176.93'
> option port '5353'
> option type 'tcp'
> 
> config server
> option enabled '1'
> option blacklist_ip '1'
> option name 'GeekDNS'
> option ip 'https://ndns.233py.com/dns-query'
> option port '443'
> option type 'https'
> 
> config server
> option enabled '1'
> option server_group 'fanqiang'
> option name 'google'
> option ip '8.8.8.8'
> option port '853'
> option type 'tls'
> 
> config server
> option enabled '1'
> option server_group 'fanqiang'
> option name 'cf'
> option ip '1.1.1.1'
> option port '853'
> option type 'tls'

在DNSmasq设置了转发到SmartDNS 本地端口后  特殊域名仍然优先通过 /etc/dnsmasq.ssr/gfw_base.conf文件 走SmartDNS的第二组5335端口解析 获得离vps最近的ip（我已经把国外DNS的IP加入了强制WAN IP走代理列表） 是这样的理解吧？

**Comment by Masstone** [comment]
openwrt
为什么我配置了第二DNS和也配置了分组，
通过默认dns的端口查询时还会给非第二dns分组绑定的上游发请求呢？
如果就是这样的设计的话，能给luci中的默认dns也加个绑定分组的功能么
