### ISSUE TITLE
希望可以在Luci中提供应用内更新的功能

### ISSUE THREAD

**Issue by QiuSimons** [pymumu/smartdns#231]
**需求应用场景**
每次更新都需要重新opkg，有点不方便，希望能实现应用内更新功能
类似于下面的app里用到的那种
https://github.com/rufengsuixing/luci-app-adguardhome

**建议的方案**
可参考上面的方案实现

**设备信息**
1. 设备信息（CPU，厂家）  
Intel 8700T

2. 固件信息
Openwrt_18.06_x86-64

**Comment by FusionPlmH** [comment]
認同
