### ISSUE TITLE
树莓派3安装配置后，主路由不配置DNS无法正常使用

### ISSUE THREAD

**Issue by blizzardster** [pymumu/smartdns#232]
**问题现象**  
局域网内树莓派作为DNS服务器，主路由一定要配置上游DNS才能使用smartdns，主路由配置了树莓派的IP就无法DNS解析，路由配置上游DNS，smartdns就正常了

**运行环境**
1. 树莓派3
安装软件smartdns.1.2019.11.02-1102.arm-debian-all.deb

2. 运营商  
上海移动

3.路由这里设置树莓派的IP，dns就无法解析，这里配置了上游DNS,树莓派dns服务器也就正常了，

![image](https://user-images.githubusercontent.com/21025731/69899938-1d95a000-13a8-11ea-8a7b-e0e0f3dcc911.png)

4，Can't open PID file /run/smartdns.pid (yet?) after start: No such file or directory错误提示

**Comment by pymumu** [comment]
DNS循环了吧，看看dnsmasq的日志吧。

**Comment by blizzardster** [comment]
> DNS循环了吧，看看dnsmasq的日志吧。

主路由用的华硕原生固件，设置找不到dnsmasq,树莓派里面也没有装过dnsmasq,小白不知道哪里看。试用下来速度确实快多了，路由不能设置树莓派为DNS服务器有点不舒服

**Comment by pV-nRT** [comment]
你的华硕路由器要在lan局域网设置填写树莓派的dns，不能在wan广域网设置填写树莓派的dns，在wan设置填写树莓派的dns是用不了的，同时你的树莓派要和你的华硕路由器在同一个子网。

**Comment by blizzardster** [comment]
> 你的华硕路由器要在lan局域网设置填写树莓派的dns，不能在wan广域网设置填写树莓派的dns，在wan设置填写树莓派的dns是用不了的，同时你的树莓派要和你的华硕路由器在同一个子网。

谢谢我上午已经测试了，发现是华硕的锅，谢谢，问题解决，感谢
