### ISSUE TITLE
luci 没有dns时延和DNS地址支持协议

### ISSUE THREAD

**Issue by mhmddb** [pymumu/smartdns#234]
**需求应用场景**
请描述需求应用的场景和方式。
luci界面提供dns 时延 协议支持显示
**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  
i3-5005U
2. 固件信息
openwrt-x86-64

**Comment by pymumu** [comment]
默认都是1s，这个值也应该足够使用了。
协议的话，在配置那里应该就能看到

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/issues/234

**Comment by pymumu** [comment]
please feel free to reopen this issue.
