### ISSUE TITLE
lede+v2ray 下安装的smartdns出国和谷歌时不时不能访问

### ISSUE THREAD

**Issue by 2660230880** [pymumu/smartdns#235]
**问题现象**  
lede+v2ray 下安装的smartdns出国和谷歌时不时不能访问，已经排除不是断流，不用smartdns就没问题，请问知道这是什么原因吗，至于那个什么tmp下的报错我开了那个开关但是没有那个文件生成所以无法提供。

**运行环境**
1. 固件型号  
lede x64
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
119.29.29.29
223.5.5.5
114.114.114.114
1.2.4.8
8.8.8.8
8.8.4.4
208.67.222.222
208.67.220.220
2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[smartdns.log](https://github.com/pymumu/smartdns/files/3911575/smartdns.log)

**Comment by pymumu** [comment]
对国内dns服务器应用ip黑名单，国外dns使用tls，https或配置-check-edns，具体操作搜索历史issue

**Comment by 2660230880** [comment]
> 对国内dns服务器应用ip黑名单，国外dns使用tls，https或配置-check-edns，具体操作搜索历史问题

可否给个链接，没找到我需要的。

**Comment by 2660230880** [comment]
> 对国内dns服务器应用ip黑名单，国外dns使用tls，https或配置-check-edns，具体操作搜索历史问题

可以把你自己的设置截图来看看看看吗，看了很多历史问题，一头雾水，不知道如何下手

**Comment by pymumu** [comment]
看#219 #74 #91

**Comment by 2660230880** [comment]
哎，已经放弃了，整了几天上谷歌一直有问题，希望以后能完善在来用吧。

**Comment by MasterThrone** [comment]
> 哎，已经放弃了，整了几天上谷歌一直有问题，希望以后能完善在来用吧。

只要用UDP DNS都会出现污染的问题,要么换DOH/DOT,要么就用V2的DNS分流.

**Comment by QiuSimons** [comment]
> 看#219 #74 #91

可以加入自动检测某i是否被污染，然后自动加入黑名单list的功能么？
