### ISSUE TITLE
华硕梅林和centos安装了都没效果

### ISSUE THREAD

**Issue by zz1985summer** [pymumu/smartdns#237]
conf文件只添加了server-tcp:ip:端口
测试最后都报这行错误
server can't find 0.0.0.0.in-addr.arpa: NXDOMAIN

强制把系统dns设置为centos地址解析打不开网页。

梅林路由器安装的是华硕官方固件对应的

**Comment by pymumu** [comment]
看看进程smartdns在不在运行
