### ISSUE TITLE
一些需求

### ISSUE THREAD

**Issue by PussAzuki** [pymumu/smartdns#238]
**需求应用场景**
请描述需求应用的场景和方式。

目前luci这边控制界面存在一些迷惑的选项:
1.“设置”里的“自定义设置”标着自定义设置却并不是像unbound或是stubby那样完全的自定义模式，存在一定的迷惑性
2.tcp-tls服务器设置页面里的“检验TLS主机名”和“TLS SNI 名称”有点让我理解不能，stubby只需要“tls auth name”一项即可，此处能否算是第二个迷惑项？
3.说到这里，还是针对tcp-tls服务器的，之前的分散包看起来需要的不是1.1.1x分支的openssl，是不是不支持tls1.3 ？
4.或许需要一个“多个 IP黑名单”来应对不同的dns...

**建议的方案**
实现上述场景建议的方案。

1.希望能明确一下其用途，如果是“真 自定义选项”，还请做些修改
2.希望能确定下是否真的需要两个选项
3.如果可以的话，希望能跟上openssl的版本，并增加tls1.2和tls1.3优先级的选项

**Comment by pymumu** [comment]
1.自定义是指可以类似conf文件方式写配置，这个会和其他界面配置合并后生成一个大的配置，具体看/var/etc/smartdns/smartdns.conf
2.tls sni是请求的时候tls头里面sni的内容
   verify tls hostname是指校验dns服务器证书是否为指定值，避免服务器伪造
3.静态编译版本目前ssl是1.1.0的，会使用最高的协议，后面会升级到openssl1.1.1

**Comment by PussAzuki** [comment]
1.这一条算是理解了，但是感觉名字或许改一下会比较好？或者搞个“只从目录那边读取配置文件的开关会不会好一点？目前感觉不是很妥当的
2.我个人以为是只需要写入tls sni就会去主动检验名字，都留空则不那样做，所以我个人觉得是有迷惑性的
3.或许弄两个版本的包会好一些？1.1.1的那个用来测试，1.1.0的拿来当正式版，然后就这样迭代下去
4.目前还是遇到那个问题:tls上游因为长时间连接闲置后会主动被断开，然后接着去查询的话就要握手因而产生一定的延迟，这段延迟有没有可能让第一个请求没有请求到tls dns上游？

**Comment by pymumu** [comment]
1.这个目前不会动，已经很多人使用了
2.默认都是不检查合法性的，除非自己设置，命名方面会在审视一次
3.openssl1.1.1会在下个版本提供
4.tcp默认启用了fast-open，同时tls启用了session-reuse，除第一次外，建立连接消耗基本和udp相同

**Comment by PussAzuki** [comment]
1.那加个开关，让“在luci控制界面这边是‘从单/多个个文件读取配置’”这件事应该...能做到的吧...
2.&3.OK
4.可我记得貌似是被主动断开？如果如你所说一致的话，那就是我多虑了...

**Comment by PussAzuki** [comment]
今天发现您的项目开源了，然后看了下luci管理界面，
1.发现白名单没加上(?)测试了下白名单功能是能用的... ---->用了一个下午没问题
2.手写配置文件比网页设置快也是很...尴尬 ---->个人强烈要求加个可以只读取手写配置文件的选项

**Comment by pymumu** [comment]
在自定义配置中，用conf-file添加自定义配置文件路径即可。
