### ISSUE TITLE
运行中但是没有生效

### ISSUE THREAD

**Issue by lovezm** [pymumu/smartdns#241]
**问题现象**  
root@OpenWrt:~# nslookup 0.0.0.0
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find 0.0.0.0.in-addr.arpa: NXDOMAIN

root@OpenWrt:~#  nslookup baidu.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      baidu.com
Address 1: 39.156.69.79
Address 2: 220.181.38.148
*** Can't find baidu.com: No answer

**运行环境**
1. openwrt

2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。

**Comment by lovezm** [comment]
另外查看端口好像在运行
root@OpenWrt:~# netstat -ntulp | grep 6053
tcp        0      0 0.0.0.0:6053            0.0.0.0:*               LISTEN      6000/smartdns
udp        0      0 0.0.0.0:6053            0.0.0.0:*                           6000/smartdns

**Comment by lovezm** [comment]
已解决

**Comment by xinpenghan** [comment]
> 已解决
请问怎么解决的呢？我的也是这个问题

**Comment by lovezm** [comment]
在运行好像就是好的  只不过有缓存

发送自 Windows 10 版邮件应用

发件人: xinpenghan
发送时间: 2019年12月20日 1:37
收件人: pymumu/smartdns
抄送: WangMuDu; State change
主题: Re: [pymumu/smartdns] 运行中但是没有生效 (#241)

已解决
请问怎么解决的呢？我的也是这个问题

**Comment by pymumu** [comment]
dnsmasq对0.0.0.0的ptr请求做了阻断，导致无法判断结果，如果查询百度只有一个IP地址返回的话，就表示生效了。

这个问题，下个版本解决。
