### ISSUE TITLE
lede 修改 指定特定域名的IP地址 之后点击保存并应用 提示 没有修改，需要手动重启 smart dns ，配置才生效

### ISSUE THREAD

**Issue by ThunderingII** [pymumu/smartdns#244]
**需求应用场景**
lede openwrt

**建议的方案**
建议修改了之后，点击保存并应用 能够自动重启smart dns

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
这种属于固件bug，和smartdns无关，可以到对应固件的网站提交issue。
