### ISSUE TITLE
希望作者认真考虑一下把smartdns开源

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#245]
这么好的软件,就因为没有开源,好多人都不敢用.我也试用过了一下真的效果一级棒.特别几个大神在Youtube视频介绍,好多人都装了试用,希望作者认真考虑把smartdns开源.谢谢

**Comment by foxconndmd** [comment]
+1

**Comment by dengchan0416** [comment]
L大和Mike Bill群组都有大量评价这软件基本上八九成人使用过都觉得好用,多数人都不敢用.主要观点没有开源,大家都有一定的顾虑在.

**Comment by pymumu** [comment]
代码最初就是准备开源的，但中途遇到一些smartdns开源不利的事情，所以目前不开源是在保护smartdns，使其能长久发展，避免smartdns使用过于广泛，保证小众化；另外是给内部有些防wr机制做一定原理保护：避免未来无干净dns可用。
 
当然后面可能会去掉防wr机制开源，仅用于dns加速，去广告等功能，差异化的二进制版本仍可能正常发布。

**Comment by MxCen** [comment]
可惜了。不开源用的人少。

**Comment by MxCen** [comment]
可惜了。不开源用的人少。
