### ISSUE TITLE
smartdns流量有点大

### ISSUE THREAD

**Issue by lix5027** [pymumu/smartdns#246]
不好意思,最近刚开始用smartdns,问题比较多
我发现用openwrt的自带流量监控程序看大概8小时的流量.
smartdns会消耗很多,不知道算不算误报?
截图在附件上了

**Comment by lix5027** [comment]
诶？没法上传附件吗

**Comment by lix5027** [comment]
![sd2](https://user-images.githubusercontent.com/8099640/70580240-fdf34880-1bed-11ea-8a30-db3be77bf500.jpg)
![sd1](https://user-images.githubusercontent.com/8099640/70580241-fdf34880-1bed-11ea-8e42-e55b20ac74e9.jpg)

哦了.看来要走全局模式才能upload attach

**Comment by lix5027** [comment]
缓存 200000
min-ttl 300
时间大概是昨天14:00到今晨8:00,这段时间17:00左右用户就下班了,内网没什么人,白天大概有50人左右,所以真正产生流量应该是14:00-17:00 50人的使用量

**Comment by pymumu** [comment]
要具体看请求的并发量，以前没关注过这块。
根据smartdns原理，没次请求都要ping或者tcp检测，ping的包字节在64字节，按上传476mb计算发生大约780w次ping，每个域名平均2个ip，约有390w请求。
看你有一个https的上游，https上传1.52gb，约按400字节一个请求，差不多400w请求。

上述两个数据差不多一直

根据统计的结果看计算，约有400w请求，可惜统计周期图中没有显示。

可以看一下审计日志，看看多长时间会有一个请求，看一下请求速率，再来看流量是否正常

**Comment by pymumu** [comment]
第二图统计的是机器整体流量，还要排除一下那个机器上有没有其他服务产生流量
