### ISSUE TITLE
上游DNS设置问题

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#247]
认真看了常问问题,其中提到如何配置上游服务器最佳。
GSLB中有测速机制，在配置上游服务器时，建议配置多个上游DNS服务器，包含多个不同区域的服务器，但总数建议在10个左右。推荐配置,
[![QseWZQ.md.jpg](https://s2.ax1x.com/2019/12/11/QseWZQ.md.jpg)](https://imgse.com/i/QseWZQ)
图片里算是4个还是2个,一组DNS要分TCP和UDP

**Comment by pymumu** [comment]
4个，一般同一个上游没必要配置不同协议
对于国内直接用udp，可增加ip黑名单，国外优先tls，https

**Comment by dengchan0416** [comment]
@pymumu 国内全部选udp?为什么,我都是有先TCP

**Comment by dengchan0416** [comment]
![image](https://user-images.githubusercontent.com/41529838/70715183-b4f1e000-1d24-11ea-90ea-bb16a2ab9f49.png)

**Comment by pymumu** [comment]
国内UDP查询速度快，没必要tcp，当然，移动的话，例外，用tcp合适。

**Comment by dengchan0416** [comment]
@pymumu 请问是不是这样设置
![image](https://user-images.githubusercontent.com/41529838/70720417-bb855500-1d2e-11ea-9813-9221b9108634.png)

**Comment by immyonlystar** [comment]
> @pymumu 请问是不是这样设置
> ![image](https://user-images.githubusercontent.com/41529838/70720417-bb855500-1d2e-11ea-9813-9221b9108634.png)

如果是tls协议的话，端口要填853，谷歌和1.1.1.1的，你可以改一下。https的端口应该也不对，建议你删掉。

**Comment by dengchan0416** [comment]
@pymumu 能否做一个上游DNS设置详细教程,你主页介绍得有点简单,谷歌和1111分别IP:8.8.8.8\1.1.1.1 端口853 协议:tls

**Comment by pymumu** [comment]
差不多就是这样，最后那个google tcp的可以删掉 ，高级里面ip黑名单应用到国内udp服务器

**Comment by dengchan0416** [comment]
@pymumu ip黑名单应用到国内udp服务器,不是很明白,
![image](https://user-images.githubusercontent.com/41529838/70847800-bbf32c80-1ea3-11ea-83aa-5d6becdf6594.png)
是不是这样设置

**Comment by dengchan0416** [comment]
@pymumu 这个IP黑名单好重要,希望能回复一下,最后一个问题了.不麻烦你了

**Comment by pymumu** [comment]
#91 上游DNS里面应用黑名单
