### ISSUE TITLE
openwrt编译时如何加入smartdns？ 没有看到luci-app-smartdns ？ 

### ISSUE THREAD

**Issue by sunlanhao** [pymumu/smartdns#248]
openwrt ×86-64位，想自己编译加入smartdns，发现没有luci-app ？

**Comment by MxCen** [comment]
没有开源。

**Comment by garypang13** [comment]
https://github.com/project-openwrt/openwrt/tree/master/package/jsda/luci-app-smartdns

**Comment by pikachullk** [comment]
https://github.com/pymumu/luci-app-smartdns
