### ISSUE TITLE
返回的DNS时好时坏,

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#251]
**问题现象**  
有时百度谷歌网站都可以,油管就不行了反遗多个IP,隔了几分钟之后,百度也不行了查时候发现有多个IP了,只有谷歌可以,每次重启都会好一段时间,不过油管都是不行

**运行环境**
1. 固件型号  
X86
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
![image](https://user-images.githubusercontent.com/41529838/70856200-43778480-1f12-11ea-9f0b-785832c2f9e0.png)
![image](https://user-images.githubusercontent.com/41529838/70856279-c2b98800-1f13-11ea-9d6a-b44e8ecd3cb3.png)

2. 访问的域名。  
![image](https://user-images.githubusercontent.com/41529838/70856203-5ee28f80-1f12-11ea-901e-246cbab0cfd3.png)

隔了3-15分钟时间之后,百度网站就不行了,smrtdns.log日志已上传
![image](https://user-images.githubusercontent.com/41529838/70856225-cc8ebb80-1f12-11ea-84c1-2396b920ff96.png)
[smartdns.log](https://github.com/pymumu/smartdns/files/3964497/smartdns.log)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by dengchan0416** [comment]
SSR这样设置之后,SmartDNS本地端口和DHCP/DNS转发改成127.0.0.1#5335.谷歌和youtube能稳定反回只有一个IP了,不过国内网站还是会有多个IP,访问163有时候反回是多个IP,有时候就只有一个IP.百度基本上多个IP,只有极少情况下突然反回只有一个IP
![image](https://user-images.githubusercontent.com/41529838/70857526-0ec3f700-1f2b-11ea-9b3f-a9687ad0c809.png)

![image](https://user-images.githubusercontent.com/41529838/70857516-e63bfd00-1f2a-11ea-93bd-7c5a635e7057.png)

**Comment by huarong2357** [comment]
清理DNS缓存试一下

dengchan0416 <notifications@github.com>于2019年12月15日 周日11:10写道：

**Comment by dengchan0416** [comment]
Microsoft Windows [版本 10.0.18363.535]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\44755>nslookup www.baidu.com
服务器:  p.to
Address:  192.168.2.1

非权威应答:
名称:    www.a.shifen.com
Addresses:  240e:ff:e020:37:0:ff:b08c:124f
          240e:ff:e020:36:0:ff:b00c:268a
          14.215.177.39
          14.215.177.38
Aliases:  www.baidu.com


C:\Users\44755>nslookup www.youtube.com
服务器:  p.to
Address:  192.168.2.1

非权威应答:
名称:    youtube-ui.l.google.com
Addresses:  2404:6800:4005:80c::200e
          216.58.200.78
Aliases:  www.youtube.com


C:\Users\44755>nslookup www.163.com
服务器:  p.to
Address:  192.168.2.1

非权威应答:
名称:    www.163.com.lxdns.com
Addresses:  2606:1980:a::9
          183.47.233.12
Aliases:  www.163.com


C:\Users\44755>nslookup www.baidu.com
服务器:  p.to
Address:  192.168.2.1

非权威应答:
名称:    www.a.shifen.com
Addresses:  240e:ff:e020:36:0:ff:b00c:268a
          240e:ff:e020:37:0:ff:b08c:124f
          14.215.177.38
          14.215.177.39
Aliases:  www.baidu.com


C:\Users\44755>nslookup www.baidu.com
服务器:  p.to
Address:  192.168.2.1

非权威应答:
名称:    www.wshifen.com
Addresses:  240e:ff:e020:37:0:ff:b08c:124f
          14.215.177.39
Aliases:  www.baidu.com


C:\Users\44755>nslookup www.163.com
服务器:  p.to
Address:  192.168.2.1

非权威应答:
名称:    z163ipv6.v.bsgslb.cn
Addresses:  240e:97e:2000:c100:0:1:2:22
          240e:97e:2000:c100:0:1:2:e
          240e:97e:2000:c100:0:1:2:2a
          240e:97e:2000:c100:0:1:2:12
          240e:97e:2000:c100:0:1:2:24
          240e:97e:2000:c100:0:1:2:1a
          183.47.233.14
          183.47.233.10
          183.47.233.13
          183.47.233.5
          183.47.233.3
          183.47.233.11
          183.47.233.12
          183.47.233.8
          183.47.233.9
          183.47.233.6
Aliases:  www.163.com
          www.163.com.163jiasu.com
          www.163.com.bsgslb.cn

**Comment by dengchan0416** [comment]
已经清理了好几次DNS缓存了

**Comment by pymumu** [comment]
应该是你的固件会周期修改dns配置，排除下吧

**Comment by dengchan0416** [comment]
@pymumu 已找到原因了

**Comment by lyslys888** [comment]
> @pymumu 已找到原因了

啥原因？能分享下么
