### ISSUE TITLE
SmartDNS开启正常但是服务器并不是smartdns，无效

### ISSUE THREAD

**Issue by Rexloong** [pymumu/smartdns#254]
作为DNSMASQ的上游(arm架构的openwrt路由器）
C:\Users\admin>nslookup -querytype=ptr 0.0.0.0
服务器:  OpenWrt.lan
Address:  192.168.1.1

*** OpenWrt.lan 找不到 0.0.0.0.in-addr.arpa.: Non-existent domain
但是返回地址只有一个
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:      www.baidu.com
www.baidu.com   canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 61.135.169.125
www.baidu.com   canonical name = www.a.shifen.com
关闭smartdns后返回两个地址，但是服务器仍然是openwrt.lan

**Comment by xiaoxiang8002** [comment]
同样的问题，请问你解决了吗？

**Comment by Rexloong** [comment]
> 同样的问题，请问你解决了吗？

并没有，暂时放弃，应该是bug等下一版修复

**Comment by pymumu** [comment]
配置的工作模式是什么，另外可以试一下直接发请求到smartdns的端口

**Comment by Rexloong** [comment]
> 配置的工作模式是什么，另外可以试一下直接发请求到smartdns的端口

dnsmasq上游，dns自动转发了,lan口dns填不填路由器地址都是上面那样。
如果换成53端口重定向返回两个地址，而且用nslookup -querytype=ptr 0.0.0.0返回的也是*** OpenWrt.lan 找不到 0.0.0.0.in-addr.arpa.: Non-existent domain。
两种模式设置完后均没有报错，系统进程里面也找得到smartdns

**Comment by garypang13** [comment]
同样的问题

**Comment by heqirong** [comment]
一样情况，在openwrt 64系统上运行起来，但是没有生效

**Comment by heqirong** [comment]
无论是53重新定向到smartdns还是作为dnsmasq上游，都是一样情况

**Comment by pymumu** [comment]
dnsmasq对0.0.0.0的ptr请求做了阻断，导致无法判断结果，如果查询百度只有一个IP地址返回的话，就表示生效了。

这个问题，下个版本解决。

**Comment by xiaoxiang8002** [comment]
dnsmasq-full会不会是因为这个原因，现在很多固件都用dnsmasq-full替换了dnsmasq

**Comment by xiaoxiang8002** [comment]
我初步测试，是dnsmasq-full的原因，我昨晚编译过两个openwrt-19.07-RC2版本
1.安装dnsmasq-full的版本，在dnsmasq里面设置DNS转发为127.0.0.1#6053，LAN自定义DNS服务器设置的是192.168.1.1，SmartDNS是未开启状态，正常应该是打不开网页的，但实际网络没有任何影响。设置SmartDNS作为dnsmasq服务器上游，开启SmartDNS后，nslookup www.baidu.com 还是返回两个地址.   
 2.安装dnsmasq的版本，是可以正常使用SmartDNS服务的，nslookup www.baidu.com 只返回一个地址。

**Comment by lengyuqingqiu** [comment]
> dnsmasq对0.0.0.0的ptr请求做了阻断，导致无法判断结果，如果查询百度只有一个IP地址返回的话，就表示生效了。
> 
> 这个问题，下个版本解决。

C:\Users\a689>nslookup www.baidu.com
服务器:  Openwrt.lan
Address:  fd9b:eb13:786c::1

非权威应答:
名称:    www.a.shifen.com
Address:  220.181.38.150
Aliases:  www.baidu.com
这样是成功了还是失败了

**Comment by xiaoxiang8002** [comment]
C:\Users\77843>nslookup www.baidu.com
服务器:  OpenWrt.lan
Address:  fd2b:2b6f:b13f::1

非权威应答:
名称:    www.a.shifen.com
Addresses:  2409:8c54:870:29:0:ff:b05c:26bf
          2409:8c54:870:28:0:ff:b049:5cef
          183.232.231.172
Aliases:  www.baidu.com

这个应该是已经设置成功的吧

**Comment by pymumu** [comment]
新版本应该解决了，具体看readme。急用可以取最新代码自行编译。
