### ISSUE TITLE
首次smartdns解析正确，后所有网站都解析到同一地址

### ISSUE THREAD

**Issue by zhaozhejun** [pymumu/smartdns#257]
**问题现象**  
模式dnsmasq
测试nslookup www.baidu.com 或者www.qq.com 首次都可以解析。
后续再运行解析多次，所有网站都返回同一个地址
**运行环境**
1. 固件型号  openwrt

2. 运营商  电信

**重现步骤**
1. 上游DNS配置。 
server-name smartdns
bind :7888
bind-tcp :7888
prefetch-domain yes
cache-size 40960
rr-ttl-min 300
log-size 64K
log-num 1
log-level error 
server-tcp 114.114.114.114  -group china -blacklist-ip 
server-tcp 182.254.116.116  -group china -blacklist-ip 
server-tcp 219.149.194.55  -group china -blacklist-ip 
server-tls dns.rubyfish.cn  -group out -check-edns
server-tls ndns.233py.com  -group out -check-edns
server-https https://cloudflare-dns.com/dns-query  -group out -check-edns
server-tcp 117.50.10.10  -group china -blacklist-ip 
server-tcp 208.67.222.222:5353  -group out -check-edns
server-https https://dns.google/dns-query  -group out -check-edns
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

![baidu](https://user-images.githubusercontent.com/22097252/70865019-8af22500-1f93-11ea-82c4-a4207c9b2ffa.PNG)
![qq](https://user-images.githubusercontent.com/22097252/70865022-8fb6d900-1f93-11ea-808e-f9c8c6805867.PNG)

**Comment by pymumu** [comment]
返回什么IP地址？

**Comment by pymumu** [comment]
https://www.cnbeta.com/articles/23851.htm?source=1
解决方法是将这个IP地址加入bogus列表。在自定义配置项里面增加如下配置：
```shell
bogus-nxdomain 218.30.64.194
```

如果有多个IP的话，可以配置子网。

**Comment by zhaozhejun** [comment]
还真是，我把电信自动获取的dns  server-tcp 219.149.194.55 -group china -blacklist-ip  这行删掉，目前不被抢先劫持了，，bogus那个就是填进黑名单里就好吧？？电信自带dns看来也不可信了，看ping值蛮低的，我才加进来。。

**Comment by zhaozhejun** [comment]
哦哦，在自定义里。。
