### ISSUE TITLE
进程自杀

### ISSUE THREAD

**Issue by paldier** [pymumu/smartdns#258]
**问题现象**  
简要描述问题出现的现象
[2019-12-15 17:51:43,881][FATAL][       smartdns.c:346 ] process exit with signal 7, code = 1, errno = 0, pid = -151444339, self = 16047, pc = 0x26670, addr = 0xf6f9248d, build(Dec 15 2019 23:28:04)
除这条日志外全部都显示正常
Dec 15 18:14:09 watchdog: restart smartdns
Dec 15 18:14:09 smartdns: conf file /etc/blacklist-ip.conf is not readable.
Dec 15 18:14:09 smartdns: conf file /etc/whitelist-ip.conf is not readable.
Dec 15 18:15:43 kernel: Unhandled fault: alignment fault (0x92000021) at 0x00000000f688941b
这是系统日志
**运行环境**
1. 固件型号  
arm64
2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
内存对齐问题，你gdb看看哪里触发的sigbus。
或者你用我发的二进制版本看看

**Comment by paldier** [comment]
看起来这是arm64自身的一些问题，大部分人建议用memcpy，还有一些指出可能和-O2有关

**Comment by paldier** [comment]
改成O1后看起来没有自杀了，不改代码的前提下，arrch64还是改用O1吧
