### ISSUE TITLE
关于预取的一个小建议

### ISSUE THREAD

**Issue by foxconndmd** [pymumu/smartdns#259]
可否设置为一个特定的缓存时间，在缓存时间内如果有查询且域名ttl已过期则返回一个ttl为0的缓存结果给客户端，然后再后台去预取。
感觉这个比现在ttl快超时主动预取几次比较好，有很多情况是在预取时间内没有额外查询域名，1天却可能有很多次。
最新的unbound有这个功能：
 serve-expired-ttl: 86400
 serve-expired: yes

**Comment by pymumu** [comment]
预读的算法就是lru，访问越多，就会一直保留，偶尔访问就应该及时丢弃

**Comment by foxconndmd** [comment]
> 
> 
> 预读的算法就是lru，访问越多，就会一直保留，偶尔访问就应该及时丢弃

谢谢回复，这样会造成资源的浪费，所有的域名就算没有再次查询也会主动预取几次，且经过几次预取后再查询又需要时间主动查询再重复主动预取。

**Comment by soffchen** [comment]
serve-expired 真心建议可以考虑，coredns 最近也加入了这个特性

相较于 prefetch，可以有效避免不热门的域名持续预查询

**Comment by pymumu** [comment]
后面添加吧

**Comment by pymumu** [comment]
已支持。

**Comment by yeezylife** [comment]
> serve-expired 真心建议可以考虑，coredns 最近也加入了这个特性
> 
> 相较于 prefetch，可以有效避免不热门的域名持续预查询

那请问开了prefetch 再开serve-expired会冲突么 @soffchen

**Comment by soffchen** [comment]
> > serve-expired 真心建议可以考虑，coredns 最近也加入了这个特性
> > 相较于 prefetch，可以有效避免不热门的域名持续预查询
> 
> 那请问开了prefetch 再开serve-expired会冲突么 @soffchen

不冲突，prefetch 只针对热门域名，不是热门的落到 server-expired

**Comment by yeezylife** [comment]
> > > serve-expired 真心建议可以考虑，coredns 最近也加入了这个特性
> > > 相较于 prefetch，可以有效避免不热门的域名持续预查询
> > 
> > 
> > 那请问开了prefetch 再开serve-expired会冲突么 @soffchen
> 
> 不冲突，prefetch 只针对热门域名，不是热门的落到 server-expired

感谢回复，我刚开始用smartdns，很多都不懂。。比如serve-expired-ttl 和 rr-ttl-min 这些设置为多少比较好啊，可以贴一下您的设置吗。。 @soffchen

**Comment by foxconndmd** [comment]
谢谢支持此功能，在使用的过程中发现firefox如遇到ttl为0的域名会再次发送dns请求，这样就起不到加速的作用了，反而会多增加一次请求，新版的unbound将过期的域名ttl默认设置为30，并可使用serve-expired-reply-ttl参数自定义返回值。
