### ISSUE TITLE
dnsmasq和smartdns功能类似？

### ISSUE THREAD

**Issue by adaaaaaa** [pymumu/smartdns#26]
而dnsmasq有smartdns没有的功能。。。
所以，smartdns什么做的比dnsmasq好？

**Comment by 523860169** [comment]
> 无法直接连接的网站走代理

这个功能我觉得超级赞，很期待，但是还是希望这个[bug](https://github.com/pymumu/smartdns/issues/29#issuecomment-420694726)能够尽快得到解决@pymumu
