### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#260]
**问题现象**  
编译报错
使用openssl 1.1.1d, 先openssl静态编译
cd smartdns-Release28/src
vi Makefile
...
override CFLAGS += -Iinclude -I/root/smartdns/openssl/include
...
LDFLAGS += -L/root/smartdns/openssl/lib -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -ldl -static

cd smartdns-Release28/package
./build-pkg.sh --platform debian --arch x86_64 --static
...
gcc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -I/root/smartdns/openssl/include -DBASE_FILE_NAME=\"art.c\" -DSMARTDNS_VERION=\"1.2019.12.16-1614\"   -c -o lib/art.o lib/art.c
gcc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -I/root/smartdns/openssl/include -DBASE_FILE_NAME=\"bitops.c\" -DSMARTDNS_VERION=\"1.2019.12.16-1614\"   -c -o lib/bitops.o lib/bitops.c
gcc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -I/root/smartdns/openssl/include -DBASE_FILE_NAME=\"radix.c\" -DSMARTDNS_VERION=\"1.2019.12.16-1614\"   -c -o lib/radix.o lib/radix.c
gcc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -I/root/smartdns/openssl/include -DBASE_FILE_NAME=\"conf.c\" -DSMARTDNS_VERION=\"1.2019.12.16-1614\"   -c -o lib/conf.o lib/conf.c
gcc smartdns.o fast_ping.o dns_client.o dns_server.o dns.o util.o tlog.o dns_conf.o dns_cache.o http_parse.o lib/rbtree.o lib/art.o lib/bitops.o lib/radix.o lib/conf.o -o smartdns -L/root/smartdns/openssl/lib -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -ldl -static
/usr/bin/ld: fast_ping.o: in function `_fast_ping_getdomain':
/root/smartdns/smartdns-Release28/src/fast_ping.c:328: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: smartdns.o: in function `_smartdns_init_ssl':
/root/smartdns/smartdns-Release28/src/smartdns.c:225: undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/smartdns.c:226: undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/smartdns.c:227: undefined reference to `OPENSSL_init_crypto'
/usr/bin/ld: dns_client.o: in function `_dns_client_close_socket':
/root/smartdns/smartdns-Release28/src/dns_client.c:882: undefined reference to `SSL_shutdown'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:883: undefined reference to `SSL_free'
/usr/bin/ld: dns_client.o: in function `_dns_client_server_close':
/root/smartdns/smartdns-Release28/src/dns_client.c:911: undefined reference to `SSL_SESSION_free'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:916: undefined reference to `SSL_CTX_free'
/usr/bin/ld: dns_client.o: in function `_DNS_client_create_socket_tls':
/root/smartdns/smartdns-Release28/src/dns_client.c:1454: undefined reference to `SSL_new'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1490: undefined reference to `SSL_set_fd'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1497: undefined reference to `SSL_set_session'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1500: undefined reference to `SSL_ctrl'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1526: undefined reference to `SSL_free'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1502: undefined reference to `SSL_ctrl'
/usr/bin/ld: dns_client.o: in function `_dns_client_socket_ssl_send':
/root/smartdns/smartdns-Release28/src/dns_client.c:1628: undefined reference to `SSL_write'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1633: undefined reference to `SSL_get_error'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1651: undefined reference to `ERR_get_error'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1657: undefined reference to `ERR_reason_error_string'
/usr/bin/ld: dns_client.o: in function `_dns_client_send_https':
/root/smartdns/smartdns-Release28/src/dns_client.c:2347: undefined reference to `SSL_shutdown'
/usr/bin/ld: dns_client.o: in function `_dns_client_server_add':
/root/smartdns/smartdns-Release28/src/dns_client.c:811: undefined reference to `TLS_client_method'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:811: undefined reference to `SSL_CTX_new'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:857: undefined reference to `SSL_CTX_free'
/usr/bin/ld: dns_client.o: in function `_dns_client_socket_ssl_recv':
/root/smartdns/smartdns-Release28/src/dns_client.c:1684: undefined reference to `SSL_read'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1689: undefined reference to `SSL_get_error'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1707: undefined reference to `ERR_get_error'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:1713: undefined reference to `ERR_reason_error_string'
/usr/bin/ld: dns_client.o: in function `_dns_client_process_tls':
/root/smartdns/smartdns-Release28/src/dns_client.c:2098: undefined reference to `SSL_connect'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2123: undefined reference to `SSL_session_reused'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2103: undefined reference to `SSL_get_error'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2130: undefined reference to `SSL_SESSION_free'
/usr/bin/ld: dns_client.o: in function `_dns_client_tls_verify':
/root/smartdns/smartdns-Release28/src/dns_client.c:2004: undefined reference to `SSL_get_peer_certificate'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2010: undefined reference to `X509_get_subject_name'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2010: undefined reference to `X509_NAME_get_text_by_NID'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2079: undefined reference to `X509_free'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2023: undefined reference to `X509_get_X509_PUBKEY'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2023: undefined reference to `i2d_X509_PUBKEY'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2029: undefined reference to `CRYPTO_malloc'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2036: undefined reference to `X509_get_X509_PUBKEY'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2036: undefined reference to `i2d_X509_PUBKEY'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2069: undefined reference to `CRYPTO_free'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/dns_client.c:2070: undefined reference to `X509_free'
/usr/bin/ld: dns_client.o: in function `_dns_client_process_tls':
/root/smartdns/smartdns-Release28/src/dns_client.c:2141: undefined reference to `SSL_get1_session'
/usr/bin/ld: dns_client.o: in function `_dns_client_tls_verify':
/root/smartdns/smartdns-Release28/src/dns_client.c:2075: undefined reference to `CRYPTO_free'
/usr/bin/ld: util.o: in function `SSL_SHA256':
/root/smartdns/smartdns-Release28/src/util.c:608: undefined reference to `SHA256_Init'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/util.c:609: undefined reference to `SHA256_Update'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/util.c:610: undefined reference to `SHA256_Final'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/util.c:611: undefined reference to `OPENSSL_cleanse'
/usr/bin/ld: util.o: in function `SSL_base64_decode':
/root/smartdns/smartdns-Release28/src/util.c:624: undefined reference to `EVP_DecodeBlock'
/usr/bin/ld: util.o: in function `SSL_CRYPTO_thread_setup':
/root/smartdns/smartdns-Release28/src/util.c:716: undefined reference to `CRYPTO_malloc'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/util.c:717: undefined reference to `CRYPTO_malloc'
/usr/bin/ld: /root/smartdns/smartdns-Release28/src/util.c:721: undefined reference to `CRYPTO_free'
/usr/bin/ld: util.o: in function `SSL_CRYPTO_thread_cleanup':
/root/smartdns/smartdns-Release28/src/util.c:743: undefined reference to `CRYPTO_free'
/usr/bin/ld: util.o: in function `SSL_CRYPTO_thread_setup':
/root/smartdns/smartdns-Release28/src/util.c:723: undefined reference to `CRYPTO_free'
/usr/bin/ld: util.o: in function `SSL_CRYPTO_thread_cleanup':
/root/smartdns/smartdns-Release28/src/util.c:744: undefined reference to `CRYPTO_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:40: smartdns] Error 1
make: Leaving directory '/root/smartdns/smartdns-Release28/src'
make smartdns failed

**运行环境**
1. Debian 10 buster x86_64

**Comment by pymumu** [comment]
要安装静态编译用的openssl库

**Comment by zhouhm** [comment]
兄弟我已经静态编译并安装openssl了，只是我没有把静态编译的openssl安装到标准目录，而是安装到了/root/smartdns/openssl目录

**Comment by zhouhm** [comment]
我大概知道问题的原因了/root/smartdns/smartdns-Release28/src/Makefile我改的不对，落东西了，应该改成LDFLAGS += -L/root/smartdns/openssl/lib -lssl -lcrypto -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -ldl -static

**Comment by zhouhm** [comment]
少了-lssl -lcrypto，明天我再试试

**Comment by zhouhm** [comment]
成功使用openssl 1.1.1d静态编译smartdns

**Comment by zhouhm** [comment]
编译指令:
./build-pkg.sh --platform debian --arch amd64 --static

**Comment by zhouhm** [comment]
不能用--arch x86_64，不知道因为啥

**Comment by foxconndmd** [comment]
[https://www.haiyun.me/archives/1347.html](url)
