### ISSUE TITLE
能否支持a和aaaa记录使用不同的上游dns

### ISSUE THREAD

**Issue by MonwF** [pymumu/smartdns#261]
**需求应用场景**
双栈网络下，电信ipv4网络好，但移动的ipv6好，现在分流配置是ipv4走电信，少量走移动，ipv6全走移动。如果用电信dns解析，得到的ipv6地址对移动访问不友好

**建议的方案**
server 规则可以指定 record类型

**Comment by pymumu** [comment]
可以尝试下双栈ip优选的功能，FAQ的第7点

**Comment by MonwF** [comment]
> 可以尝试下双栈ip优选的功能，FAQ的第7点

感谢回复
之前看过faq，也试了下第7点，但这样的会抑制了ipv6的使用，我其实是想尽可能多使用ipv6流量

**Comment by pymumu** [comment]
那你可以设置阈值，默认是30ms，你可以设置大一些，这样就ipv6就会走的多一些了

**Comment by pymumu** [comment]
那你可以设置阈值，默认是30ms，你可以设置大一些，这样就ipv6就会走的多一些了

**Comment by MonwF** [comment]
> 那你可以设置阈值，默认是30ms，你可以设置大一些，这样就ipv6就会走的多一些了

但dns解析出来的是电信ipv6地址 用移动去访问体验不好 我用overture搭配这个试下吧

**Comment by pymumu** [comment]
上游配置移动DNS。

**Comment by MonwF** [comment]
> 上游配置移动DNS。

感觉没理解我的意思，上游配置移动dns的话，我的所有ipv4都会使用移动宽带访问了，我是想ipv4用电信 ipv6用移动，dns只有1个没法解决问题

**Comment by pymumu** [comment]
配合ipset

**Comment by MonwF** [comment]
已经是ipset分流了 dns解析满足不了需求
还是老实用overture吧
