### ISSUE TITLE
大神 什么时候支持openwrt 19  求更新 求更新  

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#263]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息
我的机子用openwert 19 速度最高   可惜smartdns不支持   安装了 页面错乱没法用

**Comment by pymumu** [comment]
什么情况？19一直都支持啊

**Comment by kkjoy** [comment]
> **需求应用场景**
> 请描述需求应用的场景和方式。
> 
> **建议的方案**
> 实现上述场景建议的方案。
> 
> **设备信息**
> 
> 1. 设备信息（CPU，厂家）
> 2. 固件信息
>    我的机子用openwert 19 速度最高   可惜smartdns不支持   安装了 页面错乱没法用

我用的是OpenWrt 19.07.0-rc2 r10775-db8345d8e4 / LuCI openwrt-19.07 branch git-19.344.41526-af5d665
安装smartdns前请安装luci-compat，19.07默认没装这个库

**Comment by lalasou** [comment]
@pymumu luci 不支持

**Comment by lalasou** [comment]
@kkjoy 谢谢 知道了
