### ISSUE TITLE
server-https里的参数都填啥啊？

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#264]
-spki-pin
-tls-host-check
-hostname
-http-host
这些参数都填啥啊？

之前用dnsdist1.4搭建的DoH服务器端，用dnscrypt-proxy作为DoH客户端，测试功能都正常，但对性能不满意，想用您的smartdns试试

**Comment by zhouhm** [comment]
支持sdns格式的参数就好了，用dnsstamp.py把参数直接就算出来了

**Comment by zhouhm** [comment]
# grep -v '^#' smartdns.conf | sed '/^$/d'
bind :53
cache-size 4096
prefetch-domain yes
rr-ttl 86400
log-level info
server 114.114.114.114 -group g1 -exclude-default-group
server 223.5.5.5 -group g1 -exclude-default-group
server-https https://myurlxxxx.me/21e3g4cd-503f-353f4-b68f-8ceaf1896663 -group g2
nameserver /www.google.com/g2
nameserver /www.facebook.com/g2
nameserver /twitter.com/g2

**Comment by zhouhm** [comment]
dig @127.0.0.1 www.google.com
解析不出结果啊

**Comment by zhouhm** [comment]
我之前的dondist+dnscrypt-proxy组合都没问题啊

**Comment by foxconndmd** [comment]
当地址为ip时，hostname是告诉服务器你所请求的主机域名和sni，-tls-host-check是smartdns检查服务器返回的tls证书是否和Hostname匹配，防止中间人攻击，一般填ip hostname tls-host-check就可以了。

**Comment by zhouhm** [comment]
# grep -v '^#' smartdns.conf | sed '/^$/d'
bind :53
cache-size 4096
prefetch-domain yes
rr-ttl 86400
log-level info
server 114.114.114.114 -group g1 -exclude-default-group
server 223.5.5.5 -group g1 -exclude-default-group
server-tcp 8.8.8.8
server-https https://140.22.20.113/21e964ab-533f-43f4-b68f-8ceaf1896663 -group g2 -tls-host-check -hostname myurlxxxx.me
nameserver /www.google.com/g2
nameserver /www.facebook.com/g2
nameserver /twitter.com/g2
nameserver /github.com/g2

# dig @127.0.0.1 www.google.com

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @127.0.0.1 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65019
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		300	IN	A	172.217.164.100

;; Query time: 1180 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Dec 17 11:15:05 CST 2019
;; MSG SIZE  rcvd: 62

**Comment by zhouhm** [comment]
www.google.com解析出一次，其它都解析不了

**Comment by foxconndmd** [comment]
> 
> 
> [www.google.com解析出一次，其它都解析不了](http://www.google.com%E8%A7%A3%E6%9E%90%E5%87%BA%E4%B8%80%E6%AC%A1%EF%BC%8C%E5%85%B6%E5%AE%83%E9%83%BD%E8%A7%A3%E6%9E%90%E4%B8%8D%E4%BA%86)

用公共doh试试

**Comment by zhouhm** [comment]
兄弟，我的服务器用其它DoH客户端测试过的，一点问题没有

**Comment by zhouhm** [comment]
我帖的IP和域名都是假的，原因不用解释了吧

**Comment by foxconndmd** [comment]
看配置文件没问题，你服务器我也没法测试，你先试试同样配置换其它doh试试行不行。

**Comment by zhouhm** [comment]
https://github.com/m13253/dns-over-https
和dnscrypt-proxy都试过，一点问题没有

**Comment by foxconndmd** [comment]
看日志

**Comment by zhouhm** [comment]
得下午了

**Comment by zhouhm** [comment]
我刚试了一下，国内的IP也解析不了
nameserver /www.163.com/g1

**Comment by foxconndmd** [comment]
> 
> 
> 我刚试了一下，国内的IP也解析不了
> nameserver /www.163.com/g1

你dns服务器哪里有问题，ip正常连接吗？证书是正规的吗？path正常吗？查看日志了吗？

**Comment by zhouhm** [comment]
![IMG_20191217_123813](https://user-images.githubusercontent.com/5276186/70965294-21286700-20ca-11ea-80ff-28bd648a1801.jpg)

**Comment by zhouhm** [comment]
我们网络屏蔽了ping

**Comment by zhouhm** [comment]
日志报网络不可达

**Comment by zhouhm** [comment]
换了一个网络好用了

**Comment by zhouhm** [comment]
用smartdns
dig @127.0.0.1 twitter.com
1039 msec
用dnscrypt-proxy
dig @127.0.0.1 -p 15353 twitter.com
648 msec
用snartdns
dig @127.0.0.1 www.facebook.com
1681 msec
用dnscrypt-proxy
dig @127.0.0.1 -p 15353 www.facebook.com
223 msec

**Comment by zhouhm** [comment]
我们的smartdns还得继续努力啊，smartdns用c语言写的，潜力还很大，dnscrypt-proxy是用golang写的

继续加油😊

**Comment by zhouhm** [comment]
测试是基于同一台测试机，同样的网络进行的

**Comment by foxconndmd** [comment]
> 
> 
> 测试是基于同一台测试机，同样的网络进行的

同一台服务器搭建的不同dns服务？
这个测试不算数的，连接复用和新建立连接差别很大的。

**Comment by zhouhm** [comment]
服务器也是一台，是DoH服务器

**Comment by zhouhm** [comment]
服务器在美国旧金山，ping响应在200 msec左右

**Comment by zhouhm** [comment]
> > 测试是基于同一台测试机，同样的网络进行的
> 
> 同一台服务器搭建的不同dns服务？
> 这个测试不算数的，保持连接和连接复用和新建立连接差别很大的。

再次查询都是0 msec，因为都有缓存啊

**Comment by zhouhm** [comment]
![IMG_20191217_135914](https://user-images.githubusercontent.com/5276186/70968904-7a49c800-20d5-11ea-92af-939202ce5409.jpg)

**Comment by zhouhm** [comment]
上图是我刚刚ping的DoH server的结果，IP地址我打马赛克了，可以看出网络并不好，有丢包现象

**Comment by zhouhm** [comment]
用ss-redir 的udp over tcp转发dns查询最快，不过加上https就不行了，安全性不行

**Comment by pymumu** [comment]
仔细看帮助吧，不要盲目配置，对比性能也不是这么对比的，如果要禁止测速可以配置speed-check-mode

**Comment by zhouhm** [comment]
> 仔细看帮助吧，不要盲目配置，对比性能也不是这么对比的，如果要禁止测速可以配置speed-check-mode

听了大神的指导，配置了一下smartdns.conf中的
speed-check-mode none
再次测试
都用用smartdns
dig @127.0.0.1 www.google.com
229 msec

dig @127.0.0.1 twitter.com
192 msec

dig @127.0.0.1 www.facebook.com
209 msec

解析结果我都在https://ipinfo.io上验证了，是正确的，没有被污染

一句话总结：牛逼带闪电的
就一个问题：第一次解析twitter.com的时候没能返回结果

**Comment by zhouhm** [comment]
我勒个去，找到神器了
再告诉大神一下，今天是头一次用smartdns，昨天下午下班前编译smartdns没编译过去，今天上午编译好了，我用的是自己编译的版本

**Comment by zhouhm** [comment]
> 仔细看帮助吧，不要盲目配置，对比性能也不是这么对比的，如果要禁止测速可以配置speed-check-mode

大神能不能某些组测速，某些组不测速啊，因为有的组就一个成员

**Comment by pymumu** [comment]
后续增加特定域名停止测速，当前只能不同端口停止测速。
