### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#265]
**问题现象**  
每次打开/var/log/smrtdns.log日志,都显示下例信息,只有这段位,就没有任何信息
[2019-12-17 10:25:50,048][ERROR][      fast_ping.c:454 ] sendto 2402:f000:1:416:101:6:6:172, id 112, Permission denied

**运行环境**
X86

2. 运营商  
中国电信和联通
**重现步骤**
[smartdns.log](https://github.com/pymumu/smartdns/files/3971171/smartdns.log)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
关闭ipv6禁止ping的策略，或忽略
