### ISSUE TITLE
超长域名返回结果有异常

### ISSUE THREAD

**Issue by moetakaoruko** [pymumu/smartdns#267]
**问题现象**  
idcs-8c13c57311bc4bfdb25e8b11d37b8298.identity.oraclecloud.com 这样的超长域名，返回出来的IP是错误的，甚至每次都不一样，似乎是有内存泄漏

**运行环境**
1. 固件型号  

x64 Ubuntu 18.04

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

运营商DNS或 114.114.114.114，再配置一个Google DNS

2. 访问的域名。  
idcs-8c13c57311bc4bfdb25e8b11d37b8298.identity.oraclecloud.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
这个问题很早之前改过，你确认用最新版本了妈？

**Comment by moetakaoruko** [comment]
是我版本的问题，换最新版好了
