### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by xiaoluoabc123** [pymumu/smartdns#268]
smartdns-1.2019.11.02-1102.tar.gz: Download from https://github.com/pymumu/smartdns.git failed
smartdns-1.2019.11.02-1102.tar.gz: Requires sha256sum for verification
Checking out files from the git repository...
Cloning into 'smartdns-1.2019.11.02-1102'...
remote: Enumerating objects: 2429, done.
remote: Counting objects: 100% (2429/2429), done.
remote: Compressing objects: 100% (663/663), done.
remote: Total 2606 (delta 1575), reused 2406 (delta 1553), pack-reused 177
Receiving objects: 100% (2606/2606), 1.28 MiB | 967.00 KiB/s, done.
Resolving deltas: 100% (1690/1690), done.
Checking connectivity... done.
fatal: reference is not a tree: d51f5e6eeba7bfde1b108fe32d540bd429550573
Makefile:75: recipe for target '/home/cheng/111/lede/dl/smartdns-1.2019.11.02-1102.tar.gz' failed
make[3]: *** [/home/cheng/111/lede/dl/smartdns-1.2019.11.02-1102.tar.gz] Error 128
make[3]: Leaving directory '/home/cheng/111/lede/package/lean/smartdns-master/package/openwrt'
time: package/lean/smartdns-master/package/openwrt/compile#0.39#0.18#4.93
package/Makefile:107: recipe for target 'package/lean/smartdns-master/package/openwrt/compile' failed
make[2]: *** [package/lean/smartdns-master/package/openwrt/compile] Error 2
make[2]: Leaving directory '/home/cheng/111/lede'
package/Makefile:103: recipe for target '/home/cheng/111/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/cheng/111/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/cheng/111/lede'
/home/cheng/111/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by pymumu** [comment]
用build_pkg编译

**Comment by garypang13** [comment]
> 用build_pkg编译

一模一样的错误,导致luci-app-smartdns和smartdns都无法在openwrt中编译成功,smartdns可以用build_pkg编译那luci-app-smartdns怎么办呢?  且插件都是随固件一起编译的,如果每次还要另外编译smartdns的话就太麻烦了.

**Comment by xiaoluoabc123** [comment]
> 用build_pkg编译

编译出来99kb，不对吧?
