### ISSUE TITLE
如何解析baidu.com结束的所有域名？.baidu.com不好用啊

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#269]
我的配置
cat smartdns.conf
...
server 114.114.114.114 -group g1 -exclude-default-group
...
nameserver /.baidu.com/g1

我想把baidu.com，www.baidu.com，pan.baidu.com，blog.baidu.com ...都用g1中的dns进行解析

**Comment by pymumu** [comment]
看你这配置没错，你怎么确认功能没生效的？

可以打开debug日志看看有没有group g1的打印

**Comment by zhouhm** [comment]
估计还是跟我的网络有关，我的网络环境有点次

**Comment by zhouhm** [comment]
还是偶尔解析不出结果，不知道啥原因

**Comment by pymumu** [comment]
可以看看日志，是否是请求超时了。

**Comment by pymumu** [comment]
有问题再reopen把。
