### ISSUE TITLE
求一个freebsd x64的版本

### ISSUE THREAD

**Issue by lixuy** [pymumu/smartdns#27]
用在pfsense上

**Comment by pymumu** [comment]
sorry，暂时不考虑支持bsd，现在代码用了linux独有的接口，改造有一些工作量
关键还是bsd当路由的用户不多，所以暂不考虑

**Comment by lixuy** [comment]
那可以给个openwrt x86的版本吗，因为一些原因，跑不了x64的openwrt，用release 的x64不能用。

**Comment by pymumu** [comment]
已经发布了，安装下看看。
