### ISSUE TITLE
smartdns有解析超时设置参数吗？没找到啊

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#273]
如题

**Comment by zhouhm** [comment]
在server、server-tls、server-https参数后面

**Comment by pymumu** [comment]
没有配置，最长超时1s，如不想测速，可以开启第二dns端口，配置次端口请求不测速

**Comment by muziling** [comment]
有计划增加超时的配置吗， DNS走的VPS速度不是很理想， 默认的1S经常导致国外域名解析失败，要多刷新几次才行

**Comment by pymumu** [comment]
如果走的tls，https，第一次请求时间是可能大于1s的。这个后续改进把。

**Comment by zhouhm** [comment]
现在已经不用DoT或DoH了，用tcp，用本地代理把数据加密传出去，速度是刷刷的，代理用的不是ss和v2啊

**Comment by pymumu** [comment]
你什么类型的CPU，我调整一下重试次数，你验证一下看看

**Comment by zhouhm** [comment]
X86_64和mipsel_24kc两种都试了，我用的代理网上找不到，纯c语言实现的，另外vps性能也得好，bwh和doit的CN2 GIA没问题，一定是美西，洛杉矶，旧金山，西雅图，圣何塞这些，阿里国际香港和新加坡也没问题

**Comment by zhouhm** [comment]
美西一般200ms左右，阿里国际一般不到60ms，牛逼带闪电的

**Comment by pymumu** [comment]
这个和服务器性能没有关系，一般国际线路有可能丢包，特别是晚上，丢包严重，这样会造成tcp建立连接缓慢，建立连接时间都可能大于1s，再加上tcp的请求相比udp本来就慢。

改了3s，应该可以减少解析失败的概率 。
[smartdns-build.zip](https://github.com/pymumu/smartdns/files/4567125/smartdns-build.zip)

另外，也可以配置多个线路的tls，确保解析成功。

**Comment by zhouhm** [comment]
用DoH确实会超时，但用server_tcp没有过，这跟本地代理性能有直接关系

**Comment by pymumu** [comment]
tcp只有三次握手。
dot，doh三次握手后，还要交换证书，密钥，会更慢。

**Comment by zhouhm** [comment]
老大，我用tcp也交换证书密钥的，只不过由代理完成的

**Comment by zhouhm** [comment]
我的代理用纯c语言（不是c++）实现，性能碾压一切其它软件，用tls1.3

**Comment by zhouhm** [comment]
刚刚试的，没有缓存啊

**Comment by pymumu** [comment]
你那个应该是建立好连接，然后一直使用。
doh的，大部分DNS服务器60s没请求，就会强制断链了。再有请求就要建立连接。

如果按请求时延150ms计算。
如果是udp，那么就是150ms响应。
如果是tcp，那么最快300ms响应。
如果是tls，最快450ms响应。

中间有丢包的话，

**Comment by zhouhm** [comment]
[
![1](https://user-images.githubusercontent.com/5276186/80856202-64026a00-8c7a-11ea-8691-2c6d7a4040be.png)

**Comment by zhouhm** [comment]
老大解释的透彻，对，我的已经建立好连接了，阿里国际新加坡确实是几十ms

**Comment by zhouhm** [comment]
我抓图的用的是doit洛杉矶CN2 GIA线路

**Comment by zhouhm** [comment]
![IMG_20200502_135846-1](https://user-images.githubusercontent.com/5276186/80856553-b98c4600-8c7d-11ea-9144-a78f4291cbd1.jpg)

**Comment by zhouhm** [comment]
这是用阿里国际，但用的是udp over tcp技术

**Comment by pymumu** [comment]
please feel free to reopen this issue.
