### ISSUE TITLE
ECS支持不完整

### ISSUE THREAD

**Issue by simonsmh** [pymumu/smartdns#277]
**问题现象**  
首先是`_conf_edns_client_subnet`函数里判断有问题，导致ECS参数无法加载。
https://github.com/pymumu/smartdns/blob/master/src/dns_conf.c#L1150
然后抓包发现EDNS0参数是有了，但是没有ECS信息，因此ECS没有完全实现。
![image](https://user-images.githubusercontent.com/9512067/71180879-0a426a00-22ae-11ea-800f-4bd8341edfe9.png)
ECS的功能性在于可用使用境外支持的DNS进行CDN友好的解析，所以希望能完善一下。
**运行环境**
1. 固件型号  
NaN
2. 运营商  
NaN

**重现步骤**
1. 上游DNS配置。  
NaN
2. 访问的域名。  
NaN

**信息收集**  
NaN

Reference: https://tools.ietf.org/html/rfc7871

**Comment by foxconndmd** [comment]
这个可以有，国内大站基本上都支持edns解析，使用edns加预取可以全局使用dot或doh了。

**Comment by pymumu** [comment]
没有想清楚使用场景，所以没做完。
ecs只是给递归dns用的，本地dns场景到底是什么？

**Comment by foxconndmd** [comment]
> 
> 
> 没有想清楚使用场景，所以没做完。
> ecs只是给递归dns用的，本地dns场景到底是什么？

全网域名解析走dot加密，国外ip全部走代理，避免了本地明文解析隐私泄露。

**Comment by pymumu** [comment]
代理的话，上游dns服务器用的ecs应该是代理的ip，本地dns设置ecs似乎没有用

**Comment by foxconndmd** [comment]
> 
> 
> 代理的话，上游dns服务器用的ecs应该是代理的ip，本地dns设置ecs似乎没有用

解析的时候subnet带上本地的IP段

**Comment by pymumu** [comment]
如果只是请求dns要加密，tls，https就可以了

**Comment by foxconndmd** [comment]
> 
> 
> 如果只是请求dns要加密，tls，https就可以了

是啊，不使用ecs国内大站访问效果不好。

**Comment by simonsmh** [comment]
ECS的目的是使得获取的DNS可以偏向CDN友好，当前转发之后大概率并不能得到CDN友好的IP，因为延迟并不一定决定最优IP，尤其是跨国链路影响最大，设定EDNS可以减少解析到不合适的IP的几率。
另外，当前的全局edns-client-subnet参数不太适合，应该加给group设定，同时类似的设计可以参考这个项目。 https://github.com/shawn1m/overture

**Comment by pymumu** [comment]
这里有个悖论，递归服务器获得的ecs，和近段服务器发送的ecs什么情况下会不一样？

**Comment by foxconndmd** [comment]
经测试google dns服务器是使用携带的subnet而非smartdns查询ip，在国外vps上用dig带国内subnet段测试的。
smartdns ecs实现可以参考：
1.开启ecs转发，如果查询客户端携带subnet，直接转发，否则使用客户端ip段，同时如果客户端ip为私有则不转发ecs
2.开启ecs转发，同时有配置subnet，smartdns转发使用配置的subnet

**Comment by railjty** [comment]
所以现在是否能支持ECS？配置文档里写了用法但是不能使用

**Comment by rodge-liu** [comment]
这个ECS 功能.还有计划要做上去吗.
我这边是有多个不同国家的出口.上游指向8.8.8.8.我希望可以通过ECS(随便用另一个国家的IP) 来让8.8.8.8 解析的指定的的国家的IP
