### ISSUE TITLE
后面会增加支持SRV记录吗

### ISSUE THREAD

**Issue by JDex623** [pymumu/smartdns#278]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
什么场景，srv现在是透传到上游的

**Comment by JDex623** [comment]
windows AD

**Comment by windoze** [comment]
这个功能还是挺有用的，windows激活需要srv记录自动发现kms server。

**Comment by pymumu** [comment]
done
