### ISSUE TITLE
网关本机不能用到 SmartDNS 的解析服务，其他一切正常

### ISSUE THREAD

**Issue by 70599** [pymumu/smartdns#279]
**问题现象**  
网关本机（路由器）不能用到SmartDNS的解析服务，其他一切正常

**运行环境**
1. 固件型号  
  OpenWrt R9.12.03

2. 运营商  
  应该和运营商无关

**重现步骤**
1. 直接运行```dig```：  
  ```shell
  # dig twitter.com +short
  31.13.86.8
  ↑ 污染过的 IP

 # dig baidu.com +short
  39.156.69.79
  220.181.38.148
  ↑ 多个结果
  ```
2. 指定 IP、端口 运行```dig```：  
  ```shell
  # dig twitter.com +short @127.0.0.1 -p 6053
  104.244.42.129
  ↑ 正确 IP

 # dig baidu.com +short @127.0.0.1 -p 6053
  220.181.38.148
  ↑ 一个结果
  ```

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
  没有这个文件。
  ```log-level error```是开启的，程序应该没有出错
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
  进程也是正常的。  
3. ```iptables```转发也是正常的，局域网下所有客户端都正常。  
  ```shell
  # iptables -t nat -L PREROUTING | grep REDIRECT
  REDIRECT   udp  --  anywhere             anywhere             udp dpt:domain redir ports 6053
  REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:domain redir ports 6053
  ```

**Comment by pymumu** [comment]
iptable没有对本机的dns请求做任何处理。所以本机的请求不会发送到smartdns。

如要发送，可以配置/etc/resolv.conf文件，nameserver指向smartdns。

**Comment by 70599** [comment]
/etc/resolv.conf 文件里面该怎样写入端口号 6053 呢？我试过```:```和```#```没有效果

**Comment by 70599** [comment]
我最终没有使用```/etc/resolv.conf```，参考[这个文章](https://cokebar.info/archives/664)的下面这段描述，解决了网关本机的 DNS 处理。

> 如果你需要路由器自身也能翻，那么到这里还没结束，因为目前的DNS设置不会对路由器自身访问WAN时候的DNS请求生效，还要下面的的额外步骤：
> 
> 切换到WAN口设置→高级设置，取消“使用端局通告的DNS服务器”的勾选，并在“使用自定义的DNS服务器”中填入127.0.0.1

**Comment by shantsaichan** [comment]
同样问题
