### ISSUE TITLE
多拨下无法使用

### ISSUE THREAD

**Issue by ooxx9978** [pymumu/smartdns#28]
dns server process failed

**Comment by 523860169** [comment]
不止多拨，我单拨也经常遇到，像进程卡死，但是smartdns重启又不管用，只能路由器重启才行

**Comment by pymumu** [comment]
具体现象是什么，看看iptable路由表是不是还在

iptables -L | grep 5353

看看重定向端口的规则还在不在。@523860169

**Comment by 523860169** [comment]
@pymumu 等再遇到我发日志吧，不是一定遇到，有时一直遇到，有时几天才遇到，遇到了一重启路由器，日志就没了
