### ISSUE TITLE
为什么我的google返回的是127.0.0.1.我用的openwrt里的smartdns，dhcp的dns是pihole

### ISSUE THREAD

**Issue by feifan1113** [pymumu/smartdns#280]
**问题现象**  
简要描述问题出现的现象  油管和国内正常，只有谷歌会返回错误的dns

**运行环境**
1. 固件型号  k2p做主路由，N1里的docker op(192.168.2.2)做旁路， k2p负责DHCP  op负责网关，N1里的docker pihole(192.168.2.53)负责DNS，然后pihole里的上游DNS填smartdns（192.168.2.2#6053）：

2. 运营商  
移动

**重现步骤**
1. 上游DNS配置。  
阿里 百度 114
2. 访问的域名。  
www.google.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

![快照48](https://user-images.githubusercontent.com/57245399/71303670-e8083380-23f6-11ea-8680-48906978694c.png)
[smartdns.log](https://github.com/pymumu/smartdns/files/3991096/smartdns.log)

**Comment by pymumu** [comment]
改用https，或tls做上游。
