### ISSUE TITLE
请增加启动日志

### ISSUE THREAD

**Issue by yjbyf** [pymumu/smartdns#282]
**需求应用场景**
开启重定向，两种方式都失败了，luci显示失败提示，但是提示信息太简单了。
查看/var/log/下的日志也没什么错误提示，没有具体的错误信息无法排查具体是什么原因。

**建议的方案**
建议在/etc/init.d下的smartdns脚本加入日志输出

**设备信息**
1. OpenWrt 18.06   Armv7

**Comment by pymumu** [comment]
看syslog或/var/log/smartdns.log
