### ISSUE TITLE
刚刚安装的smartdns，一启动就会出现很多连接外部服务器80端口

### ISSUE THREAD

**Issue by sancome** [pymumu/smartdns#284]
关掉smartdns这些连接就消失了，这个问题哪位能帮忙解决一下？

tcp        0      0 XXX.XX.117.89:43150     17.248.158.148:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:46586     17.248.160.52:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:35614     17.248.158.211:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:38486     17.248.156.40:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:42932     17.248.158.148:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:46314     17.248.159.245:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:35964     17.248.159.175:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:42298     99.80.201.175:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:48566     54.154.3.223:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:36840     52.30.221.114:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:56170     17.250.120.73:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:58166     54.154.6.32:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:36338     52.209.85.91:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:44636     52.214.191.135:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:54432     52.210.197.74:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:47886     54.72.159.116:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:55876     54.171.178.93:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:45332     17.248.156.12:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:58480     52.51.205.5:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:44824     17.248.158.244:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:45028     52.17.14.59:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:60568     17.250.120.43:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:53060     54.72.190.25:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37376     17.248.160.77:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:40806     17.250.120.209:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:55470     17.248.156.73:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:42846     17.248.158.213:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:42106     17.250.120.17:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:35124     54.77.189.18:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:43126     52.210.216.213:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:42014     52.214.37.106:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:39284     52.214.60.230:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:39776     17.248.152.104:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:36710     17.154.66.255:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:52722     54.171.9.10:80          FIN_WAIT2   -                   
tcp        0      0 XXX.XX.117.89:54738     52.19.50.115:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:58374     17.248.159.108:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:41176     17.248.160.43:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:52492     17.248.156.81:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:33580     17.250.120.74:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37752     106.75.42.87:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:35132     101.227.172.15:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:56788     17.248.160.48:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:48240     54.194.178.248:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:49834     54.76.251.248:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:34660     54.72.165.136:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:55450     54.154.217.112:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:47052     17.173.66.210:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:52474     54.76.146.103:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37330     17.248.158.147:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:41626     52.208.163.160:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:55382     106.75.42.89:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37798     54.194.134.173:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:57792     17.248.156.13:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:41968     17.250.120.145:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:60802     17.248.156.76:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:40686     54.229.11.16:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:44786     17.248.158.204:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:44680     17.248.156.17:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:51472     54.194.115.233:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:56458     54.76.55.3:80           TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37738     52.212.173.62:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:57686     61.151.206.37:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:51112     17.248.152.145:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37038     17.250.120.12:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:51284     17.248.159.176:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:37058     54.76.87.64:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:32854     54.72.47.162:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:45392     54.76.4.109:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:48400     52.210.38.150:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:40064     52.214.112.69:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:33598     52.49.28.28:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:56458     17.248.160.49:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:41598     17.248.160.44:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:38332     52.215.100.90:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:34694     54.77.132.12:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:48022     52.212.41.221:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:46946     17.248.158.144:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:48164     17.248.152.80:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:38980     52.51.87.104:80         TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:46738     17.248.159.210:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:45816     17.110.234.69:80        TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:41276     52.214.200.82:80        TIME_WAIT   -                   
tcp        0      1 XXX.XX.117.89:60094     40.81.94.65:80          FIN_WAIT1   -                   
tcp        0      0 XXX.XX.117.89:34134     17.248.158.118:80       TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:39234     17.57.145.5:80          TIME_WAIT   -                   
tcp        0      0 XXX.XX.117.89:51394     106.75.42.85:80         TIME_WAIT   -                   
tcp6       0      0 ::1:25                  :::*                    LISTEN      1817/master         
tcp6       0      0 :::22                   :::*                    LISTEN      1641/sshd           
tcp6       0      0 XXX.XXX:5016:8:::36352 2403:300:a41:705::5:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::49918 2600:1417:76:197::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::58558 2600:1417:76:1bc::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::55202 2a02:26f0:7000:284:::80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::55278 2403:300:a41:907::b:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::50480 2403:300:a41:909::d:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::52912 2403:300:a41:70f::8:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::54142 2600:1417:76:1bb::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::59040 2403:300:a41:300::c:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::55098 2001:418:1456:a89::4:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::33434 2600:1417:76:1b3::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::40934 2403:300:a41:906::11:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::52168 2600:1417:76:1ad::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::58102 2403:300:a41:700::5:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::60048 2403:300:a41:70e::4:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::34128 2403:300:a41:908::d:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::48818 2600:1417:76:193::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::55098 2403:300:a41:90e::b:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::43808 2403:300:a41:303::4:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::38048 2a02:26f0:7000:28a:::80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::44262 2001:418:1456:a86::4:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::59712 2403:300:a41:301::5:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::38828 2600:1417:76:1b2::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::58900 2600:1417:76:19a::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::45358 2403:300:a41:303::8:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::58642 2001:418:1456:a98::4:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::38404 2403:300:a41:90e::11:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::34818 2403:300:a41:90a::9:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::49496 2403:300:a41:300::7:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::33738 2403:300:a41:905::7:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::40934 2600:1417:76:189::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::38160 2a02:26f0:7000:28a:::80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::60876 2403:300:a41:905::c:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::49856 2001:418:1456:a94::4:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::39060 2403:300:a41:70f::9:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::55090 2a02:26f0:7000:284:::80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::34086 2403:300:a41:908::12:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::41026 2600:1417:76:1bd::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::45640 2403:300:a41:301::c:80  TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::37350 2600:1417:76:19b::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::49358 2600:1417:76:188::44:80 TIME_WAIT   -                   
tcp6       0      0 XXX.XXX:5016:8:::34074 2403:300:a41:300::d:80  TIME_WAIT   -

**Comment by sancome** [comment]
用的是最新的release版本。

**Comment by pymumu** [comment]
测速的链接

**Comment by o2bit** [comment]
都说了会用TCP去建立连接的 测哪个最快

**Comment by hmony** [comment]
你用的speed-check-mode tcp:80,tcp:443,ping ，你用的是tcp:80 来检测你的域名返回的速度。
