### ISSUE TITLE
指定域名配置nameserver和ipset时，不希望对返回的地址做speed check

### ISSUE THREAD

**Issue by unicser** [pymumu/smartdns#285]
**需求应用场景**
指定域名配置nameserver和ipset时，不希望对返回的地址做speed check

**建议的方案**
针对指定域名定义speed check开关

**设备信息**
N/A

**Comment by pymumu** [comment]
后续版本加入

**Comment by kkkgo** [comment]
也需要这个功能

**Comment by gosleep2018** [comment]
弱弱 问问，我没搞清楚 ipset 和 nameserver 的区别，比如 ，我设置了一个vps ss服务器，通过ss科学上网，我想让一个域名 被忽略（根据介绍，ipset /domain/-，nameserver /domaii/-可以设置某域名忽略）
1、我应该用ipset 还是nameserver 去设置；
2、被忽略的定义 是什么，是否这个dns 走vps的dns解析？
