### ISSUE TITLE
IP黑名单问题

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#287]
例如:上游IP地址是:119.29.29.29、223.5.5.5
在黑名单里是不是设为：blacklist-ip 119.29.29.29/16、blacklist-ip 223.5.5.5/16
这个黑名单机制有什么用

**Comment by pymumu** [comment]
有些错误的IP可以通过IP黑名单过滤掉，避免错误解析。udp协议的dns才需要这个。
