### ISSUE TITLE
在 OpenWrt 中 smartdns 配合 shadowsocksR Plus 最优化的方式

### ISSUE THREAD

**Issue by luckyyyyy** [pymumu/smartdns#288]
**需求应用场景**
目前我使用了 L大 https://github.com/coolsnowwolf/lede 集成的 smartdns 使用时一些疑惑

我个人认为 smartdns 非常适合国内局域网的场景 
但是对于SSR其实还是适合走SSR对远程服务更快的线路
所以目前我的设置是继续让SSR走PDNS的解析结果

但是发现部分情况下 smartdns 会优先接替掉 PDNS 的结果不知为何
运行模式是 dnsmasq 上游
不知有无同学遇到过这样的情况？重启 smartdns 后即正常

正确的 google 情况应该是如下这样的

```shell
# 使用 smartdns
dig www.google.com @127.0.0.1 -p 6053 +short
69.171.233.37
# 使用 PDNS 解析对节点来说最快的IP
dig www.google.com @127.0.0.1 -p 5335 +short
172.217.24.4
# 使用 dnsmasq 转发至 smartdns （因为是google这里其实由PDNS接管）
dig www.google.com @127.0.0.1 -p 53 +short
172.217.24.4
```

正常的国内网站 1688 测试结果

```shell
# 使用 smartdns
dig www.1688.com @127.0.0.1 -p 6053 +short
www.1688.com.danuoyi.tbcache.com.
115.231.40.99
# 使用 PDNS （解析出来的IP是国外的，属于正常情况）
dig www.1688.com @127.0.0.1 -p 5335 +short
www.1688.com.danuoyi.tbcache.com.
47.246.23.235
47.246.23.236
# 使用 dnsmasq 转发至 smartdns
dig www.1688.com @127.0.0.1 -p 53 +short
www.1688.com.danuoyi.tbcache.com.
115.231.40.99
```

**设备信息**
X86

**Comment by dengchan0416** [comment]
SSR我是全部改成5335,DNS解析方式:使用本机端口5335,试过用PDNS的解析,nslookup youtube.com会有多个IP地址,而且了5335之后,就只有一个IP.

**Comment by luckyyyyy** [comment]
> SSR我是全部改成5335,DNS解析方式:使用本机端口5335,试过用PDNS的解析,nslookup youtube.com会有多个IP地址,而且了5335之后,就只有一个IP.

我不知道你的5335是哪个服务，我的目的就是要让 smartdns 只负责国内，PDNS负责国外。

**Comment by pymumu** [comment]
smartdns主要是跨区，国访问（非墙网站）网站效果好，对于结合其他软件，可以使用nameserver分流加禁止测速来支持，可以看看faq。

对特定域名停止测速，考虑后续支持。

**Comment by luckyyyyy** [comment]
> smartdns主要是跨区，国访问（非墙网站）网站效果好，对于结合其他软件，可以使用nameserver分流加禁止测速来支持，可以看看faq。
> 
> 对特定域名停止测速，考虑后续支持。

明白 谢谢

**Comment by garypang13** [comment]
我试了下,用smartdns解析出来的google ip是台湾,应该就是最快的,
