### ISSUE TITLE
这个NSLOOKUP结果算是成功了吗？

### ISSUE THREAD

**Issue by Myoko** [pymumu/smartdns#293]
PS C:\Users\Saker> nslookup www.baidu.com
服务器: PowerShell.lan
Address: fda7:1818:609d::1

非权威应答:
名称: www.a.shifen.com
Address: 14.215.177.39
Aliases: www.baidu.com

PS C:\Users\Saker> nslookup www.youtube.com
服务器: PowerShell.lan
Address: fda7:1818:609d::1

非权威应答:
名称: youtube-ui.l.google.com
Addresses: 2404:6800:4012::200e
172.217.163.238
Aliases: www.youtube.com

PS C:\Users\Saker>

ytb和百度都只返回1个IP 第一个方法反复尝试都不行 只能使用第二个方法

**Comment by pymumu** [comment]
Readme里面有检查方法，一般情况，baidu只返回一个IP的话，应该是正常工作了

**Comment by Myoko** [comment]
感谢
按照readme里面的检查方法 nslookup -querytype=ptr smartdns 检测不好使提示*** PowerShell.lan 找不到 smartdns: Non-existent domain 然后改用NSLOOKUP网址后检查多个都只有1个IP返回应该是正常工作的

root@PowerShell:~# nslookup www.baidu.com 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:      www.baidu.com
www.baidu.com   canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 14.215.177.39
*** Can't find www.baidu.com: No answer
root@PowerShell:~# nslookup www.pcbeta.com 192.168.200.1
Server:         192.168.200.1
Address:        192.168.200.1#53

Name:      www.pcbeta.com
www.pcbeta.com  canonical name = webmaster.pcbeta.com
Name:      webmaster.pcbeta.com
Address 1: 218.93.127.66
www.pcbeta.com  canonical name = webmaster.pcbeta.com
root@PowerShell:~#
