### ISSUE TITLE
centos7上的子网卡无法解析

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#294]
环境是centos7 x64，网卡上启用了子网卡，smartdns是最新的28。

用ens160来IP解析是正常的，但是用子网卡ens160:0的IP来解析就不行，好奇怪。

ens160和ens160:0是同一个网段的，试了dnsmasq是可以的。

另外子网卡端口也是可以telnet通的。

**Comment by pymumu** [comment]
可能从主网口发回应包了，感觉要指定源ip发送

**Comment by pymumu** [comment]
可以暂时用bind 指定ip地址，可以配置多个ip

**Comment by PHCSJC** [comment]
大佬你好，这个问题在Release 30上仍然存在，暂时还是用bind ip来解决的，希望大佬能修复，谢谢！
