### ISSUE TITLE
移动网络配合Smartdns似乎没什么效果

### ISSUE THREAD

**Issue by lon91ong** [pymumu/smartdns#295]
**问题现象**  
移动网络有些网页无法打开，好多人说是因为DNS的问题，以为Smartdns可以解决这个问题
然而并没有用，以前打不开的现在还打不开
比如：手机淘宝首页-领淘金币 这个页面就始终打不开，换别的网络就OK

**运行环境**
Win10 x64 PC环境通过Debian运行Smartdns，监听0.0.0.0:53
版本: 1.2019.12.15-1028.x86_64
运营商: 河北移动宽带

**重现步骤**
1. 上游DNS配置。  [设置参考](https://github.com/lon91ong/smartdns4win)
```
bind 0.0.0.0:53
cache-size 512
prefetch-domain yes
dualstack-ip-selection yes
rr-ttl-min 120
log-level error
server 10.0.0.10
server 10.0.0.9
server 211.157.15.189
server 210.22.84.3
server 203.240.193.11
server-tcp 8.8.8.8
server-tcp 114.114.114.114
server-tcp 119.29.29.29
```

2. 访问的域名。  
手机淘宝首页-领淘金币 页面无法打开
![手机淘宝领淘金币](https://user-images.githubusercontent.com/16462258/71640948-eda32a80-2cce-11ea-9f52-5a1597f8dff1.jpg)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
[smartdns.zip](https://github.com/pymumu/smartdns/files/4014024/smartdns.zip)

**Comment by pymumu** [comment]
尽量使用tls，https协议。还有就是合理使用黑名单。

**Comment by lon91ong** [comment]
实测有效，多谢指点！
