### ISSUE TITLE
conf-file /etc/smartdns/smartdns.more.conf

### ISSUE THREAD

**Issue by thb007** [pymumu/smartdns#296]
请问这个附加的配置里面的内容填写什么？目前有下面几点疑惑：

1、填写127.0.0.1   guanggao.com可以吗（类似hosts文件的格式）
2、填写这些可以吗？ whitelist-ip 1.2.3.4/16 
3、填写这些  nameserver /www.example.com/office

**Comment by pymumu** [comment]
参数格式必须要smartdns支持的。

可以参考smartdns readme中的参数说明
https://github.com/pymumu/smartdns#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0
