### ISSUE TITLE
能否提供一个 国内外 DNS 服务器 的清单？

### ISSUE THREAD

**Issue by sedneysun** [pymumu/smartdns#297]
**需求应用场景**
请描述需求应用的场景和方式。
本来想按照软件说明里的要求多配置几个国内外的DNS服务器并通过不同的方式查询（UPD，TCP，TLS，HTTPS 等），但本人小白，国内的只知道 自己ISP分配的DNS服务器，以及114和阿里的DNS，国外的就只知道 谷歌的（8.8.8.8）DNS，而且对这些DNS服务器支持哪些方式查询以及在smartDNS上如何实现 不是很清楚
**建议的方案**
实现上述场景建议的方案。
能否提供一个国内外DNS 服务器列表，并说明相关DNS服务器支持的查询方式以及在smartDNS中的配置方法 ？ 或者可以把这个做成 smartDNS中的内置的默认配置，本人小白只会照图操作，pymumu 多多包涵

**设备信息**
1. 设备信息（CPU，厂家）  
Lean 大的OpenWrt X86_64 软路由
2. 固件信息

**Comment by pymumu** [comment]
Google就支持dot和doh，可以搜索引擎搜索dot，doh
