### ISSUE TITLE
无法ping通baidu，或者任何网站

### ISSUE THREAD

**Issue by TillLindemann** [pymumu/smartdns#298]
**问题现象**  
设置了smartdns，本地端口6053，重定向无，然后在lan口设置DNS服务器为旁路由的内网ip地址，在openclash里设置上游DNS服务器为127.0.0.1：6053
虽然所有网站都可以访问，包括外网，但是在mac上，用nslookup是能找到唯一的ip地址，结果如下：
➜  ~ nslookup www.baidu.com
Server:		192.168.1.2
Address:	192.168.1.2#53

Non-authoritative answer:
Name:	www.baidu.com
Address: 198.18.0.17

但是无法在mac上ping通这个ip，显示如下：
➜  ~ ping 198.18.0.17
PING 198.18.0.17 (198.18.0.17): 56 data bytes
Request timeout for icmp_seq 0
92 bytes from openwrt.lan (192.168.1.2): Redirect Host(New addr: 192.168.1.1)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 76dc   0 0000  3f  01 7c9a 192.168.1.103  198.18.0.17

Request timeout for icmp_seq 1
92 bytes from openwrt.lan (192.168.1.2): Redirect Host(New addr: 192.168.1.1)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 7908   0 0000  3f  01 7a6e 192.168.1.103  198.18.0.17

Request timeout for icmp_seq 2
92 bytes from openwrt.lan (192.168.1.2): Redirect Host(New addr: 192.168.1.1)
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 0054 4ac4   0 0000  3f  01 a8b2 192.168.1.103  198.18.0.17

^C
--- 198.18.0.17 ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss

这日志上面显示请求被重定向至我的主路由器（我用的是老笔记本作旁路网关，强制dhcp，主路由没有做任何设置，主路由的dns应该是运营商的，但是没道理连baidu都劫持）。而且绝大多数域名都被解析到198.0.18.x这个网段，应该不是真实ip。

但是奇怪的是，假如我取消掉openclash的上游DNS服务器（即那个127.0.0.1），那么我将无法访问任何网站，百度，谷歌都显示断连。

另外，重定向里所有的设置都会导致失败，无法重定向。

**运行环境**
1. 固件型号  
openwrt，x86_64
2. 运营商  
教育网，应该是电信。
**重现步骤**

1. 上游DNS配置。  
各大DNS服务器

2. 访问的域名。  
所有域名

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

[smartdns.log](https://github.com/pymumu/smartdns/files/4019149/smartdns.log)

**Comment by TillLindemann** [comment]
## 找到问题根源在哪了。
openclash的dns设置里面，我启用了本地DNS劫持，因为不开劫持的话，Youtube视频可以打开，但是无法播放，说明没有解析到视频的IP。
关闭DNS劫持之后，就可以ping通网站，所以目前来看，SmartDNS搭配OpenClash是有点坑。

**Comment by dengchan0416** [comment]
smartdns本来就不是用来翻出去用,不是用来搭配第三方使用,smartdns作者之前说过了,翻查看一下吧

**Comment by o2bit** [comment]
smartdns适合国内网络环境使用,加速国内网站和部分国外网站的访问速度,实测速度提升还是很明显的
