### ISSUE TITLE
[请愿]请求增加DOT\DOH DNS设置示例

### ISSUE THREAD

**Issue by phantastar** [pymumu/smartdns#299]
### **需求应用场景**
**_1._** 不同服务商提供的DOT\DOH服务器DNS地址格式不同(IP / Domain), 而Readme显示DOT设置格式为**IP:PORT**, 这是否表明Domain格式的DOT([GeekDNS](www.233py.com) / [Rubyfish DNS](www.rubyfish.cn/dns)不受支持? 

**_2._** 基于问题1, Domain格式的DOT应该填写在服务器设置的哪个空里? 

_**3.**_ 根据Readme, DOH地址需要附带https:// 前缀, **IP格式**的DOT地址需要tls:// 前缀吗? 以及 **Domain格式**的DOT需要吗? 

### **建议的方案**
如果您不嫌烦, 可以考虑专门弄个Sample打消这些问题. 

### **设备信息**

X86_64软路由

### **固件信息**

openwrt_原版_SNAPSHOT_r11885

> 新年快乐

**Comment by rampageX** [comment]
```
# tls default port is 853
server-tls 8.8.8.8:853 -group gfw
server-tls 8.8.4.4:853 -group gfw
#server-tls 1.1.1.1:853 -group gfw
#server-tls 1.0.0.1:853 -group gfw
#RedFish
#server-tls 118.89.110.78:853 -group gfw
#server-tls 47.96.179.163:853 -group gfw
#GeekDNS
#server-tls 119.29.107.85:853 -group gfw
#server-tls 47.101.136.37:853 -group gfw

# https
# default port is 443
server-https https://dns.google/dns-query -group gfw
#server-https https://cloudflare-dns.com/dns-query -group gfw
#server-https https://dns.rubyfish.cn/dns-query -group gfw
#server-https https://sdns.233py.com/dns-query -group gfw
```
范例配置文件中都有，上面是我试过的。

开 debug 信息，自己试试是最好的理解方法。

**Comment by phantastar** [comment]
> ```
> # tls default port is 853
> server-tls 8.8.8.8:853 -group gfw
> server-tls 8.8.4.4:853 -group gfw
> #server-tls 1.1.1.1:853 -group gfw
> #server-tls 1.0.0.1:853 -group gfw
> #RedFish
> #server-tls 118.89.110.78:853 -group gfw
> #server-tls 47.96.179.163:853 -group gfw
> #GeekDNS
> #server-tls 119.29.107.85:853 -group gfw
> #server-tls 47.101.136.37:853 -group gfw
> 
> # https
> # default port is 443
> server-https https://dns.google/dns-query -group gfw
> #server-https https://cloudflare-dns.com/dns-query -group gfw
> #server-https https://dns.rubyfish.cn/dns-query -group gfw
> #server-https https://sdns.233py.com/dns-query -group gfw
> ```
> 
> 范例配置文件中都有，上面是我试过的。
> 
> 开 debug 信息，自己试试是最好的理解方法。

麻烦问您一下, geekdns和rubyfish您是如何得出ip地址的? 就用ip138查的结果就是吗?

**Comment by rampageX** [comment]
@phantastar 他们的官方网站都有。

**Comment by phantastar** [comment]
> @phantastar 他们的官方网站都有。

啊我看到了！谢谢您了。🍻🍻🍻

**Comment by phantastar** [comment]
给以后的用家留下一点有用的信息：

### Rubyfish
[Rubyfish命令行工具](https://www.rubyfish.cn/dns/cmd/)的页面下：
```
$ getdns_query @118.89.110.78~dns.rubyfish.cn -m -s -L -A www.google.com
$ getdns_query @47.96.179.163~dns.rubyfish.cn -m -s -L -A www.google.com
```
显示了Rubyfish的DOT IP地址。
### GeekDNS
[GeekDNS在GitHub放出的服务器配置文件](https://github.com/xyzmos/GeekDNS/blob/master/Config/Unbound/国内/gfwlist.conf)中：
```
forward-zone:
  name: "030buy.com."
  forward-tls-upstream: yes
  forward-addr: 119.28.68.142@853
  forward-addr: 107.155.79.120@853
```
显示了GeekDNS的DOT IP地址。

**Comment by yeezylife** [comment]
> ```
> # tls default port is 853
> server-tls 8.8.8.8:853 -group gfw
> server-tls 8.8.4.4:853 -group gfw
> #server-tls 1.1.1.1:853 -group gfw
> #server-tls 1.0.0.1:853 -group gfw
> #RedFish
> #server-tls 118.89.110.78:853 -group gfw
> #server-tls 47.96.179.163:853 -group gfw
> #GeekDNS
> #server-tls 119.29.107.85:853 -group gfw
> #server-tls 47.101.136.37:853 -group gfw
> 
> # https
> # default port is 443
> server-https https://dns.google/dns-query -group gfw
> #server-https https://cloudflare-dns.com/dns-query -group gfw
> #server-https https://dns.rubyfish.cn/dns-query -group gfw
> #server-https https://sdns.233py.com/dns-query -group gfw
> ```
> 
> 范例配置文件中都有，上面是我试过的。
> 
> 开 debug 信息，自己试试是最好的理解方法。

大神你好我是笨笨。我用1天的时间在win10上装好了wls ubuntu，又用了1天的时间才装上smartDNS，搜到你的文件配置之后，终于可以上网了，请问smartdns.conf文件里，除了dot，doh还有什么可以优化的设置吗？ 可以的话能把您的smartdns.conf配置全部贴上来吗。。嘤嘤

**Comment by yeezylife** [comment]
@rampageX
