### ISSUE TITLE
希望增加tcp ping，比icmp ping更准确

### ISSUE THREAD

**Issue by 523860169** [pymumu/smartdns#30]
目前gfw封ip不再是以前那样，不管tcp、udp、icmp全部连不上，而是大部分ip只屏蔽tcp，这样就导致ping的通，连不上
1、像google等被墙的，不管怎么ping全超时，如果改成tcp ping，这样就可以直接借用ss等代理，获取到最准确的、走代理服务器后的ping值
2、像其他只封了tcp的，使用tcp ping可以避免出现ping通了，但是网页还是打不开的尴尬局面

**Comment by pymumu** [comment]
现在是先ping，ping全部失效再tcp-ping的。
后面考虑增加开关，关闭ping
