### ISSUE TITLE
自编译x86_64无法正常启动

### ISSUE THREAD

**Issue by WROIATE** [pymumu/smartdns#301]
**问题现象**  
自行根据源码编译的x86_64架构的smartdns无法启动

**运行环境**
OpenWrt R9.12.31 / LuCI Master (git-19.338.43082-9e87e69)
**重现步骤**
  自编译smartdns安装成功后在luci界面无法开启，使用命令行也无法开启
![Snipaste_2020-01-05_02-44-13](https://user-images.githubusercontent.com/44677306/71770262-c1550b80-2f65-11ea-9d29-943aafe40516.png)
![Snipaste_2020-01-05_02-45-08](https://user-images.githubusercontent.com/44677306/71770265-c44ffc00-2f65-11ea-9e84-e8d4d62efb9e.png)

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
无log文件
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
无文件生成

尝试过使用/usr/sbin/smartdns -h 显示无法找到文件，可是目录里是有的，很是奇葩

**Comment by pymumu** [comment]
交叉编译工具和系统不配套

**Comment by WROIATE** [comment]
> 交叉编译工具和系统不配套

我按照脚本提示使用以下命令编译，请问需要怎么更改交叉编译工具？
./build-pkg.sh --platform openwrt --arch x86_64

**Comment by pymumu** [comment]
build-pkg 有一个—cross-tool参数

你要安装openwrt x86-64的工具链

**Comment by WROIATE** [comment]
> build-pkg 有一个—cross-tool参数
> 
> 你要安装openwrt x86-64的工具链

请问配合lean的源码需要怎么加参数调用tool chain呢，第一次接触有些不太了解，如果您不介意的话希望能指点一下

**Comment by pymumu** [comment]
直接用编译好的二进制吧，release下面

**Comment by WROIATE** [comment]
还是不行
![Snipaste_2020-01-08_04-28-41](https://user-images.githubusercontent.com/44677306/71926960-5dce1680-31cf-11ea-8388-93564b3838b9.png)

**Comment by pymumu** [comment]
你确认你的设备是x86的？

**Comment by pymumu** [comment]
uname -a看一下你的硬件类型吧

**Comment by WROIATE** [comment]
> uname -a看一下你的硬件类型吧

![Snipaste_2020-01-08_04-35-53](https://user-images.githubusercontent.com/44677306/71944112-b4eae000-31fd-11ea-95d7-49bed5c39085.png)

**Comment by WROIATE** [comment]
> uname -a看一下你的硬件类型吧

![Snipaste_2020-01-08_10-00-26](https://user-images.githubusercontent.com/44677306/71944136-ca600a00-31fd-11ea-89a8-ae0c187e636c.png)

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/releases/download/Release28/smartdns.1.2019.12.15-1028.x86_64-openwrt-all.ipk
