### ISSUE TITLE
server 2400:da00::6666:53 -group baidu -exclude-default-group

### ISSUE THREAD

**Issue by thb007** [pymumu/smartdns#302]
请问这样填写ipv4，ipv6的dns后面加上端口可以吗？

server 180.76.76.76:53 -group baidu -exclude-default-group
server 2400:da00::6666:53 -group baidu -exclude-default-group
nameserver /.baidu.com/baidu

**Comment by pymumu** [comment]
ip地址要用[]包起来，看看ipv6的表示方法吧

**Comment by thb007** [comment]
server [2400:da00::6666]:53 -group baidu -exclude-default-group这样写对吧？还有ipv的可以直接后面加端口是吗？

**Comment by pymumu** [comment]
对，但如果是默认端口，就可以不配置。
