### ISSUE TITLE
测速功能关闭之后不工作？

### ISSUE THREAD

**Issue by Bnosora** [pymumu/smartdns#303]
**问题现象**  
关闭测速功能后smartdns会直接转发dns查询，相当于不工作了。

**运行环境**
ubuntu1804lts和centos7均试过 

centos7运行在esxi6.7u3上
ubuntu1804lts运行在vmware workstation pro15上

smartdns版本：smartdns.1.2019.12.15-1028.x86_64-linux-all.tar.gz

smartdns所在机子的ip：192.168.1.2（系统如上）
进行延迟测试的电脑是：192.168.1.3（win10 1809）
主路由是：192.168.1.1(系统：lede）

测试电脑的配置：
网关：192.168.1.1
dns服务器：119.29.29.29
（会在测试延迟的时候单独指定解析服务器：dnsping -s 192.168.1.2 www.google.com）

**重现步骤**

配置1：
**bind 192.168.1.2:53 -no-speed-check**
cache-size 512
prefetch-domain yes
**speed-check-mode none**
rr-ttl 300
log-level info
server 192.168.1.1

配置2：
bind 192.168.1.2:53
cache-size 512
prefetch-domain yes
**speed-check-mode none**
rr-ttl 300
log-level info
server 192.168.1.1

配置3：
**bind 192.168.1.2:53 -no-speed-check**
cache-size 512
prefetch-domain yes
rr-ttl 300
log-level info
server 192.168.1.1

配置4：
bind 192.168.1.2:53
cache-size 512
prefetch-domain yes
rr-ttl 300
log-level info
server 192.168.1.1

（不同之处已加粗）

使用配置1或2或3都会导致解析延迟高达180ms/20ms（国外/国内。和直接向主路由查询的延迟完全一样），并且nslookup www.baidu.com 192.168.1.2 会返回2个ip。但是systemctl显示smartdns运行正常active（running）。

使用配置4的时候，解析延迟只有1ms，nslookup www.baidu.com 192.168.1.2 只返回1个ip。（应该是正常工作了）

也就是说关闭测速功能会导致smartdns停止提供解析，直接把请求转发到上游dns？亦或者是我哪里配置错了？希望大佬能帮忙看看，谢谢！

log（配置1、2、3的）：
[2020-01-06 01:55:37,655][NOTICE][       smartdns.c:260 ] smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build:Dec 15 2019 10:30:51)
[2020-01-06 01:55:37,656][ INFO][     dns_client.c:851 ] add server 192.168.1.1:53, type: udp
[2020-01-06 01:59:08,010][ INFO][     dns_server.c:2242] query server www.google.com from 192.168.1.3, qtype = 1
[2020-01-06 01:59:08,011][ INFO][     dns_client.c:2547] send request www.google.com, qtype 1, id 1
[2020-01-06 01:59:09,009][ INFO][     dns_server.c:2242] query server www.google.com from 192.168.1.3, qtype = 1

**Comment by Bnosora** [comment]
补充：
前面说的情况仅对ubuntu1804lts适用，centos7下的情况和ubuntu下还不大一样。

在centos7下：

如果改成配置4之后重启系统。系统启动之后smartdns能正常工作，在此状态下把配置改成1或2或3，smartdns一样可以正常工作。

如果改成配置1或2或3之后重启系统。系统启动之后smartdns就不能正常工作了，在此状态下把配置改成4，smartdns还是不能正常工作。

**Comment by kkkgo** [comment]
你的补充看起来是没重新加载配置，建议直接`killall smartdns`然后再启动
如果想观察日志输出，可以`killall smartdns`后运行smartdns -c config.conf -x -f

**Comment by Bnosora** [comment]
> 你的补充看起来是没重新加载配置，建议直接`killall smartdns`然后再启动
> 如果想观察日志输出，可以`killall smartdns`后运行smartdns -c config.conf -x -f

谢谢。试了一下，确实是centos的配置没成功加载。改成`killall smartdns`之后就和Ubuntu下的故障一样了。

**Comment by pymumu** [comment]
设置-no-speed-check后，缓存会失效，功能上就和dnsmasq一致了。

**Comment by Bnosora** [comment]
> 设置-no-speed-check后，缓存会失效，功能上就和dnsmasq一致了。

明白了，谢谢解答！
