### ISSUE TITLE
LEDE  luci中 基本设置没有 服务器组 选项, 

### ISSUE THREAD

**Issue by ilpl** [pymumu/smartdns#304]
**问题现象**  
简要描述问题出现的现象
LEDE  luci中 基本设置没有 服务器组 选项,  第二组有.
希望在第一组中也增加客源设置 [服务器组]
**运行环境**
1. 固件型号  

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
服务器组在每个DNS配置项里面都可以配置，要点“编辑”进去。
