### ISSUE TITLE
【需求建议】增加故障转移的servergroup选项

### ISSUE THREAD

**Issue by kkkgo** [pymumu/smartdns#305]
**需求应用场景**
场景一：
查询一些域名境内的DNS服务器查询比较快，但是更新比较慢，一些新的记录没那么快查询得到，查询境外的DNS服务器已经有了结果，但是如果把境内和境外的DNS服务器都加入ServerGroup的话，会造成很多无意义的DNS查询和测速，降低性能和增加带宽连接数占用（特别是TCP测速），因此希望能对这个域名指定一个故障转移的group选项，当default server或者指定的server group查不到结果或者ServerFailed的时候，去这组故障转移的group。

场景二：
对某个域名指定了某个nameserver，域名就托管在这个nameserver上，直接查它比较实时；
但这个nameserver拒绝查询非托管域名，当查询这个域名的记录是cname了其他域名的时候，就会返回ServerFailed，因此希望能增加一个故障转移的group选项，去查询cname。
**建议的方案**
实现上述场景建议的方案。
server增加-backup选项，当所有server都Failed的时候采用backupgroup的结果
示例：
```
server 114.114.114.114 -group baidu
server 1.0.0.1 -group baidu -backup
nameserver /baidu.com/baidu
````

**Comment by kkkgo** [comment]
或者给Server Group定义优先级，灵活性更好些：
```
-level ，数字越小越优先
server 114.114.114.114 -group baidu -level 1
server 119.29.29.29 -group baidu -level 1
server 1.1.1.1 -group baidu  -level 2
server 1.0.0.1 -group baidu  -level 2
nameserver /baidu.com/baidu
```

**Comment by pymumu** [comment]
DNS故障只是少数场景，此功能应用场景有限。
并且会大大增加代码复杂度，目前不会考虑此建议。
