### ISSUE TITLE
运行不起来！

### ISSUE THREAD

**Issue by oe77** [pymumu/smartdns#306]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  x86

coredump文件没生成出来，只有这两条错误提示！

Tue Jan  7 12:59:36 2020 daemon.err uhttpd[2251]: uci: Entry not found
Tue Jan  7 12:59:36 2020 daemon.err uhttpd[2251]: uci: Entry not found
Tue Jan  7 12:59:36 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jan  7 12:59:36 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jan  7 13:00:02 2020 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 1 seconds since last crash

[2020-01-07 12:48:19,312][ERROR][     dns_server.c:2931] create socket failed, family = 10, type = 2, proto = 17, Address family not supported by protocol
[2020-01-07 12:48:19,312][ERROR][     dns_server.c:3138] create server socket failed.
[2020-01-07 12:48:19,312][ERROR][       smartdns.c:282 ] start dns server failed.

**Comment by kkkgo** [comment]
监听端口的配置写错了吧 估计你的固件不支持ipv6 配置写了ipv6

**Comment by oe77** [comment]
> 监听端口的配置写错了吧估计你的固件不支持ipv6配置写了ipv6

ipv6编译时去掉了！关闭SmartDNS 里面的ipv6就行了
谢谢

**Comment by oe77** [comment]
> **问题现象**
> 简要描述问题出现的现象
> 
> **运行环境**
> 
> 1. 固件型号x86
> 
> coredump文件没生成出来，只有两个条错误提示！
> 
> 周二01月07日12时59分36秒2020 daemon.err uhttpd [2251]：UCI：未找到条目
> 星期二1月7日12时59分36秒2020 daemon.err uhttpd [2251]：UCI：未找到条目
> 周二01月07日12:59 ：36 2020 user.notice dnsmasq：DNS重新绑定保护处于活动状态，将丢弃上游RFC1918响应！
> 2020年1月7日星期二12:59:36 2020 user.notice dnsmasq：允许127.0.0.0/8响应
> 2020年1月7日星期二13:00:02 2020 daemon.info Procd：崩溃循环中的实例smartdns :: smartdns 6崩溃，1秒自上次崩溃以来
> 
> [2020-01-07 12：48：19,312] [错误] [dns_server.c：2931]创建套接字失败，家族= 10，类型= 2，原型= 17，协议不支持的地址家族
> [2020-01-07 12：48：19,312] [错误] [dns_server.c：3138]创建服务器套接字失败。
> [2020-01-07 12：48：19,312] [错误] [smartdns.c：282]启动DNS服务器失败。
