### ISSUE TITLE
force-AAAA-SOA

### ISSUE THREAD

**Issue by cyouhi** [pymumu/smartdns#307]
**需求应用场景**
某些域名只有AAAA记录，例如computeadmin.bxcearth.com
在遇到此类域名时候就会无解析记录，尝试过将解析记录写入本机hosts，无效。

**建议的方案**
建议下个版本更新时候能判断一下本机hosts或者address参数是否有特殊设置

**设备信息**
1. 设备信息（CPU，厂家）  
虚拟机debian
2. 固件信息
最新版

**Comment by pymumu** [comment]
建议使用dualstack-ip-selection

**Comment by cyouhi** [comment]
好的，感谢。
还有一个问题，同时设置一个udp的dns和一个https的dns，https的使用-group参数，nameserver指定了使用group来解析为什么还会被抢答掉？测试域名
www.t66y.com

Nick Peng <notifications@github.com>于2020年1月8日 周三21:24写道：

**Comment by pymumu** [comment]
看你选的我https上游是否能正确解析

**Comment by cyouhi** [comment]
可以正确解析的
而且我还是直接把httpsdns的ip用address参数写入的

例1
server-https https://xxx.com/query-dns
address /xxx.com/1.1.1.1

这样只留一个httpsdns配置的情况下是可以正常解析

例2
server 114.114.114.114
server-https https://xxx.com/query-dns -group free
address /xxx.com/1.1.1.1
nameserver /www.t66y.com/free

这样配置的情况下就会被udp的抢答掉导致解析错误

**Comment by pymumu** [comment]
nameserver /t66y.com/free

**Comment by cyouhi** [comment]
好的，感谢！
到时候改下配置试试看.
感谢.
