### ISSUE TITLE
使用nslookup解释不出网址的IP会出现timed out

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#308]
用nslookup命令有时候解释不出网址IP,DNS request timed out. 
timeout was 2 seconds.
![image](https://user-images.githubusercontent.com/41529838/72051808-e697a000-32fe-11ea-8140-374e05baf9e7.png)

![image](https://user-images.githubusercontent.com/41529838/72051941-2199d380-32ff-11ea-96ba-3c8f8a2f84c8.png)

![image](https://user-images.githubusercontent.com/41529838/72051995-3f673880-32ff-11ea-92b4-a53b8ffd2f66.png)

**Comment by pymumu** [comment]
smartdns未生效，另外，blacklist-ip的配置，不清楚你的用意是什么

**Comment by dengchan0416** [comment]
@pymumu 我看过一直在运行中,而且第二次nslookup就能正常了

**Comment by pymumu** [comment]
你先确认smartdns是否正常工作吧，比如查询百度看是否只返回一个IP地址

**Comment by dengchan0416** [comment]
@pymumu 显示是正在运行
![image](https://user-images.githubusercontent.com/41529838/72305653-659a2900-36af-11ea-926a-38bda2eca19d.png)

![image](https://user-images.githubusercontent.com/41529838/72305784-d5101880-36af-11ea-8e70-c2036bf43175.png)

**Comment by pymumu** [comment]
这只是进程在运行，可能有其他服务接管了dns请求，排除一下吧
