### ISSUE TITLE
建议 speed-check-mode 可以针对不同 group 分别设置

### ISSUE THREAD

**Issue by soffchen** [pymumu/smartdns#309]
比如希望对国内组的域名做 icmp 测速，对国外组的域名做 tcp 测速，这样相对科学一些。

**Comment by onion83** [comment]
支持，现在 no-speed-check 功能加载在 bind 功能上，通过不同端口区分不同功能，这个“第二DNS“用起来怪怪的，这样 smartdns 就不能作为标准 DNS 统一入口了，前面还得挡一层，实用性很低。

如果在 group 这个层面，例如 
```
...
nameserver /.google.com/free
...
server-tls 8.8.4.4 -group free -exclude-default-group no-speed-check
server-tls 1.0.0.1 -group free -exclude-default-group
....
```
我觉得程序实现起来也有二义性, 对于 8.8.4.4 返回的结果不测，对于 1.0.0.1 反而测？那结论是？

要不将这 nameserver 的功能扩展一下，例如
```
nameserver /.google.com/free,no-speed-check
nameserver /.office/office,no-speed-check,no-dualstack-selection
```
加多一些 option 进去满足更灵活需要？

**Comment by pymumu** [comment]
后面会增加针对特定域名不测速

**Comment by moxuanyuan** [comment]
> 后面会增加针对特定域名不测速

我也建议针对group来设置测速模式
