### ISSUE TITLE
./smartdns: can't load library 'libgcc_s.so.1'

### ISSUE THREAD

**Issue by ohmyjcc** [pymumu/smartdns#31]
[HC5861 /tmp]# ldd smartdns 
	libdl.so.0 => /lib/libdl.so.0 (0x77503000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x774dd000)
	libgcc_s.so.1 => not found
	libc.so.0 => /lib/libc.so.0 (0x77461000)
	ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x77517000)

木有这个libgcc_s 也

**Comment by ohmyjcc** [comment]
能不能编个静态的版本叻？
uClibc-0.9.33.2
system type		: MediaTek MT7620 SoC
processor		: 0
cpu model		: MIPS 24KEc V5.0
BogoMIPS		: 385.02
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
ASEs implemented	: mips16 dsp
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

**Comment by pymumu** [comment]
你用的是什么固件？openwrt的话，都应该是uclibc的。取用正确版本应该就没有问题了

静态编译涉及到开源版权问题，暂时不会静态编译。
