### ISSUE TITLE
address与httpsdns搭配的问题

### ISSUE THREAD

**Issue by cyouhi** [pymumu/smartdns#310]
**问题现象**  
httpsdns用address写死IP后会被udp的dns抢答掉，注释掉address参数后正常

**运行环境**
1. 固件型号  
debian虚拟机
2. 运营商  
长宽
**重现步骤**
1. 上游DNS配置。  
bind [::]:53
cache-size 10000
prefetch-domain yes
speed-check-mode ping,tcp:80,tcp:443
force-AAAA-SOA yes
rr-ttl 600
rr-ttl-min 600
server 114.114.114.114
server-https https://www.xxx.ml/dq -group free
#address /www.xxx.ml/1.1.1.1

nameserver /t66y.com/free
nameserver /github.com/free

2. 访问的域名。  

www.t66y.com

**Comment by soffchen** [comment]
访问的域名亮了

**Comment by pymumu** [comment]
Address不是这么用的，server-https可以使用ip地址，host-name参数配置域名，具体看配置帮助

**Comment by cyouhi** [comment]
> Address不是这么用的，server-https可以使用ip地址，host-name参数配置域名，具体看配置帮助

server-https https://www.xxx.ml/dq -group free -host-name 1.1.1.1
server-https https://www.xxx.ml/dq -group free -host-name，然后在hosts上面写？
这两种写法哪种是对的？

**Comment by pymumu** [comment]
server-https https://1.1.1.1/xxx -host-name xx.com

**Comment by cyouhi** [comment]
好用了，非常感谢开发出如此优秀的软件
