### ISSUE TITLE
联通、电信双线路DNS设置

### ISSUE THREAD

**Issue by cnclg** [pymumu/smartdns#314]
联通、电信双线同时使用，如何避免出现联通线路访问电信ip,或电信访问联通的ip，谢谢！

**Comment by thb007** [comment]
我也想知道

**Comment by rainmanzheng** [comment]
我也想问，现在我的环境是电信联通移动三家的🤣

**Comment by onion83** [comment]
1、本质上这是一个路由器问题，你们需要一个可以根据 IP 地址分流的路由器，并且不能使用负载均衡功能。
2、同时写多个运营商的IP，使用 smartdns 默认测速功能 ，并且 smartdns 也在你们的路由器后面

**Comment by pymumu** [comment]
server增加了-inerface参数，支持绑定端口。
