### ISSUE TITLE
upgrade think for DNS,maybe not very well

### ISSUE THREAD

**Issue by jkle112** [pymumu/smartdns#316]
Openwrt x64 ,smartdns x64  Release 28
其他路由器安装了其他版本，使用正常
1.DNS library in Go
https://github.com/miekg/dns
DNS库更新，保持最新，减少被远程捕捉和嗅探的可能
2.CoreDNS is a DNS server that chains plugins
https://coredns.io
https://github.com/coredns/coredns
增加插件
3.P2P DNS with content key, crypto key and PKI support. DynDNS alternative.
https://github.com/mwarning/KadNode
13.Twisted
https://github.com/xiaomi-sa/smartdns
10.DNS-over-QUIC to UDP Proxy
https://github.com/ns1/doq-proxy
4.A Rust based DNS client, server, and resolver
https://github.com/bluejekyll/trust-dns
用不同的方式和协议来提高拓展性能，防止被干扰或封锁，其中twisted无中心化，有对应的安装文件，看如何衔接配置
5.dns tunnel backdoor
https://github.com/ice-ice/dnstunnel
7.Reverse proxy and service tunnel written in Go
https://github.com/inlets/inlets
8.Solve your DNS hosts from your docker containers, then from your local configuration, then from internet
https://github.com/mageddo/dns-proxy-server
不同的代理方式，提高在复杂网络中的性能和安全应对，anti-hijacking
11.DNS from different country used different server
https://github.com/ARwMq9b6/dnsproxy
中国等有过滤的国家，访问当地网址优先用当地服务器，访问国外网址用国外服务器
12.Bypassing Geo-restrictions on Disney+ & Netflix streaming 
https://github.com/samuelngs/smartdns
其他同类的的参考，取长补短

**Comment by pymumu** [comment]
想表达什么？

**Comment by gentlyxu** [comment]
如果你还在寻找广告过滤列表，我建议你试试我维护的项目 https://github.com/privacy-protection-tools/anti-AD ，不用东奔西走，只要一个anti-AD就足够了
