### ISSUE TITLE
速度最好的ip，不能访问

### ISSUE THREAD

**Issue by listenfree** [pymumu/smartdns#317]
**问题现象**  
#通过smartdns后www.fxshell.com返回的ip为109.94.169.67,但不能访问页面。
_$ nslookup www.fxshell.com
Server:		11.41.32.200
Address:	11.41.32.200#53

Non-authoritative answer:
www.fxshell.com	canonical name = 77350780c1d184cb.cdn.jiashule.com.
Name:	77350780c1d184cb.cdn.jiashule.com
Address: 109.94.169.67_

#通过8.8.8.8返的1.255.41.180,能够访问页面。
_$ nslookup www.fxshell.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
www.fxshell.com	canonical name = 77350780c1d184cb.cdn.jiashule.com.
Name:	77350780c1d184cb.cdn.jiashule.com
Address: 1.255.41.180
Name:	77350780c1d184cb.cdn.jiashule.com
Address: 109.94.169.67_

**Comment by listenfree** [comment]
cdn的 80,443都是opened

**Comment by pymumu** [comment]
默认的测速模式应该是最佳的，一般不建议修改。

后面增加针对域名可配置测速模式。
