### ISSUE TITLE
强化一下分组的实用功能？

### ISSUE THREAD

**Issue by zxysm** [pymumu/smartdns#319]
**需求应用场景**
    多ISP接入，并且有单独一条线路过墙，后端是爱快根据ISP分流，以及自定义某些网站过墙，内网已有自建DNS服务器，DNS服务器通过GFWLIST分流解析IP，如果是国内网站使用国内DNS加速访问，如果是GFWLIST里的网站会通过过墙线路加密后直接去国外解析，而不会通过国内DNS，这样国内ISP并不知道我访问国外的DNS请求。
    但是加入smartdns后现在就会出现一个问题，设置了各个ISP的DNS、国内公共DNS、国外DNS后，如果我不希望国内ISP知道我访问国外网站的情况，那么我就只能在原来的内网DNS设置smartdns只解析国外的网站，那么国内的网站就不能获得smartdns的效果；如果我在原来的内网DNS设置smartdns加速国内网站，国外网站同样也不能获得smartdns的效果。

**建议的方案**
    现在smartdns已经支持了第二DNS服务器，并且DNS是能够分组的，那么能不能第一DNS使用ISP的DNS以及国内DNS负责解析国内网站，而第二DNS服务器负责解析国外的网站，这样就不会出现国内ISP能够知道我访问的国外网站记录了。
    也就是说把分组功能再强化一下，比如第一DNS用A、B组，第二DNS用C、D组分别来解析？

**设备信息**
1. 设备信息（CPU，厂家）  
    X64软路由，其实这个功能各个平台都应该适用的吧？
2. 固件信息
    虚拟机+OPENWRT

**Comment by pymumu** [comment]
配合nameserver使用。

**Comment by zxysm** [comment]
额，那样会需要额外设置很多nameserver的。而如果支持分组，我可以不做变动的分别使用。

**Comment by onion83** [comment]
smartdns 可以完美实现你的需求，关键配置

>  ....
>  // 默认 DNS 组
> server 119.29.29.29
> server 223.6.6.6
>  ....
>  // tls 加密的 DNS 组 命名为 free  ，不参与 默认组DNS 解析
> server-tls 8.8.8.8 -group free -exclude-default-group
> server-tls 1.1.1.1 -group free -exclude-default-group
>  ....
>  // 配合 nameserver 解析被污染的域名 使用 free DNS 组... 
> nameserver /.google.com/free
> .....

期待 domain-rules 尽快 release , master 版本已经测试通过：）
