### ISSUE TITLE
系统日志一直提示ignoring nameserver 127.0.0.1是啥情况鸭

### ISSUE THREAD

**Issue by guaguagaga** [pymumu/smartdns#32]
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface
Sat Sep 29 00:02:24 2018 daemon.warn dnsmasq[29220]: ignoring nameserver 127.0.0.1 - local interface

**Comment by pymumu** [comment]
把/etc/resolv.conf中的127.0.0.1去掉。
