### ISSUE TITLE
Fedora 31 (Server Edition)

### ISSUE THREAD

**Issue by Potterli20** [pymumu/smartdns#322]
**问题现象**  
无法安装，没有那个文件或目录

**运行环境**
1. 固件型号  
x64 Fedora 31 (Server Edition)
 
**信息收集**  
[root@dns smartdns]# ./install -i
install: 正在创建目录 '/etc/smartdns'
'src/smartdns' -> '/usr/sbin/smartdns'
'etc/smartdns/smartdns.conf' -> '/etc/smartdns/smartdns.conf'
'etc/default/smartdns' -> '/etc/default/smartdns'
已删除 '/etc/init.d/smartdns'
'etc/init.d/smartdns' -> '/etc/init.d/smartdns'
'systemd/smartdns.service' -> '/usr/lib/systemd/system/smartdns.service'
Synchronizing state of smartdns.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable smartdns
Failed to execute /usr/lib/systemd/systemd-sysv-install: 没有那个文件或目录
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
你的系统不完整。
```shell
sudo dnf install chkconfig -y
```
