### ISSUE TITLE
能否指定某一个group只返回ipv4的地址？force-AAAA-SOA yes问题

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#324]
**需求应用场景**

本地有ipv6环境，服务端ss没有

指定分组后查询得到可靠的结果包含v4和v6的地址，这时候ss不能用v6，只能v4？

可能是这个原因导致网站打不开吧？因为我修改windows的host，强制到v4的ip地址就可以访问了

具体现象如下

比如网站[https://cn.nytimes.com](https://cn.nytimes.com)，路由器开启ss，在有ipv6环境下就打不开，路由器里把ipv6关了只用ipv4就能打开了

但是ipv6对本地又是必不可少的服务，不能关闭

开那个speed-check-mode也不能筛掉返回的IP地址，因为在本地ping和tcp这个ipv4和ipv6的地址时候又都是通的，但还是不能访问网址[https://cn.nytimes.com](https://cn.nytimes.com)

**建议的方案**
分组A启用force-AAAA-SOA yes，那啥用
分组B启用dualstack-ip-selection yes，普遍用

**设备信息**
1. 设备信息（CPU，厂家）  
新3
2. 固件信息
hiboy老毛子

**Comment by qwerttvv** [comment]
不知道ss的windows客户端是怎么弄的，ipv6的环境下，就可以访问这个网址

安卓客户端也行，路由上的客户端就不行了？

**Comment by qwerttvv** [comment]
不好意思，我瞎了……

测试了force-AAAA-SOA yes

现在这个全部都只返回v4但是，，，，谷歌什么所有那些全部打不开了，提示https不是私密连接。。。？
关闭force-AAAA-SOA yes以后起码google一类的能用了，迷惑

![image](https://user-images.githubusercontent.com/56712217/72962847-77d34000-3df0-11ea-899e-c95a2a785b97.png)
![image](https://user-images.githubusercontent.com/56712217/72962866-815ca800-3df0-11ea-82c6-0fd35086f648.png)

**Comment by PikuZheng** [comment]
> 不好意思，我瞎了……
> 
> 测试了force-AAAA-SOA yes
> 
> 现在这个全部返回v4但是，，，，返回的结果全错了。。都返回facebook被墙的ip了，可是我用的是8.8.8.8解析这些网址啊。。。。
> 
> 我设置一个cache-size 0再试试

是因为你用的udp 53，本地运营商有污染。
address /live.com/#6
可以针对单个域名只返回ipv4

**Comment by qwerttvv** [comment]
> > 不好意思，我瞎了……
> > 测试了force-AAAA-SOA yes
> > 现在这个全部返回v4但是，，，，返回的结果全错了。。都返回facebook被墙的ip了，可是我用的是8.8.8.8解析这些网址啊。。。。
> > 我设置一个cache-size 0再试试
> 
> 是因为你用的udp 53，本地运营商有污染。
> address /live.com/#6
> 可以针对单个域名只返回ipv4
谢谢，我再试试看看
server-https https://dns.google/dns-query -group office
server-tls dns.google -group office

**Comment by tty228** [comment]
开启 双栈IP优选 ，然后把 国外的 dns 服务器 ip 放到代理中，理论上就不会返回 ipv6 地址了吧
因为 V6 返回得没有 V4 快
不过这个太不靠谱了，跟楼主同需求

**Comment by qwerttvv** [comment]
> 开启 双栈IP优选 ，然后把 国外的 dns 服务器 ip 放到代理中，理论上就不会返回 ipv6 地址了吧
> 因为 V6 返回得没有 V4 快
> 不过这个太不靠谱了，跟楼主同需求

我肯定国外dns是走代理的，因为是谷歌的

**Comment by tty228** [comment]
你之前有打开  双栈IP优选  吗

**Comment by qwerttvv** [comment]
打开了

bind 0.0.0.0:8051 -group china
bind 0.0.0.0:8052 -group office
# 北京联通
server 202.106.195.68 -group china
server 202.106.46.151 -group china
server 2408:8000:1010:1::8 -group china
server 2408:8000:1010:2::8 -group china
# 阿里
server 223.5.5.5 -group china
server 2400:3200::1 -group china
# 百度
server 180.76.76.76 -group china
server 2400:da00::6666 -group china
# 腾讯
server 119.29.29.29 -group china
#google
server-https https://dns.google/dns-query -group office
server-tls dns.google -group office
cache-size 1024
prefetch-domain yes
speed-check-mode tcp:443,tcp:80
dualstack-ip-selection yes

套chinadns ng
8052是ss

**Comment by tty228** [comment]
> 打开了
> 
> bind 0.0.0.0:8051 -group china
> bind 0.0.0.0:8052 -group office
> #北京联通
> server 202.106.195.68 -group china
> server 202.106.46.151 -group china
> server 2408:8000:1010:1::8 -group china
> server 2408:8000:1010:2::8 -group china
> #阿里
> server 223.5.5.5 -group china
> server 2400:3200::1 -group china
> #百度
> server 180.76.76.76 -group china
> server 2400:da00::6666 -group china
> #腾讯
> server 119.29.29.29 -group china
> #google
> server-https https://dns.google/dns-query -group office
> server-tls dns.google -group office
> cache-size 1024
> prefetch-domain yes
> speed-check-mode tcp:443,tcp:80
> dualstack-ip-selection yes
> 
> 套chinadns ng
> 8052是ss

所以我这个方法果然不是很靠谱，但是我这边确实可用啊……

![1](https://user-images.githubusercontent.com/33397881/74460628-20446380-4ec8-11ea-94d1-789d20060377.png)

**Comment by qwerttvv** [comment]
> > 打开了
> > bind 0.0.0.0:8051 -group china
> > bind 0.0.0.0:8052 -group office
> > #北京联通
> > server 202.106.195.68 -group china
> > server 202.106.46.151 -group china
> > server 2408:8000:1010:1::8 -group china
> > server 2408:8000:1010:2::8 -group china
> > #阿里
> > server 223.5.5.5 -group china
> > server 2400:3200::1 -group china
> > #百度
> > server 180.76.76.76 -group china
> > server 2400:da00::6666 -group china
> > #腾讯
> > server 119.29.29.29 -group china
> > #google
> > server-https https://dns.google/dns-query -group office
> > server-tls dns.google -group office
> > cache-size 1024
> > prefetch-domain yes
> > speed-check-mode tcp:443,tcp:80
> > dualstack-ip-selection yes
> > 套chinadns ng
> > 8052是ss
> 
> 所以我这个方法果然不是很靠谱，但是我这边确实可用啊……
> 
> ![1](https://user-images.githubusercontent.com/33397881/74460628-20446380-4ec8-11ea-94d1-789d20060377.png)

其实最好还是大佬辛苦辛苦造福大众，实现分组可以指定返回：）

**Comment by qwerttvv** [comment]
我现在pc端好说，浏览器插件就行了
主要是手机端，，，我用的那个插件吧，没有苹果版本，安卓机器还可以，苹果这个就难受了

不过也不是不能用，就是，，，别扭点儿

**Comment by pymumu** [comment]
最新代码bind配置支持force-aaaa-soa配置。
