### ISSUE TITLE
smartdns给的IP速度还没有不用快

### ISSUE THREAD

**Issue by catcherxuefeng** [pymumu/smartdns#327]
**问题现象**  
简要描述问题出现的现象
使用smartdns解析的地址延迟比直接解析还要高
直接解析：
`root@os8 ~# dig www.baidu.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> www.baidu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59077
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.baidu.com.                 IN      A

;; ANSWER SECTION:
www.baidu.com.          1007    IN      CNAME   www.a.shifen.com.
www.a.shifen.com.       133     IN      A       180.101.49.11
www.a.shifen.com.       133     IN      A       180.101.49.12

;; Query time: 52 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: 日 1月 26 18:55:53 CST 2020
;; MSG SIZE  rcvd: 101

`
ping
`root@os8 ~# nping 180.101.49.11

Starting Nping 0.7.70 ( https://nmap.org/nping ) at 2020-01-26 18:56 CST
SENT (0.0191s) ICMP [192.168.2.28 > 180.101.49.11 Echo request (type=8/code=0) id=44185 seq=1] IP [ttl=64 id=36341 iplen=28 ]
RCVD (0.2230s) ICMP [180.101.49.11 > 192.168.2.28 Echo reply (type=0/code=0) id=44185 seq=1] IP [ttl=51 id=36341 iplen=28 ]
SENT (1.0195s) ICMP [192.168.2.28 > 180.101.49.11 Echo request (type=8/code=0) id=44185 seq=3] IP [ttl=64 id=36341 iplen=28 ]
RCVD (1.2628s) ICMP [180.101.49.11 > 192.168.2.28 Echo reply (type=0/code=0) id=44185 seq=3] IP [ttl=51 id=36341 iplen=28 ]
SENT (2.0197s) ICMP [192.168.2.28 > 180.101.49.11 Echo request (type=8/code=0) id=44185 seq=3] IP [ttl=64 id=36341 iplen=28 ]
RCVD (2.0947s) ICMP [180.101.49.11 > 192.168.2.28 Echo reply (type=0/code=0) id=44185 seq=3] IP [ttl=51 id=36341 iplen=28 ]
SENT (3.0218s) ICMP [192.168.2.28 > 180.101.49.11 Echo request (type=8/code=0) id=44185 seq=4] IP [ttl=64 id=36341 iplen=28 ]
RCVD (3.1349s) ICMP [180.101.49.11 > 192.168.2.28 Echo reply (type=0/code=0) id=44185 seq=4] IP [ttl=51 id=36341 iplen=28 ]
SENT (4.0246s) ICMP [192.168.2.28 > 180.101.49.11 Echo request (type=8/code=0) id=44185 seq=5] IP [ttl=64 id=36341 iplen=28 ]
RCVD (4.1748s) ICMP [180.101.49.11 > 192.168.2.28 Echo reply (type=0/code=0) id=44185 seq=5] IP [ttl=51 id=36341 iplen=28 ]

Max rtt: 243.272ms | Min rtt: 74.819ms | Avg rtt: 156.949ms
Raw packets sent: 5 (140B) | Rcvd: 5 (230B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 4.17 seconds
`
smartdns:
`root@os8 ~# dig @192.168.2.27  www.baidu.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el8 <<>> @192.168.2.27 www.baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30294
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.baidu.com.                 IN      A

;; ANSWER SECTION:
www.baidu.com.          148     IN      CNAME   www.wshifen.com.
www.wshifen.com.        148     IN      A       104.193.88.123

;; Query time: 865 msec
;; SERVER: 192.168.2.27#53(192.168.2.27)
;; WHEN: 日 1月 26 18:56:06 CST 2020
;; MSG SIZE  rcvd: 104
`
ping:
`root@os8 ~# nping 104.193.88.123

Starting Nping 0.7.70 ( https://nmap.org/nping ) at 2020-01-26 18:57 CST
SENT (0.0200s) ICMP [192.168.2.28 > 104.193.88.123 Echo request (type=8/code=0) id=6551 seq=1] IP [ttl=64 id=43253 iplen=28 ]
RCVD (0.2202s) ICMP [104.193.88.123 > 192.168.2.28 Echo reply (type=0/code=0) id=6551 seq=1] IP [ttl=51 id=43253 iplen=28 ]
SENT (1.0204s) ICMP [192.168.2.28 > 104.193.88.123 Echo request (type=8/code=0) id=6551 seq=2] IP [ttl=64 id=43253 iplen=28 ]
RCVD (1.2601s) ICMP [104.193.88.123 > 192.168.2.28 Echo reply (type=0/code=0) id=6551 seq=2] IP [ttl=51 id=43253 iplen=28 ]
SENT (2.0207s) ICMP [192.168.2.28 > 104.193.88.123 Echo request (type=8/code=0) id=6551 seq=3] IP [ttl=64 id=43253 iplen=28 ]
RCVD (2.3001s) ICMP [104.193.88.123 > 192.168.2.28 Echo reply (type=0/code=0) id=6551 seq=3] IP [ttl=51 id=43253 iplen=28 ]
SENT (3.0209s) ICMP [192.168.2.28 > 104.193.88.123 Echo request (type=8/code=0) id=6551 seq=4] IP [ttl=64 id=43253 iplen=28 ]
RCVD (3.3407s) ICMP [104.193.88.123 > 192.168.2.28 Echo reply (type=0/code=0) id=6551 seq=4] IP [ttl=51 id=43253 iplen=28 ]
SENT (4.0221s) ICMP [192.168.2.28 > 104.193.88.123 Echo request (type=8/code=0) id=6551 seq=5] IP [ttl=64 id=43253 iplen=28 ]
RCVD (4.3806s) ICMP [104.193.88.123 > 192.168.2.28 Echo reply (type=0/code=0) id=6551 seq=5] IP [ttl=51 id=43253 iplen=28 ]

Max rtt: 358.392ms | Min rtt: 199.991ms | Avg rtt: 279.400ms
Raw packets sent: 5 (140B) | Rcvd: 5 (230B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 4.38 seconds
`

日志文件：
`[2020-01-26 18:07:09,005][NOTICE][       smartdns.c:260 ] smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build:Dec 15 2019 10:30:51)
[2020-01-26 18:07:09,007][ INFO][     dns_client.c:851 ] add server 8.8.8.8:853, type: tls
[2020-01-26 18:07:09,007][ INFO][     dns_client.c:851 ] add server 1.1.1.1:853, type: tls
[2020-01-26 18:07:09,007][ INFO][     dns_client.c:851 ] add server 9.9.9.9:853, type: tls
[2020-01-26 18:07:09,007][ INFO][     dns_client.c:1012] add pending server cloudflare-dns.com
[2020-01-26 18:07:11,909][ INFO][     dns_client.c:2547] send request cloudflare-dns.com, qtype 1, id 1
[2020-01-26 18:07:11,909][ INFO][     dns_client.c:2547] send request cloudflare-dns.com, qtype 28, id 2
[2020-01-26 18:07:13,008][ INFO][     dns_server.c:712 ] result: cloudflare-dns.com, rcode: 0,  2606:4700:0000:0000:0000:0000:6810:f9f9
[2020-01-26 18:07:13,008][ INFO][     dns_server.c:676 ] result: cloudflare-dns.com, rcode: 0,  104.16.249.249
[2020-01-26 18:07:13,908][ INFO][     dns_client.c:851 ] add server 104.16.249.249:443, type: https
[2020-01-26 18:56:07,921][ INFO][     dns_server.c:2242] query server www.baidu.com from 192.168.2.28, qtype = 1
[2020-01-26 18:56:07,922][ INFO][     dns_client.c:2547] send request www.baidu.com, qtype 1, id 3
[2020-01-26 18:56:08,786][ INFO][     dns_server.c:676 ] result: www.baidu.com, rcode: 0,  104.193.88.123
`

**运行环境**
1. 固件型号  
linux x86_64
2. 运营商  
中国电信

**重现步骤**
1. 上游DNS配置。  
8.8.8.8
2. 访问的域名。  
www.baidu.com 

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
smartdns的查询时间为：Query time: 865 msec
说明一个情况，smartdns的ping功能未生效，使用了tcp测速。
如下可能性：
1. 你的设备可能禁止ping，
2. 上游配置不正确，给smartdns的结果没有包含速度最佳的地址。
3. 运营商做了一些未知操作。

你可以打开debug日志排查。
或使用标准ping命令看是否能ping。

**Comment by leeshaoheng** [comment]
你这上游服务器，全是国外DNS，返回的地址也都是国外的，速度能不慢吗。。。
上游dns应该配置国内的

**Comment by Bnosora** [comment]
这毛病我也碰到过，而且也是`www.baidu.com`被谷歌解析到了美国，别的网站都没遇到过。也许是百度比较奇葩吧……可以考虑让百度单独走国内的dns解析

**Comment by catcherxuefeng** [comment]
已解决，原因：上游配置了代理
