### ISSUE TITLE
请问edns client subnet这个功能可以添加开启的命令吗？

### ISSUE THREAD

**Issue by thb007** [pymumu/smartdns#328]
比如开启 edns client subnet yes，关闭 edns client subnet no。目前好像只能手动添加ip/subnet，（类似edns-client-subnet 192.168.1.1/24），这样如果换个地方需要重新添加很麻烦

**Comment by XiaoliChan** [comment]
pcap-dnsproxy了解一下，能开edns

**Comment by pymumu** [comment]
edns client subnet 当前功能不可用，

具体讨论看这里

https://github.com/pymumu/smartdns/issues/277

**Comment by thb007** [comment]
> edns客户子网当前功能不可用，
> 
> 具体讨论看这里
> 
> [＃277](https://github.com/pymumu/smartdns/issues/277)

我弄了支持ecs的dns，现在想用smartdns转发一些国外的dns出去，但是没法启动。经过smartdns解析的Ip没ecs数据
![a](https://user-images.githubusercontent.com/17548936/73429448-b16af480-4376-11ea-990f-be0108366587.png)

**Comment by thb007** [comment]
> edns客户子网当前功能不可用，
> 
> 具体讨论看这里
> 
> [＃277](https://github.com/pymumu/smartdns/issues/277)

好像关闭了
