### ISSUE TITLE
可以增加忽略所有AAAA查询请求的选项吗？或者忽略指定域名的AAAA

### ISSUE THREAD

**Issue by 523860169** [pymumu/smartdns#33]
因为tls sni reset技术，只要域名符合gfw，即使获取的ipv6地址正常，也会被连接重置。
而大部分系统、浏览器都是ipv6优先的，只有在ipv6访问超时才会转而请求ipv4，这样就不可避免的导致连接时间的大大增加
另外并不是所有vps都支持ipv6的，所以即使路由器想把被墙的v6连接走代理，也不可行，所以还不如直接由smartdns给出“查询不到AAAA”的结果，让系统、浏览器误以为这些网站不支持v6，而直接走v4
[诸如此类](https://www.v2ex.com/t/493222)

**Comment by pymumu** [comment]
这个问题确实很头痛，只能期待tls1.3的SNI加密解决。

IP双栈的情况下，现在默认都是优先IPV6，所以导致这个问题。windows可以强制优先IPV4避免，但不是长久之计。

AAAA查询的情况下，只要返回SOA就表示无AAAA地址了。就看这样能否解决问题了，后续IPV6是趋势，这个可能只是暂时方案。

**Comment by 523860169** [comment]
我也觉得这只能是暂时的，但至少现在，忽略某些域名的AAAA还是非常有必要的。
甚至如果v6国际带宽一直比v4低，而国内又大规模普及v6的情况下，v6上外网的体验也只会越来越差

**Comment by pymumu** [comment]
我看看修改多不多，如果不多，就加进去。

**Comment by pymumu** [comment]
增加了此功能，通过配置项  
force-AAAA-SOA yes
强制停用IPV6域名。

界面没提供配置，可以在自定义配置界面手工增加配置项。

支持版本。
https://github.com/pymumu/smartdns/releases/tag/Beta14

**Comment by 523860169** [comment]
@pymumu 感谢大佬。也希望能增加忽略指定域名的AAAA，这样会更灵活一点

**Comment by 523860169** [comment]
感觉有bug，force-AAAA-SOA yes后，所有网页都会先是打不开，提示nxdomain什么的，过几秒才能打开，而且仅ipv4的网页也是如此

**Comment by 523860169** [comment]
我刚刚测试结果是，dig谷歌的AAAA时，force-AAAA-SOA yes后，延迟1千多才返回SOA，而force-AAAA-SOA no后，500左右就能返回AAAA了，所以虽然force-AAAA-SOA yes，但是smartdns还是会先查询AAAA、测试，最后再丢弃掉结果，只返回SOA吗？
因为dig AAAA时明显时间比正常情况下花的更多

**Comment by pymumu** [comment]
确认了代码，是立即返回的

root@raspberrypi:/home/pi/code # dig -t AAAA www.google.com @127.0.0.1

; <<>> DiG 9.10.3-P4-Raspbian <<>> -t AAAA www.google.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 2339
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.                        IN      AAAA

;; AUTHORITY SECTION:
www.google.com.         0       IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Oct 12 21:49:02 HKT 2018
;; MSG SIZE  rcvd: 122

看这个，返回时间是0ms

**Comment by 523860169** [comment]
我是把smartdns作为dnsmasq的上游，刚刚试了下，yes后直接dig smartdns的AAAA后确实延迟很低，所以可能 是我刚刚没设置好。但是所有网站第一次访问都打不开，要等3-5秒以后才能正常打开，这在centbrowser和火狐都能复现，只不过centbrowser有如下提示，火狐只是说找不到服务器ip
dns_probe_finished_bad_config
DNS_PROBE_FINISHED_NXDOMAIN
这是不是因为ipv6优先导致的？

**Comment by pymumu** [comment]
系统是先请求IPV6的。

你试一release 14重新发布的版本看看。

**Comment by lixuy** [comment]
也有同样问题，一方面是国内的网站ipv6没cdn，另一方面是有的国外网站IPV6连不上。建议增加这三种选项：
1、【速度优先】同时检测该域名AAAA和A记录的延迟，仅在AAAA延迟比A记录低时返回AAAA记录，否则只返回A记录，强行过滤AAAA；
2、【IPV4优先】当该域名同时存在AAAA和A记录时，仅返回A记录；当该域名仅存在AAAA记录时，返回AAAA记录；
3、【指定list】指定某些域名仅使用IPV6/IPV4结果（比如一些ipv6的下载站）

**Comment by HSXX** [comment]
有没有选项不优选IP呢？直接返回原始结果的IPV4，过滤IPV6

**Comment by pymumu** [comment]
@HSXX @523860169 @lixuy 
增加了双栈IP优选的功能，可以试用，如有问题，请提交issue

**Comment by 523860169** [comment]
@pymumu [ss.conf](https://raw.githubusercontent.com/523860169/hosts/master/ss.conf)
```
# Add custom settings here.

server-name smartdns

# dns server bind ip and port, default dns server port is 53.
# bind [IP]:port, 
# example: 
#   IPV4: :53
#   IPV6  [::]:53

bind :5353
cache-size 0
#force-AAAA-SOA no
# 启用IPv4/IPv6双栈优选
#dualstack-ip-selection-threshold 100
#dualstack-ip-selection yes

rr-ttl-min 60
#rr-ttl-max 86400

# set log level
# log-level [level], level=error, warn, info, debug
log-level error

# log-size k,m,g
log-size 128k

log-file /var/log/smartdns.log
log-num 2

# remote udp dns server list
# server [IP]:[PORT], default port is 53
server 58.22.96.66
server 218.104.128.106
server 114.114.114.114
server 114.114.115.115
server 223.5.5.5
server 223.6.6.6
server 1.2.4.8
server 210.2.4.8
server 119.29.29.29
server 117.50.11.11
server 117.50.22.22
server 8.8.8.8
#中科大
server 202.141.162.123:5353
#OpenDNS
server 208.67.220.220:443
server 208.67.222.222:443
#rubyfish.cn
server-tls 115.159.154.226:853
server-tls 47.99.165.31:853
server-tls 8.8.8.8:853
server-tls 1.1.1.1:853

# edns client subnet
edns-client-subnet-ipv4 58.22.53.145/32

# List of hosts that supply bogus NX domain results 
# bogus-nxdomain [ip]
bogus-nxdomain 220.250.64.0/24

conf-file /etc/smartdns/ad.conf
conf-file /etc/dnsmasq.d/ss.conf
```

**Comment by pymumu** [comment]
这个配置文件我用了没有问题。

是不是你最后那个ss.conf文件格式不正确。

smartdns配置项格式和dnsmasq是不同的。

另外还有一个事情，ECS现在功能还没实现，只有配置项。

**Comment by pymumu** [comment]
ipset后面是空格，不是等号。

**Comment by 523860169** [comment]
是，我也发现了。。。。没注意，直接把dnsmasq用的规则加载过去了
sorry

**Comment by 523860169** [comment]
@pymumu 对了，google的部分域名返回的是北京的ip，但是只用ipset的话，也会把这部分不用走代理的也走代理，我一直在找iptables规则，但是试了很多次，都是一会儿可以一会儿不行，请问你有什么办法或规则分享的吗

**Comment by pymumu** [comment]
你说的是子域名把。

后面或支持指定子域名排除规则。
现在的话，只能增加一个不走代理的ipset，把子域名加入那个ipset中。
