### ISSUE TITLE
内网公网混合环境下，“返回连接速度最快的查询结果”的实现逻辑

### ISSUE THREAD

**Issue by HiGarfield** [pymumu/smartdns#330]
**问题现象**  
简要描述问题出现的现象

单位内网，上游DNS服务器为8个公网DNS服务器（只能解析公网域名）+2个内网DNS服务器（能解析公网域名和内网域名）。

指定DNS服务器查询内网域名时，8个公网DNS服务器返回“域名不存在”，而2个内网DNS服务器会返回正确的内网IP地址。

但使用SmartDNS后，返回的最终结果是“域名不存在”，按理来说，“返回连接速度最快的查询结果”，应该能返回正确的IP地址。所以不太明白。

由于内网的域名繁多且极其混乱、无统一规范（无统一后缀，甚至有xxxx.net之类的域名，与公网域名无法区分），所以无法用nameserver进行分流到内网DNS服务器，给使用造成了不方便。

这个问题如何解决呢？谢谢！

由于单位内部网络涉密，无法上传相关日志，请谅解。

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/blob/80174d9da5dc8209395b74129e37f823dac4a4af/src/dns_server.c#L1458

这里有投票机制，超过一半的服务器返回SOA，smartdns就会立即返回SOA。
你可以做适当修改。

**Comment by HiGarfield** [comment]
> https://github.com/pymumu/smartdns/blob/80174d9da5dc8209395b74129e37f823dac4a4af/src/dns_server.c#L1458
> 
> 这里有投票机制，超过一半的服务器返回SOA，smartdns就会立即返回SOA。
> 你可以做适当修改。

了解，谢谢了！

**Comment by HiGarfield** [comment]
还是有问题

https://github.com/pymumu/smartdns/blob/80174d9da5dc8209395b74129e37f823dac4a4af/src/dns_server.c#L1458

我改成了
if (atomic_inc_return(&request->soa_num) == dns_server_num()) { 

重新编译后，没解决问题：

- 未开启SmartDNS，指定内网DNS服务器，可以正确返回地址：
C:\>nslookup 内网域名 内网DNS服务器
服务器:  UnKnown
Address:  内网DNS服务器

名称:    内网域名
Address:  正确解析的内网IP地址
Aliases:  *.*.*.*

- 开启SmartDNS，指定内网DNS服务器，无法正确返回地址：
C:\>nslookup 内网域名 内网DNS服务器
服务器:  UnKnown
Address:  内网DNS服务器

*** UnKnown 找不到 内网域名: Non-existent domain

为什么开了SmartDNS之后，我哪怕在电脑上指定内网DNS服务器，都无法正确返回IP地址？

**Comment by pymumu** [comment]
看你的日志里面，响应的结果是什么。

**Comment by HiGarfield** [comment]
找到问题了，单位的私有qiang导致的。使用外网DNS是违规的，被私有qiang处理了。。。
