### ISSUE TITLE
双栈网站ipv4优先，纯ipv6网站不影响访问 (自己实验到解决方法）

### ISSUE THREAD

**Issue by qingxiwa** [pymumu/smartdns#332]
自己实验的解决方法，各位可以有同样需要的，自己用nslookup命令查询一下啊

IPV6服务器     启用IPV6服务器
双栈IP优选      启用或禁用IPV4，IPV6间的IP优选策略。

这两个都不勾选，双栈网站返回ipv4，纯ipv6网站也能返回ipv6，实现了ipv4访问优先

**需求应用场景**
请描述需求应用的场景和方式。
国内这ipv6状况不完善，但是ipv6公网对移动宽带还是有价值的，如pt下载，远程访问。
但是移动只有移动网内ipv6保证速度，跨网的ipv6限流严重。

**建议的方案**
实现上述场景建议的方案。
客户端向smartdns查询，smartdns向上游dns查询，上游返回的如果是ipv4/ipv6双栈域名，smartdns将ipv6 aaaa地址丢掉，只向客户端返回ipv4地址，然后如果域名只有ipv6地址的才向客户端返回ipv6 地址

openwrt用smartdns作为dnsmasq的上游，dnsmasq不缓存dns记录

**Comment by pymumu** [comment]
你应该启用双栈IP优选功能。

**Comment by qingxiwa** [comment]
> 你应该启用双栈IP优选功能。
谢谢

请教一下： dualstack-ip-selection-threshold [0-1000]，这个阈值是指？
1.分别ping ipv4和ipv6地址的延迟之差，然后我也不懂了
2.ping ipv4延迟大于这个值就选用ipv6
3.ping ipv6延迟大于这个值就选用ipv6

附你的介绍（中英文好像都没具体说明这个阈值的用法）

IPV4, IPV6双栈IP优选功能如何使用
目前IPV6已经开始普及，但IPV6网络在速度上，某些情况下还不如IPV4，为在双栈网络下获得较好的体验，smartdns提供来双栈IP优选机制，同一个域名，若IPV4的速度远快与IPV6，那么smartdns就会阻止IPV6的解析，让PC使用IPV4访问，具体配置文件通过dualstack-ip-selection yes启用此功能，通过dualstack-ip-selection-threshold [time]来修改阈值。如果要完全禁止IPV6 AAAA记录解析，可设置force-AAAA-SOA yes。
How to use the IPV4, IPV6 dual stack IP optimization feature
At present, IPV6 network is not as fast as IPV4 in some cases. In order to get a better experience in the dual-stack network, SmartDNS provides a dual-stack IP optimization mechanism, the same domain name, and the speed of IPV4. Far faster than IPV6, then SmartDNS will block the resolution of IPV6, let the PC use IPV4, the feature is enabled by dualstack-ip-selection yes, dualstack-ip-selection-threshold [time] is for threshold. if you want to disable IPV6 AAAA record complete, please try force-AAAA-SOA yes.

**Comment by pymumu** [comment]
分别ping ipv4和ipv6地址的延迟之差

**Comment by qingxiwa** [comment]
我之前启用过双栈IP优选功能，luci界面没有阈值改，后来登录后台查文件发现阈值默认是0，没有改阈值，然后我在windows上用nslookup命令查，返回的有ipv6和ipv4地址。

我不理解smartdns是怎么比较阈值和差值，然后给客户端返回ip地址的
能不能解释一下这两个例子
1
（启用过双栈IP优选功能，阈值设为30）
向上游查询ipv6.baidu.com
上游返回2400:da00:2::29和220.181.38.148两个值
Ping 2400:da00:2::29 平均 = 173ms，Ping 220.181.38.148 平均 = 61ms， 两者差值为112ms
那么差值>阈值，然后smartdns会怎么做？

2:情况相反
（启用过双栈IP优选功能，阈值设为30）
向上游查询ipv6.baidu.com
上游返回2400:da00:2::29和220.181.38.148两个值
Ping 2400:da00:2::29 平均 = 61ms，Ping 220.181.38.148 平均 = 173ms， 两者差值为112ms
那么差值>阈值，然后smartdns会怎么做？

**Comment by pymumu** [comment]
1. IPV4
2. IPV6

**Comment by PikuZheng** [comment]
address /live.com/#6
不会返回ipv6结果
这个功能一直有啊？

**Comment by qingxiwa** [comment]
自己实验的解决方法，各位可以有同样需要的，自己用nslookup命令查询一下啊

IPV6服务器     启用IPV6服务器
双栈IP优选      启用或禁用IPV4，IPV6间的IP优选策略。

这两个都不勾选，双栈网站返回ipv4，纯ipv6网站也能返回ipv6，实现了ipv4访问优先

**Comment by wangmice** [comment]
smartdns是不是无法解析纯ipv6的网址？
不知道为何，vps上解析ipv6.google.com失败。

**Comment by BTimer6** [comment]
![image](https://user-images.githubusercontent.com/71555757/108138539-1d8ed680-70f9-11eb-991c-2fdb580a7e37.png)
还有其它方法走优先ipv6吗，我默认还是ipv6。

**Comment by PikuZheng** [comment]
> smartdns是不是无法解析纯ipv6的网址？
> 不知道为何，vps上解析ipv6.google.com失败。

可以。检查上游或是不是配置了只返回ipv4结果

**Comment by PikuZheng** [comment]
> ![image](https://user-images.githubusercontent.com/71555757/108138539-1d8ed680-70f9-11eb-991c-2fdb580a7e37.png)
> 还有其它方法走优先ipv6吗，我默认还是ipv6。

看不懂你的需求

**Comment by kkkgo** [comment]
> 分别ping ipv4和ipv6地址的延迟之差

如果ipv4地址禁ping，但ipv6地址不禁ping，那是不是就会被优选成ipv6了，然而我的需求和楼主一样是只希望纯ipv6网站才返回ipv6地址。
