### ISSUE TITLE
** server can't find smartdns: NXDOMAIN

### ISSUE THREAD

**Issue by simonfire007** [pymumu/smartdns#333]
**问题现象**  
使用正常，但是nslookup -querytype=ptr smartdns测试显示** server can't find smartdns: NXDOMAIN
是不是还有什么地方没配置对

用在Ubuntu 18.04上

**Comment by pymumu** [comment]
最新版本的smartdns才可以这样查  
你可以看看查询百度是否返回一个IP地址，如果是则工作了

**Comment by texplorer1** [comment]
1. 我想把smartdns做为了pihole的上游，需要在pihole的上游dns栏里怎么设置？
2. 当运行nslookup时我也同样遇到了问题：
`pi@raspberrypi:~ $ nslookup baidu.com
Server:		192.168.50.155
Address:	192.168.50.155#53

Non-authoritative answer:
Name:	baidu.com
Address: 220.181.38.148
Name:	baidu.com
Address: 220.181.38.251`

我还参考了https://7zht.com/index.php/smartdnspi-hole-wangyemiaokai.html#comments

3. 是不是可以考虑在/etc/smartdns/smartdns.conf配置中加类似的代码来解决我的问题？

`listen_addresses = ['127.0.0.1:5350', '[::1]:5350']`
