### ISSUE TITLE
我该使用哪个安装包？

### ISSUE THREAD

**Issue by wyjtm** [pymumu/smartdns#334]
Release的最新版和教程里的完全对不上号 不知道该下哪个

求教

MT7620
ARM A7

这两个该用哪个安装包？

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/releases/download/Release28/smartdns.1.2019.12.15-1028.arm-openwrt-all.ipk

**Comment by wyjtm** [comment]
谢谢
