### ISSUE TITLE
最新版重启路由smartdns和ShadowSocksR Plus+都不能启动

### ISSUE THREAD

**Issue by jiatianxa** [pymumu/smartdns#336]
**问题现象**  
在smartdns自定义里创建bind :7054 -group us
bind :7055 -group china 后 ShadowSocksR Plus+ 国外端口设7054用户组，都能启动正常，但是重启路由后两个插件都不能启动。DHCP/DNS 转发里添加的7054和7055端口，自动改成默认5335.还有在ShadowSocksR Plus+ 里用白名单模式开启正常，但是不到一分钟国外线路不通，国内正常。

**运行环境**
1. 固件型号  
固件版本 | OpenWrt R9.11.23 / LuCI Master (git-19.325.28777-62a63ed)
内核版本 | 4.14.158
2. 运营商  
中国移动
**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
1. 看一下smartdns的日志里面有什么。
2. 手工执行一下：
```shell
/etc/init.d/smartdns enable
```

**Comment by jiatianxa** [comment]
换了最新passwail的最新固件暂时没问题了
