### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by bitching** [pymumu/smartdns#337]
**需求应用场景**
实现规则少、速度优的透明代理。

**建议的方案**
方案基于以下假设和条件：
1. DNS污染不会返回国内IP。
2. 运营商DNS`(在不发生故障的时候)`返回结果的速度比自定义DNS快。
3. 国内所有的IP段可以通过APNIC获取，可以做成ipset（以便和iptables共享），或者以文本形式让`smartdns`读取。
4. 通过`ss-tunnel`之类的工具使自定义DNS服务器返回的结果不受污染。

Option 1. 先向`运营商DNS服务器`发起请求，当返回的IP是国内IP则使用，没有后续步骤。若非国内IP则抛弃结果，重新向`自定义DNS服务器`发起请求并使用相应结果。

Option 2. 同时向`运营商DNS服务器`和`自定义DNS服务器`发起请求。当运营商DNS返回国内IP，则抛弃后续结果，若非国内IP则抛弃当前结果，等待并使用自定义DNS返回的结果。

若自定义DNS使用VPS提供商的DNS，就同时保证了国内和国外CDN的速度。

**Comment by pymumu** [comment]
你说的可以尝试ip黑白名单。
另外，smartdns不解决dns污染问题，只关注网络加速。

**Comment by bitching** [comment]
并没有让smartdns解决污染的问题。只是说我可以这么做。
我看文档没有找到 per - dns_server IP黑白名单的设置方法。
如果设置国内IP为白名单，国外网站的解析结果不是始终就被丢弃了么……
