### ISSUE TITLE
18.06.1还不支持

### ISSUE THREAD

**Issue by yuhaiyang** [pymumu/smartdns#34]
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured

NETGEAR WNDR4300  

ar71xx  

期待下一次发布能够支持

**Comment by yuhaiyang** [comment]
IPK文件选择错误，应该用mips_24kc

**Comment by cod1ingcoding** [comment]
mips_24kc Releases页面没有看到，需要自己编译？
