### ISSUE TITLE
进程耗尽cpu和内存

### ISSUE THREAD

**Issue by PikuZheng** [pymumu/smartdns#341]
**问题现象**  
进程耗尽cpu和内存

**运行环境**
1. 固件型号  
Openwrt X86_64 18.06.5
2. 运营商  
无关
**重现步骤**
概率发生，各种操作无法重现
1. 上游DNS配置。  
https://223.5.5.5/dns-query

2. 访问的域名。  
无关

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
`
[2020-02-06 23:28:40,105][ERROR][     dns_client.c:2410] send query to 223.5.5.5 failed, Bad address, type: 3
`
日志里上百行都是这个，没有其他内容

2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

注：系统日志
`Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.304887] smartdns invoked oom-killer: gfp_mask=0x14201ca(GFP_HIGHUSER_MOVABLE|__GFP_COLD), nodemask=(null),  order=0, oom_score_adj=0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.305341] CPU: 0 PID: 6523 Comm: smartdns Not tainted 4.14.151 #0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.305588] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 12/12/2018
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.305951] Call Trace:
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306059]  0xffffffff815bd0c0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306183]  0xffffffff811059fb
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306307]  0xffffffff81104e39
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306431]  ? 0xffffffff81088e8b
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306559]  0xffffffff811058dd
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306683]  0xffffffff81109a0e
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306807]  0xffffffff811032fa
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.306931]  0xffffffff811fef7f
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307055]  0xffffffff81124fe2
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307187]  0xffffffff8112acc4
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307310]  0xffffffff8112b167
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307434]  0xffffffff81050fba
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307557]  0xffffffff810510f2
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307681]  ? 0xffffffff8160150c
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307809]  0xffffffff81601522
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.307933] RIP: 0033:0x5d99f5
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.308055] RSP: 002b:00007fd4e9189898 EFLAGS: 00010246
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.308241] RAX: 00007fd4e918db20 RBX: 0000000000feeab8 RCX: 0000000000007f77
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.308482] RDX: 0000000000000000 RSI: 00000000006d73c0 RDI: 000000000000000c
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.308724] RBP: 00007fd4e918bd30 R08: 0000000000002000 R09: 000000000063a893
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.308965] R10: 0000000000000000 R11: 0000000000000000 R12: 000000000000002d
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309206] R13: 00007fd4e9189900 R14: 000000000000000c R15: 0000000000000003
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309449] Mem-Info:
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309549] active_anon:110993 inactive_anon:163 isolated_anon:0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309549]  active_file:42 inactive_file:82 isolated_file:0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309549]  unevictable:0 dirty:0 writeback:0 unstable:0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309549]  slab_reclaimable:530 slab_unreclaimable:2996
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309549]  mapped:7 shmem:1202 pagetables:390 bounce:0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.309549]  free:4551 free_pcp:170 free_cma:0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.310619] Node 0 active_anon:443972kB inactive_anon:652kB active_file:168kB inactive_file:328kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:28kB dirty:0kB writeback:0kB shmem:4808kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.311369] DMA free:2396kB min:516kB low:644kB high:772kB active_anon:13196kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:0kB pagetables:24kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.312230] lowmem_reserve[]: 0 472 472 472
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.312390] DMA32 free:15808kB min:15864kB low:19828kB high:23792kB active_anon:430776kB inactive_anon:652kB active_file:168kB inactive_file:328kB unevictable:0kB writepending:0kB present:507776kB managed:488120kB mlocked:0kB kernel_stack:1904kB pagetables:1536kB bounce:0kB free_pcp:680kB local_pcp:680kB free_cma:0kB
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.313630] lowmem_reserve[]: 0 0 0 0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.313770] DMA: 1*4kB (M) 1*8kB (M) 1*16kB (M) 0*32kB 1*64kB (M) 0*128kB 1*256kB (M) 0*512kB 0*1024kB 1*2048kB (M) 0*4096kB = 2396kB
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.314177] DMA32: 330*4kB (UE) 341*8kB (UE) 85*16kB (UE) 13*32kB (UE) 8*64kB (UME) 14*128kB (UME) 14*256kB (UME) 2*512kB (UM) 3*1024kB (UM) 0*2048kB 0*4096kB = 15808kB
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.314687] 1337 total pagecache pages
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.314831] 0 pages in swap cache
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.314959] Swap cache stats: add 0, delete 0, find 0/0
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.315154] Free swap  = 0kB
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.315269] Total swap = 0kB
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.315395] 130942 pages RAM
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.315509] 0 pages HighMem/MovableOnly
Thu Feb  6 23:08:27 2020 kern.warn kernel: [51517.315652] 4935 pages reserved
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.315774] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.316077] [ 1776]     0  1776     2250       23      11       3        0             0 ubusd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.316386] [ 1778]     0  1778      682        9       6       3        0             0 askfirst
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.316692] [ 2029]     0  2029     1771       47       9       3        0             0 logd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.316987] [ 2048]     0  2048     3843       33      14       3        0             0 rpcd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.317284] [ 2100]   453  2100     1800       26       9       3        0             0 dnsmasq
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.317589] [ 2127]     0  2127      725        9       6       3        0             0 dropbear
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.317900] [ 2185]     0  2185     3880       39      14       3        0             0 netifd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.318201] [ 2218]     0  2218     2809       28      12       3        0             0 odhcpd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.318542] [ 2272]     0  2272      684        8       7       3        0             0 p910nd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.318845] [ 2317]     0  2317     2777       29      11       3        0             0 uhttpd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.319146] [ 2347]     0  2347     3276       50      12       3        0             0 keepalived
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.319455] [ 2378]     0  2378     3299       74      10       3        0             0 keepalived
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.319767] [ 2440]     0  2440     1214       14       7       3        0             0 odhcp6c
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.320072] [ 2536]     0  2536      689       11       6       3        0             0 vlmcsd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.320376] [ 2586]     0  2586      771        8       6       3        0             0 ntpd
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.320676] [ 2715]     0  2715      450      189       5       2        0             0 ss-redir
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.320982] [ 2717]     0  2717      108       34       5       3        0             0 obfs-local
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.321293] [ 2750]     0  2750      449      190       4       2        0             0 ss-redir
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.321600] [ 2753]     0  2753      106       31       5       3        0             0 obfs-local
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.321917] [ 6520]     0  6520   110207   109070     219       3        0             0 smartdns
Thu Feb  6 23:08:27 2020 kern.err kernel: [51517.322223] Out of memory: Kill process 6520 (smartdns) score 841 or sacrifice child
Thu Feb  6 23:08:27 2020 kern.err kernel: [51517.322503] Killed process 6520 (smartdns) total-vm:440828kB, anon-rss:436280kB, file-rss:0kB, shmem-rss:0kB
Thu Feb  6 23:08:27 2020 kern.info kernel: [51517.422345] oom_reaper: reaped process 6520 (smartdns), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by pymumu** [comment]
你配置的缓存是多少。

**Comment by PikuZheng** [comment]
缓存4096 发生问题后改2048 无改善

**Comment by PikuZheng** [comment]
进程没有生成 coredump 文件

**Comment by pymumu** [comment]
把你配置发一下把。

**Comment by PikuZheng** [comment]
`server-name smartdns
bind :53
bind-tcp :53
prefetch-domain yes
cache-size 2048
rr-ttl-min 300
log-size 64K
log-num 1
log-level error
server-tls 8.8.8.8  -group outbound exclude-default-group
server-https https://i.233py.com/dns-query  -group mainland
server-https https://223.5.5.5/dns-query  -group mainland
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf
`

`# Add domains which you want to force to an IP address here.
# The example below send any host in example.com to a local webserver.
# address /domain/[ip|-|-4|-6|#|#4|#6]
# address /www.example.com/1.2.3.4, return ip 1.2.3.4 to client
# address /www.example.com/-, ignore address, query from upstream, suffix 4, for ipv4, 6 for ipv6, none for all
# address /www.example.com/#, return SOA to client, suffix 4, for ipv4, 6 for ipv6, none for all

# specific ipset to domain
# ipset /domain/[ipset|-]
# ipset /www.example.com/block, set ipset with ipset name of block
# ipset /www.example.com/-, ignore this domain

# specific nameserver to domain
# nameserver /domain/[group|-]
# nameserver /www.example.com/office, Set the domain name to use the appropriate server group.
# nameserver /www.example.com/-, ignore this domain

address /google.com.my/#6
address /google.co.jp/#6
address /google.com/#6
address /1e1000.net/#6
address /youtube.com/#6
address /ytimg.com/#6
address /ggpht.com/#6
address /gstatic.com/#6
address /googleapis.com/#6
address /googleapis.cn/#6
address /googleusercontent.com/#6
address /googlevideo.com/#6
address /live.com/#6
address /freebsd.org/#6
address /ip138.com/#6
address /pinterest.com/#6
address /openvpn.net/#6
address /openvpn.org/#6
address /avaaz.org/#6
address /redd.it/#6
address /cloudcone.com/#6
address /v2ray.com/#6

nameserver /233py.com/mainland
nameserver /.googleapis.cn/outbound
nameserver /.google.com.my/outbound
nameserver /.google.co.jp/outbound
nameserver /.google.com/outbound
nameserver /.1e1000.net/outbound
nameserver /.youtube.com/outbound
nameserver /.ytimg.com/outbound
nameserver /.ggpht.com/outbound
nameserver /.gstatic.com/outbound
nameserver /.googleapis.com/outbound
nameserver /.googleusercontent.com/outbound
nameserver /.googlevideo.com/outbound
nameserver /.v2ray.com/outbound
nameserver /.mega.nz/outbound
nameserver /.github.com/outbound

nameserver /.cn/mainland
nameserver /.weibo.com/mainland
nameserver /.sinaedge.com/mainland
nameserver /.wsglb0.com/mainland
nameserver /.qq.com/mainland
nameserver /.qlogo.com/mainland
nameserver /.qqmail.com/mainland
nameserver /.qcloud.com/mainland
nameserver /.idqqimg.com/mainland
nameserver /.gtimg.com/mainland
nameserver /.tencent.com/mainland
nameserver /.weiyun.com/mainland
nameserver /.kugou.com/mainland
nameserver /.kgimg.com/mainland
nameserver /.microsoft.com/mainland
nameserver /.91.com/mainland
nameserver /.sina.com/mainland
nameserver /.sinacdn.com/mainland
nameserver /.sinaapp.com/mainland
nameserver /.sinacloud.com/mainland
nameserver /.360buyimg.com/mainland
nameserver /.jd.com/mainland
nameserver /.jdcdn.com/mainland
nameserver /.qianxun.com/mainland
nameserver /.lxdns.com/mainland
nameserver /.163.com/mainland
nameserver /.netease.com/mainland
nameserver /.youku.com/mainland
nameserver /.tudou.com/mainland
nameserver /.ykimg.com/mainland
nameserver /.pengyou.com/mainland
nameserver /.iqiyi.com/mainland
nameserver /.acgvideo.com/mainland
nameserver /.ctrip.com/mainland
nameserver /.ourwebcdn.com/mainland
nameserver /.wuruo.com/mainland
nameserver /.wscdns.com/mainland
nameserver /.chunshuitang.com/mainland
nameserver /.weiyun.com/mainland
nameserver /.buy.com/mainland
nameserver /.yhbimg.com/mainland
nameserver /.lofter.com/mainland
nameserver /.ifengimg.com/mainland
nameserver /.suning.com/mainland
nameserver /.airchina.com/mainland
nameserver /.zuche.com/mainland
nameserver /.express.com/mainland
nameserver /.csair.com/mainland
nameserver /.bilibili.com/mainland
nameserver /.biliapi.com/mainland
nameserver /.im9.com/mainland
nameserver /.zuchecdn.com/mainland
nameserver /.ch.com/mainland
nameserver /.oneplusbbs.com/mainland
nameserver /.qiyi.com/mainland
nameserver /.qiyipic.com/mainland
nameserver /.microsoft.com/mainland
nameserver /.apple.com/mainland
nameserver /.hdslb.com/mainland
nameserver /.biligame.com/mainland
nameserver /.ourdvs.com/mainland
nameserver /.wx.com/mainland
nameserver /.weixin.com/mainland
nameserver /.flyertea.com/mainland
nameserver /.coolapk.com/mainland
nameserver /.coolapkmarket.com/mainland
nameserver /.diaox2.com/mainland
nameserver /.kunlun.com/mainland
nameserver /.kunlungr.com/mainland
nameserver /.kunlunar.com/mainland
nameserver /.kunlunpi.com/mainland
nameserver /.kunlunhuf.com/mainland
nameserver /.cdn.com/mainland
nameserver /.alimmdn.com/mainland
nameserver /.eltima.com/mainland
nameserver /.tenpay.com/mainland
nameserver /.cdntip.com/mainland
nameserver /.dianping.com/mainland
nameserver /.dpfile.com/mainland
nameserver /.dnsv1.com/mainland
nameserver /.office365.com/mainland
nameserver /.xiami.com/mainland
nameserver /.amemv.com/mainland
nameserver /.ixigua.com/mainland
nameserver /.apple.com/mainland
nameserver /.mydrivers.com/mainland
nameserver /.youziku.com/mainland
nameserver /.xiumius.com/mainland
nameserver /.cdntip.com/mainland
nameserver /.smzdm.com/mainland
nameserver /.kugou.com/mainland
nameserver /.mgtv.com/mainland
nameserver /.hitv.com/mainland
nameserver /.hifuntv.com/mainland
nameserver /.videojj.com/mainland
nameserver /.znds.com/mainland
nameserver /.downbei.com/mainland
nameserver /.dangcdn.com/mainland
nameserver /.dianshijia.com/mainland
nameserver /.letv.com/mainland
nameserver /.starschina.com/mainland
nameserver /.starschinalive.com/mainland
nameserver /.pptv.com/mainland
nameserver /.dnion.com/mainland
nameserver /.youku.com/mainland
nameserver /.ykimg.com/mainland
nameserver /.gwdang.com/mainland
nameserver /.ydstatic.com/mainland
nameserver /.douban.com/mainland
nameserver /.kunlunca.com/mainland
nameserver /.kunlunar.com/mainland
nameserver /.iflyrec.com/mainland
nameserver /.sinacloud.com/mainland
nameserver /.applinzi.com/mainland
nameserver /.hp.com/mainland
nameserver /.eqh5.com/mainland
nameserver /.cnblogs.com/mainland
nameserver /.miaopai.com/mainland
nameserver /.sinasws.com/mainland
nameserver /.wsglb0.com/mainland
nameserver /.yunduns.com/mainland
nameserver /.51cto.com/mainland
nameserver /.cdntip.com/mainland
nameserver /.smzdm.com/mainland
nameserver /.zdmimg.com/mainland
nameserver /.nipic.com/mainland
nameserver /.upaiyun.com/mainland
nameserver /.hicloud.com/mainland
nameserver /.huawei.com/mainland
nameserver /.dbankcdn.com/mainland
nameserver /.126.net/mainland
nameserver /.csdn.net/mainland
nameserver /.edgekey.net/mainland
nameserver /.akadns.net/mainland
nameserver /.akamai.net/mainland
nameserver /.edgesuite.net/mainland
nameserver /.cedexis.net/mainland
nameserver /.llnwd.net/mainland
nameserver /.cnki.net/mainland
nameserver /.meituan.net/mainland
nameserver /.xiami.net/mainland
nameserver /.autojs.net/mainland
nameserver /.hanzify.org/mainland
nameserver /.tvapk.net/mainland
nameserver /.dangbei.net/mainland
nameserver /.cibntv.net/mainland
nameserver /.tl88.net/mainland
nameserver /cdn.net/mainland
nameserver /.crskybbs.org/mainland
nameserver /7766.net/mainland
nameserver /.taobao.com/mainland
nameserver /.taobaocdn.com/mainland
nameserver /.tmall.com/mainland
nameserver /.alicdn.com/mainland
nameserver /.tbcache.com/mainland
nameserver /.aliyun.com/mainland
nameserver /.tank.com/mainland
nameserver /.alipay.com/mainland
nameserver /.alipayobjects.com/mainland
nameserver /.freshhema.com/mainland
nameserver /.mmstat.com/mainland
nameserver /.alibabadns.com/mainland
nameserver /.aliyuncs.com/mainland
nameserver /.fliggy.com/mainland
nameserver /.xiumi.us/mainland
nameserver /.acg.tv/mainland
nameserver /.aliapp.org/mainland
nameserver /.staticfile.org/mainland
nameserver /.bishi.im/mainland
nameserver /.dancf.com/mainland`
`# Add IP blacklist which you want to filtering from some DNS server here.
# The example below filtering ip from the result of DNS server which is configured with -blacklist-ip.
# blacklist-ip [ip/subnet]
# blacklist-ip 254.0.0.1/16
blacklist-ip 203.98.7.65
blacklist-ip 243.185.187.39
blacklist-ip 8.7.19.45
blacklist-ip 46.82.174.68
blacklist-ip 159.106.121.75
blacklist-ip 78.16.49.15
blacklist-ip 59.24.3.173
blacklist-ip 93.46.8.89
blacklist-ip 37.61.54.158
`

`# Add custom settings here.

# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
# log-level error

# log-size k,m,g
# log-size 128k

# log-file /var/log/smartdns.log
# log-num 2

# List of hosts that supply bogus NX domain results
# bogus-nxdomain [ip/subnet]

#force-AAAA-SOA yes
speed-check-mode none
#speed-check-mode tcp:80
`

**Comment by pymumu** [comment]
打开debug日志，看一下smartdns是否出现请求循环把。

感觉你这个应该是iptables配置不正确，导致smartdns循环

**Comment by PikuZheng** [comment]
`
iptables -t nat -A PREROUTING -d 172.17.2.100 -p udp -m udp --dport 53 -j DNAT --to-destination 172.17.2.102:53
`
#167 多ip监听问题
其中102是本机 ip，开机后能 SmartDNS 正常服务。100是 keepalived 在启动后给本机增加的 ip，SmartDNS 不监听。iptables 只有这一条，用于使100能正常工作。
我检查了下现在这个故障似乎是在增加了https上游后出现的，可能服务自身的查询请求出现了问题？

**Comment by PikuZheng** [comment]
好了我知道怎么回事了。
上游https dns （因为是域名）本身需要dns查询一次。
Openwrt系统默认dns服务是127.0.0.1，所以这个查询又回到了SmartDNS。
结果这个查询只能走到223.5.5.5，然而这个223.5.5.5又经常失灵。
所以循环了。

**Comment by PikuZheng** [comment]
修正以上问题后，仍出现内存耗尽情况。日志如下：
‘’‘
[2020-02-07 14:47:18,001][DEBUG][     dns_client.c:2728] retry query www.facebook.com
[2020-02-07 14:47:18,001][DEBUG][     dns_client.c:1657] SSL write fail error no:  shutdown while in init(336462231)
[2020-02-07 14:47:18,001][ERROR][     dns_client.c:2410] send query to 218.60.18.35 failed, Bad address, type: 3
[2020-02-07 14:47:18,001][DEBUG][     dns_client.c:2412] send query to 223.5.5.5 failed, Out of memory, type: 3
’‘’

**Comment by pymumu** [comment]
你说的是日志里面的out-of-memory么？
那个是debug，不影响，但的dns配置有错误，223.5.5.5配置了不支持的协议。

**Comment by sammimk830** [comment]
其實我也遇到了這個問題，發生是在昨天，這邊的網絡不穩，DNS是我在某地建的，但線路不穩導致DNS time out然後就一直Out of memory，直到重啟才正常
我bind了兩個group，一個有問題，另一個就沒事。

[2020-05-27 00:05:14,204][ERROR][     dns_server.c:2969] dns server process failed.
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2896] retry query heartbeat.belkin.com
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2553] send query to 203.174.52.78 failed, Out of memory, type: 2
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2896] retry query presence.teams.microsoft.com
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2553] send query to 203.174.52.78 failed, Out of memory, type: 2
