### ISSUE TITLE
怎样配合chinadns适用?总是提示转发Dnsmasq失败

### ISSUE THREAD

**Issue by chancat87** [pymumu/smartdns#344]
**问题现象**  
想和chinadns配合使用,配置完后启动成功转发Dnsmasq失败
咨询问题是在尝试与请教

**运行环境**
1. openwrt x86_64  

2. 运营商  
电信

**重现步骤**
问题1:
试着尝试与配合chinadns分别对国内国外的dns解析  ,
smartdns端口设置为6053,用作为chinadns的上游,chiandns端口设置为5335(因为固件里ssplus插件的本地解析方式里只有5335端口), 在smartdns里面对dns进行分组为china和us两个,自定义设置里新增两条分组规则, 然后回到chinadns上游服务器里添加127.0.0.1:us 的分组端口,最后在固件DHCP/DNS的DNS 转发设置为127.0.0.1:china 的分组端口,启动后发现只能访问国内网站,国外不行,并且smartdns界面显示转发Dnsmasq失败,请问我这样操作哪里不正确?是否可以配合chinadns进行区分国内外网站分别解析?

问题2
上面的操作失败后,我就关闭了chinadns,只开启smartdns这样可以正常翻墙,请问我本地wal口和lan口的自定义DNS还需要设置么？目前设置的是：wan:127.0.0.1 lan:192.168.1.1

问题3,只启用smartdns来作为主dns之后发现带宽只能跑一半了?....油管只有6000的速度就不错了， 不知道是哪里设置错了。。,奇怪啊,然后我关闭了smartdns只开启chinadns 速度马上回来了..油管能跑10W...求助

2. 访问的域名。  

**信息收集**  
日志没了...我用手机操作的,然后设置东西的时候搞崩溃了就重置了...

**Comment by pymumu** [comment]
理解原理在设置，和想清楚数据的流向在设置，不清楚原理，最好默认。
