### ISSUE TITLE
[Feature Request]将测速结果输出为特定格式

### ISSUE THREAD

**Issue by showgood163** [pymumu/smartdns#347]
**需求应用场景**
根据本地网络环境（PING/TCP@443是否连通），自适应的生成无法直连的域名列表，并以特定形式输出（如PAC），方便后续处理（如使用代理访问）

**建议的方案**
将测速时无法连通的域名记录到一份列表中，并在之后测速时不断更新该列表
可以参考[COW](https://github.com/cyfdecyf/cow)中的实现思路

**设备信息**
1. 设备信息（CPU，厂家）  
无
2. 固件信息
无

**Comment by pymumu** [comment]
此类需求不会做到smartdns中。

**Comment by showgood163** [comment]
你好。

如果我想使用smartdns实现上述功能，请问我该怎么做？

**Comment by pymumu** [comment]
_dns_server_request_complete函数，判断是否有ping结果
