### ISSUE TITLE
[Feature Request]添加可用于dd-wrt的entware安装包

### ISSUE THREAD

**Issue by showgood163** [pymumu/smartdns#348]
**需求应用场景**
目前release的entware包中路径是针对openwrt的，dd-wrt中使用需要手动解压并安装。

**建议的方案**
[entware on dd-wrt安装指南](https://wiki.dd-wrt.com/wiki/index.php/Installing_Entware)中指出，软件包安装的默认路径在`/opt/etc`下。其他控制文件的路径也需要相应作出调整。

**设备信息**
1. 设备信息（CPU，厂家）  
netgear r6400 Broadcom BCM4708 
2. 固件信息
dd-wrt

**Comment by pymumu** [comment]
使用optware的安装包即可。
