### ISSUE TITLE
关于netflix 出现锁区问题

### ISSUE THREAD

**Issue by gosleep2018** [pymumu/smartdns#349]
**问题现象**  
我设置了一个vps ss服务器，通过ss科学上网，运行smartdns后，感觉是快了，但是netflix 提示锁区了？
查了下说明，有两个命令： ipset  和nameserver 可以指定域名 忽略，我没搞清楚 ipset 和 nameserver 的区别，比如 ，想让一个域名 被忽略（根据介绍，ipset /domain/-，nameserver /domaii/-可以设置某域名忽略），提问：
1、我应该用ipset 还是nameserver 去设置？ipset /www.netflix.com/-，nameserver /www.netflix.com/-，选哪个？
2、被忽略的定义 是什么，是否这个域名走vps的dns解析？
**运行环境**
1. 固件型号  
openwrt
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
www.netflix.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
表示指定的规则不生效。

**Comment by gosleep2018** [comment]
多谢，2 明白了，那问题1呢？

**Comment by pymumu** [comment]
两个是独立的功能，看你用途。
