### ISSUE TITLE
问：基本设置里的“重定向”是什么意思？我只有选择无 dns 才稳定？

### ISSUE THREAD

**Issue by gosleep2018** [pymumu/smartdns#350]
**需求应用场景**
基本设置里的“重定向”是什么意思？我只有选择无 dns 才稳定？
如果选择’作为dnsmasq的上游服务器‘，有的时候，openwrt ’正确上网姿势✔️“里 ‘谷歌连接’点击 显示连接 就不动了。
 请教Boss，这个选项三个事啥意思，应该选哪个 多谢？

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
应该是你设备里面有其他dns服务导致冲突了。

具体说明，可以看readme。
