### ISSUE TITLE
增加配置参数允许在不影响缓存的情况下修改返回的TTL值

### ISSUE THREAD

**Issue by CyberKoo** [pymumu/smartdns#351]
**需求应用场景**
多级DNS配置，下游DNS不支持复写TTL时间以及禁用缓存

**建议的方案**
根据介绍，使用rr-ttl来重写TTL会直接影响缓存中域名过期的时间。
增加类似于rr-ttl-*的参数，允许在不影响smartdns本地缓存的情况下重写返回数据中的TTL值。

**设备信息**
1. 设备信息（CPU，厂家）  
RPI4B

2. 固件信息
ArchLinux

**Comment by pymumu** [comment]
使用过期缓存功能。
