### ISSUE TITLE
无法自动启动

### ISSUE THREAD

**Issue by reky04** [pymumu/smartdns#352]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
AC88U + 梅林原版
2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
安装好重启路由器不能自动启动
路由器日志：
May  5 13:05:27 admin:  sh /opt/S50smartdns.1 start
May  5 13:05:28 rc_service: hotplug 882:notify_rc restart_nasapps
May  5 13:05:28 avahi-daemon[378]: Files changed, reloading.
May  5 13:05:28 avahi-daemon[378]: Loading service file /tmp/avahi/services/mt-daap.service.
May  5 13:05:28 iTunes: daemon is stopped
May  5 13:05:28 FTP_Server: daemon is stopped
May  5 13:05:28 Samba_Server: smb daemon is stopped
May  5 13:05:28 kernel: gro disabled
。。。略。。。
May  5 13:05:31 admin:  sh /opt/S50smartdns.1 firewall-start
May  5 13:05:31 Samba_Server: daemon is started
May  5 13:05:31 wsdd2[1306]: starting.
May  5 13:05:31 wsdd2[1306]: wsdd-http-v6: open_ep: bind: Address already in use
May  5 13:05:31 miniupnpd[1313]: HTTP listening on port 50512
May  5 13:05:31 miniupnpd[1313]: Listening for NAT-PMP/PCP traffic on port 5351
May  5 13:05:33 dnsmasq[343]: read /etc/hosts - 13 addresses
May  5 13:05:33 dnsmasq[343]: read /etc/hosts.dnsmasq - 6 addresses

SSH 手工运行
 sh /opt/S50smartdns.1 start
后运行正常！

smartdns.log        error模式
[2020-02-13 13:17:47,160][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,161][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,161][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,161][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,161][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,161][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,318][ERROR][     dns_client.c:1413] connect failed.
[2020-02-13 13:17:47,318][ERROR][     dns_client.c:1413] connect failed.

重启后运行测试：
C:\Windows\System32>nslookup www.baidu.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  2001:470:***:***::1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

SSH 手工运行成功后测试：
C:\Windows\System32>nslookup www.163.com
服务器:  smartdns
Address:  2001:470:***:***::1

非权威应答:
名称:    www.163.com.lxdns.com
Address:  157.185.167.18
Aliases:  www.163.com

**Comment by reky04** [comment]
smartdns 模式2

dnsmasq.conf.add 
port=653
# dnsmasq 端口改653

**Comment by pymumu** [comment]
要配置optware自动启动。
这个具体看optware的操作说明。
