### ISSUE TITLE
Makefile中LDFLAGS少 -lrt 参数

### ISSUE THREAD

**Issue by HiGarfield** [pymumu/smartdns#353]
https://github.com/pymumu/smartdns/blob/4bd6c025db7db4132076772355259d33ebb7a138/src/Makefile#L38

在CentOS 6.1实测，LDFLAGS要加上 -lrt 才能正常编译。

抱歉，Pull request不会搞，只能这样提问题报告了。

**Comment by HiGarfield** [comment]
不加-lrt报以下错误：

cc smartdns.o fast_ping.o dns_client.o dns_server.o dns.o util.o tlog.o dns_conf.o dns_cache.o http_parse.o lib/rbtree.o lib/art.o lib/bitops.o lib/radix.o lib/conf.o -o smartdns -lssl -lcrypto -lpthread
util.o: In function `get_tick_count':
/root/smartdns/src/util.c:95: undefined reference to `clock_gettime'
tlog.o: In function `_tlog_wait_log_locked':
/root/smartdns/src/tlog.c:1221: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [smartdns] Error 1

**Comment by HiGarfield** [comment]
不加-lrt报以下错误：

`cc smartdns.o fast_ping.o dns_client.o dns_server.o dns.o util.o tlog.o dns_conf.o dns_cache.o http_parse.o lib/rbtree.o lib/art.o lib/bitops.o lib/radix.o lib/conf.o -o smartdns -lssl -lcrypto -lpthread
util.o: In function `get_tick_count':
/root/smartdns/src/util.c:95: undefined reference to `clock_gettime'
tlog.o: In function `_tlog_wait_log_locked':
/root/smartdns/src/tlog.c:1221: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [smartdns] Error 1
`

**Comment by pymumu** [comment]
旧版本系统不再支持。

如果你要编译可以使用如下命令编译
```shell
LDFLAGS=-lrt make
``

**Comment by HiGarfield** [comment]
> 旧版本系统不再支持。
> 
> 如果你要编译可以使用如下命令编译
> 
> ```shell
> LDFLAGS=-lrt make
> ```

嗯，网上查了一下， glibc版本低于2.17的情况下，使用clock_gettime函数需要在LDFLAGS中加-lrt选项。
用ldd --version查了一下，我的CentOS 6.1里面，glibc版本是2.12。
