### ISSUE TITLE
添加自定义 PTR 记录规则

### ISSUE THREAD

**Issue by felixonmars** [pymumu/smartdns#354]
**需求应用场景**
自定义 PTR 记录以便内网地址可读。

**建议的方案**
希望能添加自定义 PTR 记录，对应 dnsmasq 的 ptr-record 设置项。

**设备信息**
1. 设备信息（CPU，厂家）  
J1900，工控机

2. 固件信息
Arch Linux x86_64

**Comment by pymumu** [comment]
后面有空添加把，不过smartdns没有dhcp-server，无法自动获取PTR记录，都要手工配置。

这个主要场景是什么？

**Comment by felixonmars** [comment]
@pymumu 只是标记内网IP地址便于分辨设备，不急 :)

**Comment by dominicx** [comment]
我也需要这个功能，那怕设置ptr记录到另外一个dns服务器，比如设置ptr到DHCP服务器，由DHCP所在服务器负责ptr反向解析。

**Comment by Ryker97** [comment]
附议

**Comment by pymumu** [comment]
最新版本支持解析dnsmasq的dhcp lease文件并相应ptr记录

可以配置指定lease文件路径，具体看readme

**Comment by pymumu** [comment]
启用address的反向解析即可
https://pymumu.github.io/smartdns/config/domain-address/

自动扩展address对应的PTR记录

**Comment by shoyuf** [comment]
> 启用address的反向解析即可 https://pymumu.github.io/smartdns/config/domain-address/
> 
> 自动扩展address对应的PTR记录

expand-ptr-from-address yes
会对 dhcp.lease 内的设备和 IP 生效吗？
