### ISSUE TITLE
授权协议问题

### ISSUE THREAD

**Issue by felixonmars** [pymumu/smartdns#355]
README 中目前描述为
```
Smartdns 基于GPL V3协议开源。
```
但仓库根目录的 LICENSE 文件内容为 AGPL v3。

请问应该以哪个为准？

**Comment by pymumu** [comment]
最初是打算AGPL的，代码里面都是GPL，那个License文件忘记更新了。

**Comment by cdluminate** [comment]
@pymumu 请求更新LICENSE文件。当上传该软件到严格的发行版(e.g. Debian)时，AGPL-3.0 许可证会对不能阅读中文的审核人员带来困扰。
