### ISSUE TITLE
勾选启动tcp服务器后报错

### ISSUE THREAD

**Issue by Mousehk** [pymumu/smartdns#357]
**问题现象**  
勾选启动tcp服务器后报错，并不能联网。

**运行环境**
1. 固件型号  n1 openwrt旁路由 

2. 运营商  移动

**重现步骤**
1. 上游DNS配置。  
配置tcp协议报错
[smartdns.log](https://github.com/pymumu/smartdns/files/4202325/smartdns.log)

**Comment by pymumu** [comment]
你启动服务后，看一下进程在不在把。

**Comment by Mousehk** [comment]
813     1 root     S     5056   0%   0% /usr/sbin/smartdns -f -c /var/etc/smartdns/smartdns.conf
在的，无论勾不勾选都显示运行中，但是只要勾选启动tcp后就上不了网了。

**Comment by pymumu** [comment]
cat  /var/etc/smartdns/smartdns.conf
看看

**Comment by Mousehk** [comment]
server-name china
bind [::]:5335
dualstack-ip-selection yes
prefetch-domain yes
cache-size 5120
rr-ttl-min 300
log-size 64K
log-num 1
log-level error
server 114.114.114.114:53  -group china 
server 235.5.5.5:53  -group china 
server 180.76.76.76:53  -group china 
server-tcp 119.29.29.29:53  -group china 
server-tls 8.8.8.8:53  -group overseas 
server-tls 208.67.222.222:53  -group overseas 
server-tcp 208.67.222.222:53  -group overseas 
server-https https://dns.google/dns-query  -group overseas 
server-https https://doh.opendns.com/dns-query  -group overseas 
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

**Comment by gosleep2018** [comment]
勾选这个的目的是什么？

**Comment by Mousehk** [comment]
使用tcp协议呀 现在只能udp开启正常

**Comment by pymumu** [comment]
看配置并没启用tcp
你换个端口看看把。

**Comment by Mousehk** [comment]
感谢答复，我试着重启路由器好了。
