### ISSUE TITLE
请教：关于基本配置里 “tcp服务器”是否勾选的作用？

### ISSUE THREAD

**Issue by gosleep2018** [pymumu/smartdns#358]
请教：关于基本配置里 “tcp服务器”是否勾选的作用？

勾和不勾的作用是什么呢？google 半天 没找到答案

**运行环境**
1. 固件型号  

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
主要是提供终端设备用TCP到smartdns查询，一般用不到。
