### ISSUE TITLE
nslookup查询百度只返回一个ip，但查youtube返回几个ip，是否正常？

### ISSUE THREAD

**Issue by daisuki4gh** [pymumu/smartdns#361]
**需求应用场景**
确认smartdns是否运行成功。

翻了很多您回复的帖子，都提到“你可以看看查询百度是否返回一个IP地址，如果是则工作了”，我现在百度返回一个，但是需要富强的网站返回好几个IP，是否正常？
![WX20200216-002256](https://user-images.githubusercontent.com/40634329/74591432-ea7fb600-5052-11ea-8c61-e663fb4bc0ed.png)

**建议的方案**
已在openwrt 64上配置smartdns并运行。

**设备信息**
1. 设备信息（CPU，厂家）  
主机名	OpenWrt
主机型号	Intel(R) Celeron(R) CPU 3215U @ 1.70GHz : 1 Core 1 Thread
CPU信息	1696.074 MHz +100.0°C
固件版本	OpenWrt 19.07-SNAPSHOT / LuCI 18-Lienol (git-20.044.63297-f21c9fa)
内核版本	4.14.169
本地时间	2020-02-16 00:18:48 星期日
运行时间	14h 35m 37s
平均负载	0.04, 0.02, 0.00
2. 固件信息
固件版本	OpenWrt 19.07-SNAPSHOT / LuCI 18-Lienol (git-20.044.63297-f21c9fa)
smartdns	 2019.12.15-2

**Comment by pymumu** [comment]
软件被设计只会返回一个IP地址。

**Comment by daisuki4gh** [comment]
> 软件被设计只会返回一个IP地址。

您好，可能我表述的不够清楚，误会我的意思了。
我的疑问是：像YouTube这种返回好几个ip的是不是说明我的配置有错误？

**Comment by pymumu** [comment]
任何情况都只会返回一个地址

**Comment by daisuki4gh** [comment]
> 任何情况都只会返回一个地址

看来还是没配置好，我再研究下。谢谢！

**Comment by onion83** [comment]
当服务器为双栈，且当 dualstack-ip-selection no 时候，应该返回一个 IPv4 和 一个 IPv6

**Comment by daisuki4gh** [comment]
> 当服务器为双栈，且当 dualstack-ip-selection no 时候，应该返回一个 IPv4 和 一个 IPv6
这样吗？

`root@OpenWrt:~# nslookup youtube.com
Server:		120.196.165.24
Address:	120.196.165.24#53

Name:      youtube.com
Address 1: 69.171.244.12
Address 2: 2001::4a56:cac`

**Comment by onion83** [comment]
@daisuki4gh 是的，但是双栈环境非常复杂，既有 A 记录又有 AAAA 记录的话，很多系统、客户端都会优选 AAAA 记录。因为 IPv4 和 IPv6 有不同的路由，防火墙规则会导致如 ss 透明代理失败，我目前是利用新的  domain-rules 禁掉 gfwlist 返回 IPv6 地址的，见 #370

**Comment by dengchan0416** [comment]
请问你的问题解决了吗？我跟你遇到一样问题

**Comment by daisuki4gh** [comment]
没有，后面还ROS了

dengchan0416 <notifications@github.com> 于 2020年11月16日周一 15:48写道：

**Comment by dengchan0416** [comment]
解决了



在 2020-11-16 22:58:02，"daisuki4gh" <notifications@github.com> 写道：

没有，后面还ROS了

dengchan0416 <notifications@github.com> 于 2020年11月16日周一 15:48写道：

**Comment by pymumu** [comment]
Which installation package file?

The /var/run/ path is used by most linux.
/run/ is used by some latest linux.
