### ISSUE TITLE
希望软路由里可以批量添加dns

### ISSUE THREAD

**Issue by jiatianxa** [pymumu/smartdns#362]
**需求
希望软路由里的可以加入批量添加dns，添加完再修改都可以的。因为每次都逐条添加太麻烦了。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息
openwrt

**Comment by pymumu** [comment]
直接在自定义页面写配置项就可以了。
