### ISSUE TITLE
当speed-check-mode设置为none时，缓存查询结果

### ISSUE THREAD

**Issue by rampageX** [pymumu/smartdns#364]
**问题现象**  
如果使用 `speed-check-mode none` 关闭测速，则缓存功能也随即失效。

**运行环境**
1. 固件型号  

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

设计上是这样？如果是，应该在文档中做出说明。

**Comment by pymumu** [comment]
关闭测速的缓存支持，还没完成。

**Comment by PHCSJC** [comment]
测速默认是关闭的吧？那是不是默认就是不缓存的？

**Comment by Alion548** [comment]
> 关闭测速的缓存支持，还没完成。

关闭测速功能，ipset 配置也没有生效

**Comment by zhaibin18** [comment]
> > 关闭测速的缓存支持，还没完成。
> 
> 关闭测速功能，ipset 配置也没有生效

确实是这样，麻烦在测试设置为none的情况也让ipset生效。

**Comment by Alion548** [comment]
关闭测速功能，ipset生效功能挺重要的，希望作者能提高下该功能的实现优先级
