### ISSUE TITLE
请教梅林改固件如何添加上游DNS

### ISSUE THREAD

**Issue by ohhhyy** [pymumu/smartdns#365]
首先感谢作者的无私奉献，让大家用上这么好的东西。

我用的是网件R8500刷梅林改固件，成功安装后不知道该如何添加上游DNS，找到smartdns.conf后对比配置参数也是一头雾水，网上找了其他人分享的文件也不敢替换，怕不兼容。
请教大家怎么添加上游DNS，谢谢了

**Comment by ohhhyy** [comment]
另外请问下路由器设置里面【LAN》DNS Server】和【WAN》DNS 服务器】需要修改为路由器地址么？

**Comment by pymumu** [comment]
按照readme中华硕路由器的安装方式安装。

**Comment by ohhhyy** [comment]
> 按照readme中华硕路由器的安装方式安装。
> 对应的配置文件在/opt/etc/smartdns/smartdns.conf
> 配置项可以看smartdns.conf中的帮助，或readme中的帮助。

谢谢回复，今天已经看明白添加过了，NSLOOKUP也只返回一个IP，不过感觉加速效果不明显，是不是需要在路由器设置里设置LAN或者WAN的DNS地址？

**Comment by pymumu** [comment]
看Readme中的FAQ

**Comment by ohhhyy** [comment]
已测试无需设置WAN LAN的DNS

**Comment by jojolfy** [comment]
> 已测试无需设置WAN LAN的DNS

你好，请问梅林固件是怎么安装smartdns的？我只在entware中看到有，安装后不知道咋弄，可以帮忙指导下不？
