### ISSUE TITLE
请求支持设置测速超时时间

### ISSUE THREAD

**Issue by LoliLin** [pymumu/smartdns#367]
**需求应用场景**
本人在境内外均布设了 smartdns 服务器以便于境内科学上网的可靠性，中间使用 greendns 进行分流
当请求境外域名 DNS 时，smartdns 国外会很快返回结果，而 smartdns 国内会在测速时卡在 GFW 返回的 IP 上导致 greendns 会等待国内 DNS 后返回结果，使其返回时间延长到 300ms~，严重影响上网体验

**建议的方案**
提供测速超时时间选项，建议默认值在 50~100ms 之间，其中测速超时的可直接返回所有查询到的 DNS 结果，由客户端浏览器进行检测

**设备信息**
1. 设备信息（CPU，厂家）  
Intel

2. 固件信息
 Ubuntu 18.04 x86_64

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/issues/234
