### ISSUE TITLE
为什么用了smartdns，解锁网易就运行不了

### ISSUE THREAD

**Issue by feifan1113** [pymumu/smartdns#368]
**问题现象**  
解锁网易无法运行，能否设置163.com白名单 不走smartdns

**运行环境**
1. 固件型号  斐讯N1

![image](https://user-images.githubusercontent.com/57245399/74701155-cf729900-5240-11ea-96ab-e2ee7e2268f7.png)

**Comment by pymumu** [comment]
不清楚，分析一些此软件的日志把。
