### ISSUE TITLE
DOT支持TLS hello么？ 

### ISSUE THREAD

**Issue by Masstone** [pymumu/smartdns#369]
**需求应用场景**
请描述需求应用的场景和方式。
我用的红鱼 个人定制DNS（个人字段.d.rubyfish.cn），在smartdns上配置了DOT之后，不能起到相关的作用

DNS个性化服务的实现：
就是 TLS 的 SNI 扩展，当 TLS 创建连接时，客户端的 TLS Hello 里会带上域名，给服务器，让服务器决定用什么证书来通信，这样 webserver 才能做到一个 IP 上支持多个域名的站点

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
看配置参数帮助
