### ISSUE TITLE
还是来建议增加以下tcp端口监听。

### ISSUE THREAD

**Issue by cjjdaq** [pymumu/smartdns#37]
某些场景下的确需要用到监听tcp端口。希望作者能增加此功能。

**Comment by fonlan** [comment]
查TCP端口的我一直有个疑问，SmartDns只是一个DNS Server，并不知道客户端实际连的哪个TCP端口，毕竟不是所有DNS请求的客户端都是要连接目标的80或者443端口，所以如果Smart DNS用TCP测速到底该用哪个端口来测？

**Comment by pymumu** [comment]
现在是通过80端口测速的。只要80端口有响应，不管是链接成功，还是拒绝，都算测速。

现在测速是先ping，ping全部不通的情况下才使用tcp 80端口测速。

**Comment by pymumu** [comment]
支持TCP查询的代码已经发布，可以获取验证。

**Comment by cjjdaq** [comment]
@pymumu 升级了并未监听tcp端口，依然只有udp端口，还需要特殊配置？

**Comment by pymumu** [comment]
默认配置没启用。
openwrt的话，页面配置，其他情况，增加如下配置项
bind-tcp [::]:53
