### ISSUE TITLE
怎么设置部分解析不测速呢？

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#370]
server 114.114.114.114
server 119.29.29.29

server-tcp 8.8.8.8 -group gfwlist -exclude-default-group
server-tcp 1.1.1.1 -group gfwlist -exclude-default-group

conf-file /etc/smartdns/gfwlist.conf

我的配置是上面这样的，我希望gfwlist这个解析结果不要测速，因为走代理可能不准确，这个怎么设置呢？谢谢！

**Comment by Auska** [comment]
利用domain-rules
例子： domain-rules /www.example.com/ -speed-check-mode none

**Comment by PHCSJC** [comment]
@Auska gfwlist里好几千个域名，该怎么写呢？

**Comment by onion83** [comment]
下载转换脚本

```
wget https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh -O gfwlist2dnsmasq.sh -O gfwlist2dnsmasq.sh

chmod +x gfwlist2dnsmasq.sh
```

修改 290 行

```
sort -u $DOMAIN_FILE | $SED_ERES 's#(.+)#domain-rules /\1/ -nameserver free -speed-check-mode none -address \#6#g' > $CONF_TMP_FILE
```
输出到文件
```
./gfwlist2dnsmasq.sh -o gfwlist.conf
```

**Comment by PHCSJC** [comment]
@onion83 明白了，感谢，就是要放5000多条记录到配置文件里，感觉好恐怖。

另外，请教一下，如果我访问google，smartdns解析后收到了2个IP，此时smartdns会先测速再返回给客户端吗？那如果由于IP不通，测速失败呢？会怎么处理呢？

**Comment by onion83** [comment]
生成的文件其实不需要管它直接用 conf-file 包含进来即可，不需要全堆在 smartdns.conf 文件里面

> conf-file /etc/smartdns/gfwlist.conf

smartdns 设计的原则，只会返回一个`理论最快`的IP，如果结果既有 A 也有 AAAA 且配置使用了 `dualstack-ip-selection no` 就会返回两个：IPv4 一个 IPv6 #361 有讨论

至于 `理论最快` 的定义，我觉得还有讨论空间 #114 不过新上的 domain-rules  功能，已经可以满足 90% 使用场景了.

**Comment by tufu9441** [comment]
> 下载转换脚本
> 
> ```
> wget https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh -O gfwlist2dnsmasq.sh -O gfwlist2dnsmasq.sh
> 
> chmod +x gfwlist2dnsmasq.sh
> ```
> 
> 修改 290 行
> 
> ```
> sort -u $DOMAIN_FILE | $SED_ERES 's#(.+)#domain-rules /\1/ -nameserver gfwlist -speed-check-mode none -address \#6#g' > $CONF_TMP_FILE
> ```
> 
> 输出到文件
> 
> ```
> ./gfwlist2dnsmasq.sh -o gfwlist.conf
> ```

很奇怪，我经过反复测试，利用这个方法给所有gfwlist域名添加了address #6参数之后，观看youtube的速度会下降为原来的一半，复原后又恢复正常，但通过speedtest.net测速的结果基本一样，不知道该怎么理解这个现象，难道是双栈优选后ipv6的访问效果会比ipv4好那么多？
