### ISSUE TITLE
domain-rules 如何配置

### ISSUE THREAD

**Issue by xlighting2017** [pymumu/smartdns#371]
domain-rules 如果同一个域名，要同时写多个参数， 是要分几行， 还是可以合并？

例如
`
domain-rules /qq.com/ -speed-check-mode tcp:80,tcp:443,ping -nameserver 114.114.114.114
`
还是
`domain-rules /qq.com/ -speed-check-mode tcp:80,tcp:443,ping
`
`domain-rules /qq.com/ -nameserver 114.114.114.114`

**Comment by pymumu** [comment]
第一种
但第一种nameserver配置不正确，nameserver配置参考单独的nameserve选项

**Comment by blog2i2j** [comment]
pymumu, 请问如下写法正确吗?
domain-rules /qq.com/ -nameserver /qq.com/114.114.114.114, -ipset /qq.com/chn

这个qq.com要重复写这么多次吗? 有没有简洁的写法?

**Comment by pymumu** [comment]
domain-rules /qq.com/ -nameserver group
 -ipset chn

仔细看readme
