### ISSUE TITLE
命令行opkg安装luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk有报错

### ISSUE THREAD

**Issue by zlowly** [pymumu/smartdns#372]
**问题现象**  
命令行opkg安装luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk报错

**运行环境**
1. 固件型号  
Mercury MW4530R v1
2. 固件版本
OpenWrt 19.07.1 r10911-c155900f66 / LuCI openwrt-19.07 branch git-20.046.57886-0da47ff

**重现步骤**
1. 用scp将release 29下载的luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk上传到路由器的/tmp目录
2. 在路由器上用opkg命令安装：
root@OpenWrt:/tmp# opkg install /tmp/luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk
Installing luci-app-smartdns (1.2020.02.20-0202) to root...
Configuring luci-app-smartdns.
//usr/lib/opkg/info/luci-app-smartdns.postinst: .: line 2: can't open '/etc/uci-defaults/50_luci-smartdns': No such file or directory
Collected errors:
 * wfopen: /etc/uci-defaults/50_luci-smartdns: Stale file handle.
但在Luci界面已可以正常操作smartdns菜单，opkg也可以查看到软件包已安装完。
root@OpenWrt:/tmp# opkg info luci-app-smartdns
Package: luci-app-smartdns
Version: 1.2020.02.20-0202
Depends: libc, smartdns
Status: install user installed
Architecture: all
Installed-Time: 1582216863

**Comment by crackerfly** [comment]
装错了版本，请仔细阅读下载页说明，装另一个

**Comment by zlowly** [comment]
下载页说明的是"仅19.07之后版本适用，19.07之前版本请使用compat版本"，按我理解我的19.07.1应该就是装luci-app-smartdns.xxxxxxxx.xxxx.all.ipk，而18.06.x和更早才是装compat版本，对吗？。

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/releases/download/Release29/luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk
