### ISSUE TITLE
发布的ipk在openwrt-imagebuilder工具中不能正确编制索引

### ISSUE THREAD

**Issue by zlowly** [pymumu/smartdns#373]
**问题现象**  
发布的ipk在openwrt-imagebuilder工具中，使用./scripts/ipkg-make-index.sh生成Packages时会出错。

**运行环境**
1. 型号	Mercury MW4530R v1
2. 固件版本	OpenWrt 19.07.1 r10911-c155900f66 / LuCI openwrt-19.07 branch git-20.046.57886-0da47ff
**重现步骤**
1. 将ipk软件包（luci-app-smartdns.1.2020.02.20-0202.all-luci-all）放在openwrt-imagebuilder目录下mypackages中
2. 运行ipkg-make-index.sh生成 Packages

~/openwrt-imagebuilder/mypackages ❯ PATH=$PATH:../staging_dir/host/bin ../scripts/ipkg-make-index.sh . > Packages
Generating index for package ./luci-app-shadowsocks-libev_git-20.048.32085-85a6f07-1_all.ipk
Generating index for package ./luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk
tar: ./control.tar.gz: Not found in archive
tar: Exiting with failure status due to previous errors

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

如果查看正常的ipk包，可以看到打包时开头是带了'.'
❯ tar tzf luci-app-shadowsocks-libev_git-20.048.32085-85a6f07-1_all.ipk
./debian-binary
./data.tar.gz
./control.tar.gz
而 luci-app-smartdns则是没有的。
❯ tar tzf luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk
control.tar.gz
data.tar.gz
debian-binary
虽然这并不影响直接安装ipk，但如果用openwrt-imagebuilder自己生成固件的话，就得自己拆包重新打包，比较麻烦。

另外ipk包里还有个很小的问题，但没什么影响，就不另新开issue，就是control文件里面有两个Installed-Size。
Package: luci-app-smartdns
Version: 1.2020.02.20-0202
Depends: libc, smartdns
Source: feeds/luci/applications/luci-app-smartdns
Section: luci
Architecture: all
Installed-Size: 1040
Description:  A smartdns server module
Installed-Size: 100554
我看了似乎是luci/control/control里面本来就有一行Installed-Size: 1040，但luci/make.sh里又直接echo追加了一行Installed-Size。建议去掉control原本的那行一行Installed-Size，或者将echo改用sed。

**Comment by EdiTurn** [comment]
本体的预编译 ipk 也受 '.' 的影响，无法在 Image Builder 中被索引到。
修了 luci 的，本体没修。

**Comment by edison0354** [comment]
@pymumu 如LS所说，最新的本体还是有问题，方便的时候能修一下么？谢谢！
