### ISSUE TITLE
关闭测速功能（speed-check-mode none）出现问题

### ISSUE THREAD

**Issue by Alion548** [pymumu/smartdns#374]
大家好，反馈测速功能关闭问题：
配置 bind [::]:53 -no-speed-check 或 speed-check-mode none时，出现以下问题：
1. 缓存、address、nameserver、ipset 配置不生效；

**Comment by Alion548** [comment]
当关闭测速功能时，ipset行为建议和dnsmasq一致（将所有查询到的结果添加到ipset）

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/issues/364#issuecomment-589617692
