### ISSUE TITLE
使用一段时间后无法打开网页

### ISSUE THREAD

**Issue by thinkpack** [pymumu/smartdns#375]
使用win10 1909的wsl，安装win下的smartdns。使用半天或者10来个小时后，浏览器无法打开任何网页，更换不同内核的浏览器依然无法打开网页。在终端中，可以ping通网址，也可以正常游戏和下载，唯一就是打不开网页。查看日志，显示类似connect 119.29.29.29 failed, Invalid argument错误。这个时候，只能卸载smartdns，然后修改dns，禁用再启用网络，才能上网，而仅仅修改dns是无法再次上网的。这个是配置有问题还是什么？

附上wsl日志
[smartdns.log](https://github.com/pymumu/smartdns/files/4236086/smartdns.log)
smartdns配置文件
[smartdns_conf.txt](https://github.com/pymumu/smartdns/files/4236090/smartdns_conf.txt)

**Comment by rampageX** [comment]
server-tcp 和 server-tls 几乎全部是错的。国内 DNS 没几个支持 TCP 的，TLS 也不是那么写的。

**Comment by zlowly** [comment]
server-tcp 223.5.5.5
server-tcp 223.6.6.6
server-tcp 119.29.29.29
server-tcp 218.201.4.3
server-tcp 114.114.114.114
这几个，用dig +vc测试过TCP,，只有223.5.5.5，223.6.6.6，114.114.114.114有查询响应，119.29.29.29和 218.201.4.3是拒绝连接。

**Comment by thinkpack** [comment]
那如何修改？只写server 不写tcp和tls那些吗？主要是为何使用半天多以后才会出现这个问题？我先试试只写server dns 其他不配置看看，看会不会遇到问题。

**Comment by thinkpack** [comment]
确实是多修改了tcp tls配置。单独配置server就行了。
