### ISSUE TITLE
可否为ipset添加域名组的支持

### ISSUE THREAD

**Issue by zlowly** [pymumu/smartdns#376]
**需求应用场景**
对于一些有大量域名（例如某gXXlist有5k行）需要既设置nameserver由设置ipset的情况，能否让ipset直接支持域名组，从而使得配置文件可以减半？

**建议的方案**
对于象以下这样的配置
nameserver /domain1/group
nameserver /domain2/group
nameserver /domain3/group
......
之后接同样类似的大量ipset
ipset /domain1/ipset
ipset /domain2/ipset
ipset /domain3/ipset
......
可以有两种替代方案：
1、直接添加域名组支持，例如
ipset /@group/ipset
2、直接增加命令，例如
groupipset /group/ipset

**Comment by pymumu** [comment]
使用domain-rules
