### ISSUE TITLE
缓存大小的单位 和 功能 求教

### ISSUE THREAD

**Issue by wyjtm** [pymumu/smartdns#378]
外行人提几个问题排版有点乱，格式套用不上，请有空看下解答下

问题1
关于dns缓存问题

我看到有提问的回答是
https://github.com/pymumu/smartdns/issues/75
他问的是文件大小

插件上提示是 【缓存DNS的结果，缓存大小，配置零则不缓存】

你回答的是 《域名个数，每个cache占用605字节》
是指 按域名个数，每个占用605字节 然后自己计算设置多少个域名个数，乘以605，在设置大小吗？

还是单纯的和 openwrt里的提示一样 【缓存的 DNS 条目数量（最大 10000，0 表示不缓存）（默认150）】的含义相同呢？

如果是条目的话能不能改成 【缓存DNS结果的条目数量，配置零则不缓存】
或者直接在后面写上【单位：条目数量】
TTL同样【单位：秒】

换个方式写介绍清楚或者写上单位，可以让外行小白搜了各种百科后知道怎么大概填，毕竟不是人人都是内行dalao嘛，我想你本意也是帮助大家

“比如之前加的群里有人问【域名TTL最小值 默认300】有的人说你教程是写10-30分钟 这里写的300 需不需要改成10-30............我之前用过其他工具跟他说应该是秒单位，换算一下试试”

问题2
【开启域名预获取功能】
【过期缓存服务功能】

这两个可以和需要同时开启吗？ 看主页教程介绍似乎是 有了预获取，就不需要过期缓存了，因为不产生过期？

问题3
smartdns开启缓存后，openwrt自带的缓存配置需要设置为0不缓存吗？
还是直接使用【重定向53端口到SmartDNS】？

还是不管它？————重复二次缓存？

问题4
可否推荐几个可用的httpsDNS
测试了https://cloudflare-dns.com/dns-query 和 https://dns.google/dns-query

朋友在他的机场服务器上说可用
但我在自家设置好 发现不起作用，河南联通
他说可能是被墙了？

我的设置 例如
https://cloudflare-dns.com/dns-query   443端口   https

**Comment by wyjtm** [comment]
字体怎么会有大有小.....算了...

**Comment by pymumu** [comment]
1. 记录条数。
2. 可以，但不建议。直接开启过期缓存即可。
3. 可以，但配置与否没有差别。
4. 自行查找。

其他，请看readme的描述。

**Comment by liyiranlab** [comment]
感觉DNS网站会自动屏蔽smartdns的doh请求

**Comment by yyysuo** [comment]
过期缓存有TTL吗？是否受设置的TTL参数影响呢？

**Comment by pymumu** [comment]
可以设置最大的过期TTL， 配置参数`serve-expired-ttl`，默认是0，表示不过期。
