### ISSUE TITLE
ipset 无作用

### ISSUE THREAD

**Issue by datong** [pymumu/smartdns#379]
**问题现象**  
使用 domain-rules 时 ipset 无作用。

```
nameserver /domain.com/china
ipset /domain.com/chnroute
domain-rules /domain.com/ -speed-check-mode none
```
 
删除domain-rules ，而有作用.

**运行环境**
1. 固件型号  
最新

**Comment by zlowly** [comment]
我觉得是speed-check-mode参数影响了ipset。我这里设置address.conf
>domain-rules /google.com/ -nameserver group -ipset myset
>domain-rules /zuobiao.me/ -speed-check-mode none -nameserver group -ipset myset
然后
`$ipset flush`
`$dig google.com`
`$dig zuobiao.me`
`$ipset list`
可以看到dig能正确解析两个域名到ip，但只有google.com的ip被加入到了ipset里。

**Comment by foxconndmd** [comment]
当前版本禁用speed-check-mode后ipset 缓存 ttl修改无效。

**Comment by serafwind** [comment]
> 当前版本禁用speed-check-mode后ipset 缓存 ttl修改无效。

所以要如何使用才能让它正常？它有没有日志可以导出看看呢？
我感觉用了之后好像还没有LEAN大自带turbo acc的pdnsd的加速 打开网页和图片响应快
不知道是跟LEAN的固件有冲突还是什么
另外IPV6的选项那些一勾选就没法运行

**Comment by foxconndmd** [comment]
> > 当前版本禁用speed-check-mode后ipset 缓存 ttl修改无效。
> 
> 所以要如何使用才能让它正常？它有没有日志可以导出看看呢？
> 我感觉用了之后好像还没有LEAN大自带turbo acc的pdnsd的加速 打开网页和图片响应快
> 不知道是跟LEAN的固件有冲突还是什么
> 另外IPV6的选项那些一勾选就没法运行

等作者更新支持

**Comment by kousyougi** [comment]
需要這個功能+1
透過vpn查詢DNS, 還沒加入ipset的ip, 有些路由走vpn、有些直連, 測速會不準。
目前在境外上游也裝smartdns，在上游先測速過後，只返回一個ip。暫時解決這個問題。

PS: 發現smartdns只收到一個IP好像還是會測速，送一個ping出去。

**Comment by pymumu** [comment]
使用最新版本看看，如还有问题reopen issue，贴上日志
