### ISSUE TITLE
建议增加类似chinadns的功能

### ISSUE THREAD

**Issue by kkkgo** [pymumu/smartdns#38]
功能：
对返回的dns结果进行判断，如果该结果位于指定的ip列表内（比如china ip list），则信任位于该指定的ip列表内的dns供应商（比如114 dns）提供的结果；如果返回的dns结果不在指定的ip列表内，则信任该指定的ip列表外的dns供应商的结果（比如本地的dnscrypt-proxy）

**Comment by lixuy** [comment]
顺便如果能内建dnscrypt-proxy的功能就好啦，这样就可以少装两个程序XD

**Comment by lixuy** [comment]
https://github.com/chengr28/Pcap_DNSProxy

**Comment by pymumu** [comment]
不会支持dnscrypt，会支持TLS。

至于信任，还是不信任，没有合适的判断标准。如果通过IP段判断，那么将丧失速度优势，也不一定合适的。

**Comment by pymumu** [comment]
目前TLS已经支持，后面还会支持https，在配合域名分流，已经能保证查询结果的正确性。
所以不需要类似chinadns的机制了。
