### ISSUE TITLE
smartdns支持正则匹配吗?

### ISSUE THREAD

**Issue by blog2i2j** [pymumu/smartdns#380]
**需求应用场景**
想匹配类似*.google.*的域名, 这样可以大幅度减少条目. smartdns支持regex或者类似这样通配方式吗?
没有的话, 能请求加入吗?

**建议的方案**
dnsmasq有人给做了个dnsmasq-regex, https://github.com/lixingcong/dnsmasq-regex

**Comment by pymumu** [comment]
不会支持正则式，正则式会导致软件性能急剧下降。
