### ISSUE TITLE
luci页面无法打开

### ISSUE THREAD

**Issue by wxs-dev** [pymumu/smartdns#381]
**问题现象**  

按照步骤安装luci-app-smartdns.1.2020.02.20-0202.all-luci-all.ipk、smartdns.1.2020.02.20-0202.mipsel-openwrt-all.ipk，打开路由器页面出错，如下：

/usr/lib/lua/luci/controller/smartdns.lua:25: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/smartdns.lua:25: in function 't'
	/usr/lib/lua/luci/dispatcher.lua:465: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**运行环境**
主机名 | OpenWrt
主机型号 | GeHua GHL-R-001
架构 | MediaTek MT7621 ver:1 eco:3 x 4
固件版本 | OpenWrt R20.2.15 / LuCI Master (git-20.051.42827-3e80fef)
内核版本 | 4.14.169

**Comment by pymumu** [comment]
安装compat版本。

**Comment by wxs-dev** [comment]
安装compat版本，也是出现相同的结果
