### ISSUE TITLE
speed-check-mode设置为none后返回所有结果

### ISSUE THREAD

**Issue by zhaibin18** [pymumu/smartdns#383]
**需求应用场景**
smartdns设置speed-check-mode none，也跟测速一样返回一个结果，比如：
dig @192.168.1.1 www.taobao.com 返回
www.taobao.com.         396     IN      CNAME   www.taobao.com.danuoyi.tbcache.com.
www.taobao.com.danuoyi.tbcache.com. 1597 IN A   60.28.226.41
dig @123.123.123.123 www.taobao.com 返回
www.taobao.com.         201     IN      CNAME   www.taobao.com.danuoyi.tbcache.com.
www.taobao.com.danuoyi.tbcache.com. 30 IN A     125.39.135.240
www.taobao.com.danuoyi.tbcache.com. 30 IN A     125.39.135.241
www.taobao.com.danuoyi.tbcache.com. 30 IN A     60.28.226.41

**建议的方案**
设置speed-check-mode none返回所有结果

**设备信息**
1. 华硕AC66U-B1，kernel 2.6.36.4 armv7l ASUSWRT-Merlin

2. 固件信息
原版梅林ASUSWRT-Merlin

**smartdns版本**

1.20200216-1619

**Comment by rampageX** [comment]
反对。要么做个开关。

**Comment by rampageX** [comment]
反对，逻辑上说不通。
或者做个单独的开关。

**Comment by zhaibin18** [comment]
> 反对，逻辑上说不通。
> 或者做个单独的开关。

反正都不测速了，返回所有的结果应该是预期，有测速要求的才返回最快的，不知道这个逻辑哪里说不通。

**Comment by zhaibin18** [comment]
我可能搞错了，目前的逻辑已经是这样了。
