### ISSUE TITLE
dns server process failed

### ISSUE THREAD

**Issue by TesleYoung** [pymumu/smartdns#389]
**问题现象**  
简要描述问题出现的现象
日志一段时间重复打印
tlog(TLOG_ERROR, "dns server process failed.");
且该段时间域名解析服务不可用
**运行环境**
1. 固件型号  
K3官改使用梅林optware

2. 运营商  
四川电信
**重现步骤**
1. 上游DNS配置。  
61.139.2.69
223.6.6.6
223.5.5.5
2. 访问的域名。  
不定域名,不定时出现

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

tlog(TLOG_ERROR, "dns server process failed.");

**Comment by pymumu** [comment]
可以忽略。也可以增加打印，打开debug日志，提供更多信息分析原因。
