### ISSUE TITLE
SmartDns CPU占用100%

### ISSUE THREAD

**Issue by fonlan** [pymumu/smartdns#39]
在不支持科学上网的服务器上配置server-tcp 8.8.8.8后log里会每两秒钟打印一个[ERROR][dns_client.c:1023] send query to 8.8.8.8 failed, Broken pipe。时间长了CPU占用就100%了。

**Comment by pymumu** [comment]
有完整日志发一下，如果能再次出现的话，开一下INFO日志。

另外，这个是x86_64版本吗？

**Comment by pymumu** [comment]
更新一下最新版本看看。

**Comment by fonlan** [comment]
用了两天了，还正常
