### ISSUE TITLE
Systemd service unit doesn't follow FHS guideline. 请遵守 FHS 路径

### ISSUE THREAD

**Issue by LEXUGE** [pymumu/smartdns#390]
**问题现象**  
The systemd service doesn't follow the right [FHS guideline](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html)
See also the [patch on Arch](https://git.archlinux.org/svntogit/community.git/tree/trunk/systemd.patch?h=packages/smartdns)
Also the `install.sh` is not in a standard FHS form, **please** write a makefile instead.
Here is an [example](https://github.com/medusalix/xow/blob/a35977eaada7b6cf8191e47e9f6bf5473b9ee18a/Makefile)

systemd unit 没有遵守 [FHS guideline](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s13.html)
可以看 [Arch的补丁](https://git.archlinux.org/svntogit/community.git/tree/trunk/systemd.patch?h=packages/smartdns)来修改
此外`install.sh`也不遵守 FHS , **请** 写一个 makefile.
比如 [这样](https://github.com/medusalix/xow/blob/a35977eaada7b6cf8191e47e9f6bf5473b9ee18a/Makefile)

**运行环境**
1. 固件型号  
All

2. 运营商  
All

**重现步骤**
1. 上游DNS配置。  
N/A
2. 访问的域名。  
N/A

**Comment by pymumu** [comment]
1. /var/run和/run
   /run目录并不是所有系统都支持，因为历史原因/var/run支持度更好。
   因为smartdns涉及到多个平台，所以pid文件目录使用兼容性好的/var/run目录。
2. /usr/bin和/usr/sbin
   smartdns因为需要root权限才能正确运行，所以放到/usr/sbin是正确的。

**Comment by LEXUGE** [comment]
>     1. /var/run和/run
>        /run目录并不是所有系统都支持，因为历史原因/var/run支持度更好。
>        因为smartdns涉及到多个平台，所以pid文件目录使用兼容性好的/var/run目录。
> 
>     2. /usr/bin和/usr/sbin
>        smartdns因为需要root权限才能正确运行，所以放到/usr/sbin是正确的。

所以有可能维护多个 service 文件吗？不同平台可以按照不同需求安装。

**Comment by jtojnar** [comment]
1. It would be nice if the `runtimedir` was configurable during installation. Proper Makefile such as https://github.com/medusalix/xow/blob/a35977eaada7b6cf8191e47e9f6bf5473b9ee18a/Makefile would help.
2. It is not the issue that it is being installed to `/usr/sbin` instead of `/usr/bin` but rather that it is installed to `$PREFIX/usr/sbin` instead of `$PREFIX/sbin` (`$PREFIX` defaults to `/usr` on some UNIX systems but not everywhere.) Perhaps you are meaning to use [`DESTDIR`](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) instead of `PREFIX`.
3. Another thing the Arch patch fixes is `StartLimitBurst` and `StartLimitIntervalSec` belonging to [`Unit` section](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval), not [`Service` section](https://www.freedesktop.org/software/systemd/man/systemd.service.html).

**Comment by pymumu** [comment]
这个暂时没必要把。
比如debian的：
```shell
root@raspberrypi:/lib/systemd/system# grep -n "PID" . -R
./rc.local.service:23:GuessMainPID=no
./rpc-statd.service:16:PIDFile=/var/run/rpc.statd.pid
./ssh.service:12:ExecReload=/bin/kill -HUP $MAINPID
./openvpn@.service:17:PIDFile=/run/openvpn/%i.pid
./openvpn@.service:19:ExecReload=/bin/kill -HUP $MAINPID
./postfix@.service:12:GuessMainPID=no
./samba-ad-dc.service:10:PIDFile=/var/run/samba/samba.pid
./samba-ad-dc.service:14:ExecReload=/bin/kill -HUP $MAINPID
./dhcpcd.service:8:PIDFile=/run/dhcpcd.pid
./rc-local.service:23:GuessMainPID=no
./smbd.service:10:PIDFile=/var/run/samba/smbd.pid
./smbd.service:15:ExecReload=/bin/kill -HUP $MAINPID
./nmbd.service:10:PIDFile=/var/run/samba/nmbd.pid
./nmbd.service:13:ExecReload=/bin/kill -HUP $MAINPID
./netatalk.service:11:GuessMainPID=no
./netatalk.service:13:PIDFile=/var/lock/netatalk
./netatalk.service:14:ExecReload=/bin/kill -HUP $MAINPID
./usbmuxd.service:7:PIDFile=/var/run/usbmuxd.pid
``
都是/var/run目录。

StartLimitBurst和StartLimitIntervalSec会修正，也会提供makefile

**Comment by LEXUGE** [comment]
> 这个暂时没必要把。
> 比如debian的：
> 
> ```shell
> root@raspberrypi:/lib/systemd/system# grep -n "PID" . -R
> ./rc.local.service:23:GuessMainPID=no
> ./rpc-statd.service:16:PIDFile=/var/run/rpc.statd.pid
> ./ssh.service:12:ExecReload=/bin/kill -HUP $MAINPID
> ./openvpn@.service:17:PIDFile=/run/openvpn/%i.pid
> ./openvpn@.service:19:ExecReload=/bin/kill -HUP $MAINPID
> ./postfix@.service:12:GuessMainPID=no
> ./samba-ad-dc.service:10:PIDFile=/var/run/samba/samba.pid
> ./samba-ad-dc.service:14:ExecReload=/bin/kill -HUP $MAINPID
> ./dhcpcd.service:8:PIDFile=/run/dhcpcd.pid
> ./rc-local.service:23:GuessMainPID=no
> ./smbd.service:10:PIDFile=/var/run/samba/smbd.pid
> ./smbd.service:15:ExecReload=/bin/kill -HUP $MAINPID
> ./nmbd.service:10:PIDFile=/var/run/samba/nmbd.pid
> ./nmbd.service:13:ExecReload=/bin/kill -HUP $MAINPID
> ./netatalk.service:11:GuessMainPID=no
> ./netatalk.service:13:PIDFile=/var/lock/netatalk
> ./netatalk.service:14:ExecReload=/bin/kill -HUP $MAINPID
> ./usbmuxd.service:7:PIDFile=/var/run/usbmuxd.pid
> ``
> 都是/var/run和/run同时存在。
> 
> StartLimitBurst和StartLimitIntervalSec会修正，也会提供makefile
> ```

确实可以但是 systemd 其实是偏向 `/run` 的，`/var/run` 在那里是 link。我们觉得还是应该可配置这样下游有更多选择。

**Comment by jtojnar** [comment]
The issue with using `/var/run` is not at runtime since, as you point out, most distros provide a symlink. The issue occurs when Linux distributions check packages for best practices using automated linters. For them, using deprecated path in the service file is an error.

But it is not priority for us as NixOS does not do that at the moment. I only suggested it because it might be useful for others.

**Comment by pymumu** [comment]
@jtojnar 
many platforms  are supported by smartdns,  so smartdns uses `/var/run`  for compatibility.   
For example, openwrt does not have the `/run`  directory. In this case, the service cannot be started.

what is the best soloution, any suggestion?

**Comment by LEXUGE** [comment]
> @jtojnar
> many platforms are supported by smartdns, so smartdns uses `/var/run` for compatibility.
> For example, openwrt does not have the `/run` directory. In this case, the service cannot be started.
> 
> what is the best soloution, any suggestion?

My suggestion would be let runtimedir be configurable or provide two files one is standard and another one is legacy for compatibility.

**Comment by jtojnar** [comment]
Yes, I would suggest making it configurable in the makefile.

For example in [the one I linked](https://github.com/medusalix/xow/blob/a35977eaada7b6cf8191e47e9f6bf5473b9ee18a/Makefile), they have `.service.in` template file and replace `@BINDIR@` placeholder to produce the final `.service` file. Your build script could do the same for `SBINDIR` and `RUNSTATEDIR` (see the [GNU directory variable standard](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html).
