### ISSUE TITLE
使用SmartDNS后好像所有的网页都以https的方式打开了

### ISSUE THREAD

**Issue by liyiranlab** [pymumu/smartdns#392]
**需求应用场景**
请描述需求应用的场景和方式。
使用SmartDNS后好像所有的网页都以https的方式打开，请问使用Smartdns还有意义没有？因为我觉得现在打开网页好像全变成https开头的网页，即使用了SmartDNS打开网页瞬间反应也好慢。请问SmartDNS对Https开头的网页有加速作用吗？
**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  
7621 联发科
2. 固件信息
r3g lede编译固件

**Comment by pymumu** [comment]
https和DNS没有关系。
smartdns是DNS解析，https是通讯协议。
smartdns解决的是域名解析和路径问题，无关https协议。
