### ISSUE TITLE
 在openwrt官方版，为什么又找不到luci-app-smartdns了？

### ISSUE THREAD

**Issue by shenzt68** [pymumu/smartdns#393]
如题。
想把smartdns集成在固件里，现在找不到luci-app-smartdns，怎么办呢？

**Comment by pymumu** [comment]
https://github.com/pymumu/luci-app-smartdns

**Comment by shenzt68** [comment]
https://github.com/pymumu/luci-app-smartdns
这个没升级吧！
另外，这个在大屌lean的lede里编译不过啊

**Comment by pymumu** [comment]
这个是配套19.07的，你可以github搜索看看。
否则就直接使用独立的安装包，用imagebuild打包进去。

**Comment by FoxDring** [comment]
> 这个是配套19.07的，你可以github搜索看看。
> 否则就直接使用独立的安装包，用imagebuild打包进去。

大佬请问如何自己根据最新代码编译smartdns和luci-app-smartdns

**Comment by pymumu** [comment]
https://github.com/pymumu/luci-app-smartdns
参考
