### ISSUE TITLE
smartdns的指定特定域名ip地址无法对内网ip生效

### ISSUE THREAD

**Issue by ikelvingo** [pymumu/smartdns#394]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号
openwrt 19.07  

2. 运营商  

**重现步骤**
1. 上游DNS配置。
启用	DNS服务器名称	DNS服务器IP	DNS服务器端口	协议类型	

dnspod
119.119.119.29
53

ali
223.5.5.5
53

cnnic
1.2.4.8
53

rubyfish
dns.rubyfish.cn
853

local
15.192.252.188
53

baidu
180.76.76.76
53

114
114.114.114.114
53

360
101.226.4.6
53

  

2. 访问的域名。  

个人域名：xxx.xxx.me
该域名通过ddns获取外网ip指向某内网服务器（101.xxx.xxx.xxx），因此希望通过smartdns直接将内网内的访问指向该服务器内网地址（192.168.xxx.xxx）。
结果发现在smartdns配置完毕后，该dns解析的拦截不成功，该域名无法解析到任何地址。

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
请按照readme的步骤配置。

**Comment by ikelvingo** [comment]
> 请按照readme的步骤配置。

确定配置成功。而且如果我用其它地址，如1.2.3.4或者111.111.111.111等外部地址，全部可以拦截成功，但是内网地址如10/172/192开头的，全部会拦截失效，已经反复验证，使用release28版本。

**Comment by pymumu** [comment]
smartdns没启用重定向的情况下，不会拦截DNS请求，你最好确认是否有其他服务重定向了dns

**Comment by ikelvingo** [comment]
确定拦截成功，只是当指定IP是内网保留地址时，不会返回内网地址，如果指定外网地址，则可以正确生效。

**Comment by wxs-dev** [comment]
> 确定拦截成功，只是当指定IP是内网保留地址时，不会返回内网地址，如果指定外网地址，则可以正确生效。

如果是用Dnsmasq转发到samrtdns的，请关闭重绑定保护(DHCP/DNS -> 重绑定保护)

**Comment by liuqi0270** [comment]
> 确定拦截成功，只是当指定IP是内网保留地址时，不会返回内网地址，如果指定外网地址，则可以正确生效。

你没有拦截成功是重定向保护了，或者其他dns起作用。按你现在的配置，拦截一个随便的公网地址也会不生效的。

建议整系统排查。

**Comment by raofeng** [comment]
> > 确定拦截成功，只是当指定IP是内网保留地址时，不会返回内网地址，如果指定外网地址，则可以正确生效。
> 
> 如果是用Dnsmasq转发到samrtdns的，请关闭重绑定保护(DHCP/DNS -> 重绑定保护)

遇到同样的问题，就是这样解决的。点赞！
