### ISSUE TITLE
Multiple ipsets supoort for one domain

### ISSUE THREAD

**Issue by yujincheng08** [pymumu/smartdns#395]
**需求应用场景**
I wanna use [ss-rules](https://github.com/openwrt/packages/blob/openwrt-19.07/net/shadowsocks-libev/files/ss-rules) for smart forward of shadowsocks. It creates some ipsets for this purpose, among which `ss_rules_dst_forward` and `ss_rules6_dst forward` for ipv4 and ipv6 respectively could be utilized by smartdns. So I wrote rules like:
```
nameserver /google.com/oversea # use oversea group for this domain
ipset /google.com/ss_rules_dst_forward # for ipv4
ipset /google.com/ss_rules6_dst_forward # for ipv4
```
However it didn't work as expected. Only `ss_rules6_dst_forward` took effect and I can only had ipv6 traffic forwarded.

**建议的方案**
The resolved result can be added to all ipsets associated with this domain.
I scan the code. Maybe changing `domain_rule.rules[DOMAIN_RULE_IPSET]->ipset_name` to an array is helpful.

**设备信息**
1. 设备信息（CPU，厂家）  
x86 soft router
2. 固件信息
Openwrt 19.07. Latest ver of smartdns compiled by myself.

**Comment by yujincheng08** [comment]
Oh sorry. I read the code carefully and it seems to be a linked list.

**Comment by pymumu** [comment]
Will add this feature later, and consider the following configuration.
```
# only ipv4 or ipv6
ipset /www.example.com/dns
# for ipv4
ipset /www.example.com/#4:dns
# for ipv6
ipset /www.example.com/#6:dns
# for both ipv4, ipv6
ipset /www.example.com/#4:dns4,$6dns6
```
