### ISSUE TITLE
请教domain-rules的写法

### ISSUE THREAD

**Issue by blog2i2j** [pymumu/smartdns#397]
没有搜索到domain-rules的具体写法. 想请问一下, 以下的写法正确吗?

domain-rules /qq.com/ -nameserver /qq.com/114.114.114.114, -ipset /qq.com/chn

这样qq.com要写很多次, 有没有简洁的写法?

**Comment by CyberKoo** [comment]
domain-rules /qq.com/ -nameserver GROUP -ipset chn
大概是这样

**Comment by blog2i2j** [comment]
如果不使用group, 直接使用114.114.114.114呢? 把group替换成114就可以了吧?

**Comment by CyberKoo** [comment]
> 如果不使用group, 直接使用114.114.114.114呢? 把group替换成114就可以了吧?

不可以，根据 https://github.com/pymumu/smartdns#配置参数 中的介绍，nameserver后面只能使用分组。
nameserver中的介绍写的是 

> 指定域名使用server组解析

**Comment by 523860169** [comment]
```
server 8.8.8.8 -group foreign
domain-rules /google.com/ -address #6 -nameserver foreign -ipset proxylist

```

**Comment by blog2i2j** [comment]
domain-rules /dl.google.com/ -nameserver "-" -ipset "-"
这上面的带引号的2个-表示什么意思?

**Comment by 523860169** [comment]
不要带引号，具体规则参考相应的原设定，比如nameserver部分就看nameserver的说明，ipset就看ipset的说明
具体例子就比如
`domain-rules /google.com/ -address #6 -nameserver foreign -ipset proxylist`
google全站不查询ipv6的dns记录，通过foreign的dns组查询，结果添加到proxylist的ipset组
domain-rules /dl.google.com/ -nameserver - -ipset -
排除dl.google.com，不使用其他规则设定的nameserver规则和ipset规则

**Comment by blog2i2j** [comment]
感谢523860169, 讲得浅显易懂, 终于明白怎么使用了. 非常感谢!
