### ISSUE TITLE
必须卸载旧版再装新版吗？可不可以提供个配置备份功能啊。

### ISSUE THREAD

**Issue by czdj2000** [pymumu/smartdns#398]
不然每次都要重新配置 好麻烦啊！

**Comment by 523860169** [comment]
一直都是直接升级安装，配置文件也不会被覆盖，可能是你的操作问题

**Comment by kmxzq** [comment]
在OpenWRT 19.07下报错啦
`root@OpenWrt:/tmp# opkg remove luci-app-smartdns
Removing package luci-app-smartdns from root...
root@OpenWrt:/tmp# opkg install luci-app-smartdns.1.2020.02.25-2212.all-luci-com
pat-all.ipk
Installing luci-app-smartdns (1.2020.02.25-2212) to root...
Configuring luci-app-smartdns.
uci: Entry not found
uci: Entry not found
root@OpenWrt:/tmp# uname -a
Linux OpenWrt 4.14.171 #0 SMP Mon Feb 24 18:25:12 2020 mips GNU/Linux
root@OpenWrt:/tmp#
`
两个uci Entry不在，导致无法启动smartdns

**Comment by pymumu** [comment]
使用最新版本。
注意选择相应固件版本的luci。如果安装错误，卸载软件包重启路由器。
