### ISSUE TITLE
增加linux x64版下载。

### ISSUE THREAD

**Issue by cjjdaq** [pymumu/smartdns#4]
装在vps上用来给路由做国外上级。

**Comment by pymumu** [comment]
已经增加

**Comment by cjjdaq** [comment]
作者，tcp监听还是有必要的，比如说吧，装在国外vps上，路由上肯定用tcp来连接vps上的smartdns，udp被污染，不然还要套一层支持tcp的dnsmasq或者pdnsd什么的，你说是不是。
