### ISSUE TITLE
Openwrt默认DNS无法使用分组

### ISSUE THREAD

**Issue by Masstone** [pymumu/smartdns#400]
**问题现象**  
简要描述问题出现的现象
想通过分组做分流，第二DNS启用并配置使用fallback分组，
第二DNS没问题，只查询了fallback分组
但发现发给第一DNS始终会查询所有分组，无法纯粹的分开
手动修改/etc/smartdns/smartdns.conf给第一DNS加-group参数
不起作用，/tmp/etc/smartdns/smartdns.conf始终会无法添加上-group参数
所以希望可以在luci端给默认dns增加分组的配置。
谢谢大佬的付出

**运行环境**
1. 固件型号  
OpenWrt 19.07.1 r10911-c155900f66 / LuCI openwrt-19.07 branch git-20.057.55219-13dd17f
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  

server-name smartdns
bind :6053
cache-size 0
rr-ttl-min 600
rr-ttl-max 3000
log-size 64K
log-num 1
log-level error
bind :6553  -no-speed-check -group fallback -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa -no-dualstack-selection
server-tls 1.1.1.1:853  -tls-host-verify cloudflare-dns.com -group fallback 
server-tls 1.0.0.1:853  -tls-host-verify cloudflare-dns.com -group fallback 
server-tls 8.8.8.8:853  -tls-host-verify dns.google -host-name dns.google -group fallback 
server-tls 8.8.4.4:853  -tls-host-verify dns.google -host-name dns.google -group fallback 
server-tls 47.96.179.163:853  -tls-host-verify dns.rubyfish.cn -group fallback 
server-tls 134.175.134.112:853  -tls-host-verify *.rubyfish.cn 
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by yujincheng08** [comment]
As a workaround, add `-group` to `/etc/init.d/smartdns#287,289`.

**Comment by pymumu** [comment]
```
[-exclude-default-group]：将DNS服务器从默认组中排除
```
对上游服务器配置上述参数

**Comment by yujincheng08** [comment]
@pymumu luci interface does not have this option.

**Comment by pymumu** [comment]
`额外的服务器参数`  加到这个配置框

**Comment by Masstone** [comment]
> `额外的服务器参数` 加到这个配置框

好的。如果多个额外参数就用空格分割么
