### ISSUE TITLE
Wildcard TLS verification

### ISSUE THREAD

**Issue by yujincheng08** [pymumu/smartdns#401]
**问题现象**  
https://dns.twnic.tw/dns-query is one DoH server, its TLS certificate is `*.twnic.tw`, which smartdns seems not to consider it's valid as the hostname is `dns.twnic.tw` 

**运行环境**
1. 固件型号  
Openwrt 19.07
2. 运营商  
ChinaNet
**重现步骤**
1. 上游DNS配置。  
```
server-https 210.17.9.228/dns-query -tls-host-verify dns.twnic.tw -http-host dns.twnic.tw -host-name dns.twnic.tw
```
2. 访问的域名。  
www.google.com.hk

**信息收集** 
```
[2020-03-01 21:20:05,712][ INFO][     dns_client.c:2080] server 210.17.9.228 CN is invalid, peer CN: *.twnic.tw, expect CN: dns.twnic.tw
```

**Comment by pymumu** [comment]
you should use 
```
-tls-host-verify *.twnic.tw
```

**Comment by yujincheng08** [comment]
@pymumu yes, I used this as a workaround but I still think it's a bug.

**Comment by pymumu** [comment]
已经修正。
