### ISSUE TITLE
release 30 mipsel openwrt 无法使用

### ISSUE THREAD

**Issue by kalagxw** [pymumu/smartdns#402]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

/usr/sbin/smartdns: line 1: syntax error: unexpected "("
cpu ar71xx

**Comment by yujincheng08** [comment]
As I know, ar71xx is `mips` instead of `mipsel`.

**Comment by kalagxw** [comment]
you are right!
