### ISSUE TITLE
SSR Plus 配合 Smartdns国外网站可以解析出最快的一个IP，国内站点无效

### ISSUE THREAD

**Issue by Feb17** [pymumu/smartdns#404]
**问题现象**  
SSR Plus + Smartdns，国外网站可以解析出最快的一个IP，国内站点无效。。

**运行环境**
OpenWrt R9.11.23

中国电信

**重现步骤**
1. 上游DNS配置。  
![image](https://user-images.githubusercontent.com/7236132/75690480-e2c04280-5cdd-11ea-8746-b77415652788.png)

![image](https://user-images.githubusercontent.com/7236132/75690543-01bed480-5cde-11ea-9267-1328329b411f.png)

![image](https://user-images.githubusercontent.com/7236132/75690559-0aafa600-5cde-11ea-9bbd-1eac5acdded5.png)

2. 访问的域名。  

![image](https://user-images.githubusercontent.com/7236132/75690638-2ca92880-5cde-11ea-9441-0d0e35236541.png)

**信息收集**  

![image](https://user-images.githubusercontent.com/7236132/75691137-cd97e380-5cde-11ea-821b-3ed9d9233353.png)

**Comment by pymumu** [comment]
没和此类软件做个测试，请自行检查其他软件配置。
