### ISSUE TITLE
强制域添加到IP 可不可以同一个域名 预先添加几个ip 自动选择最快

### ISSUE THREAD

**Issue by sxml** [pymumu/smartdns#406]
**需求应用场景**
请描述需求应用的场景和方式。

强制域添加到IP 同域名 预先添加几个ip 自动选择丢包率 ping低 最快的
cloudflare 节点选择
address /www.example.com/1.2.3.4
address /www.example.com/5.6.7.8

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息
OpenWrt R20.2.15

**Comment by pymumu** [comment]
done
