### ISSUE TITLE
并不起作用,两条ip信息,和系统本地的dns结果一致

### ISSUE THREAD

**Issue by QQ3516969** [pymumu/smartdns#407]
**问题现象**  
简要描述问题出现的现象
并不起作用,两条ip信息,和系统本地的dns结果一致 ping值依然很高
**运行环境**
斐讯K3 拨号adsl
1. 固件型号  

OpenWrt R20.2.15 mod by huah0235 v1.5 / LuCI Master (git-20.058.13156-2faf063)
--

2. 运营商  
联通或者电信
**重现步骤**
1. 上游DNS配置。  
作为dnsmasq上有服务器
2. 访问的域名。 
nslookup www.baidu.com

**信息收集**

**Comment by tty228** [comment]
![111111111111111111](https://user-images.githubusercontent.com/33397881/75774383-dfcf5b80-5d8a-11ea-887d-2215b4837a4d.png)

我觉得你设置有问题

**Comment by QQ3516969** [comment]
[image: FireShot Capture 001 - OpenWrt - SmartDNS - LuCI - 10.10.10.13.png]
[image: FireShot Capture 002 - OpenWrt - DHCP_DNS - LuCI - 10.10.10.13.png]
[image: QQ截图20200313165227.jpg]
*按照别人教程按部就班做的,不知道起没起作用,看你的延迟都个位数了,我是山东联通200兆,*
*主路由K3   10.10.10.13 还有一个N1当的旁路由(10.10.10.10)翻墙*
*下面是旁路游LAN设置,主路由关闭DHCP,有时间就回,没时间就不用问我了,谢谢*
[image: FireShot Capture 003 - OpenWrt - 接口 - LuCI - 10.10.10.10.png]


tty228 <notifications@github.com> 于2020年3月3日周二 下午8:09写道：

**Comment by pymumu** [comment]
please feel free to reopen this issue.
