### ISSUE TITLE
SmartDNS错误

### ISSUE THREAD

**Issue by Yofo-me** [pymumu/smartdns#409]
> ` 固件版本： OpenWRT koolswhare mod V2.33 r12074-007caa48d1 `

>  ` 系统： X86_64 `

> ` 正常安装 x64位的smartDNS IPK 和 luci-app IPK后，在web管理后台点击 服务->SmartDNS却提示错误 (如图所示）  `

![用不了](https://user-images.githubusercontent.com/55388087/75847370-eb1d9800-5e19-11ea-8a4f-3e94498602f4.png)

> ` 请问怎么修复 `

**Comment by pymumu** [comment]
卸载安装的，再安装配套的。

仔细看release中的说明。
