### ISSUE TITLE
对DOH上游服务器支持有问题

### ISSUE THREAD

**Issue by lnc1995** [pymumu/smartdns#410]
在上游服务器中单独配置DOH类型的服务器，SmartDNS会停止运行。
如红鱼DNS,GeekDNS。

**Comment by pymumu** [comment]
1. 升级最新版本。
2. 如果配置的地址是域名，那么smartdns需要自解析，在无法自解析的情况下，就会退出。考虑配置一个IP地址的上游。
3. 发日志。
