### ISSUE TITLE
如何设置服务器优先级？

### ISSUE THREAD

**Issue by lnc1995** [pymumu/smartdns#411]
比如有些DNS服务可以提供广告过滤等高级功能，那么想要使得该服务器作为最高优先级，只要该服务器有返回结果就采用，只有该服务器没返回结果时再采用其他服务器。

speed-check-mode none

这个配置可以实现这样的场景吗？

**Comment by pymumu** [comment]
目前smartdns不支持，要过滤广告，只能配置规则给smartdns。
