### ISSUE TITLE
可否让gfwlist里的域名不解析ipv6？

### ISSUE THREAD

**Issue by b08240** [pymumu/smartdns#413]
smartdns配合passwall用起来很好用，但是开启ipv6的dns解析后，因为翻墙服务器不支持ipv6，所以google和youtube解析出的ipv6地址无法打开。
我是用gfwlist的方式翻的，想请问一下怎么可以让gfwlist里面的域名不解析ipv6地址？
补充一下，按理说smartdns会自动优选速度最快的服务器ip，而google和youtube的ipv6地址却是无法连接的，那为什么会首先返回ipv6地址？

**Comment by pymumu** [comment]
配置force-AAAA-soa yes

**Comment by 1phalley** [comment]
我是推特图片视频走了ipv6直连，速度不算快，在smartdns的自定义设置里添加 address /twimg.com/#6  这样推特的视频和图片都不返回ipv6地址了。force-AAAA-soa yes会让所有ipv6都无法解析，稍有不便。这里回复一下希望能帮到有同样需求的人。

**Comment by onion83** [comment]
> 我是推特图片视频走了ipv6直连，速度不算快，在smartdns的自定义设置里添加 address /twimg.com/#6 这样推特的视频和图片都不返回ipv6地址了。force-AAAA-soa yes会让所有ipv6都无法解析，稍有不便。这里回复一下希望能帮到有同样需求的人。

`domain-rules /twimg.com/ -nameserver free -speed-check-mode none -address #6`

**Comment by hwangjunjie** [comment]
> 我是推特图片视频走了ipv6直连，速度不算快，在smartdns的自定义设置里添加 address /twimg.com/#6 这样推特的视频和图片都不返回ipv6地址了。force-AAAA-soa yes会让所有ipv6都无法解析，稍有不便。这里回复一下希望能帮到有同样需求的人。

经测试，这个方法在我这边能生效
ipv6全开，youtube是正常，但是netflex一直因为ipv6检测到大陆IP，导致不支持播放，在自定义设置里增加以下设置就正常了，还不影响原有ipv6功能
```
address /netflex.com/#6
address /nflxso.net/#6
address /nflxvideo.net/#6
```
