### ISSUE TITLE
什么时候出Window直接可用版本啊

### ISSUE THREAD

**Issue by wysnxzm** [pymumu/smartdns#414]
十分渴望!

**Comment by pymumu** [comment]
win10可以使用WSL
https://github.com/pymumu/smartdns#windows-10-wsl%E5%AE%89%E8%A3%85wsl-ubuntu
win10之前系统不会支持。

**Comment by wysnxzm** [comment]
> win10可以使用WSL
> https://github.com/pymumu/smartdns#windows-10-wsl%E5%AE%89%E8%A3%85wsl-ubuntu
> win10之前系统不会支持。

有意向出windows的客户端吗?可以开个投票看看?
