### ISSUE TITLE
/usr/lib/lua/luci/controller/smartdns.lua:25: attempt to call global 'view' (a nil value)

### ISSUE THREAD

**Issue by kl9800** [pymumu/smartdns#415]
**问题现象**  
安装以后，**页面**出现报错
1.opkg install smartdns.1.2020.02.25-2212.x86_64-openwrt-all.ipk
2.opkg install luci-app-smartdns.1.2020.02.25-2212.all-luci-all.ipk
报错以后换成
3.opkg install luci-app-smartdns.1.2020.02.25-2212.all-luci-compat-all.ipk
一样报错，报错如下  ↓↓↓↓↓↓↓↓↓↓
**/usr/lib/lua/luci/controller/smartdns.lua:25: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/smartdns.lua:25: in function 't'
	/usr/lib/lua/luci/dispatcher.lua:465: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>**

**运行环境**
1. 固件型号  
   OpenWrt R20.3.8 / LuCI Master (git-20.068.29105-b2cf61d)
2. 运营商  
    还没到这一步
**重现步骤**
1. 上游DNS配置。  
   还没到这一步
2. 访问的域名。  
   还没到这一步

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
lede请安装compat版本。
仔细阅读release中的注意事项。

**Comment by zhuceney** [comment]
compat版本安装后需要重启
