### ISSUE TITLE
首次回显正确，后续均被国外抢先回答的疑问。

### ISSUE THREAD

**Issue by zhaozhejun** [pymumu/smartdns#416]
目前见到大多数都是 国内写china，那实际可以随便写吗？？不涉及端口分开监听。。因为目前碰到  同时启用国内外dns
，例如nslookup www.baidu.com或者www.qq.com，，，附图百度。。
仅第一次返回国内ip，后续都被国外dns抢先解析了。实际ping的话，肯定延时大很多。
配置如下，国外没办法都被标注掉了。
新三主路由或者软旁路由，都是一个情况，哪里有问题吗？
bogus-nxdomain 218.30.64.194
bogus-nxdomain 106.75.67.118
speed-check-mode tcp:443,tcp:80,ping
server-https https://dns.alidns.com/dns-query  -group china  -blacklist-ip 
server  219.149.194.55 -blacklist-ip  -group china  -blacklist-ip 
server  140.143.226.193  -blacklist-ip -group office   -blacklist-ip 
server 119.29.29.29  -group china -blacklist-ip 
server-https https://i.233py.com/dns-query  -group office   -blacklist-ip
server 117.50.10.10  -group china   -blacklist-ip
server-https https://doh.360.cn/dns-query  -group china  -blacklist-ip 
#server-https https://dns.quad9.net/dns-query  -group office
#server-https https://cloudflare-dns.com/dns-query  -group office 
#server-https https://dns.nextdns.io/9ccef4  -group office
force-AAAA-SOA yes
配置仅后三个是office命名，前面都是命名的china，前面有偶尔office是后改的，但只要后三个启用，均被抢答。。
新配置如下，也不行
speed-check-mode tcp:443,tcp:80,ping
force-AAAA-SOA yes
server-https https://dns.alidns.com/dns-query  -group china -blacklist-ip -check-edns
server 119.29.29.29  -group china -blacklist-ip -check-edns
server-https https://i.233py.com/dns-query  -group out -blacklist-ip -check-edns
server 52.80.66.66  -group china -blacklist-ip -check-edns
server 211.141.16.99  -group china -blacklist-ip -check-edns
server-https https://doh.360.cn/dns-query  -group out -blacklist-ip -check-edns
server-https https://dns.quad9.net/dns-query  -group out -blacklist-ip -check-edns
server-https https://cloudflare-dns.com/dns-query  -group out -blacklist-ip -check-edns
server-https https://dns.nextdns.io/9ccef4  -group out -blacklist-ip -check-edns

![11111](https://user-images.githubusercontent.com/22097252/76371560-9d52e380-6375-11ea-9806-f1f03dd7f619.png)
![2222222](https://user-images.githubusercontent.com/22097252/76371972-fc652800-6376-11ea-8273-c34a7221ba5b.png)
![333333333](https://user-images.githubusercontent.com/22097252/76372474-7944d180-6378-11ea-99cb-d457801a3532.png)
图中103.235.X.X查询后是香港的，

**Comment by o0HalfLife0o** [comment]
当然可以

**Comment by tty228** [comment]
在国外DNS组，额外的服务器参数加入 [-exclude-default-group]
把国外组移出默认解析列表
