### ISSUE TITLE
【求助】梅林下SSR和SMART DNS有冲突

### ISSUE THREAD

**Issue by ohhhyy** [pymumu/smartdns#417]
**需求应用场景**
梅林下开启SMART DNS后SSR无法正常运行，GFW模式失效，白名单模式正常。

**建议的方案**

**设备信息**
1. 设备信息（CPU，厂家）  
网件R8500
2. 固件信息
梅林改380

开启SMART DNS后SSR的GFW模式无法正常运行，白名单模式正常。
智能网络卫士DNS FILTERING开启并开启ROUTER模式后才SSR正常工作，其他模式（包括no filtering和关闭DNS filtering）均无法正常工作。可开启router模式后nslookup查看smart dns又失效。
实在不知道该如何解决，请教该怎么办？

**Comment by pymumu** [comment]
没有经过验证，无法支持。
