### ISSUE TITLE
第二DNS与第一DNS是否共享同一个缓存？

### ISSUE THREAD

**Issue by Mosney** [pymumu/smartdns#418]
**问题现象**  

通过luci配置DNS1绑定`6053`作为国内DNS，DNS2绑定`7053`使用DoT/H作为国外DNS确保返回结果无污染，分别作为作为clash的DNS上游和fallback DNS上游。

观察到：
1. 如果先使用6053查询了受污染的域名，再通过7053端口查询会直接返回之前被污染的结果，猜测可能是因为共享DNS缓存结果导致的。
2. 先使用7053端口查询会被污染的域名，正常返回IP未污染；接下来用6053查询，返回结果是被污染的IP，这种情况下似乎两个DNS又不共享缓存了。然而随后再使用7053查询仍然返回之前被污染的结果，此时又跟现象1一样了。

**运行环境**
1. 固件型号  
OpenWrt 19.07.2
2. 运营商  
联通家宽 不存在DNS劫持

**重现步骤**

现象1.
```
; <<>> DiG 9.11.5-P4-5.1-Debian <<>> youtube.com @10.1.1.1 -p 6053 +noall +answer
;; global options: +cmd
youtube.com.		300	IN	A	31.13.77.55

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> youtube.com @10.1.1.1 -p 7053 +noall +answer
;; global options: +cmd
youtube.com.		300	IN	A	31.13.77.55

```

现象2. 

```

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> twitter.com @10.1.1.1 -p 7053 +noall +answer
;; global options: +cmd
twitter.com.		80	IN	A	104.244.42.1
twitter.com.		80	IN	A	104.244.42.129

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> twitter.com @10.1.1.1 -p 6053 +noall +answer
;; global options: +cmd
twitter.com.		300	IN	A	199.16.158.190

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> twitter.com @10.1.1.1 -p 7053 +noall +answer
;; global options: +cmd
twitter.com.		300	IN	A	199.16.158.190


```
**信息收集**  
log-level info
[smartdns.log](https://github.com/pymumu/smartdns/files/4310760/smartdns.log)

**Comment by pymumu** [comment]
使用IP黑名单。

**Comment by Mosney** [comment]
所以这两个DNS是使用同一个缓存么？

**Comment by Mosney** [comment]
IP黑名单来处理污染难以获得时下全面的污染IP段并且容易误伤

**Comment by Mosney** [comment]
我来解释一下这如果多个监听端口共享同一个缓存会有什么缺点：

相信SmartDNS的用户不仅是为了返回最快最优的IP，还有很大一部分是把它用作类似ChinaDNS的功能，分流查询避免被污染。
以我为例，我是将SmartDNS监听的两个端口作为[Clash](https://github.com/Dreamacro/clash)的DNS普通上游和fallback上游（并发查询这两个上游，普通DNS解析结果GeoIP为非CN的时候使用fallback结果），虽然clash本身的两种运作模式基本可以忽略DNS污染的影响，但还是存在漏网之鱼和污染后的负面影响。
如果这两个监听的端口共享同一个DNS缓存的话，第二DNS就没有意义了，按照最开始贴的测试结果来看SmartDNS大概率会缓存污染后的结果。

**Comment by Mosney** [comment]
目前第二DNS勾选跳过cache了，能解决上面我说的问题，就是可惜不能使用缓存了
