### ISSUE TITLE
请问如果在OPENWRT编译中添加SMARTDNS？

### ISSUE THREAD

**Issue by johnita-biubiu** [pymumu/smartdns#420]
原来OPENWRT有自带的，现在没有了，小白请问如何添加安装源？谢谢。

**Comment by pymumu** [comment]
用release中的安装包。

**Comment by johnita-biubiu** [comment]
谢谢回复，可是安装release中的安装包，每次新装都要安装一次ipk很麻烦，能不能直接在编译的时候git到，我git你的源，在编译的时候应该是安装进去了，但是没出现配置菜单。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nick Peng"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上11:18
收件人: "pymumu/smartdns"<smartdns@noreply.github.com&gt;; 
抄送: "187176802"<187176802@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pymumu/smartdns] 请问如果在OPENWRT编译中添加SMARTDNS？ (#420)





 
用release中的安装包。
 
&mdash;

**Comment by wmjlxl** [comment]
同样有需求，请 大大 搞搞能否实现呢？ 谢谢啦
