### ISSUE TITLE
解析规则匹配错误

### ISSUE THREAD

**Issue by ayalhw** [pymumu/smartdns#421]
**问题现象**  
简要描述问题出现的现象
对域名解析规则进行匹配时出现错误
定义或导入的规则中没有top的规则。但是blog.lhwcrt.top这个域名被匹配进china 组

**运行环境**
1. 固件型号  
Arch Linux

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

使用felixonmars提供的规则 https://github.com/felixonmars/dnsmasq-china-list

server 119.29.29.29 -group china -exclude-default-group
server 233.5.5.5 -group china -exclude-default-group
server-tcp 8.8.8.8
server-tcp 8.8.4.4
server-tls 8.8.8.8
server-tls 8.8.4.4
server-tls 1.0.0.1
server-tls 1.1.1.1
2. 访问的域名。  

blog.lhwcrt.top

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

[smartdns.log](https://github.com/pymumu/smartdns/files/4315455/smartdns.log)

我的配置
[smartdns.txt](https://github.com/pymumu/smartdns/files/4315458/smartdns.txt)

**Comment by pymumu** [comment]
smartdns的格式和dnsmasq有差异，不能直接用。具体看配置参数。

**Comment by ayalhw** [comment]
> smartdns的格式和dnsmasq有差异，不能直接用。具体看配置参数。

您可能被仓库名误导了……
我使用的是用这个仓库生成的smartdns规则……

[accelerated-domains.china.smartdns.txt](https://github.com/pymumu/smartdns/files/4321102/accelerated-domains.china.smartdns.txt)

**Comment by CyberKoo** [comment]
> > smartdns的格式和dnsmasq有差异，不能直接用。具体看配置参数。
> 
> 您可能被仓库名误导了……
> 我使用的是用这个仓库生成的smartdns规则……
> 
> [accelerated-domains.china.smartdns.txt](https://github.com/pymumu/smartdns/files/4321102/accelerated-domains.china.smartdns.txt)

配置文件中 57779 行 ``nameserver /top/china``
匹配了全部的top后缀

**Comment by ayalhw** [comment]
> > > smartdns的格式和dnsmasq有差异，不能直接用。具体看配置参数。
> > 
> > 
> > 您可能被仓库名误导了……
> > 我使用的是用这个仓库生成的smartdns规则……
> > [accelerated-domains.china.smartdns.txt](https://github.com/pymumu/smartdns/files/4321102/accelerated-domains.china.smartdns.txt)
> 
> 配置文件中 57779 行 `nameserver /top/china`
> 匹配了全部的top后缀

抱歉是我的问题
在此向您表示感谢
