### ISSUE TITLE
请问rr-ttl-min 后面的数字单位是秒吗。。

### ISSUE THREAD

**Issue by yeezylife** [pymumu/smartdns#422]
那按照“建议是超时时间设置在10～30分钟，避免服务器域名变化时，查询到失效域名。” 里说的，是不是设置rr-ttl-min 600 ~1800比较好。

**Comment by soffchen** [comment]
不懂的不要设就好了 默认设置帮你设好

**Comment by yeezylife** [comment]
> 不懂的不要设就好了 默认设置帮你设好

有一种被活捉的感觉。。我不是在另一个问题@的你么。。

**Comment by yeezylife** [comment]
> 不懂的不要设就好了 默认设置帮你设好

太小白的问题不能老逮着一个人问，人家有可能说会烦！所以我特地兵分两路，万万没想到！
