### ISSUE TITLE
想请教一下docker版smartdns的安装教程

### ISSUE THREAD

**Issue by Licolnlee** [pymumu/smartdns#425]
想在docker中安装smartdns，已经把smartdns的通用版本压缩包导入到docker镜像中，但是不知道有没有具体配置上的要求比如说配置目录这些是自动生成还是手动设置，希望作者能够指点一下方向，谢谢，有劳了。

**Comment by pymumu** [comment]
dockhub上应该有现成的镜像了

**Comment by Licolnlee** [comment]
> dockhub上应该有现成的镜像了
好的谢谢您，我去看看
