### ISSUE TITLE
经常解析到香港的IP

### ISSUE THREAD

**Issue by 2427237507** [pymumu/smartdns#426]
**问题现象**  
经常解析到香港的IP
阿里云部分CDN没有在我省移动铺设，导致他一度认为香港的IP是访问最快的，然而实际上该IP被Qos,当从延迟来看确实是最快的。
希望：能够引入/完善ECS功能或改变测速逻辑

**运行环境**
1. 固件型号  
K3C openwrt 15.05
2. 运营商  
移动
**重现步骤**
1. 上游DNS配置。  
转发谷歌DoH（ECS无法实现），阿里DoH，CloudFlare DoH
2. 访问的域名。  
g.alicdn.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
可以将对应的IP地址段加入ignore-ip列表。
