### ISSUE TITLE
Netflix走IPv6不走IPv4

### ISSUE THREAD

**Issue by yaott2020-666** [pymumu/smartdns#427]
**问题现象**  
netflix.com不想要IPv6解析
设置了
address /netflix.com/-6
address /netflix.net/-6
address /nflxext.com/-6
address /nflximg.net/-6
address /nflxso.net/-6
address /nflxvideo.net/-6
address /fast.com/-6
没用
**运行环境**
1. 固件型号  
Newifi D2
2. 运营商  
移动
**重现步骤**
1. 上游DNS配置。  

tls dns.rubyfish.cn
223.5.5.5
208.67.220.222:443
180.76.76.76
tls dns.google:853
tls 1.0.0.1

2. 访问的域名。  
 netflix.com

名称:    netflix.com
Addresses:  2a01:578:3::22f6:3f00
          2a01:578:3::36c2:57d0
          2a01:578:3::364c:3c27
          2a01:578:3::22fa:3d7d
          2a01:578:3::22fb:b596
          2a01:578:3::369a:5167
          2a01:578:3::364d:1824
          2a01:578:3::364c:9f12
          52.210.221.246
          52.211.42.108
          34.246.137.168
          34.250.3.119
          34.246.46.249
          52.208.209.205
          52.214.145.233
          52.211.94.145

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by jack2598** [comment]
```
address /netflix.com/#6 #这样不解析ipv6地址
address /netflix.com/#4 #这样不解析ipv4地址
```
