### ISSUE TITLE
openwrt-mipsel版本无法使用DOT

### ISSUE THREAD

**Issue by Freedomzasf** [pymumu/smartdns#429]
**问题现象**  
openwrt下新版本无法使用DOT

**运行环境**
1. 固件型号  
R20.3.11
2. 运营商  
中国电信
**重现步骤**
1. 上游DNS配置。  
8.8.8.8@853
2. 访问的域名。  
all

**信息收集**  
更新了新版本之后走tls的全部失效，tcp和udp正常，旧版能用tls，卸载重装后继承了原来的设置

**Comment by 873578156** [comment]
是的，我在使用的时候，发现tls和https在openwrt上回导致进程崩溃。

**Comment by pymumu** [comment]
用的什么版本，有配置域名作为上游地址吗？

**Comment by Licolnlee** [comment]
是的，新路由3 用的最新版25的mipsle版本smartdns，使用的alidns，360，233py和红鱼dns提供的dot或者doh都无法正常使用，国外google，adguard等的doh或者dot也无法使用，自己的旁路由使用的arm版smartdns可以正常解析。

**Comment by shenzhonghua** [comment]
这个我遇到过，代码貌似没问题，我自己下下来交叉编译出来的版本就是好的

**Comment by Freedomzasf** [comment]
> 用的什么版本，有配置域名作为上游地址吗？

用的最新版，没有配置上游，就是用的smartdns做主DNS

**Comment by pymumu** [comment]
无相关硬件，无法验证，可以尝试自行编译

**Comment by Licolnlee** [comment]
> 无相关硬件，无法验证，可以尝试自行编译

update：misple新三将smartdns加入自编译后使用的doh和dot是正常的，但是有部分会报错在log文件中（arm版相同配置没有任何报错，但是如果使用release中的ipk会出现无法使用dot和doh的情况。

**Comment by wonpn** [comment]
openwrt DOH确实无法使用，

**Comment by pymumu** [comment]
可以发下日志看看什么错误

**Comment by Licolnlee** [comment]
[2020-04-17 14:14:40,870][ERROR][     dns_client.c:287 ] host = dns.google, port = 853, type = 2, protocol = 0
[2020-04-17 14:14:40,870][ERROR][     dns_client.c:2771] add pending DNS server dns.google failed

貌似是不支持域名格式的dot...切换成ip的dot就没有报错log

**Comment by pymumu** [comment]
如果配置的服务器是域名，是需要解析后才能使用的。

smartdns会利用
1. 已经配置IP地址的服务器进行延迟解析。
2. 利用设备自身的dns解析。

如果两种都失败，那么此服务器配置，将不能正确工作。
所以，必须要保证上述两种情况有一种能满足。

**Comment by pymumu** [comment]
please feel free to reopen this issue.
