### ISSUE TITLE
问下大佬们，ip黑名单用不用加

### ISSUE THREAD

**Issue by stztao** [pymumu/smartdns#430]
已经设置好国内外分流，高级设置里的ip黑名单填不填好？对解析速度有提升吗，可否提供一下比较实用的名单，感谢

**Comment by liuqi0270** [comment]
> 已经设置好国内外分流，高级设置里的ip黑名单填不填好？对解析速度有提升吗，可否提供一下比较实用的名单，感谢

这个问题比较基本了，想要让梯子找到最快的节点，还是设置比较好，网上搜一下，有很多相关的内容
