### ISSUE TITLE
is:issue is:大神们，我设置分组，分国外和国内DNS，用PassWall连了香港的节点，国外返回ip并不是最优的，返回美国的，什么原因呢？

### ISSUE THREAD

**Issue by qbbqccqdd** [pymumu/smartdns#431]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by cnclg** [comment]
设置国外的dns最好走代理，那样可以返回走vps返回的ip,这样应该有比较好的速度。

**Comment by 70599** [comment]
那你直接在你那个香港节点上查询你说的域名，看看返回了哪里的IP
