### ISSUE TITLE
chkconfig: command not found

### ISSUE THREAD

**Issue by anlexN** [pymumu/smartdns#432]
**问题现象**  
无法确定是否正确安装smartdns

我的服务器是opensuse
![image](https://user-images.githubusercontent.com/8686739/77217004-dea77800-6b59-11ea-98d7-66181cda7d38.png)
![image](https://user-images.githubusercontent.com/8686739/77217008-ecf59400-6b59-11ea-85de-20303dff4377.png)
opensuse没看到有chkconfig

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/issues/322

**Comment by anlexN** [comment]
我看了#322, 但是opensuse 怎么安装chkconfig?

**Comment by pymumu** [comment]
please free free to reopen this issue.
