### ISSUE TITLE
求问smartdns支持ddwrt么

### ISSUE THREAD

**Issue by ShadowEmbrace** [pymumu/smartdns#433]
最近的网实在太烂，忍不住要开始折腾了。
华硕66u_b1刷了DD-WRT v3.0-r37305 std (10/10/18)，Kernel version: Linux 4.4.159 #4001 SMP Wed Oct 10 09:28:16 CEST 2018 armv7l
ddwrt可以用openwrt的方法装smartdns吗？
谢谢

**Comment by pymumu** [comment]
使用optware的安装包即可

**Comment by ShadowEmbrace** [comment]
> 
> 
> 使用optware的安装包即可

谢谢

**Comment by abolast** [comment]
> 使用optware的安装包即可

发现最新的ddwrt已经内置smartdns，就是不知道是基于哪个版本
![image](https://user-images.githubusercontent.com/48117390/202918649-fa5d4480-81f6-4c03-82e2-7833996b1ac9.png)
