### ISSUE TITLE
luci-app-smartdns加上黑名单订阅

### ISSUE THREAD

**Issue by fonlan** [pymumu/smartdns#434]
**需求应用场景**
很多人拿AdGuardHome和SmartDns比，我感觉SmartDns缺少的就是一个黑名单规则订阅功能，加上的话就能完全取代AdGuardHome了。

**建议的方案**
最简单的应该是通过luci-app-smartdns的修改加入订阅规则功能，通过添加cron任务实现定时更新

**设备信息**
1. 设备信息（CPU，厂家）  
x86-64软路由

2. 固件信息
OpenWrt

**Comment by pymumu** [comment]
smartdns只提供工具，不提供内容。

**Comment by fonlan** [comment]
> smartdns只提供工具，不提供内容。

这我知道，所以只是希望提供一个自动更新订阅的功能，否则每次都要手动把规则转换填进来太麻烦不是，只需要luci界面加个填写订阅连接的地方，对SmartDns本身的功能没有影响。

**Comment by pymumu** [comment]
可以在路由器的crontab中添加脚本。

**Comment by fonlan** [comment]
对，添加周期性获取规则就够了，不过最好是能同时支持hosts格式和AdGuardhome格式的规则，自适应。本身不需要带任何规则。

**Comment by pymumu** [comment]
最新版本增加了相关能力的支持。
