### ISSUE TITLE
smartdns在官方master分支固件下dns解析地址不一致导致不能运行！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [pymumu/smartdns#435]
1、smartdns在官方master分支固件下不能运行，init里的dns解析地址与官方master分支的dns解析地址不一致导致！修改smartdns里的解析地址为官方默认的解析地址，仍不能正常。。。
2、smartdns启动后再关闭，dnsmasq的dns转发列表和忽略解析文件均不会释放。。。

**Comment by pymumu** [comment]
不清楚你说额官方是什么。smartdns已经推送到openwrt的官方package中。
直接获取openwrt的package即可。

https://github.com/openwrt/packages/tree/master/net/smartdns

**Comment by zxlhhyccc** [comment]
> 不清楚你说的官方是什么。smartdns已经推送到openwrt的官方package中。
> 直接获取openwrt的package即可。
> 
> https://github.com/openwrt/packages/tree/master/net/smartdns

我是用的你推送到openwrt的package中的包，我看了一下，编译出来的init解析地址仍然是旧的解析地址，即：18.06、19.07默认的解析地址，而openwrt官方的dns解析地址是新的，导致不兼容，见截图！
18.06、19.07的解析导致是：/tmp/resolv.conf.auto
官方openwrt的msater分支的解析地址是：/tmp/resolv.conf.d/resolv.conf.auto
两个解析地址不一致，即使smartdns能运行，但会导致路由不间断性断网，而且非常频繁！
你源码init的dns解析地址：
![image](https://user-images.githubusercontent.com/45259624/77245361-fb76a500-6c58-11ea-85e1-cd28c4981b25.png)
而官方openwrt的master分支的解析地址是：
![image](https://user-images.githubusercontent.com/45259624/77245407-590af180-6c59-11ea-9494-5464f4d24244.png)

**Comment by pymumu** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/4364922/smartdns.zip)

替换这个文件到/etc/init.d/smartdns
替换后执行
chmod +x /etc/init.d/smartdns

**Comment by zxlhhyccc** [comment]
> [smartdns.zip](https://github.com/pymumu/smartdns/files/4364922/smartdns.zip)
> 
> 替换这个文件到/etc/init.d/smartdns
> 替换后执行
> chmod +x /etc/init.d/smartdns

经测试，替换后给了权限仍不能运行，但dnsmasq的dns转发列表和忽略解析列表能正常释放。。。
![image](https://user-images.githubusercontent.com/45259624/77246847-0f74d380-6c66-11ea-9e60-c0634425015d.png)

**Comment by pymumu** [comment]
你的luci-app是什么版本？

你这看上去是没触发启动。
执行：
/etc/init.d/smartdns start

或安装release连接中的luci看看。

**Comment by zxlhhyccc** [comment]
> 你的luci-app是什么版本？
> 
> 你这看上去是没触发启动。
> 执行：
> /etc/init.d/smartdns start
> 
> 或安装release连接中的luci看看。

又出现不能运行的现象。。。

**Comment by pymumu** [comment]
please feel free to reopen this issue.
