### ISSUE TITLE
安装Luci-app包后无法访问路由器配置页面，报错详情

### ISSUE THREAD

**Issue by kevin2zhu** [pymumu/smartdns#436]
**问题现象**  
将软件底包和Luci-app配置包上传到路由进行安装，先安装底包再安装luci包后再次刷新路由器配置页面就报如下错：
    /usr/lib/lua/luci/controller/smartdns.lua:25: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/smartdns.lua:25: in function 't'
	/usr/lib/lua/luci/dispatcher.lua:465: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**运行环境**
1.系统为: X86 OpenWrt R20.3.19 / LuCI Master (git-20.079.47035-c242d65)
   内核为: 4.19.108

2.安装的包为:
  smartdns.1.2020.02.25-2212.x86-openwrt-all.ipk;
  luci-app-smartdns.1.2020.02.25-2212.all-luci-all.ipk

**Comment by FantasyGmm** [comment]
最新源代码编译的佐大的LEDE，内核4.9，同款报错，同款架构

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/issues/384
