### ISSUE TITLE
/usr/lib/lua/luci/controller/smartdns.lua:25: attempt to call global 'view' (a nil value)

### ISSUE THREAD

**Issue by MADAOMu** [pymumu/smartdns#438]
**问题现象**  
op登录后显示 无法进入主页
/usr/lib/lua/luci/controller/smartdns.lua:25: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/smartdns.lua:25: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:612: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:261: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>
×

**运行环境**
1. 固件型号  N1安装op

2. 运营商  

**重现步骤**
op选择上传luci-app-smartdns.1.2020.02.25-2212.all-luci-all.ipk
smartdns.1.2020.02.25-2212.arm-openwrt-all.ipk
分别点击安装 刷新后显示上述

请问如何解决呢 谢谢

**Comment by pymumu** [comment]
看历史issue。
