### ISSUE TITLE
在WSL2环境下安装会报错

### ISSUE THREAD

**Issue by a1623382** [pymumu/smartdns#439]
install: 正在创建目录'/etc/smartdns'
'src/smartdns' -> '/usr/sbin/smartdns'
'etc/smartdns/smartdns.conf' -> '/etc/smartdns/smartdns.conf'
'etc/default/smartdns' -> '/etc/default/smartdns'
已删除'/etc/init.d/smartdns'
'etc/init.d/smartdns' -> '/etc/init.d/smartdns'
System has not been booted with systemd as init system (PID 1). Can't operate.
System has not been booted with systemd as init system (PID 1). Can't operate.
dirname: 缺少操作数
Try 'dirname --help' for more information.
System has not been booted with systemd as init system (PID 1). Can't operate.
System has not been booted with systemd as init system (PID 1). Can't operate.
dirname: 缺少操作数
Try 'dirname --help' for more information.
System has not been booted with systemd as init system (PID 1). Can't operate.
Install smartdns failed.

**Comment by pymumu** [comment]
镜像要使用systemd启动。

或者直接使用docker。

**Comment by rickllyxu** [comment]
> 镜像要使用systemd启动。
> 
> 或者直接使用docker。

其实是程序没有判断到当前运行环境是 `wsl` 或者说没有正确判断当前环境是否支持 `systemd`.
稍加修改即可：
修改 下载的gz包里的install文件中的 `init_dir()` 函数。
修改为：
```bash
init_dir()
{
        local ID=`id -u`
        if [ $ID -ne 0 ]; then
                echo "Please run as root."
                return 1
        fi

        SMARTDNS_CONF_DIR=$PREFIX/etc/smartdns
        SMARTDNS_INIT_DIR=$PREFIX/etc/init.d
        # check if the system support systemctl?
        systemctl >/dev/null 2>&1
        ISSYSTEMD="$?"
        # Running under WSL (Windows Subsystem for Linux)?
        # cat /proc/version | grep Microsoft >/dev/null 2>&1;
        if [ $ISSYSTEMD -ne 0 ]; then
                ISSYSTEMD=1
                ISWSL=0
        fi

        cd $INST_DIR
}
```

**Comment by a1623382** [comment]
我试了一下，成功了，谢谢

**Comment by yeezylife** [comment]
> > 镜像要使用systemd启动。
> > 或者直接使用docker。
> 
> 其实是程序没有判断到当前运行环境是 `wsl` 或者说没有正确判断当前环境是否支持 `systemd`.
> 稍加修改即可：
> 修改 下载的gz包里的install文件中的 `init_dir()` 函数。
> 修改为：
> 
> ```shell
> init_dir()
> {
>         local ID=`id -u`
>         if [ $ID -ne 0 ]; then
>                 echo "Please run as root."
>                 return 1
>         fi
> 
>         SMARTDNS_CONF_DIR=$PREFIX/etc/smartdns
>         SMARTDNS_INIT_DIR=$PREFIX/etc/init.d
>         # check if the system support systemctl?
>         systemctl >/dev/null 2>&1
>         ISSYSTEMD="$?"
>         # Running under WSL (Windows Subsystem for Linux)?
>         # cat /proc/version | grep Microsoft >/dev/null 2>&1;
>         if [ $ISSYSTEMD -ne 0 ]; then
>                 ISSYSTEMD=1
>                 ISWSL=0
>         fi
> 
>         cd $INST_DIR
> }
> ```

请问这个怎么加啊  直接记事本打开install.bat加在最底下么。。我wsl2安装出现同样的问题了

**Comment by yeezylife** [comment]
兄弟我也用这办法成功安装了 但是上不去网..IPV4地址已经调成了127.0.0.1

**Comment by MC-dusk** [comment]
使用楼上的代码能安装成功，但可能是被win10防火墙拦截了，导致DNS配置为127.0.0.1后不能使用smartdns
所以还是建议使用WSL1
