### ISSUE TITLE
安装不成功 求助 opkg

### ISSUE THREAD

**Issue by ffplayer** [pymumu/smartdns#44]
>   Base on OpenWrt BARRIER BREAKER (17.02, 2017-02-23-git-6e378cb)
[root@PandoraBox_80BE:/root]#opkg install smartdns.1.2018.11.03-2215.mipsel_24ke
c_dsp.ipk
Unknown package 'smartdns'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package smartdns.

安装的时候提示这样。看了CPU架构是对的哇

> src/gz 17.02_core http://downloads.pandorabox.com.cn/pandorabox/targets/ralink/mt7621/packages

smartdns.1.2018.11.03-2215.ramips_24kec.ipk
smartdns.1.2018.10.12-2158.mipsel_24kc.ipk
smartdns.1.2018.11.03-2215.mipsel_24kec_dsp.ipk
这几个都试了都是这样。。

问题有点新手，但自己搜不到解决方案。。求助。。

**Comment by ffplayer** [comment]
`当架构不兼容时会提示 but incompatible with the architectures configured,
此种情况一般在 ramips_24kec 架构的软件包安装时出现.
可以通过编辑 /etc/opkg.conf 调整架构支持,
在文件末尾添加(也可以在 LuCI 设置页面修改):

arch all 100
arch ramips 200
arch ramips_24kec 300

添加完成后使用 opkg update 更新一次
再次使用 opkg install {packagename}.ipk 安装`

自己参考这个解决了上面这个问题。。。又遇到了另一个提示。。

>  * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-smartdns:

似乎是内核太旧了。。。似乎是要更新下？

**Comment by pymumu** [comment]
先按照smartdns，再按照luci-app-smartdns
潘多拉的固件架构和openwrt不兼容。要看潘多拉写的架构版本是什么样的。

**Comment by pymumu** [comment]
请使用新版本，有问题再reopen issue

**Comment by xiaoleigithub** [comment]
求助：
Collected errors:

pkg_hash_check_unresolved: cannot find dependency bind-client for ddns-scripts_nsupdate
pkg_hash_fetch_best_installation_candidate: Packages for ddns-scripts_nsupdate found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package ddns-scripts_nsupdate.
