### ISSUE TITLE
华硕66u_b1，官方原版固件最新385。该怎么启用smartdns？

### ISSUE THREAD

**Issue by ShadowEmbrace** [pymumu/smartdns#440]
华硕66u_b1，官方原版固件最新385。该怎么启用smartdns？没找到合适的教程。。。
执行opkg install smartdns
Installing smartdns (1.2020.28-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/smartdns_1.2020.28-1_armv7-2.6.ipk
Configuring smartdns.
然后我就不知道怎么办了，输入smartdns之后会在sbin目录出现132k的smartdns。
nslookup baidu.com 有两个ip（配置文件还没修改，我是想先弄得能运行了再去学配置）
我并不介意每次开机都输入一次命令，也是个学习的过程，但是我现在似乎是没让smartdns跑起来。
看了很多的教程都是用网页界面的，但是我这个原版的大概是不能用网页界面吧。
没有按readme.md的介绍装的原因是介绍里说华硕的用mipsbig，但是我在盘里看到了asusware.arm，觉得我的大概不是mips，怕弄错版本，就直接用在线安装了。
谢谢大神解答~
_____________________
试了下载smartdns.1.2020.02.25-2212.arm-optware（/mips）-all.ipk安装显示segmentaion fault

**Comment by pymumu** [comment]
试试mips，或mipsel把。

安装看Readme华硕路由器部分
