### ISSUE TITLE
设置优先使用 tcping 失败，是我设置有误吗

### ISSUE THREAD

**Issue by tty228** [pymumu/smartdns#445]
**问题现象**  

设置方法是在 luci 额外的服务器参数 中输入 `speed-check-mode tcp:80,ping`

这里有个网站 gs.nnfcxx.com，解析出来两个 ip

![4](https://user-images.githubusercontent.com/33397881/77727111-87f7dd80-7034-11ea-9344-b33d92e700f0.png)

ip1（116.1.214.79）
能 ping 通，ping值为 15ms
--- 116.1.214.79 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 15.982/16.537/16.970 ms

tcping 80 端口失败，http 访问超时
![1](https://user-images.githubusercontent.com/33397881/77726859-ea9ca980-7033-11ea-87ad-1b3acf0adda0.png)

ip2（211.138.247.250）
能 ping 通，ping值为 22ms
--- 211.138.247.250 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 22.425/22.703/22.845 ms

tcping 80 端口正常，http 访问正常

![2](https://user-images.githubusercontent.com/33397881/77726843-e1abd800-7033-11ea-8e1f-336ab73e78c3.png)

但是我使用 `speed-check-mode tcp:80,ping` 参数，只能解析到 ip1，无法正常访问网站，我我设置有误还是啥

![3](https://user-images.githubusercontent.com/33397881/77727123-8e865500-7034-11ea-82f5-cfc578f962ba.png)

**运行环境**
1. 固件型号  

斐讯 K3 ，官方源码 19.07.2 + luci19

2. 运营商  

深圳电信 200M

**重现步骤**
1. 上游DNS配置。  

config server
	option type 'udp'
	option name '10000'
	option ip '202.96.134.133'
	option server_group 'china'
	option blacklist_ip '0'
	option enabled '1'
	option addition_arg 'speed-check-mode tcp:80,ping'

config server
	option type 'udp'
	option name '10000_2'
	option ip '202.96.134.33'
	option server_group 'china'
	option blacklist_ip '0'
	option enabled '1'
	option addition_arg 'speed-check-mode tcp:80,ping'

2. 访问的域名。  

gs.nnfcxx.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by jhsb** [comment]
也有这个问题，现在我直接在自定义参数栏上加上了
`speed-check-mode tcp:443,tcp:80,ping`

**Comment by tty228** [comment]
> 也有这个问题，现在我直接在自定义参数栏上加上了
> `speed-check-mode tcp:443,tcp:80,ping`

感谢提醒，可以用了，但是测速应该只支持设置两个
https://github.com/pymumu/smartdns/issues/209

**Comment by qwerttvv** [comment]
歪个楼，楼主看看这个https://github.com/zfl9/chinadns-ng/issues/41

有时间一起试试
