### ISSUE TITLE
arm版openwrt smartdns 重启之后无法自动开启二号服务器

### ISSUE THREAD

**Issue by Licolnlee** [pymumu/smartdns#446]
**问题现象**  
arm版openwrt smartdns 重启之后无法自动开启二号服务器

**运行环境**
1. 固件型号  
N1 openwrt armv8
2. 运营商  
教育网
**重现步骤**
1. 上游DNS配置。  
adguard，google等dot和doh
2. 访问的域名。  
google.com

测试之后发现arm版openwrt插件重启之后不会自动打开第二dns服务器，需要再次手动重启smartdns才能正常使用。希望能检查一下，谢谢。

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by tty228** [comment]
`netstat -ltue | grep 端口号`  查看端口是否被其他进程占用

**Comment by Licolnlee** [comment]
> `netstat -ltue | grep 端口号`  查看端口是否被其他进程占用

端口没有被占用，换成自编译后稳定了，感谢指导。
