### ISSUE TITLE
有的三级域名无应答，比如srv.buysellads.com

### ISSUE THREAD

**Issue by simonfire007** [pymumu/smartdns#449]
**问题现象**  
nslookup srv.buysellads.com 
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
*** Can't find srv.buysellads.com: No answer

**运行环境**
1. 固件型号  
Ubuntu 18.04
2. 运营商  

**重现步骤**
1. 上游DNS配置。  
server 8.8.8.8
server 223.5.5.5
server 119.29.29.29
2. 访问的域名。  
srv.buysellads.com

用buysellads.com和www.buysellads.com都正常
其他域名也发现有这个情况

**Comment by pymumu** [comment]
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   srv.buysellads.com
Address: 167.99.170.23

没发现问题。

**Comment by simonfire007** [comment]
> Server: 192.168.1.1
> Address: 192.168.1.1#53
> 
> Non-authoritative answer:
> Name: srv.buysellads.com
> Address: 167.99.170.23
> 
> 没发现问题。

找到原因了，配置文件里之前我加了过滤广告的hosts，里面就包含这条
