### ISSUE TITLE
安装过程中出现错误

### ISSUE THREAD

**Issue by holydomain** [pymumu/smartdns#450]
opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `Cannot open file kuoruan-public.keyecho

**Comment by holydomain** [comment]
Openwrt Koolshare mod V2.30

**Comment by holydomain** [comment]
Package smartdns (1.2020.02.25-2212) installed in root is up to date.
Collected errors:
 * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `Cannot open file kuoruan-public.keyecho'

**Comment by pymumu** [comment]
没看出和smartdns有明显关系，检查你设备的opkg命令是否有正确工作
