### ISSUE TITLE
怎么实现部分上级DNS测速，部分又不测速呢？

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#451]
我的DNS是这样的：
server 114.114.114.114
server 119.29.29.29
server-tcp 8.8.8.8 -group gfwdns -exclude-default-group
server-tcp 1.1.1.1 -group gfwdns -exclude-default-group
conf-file /etc/smartdns/gfwlist.conf

gfwlist.conf这个会走gfwdns来解析，那我现在希望的是，114.和119这2个DNS解析出来的域名测速，走8.8.8.8和1.1.1.1这个DNS解析出来的不测速。

这个怎么实现呢？感谢！

**Comment by pymumu** [comment]
看readme中bind帮助
