### ISSUE TITLE
捐款QR码中头像的许可证问题

### ISSUE THREAD

**Issue by cdluminate** [pymumu/smartdns#452]
您好，我是Debian开发人员，正在尝试将smartdns引入Debian官方仓库。近期我们的FTP团队对源码进行检查之后对仓库中的部分文件存在许可证/版权方面的疑惑。简单讨论之后我们希望能够向作者确定几个问题，希望得到解答，谢谢！

具体问题如下：
1. `doc/alipay_donate.jpg` 与 `doc/wechat_donate.jpg` 两个QR码中央部分的头像是否是软件作者的作品？如果是，请确认相应的许可协议。如果不是，请告知其来源，以及这两个图像是否是可以自由使用的？
2. 如果两个头像图片不是软件作者本身的作品，那可能会有潜在的法律风险。这种情况下我们Debian这边可以选择读取QR码之后重新生成不带头像的版本，然而这样的解决方案的弊端则是一旦捐款QR码发生更新，软件包维护人员可能会注意不到变化从而漏掉更新。所以如果是这种情况的话，我们希望请求作者将QR码的头像去除，这样也方便我们下游维持源码完整性。

我们的简短讨论是公开的，可以在以下邮件列表进行查看：
https://lists.debian.org/debian-devel/2020/03/msg00485.html

非常感谢您以GPL-3分享这个软件。

**Comment by pymumu** [comment]
支付宝QR码中的图像为从fc模拟器游戏中截图的头像
微信图像为实物拍摄。

对于支付宝的头像，因来源任天堂游戏，不清楚是否有版权问题。
微信的我理解为个人拍摄，应该没有版权问题。

**Comment by cdluminate** [comment]
非常感谢您的及时回复。

任天堂的专有(proprietary)作品图像包含入GPL-3的源码中是存在法律风险的。鉴于全局的GPL-3许可协议覆盖了这些提到的图像文件，而GPL-3又确定用户有着各种使用这些文件的自由。严格来说GPL-3就与任天堂作品的用户协议（我没调查，但肯定不自由）产生冲突。

因此这边建议您从源码包中删除这部分头像（比如临时替换，生成QR以后换回去），从而避免问题。
我后续会从Debian分发的 `smartdns_30.tar.gz` 源码包中删除存在问题的QR码，并使用脚本新生成的QR码进行代替。

有些时候连我自己都觉得Debian严格起来有点麻烦。不过非常感谢您的配合。

**Comment by pymumu** [comment]
支付宝的头像，我已经更换。
