### ISSUE TITLE
speed-check-mode和dualstack-ip-selection的问题？

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#454]
我突然发现这玩意儿速度不太稳，就拿狗东来说，我试了几个时间段，返回的几个ip，现在这个快，一会儿那个快，高峰非高峰差距还挺大

等于说要是缓存结果是测速之后的那个地址，那这个地址可能也就是在缓存的时候儿快，等换一个时段，可能就不如别的地址快了

但是如果缓存的是所有的地址，每次访问都测一遍速，那也不太理想不是，哈哈

有没有一个什么比较好一些的权衡一些的机制呢?

--------------------
这个我知道了，开那个域名预获取，调整ttl就行了

**Comment by qwerttvv** [comment]
另外就是dualstack-ip-selection测速是不是就是speed-check-mode定义的？比如speed-check-mode tcp:443,tcp:80的话，dualstack-ip-selection就是先测443再测80？

有一个网站域名，443全都不通，没有https，只有http，A的80是不通的，本地tcp ping直接超时，AAAA的80是通的，开了dualstack-ip-selection以后为啥总是只返回一个A呢

**Comment by qwerttvv** [comment]
来回来去测试了好几天，大概猜出来逻辑了

**Comment by pymumu** [comment]
为什么要搞那么复杂, 默认配置已经是适合大多数用户了。
配置好上游，其他基本不建议动。

如果有IPV6，有建议开启dualstack-ip-selection。
如果要响应快，就开启serve-expired，或开启preftch。
至于测速方式，一般不建议修改。
大部分网站都是响应ping的。只有个别网站不响应ping，比如github，这种就单独用domain-rule配置一下特定域名的测速方式就好了
