### ISSUE TITLE
同时使用多种协议影响性能么（比如tls和https混着填）

### ISSUE THREAD

**Issue by yeezylife** [pymumu/smartdns#456]
还是说统一填tls 或者统一https比较好啊

**Comment by pymumu** [comment]
没有任何影响, 但不建议同一个DNS服务器配置多种协议。

**Comment by yeezylife** [comment]
> 没有任何影响, 但不建议同一个DNS服务器配置多种协议。

那同一个服务器 主地址和备用地址都填上，不会造成重复查询吗，比如tls 8.8.8.8 tls 8.8.4.4
因为smartdns是并发查询嘛，主副一起查有必要么…

**Comment by pymumu** [comment]
这种没有问题。
