### ISSUE TITLE
华硕路由器安装求助

### ISSUE THREAD

**Issue by GalaxyAlpha** [pymumu/smartdns#458]
**运行环境**
ASUS ac86U  固件版本：Merlin 384.16  IP:10.0.1.1 

**问题现象**  
arm optware版安装成功，但是top没看到服务，指定路径也没有生成log。希望能告知是哪个步骤出了问题，要怎么解决。

执行
/opt/usr/sbin/smartdns -h  
正常  

执行
/opt/usr/sbin/smartdns -f
显示load config failed.

执行
/opt/etc/init.d/S50smartdns enable
/opt/etc/init.d/S50smartdns restart
之后没反应

iptables规则
NCT@RT-AC86U-2A48:/tmp/home/root# iptables -t nat -L PREROUTING | grep REDIRECT
REDIRECT   tcp  --  anywhere             RT-AC86U-2A48.Router  tcp dpt:domain redir ports 535
REDIRECT   udp  --  anywhere             RT-AC86U-2A48.Router  udp dpt:domain redir ports 535
REDIRECT   tcp  --  anywhere             10.0.0.2             tcp dpt:domain redir ports 535
REDIRECT   udp  --  anywhere             10.0.0.2             udp dpt:domain redir ports 535
显示的IP是光猫分配给路由的IP

PC命令行执行nslookup -querytype=ptr smartdns
服务器:  UnKnown
Address:  10.0.1.1

DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

配置文件
server-name smartdns
bind [::]:535
bind-tcp [::]:535
tcp-idle-time 120
cache-size 512
prefetch-domain yes
serve-expired yes
serve-expired-ttl 0
speed-check-mode tcp:443,tcp:80,ping
dualstack-ip-selection-threshold 30
dualstack-ip-selection yes
rr-ttl:600 
rr-ttl-min:60 
rr-ttl-max:600 
log-level info
log-file /var/log/smartdns.log
log-size 128k
log-num 2
server-tls 8.8.8.8:853 -tls-host-verify:dns.google
server-tls 1.1.1.1:853 -tls-host-verify:cloudflare-dns.com

**Comment by pymumu** [comment]
server-tls 8.8.8.8:853 -tls-host-verify dns.google
server-tls 1.1.1.1:853 -tls-host-verify cloudflare-dns.com

**Comment by GalaxyAlpha** [comment]
> rr-ttl 600
> rr-ttl-min 60
> rr-ttl-max 600
> 
> speed-check-mode tcp:443,tcp:80
> server-tls 8.8.8.8:853 -tls-host-verify dns.google
> server-tls 1.1.1.1:853 -tls-host-verify cloudflare-dns.com
> 
> 仔细看smartdns.conf中的帮助

感谢回复，目前可以正常解析了，顺便问一下
nslookup -querytype=ptr smartdns
服务器:  smartdns
Address:  10.0.1.1

*** smartdns 找不到 smartdns: Non-existent domain
请问这又是什么问题呢。

**Comment by pymumu** [comment]
升级最新版本

**Comment by GalaxyAlpha** [comment]
> 升级最新版本

之前安装的就是smartdns.1.2020.02.25-2212.arm-optware-all.ipk，现重新安装，但是情况依旧复现。

**Comment by pymumu** [comment]
这是我的设备。
```
C:\Users\xxxxx>nslookup -querytype=ptr smartdns
服务器:  smartdns
Address:  192.168.1.1

非权威应答:
smartdns        name = smartdns
```

你确认安装了正确版本？

**Comment by GalaxyAlpha** [comment]
> 这是我的设备。
> 
> ```
> C:\Users\xxxxx>nslookup -querytype=ptr smartdns
> 服务器:  smartdns
> Address:  192.168.1.1
> 
> 非权威应答:
> smartdns        name = smartdns
> ```
> 
> 你确认安装了正确版本？

![ScreenShot_20200409001657](https://user-images.githubusercontent.com/49036703/78808559-2baf9900-79f8-11ea-9296-c908eb2cafb9.png)
确定，如果我没看错的话。
