### ISSUE TITLE
IPV6解析问题

### ISSUE THREAD

**Issue by xun188** [pymumu/smartdns#46]
我来说下场景，不知道具体原因，作为dnsmasq上游模式，开启ipv6，ping outlook.com ，返回结果为ipv6地址，ping值400ms左右，禁用ipv6模式，只返回ipv4，那么ping值在60ms左右，开启ipv6后，明显上网卡慢了，系统openwrt18.06.1

**Comment by pymumu** [comment]
可能是openwrt禁止ipv6的ping了。

可以先看一下日志 /var/log/smartdns.log里面有没有ping相关的错误日志。
或者登录到路由器中，用ping6命令，试一下ping6是否正常工作。

**Comment by xun188** [comment]
> 可能是openwrt禁止ipv6的ping了。
> 
> 可以先看一下日志 /var/log/smartdns.log里面有没有ping相关的错误日志。
> 或者登录到路由器中，用ping6命令，试一下ping6是否正常工作。

路由上如下：
root@OpenWrt:~# ping www.outlook.com
PING www.outlook.com (40.100.54.210): 56 data bytes
64 bytes from 40.100.54.210: seq=0 ttl=239 time=45.564 ms
root@OpenWrt:~# ping6 2603:1046:c02:1060::2
PING 2603:1046:c02:1060::2 (2603:1046:c02:1060::2): 56 data bytes
64 bytes from 2603:1046:c02:1060::2: seq=0 ttl=45 time=361.461 ms
64 bytes from 2603:1046:c02:1060::2: seq=1 ttl=45 time=361.703 ms
64 bytes from 2603:1046:c02:1060::2: seq=2 ttl=45 time=361.111 ms
64 bytes from 2603:1046:c02:1060::2: seq=3 ttl=45 time=361.361 ms
在电脑pc上如下：
正在 Ping outlook.ms-acdc.office.com [2603:1046:c02:1060::2] 具有 32 字节的数据:
来自 2603:1046:c02:1060::2 的回复: 时间=399ms
来自 2603:1046:c02:1060::2 的回复: 时间=403ms
来自 2603:1046:c02:1060::2 的回复: 时间=400ms
来自 2603:1046:c02:1060::2 的回复: 时间=410ms

路由设置作为dnsmaq上游，开启ipv6，大概就这样，软件正常running

**Comment by pymumu** [comment]
使用ipv4，还是ipv6现在是终端设备自己选择的。
smartdns并没有在Ipv4和ipv6间优化选择。
目前，终端请求IPV4地址，smartdns只能返回IPV4地址，不能返回IPV6地址。
同理，终端请求IPV6地址，也只能返回IPV6地址。
使用哪个地址决定权在终端，smartdns没有决定权。

当然，smartdns也可以做处理，强制返回地址不可用。
比如终端请求IPV4地址时，smartdns同时检测IPV4和IPV6地址，如果IPV4地址快，就返回IPV4，如果IPV6快，就返回SOA，表示IPV4不可用。
这样终端就会重新请求IPV6地址。smartdns返回IPV6这时就对了。
终端请求IPV6地址时，也可以用同样方法，返回IPV4地址。

当然，还要细化考虑。

**Comment by pymumu** [comment]
当前情况，IPV6并不是很成熟，可以考虑直接禁用IPV6试试，强制使用IPV4地址。
也就是配置force-AAAA-soa yes。

**Comment by pymumu** [comment]
Release 18增加了双栈IP优选策略。
配置参数为dualstack-ip-selection yes
如需要设置自定义优选阈值，请使用配置
dualstack-ip-selection-threshold
