### ISSUE TITLE
关闭测速后缓存失效

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#460]
版本：smartdns 1.2020.02.20-0202

用speed-check-mode none关闭测试后，缓存就失效了。

不想测速的原因是：解析的google的IP测速肯定不准确，因为走的代理，而测速是直连。

所以希望大佬能解决这个问题，就是关闭测速后缓存依然有效。

谢谢！

**Comment by PHCSJC** [comment]
不添加speed-check-mode：
会用ICMP测速，缓存有效，可能是ICMP不通的原因，非常慢，有时要900ms以上。

speed-check-mode none
不会测速，应该是以最先获得的结果为准，但缓存失效，所以重复解析每次都要200ms。

speed-check-mode tcp:80
用TCP连接80端口测速，缓存有效，但好像有BUG，不会等所有DNS都返回结果才测速，而是只要返回了一个就开始测速，然后马上把结果给Client。
这个的测试方法是：加了3个DNS，8.8.8.8和1.1.1.1（都是走代理的，可以正常解析），再加一个国内的DNS（距这个DNS的延迟只有10ms，并且可以正常返回google域名的结果），如果不加第3个国内的DNS，每次查询google域名要200多ms，并抓包发现有测速，如果加上第3个DNS，只要10ms左右就返回结果，并抓到有测速，也就是说从第3个DNS得到了结果（这个第3个DNS也是我自己的，查看日志可以发现的确是从这获取的解析），然后马上测速，再然后马上给了客户端结果，并没有等另外2个DNS的结果来测试对比，因为如果等另外2个DNS的结果，客户端返回结果的时间就不可能是10ms。
再备注下，每次测试我都重启了smartdns进程。

**Comment by pymumu** [comment]
默认情况是ping，再tcp：80
配置none的情况，目前不会缓存结果，这个后面有空优化。
配置tcp：80的话，和ping行为一致。

如果测速响应时间<10ms，就会立即返回了。

**Comment by PHCSJC** [comment]
@pymumu 
请问测速ping不通，超时时间是多少呢？

再请个建议：
按上级DNS设置是否开启测速，比如下面的：
server 114.114.114.114
server 119.29.29.29
server-tcp 8.8.8.8 -group gfwlist -exclude-default-group
server-tcp 1.1.1.1 -group gfwlist -exclude-default-group

国内走114和119，我希望可以测速，国外用8和1，我不希望测速，因为可能不准。

**Comment by pymumu** [comment]
最长1s。

这个不会做。
