### ISSUE TITLE
DoT，DoH配置问题

### ISSUE THREAD

**Issue by szl0834** [pymumu/smartdns#461]
我没太看懂文档里面关于DoT和DoH配置文件的写法，比如server-tls后面只能跟ip地址然后域名再通过-hostname添加还是可以直接填域名，还有-spki-pin和-tls-host-check这两个验证是可选的， 不填会自动获取的，还是必须强制填写的？

还有就是希望example里面能够包含各种选项的用法，不然有时候不太弄得清楚怎么填写。

**Comment by pymumu** [comment]
配置参数说明的例子不是有了么？为什么还要搞那么复杂？

至于额外的参数，弄清楚了再配置，弄不清楚，就不要配置。
