### ISSUE TITLE
openwrt中无法启动smartdns

### ISSUE THREAD

**Issue by thinkpack** [pymumu/smartdns#463]
第三方openwrt 内核 4.14.172
安装smartdns正常，并没有报错。但是在界面上勾选启用smartdns时候，并没有运行。ssh登录上去使用/usr/sbin/smartdns启动报错“/usr/sbin/smartdns: line 1: syntax error: unexpected "(" ” 。由于没有形成日志，无法查询具体错误。请问各位，是否知道这个问题大概什么造成的？缺失lib亦或固件本身缺失以及如何解决？

**Comment by pymumu** [comment]
安装不配套了，搞清楚自己设备CPU的类型，再安装配套的软件包。

**Comment by thinkpack** [comment]
谢谢回复。我查询了newifi3 d2 mt7261 mips架构，应该下载smartdns.1.2020.02.20-0202.mips-openwrt-all.ipk 。安装的也是这个版本，所以才疑问是哪里造成的错误？openwrt固件问题？
