### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by h3fang** [pymumu/smartdns#465]
**问题现象**  
smartdns内存占用缓慢增长，至几百MB

**运行环境**
1. 固件型号  
Arch Linux smartdns 30-1

2. 运营商  
应该无关，不想透露

**重现步骤**
1. 上游DNS配置。  
```
server 101.6.6.6
server 119.29.29.29
server 223.5.5.5
server-https https://cloudflare-dns.com/dns-query
server-https https://dns.containerpi.com/dns-query
server-https https://dns.quad9.net/dns-query
server-https https://dns.rubyfish.cn/dns-query

cache-size 1024

prefetch-domain yes
speed-check-mode tcp:443,ping
rr-ttl-min 10
```

2. 访问的域名。  
任意

**信息收集**  
[valgrind-output.txt](https://github.com/pymumu/smartdns/files/4460209/valgrind-output.txt)
从valgrind信息分析，应该是https://github.com/pymumu/smartdns/blob/b78c9eb6feeca9121bbfe0def83e4fb0c8bbb3c9/src/dns_client.c#L1832 和 https://github.com/pymumu/smartdns/blob/b78c9eb6feeca9121bbfe0def83e4fb0c8bbb3c9/src/dns_client.c#L1859 这两个break导致http_head没有被释放造成的。注释后不再出现泄漏，但不清楚是否影响程序逻辑。

为了避免类似的错误，能否使用curl等库的http(s)实现，避免重复造轮子。

**Comment by pymumu** [comment]
应该是1832行导致的
写http解析，就是因为不想依赖curl，在路由器上运行的话，不是所有设备都有libcurl的

**Comment by pymumu** [comment]
最新一次提交修改了此问题，可以验证看看

**Comment by h3fang** [comment]
没有泄漏了，感谢

**Comment by cncqcyc** [comment]
我的x86平台编译的5.4.138内核，lean的固件，也发现了此问题，内存缓慢增长直至系统自动把smartdns杀掉，持续观察当可用内存变小后，手动开关一下smartdns可用内存恢复正常
