### ISSUE TITLE
The answer regarding to 'Smartdns is not designed to replace DNSMASQ' is incomplete.

### ISSUE THREAD

**Issue by enihcam** [pymumu/smartdns#469]
In [FAQ](https://github.com/pymumu/smartdns/blob/master/ReadMe_en.md#faq), you are saying 'Smartdns is not designed to replace DNSMASQ', so regarding to the DNS functionalities (ignore DHCP), what SmartDNS cannot do but DNSMASQ can?

**Comment by pymumu** [comment]
There are several missing functions, one is dhcp server, and the other is that smartdns only processes A and AAAA records,other records are transparently forwarded.   

The difference between smartdns and dnsmasq can be obtained from the configuration parameters of the two software.
