### ISSUE TITLE
koolshare lede 2.34 luci程序显示状态不正确

### ISSUE THREAD

**Issue by yyysuo** [pymumu/smartdns#471]
**问题现象**  
koolshare lede 2.34重新安装smartdns release 30主程序和luci界面后（卸载再安装，配置文件存在），运行状态正常，可正常使用，luci界面基本设置部分提示：尚无任何配置

**运行环境**
1. 固件型号  
koolshare 2.34
http://firmware.koolshare.cn/LEDE_X64_fw867/openwrt-koolshare-mod-v2.34-r13929-b0a6daaa6b-x86-64-generic-squashfs-combined.img.gz
2. 运营商  
联通
**重现步骤**
1. 上游DNS配置。  
tls://9.9.9.9:853
tls://8.8.8.8:853
tls://8.8.4.4:853
tls://1.1.1.1:853
tls://dns.google:853
https://dns.google/dns-query
https://dns.quad9.net/dns-query
https://1.1.1.1/dns-query
2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。 
[2020-04-15 16:02:16,467][ERROR][            dns.c:1647] decode NS failed, 
 
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
配置不是这种格式
另外如果是自定义配置修改保存后提示无配置更新，这种情况是luci的问题，可以修改其他配置后一起生效

**Comment by yyysuo** [comment]
sorry，我可能理解错了，实际上这个错误是koolshare lede的内核大版本更新有关系，目前内核版本已经升级到5.4.31了，然后程序运行正常，使用也正常，但是luci无法正常显示使用了。2个版本的luci我都试过，luci-app-smartdns.1.2020.02.25-2212.all-luci-compat-all.ipk不报错，但是显示无配置文件，luci-app-smartdns.1.2020.02.25-2212.all-luci-all.ipk安装后点击服务里面的smartdns会报错。

smartdns.conf 内容如下：
server-name smartdns
bind [::]:6053
bind-tcp [::]:6053
prefetch-domain yes
serve-expired yes
cache-size 10000
rr-ttl 600
rr-ttl-min 600
rr-ttl-max 600
log-size 64K
log-num 1
log-level error
server 119.29.29.29  
server 119.28.28.28  
server 223.5.5.5  
server 223.6.6.6  
server 180.76.76.76  
server 114.114.114.114  
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

**Comment by yyysuo** [comment]
好像是koolshare 2.34的luci通过rpc与程序交互，所以好多luci都不能用了。

**Comment by kang-mk** [comment]
koolshare 的升级过于激进了

**Comment by pymumu** [comment]
使用javascript版本的luci验证下看看

**Comment by yyysuo** [comment]
> 使用javascript版本的luci验证下看看

2个版本的luci程序都不行
compat版本提示Insufficient permissions to read UCI configuration.
另外一个版本直接提示error
