### ISSUE TITLE
如何清除单个域名的缓存

### ISSUE THREAD

**Issue by baoziking** [pymumu/smartdns#472]
你好，请问，我自己的域名，动态DNS，绑定我的公网地址，但smartdns一直缓存着变更前的，变更后的IP地址没有被缓存到，请问SMARTDNS缓存存放在什么位置，有什么方法可以清理单条缓存记录重新缓存吗？

**Comment by pymumu** [comment]
建议是修改dns的ttl值。

或者直接内网address强制指定本地IP地址。

address /xxx.ddns.com/192.168.1.1
address /xxx.ddns.com/#6

**Comment by naoki66** [comment]
我在[自定义设置]添加这个ddns无效呢
domain-rules /ddns.xyz/ --no-serve-expired

**Comment by PikuZheng** [comment]
> 我在[自定义设置]添加这个ddns无效呢 domain-rules /ddns.xyz/ --no-serve-expired

上游不要用阿里云，它有一个巨大的过期缓存
