### ISSUE TITLE
有办法限制 每个客户端的每秒请求数吗?

### ISSUE THREAD

**Issue by fcying** [pymumu/smartdns#473]
在proxmox上搭的smartdns服务器. 

有一台虚拟机中毒了. 不停发dns 请求, 导致smartdns cpu 100%
同时别的机器的dns 请求也都不能用了. 

有办法限制 每个客户端的每秒请求数吗? 这样有时候有客户端出问题了 也不会影响到别的客户端

**Comment by pymumu** [comment]
smartdns是异步处理的，不会因为单个客户端大量请求导致其他客户端完全无法响应，只可能稍慢

**Comment by fcying** [comment]
不能说完全无法响应了. 只是其他机器 dig 查询都要好久. 有时候还超时. 
用top 看就是smartdns 100%了. log里全是那台问题机刷的log.

**Comment by fonlan** [comment]
试试iptables规则能限制住不：
iptables -A INPUT -p udp --sport 53 -m limit -d 192.168.1.2 --limit 30/s --limit-burst 100 -j ACCEPT

**Comment by fcying** [comment]
> -s 192.168.1.2

感谢, 用iptables能限制住. 

加了一行 iptables -A INPUT -p udp --dport 53 -j DROP

**Comment by fonlan** [comment]
> > -s 192.168.1.2
> 
> 感谢, 用iptables能限制住.
> 
> 加了一行 iptables -A INPUT -p udp --dport 53 -j DROP

大兄弟，你这是把所有DNS请求全丢了呀。。。我还以为你是想针对特定IP做DNS请求的速率限制。

**Comment by fcying** [comment]
> 
> 
> > > -s 192.168.1.2
> > 
> > 
> > 感谢, 用iptables能限制住.
> > 加了一行 iptables -A INPUT -p udp --dport 53 -j DROP
> 
> 大兄弟，你这是把所有DNS请求全丢了呀。。。我还以为你是想针对特定IP做DNS请求的速率限制。

对的. 是想限制全部 设备做DNS请求的限制. 
刚开始 加了 
iptables -A INPUT -p udp --dport 53 -m limit --limit 30/s --limit-burst 100 -j ACCEPT 没限制住...
然后gg了下 iptables 限制端口连接数...看别的教程里面有个DROP, 就加上了...现在看起来功能正常...

```
iptables -A INPUT -p udp --dport 53 -m limit --limit 30/s --limit-burst 100 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j DROP
```
