### ISSUE TITLE
nameserver规则编写疑问

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#477]
目前是DNSMASQ和SMARTDNS共用，打算将DNSMASQ的规则全部移到SMARTDNS。

用简单的例子来举例吧。

在DNSMASQ上
server=/cn/114.114.114.114
server=/baidu.com/114.114.114.114
这两条规则就可以将所有的cn后缀和所有的百毒域名（含主域名）直接用114解释

换到SMARTDNS的话
nameserver /cn/IPV4CHN
nameserver /baidu.com/IPV4CHN
这样能实现一样的效果吗？

还是要
nameserver /.cn/IPV4CHN
nameserver /.baidu.com/IPV4CHN
这样才行？如果是这种的话，那这样不是还要多加一个
nameserver /baidu.com/IPV4CHN
才能解释主域名的？

**Comment by pymumu** [comment]
配合server的group参数使用，如
server 114.114.114.114 -group IPV4CHN

**Comment by pymumu** [comment]
另外，.baidu.com和baidu.com是同一个规则

**Comment by ztjal** [comment]
> 
> 
> 另外，.baidu.com和baidu.com是同一个规则，包含主域名和子域名

nameserver /cn/IPV4CHN
nameserver /us/IPV4USA
nameserver /jp/IPV4JPN
nameserver /gov/NNNNNDNS

这样能解释匹配对应的后缀吗？

别外加个建议，把WIKI功能开了吧，将一些规则的写法之类的整理到一块去，方便查。
