### ISSUE TITLE
所有Doh服务器，填IP地址（1.x.x.1）就能使用，填英文地址cloudxxx.com就不能使用

### ISSUE THREAD

**Issue by yeezylife** [pymumu/smartdns#478]
为什么会这样啊 我试过了四个不同的服务器，都是这种情况，server-https后面填写数字IP地址就能正常上网，server-https后面填英文网址都上不去网，我看其他人能填英文网址啊。。
我用的是win1064位WSL下的最新版。
比如填写server-https https://cloudflare-dns.com/dns-query就不行，填写server-https https://1.1.1.1/dns-query就可以。。

**Comment by yeezylife** [comment]
我用的是win10WSL下的最新版哦

**Comment by pymumu** [comment]
要至少保留一个IP地址形式的上游服务器。

**Comment by yeezylife** [comment]
> 要至少保留一个IP地址形式的上游服务器。

还有这种说法，之前没注意。那请问是所有的上游服务器类型里（dot，doh,普通server），只要有任意一个是IP地址形式的就行么，还是说必须也是DOH的。。

**Comment by pymumu** [comment]
只要有一个是ip地址就可以
