### ISSUE TITLE
配置总提示无法保存

### ISSUE THREAD

**Issue by goldzy123** [pymumu/smartdns#48]
右上角总提示有两项配置要保存，卸载，手动删配置再重新安装还是没用。而且开机不会自动运行了。

smartdns.cfg016bb1
smartdns.cfg016bb1.old_port+=
smartdns.cfg016bb1.old_port+=6053
smartdns.cfg016bb1.old_redirect+=
smartdns.cfg016bb1.old_redirect+=none

**Comment by pymumu** [comment]
开机没启动，是是因为自动启动被关闭了
可以到配置界面的`系统`->`启动项`中找到`smartdns`，点击`启用`

配置没保存的提示不影响功能，可以暂时忽略，不影响功能，下个版本解决。

**Comment by goldzy123** [comment]
@pymumu 不行啊，启动项肯定开了，但是开机怎么都启动不了。禁用打开重启都不行。

**Comment by pymumu** [comment]
打开日志看看
用的什么固件，我这边openwrt是验证启动正常的。

**Comment by goldzy123** [comment]
系统日志里没有相关的东西，smartdns的日志也是空的。

**Comment by pymumu** [comment]
什么固件

**Comment by goldzy123** [comment]
@pymumu 我还有个hyperv虚拟的原版lede18.06，也是不自动启动。之前有些版本是可以重启的，反正升级这么几次不知道哪有问题就不能自动启动了。
把/etc/smartdns log 还有配置文件都清理了，重装还是不行。

**Comment by goldzy123** [comment]
系统日志里只有一条

Sun Dec  9 10:48:31 2018 user.notice ucitrack: Setting up /etc/config/smartdns reload trigger for non-procd /etc/init.d/smartdns

**Comment by goldzy123** [comment]
smartdns启动的时候还会把 dnsmasq自定义解析文件重置为 /tmp/resolv.conf.auto?
我试了直接重启不会变，一开smartdns立马重置回去了，我是用自己的解析文件，能不能不要重置。

**Comment by pymumu** [comment]
设置none之后，不会取改dnsmasq的配置文件。
你确认一下版本是不是12.2号17点的。

无法启动的那个，我这里不重现，暂时不知道什么原因。

先确认一下启动项是否设置启动。

还是不行的话，我加点日志在代码里面，给你一个临时版本呢，帮助定位一下。

**Comment by goldzy123** [comment]
重定向就是设置的none 
版本是smartdns.1.2018.12.02-1745.x86_64
luci-app-smartdns.1.2018.12.02-1745.all
都是最新下的
我看了一圈所有issue，好像之前有人也是説无法启动，要删除luci手动启动就没问题了，会不会有这种情况。

**Comment by pymumu** [comment]
这个启动项不是在smartdns的页面上
在openwrt的系统->启动项

**Comment by goldzy123** [comment]
肯定的啊，基本操作还是知道的

**Comment by pymumu** [comment]
路由器上运行下这个命令试试
/etc/init.d/smartdns enable

**Comment by pymumu** [comment]
@goldzy123 
Release 18已经解决此问题，请取用。
