### ISSUE TITLE
smartdns配合passwall生效问题

### ISSUE THREAD

**Issue by AlexZSD** [pymumu/smartdns#480]
**问题现象**  
简要描述问题出现的现象
设置了国内，国外两组dns服务器，pw的dns模式选择了使用本机7913端口的dns。机场用的是国内bgp中继，能出国，但好像smartdns的第二组服务器没生效。
国内的dns应该是生效了：
C:\Users\alexc>nslookup -querytype=ptr smartdns www.baidu.com
服务器:  UnKnown
Address:  14.215.177.38

非权威应答:
smartdns        name = china

但国外的不行：
C:\Users\alexc>nslookup www.youtube.com
服务器:  OpenWrt.lan
Address:  192.168.2.32

非权威应答:
名称:    youtube-ui.l.google.com
Addresses:  172.217.160.78
          216.58.200.46
          172.217.24.14
          172.217.160.110
          172.217.27.142
          216.58.200.238
Aliases:  www.youtube.com
国外用的是google和cloudflare dot，换成udp以后解析出来的IP更多了。
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      www.youtube.com
www.youtube.com	canonical name = youtube-ui.l.google.com
Name:      youtube-ui.l.google.com
Address 1: 172.217.24.206
Address 2: 216.58.220.206
Address 3: 172.217.24.46
Address 4: 172.217.24.78
Address 5: 172.217.26.142
Address 6: 216.58.221.238
Address 7: 172.217.31.238
Address 8: 172.217.161.142
Address 9: 216.58.199.14
Address 10: 172.217.161.174
Address 11: 172.217.25.14
Address 12: 216.58.200.14
Address 13: 216.58.197.110
*** Can't find www.youtube.com: No answer

国外的网站能正常上，但这算是生效了吗？
C:\Users\alexc>nslookup -querytype=ptr smartdns www.youtube.com
服务器:  tsa03s01-in-f238.1e100.net
Address:  216.58.200.238

*** tsa03s01-in-f238.1e100.net 找不到 smartdns: Non-existent domain

将节点换成自建的阿里云新加坡中继V2，从non-existent domain变成了request timed out
C:\Users\alexc>nslookup -querytype=ptr smartdns www.youtube.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  216.58.200.238

DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时

**运行环境**
1. 固件型号  
VMWare OpenWRT

2. 运营商  
中国电信

**Comment by pymumu** [comment]
用nameserver分流
聚合配置可以用domain-rule
