### ISSUE TITLE
或者需要DNS-rebind attack detected类的功能

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#481]
**需求应用场景**
dnsmasq有个功能叫“重绑定保护”，主要是拒绝解析包含私有和保留 IP 地址的域名
例如：127.0.0.0/8，10.0.0.0/8，172.16.0.0/12，192.168.0.0/16
也可以增加忽略的域名

例如dnsmasq拦截的时会打印信息一条信息
Fri Apr 24 22:15:39 2020 daemon.warn dnsmasq[2445]: possible DNS-rebind attack detected: groupclient.qq.com

**建议的方案**
可以手动配置，参考dnsmasq可以手动改CONF文件
stop-dns-rebind
rebind-domain-ok=/.xxxxx.com/

**Comment by pymumu** [comment]
ignore-ip 10.0.0.0/8
ignore-ip 172.16.0.0/16
ignore-ip 172.17.0.0/16
ignore-ip 172.18.0.0/16
ignore-ip 172.19.0.0/16

**Comment by ztjal** [comment]
> 
> 
> ignore-ip 10.0.0.0/8
> ignore-ip 172.16.0.0/16
> ignore-ip 172.17.0.0/16
> ignore-ip 172.18.0.0/16
> ignore-ip 172.19.0.0/16

啊，笨了😆
在现有规则下有没有能实现“白名单域名”的方法，即定义某个域名后，跳过所有忽略规则？
@pymumu

**Comment by pymumu** [comment]
看帮助，一般“-”表示忽略某个域名的规则

**Comment by ztjal** [comment]
> 
> 
> 看帮助，一般“-”表示忽略某个域名的规则

例如我写了
ignore-ip 127.0.0.0/8
是能拦截了，但
现在有个域名myhome.abc.com，IPV4记录是127.0.0.1，试了下边两个写法都不行
domain-rules /myhome.abc.com/ -address - -ipset -
domain-rules /myhome.abc.com/ -whitelist-ip 127.0.0.0/8

怎么才能让这个myhome.abc.com成为白名单？
@pymumu

**Comment by pymumu** [comment]
这个没有直接办法。  
但你可以把127.0.0.1/8从ignore-ip去掉，然后直接指定对应的域名地址即可。
