### ISSUE TITLE
使用Smartdns后图片解析不全

### ISSUE THREAD

**Issue by gzelvis** [pymumu/smartdns#482]
**问题现象**  
使用smartdns做域名解析后，经常会在某些一个页面列出好多个图片（略缩图）的网页里，出现部分图片无法显示的问题。这些图片都用的同一个服务器，理论上能打开大部分其它的都应该能打开。换回dnsmasq解析后没有出现此问题。

距离，pianyuan.la这个网站，就会出现这样的问题
![截屏2020-04-26 20 07 46](https://user-images.githubusercontent.com/7994074/80307155-f37ec780-87f9-11ea-8652-f31681b36578.png)

**运行环境**
1. 固件型号  
centos7.7 ，30.0版本smartdns
2. 运营商  
中国电信
**重现步骤**
1. 上游DNS配置。  
8.8.8.8；1.1.1.1；208.67.222.222
2. 访问的域名。  
pianyuan.la

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
我改成114.114.114.114访问也可以看到一些无图片的项目。

这个没看出和smartdns有关系。
你可以用同一个图片，用不同dns加载看看。

**Comment by gzelvis** [comment]
就譬如服务器装个Plex Server，在没装smartdns前单独指用运营商DNS或者119.29之类的，演员阵容可以全部显示，装了smartdns后经常会有图片显示不出来，结果如下
![截屏2020-04-26 22 42 36](https://user-images.githubusercontent.com/7994074/80310845-5d559c00-880f-11ea-871c-280867eaa577.png)

**Comment by pymumu** [comment]
我这里是可以正常显示的。
C:\Users\meikechong>ping pianyuan.la

正在 Ping t618n8.67cdn.com [103.117.102.81] 具有 32 字节的数据:
来自 103.117.102.81 的回复: 字节=32 时间=13ms TTL=52
来自 103.117.102.81 的回复: 字节=32 时间=14ms TTL=52

**Comment by gzelvis** [comment]
首先很感谢你制作了这个软件，也曾支付宝给你做过小捐赠。但这个同一页面下一次过显示该域名下的一堆图片会显示不全的问题，我记得之前还有其他网友也发过这样的issue。就希望作者你有机会留意看看问题在哪里能否fix。除此以外，最新30版的smartdns在linux下运行还是会经常出现那个pid文件无法打开的故障提示，虽然它不影响正常使用。（config那里删减一下，或许有次就不提示pid文件无法打开错误了）。

衷心希望这个软件能越做越好

**Comment by pymumu** [comment]
理解你的心情，但仅靠上述信息，没法明确问题原因的。
很多时候，大家发的问题，在我自己的设备和网络中是没有问题的。
这种，单靠截图是无法定位问题的。有些可能是软件问题，有些可能是配置，有些可能是网络问题。

这也是为什么issue的模板，要求大家写一些详细信息，包括收集日志。
如果要高效的解决问题，就要提供充足的信息。

所以，建议尝试打开浏览器的网络调试功能和smartdns的debug日志，看对应域名解析的IP地址是多少。看解析的IP地址是否正确。

**Comment by z826540272** [comment]
可能是解析到了不同的ip地址

**Comment by pymumu** [comment]
使用最新版本看看，如还有问题reopen issue，贴上日志

**Comment by yangchenlarkin** [comment]
我也遇到了一样的问题，比如微信、微博的图片（xxx.qpic.cn和sinaimg啥的）

**Comment by PikuZheng** [comment]
> 我也遇到了一样的问题，比如微信、微博的图片（xxx.qpic.cn和sinaimg啥的）

这些国内外都有cdn的网站，如果用错误的策略解到国外的地址，就会出现这样的情况，也可能是ipv6的问题
