### ISSUE TITLE
lede2.3.4的luci-smartdns-compat安装后无法进行设置

### ISSUE THREAD

**Issue by necrolytescat** [pymumu/smartdns#483]
**问题现象**  
lede2.3.4的luci-smartdns-compat安装后无法进行设置

**运行环境**
lede2.3.4

![QQ截图20200427011232](https://user-images.githubusercontent.com/48013927/80314466-3fdefd00-8824-11ea-8f79-44b308453cdb.png)

**Comment by pymumu** [comment]
用javascript版本的luci看看。

**Comment by pymumu** [comment]
使用最新版本看看，如还有问题reopen issue，贴上日志
