### ISSUE TITLE
server-tls、server-https中的-tls-host-verify参数无法识别证书主机名里的通配符

### ISSUE THREAD

**Issue by brainos233** [pymumu/smartdns#485]
**问题现象**  
给9.9.9.9等主机名为*.quad9.net的dns指定为dns.quad9.net时就会这样
server 9.9.9.9 CN is invalid, peer CN: *.quad9.net, expect CN: dns.quad9.net
peer 9.9.9.9 verify failed.
直接指定*.quad9.net正常
add server 9.9.9.9:853, type: tls
虽然不是严重问题但是十分别扭，如果有时间请修复一下

**运行环境**
1. 固件型号  
optware/entware版本（从entware仓库安装）
2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
可以获取最新代码编译下看看。

**Comment by brainos233** [comment]
> 
> 
> 可以获取最新代码编译下看看。

编译时出现
/opt/bin/ld: warning: libc.so.0, needed by /usr/lib/libssl.so, may conflict with libc.so.6
/opt/bin/ld: errno@@GLIBC_PRIVATE: TLS definition in /tmp/mnt/Entware/entware/bin/../lib/gcc/arm-openwrt-linux-gnueabi/7.4.0/libc.so.6 section .tbss mismatches non-TLS definition in /lib/libc.so.0 section .bss
/lib/libc.so.0: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:46: smartdns] Error 1
make: Leaving directory '/tmp/mnt/sda1/smartdns-Release30/src'
make smartdns failed

**Comment by pymumu** [comment]
最好是交叉编译，你这是路由器的运行库和/optware的不一致。

**Comment by pymumu** [comment]
[smartdns.1.2020.05.01-2108.arm-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/4564273/smartdns.1.2020.05.01-2108.arm-optware-all.ipk.zip)

**Comment by brainos233** [comment]
> 
> 
> [smartdns.1.2020.05.01-2108.arm-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/4564273/smartdns.1.2020.05.01-2108.arm-optware-all.ipk.zip)

感谢，解决了
