### ISSUE TITLE
想问一下smartdns是否跟bbr加速有冲突？

### ISSUE THREAD

**Issue by roycho93** [pymumu/smartdns#487]
**问题现象**  
开启固件Turbo ACC的bbr加速后总是很难打开网页，想请教下是否有冲突，如果有的话希望能简单了解原理谢谢。
补充一下我用的固件中Turbo ACC里只有Flow Offloading跟BBR两个加速选项，没有DNS加速，所以我说的情况只是选中了BBR加速打开。

**运行环境**
1. 固件型号  OpenWRT 19.07

2. 运营商  CMCC

**重现步骤**
1. 上游DNS配置。  
114 google opendns cmcc运营商dns
2. 访问的域名。  
几乎所有

**Comment by pymumu** [comment]
bbr本身只是tcp带宽提升，本身和smartdns功能不冲突。
但如果是非openwrt的衍生版本固件，因不清楚其工作原理，无法给你明确答复。
考虑打开smartdns的调试看解析的IP地址是否正确。

**Comment by roycho93** [comment]
> bbr本身只是tcp带宽提升，本身和smartdns功能不冲突。
> 但如果是非openwrt的衍生版本固件，因不清楚其工作原理，无法给你明确答复。
> 考虑打开smartdns的调试看解析的IP地址是否正确。

 感谢回复，请问怎样打开smartdns的调试呢？是用nslookup命令查看吗？

**Comment by pymumu** [comment]
配置文件中增加log-level info
或配置中增加audit-enable yes看审计日志
