### ISSUE TITLE
请问smartdns能作为dns服务器提供dot和doh查询吗

### ISSUE THREAD

**Issue by LittleGrocery** [pymumu/smartdns#488]
我配置了，目前知道smart dns上游dns支持dot doh查询， 但是smart dns能否作为服务器，向其他设备提供doh和dot查询呢？因为如果只是提供53端口解析的话，百分百会被抢答

**Comment by pymumu** [comment]
smartdns定位场景是本地局域网dns服务器，所以没有计划支持提供dot，doh能力。

**Comment by LittleGrocery** [comment]
> smartdns定位场景是本地局域网dns服务器，所以没有计划支持提供dot，doh能力。

好的，不知道github另一位拿你源码搞的magnisk模块的smart dns你可知道，这个安卓真能用吗？

**Comment by pymumu** [comment]
只要符合GPL开源的要求就没问题
安卓本身也是linux，理论应该可以运行

**Comment by LittleGrocery** [comment]
> 只要符合GPL开源的要求就没问题
> 安卓本身也是linux，理论应该可以运行

好的 感谢回答
