### ISSUE TITLE
有计划支持ipq806x吗？

### ISSUE THREAD

**Issue by luckyyyyy** [pymumu/smartdns#49]
树莓派上试了一下，效果不错，想给R7800安上，CPU是ipq806x

**Comment by pymumu** [comment]
[Uploading smartdns_build.zip…](附件)
 
看看能不能用。

**Comment by luckyyyyy** [comment]
@pymumu 似乎不太行 有联系方式没 我给你看下

**Comment by pymumu** [comment]
吧openwrt的软件源下载路径发一下
我确认一下版本号

**Comment by pymumu** [comment]
另外，上述文件能安装吗，还是安装的时候报错了？

**Comment by pymumu** [comment]
ldd /usr/sbin/smartdns

**Comment by luckyyyyy** [comment]
root@LEDE:/usr/sbin# ldd /usr/sbin/smartdns
	/lib/ld-musl-arm.so.1 (0x7f61b000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb6ef0000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb6dad000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6d93000)
	libc.so => /lib/ld-musl-arm.so.1 (0x7f61b000)

**Comment by pymumu** [comment]
/usr/sbin/smartdns -h命令呢

**Comment by luckyyyyy** [comment]
这种状态应该是 
不是一个合法的可执行文件或者毁坏了，所以应该是还是平台的问题。

R7800就是ipq806x Qualcomm的SoC

**Comment by pymumu** [comment]
ldd命令解析对的，按理说应该要可以执行的。
给你的是ipq40xx的版本。

ipq806x的要交叉编译环境，现在没有，要的话，要等几天。

**Comment by luckyyyyy** [comment]
没事 等几天吧 我在ubuntu上调试了一下 问题不大

**Comment by pymumu** [comment]
[smartdns_build.zip](https://github.com/pymumu/smartdns/files/2683389/smartdns_build.zip)

试一下这个

**Comment by luckyyyyy** [comment]
似乎还是不行 
![image](https://user-images.githubusercontent.com/9210430/50059822-c0203780-01c6-11e9-9a22-036871c79496.png)

**Comment by luckyyyyy** [comment]
似乎还是不行
![image](https://user-images.githubusercontent.com/9210430/50059867-666c3d00-01c7-11e9-82a7-0cfae3bfb443.png)

root@LEDE:~# ldd /usr/sbin/smartdns
        /lib/ld-musl-arm.so.1 (0x7f60c000)
        libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb6ed7000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb6d94000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6d7a000)
        libc.so => /lib/ld-musl-arm.so.1 (0x7f60c000)
root@LEDE:~#

**Comment by luckyyyyy** [comment]
```
root@LEDE:~# ll /usr/sbin/smartdns
-rwxr-xr-x    1 root     root        160208 Dec 16 08:45 /usr/sbin/smartdns*
root@LEDE:~# /usr/sbin/smartdns -h
-ash: /usr/sbin/smartdns: not found
root@LEDE:~#

```

**Comment by pymumu** [comment]
感觉是你系统少了依赖。
看看如下结果：
ldd /usr/lib/libssl.so.1.0.0
ldd /usr/lib/libcrypto.so.1.0.0
ldd /lib/libgcc_s.so.1

**Comment by luckyyyyy** [comment]
![image](https://user-images.githubusercontent.com/9210430/50089736-98ba8080-0241-11e9-8591-fb8a93c14d07.png)

**Comment by pymumu** [comment]
你这是官方固件吗？
上图ldd的命令结果不正常，但没看出问题在哪里。

你装一个strace命令，执行以下
strace /usr/sbin/smartdns -h

发一下输出。

**Comment by luckyyyyy** [comment]
https://downloads.openwrt.org/releases/17.01.1/targets/ipq806x/generic/

execve("/usr/sbin/smartdns", ["/usr/sbin/smartdns", "-h"], [/* 12 vars */]) = -1 ENOENT (No such file or directory)
writev(2, [{iov_base="strace: exec: No such file or di"..., iov_len=39}, {iov_base="\n", iov_len=1}], 2strace: exec: No such file or directory
) = 40
writev(2, [{iov_base="", iov_len=0}, {iov_base=NULL, iov_len=0}], 2) = 0
getpid()                                = 13931
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by pymumu** [comment]
看一下这个文件在不在
/lib/ld-musl-arm.so.1

ls -lh /lib

**Comment by pymumu** [comment]
[smartdns_build.zip](https://github.com/pymumu/smartdns/files/2691053/smartdns_build.zip)

在看看这个把。感觉应该对了

**Comment by luckyyyyy** [comment]
```
drwxr-xr-x    2 root     root          29 Apr 18  2017 config
drwxr-xr-x    1 root     root         224 Apr 18  2017 firmware
drwxr-xr-x    2 root     root         140 Apr 18  2017 functions
-rwxr-xr-x    1 root     root        7.9K Apr 18  2017 functions.sh
-rw-r--r--    1 root     root        1.3K Apr 18  2017 ipq806x.sh
lrwxrwxrwx    1 root     root           7 Apr 18  2017 ld-musl-armhf.so.1 -> libc.so
-rw-r--r--    1 root     root       16.0K Apr 18  2017 libblkid-tiny.so
-rw-r--r--    1 root     root        8.0K Apr 18  2017 libblobmsg_json.so
-rwxr-xr-x    1 root     root      400.7K Apr 18  2017 libc.so
-rw-r--r--    1 root     root       28.1K Apr 18  2017 libfstools.so
-rw-r--r--    1 root     root       39.5K Apr 18  2017 libgcc_s.so.1
-rw-r--r--    1 root     root        8.0K Apr 18  2017 libjson_script.so
-rw-r--r--    1 root     root        4.0K Apr 18  2017 libsetlbf.so
-rw-r--r--    1 root     root       32.0K Apr 18  2017 libubox.so
-rw-r--r--    1 root     root       20.1K Apr 18  2017 libubus.so
-rwxr-xr-x    1 root     root       32.0K Apr 18  2017 libuci.so
-rw-r--r--    1 root     root       12.6K Apr 18  2017 libvalidate.so
drwxr-xr-x    1 root     root         224 Apr 18  2017 modules
drwxr-xr-x    4 root     root         212 Apr 18  2017 netifd
drwxr-xr-x    2 root     root          49 Apr 18  2017 network
drwxr-xr-x    2 root     root         377 Apr 18  2017 preinit
-rw-r--r--    1 root     root         771 Apr 18  2017 uboot-envtools.sh
drwxr-xr-x    1 root     root         224 Jul 21 07:34 upgrade
drwxr-xr-x    2 root     root          34 Apr 18  2017 wifi

```

**Comment by luckyyyyy** [comment]
![image](https://user-images.githubusercontent.com/9210430/50163241-f969bc00-031a-11e9-98f8-6f9c83894419.png)
不容易啊

**Comment by pymumu** [comment]
没设备，没法验证。交叉编译环境搞错了。

**Comment by pymumu** [comment]
Release 18正式版本发布，请取用验证。
