### ISSUE TITLE
smartdns启用成功与否确认

### ISSUE THREAD

**Issue by roycho93** [pymumu/smartdns#491]
**问题现象**  
其实不算是问题，只是请教一下我的smartdns启用成功与否
1.用putty连接到路由器，输入nslookup www.baidu.com的情况下返回是一个ip地址，后面再加114或别的dns的话返回是多个ip，应该算启用成功的吧？但是nslookup netflix.com的情况下都是返回多个网址这样算启动成功了吗？

2.我在win的cmd下用tracert命令查询跃点，发现貌似ipv6的网址在第一行出现了smartdns[2409开头可以访问路由的ipv6网址]，但是查询ipv4的网站的时候第一行出现的是openwrt.lan[192.168.1.1]，就是疑惑为什么查询ipv4的时候出现的是openwrt.lan而非smartdns

3.putty连接路由器输入nslookup -querytype=ptr smartdns，返回Invalid query type "ptr"，win的cmd下输入nslookup -querytype=ptr smartdns，返回
服务器:  OpenWrt.lan
Address:  fdb8:f4a4:4c36::1

*** OpenWrt.lan 找不到 smartdns: Non-existent domain

**运行环境**
1. 固件型号  
OpenWRT 19.07
2. 运营商  
CMCC
**重现步骤**
1. 上游DNS配置。  
114 Google 百度 腾讯 本地运营商DNS

**Comment by pymumu** [comment]
在windows机器上验证是否生效，不要在路由器上验证

**Comment by VanDeAnna** [comment]
> 在windows机器上验证是否生效，不要在路由器上验证

看了楼主说的，我也去试了下
我之前很早就在 custom.conf 加入了参数 force-AAAA-SOA yes
Win10 上 Flush DNS 后在 CMD 中测试 nslookup 了好几个国外地址
唯独 netflix 会返回一个 IPv4 地址和多个 IPv6 地址
`>nslookup netflix.com
Server:  Openwrt.lan
Address:  10.10.10.1

Non-authoritative answer:
Name:    netflix.com
Addresses:  2a01:578:3::22fa:3d7d
          2a01:578:3::3410:e72b
          2a01:578:3::369a:5167
          2a01:578:3::22fd:10b
          2a01:578:3::22f6:89a8
          2a01:578:3::364c:9f12
          2a01:578:3::341e:3b51
          2a01:578:3::34d3:5e91
          35.161.95.70`
`>nslookup google.com
Server:  Openwrt.lan
Address:  10.10.10.1

Non-authoritative answer:
DNS request timed out.
    timeout was 2 seconds.
Name:    google.com
Address:  8.7.198.46`

`>nslookup youtube.com
Server:  Openwrt.lan
Address:  10.10.10.1

Non-authoritative answer:
Name:    youtube.com
Address:  172.217.160.78`

`>nslookup facebook.com
Server:  Openwrt.lan
Address:  10.10.10.1

Non-authoritative answer:
Name:    facebook.com
Address:  31.13.64.35`

路由器是x86 Koolshare LEDE 2.32
SmartDNA v31，系统上有 20190110-1 版的 ca-bundle

**Comment by pymumu** [comment]
你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。

你的情况，大概率IPV6的查询没走smartdns。

**Comment by roycho93** [comment]
> 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> 
> 你的情况，大概率IPV6的查询没走smartdns。

感谢回复，上面是回复的我的情况吗？我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
服务器: OpenWrt.lan
Address: fdb8:f4a4:4c36::1
*** OpenWrt.lan 找不到 smartdns: Non-existent domain

后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？

我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？

**Comment by railjty** [comment]
> > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > 你的情况，大概率IPV6的查询没走smartdns。
> 
> 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> 服务器: OpenWrt.lan
> Address: fdb8:f4a4:4c36::1
> *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> 
> 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> 
> 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？

smartdns没有在ipv6 53端口监听

**Comment by roycho93** [comment]
> > > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > > 你的情况，大概率IPV6的查询没走smartdns。
> > 
> > 
> > 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> > 服务器: OpenWrt.lan
> > Address: fdb8:f4a4:4c36::1
> > *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> > 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> > 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？
> 
> smartdns没有在ipv6 53端口监听

请问如何开启ipv6 53端口监听？

**Comment by railjty** [comment]
> > > > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > > > 你的情况，大概率IPV6的查询没走smartdns。
> > > 
> > > 
> > > 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> > > 服务器: OpenWrt.lan
> > > Address: fdb8:f4a4:4c36::1
> > > *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> > > 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> > > 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？
> > 
> > 
> > smartdns没有在ipv6 53端口监听
> 
> 请问如何开启ipv6 53端口监听？

先找到占用[::]53的程序，然后如下配置
![image](https://user-images.githubusercontent.com/30927889/80916152-8df68200-8d89-11ea-99f0-3969f2674225.png)

**Comment by roycho93** [comment]
> > > > > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > > > > 你的情况，大概率IPV6的查询没走smartdns。
> > > > 
> > > > 
> > > > 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> > > > 服务器: OpenWrt.lan
> > > > Address: fdb8:f4a4:4c36::1
> > > > *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> > > > 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> > > > 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？
> > > 
> > > 
> > > smartdns没有在ipv6 53端口监听
> > 
> > 
> > 请问如何开启ipv6 53端口监听？
> 
> 先找到占用[::]53的程序，然后如下配置
> ![image](https://user-images.githubusercontent.com/30927889/80916152-8df68200-8d89-11ea-99f0-3969f2674225.png)

感谢回复，抱歉小白不是很懂上面的内容，我用netstat -pan | grep 53查询貌似是dnsmasq占用的ipv6的53端口，请问您是如何从我的描述中判断出我的ipv6 53端口被占用的？

**Comment by railjty** [comment]
> > > > > > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > > > > > 你的情况，大概率IPV6的查询没走smartdns。
> > > > > 
> > > > > 
> > > > > 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> > > > > 服务器: OpenWrt.lan
> > > > > Address: fdb8:f4a4:4c36::1
> > > > > *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> > > > > 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> > > > > 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？
> > > > 
> > > > 
> > > > smartdns没有在ipv6 53端口监听
> > > 
> > > 
> > > 请问如何开启ipv6 53端口监听？
> > 
> > 
> > 先找到占用[::]53的程序，然后如下配置
> > ![image](https://user-images.githubusercontent.com/30927889/80916152-8df68200-8d89-11ea-99f0-3969f2674225.png)
> 
> 感谢回复，抱歉小白不是很懂上面的内容，我用netstat -pan | grep 53查询貌似是dnsmasq占用的ipv6的53端口，请问您是如何从我的描述中判断出我的ipv6 53端口被占用的？

这里比较明显可以发现是OpenWRT自己的DNS服务器，解析不了smartdns且服务器是OpenWRT.lan

![image](https://user-images.githubusercontent.com/30927889/80916469-77512a80-8d8b-11ea-85af-3be43a765ce0.png)
另外我把smartdns安装在光猫上，也遇到自带的dnsforward占用端口的情况（有点类似）

**Comment by roycho93** [comment]
> > > > > > > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > > > > > > 你的情况，大概率IPV6的查询没走smartdns。
> > > > > > 
> > > > > > 
> > > > > > 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> > > > > > 服务器: OpenWrt.lan
> > > > > > Address: fdb8:f4a4:4c36::1
> > > > > > *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> > > > > > 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> > > > > > 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？
> > > > > 
> > > > > 
> > > > > smartdns没有在ipv6 53端口监听
> > > > 
> > > > 
> > > > 请问如何开启ipv6 53端口监听？
> > > 
> > > 
> > > 先找到占用[::]53的程序，然后如下配置
> > > ![image](https://user-images.githubusercontent.com/30927889/80916152-8df68200-8d89-11ea-99f0-3969f2674225.png)
> > 
> > 
> > 感谢回复，抱歉小白不是很懂上面的内容，我用netstat -pan | grep 53查询貌似是dnsmasq占用的ipv6的53端口，请问您是如何从我的描述中判断出我的ipv6 53端口被占用的？
> 
> 这里比较明显可以发现是OpenWRT自己的DNS服务器，解析不了smartdns且服务器是OpenWRT.lan
> 
> ![image](https://user-images.githubusercontent.com/30927889/80916469-77512a80-8d8b-11ea-85af-3be43a765ce0.png)
> 另外我把smartdns安装在光猫上，也遇到自带的dnsforward占用端口的情况（有点类似）,当时就想到直接kill掉那个东西

您说的这里是我用win的cmd输入nslookup -querytype=ptr smartdns得到的返回结果，用mac的终端输入就能正常返回name为smartdns

**Comment by yubanmeiqin9048** [comment]
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  fdcd:ae72:a84e::1

DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时
我并没有开启IPV6，如何手动绑定Address

**Comment by yubanmeiqin9048** [comment]
C:\Users\zhang>nslookup www.twitter.com
服务器:  OpenWrt.lan
Address:  fdcd:ae72:a84e::1

非权威应答:
名称:    twitter.com
Addresses:  104.244.42.65
          104.244.42.1
Aliases:  www.twitter.com
解析推特的时候是失败的，返回不正确的地址，导致推特无法使用
上游服务器是谷歌，open，诺顿，watch，comodo

**Comment by yutian33** [comment]
> > > > > > > > 你可能中间插入了其他dns服务器了。最好搞清楚经过了几个dns服务器，从流程上排查一遍。
> > > > > > > > 你的情况，大概率IPV6的查询没走smartdns。
> > > > > > > 
> > > > > > > 
> > > > > > > 感谢回复，上面是回复的我的情况吗？应该没有开别的dns服务器。我是win的cmd下输入nslookup -querytype=ptr smartdns，返回
> > > > > > > 服务器: OpenWrt.lan
> > > > > > > Address: fdb8:f4a4:4c36::1
> > > > > > > *** OpenWrt.lan 找不到 smartdns: Non-existent domain
> > > > > > > 后来用mac的终端试了下，nslookup -querytype=ptr smartdns，返回的name是smartdns，这样是正常的对吧？
> > > > > > > 我的第二DNS服务器中开启了Force AAAA SOA，因为即使开启双栈优选，netflix还是会直接用ipv6直接连接而跳过ipv4代理，所以索性关闭了IPV6解析，想问问有办法优先ipv4解析吗？
> > > > > > 
> > > > > > 
> > > > > > smartdns没有在ipv6 53端口监听
> > > > > 
> > > > > 
> > > > > 请问如何开启ipv6 53端口监听？
> > > > 
> > > > 
> > > > 先找到占用[::]53的程序，然后如下配置
> > > > ![image](https://user-images.githubusercontent.com/30927889/80916152-8df68200-8d89-11ea-99f0-3969f2674225.png)
> > > 
> > > 
> > > 感谢回复，抱歉小白不是很懂上面的内容，我用netstat -pan | grep 53查询貌似是dnsmasq占用的ipv6的53端口，请问您是如何从我的描述中判断出我的ipv6 53端口被占用的？
> > 
> > 
> > 这里比较明显可以发现是OpenWRT自己的DNS服务器，解析不了smartdns且服务器是OpenWRT.lan
> > ![image](https://user-images.githubusercontent.com/30927889/80916469-77512a80-8d8b-11ea-85af-3be43a765ce0.png)
> > 另外我把smartdns安装在光猫上，也遇到自带的dnsforward占用端口的情况（有点类似）,当时就想到直接kill掉那个东西
> 
> 您说的这里是我用win的cmd输入nslookup -querytype=ptr smartdns得到的返回结果，用mac的终端输入就能正常返回name为smartdns

会不会是你mac没有启用ipv6？

**Comment by pymumu** [comment]
please free free to reopen this issue.
