### ISSUE TITLE
换了n1，同样的smartdns配置，ipset规则却时不时没生效

### ISSUE THREAD

**Issue by o0HalfLife0o** [pymumu/smartdns#492]
**问题现象**  
简要描述问题出现的现象
从k2p换到n1，同样的smartdns配置，ipset规则却时不时没生效，匹配到的域名ip经常没有成功添加到ipset规则里
比如www.****.com解析到的66.254.114.41，就没有添加成功
但是www.cnn.com解析到的151.101.65.67又添加成功了

**运行环境**
1. 固件型号  
Phicomm N1 OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)  5.6.7-flippy-35+

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
www.****.com

**信息收集**  

系统日志里有很多这个错误，以前k2p时没有出现过，不知是否有关
> Sun May  3 08:22:19 2020 kern.warn kernel: [42814.719588] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:28 2020 kern.warn kernel: [42823.631667] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:28 2020 kern.warn kernel: [42824.201989] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:29 2020 kern.warn kernel: [42824.912439] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:29 2020 kern.warn kernel: [42825.102279] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:30 2020 kern.warn kernel: [42825.578906] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:32 2020 kern.warn kernel: [42827.756749] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:32 2020 kern.warn kernel: [42827.791697] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:33 2020 kern.warn kernel: [42828.786977] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:38 2020 kern.warn kernel: [42834.509368] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:22:39 2020 kern.warn kernel: [42834.735101] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:23:28 2020 kern.warn kernel: [42883.882866] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:23:29 2020 kern.warn kernel: [42884.701948] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:33:58 2020 kern.warn kernel: [43514.083838] netlink: 'smartdns': attribute type 6 has an invalid length.
> Sun May  3 08:33:58 2020 kern.warn kernel: [43514.104874] netlink: 'smartdns': attribute type 6 has an invalid length.

**Comment by pymumu** [comment]
ipset-timeout yes
去掉试试，可能内核没开启，或支持ipset超时功能。

**Comment by o0HalfLife0o** [comment]
测试了多个不同的网站，似乎解决了，谢谢。

**Comment by o0HalfLife0o** [comment]
@pymumu 想问下大佬，最新代码的domain-rule中关闭测速功能是不是还没做好，因为我发现我配置里的那些域名全是单个ip，但log里还是有测速这个过程
