### ISSUE TITLE
关于国内网站精准分流问题

### ISSUE THREAD

**Issue by LittleGrocery** [pymumu/smartdns#493]
目前设置如下:
dnsmasq-chinalist,默认组排除-国内上游dns服务器组
ignore-ip.(忽略中国ip，强制所有中国ip走国内dns组)-国外上游dns组

设置国外服务器忽略国内ip原本是想让所有dnsmasq-chinalist的国内漏网之鱼都走国内上游dns，问题是这样由于默认组排除了国内服务器，这些国内漏网之鱼就变成国内外上游都得不到结果，但是不排除的话又可能会让国外的漏网之鱼走了国内的上游服务器进行解析，请问如何解决这个问题呢？
说得有点乱，见谅！

**Comment by pymumu** [comment]
配置IP地址黑白名单，IP地址列表可以从CHROUTE获取。
国内外DNS都发送请求，缺点是请求dns隐私受影响。
