### ISSUE TITLE
smartDNS未运行

### ISSUE THREAD

**Issue by 18690819111** [pymumu/smartdns#494]
**问题现象**  
简要描述问题出现的现象
smart一直未运行状态
**运行环境**
1. 固件型号  X86

2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
运营商、114、谷歌、open
2. 访问的域名。  

**信息收集**  

未能生成日志文件，因为无论怎么设置都是未运行状态，之前新装固件时间同样问题查阅资料显示缺少ibopenssl文件，安装之后就好了，这次因为重新刷机，同样安装后无法正常使用，请大神帮忙解决一下。

**Comment by pymumu** [comment]
使用最新版本看看，如还有问题reopen issue，贴上日志
