### ISSUE TITLE
最新版本Release修改上游服务器会报错

### ISSUE THREAD

**Issue by gimgoo** [pymumu/smartdns#496]
在已有的上游服务器列表中，点击修改某个DNS，会出现一下报错。
![image](https://user-images.githubusercontent.com/31849284/80914165-68af4700-8d7c-11ea-8a07-0c2ad2a11599.png)

与运营商，系统无关。

**Comment by roycho93** [comment]
试了下确认到同样问题，应该要等待大佬更新了

**Comment by railjty** [comment]
去对应的OpenWRT包作者那里去提问题，这里只是服务端

**Comment by GimmGoo** [comment]
> 去对应的OpenWRT包作者那里去提问题，这里只是服务端

不懂装懂是个很可怕的问题，脑子是个好东西，希望你也有

**Comment by roycho93** [comment]
> 去对应的OpenWRT包作者那里去提问题，这里只是服务端

作者当天已经重新发布修正这个问题了

**Comment by railjty** [comment]
> > 去对应的OpenWRT包作者那里去提问题，这里只是服务端
> 
> 不懂装懂是个很可怕的问题，脑子是个好东西，希望你也有

也许我只是直接用smartdns的后端服务然后没看到ipk吧，但是没遇到问题，OpenWRT就抱歉没看明白了

**Comment by railjty** [comment]
> > 去对应的OpenWRT包作者那里去提问题，这里只是服务端
> 
> 作者当天已经重新发布修正这个问题了

确实，抱歉没看明白

**Comment by pymumu** [comment]
please free free to reopen this issue.
