### ISSUE TITLE
关于双栈优选功能慢的问题

### ISSUE THREAD

**Issue by roycho93** [pymumu/smartdns#497]
**问题现象**  
之前的#491issue后面提到了这个问题但是有点乱麻烦老大关闭了我重新开个好让老大看得清爽点。
我目前用smartdns配合passwall使用，重定向是作为dnsmsq的上游服务器，在固件的DNS转发中也设置了127.0.0.1#6053，设置了第二DNS服务器，设置如下
![FireShot Capture 004 - OpenWrt - SmartDNS - LuCI - 192 168 88 1](https://user-images.githubusercontent.com/50717235/80917482-b71b1080-8d91-11ea-913f-c9e5955b7e85.png)

![FireShot Capture 003 - OpenWrt - SmartDNS - LuCI - 192 168 88 1](https://user-images.githubusercontent.com/50717235/80917447-83d88180-8d91-11ea-8b76-ed9681a395b1.png)

passwall中dns模式为使用本机7913端口的DNS

目前我的困扰就是netflix在不用smartdns的情况下会直接使用ipv6直接连接，导致没有通过代理，于是想通过smartdns的双栈优选功能（我的理解是优先ipv4？还是检测哪个速度快连哪个？），在目前的设置中打开国外的双栈网站（国内不清楚哪些是双栈网站故未测试）速度比较慢，netflix确实可以通过ipv4访问，于是使用win的cmd 输入nslookup netflix.com youtube.com google.com等网站查询，发现除google外，通通有DNS request timed out.timeout was 2 seconds.的提示，导致解析变慢，所以想问一下有
1.办法使双栈优选下速度变快吗？
2.双栈优选的含义也不太明白，是优先ipv4呢还是ipv4与ipv6中选择最快速度的进行连接?
3.我目前dns服务器列表中只有ipv4服务器，对使用会有影响吗？

谢谢

**Comment by pymumu** [comment]
双栈优选，功能就是IPv4, IPv6之间选择ping值小的IP。

功能是，在请求IPV6地址时，同时查询IPv4地址，并进行测速，如果IPV6的速度慢于IPV4，则返回SOA。客户端会使用IPV4。
但不清楚你说的问题。

你可以尝试使用
address /xx.com/#6
来屏蔽特定域名的IPV6解析。

**Comment by roycho93** [comment]
> 双栈优选，功能就是IPv4, IPv6之间选择ping值小的IP。
> 
> 功能是，在请求IPV6地址时，同时查询IPv4地址，并进行测速，如果IPV6的速度慢于IPV4，则返回SOA。客户端会使用IPV4。
> 但不清楚你说的问题。
> 
> 你可以尝试使用
> address /xx.com/#6
> 来屏蔽特定域名的IPV6解析。

请问是在smartdns的自定义设置中直接把address /xx.com/#6加在最后保存就可以吗？

**Comment by pymumu** [comment]
对，

smartdns上游是否有IPv6地址的服务器没有约束。没有也不妨碍IPv6地址解析。
但如果你有IPV6网络，那么smartdns要开启IPV6查询支持。

也就是配置  
bind [::]:6053  

而不是配置  
bind :6053  

这些使用luci界面的话，都应该时自动完成的。

**Comment by pymumu** [comment]
看了你的问题描述，感觉应该是你搞错了。
1. 如果配置`作为dnsmasq上游`的话，无需单独启用IPV6服务器。
2. smartdns的双栈优选，不会有超时的情况。

你可能将dnsmasq配置了国内外分流，国内走了smartdns，国外地址可能没有走smartdns。
你执行nslookup某些国外地址时，应该使用了国外的服务器。

你可以排查一下。

**Comment by roycho93** [comment]
> 看了你的问题描述，感觉应该是你搞错了。
> 
> 1. 如果配置`作为dnsmasq上游`的话，无需单独启用IPV6服务器。
> 2. smartdns的双栈优选，不会有超时的情况。
> 
> 你可能将dnsmasq配置了国内外分流，国内走了smartdns，国外地址可能没有走smartdns。
> 你执行nslookup某些国外地址时，应该使用了国外的服务器。
> 
> 你可以排查一下。

感谢老大花时间查看我的问题，确实设置了分流，但是国外应该是设置走了smartdns的，smartdns的第二dns服务器中设置端口为7913，passwall的国内dns服务器(udp)设置为“127.0.0.1#6053”，dns模式设置为“本机7913端口”，在smartdns的第二dns服务器中设置Force AAAA SOA与跳过双栈优选打勾时netflix可以很快直接访问到ipv4地址，取消打勾Force AAAA SOA就会直接访问ipv6网站，相关设置可以生效，所以应该是国外地址走了smartdns。当把Force AAAA SOA与跳过双栈优选取消打勾时，可以访问到ipv4的netflix，只是比较慢，win的cmd使用nslookup netflix youtube就会出现查询超时的情况，但是google不会超时，所以我才会以为是ipv6的dns服务器有问题，才会问老大是不是上游dns服务器得添加一些国内外的公共ipv6服务器，目前添加了还是一样的症状。。。

**Comment by pymumu** [comment]
把你nslookup的全命令查询截图发一下。

**Comment by roycho93** [comment]
> 把你nslookup的全命令查询截图发一下。

以下是第二DNS服务器中“跳过双栈优选”与“Force AAAA SOA”不打勾的情况下的nslookup命令截图
![QQ图片20200503230756](https://user-images.githubusercontent.com/50717235/80920490-d2dae280-8da2-11ea-9655-7cba0e514b12.png)

**Comment by pymumu** [comment]
修改一下smartdns的日志级别为debug
再进行一次相同的查询，

查询完成后，将/var/log/smartdns.log发一下。

**Comment by roycho93** [comment]
[smartdns.log](https://github.com/pymumu/smartdns/files/4571089/smartdns.log)
已上传请查看

**Comment by pymumu** [comment]
要开debug日志。
log-level debug

**Comment by roycho93** [comment]
> 要开debug日志。
> log-level debug

抱歉，貌似修改日志级别为debug后再次查看又变为error级别，luci中关闭了smartdns后再修改还是一样，我是用winscp直接在var/etc/smartdns/smartdns.conf中修改，是否正确？

**Comment by pymumu** [comment]
在自定义配置里面修改。

**Comment by roycho93** [comment]
再次上传请查看

[smartdns.log](https://github.com/pymumu/smartdns/files/4571204/smartdns.log)

**Comment by pymumu** [comment]
没看到有请求到smartdns，你还是排查请求到smartdns之前有哪些服务在处理请求把。

**Comment by roycho93** [comment]
把已知可能干扰的东西都关闭了。
在同一台iMac机器的win上使用nslookup后会超时，mac系统的终端中同样命令不会超时，但是只能返回ipv4结果，查询纯ipv6网站的ip也查询不到，浏览器是可以正常访问纯ipv6，win的cmd中查询同样纯ipv6网站会有返回结果。另外mac终端中输入nslookup -querytype=ptr smartdns，name名称会返回smartdns，并且smartdns的设置有效影响着客户端，不管是win还是mac，我再上传一次两个系统中都nslookup过的日志，实在找不出原因有也没有办法了，也不影响日常使用，谢谢大佬啦。
[smartdns.log](https://github.com/pymumu/smartdns/files/4571336/smartdns.log)

**Comment by roycho93** [comment]
现在又出现google不会超时别的会超时的情况了 我再传一个log看看
[smartdns.log](https://github.com/pymumu/smartdns/files/4571350/smartdns.log)

**Comment by roycho93** [comment]
试着把跳过双栈优选打勾，Force AAAA SOA不打勾，就不会有超时问题了，并且日志中出现了我要查询的域名。日志附上烦请查看。
[smartdns.log](https://github.com/pymumu/smartdns/files/4571369/smartdns.log)

**Comment by pymumu** [comment]
几个问题：
1. 同样dns服务器，没有必要同时配置udp和tcp两种协议。
2. 你的环境，tcp协议估计被做了转发处理了。只有208.67.xxx.xxx, 8.8.x.xIP是可以连接，其他都是失效的。且连接的是你本地的代理。而不是远端真正的服务器。
3. 看了你所有查询记录，都没有查询过ipv6的地址，除了hk-27.mitsuha-node.com域名。

所以，可能是你dnsmasq中间做了处理，或有其他软件将53端口的请求单独处理了。

**Comment by roycho93** [comment]
您好，第一个问题是说上游dns服务器填写时没有必要像图中这样udp跟tcp都进行设置吗？那如何设置最好呢？
<img width="1147" alt="屏幕快照 2020-05-04 上午11 31 13" src="https://user-images.githubusercontent.com/50717235/80934468-e74ac980-8dfa-11ea-8815-008ca0a3e4d4.png">
第二个问题有可能的原因是什么？跟passwall可能有关系吗？208.67.xxx.xxx, 8.8.x.xIP应该是opendns跟google的dns服务器地址
第三个问题中hk-27.mitsuha-node.com是passwall当前正在使用代理服务器的域名

按照我目前的设置应该只是将smartdns作为了dnsmasq的上游服务器，没有别的设置。所描述的超时问题也只有在跳过双栈优选打勾，Force AAAA SOA不打勾的情况下发生，smartdns应该是及时响应了我所做的设置，试过address /xx.com/#6能解决我目前的需求，只是觉得这个现象有点奇怪，不应该会有别的软件干扰了。

**Comment by roycho93** [comment]
目前我把passwall的dns设置改成图中chindns-ng模式，并手动指定为第二dns端口后问题似乎得到解决，原来dns模式为使用本机7913端口的dns我也是按照别人教程设置，没想到会有问题。
![FireShot Capture 006 - OpenWrt - 基本设置 - LuCI - 192 168 88 1](https://user-images.githubusercontent.com/50717235/80935634-1a438c00-8e00-11ea-8cfd-90eb81e6d4be.png)
改变模式后再次查询的日志如有空请查看
[smartdns.log](https://github.com/pymumu/smartdns/files/4572734/smartdns.log)

**Comment by pymumu** [comment]
1. 这种是错误的配置。国内建议用udp，国外用tls/https。若是移动，考虑国内tcp。同一个地址，配置多种协议，一般没有必要。
2. 可能是处理的tcp协议的。你可以看看你的ipset规则。

**Comment by roycho93** [comment]
原来如此，如果同一个地址同时配置udp与tcp可能会有什么不好的影响吗？因为我是移动，所以最好国内都配置成tcp对吗

**Comment by roycho93** [comment]
> 1. 这种是错误的配置。国内建议用udp，国外用tls/https。若是移动，考虑国内tcp。同一个地址，配置多种协议，一般没有必要。
> 2. 可能是处理的tcp协议的。你可以看看你的ipset规则。

我的防火墙中不知道为何有如下两条自定义规则，会不会是这个的影响？
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

**Comment by o0HalfLife0o** [comment]
@roycho93 这两条规则会干扰，我之前刚换n1，用的lean的固件，就是各种dns解析的问题，后来才发现好多问题都是这两条导致的，注释掉，就好了

**Comment by pymumu** [comment]
please free free to reopen this issue.
