### ISSUE TITLE
R31版本安装后，没有luci界面

### ISSUE THREAD

**Issue by crackerfly** [pymumu/smartdns#498]
**问题现象**  
安装：

1. smartdns.1.2020.05.03-1702.arm-openwrt-all.ipk
2. luci-app-smartdns.1.2020.05.03-1702.all-luci-all.ipk

之后，Luci下没有services 菜单，之前安装 Release 30 是正常的。

经测试混装：
1. smartdns.1.2020.05.03-1702.arm-openwrt-all.ipk
2. luci-app-smartdns.1.2020.02.25-2212.all-luci-all.ipk

可以正常出现 services -> smartdns 菜单

**运行环境**
固件版本：19.07.2
硬件型号：Netgear R8000

2. 运营商  
中国电信(与问题无关联)

**重现步骤**
1. 删除旧版smartdns
opkg remove luci-app-smartdns
opkg remove smartdns

2. 重启路由器、删除 etc/config/smartdns ; etc/smartdns, 后重新安装新版 smartdns 
opkg install smartdns.xxxxxxxx.xxxx.ipk
opkg install luci-app-smartdns.xxxxxxxx.xxxx.all.ipk

3. 安装完成后，未能出现 services -> smartdns 菜单
4. 重启路由器重试，问题依旧
5. 保留新版smartdns，尝试替换旧版luci-app-smartdns ，测试成功，正常出现 services -> smartdns 菜单。

**信息收集**  
暂无

**Comment by pymumu** [comment]
用compat版本的luci。非compat版本适配openwrt的最新版本。

**Comment by crackerfly** [comment]
> 用compat版本的luci。非compat版本适配openwrt的最新版本。

我用的就是openwrt最新R版哎🥺

**Comment by pymumu** [comment]
openwrt最新版本，已经全部将lua切换为Javascript了。

你用compat就可以了，功能是一样的。

**Comment by wyjtm** [comment]
出现同样的问题
luci-app-smartdns.1.2020.05.04-0005.all-luci-all 装上没有界面
luci-app-smartdns.1.2020.05.04-0005.all-luci-compat-all 装上可用
OpenWrt 19.07.2

**Comment by MasterThrone** [comment]
@crackerfly  我这边19.07.2装luci-all没菜单,装luci-compat有菜单,但是报错说没有smartdns.js文件,从github上面在本地添加js文件就能用了.
@pymumu 安装完以后目录的所有人不是root:root

**Comment by pymumu** [comment]
openwrt最新版本已经完全去掉了lua了，如果不是最新的openwrt，安装compt版本，再安装luci-compat就可以了

**Comment by crackerfly** [comment]
打扰问一下，您说的’最新版’ 是指稳定版分支下最新的19.07.2嘛？

**Comment by pymumu** [comment]
2月份或3月份之后的版本，不是想折腾的话，直接用compat版本就好了
或用上一个版本也是可以的，只是不能配置TLS证书校验而已。

**Comment by pymumu** [comment]
使用最新版本看看，如还有问题reopen issue，贴上日志

**Comment by crackerfly** [comment]
伟大的作者您好，这个问题r31版本后来我发现原因并解决了。
原因：chrome 不刷新页面缓存，即使手动刷新页面也无用
解决方法：清理浏览器缓存或使用无痕模式打开
