### ISSUE TITLE
Lean 版竞斗云固件安装0504版smartdns，luci 界面出现问题

### ISSUE THREAD

**Issue by kiss2u** [pymumu/smartdns#499]
**问题现象**  

Lean 版竞斗云固件 安装 Smartdns，选取：

1. luci-app-smartdns.1.2020.05.04-0005.all-luci-compat-all.ipk
2. smartdns.1.2020.05.04-0005.arm-openwrt-all.ipk

上传插件，卸载原有安装包，顺次安装后运行，点击 dns 单项“修改” 时，luci 界面出现问题：
[截图](https://user-images.githubusercontent.com/31849284/80914165-68af4700-8d7c-11ea-8a07-0c2ad2a11599.png)

**运行环境**
1. 主机型号：P&W R619AC 128M
2. 系统架构：ARMv7 Processor rev 5 (v7l) x 4 
3. 固件版本：Lean版 OpenWrt R20.4.8 / LuCI Master (git-20.117.60969-420c61a) 

**重现步骤**
详见 **问题现象**  

**信息收集**  
详见 **问题现象**

**Comment by pymumu** [comment]
版本有刷新过，目前release提供的软件没有问题，重新下载安装把。

**Comment by GimmGoo** [comment]
> 版本有刷新过，目前release提供的软件没有问题，重新下载安装把。

大佬，很多人都遇到这个问题，不止他一个

**Comment by kiss2u** [comment]
> 版本有刷新过，目前release提供的软件没有问题，重新下载安装把。

新版测试多次，问题依旧。包括用scripts build 命令生成的 ipk 也无法使用，问题一样。

**Comment by pymumu** [comment]
openwrt最新版本已经完全去掉了lua了，如果不是最新的openwrt，先安装luci-compat，再安装安装luci-app-smartdns-compat就可以了

19.07在切换javascript时，有版本是要求luci-app-smartdns同时有luci和javascript。

**Comment by pymumu** [comment]
please free free to reopen this issue.
