### ISSUE TITLE
除了监听的端口，还有另外3个端口是什么？

### ISSUE THREAD

**Issue by cjjdaq** [pymumu/smartdns#5]
[root@host ~]# netstat -luntp|grep smart
udp        0      0 0.0.0.0:51758           0.0.0.0:*                           17388/smartdns      
udp        0      0 127.0.0.1:53            0.0.0.0:*                           17388/smartdns      
udp        0      0 0.0.0.0:58238           0.0.0.0:*                           17388/smartdns      
udp        0      0 0.0.0.0:53194           0.0.0.0:*                           17388/smartdns

**Comment by pymumu** [comment]
每配置一个DNS服务器，会相应的创建一个客户端。
你这配置了3个DNS服务器。

**Comment by cjjdaq** [comment]
还是建议添加tcp监听，装在国外vps上，国内路由上还是得用tcp查询方便点。直接udp污染，走通道会慢很多。直接tcp反而比较快。
