### ISSUE TITLE
doh  dot

### ISSUE THREAD

**Issue by kl9800** [pymumu/smartdns#500]
**需求应用场景**
看到了最新版本，支持dot/h，很激动，
我想问问，如果我把smartdns架设在我自己的服务器上，怎么调成tls模式？
我的目的是走tls访问自己的dns

**建议的方案**
无

**设备信息**
1. 设备信息（CPU，厂家）  
   我的服务端是centos7
2. 固件信息
    客户端是j1900  x86  64

**Comment by rampageX** [comment]
smartdns 是支持做 dot/h 客户端，而不是服务端。

**Comment by showgood163** [comment]
服务端dot/doh是有意义的。国内这个环境下，没有加密dns请求，连为自己提供公网解析都没法做到。
