### ISSUE TITLE
黑白名单的疑惑

### ISSUE THREAD

**Issue by zhaozhejun** [pymumu/smartdns#503]
server 119.28.28.28    -blacklist-ip -whitelist-ip  -check-edns  -group china
server   8.8.8.8  -blacklist-ip -check-edns  -group out
白名单用设置的国内ip段，黑名单是返回的没用ip
第一组是 国内ip都用119进行解析并过滤黑名单ip段  可以这么理解吗？
疑惑一、正常大部分解析不是从域名解析的吗，在不知道返回ip到底是国内还是国外ip的情况下，那么白名单的作用是？
疑惑二、白名单已经是国内ip段了，但是解析返回黑名单的话，他会过滤，并继续重新解析吗？
疑惑三、配置参数里好像有某些网站nameserver /www.example.com/china  这种进行解析经常访问网站，效果是不是更好些，毕竟非常规网站，也不太考虑他返回的速度。

**Comment by pymumu** [comment]
白名单是指，值接受指定IP地址范围内的结果， 黑名单就是对应名单中的结果，全部丢弃。
是两个相反的列表。  

最简单就是国内用白名单。列表用CHNROUTE
国外走TLS
