### ISSUE TITLE
wsl安装的smartdns过一段时间服务会掉

### ISSUE THREAD

**Issue by TUT123456** [pymumu/smartdns#509]
**问题现象**  
简要描述问题出现的现象

    运行一段时间后，会出现无法联网，用 nslookup -querytype=ptr smartdns后发现 server unknow，看起来是进程被杀了，点击D:\smartdns\package\windows\reload.bat后恢复正常，这情况会经常出现，启动项是打开的。

**运行环境**

Windows WSL

**重现步骤**

运行一段时间随机发生

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。 
[smartdns.log](https://github.com/pymumu/smartdns/files/4605202/smartdns.log) 
(10点到12点的期间就是服务停止的时间段)
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
WSL下如何生成coredump呀，我下次出现这种情况就添加上

**Comment by pymumu** [comment]
看看用release 30有没有问题。

**Comment by TUT123456** [comment]
嗯，我试试，有问题再反馈。

**Comment by yeezylife** [comment]
> 看看用release 30有没有问题。

我用的最新release 31  一周了没这情况。。  win10最新专业版 64位 非ghost精简系统

**Comment by TUT123456** [comment]
> > 看看用release 30有没有问题。
> 
> 我用的最新release 31 一周了没这情况。。 win10最新专业版 64位 非ghost精简系统

也许是我这里环境问题，我在找原因，不过我不懂怎么拿到进程的运行日志。

**Comment by TUT123456** [comment]
我发现从“睡眠”中唤醒会出现这种情况，可能在“睡眠”的时候wsl进程被杀了，有没有可能在vbs文件中加入cron命令来周期的唤醒smartdns进程。

**Comment by TUT123456** [comment]
最近发现可能是clash for windows也监听53端口，冲突导致的。
