### ISSUE TITLE
lean openwrt R20.5.9 下luci界面样式异常

### ISSUE THREAD

**Issue by zyc199847** [pymumu/smartdns#510]
**问题现象**  
lean openwrt R20.5.9下luci界面样式异常，R20.4.8版样式正常，推测与新版lean固件的luci配置有关。可能与issue #499 有关。

R20.4.8版lean固件不允许安装luci-compat，compat版luci-app-smartdns样式正常。R20.5.9安装luci-compat后luci组件异常（Insufficient permissions to read UCI configuration），但是需要luci-compat依赖的app可以在未安装luci-compat依赖时正常使用。

异常样式截图：
![1](https://user-images.githubusercontent.com/14220017/81497911-3c537780-92f4-11ea-89f3-302b97dd1dfd.png)
![2](https://user-images.githubusercontent.com/14220017/81497913-3e1d3b00-92f4-11ea-9651-7d9dfcf74125.png)
![3](https://user-images.githubusercontent.com/14220017/81497915-407f9500-92f4-11ea-9391-df0acdeac5d1.png)
![4](https://user-images.githubusercontent.com/14220017/81497916-42e1ef00-92f4-11ea-8231-a6b7157f2025.png)

**运行环境**
1. 固件型号  
OpenWrt R20.5.9 / LuCI Master (git-20.117.60969-420c61a)
luci-app-smartdns.1.2020.05.04-0005.all-luci-compat-all.ipk
smartdns.1.2020.05.04-0005.x86_64-openwrt-all.ipk

**重现步骤**
NA

**信息收集**  
NA

**Comment by pymumu** [comment]
这个不是smartdns本身的问题，你可以提交issue给固件维护人。

**Comment by robin20200222** [comment]
OpenWrt R20.5.9 / LuCI Master  请问密码是多少钱  用户名是root   密码是多少 我的一直都进不去呀
