### ISSUE TITLE
tls、https用不了

### ISSUE THREAD

**Issue by ztjal** [pymumu/smartdns#511]
**问题现象**  
长期问题了……

**运行环境**
1. 固件型号  
smartdns.1.2020.05.04-0005.mipsel-openwrt-all

2. 运营商  
电信

**重现步骤**
1. 上游DNS配置。  

server-tls 8.8.4.4:853 -group gfw -exclude-default-group
server-tls 1.1.1.1:853 -group gfw -exclude-default-group
server-tls 1.0.0.1:853 -group gfw -exclude-default-group
server-https https://dns.google/dns-query -group gfw -exclude-default-group
server-https https://cloudflare-dns.com/dns-query -group gfw -exclude-default-group
#server-https https://security.cloudflare-dns.com/dns-query -group gfw -exclude-default-group
server-https https://i.233py.com/dns-query -group gfw -exclude-default-group

nameserver /pixiv.net/gfw

2. 访问的域名。  

www.pixiv.net

**信息收集**  
[smartdns.zip](https://github.com/pymumu/smartdns/files/4605674/smartdns.zip)

**Comment by pymumu** [comment]
你的DOT就无法建立连接，你可以尝试用telnet 连接一下1.0.0.1:853看看能否正常。

看smartdns日志，你配置的TLS无法建立通信。

**Comment by anafkk** [comment]
@pymumu 我和提问者一样的问题和 log（tls server connecting），telnet 连接 DoT 地址正常，且相同的配置 2019.12.15 的 release 版本（28、29）就可以，新版就不行，安装 ca-bundle 、停用证书校验的办法都试了，都不行

**Comment by pymumu** [comment]
打开debug，发出问题的日志

**Comment by ztjal** [comment]
TLS肯定有问题，我现在用LEAN的源码编译了一个固件，全新刷机，刷完马上装了SMDNS，规则什么都没改，继续ping www.pixiv.net，还是不行。（ca-bundle，ca-certificates固件化了）

[smartdns.zip](https://github.com/pymumu/smartdns/files/4623713/smartdns.zip)

@pymumu

**Comment by pymumu** [comment]
用早先的版本看看能否用

**Comment by ztjal** [comment]
我手头上保存的三个版本
smartdns.1.2020.05.04-0005.mipsel-openwrt-all，不行
smartdns.1.2020.02.25-2212.mipsel-openwrt-all，不行
smartdns.1.2019.11.02-1102.mipsel-openwrt-all，成功解释到TLS了
@pymumu

**Comment by pymumu** [comment]
可能是换了编译器导致的
你用自己配套的编译工具编译一个看看吧

**Comment by anafkk** [comment]
@ztjal 我也是 mipsel-openwrt 的包，问题相同，你自己编译 smartdns 的如果 TLS 连接正常，麻烦 share 一下编译环境、工具和 ipk 文件，无比感谢~

**Comment by anafkk** [comment]
> 可能是换了编译器导致的
> 你用自己配套的编译工具编译一个看看吧

@pymumu 您编译后自测没问题吗

**Comment by ztjal** [comment]
自己编译的成功了，TLS正常使用😌
版本是1.2020.30-1
用LEAN的OP源码，加懒人脚本
https://github.com/pymumu/luci-app-smartdns
一齐编译，编译成ipk包再装

@pymumu
把编译器换回去吧……

@anafkk 
我路由是newifi d1，mipsel_24kc，LEAN源码当前内核是4.14.176
编译环境是VMware装ubuntu-18.04.4-desktop-amd64，其它跟着LEAN源码下边的方法做就得

**Comment by anafkk** [comment]
@ztjal 我路由是歌华链 GHL-R-001，mipsel_24kc，内核为 4.14.178，你编译的 ipk 应该可以直装，麻烦 share 下我试下，现在新版 TLS 连不上，只能退回老版很伤 ...

**Comment by ztjal** [comment]
[smartdns-zh-cn_1.2020.30-1_all.zip](https://github.com/pymumu/smartdns/files/4638112/smartdns-zh-cn_1.2020.30-1_all.zip)

@anafkk 
你试下吧，依赖顶
Depends: libc, libpthread, libopenssl1.1

**Comment by anafkk** [comment]
@ztjal 收到 感谢~ 我看下了 依赖项我都有的，另外你是根据 release 30 自编译的、还是最新的 release 31？我看下要不要装 ca-bundle

**Comment by ztjal** [comment]
ca-bundle也装上吧
版本是1.2020.30-1，懒人脚本feeds update回来就是这个东西了，以后怎么更新新版也不知道😂
@anafkk

**Comment by anafkk** [comment]
@ztjal get，想想也是 具体啥版本也是看作者在懒人脚本里拉取了啥，老铁编译的时候选择不了

**Comment by ztjal** [comment]
你在编译？
你先
cd lede
再参考懒人脚本加了，然后再
./scripts/feeds update -a
./scripts/feeds install -a
之后
make menuconfig
在luci里边才会见到
luci-app-smartdns
@anafkk

**Comment by lzx2009vb** [comment]
> 你在编译？
> 你先
> cd lede
> 再参考懒人脚本加了，然后再
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> 之后
> make menuconfig
> 在luci里边才会见到
> luci-app-smartdns
> @anafkk


我也用懒人包，可是用完之后没有在luci里看到这项，是master分支还是lede分支？

**Comment by ztjal** [comment]
> 
> 
> > 你在编译？
> > 你先
> > cd lede
> > 再参考懒人脚本加了，然后再
> > ./scripts/feeds update -a
> > ./scripts/feeds install -a
> > 之后
> > make menuconfig
> > 在luci里边才会见到
> > luci-app-smartdns
> > @anafkk
> 
> 我也用懒人包，可是用完之后没有在luci里看到这项，是master分支还是lede分支？

当然要改成
LUCIBRANCH="lede"

**Comment by lzx2009vb** [comment]
> > > 你在编译？
> > > 你先
> > > cd lede
> > > 再参考懒人脚本加了，然后再
> > > ./scripts/feeds update -a
> > > ./scripts/feeds install -a
> > > 之后
> > > make menuconfig
> > > 在luci里边才会见到
> > > luci-app-smartdns
> > > @anafkk
> > 
> > 
> > 我也用懒人包，可是用完之后没有在luci里看到这项，是master分支还是lede分支？
> 
> 当然要改成
> LUCIBRANCH="lede"

emmm，刚试了下，好像不行。。

**Comment by ztjal** [comment]
> 
> 
> > > > 你在编译？
> > > > 你先
> > > > cd lede
> > > > 再参考懒人脚本加了，然后再
> > > > ./scripts/feeds update -a
> > > > ./scripts/feeds install -a
> > > > 之后
> > > > make menuconfig
> > > > 在luci里边才会见到
> > > > luci-app-smartdns
> > > > @anafkk
> > > 
> > > 
> > > 我也用懒人包，可是用完之后没有在luci里看到这项，是master分支还是lede分支？
> > 
> > 
> > 当然要改成
> > LUCIBRANCH="lede"
> 
> emmm，刚试了下，好像不行。。

./scripts/feeds update -a
./scripts/feeds install -a
他还要下载东西回来啊。

**Comment by lzx2009vb** [comment]
> > > > > 你在编译？
> > > > > 你先
> > > > > cd lede
> > > > > 再参考懒人脚本加了，然后再
> > > > > ./scripts/feeds update -a
> > > > > ./scripts/feeds install -a
> > > > > 之后
> > > > > make menuconfig
> > > > > 在luci里边才会见到
> > > > > luci-app-smartdns
> > > > > @anafkk
> > > > 
> > > > 
> > > > 我也用懒人包，可是用完之后没有在luci里看到这项，是master分支还是lede分支？
> > > 
> > > 
> > > 当然要改成
> > > LUCIBRANCH="lede"
> > 
> > 
> > emmm，刚试了下，好像不行。。
> 
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> 他还要下载东西回来啊。

是的啊，我看了下文件产生的目录 feeds（luci和package）里面都有了

**Comment by ztjal** [comment]
> 
> 
> > > > > > 你在编译？
> > > > > > 你先
> > > > > > cd lede
> > > > > > 再参考懒人脚本加了，然后再
> > > > > > ./scripts/feeds update -a
> > > > > > ./scripts/feeds install -a
> > > > > > 之后
> > > > > > make menuconfig
> > > > > > 在luci里边才会见到
> > > > > > luci-app-smartdns
> > > > > > @anafkk
> > > > > 
> > > > > 
> > > > > 我也用懒人包，可是用完之后没有在luci里看到这项，是master分支还是lede分支？
> > > > 
> > > > 
> > > > 当然要改成
> > > > LUCIBRANCH="lede"
> > > 
> > > 
> > > emmm，刚试了下，好像不行。。
> > 
> > 
> > ./scripts/feeds update -a
> > ./scripts/feeds install -a
> > 他还要下载东西回来啊。
> 
> 是的啊，我看了下文件产生的目录 feeds（luci和package）里面都有了

懒人脚本下载回来的不算
./scripts/feeds update -a
时是再有smartdns的下载的

**Comment by ztjal** [comment]
> 一样的，都木有哦。。

你试下分两次，先
https://github.com/pymumu/openwrt-smartdns
然后再
https://github.com/pymumu/luci-app-smartdns
的方法看看？
不行我也没办法……

**Comment by pymumu** [comment]
谁有空测试下，看看能不能运行。
[smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4638697/smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip)

**Comment by ztjal** [comment]
> 
> 
> 谁有空测试下，看看能不能运行。
> [smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4638697/smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip)

试了，这个行，TLS正常。😀

**Comment by stztao** [comment]
> 谁有空测试下，看看能不能运行。
> [smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4638697/smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip)

大佬空闲时把新版本同步下懒人包吧，编译这个好用

**Comment by lzx2009vb** [comment]
> 谁有空测试下，看看能不能运行。
> [smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4638697/smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip)

有x86_64的没。。

**Comment by lzx2009vb** [comment]
> 谁有空测试下，看看能不能运行。
> [smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4638697/smartdns.1.2020.05.16-2115.mipsel-openwrt-all.ipk.zip)

emmmm，重新编译后还是一样解析不了tls和https，有点炸了= =

**Comment by arfaWong** [comment]
同样是 tls 和 https 用不了。。。

**Comment by pymumu** [comment]
发日志，或用上面的版本看看

**Comment by pymumu** [comment]
使用最新版本，如果有问题reopen issue，提交日志。
