### ISSUE TITLE
server 等参数建议增加 interface 参数

### ISSUE THREAD

**Issue by soffchen** [pymumu/smartdns#512]
**需求应用场景**
指定 interface 以通过特定 interface 访问  server 

**建议的方案**
```
server -interface wg0
server-tls -interface wg0
server-tcp -interface wg0
server-https -interface wg0
```

**Comment by pymumu** [comment]
场景是什么

**Comment by soffchen** [comment]
wg0 是 wireguard vpn，或者其他的 vpn 或者 tun 设备，通过这些出去。
现在不支持这个功能，只能在 vpn 内的机器上面做 udp/tcp 转发，有这个功能就方便了

类似 curl --interface, ping -I, ...

**Comment by pymumu** [comment]
iptable设置一下，也可以一样效果。

但通过转发请求的方式，可能会导致远端DNS解析的IP地址不是最佳

**Comment by soffchen** [comment]
所以增加 interface 参数还是有用的，考虑一下？

**Comment by pymumu** [comment]
done
