### ISSUE TITLE
我在二级软路由上搭建的smartdns，然后我把二级路由的IP设置到了主路由上面，结果一堆报错

### ISSUE THREAD

**Issue by ecareyu** [pymumu/smartdns#514]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
Openwrt Koolshare mod V2.31, r10822-50aa0525d1 by fw867
smartdns.1.2020.05.04-0005.x86_64-openwrt-all
luci-app-smartdns.1.2019.06.21-2337.all-luci-all

2. 运营商  

**重现步骤**
主路由IP 192.168.0.1
二级路由IP 192.168.0.9/192.168.88.1

主路由与二级路由之间，我做了静态路由，所以，是互通的.

我笔记本由于是连的网线，所以，只能接入到主路由网段，所以我将网卡dns的配置配成了192.168.0.9结果发现，dns服务根本没法用，所以，我开了debug日志，发现出现了一堆
`recv ping packet from 192.168.0.9 failed.`

SmartDNS配置截图:
![image](https://user-images.githubusercontent.com/2928867/81799196-939b5700-9543-11ea-90d7-efe56d3713dc.png)

**信息收集**  
1.报错日志
[smartdns.log](https://github.com/pymumu/smartdns/files/4621211/smartdns.log)

**Comment by pymumu** [comment]
都是debug日志，可以不用关心，或将日志级别修改为info以上

**Comment by Ecareyu** [comment]
哦哦，我有个小问题，那我怎么验证，我的网络是否用上了我搭建的dns，因为，我通过几个方法去验证，结果，只有最后一个正常。
![image](https://user-images.githubusercontent.com/2928867/81884907-bffab600-95cb-11ea-8915-48870f3c2ade.png)

**Comment by pymumu** [comment]
使用最新版本，如果有问题reopen issue，提交日志。
