### ISSUE TITLE
如何限制允许查询的ip

### ISSUE THREAD

**Issue by aruisi2017** [pymumu/smartdns#516]
例如像bind的allow-query选项那样，只接受某些指定的ip查询dns服务器。

**Comment by chainofhonor** [comment]
这个用防火墙 
比如禁止客户端192.168.1.2查询
iptables -A INPUT -s 192.168.1.2/24 -j DROP

**Comment by pymumu** [comment]
最新代码：
https://pymumu.github.io/smartdns/config/client-rule/
