### ISSUE TITLE
Hope more security!

### ISSUE THREAD

**Issue by jkle112** [pymumu/smartdns#517]
Openwrt x64 in mini PC
Linksys WRT1900AC with OpenWrt 19.07.2
Hope more security!
https://allinfa.com/dns-over-https-doh.html
https://allinfa.com/encrypted-server-name-indication-esni.html
https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by AZ-X** [comment]
@jkle112 
You should always keep transparency when facing G*W, in another words, bypass it legally.
Unless the connection reset phenomenon is desirable, don’t ever think words such as ‘fight’
