### ISSUE TITLE
建议使用 IP 地址形式的 DoT/DoH，去解析域名形式的 DoT/DoH

### ISSUE THREAD

**Issue by anafkk** [pymumu/smartdns#520]
**需求应用场景**
在使用 OpenDNS 这种目前仅支持域名 DoH 的上游可信服务时，SmartDNS 会使用其他 IP 地址形式的上游服务器进行域名延迟解析、避免启动失败，但这些上游服务不一定都是可信的（比如国内的公共 DNS），此时依旧会明文暴露一次查询

**建议的方案**
使用 IP 地址形式的 DoT/DoH 可信服务，去解析域名形式的 DoT/DoH（此时优先使用同组内的 IP 可信服务、同组内若无则使用他组内的 IP 可信服务，若均无则再使用其他的 IP 地址形式的上游服务器进行域名解析。）

**Comment by pymumu** [comment]
可以直接配置IP地址，看参数说明

**Comment by anafkk** [comment]
> 可以直接配置IP地址，看参数说明

@pymumu 您的意思是用 address 参数，指定 DoH 域名的 IP 么？OpenDNS 仅支持域名形式的 DoH：http://dwz.date/aEC8，不支持 IP 形式的 DoH

**Comment by Alion548** [comment]
试试-hostname 参数

**Comment by anafkk** [comment]
> 试试-hostname 参数

@Alion548 现在是已知 DoH/DoT  URL 比如，要用可信服务获知其对应的 IP，用 -host-name 再配置一遍域名的域名起什么作用..

**Comment by anafkk** [comment]
> > 可以直接配置IP地址，看参数说明
> 
> @pymumu 您的意思是用 address 参数，指定 DoH 域名的 IP 么？

@pymumu 您想表达的是这个意思吗

**Comment by anafkk** [comment]
@pymumu 同一个域名用 address 参数指定多个 IP 后，只会走最后一个配置，而不会走 smartdns 自己 IP 测速优选逻辑吗？

**Comment by pymumu** [comment]
address只能配置一个ip

**Comment by anafkk** [comment]
> address只能配置一个ip

可以考虑优化一下吗，现在想用可信上游（多个 IP 形式的 DoH / DoT ）去解析 DoH 域名获得最快的 dns server，要不还是明文暴露一次”请求 DoH“的请求

**Comment by pymumu** [comment]
用ip地址啊，server-https https://8.8.8.8/dnsquery -host-name dns.google

**Comment by anafkk** [comment]
> 用ip地址啊，server-https https://8.8.8.8/dnsquery -host-name dns.google

@pymumu 我之前说过了，OpenDNS 仅支持域名形式的 DoH：http://dwz.date/aEC8  不支持 IP 形式调用

**Comment by pymumu** [comment]
给你的是可以用的。-host-name配置的是域名，让服务器能处理的。

server-https https://1.32.218.198/aEC8 -host-name dwz.date

**Comment by anafkk** [comment]
@pymumu 感谢！请问下这个 IP 是如何选取出来的？我看 https://github.com/oneoffdallas/dohservers 中 OpenDNS 的主 dns ip 也是在之中的，但是  server-https https://208.67.222.222/dns-query -host-name doh.opendns.com  这样的配置就连接不通

**Comment by wyjtm** [comment]
> -host-name dns.google

求教这个  -host-name dns.google  在ui设置里 是在哪里设置的？

顺便谷歌的dot会报ssl错误  doh也是不能用的  坐标河南联通

**Comment by anafkk** [comment]
@wyjtm UI 里是那个 TLS SNI名称

**Comment by wyjtm** [comment]
@anafkk o 好的 谢谢
这个设置在doh里也是能用的吗？

**Comment by anafkk** [comment]
> @anafkk o 好的 谢谢
> 这个设置在doh里也是能用的吗？

@wyjtm 都可以，不过你的 doh/dot 连不上应该是作者编译器更换的问题，详情参见：https://github.com/pymumu/smartdns/issues/511

**Comment by wyjtm** [comment]
> > @anafkk o 好的 谢谢
> > 这个设置在doh里也是能用的吗？
> 
> @wyjtm 都可以，不过你的 doh/dot 连不上应该是作者编译器更换的问题，详情参见：#511

@anafkk 不 我的情况是只有谷歌的出问题  dot ssl错误  doh连不上  其他的doh dot都正常
还有就是插件崩溃问题

**Comment by rampageX** [comment]
dns.google=8.8.8.8/8.8.4.4 是 TCP 阻断，不用它即可。

**Comment by anafkk** [comment]
@wyjtm 把 google dns 的 IP 和域名加到强制走代理的白名单中

**Comment by wyjtm** [comment]
> @wyjtm 把 google dns 的 IP 和域名加到强制走代理的白名单中
> ![image](https://user-images.githubusercontent.com/65156682/82687363-c9e67e00-9c89-11ea-8436-771abf7f360f.png)
> ![image](https://user-images.githubusercontent.com/65156682/82687388-d36fe600-9c89-11ea-948e-52ac6f1b775f.png)

@anafkk 但是这样做不就没意义了吗 走代理解析出来的结果不就是根据代理服务器的ip来解析了嘛
本地再用不是更卡

**Comment by anafkk** [comment]
@wyjtm 什么鬼  是替代本地直连，请求 dns IP 时走加密代理，保证连通性和防污染，比如长城的 TCP 阻断或者运营商 DNS 劫持，而且很多时候，即使加入了代理中转，还是比本地直连国外 DNS 要快得多

**Comment by pymumu** [comment]
please free free to reopen this issue.

**Comment by 1klakla1** [comment]
Mark一下。

**Comment by 1klakla1** [comment]
> @pymumu 感谢！请问下这个 IP 是如何选取出来的？我看 https://github.com/oneoffdallas/dohservers 中 OpenDNS 的主 dns ip 也是在之中的，但是 server-https https://208.67.222.222/dns-query -host-name doh.opendns.com 这样的配置就连接不通
> 
> 像 dns.sb 也是，俩 IP 设置的 DoH URL 一样联不通，这是什么原因？

你搞明白这个问题了没有？。
搞明白了的话能不能讲一下。囧。我也是很困惑。

**Comment by 1klakla1** [comment]
> 给你的是可以用的。-host-name配置的是域名，让服务器能处理的。
> 
> server-https https://146.112.41.2/dns-query -host-name doh.opendns.com

请问这个IP是怎么得到的？直接PING那个服务器的返回IP么？

**Comment by yanghonghao6789** [comment]
我的smartdns 像上面那种加上hostname  直接上不了网 去掉就可以正常上网
