### ISSUE TITLE
我想运行smartdns二个进程一个国内，一个国外进行分流，多进程如何运行，在些谢过

### ISSUE THREAD

**Issue by osxdiy** [pymumu/smartdns#522]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）x86 openwrt 5.4  

2. 固件信息

**Comment by rampageX** [comment]
先回答你的问题：
`server-name` 不同，`监听端口` 不同，`pid` 文件不同

但是你的需求其实只需要监听两个不同端口，然后通过 group 来分流即可，无需启动两个进程。

**Comment by osxdiy** [comment]
pid 文件不同，如何实现，请教我一下，谢谢！

**Comment by rampageX** [comment]
-p smartdns1.pid

-p smartdns2.pid

**Comment by osxdiy** [comment]
谢谢您，我来试试这种方式好不好
