### ISSUE TITLE
建议增加被墙域名检测机制

### ISSUE THREAD

**Issue by hsex-tv** [pymumu/smartdns#523]
**需求应用场景**
被墙域名会返回虚假IP。

**建议的方案**
可以通过检测NS记录判断域名是否被墙。
能检测到NS记录的说明这个域名解析记录有效的。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by anafkk** [comment]
建议对上游分组  之后配合 chinadns 食用

**Comment by rampageX** [comment]
这个只对目前电信网络有效，移动无效的。

而且确切的描述是：

指定用境外 DNS 服务器解析域名的 NS，如果返回 A 记录则域名被污染。

例如：

正常域名，返回 NS 或者 CNAME & SOA：

```
dig 163.com @1.0.0.1 NS

; <<>> DiG 9.12.4 <<>> 163.com @1.0.0.1 NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51650
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;163.com.			IN	NS

;; ANSWER SECTION:
163.com.		168272	IN	NS	ns4.nease.net.
163.com.		168272	IN	NS	ns6.nease.net.
163.com.		168272	IN	NS	ns2.166.com.
163.com.		168272	IN	NS	ns3.nease.net.
163.com.		168272	IN	NS	ns8.166.com.
163.com.		168272	IN	NS	ns1.nease.net.
163.com.		168272	IN	NS	ns5.nease.net.

;; Query time: 167 msec
;; SERVER: 1.0.0.1#53(1.0.0.1)
;; WHEN: Sat May 23 01:33:19 CST 2020
;; MSG SIZE  rcvd: 182

dig www.163.com @1.0.0.1 NS

; <<>> DiG 9.12.4 <<>> www.163.com @1.0.0.1 NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44239
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;www.163.com.			IN	NS

;; ANSWER SECTION:
www.163.com.		268	IN	CNAME	www.163.com.163jiasu.com.

;; AUTHORITY SECTION:
163jiasu.com.		68	IN	SOA	ns1.ntes53.com. wtzhu182.163.com. 2015102101 3600 180 1209600 10800

;; Query time: 169 msec
;; SERVER: 1.0.0.1#53(1.0.0.1)
;; WHEN: Sat May 23 01:33:32 CST 2020
;; MSG SIZE  rcvd: 142
```

被污染域名，返回 A 记录：

```
dig WWW.WSJ.com @1.1.1.1 NS

; <<>> DiG 9.12.4 <<>> WWW.WSJ.com @1.1.1.1 NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8684
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;WWW.WSJ.com.			IN	NS

;; ANSWER SECTION:
WWW.WSJ.com.		179	IN	A	31.13.81.1

;; Query time: 3 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sat May 23 01:32:04 CST 2020
;; MSG SIZE  rcvd: 45
```

**Comment by pymumu** [comment]
ip黑名单

**Comment by hsex-tv** [comment]
> 这个只对目前电信网络有效，移动无效的。
> 
> 而且确切的描述是：
> 
> 指定用境外 DNS 服务器解析域名的 NS，如果返回 A 记录则域名被污染。
> 
> 例如：
> 
> 正常域名，返回 NS 或者 CNAME & SOA：
> 
> ```
> dig 163.com @1.0.0.1 NS
> 
> ; <<>> DiG 9.12.4 <<>> 163.com @1.0.0.1 NS
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51650
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1452
> ;; QUESTION SECTION:
> ;163.com.			IN	NS
> 
> ;; ANSWER SECTION:
> 163.com.		168272	IN	NS	ns4.nease.net.
> 163.com.		168272	IN	NS	ns6.nease.net.
> 163.com.		168272	IN	NS	ns2.166.com.
> 163.com.		168272	IN	NS	ns3.nease.net.
> 163.com.		168272	IN	NS	ns8.166.com.
> 163.com.		168272	IN	NS	ns1.nease.net.
> 163.com.		168272	IN	NS	ns5.nease.net.
> 
> ;; Query time: 167 msec
> ;; SERVER: 1.0.0.1#53(1.0.0.1)
> ;; WHEN: Sat May 23 01:33:19 CST 2020
> ;; MSG SIZE  rcvd: 182
> 
> dig www.163.com @1.0.0.1 NS
> 
> ; <<>> DiG 9.12.4 <<>> www.163.com @1.0.0.1 NS
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44239
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1452
> ;; QUESTION SECTION:
> ;www.163.com.			IN	NS
> 
> ;; ANSWER SECTION:
> www.163.com.		268	IN	CNAME	www.163.com.163jiasu.com.
> 
> ;; AUTHORITY SECTION:
> 163jiasu.com.		68	IN	SOA	ns1.ntes53.com. wtzhu182.163.com. 2015102101 3600 180 1209600 10800
> 
> ;; Query time: 169 msec
> ;; SERVER: 1.0.0.1#53(1.0.0.1)
> ;; WHEN: Sat May 23 01:33:32 CST 2020
> ;; MSG SIZE  rcvd: 142
> ```
> 
> 被污染域名，返回 A 记录：
> 
> ```
> dig WWW.WSJ.com @1.1.1.1 NS
> 
> ; <<>> DiG 9.12.4 <<>> WWW.WSJ.com @1.1.1.1 NS
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8684
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;WWW.WSJ.com.			IN	NS
> 
> ;; ANSWER SECTION:
> WWW.WSJ.com.		179	IN	A	31.13.81.1
> 
> ;; Query time: 3 msec
> ;; SERVER: 1.1.1.1#53(1.1.1.1)
> ;; WHEN: Sat May 23 01:32:04 CST 2020
> ;; MSG SIZE  rcvd: 45
> ```

能返回主域名的正常NS记录才是有效的。
移动测试被墙也不能正常返回NS记录。
NS记录查询正确回应应该是NS记录，肯定不是A记录或者是空记录。
![截图](https://user-images.githubusercontent.com/28925313/82907917-d1639b00-9f99-11ea-8732-750d1e5bb2c0.png)

**Comment by hsex-tv** [comment]
墙污染域名的根本原理还是，需要污染根服务器的。

**Comment by pymumu** [comment]
nameserver分流加ip黑白名单

**Comment by muink** [comment]
> > 这个只对目前电信网络有效，移动无效的。
> > 而且确切的描述是：
> > 指定用境外 DNS 服务器解析域名的 NS，如果返回 A 记录则域名被污染。
> > 例如：
> > 正常域名，返回 NS 或者 CNAME & SOA：
> > ```
> > dig 163.com @1.0.0.1 NS
> > 
> > ; <<>> DiG 9.12.4 <<>> 163.com @1.0.0.1 NS
> > ;; global options: +cmd
> > ;; Got answer:
> > ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51650
> > ;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1
> > 
> > ;; OPT PSEUDOSECTION:
> > ; EDNS: version: 0, flags:; udp: 1452
> > ;; QUESTION SECTION:
> > ;163.com.			IN	NS
> > 
> > ;; ANSWER SECTION:
> > 163.com.		168272	IN	NS	ns4.nease.net.
> > 163.com.		168272	IN	NS	ns6.nease.net.
> > 163.com.		168272	IN	NS	ns2.166.com.
> > 163.com.		168272	IN	NS	ns3.nease.net.
> > 163.com.		168272	IN	NS	ns8.166.com.
> > 163.com.		168272	IN	NS	ns1.nease.net.
> > 163.com.		168272	IN	NS	ns5.nease.net.
> > 
> > ;; Query time: 167 msec
> > ;; SERVER: 1.0.0.1#53(1.0.0.1)
> > ;; WHEN: Sat May 23 01:33:19 CST 2020
> > ;; MSG SIZE  rcvd: 182
> > 
> > dig www.163.com @1.0.0.1 NS
> > 
> > ; <<>> DiG 9.12.4 <<>> www.163.com @1.0.0.1 NS
> > ;; global options: +cmd
> > ;; Got answer:
> > ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44239
> > ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
> > 
> > ;; OPT PSEUDOSECTION:
> > ; EDNS: version: 0, flags:; udp: 1452
> > ;; QUESTION SECTION:
> > ;www.163.com.			IN	NS
> > 
> > ;; ANSWER SECTION:
> > www.163.com.		268	IN	CNAME	www.163.com.163jiasu.com.
> > 
> > ;; AUTHORITY SECTION:
> > 163jiasu.com.		68	IN	SOA	ns1.ntes53.com. wtzhu182.163.com. 2015102101 3600 180 1209600 10800
> > 
> > ;; Query time: 169 msec
> > ;; SERVER: 1.0.0.1#53(1.0.0.1)
> > ;; WHEN: Sat May 23 01:33:32 CST 2020
> > ;; MSG SIZE  rcvd: 142
> > ```
> > 
> > 
> > 被污染域名，返回 A 记录：
> > ```
> > dig WWW.WSJ.com @1.1.1.1 NS
> > 
> > ; <<>> DiG 9.12.4 <<>> WWW.WSJ.com @1.1.1.1 NS
> > ;; global options: +cmd
> > ;; Got answer:
> > ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8684
> > ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> > 
> > ;; QUESTION SECTION:
> > ;WWW.WSJ.com.			IN	NS
> > 
> > ;; ANSWER SECTION:
> > WWW.WSJ.com.		179	IN	A	31.13.81.1
> > 
> > ;; Query time: 3 msec
> > ;; SERVER: 1.1.1.1#53(1.1.1.1)
> > ;; WHEN: Sat May 23 01:32:04 CST 2020
> > ;; MSG SIZE  rcvd: 45
> > ```
> 
> 能返回主域名的正常NS记录才是有效的。
> 移动测试被墙也不能正常返回NS记录。
> NS记录查询正确回应应该是NS记录，肯定不是A记录或者是空记录。
> ![截图](https://user-images.githubusercontent.com/28925313/82907917-d1639b00-9f99-11ea-8732-750d1e5bb2c0.png)

使用dig的+trace更清晰，刚把根服务器解析完就能收到污染包

**Comment by pymumu** [comment]
udp协议，增加-check-edns参数。其他优选TLS，HTTPS。

**Comment by pymumu** [comment]
please free free to reopen this issue.
