### ISSUE TITLE
建议给DoH/DoT在设置时提供能够自定义的Bootstrap DNS 服务器

### ISSUE THREAD

**Issue by aasunaa** [pymumu/smartdns#524]
**需求应用场景**
请描述需求应用的场景和方式。
在分组了的情况下:
如果以国内dns去解析的话会很慢,如果以保留一个国外ip地址的dns,那么查询请求有可能会直接走ip地址进行查询,而不是走DoH
实现上述场景建议的方案。
在设置DoH时能够单独设置其可信的Bootstrap DNS 服务器,

**Comment by anafkk** [comment]
我也提了类似的建议：https://github.com/pymumu/smartdns/issues/520

目的其实有两个：一是统一用国外服务解析寻址最快，二是不明文向非可信上游暴露”请求 DoH“这个动作的解析请求，以防暴露和劫持

**Comment by pymumu** [comment]
group 配合nameserver

nameserver /one.one.one.one/foreign
server-https https://one.one.one.one/
server-tls 1.1.1.1 -group foreign

**Comment by anafkk** [comment]
@pymumu 用 nameserver 将 DoH 发送给了指定的 group，能解析出对应的 IP 集 ，但是感觉一直在反复选择最优 IP，网页依旧打不开

[smartdns (5).log](https://github.com/pymumu/smartdns/files/4674008/smartdns.5.log)

**Comment by pymumu** [comment]
你用最新代码编译一个版本试试，最新release的这块有点问题

**Comment by pymumu** [comment]
please free free to reopen this issue.
