### ISSUE TITLE
建议增加其他形式的内网解析，如 CNAME 和 SRV

### ISSUE THREAD

**Issue by purerosefallen** [pymumu/smartdns#525]
**需求应用场景**

如，内网 KMS 服务器，需要实现无配置自动激活 Windows。这时候需要添加一个 `_vlmcs._tcp.lan` 的 SRV 记录，来自动激活。

**建议的方案**

类比 Dnsmasq，在配置文件中支持:
```
srv-host 0 100 1688 kms-server.example.com
```
CNAME 等其他形式的记录同理。

**设备信息**
1. 设备信息（CPU，厂家）  
x86
2. 固件信息
Debian

**Comment by xyxu1024** [comment]
+1

**Comment by pymumu** [comment]
done
