### ISSUE TITLE
请教黑名单的使用

### ISSUE THREAD

**Issue by wyjtm** [pymumu/smartdns#526]
> 国外dns
> option server_group 'foreign'
> option blacklist_ip '1'
> 
> 黑名单里加上
> nameserver /bing.com/foreign
> nameserver /cctv.com/foreign
> nameserver /taobao.com/foreign
> nameserver /bilibili.com/foreign

1、这样是让所有foreign组的dns都放弃解析这个域名或者丢弃结果吗？
2、只让foreign组解析这些域名

我自己这边看到的是2
bing.com、cctv.com都被解析到了欧洲和美国  
taobao.com被解析到了香港
bilibili.com到了台湾

> 国内dns
> option server_group 'china'
> option blacklist_ip '1'
> 
> 黑名单里加上
> nameserver /bing.com/china
> nameserver /cctv.com/china
> nameserver /taobao.com/china
> nameserver /bilibili.com/china

[china.domain.conf.txt](https://github.com/pymumu/smartdns/files/4679440/china.domain.conf.txt)

1、这样是让所有china组的dns都放弃解析这个域名或者丢弃结果吗？
2、只让china组解析这些域名

我自己这边看到的是2
所有都解析到了中国、和不使用smartdns的结果是一样的

好像和https://github.com/pymumu/smartdns/issues/503 
这里的

> 白名单是指，值接受指定IP地址范围内的结果

如果白名单这样设定
nameserver /cctv.com/china
是
1、china组的dns只解析表里设定的域名？不在解析其他域名？
2、列表里的域名只接受china组解析？ china组也继续接受解析其他域名？

> 黑名单就是对应名单中的结果，全部丢弃？

nameserver /bilibili.com/foreign
这样设定之后 解析到了台湾
和上面解释完全相反

这个到底该怎么用？ 能给个范例吗？

附件是现在在用的配置、使用的是第二个模式、能正常把国内域名解析到中国

https://github.com/pymumu/smartdns/issues/501 用的是这贴里的smartdns.1.2020.05.17-0943.arm-openwrt-all.ipk.zip

[smartdns.txt](https://github.com/pymumu/smartdns/files/4679444/smartdns.txt)
[china.domain.conf.txt](https://github.com/pymumu/smartdns/files/4679445/china.domain.conf.txt)
黑名单里加上conf-file /etc/smartdns/china.domain.conf
白名单里也可以用 conf-file 添加配置文件吗？

**Comment by pymumu** [comment]
nameserver是分流，具体如何使用看readme的参数和FAQ

**Comment by wyjtm** [comment]
> nameserver是分流，具体如何使用看readme的参数和FAQ

有什么简单的方法让国外dns的不解析国内的地址吗
现在的默认配置一次全都解析会让国内域名 浏览器也转两圈才会解析到  解析国内的速度反而比不用慢了
河南联通

**Comment by pymumu** [comment]
将chnrouter作为黑名单配置到国外服务器上

**Comment by wyjtm** [comment]
> 将chnrouter作为黑名单配置到国外服务器上

不知道怎么弄 能给个配置示例吗
@pymumu
