### ISSUE TITLE
增加对 OpenRC 的支持

### ISSUE THREAD

**Issue by Zerorigin** [pymumu/smartdns#528]
**需求应用场景**
增加对 OpenRC 的支持，以便管理运行在 Alpine Linux 此类轻量发行版的 smartdns

**建议的方案**
增加对 OpenRC 的支持，以便管理运行在 Alpine Linux 此类轻量发行版的 smartdns

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
自行用代码编译即可
