### ISSUE TITLE
其線路不穩導致DNS time out然後就一直Out of memory，直到重啟才正常

### ISSUE THREAD

**Issue by sammimk830** [pymumu/smartdns#529]
其實我也遇到了這個問題，發生是在昨天，這邊的網絡不穩，DNS是我在某地建的，但線路不穩導致DNS time out然後就一直Out of memory，直到重啟才正常
我bind了兩個group，一個有問題，另一個就沒事。

[2020-05-27 00:05:14,204][ERROR][     dns_server.c:2969] dns server process failed.
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2896] retry query heartbeat.belkin.com
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2553] send query to 203.174.52.78 failed, Out of memory, type: 2
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2896] retry query presence.teams.microsoft.com
[2020-05-27 00:05:14,277][DEBUG][     dns_client.c:2553] send query to 203.174.52.78 failed, Out of memory, type: 2

_Originally posted by @sammimk830 in https://github.com/pymumu/smartdns/issues/341#issuecomment-634421184_

**Comment by pymumu** [comment]
配置了什么协议的服务器，是否有可能是pppoe拨号中断导致的，可以看一下

**Comment by sammimk830** [comment]
配置了是一台我建在香港的TLS服務器，有有效証書的
server-tls 2xx.174.52.xx:853 -group hkdns -exclude-default-group -no-check-certificate -host-name dns.xxxxxxxxx.com.hk
我確定不是pppoe斷線，因為當時是可以ping通他的，但只是被干擾，所以會有時候time out的，而香港那邊也是固定ip來的，只是感覺是DOT如果DNS服務器超時，就會導致Out of memory，但是服務器1是可以繼續運作的，只是服務器2不會再回復了。

**Comment by pymumu** [comment]
是否只配置了一个服务器
可能是tcp连接是好的，但所有请求都不回应了，远端服务器什么软件

**Comment by sammimk830** [comment]
對，只配置了一個，就是因為要走那個線路出去，所以在那個線路上建DNS，CDN的效果是最好的，而且用TLS方式也不會因為其他的軟件中間的線路不穩而導致DNS解釋不了，但是如果是被干擾這是在所難免的。不過也不應該是會直接變為out of memory，應該是查詢出錯，等那邊好了會灰復才是吖。
那邊用的是AdGuardHome。

**Comment by pymumu** [comment]
adguard的协议支持可能有问题，就是在某些情况下，tls连接正常，但不处理任何数据，导致smartdns发送端缓冲区满，你出问题的时候可以重启adguard看看

**Comment by sammimk830** [comment]
重啟adguard是沒有反應的，我想應該是smartdns已經出現錯誤後就不再工作了。

**Comment by PikuZheng** [comment]
相同问题。比如pppoe重新拨号了。那么在拨号后的8分钟内（甚至更长），dnsmasq是无法正常工作的。日志显示大量的out of memory。
配置了多个上游服务器。

**Comment by pymumu** [comment]
日志里面的out of memory指的是，发送请求的缓冲区满，导致的原因是上游服务器TLS，TCP或HTTPS没有回应。
考虑排查上游服务器连接是否能成功。

**Comment by PikuZheng** [comment]
比如我断开pppoe然后重新拨号。有没有可能是之前连接成功的dot/doh仍处于established状态，没有触发断开或重新连接导致的查询失败？我看另一个issue说连接超时十分钟，似乎可以解释这个现象。

**Comment by pymumu** [comment]
什么固件，我编译了一个版本，增加了一些处理，可以发给各位验证一下

**Comment by PikuZheng** [comment]
> 什么固件，我编译了一个版本，增加了一些处理，可以发给各位验证一下

我的是openwrt x86_64

**Comment by PikuZheng** [comment]
> 比如我断开pppoe然后重新拨号。有没有可能是之前连接成功的dot/doh仍处于established状态，没有触发断开或重新连接导致的查询失败？我看另一个issue说连接超时十分钟，似乎可以解释这个现象。

测试了几次，这个现象可以重现。而且（从路由）给这些连接发送rst也不能触发断开重连。但重启服务可以立即正常。

**Comment by pymumu** [comment]
[smartdns.1.2020.06.26-1700.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4839803/smartdns.1.2020.06.26-1700.x86_64-openwrt-all.ipk.zip)

**Comment by PikuZheng** [comment]
> [smartdns.1.2020.06.26-1700.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4839803/smartdns.1.2020.06.26-1700.x86_64-openwrt-all.ipk.zip)

有改善，相同测试条件下大概恢复时间缩短到一分钟

**Comment by pymumu** [comment]
[smartdns.1.2020.06.27-1033.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/4839859/smartdns.1.2020.06.27-1033.x86_64-openwrt-all.ipk.zip)

有个地方改漏了，再试试这个。
