### ISSUE TITLE
集成到openwrt-lede内无法启动，无日志

### ISSUE THREAD

**Issue by shuzhifenxi** [pymumu/smartdns#530]
**问题现象**  
简要描述问题出现的现象
       用的N1盒子和自编的lede固件。
       把src-git smartdns https://github.com/pymumu/smartdns.git 添加到feeds.conf.default中，没有改任何参数，正常编译成功，luci有选项。U盘启动后打开samart管理界面也可以保存配置，但是反复点击开启关闭，一直显示“smartdns 未运行”。系统日志内无记录，用命令samrtdns -v可以看到版本信息。
       然后，我直接把官网的ipk上传到设备上安装，提示安装失败，但此时又一直显示“smartdns 运行中”，无法关闭，但实际dns未启动，没有效果，且仍然无日志。
       有路过的大神指点一下，谢谢！

**Comment by pymumu** [comment]
配置启用后，你ps看看是否有进程运行，

**Comment by ivanxxxx** [comment]
貌似我也遇到类似问题，但不确定是否一样的问题

我跟楼主不一样的是我没有编译这里的代码，而是直接下载release版本到openwrt x86 64位上面使用

启动smartdns会有报错如下：

[ 1165.456848] smartdns[5904]: segfault at 0 ip 000000000058b63c sp 00007fff7304b358 error 6 in smartdns[401000+19e000]
[ 1170.458093] smartdns[5931]: segfault at 0 ip 000000000058b63c sp 00007fff5e31f608 error 6 in smartdns[401000+19e000]
[ 1175.460897] smartdns[5944]: segfault at 0 ip 000000000058b63c sp 00007ffe7ad46d28 error 6 in smartdns[401000+19e000]
[ 1180.461973] smartdns[5955]: segfault at 0 ip 000000000058b63c sp 00007ffd22e49be8 error 6 in smartdns[401000+19e000]
[ 1185.463045] smartdns[5966]: segfault at 0 ip 000000000058b63c sp 00007ffc2bc9dc68 error 6 in smartdns[401000+19e000]
[ 1190.464550] smartdns[5977]: segfault at 0 ip 000000000058b63c sp 00007fffcc05dfd8 error 6 in smartdns[401000+19e000]

**Comment by pymumu** [comment]
用最新版本验证。
