### ISSUE TITLE
WSL2下装上了smartDNS但是上不去网。。

### ISSUE THREAD

**Issue by yeezylife** [pymumu/smartdns#532]
网络中心有三个网络连接。分别为：vEthernet (Default Switch)；vEthernet (WSL)；和之前的 以太网 2   我把三个的IPV4都改成了127.0.0.1.。还是打不开网

我在想 如果只用smartdns 是不是就用WSL1算了。。WSL2还多了一个Vmmem进程，常驻300M内存

**Comment by yeezylife** [comment]
nslookup -querytype=ptr smartdns
服务器:  UnKnown
Address:  ::1

*** UnKnown 找不到 smartdns: No response from server

**Comment by TUT123456** [comment]
用wsl2的话，windows下只有填localhost才能连到wsl，127.0.0.1是不行的，你可以ipconfig查看wsl的ip，dns填ip就行了，不过wsl2每次重启ip都会变。

**Comment by yeezylife** [comment]
> 用wsl2的话，windows下只有填localhost才能连到wsl，127.0.0.1是不行的，你可以ipconfig查看wsl的ip，dns填ip就行了，不过wsl2每次重启ip都会变。

IPV4的地址里格式是固定的XX.XX.XX.XX额。  不过我已经退回WSL1了  WSL2问题多的同时，内存占用还高。。感觉没必要

**Comment by achtowen** [comment]
> 用wsl2的话，windows下只有填localhost才能连到wsl，127.0.0.1是不行的，你可以ipconfig查看wsl的ip，dns填ip就行了，不过wsl2每次重启ip都会变。

我找到WSL2的动态IP，dns填上，无法正常解析，其它地方还需要修改设定吗？
