### ISSUE TITLE
解析到單一IP還會測速嗎？

### ISSUE THREAD

**Issue by kousyougi** [pymumu/smartdns#533]
目前測速功能好像不能關，不然會無法用緩存跟ipset的功能。
所以我就把smartdns也裝一個在遠端，讓遠端測速後只返回單一IP。這樣本地的測速不會因為因為走不同路由亂掉。
但我發現本地的smartdns收到測完的單一IP，好像還會再送出一個ping出去測速。
請問解析結果只返回一個IP還會對那個IP測速嗎？

**Comment by pymumu** [comment]
可以关闭测速，speed-checkmode参数。
