### ISSUE TITLE
安装Luci-app-smartdns显示uci: Entry not found

### ISSUE THREAD

**Issue by Suidge** [pymumu/smartdns#534]
root@NSLEDE:/tmp# opkg install smartdns.ipk
Installing smartdns (1.2020.05.04-0005) to root...
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Configuring smartdns.
root@NSLEDE:/tmp# opkg install luci-app-smartdns.ipk
Installing luci-app-smartdns (1.2020.05.04-0005) to root...
Configuring luci-app-smartdns.
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
root@NSLEDE:/tmp#

**Comment by cczid** [comment]
opkg update
opkg install luci-compat
