### ISSUE TITLE
ipv6 网址无法解析

### ISSUE THREAD

**Issue by tonyliangli** [pymumu/smartdns#535]
**问题现象**  
OpenWrt 作为旁路由，无论设置转发到53端口或作为dnsmasq上游，包括打开ipv6服务器，关闭双栈优选，ipv6 地址均无法解析。openwrt本身DHCP/DNS中的关闭AAAA也没有打勾。请问可能是什么原因，谢谢。把接口里LAN设置中的自定义DNS改回运营商提供的DNS，不使用smartdns，ipv6正常。

主路由已经将DNS设置为旁路由，Windows下用 nslookup -querytype=ptr smartdns 测试结果为：
服务器:  UnKnown
Address:  10.10.10.1

非权威应答:
smartdns        name = china

用 nslookup hdtv.lzu6.edu.cn 测试，结果为：
服务器:  UnKnown
Address:  10.10.10.1

*** 没有 hdtv.lzu6.edu.cn 可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录

**运行环境**
1. 固件型号  

软路由x86，openwrt 作为旁路由，ros作为主路由。

2. 运营商  

中国联通

**重现步骤**
1. 上游DNS配置。

转发到53端口或作为dnsmasq上游都试过  

2. 访问的域名。  

hdtv.lzu6.edu.cn
http://test-ipv6.com/

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump
功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

[smartdns.zip](https://github.com/pymumu/smartdns/files/4791167/smartdns.zip)

**Comment by tonyliangli** [comment]
找到问题了，自定义配置里有一个：force-AAAA-SOA yes
删除就好了。。。

**Comment by playcase** [comment]
> 找到问题了，自定义配置里有一个：force-AAAA-SOA yes
> 删除就好了。。。

同样问题，困扰很久，按照你的方法解决了，多谢。
