### ISSUE TITLE
自定义设置没有权限

### ISSUE THREAD

**Issue by yyjazsf** [pymumu/smartdns#539]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
OpenWrt 19.07.3 r11063-85e04e9f46

2. 运营商  
联通

**重现步骤**
1. 安装
```bash
opkg install smartdns.xxxxxxxx.xxxx.ipk
opkg install luci-app-smartdns.xxxxxxxx.xxxx.all.ipk
```

2. 在webui 里面设置 custom setting
```
speed-check-mode tcp:443,ping
```
点击保存，提示没有权限

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
不存在这个文件

2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
也没有 /tmp/smartdns.*

**Comment by pymumu** [comment]
这个属于openwrt的BUG，一直没解决，可以重新配置其他选项，使save可点击。

**Comment by pymumu** [comment]
please feel free to reopen this issue.
