### ISSUE TITLE
请问smartdns可以劫持域名。并且增加多条A记录做负载均衡麽？

### ISSUE THREAD

**Issue by boyyao** [pymumu/smartdns#540]
**需求应用场景**
针对某个域名，想劫持。并且自定义几个IP地址来做负载均衡

**建议的方案**
增加多条A记录的支持。并且轮询解释

**设备信息**
1. openwrt x64

2. 固件信息
openwrt x64

假设我有个域名xx.com想用smart劫持
我尝试在地址列表中添加如下：
address /xx.com/1.1.1.1
address /xx.com/2.2.2.2
address /xx.com/3.3.3.3
address /xx.com/4.4.4.4

希望在解释的时候随机的解释这4个IP。并且保证ip能ping通，而不考虑延迟。
但是我尝试用
root@OpenWrt:~# nslookup xx.com  127.0.0.1#6053
Server:         127.0.0.1
Address:        127.0.0.1#6053

Name:      xx.com
Address 1: 4.4.4.4
** server can't find xx.com: SERVFAIL
得到的总是最后一个。。

**Comment by pymumu** [comment]
现在没有这个功能，相同域名的，生效的是最后一个

**Comment by TendernessRadif** [comment]
address /aircat.phicomm.com/192.168.1.7
