### ISSUE TITLE
长时间运行后，出现所有域名解析到10.0.0.1

### ISSUE THREAD

**Issue by szl0834** [pymumu/smartdns#541]
**问题现象**  
在长时间运行后（大概1-2天，有时一周），会出现把所有域名解析到10.0.0.1这个地址的情况，造成无法上网的问题。
重启后解决

**运行环境**
1. 最新的Arch Linux

2. 中国移动  

**重现步骤**
1. 上游DNS配置。  
配置文件如下：
[smartdns.zip](https://github.com/pymumu/smartdns/files/4826532/smartdns.zip)
2. 访问的域名。  

**信息收集**  
Log如下：
[smartdns.log-20200624-233033.gz](https://github.com/pymumu/smartdns/files/4826523/smartdns.log-20200624-233033.gz)

**Comment by pymumu** [comment]
看一下你的路由器，如果是华硕的，要关闭英特网检测。
华硕路由器，在检测网络失败后，会重定向所有dns到特定的IP地址。

**Comment by szl0834** [comment]
> 看一下你的路由器，如果是华硕的，要关闭英特网检测。
> 华硕路由器，在检测网络失败后，会重定向所有dns到特定的IP地址。

感谢回复，我用的确实是华硕的路由器。
我去把网络监测关了试试看。

**Comment by szl0834** [comment]
> 看一下你的路由器，如果是华硕的，要关闭英特网检测。
> 华硕路由器，在检测网络失败后，会重定向所有dns到特定的IP地址。

经过几天的测试，还是会出现这个故障，确认已经关闭了路由器的网络检测功能

**Comment by szl0834** [comment]
放弃梅林固件，转战openwrt

**Comment by pymumu** [comment]
我华硕路由器之前也有类似的情况，所有IP都会解析到10.0.0.1， 原因就是网络检测问题。

后面完全关闭那个功能，就没有问题了。至于梅林是否有类似问题，或开关是否生效，那要配置看看。

配置项是这个：`开启 WAN 中断的浏览器导页通知`

**Comment by js882829** [comment]
> 我华硕路由器之前也有类似的情况，所有IP都会解析到10.0.0.1， 原因就是网络检测问题。
> 
> 后面完全关闭那个功能，就没有问题了。至于梅林是否有类似问题，或开关是否生效，那要配置看看。
> 
> 配置项是这个：`开启 WAN 中断的浏览器导页通知`

我现在也遇到了这个问题，但是没有找到上面所说的配置项。我是华硕ax11000
找到了一个类似的配置项：外部网络--》互联网连接 ---》账号设置---》 网络监测  
我直接选择了关闭，我是电信网络。不知道电信断网后路由器是否重连。先试下了。。。

**Comment by pymumu** [comment]
关闭
系统管理-系统设置-开启WAN中断的浏览器导页通知

**Comment by js882829** [comment]
> 关闭
> 系统管理-系统设置-开启WAN中断的浏览器导页通知

好的，找到了。谢谢大佬！试试看，如果没问题了。我再来回复!

**Comment by js882829** [comment]
> > 关闭
> > 系统管理-系统设置-开启WAN中断的浏览器导页通知
> 
> 好的，找到了。谢谢大佬！试试看，如果没问题了。我再来回复!

4天了，问题未再出现！建议可以关闭了。
