### ISSUE TITLE
配置文件存放位置问题

### ISSUE THREAD

**Issue by QuteSaltyFish** [pymumu/smartdns#545]
你好，请问smartdns的上游服务器的配置文件放在什么地方啊。。我使用的是openwrt，每次更新都要花半个小时重新配置觉得很麻烦。现在只找到/tmp/etc/smartdns/smartdns.conf里面存在，但是改动了没什么用，有大佬会吗

**Comment by anafkk** [comment]
@pymumu

**Comment by pymumu** [comment]
配置文件分两个地方，一个是  
1. /etc/config/smartdns
2. /etc/smartdns/address.conf
    /etc/smartdns/blacklist-ip.conf
    /etc/smartdns/custom.conf

其他地方的配置，都是自动生成的。

**Comment by yxz626** [comment]
> 配置文件分两个地方，一个是
> 
> 1. /etc/config/smartdns
> 2. /etc/smartdns/address.conf
>    /etc/smartdns/blacklist-ip.conf
>    /etc/smartdns/custom.conf
> 
> 其他地方的配置，都是自动生成的。

我也建议可以考虑给smartDNS增加一个配置导入导出功能把！！！

**Comment by anafkk** [comment]
确实 可以在 luci 里加一个配置导入导出功能 希望 @pymumu 可以考虑下

**Comment by jiayuqian** [comment]
> 配置文件分两个地方，一个是
> 
> 1. /etc/config/smartdns
> 2. /etc/smartdns/address.conf
>    /etc/smartdns/blacklist-ip.conf
>    /etc/smartdns/custom.conf
> 
> 其他地方的配置，都是自动生成的。

/etc/smartdns/smartdns.conf ，这个配置文件只是一个参考么？
