### ISSUE TITLE
centos7加入开机服务的时候提示 Too many levels of symbolic links

### ISSUE THREAD

**Issue by chainofhonor** [pymumu/smartdns#548]
用centos7安装smartdns服务
看命令
[root@centos7-1708 ~]# chkconfig smartdns on
Note: Forwarding request to 'systemctl enable smartdns.service'.
Failed to execute operation: Too many levels of symbolic links

这样就无法开机自动启动smartdns服务了
虽说软路由不用重启，但是万一服务器停电

**Comment by pymumu** [comment]
不要用checkconfig
用systemctl enable smartdns

**Comment by shuoyang129** [comment]
我使用 systemctl enable smartdns 也提示 Failed to execute operation: Too many levels of symbolic links

**Comment by z836454898** [comment]
同样的问题

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
