### ISSUE TITLE
为什么所有查询都显示来自127.0.0.1？

### ISSUE THREAD

**Issue by WROIATE** [pymumu/smartdns#550]
**问题现象**  
简要描述问题出现的现象
所有查询的域名都显示from 127.0.0.1
<br>
**运行环境**
1. 固件型号  
openwrt LuCI 17.01 Lienol (git-297a920)
配合adguardhome去广告使用，smartdns为adh的上游
2. 运营商  
移动

**重现步骤**
1. 上游DNS配置。  
```
speed-check-mode tcp:80,tcp:443,ping

server 202.141.178.13:5353
server 202.38.93.153:5353
server 202.141.162.123:5353
# server 2001:da8::666
server 114.114.114.114
server 223.5.5.5


server-tcp 9.9.9.9 -group fq_dns -exclude-default-group
server-tcp 8.8.8.8 -group fq_dns -exclude-default-group
server-tcp 1.0.0.1 -group fq_dns -exclude-default-group
server-tcp  208.67.222.222:5353 -group fq_dns -exclude-default-group
server-tcp 101.6.6.6:5353

server-tls 115.159.131.230 -host-name dns.rubyfish.cn
server-tls dns.rubyfish.cn
server-tls dns.233py.com
server-tls 8.8.8.8 -host-name dns.google -group fq_dns -exclude-default-group
server-tls dns.google -group fq_dns -exclude-default-group
server-tls 1.0.0.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group
server-tls 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group
server-tls 202.141.176.110
# server-tls 2001:da8:d800:95::110

# server-https https://202.141.178.13/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
server-https https://202.38.93.153/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
server-https https://neatdns.ustclug.org/resolve
server-https https://115.159.131.230/resolve -host-name dns.rubyfish.cn -http-host dns.rubyfish.cn
server-https https://dns.rubyfish.cn/dns-query
# server-https https://45.77.180.10/resolve -host-name dns.containerpi.com -http-host dns.containerpi.com
server-https https://dns.containerpi.com/dns-query
server-https https://210.17.9.228/dns-query -host-name dns.twnic.tw -http-host dns.twnic.tw
server-https https://dns.twnic.tw/dns-query
server-https https://i.233py.com/dns-query
server-https https://9.9.9.9/dns-query -host-name dns9.quad9.net -http-host dns9.quad9.net -group fq_dns -exclude-default-group
server-https https://dns9.quad9.net/dns-query -group fq_dns -exclude-default-group
server-https https://1.0.0.1/dns-query -group fq_dns -exclude-default-group
server-https https://cloudflare-dns.com/dns-query -group fq_dns -exclude-default-group
server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group fq_dns -exclude-default-group
server-https https://doh.opendns.com/dns-query -group fq_dns -exclude-default-group
```

2. 访问的域名。  
google.com
github.com
baidu.com

**信息收集**  
![Snipaste_2020-07-11_20-01-18](https://user-images.githubusercontent.com/44677306/87224080-e4e58c80-c3b4-11ea-991b-4db2fb82e2f7.png)

**Comment by WROIATE** [comment]
是因为本地查询smartdns吗？这样算是配置成功吗？

**Comment by pymumu** [comment]
如果全是127.0.0.1的话，可能是dnsmasq查询的，正常。

**Comment by WROIATE** [comment]
> 如果全是127.0.0.1的话，可能是dnsmasq查询的，正常。

还有一个问题，我开启了第二服务器，用于解析passwall的国外ip，但是每次都是开始能解析，过一段时间谷歌就无法解析为正确的ip了，需要重启smartdns才能恢复正常，并以此循环，请问有什么问题吗

**Comment by sdwhw211** [comment]
> **问题现象**
> 简要描述问题出现的现象
> 所有查询的域名都从127.0.0.1开始
> 
> 
> **运行环境**
> 
> 1. 固件型号
>    openwrt LuCI 17.01 Lienol（git-297a920）
>    配合adguardhome去广告使用，smartdns为adh的上游
> 2. 运营商
>    移动
> 
> **重现步骤**
> 
> 1. 上游DNS配置。
> 
> ```
> speed-check-mode tcp:80,tcp:443,ping
> 
> server 202.141.178.13:5353
> server 202.38.93.153:5353
> server 202.141.162.123:5353
> # server 2001:da8::666
> server 114.114.114.114
> server 223.5.5.5
> 
> 
> server-tcp 9.9.9.9 -group fq_dns -exclude-default-group
> server-tcp 8.8.8.8 -group fq_dns -exclude-default-group
> server-tcp 1.0.0.1 -group fq_dns -exclude-default-group
> server-tcp  208.67.222.222:5353 -group fq_dns -exclude-default-group
> server-tcp 101.6.6.6:5353
> 
> server-tls 115.159.131.230 -host-name dns.rubyfish.cn
> server-tls dns.rubyfish.cn
> server-tls dns.233py.com
> server-tls 8.8.8.8 -host-name dns.google -group fq_dns -exclude-default-group
> server-tls dns.google -group fq_dns -exclude-default-group
> server-tls 1.0.0.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group
> server-tls 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group
> server-tls 202.141.176.110
> # server-tls 2001:da8:d800:95::110
> 
> # server-https https://202.141.178.13/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
> server-https https://202.38.93.153/resolve -host-name neatdns.ustclug.org -http-host neatdns.ustclug.org
> server-https https://neatdns.ustclug.org/resolve
> server-https https://115.159.131.230/resolve -host-name dns.rubyfish.cn -http-host dns.rubyfish.cn
> server-https https://dns.rubyfish.cn/dns-query
> # server-https https://45.77.180.10/resolve -host-name dns.containerpi.com -http-host dns.containerpi.com
> server-https https://dns.containerpi.com/dns-query
> server-https https://210.17.9.228/dns-query -host-name dns.twnic.tw -http-host dns.twnic.tw
> server-https https://dns.twnic.tw/dns-query
> server-https https://i.233py.com/dns-query
> server-https https://9.9.9.9/dns-query -host-name dns9.quad9.net -http-host dns9.quad9.net -group fq_dns -exclude-default-group
> server-https https://dns9.quad9.net/dns-query -group fq_dns -exclude-default-group
> server-https https://1.0.0.1/dns-query -group fq_dns -exclude-default-group
> server-https https://cloudflare-dns.com/dns-query -group fq_dns -exclude-default-group
> server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group fq_dns -exclude-default-group
> server-https https://doh.opendns.com/dns-query -group fq_dns -exclude-default-group
> ```
> 
> 1. 访问的
>    域名
>    。google.com github.com 
>    baidu.com
> 
> **信息收集**
> ![Snipaste_2020-07-11_20-01-18](https://user-images.githubusercontent.com/44677306/87224080-e4e58c80-c3b4-11ea-991b-4db2fb82e2f7.png)

如果客户端显示127.0.0.1那么必定是dnsmasq转发到adguardhome去查询，所以客户端只显示一个，解决办法可以将所有dns查询劫持到adguardhome端口，就会显示所有客户。

**Comment by WROIATE** [comment]
这个问题解决了，拎一个我另开一个issue吧
