### ISSUE TITLE
为何 release 版本还不更新？

### ISSUE THREAD

**Issue by anafkk** [pymumu/smartdns#551]
@pymumu 作者辛苦了，距离上个版本已有两个多月，多个反馈里提到了大量 DOT/DOH 相关的问题，但目前 release 版本仍未修复

复习一下：
Crash 崩溃：https://github.com/pymumu/smartdns/issues/529
超时：https://github.com/pymumu/smartdns/issues/536
nameserver 指定域名用特定 group 解析失败：https://github.com/pymumu/smartdns/issues/524
编译器更换导致 DoT/DoH 不可用 https://github.com/pymumu/smartdns/issues/511

**Comment by pymumu** [comment]
crash的问题我自己设备无法复现，所以不好定位，代码库上更新了几个点，可以自行编译下看看。
你的设备也有doh导致异常的问题？

**Comment by jtzgc** [comment]
试了两天AGH很不习惯，还是SMD顺畅，期待版本更新

**Comment by anafkk** [comment]
@pymumu 我个人没有遇到 crash 问题，我遇到的两个主要的问题是：
1. release 版更换编译器后 DoT/DoH 不可用：https://github.com/pymumu/smartdns/issues/511

**Comment by anafkk** [comment]
@jtzgc  agh  那个就是无脑并发，在 Dnsmasq 里设置 all-servers 并发并设置并发数也能达到相同的效果，agh 反而冗余

**Comment by pymumu** [comment]
> @pymumu 我个人没有遇到 crash 问题，我遇到的两个主要的问题是：
> 
> 1. release 版更换编译器后 DoT/DoH 不可用：https://github.com/pymumu/smartdns/issues/511
> 
> 2. 用 nameserver 参数将 DoH 域名发送给了指定的 group 去解析后，反复选择最优 IP：https://github.com/pymumu/smartdns/issues/524
> 
> 
> 
> 还望能整体解决下，现在最新  release 版的 DoT/DoH 基本上就是不可用的状态

你什么设备，doh日志里面报什么错误？

**Comment by CORE2021** [comment]
> @jtzgc agh 那个就是无脑并发，在 Dnsmasq 里设置 all-servers 并发并设置并发数也能达到相同的效果，agh 反而冗余

已经有返回最快了啊

**Comment by anafkk** [comment]
@pymumu 麻烦看下里面引用的 issues，  里面均提供过日志文件...

**Comment by pymumu** [comment]
你是mips的CPU吗？

可以尝试下载openwrt的版本看看。

https://download.openwrt.org/snapshots/packages/[arch]/packages/smartdns_xxxx.ipk

**Comment by anafkk** [comment]
@pymumu 我编译的 Lienol 的 OpenWrt：https://github.com/Lienol/openwrt，仅自带 usb和ipv6 的无插件纯净版

**Comment by jkle112** [comment]
可以的话还是希望官方发布IPK 文件，及时更新，实在不行，可以推出测试版本，有问题大家反馈，这样减轻开发者的后期工作量。
