### ISSUE TITLE
新浪微博偶尔会提示频繁

### ISSUE THREAD

**Issue by chainofhonor** [pymumu/smartdns#552]
我猜测可能是dns解析的时候smartdns访问了服务器多个IP,以确定哪个最优
然后瞬间客户端又访问了,就被新浪的防火墙挡住了

**Comment by pymumu** [comment]
这个感觉没关系。
无smartdns时，dns返回多个IP，客户端会随机选一个的，也可能用不通IP访问服务器的情况。

**Comment by chainofhonor** [comment]
额,不是DNS的问题,我换了其他DNS了,今天又出现这个提示了,估计就是新浪的服务器的问题  囧

**Comment by cheneyxx** [comment]
我的新浪微博也这样
