### ISSUE TITLE
请教一个关于nameserver使用上域名匹配的问题

### ISSUE THREAD

**Issue by yuanlam** [pymumu/smartdns#555]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

我想利用dnsmasq-china-list 配合nameserver 利用server的分组达到国内外DNS查询分流，想请教一下，smartdns对域名的匹配上，baidu.com会不会自动匹配前缀呢，例如xxx.baidu.com，还是只是单单匹配baidu.com？

**Comment by pymumu** [comment]
smartdns所有匹配采用的是后缀匹配，和dnsmasq一致。

**Comment by yuanlam** [comment]
谢谢，感谢解答
