### ISSUE TITLE
作者您好，不打算支持json格式的doh和DNSSEC吗？

### ISSUE THREAD

**Issue by chuansao-258** [pymumu/smartdns#557]
**需求应用场景**
请描述需求应用的场景和方式。
中科大的doh：https://neatdns.ustclug.org/resolve无法使用
**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  
x86 openwrt
2. 固件信息
R20.7.7

**Comment by anafkk** [comment]
@chuansao-258 看下这里面的解答：https://github.com/pymumu/smartdns/issues/121，json格式不在RFC规范中，所以 smartdns只会支持wireformat格式的DoH。
