### ISSUE TITLE
发现一个DNS重定向的Bug

### ISSUE THREAD

**Issue by yxz626** [pymumu/smartdns#558]
**需求应用场景**
smartdns启用DNS重定向时，在系统Dnsmasq里的DNS转发仅设置为：“127.0.0.1#端口”，这有一定几率使得smartdns作用失效，即nslookup查询www时返回多个地址。

**建议的方案**
建议启用DNS重定向时，在系统Dnsmasq里的DNS转发中增加：“lan ip#端口”，比如“192.168.0.1#6053”或“10.0.0.1#6053”，就不再出现smartdns失效情况。

**设备信息**
1. 设备信息（CPU，厂家）  
Intel(R) Core(TM) i5-4200U CPU
2. 固件信息
OpenWrt R20.7.1 SPP v7.1[2020] Compiled by eSir / LuCI Master (git-20.180.30743-de9fdad)

**Comment by pymumu** [comment]
没看懂，是dnsmasq的上游被设置了多个吗？

如果只配置127.0.0.1的话，dnsmasq应该不会再使用其他局域网IP地址访问smartdns。

**Comment by yxz626** [comment]
谢谢回复！
我的意思是说dnsmasq中dns转发需同事设置127.0.0.1和lan ip(如192.168.0.1)后smartdns功能才正常，若只是设置127.0.0.1转发则有一定几率失效，特别是在客户端用nslookup查询的时候。

**Comment by pymumu** [comment]
明白你说的，最好发一下你dnsmasq的配置。
/etc/dnsmasq.conf文件。

**Comment by yxz626** [comment]
我的/etc/dnsmasq.conf文件

[dnsmasq.zip](https://github.com/pymumu/smartdns/files/4953236/dnsmasq.zip)

**Comment by pymumu** [comment]
/tmp/etc/dnsmasq.conf吧。

ps命令查看dnsmasq使用的配置文件路径。

**Comment by yxz626** [comment]
谢谢回复，我用PS查看的dnsmasq如下。
[dnsmasq.conf.zip](https://github.com/pymumu/smartdns/files/4981997/dnsmasq.conf.zip)

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
