### ISSUE TITLE
发现一个不知是smartdns还是kdig的bug

### ISSUE THREAD

**Issue by PussAzuki** [pymumu/smartdns#559]
**问题现象**  
简要描述问题出现的现象
使用Alidns和DNSPod的DoT，检验主机名总是通不过，直到将验证用的名称改成了 *.alidns.com *.dns.pub 才可用

**运行环境**
1. 固件型号  
openwrt
2. 运营商  
任意(?)
**重现步骤**
1. 上游DNS配置。  
server-tls 223.5.5.5:853 -whitelist-ip -group local -tls-host-verify alidns.com
server-tls 162.14.21.178:853 -whitelist-ip -group local -tls-host-verify dns.pub

这之后log显示 开始查询后 远程主机名（*.alidns.com）与这边需求的（alidns.com）不同而无法使用

server-tls 223.5.5.5:853 -whitelist-ip -group local -tls-host-verify *.alidns.com
server-tls 162.14.21.178:853 -whitelist-ip -group local -tls-host-verify *.dns.pub
改成这样才正常

但是 kdig正常，见下面
2. 访问的域名。  
任意

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

$ kdig -d @223.6.6.6 +tls-ca +tls-host=alidns.com baidu.com
;; DEBUG: Querying for owner(baidu.com.), class(1), type(1), server(223.6.6.6), port(853), protocol(TCP)
;; DEBUG: TLS, imported 127 system certificates
;; DEBUG: TLS, received certificate hierarchy:
;; DEBUG:  #1, C=CN,ST=浙江省,L=杭州市,O=阿里巴巴（中国）网络技术有限公司,CN=*.alidns.com
;; DEBUG:      SHA-256 PIN: +ACy/80ww+XSVtadTogT+4L2XuYk9ZbigM6mnqmbgX8=
;; DEBUG:  #2, C=BE,O=GlobalSign nv-sa,CN=GlobalSign RSA OV SSL CA 2018
;; DEBUG:      SHA-256 PIN: hETpgVvaLC0bvcGG3t0cuqiHvr4XyP2MTwCiqhgRWwU=
;; DEBUG: TLS, skipping certificate PIN check
;; DEBUG: TLS, The certificate is trusted.
;; TLS session (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 59781
;; Flags: qr rd ra; QUERY: 1; ANSWER: 2; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 4096 B; ext-rcode: NOERROR
;; PADDING: 86 B

;; QUESTION SECTION:
;; baidu.com.                   IN      A

;; ANSWER SECTION:
baidu.com.              134     IN      A       39.156.69.79
baidu.com.              134     IN      A       220.181.38.148

;; Received 178 B
;; Time 2020-07-18 15:12:27 CST
;; From 223.6.6.6@853(TCP) in 9.6 ms

很好奇这个是smartdns的bug还是kdig的bug

**Comment by pymumu** [comment]
这里是检测证书里面的CN是否符合-tls-host-verify的设置值。
这里有一个域名包含的逻辑关系。

smartdns再设计的时候，想的是用-tls-host-verify指定的值，校验CN。
但有些软件似乎是反过来了，用CN校验-tls-host-verify。

可以先使用证书校验。

**Comment by PussAzuki** [comment]
那两者在安全性和测试时有什么优劣吗？
证书我有安装 ca-certificates 和 ca-bundle 软件包...

**Comment by pymumu** [comment]
证书的更安全

**Comment by pymumu** [comment]
使用最新版本，如果有问题reopen issue，提交日志。
