### ISSUE TITLE
大佬能出个单个运行文件的版本吗，arm64的，在安卓上运行

### ISSUE THREAD

**Issue by charli2014** [pymumu/smartdns#56]
大佬能出个单个运行文件的版本吗，arm64的，在安卓上运行，这样也能加快访问速度。

**Comment by charli2014** [comment]
安卓上用命令行运行，然后用iptable劫持53端口，转发安卓所有dns请求

**Comment by pymumu** [comment]
暂时没考虑这方面的需求。
主要是技术上有限制，andriod的程序没有root权限，很多设置搞不了。
比如53端口绑定，iptalbe命令，ping都不行。

建议的玩法是：
在家里路由器上部署smartdns，然后手机VPN到家里访问网络。

**Comment by charli2014** [comment]
谢谢大佬，不过可以用magisk包的形式安装运行，magisk可以安装busybox，里面包含了iptable，nslook等常见命令的。

**Comment by ziyuedi** [comment]
> 
> 
> 暂时没考虑这方面的需求。
> 主要是技术上有限制，andriod 的程序没有 root 权限，很多设置搞不了。
> 比如 53 端口绑定，iptalbe 命令，ping 都不行。
> 
> 建议的玩法是：
> 在家里路由器上部署 smartdns，然后手机 VPN 到家里访问网络。

同有此需求，（可以用magisk实现），VPN连接/自建服务器如果使用不支持edns的dns/网站的ns不支持edns，效果并不好。即使支持edns，测速也是在服务器上测，测试结果对客户端并不准确。
