### ISSUE TITLE
最新版smartdns网络重连无效

### ISSUE THREAD

**Issue by WROIATE** [pymumu/smartdns#561]
**问题现象** 
 
今天刚编译的smartdns，使用lienol的源，出现在路由器重启后查询dns失效，必须重启服务才能恢复

**运行环境**
1. 固件型号  

OpenWrt SNAPSHOT / LuCI 17.01 Lienol (git-faaf770)

2. 运营商  

移动

**重现步骤**
1. 上游DNS配置。  
```
speed-check-mode tcp:443,tcp:80,ping

server 202.141.178.13:5353 -check-edns
server 202.38.93.153:5353 -check-edns
server 202.141.162.123:5353 -check-edns
server ns-a.ustclug.org -check-edns


server-tcp 8.8.8.8 -group fq_dns -exclude-default-group
server-tcp 1.0.0.1 -group fq_dns -exclude-default-group
server-tcp 208.67.222.222:5353  -group fq_dns -exclude-default-group

server-tls 1.1.1.1
server-tls 115.159.131.230 -host-name dns.rubyfish.cn
# server-tls dns.rubyfish.cn
server-tls dns.233py.com -group fq_dns -exclude-default-group
server-tls 8.8.8.8 -host-name dns.google -group fq_dns -exclude-default-group
# server-tls dns.google -group fq_dns -exclude-default-group
server-tls 1.0.0.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group
# server-tls 1dot1dot1dot1.cloudflare-dns.com -group fq_dns -exclude-default-group

# server-https https://doh.dns.sb/dns-query  -group true_dns -exclude-default-group
server-https https://dns.alidns.com/dns-query
server-https https://neatdns.ustclug.org/resolve
# server-https https://115.159.131.230/resolve -host-name dns.rubyfish.cn -http-host dns.rubyfish.cn
# server-https https://dns.rubyfish.cn/dns-query  -group true_dns -exclude-default-group
server-https https://dns.containerpi.com/dns-query -group fq_dns -exclude-default-group
# server-https https://210.17.9.228/dns-query -host-name dns.twnic.tw -http-host dns.twnic.tw
server-https https://dns.twnic.tw/dns-query -group fq_dns -exclude-default-group
server-https https://i.233py.com/dns-query -group fq_dns -exclude-default-group
# server-https https://9.9.9.9/dns-query -host-name dns9.quad9.net -http-host dns9.quad9.net -group fq_dns -exclude-default-group
server-https https://dns9.quad9.net/dns-query -group fq_dns -exclude-default-group
# server-https https://1.0.0.1/dns-query -group fq_dns -exclude-default-group
server-https https://cloudflare-dns.com/dns-query -group fq_dns -exclude-default-group
server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group fq_dns -exclude-default-group
# server-https https://doh.opendns.com/dns-query -group fq_dns -exclude-default-group
```
2. 访问的域名。  

**信息收集**  
```
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.38.93.153 failed, Network unreachable, type: 0 [2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.141.178.13 failed, Network unreachable, type: 0[2020-07-20 20:52:56,736][ERROR][     dns_client.c:1585] connect 115.159.131.230 failed, Network unreachable
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:1585] connect 1.1.1.1 failed, Network unreachable
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.141.162.123 failed, Network unreachable, type: 0
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.38.93.153 failed, Network unreachable, type: 0 [2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.141.178.13 failed, Network unreachable, type: 0[2020-07-20 20:52:56,736][ERROR][     dns_client.c:2579] Send query to upstream server failed.
[2020-07-20 20:52:56,736][ERROR][     dns_server.c:2296] send dns request failed.
[2020-07-20 20:52:56,736][ERROR][     dns_server.c:2374] do query music.163.com failed.
[2020-07-20 20:52:56,736][ERROR][     dns_server.c:2969] dns server process failed.
[2020-07-20 20:52:56,736][ INFO][     dns_server.c:2359] query server interface.music.163.com from 127.0.0.1, qtype = 1
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:1585] connect 115.159.131.230 failed, Network unreachable
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:1585] connect 1.1.1.1 failed, Network unreachable
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.141.162.123 failed, Network unreachable, type: 0
[2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.38.93.153 failed, Network unreachable, type: 0 [2020-07-20 20:52:56,736][ERROR][     dns_client.c:2553] send query to 202.141.178.13 failed, Network unreachable, type: 0[2020-07-20 20:52:56,736][ERROR][     dns_client.c:1585] connect 115.159.131.230 failed, Network unreachable
[2020-07-20 20:52:56,737][ERROR][     dns_client.c:1585] connect 1.1.1.1 failed, Network unreachable
[2020-07-20 20:52:56,737][ERROR][     dns_client.c:2553] send query to 202.141.162.123 failed, Network unreachable, type: 0
[2020-07-20 20:52:56,737][ERROR][     dns_client.c:2553] send query to 202.38.93.153 failed, Network unreachable, type: 0 [2020-07-20 20:52:56,737][ERROR][     dns_client.c:2553] send query to 202.141.178.13 failed, Network unreachable, type: 0[2020-07-20 20:52:56,737][ERROR][     dns_client.c:2579] Send query to upstream server failed.
[2020-07-20 20:52:56,737][ERROR][     dns_server.c:2296] send dns request failed.
[2020-07-20 20:52:56,737][ERROR][     dns_server.c:2374] do query interface.music.163.com failed.
[2020-07-20 20:52:56,737][ERROR][     dns_server.c:2969] dns server process failed.
[2020-07-20 20:52:56,737][ INFO][     dns_server.c:2359] query server interface.music.163.com from 127.0.0.1, qtype = 28
[2020-07-20 20:52:56,737][ERROR][     dns_client.c:1585] connect 115.159.131.230 failed, Network unreachable
[2020-07-20 20:52:56,737][ERROR][     dns_client.c:1585] connect 1.1.1.1 failed, Network unreachable
[2020-07-20 20:52:56,737][ERROR][     dns_client.c:2553] send query to 202.141.162.123 failed, Network unreachable, type: 0
```

**Comment by WROIATE** [comment]
目前我加了一个启动脚本来监控并重启
```
#!/bin/sh
log_file="/root/link.log"
echo -n "" > $log_file
while true
do
        ping -c 4 1.1.1.1
        if [ $? == 0 ];then
                `/etc/init.d/smartdns restart`
                echo "[`date +'%Y-%m-%d %H:%M:%S'`] success" >> $log_file
                break
        fi
        sleep 3
        echo "[`date +'%Y-%m-%d %H:%M:%S'`] failed" >> $log_file
done
```

我自己脚本的log
```
[2020-07-20 21:12:33] failed
[2020-07-20 21:12:36] failed
[2020-07-20 21:12:39] failed
[2020-07-20 21:12:42] failed
[2020-07-20 21:12:47] success
```

**Comment by pymumu** [comment]
看日志是提示网络有问题，网络不通。
有可能pppoe自动断开后，没有重新连接。

**Comment by WROIATE** [comment]
> 看日志是提示网络有问题，网络不通。
> 有可能pppoe自动断开后，没有重新连接。

可是我确定的是pppoe之后连通了，能ping通1.1.1.1，为什么smartdns没有重连呢

**Comment by pymumu** [comment]
一直再重连啊，connect的就是

检查你的防火墙配置看看

**Comment by WROIATE** [comment]
> 一直再重连啊，connect的就是
> 
> 检查你的防火墙配置看看

可是我日志看到后面就没有error了，全是info查询的记录，但是却并没有返回ip，nslookup也是timeout

**Comment by pymumu** [comment]
connect 1.1.1.1 failed, Network unreachable

这里就表示连接1.1.1.1， 但网络不通。

出问题的时候，到路由器里面ping一下看看吧。

**Comment by WROIATE** [comment]
出问题的时候就是路由器重启后还在pppoe联网的时候

**Comment by pymumu** [comment]
如果还没连接好网络，那报错也是正常的。
但连接网络成功后，smartdns应该就要恢复查询了。
如果没有，那在看看网络是否正常。

另外，可以用最新代码编译一个版本，最新代码增加了重试机制。使用上会好一点。

**Comment by WROIATE** [comment]
> 如果还没连接好网络，那报错也是正常的。
> 但连接网络成功后，smartdns应该就要恢复查询了。
> 如果没有，那在看看网络是否正常。
> 
> 另外，可以用最新代码编译一个版本，最新代码增加了重试机制。使用上会好一点。

可是我用的就是最新源码，之前的反而还没问题

**Comment by huifukejian** [comment]
这个问题我也遇到了。版本smartdns 1.2020.30
openwrt日志
Sun Aug  2 15:02:13 2020 daemon.info pppd[1818]: LCP terminated by peer
Sun Aug  2 15:02:13 2020 daemon.info pppd[1818]: Connect time 2875.1 minutes.
Sun Aug  2 15:02:13 2020 daemon.info pppd[1818]: Sent 1261188004 bytes, received 3652644475 bytes.
Sun Aug  2 15:02:13 2020 daemon.notice netifd: Network device 'pppoe-wan' link is down
Sun Aug  2 15:02:13 2020 daemon.notice pppd[1818]: Modem hangup
Sun Aug  2 15:02:13 2020 daemon.notice pppd[1818]: Connection terminated.
Sun Aug  2 15:02:13 2020 daemon.info pppd[1818]: Sent PADT
Sun Aug  2 15:02:13 2020 daemon.notice netifd: Interface 'wan' has lost the connection
Sun Aug  2 15:02:13 2020 daemon.info pppd[1818]: Exit.
Sun Aug  2 15:02:13 2020 daemon.notice netifd: Interface 'wan' is now down
Sun Aug  2 15:02:13 2020 daemon.notice netifd: Interface 'wan' is setting up now
Sun Aug  2 15:02:13 2020 daemon.err insmod: module is already loaded - slhc
Sun Aug  2 15:02:13 2020 daemon.err insmod: module is already loaded - ppp_generic
Sun Aug  2 15:02:13 2020 daemon.err insmod: module is already loaded - pppox
Sun Aug  2 15:02:13 2020 daemon.err insmod: module is already loaded - pppoe
Sun Aug  2 15:02:13 2020 daemon.notice netifd: wan (14125): uci: Entry not found
Sun Aug  2 15:02:13 2020 daemon.notice netifd: wan (14125): sh: out of range
Sun Aug  2 15:02:13 2020 daemon.info pppd[14153]: Plugin rp-pppoe.so loaded.
Sun Aug  2 15:02:13 2020 daemon.info pppd[14153]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
Sun Aug  2 15:02:13 2020 daemon.notice pppd[14153]: pppd 2.4.8 started by root, uid 0
Sun Aug  2 15:02:13 2020 daemon.info pppd[14153]: PPP session is 18420
Sun Aug  2 15:02:13 2020 daemon.warn pppd[14153]: Connected to da:86:8e:8a:00:34 via interface eth0.2
Sun Aug  2 15:02:14 2020 daemon.info pppd[14153]: Renamed interface ppp0 to pppoe-wan
Sun Aug  2 15:02:14 2020 daemon.info pppd[14153]: Using interface pppoe-wan
Sun Aug  2 15:02:14 2020 daemon.notice pppd[14153]: Connect: pppoe-wan <--> eth0.2
Sun Aug  2 15:02:16 2020 daemon.info pppd[14153]: syncppp not active
Sun Aug  2 15:02:17 2020 daemon.info pppd[14153]: Remote message: Authentication success,Welcome!
Sun Aug  2 15:02:17 2020 daemon.notice pppd[14153]: PAP authentication succeeded
Sun Aug  2 15:02:17 2020 daemon.notice pppd[14153]: peer from calling number DA:86:8E:8A:00:34 authorized
Sun Aug  2 15:02:17 2020 daemon.notice pppd[14153]: local  IP address 113.118.47.225
Sun Aug  2 15:02:17 2020 daemon.notice pppd[14153]: remote IP address 113.118.44.1
Sun Aug  2 15:02:17 2020 daemon.notice pppd[14153]: primary   DNS address 202.96.128.86
Sun Aug  2 15:02:17 2020 daemon.notice pppd[14153]: secondary DNS address 202.96.134.33
Sun Aug  2 15:02:17 2020 daemon.notice netifd: Network device 'pppoe-wan' link is up
Sun Aug  2 15:02:17 2020 daemon.notice netifd: Interface 'wan' is now up

smartdns日志
[2020-08-02 15:03:19,716][ERROR][     dns_client.c:2492] send query to 223.6.6.6 failed, Bad address, type: 3
[2020-08-02 15:03:19,716][ERROR][     dns_client.c:2492] send query to 223.5.5.5 failed, Bad address, type: 3

smartdns解析不了dns
路由器ping 119.29.29.29没有问题

**Comment by WROIATE** [comment]
> 这个问题我也遇到了。版本smartdns 1.2020.30
> openwrt日志
> Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: LCP terminated by peer
> Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Connect time 2875.1 minutes.
> Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Sent 1261188004 bytes, received 3652644475 bytes.
> Sun Aug 2 15:02:13 2020 daemon.notice netifd: Network device 'pppoe-wan' link is down
> Sun Aug 2 15:02:13 2020 daemon.notice pppd[1818]: Modem hangup
> Sun Aug 2 15:02:13 2020 daemon.notice pppd[1818]: Connection terminated.
> Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Sent PADT
> Sun Aug 2 15:02:13 2020 daemon.notice netifd: Interface 'wan' has lost the connection
> Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Exit.
> Sun Aug 2 15:02:13 2020 daemon.notice netifd: Interface 'wan' is now down
> Sun Aug 2 15:02:13 2020 daemon.notice netifd: Interface 'wan' is setting up now
> Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - slhc
> Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - ppp_generic
> Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - pppox
> Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - pppoe
> Sun Aug 2 15:02:13 2020 daemon.notice netifd: wan (14125): uci: Entry not found
> Sun Aug 2 15:02:13 2020 daemon.notice netifd: wan (14125): sh: out of range
> Sun Aug 2 15:02:13 2020 daemon.info pppd[14153]: Plugin rp-pppoe.so loaded.
> Sun Aug 2 15:02:13 2020 daemon.info pppd[14153]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
> Sun Aug 2 15:02:13 2020 daemon.notice pppd[14153]: pppd 2.4.8 started by root, uid 0
> Sun Aug 2 15:02:13 2020 daemon.info pppd[14153]: PPP session is 18420
> Sun Aug 2 15:02:13 2020 daemon.warn pppd[14153]: Connected to da:86:8e:8a:00:34 via interface eth0.2
> Sun Aug 2 15:02:14 2020 daemon.info pppd[14153]: Renamed interface ppp0 to pppoe-wan
> Sun Aug 2 15:02:14 2020 daemon.info pppd[14153]: Using interface pppoe-wan
> Sun Aug 2 15:02:14 2020 daemon.notice pppd[14153]: Connect: pppoe-wan <--> eth0.2
> Sun Aug 2 15:02:16 2020 daemon.info pppd[14153]: syncppp not active
> Sun Aug 2 15:02:17 2020 daemon.info pppd[14153]: Remote message: Authentication success,Welcome!
> Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: PAP authentication succeeded
> Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: peer from calling number DA:86:8E:8A:00:34 authorized
> Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: local IP address 113.118.47.225
> Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: remote IP address 113.118.44.1
> Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: primary DNS address 202.96.128.86
> Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: secondary DNS address 202.96.134.33
> Sun Aug 2 15:02:17 2020 daemon.notice netifd: Network device 'pppoe-wan' link is up
> Sun Aug 2 15:02:17 2020 daemon.notice netifd: Interface 'wan' is now up
> 
> smartdns日志
> [2020-08-02 15:03:19,716][ERROR][ dns_client.c:2492] send query to 223.6.6.6 failed, Bad address, type: 3
> [2020-08-02 15:03:19,716][ERROR][ dns_client.c:2492] send query to 223.5.5.5 failed, Bad address, type: 3
> 
> smartdns解析不了dns
> 路由器ping 119.29.29.29没有问题

那你可以先用我的脚本应急一下，把1.1.1.1换成你确定能ping通的就行

**Comment by huifukejian** [comment]
> > 这个问题我也遇到了。版本smartdns 1.2020.30
> > openwrt日志
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: LCP terminated by peer
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Connect time 2875.1 minutes.
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Sent 1261188004 bytes, received 3652644475 bytes.
> > Sun Aug 2 15:02:13 2020 daemon.notice netifd: Network device 'pppoe-wan' link is down
> > Sun Aug 2 15:02:13 2020 daemon.notice pppd[1818]: Modem hangup
> > Sun Aug 2 15:02:13 2020 daemon.notice pppd[1818]: Connection terminated.
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Sent PADT
> > Sun Aug 2 15:02:13 2020 daemon.notice netifd: Interface 'wan' has lost the connection
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[1818]: Exit.
> > Sun Aug 2 15:02:13 2020 daemon.notice netifd: Interface 'wan' is now down
> > Sun Aug 2 15:02:13 2020 daemon.notice netifd: Interface 'wan' is setting up now
> > Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - slhc
> > Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - ppp_generic
> > Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - pppox
> > Sun Aug 2 15:02:13 2020 daemon.err insmod: module is already loaded - pppoe
> > Sun Aug 2 15:02:13 2020 daemon.notice netifd: wan (14125): uci: Entry not found
> > Sun Aug 2 15:02:13 2020 daemon.notice netifd: wan (14125): sh: out of range
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[14153]: Plugin rp-pppoe.so loaded.
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[14153]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
> > Sun Aug 2 15:02:13 2020 daemon.notice pppd[14153]: pppd 2.4.8 started by root, uid 0
> > Sun Aug 2 15:02:13 2020 daemon.info pppd[14153]: PPP session is 18420
> > Sun Aug 2 15:02:13 2020 daemon.warn pppd[14153]: Connected to da:86:8e:8a:00:34 via interface eth0.2
> > Sun Aug 2 15:02:14 2020 daemon.info pppd[14153]: Renamed interface ppp0 to pppoe-wan
> > Sun Aug 2 15:02:14 2020 daemon.info pppd[14153]: Using interface pppoe-wan
> > Sun Aug 2 15:02:14 2020 daemon.notice pppd[14153]: Connect: pppoe-wan <--> eth0.2
> > Sun Aug 2 15:02:16 2020 daemon.info pppd[14153]: syncppp not active
> > Sun Aug 2 15:02:17 2020 daemon.info pppd[14153]: Remote message: Authentication success,Welcome!
> > Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: PAP authentication succeeded
> > Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: peer from calling number DA:86:8E:8A:00:34 authorized
> > Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: local IP address 113.118.47.225
> > Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: remote IP address 113.118.44.1
> > Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: primary DNS address 202.96.128.86
> > Sun Aug 2 15:02:17 2020 daemon.notice pppd[14153]: secondary DNS address 202.96.134.33
> > Sun Aug 2 15:02:17 2020 daemon.notice netifd: Network device 'pppoe-wan' link is up
> > Sun Aug 2 15:02:17 2020 daemon.notice netifd: Interface 'wan' is now up
> > smartdns日志
> > [2020-08-02 15:03:19,716][ERROR][ dns_client.c:2492] send query to 223.6.6.6 failed, Bad address, type: 3
> > [2020-08-02 15:03:19,716][ERROR][ dns_client.c:2492] send query to 223.5.5.5 failed, Bad address, type: 3
> > smartdns解析不了dns
> > 路由器ping 119.29.29.29没有问题
> 
> 那你可以先用我的脚本应急一下，把1.1.1.1换成你确定能ping通的就行

openwrt网络重连会不会触发什么脚本，感觉在那里加上 smartdns  restart 比较好

**Comment by pymumu** [comment]
smartdns被配置在防火墙变化时，重启
service_triggers() {
	procd_add_reload_trigger firewall
	procd_add_reload_trigger smartdns
}

你可以增加一下网络连接的触发接口看看

**Comment by huifukejian** [comment]
> smartdns被配置在防火墙变化时，重启
> service_triggers() {
> procd_add_reload_trigger firewall
> procd_add_reload_trigger smartdns
> }
> 
> 你可以增加一下网络连接的触发接口看看

是加在  /etc/init.d/smartdns 里面吗？ 好像没有效果， 在网上找到了另外一种方式，创建了一个文件/etc/hotplug.d/iface/098-smartdns 加入下面代码
#!/bin/sh

[ "$ACTION" = ifup ] || exit 0
sleep 10
/etc/init.d/smartdns reload

每次wan up的时候，就重启smartdns

**Comment by WROIATE** [comment]
@huifukejian 
对，这个方法可以成功，sleep可以删掉
