### ISSUE TITLE
添加同网段的dns服务器为上游，无效

### ISSUE THREAD

**Issue by yutian33** [pymumu/smartdns#562]
**问题现象**  
1、局域网内搭建了用于内部解析的dns服务器，192.168.2.248
2、局域网内安装了openwrt，192.168.2.233 并开启了smartdns，在smartdns中设置192.168.2.248为上游服务器
3、同局域网内的电脑，设置dns服务器为192.168.2.233

电脑上访问外网正常，nslookup验证，dns服务器为smartdns，外网均只返回最快的ip
但是无法解析访问内部的域名

nslookup ftp.b
服务器:  smartdns
Address:  192.168.2.233

*** 没有 ftp.b 可以使用的 internal type for both IPv4 and IPv6 Addresses (A+AAAA)记录

强制使用192.168.2.248解析是ok的
nslookup ftp.b 192.168.2.248
服务器:  UnKnown
Address:  192.168.2.248

名称:    server3.b
Address:  192.168.2.203
Aliases:  ftp.b

请问应如何解决？
谢谢！

**Comment by pymumu** [comment]
发一下log看看。

**Comment by yutian33** [comment]
> 发一下log看看。

/tmp 下未找到smartdns.XXX.core文件 已开启生成coredump

**Comment by yutian33** [comment]
解决了，是DNSMASQ的重绑定保护导致的，在openwrt后台 -> 网络 ->DHCP/DNS-> 一般设置 -> 重绑定保护（丢弃 RFC1918 上行响应数据）
把这个的勾去掉，就OK了。

**Comment by Johnny-Song-Tiger** [comment]
> 解决了，是DNSMASQ的重绑定保护导致的，在openwrt后台 -> 网络 ->DHCP/DNS-> 一般设置 -> 重绑定保护（丢弃 RFC1918 上行响应数据）
> 把这个的勾去掉，就OK了。

靠谱！
