### ISSUE TITLE
请问大神，我在debian安装smatrdns设置问题

### ISSUE THREAD

**Issue by 281677160** [pymumu/smartdns#563]
bind [::]:53
bind [::]:6053 -group dns1 no-dualstack-selection
bind [::]:7913 -group dns2 -no-speed-check -no-cache no-dualstack-selection

cache-size 5120
log-level info
force-AAAA-SOA yes
rr-ttl-min 20
prefetch-domain yes
serve-expired yes
serve-expired-ttl 0

server 114.114.114.114:53 -blacklist-ip -group dns1
server 120.196.165.24:53 -blacklist-ip -group dns1
server 223.5.5.5:53 -blacklist-ip -group dns1
server 119.29.29.29:53 -blacklist-ip -group dns1
server 101.226.4.6:53 -blacklist-ip -group dns1
server 180.76.76.76:53 -blacklist-ip -group dns1
server 1.2.4.8:53 -blacklist-ip -group dns1

server 8.8.8.8:53 -blacklist-ip -group dns2
server 8.8.4.4:53 -blacklist-ip -group dns2
server 208.67.222.222:53 -blacklist-ip -group dns2
server 199.85.126.10:53 -blacklist-ip -group dns2
server 84.200.69.80:53 -blacklist-ip -group dns2
server 64.6.64.6:53 -blacklist-ip -group dns2

以上是默认设置加我自己按说明摸索的设置，请问这样设置对不对，能写一份大神你的设置给我吗？

**Comment by pymumu** [comment]
server配置国内走国内，国外走tls/https等协议。

**Comment by danshui-git** [comment]
> 服务器配置国内走本地，国外走tls / https等协议。

现在除了是把走国外的dns修改下，还请问大神，请问我这个格式的设置对吗？我不需要IPV6的，就这样修改下国外DNS就可以了？

**Comment by pymumu** [comment]
格式没有问题，但黑名单地址列表不要弄错，务必要添加可信服务器。否则可能会无IP可用。

**Comment by 281677160** [comment]
黑名单是啥都不太明白啊，我不写-blacklist-ip也可以，写也可以上网，主要是在debian上没有跟网页一样有文本可以清晰的知道在干嘛，感谢你在百忙当中抽时间来回答我问题，如果你在配置说明那里弄一份举例样式就容易明白多了，没办法，小白一个，感谢大神！！！

**Comment by pymumu** [comment]
看readme和faq吧

**Comment by 281677160** [comment]
> 看readme和faq吧

谢谢大神，刚赞助了一点，钱不多，希望别介意

**Comment by pymumu** [comment]
多谢支持
