### ISSUE TITLE
有没有人用redmiac2100使用smartdns导致内核gg的

### ISSUE THREAD

**Issue by paldier** [pymumu/smartdns#565]
代码完全和85p共用，所以应该是没问题的，可能是128内存太小？不过smartdns好像也没要求太多内存吧，目前完全没有头绪
有相同情况可以说下smartdns的版本

**Comment by pymumu** [comment]
看看内存方面有没有占用过多。dmesg看看。

**Comment by paldier** [comment]
内核都gg了还怎么看，不过老毛子好像没问题？

**Comment by pymumu** [comment]
你用看是因为内核bug导致，还是内存不够导致的

**Comment by paldier** [comment]
看不出来，我在想是不是你的预编译可能对内存有什么要求，之前我也一直以为是内核bug，直到为了取消干扰因素取消了smartdns

**Comment by pymumu** [comment]
你cache配置多少

**Comment by paldier** [comment]
9999，这个占不了多少内存吧

**Comment by paldier** [comment]
我好像想到了，华硕会分配一部分内存做内存盘然后挂成swap，这样剩余内存会非常小，我去试试看

**Comment by paldier** [comment]
确认问题解决，确实是内存不够的问题
