### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by jkle112** [pymumu/smartdns#566]
Openwrt x64  in mini PC
Hope add certificate pinning in.
The certificate pinning was canceled in the Chrome browser at the end of April 2018. Since version 72, Firefox has also turned off certificate pinning by default. Without certificate pinning, it will not be able to resist such national-level hacking attacks.
Sandbox the cookies that through the mini PC for more security.
need add WebRTC Protection.

**Comment by pymumu** [comment]
I don't understand how to use this, can you explain it in detail?
If you want smartdns to verify the remote server, you can use spki-pin or certificate verification

**Comment by jkle112** [comment]
增加证书钉扎的功能，主要是防止劫持，
webRTC保护，主要是防止隐私泄露的，
cookies 沙盒主要是提供保护，最好可以借用其他的动态变化，包括printerfinger

**Comment by pymumu** [comment]
这个和DNS服务器有什么关系？不清楚机制。

不过既然chrome已经不支持了，再做也没有意义。

**Comment by jkle112** [comment]
很有必要做的，这个功能主要是防止劫持，即使加密也可以用蜜罐劫持的。
chrome已经不支持了，是因为有开源的软件了，而且体积变大对浏览器的负担加重，这不是浏览器必备的功能，所以去掉了。
SMARTDNS是查询的工具，如果被劫持基本就没有什么用了，所以有必要做，但是怎么做可以多参考不同的软件，都是开源的，有现成的定义规则，定期更新就行，就好像我从GITHUB上找到的针对SMARTDNS开发的过滤广告的CONF文件一样，直接放在配置文件夹下，运行加载就起作用了。
