### ISSUE TITLE
OpenWrt版本的luci界面修改-no-check-certificate无效

### ISSUE THREAD

**Issue by szl0834** [pymumu/smartdns#568]
**问题现象**  
在openwrt版的smartdns的luci界面上修改高级配置中的-no-check-certificate，无论钩不勾选，最后生成的配置文件（/var/etc/smartdns/smartdns.conf)里面都是带有-no-check-certificate选项的。
![2020-07-28 (2)](https://user-images.githubusercontent.com/16066867/88668004-a53cd580-d114-11ea-9fac-6d65bf364a95.png)
![2020-07-28 (1)](https://user-images.githubusercontent.com/16066867/88668025-ac63e380-d114-11ea-8a70-1b47aece3128.png)

**运行环境**
1. 固件型号  
X86_64位版本的2.36版koolshare openwrt

**Comment by pymumu** [comment]
/etc/config/smartdns配置文件里面对应的配置项是什么？

**Comment by szl0834** [comment]
> /etc/config/smartdns配置文件里面对应的配置项是什么？

config server
	option enabled '1'
	option name 'rubyfish_DoH'
	option ip 'https://118.126.68.223/dns-query'
	option type 'https'
	option blacklist_ip '0'
	option tls_host_verify 'rubyfish.cn'
	option no_check_certificate '0'
	option host_name 'rubyfish.cn'
	option http_host 'rubyfish.cn'

**Comment by pymumu** [comment]
勾选才是不校验

**Comment by szl0834** [comment]
> 勾选才是不校验
我勾选了，然后/etc/config/smartdns显示的是这个样子

```
config server
	option enabled '1'
	option name 'rubyfish_DoH'
	option ip 'https://118.126.68.223/dns-query'
	option type 'https'
	option blacklist_ip '0'
	option tls_host_verify 'rubyfish.cn'
	option host_name 'rubyfish.cn'
	option http_host 'rubyfish.cn'
	option no_check_certificate '1'
```
但是在/var/etc/smartdns/smartdns.conf里面还是和上面一样
`server-https https://118.126.68.223/dns-query  -tls-host-verify rubyfish.cn -no-check-certificate -host-name rubyfish.cn -http-host rubyfish.cn`

**Comment by pymumu** [comment]
可以使用32RC版本看看

**Comment by szl0834** [comment]
> 可以使用32RC版本看看

换用32RC后问题已解决
