### ISSUE TITLE
Resolving Domains with Capital Letters - 查询有大写的域名

### ISSUE THREAD

**Issue by whatrichme** [pymumu/smartdns#570]
这里有用teamviewer 的朋友吗?

一直我在openwrt 上用cloudflare 的DNS (不加密), 然后用了unbound (TLS) 跟 stubby (TLS) 各一个月, 刚换到SmartDNS.
SmartDNS 的速度比 unbound/stubby 好, 运行顺畅, 但换了后发现teamviewer 用不了.

查看了teamviewer的log, 是解析 teamviewer 伺服器失败.
他们的伺服器都这个格式: XX-XXX-XXX-XXXX.teamviewer.com
譬如说:
TW-TPE-ANX-R001.teamviewer.com
TW-TPE-ANX-R002.teamviewer.com

在windows 的环境下, ping 他们的伺服器失败, 但都换成小写就能ping 成功, 之后再ping 大写的就可以. (见附图)

![cmd](https://user-images.githubusercontent.com/68962634/88898139-e8b35300-d27e-11ea-82ff-7b6c773fb071.png)

看了smartDNS 的log, 倒是蛮干净的. 什么都没有.
(作dnsmasq上游 / 转53端口, udp, https, tls 几种模式都试过)

以下是我的配置:

config smartdns
	option seconddns_no_dualstack_selection '0'
	option rr_ttl_min '300'
	option seconddns_no_speed_check '0'
	option port '6053'
	option prefetch_domain '1'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_soa '0'
	option seconddns_tcp_server '1'
	option coredump '0'
	option enabled '1'
	option seconddns_no_cache '0'
	option force_aaaa_soa '0'
	option seconddns_no_rule_ipset '0'
	option dualstack_ip_selection '0'
	option serve_expired '1'
	option ipv6_server '0'
	option tcp_server '1'
	option server_name 'SmartDNS'
	option seconddns_port '6553'
	option redirect 'dnsmasq-upstream'
	list old_redirect 'dnsmasq-upstream'
	list old_port '6053'
	list old_enabled '1'

config server
	option enabled '1'
	option type 'tls'
	option name '1.1.1.1'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option ip '1.1.1.1'

config server
	option enabled '1'
	option type 'tls'
	option name '1.0.0.1'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option ip '1.0.0.1'

各位有什么建议吗?
如何能让SmartDNS 支援有大写的网址, 或者有方法先让 *.teamviewer.com 绕过SmartDNS也可以.
谢谢

**Comment by soffchen** [comment]
SmartDNS 用户表示，正常解析。

```
❯ dig TW-TPE-ANX-R001.teamviewer.com

; <<>> DiG 9.10.6 <<>> TW-TPE-ANX-R001.teamviewer.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62023
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;TW-TPE-ANX-R001.teamviewer.com.	IN	A

;; ANSWER SECTION:
TW-TPE-ANX-R001.teamviewer.com.	300 IN	A	188.172.208.132

;; Query time: 88 msec
;; SERVER: 10.0.0.3#53(10.0.0.3)
;; WHEN: Sat Aug 01 21:58:59 CST 2020
;; MSG SIZE  rcvd: 94
```

**Comment by whatrichme** [comment]
你好, 谢谢你的测试.
刚又抓了几个伺服器测试, 结果是一半半.

澳大利亚, ​​德国, 西班牙, 意大利 都直接成功
![au](https://user-images.githubusercontent.com/68962634/89104900-3e3e5a00-d44f-11ea-92f0-b503b6c5e814.png)
![DE](https://user-images.githubusercontent.com/68962634/89104901-41394a80-d44f-11ea-8403-bd27f1baf511.png)
![ES](https://user-images.githubusercontent.com/68962634/89104904-44343b00-d44f-11ea-80de-06f263e6ec98.png)
![IT](https://user-images.githubusercontent.com/68962634/89104905-46969500-d44f-11ea-9912-b46d20c179d9.png)


越南, 日本, 瑞士, 罗马尼亚 都要换小写才成功.
![VN](https://user-images.githubusercontent.com/68962634/89105206-b73eb100-d451-11ea-8394-ee938ba5725f.png)
![JP](https://user-images.githubusercontent.com/68962634/89104909-4f876680-d44f-11ea-81a9-9c168c932572.png)
![ZRH](https://user-images.githubusercontent.com/68962634/89104914-5a41fb80-d44f-11ea-8dfa-17137624d11a.png)
![RO](https://user-images.githubusercontent.com/68962634/89104916-5dd58280-d44f-11ea-8033-bc9ae4d5b466.png)


伺服器名单在这里有:
https://subdomainfinder.c99.nl/scans/2020-07-31/teamviewer.com
以上只是测试测试, 主要 teamviewer 随机用哪个就哪个, 用家选不了

也发现了, 浏览器都会先换小写再去查询, 所以在浏览器上, 只要是在线的都能解析.
要是在浏览器上去过以上这些网域, 再ping 的话, 是肯定可以的.

相信跟地域也不太有关, 他们也不是受污染的对象
所以呢, 还请各位指点一下

**Comment by huifukejian** [comment]
这应该是dns上油的问题，不是smartdns的问题， 可以试下指定dns解析

**Comment by whatrichme** [comment]
谢谢以上

加了两句, 主要是让TV走 Quad9, 已经成功连上:
nameserver /teamviewer.com/TV
server-tls 9.9.9.9:853 -group TV -exclude-default-group

不过不解的, 是 cloudflare 在openwrt (53), unbound (853) 跟 stubby (853) 都正常.
