### ISSUE TITLE
smartdns并发很多ICMP协议的连接，请问是不是正常的?

### ISSUE THREAD

**Issue by LsnmxNB** [pymumu/smartdns#571]
有时并发到了500个连接数，ICMP连接目的地址又不是DNS啊好奇怪，我关闭smartdns就没这大量ICMP连接了
谢谢！

<img width="1639" alt="Snipaste_2020-07-31_18-01-00" src="https://user-images.githubusercontent.com/42826027/89024763-351e9180-d358-11ea-9ca2-9fee3d825a7b.png">
<img width="1608" alt="Snipaste_2020-07-31_18-03-04" src="https://user-images.githubusercontent.com/42826027/89024769-36e85500-d358-11ea-954d-414cb15b305c.png">

**Comment by pymumu** [comment]
这个是测速使用的ping请求。

**Comment by LsnmxNB** [comment]
@pymumu 谢谢解答，自己谷歌了一下很多相关的知识，请考虑一下smartdns后期加入大陆IP域名用国内DNS解析，国外域名用国外DNS解析，取代路由的DNS功能，弱弱问一下能出个WIN10版本吗，在本地WIN10跑一个很爽

**Comment by pymumu** [comment]
可以wsl运行

**Comment by anafkk** [comment]
@LsnmxNB 国内外分流可以 smartdns 分组 配合 chinadns 使用，不过建议国外域名都走隧道代理，否则解析出来的也是本地路由器的最优CDN节点DNS记录，并不会更快，反而可能会更慢

**Comment by LsnmxNB** [comment]
@LsnmxNB  谢谢在用了，在想WIN怎么运行smartdns

**Comment by LsnmxNB** [comment]
@pymumu 现在有个问题就是使用smartdns后PC上迅雷下载大量并发让smartdns反应不过来

**Comment by BGzErol** [comment]
> @pymumu 现在有个问题就是使用smartdns后PC上迅雷下载大量并发让smartdns反应不过来

国外不要全配置https，也加个tcp上去。我也是和你一样的情况，但加个8.8.8.8的tcp后就正常了
