### ISSUE TITLE
Release 31会在tmp目录下生成大量_MEI开头的临时文件

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#572]
debian 10 x64，smart版本是v31，配置文件如下：
`bind [::]:53
bind-tcp [::]:53

cache-size 10240

prefetch-domain yes

speed-check-mode tcp:80

serve-expired yes
serve-expired-ttl 864000

log-level info
log-size 5M
log-file /tmp/smartdns.log

server-tls 223.5.5.5
server-tls dns.pub
server-https https://223.5.5.5/dns-query
server-https https://dns.pub/dns-query
`

产生大量的临时文件，如下图，红圈里的目录就是，每个大小是25M。
![QQ截图20200803083600](https://user-images.githubusercontent.com/22064544/89136126-ac287580-d564-11ea-9787-75aac8e4b410.jpg)

下图是目录里的内容：
![2](https://user-images.githubusercontent.com/22064544/89136174-ec87f380-d564-11ea-8d97-81c46f9f93e2.jpg)

**Comment by PHCSJC** [comment]
我退回到smartdns 1.2020.02.20-0202了，发现这个版本在tmp下也会生成_MEI开头的目录，但是马上就会被自动删除了。

结论是这个版本没有这个问题！

**Comment by pymumu** [comment]
这个和smartdns无关，排查设备是不是被黑了

**Comment by PHCSJC** [comment]
抱歉，搞错了，是另一个python软件生成的

**Comment by PHCSJC** [comment]
> > 抱歉，搞错了，是另一个python软件生成的，@pymumu 删除这个issue吧！
> 
> 您好, 想问下具体是什么python软件呢? 我也遇到了这个问题

https://github.com/NewFuture/DDNS
这个软件生成的，在那边反馈，作者不承认是ddns生成的，没办法，现在已经不用了。
