### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by alecgao1984** [pymumu/smartdns#574]
**需求应用场景**
新3路由器 Newifi3 Lede Openwrt 
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/smartdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/smartdns-opkg.
root@OpenWrt:~# opkg install luci-app-smartdns.1.2020.08.03-0107.all-luci-compat-all.ipk
Installing luci-app-smartdns (1.2020.08.03-0107) to root...
Configuring luci-app-smartdns.
root@OpenWrt:~# opkg install smartdns.1.2020.08.03-0107.mipsel-openwrt-all.ipk
Installing smartdns (1.2020.08.03-0107) to root...
Configuring smartdns.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/smartdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/smartdns-opkg.
root@OpenWrt:~# 

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  
Newifi3 D2
2. 固件信息

固件版本 | OpenWrt 19.07-SNAPSHOT / LuCI 17.01 Lienol (git-97bc582)
-- | --
内核版本 | 4.14.187

**Comment by pymumu** [comment]
安装成功的，忽略即可，提示是说明使用了旧的配置文件

**Comment by alecgao1984** [comment]
感谢回复
安装成功了
用上最新版本了
感动
