### ISSUE TITLE
如何避免 smartdns 解析国内域名为国外IP？

### ISSUE THREAD

**Issue by moxuanyuan** [pymumu/smartdns#575]
在openwrt上， 我是直接把dnsmasq dns 端口改为别的，然后把smartdns 端口改为53，

把上游DNS服务器分为两组，一组是国内，一组是国外，国外组走代理。

同时国内组设置国内IP段白名单，国外组设置国内IP段黑名单。

配置gfwlist 里面的域名走国外组走解析。

这个配置使用了两天，基问上没什么问题。

但不知为什么有时候把taobao.com解析到国外IP，然后 taobao.com 跳转到 [world.taobao.com](http://world.taobao.com/)

我理解国内组和国外组会同时解析 taobao.com，国内组返回国内ip，国外组返回国外ip，

按道理smartdns测速，国内ip应该快过国外ip，应该返回国个ip才对，为什么有时候会返回国个ip？

```
# 禁用IPV6解析
force-AAAA-SOA yes

# 测速模式选择
speed-check-mode tcp:443,ping

# 缓存大小
cache-size 5048

# 启用过期缓存服务
serve-expired yes

# 开启域名预获取
prefetch-domain yes

# 设置 TTL 最小值和最大值
rr-ttl-min 1800
rr-ttl-max 86400

# 上游服务器 - 国内
# 配置国内IP段白名单
server 119.29.29.29 -whitelist-ip   
server-tls 118.126.68.223 -host-name rubyfish.cn -whitelist-ip
server-https https://223.5.5.5/dns-query -whitelist-ip
server-https https://162.14.21.178/dns-query -host-name dns.pub -whitelist-ip

# 上游服务器 - 国外
# 配置国内IP段黑名单
server-tls 8.8.4.4:853 -host-name dns.google -group foreign -blacklist-ip
server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -group foreign -blacklist-ip

# 上游服务器 - 出国 Server
# 专门用来解析出国服务器 IP
server-tls 115.159.131.230 -host-name dns.rubyfish.cn -group server -exclude-default-group
server-tls 162.14.21.178 -host-name dns.pub -group server -exclude-default-group
# nameserver /example.com/server   

# GFWList
# 指定 GFWList 里面的域名由国外DNS分组解析
# 使用脚本定时更新 https://raw.githubusercontent.com/moxuanyuan/ShellScripts/master/router/Update-smartdns-gfwlist.sh
conf-file /etc/smartdns/gfwlist.conf

# 国内IP段黑白名单
# 使用脚本定时更新 https://raw.githubusercontent.com/moxuanyuan/ShellScripts/master/router/Update-smartdns-chnroute.sh

# Whitelist - Chnroute
conf-file /etc/smartdns/whitelist-chnroute.conf

# Blacklist - Chnroute
conf-file /etc/smartdns/blacklist-chnroute.conf

```

**Comment by anafkk** [comment]
国外组的 DNS 添加 -exclude-default-group 参数，以排除出默认组

**Comment by moxuanyuan** [comment]
> 国外组的 DNS 添加 -exclude-default-group 参数，以排除出默认组

我又想国外组参与解析， 参与解析在GFWList 里面的外国域名

**Comment by anafkk** [comment]
> > 国外组的 DNS 添加 -exclude-default-group 参数，以排除出默认组
> 
> 我又想国外组参与解析， 参与解析不在GFWList 里面的外国域名

用 chinadns 分流，可信 DNS 指向 smartdns 的国外组，没命中 chnlist和ipset的国外域名和IP，都会走国外组解析

**Comment by moxuanyuan** [comment]
> > > 国外组的 DNS 添加 -exclude-default-group 参数，以排除出默认组
> > 
> > 
> > 我又想国外组参与解析， 参与解析不在GFWList 里面的外国域名
> 
> 用 chinadns 分流，可信 DNS 指向 smartdns 的国外组，没命中 chnlist和ipset的国外域名和IP，都会走国外组解析

我的配置中，就是想用smartdns 实现chinadns的功能，只是实际有点了一点点偏差

**Comment by anafkk** [comment]
> > > > 国外组的 DNS 添加 -exclude-default-group 参数，以排除出默认组
> > > 
> > > 
> > > 我又想国外组参与解析， 参与解析不在GFWList 里面的外国域名
> > 
> > 
> > 用 chinadns 分流，可信 DNS 指向 smartdns 的国外组，没命中 chnlist和ipset的国外域名和IP，都会走国外组解析
> 
> 我的配置中，就是想用smartdns 实现chinadns的功能，只是实际有点了一点点偏差

smartdns 只能用 namesevers 等参数指定用于解析的分组，只能穷举，没有 else 的逻辑，不能完全替代

**Comment by ztjal** [comment]
server 223.5.5.5 -group ALIBABA -exclude-default-group

nameserver /taobao.com/ALIBABA
nameserver /tmall.com/ALIBABA

自己常去的网站还是要自己写规则，A系的网站用它自己的DNS，B系也是用它自己的DNS，T系也是一样处理
BAT都有自己的DNS，而且也没必要用加密。

**Comment by huifukejian** [comment]
可以看下我的，日常用起来还可以， 没什么问题

force-AAAA-SOA yes
conf-file /etc/smartdns/smartdns-domains.china.conf
speed-check-mode tcp:443,tcp:80,ping
bind: 6053 -group china
bind: 5335 -group gfwlist 

server-https https://doh.pub/dns-query -group china -exclude-default-group
server-https https://223.5.5.5/dns-query    -group china -exclude-default-group

server-tls 1.0.0.1:853  -group gfwlist 
server-tls 8.8.4.4:853  -group gfwlist 

------------------------------------------------------------------------------
/etc/smartdns/smartdns-domains.china.conf  加载中国域名文件，生成的脚本代码
https://github.com/huifukejian/test/blob/master/update-china-list.sh
弄个定时脚本每天执行一次就可以了

**Comment by moxuanyuan** [comment]
> 可以看下我的，日常用起来还可以， 没什么问题
> 
> force-AAAA-SOA yes
> conf-file /etc/smartdns/smartdns-domains.china.conf
> speed-check-mode tcp:443,tcp:80,ping
> bind: 6053 -group china
> bind: 5335 -group gfwlist
> 
> server-https https://doh.pub/dns-query -group china -exclude-default-group
> server-https https://223.5.5.5/dns-query -group china -exclude-default-group
> 
> server-tls 1.0.0.1:853 -group gfwlist
> server-tls 8.8.4.4:853 -group gfwlist
> 
> /etc/smartdns/smartdns-domains.china.conf 加载中国域名文件，生成的脚本代码
> https://github.com/huifukejian/test/blob/master/update-china-list.sh
> 弄个定时脚本每天执行一次就可以了

你的方法不错，但在家里的k2p上试了，可能是性能太弱了，有点问题，明天回公司的openwrt x86 上试一下

**Comment by huifukejian** [comment]
@moxuanyuan 你的问题是什么？我也是k2p, 常用域名解析都是几十毫毛，国外域名解析速度就看你翻墙的线路了。 我对比过不加载域名文件，速度影响不大， github上应该也有一些小的国内域名列表，可以自己找找，不过域名太少了，就容易出现国内域名解析到国外ip的情况

**Comment by anafkk** [comment]
@huifukejian 你这个还是没解决“不在GFWList 里面的外国域名”走国外解析吧，只是尽可能的遍历国内域名，提高命中率..

**Comment by huifukejian** [comment]
> GFWList

我这个默认解析是使用8.8.4.4和1.0.0.1， 只有在列表里面的域名才用国内dns解析， 已经不需要gfwlist了，一个域名只有3种情况：
1，国内域名在domains.china.conf列表里，直接使用国内dns解析
2，国内域名不在domains.china.conf列表里， 使用国外dns解析，只要你的列表够全，这种情况只有非常偏僻的域名或者一些私密api地址， 普通人几乎遇不到， 遇到了使用8.8.4.4和1.0.0.1 也可以正确解析
3， 国外域名直接使用8.8.4.4和1.0.0.1 解析

**Comment by anafkk** [comment]
@huifukejian 你将 2、3  类域名发送到国外dns解析的分组逻辑在哪儿，smartdns 不指定分组 默认是用主 dns 来解析的

**Comment by huifukejian** [comment]
> @huifukejian 你将 2、3 类域名发送到国外dns解析的分组逻辑在哪儿，smartdns 不指定分组 默认是用主 dns 来解析的

smartdns的解析逻辑是 
主解析端口6053（group default）  一个域名如果匹配到了group就会使用对应group的dns解析 。没有匹配到 group时,  所有不设置-exclude-default-group 的dns都会参与解析, 包括china和gfwlist，哪怕group gfwlist设置了5335端口一样会参与解析
副解析端口5335 （group gfwlist） 向这个端口发送的域名请求，只会使用gfwlist的dns解析。

总结， 6053端口国内和国外的域名都可以解析， 5335端口可以正常解析国外域名，解析国内域名就会返回国外ip。bind: 6053 -group china 这个设置其实在程序运行的时候会修改成bind: 6053 -group default。

**Comment by anafkk** [comment]
@huifukejian 懂了 你是将国内 DNS 反向排除出默认组的方式 实现的”非国内域名统一境外解析“

**Comment by hiddow** [comment]
> > @huifukejian 你将 2、3 类域名发送到国外dns解析的分组逻辑在哪儿，smartdns 不指定分组 默认是用主 dns 来解析的
> 
> smartdns的解析逻辑是
> 主解析端口6053（group default） 一个域名如果匹配到了group就会使用对应group的dns解析 。没有匹配到 group时, 所有不设置-exclude-default-group 的dns都会参与解析, 包括china和gfwlist，哪怕group gfwlist设置了5335端口一样会参与解析
> 副解析端口5335 （group gfwlist） 向这个端口发送的域名请求，只会使用gfwlist的dns解析。
> 
> 总结， 6053端口国内和国外的域名都可以解析， 5335端口可以正常解析国外域名，解析国内域名就会返回国外ip。bind: 6053 -group china 这个设置其实在程序运行的时候会修改成bind: 6053 -group default。

你好，完整版配置方便给参考一下吗？

**Comment by huifukejian** [comment]
> > > @huifukejian 你将 2、3 类域名发送到国外dns解析的分组逻辑在哪儿，smartdns 不指定分组 默认是用主 dns 来解析的
> > 
> > 
> > smartdns的解析逻辑是
> > 主解析端口6053（group default） 一个域名如果匹配到了group就会使用对应group的dns解析 。没有匹配到 group时, 所有不设置-exclude-default-group 的dns都会参与解析, 包括china和gfwlist，哪怕group gfwlist设置了5335端口一样会参与解析
> > 副解析端口5335 （group gfwlist） 向这个端口发送的域名请求，只会使用gfwlist的dns解析。
> > 总结， 6053端口国内和国外的域名都可以解析， 5335端口可以正常解析国外域名，解析国内域名就会返回国外ip。bind: 6053 -group china 这个设置其实在程序运行的时候会修改成bind: 6053 -group default。
> 
> 你好，完整版配置方便给参考一下吗？

你smartdns装在什么系统里面?

**Comment by huifukejian** [comment]
@hiddow   openwrt的设置图片我上传到github里面，文字比较难描述
https://github.com/huifukejian/test/tree/master/smartdns

**Comment by moxuanyuan** [comment]
> @moxuanyuan 你的问题是什么？我也是k2p, 常用域名解析都是几十毫毛，国外域名解析速度就看你翻墙的线路了。 我对比过不加载域名文件，速度影响不大， github上应该也有一些小的国内域名列表，可以自己找找，不过域名太少了，就容易出现国内域名解析到国外ip的情况

加截gfwlist 和 china list 后经常出现 DNS_PROBE_FINISHED_NXDOMAIN，怎样解决？

**Comment by anafkk** [comment]
@huifukejian 你这个配置有个神奇的地方，有保存顺序。。必须最后重新部署下 SSRP 才行，否则 WAN IP 加了国外 DNS IP 后 gfwlist 中的 DNS IP 全都解析不出来

**Comment by anafkk** [comment]
亲测这套单纯依赖 smartdns 的解决方案非常不稳。。不仅有隐藏的保存顺序 还会间歇性失效 导致 gfwlist 中的域名全部解析不到主机，退回 chinadns 分流的方案了，看来有些中间层的专业工具不能省，单一工具全包圆的方案看似美好，实际上各司其职才能效果最大化

**Comment by moxuanyuan** [comment]
> 亲测这套单 smartdns 的解决方案非常不稳。。不仅要生效有隐藏的保存顺序 使用中还会间歇性失效 导致国外组的 DNS IP 无法隧道联通，进而导致 gfwlist 中的域名全部解析不到主机
> 
> 退回 chinadns 作为上游的方案了，分流逻辑简单高效合理，看来有些中间层的专业工具不能省，单一工具全包圆的方案看似美好，实际上各司其职才能效果最大化

我在openwrt x86上使用了10多天，没问题呀

**Comment by anafkk** [comment]
> > 亲测这套单 smartdns 的解决方案非常不稳。。不仅要生效有隐藏的保存顺序 使用中还会间歇性失效 导致国外组的 DNS IP 无法隧道联通，进而导致 gfwlist 中的域名全部解析不到主机
> > 退回 chinadns 作为上游的方案了，分流逻辑简单高效合理，看来有些中间层的专业工具不能省，单一工具全包圆的方案看似美好，实际上各司其职才能效果最大化
> 
> 我在openwrt x86上使用了10多天，没问题呀

你的 K2P 不是一样运行不稳。。我的也是 MT7621 CPU

**Comment by anafkk** [comment]
> > > > 亲测这套单 smartdns 的解决方案非常不稳。。不仅要生效有隐藏的保存顺序 使用中还会间歇性失效 导致国外组的 DNS IP 无法隧道联通，进而导致 gfwlist 中的域名全部解析不到主机
> > > > 退回 chinadns 作为上游的方案了，分流逻辑简单高效合理，看来有些中间层的专业工具不能省，单一工具全包圆的方案看似美好，实际上各司其职才能效果最大化
> > > 
> > > 
> > > 我在openwrt x86上使用了10多天，没问题呀
> > 
> > 
> > 你的 K2P 不是一样运行不稳。。我的也是 MT7621 CPU ，核心频率还超到了 1.14G
> 
> 公司用 openwrt x86，家里用k2p，在公司时间多于在家里，公司是没有什么问题的，但k2p可能真的是CPU和内存不够，还是有小小问题，等有空我也刷N1做旁路试试

并不是性能不够，  chinadns 用同样的 list 转发性能杠杠的，应该是 smartdns 的 namesevers 寻址没那么高效

**Comment by huifukejian** [comment]
@anafkk , 是没有所谓的保存顺序的问题的，因为dns解析是否转发到ss ,是iptables规则决定的， smartdns作为dnsmasq上游后不管你怎么设置都不会涉及到iptables。   偶尔会失效，是smartdns的一个小问题， 默认解析域名超时时间是1s, 如果你的翻墙线路速度不快， 是会出现解析失败的情况。加一个国内无污染的dns可以大大减少这个概率。推荐红鱼DNS，dot doh都支持。

gfw的域名解析关闭测速和跳过nameserver规则后会快一点， 5335只解析gfw域名，不需要nameserver规则。而且ss代理是不支持imcp协议的，所以测速只能得到你本地到访问服务器的ping值，得不到隧道节点到服务器的ping值，推荐关掉。
bind :5335  -no-speed-check -group gfwlist -no-rule-nameserver

 dns解析目前主流的有3种方案， 就是白名单， 黑名单，fakeip 。这些方案都有一些瑕疵。

**Comment by Shankszhu** [comment]
> @anafkk , 是没有所谓的保存顺序的问题的，因为dns解析是否转发到ss ,是iptables规则决定的， smartdns作为dnsmasq上游后不管你怎么设置都不会涉及到iptables。 偶尔会失效，是smartdns的一个小问题， 默认解析域名超时时间是1s, 如果你的翻墙线路速度不快， 是会出现解析失败的情况。加一个国内无污染的dns可以大大减少这个概率。推荐红鱼DNS，dot doh都支持。
> 
> gfw的域名解析关闭测速和跳过nameserver规则后会快一点， 5335只解析gfw域名，不需要nameserver规则。而且ss代理是不支持imcp协议的，所以测速只能得到你本地到访问服务器的ping值，得不到隧道节点到服务器的ping值，推荐关掉。
> bind :5335 -no-speed-check -group gfwlist -no-rule-nameserver
> 
> dns解析目前主流的有3种方案， 就是白名单， 黑名单，fakeip 。这些方案都有一些瑕疵。

大大你好，感谢分享配置，我是东方有线的宽带，运营商dns污染很严重，请问自己添加dns是在server-tls 1.0.0.1:853 -group gfwlist
server-tls 8.8.4.4:853 -group gfwlist 这里后边再加两行对吗？一直没明白gfw的dns污染的逻辑顺序，国内的isp是不是也是gfw的帮凶，另外请教大大现在这套配置每次smartdns reload大概多久需要更新一下那个ip config的列表？

**Comment by Shankszhu** [comment]
另外想请教大大系统日志里显示ssrp connection reset by peer是因为端口转发的问题吗？

Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
Sat Oct 24 00:44:28 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer

**Comment by shatlyktm** [comment]
> server 223.5.5.5 -group ALIBABA -exclude-default-group
> 
> nameserver /taobao.com/ALIBABA
> nameserver /tmall.com/ALIBABA
> 
> 自己常去的网站还是要自己写规则，A系的网站用它自己的DNS，B系也是用它自己的DNS，T系也是一样处理
> BAT都有自己的DNS，而且也没必要用加密。
https://162.14.21.178/dns-query

**Comment by hanzhenlei** [comment]
我遇到的问题就更奇怪了，使用ssrp+adgh+smartdns，无论如何访问国内和国外的网站都会得到一个国外的ip，我看也有朋友passwall+adgh+smartdns出现这个问题。
我的更严重一些，只要打开ssrp或者passwall，只能获得国外的ip，反而从国外查询有时候会获得一个国内的ip，wierd

**Comment by huifukejian** [comment]
> 另外想请教大大系统日志里显示ssrp connection reset by peer是因为端口转发的问题吗？
> 
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:09 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer
> Sat Oct 24 00:44:28 2020 kern.err /usr/bin/ssr-redir[27654]: server recv: Connection reset by peer

Connection reset by peer 日志出现这个是正常的，想要抗dns污染，最稳定的方法就是使用 dns over https,  硬路由简单一点就是使用 clash,  国内dns 填 ali和dnspod的 https dns, 国内填 8.8.8.8和1.1.1.1，翻墙和dns 一个软件搞定， 你找下硬路由 clash的教程吧

**Comment by shatlyktm** [comment]
😉ss://YWVzLTI1Ni1nY206eDIzWjRMR2tHRGtUaFo5S2F6NERVUlFwQDE5My4yOS4xMDcuMTA5OjQwMDkz#TKMVPN88

пн, 30 нояб. 2020 г., 12:25 huifukejian <notifications@github.com>:

**Comment by LsnmxNB** [comment]
解决国内DNS打群架问题
每次一到重要节日国内DNS就开始打架
各自作死
把竞争对手的域名解析到国外
有时还打不开
一起收集完善国内几家喜欢用DNS打架家族的常用域名

server 223.5.5.5 -group AliDNS -exclude-default-group

nameserver /alipay.com/AliDNS
nameserver /aliyun.com.com/AliDNS
nameserver /taobao.com/AliDNS
nameserver /tmall.com/AliDNS
nameserver /xianyuso.com/AliDNS
nameserver /alibabacloud.com/AliDNS

server 119.29.29.29 -group DNSPod -exclude-default-group

nameserver /weixin.com/DNSPod
nameserver /qq.com/DNSPod
nameserver /jd.com/DNSPod
nameserver /qzoneapp.com/DNSPod
nameserver /qqgameapp.com/DNSPod
nameserver /qqopenapp.com/DNSPod
nameserver /pengyou.com/DNSPod
nameserver /tencent.com/DNSPod

server 180.76.76.76 -group Baidu -exclude-default-group

nameserver /baidu.com/Baidu

**Comment by LsnmxNB** [comment]
> 我遇到的问题就更奇怪了，使用ssrp+adgh+smartdns，无论如何访问国内和国外的网站都会得到一个国外的ip，我看也有朋友passwall+adgh+smartdns出现这个问题。
> 我的更严重一些，只要打开ssrp或者passwall，只能获得国外的ip，反而从国外查询有时候会获得一个国内的ip，wierd

看我的回复，一个是国内DNS打架原因一个是国外组可能没加-exclude-default-group原因

**Comment by my5xhni** [comment]
> @hiddow openwrt的设置图片我上传到github里面，文字比较难描述
> https://github.com/huifukejian/test/tree/master/smartdns

大佬，请问你这个配图是 作主路由的时候的设置吗？有没有旁的设置方案呢？
还有就是那个 定时更新远程脚本的代码截图能放一张吗？小白不会写更新代码。

**Comment by z826540272** [comment]
因为你是TCP方式测速,翻墙的情况下TCP测速延迟从来都是1毫秒

**Comment by 1klakla1** [comment]
> 可以看下我的，日常用起来还可以， 没什么问题
> 
> force-AAAA-SOA yes
> conf-file /etc/smartdns/smartdns-domains.china.conf
> speed-check-mode tcp:443,tcp:80,ping
> bind: 6053 -group china
> bind: 5335 -group gfwlist
> 
> server-https https://doh.pub/dns-query -group china -exclude-default-group
> server-https https://223.5.5.5/dns-query -group china -exclude-default-group
> 
> server-tls 1.0.0.1:853 -group gfwlist
> server-tls 8.8.4.4:853 -group gfwlist
> 
> /etc/smartdns/smartdns-domains.china.conf 加载中国域名文件，生成的脚本代码
> https://github.com/huifukejian/test/blob/master/update-china-list.sh
> 弄个定时脚本每天执行一次就可以了

这个方法真的很不错，可以告诉我具体怎么用吗？我把.sh下载下来在路由器上sh 执行这个脚本，会报错

**Comment by realconnor** [comment]
> > > > > 亲测这套单 smartdns 的解决方案非常不稳。。不仅要生效有隐藏的保存顺序 使用中还会间歇性失效 导致国外组的 DNS IP 无法隧道联通，进而导致 gfwlist 中的域名全部解析不到主机
> > > > > 退回 chinadns 作为上游的方案了，分流逻辑简单高效合理，看来有些中间层的专业工具不能省，单一工具全包圆的方案看似美好，实际上各司其职才能效果最大化
> > > > 
> > > > 
> > > > 我在openwrt x86上使用了10多天，没问题呀
> > > 
> > > 
> > > 你的 K2P 不是一样运行不稳。。我的也是 MT7621 CPU ，核心频率还超到了 1.14G
> > 
> > 
> > 公司用 openwrt x86，家里用k2p，在公司时间多于在家里，公司是没有什么问题的，但k2p可能真的是CPU和内存不够，还是有小小问题，等有空我也刷N1做旁路试试
> 
> 并不是性能不够， chinadns 用同样的 list 转发性能杠杠的，应该是 smartdns 的 namesevers 寻址没那么高效

我目前也是用SmartDNS开国内/国外双端口，分别作为ChinaDNS-NG的国内/可信上游服务，用起来还不错，但是有个小瑕疵。即对ChinaDNS-NG的chnlist/gfwlist之外的域名而言（如果列表够全，这种情况其实很少，但是存在这个可能性…），程序会同时向上游的两个端口发起域名请求后再去对比chnroute判断，这时为保证SmartDNS的缓存不被污染，需要给其中一个端口（比如国内组）加上“-no-cache”参数，这样“缓存预取”或“过期缓存”的功力直接废掉一半。而且是为了照顾极少数未匹配到域名列表的情况，感觉很划不来。

好在最新的AdGuardHome也部署了类似unbound和SmartDNS的过期缓存功能（RFC 8767），叫“乐观缓存”，可以继续将ChinaDNS-NG作AdGuardHome的上游，但是这样套娃下来低性能设备直接就爆炸了。所以找到这个issue，还是挺希望 @moxuanyuan 同学能摸索出一个能让SmartDNS独立分流防污染的配置来，不知道现在是个什么情况？目前看下来，当前配置的逻辑似的没啥问题，只有一点：对于未能匹配到nameserver规则的请求，如果它同时返回国内IP和国外IP呢？是靠speed-check来把最后一关了？这样似乎有些邪门…

**Comment by HarlockHomes** [comment]
行了，有这个问题的人都去换软件吧。https://github.com/IrineSistiana/mosdns/wiki

**Comment by pymumu** [comment]
-blacklist-ip -blacklist-ip可以尝试。

**Comment by frankilla1987** [comment]
> @hiddow openwrt的设置图片我上传到github里面，文字比较难描述 https://github.com/huifukejian/test/tree/master/smartdns

大佬，smartdns里像你这样在【自定义设置】里设置了dns，是不是下面那个【上游服务器】就无需再设置dns了？谢谢

**Comment by PikuZheng** [comment]
> 

自定义设置 里可以直接写上游服务器和参数  “上游服务器”可以保持空白。
以前我也是在“上游服务器”里一行一行填 后来发现直接写在自定义配置里 又快又好

**Comment by PikuZheng** [comment]
> 
> 谢谢解答，还有一个问题想再麻烦你一下，不好意思。我的openwrt是作为旁路网关来使用的，不知道这个【旁路网关】是否正确，就是openwrt只负责出海，过滤广告。拨号 DHCP都交给了ikuai。然后我接口里没有wan口，你设置里的那个wan口强制走代理的【1.0.0.1】和【8.8.4.4】这两个DNS我的里面是否要移位呢？不知道我这样说你是否能明白（表达有点差。）谢谢

wan ip是指对端IP，和wan口无关。

**Comment by frankilla1987** [comment]
> > 谢谢解答，还有一个问题想再麻烦你一下，不好意思。我的openwrt是作为旁路网关来使用的，不知道这个【旁路网关】是否正确，就是openwrt只负责出海，过滤广告。拨号 DHCP都交给了ikuai。然后我接口里没有wan口，你设置里的那个wan口强制走代理的【1.0.0.1】和【8.8.4.4】这两个DNS我的里面是否要移位呢？不知道我这样说你是否能明白（表达有点差。）谢谢
> 
> wan ip是指对端IP，和wan口无关。

好的，谢谢明白了！~

**Comment by tufu9441** [comment]
> > GFWList
> 
> 我这个默认解析是使用8.8.4.4和1.0.0.1， 只有在列表里面的域名才用国内dns解析， 已经不需要gfwlist了，一个域名只有3种情况： 1，国内域名在domains.china.conf列表里，直接使用国内dns解析 2，国内域名不在domains.china.conf列表里， 使用国外dns解析，只要你的列表够全，这种情况只有非常偏僻的域名或者一些私密api地址， 普通人几乎遇不到， 遇到了使用8.8.4.4和1.0.0.1 也可以正确解析 3， 国外域名直接使用8.8.4.4和1.0.0.1 解析

按照这个方法配置了，刚开始用，看上去没什么问题，思路很清晰。

**Comment by tufu9441** [comment]
> @hiddow openwrt的设置图片我上传到github里面，文字比较难描述 https://github.com/huifukejian/test/tree/master/smartdns

根据我的理解，按照这套设置的DNS解析逻辑应该大致如下：

前提：在SSR Plus的“访问控制”-“WAN IP访问控制”-“强制走代理的WAN IP”中添加海外DNS的IP地址（若使用DOH还要把对应的https网址填入“强制走代理的域名”中），这样可以使smartdns的上游海外DNS正确走代理隧道进行查询，类似于SSR Plus自带的PDNSD TCP隧道查询。（见https://github.com/coolsnowwolf/lede/issues/2551#issuecomment-568984620 ）

SSR Plus使用绕过中国大陆IP模式（开启GFWlist查询，同时打开国内IP库查询）时，客户端发起域名解析请求>>判断该域名是否在GFWlist中？

- 是，转发到smartdns的5335端口，使用海外DNS服务器进行隧道查询，返回结果是基于节点VPS的位置和IP，并使用隧道访问。

- 否，由Dnsmasq转发到smartdns的6053端口，若域名符合`smartdns-domains.china.conf`列表中的规则，则使用国内DNS查询，返回结果来自于国内DNS，此时会再进行一次SSR Plus国内IP库的匹配：属于国内IP就通过直连访问，不属于国内IP使用隧道访问（当然国内域名解析的结果应该基本都属于国内IP）；若不在上述国内域名列表中，则使用默认DNS（即海外组，因为国内组已经添加了`-exclude-default-group`参数）进行隧道查询并返回结果，同样地，该处也会进行一次国内IP库的查询：返回结果属于国内IP则使用直连访问，不属国内IP使用隧道访问。

以上理解主要总结自https://github.com/coolsnowwolf/lede/issues/2551 中的内容，不知道对不对，还请各位大佬和作者指教。

**Comment by PikuZheng** [comment]
> 前提：在SSR Plus的“访问控制”-“WAN IP访问控制”-“强制走代理的WAN IP”中添加海外DNS的IP地址（若使用DOH还要把对应的https网址填入“强制走代理的域名”中），这样可以使smartdns的上游海外DNS正确走代理隧道进行查询，类似于SSR Plus自带的PDNSD TCP隧道查询。（见[coolsnowwolf/lede#2551 (comment)](https://github.com/coolsnowwolf/lede/issues/2551#issuecomment-568984620) ）

想了半天逻辑上是正确的。
对于原版ss，除了以上设置外，需要额外配置”代理自身“为”正常代理“（我不用ssr+，不确定
如果还有其他问题，建议单独开issue，否则上面所有用户都会收到邮件

**Comment by tufu9441** [comment]
> > @huifukejian 你将 2、3 类域名发送到国外dns解析的分组逻辑在哪儿，smartdns 不指定分组 默认是用主 dns 来解析的
> 
> smartdns的解析逻辑是 主解析端口6053（group default） 一个域名如果匹配到了group就会使用对应group的dns解析 。没有匹配到 group时, 所有不设置-exclude-default-group 的dns都会参与解析, 包括china和gfwlist，哪怕group gfwlist设置了5335端口一样会参与解析 副解析端口5335 （group gfwlist） 向这个端口发送的域名请求，只会使用gfwlist的dns解析。
> 
> 总结， 6053端口国内和国外的域名都可以解析， 5335端口可以正常解析国外域名，解析国内域名就会返回国外ip。bind: 6053 -group china 这个设置其实在程序运行的时候会修改成bind: 6053 -group default。

我又想了一下，既然smartdns内已经配置好了国内域名列表，并且6053端口对国内外的域名都可以解析，其实smartdns就可以只开6053一个端口，然后设法同时作为dnsmasq和ssrplus的上游dns服务器，所有解析请求都交给smartdns来处理，反正除了国内域名默认都会使用海外dns来查询。

**Comment by ixmu** [comment]
> 

请问你解决这个问题了吗？是如何解决的？
版本smartdns 1.2022.36

**Comment by PikuZheng** [comment]
> > 
> 
> 请问你解决这个问题了吗？是如何解决的？ 版本smartdns 1.2022.36

国内域名不使用国外上游dns服务就可以避免解析出国外IP。
如果还有其他问题，建议单独开issue，否则上面所有用户都会收到邮件

**Comment by dragonfivechen** [comment]
指定域名分组解析国内组
手机端:nameserver /m.taobao.com/chain
pc端:nameserver /www.taobao.com/chain

**Comment by wzy105** [comment]
> 可以看下面我的，日常用起来还可以，没有什么问题
> 
> force-AAAA-SOA yes conf-file /etc/smartdns/smartdns-domains.china.conf speed-check-mode tcp:443,tcp:80,ping bind: 6053 -group china bind: 5335 -group gfwlist
> 
> 服务器-https https://doh.pub/dns-query -group china -exclude-default-group 服务器-https https://223.5.5.5/dns-query -group china -exclude-default-group
> 
> 服务器-tls 1.0.0.1:853 -group gfwlist 服务器-tls 8.8.4.4:853 -group gfwlist
> 
> /etc/smartdns/smartdns-domains.china.conf 添加中国域名文件，生成的脚本代码 https://github.com/huifukejian/test/blob/master/update-china-list.sh 弄个定时脚本每天执行一次就可以了

师傅我设置好脚本了，但是不生效。是哪出问题了呢
![屏幕截图 2022-11-27 150936](https://user-images.githubusercontent.com/117211092/204123789-32912cc7-1852-4007-b81f-3bd9ec96f02b.png)
![屏幕截图 2022-11-27 151427](https://user-images.githubusercontent.com/117211092/204123793-5dfc6293-2b15-4fb3-a573-b74abdf5322a.png)
