### ISSUE TITLE
大神能不能更新下库里的luci-app-smartdns和smartdns编译文件 

### ISSUE THREAD

**Issue by shaoyou11** [pymumu/smartdns#576]
大神能不能更新下库里的luci-app-smartdns和smartdns编译文件 
https://github.com/pymumu/luci-app-smartdns 和 https://github.com/pymumu/openwrt-smartdns 单独编译文件 现在还是30版本的
我在https://github.com/pymumu/smartdns 找到的编译文件都是旧的，还是我找错了。编译固件的时候不知道拉取哪个了。

还有没有好心人帮忙回答下

**Comment by huifukejian** [comment]
# 修改smartdns版本， 你可以试下， 注意下Makefile 路径
sed -i 's/PKG_VERSION:=.*/PKG_VERSION:=5.2020.04/g;s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=Release31/g' package/smartdns/Makefile 
我只编译了 smartdns,  luci还是用作者自己编译的。

**Comment by FusionPlmH** [comment]
認同，最好大佬自己更新下裡面的吧

**Comment by RayorRui** [comment]
附议，现有的luci太老了
