### ISSUE TITLE
R6220刷了openwrt以后使用smartdns不能解析

### ISSUE THREAD

**Issue by chainofhonor** [pymumu/smartdns#577]
https://downloads.openwrt.org/releases/19.07.3/targets/ramips/mt7621/
R6220直接从官方固件刷上面的固件r6220-squashfs-factory.img
然后依次安装下面三个文件
libopenssl1.1_1.1.1g-1_mipsel_24kc.ipk
smartdns.1.2020.05.04-0005.mipsel-openwrt-all.ipk
luci-app-smartdns.1.2020.05.04-0005.all-luci-all.ipk

然后打开网页,配置smartdns
勾选enabled
重定向模式选择作为dnsmasq的上游服务器
配置了上游服务器是https://223.5.5.5/dns-query
然后保存并应用

网页上显示服务正常运行
但是客户端解析失败,无法进行dns解析

把iptables改为允许
iptables -I INPUT 1 -j ACCEPT
OUTPUT FORWARD都这样插入
还是不行
查看了dnsmasq的配置,已经配置为转发到127.0.0.1#6053了

实在不知道是什么问题了,最后不得已停用了smartdns服务

谁的路由器刷了openwrt,你们的能正常使用吗?

**Comment by anafkk** [comment]
你用的 release 版本因为更换了编译器，导致 DOT/DOH 有问题，请用最新的 RC 版：https://github.com/pymumu/smartdns/releases/tag/Release32-RC1

**Comment by chainofhonor** [comment]
> 你用的 release 版本因为更换了编译器，导致 DOT/DOH 有问题，请用最新的 RC 版：https://github.com/pymumu/smartdns/releases/tag/Release32-RC1

你好,安装了最新版的 还是不行
查看日志提示
[2020-08-13 11:24:36,827][ERROR][     dns_client.c:1599] connect 2400:3200::1 failed, Permission denied

**Comment by chainofhonor** [comment]
> 你用的 release 版本因为更换了编译器，导致 DOT/DOH 有问题，请用最新的 RC 版：https://github.com/pymumu/smartdns/releases/tag/Release32-RC1

哦 可以了 不能选择代理,要选择重定向53端口到smartdns就行了

**Comment by chainofhonor** [comment]
哎,电信劫持dns,真的恶心
劫持的蓝奏云
然后电信还小心翼翼的只劫持光猫下面的一级客户端
如果你自己接了个路由器,然后路由器下面的设备手动设置DNS的话是不会被劫持的,但是一般用户都是把dns设置为路由器的LAN口地址,这样会让用户误以为是路由器劫持的
这招真的恶心 
前几年电信的10000管家就后台装垃圾推广软件,现在还来这套

**Comment by chainofhonor** [comment]
最后回复一下我的操作:
直接把smartdns的端口改为53 代理模式选择none
把dnsmasq的端口改为5353
可以正常工作

**Comment by ylbkoo** [comment]
> 最后回复一下我的操作:
> 直接把smartdns的端口改为53 代理模式选择none
> 把dnsmasq的端口改为5353
> 可以正常工作

我按照这个方式配置了，会导致苹果设备无法上网，卸载了SmartDns就可以正常了，知道啥原因吗？

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
