### ISSUE TITLE
[NOT RUNNING] [OpenWRT] 编译了正确architecture的ipk以后,正常安装但无法运行

### ISSUE THREAD

**Issue by phantastar** [pymumu/smartdns#578]
### 安装平台
OpenWRT v19.07.3 X86_64原版
### 编译平台
VMWare + Ubuntu 20.04 AMD64服务器版
### 源码Clone时间
2020/8/12 19:30
### 操作步骤
```
1.  cd smartdns/package/luci
2.  sudo sh ./make.sh --arch x86_64
3.  得到luci ipk
4.  去smartdns/package/openwrt目录里重复1/2/3获取ipk
5.  正常安装
```
 6. 无法运行
**没有日志输出, tmp目录也找不到崩溃文件**
### 问题文件
[smartdns.1.2020.08.12-1258.x86_64.zip](https://github.com/pymumu/smartdns/files/5062875/smartdns.1.2020.08.12-1258.x86_64.zip)
[luci-app-smartdns.1.2020.08.12-1302.x86_64.zip](https://github.com/pymumu/smartdns/files/5062876/luci-app-smartdns.1.2020.08.12-1302.x86_64.zip)
### 疑问所在
我怎么也想不通出问题的地方, 烦请您给予解答^

**Comment by MK1909** [comment]
同问

**Comment by pymumu** [comment]
虽然都是x86的，但要交叉编译
服务器系统和openwrt使用的系统库是不同的

也可以使用release中发布的静态编译版本，那个是x86通用

**Comment by phantastar** [comment]
> 虽然都是x86的，但要交叉编译
> 服务器系统和openwrt使用的系统库是不同的
> 
> 也可以使用release中发布的静态编译版本，那个是x86通用

好的😊我一会儿用桌面版Linux(Deepin)再试一下，多谢

**Comment by CyberKoo** [comment]
openwrt用的是musl-libc，最简单的办法是在alpine linux下编译，alpine linux用的也是musl。

**Comment by phantastar** [comment]
> openwrt用的是musl-libc，最简单的办法是在alpine linux下编译，alpine linux用的也是musl。

您的意思是说，通常的桌面版Linux(比如Deepin)编译出来也是无法正常使用对吗?

**Comment by CyberKoo** [comment]
> > openwrt用的是musl-libc，最简单的办法是在alpine linux下编译，alpine linux用的也是musl。
> 
> 您的意思是说，通常的桌面版Linux(比如Deepin)编译出来也是无法正常使用对吗?

可以用musl-gcc wrapper，更多细节看官网 https://www.musl-libc.org/how.html

**Comment by phantastar** [comment]
> > > openwrt用的是musl-libc，最简单的办法是在alpine linux下编译，alpine linux用的也是musl。
> > 
> > 
> > 您的意思是说，通常的桌面版Linux(比如Deepin)编译出来也是无法正常使用对吗?
> 
> 可以用musl-gcc wrapper，更多细节看官网 https://www.musl-libc.org/how.html

谢谢大佬! 我搞一搞

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
