### ISSUE TITLE
增加类似 NGINX reload 的功能

### ISSUE THREAD

**Issue by LisonFan** [pymumu/smartdns#589]
我的 SmartDNS 是跑在 Docker 里的，每次更新配置都需要重启容器，如果能像 NGINX 样增加个 reload 就好了

**Comment by pymumu** [comment]
比较复杂，重启进程代价也没有多少，且很多异常都不用考虑。
可以在容器里面使用systemd服务监控smartdns，这样就比较快恢复了。
