### ISSUE TITLE
这个的作用是从上游DNS服务器池中选择最快的解析是吗

### ISSUE THREAD

**Issue by molichen88** [pymumu/smartdns#59]
看了下解析，没有示例中的那么快，还是20多ms不过看解析的地址。应该是从上游dns服务器中找解析。所以我们自己的上游dns服务器决定了解析的速度是吧。

**Comment by pymumu** [comment]
还有你要确认是生效的。
nslookup -querytype=ptr 0.0.0.0
看看返回结果有没有smartdns字样。

或者看看域名的返回结果是不是都只有一个IP地址。

具体方法看指导吧。

**Comment by molichen88** [comment]
好的
