### ISSUE TITLE
国外访问www.baidu.com解析

### ISSUE THREAD

**Issue by hottom** [pymumu/smartdns#590]
**需求应用场景**
在使用smartDNS最新版本，在国外ping www.baidu.com时，会轮流解析到104.193.88.123 US和103.235.46.40 HK两个IP，但HK的这个地址响应速度快。需要在解析时稳定解析到HK地址上。即使使用国内的DNS，DNS服务器看到是国外IP访问也会轮流解析到上面的两个地址，而不是国内的百度IP。

**建议的方案**
smartDNS在使用公共服务器时，在同时解析的时候选择最快的IP返回，但也希望能直接返回历史记录中最快的服务器IP，并设定这个IP的有效时间。

**设备信息**

**Comment by anafkk** [comment]
你没开缓存么

**Comment by hottom** [comment]
cache-size 512 缺省
