### ISSUE TITLE
几个问题想咨询一下

### ISSUE THREAD

**Issue by ZhxChen** [pymumu/smartdns#593]
1.在openwrt下不装luci，只用命令行如何重启或停止smartdns
使用命令smartdns start或/etc/init.d/smartdns start开启后
无论使用smartdns stop或/etc/init.d/smartdns stop都无法关闭 restart也一样
查看netstat -anup 还是能看到监听的端口号，进程号也没有变

2.openwrt在运行ss情况下，使用tcp测速不准确。tcp测速始终为1ms上下，开代理状态下有什么办法吗？

3.因为问题2，我只开启了icmp测速 speed-check-mode ping。在这个模式下如果一个域名解析结果的IP地址为禁ping的，这时是无法通过icmp测速来优选结果的。那么该程序会如何选择返回的域名？

谢谢解答

**Comment by pymumu** [comment]
/etc/init.d/smartdns start|stop|restart 控制。

这个是openwrt的管理机制。
