### ISSUE TITLE
smartdns可以怎么设置用来查询主机名

### ISSUE THREAD

**Issue by blog2i2j** [pymumu/smartdns#595]
局域网内的机器, 比较多, 想通过主机名来识别, 按照基本步骤设置了smartdns, ping主机名无法找到IP. 想要实现主机名查询IP, 应该怎么设置? 求教了, 谢谢!

**Comment by pymumu** [comment]
需要dhcp的支持。smartdns没有dhcp功能，所有不能支持此功能。

可以的方式是，网络使用静态IP，smartdns配置ip和主机名关系可以。
但维护IP也是比较繁琐的

所以，不建议折腾

**Comment by blog2i2j** [comment]
感谢回复, 最终是加了一个本地后缀,然后把需求转发到dnsmasq解决了
