### ISSUE TITLE
关于f大的openwrt的smartDNS以及刷入失败的问题

### ISSUE THREAD

**Issue by Rockzhangchenhao** [pymumu/smartdns#596]
版本：f大的openwrt 43+o
版本为8.24的release 32 RC4

问题报告：安装Luci时出现的问题
Collected errors:
 * check_data_file_clashes: Package luci-app-smartdns wants to install file /usr/lib/lua/luci/i18n/smartdns.zh-cn.lmo
        But that file is already provided by package  * luci-i18n-smartdns-zh-cn
 * opkg_install_cmd: Cannot install package luci-app-smartdns.

同时，还有一个提问。f大的openwrt的smartDNS貌似存在一瞬间会使所有的节点tcping超时一段时间，简而言之就是断网。。。

**Comment by pymumu** [comment]
release的uci包含的语言包，和标准编译的有冲突。
可以卸载luci-i18n-smartdns-zh-cn后，再安装。

后面问题可以发一下smartdns的log看看。

**Comment by Rockzhangchenhao** [comment]
ok了，只需把语言包删除就没问题了 opkg remove luci-i18n-smartdns-zh-cn 然后再安装就好了
