### ISSUE TITLE
持久化缓存文件未生成

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#597]
大佬好，感谢大佬的杰作
试了下9月8号版本的新功能，持久化缓存，发现未生成缓存文件。
系统是aarch64，smartdns版本是1.2020.09.08-2235，配置如下：
bind [::]:53
bind-tcp [::]:53
cache-size 10240
prefetch-domain yes
speed-check-mode ping
serve-expired yes
serve-expired-reply-ttl 5
serve-expired-ttl 864000
cache-persist yes
cache-file /var/log/smartdns.cache
log-level info
log-size 5M
server-tls dns.pub
server-https https://dns.pub/dns-query
server-https https://223.5.5.5/dns-query

**Comment by pymumu** [comment]
重启服务的时候生成

**Comment by PHCSJC** [comment]
我是直接下载的bin文件，替换旧版本后，Kill后重新启动的进程，没有生成cache文件，什么问题呢？

**Comment by pymumu** [comment]
要用正常启停
比如重新拨号，重启设备，不能kill

**Comment by PHCSJC** [comment]
还是不太理解，我就是在Linux系统上使用的，没有拨号，直接配置的静态ip，这种怎么办呢？

**Comment by PHCSJC** [comment]
touch一个，貌似理解了一点，这个功能是在smartdns进程在关闭的时候把缓存写到这个cache文件里的，下次再启动会先读取这个文件。
是这样吗？

**Comment by pymumu** [comment]
对，再服务器正常停止的时候，才会写缓存文件，下次启动时使用。运行时是不会写的。

主要是解决路由等设备，断网重拨后，smartdns重启，导致的缓存清空的问题。

**Comment by yyysuo** [comment]
> 对，再服务器正常停止的时候，才会写缓存文件，下次启动时使用。运行时是不会写的。
> 
> 主要是解决路由等设备，断网重拨后，smartdns重启，导致的缓存清空的问题。

我看默认的路径是/tmp下面，那么系统重启的时候是自动copy到另外的地方重启后再copy回来么？这个选项是不是对过期缓存功能最有意义呢。

**Comment by PHCSJC** [comment]
今天还发现一个问题，我的gfwlist列表新加了一个域名，没有生效，就是解析不会写到ipset里，退回上个版本好了。

**Comment by pymumu** [comment]
33和32变化不大，发一下对比日志看看
