### ISSUE TITLE
老大你的smartdns能在Android上运行吗？想在Android上玩玩

### ISSUE THREAD

**Issue by zhouhm** [pymumu/smartdns#598]
Linux(Debian Fedora)上都玩过了，一点问题没有
OpenWrt上也都玩过了，mips架构，arm架构都玩过了，也一点问题没有，想玩Android平台了^_^ ^_^

**Comment by pymumu** [comment]
有人做过，github上搜搜看

**Comment by zhouhm** [comment]
找到一个
https://github.com/x4455/smartdns-Android

还是5个月以前更新的呢，看来要想新还得自己编译了，还得继续编译

**Comment by x4455** [comment]
> 找到一个
> https://github.com/x4455/smartdns-Android
> 
> 还是5个月以前更新的呢，看来要想新还得自己编译了，还得继续编译

因为学业问题没怎么更新，你可以试着直接替换二进制文件进行升级（
而最近的版本也遇到了一些问题(路径权限什么的)，可能要重写一部分。
更新会有的但速度不保证。

**Comment by zhouhm** [comment]
朋友能不能跟你学一学啊，付费学^_^ ^_^ 对Android一点不熟悉啊。研究两天了，还没入门

**Comment by masx200** [comment]
可以不root在zerotermux里面运行smartdns吗？然后浏览器可以设定本地doh，安卓设置本地dot，然后安装自签名证书是不是就可以了

**Comment by PikuZheng** [comment]
> 可以不root在zerotermux里面运行smartdns吗？然后浏览器可以设定本地doh，安卓设置本地dot，然后安装自签名证书是不是就可以了

建议考虑使用rust重写的smartdns
