### ISSUE TITLE
昨晚崩溃

### ISSUE THREAD

**Issue by cjameslynn** [pymumu/smartdns#60]
[smartdns.1547252346.10656.11.zip](https://github.com/pymumu/smartdns/files/2751671/smartdns.1547252346.10656.11.zip)
[log.zip](https://github.com/pymumu/smartdns/files/2751698/log.zip)
**运行环境**
1. LEDE_X64 

2. 电信ipv4+ipv6，移动ipv4  

**重现步骤**
1. 昨晚游戏玩一半就登不上服务器，早上排查原因，smartdns挂了。

**Comment by pymumu** [comment]
并没有看到进程异常退出，进程还在运行。

从日志看看不出什么问题。至少能确认进程还在运行。
8点的时候，还在处理请求。

用nslookup -querytype=ptr 0.0.0.0命令
或dig -t ptr 0.0.0.0看看有没什么输出吧。

**Comment by cjameslynn** [comment]
界面上看是未运行，需要关闭，应用，再打开，再应用

**Comment by cjameslynn** [comment]
不过我早上更新了你的beta18正式版，之前还是RC版。

**Comment by pymumu** [comment]
嗯，换下试试吧
