### ISSUE TITLE
Openwrt系统下，如运行多个smartdns进程，并且第二个进程启用了审计日志的话，不会根据配置文件内指定的路径生成审计日志

### ISSUE THREAD

**Issue by fox85** [pymumu/smartdns#600]
Openwrt系统下，如运行多一个smartdns实例，并且第二个实例也启用了审计日志的话，第二个实例不会根据配置文件内指定的路径生成审计日志

第二个实例是以这样的命令跑起来的
/usr/sbin/smartdns -p /tmp/smartdns-2.txt -c /etc/smartdns/smartdns-2.conf

然后配置文件的内容是这样的
log-size 128K
log-num 2
log-level info
log-file /var/log/smartdns-2.log
audit-enable yes
audit-size 128K
audit-num 2
audit-file /var/log/smartdns-audit-2.log

经过运行后的观察，以上路径内没有生成审计日志smartdns-audit-2.log，倒是第一个实例则有生成审计日志。
而smartdns-2.log则有生成，但是里面记录的时间不对，与现实时间刚好是有-8个小时的差距。
但第一个实例记录的log-file日志上的时间则正确。

请大佬帮忙看看，谢谢

**Comment by pymumu** [comment]
看看有没有请求，时差的问题是时区导致的，要导出TZ环境变量指定时区。

**Comment by fox85** [comment]
> 看看有没有请求，时差的问题是时区导致的，要导出TZ环境变量指定时区。

有请求的，是用dig发送请求的。就是多开实例的情况下，从第二个运行中的实例开始就没有审计日志生成，第一个运行中的实例就有审计日志生成

时差问题的话，第一个实例的日志记录时间是正确的，但就是从第二个实例开始的日志所记录的时间都会偏差-8个小时
