### ISSUE TITLE
smartdns的启动顺序是否应该更靠前？

### ISSUE THREAD

**Issue by HiGarfield** [pymumu/smartdns#603]
https://github.com/pymumu/smartdns/blob/baa1397fb0d748055d56042739f19aff3f69c4fe/package/openwrt/files/etc/init.d/smartdns#L18

目前smartdns的启动顺序是99。本人遇到udp2raw启动顺序是98，udp2raw启动过程中需要做域名解析，smartdns的启动导致udp2raw启动过程中域名解析失败（smartdns作为dnsmasq上游的工作模式），最终udp2raw无法正常启动。通过调小smartdns的启动顺序，使得smartdns启动之后再启动udp2raw，那么一切正常。

目前我不是很确定smartdns最早可以提早哪一个顺序启动，但目前可以确定的是，smartdns尽早启动，能避免其他的init脚本包含域名解析的服务启动失败。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue

**Comment by HiGarfield** [comment]
> 最新版本验证，有问题reopen issue

最新版本没问题。感谢！
