### ISSUE TITLE
openwrt编译后无法保存设置，保存表单时出错:  错误的数据回复格式

### ISSUE THREAD

**Issue by kbnq** [pymumu/smartdns#606]
编译的时候加入了smartdns，安装固件之后无法保存设置。
![微信截图_20200917180807](https://user-images.githubusercontent.com/22976092/93456807-c51c9880-f910-11ea-838e-95db53fa0d45.png)

**Comment by RoninYuan-WY** [comment]
补充环境，应该是用dev-master编译后有这个问题。op19没有这个问题

**Comment by pymumu** [comment]
用最新版本。
