### ISSUE TITLE
进程进程会出现不运行的情况

### ISSUE THREAD

**Issue by asnon** [pymumu/smartdns#61]
**问题现象**  
每天都会固定重启一次。。而且不定时。。不知是不是和软件中心哪个软件冲突还是怎样？装了v2ray，

**运行环境**
1、Openwrt Koolshare mod V2.26 r9789-f4b7c27ab5

**重现步骤**
1. 上游DNS配置。 
![image](https://user-images.githubusercontent.com/34601728/51084907-ce815500-176c-11e9-85db-735ff5ad53e5.png)
![image](https://user-images.githubusercontent.com/34601728/51084909-db9e4400-176c-11e9-8a90-a47733605d61.png)
![image](https://user-images.githubusercontent.com/34601728/51084969-9cbcbe00-176d-11e9-8158-5c3942250458.png)

2. 只要出现不能访问网络的情况，一看就是smart dns进程未运行

**信息收集**  
1. 将/var/log/smrtdns.log日志
[2019-01-13 14:41:40,657][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 14:41:40,657][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 15:04:14,708][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 15:04:14,708][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 15:04:15,214][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 15:04:15,214][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 15:45:56,148][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 15:45:56,148][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 16:26:44,807][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 16:26:44,807][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 16:46:28,269][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 16:46:28,269][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 16:46:28,546][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 16:46:28,546][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 17:51:13,615][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 17:51:13,615][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 18:52:11,187][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 18:52:11,187][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 18:52:11,573][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 18:52:11,573][ERROR][     dns_server.c:1883] dns server process failed.
[2019-01-13 19:52:40,108][ERROR][     dns_server.c:1294] decode failed.
[2019-01-13 19:52:40,108][ERROR][     dns_server.c:1883] dns server process failed.

2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
[smartdns.1547129275.1543.11.zip](https://github.com/pymumu/smartdns/files/2753037/smartdns.1547129275.1543.11.zip)

**Comment by pymumu** [comment]
你用的是release 18的稳定版本吗？

**Comment by pymumu** [comment]
release 18进程异常退出应该会自动重启的。
你的进程没有自动重启吗？界面看到进程是not running么？

**Comment by asnon** [comment]
> release 18进程异常退出应该会自动重启的。
> 你的进程没有自动重启吗？界面看到进程是not running么？
> 
> 执行以下这个命令，看看RESPAWN设置的是多少。
> cat /etc/init.d/smartdns | grep ^RESPAWN

![image](https://user-images.githubusercontent.com/34601728/51096293-5a8b8f00-17f6-11e9-928f-a6ea2a0d8b0c.png)

**Comment by asnon** [comment]
> 你kill进程看看会不会自动重启

![image](https://user-images.githubusercontent.com/34601728/51096700-75abce00-17f9-11e9-8b6e-bd063b8e5c1a.png)
关闭这个进程会自动重启

**Comment by pymumu** [comment]
把你的配置发一下吧，晚上回去看看能否复现
配置文件/var/etc/smartdns/smartdns.conf

**Comment by asnon** [comment]
> 把你的配置发一下吧，晚上回去看看能否复现
> 配置文件/var/etc/smartdns/smartdns.conf


[smartdns.zip](https://github.com/pymumu/smartdns/files/2754063/smartdns.zip)

**Comment by asnon** [comment]
> 你的客户端有些什么设备。

好多，我试试看看，客户端都是电视，手机，电脑，没有NAS之类的，KP过滤的插件也是只过滤电视ip，其他都没用。

**Comment by asnon** [comment]
> 我编译了一个debug版本，麻烦用这个版本，获取一下coredump。
> 
> [smartdns_build.zip](https://github.com/pymumu/smartdns/files/2760551/smartdns_build.zip)
> 
> 大概看了一下，是从客户端收到了请求后挂掉。
> 
> 你的客户端有些什么设备。

这两天观察了下没有重启的情况了。。最近观察了下，一用百度DNS就容易出问题。。后面删了后就没问题了。。但是用百度DNS ping值又低。。真是尴尬了。。后面用14.215.177.39这个也还可以

**Comment by pymumu** [comment]
重启应该会自动拉起来的。

/tmp下面看看有没有新生成coredump文件

百度DNS会不定期返回错误格式的DNS数据包。会导致smartdns有异常打印，其他应该没什么影响。
当然，异常数据包格式可能触发包解析的BUG。

**Comment by asnon** [comment]
> 重启应该会自动拉起来的。
> 
> /tmp下面看看有没有新生成coredump文件
> 
> 百度DNS会不定期返回错误格式的DNS数据包。会导致smartdns有异常打印，其他应该没什么影响。
> 当然，异常数据包格式可能触发包解析的BUG。

刚看了下没有生产coredump文件呢，估计是稳定了，百度这个DNS应该冲突不少。。会有些bug。。

**Comment by pymumu** [comment]
代码没改过，那就这样用吧。

等后面在出现了再说。

**Comment by asnon** [comment]
> 代码没改过，那就这样用吧。
> 
> 等后面在出现了再说。

嗯嗯，辛苦啦，谢谢。

**Comment by kangmya** [comment]
@asnon @pymumu 找到这个问题的原因了  V2RAY自带有集成的smartdns    而V2RAY同时也自带连接诊断  一旦发现V2连接出问题断开   便会重启V2进程    在重启V2进程的过程中 他会同时重启所有和V2有关的软件   包括他集成的SMARTDNS     但他并不会判断当前运行的SMARTDNS是他集成的  还是用户单独安装的，  反正就是直接干死就对了   所以大家的SMARTDNS进程就会莫名其妙的消失   而且也不会生成coredump文件
解决方法就是使用SS   要么就是关闭V2的链接诊断
我刚刚手动杀死V2的进程实验了两次  观察了路由进程   发现应该就是这个原因

**Comment by kangmya** [comment]
这个问题需要跟kool论坛沟通一下   或者干脆在KOOL的软件商店也上架一个SMARTDNS，这样用户使用也方便    kool也不用再额外集成了
v2里面集成的smartdns配置文件没有WEB界面，玩不转

**Comment by asnon** [comment]
> @asnon @pymumu 找到这个问题的原因了 V2RAY自带有集成的smartdns 而V2RAY同时也自带连接诊断 一旦发现V2连接出问题断开 便会重启V2进程 在重启V2进程的过程中 他会同时重启所有和V2有关的软件 包括他集成的SMARTDNS 但他并不会判断当前运行的SMARTDNS是他集成的 还是用户单独安装的， 反正就是直接干死就对了 所以大家的SMARTDNS进程就会莫名其妙的消失 而且也不会生成coredump文件
> 解决方法就是使用SS 要么就是关闭V2的链接诊断
> 我刚刚手动杀死V2的进程实验了两次 观察了路由进程 发现应该就是这个原因

这个问题我之前遇到过，但是我v2那边是设置的路由器ip，没有用smart dns。。暂时这边没有问题了。。不知道v2集成的smartdns是不是和这个一样的模式。。

**Comment by asnon** [comment]
> server-name smartdns
> bind [::]:7923
> bind-tcp [::]:7923
> cache-size 10240
> log-size 128K
> log-num 3
> log-level error
> server 223.5.5.5:53
> server 223.6.6.6:53
> server 119.29.29.29:53
> server 114.114.114.114:53
> server 180.76.76.76:53
> server 101.226.4.6:53
> server 199.91.73.222:53
> server 9.9.9.9:53
> server-tcp 8.8.8.8:53
> server 117.50.11.11:53
> 
> V2RAY集成的SMARTDNS配置文件
> 不过不知道是版本17还是18，为了避免麻烦，暂时先用V2+配合集成的SMARTDNS版本了

而且v2里面的smart dns不是不能自定义。。这个估计后续会加入吧。。最好的一个方案是看能否集成到kool软件中心里，那后续更新都会非常方便，而且无名bug也会少很多，不过这需要大神之间沟通啦。。现在用这个插件这几天也没出现问题了。。

**Comment by kangmya** [comment]
> > server-name smartdns
> > bind [::]:7923
> > bind-tcp [::]:7923
> > cache-size 10240
> > log-size 128K
> > log-num 3
> > log-level error
> > server 223.5.5.5:53
> > server 223.6.6.6:53
> > server 119.29.29.29:53
> > server 114.114.114.114:53
> > server 180.76.76.76:53
> > server 101.226.4.6:53
> > server 199.91.73.222:53
> > server 9.9.9.9:53
> > server-tcp 8.8.8.8:53
> > server 117.50.11.11:53
> > V2RAY集成的SMARTDNS配置文件
> > 不过不知道是版本17还是18，为了避免麻烦，暂时先用V2+配合集成的SMARTDNS版本了
> 
> 而且v2里面的smart dns不是不能自定义。。这个估计后续会加入吧。。最好的一个方案是看能否集成到kool软件中心里，那后续更新都会非常方便，而且无名bug也会少很多，不过这需要大神之间沟通啦。。现在用这个插件这几天也没出现问题了。。

嗯  可以自定义 但是只能通过直接修改配置文件来更改  比较麻烦  没有WEB来的直接
后续看@pymumu要是可以直接集成到软件就更加方便了，把WEB控制入口从服务选项下直接挪到酷软中心下面，现在玩软路由的越来越多了，用户基础也不少

**Comment by pymumu** [comment]
提供软件中心插件的需求，后面有机会搞一下。
现在我联系一下v2ray插件的作者看看问题出现在哪里。

**Comment by kangmya** [comment]
@pymumu 大佬辛苦了

**Comment by asnon** [comment]
今天中午突然出现错误。。已经稳定运行快一星期了。。
[新建压缩文件.zip](https://github.com/pymumu/smartdns/files/2847735/default.zip)

**Comment by pymumu** [comment]
获取一下Release 20测试下吧。这个版本主要解决问题。
