### ISSUE TITLE
CentOS 6 无法编译通过

### ISSUE THREAD

**Issue by purplegrape** [pymumu/smartdns#610]
**问题现象**  
CentOS 6 无法编译通过

**运行环境**
CentOS 6 
openssl 1.0.1e-58.el6_10

**重现步骤**
+ make -j8
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"smartdns.c\"   -c -o smartdns.o smartdns.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"fast_ping.c\"   -c -o fast_ping.o fast_ping.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"dns_client.c\"   -c -o dns_client.o dns_client.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"dns_server.c\"   -c -o dns_server.o dns_server.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"dns.c\"   -c -o dns.o dns.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"util.c\"   -c -o util.o util.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"tlog.c\"   -c -o tlog.o tlog.c
cc -O2 -g -Wall -Wstrict-prototypes -fno-omit-frame-pointer -Wstrict-aliasing  -Iinclude -DBASE_FILE_NAME=\"dns_conf.c\"   -c -o dns_conf.o dns_conf.c
dns_conf.c: In function '_conf_domain_rule_address':
dns_client.c: In function '_dns_client_socket_ssl_send':
dns_client.c:1886: error: 'SSL_R_SHUTDOWN_WHILE_IN_INIT' undeclared (first use in this function)
dns_client.c:1886: error: (Each undeclared identifier is reported only once
dns_client.c:1886: error: for each function it appears in.)
dns_client.c: In function '_dns_client_socket_ssl_recv':
dns_client.c:1946: error: 'SSL_R_SHUTDOWN_WHILE_IN_INIT' undeclared (first use in this function)
dns_conf.c:721: warning: dereferencing pointer 'addr_in6' does break strict-aliasing rules
dns_conf.c:721: warning: dereferencing pointer 'addr_in6' does break strict-aliasing rules
dns_conf.c:721: warning: dereferencing pointer 'addr_in6' does break strict-aliasing rules
dns_conf.c:720: note: initialized from here
make: *** [dns_client.o] Error 1
make: *** Waiting for unfinished jobs....

**信息收集**  
请问smartdns是否对gcc 或openssl 版本有要求？

**Comment by pymumu** [comment]
1.0.2之后的openssl应该都可以使用。
你可以删掉SSL_R_SHUTDOWN_WHILE_IN_INIT。

**Comment by purplegrape** [comment]
many thanks. close  the issue and will update the rpm spec file
