### ISSUE TITLE
BUG: SmartDNS would stop working when PPPoE restarts

### ISSUE THREAD

**Issue by purerosefallen** [pymumu/smartdns#611]
**问题现象**  
Our company has 2 internet lines, `ppp0` and `ppp1`, the route table of which are as follows.

```
default dev ppp0 scope link metric 100 
default dev ppp1 scope link metric 101
```

Due to the policy of China Telecom, the `ppp0` would restart every 2875 minutes. For high availability, our outbound internet traffic would be switched to `ppp1` during the period of `ppp0` redialing.
However, after the redial, SmartDNS would run super slow or stop working. I always have to restart SmartDNS when this happens.

**运行环境**
1. 固件型号  

On a Debian Buster VM running on VMware ESXi. (Not on gateway)

```
Linux utility 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

2. 运营商  

`ppp0` is China Telecom, and `ppp1` is GWBN.

**重现步骤**

1. 上游DNS配置。  

```
bind-tcp [::]:53
bind [::]:53

tcp-idle-time 3
cache-size 4096
cache-persist yes
cache-file /tmp/smartdns-cache/cache
prefetch-domain yes

serve-expired yes
serve-expired-ttl 0

speed-check-mode tcp:80,tcp:443,ping
rr-ttl-min 1
rr-ttl-max 86400

log-level warn

force-AAAA-SOA yes

#server-https https://cloudflare-dns.com/dns-query -group tls

# TLS DNSes
server-tls 8.8.8.8 -group tls
server-tls 1.0.0.1 -group tls
server-tls 9.9.9.9 -group tls

# China DNSes
server 202.96.134.33 -group china -exclude-default-group
server 202.96.134.133 -group china -exclude-default-group

# domains owned by MyCard
nameserver /mycard.moe/china
nameserver /momobako.com/china
nameserver /yuzurisa.com/china
nameserver /moecube.com/china
nameserver /moestart.com/china
nameserver /moenext.com/china
nameserver /ygobbs.com/china
nameserver /newwise.com/china
nameserver /my-card.in/china
nameserver /mius.pro/china

# china list
conf-file /etc/smartdns/china-list.conf
```

2. 访问的域名。 

This happens on almost every domains. `baidu.com` and `google.com` are tested for both common DNS and TLS DNS.

**Comment by pymumu** [comment]
please upload log file, /var/log/smartdns.log

**Comment by purerosefallen** [comment]
I checked the log file, but nothing came out.

**Comment by pymumu** [comment]
set log level to debug
```
log-level debug
```

**Comment by LEXUGE** [comment]
Might be related to #615?

**Comment by purerosefallen** [comment]
In fact the same thing

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
