### ISSUE TITLE
只配置DoH域名不能解析

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#613]
下面这样是可以解析的：
server-tls dns.pub
server-https https://dns.pub/dns-query
server-https https://223.5.5.5/dns-query

下面这样是不能解析的：
server-tls dns.pub
server-https https://dns.pub/dns-query
会提示下面的错误：
[2020-09-25 21:37:51,145][ERROR][     dns_server.c:2770] do query dns.pub failed.
[2020-09-25 21:37:51,145][ERROR][     dns_client.c:2692] Send query to upstream server failed.
[2020-09-25 21:37:51,145][ERROR][     dns_server.c:2634] send dns request failed.
[2020-09-25 21:37:51,145][ERROR][     dns_server.c:2770] do query dns.pub failed.

猜测应该是提供服务前需要先把dns.pub的域名解析出来，所以配置233.5.5.5的可以通过这个DNS先解析。

那请教下，不想配置233这个DNS，因为阿里的DNS不好用，那怎么实现第一次解析呢？可以再加一个server 119.29.29.29这样的DNS，但这样加上去之后这个DNS也开始提供服务了，DNS的解析又不安全了，咋办呢？

**Comment by PHCSJC** [comment]
理想的情况可能是这样的，专门设置一个DNS用于DoT, DoH的域名解析，smartdns启动后，会先用这个DNS去解析出DoT, DoH的域名，然后这个DNS就不再使用了。

**Comment by PHCSJC** [comment]
目前找到一个临时的方案：
server 114.114.114.114 -group dohdns -exclude-default-group
server 119.29.29.29 -group dohdns -exclude-default-group
domain-rules /dns.pub/ -speed-check-mode none -nameserver dohdns
domain-rules /doh.pub/ -speed-check-mode none -nameserver dohdns

缺点是进程启动后，要等几秒才可以正常提供解析。

**Comment by fangjia052** [comment]
server 119.29.29.29 -group jx -exclude-default-group
server-tls dns.pub -group home -exclude-default-group
server-https https://dns.pub/dns-query -group home -exclude-default-group
nameserver /dns.pub/jx
可以这样设置

**Comment by fangjia052** [comment]
> 下面这样是可以解析的：
> server-tls dns.pub
> server-https https://dns.pub/dns-query
> server-https https://223.5.5.5/dns-query
> 
> 下面这样是不能解析的：
> server-tls dns.pub
> server-https https://dns.pub/dns-query
> 会提示下面的错误：
> [2020-09-25 21:37:51,145][ERROR][ dns_server.c:2770] do query dns.pub failed.
> [2020-09-25 21:37:51,145][ERROR][ dns_client.c:2692] Send query to upstream server failed.
> [2020-09-25 21:37:51,145][ERROR][ dns_server.c:2634] send dns request failed.
> [2020-09-25 21:37:51,145][ERROR][ dns_server.c:2770] do query dns.pub failed.
> 
> 猜测应该是提供服务前需要先把dns.pub的域名解析出来，所以配置233.5.5.5的可以通过这个DNS先解析。
> 
> 那请教下，不想配置233这个DNS，因为阿里的DNS不好用，那怎么实现第一次解析呢？可以再加一个server 119.29.29.29这样的DNS，但这样加上去之后这个DNS也开始提供服务了，DNS的解析又不安全了，咋办呢？

server 119.29.29.29 -group jx -exclude-default-group
server-tls dns.pub -group home -exclude-default-group
server-https https://dns.pub/dns-query -group home -exclude-default-group
nameserver /dns.pub/jx
可以这样设置

**Comment by Alion548** [comment]
遇到相同情况，从日志中可以看到有IP返回，不过dig还是超时了

``` shell
[root@localhost smartdns]# dig www.moerats.com @127.0.0.1 -p 11953

; <<>> DiG 9.11.22-RedHat-9.11.22-1.fc32 <<>> www.moerats.com @127.0.0.1 -p 11953
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```shell
bind [::]:11953 -group chinaDoH -no-rule-addr -no-rule-nameserver -no-speed-check -no-cache

cache-size 4096
prefetch-domain yes
speed-check-mode none
force-AAAA-SOA yes
cache-persist yes
cache-file /usr/local/etc/smartdns/smartdns.cache
ca-file /usr/local/etc/cert/cacert.pem

server-https https://223.5.5.5/dns-query -hostname 'dns.alidns.com' -group chinaDoH -exclude-default-group
server-https https://162.14.21.56/dns-query -hostname 'doh.pub' -group chinaDoH -exclude-default-group
```

```log
[-:48,461][ INFO][     dns_server.c:2708] query server www.moerats.com from 127.0.0.1, qtype = 1
[-:48,461][DEBUG][     dns_client.c:468 ] send query to group chinaDoH
[-:48,461][ INFO][     dns_client.c:2899] send request www.moerats.com, qtype 1, id 234
[-:48,471][DEBUG][     dns_client.c:2447] tls server 127.0.0.1 connected.
[-:48,471][DEBUG][     dns_client.c:2452] new session
[-:48,471][DEBUG][     dns_client.c:2322] peer CN: cloudflare-dns.com
[-:48,471][DEBUG][     dns_client.c:2373] cert SPKI pin(sha256): 57:AC:DE:B3:C8:47:05:5C:14:10:2B:07:7F:BB:95:E7:11:8C:ED:D8:F7:B8:C5:C8:4B:DF:FF:EE:A0:BC:FA:35
[-:48,547][DEBUG][     dns_client.c:2069] recv tcp packet from 127.0.0.1, len = 470
[-:48,547][DEBUG][            dns.c:1546] opt type 12
[-:48,547][DEBUG][            dns.c:1564] DNS opt type = 12 not supported
[-:48,547][DEBUG][     dns_client.c:1481] qdcount = 1, ancount = 4, nscount = 0, nrcount = 0, len = 468, id = 232, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 1232
[-:48,547][DEBUG][     dns_client.c:1492] domain: client.wns.windows.com qtype: 1  qclass: 1
[-:48,547][DEBUG][     dns_server.c:1642] domain: sg2p.wns.notify.windows.com.akadns.net TTL:290 IP: 52.139.250.253
[-:48,547][DEBUG][     dns_client.c:2069] recv tcp packet from 127.0.0.1, len = 470
[-:48,547][DEBUG][            dns.c:1546] opt type 12
[-:48,547][DEBUG][            dns.c:1564] DNS opt type = 12 not supported
[-:48,547][DEBUG][     dns_client.c:1481] qdcount = 1, ancount = 4, nscount = 0, nrcount = 0, len = 468, id = 233, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 1232
[-:48,547][DEBUG][     dns_client.c:1492] domain: client.wns.windows.com qtype: 1  qclass: 1
[-:48,547][DEBUG][     dns_server.c:1642] domain: sg2p.wns.notify.windows.com.akadns.net TTL:290 IP: 52.139.250.253
[-:48,649][DEBUG][     dns_client.c:2069] recv tcp packet from 223.5.5.5, len = 257
[-:48,649][DEBUG][     dns_client.c:1481] qdcount = 1, ancount = 1, nscount = 0, nrcount = 0, len = 75, id = 234, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 2048
[-:48,649][DEBUG][     dns_client.c:1492] domain: www.moerats.com qtype: 1  qclass: 1
[-:48,649][DEBUG][     dns_server.c:1642] domain: www.moerats.com TTL:300 IP: 172.83.156.172
[-:48,674][DEBUG][     dns_client.c:2069] recv tcp packet from 162.14.21.56, len = 483
[-:48,674][DEBUG][            dns.c:1546] opt type 8
[-:48,674][DEBUG][            dns.c:1373] ECS: family:1, source_prefix:32, scope_prefix:0, len:4
[-:48,674][DEBUG][            dns.c:1375] 59.35.57.210
[-:48,674][DEBUG][     dns_client.c:1481] qdcount = 1, ancount = 1, nscount = 0, nrcount = 0, len = 87, id = 234, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 4096
[-:48,674][DEBUG][     dns_client.c:1492] domain: www.moerats.com qtype: 1  qclass: 1
[-:48,674][DEBUG][     dns_server.c:1642] domain: www.moerats.com TTL:300 IP: 172.83.156.172
```

**Comment by felix-fly** [comment]
可以先指定ip再用其解析，比如
`address /dns.alidns.com/223.5.5.5`
`server-https https://dns.alidns.com/dns-query?`

**Comment by snowyu** [comment]
try `-host-name` option: `server-https https://233.555./dns-query -host-name  dns.alidns.com`
