### ISSUE TITLE
屏蔽 type65 返回里面的 AAAA 记录

### ISSUE THREAD

**Issue by ghost** [pymumu/smartdns#616]
**需求应用场景**
参考 https://www.v2ex.com/t/712074#reply0
iOS14 会直接利用 type65 里面的 AAAA 记录请求最终服务

**建议的方案**
force-AAAA-SOA yes 时屏蔽 type65 里面的 AAAA

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by fox85** [comment]
+1, 希望大佬能尽快添加屏蔽客户端发出的qtype 65的请求,目前我能想到的暂时性屏蔽方案是使用 iptables过滤特定qtype
ref: https://www.bortzmeyer.org/files/generate-netfilter-u32-dns-rule.py

**Comment by kousyougi** [comment]
> +1, 希望大佬能尽快添加屏蔽客户端发出的qtype 65的请求,目前我能想到的暂时性屏蔽方案是使用 iptables过滤特定qtype
> ref: https://www.bortzmeyer.org/files/generate-netfilter-u32-dns-rule.py

请问iptables 要怎么把 qtype 65挡掉？
我现在DNS被qtype 65 污染的问题感到很困扰，ipset几乎失效。

**Comment by fox85** [comment]
> > +1, 希望大佬能尽快添加屏蔽客户端发出的qtype 65的请求,目前我能想到的暂时性屏蔽方案是使用 iptables过滤特定qtype
> > ref: https://www.bortzmeyer.org/files/generate-netfilter-u32-dns-rule.py
> 
> 请问iptables 要怎么把 qtype 65挡掉？
> 我现在DNS被qtype 65 污染的问题感到很困扰，ipset几乎失效。

iptables过滤效果有限制性，请使用另外一个dns软件
https://github.com/wolf-joe/ts-dns
可以过滤AAAA，qtype 65

**Comment by kousyougi** [comment]
> > > +1, 希望大佬能尽快添加屏蔽客户端发出的qtype 65的请求,目前我能想到的暂时性屏蔽方案是使用 iptables过滤特定qtype
> > > ref: https://www.bortzmeyer.org/files/generate-netfilter-u32-dns-rule.py
> > 
> > 
> > 请问iptables 要怎么把 qtype 65挡掉？
> > 我现在DNS被qtype 65 污染的问题感到很困扰，ipset几乎失效。
> 
> iptables过滤效果有限制性，请使用另外一个dns软件
> https://github.com/wolf-joe/ts-dns
> 可以过滤AAAA，qtype 65

谢谢 刚刚装好，似乎可以用。

但查询速度好像还是没smartdns好。
测试各种组合，最后不用他的测速跟gfwlist分流。只用qtype 65过滤功能，装在国外当上游DNS。本地还是用smartdns。

**Comment by micturkey** [comment]
这几天也遇到了这个问题，主要是cloudflare加速的相关域名的type65解析问题，希望能够屏蔽

**Comment by pymumu** [comment]
最新代码试试：

```shell
force-qtype-SOA 65
```

**Comment by micturkey** [comment]
> 最新代码试试：
> 
> 
> 
> ```shell
> 
> force-qtype-SOA 65
> 
> ```

试了一下，效果很好👍

**Comment by Bitcion** [comment]
> 最新代码试试：
> 
> ```shell
> force-qtype-SOA 65
> ```

能对指定上游或者组 实现吗，类似于 -no-rule-nameserver
