### ISSUE TITLE
不兼容 iptables 的 REDIRECT

### ISSUE THREAD

**Issue by FH0** [pymumu/smartdns#617]
我在服务器上面做测试，环境为 Debian 10

`iptables -t nat -D OUTPUT -d 1.1.1.1/32 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53`

执行了上面的的命令，想劫持所有发往 1.1.1.1 的 dns 请求。但失败了。
![image](https://user-images.githubusercontent.com/32861476/94882655-290b9900-049b-11eb-8c8c-a37d40d2e26f.png)
抓包是这样的
![image](https://user-images.githubusercontent.com/32861476/94882579-f95c9100-049a-11eb-9de4-aa6f10d9bf79.png)

随后我又测试了

`iptables -t nat -A OUTPUT -d 1.1.1.1/32 -p udp -m udp --dport 53 -j DNAT --to 172.17.49.x:53`

成功了
![image](https://user-images.githubusercontent.com/32861476/94882711-50626600-049b-11eb-9050-2a91824f3826.png)

这是配置文件
![image](https://user-images.githubusercontent.com/32861476/94882894-c666cd00-049b-11eb-8fe1-084152bc8aca.png)

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
