### ISSUE TITLE
开了 smartdns然后关掉。电脑无法打开网页

### ISSUE THREAD

**Issue by loyingEcu** [pymumu/smartdns#62]
如题，只要打开了然后再关掉，电脑就打不开网页了 还能上QQ
两个模式都试过了都是关掉电脑就打不开网页，重启路由器都不行
手机却没问题

**Comment by pymumu** [comment]
用的release 18稳定版本吗？

**Comment by pymumu** [comment]
你看一下dnsmasq上游配置有没有被还原吧

**Comment by loyingEcu** [comment]
确实是 搞定了
