### ISSUE TITLE
CentOS 8和阿里云上的CentOS 7安装报错

### ISSUE THREAD

**Issue by IRN-Kawakaze** [pymumu/smartdns#622]
**问题现象**  
有两个问题，先讲第一个：
在CentOS8上按教程安装时报错

install: 正在创建目录'/etc/smartdns'
'usr/sbin/smartdns' -> '/usr/sbin/smartdns'
'etc/smartdns/smartdns.conf' -> '/etc/smartdns/smartdns.conf'
'etc/default/smartdns' -> '/etc/default/smartdns'
'etc/init.d/smartdns' -> '/etc/init.d/smartdns'
Failed to parse bus message: 无效的参数
dirname: 缺少操作数
请尝试执行 "dirname --help" 来获取更多信息。
Failed to parse bus message: 无效的参数
dirname: 缺少操作数
请尝试执行 "dirname --help" 来获取更多信息。

**运行环境**
1. 固件型号  

SmartDNS Release 33

CentOS Linux release 8.2.2004 (Core)

Linux version 5.8.14-1.el8.elrepo.x86_64 (mockbuild@99b44480d09a45019ca1cea289c079c8)

systemd 239
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy

**重现步骤**
./install -i

**信息收集**  
我认为是`systemctl show $service | grep FragmentPath | awk -F'=' '{print $2}'`在CentOS8上无法获取地址导致的。
参考链接：https://bugzilla.redhat.com/show_bug.cgi?id=1853736

实测也确实无法获取到正确的地址（CentOS7上正常）：
[root@centos smartdns]# dirname \`systemctl show sshd.service | grep FragmentPath | awk -F'=' '{print $2}'\`
Failed to parse bus message: 无效的参数
dirname: 缺少操作数
请尝试执行 "dirname --help" 来获取更多信息。

写死`SERVICE_PATH="/usr/lib/systemd/system/sshd.service"`之后就可以正常安装不再报错了。

-----------------------分割线-------------------------
然后是第二个问题：
**问题现象**  
在阿里云的CentOS7上安装，同样会报错，但数量比前一个问题少。

"usr/sbin/smartdns" -> "/usr/sbin/smartdns"
"etc/default/smartdns" -> "/etc/default/smartdns"
已删除"/etc/init.d/smartdns"
"etc/init.d/smartdns" -> "/etc/init.d/smartdns"
"systemd/smartdns.service" -> "/etc/systemd/system/smartdns.service"
Failed to execute operation: Invalid argument

**运行环境**
1. 固件型号  

SmartDNS Release 33

CentOS Linux release 7.8.2003 (Core)

Linux version 5.8.8-1.el7.elrepo.x86_64 (mockbuild@Build64R7)

systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

**重现步骤**
./install -i

**信息收集**  
这个问题出现的段落应该是`start_service`的`systemctl enable smartdns`，安装后手动运行会有同样的错误。

同样是写死`SERVICE_PATH="/usr/lib/systemd/system/sshd.service"`（或者把$service写死为sshd.service）之后就可以正常安装不再报错了。

经过测试，在阿里云服务器上`systemctl --no-legend| grep '\.service' | head -n 1 | awk '{print $1}'`获取到的是aliyun.service，由于aliyun.service和别的service不太一样，所以之后的 <code>dirname \`systemctl show aliyun.service | grep FragmentPath | awk -F'=' '{print $2}'\`</code> 获取到的是/etc/systemd/system而非从其他service能获得的/usr/lib/systemd/system。

我**猜测**这就是问题所在。

不知猜测是否正确？如果错了，希望大佬能指教这俩问题的原因。如果没错，不知道大佬有没有什么好办法能规避一下这俩问题？或者提醒一下可能发生的错误？

最后再捎个小问题，在CentOS8上，运行`systemctl enable smartdns`会提醒：

smartdns.service is not a native service, redirecting to systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable smartdns

这个有啥影响吗？

**Comment by nkh0472** [comment]
Same error on my CentOS 8
(centos-release-8.2-2.2004.0.2.el8.x86_64, kernel: 5.9.8-1.el8.elrepo.x86_64)
```
# ./install -i
install: creating directory '/etc/smartdns'
'usr/sbin/smartdns' -> '/usr/sbin/smartdns'
'etc/smartdns/smartdns.conf' -> '/etc/smartdns/smartdns.conf'
'etc/default/smartdns' -> '/etc/default/smartdns'
'etc/init.d/smartdns' -> '/etc/init.d/smartdns'
Failed to parse bus message: Invalid argument
dirname: missing operand
Try 'dirname --help' for more information.
Failed to parse bus message: Invalid argument
dirname: missing operand
Try 'dirname --help' for more information.
```

```
# ./install -u
Failed to parse bus message: Invalid argument
dirname: missing operand
Try 'dirname --help' for more information.
```

**Comment by nkh0472** [comment]
我按照您的提示，把install中的`get_systemd_path()`函数内容进行了修改，确实解决了问题。
感谢！
```
get_systemd_path()
{
	service="`systemctl --no-legend| grep '\.service' | head -n 1 | awk '{print $1}'`"
	SERVICE_PATH="/usr/lib/systemd/system/sshd.service"
	dirname $SERVICE_PATH
}
```

**Comment by pymumu** [comment]
问题是ali的代码不规范，导致获取列表失效，
可以把head -n 1 改成tail -n 1也应该能规避。

可以看看aliyun的那个返回的是什么。还有aliyun.systemd里面有什么？

**Comment by IRN-Kawakaze** [comment]
> 问题是ali的代码不规范，导致获取列表失效，
> 可以把head -n 1 改成tail -n 1也应该能规避。
> 
> 可以看看aliyun的那个返回的是什么。还有aliyun.systemd里面有什么？

运行：``dirname `systemctl show aliyun.service | grep FragmentPath | awk -F'=' '{print $2}'` ``
获取到的是: `/etc/systemd/system`

/etc/systemd/system/aliyun.service里面的内容如下：
```
[Unit]
Description=阿里云助手
ConditionFileIsExecutable=/usr/local/share/aliyun-assist/2.2.0.70/aliyun-service

After=network-online.target
Wants=network-online.target

[Service]
StartLimitInterval=3600
StartLimitBurst=10
ExecStart=/usr/local/share/aliyun-assist/2.2.0.70/aliyun-service







Restart=on-failure

RestartSec=120
EnvironmentFile=-/etc/sysconfig/aliyun
KillMode=process
[Install]
WantedBy=multi-user.target
```

**Comment by pymumu** [comment]
用新版本测试吧，有问题再open issue
