### ISSUE TITLE
How block ads with an extra file?

### ISSUE THREAD

**Issue by simonbcn** [pymumu/smartdns#623]
I want to use this adblock file: https://github.com/privacy-protection-tools/anti-AD/blob/master/anti-ad-smartdns.conf but how do I get smartdns to load the normal configuration file (`/etc/smartdns/smartdns.conf`) and this one (`/etc/smartdns/anti-ad-smartdns.conf`)? 
With 2 `-c` options: `smartdns -c /etc/smartdns/smartdns.conf -c /etc/smartdns/anti-ad-smartdns.conf`?
With an `include /etc/smartdns/anti-ad-smartdns.conf` at the end of main config file?

**Comment by 5points** [comment]
If you're using luci on openwrt
You can:
1. Put the configuration file "anti-ad-smartdns.conf"in this  folder " /etc/smartdns/ " 
2.Add this Parameter in this file "/etc/smartdns/custom.conf"
conf-file /etc/smartdns/anti-ad-smartdns.conf
