### ISSUE TITLE
speed-check-mode tcp:443  好像无效的样子不会选tcp 443通的ip

### ISSUE THREAD

**Issue by nameless3721** [pymumu/smartdns#624]
**问题现象**  
简要描述问题出现的现象
因为 raw.githubusercontent.com 的部分ip如151.101.0.133 443端口疑似被ban了icmp和80端口通 直连不了使用 speed-check-mode tcp:443 也不会选择443通的ip 151.101.192.133:443
![image](https://user-images.githubusercontent.com/50364156/96182739-da68ff00-0f70-11eb-9b3c-fc07e441e655.png)
解析出的结果是给到443被封的
![image](https://user-images.githubusercontent.com/50364156/96182925-1ef49a80-0f71-11eb-9a23-6bb388a17d44.png)
看上去是3个通的不给 给了个443不通的 smartdns 1.2020.09.08-2235
**运行环境**
1. 固件型号  
OpenWrt R20.9.15 / LuCI Master (git-20.256.12360-1a54222) x86-64
--
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
server-https https://1.0.0.1/dns-query  -group gugu 
2. 访问的域名。  
raw.githubusercontent.com 

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[smartdns.log](https://github.com/pymumu/smartdns/files/5387609/smartdns.log)

**Comment by ShureCool** [comment]
我也碰到了同样的现象，只开启了TCP 443测速的情况下，raw.githubusercontent.com和user-images.githubusercontent.com这两个域名返回151.101.0.133，但是这个IP虽然正确，实际用tcping 443端口不通，手动设置如下IP之后可以直连
address /raw.githubusercontent.com/151.101.108.133
address /user-images.githubusercontent.com/151.101.108.133

楼主的log里面，tcping 151.101.0.133返回的时间是30ms，这个是不是判断上有问题？
[2020-10-16 04:22:49,079][DEBUG][     dns_server.c:1161] from 151.101.0.133:443: seq=1 **time=30**
[2020-10-16 04:22:49,079][ INFO][     dns_server.c:760 ] result: raw.githubusercontent.com, rcode: 0,  151.101.0.133
[2020-10-16 04:22:49,079][DEBUG][      fast_ping.c:387 ] ping end, id 22

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
