### ISSUE TITLE
prefetch时，似乎任何网站都是用default的group来获得dns并测速

### ISSUE THREAD

**Issue by wikihua** [pymumu/smartdns#626]
**问题现象**  
prefetch时，似乎任何网站都是用default的group来获得dns并测速
-- 上游DNS服务器，设置了default组 监听1111 和 proxy组监听8888
--  基于GFWlist，dnsmasq设置了在GFWlist内的，向8888查询dns，并记录在ipset内
然后发现在prefetch时，之前向由8888端口监听到的网址（即在GFWlist内的网址），也是用default group来做prefetch

**运行环境**
1. 固件型号  
斐讯N1 OPENWRT
2. 运营商  
电信

**重现步骤**
1. 上游DNS配置。  
default group：233.5.5.5， 114.114.114.114 等国内DNS服务器
proxy group： 8.8.8.8，1.1.1.1

2. 访问的域名。  
www.google.com  (prefetch时）

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  

> [2020-10-18 23:32:14,950][DEBUG][     dns_server.c:3162] ***prefetch by cache www.google.com***, qtype 1, ttl 300, hitnum 70
> [2020-10-18 23:32:14,951][DEBUG][     dns_client.c:398 ] send query to ***group default***
> [2020-10-18 23:32:14,951][ INFO][     dns_client.c:2823] send request www.google.com, qtype 1, id 3605
> [2020-10-18 23:32:14,953][DEBUG][     dns_client.c:1772] recv udp packet from 210.22.70.225, len: 59, ttl: 155
> [2020-10-18 23:32:14,953][DEBUG][     dns_client.c:1419] qdcount = 1, ancount = 1, nscount = 0, nrcount = 0, len = 59, id = 3605, tc = 0, rd = 1, ra = 1, rcode = 0, payloadsize = 4096
> [2020-10-18 23:32:14,953][DEBUG][     dns_client.c:1425] domain: www.google.com qtype: 1  qclass: 1
> [2020-10-18 23:32:14,953][DEBUG][     dns_server.c:1375] domain: www.google.com TTL:60 IP: 103.252.115.53
> [2020-10-18 23:32:14,954][DEBUG][     dns_server.c:1206] ping 103.252.115.53:443 with tcp
> [2020-10-18 23:32:14,954][DEBUG][      fast_ping.c:1075] ping 103.252.115.53:443, id = 18781

**Comment by kousyougi** [comment]
请问这个bug现在有解吗？困扰中

**Comment by cnommo-star** [comment]
因为cache里面记录的信息并没有记录下首次查询的group，所以后面预取时，要不用指定了nameserfer的(有规则), 要不就只能default。我个人用的时候，发现问题并进行了修改

**Comment by wikihua** [comment]
> 因为cache里面记录的信息并没有记录下首次查询的group，所以后面预取时，要不用指定了nameserfer的(有规则), 要不就只能default。我个人用的时候，发现问题并进行了代码修改

感谢回复...  哎，可惜我不懂代码不会改。 只能放弃这个功能了

**Comment by rampageX** [comment]
> 因为cache里面记录的信息并没有记录下首次查询的group，所以后面预取时，要不用指定了nameserfer的(有规则), 要不就只能default。我个人用的时候，发现问题并进行了代码修改

PR?

**Comment by 1phalley** [comment]
> > 因为cache里面记录的信息并没有记录下首次查询的group，所以后面预取时，要不用指定了nameserfer的(有规则), 要不就只能default。我个人用的时候，发现问题并进行了代码修改
> 
> 感谢回复... 哎，可惜我不懂代码不会改。 只能放弃这个功能了
在自定义设置中conf-file /etc/smartdns/smartdns.more.conf
里面写入
nameserver /0-100.com/cn
nameserver /zzux.com/us
类似的语句，我就是将Chinalist和gfwlist分别直接写死在配置文件里，省得乱解析。作者测试即使写了10万条，查找也仅需1毫秒，对性能毫无影响。

**Comment by 1klakla1** [comment]
> 因为cache里面记录的信息并没有记录下首次查询的group，所以后面预取时，要不用指定了nameserver的(有规则), 要不就只能default。我个人用的时候，发现问题并进行了代码修改

大佬能不能发下怎么改的代码？

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
