### ISSUE TITLE
过期缓存不更新的问题

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#633]
我有个动态域名，发现有时这个动态域名在smartdns不更新，一直是旧的IP，排查的方法有：
1.dig本地的smartdns是已经过期的IP。
2.dig @114.114.114.114是新的IP。
3.dig @119.29.29.29是新的IP。
4.dig @223.5.5.5是新的IP。
5.再次dig本地的smartdns，还是已经过期的IP。
6.查看smartdns日志，发现是有查询的请求的，但就是不更新IP。
7.把smartdns进程结束，再次启动，再dig本地smartdns，是新的IP了，此时正常了。

smartdns是运行在arm64上的，版本是1.2020.08.27-2335，配置文件是：
bind :53 -group chinadns
cache-size 10240
prefetch-domain yes
serve-expired yes
serve-expired-ttl 864000
log-level info
log-size 5M
log-file /tmp/smartdns.log

server-https https://dns.pub/dns-query -group chinadns
server-https https://223.5.5.5/dns-query -group chinadns

**Comment by rampageX** [comment]
`serve-expired-ttl 864000` ?????

**Comment by PHCSJC** [comment]
> `serve-expired-ttl 864000` ?????

这是过期缓存服务的最长时间，并不是域名的ttl时间，我理解你的意思是指rr-ttl这个参数。

**Comment by PHCSJC** [comment]
今天又出现这个问题了，我把serve-expired-ttl去掉了，还是一样。

**Comment by eggboy9999** [comment]
遇到了同样的问题，没办法只能先关掉serve-expired。不知道有没有解决办法？

**Comment by PHCSJC** [comment]
这个问题暂时解决了，就是把下面2个参数去掉就可以了，按理说不应该，可能是BUG：
#serve-expired yes
#serve-expired-ttl 864000

**Comment by PHCSJC** [comment]
再更新下，希望大佬有时间能修复，试了最新的Release 35版本，这个BUG依然存在，解决方法依然是上面说的，把serve-expired这个参数去掉就可以了。

**Comment by realconnor** [comment]
这个问题可以说非常奇特，在不开启「过期缓存」的情况下，常规的缓存会在`ttl`到期时失效，但是在失效之前，是无法通过`dig`观测到的。譬如查询`sogou.com`，初次从上游拿到的结果是`ttl=239`，
```
root@OpenWrt:/tmp# dig -p6153 sogou.com

; <<>> DiG 9.17.13 <<>> -p6153 sogou.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33187
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sogou.com.                     IN      A

;; ANSWER SECTION:
sogou.com.              239     IN      A       119.28.109.132
sogou.com.              239     IN      A       118.191.216.57

;; Query time: 36 msec
;; SERVER: 127.0.0.1#6153(127.0.0.1) (UDP)
;; WHEN: Sun Oct 10 14:32:14 CST 2021
;; MSG SIZE  rcvd: 70
```
在该有效期内，每次（从缓存）查询的结果都显示`ttl=239`，
```
root@OpenWrt:/tmp# dig -p6153 sogou.com

; <<>> DiG 9.17.13 <<>> -p6153 sogou.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15217
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sogou.com.                     IN      A

;; ANSWER SECTION:
sogou.com.              239     IN      A       119.28.109.132
sogou.com.              239     IN      A       118.191.216.57

;; Query time: 0 msec
;; SERVER: 127.0.0.1#6153(127.0.0.1) (UDP)
;; WHEN: Sun Oct 10 14:32:18 CST 2021
;; MSG SIZE  rcvd: 70
```
直到239秒之后重新从上游查询到一个新的`ttl=300`
```
root@OpenWrt:/tmp# dig -p6153 sogou.com

; <<>> DiG 9.17.13 <<>> -p6153 sogou.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8915
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sogou.com.                     IN      A

;; ANSWER SECTION:
sogou.com.              300     IN      A       119.28.109.132
sogou.com.              300     IN      A       118.191.216.57

;; Query time: 52 msec
;; SERVER: 127.0.0.1#6153(127.0.0.1) (UDP)
;; WHEN: Sun Oct 10 14:51:32 CST 2021
;; MSG SIZE  rcvd: 70
```
正常的结果不应该是每次查询，`ttl`都实时的减少吗？而开启「过期缓存」之后，通过`dig`可以看到，`ttl`会固定住，永远不过期，当然`serve-expired-ttl `之后也许会更新，这个没意义，与RFC标准或unbound/ADH的实现是不符的。
也即「此功能会在`ttl`超时后，将返回`ttl=0`给客户端（默认应该是5秒），并且同时再次发送查询请求，并缓存新的结果给后续使用。」——缓存永远不过期，所以向上游更新缓存这件事永远都不会发生，当然`serve-expired-ttl `之后也许会发生？我没试。

`serve-expired yes`时，`ttl=215`到天荒地老😸

```
root@OpenWrt:/tmp# dig -p6153 sogou.com

; <<>> DiG 9.17.13 <<>> -p6153 sogou.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8915
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;sogou.com.                     IN      A

;; ANSWER SECTION:
sogou.com.              215     IN      A       118.191.216.57
sogou.com.              215     IN      A       119.28.109.132

;; Query time: 0 msec
;; SERVER: 127.0.0.1#6153(127.0.0.1) (UDP)
;; WHEN: Sun Oct 10 14:51:32 CST 2021
;; MSG SIZE  rcvd: 70
```

这应该是缓存管理的大Bug了，辛苦作者早日修复吧…

**Comment by PHCSJC** [comment]
> 更正，从`DEBUG`日志来看，「向上游重新请求」这件事发生了，但是缓存没有更新，不知道为什么。

是的，我的动态域名每次都不更新，只能把serve-expired这个选项关闭了

**Comment by crysislinux** [comment]
@PHCSJC 那你要reopenticket了。不然作者看到closed了还以为解决了

**Comment by PHCSJC** [comment]
> 
TTL不变应该是你设置了speed-check-mode none吧？这是另一个BUG。

另外，我发现最新的2021.08.27版本，好像已经解决缓存不成新的问题了，部分参数如下：
speed-check-mode ping
serve-expired yes

**Comment by realconnor** [comment]
> @realconnor
> TTL不变应该是你设置了speed-check-mode none吧？这是另一个BUG。
> 
> 另外，我发现最新的2021.08.27版本，好像已经解决缓存不成新的问题了，部分参数如下：
> speed-check-mode ping
> serve-expired yes

换mosdns了，这个测速我觉得挺离谱的自始自终没用过。

**Comment by PHCSJC** [comment]
@realconnor 
为什么换mosdns呢？我看了下mosdns的性能好像不如smartdns

**Comment by realconnor** [comment]
因为家用不可能达到性能瓶颈，何况下游还有adh和dnsmasq呢，mosdns比他俩都快就行，瓶颈不是它。
何况如果开启测速，smartdns也快不起来。而且还有一些奇怪的问题。

**Comment by PikuZheng** [comment]
已知bug，启用域名预加载后，预加载的域名解析记录不会超时 #787 这里有个补丁

**Comment by PHCSJC** [comment]
> 因为家用不可能达到性能瓶颈，何况下游还有adh和dnsmasq呢，mosdns比他俩都快就行，瓶颈不是它。 何况如果开启测速，smartdns也快不起来。而且还有一些奇怪的问题。

试了下mosdns，配置文件好奇怪，多个tab都会报错，说是简单，其实更复杂了，还是继续用smartdns吧，我用smartdns当主DNS

**Comment by PHCSJC** [comment]
> 已知bug，启用域名预加载后，预加载的域名解析记录不会超时 #787 这里有个补丁

应该是关闭了测速后才会有这个BUG的吧？而不是启用预加载

**Comment by realconnor** [comment]
> > 因为家用不可能达到性能瓶颈，何况下游还有adh和dnsmasq呢，mosdns比他俩都快就行，瓶颈不是它。 何况如果开启测速，smartdns也快不起来。而且还有一些奇怪的问题。
> 
> 试了下mosdns，配置文件好奇怪，多个tab都会报错，说是简单，其实更复杂了，还是继续用smartdns吧，我用smartdns当主DNS

我觉得还好，和adh差不多，而且可以省去一个chinadns。还支持dnscrypt，可比dot/doh这种加密dns快多了。

**Comment by Qeynos** [comment]
遇到了一样的情况，不知道是否设计中就是这样

**Comment by PHCSJC** [comment]
@Qeynos 是个BUG，参考 #867

**Comment by Qeynos** [comment]
> @Qeynos 是个BUG，参考 #867

我还发现在bind后面设置-no-cache，解析的结果疑似还是会被`serve-expired yes`影响，返回的ttl是1，并且好像也会被prefetch

**Comment by PHCSJC** [comment]
> > @Qeynos 是个BUG，参考 #867
> 
> 我还发现在bind后面设置-no-cache，解析的结果疑似还是会被`serve-expired yes`影响，返回的ttl是1，并且好像也会被prefetch

是的，其实是2个BUG，cname和-no-cache都会导致TTL不变，进而导致域名的IP不更新

**Comment by Qeynos** [comment]
> > > @Qeynos 是个BUG，参考 #867
> > 
> > 
> > 我还发现在bind后面设置-no-cache，解析的结果疑似还是会被`serve-expired yes`影响，返回的ttl是1，并且好像也会被prefetch
> 
> 是的，其实是2个BUG，带有cname的域名TTL不变，和-no-cache会导致所有域名TTL不变，进而导致域名的IP不更新

那目前有没有比较有效的解决方案？我想避免的是ddns解析不出错，只能打开测速？

**Comment by PHCSJC** [comment]
@Qeynos 是的，关闭测速，没什么别的办法

**Comment by Qeynos** [comment]
> > @Qeynos 是个BUG，参考 #867
> 
> 我还发现在bind后面设置-no-cache，解析的结果疑似还是会被`serve-expired yes`影响，返回的ttl是1，并且好像也会被prefetch

更正一下，ttl返回1是部分dns服务器的问题，-no-cache确实ttl不变了，但理论上确实应该不变，没有缓存以后每次都是重新获取的解析，ttl都是最大值才对，从延迟上也看得出是从远端dns服务器解析的
