### ISSUE TITLE
[ERROR][ dns_server.c:3322] dns server process failed.  R2S openwrt 间歇性自动变成未运行状态

### ISSUE THREAD

**Issue by yfchen1988** [pymumu/smartdns#635]
**问题现象**  
在R2s上，openwrt，运行一段时间，不定时的，会显示"SmartDNS - 未运行“
web管理界面”开启“状态打钩的，实际上已经没有dns服务了，需要关闭一次服务，重新手动再次开启。
smartdns 1.2020.09.08-2235

日志中，每4秒钟，增加一套记录，[ERROR][     dns_server.c:3322] dns server process failed.

**运行环境**
1. 固件型号  

固件版本	OpenWrt r14607-3fab4ace57
内核版本	5.4.68

2. 运营商  

中国电信

**重现步骤**
1. 上游DNS配置。  
/etc/smartdns 中的所有文件
[etc.zip](https://github.com/pymumu/smartdns/files/5482113/etc.zip)

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  [log.zip](https://github.com/pymumu/smartdns/files/5482102/log.zip)
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by yfchen1988** [comment]
目前才手动开启的coredump，暂时/tmp下没有对应信息文件，后续如果发现了，会再次上传

**Comment by yfchen1988** [comment]
coredump有一个了

[smartdns.1604416968.13074.11.core.zip](https://github.com/pymumu/smartdns/files/5482246/smartdns.1604416968.13074.11.core.zip)

**Comment by PikuZheng** [comment]
你的配置文件是空白的。
目前怀疑 当开启了 双栈IP优选 或 测速 且设备本身不支持ipv6时，出现此故障，可以试试 force-AAAA-soa yes

**Comment by PikuZheng** [comment]
#35

**Comment by pymumu** [comment]
用最新版本验证。
