### ISSUE TITLE
升级wsl2后，无法使用127.0.0.1进行解析，更换实际动态IP也无法正常解析。 

### ISSUE THREAD

**Issue by achtowen** [pymumu/smartdns#636]
**需求应用场景**
win10系统专业版正常安装wsl,并升级到WSL2，仍使用WSL正常可使用的配置文件。

**建议的方案**
使得WSL2动态生成的IP测试过，无法正常解析。
请教WSL2下使用smartdns设定方法。

**Comment by pymumu** [comment]
wsl2没测试过，你可以将dns配置为wsl2的IP地址即可。
