### ISSUE TITLE
如何实现dns-query

### ISSUE THREAD

**Issue by aogg** [pymumu/smartdns#638]
![image](https://user-images.githubusercontent.com/8998031/98332517-c8dbba00-2039-11eb-9f58-f7d449a0806f.png)

这样就可以在浏览器里自定义了

**Comment by tudnew** [comment]
这个好像没必要吧，公共场所搭建DNS需要认证，私人直接局域网搭建了，局域网都无法信任那没法搞了。

**Comment by aogg** [comment]
主要是提供给浏览器用的，流浪器不支持普通dns设置，只支持dns-query

**Comment by tudnew** [comment]
哦，看样子作者不打算支持，都关了，我自己用AdGuard，smartdns做上游，还是有WEBUI的香🤣

**Comment by aogg** [comment]
> 哦，看样子作者不打算支持，都关了，我自己用AdGuard，smartdns做上游，还是有WEBUI的香🤣

我就想着加速流浪器，你都做起广告屏蔽了🤣。

不过感觉没理解对你的AdGuard，啥webui啊

**Comment by pymumu** [comment]
首先，要理解浏览器DOH的使用场景，在使用，否则只是徒劳折腾，大部分情况可能还会起到反作用。
smartdns定位是家庭局域网的服务，对外使用了加密TLS请求，为安全，对家庭使用UDP，为性能。
原则上，认为家里网络是可信的，无需特别保护，主要是性能为目标，而不是安全。
所以，家里网络，浏览器没有必要再使用DOH，smartdns已经有DOT，DOT，在DNS上比浏览器更强。

WebUI方面，smartdns集成到了openwrt上，易用性上能满足要求，也更容易部署。

**Comment by aogg** [comment]
主要是最近用了xip.io作为开发环境的域名，然后已经用上smartdns了还是会出现过一段时间出现ip找不到的情况，看下了又不能单独设置上级域名的及子域名下的ttl，最好永久ttl这样

哪怕最小ttl也是不行的，所以想着要不试下dns-query
感觉上这样也会被说定位不对，但还是希望能支持下

**Comment by aogg** [comment]
xip.io对开发环境网站多，外包这样，好多好多项目和域名，然后又想用域名不用二级路径这样，就会出现体验不好

**Comment by tudnew** [comment]
> > 哦，看样子作者不打算支持，都关了，我自己用AdGuard，smartdns做上游，还是有WEBUI的香🤣
> 
> 我就想着加速流浪器，你都做起广告屏蔽了🤣。
> 
> 不过感觉没理解对你的AdGuard，啥webui啊
> https://github.com/AdguardTeam/AdGuardHome
> 是吧

是的，其实广告屏蔽不是很好，算比没有好吧，规则太多容易误伤，主要是可以劫持CNAME，可以方便查域名日志，我正好需要(大不了套娃呗🤣)，加速效果没这个好的。
