### ISSUE TITLE
smartdns.service: Can't open PID file /run/smartdns.pid

### ISSUE THREAD

**Issue by simonbcn** [pymumu/smartdns#639]
```
Arch Linux
smartdns git version installed from AUR package (https://aur.archlinux.org/packages/smartdns-git/)
```

```
$ systemctl status smartdns
● smartdns.service - smartdns server
Loaded: loaded (/usr/lib/systemd/system/smartdns.service; enabled; vendor preset: disabled)
Active: active (running) since Fri 2020-11-06 19:03:31 CET; 4s ago
Process: 125082 ExecStart=/usr/bin/smartdns -p /run/smartdns.pid $SMART_DNS_OPTS (code=exited, status=0/SUCCESS)
Main PID: 125083 (smartdns)
Tasks: 4 (limit: 76980)
Memory: 11.2M
CGroup: /system.slice/smartdns.service
└─125083 /usr/bin/smartdns -p /run/smartdns.pid

nov 06 19:03:31 juan-PC systemd[1]: Starting smartdns server...
nov 06 19:03:31 juan-PC systemd[1]: smartdns.service: Can't open PID file /run/smartdns.pid (yet?) after start: Operation not permitted
nov 06 19:03:31 juan-PC systemd[1]: Started smartdns server.
```

**Comment by 6870** [comment]
https://askubuntu.com/questions/1117330/opendkim-wont-start-cant-open-pid-file
1. open the /lib/systemd/system/smartdns.service with vim or nano
2. find the line: ExecStart=/usr/sbin/smartdns -p /var/run/smartdns.pid $SMART_DNS_OPTS
3. del /var and save the file. the changed line will be equal to "ExecStart=/usr/sbin/smartdns -p /run/smartdns.pid $SMART_DNS_OPTS"
4. run systemdctl daemon-reload && systemdctl restart smartdns 
5. problem temporarily solved.

**Comment by simonbcn** [comment]
It doesn't happen anymore.

**Comment by dream10201** [comment]
![image](https://github.com/pymumu/smartdns/assets/20334372/855519a4-25d2-4f7f-bb40-e179784d3db9)
又出现了

**Comment by PikuZheng** [comment]
可否检查配置文件中是否有 restart-on-crash yes

**Comment by PikuZheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/20334372/326658284-855519a4-25d2-4f7f-bb40-e179784d3db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDk5NDMsIm5iZiI6MTcxNDQ0OTY0MywicGF0aCI6Ii8yMDMzNDM3Mi8zMjY2NTgyODQtODU1NTE5YTQtMjVkMi00ZjdmLWJiNDAtZTE3OTc4NGQzZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA0MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliOTNlNjU0ZDkzMWQxODBlMTJlMTQyYzE0NmMyMTdkZTQxYzlmODM5ZjdiOWY5YzZhNjJmMjdkNGI1NGNmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PgO-DfiS3d3-zUfiWg-S3aRl-vpWP6nxUbl-1ppfVwo) 又出现了

这个 -R 就是 restart-on-crash yes，它与systemd不兼容，请查查看这个是哪来的（配置文件？环境变量？）去掉应该就可以了

**Comment by dream10201** [comment]
是我添加的，去除之后没再出现了，感谢！
