### ISSUE TITLE
添加潘多拉AR71XX相关架构

### ISSUE THREAD

**Issue by zzxxtt** [pymumu/smartdns#64]
**需求应用场景**
根据AR71XX选择smartdns.1.2019.01.07-2334.mips_24kc.ipk
修改opkg arch后安装无法启动，luci显示 SmartDNS - 未运行
手动执行/usr/sbin/smartdns报错
[root@PandoraBox_00BA0m:/tmp]#ls -al smartdns24k*
-rwxrwxrwx    1 root     root        166493 Jan  7 23:35 smartdns24kc
-rwxrwxrwx    1 root     root        165160 Jan  7 23:35 smartdns24kecdsp
[root@PandoraBox_00BA0m:/tmp]#./smartdns24kc
bash: ./smartdns24kc: cannot execute binary file: Exec format error
[root@PandoraBox_00BA0m:/tmp]#./smartdns24kecdsp
bash: ./smartdns24kecdsp: No such file or directory

**建议的方案**
增加编译架构 

**设备信息**
1. 设备信息（CPU，厂家）  
QCA9558
MIPS 74Kc V5.0
DomyWifi DW33D

2. 固件信息
PandoraBox 19.01 2018-12-31-git-4b6a3d5ca / 			LuCI Master (git-18.364.80006-87f648f)
3.14.79

**Comment by pymumu** [comment]
smartdns.xxxxxxxx.mipsel_24kec_dsp.ipk
这个能用吗？

**Comment by zzxxtt** [comment]
也无法运行

**Comment by pymumu** [comment]
发一下软件源安装URL。

**Comment by zzxxtt** [comment]
src/gz 19.01_core http://downloads.pangubox.cn/pandorabox/19.01/targets/ar71xx/generic/packages
src/gz 19.01_base http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/base
src/gz 19.01_newifi http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/newifi
src/gz 19.01_pear http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/pear
src/gz 19.01_packages http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/packages
src/gz 19.01_luci http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/luci
src/gz 19.01_lafite http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/lafite
src/gz 19.01_mtkdrv http://downloads.pangubox.cn/pandorabox/19.01/packages/mips_74kc_dsp2/mtkdrv

**Comment by pymumu** [comment]
看你的安装源，感觉
https://github.com/pymumu/smartdns/releases/download/release18/smartdns.1.2019.01.07-2334.ar71xx.ipk

这个可用。

**Comment by pymumu** [comment]
可能要改一下arch字段
