### ISSUE TITLE
新增prefetch-size设定

### ISSUE THREAD

**Issue by kousyougi** [pymumu/smartdns#640]
**需求应用场景**
域名预先获取功能，希望可以新增prefetch-size设定

**建议的方案**
假设 cache-size 设定 10000，prefetch-size 设定100 的话。

1. 在10000个cache里面找累计查询最多的前100个domain，TTL到期自动更新。
或
2. 最近查询的前100个domain，TTL到期自动更新。

第二种方法好像比较省资源。我自己比对我自己的DNS查询记录，反复查询的domain大概就只有几十个，这两种方法我常用的那
几十个domain都会在那100个prefetch domain里面。

希望可以增加这个功能。
谢谢

**Comment by cnommo-star** [comment]
这个主要是用来降低DNS查询的压力吧。实际代码的逻辑，已经是默认只预取一次。
在ttl有效时间内，如果有dns访问，则会增加预取次数，这已经是自动适应了。

**Comment by pymumu** [comment]
建议直接使用serve-expired功能。具体看手册。
