### ISSUE TITLE
Ubuntu 20.04下systemd启动一直报错

### ISSUE THREAD

**Issue by vongoethe** [pymumu/smartdns#642]
**问题现象**  
简要描述问题出现的现象
Ubuntu 20.04系统，安装完smartdns，systemd一直报
“smartdns.service: Can't open PID file /run/smartdns.pid (yet?) after start: Operation not permitted”
但是查询功能是可以使用的

**运行环境**
1. 固件型号  
Ubuntu 20.04

2. 运营商  
**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
/usr/sbin/smartdns -h
看看。

**Comment by lonelykid** [comment]
release里的systemd配置不对，仓库里的已经改了，不知道为啥release打包的不对
https://github.com/pymumu/smartdns/commit/baa1397fb0d748055d56042739f19aff3f69c4fe

**Comment by lonelykid** [comment]
有两个问题，
- /var/run只是link到/run，systemd似乎想要你创建到/run
- pid文件的权限不对，`ExecStartPost=/bin/sh -c 'chmod 644 /run/smartdns.pid'`，在service部分加上这行。

**Comment by pymumu** [comment]
有空我验证下

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue

**Comment by Moebyte** [comment]
这个问题在Debian11依旧出现

**Comment by pymumu** [comment]
可能是systemd的bug，忽略就好。

或者systemd的unit文件中，删除PIDFile，增加GuassMainPid=yes。

**Comment by pymumu** [comment]
最新代码优化了一下，应该不会有错误了。
