### ISSUE TITLE
国内能解释出一个IP，Youtube解释出来是多个IP

### ISSUE THREAD

**Issue by dengchan0416** [pymumu/smartdns#643]
smartdns+passwall，国内域名没有问题能过nslookup都能解释到一个IP，就是youtube解释出来都是多个IP，重定向已经是设为53
![QQ截图20201116150201](https://user-images.githubusercontent.com/41529838/99224477-5a5ce000-2821-11eb-9f4b-14e58f99fa67.jpg)
![QQ截图20201116153725](https://user-images.githubusercontent.com/41529838/99224639-ac056a80-2821-11eb-9bcb-8ce3ffdaef71.jpg)
![QQ截图20201116154113](https://user-images.githubusercontent.com/41529838/99224961-34840b00-2822-11eb-8411-bc2e4619e4a4.jpg)
![QQ截图20201116154250](https://user-images.githubusercontent.com/41529838/99225095-757c1f80-2822-11eb-8753-e0d64ae971ac.jpg)
Passwall设置
![QQ截图20201116154356](https://user-images.githubusercontent.com/41529838/99225248-b116e980-2822-11eb-9541-499a1e836d7a.jpg)

**Comment by dengchan0416** [comment]
找到原因了，在第二DNS服务器自动跳过测速勾取消就正常了

**Comment by cnommo-star** [comment]
但这里很不建议启动测速，经过了几层代理线路，测试出来的结果其实已经不准确了，还不如原始的好

**Comment by smdx** [comment]
遇到同样问题，所有网站都正常返回单个ip，就www.youtube.com返回n个ip。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
