### ISSUE TITLE
经常无法访问google

### ISSUE THREAD

**Issue by xiaotudoubaba** [pymumu/smartdns#644]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
部署在centos7服务器上,
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
 server-tcp 8.8.8.8
 server-tcp 114.114.114.114
 server-tcp 114.114.115.115
 server-tcp 223.5.5.5
 server-tcp 223.6.6.6
 server-tcp 180.76.76.76
 server-tcp 119.29.29.29
 server-tcp 182.254.116.116

 server-tls 8.8.8.8
 server-tls 8.8.4.4
 server-tls 1.1.1.1
 server-tls 1.1.0.0

2. 访问的域名。  
www.google.com
www.google.com.hk

**信息收集**  
经常访问google 出现如下错误,
![Snip20201119_18](https://user-images.githubusercontent.com/72748373/99644794-5632fb80-2a89-11eb-8ad1-238a9b381f0e.png)

**Comment by cnommo-star** [comment]
这是证书错误， 与dns有关但不全是。并极有可能是去广告功能引起

**Comment by pymumu** [comment]
看一下具体的证书信息吧。

**Comment by pymumu** [comment]
用IP地址黑名单或白名单。
