### ISSUE TITLE
我提几个明确的需求或问题

### ISSUE THREAD

**Issue by cnommo-star** [pymumu/smartdns#646]
**需求应用场景**
我提一些需要的改进，这些已经在我们的系统上尝试验证应该可行
1  prefetch时使用初次查询指定的group， 也即cache信息中包含group
2 prefetch的预设次数可指定（不一定是1， 代码中预设是hitnum是3，意即预取1次），提高体验
3 域名查询，可以指定多个group， group内并发，group间串行（如dns服务器有企业内的，公网的，一般优先企业内解析）
4 对于passthrough模式，即不check speed， 返回的ttl也应该是可变的（目前是固定不变的）
5 不仅限于AAAA查询，可以指定其他qtype（如httpsvc 65）也返回SOA（或符合协议约束的空返回）
6 对于doh等地址包含域名的方式，这些域名的查询应该不需要测速（这是dns服务器地址，本身的速度并无太大意义）， 反而丢掉了多dns地址容灾的好处
7 换一种方式如 port/group查询，缓存应忽略或失效
8 dns encode 未支持域名压缩（减少包大小）

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by kousyougi** [comment]
qtype、speed check、prefetch 目前困扰我的三个问题。qtype最头痛。

**Comment by pymumu** [comment]
1. 这个没看懂。意思是第一次用特点group，第二次不用？现在prefetch用的group是domain-rule指定的。
2. 这个有测试数据吗，3也只是一个经验值。配置少一点，使用也简单。
3. group可以指定多个，多个-group参数即可。目前都是并行。
4. 穿透的情况，ttl就是上游值，这里应该要刷新的，有些代码量，要dns解析哪里支持多IP。后面补充。
5. 这个可以增加，但场景是什么？
6. 只是实现上便捷，关键的不是这个，是IP地址变化，目前还没支持。
7. 支持不同port用不同group或忽略，具体看readme
8. 是，这个代码还没支持。

欢迎你们贡献代码。

**Comment by pymumu** [comment]
done
