### ISSUE TITLE
无法解析至192.168.x.x 吗？

### ISSUE THREAD

**Issue by libra1010** [pymumu/smartdns#647]
**问题现象**  
简要描述问题出现的现象
无法解析至192.168.x.x 吗？
address /xx.xxx.com/192.168.1.100 
无效返回 
on-authoritative answer:
*** Can't find nas.ikolo.me: No answer

address /xx.xxx.com/1.2.3.4
address /xx.xxx.com/127.0.0.1
则完全正确

**运行环境**
1. 固件型号  
openwrt
2. 运营商  

**重现步骤**
1. 上游DNS配置。  
114
2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
