### ISSUE TITLE
ASUS AC86U 安装arm版本成功，但重启后似乎没有在运行

### ISSUE THREAD

**Issue by ckorz** [pymumu/smartdns#65]
ASUS AC86U 安装arm版本成功，但重启后似乎没有在运行
SHH输入命令top没有显示smartdns进程，在指定位置也没有生产log文件，但U盘根目录确实有smartdns的相关文件。

固件型号  ：3.0.0.4.384_32799_koolshare

**Comment by pymumu** [comment]
是华硕的官方固件吗？
如果是，执行一下/opt/etc/init.d/S50smartdns enable，设置服务自动启动。

**Comment by ckorz** [comment]
> 是华硕的官方固件吗？
> 如果是，执行一下/opt/etc/init.d/S50smartdns enable，设置服务自动启动。

是官改固件来的,在官方固件的基础上添加了软件中心，执行了命令，没有报错，但重启了还是没有在运行的样子，日志文件也没有生成。。我试试更新下固件。

**Comment by pymumu** [comment]
是梅林固件吧，梅林固件没有测试过，没路由器。

等后面淘一个便宜点的路由装下测试

**Comment by ckorz** [comment]
> 是梅林固件吧，梅林固件没有测试过，没路由器。
> 
> 等后面淘一个便宜点的路由装下测试

http://koolshare.cn/thread-139965-1-1.html
上面的是固件的网址,按照说明是没有用梅林固件代码的.

二、固件主要特色
使用官方固件源代码为基础（非merlin固件代码）修改；
固件ROG信仰皮肤加成，见本帖最后图片欣赏；
在官方固件基础上增加一些功能，如ipset，base64，tproxy，wan-start，nat-start等功能；
koolshare软件中心支持（1.5代，不兼容一代），软件中心支持rog皮肤和非rog皮肤；
wireguard原生内核支持。

**Comment by recgo** [comment]
我的AC86U也是安装arm版本不见运行，不过固件是华硕官方的3.0.0.4.384_45149，试了smartdns.1.2018.12.02-1745.arm.ipk和smartdns.1.2019.01.26-0014.arm.ipk都不行:cry:

**Comment by pymumu** [comment]
先执行一下
/opt/usr/sbin/smartdns -h
看看有没有反应

如果有，执行
/opt/etc/init.d/S50smartdns enable
/opt/etc/init.d/S50smartdns restart

具体参考ReadMe的安装说明optware部分，即华硕路由器章节。

**Comment by recgo** [comment]
执行`/opt/usr/sbin/smartdns -h`提示`-sh: /opt/usr/sbin/smartdns: not found`
去/opt/usr/sbin/看的话的确是有个smartdns在那里啊
如果执行`/opt/etc/init.d/S50smartdns restart`则是

> cat: can't open '/var/run/smartdns.pid': No such file or directory
smartdns not running.
/opt/etc/init.d/S50smartdns: line 258: /opt/usr/sbin/smartdns: not found

**Comment by ShinkaiMakoto** [comment]
NEATGEAR R7000 刷了koolshare的梅林固件
架构是arm
安装时，所有步骤都没有报错
症状和第一个人的情况一样，top没有进程，没有日志文件生成，没有coredump生成
但是，尝试了以`/opt/usr/sbin/smartdns -f`命令启动后，ssh界面显示`load config failed.
`
另外，iptables规则是有的，如下`admin@R7000-2E04:/tmp/home/root# iptables -t nat -L PREROUTING | grep REDIRECT
REDIRECT   udp  --  anywhere             R7000-2E04.          udp dpt:domain redir ports 535
REDIRECT   udp  --  anywhere             169.254.68.65        udp dpt:domain redir ports 535
`

**Comment by pymumu** [comment]
用这个配置文件试试
[smartdns.zip](https://github.com/pymumu/smartdns/files/2799882/smartdns.zip)

**Comment by Serino2009** [comment]
梅林 7.9.1 （官改不晓得）之后，自启动貌似有些问题，
不知道是不是因为砍掉 cronb 命令导致的

想要添加自启动脚本，可以尝试在 
/jffs/scripts 下的 services-start 下添加
没有这个文件可以自己创建，木有后缀名
权限 0777 或者 0755

这个启动命令可以在路由重启后生效，
有些配置在重新拨号或者调试 WiFi 之后会重置，需要自己手动运行脚本

另外
/jffs/scripts 下的 nat-start 和 wan-start 添加的启动命令
我的机子(RT-AC5300 梅林7.9.1)上无法生效

**Comment by pymumu** [comment]
感觉梅林安装optware后，应该能自动启动才对，
要不然optware都有问题了。

重新拨号，wifi不可用，是因为刷新了iptable，所有配置都丢了。
华硕的会调用firewall-start分支。梅林应该有类似的机制才对。

但总之，后面看看梅林的开发指导，看看有什么差异。

**Comment by pymumu** [comment]
smartdns代码里面在增加一个reconfigure分支就可以支持wifi配置变动刷新了。

你可以先手工增加reconfigure分支看看，修改文件/opt/etc/init.d/S50smartdns的253行
改为：
firewall-start|reload|force-reload|reconfigure)

**Comment by pymumu** [comment]
尝试Release 26静态编译版本把。

**Comment by gengxf0505** [comment]
TM-AC1900 改RT-AC68 固件FW_RT_AC68U_30043763626：
安装成功： smartdns.1.2020.02.25-2212.arm-optware-all.ipk  其他有各种问题。
Installing smartdns (1.2020.02.25-2212) to /opt/...
Configuring smartdns
Successfully terminated.

执行：admin@(none):/tmp/mnt/USB# /opt/usr/sbin/smartdns -f
load config failed.
更换 https://github.com/pymumu/smartdns/issues/65#issuecomment-457900527 的配置文件后正常
![image](https://user-images.githubusercontent.com/32632982/77847118-35adec80-71ed-11ea-8af9-d63c356ffad3.png)

![image](https://user-images.githubusercontent.com/32632982/77847148-6a21a880-71ed-11ea-944b-989b62b92eb5.png)
