### ISSUE TITLE
现在不build华硕梅林平台mipsbig的包了么

### ISSUE THREAD

**Issue by zyystudio** [pymumu/smartdns#651]
**需求应用场景**
请描述需求应用的场景和方式。
ipk包发个吧
**建议的方案**
实现上述场景建议的方案。
ipk包发个吧
**设备信息**
1. 设备信息（CPU，厂家）  
ipq4708
2. 固件信息
384

谢谢

**Comment by pymumu** [comment]
https://github.com/pymumu/smartdns/releases/download/Release33/smartdns.1.2020.09.08-2235.mips-optware-all.ipk
