### ISSUE TITLE
cache-persist 默认被打开

### ISSUE THREAD

**Issue by felixonmars** [pymumu/smartdns#652]
**问题现象**  
在配置文件中未指定 cache-persist 的时候，`/tmp/smartdns.cache`被生成和使用了。而 README 等地方写的这个配置项的默认值为 `no`。在手动指定 `cache-persist no`后，这个文件才消失。

**运行环境**
1. 固件型号  
Arch Linux x86_64
smartdns 33-1

**Comment by huyz-git** [comment]
我也发现这个问题了。
看了下代码，应该是文档没有更新。

代码在
https://github.com/pymumu/smartdns/blob/42b3e98b2a3ca90ea548f8cb5ed19a3da6011b74/src/dns_conf.c#L84
这个地方，把 `dns_conf_cache_persist` 初始化为了 2。然后如果配置文件里配置了 yes 或 no，则将其置为 1 或 0。即 `cache-persist` 的默认值既不是 yes 也不是 no。

随后，当 `dns_conf_cache_persist` 为 2 时，在
https://github.com/pymumu/smartdns/blob/42b3e98b2a3ca90ea548f8cb5ed19a3da6011b74/src/dns_server.c#L3594-L3600
这里做了个判断，如果 `cache_file` 所在的地方有超过 `CACHE_AUTO_ENABLE_SIZE` （默认值为 1024 * 1024 * 128，即 128MB ）的空闲空间时，则会启用 `cache-persist`。
