### ISSUE TITLE
关闭speed-check后audit 审计功能无效

### ISSUE THREAD

**Issue by youxixin888** [pymumu/smartdns#654]
平台Linux 4.11.8-1.el7.elrepo.x86_64

配置
bind [::]:53-group localdnsg1 **-no-speed-check**
或者
**speed-check-mode none**
后
audit功能配置项失效。

**Comment by pymumu** [comment]
目前是这样的，因为关闭测速后，没有再解析IP地址信息。后面支持多IP了再增加。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
