### ISSUE TITLE
介于现国内公共DNS打架，解决国内DNS打群架问题

### ISSUE THREAD

**Issue by LsnmxNB** [pymumu/smartdns#656]
解决国内DNS打群架问题
每次一到重要节日国内DNS就开始打架
各自作死
把竞争对手的域名解析到国外
有时还打不开
一起收集完善国内几家喜欢用DNS打架家族的常用域名
字节跳动旗下没公共DNS，就不加入了，字节跳动公司也开始招人做公共DNS了，都是国内DNS打群架
2021.04.7更新

smartdns上游服务器
<img width="1485" alt="smartdns上游服务器" src="https://user-images.githubusercontent.com/42826027/113815931-8b28bc00-97a6-11eb-9950-c5921b80bfe0.png">

自定义设置

测速模式选择
Disable ipv6 address resolution
force-AAAA-SOA yes

speed-check-mode ping,tcp:80

#example bind :7054 -group us -no-dualstack-selection -no-cache -force-aaaa-soa

bind: 8888 -group cn
bind: 8889 -group us -exclude-default-group

#cnDoH-alidns
#server 223.6.6.6 -group cnDoH-alidns -exclude-default-group
#nameserver /dns.alidns.com/cnDoH-alidns

#cnDoH-DNSPod
server 119.29.29.29 -group cnDoH-DNSPod -exclude-default-group
nameserver /doh.pub/cnDoH-DNSPod
nameserver /dns.pub/cnDoH-DNSPod
nameserver /dot.pub/cnDoH-DNSPod

#usDoH-Cloudflare
#server 1.1.1.1 -group usDoH-Cloudflare -exclude-default-group
#nameserver /cloudflare-dns.com/usDoH-Cloudflare

#usDoH-Google
server 8.8.8.8 -group usDoH-Google -exclude-default-group
nameserver /dns.google/usDoH-Google

#server 223.5.5.5 -group AliDNS -exclude-default-group

server-https https://223.6.6.6/dns-query -group AliDNS -exclude-default-group

nameserver /alipay.com/AliDNS
nameserver /aliyun.com.com/AliDNS
nameserver /taobao.com/AliDNS
nameserver /tmall.com/AliDNS
nameserver /xianyuso.com/AliDNS
nameserver /alibabacloud.com/AliDNS
nameserver /weibo.com/AliDNS
nameserver /weibo.cn/AliDNS
nameserver /amap.com/AliDNS
nameserver /uc.cn/AliDNS
nameserver /1688.com/AliDNS
nameserver /koubei.com/AliDNS
nameserver /ele.me/AliDNS
nameserver /alibaba.com/AliDNS
nameserver /etao.com/AliDNS
nameserver /fliggy.com/AliDNS
nameserver /xiami.com/AliDNS
nameserver /taopiaopiao.com/AliDNS
nameserver /youku.com/AliDNS
nameserver /dingtalk.com/AliDNS
nameserver /cainiao.com/AliDNS
nameserver /guoguo-app.com/AliDNS
nameserver /tudou.com/AliDNS
nameserver /mybank.cn/AliDNS
nameserver /cnzz.com/AliDNS
nameserver /umeng.com/AliDNS
nameserver /alicdn.com/AliDNS
nameserver /tanx.com/AliDNS
nameserver /mmstat.com/AliDNS
nameserver /ykimg.com/AliDNS
nameserver /sinaimg.cn/AliDNS
nameserver /sinajs.cn/AliDNS
nameserver /meizu.cn/AliDNS
nameserver /meizu.com/AliDNS
nameserver /mzres.com/AliDNS
nameserver /aliyuncs.com/AliDNS
nameserver /ucweb.com/AliDNS
nameserver /flyme.cn/AliDNS
nameserver /flyme.com/AliDNS
nameserver /aliyuncs.com/AliDNS
nameserver /sina.cn/AliDNS
nameserver /weibocdn.com/AliDNS

#server 119.29.29.29 -group DNSPod -exclude-default-group

server-https https://doh.pub/dns-query -group DNSPod -exclude-default-group

nameserver /weixin.com/DNSPod
nameserver /qq.com/DNSPod
nameserver /qzoneapp.com/DNSPod
nameserver /qqgameapp.com/DNSPod
nameserver /qqopenapp.com/DNSPod
nameserver /pengyou.com/DNSPod
nameserver /tencent.com/DNSPod
nameserver /sogou.com/DNSPod
nameserver /maoyan.com/DNSPod
nameserver /gtimg.com/DNSPod
nameserver /qpic.cn/DNSPod
nameserver /sogoucdn.com/DNSPod
nameserver /qlogo.cn/DNSPod
nameserver /gtimg.cn/DNSPod
nameserver /gdtimg.com/DNSPod

server 180.76.76.76 -group Baidu -exclude-default-group

nameserver /baidu.com/Baidu
nameserver /iqiyi.com/Baidu
nameserver /baidupcs.com/Baidu
nameserver /bdstatic.com/Baidu
nameserver /91.com/Baidu
nameserver /iqiyipic.com/Baidu
nameserver /bdimg.com/Baidu
nameserver /baifubao.com/Baidu
nameserver /qingting.fm/Baidu
nameserver /duxiaoman.com/Baidu
nameserver /qy.net/Baidu
nameserver /bcebos.com/Baidu

#server 8.8.4.4 -group Google -exclude-default-group

server-https https://dns.google/dns-query -group Google -exclude-default-group

nameserver /googleusercontent.com/Google
nameserver /gvt1.com/Google
nameserver /google.com/Google
nameserver /youtube.com/Google
nameserver /waze.com/Google
nameserver /blog.youtube/Google
nameserver /tiltbrush.com/Google
nameserver /android.com/Google
nameserver /gstatic.com/Google
nameserver /ytimg.com/Google
nameserver /ggpht.com/Google
nameserver /googleapis.com/Google
nameserver /googlevideo.com/Google
nameserver /doubleclick.net/Google
nameserver /lra8j.com/Google
nameserver /measurement.com/Google
nameserver /fonts.loli.net/Google

# 去广告文件，去掉#就可以使用自带去广告的文件了，也可以自己上传。
# conf-file /etc/smartdns/anti-ad-smartdns.conf

**Comment by soffchen** [comment]
好像没有吧？

另外，smartdns 不是可以测速吗，都管上。

**Comment by recall704** [comment]
不是有 group 吗

**Comment by LsnmxNB** [comment]
> 不是有 group 吗
> 
> 你把阿里放一个 group，百度放一个 group，腾讯放一个 group
> 各自用自己的 dns 解析。

@recall704   大佬来个完整命令谢谢了

**Comment by LsnmxNB** [comment]
> 好像没有吧？
> 
> 另外，smartdns 不是可以测速吗，都管上。

不行啊反正开了测速得到的结果还是最慢的

**Comment by LsnmxNB** [comment]
解决国内DNS打群架问题
# 测速模式选择

#Disable ipv6 address resolution
force-AAAA-SOA yes

speed-check-mode tcp:443,tcp:80,ping
#example bind :7913 -group us -no-dualstack-selection -no-cache -force-aaaa-soa
bind: 8888 -group cn
bind: 8889 -group us -exclude-default-group

server 223.5.5.5 -group AliDNS -exclude-default-group

nameserver /alipay.com/AliDNS
nameserver /aliyun.com.com/AliDNS
nameserver /taobao.com/AliDNS
nameserver /tmall.com/AliDNS
nameserver /xianyuso.com/AliDNS
nameserver /alibabacloud.com/AliDNS

server 119.29.29.29 -group DNSPod -exclude-default-group

nameserver /weixin.com/DNSPod
nameserver /qq.com/DNSPod
nameserver /jd.com/DNSPod
nameserver /qzoneapp.com/DNSPod
nameserver /qqgameapp.com/DNSPod
nameserver /qqopenapp.com/DNSPod
nameserver /pengyou.com/DNSPod

erver 180.76.76.76 -group Baidu -exclude-default-group

nameserver /baidu.com/Baidu

**Comment by jikkyfu** [comment]
> 解决国内DNS打群架问题
> server 223.5.5.5 -group AliDNS -exclude-default-group
> 
> nameserver /alipay.com/AliDNS
> nameserver /aliyun.com.com/AliDNS
> nameserver /taobao.com/AliDNS
> nameserver /tmall.com/AliDNS
> nameserver /xianyuso.com/AliDNS
> nameserver /alibabacloud.com/AliDNS
> nameserver /weibo.com/AliDNS
> nameserver /amap.com/AliDNS
> nameserver /uc.cn/AliDNS
> nameserver /1688.com/AliDNS
> nameserver /koubei.com/AliDNS
> nameserver /ele.me/AliDNS
> nameserver /alibaba.com/AliDNS
> nameserver /etao.com/AliDNS
> nameserver /fliggy.com/AliDNS
> nameserver /xiami.com/AliDNS
> nameserver /taopiaopiao.com/AliDNS
> nameserver /youku.com/AliDNS
> nameserver /dingtalk.com/AliDNS
> nameserver /cainiao.com/AliDNS
> nameserver /guoguo-app.com/AliDNS
> nameserver /tudou.com/AliDNS
> nameserver /mybank.cn/AliDNS
> 
> server 119.29.29.29 -group DNSPod -exclude-default-group
> 
> nameserver /weixin.com/DNSPod
> nameserver /qq.com/DNSPod
> nameserver /jd.com/DNSPod
> nameserver /qzoneapp.com/DNSPod
> nameserver /qqgameapp.com/DNSPod
> nameserver /qqopenapp.com/DNSPod
> nameserver /pengyou.com/DNSPod
> nameserver /tencent.com/DNSPod
> nameserver /sogou.com/DNSPod
> 
> server 180.76.76.76 -group Baidu -exclude-default-group
> 
> nameserver /baidu.com/Baidu
> nameserver /iqiyi.com/Baidu

大佬，你这个默认用的DNS不能包含在上述3家DNS吧。

**Comment by LsnmxNB** [comment]
> > 解决国内DNS打群架问题
> > server 223.5.5.5 -group AliDNS -exclude-default-group
> > nameserver /alipay.com/AliDNS
> > nameserver /aliyun.com.com/AliDNS
> > nameserver /taobao.com/AliDNS
> > nameserver /tmall.com/AliDNS
> > nameserver /xianyuso.com/AliDNS
> > nameserver /alibabacloud.com/AliDNS
> > nameserver /weibo.com/AliDNS
> > nameserver /amap.com/AliDNS
> > nameserver /uc.cn/AliDNS
> > nameserver /1688.com/AliDNS
> > nameserver /koubei.com/AliDNS
> > nameserver /ele.me/AliDNS
> > nameserver /alibaba.com/AliDNS
> > nameserver /etao.com/AliDNS
> > nameserver /fliggy.com/AliDNS
> > nameserver /xiami.com/AliDNS
> > nameserver /taopiaopiao.com/AliDNS
> > nameserver /youku.com/AliDNS
> > nameserver /dingtalk.com/AliDNS
> > nameserver /cainiao.com/AliDNS
> > nameserver /guoguo-app.com/AliDNS
> > nameserver /tudou.com/AliDNS
> > nameserver /mybank.cn/AliDNS
> > server 119.29.29.29 -group DNSPod -exclude-default-group
> > nameserver /weixin.com/DNSPod
> > nameserver /qq.com/DNSPod
> > nameserver /jd.com/DNSPod
> > nameserver /qzoneapp.com/DNSPod
> > nameserver /qqgameapp.com/DNSPod
> > nameserver /qqopenapp.com/DNSPod
> > nameserver /pengyou.com/DNSPod
> > nameserver /tencent.com/DNSPod
> > nameserver /sogou.com/DNSPod
> > server 180.76.76.76 -group Baidu -exclude-default-group
> > nameserver /baidu.com/Baidu
> > nameserver /iqiyi.com/Baidu
> 
> 大佬，你这个默认用的DNS不能包含在上述3家DNS吧。

 -exclude-default-group请好好读SM官方文档

**Comment by jikkyfu** [comment]
-exclude-default-group 这个是将服务器从默认组中排除，显然需要一个默认的DNS解析
楼上提到的 223.5.5.5，119.29.29.29，180.76.76.76 基本把国内第三方速度快的给囊括了。
如果用了上述这种配置，那么默认的是否需要设置成其它家的？反之是否就有被污染的风险？

我的理解是选一个你经常用的做默认，其它2个可以参考楼上的写法。

说的不一定对，请大佬指正下。

**Comment by LsnmxNB** [comment]
> -exclude-default-group 这个是将服务器从默认组中排除，显然需要一个默认的DNS解析
> 楼上提到的 223.5.5.5，119.29.29.29，180.76.76.76 基本把国内第三方速度快的给囊括了。
> 如果用了上述这种配置，那么默认的是否需要设置成其它家的？反之是否就有被污染的风险？
> 
> 我的理解是选一个你经常用的做默认，其它2个可以参考楼上的写法。
> 
> 说的不一定对，请大佬指正下。

默认的不要跟表上的一样就行了，不想排除默认就加-exclude-default-group ，以上除了百度DNS都有备用DNS

**Comment by jikkyfu** [comment]
感谢大佬解答

**Comment by smdx** [comment]
> 解决国内DNS打群架问题
> 每次一到重要节日国内DNS就开始打架
> 各自作死
> 把竞争对手的域名解析到国外
> 有时还打不开
> 一起收集完善国内几家喜欢用DNS打架家族的常用域名
> 字节跳动旗下没公共DNS，就不加入了，字节跳动公司也开始招人做公共DNS了，都是国内DNS打群架
> 2021.04.7更新
> 
> smartdns上游服务器
> <img alt="smartdns上游服务器" width="1485" src="https://user-images.githubusercontent.com/42826027/113815931-8b28bc00-97a6-11eb-9950-c5921b80bfe0.png">
> 
> 自定义设置
> 
> 测速模式选择
> Disable ipv6 address resolution
> force-AAAA-SOA yes
> 
> speed-check-mode ping,tcp:80
> 
> #example bind :7054 -group us -no-dualstack-selection -no-cache -force-aaaa-soa
> 
> bind: 8888 -group cn
> bind: 8889 -group us -exclude-default-group
> 
> #cnDoH-alidns
> #server 223.6.6.6 -group cnDoH-alidns -exclude-default-group
> #nameserver /[dns.alidns.com/cnDoH-alidns](dns.alidns.com/cnDoH-alidns)
> 
> #cnDoH-DNSPod
> server 119.29.29.29 -group cnDoH-DNSPod -exclude-default-group
> nameserver /doh.pub/cnDoH-DNSPod
> nameserver /dns.pub/cnDoH-DNSPod
> nameserver /dot.pub/cnDoH-DNSPod
> 
> #usDoH-Cloudflare
> #server 1.1.1.1 -group usDoH-Cloudflare -exclude-default-group
> #nameserver /[cloudflare-dns.com/usDoH-Cloudflare](cloudflare-dns.com/usDoH-Cloudflare)
> 
> #usDoH-Google
> server 8.8.8.8 -group usDoH-Google -exclude-default-group
> nameserver /dns.google/usDoH-Google
> 
> #server 223.5.5.5 -group AliDNS -exclude-default-group
> 
> server-https https://223.6.6.6/dns-query -group AliDNS -exclude-default-group
> 
> nameserver /[alipay.com/AliDNS](alipay.com/AliDNS)
> nameserver /[aliyun.com.com/AliDNS](aliyun.com.com/AliDNS)
> nameserver /[taobao.com/AliDNS](taobao.com/AliDNS)
> nameserver /[tmall.com/AliDNS](tmall.com/AliDNS)
> nameserver /[xianyuso.com/AliDNS](xianyuso.com/AliDNS)
> nameserver /[alibabacloud.com/AliDNS](alibabacloud.com/AliDNS)
> nameserver /[weibo.com/AliDNS](weibo.com/AliDNS)
> nameserver /[weibo.cn/AliDNS](weibo.cn/AliDNS)
> nameserver /[amap.com/AliDNS](amap.com/AliDNS)
> nameserver /[uc.cn/AliDNS](uc.cn/AliDNS)
> nameserver /[1688.com/AliDNS](1688.com/AliDNS)
> nameserver /[koubei.com/AliDNS](koubei.com/AliDNS)
> nameserver /ele.me/AliDNS
> nameserver /[alibaba.com/AliDNS](alibaba.com/AliDNS)
> nameserver /[etao.com/AliDNS](etao.com/AliDNS)
> nameserver /[fliggy.com/AliDNS](fliggy.com/AliDNS)
> nameserver /[xiami.com/AliDNS](xiami.com/AliDNS)
> nameserver /[taopiaopiao.com/AliDNS](taopiaopiao.com/AliDNS)
> nameserver /[youku.com/AliDNS](youku.com/AliDNS)
> nameserver /[dingtalk.com/AliDNS](dingtalk.com/AliDNS)
> nameserver /[cainiao.com/AliDNS](cainiao.com/AliDNS)
> nameserver /[guoguo-app.com/AliDNS](guoguo-app.com/AliDNS)
> nameserver /[tudou.com/AliDNS](tudou.com/AliDNS)
> nameserver /[mybank.cn/AliDNS](mybank.cn/AliDNS)
> nameserver /[cnzz.com/AliDNS](cnzz.com/AliDNS)
> nameserver /[umeng.com/AliDNS](umeng.com/AliDNS)
> nameserver /[alicdn.com/AliDNS](alicdn.com/AliDNS)
> nameserver /[tanx.com/AliDNS](tanx.com/AliDNS)
> nameserver /[mmstat.com/AliDNS](mmstat.com/AliDNS)
> nameserver /[ykimg.com/AliDNS](ykimg.com/AliDNS)
> nameserver /[sinaimg.cn/AliDNS](sinaimg.cn/AliDNS)
> nameserver /[sinajs.cn/AliDNS](sinajs.cn/AliDNS)
> nameserver /[meizu.cn/AliDNS](meizu.cn/AliDNS)
> nameserver /[meizu.com/AliDNS](meizu.com/AliDNS)
> nameserver /[mzres.com/AliDNS](mzres.com/AliDNS)
> nameserver /[aliyuncs.com/AliDNS](aliyuncs.com/AliDNS)
> nameserver /[ucweb.com/AliDNS](ucweb.com/AliDNS)
> nameserver /[flyme.cn/AliDNS](flyme.cn/AliDNS)
> nameserver /[flyme.com/AliDNS](flyme.com/AliDNS)
> nameserver /[aliyuncs.com/AliDNS](aliyuncs.com/AliDNS)
> nameserver /[sina.cn/AliDNS](sina.cn/AliDNS)
> nameserver /[weibocdn.com/AliDNS](weibocdn.com/AliDNS)
> 
> #server 119.29.29.29 -group DNSPod -exclude-default-group
> 
> server-https https://doh.pub/dns-query -group DNSPod -exclude-default-group
> 
> nameserver /[weixin.com/DNSPod](weixin.com/DNSPod)
> nameserver /[qq.com/DNSPod](qq.com/DNSPod)
> nameserver /[qzoneapp.com/DNSPod](qzoneapp.com/DNSPod)
> nameserver /[qqgameapp.com/DNSPod](qqgameapp.com/DNSPod)
> nameserver /[qqopenapp.com/DNSPod](qqopenapp.com/DNSPod)
> nameserver /[pengyou.com/DNSPod](pengyou.com/DNSPod)
> nameserver /[tencent.com/DNSPod](tencent.com/DNSPod)
> nameserver /[sogou.com/DNSPod](sogou.com/DNSPod)
> nameserver /[maoyan.com/DNSPod](maoyan.com/DNSPod)
> nameserver /[gtimg.com/DNSPod](gtimg.com/DNSPod)
> nameserver /[qpic.cn/DNSPod](qpic.cn/DNSPod)
> nameserver /[sogoucdn.com/DNSPod](sogoucdn.com/DNSPod)
> nameserver /[qlogo.cn/DNSPod](qlogo.cn/DNSPod)
> nameserver /[gtimg.cn/DNSPod](gtimg.cn/DNSPod)
> nameserver /[gdtimg.com/DNSPod](gdtimg.com/DNSPod)
> 
> server 180.76.76.76 -group Baidu -exclude-default-group
> 
> nameserver /[baidu.com/Baidu](baidu.com/Baidu)
> nameserver /[iqiyi.com/Baidu](iqiyi.com/Baidu)
> nameserver /[baidupcs.com/Baidu](baidupcs.com/Baidu)
> nameserver /[bdstatic.com/Baidu](bdstatic.com/Baidu)
> nameserver /[91.com/Baidu](91.com/Baidu)
> nameserver /[iqiyipic.com/Baidu](iqiyipic.com/Baidu)
> nameserver /[bdimg.com/Baidu](bdimg.com/Baidu)
> nameserver /[baifubao.com/Baidu](baifubao.com/Baidu)
> nameserver /qingting.fm/Baidu
> nameserver /[duxiaoman.com/Baidu](duxiaoman.com/Baidu)
> nameserver /[qy.net/Baidu](qy.net/Baidu)
> nameserver /[bcebos.com/Baidu](bcebos.com/Baidu)
> 
> #server 8.8.4.4 -group Google -exclude-default-group
> 
> server-https https://dns.google/dns-query -group Google -exclude-default-group
> 
> nameserver /[googleusercontent.com/Google](googleusercontent.com/Google)
> nameserver /[gvt1.com/Google](gvt1.com/Google)
> nameserver /[google.com/Google](google.com/Google)
> nameserver /[youtube.com/Google](youtube.com/Google)
> nameserver /[waze.com/Google](waze.com/Google)
> nameserver /blog.youtube/Google
> nameserver /[tiltbrush.com/Google](tiltbrush.com/Google)
> nameserver /[android.com/Google](android.com/Google)
> nameserver /[gstatic.com/Google](gstatic.com/Google)
> nameserver /[ytimg.com/Google](ytimg.com/Google)
> nameserver /[ggpht.com/Google](ggpht.com/Google)
> nameserver /[googleapis.com/Google](googleapis.com/Google)
> nameserver /[googlevideo.com/Google](googlevideo.com/Google)
> nameserver /[doubleclick.net/Google](doubleclick.net/Google)
> nameserver /[lra8j.com/Google](lra8j.com/Google)
> nameserver /[measurement.com/Google](measurement.com/Google)
> nameserver /[fonts.loli.net/Google](fonts.loli.net/Google)
> 
> # 去广告文件，去掉#就可以使用自带去广告的文件了，也可以自己上传。
> # conf-file /etc/smartdns/anti-ad-smartdns.conf

感谢分享，反馈个问题：使用以上自定义后发现 server 180.76.76.76 -group Baidu这组规则会导致百度贴吧首页图片不显示、百度首页顶栏那里的百度视频点进去页面载入不正常。删除这条规则所有内容后相关页面就没问题了。

**Comment by 7xanthus** [comment]
> 解决国内DNS打群架问题 每次一到重要节日国内DNS就开始打架 各自作死 把竞争对手的域名解析到国外 有时还打不开 一起收集完善国内几家喜欢用DNS打架家族的常用域名 字节跳动旗下没公共DNS，就不加入了，字节跳动公司也开始招人做公共DNS了，都是国内DNS打群架 2021.04.7更新
> 
> smartdns上游服务器 <img alt="smartdns上游服务器" width="1485" src="https://user-images.githubusercontent.com/42826027/113815931-8b28bc00-97a6-11eb-9950-c5921b80bfe0.png">
> 
> 自定义设置
> 
> 测速模式选择 Disable ipv6 address resolution force-AAAA-SOA yes
> 
> speed-check-mode ping,tcp:80
> 
> #example bind :7054 -group us -no-dualstack-selection -no-cache -force-aaaa-soa
> 
> bind: 8888 -group cn bind: 8889 -group us -exclude-default-group
> 
> #cnDoH-alidns #server 223.6.6.6 -group cnDoH-alidns -exclude-default-group #nameserver /dns.alidns.com/cnDoH-alidns
> 
> #cnDoH-DNSPod server 119.29.29.29 -group cnDoH-DNSPod -exclude-default-group nameserver /doh.pub/cnDoH-DNSPod nameserver /dns.pub/cnDoH-DNSPod nameserver /dot.pub/cnDoH-DNSPod
> 
> #usDoH-Cloudflare #server 1.1.1.1 -group usDoH-Cloudflare -exclude-default-group #nameserver /cloudflare-dns.com/usDoH-Cloudflare
> 
> #usDoH-Google server 8.8.8.8 -group usDoH-Google -exclude-default-group nameserver /dns.google/usDoH-Google
> 
> #server 223.5.5.5 -group AliDNS -exclude-default-group
> 
> server-https https://223.6.6.6/dns-query -group AliDNS -exclude-default-group
> 
> nameserver /alipay.com/AliDNS nameserver /aliyun.com.com/AliDNS nameserver /taobao.com/AliDNS nameserver /tmall.com/AliDNS nameserver /xianyuso.com/AliDNS nameserver /alibabacloud.com/AliDNS nameserver /weibo.com/AliDNS nameserver /weibo.cn/AliDNS nameserver /amap.com/AliDNS nameserver /uc.cn/AliDNS nameserver /1688.com/AliDNS nameserver /koubei.com/AliDNS nameserver /ele.me/AliDNS nameserver /alibaba.com/AliDNS nameserver /etao.com/AliDNS nameserver /fliggy.com/AliDNS nameserver /xiami.com/AliDNS nameserver /taopiaopiao.com/AliDNS nameserver /youku.com/AliDNS nameserver /dingtalk.com/AliDNS nameserver /cainiao.com/AliDNS nameserver /guoguo-app.com/AliDNS nameserver /tudou.com/AliDNS nameserver /mybank.cn/AliDNS nameserver /cnzz.com/AliDNS nameserver /umeng.com/AliDNS nameserver /alicdn.com/AliDNS nameserver /tanx.com/AliDNS nameserver /mmstat.com/AliDNS nameserver /ykimg.com/AliDNS nameserver /sinaimg.cn/AliDNS nameserver /sinajs.cn/AliDNS nameserver /meizu.cn/AliDNS nameserver /meizu.com/AliDNS nameserver /mzres.com/AliDNS nameserver /aliyuncs.com/AliDNS nameserver /ucweb.com/AliDNS nameserver /flyme.cn/AliDNS nameserver /flyme.com/AliDNS nameserver /aliyuncs.com/AliDNS nameserver /sina.cn/AliDNS nameserver /weibocdn.com/AliDNS
> 
> #server 119.29.29.29 -group DNSPod -exclude-default-group
> 
> server-https https://doh.pub/dns-query -group DNSPod -exclude-default-group
> 
> nameserver /weixin.com/DNSPod nameserver /qq.com/DNSPod nameserver /qzoneapp.com/DNSPod nameserver /qqgameapp.com/DNSPod nameserver /qqopenapp.com/DNSPod nameserver /pengyou.com/DNSPod nameserver /tencent.com/DNSPod nameserver /sogou.com/DNSPod nameserver /maoyan.com/DNSPod nameserver /gtimg.com/DNSPod nameserver /qpic.cn/DNSPod nameserver /sogoucdn.com/DNSPod nameserver /qlogo.cn/DNSPod nameserver /gtimg.cn/DNSPod nameserver /gdtimg.com/DNSPod
> 
> server 180.76.76.76 -group Baidu -exclude-default-group
> 
> nameserver /baidu.com/Baidu nameserver /iqiyi.com/Baidu nameserver /baidupcs.com/Baidu nameserver /bdstatic.com/Baidu nameserver /91.com/Baidu nameserver /iqiyipic.com/Baidu nameserver /bdimg.com/Baidu nameserver /baifubao.com/Baidu nameserver /qingting.fm/Baidu nameserver /duxiaoman.com/Baidu nameserver /qy.net/Baidu nameserver /bcebos.com/Baidu
> 
> #server 8.8.4.4 -group Google -exclude-default-group
> 
> server-https https://dns.google/dns-query -group Google -exclude-default-group
> 
> nameserver /googleusercontent.com/Google nameserver /gvt1.com/Google nameserver /google.com/Google nameserver /youtube.com/Google nameserver /waze.com/Google nameserver /blog.youtube/Google nameserver /tiltbrush.com/Google nameserver /android.com/Google nameserver /gstatic.com/Google nameserver /ytimg.com/Google nameserver /ggpht.com/Google nameserver /googleapis.com/Google nameserver /googlevideo.com/Google nameserver /doubleclick.net/Google nameserver /lra8j.com/Google nameserver /measurement.com/Google nameserver /fonts.loli.net/Google
> 
> # 去广告文件，去掉#就可以使用自带去广告的文件了，也可以自己上传。
> # conf-file /etc/smartdns/anti-ad-smartdns.conf

bind: 8889 -group us -exclude-default-group

这条配置的-exclude-default-group有啥用？
