### ISSUE TITLE
希望在domain-rules参数后增加双栈优选开关

### ISSUE THREAD

**Issue by phoenixxie7** [pymumu/smartdns#657]
**需求应用场景**
希望在domain-rules参数后增加双栈优选开关，用于解决针对某些域名的分流。

**建议的方案**
domain-rules增加针对双栈的优选开关，可以解决国内使用henet的V6隧道带来的问题。

**Comment by pymumu** [comment]
最新代码已经增加，可以获取验证。
参数为domain-rule /xxx.com/ -d [yes|no]
