### ISSUE TITLE
大佬，域名TTL 域名TTL最小值 域名TTL最大值，这三个值的设定实在是迷糊

### ISSUE THREAD

**Issue by ywyha** [pymumu/smartdns#658]
我实在是搞不懂这几个值的大小的具体区别……
比如开启预加载，看大佬说过TTL过期前5秒刷新，那么TTL过期与这几个哪个数值有关系，又比如说再同时开启缓存过期，拿又跟哪个值有关系……
好用的工具却不知道怎样来良好的设定，太纠结了，大佬，求助……

**Comment by ywyha** [comment]
明明都有域名TTL了，那设定最小值和最大值又有什么额外的影响……迷糊

**Comment by cnommo-star** [comment]
这个都是用来控制返回给客户端的ttl时间的
1. 域名TTL，是不管上游返回的TTL多少， 都改成这个值
2.域名TTL最小值 域名TTL最大值， 是如果上游的TTL不在这个范围，则最小调整到域名最小TTL， 最大调整到域名最大TTL

**Comment by ywyha** [comment]
> 这个都是用来控制返回给客户端的域名记录ttl时间的
> 
> 1. 域名TTL，是不管上游返回的TTL多少， 都改成这个值（这个优先）
> 2. 域名TTL最小值 域名TTL最大值， 是如果上游的TTL不在这个范围，则最小调整到域名最小TTL， 最大调整到域名最大TTL
> 3. 开启expire-ttl后，缓存内容，ttl到期不会删除，如有域名请求，则仍先返回过期的这个记录，但ttl会调整到提及的5s（因为给的是失效信息）， 然后会立刻进行预取，避免cache信息过旧。
> 4. 目前代码有bug，一旦当次预取失败，如超时，则预取中断失败（不开启expire-cache）， 即便预取次数还有很多。

真的很感谢，这么详细的耐心解答，谢谢大佬，可是因为实在是太小白的关系，对于域名TTL最小和最大值与TTL值的关系还是似懂非懂。

大佬，打个比方，我这么设定，域名TTL设定为300，最小TTL设置为600，最大ttl1200，一旦采用这种设定后，smartdns服务下的客户端设备访问一个域名得到的解析生存时间是否为300？也就是说一旦三个值都设定了，后两个值是不产生作用的？

如果域名TTL不设置，只设定最小TTL和最大TTL，那么客户端得到的TTL值是否在最小和最大TTL范围内随机？如果不随机，smartdns是根据什么给出客户端获得的最小和最大TTL范围内的数值的？比如根据系统负载？或者是其他什么的?

因为我实在是太小白了……我不知道我上述说的话逻辑是否表达正确，还是我又理解错了……（小白的痛苦），在这之前我连TTL是啥都没听过……

最后再次谢谢大佬的打了这么多字解答，感谢

**Comment by cnommo-star** [comment]
域名TTL设定为300，则无论上游返回多少TTL，给客户端的响应都是300
如果域名TTL没有设置， 而最小TTL设置为600，最大ttl1200， 则上游的ttl小于600， 调成600，大于1200，调成1200，其他不变

**Comment by ywyha** [comment]
> 首先smartdns 去上游解析域名是有上游给的ttl的，这是dns的规范。而这个ttl在smartdns给客户端的时候可以被调整
> 
> 域名TTL设定为300，则无论上游返回多少TTL，给客户端的响应都是300
> 如果域名TTL没有设置， 而最小TTL设置为600，最大ttl1200， 则上游的ttl小于600， 调成600，大于1200，调成1200，其他不变
> 
> 最大最小就是一个范围限定的要求，不能越过这个范围，越过就取边界
> if a>max a=max; if a<min a=min

完全懂了，感谢大佬对小白的帮助，一百个赞给你，真的非常感谢大佬解惑。

**Comment by aogg** [comment]
那么如何指定特定域名的ttl，甚至包含旗下子域名

**Comment by yuxuan0107** [comment]
> 首先smartdns 去上游解析域名是有上游给的ttl的，这是dns的规范。而这个ttl在smartdns给客户端的时候可以被调整
> 
> 域名TTL设定为300，则无论上游返回多少TTL，给客户端的响应都是300 如果域名TTL没有设置， 而最小TTL设置为600，最大ttl1200， 则上游的ttl小于600， 调成600，大于1200，调成1200，其他不变
> 
> 最大最小就是一个范围限定的要求，不能越过这个范围，越过就取边界 if a>max a=max; if a<min a=min

感谢你的解释
