### ISSUE TITLE
又双叒叕自动关闭了

### ISSUE THREAD

**Issue by cjameslynn** [pymumu/smartdns#66]
**问题现象**  
自动关闭

**运行环境**
1. LEDE X64
2. 电信、移动、ipv6 

**重现步骤**
1. 自动关闭  

**信息收集**  
[Desktop.zip](https://github.com/pymumu/smartdns/files/2776488/Desktop.zip)

**Comment by pymumu** [comment]
先确认：
    是否是正式的Release 18，因为正式Release 18的话，进程异常是会自动拉起的。不会有smartdns不服务的问题，也就是正式的Release 18不应该出现进程自动关闭不再启动的情况。
    看一下：`cat /etc/init.d/smartdns  | grep ^RESPAWN`输出的结果。
    正式版本，这里是RESPAWN="1"，表示进程异常自动重启。 

如果上述确认是Release 18的正式版本，那么请再看：
是否使用了koolshare软件中心的v2ray？
v2ray里面前面有人反馈过此问题，v2ray集成的smartdns和openwrt的安装版本冲突了。v2ray断开的时候，会杀掉smartdns，后面我看看和v2ray插件的作者了解一下情况。

**Comment by cjameslynn** [comment]
是18的，
Using username "root".


BusyBox v1.29.3 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 Openwrt Koolshare mod V2.26, r9768-c8eea3fdd1 by fw867
 -----------------------------------------------------
root@Openwrt:~# cat /etc/init.d/smartdns | grep ^RESPAWN
RESPAWN="1"
root@Openwrt:~#

**Comment by cjameslynn** [comment]
我知道v2ray的问题
