### ISSUE TITLE
无法访问本机ip

### ISSUE THREAD

**Issue by heheda2033** [pymumu/smartdns#661]
**问题现象**  
简要描述问题出现的现象
设置好端口转发后，局域网机器，无法通过IP地址+端口号访问内网设备
如手机只能开4g才能连接nas，开启smartdns 后，出现这个问题，且无法通过关闭smartdns解决问题

**运行环境**
1. 固件型号  

2019.12.15-2

2. 运营商  

电信

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
看你的转发规则吧，smartdns如果配置了转发，也只会转发udp请求。不会对tcp，上网有影响。
