### ISSUE TITLE
关于返回多IP的建议

### ISSUE THREAD

**Issue by supppig** [pymumu/smartdns#662]
**需求应用场景**
使用迅雷等多线程下载工具，希望提高下载速度。

**建议的方案**
对于一个域名对应多个IP的情况，希望能设置一个阈值N，若测速结果为最小值是A，则响应时间在范围A+N内的IP，均返回（而不是返回唯一最快的IP）。这样能避免迅雷多线程时，请求的是同一个IP，导致下载速度慢甚至服务器限制并发的问题。

**设备信息**
1. R2S ARMv8
2. newifi D2 mipsel

2. 固件信息
lede

**Comment by LsnmxNB** [comment]
目前局域网使用SM多用户，最好关了测速功能，要不然哪连接数直接炸了

**Comment by LsnmxNB** [comment]
@pymumu 大佬有空解决下迅雷等多线程下载工具导致并发过多问题

**Comment by pymumu** [comment]
有方案，但目前没时间开发
方案是开启serve-expired后，可以返回多ip
现在要修改
1.dns回应包支持多ip
2.多IP请求测速

可能有500行代码

**Comment by LsnmxNB** [comment]
> 有方案，但目前没时间开发
> 方案是开启serve-expired后，可以返回多ip
> 现在要修改
> 1.dns回应包支持多ip
> 2.多IP请求测速
> 
> 可能有500行代码

好的，有时间再折腾不是吹大佬你，迅雷，视频网站客户端等P2P很烦恼返回太多IP，SM就补长期占用搞得整个局域网的DSN别的设备都反就不过来了

**Comment by LsnmxNB** [comment]
> 有方案，但目前没时间开发
> 方案是开启serve-expired后，可以返回多ip
> 现在要修改
> 1.dns回应包支持多ip
> 2.多IP请求测速
> 
> 可能有500行代码

大佬这个功能，Release 35 有了吗？如何开启，文档没有啊

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
