### ISSUE TITLE
Hope upgrade.

### ISSUE THREAD

**Issue by jkle112** [pymumu/smartdns#663]
The smartdns codes is update,hope releases upgrade .
Hope force enable ENSI and DNSSEC!

I hope that, like Shareaza, different networks can be used to bypass the blockade, so that ESNI can be forcibly turned on.

Shareaza can connect to up to 4 separate Peer-to-Peer networks, providing access to hundreds of thousands of diverse users, all from one single program. You can download/upload from these networks: EDonkey2000, Gnutella, BitTorrent and Gnutella2 (G2).

It is best to use high-strength special encryption rules to prevent being blocked by surveillance.

Openwrt X64 ,openwrt within Gl-inet mv1000w/Linksys wrt1900ac v1
Thank you!

**Comment by pymumu** [comment]
ESNI's RFC is still in draft status, but I will look at the draft content.

**Comment by jkle112** [comment]
Maybe you could used the ESNI's RFC for security.
https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by Jiew-KueJwiaeng** [comment]
> ESNI's RFC is still in draft status, but I will read the draft.
ECH (Encrypted Client Hello) is now available in Chrome Canary (chrome://flags/#encrypted-client-hello). Hopefully SmartDNS will be adapted as well.
ECH (Encrypted Client Hello)现已能在Chrome Canary中启用 (chrome://flags/#encrypted-client-hello)。希望SmartDNS也能得到适配。
