### ISSUE TITLE
我家使用smartdns经常莫名奇妙自动停止运行，各位大佬有遇到这个情况吗？

### ISSUE THREAD

**Issue by wuchen4588** [pymumu/smartdns#664]
我家smartdns经常停止运行，倒是再次重启可以正常使用。各位大佬请问这个问题如何解决。

**Comment by PinkyStaRrrr** [comment]
不知道是不是google doh的问题

**Comment by wuchen4588** [comment]
> 不知道是不是google doh的问题

程序上的错误跟Google家的DNS有的问题？？？？

**Comment by zgc** [comment]
我这几天也遇到了，等下一次出问题，再导日志

**Comment by shenlanAZ** [comment]
每周都会遇到

**Comment by jkle112** [comment]
每天都碰到这样的问题，要手动开启，结果又莫名的关闭了，考虑再三提了升级的建议。
https://github.com/pymumu/smartdns/issues/663

**Comment by ShureCool** [comment]
建议你检查一下设置，我之前也碰到过，是自定义参数里面符号有问题，出错了

**Comment by pymumu** [comment]
看一下smartdns的log，看看是否是代码crash，还是配置错误，还是端口被占用了。

**Comment by jkle112** [comment]
代碼更新了，不過還沒有推出升級版本。
希望可以像Shareaza利用 4 種不同的P2P網絡： EDonkey2000, Gnutella, BitTorrent and Gnutella2 (G2)，
來提供聯通性能和安全，或者獨特的高强度加密來提供保護和防護。
