### ISSUE TITLE
求助7621A的CPU是用mips还是mipsel啊？怎样判断……

### ISSUE THREAD

**Issue by ywyha** [pymumu/smartdns#665]
我在网上查CPU架构是MIPS1004Kc

但是软件源里有mipsel_24kc，还有ramips

我蒙圈了，怎样判断安装哪个……

**Comment by rampageX** [comment]
MediaTek MT7621A Wi-Fi SoC contains a powerful 880 MHz `MIPS®` 1004KEc™ dual-core CPU

https://www.mediatek.com/products/homeNetworking/mt7621

**Comment by pymumu** [comment]
直接使用mips的静态编译包即可。

**Comment by a892728** [comment]
MT7621 要選mipsel的
https://blog.hackpascal.net/2019/10/debian-for-mt7621-%E6%8A%98%E8%85%BE%E8%AE%B0-3-%E7%BC%96%E8%AF%91-debian-kernel-package/

**Comment by nidbCN** [comment]
赞成 @a892728 的说法，经过测试，mips 版本的无法运行

```
root@openwrt-router:~# /usr/sbin/smartdns
/usr/sbin/smartdns: line 1: syntax error: unexpected "("
```

我在网上抱着试试看的心态，发现有人错把 mipsel 的编译成 mips 才这样，然后使用了 Mipsel 架构的包，正常运行
