### ISSUE TITLE
smartdns 日常使用两个问题

### ISSUE THREAD

**Issue by JunTsao** [pymumu/smartdns#666]
设备：openwrt X86

问题1：
请问openwrt X86如何查看日志？
/var/log/下并没有日志文件，手动配置：log-file /tmp/smartdns.log也无法生成日志文件

问题2：
接入线路：广东电信
拓扑：猫-smartdns - openclash - adghome，adg负责劫持
DNS配置：
bind :6053
bind-tcp :6053
bind :5335  -group guowai
bind-tcp :5335  -group guowai
server 114.114.114.114  -blacklist-ip -check-edns
server-tls dns.pub:853  -blacklist-ip -check-edns
server-https https://doh.pub/dns-query  -group china -exclude-default-group
server-https https://223.5.5.5/dns-query  -group china -exclude-default-group
server-tls 8.8.4.4:853  -group guowai -exclude-default-group -host-name dns.google
server-tls 1.1.1.1:853  -group guowai -exclude-default-group -host-name 1dot1dot1dot1.cloudflare-dns.com
server-https https://dns.twnic.tw/dns-query  -group guowai -exclude-default-group

以上是tmp/etc内复制的配置
如在LUCI界面配置为：
force-AAAA-SOA yes
speed-check-mode tcp:443,tcp:80,ping
serve-expired yes
bind: 6053 -group china
bind: 5335 -group guowai
prefetch-domain yes
log-file /tmp/smartdns.log

目前发现如抖音、微博图床解析到了联通IP上，导致连接效果并不理想
请问我配置是否有错？还请作者指点一二，不胜感激！

**Comment by pymumu** [comment]
checkedns不用对国内设置，会导致国内解析失效。
没日志输出，是因为默认是ERROR日志，修改log-level为info可看到运行日志。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
