### ISSUE TITLE
domain-rules conf-file 有限制

### ISSUE THREAD

**Issue by sammimk830** [pymumu/smartdns#667]
**问题现象**  
我在用domain-rules的時候發現到了16220行就會讀不下去的，麻煩看一下是否有數量限制的呢。謝謝﹗

**运行环境**
1. DOCKER  

2. 中國電信 

**重现步骤**
我是用这個CHINA LIST去設定domain-rules，因為發現在dns group里並不能設定測速，但在用到國外的DNS時，是不能用上測速的，所以我只能把測速關掉，在每一個DOMAIN用domain-rules來開測速了
https://github.com/felixonmars/dnsmasq-china-list
 

**信息收集**  
![image](https://user-images.githubusercontent.com/34807325/103462969-e42a2380-4d63-11eb-8e9c-5b953ce94dc4.png)

**Comment by pymumu** [comment]
没有数量限制，看16220行的内容是什么？

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
