### ISSUE TITLE
在dns group設定曾加是否返回IPV6和測速

### ISSUE THREAD

**Issue by sammimk830** [pymumu/smartdns#668]
**需求应用场景**
我們現在通常會有GFW或者是類似這種的LIST用來分別去不同的DNS GROUP取得IP地址，例如如果是國內的，是可以測速和取得IPV6的IP的，但國外的就不能測速和用到IPV6了，這是太多速情況吧。但是如果要一個SMARTDNS以現在我知道的設定是不能用GROUP來設定IPV6和測速的開關，我只知道要用上BIND在不同的端口上才能實現測速和IPV6的開關，這樣的話就要一定用上dnsmasq 來實現分開不同的端口去取，如果能在DNS GROUP的設定加上這兩個功能，那就不用靠第三方的DNS來分流了。謝謝﹗

**建议的方案**
在dns group設定曾加是否返回IPV6和測速

**Comment by pymumu** [comment]
使用domain rule和-speed-check-mode参数。
