### ISSUE TITLE
整理了一个dns污染列表，但是会导致大部分A记录无法解析

### ISSUE THREAD

**Issue by ziyuedi** [pymumu/smartdns#67]
**问题现象**  
整理了一个dns污染列表
[smartdns.zip](https://github.com/pymumu/smartdns/files/2786124/smartdns.zip)
**运行环境**
1. 固件型号  
树莓派2b，已apt-get upgrade到最新版，内核版本Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
2. 运营商  
山西移动
**重现步骤**
1. 上游DNS配置。  
server 2409:800c:2000::2 -blacklist-ip
server-tcp 119.29.29.29 -check-edns -blacklist-ip
server 114.114.114.114 -blacklist-ip
server 180.76.76.76 -check-edns -blacklist-ip
server 2400:da00::6666 -check-edns -blacklist-ip
server 223.5.5.5 -blacklist-ip
server-tcp 1.2.4.8 -check-edns -blacklist-ip
server 101.226.4.6 -blacklist-ip
server-tcp 202.141.178.13:5353 -check-edns
server-tcp 101.6.6.6:5353 -check-edns
server-tcp 2001:da8::666 -check-edns
server-tcp 211.138.106.2 -check-edns
server-tcp 208.67.222.222:5353 -check-edns
server-tcp [2620:0:ccc::2]:5353 -check-edns
server-tcp 4.2.2.2 -check-edns
server-tcp 101.101.101.101 -check-edns
server-tcp 2001:de4::101 -check-edns
server-tcp 185.121.177.177:5353 -check-edns
server-tcp 2a05:dfc7:5::53 -check-edns
server-tcp 80.80.80.80 -check-edns
server-tcp 64.6.64.6 -check-edns
server-tcp 240c::6666 -check-edns
server-tcp 2001:500:2f::f -check-edns
server-tls ea-dns.rubyfish.cn
server-tls dns.google
server-tls 1.1.1.1
server-tls 2606:4700:4700::1111
server-tls 9.9.9.9
server-tls 2620:fe::fe
（好像有些没必要）。。。
2. 访问的域名。  
dig @树莓派IP baidu.com 
等等
**信息收集**  
1. 
[smartdns.log](https://github.com/pymumu/smartdns/files/2786138/smartdns.log)

**Comment by pymumu** [comment]
bogus-nxdomain配置是过滤上游的，主要是避免运营商在访问无效域名时的劫持。不用做防污染。
所以bogus-nxdomain一般都不配置。

另外，-check-edns和-blacklist-ip两个server参数用途：
-check-edns用于国外DNS服务器，GFW的污染过滤，所以只在国外DNS上增加，比如8.8.8.8。
-blacklist-ip用于国内DNS服务器，过滤GFW的二次污染返回的错误地址，比如114

-check-edns只对UDP生效。

另外，你的配置我验证了一下，都是能正确返回地址的。
移动的话，UDP的估计全军覆没了 ，如果A地址都没有任何结果，就说明被过滤完了所有地址了。
我没移动不好验证，你可以用ping检查一下dns服务器的响应速度，小于5ms的，基本判断被移动劫持了。
配置再多也没用，移动用tcp，tls可能会好一点。

**Comment by ziyuedi** [comment]
除了其中运营商的dns外，没有一个小于5s
Best trace测路由，结果也都正常
dig结果：
user@NOTEBOOK:~$ dig @180.76.76.76 baidu.com

; <<>> DiG 9.10.3-P4-Debian <<>> @180.76.76.76 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21848
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              288     IN      A       123.125.115.110
baidu.com.              288     IN      A       220.181.57.216

;; Query time: 19 msec
;; SERVER: 180.76.76.76#53(180.76.76.76)
;; WHEN: Thu Jan 24 17:58:28 DST 2019
;; MSG SIZE  rcvd: 70
user@NOTEBOOK:~$ dig @223.5.5.5 baidu.com

; <<>> DiG 9.10.3-P4-Debian <<>> @223.5.5.5 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51840
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              131     IN      A       220.181.57.216
baidu.com.              131     IN      A       123.125.115.110

;; Query time: 60 msec
;; SERVER: 223.5.5.5#53(223.5.5.5)
;; WHEN: Thu Jan 24 17:59:03 DST 2019
;; MSG SIZE  rcvd: 59
user@NOTEBOOK:~$ dig @1.1.1.1 baidu.com

; <<>> DiG 9.10.3-P4-Debian <<>> @1.1.1.1 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20782
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              368     IN      A       123.125.115.110
baidu.com.              368     IN      A       220.181.57.216

;; Query time: 51 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Jan 24 17:59:25 DST 2019
;; MSG SIZE  rcvd: 70
user@NOTEBOOK:~$ dig @8.8.8.8 baidu.com

; <<>> DiG 9.10.3-P4-Debian <<>> @8.8.8.8 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2382
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              113     IN      A       123.125.115.110
baidu.com.              113     IN      A       220.181.57.216

;; Query time: 208 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jan 24 17:59:37 DST 2019
;; MSG SIZE  rcvd: 70
user@NOTEBOOK:~$ dig @9.9.9.9 baidu.com +tcp

; <<>> DiG 9.10.3-P4-Debian <<>> @9.9.9.9 baidu.com +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19955
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              600     IN      A       123.125.115.110
baidu.com.              600     IN      A       220.181.57.216

;; Query time: 609 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Thu Jan 24 18:00:09 DST 2019
;; MSG SIZE  rcvd: 70

user@NOTEBOOK:~$ dig @80.80.80.80 baidu.com +tcp

; <<>> DiG 9.10.3-P4-Debian <<>> @80.80.80.80 baidu.com +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12704
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              191     IN      A       220.181.57.216
baidu.com.              191     IN      A       123.125.115.110

;; Query time: 107 msec
;; SERVER: 80.80.80.80#53(80.80.80.80)
;; WHEN: Thu Jan 24 18:00:16 DST 2019
;; MSG SIZE  rcvd: 70
user@NOTEBOOK:~$ dig @2620:0:ccc::2 -p 5353 baidu.com

; <<>> DiG 9.10.3-P4-Debian <<>> @2620:0:ccc::2 -p 5353 baidu.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64293
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;baidu.com.                     IN      A

;; ANSWER SECTION:
baidu.com.              298     IN      A       123.125.115.110
baidu.com.              298     IN      A       220.181.57.216

;; Query time: 105 msec
;; SERVER: 2620:0:ccc::2#5353(2620:0:ccc::2)
;; WHEN: Thu Jan 24 18:01:09 DST 2019
;; MSG SIZE  rcvd: 70
user@NOTEBOOK:~$ dig @8.8.8.8 ipv6.baidu.com +tcp

; <<>> DiG 9.10.3-P4-Debian <<>> @8.8.8.8 ipv6.baidu.com +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52145
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ipv6.baidu.com.                        IN      A

;; ANSWER SECTION:
ipv6.baidu.com.         7199    IN      A       220.181.57.217
ipv6.baidu.com.         7199    IN      A       111.13.101.208
ipv6.baidu.com.         7199    IN      A       123.125.114.144
ipv6.baidu.com.         7199    IN      A       220.181.57.216

;; Query time: 433 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Jan 24 18:01:29 DST 2019
;; MSG SIZE  rcvd: 107

**Comment by pymumu** [comment]
你最好先少配置几个服务器，一个一个测试下，配置多了不知道哪些出问题。
-check-edns不是所有上游都支持的，配置不正确，就会导致解析失败。

**Comment by ziyuedi** [comment]
就是bogus-nxdomain杀伤面积太广了。。。
全部去掉后正常

**Comment by ziyuedi** [comment]
![default](https://user-images.githubusercontent.com/24859058/51730271-ce108480-20b1-11e9-8bb9-6d4c6b24ff15.png)
什么情况？bug？
[smartdns.log](https://github.com/pymumu/smartdns/files/2794965/smartdns.log)

**Comment by pymumu** [comment]
双栈优选在Release 18还有问题，即将发布的Release 19已经解决

**Comment by pymumu** [comment]
IPV4你不也配置了bogus-nxdomain吗？

IPV4，IPV6是完全独立的两套过滤机制

**Comment by ziyuedi** [comment]
不，在去掉ipv6的bogus-nxdomain后ipv4，v6都解析正常

**Comment by ziyuedi** [comment]
已确认，导致问题的是
```
#bogus-nxdomain 4000::/3
#bogus-nxdomain 6000::/3
#bogus-nxdomain 8000::/3
#bogus-nxdomain C000::/3
```
这几条规则
如果不注释掉这几条规则，更新19版后问题依然存在

**Comment by ziyuedi** [comment]
还有ignore-ip，blacklist-ip和bogus-nxdomain实现上有什么区别

**Comment by pymumu** [comment]
ignore-ip是将结果中的IP丢弃，但其他IP依然有效，主要用于smartdns检测错误。比如某个IP虽然速度快，但有超时的情况。
blacklist-ip主要是过滤国内二次污染的域名，比如到114查询google，这时的IP是污染的，114的这个结果包含了污染范围的IP，那整个结果是直接丢弃的。这个要配合-blacklist-ip参数使用。
bogus-nxdomain主要是过滤运营商的广告IP，比如访问一个不存在的域名，运营商会重定向到广告页面。这时就这个，这个不能用来做污染过滤，这个会全局生效。

**Comment by ziyuedi** [comment]
ipv6过滤规则影响ipv4的bug能不能看看

**Comment by pymumu** [comment]
bogus-nxdomain 4000::/3
配置这个原因时什么？

**Comment by pymumu** [comment]
没改几行代码，临时给你个测试版本吧。

[smartdns.1.2019.01.26-2340.armhf.deb.zip](https://github.com/pymumu/smartdns/files/2799161/smartdns.1.2019.01.26-2340.armhf.deb.zip)

**Comment by ziyuedi** [comment]
参考了https://github.com/chengr28/Pcap_DNSProxy/blob/master/Source/Auxiliary/ExampleConfig/IPFilter.ini
测试版本我待会试试

**Comment by ziyuedi** [comment]
正常了
谢谢

**Comment by ziyuedi** [comment]
请问什么时候会发新的release？
希望尽快吧
