### ISSUE TITLE
有个小建议~

### ISSUE THREAD

**Issue by fangjia052** [pymumu/smartdns#671]
作者好，自从用上了smartdns之后对这款插件很喜欢，一直在使用。

想提个自己的小想法：如果能把大众常用的域名，比如说淘宝京东支付宝qq微信什么的，这些域名做成一个列表，然后在开启smartdns后自动去获取ip，然后每次快过期时再次自动获取ip，这样的话访问速度会比较快

作者最近是很忙吗？希望这个项目能坚持下去，很好的插件！

**Comment by snday** [comment]
这个很好，越来越智能化了，不用人为干预，小白也能轻松使用了!

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
