### ISSUE TITLE
请问是否可以考虑单独出一个bootstrap参数

### ISSUE THREAD

**Issue by Jan20th9e** [pymumu/smartdns#672]
请问是否可以考虑单独出一个bootstrap参数用于解析DoH/DoT域名而不参与默认解析。比如想要全部使用纯域名形式的DoH。现在用的方案是
server 119.29.29.29 -group bootstrap -exclude-default-group
server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query
nameserver /doh.pub/bootstrap
nameserver /dns.alidns.com/bootstrap
这样虽然可行但是感觉配置略微繁琐，特别是配置多个服务器后可能需要每次增加一行分流。如果单独配置一个参数那可以直接简化成
server 119.29.29.29 bootstrap
server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query

**Comment by pymumu** [comment]
只是一个默认内置组的问题，看多少人要把。

**Comment by honwen** [comment]
Good point

**Comment by garypang13** [comment]
支持.

**Comment by osxdiy** [comment]
server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query
bootstrap=119.29.29.29
这种方式更好

**Comment by izeroo** [comment]
支持

**Comment by SuSpoiled** [comment]
支持

**Comment by YChen0317** [comment]
支持
