### ISSUE TITLE
TLS校验参数

### ISSUE THREAD

**Issue by tudnew** [pymumu/smartdns#673]
server-tls 162.14.21.56 -host-name dns.google -tls-host-verify
正常
server-tls 162.14.21.56 -host-name dns.google -tls-host-verify dns.google
报错
server-tls 162.14.21.56 -tls-host-verify dns.google
报错

所以这-host-name到底有什么用啊？域名别在意，就是为了试错

**Comment by pymumu** [comment]
hostname指的是发给服务器的，用于让服务器知道你在请求什么，就是http请求头里面的hostname

**Comment by tudnew** [comment]
> hostname指的是发给服务器的，用于让服务器知道你在请求什么，就是http请求头里面的hostname

了解了，doh.pub 不设置就有随机报错，应该是这个问题，谢谢
