### ISSUE TITLE
请问下有重新规划ECS的计划吗？

### ISSUE THREAD

**Issue by qwerttvv** [pymumu/smartdns#674]
https://github.com/pymumu/smartdns/blob/master/etc/smartdns/smartdns.conf

    # edns client subnet
    # edns-client-subnet [ip/subnet]
    # edns-client-subnet 192.168.1.1/24
    # edns-client-subnet [8::8]/56

我看配置文件里写了这个，又搜到该功能现在已经被关闭了

现实中无论国内科学上网的用户还是有其它特殊需求的，我想对这个还是有需求

如果ECS也支持分组设置，那一个分组用梯子地址，一个分组用国内实际地址，这样是不是好一些

而且不同分组采用不同的ECS，配置起来也更加灵活，可以实现更多的特殊需求

**Comment by pymumu** [comment]
可以具体描述一下你的ecs使用场景

**Comment by qwerttvv** [comment]
有时候CDN不准，尤其科学上网时候会绕远儿

**Comment by honwen** [comment]
> 有时候CDN不准，尤其科学上网时候会绕远儿

例子: 有些IP段会被识别到其他地方, 如阿里云轻量的海外IP(US)可能会有识别为CN
