### ISSUE TITLE
开启双栈优选后，解析纯IPv6网站有时会返回空记录

### ISSUE THREAD

**Issue by ningzichun** [pymumu/smartdns#676]
**问题现象**  

开启双栈优选后，解析纯IPv6网站有时会返回空记录
dualstack-ip-selection yes

**运行环境**
1. 固件型号  
smartdns.1.2020.09.08-2235.x86_64-debian-all.deb
2. 运营商  
VPS(ColoCrossing机房)

**重现步骤**
1. 上游DNS配置。  
server 1.1.1.1
server 8.8.8.8
server-tcp 8.8.8.8

2. 访问的域名。  
· 在VPS上使用nslookup测试

```
> server 127.0.0.1
> speed.neu6.edu.cn
Non-authoritative answer:
*** Can't find speed.neu6.edu.cn: No answer
> bt.byr.cn
Non-authoritative answer:
*** Can't find bt.byr.cn: No answer
> mirrors.tuna.tsinghua.edu.cn
Non-authoritative answer:
mirrors.tuna.tsinghua.edu.cn    canonical name = cdnmirrors.s.tuna.tsinghua.edu.cn.
Name:   cdnmirrors.s.tuna.tsinghua.edu.cn
Address: 101.6.8.193
Name:   cdnmirrors.s.tuna.tsinghua.edu.cn
Address: 2402:f000:1:408:8100::1
> mirrors6.tuna.tsinghua.edu.cn
Non-authoritative answer:
mirrors6.tuna.tsinghua.edu.cn   canonical name = cdnmirrors6.a.s.tuna.tsinghua.edu.cn.
> cdnmirrors6.a.s.tuna.tsinghua.edu.cn
Non-authoritative answer:
*** Can't find cdnmirrors6.a.s.tuna.tsinghua.edu.cn: No answer
```

· 使用1.1.1.1
```
> speed.neu6.edu.cn
Non-authoritative answer:
Name:   speed.neu6.edu.cn
Address: 2001:da8:9000::66
> bt.byr.cn
Non-authoritative answer:
Name:   bt.byr.cn
Address: 2001:da8:215:4078:250:56ff:fe97:654d
> mirrors.tuna.tsinghua.edu.cn
Non-authoritative answer:
mirrors.tuna.tsinghua.edu.cn    canonical name = cdnmirrors.s.tuna.tsinghua.edu.cn.
Name:   cdnmirrors.s.tuna.tsinghua.edu.cn
Address: 101.6.8.193
Name:   cdnmirrors.s.tuna.tsinghua.edu.cn
Address: 2402:f000:1:408:8100::1
> mirrors6.tuna.tsinghua.edu.cn
Non-authoritative answer:
mirrors6.tuna.tsinghua.edu.cn   canonical name = cdnmirrors6.a.s.tuna.tsinghua.edu.cn.
Name:   cdnmirrors6.a.s.tuna.tsinghua.edu.cn
Address: 2402:f000:1:408:8100::1
```

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
[log.txt](https://github.com/pymumu/smartdns/files/5809630/log.txt)

电信v6访问海外较慢，在路由器端使用smartdns，并开启双栈优选后，很好地解决了问题。
不过在使用中发现了个小问题。就是有时候访问纯v6网站的时候，dns解析没有返回地址。似乎打不开的网站较多数是离我这地理位置较远的，比如中科大源可以打开，但清华源和东北测速站以及境外有时不行 : ) 。稍微猜测下，也许是测试超时话，就不会返回这个v6地址了吧，所以在VPS上测试解析国内教育网纯v6域名。

谢谢 : )

**Comment by pymumu** [comment]
沒有問題，你可以在windows下执行
```
nslookup speed.neu6.edu.cn
```
看看

**Comment by ningzichun** [comment]
嗯，我在本地宽带下，OpenWRT路由器开启SmartDNS，记录debug日志
日志文件：[log2401.txt](https://github.com/pymumu/smartdns/files/5860710/log2401.txt)  配置文件：[smartdns.conf.txt](https://github.com/pymumu/smartdns/files/5860713/smartdns.conf.txt)

在Windows电脑上使用nslookup测试，部分纯v6域名解析返回空记录
‘’‘
> ipv6.mirrors.ustc.edu.cn
服务器:  [10.0.0.1]
Address:  10.0.0.1

名称:    ipv6.mirrors.ustc.edu.cn
Address:  2001:da8:d800:95::110

> speed.neu6.edu.cn
服务器:  [10.0.0.1]
Address:  10.0.0.1

名称:    speed.neu6.edu.cn

> bt.byr.cn
服务器:  [10.0.0.1]
Address:  10.0.0.1

名称:    bt.byr.cn

>
’‘’

**Comment by thinktip** [comment]
同样的问题，所以有些只有AAAA记录的域名，只好加domain-rules规则，丢弃A记录才行。

**Comment by 1phalley** [comment]
我的思路是先看看是不是ipv6dns服务器本身就解析不出来，二就是看smartdns设置有无问题，三就是电脑的ipv6是不是真的经过smartdns的解析

smartdns缓存设置为零，第二dns服务器跳过cache，dnsmasq高级设置缓存设为0
dig bt.byr.cn @openwrt地址 -p第一或第二DNS服务器端口 AAAA 分别是什么结果
先ssh进路由测试，再在电脑上测试，时不时ipconfig /flushdns刷新dns缓存

可能你已经弄好了，写个有需要的人看

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
