### ISSUE TITLE
使用在openwrt路由器上，很大几率wan口断连后服务器不通

### ISSUE THREAD

**Issue by hplee0120** [pymumu/smartdns#679]
自己手动尝试使用wan口重连，然后第二服务器不通。大概率是主服务器正常，第二服务器发生断连，偶尔是第一和第二服务器全部断连。重启路由器或者重新保存并应用就恢复正常了，

第一服务器正常，第二服务器失效
C:\Windows\system32>nslookup baidu.com
服务器:  smartdns
Address:  2409:8a55:4417:d890::1

非权威应答:
名称:    baidu.com
Address:  39.156.69.79

C:\Windows\system32>nslookup google.com
服务器:  smartdns
Address:  2409:8a55:4417:d890::1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 smartdns 超时

重新保存并应用插件后全部正常
C:\Windows\system32>nslookup qq.com
服务器:  smartdns
Address:  2409:8a55:4417:d890::1

非权威应答:
名称:    qq.com
Address:  58.250.137.36

C:\Windows\system32>nslookup google.com
服务器:  smartdns
Address:  2409:8a55:4417:d890::1

非权威应答:
名称:    google.com
Address:  172.217.24.206

C:\Windows\system32>nslookup youtube.com
服务器:  smartdns
Address:  2409:8a55:4417:d890::1

非权威应答:
名称:    youtube.com
Address:  216.58.199.110
配置文件
# 默认DNS服务器（解析国内DNS组）
server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query
server-https https://dns.ipv6dns.com/dns-query
# 第二DNS服务器（解析国外DNS组）
server-tls dns.google -group world -exclude-default-group
server-tls one.one.one.one -group world -exclude-default-group
# 解析DoH/DoT域名
server 119.29.29.29 -group bootstrap -exclude-default-group
server 208.67.222.222:5353 -group bootstrap -exclude-default-group
nameserver /doh.pub/bootstrap
nameserver /dns.alidns.com/bootstrap
nameserver /dns.ipv6dns.com/bootstrap
nameserver /dns.google/bootstrap
nameserver /one.one.one.one/bootstrap
luci界面的设置
config smartdns
	option server_name 'smartdns'
	option serve_expired '1'
	option coredump '0'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_ipset '0'
	option seconddns_no_rule_soa '0'
	option cache_size '20000'
	option seconddns_server_group 'world'
	option seconddns_no_cache '1'
	option prefetch_domain '1'
	option redirect 'dnsmasq-upstream'
	option tcp_server '1'
	option seconddns_tcp_server '1'
	option rr_ttl_min '300'
	option port '3333'
	option seconddns_port '5335'
	option seconddns_no_speed_check '1'
	option seconddns_no_dualstack_selection '0'
	option force_aaaa_soa '1'
	option enabled '1'
	option seconddns_enabled '1'
	option ipv6_server '1'
	option dualstack_ip_selection '1'
	list old_redirect 'dnsmasq-upstream'
	list old_port '3333'
	list old_enabled '1'
使用方法是第二服务器5335端口，分配给ssrplus插件使用。使用作为dnsmasq上游
使用的源码为https://github.com/project-openwrt/openwrt/tree/openwrt-18.06/package/ntlf9t
应当跟大佬的源码是同步的。
尝试过在https://github.com/pymumu/smartdns/releases 下载ipk安装后问题一致。
[2021-01-18 05:02:16,984][ERROR][     dns_client.c:2768] Send query to upstream server failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2645] send dns request failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2723] do query github.com failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:3322] dns server process failed.
[2021-01-18 05:02:16,984][ERROR][     dns_client.c:2768] Send query to upstream server failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2645] send dns request failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2723] do query github.com failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:3322] dns server process failed.
[2021-01-18 05:02:16,984][ERROR][     dns_client.c:2768] Send query to upstream server failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2645] send dns request failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2723] do query github.com failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:3322] dns server process failed.
[2021-01-18 05:02:16,984][ERROR][     dns_client.c:2768] Send query to upstream server failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2645] send dns request failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2723] do query github.com failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:3322] dns server process failed.
[2021-01-18 05:02:16,984][ERROR][     dns_client.c:2768] Send query to upstream server failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2645] send dns request failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:2723] do query github.com failed.
[2021-01-18 05:02:16,984][ERROR][     dns_server.c:3322] dns server process failed.
尝试开启coredump功能后问题复现，但是并没有在tmp文件夹生成相关文件。

**Comment by hplee0120** [comment]
https://github.com/pymumu/smartdns/issues/529
找到一个同样现象的反馈，问题是我已经采用最新版了请问问题还没有被修复吗。。。

**Comment by hplee0120** [comment]
经过查看多个相似问题的反馈后得到灵感，现在为第二服务器增加一个udp协议的dns后似乎问题得到解决，经过多次重连wan后暂时未出现之前的问题，希望大佬确定问题后可以修复。
现在的配置文件
server-https https://doh.pub/dns-query
server-https https://dns.alidns.com/dns-query
server 208.67.222.222:5353 -group world -exclude-default-group
server-tls dns.google -group world -exclude-default-group
server-tls one.one.one.one -group world -exclude-default-group
server 119.29.29.29 -group bootstrap -exclude-default-group
server 208.67.222.222:5353 -group bootstrap -exclude-default-group
nameserver /doh.pub/bootstrap
nameserver /dns.alidns.com/bootstrap
nameserver /dns.google/bootstrap
nameserver /one.one.one.one/bootstrap

**Comment by PikuZheng** [comment]
你这个应该是和我相同的情况 https://github.com/pymumu/smartdns/issues/341#issuecomment-583236776
主要原因是smartdns在运行时需要先给配置的上游域名解析为ip才能工作。但系统自身的请求又循环给了smartdns，导致内存耗尽。
我的解决方案 一是配置上游服务器为ip且额外指定域名。二是和你的方法一样，在 nameserver 段指定这几个上游域名走一个单独的组，并配置这个单独的组的上游为ip+udp

**Comment by hplee0120** [comment]
> 你这个应该是和我相同的情况 [#341 (comment)](https://github.com/pymumu/smartdns/issues/341#issuecomment-583236776)
> 主要原因是smartdns在运行时需要先给配置的上游域名解析为ip才能工作。但系统自身的请求又循环给了smartdns，导致内存耗尽。
> 我的解决方案 一是配置上游服务器为ip且额外指定域名。二是和你的方法一样，在 nameserver 段指定这几个上游域名走一个单独的组，并配置这个单独的组的上游为ip+udp

我这边似乎并没有发现内存异常的情况。另外奇怪的是第一服务器和第二服务器都使用纯doh/dot的情况下，重连wan后为什么第一服务器一般不会出问题，而第二服务器大概率会有问题，必须为第二服务器单独增加一个udp。另外我也建议作者单独增加一个bootstrap参数，用于专门用来解析服务器域名而不参与解析，这样就不用单独增加一堆nameserver了。
我就是看了你发言的那个反馈前面的人提的一句“ 比如我断开pppoe然后重新拨号。有没有可能是之前连接成功的dot/doh仍处于established状态，没有触发断开或重新连接导致的查询失败？”，所以尝试使用udp协议然后问题解决了。

**Comment by PikuZheng** [comment]
根据我的观察smartdns解析自身服务器配置是走resolv.conf的。你的第二服务器是dnsmasq的上游，会导致请求循环。

**Comment by hplee0120** [comment]
> 根据我的观察smartdns解析自身服务器配置是走resolv.conf的。你的第二服务器是dnsmasq的上游，会导致请求循环。

放弃折腾了，本来的想法是因为开启了ipv6，想保留国内ipv6然后利用第二服务器禁用国外的ipv6解析，现在越琢磨感觉问题越多，干脆关了ipv6和第二服务器，就开了主服务器解析国内当一个支持Doh/DoT的工具用了。

**Comment by PikuZheng** [comment]
> > 根据我的观察smartdns解析自身服务器配置是走resolv.conf的。你的第二服务器是dnsmasq的上游，会导致请求循环。
> 
> 放弃折腾了，本来的想法是因为开启了ipv6，想保留国内ipv6然后利用第二服务器禁用国外的ipv6解析，现在越琢磨感觉问题越多，干脆关了ipv6和第二服务器，就开了主服务器解析国内当一个支持Doh/DoT的工具用了。

这个想法可以有。我是手动搞了个表，国外重点的域名不返回ipv6结果。国内的正常解析。

**Comment by hplee0120** [comment]
> > > 根据我的观察smartdns解析自身服务器配置是走resolv.conf的。你的第二服务器是dnsmasq的上游，会导致请求循环。
> > 
> > 
> > 放弃折腾了，本来的想法是因为开启了ipv6，想保留国内ipv6然后利用第二服务器禁用国外的ipv6解析，现在越琢磨感觉问题越多，干脆关了ipv6和第二服务器，就开了主服务器解析国内当一个支持Doh/DoT的工具用了。
> 
> 这个想法可以有。我是手动搞了个表，国外重点的域名不返回ipv6结果。国内的正常解析。
试来试去都是同一个结果，就是重连wan后第二服务器就起不来了，主服务器倒是没什么问题。
