### ISSUE TITLE
增加Support nftables set

### ISSUE THREAD

**Issue by rodge-liu** [pymumu/smartdns#681]
因为cenots8 和debian 10 已经从iptables 改为nftables .原IPSET 无法在nftables使用。

**Comment by kulongwangzhi85** [comment]
支持

**Comment by sky96111** [comment]
https://openwrt.org/releases/22.03/notes-22.03.0-rc1

OpenWrt 22.03.0开始将iptables改成了nftables

**Comment by yujincheng08** [comment]
#1117 这个可以关了
