### ISSUE TITLE
win10-WSL(ubuntu)安装smartdns问题

### ISSUE THREAD

**Issue by MC-dusk** [pymumu/smartdns#686]
一步步按照[readme](https://github.com/pymumu/smartdns/blob/master/ReadMe.md)来安装，遇到了一些问题，有些解决了，有些仍有疑问，一并写出。

1. 按照[ubuntu官网教程](https://ubuntu.com/wsl)安装好WSL，默认使用WSL2，安装smartdns，发现安装失败，按照 #439 的说明重新安装，成功，配置好上游DNS，改默认DNS为127.0.0.1，但smartdns服务没有生效（用`nslookup -querytype=ptr smartdns`检查，类似 #326）（按 #532 设置默认DNS也不行）。后来发现可能被win10防火墙阻碍。（类似问题： #491 #29）

2. 换用WSL1，重新按原方法安装，成功（会弹出防火墙许可窗口），然后配置上游DNS和本地默认DNS，用`nslookup -querytype=ptr smartdns`检查是否启用smartdns，显示（如下）与[readme](https://github.com/pymumu/smartdns/blob/master/ReadMe.md)不完全一致，~~这是成功了吗？~~[readme](https://github.com/pymumu/smartdns/blob/master/ReadMe.md)中的`192.168.1.1`是路由器的地址吧，对于WSL应该就是`127.0.0.1`。

`powershell`
```
PS C:\Users\XX> nslookup -querytype=ptr smartdns
服务器:  smartdns
Address:  127.0.0.1

非权威应答:
smartdns        name = smartdns
```

`WSL1-ubuntu`
```
ZZ@YY:/mnt/c/Users/XX$ nslookup -querytype=ptr smartdns
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
smartdns        name = smartdns.

Authoritative answers can be found from:
```

3. 是否每次开机，需要**手动启动**WSL1，然后**运行**reload.bat，才能启用smartdns服务？

4. [readme](https://github.com/pymumu/smartdns/blob/master/ReadMe.md)提供的改DNS教程：

   >将DNS请求转发的SmartDNS解析。
   >
   >将Windows的默认DNS服务器修改为`127.0.0.1`，具体步骤参考[IP配置](https://support.microsoft.com/zh-cn/help/15089/windows-change-tcp-ip-settings)

   可能过时（大概这是微软的锅？）。
在**设置**里改DNS无效，
![图片](https://user-images.githubusercontent.com/52311860/105674787-fb070480-5f22-11eb-80bb-d066108898a9.png)
在**控制面板-网络和共享中心**里改DNS才有效，如图。
![图片](https://user-images.githubusercontent.com/52311860/105675000-56d18d80-5f23-11eb-9e61-1b849ac64e79.png)

**Comment by MC-dusk** [comment]
使用数小时后发生类似 #509 的情况，smartdns服务断开，且reload.bat重启失败，需要重启电脑（我只会重启电脑

**Comment by phyolization** [comment]
同问！WSL是被遗弃了么：（

**Comment by pymumu** [comment]
用WSL1，WSL2理论可以，配置上没用验证过，

可以找到wsl2的IP地址，配置对应的IP地址即可。

**Comment by MC-dusk** [comment]
😅

**Comment by kyleli666** [comment]
遇到了同样的问题，WSL2内无法使用，ip addr show 列出的所有IP均无法正常使用。
切换到WSL1可正常使用。

**Comment by PikuZheng** [comment]
> 遇到了同样的问题，安装在WSL2内无法使用，ip addr show 列出的所有IP均无法正常使用。 `wsl --set-version Ubuntu 1` 切换到WSL1可正常使用。

wsl2 自身会起一个dns服务wslhost.exe，最简单的方法是smartdns不绑定53端口换用别的端口。否则就得改掉wsl2，关闭自身的dns服务

**Comment by DoiiarX** [comment]
> ip addr show

看起来有时候还需要用kill杀死端口占用。且要用ip addr show找到服务器实ip。不能填写127.0.0.1

**Comment by DoiiarX** [comment]
53改其他端口这个，Windows好像没法配置。不知道怎么处理。
