### ISSUE TITLE
建议针对第三方CDN，增加“域名承接”功能

### ISSUE THREAD

**Issue by xyl23333** [pymumu/smartdns#687]
**需求应用场景**
某些网站在无特殊上网方案的情况下，下载文件可能较慢，也可能无法正常访问。我们通常会用一些第三方CDN服务器。
比如raw.githubusercontent.com： https://raw.githubusercontent.com/pymumu/smartdns/master/LICENSE  。换成raw.fastgit.com后可以正常访问 https://raw.fastgit.org/pymumu/smartdns/master/LICENSE

此类案例还有很多，不一一赘述。但是这些域名的IP也在发生变化，仅仅更改hosts不方便，而且iOS机型几乎无法修改hosts。因此可以在smartdns端，将解析出的fastgit IP应用于githubusercontent。

**建议的方案**
在配置文件上增加domain-transfer 选项以解释域名间的承接关系，每项只允许两个域名。比如:
domain-transfer raw.githubusercontent.com raw.fastgit.com
用户以前者域名请求，返回后者的IP。

**设备信息**
1. 设备信息（CPU，厂家）  
CPU:MT7621 
型号:华硕AC1200GU

2. 固件信息
华硕原厂固件，固件版号为3.0.0.4.380_10923-g3f93b02

**Comment by supppig** [comment]
对于https，这涉及中间人攻击，不属于dns的范畴。
你应该找支持https广告过滤的软件，自己写规则。
哦，对了，如果这样做的话，还需要客户端装自签名根证书，emmmmmm。。。。

**Comment by onion83** [comment]
这已经叫 URLRewrite ，不属于DNS 的范畴了

**Comment by lilydjwg** [comment]
给它添加一个 CNAME 记录？

**Comment by qwIvan** [comment]
> 给它添加一个 CNAME 记录？

仙子怎么在smartdns加CNAME记录

**Comment by lilydjwg** [comment]
On Thu, Apr 08, 2021 at 02:27:28AM -0700, Ivan Ng wrote:
> > 给它添加一个 CNAME 记录？
> 
> 仙子怎么在smartdns加CNAME记录

还做不到吧。我的意思是，这个需求在技术层面上可以这么搞。

-- 
Best regards,
lilydjwg

**Comment by pymumu** [comment]
cname参数已经支持。
