### ISSUE TITLE
返回的ip ping值很高

### ISSUE THREAD

**Issue by willie91** [pymumu/smartdns#69]
**问题现象**  
简要描述问题出现的现象
![image](https://user-images.githubusercontent.com/32695308/51674623-1ecda200-200c-11e9-8019-b5e1b20edec3.png)
试了几次，有时返回的ip的ping值很低，有时很高，这是正常的吗？

**运行环境**
1. esxi虚拟lede

2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。 
![screenshot-lede iamok cc-2019 01 24-19-15-18](https://user-images.githubusercontent.com/32695308/51674722-6eac6900-200c-11e9-862b-7261dee8c5cc.png)
 

2. 访问的域名。  
baidu.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
跑到香港去了，是否开了什么科学软件？
看你的配置，基本都是国内的服务器，不应该这样，可能DNS是其他服务提供了。
这个命令看一下返回值。
dig www.baidu.com -p 6053

**Comment by willie91** [comment]
> 跑到香港去了，是否开了什么科学软件？
> 看你的配置，基本都是国内的服务器，不应该这样，可能DNS是其他服务提供了。
> 。这个命令看一下返回值
> 挖[www.baidu.com](http://www.baidu.com) -p 6053

是的，用了路由器翻墙插件。
命令是不是错了？- -。

**Comment by pymumu** [comment]
nslookup www.baidu.com -port=6053

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51732118-32cedd80-20b8-11e9-9f72-f2e1e649a7f8.png)

**Comment by pymumu** [comment]
你下载一个dig命令吧。windows的nslookup
不支持端口号的。

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51732892-affb5200-20ba-11e9-9a17-66f17365be77.png)
我换了个Ubuntu

**Comment by pymumu** [comment]
smartdns应该是启动在6053端口号的。

dig www.baidu.com -p 6053就是到6053端口查询。
可以指定下IP看看
dig www.baidu.com [路由IP] -p 6053

确认smartdns服务器是不是运行正常

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51733374-1a60c200-20bc-11e9-8395-0a9c37a2e071.png)
![image](https://user-images.githubusercontent.com/32695308/51733386-22206680-20bc-11e9-9b6c-2b1a38af88c7.png)
在lede倒是能看到正在运行，这两天也没断过。

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51734131-93f9af80-20be-11e9-8a63-5fa3248fca03.png)
路由地址没错的- -。

**Comment by pymumu** [comment]
dig -t ptr 0.0.0.0
看看命令结果里面有没有SmartDNS字样

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51735394-4ed77c80-20c2-11e9-814b-7759138c9a45.png)
有

**Comment by pymumu** [comment]
你用的哪个安装文件，我给你个19的版本看看。

**Comment by pymumu** [comment]
你百度的结果也有正常的时候。
你在路由器里面ping百度的IP地址是否时正常的？

**Comment by willie91** [comment]
smartdns.1.2019.01.07-2334.x86_64.ipk
![image](https://user-images.githubusercontent.com/32695308/51759539-67b45200-2103-11e9-8ce8-7e9522cfcb0c.png)
这样算正常么？这个ip倒是没问题

**Comment by willie91** [comment]
更新了新版之后，大部分ping值都在30.40左右

奇怪的是，一开始返回的ip我ping了一下只有10左右，我开了缓存功能，为什么下次给的ip还是不一样的呢？

**Comment by pymumu** [comment]
是不是10ms那个结果不稳定，你一直ping 10ms那个地址看看有无超时

**Comment by pymumu** [comment]
另外缓存是ttl超时的，超过ttl的值就丢弃了，有个min-ttl可以控制这个值

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51782372-f952ac80-2161-11e9-8a72-9042e949e15b.png)
ip没啥问题

**Comment by pymumu** [comment]
有配置启用过反回答伪造吗

**Comment by willie91** [comment]
没有，都是默认的

**Comment by pymumu** [comment]
家里有电信IPTV的话，猫如果不好，会有超时的情况的。

**Comment by willie91** [comment]
![image](https://user-images.githubusercontent.com/32695308/51785462-06d45a80-2193-11e9-9fa7-d71f9ce59dd6.png)
- -。14开头的这个地址有丢包，另外，百度，淘宝，京东之类的都返回过ping值很低的地址，但很多时候返回的地址都是40左右的ping值

**Comment by pymumu** [comment]
应该时检测速度的时候，出现了超时，所以没有返回ping值小的IP
你这网络质量不佳，可能和你的光猫，或路由器相关。

可以联系电信的给你处理下，就好了。

**Comment by pymumu** [comment]
更新最新版本看看吧，有问题再reopen issue
