### ISSUE TITLE
Block list IP set for the answer from a dns

### ISSUE THREAD

**Issue by hizukiayaka** [pymumu/smartdns#690]
**需求应用场景**
请描述需求应用的场景和方式。
For some environment, the upstream would return an valid IP address for a query of A record, but the answer is poisoned.
To be more specific, for example, we have Internet connection to different countries, their track is the most short case. I only want the answer from a dns which is charging its country, if the answer is not from your IPset, then left the query to the other or default server.
**建议的方案**
实现上述场景建议的方案。
IPset block list
http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=13d86c7372e01392d1e3af7c90312b49e2a5c15d
ChinaDNS-ng

I would submit a MR if I have time to write it.
**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
try blacklist-ip and whitelist-ip
