### ISSUE TITLE
建议兼容V2ray的geosite/geoip文件设定域名规则

### ISSUE THREAD

**Issue by flynxea** [pymumu/smartdns#691]
**需求应用场景**
根据域名设计规则，geosite已经有详细的域名分类

**建议的方案**
建议兼容V2ray的geosite/geoip文件设定域名规则

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by wy16W2pIilK1xgqN** [comment]
非常赞同。

**Comment by Karmylr** [comment]
非常赞同。但是不知道维护人员能不能看到

**Comment by pymumu** [comment]
不会支持，请自行转换。
