### ISSUE TITLE
DNS结果解析响应速度异常慢

### ISSUE THREAD

**Issue by tony198911** [pymumu/smartdns#694]
**问题现象**  

首先感谢作者的辛勤付出，感谢有你~

DNS结果解析速度异常，如图所示
dnsmasq→ADGuardHOME→223.5.5.5= 40+ 毫秒
dnsmasq→ADGuardHOME→SmartDNS→223.5.5.5= 500+ 毫秒

**运行环境**
1. Openwrt

![}Z_$}H(~U7KTO4ZY5D$@$YC](https://user-images.githubusercontent.com/18481553/107186698-b6e62a80-6a1f-11eb-8351-f7e73d9c0bf0.png)

2. 运营商  
电信1000M光纤入户

**重现步骤**
1. 上游DNS
dnsmasq→ADGuardHOME→223.5.5.5
dnsmasq→ADGuardHOME→SmartDNS→223.5.5.5

2. 访问的域名。  
观看B站视频，即可随机访问*.mcdn.bilivideo.cn
xy171x94x108x27xy.mcdn.bilivideo.cn
xy171x222x121x234xy.mcdn.bilivideo.cn

**信息收集**  
自定义设置：
log-level fatal
speed-check-mode tcp:443,tcp:80
force-AAAA-SOA yes

**建议**
个人猜测：由于*.mcdn.bilivideo.cn解析的IP都没有开启443端口，所以smartDNS应该是等到超时了才继续测速80端口
所以建议：如果域名解析后只返回一个IP，那就不要测速，直接使用即可

最后，感谢作者，您的smartDNS对网络体验的改善非常明显

**Comment by pymumu** [comment]
只有一个ip的情况，是立即返回的。
可以将测速模式换成tcp。

建议开启
```shell
serve-expired yes
serve-expired-ttl 86400

```
提升查询速度的同时避免一些时延。
