### ISSUE TITLE
解析到的IP地址如果在用户指定的范围内就采用特定DNS解析的结果这个要怎么弄?

### ISSUE THREAD

**Issue by chainofhonor** [pymumu/smartdns#696]
解析服务器添加了223.5.5.5和8.8.8.8
然后解析 www.test.com 
第一次解析的时候 两边同时发送解析请求
然后肯定是alidns的解析速度快,假如解析的地址在用户自己指定的IP段内(比如地址是国外的),则采用8.8.8.8返回的结果(如果8.8.8.8返回失败,则也给用户反馈解析失败即使alidns是正常的) 同时记住这个操作,未来下面的客户端解析这个域名的时候就全部走8.8.8.8了 就不再同时发送给223.5.5.5了 如果用户开启了缓存,则刷新的时候也是向8.8.8.8请求

请问这个需求现在能做到吗?
不需要用户自己去添加域名走哪条线,直接自动检测

**Comment by helianling** [comment]
建议使用上的问题去一些交流群聊比较好，因为这并不是软件本身的Bug，是没有根据使用场景做正确的配置。
