### ISSUE TITLE
大神，可以编译一下最新的ipk安装包到release页面吗？

### ISSUE THREAD

**Issue by iovefish** [pymumu/smartdns#697]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
最新代码，还有crash问题，还没定位，等定位了就发release。

**Comment by yyysuo** [comment]
大佬最近太忙了吗，好久没有理这个项目了。

**Comment by pymumu** [comment]
用最新代码。
