### ISSUE TITLE
建议增加一个统一查询端口，程序内部自动分流国内国外到原有第一、第二端口

### ISSUE THREAD

**Issue by lededev** [pymumu/smartdns#698]
原有功能不变以兼容现有的各种应用。新增一个统一查询端口，接受国内外所有域名查询请求，然后以geodata或者chinalist等等数据源，和可配置的的分流规则，在程序内部将查询请求分配给第一或第二服务器。

单一运行模式可选项（不兼容原有功能）。应用此方案时，停止监听第一、第二服务器的端口，此时smartdns仅监听一个端口，即统一查询端口。

**Comment by 44571366** [comment]
这个提议不错，在接管DNS后，应该直接把设备国内、国外的DNS端口设置统一放在smartDNS，好多软件要么只有国内设置，要么只有国外设置

**Comment by helianling** [comment]
目前已经可以基于端口分流了，目前感觉足够了。至于国内国外规则其他插件本身就有此功能了，再配合不同端口就可以了。

**Comment by lededev** [comment]
目前由于没有直接使用geodata或者gfwlist的数据源，而是需要进行配置文件的格式转换，而这些数据有好几MB大小。
导致DNS解析和XRay或iptables本该共用的数据源，在同一台路由上被分成了几个不同格式，但内容其实相同的文件。
不仅每次更新需要对每种应用所需的格式单独更新，也造成了闪存较小的设备没法涵盖全部格式而无法使用。

**Comment by yangjie1388** [comment]
本来就有域名用指定DNS分组出去的功能，再设置这个功能没有必要吧。
