### ISSUE TITLE
建议增强去广告的功能的兼容性

### ISSUE THREAD

**Issue by jack4red** [pymumu/smartdns#699]
**需求应用场景**
目前smartdns只支持自己的屏蔽广告的语法，而很多其它的广告拦截规则不能适用，需要手动修改添加

**建议的方案**
希望能够适配通用的广告拦截规则，如果可以直接填入广告拦截规则自动更新更佳

**Comment by helianling** [comment]
DNS去广告本身就有其局限性的，感觉Smartdns本身更专注于DNS这块的。是小而美还是大而全是很难平衡的。

**Comment by foxconndmd** [comment]
基于dns去广告的方案就是鸡肋。

**Comment by featherwit** [comment]
想要那些可以上AdGuardHome和SmartDNS做套娃

但我觉得那些才是鸡肋，像Easylist这些更多是为了浏览器设计的，而且规则搞多了会影响解析速度的

DNS反广告直接搞个anti-AD就足够了，直接有SmartDNS的版本

**Comment by outsidesilence** [comment]
术业有专攻，smartdns不应该做多而杂的事，应该把更多精力放在优化和修复bug上。

**Comment by hpcex** [comment]
去广告感觉还是靠浏览器好，dns里去做，有的误屏蔽了，排查也麻烦，还消耗资源。

**Comment by pymumu** [comment]
最好还是浏览器广告屏蔽。
参考：https://pymumu.github.io/smartdns/config/ad-block/
