### ISSUE TITLE
建议增加一个检测配置文件是否正确的功能

### ISSUE THREAD

**Issue by ziyuedi** [pymumu/smartdns#70]
**需求应用场景**
如题，否则配置文件搞错了太难排查

**建议的方案**
从格式和可用性方面分别检测配置文件
1.检测配置文件中所有服务器是否可用
2.端口是否被占用
等等

**Comment by pymumu** [comment]
release 19启动的时候增加了打印。
可以用
smartdns -f -v -c smartdns.conf看到。
或者到
路由器的syslog中查看。
