### ISSUE TITLE
建议增加类似dnsmasq的alias配置

### ISSUE THREAD

**Issue by sylingd** [pymumu/smartdns#707]
**需求应用场景**
alias用途是将上游DNS返回的特定IP/IP段，强行指定到目标IP。

实际用途是针对Cloudflare等这类有众多IP的CDN。因使用其服务的域名众多，无法直接用现有功能指定。用户通过其他方法（例如[CFIP](https://github.com/BlueSkyXN/CFIP)）获取到对于当前环境速度最佳的IP后，可以直接将其强行指定到固定的IP。

**建议的方案**
在配置中增加alias功能，格式为`/旧IP或IP段/新IP/新IP的子网掩码`。
例如：
```
# 将上游DNS返回的1.2.3.4，指定到5.6.7.8
alias /1.2.3.4/5.6.7.8

# 将1.2.3.x指定到5.6.7.x
alias /1.2.3.0/5.6.7.0/255.255.255.0

# 将192.168.0.10->192.168.0.40 指定到 10.0.0.10->10.0.0.40
alias /192.168.0.10-192.168.0.40/10.0.0.0/255.255.255.0

# 将192.168.0.10->192.168.0.40 指定到 1.2.3.4
alias /192.168.0.10-192.168.0.40/1.2.3.4/255.255.255.255
```

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
已经添加ip-alias功能。
