### ISSUE TITLE
建议增加TLS同时指定域名和IP的功能

### ISSUE THREAD

**Issue by ziyuedi** [pymumu/smartdns#71]
**需求应用场景**
大部分CA很少对IP发证书，这时就需要指定域名，然而通过传统dns再查询域名很多时候又画蛇添足

**建议的方案**
配置文件增加对DoT同时指定域名和IP的功能

**Comment by pymumu** [comment]
你的意思是校验DoT服务端的证书吧。

这个RFC有对应的方案的，一般检查SKPI的值的。
比如下面的命令，就是获取CDH的SKPI
```
echo | openssl s_client -connect '1.1.1.1:853' 2>/dev/null | openssl x509 -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | openssl enc -base64
```

smartdns后面会增加DOT的证书检查参数。

**Comment by ziyuedi** [comment]
不是，是在配置DoT是如果指定域名，还要通过传统DNS查询一次IP，这样有些没必要

**Comment by pymumu** [comment]
请取新版本验证，看看增加域名分流功能是否满足你的要求。
