### ISSUE TITLE
怎么实现smartdns在openwrt守护进程

### ISSUE THREAD

**Issue by LsnmxNB** [pymumu/smartdns#711]
smartdns时不时就自动关闭了，时间也不定时，日志也没看出什么问题，所以请教一下有没有办法在openwrt下守护进程smartdns，监控smartdns状况就自动打开

**Comment by 1phalley** [comment]
AC2100内存128MB，还开别的进程内存够用吗，不知道。建议可以试着定时重启smartdns。

**选择一条规则添加到系统-计划任务里**

- 每隔1小时自动重启smartdns
  0 * * * * service smartdns restart >/dev/null 2>&1

- 每隔6小时自动重启smartdns
  0 */6 * * * service smartdns restart >/dev/null 2>&1

- 每隔15分钟自动重启smartdns
  */15 * * * * service smartdns restart >/dev/null 2>&1

- 每天凌晨4点自动重启smartdns
  0 4 * * * service smartdns restart >/dev/null 2>&1

**Comment by 1phalley** [comment]
可以试着定时重启smartdns

**选择一条规则添加到系统-计划任务里**

- 每隔1小时自动重启smartdns
  0 * * * * service smartdns restart >/dev/null 2>&1

- 每隔6小时自动重启smartdns
  0 */6 * * * service smartdns restart >/dev/null 2>&1

- 每隔15分钟自动重启smartdns
  */15 * * * * service smartdns restart >/dev/null 2>&1

- 每天凌晨4点自动重启smartdns
  0 4 * * * service smartdns restart >/dev/null 2>&1

**Comment by LsnmxNB** [comment]
> 可以试着定时重启smartdns
> 
> **选择一条规则添加到系统-计划任务里**
> 
> * 每隔1小时自动重启smartdns
>   0 * * * * service smartdns restart >/dev/null 2>&1
> * 每隔6小时自动重启smartdns
>   0 */6 * * * service smartdns restart >/dev/null 2>&1
> * 每隔15分钟自动重启smartdns
>   */15 * * * * service smartdns restart >/dev/null 2>&1
> * 每天凌晨4点自动重启smartdns
>   0 4 * * * service smartdns restart >/dev/null 2>&1

这个不是好办法，不知道怎么现实系统级的openwrt守护进程，只要smartdns自动退去就自动启动~~~~
谢谢

**Comment by 1phalley** [comment]
> 这个不是好办法，不知道怎么现实系统级的openwrt守护进程，只要smartdns自动退去就自动启动~~~~
> 谢谢

下载我刚写的[smartdns自动守护脚本](https://github.com/1phalley/smartdnsprocd/raw/main/smartdnsprocd)

说明：
OpenWrt上Smartdns的自动守护进程，监控smartdns运行状态，在崩溃时自动重启。

使用方法：
将smartdnsprocd文件放到 /etc/init.d 目录下执行 chmod 755 smartdnsprocd 赋予权限
开机自启 service smartdnsprocd enable
开始监控 service smartdnsprocd start
停止监控 service smartdnsprocd stop

查看效果：
执行 pgrep smartdns 查看smartdns的进程号
执行 kill -s 9 进程号 杀死进程，此时再快速执行 pgrep smartdns 应该不会有smartdns进程号出现
等待几秒后执行 pgrep smartdns 发现smartdns以新的进程号启动成功

[Github项目地址](https://github.com/1phalley/smartdnsprocd)

**Comment by LsnmxNB** [comment]
> > 这个不是好办法，不知道怎么现实系统级的openwrt守护进程，只要smartdns自动退去就自动启动~~~~
> > 谢谢
> 
> 下载我刚写的[smartdns自动守护脚本](https://github.com/1phalley/smartdnsprocd/raw/main/smartdnsprocd)（右键链接另存为smartdnsprocd，不带后缀）
> 
> 说明：
> OpenWrt上Smartdns的自动守护进程，监控smartdns运行状态，在崩溃时自动重启。
> 
> 使用方法：
> 将smartdnsprocd文件放到 /etc/init.d 目录下执行 chmod 755 smartdnsprocd 赋予权限
> 开机自启 service smartdnsprocd enable
> 开始监控 service smartdnsprocd start
> 停止监控 service smartdnsprocd stop
> 
> 查看效果：
> 执行 pgrep smartdns 查看smartdns的进程号
> 执行 kill -s 9 进程号 杀死进程，此时再快速执行 pgrep smartdns 应该不会有smartdns进程号出现
> 等待几秒后执行 pgrep smartdns 发现smartdns以新的进程号启动成功
> 
> [Github项目地址](https://github.com/1phalley/smartdnsprocd)

牛逼啊，太感谢大佬了
将smartdnsprocd文件放到 /etc/init.d 目录下执行 chmod 755 /etc/init.d/smartdnsprocd 赋予权限
这样更直接不用再cd到 /etc/init.d 目录下才能执行 chmod 755

**Comment by wy16W2pIilK1xgqN** [comment]
自动重启倒是好解决。
现在的动不动就僵死，CPU 占用超高。

**Comment by sklohk** [comment]
smartdns 本身已经是守护启动了，但的确不时会停止或失效，请阅读作者的readme，里面有详细说明不同模式如何测试是否生效，然后写个script，定时检查，失效时就重启。
1. 用ubus call service list，检测smartdns 是否 runnning
2. 用 uci 读取smartdns config, 确定运行模式
3. 按readme的检测方法检测，dnsmasq upstream 模式，用 nslookup  或 dig 检测 baidu.com 是否只回应一个地址
4. redirect 模式，用作者提供的 iptables cmd 检测重导rule 是否存在

**Comment by pymumu** [comment]
进程已经是守护进程了，可能存在连续异常，导致服务没有重启。
后面我检查一下脚本是不是有问题。

**Comment by xiaobaishu1** [comment]
> 进程已经是守护进程了，可能存在连续异常，导致服务没有重启。
> 后面我检查一下脚本是不是有问题。

用迅雷下载最容易崩了 虽然显示还在运行 但是任何网站都无法解析打开了

**Comment by pymumu** [comment]
用最新代码尝试。

**Comment by LsnmxNB** [comment]
> 用最新代码尝试。

大佬能不能编译一个测试版出来，不会自己编译啊

**Comment by PikuZheng** [comment]
> > 用最新代码尝试。
> 
> 大佬能不能编译一个测试版出来，不会自己编译啊
可以试试我编译的版本
https://github.com/PikuZheng/smartdns/releases/tag/v36.16
