### ISSUE TITLE
小米9故意内置隐藏的114DNS污染了路由器海外DNS解析结果

### ISSUE THREAD

**Issue by 1phalley** [pymumu/smartdns#712]
- **小米的隐藏DNS是什么？**

WiFi 高级设置都会提供两个DNS栏位，但小米某些型号的手机内置了第三个DNS无法去掉，不通过特殊手段不会知道它的存在。我的小米9内置的是 114.114.114.114，而 红米5 plus 却没有内置额外的DNS。如果你的小米9用的 MIUI11，在终端模拟器输入 _getprop | grep dns_ 就会看到第三个DNS是 114.114.114.114。

- **它干扰DNS解析对手机电脑使用的影响？**

2019 年，在小米9上每次刚开 WiFi 还能看 YouTube 客户端，用个十几分钟就无法访问了，再看电脑上却没问题。用防火墙阻断 114DNS 解析解决了此问题。
前几天，也许是小米9更新了几个系统应用后，问题复现，不同的是，电脑也受到了影响无法访问。又增加了一条防火墙规则解决了此问题。

- **如何发现小米9是污染源的？**

实属偶然，2019 年是用小米9打开 [Whoer匿名性检测](https://whoer.net/zh) 却看到了奇怪的DNS。通过OpenWrt的状态-实时信息证实了小米9同时向 Dnsmasq 的53端口和 114.114.114.114:53 查询DNS。现在已经有了专门的 [DNS泄露检查](https://whoer.net/zh/dns-leak-test)，和电脑的结果对比看看你的手机有没有第三个DNS吧。

- **DNS污染方式猜测**

猜测2019年是114的DNS结果覆盖污染了小米9本地的正确解析结果，所以电脑上其他手机上都没有受到影响。今年是某种申必方式影响到了OpenWrt上的DNS缓存，至于是dnsmasq的缓存还是smartdns的缓存就没去排查了。在DNS污染后，重启smartdns必然能恢复正常，验证了十几次。我ssh到OpenWrt上用 dig www.youtube.com -p 5335 也就是指定用海外DNS解析能出正确结果，内网设备都能恢复正常解析了（等几分钟又会被污染）。

- **我做了那些尝试？**

下面的防火墙语句目的是为了劫持内网所有向外的DNS查询都转到OpenWrt路由53端口，但似乎没起作用。
_iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53_

在这种情况下，2019年我添加的防火墙规则如下，成功阻止了小米9单独向114查询DNS

![image](https://user-images.githubusercontent.com/35102295/113734399-e5d20180-972d-11eb-92e7-88695f98f40f.png)

前几天也许是手机更新了一个"三方应用异常分析"系统APP 后上面的规则突然无效了，试着添加的另一条规则成功屏蔽了小米向114DNS请求解析：

![image](https://user-images.githubusercontent.com/35102295/113734549-026e3980-972e-11eb-8ac5-bb4f7bc73e6c.png)

2019年的规则范围更大却无效，新的规则范围更小居然有用，没能理解。

**Comment by keeno1982** [comment]
我有一只小米9SE，最近升级到12.5.1后发现谷歌商店和油管全都没法用了，我勒个去

**Comment by xyxu1024** [comment]
我使用了dnschanger

**Comment by 1phalley** [comment]
> 我使用了dnschanger

我也是，没想到有人遇到了跟我一样的问题。

**Comment by 1phalley** [comment]
> 我有一只小米9SE，最近升级到12.5.1后发现谷歌商店和油管全都没法用了，我勒个去

没准儿你也遇到了它内置114dns查询导致的dns污染。清除缓存、结束应用、重启手机后用手机的翻墙客户端能连上，而单纯WIFI用路由的代理连不上多半就是被dns污染了

**Comment by xyxu1024** [comment]
我倒没有遇到你的问题@1phalley，用dnschange主要是因为wifi设置里根本就没有修改ipv6 dns的地方，我是用旁路由代理的，ipv4 dns可以指向旁路有，但是ipv6只能指向主路由且无法修改，所以用的dnschange把ipv6 dns指向::1

**Comment by BGzErol** [comment]
试试防火墙劫持53端口？

**Comment by 1phalley** [comment]
> 试试防火墙劫持53端口，应该可以强制指向网关

曾经有用，

**Comment by BGzErol** [comment]
> > 试试防火墙劫持53端口，应该可以强制指向网关
> 
> 曾经有用，

如果开了ipv6的话只劫持v4是不行的
还得这样来劫持v6
ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

**Comment by 1phalley** [comment]
> 如果开了ipv6的话只劫持v4是不行的
> 还得这样来劫持v6
> ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
> ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

感谢回复，但是此方法刚尝试了无效，我是OpenWrt作从路由，之前在爱快主路由已经将 v6DNS 设置为从路由OpenWrt了
关了smartdns里所有dns，使用whoer依然能查出111.7.223.98和111.7.223.99广东移动的ip，而我并不在广东，理论上应该是一个dns结果都不会出现。

**Comment by 15108428326** [comment]
53端口到53端口？能这样用么？确定此时smartdns有作用？

**Comment by 15108428326** [comment]
53端口到53端口？能这样用么？确定此时smartdns有作用？

**Comment by 15108428326** [comment]
如果smartdns按上述能工作，则试试这样
iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:53

**Comment by 15108428326** [comment]
可以将后面的53改为smartdns的端口号

**Comment by 1phalley** [comment]
> 其实miui是有两个内置dns 114.114.114.114 和240c::6666 ,最简单方法是路由器配置iptables把这两个地址的53端口给墙掉,这样它就只好乖乖用路由器下发的dns了

破案了，是我在Openwrt配置转发规则时没有勾选下面的星期一到星期日，导致规则是对的，但是从没开始执行过...... 这两个dns也屏蔽成功，感谢补充的240c::6666

**Comment by cnnbgo** [comment]
miui11无故DNS被污染，网上说法有内置DNS和某cn域名作怪，旁路由开全局也没用。折腾几天，无奈只能简单粗暴完美解决：
iptables -I FORWARD 1 -p udp -j REJECT
iptables -I FORWARD 2 -p tcp -j REJECT
然后开全局

**Comment by xspeed1989** [comment]
Mi10 Pro最新稳定版遇到同样的问题，
OpenWrt将发送到114的的53端口流量转发到路由器就可以了，让他用114查吧，最终还是查的路由器的DNS
![image](https://user-images.githubusercontent.com/5162926/143274628-e4bc1676-88f8-44a8-adc6-5ab521b80c8e.png)

**Comment by X-Bird** [comment]
Mi10 也遇到这个问题，原来不是我一个人
调试了好久突然觉得可能有隐藏dns，换了关键词谷歌找到这唯一的帖子
iptable没搞明白，直接用的dnschanger解决

**Comment by xe5700** [comment]
其实你路由器设两个IP就行了 是安卓的特性 只有一个DNS服务器会自动加8.8.8.8作为备用服务器 国内系统本地化改成了114.114.114.114 之类的

**Comment by X-Bird** [comment]
> 其实你路由器设两个IP就行了 是安卓的特性 只有一个DNS服务器会自动加8.8.8.8作为备用服务器 国内系统本地化改成了114.114.114.114 之类的

没用的，你试下就知道了。

**Comment by xe5700** [comment]
我试过有两个DNS就不会添加114.114.114.114或者8.8.8.8

**Comment by xe5700** [comment]
> > 其实你路由器设两个IP就行了 是安卓的特性 只有一个DNS服务器会自动加8.8.8.8作为备用服务器 国内系统本地化改成了114.114.114.114 之类的
> 
> 没用的，你试下就知道了。

好吧 竟然有三个DNS 小米是不是有毒

**Comment by gogogogood** [comment]
确实是MIUI的问题，而且我iphone也碰到了，应该IOS也有内置114的DNS，之前用ssrp没这问题，换成openclash就出来了

**Comment by onion83** [comment]
ColorOS 14 也有这个问题
![Uploading Screenshot_2024-04-10-15-30-23-99_dd3f83c80b3d9d51366a6ecc1f30ec4b.jpg…]()

**Comment by llllllllqq** [comment]
据说originos也有类似问题
https://www.txrjy.com/thread-1326785-1-1.html

**Comment by PikuZheng** [comment]
> ColorOS 14 也有这个问题 ![Screenshot_2024-04-10-15-30-23-99_dd3f83c80b3d9d51366a6ecc1f30ec4b](https://private-user-images.githubusercontent.com/514467/321146320-839890a5-bab1-43fa-941c-71d40011bf64.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzI4MjcsIm5iZiI6MTcxNDg3MjUyNywicGF0aCI6Ii81MTQ0NjcvMzIxMTQ2MzIwLTgzOTg5MGE1LWJhYjEtNDNmYS05NDFjLTcxZDQwMDExYmY2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMTI4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjQ4NTc4MWU0MWI0NzcxYzMyYmY2MzAzMjNhN2E2NjI3ZGI2MDcwYWZlMmFkYTEzZDU5OWJhNzcwNWYyNzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LJggzhFLbTBj0vAuD9isbT4Llou94cmasz_Q77FC61Q)

坑，才知道有这个问题

**Comment by Ovear** [comment]
> ColorOS 14 也有这个问题 

@onion83 请问这个是什么软件？

**Comment by PikuZheng** [comment]
> > ColorOS 14 也有这个问题
> 
> @onion83 请问这个是什么软件？

analiti 包名是 com.analiti.fastest.android

**Comment by qian9008** [comment]
coloros 同，已经路由器上屏蔽，但是有时候会出现无法解析情况，需要重启wifi。。

**Comment by qian9008** [comment]
uci add firewall redirect
uci set firewall.@redirect[-1].name='dns_114_to_local'
uci set firewall.@redirect[-1].src='lan'
uci set firewall.@redirect[-1].proto='tcp udp'
uci set firewall.@redirect[-1].src_dip='114.114.114.114'
uci set firewall.@redirect[-1].src_dport='53'
uci set firewall.@redirect[-1].dest='lan'
uci set firewall.@redirect[-1].dest_ip='127.0.0.1'
uci set firewall.@redirect[-1].dest_port='53'

uci commit firewall
fw4 reload
