### ISSUE TITLE
请问我想要这个效果，该怎么做到呢

### ISSUE THREAD

**Issue by Karmylr** [pymumu/smartdns#713]
请问我想要这个效果该怎么办：国内的域名由指定的几个dns服务器来查询，国外的域名也由指定的服务器来解析，通过geoip来分流。同时因为国内的不同的dns服务器会把竞争对手的域名解析到国外来拖慢速度，所以我希望可以在国内外分开的基础上再自定义几条规则，比如说由dnspod来解析腾讯的域名

求帮助！！！

**Comment by Karmylr** [comment]
感觉国内的域名，谷歌的dns解析慢一点

**Comment by snday** [comment]
你好象要这个效果吧 https://github.com/pymumu/smartdns/issues/656

**Comment by vpei** [comment]
都用国外的来解析，感觉还行，国内的会污染DNS。

**Comment by sklohk** [comment]
作者的readme，应用指导有明确说明，用分区
