### ISSUE TITLE
双栈优选在多cname配置下失效

### ISSUE THREAD

**Issue by felix-fly** [pymumu/smartdns#715]
**问题现象**  
域名使用cname类型，并且存在多条记录，进一步分别解析为v4和v6的ip地址后，会同时返回，启用双栈优选在这种情况下不工作。

**运行环境**
以 `mpay.suning.com` 为例，在Linux服务器上运行 smartdns，配置如下：

`bind [::]:1053`
`server 1.1.1.1`
`dualstack-ip-selection yes`

**重现步骤**

`nslookup -port=1053 mpay.suning.com 127.0.0.1`
`Server:		127.0.0.1`
`Address:	127.0.0.1#1053`

`Non-authoritative answer:`
`mpay.suning.com	canonical name = zqbsuningipv6.v.trpcdn.net.`
`Name:	zqbsuningipv6.v.trpcdn.net`
`Address: 103.104.168.99`
`Name:	zqbsuningipv6.v.trpcdn.net`
`Address: 2405:fd80:a10::b`

**信息收集**  

[smartdns.log](https://github.com/pymumu/smartdns/files/6364055/smartdns.log)

**Comment by kulongwangzhi85** [comment]
我也遇到了，有个域名是别名，并且只有IPV6。开启后经常解析不到ipv6地址。关闭了就没问题

**Comment by pymumu** [comment]
用最新代码
