### ISSUE TITLE
smartdns配置文件和address.conf最大条目

### ISSUE THREAD

**Issue by jiayuqian** [pymumu/smartdns#717]
**问题现象**  
1. 请问对smartdns配置文件的理解是否正确，如下：
/etc/config/smartdns     =>对应General Settings和Upstream Servers？
/etc/smartdns/smartdns.conf  =>在openwrt中这个配置只是一个示例文件吗？
/etc/smartdns/custom.conf =>对应General Settings
/etc/smartdns/address.conf  =>对应Set Specific domain ip address.？

2.请问smart FAQ，第6点中提到，如设置server group，server 192.168.1.1 -group home -exclude-default-group
在smartdns - 1.2020.09.08-2235版本中，server group的配置是否被移到了，option server_group中，如下：
config server
	option enabled '1'
	option type 'udp'
	option name 'pdns.dnspod.cn'
	option blacklist_ip '0'
	option ip '119.29.29.29'
	option server_group 'cndns'

3.请问address.conf最大支持的条目是否存在限制，有一份accelerated-domains.china.conf文件，约69774条。已作为附件上传。
luci-smartdns->domain ip address未能显示，如果手动黏贴，提示：如少量黏贴则不报错。
==========
Save error
An error occurred while saving the form:

Invalid argument
==========

**运行环境**
1. 固件型号:Linux openwrtv19_test 4.14.221 #0 SMP Mon Feb 15 15:22:37 2021 x86_64 GNU/Linux
2. smartdns：smartdns - 1.2020.09.08-2235
3. 运营商 : 中国电信

**重现步骤**
1. 上游DNS配置。  1.1.1.1，8.8.8.8，223.5.5.5，119.29.29.29

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[address.zip](https://github.com/pymumu/smartdns/files/6370505/address.zip)

**Comment by vpei** [comment]
等大佬更新

**Comment by pymumu** [comment]
这个是luci的限制，可以使用外部文件引入。
