### ISSUE TITLE
关于smartdns屏蔽域名问题

### ISSUE THREAD

**Issue by 15108428326** [pymumu/smartdns#719]
smartdns里设置
address /.douyin.com/#
或
address /douyin.com/#
均只能屏蔽
xxx.douyin.com
而
douyin.com还是能获取ip并ping通，
无法达到完全屏蔽效果
那么，要屏蔽xxx.douyin.com与douyin.com改如何设置

**Comment by chainofhonor** [comment]
试试 手动设置hosts  把douyin.com返回127.0.0.1
