### ISSUE TITLE
建议增加屏蔽某个域名IPv4/v6的功能

### ISSUE THREAD

**Issue by ziyuedi** [pymumu/smartdns#72]
**需求应用场景**
有时某个网站同时配置了IPv4和v6，但v4/v6不能访问

**建议的方案**
配置文件中增加参数允许指定
指定的域名v4/v6返回SOA

**Comment by pymumu** [comment]
release 19已经支持，参考address的配置说明

address /domain.example.com/# 返回SOA
address /domain.example.com/#4 A地址返回SOA
address /domain.example.com/#6 AAAA地址返回SOA
address /domain.example.com/- 忽略规则。
