### ISSUE TITLE
可否忽略某些特殊网址的特殊解析到127.0.0.1

### ISSUE THREAD

**Issue by thofd** [pymumu/smartdns#722]
**需求应用场景**
访问hackp.com的时候会解析到127.0.0.1，我本人并不是很懂，我推测是该网站管理员为了防止攻击做了特殊的解析指向127.0.0.1，而我们smartdns是取得了一个最快的IP返回给客户端（也就是127.0.0.1），所以出现了网址不能访问的情况，还请大侠鉴定，感谢

**建议的方案**
建议smartdns如果获取到127.0.0.1的IP可以在客户端忽略

**设备信息**
1. 设备信息（CPU，厂家）  
X86 OPENWRT
2. 固件信息
OpenWrt R21.4.18 GDQ v5.1[2021] Compiled by eSir / LuCI Master (git-21.114.56541-974fb04)

**Comment by thofd** [comment]
研究了一下，看到选项里面有一个跳过测速的选项，打勾，貌似不会解析到127.0.0.1了

**Comment by thofd** [comment]
上面的这个方法不对，我把smartdns停止再启动就会好个一天，第二天还是会解析到127.0.0.1

**Comment by i-sususu** [comment]
设置blacklist-ip 127.0.0.1也许可行

**Comment by bdzwater** [comment]
试试这个
bogus-nxdomain 0.0.0.0/16
bogus-nxdomain 127.0.0.0/16

**Comment by pymumu** [comment]
用最新代码
