### ISSUE TITLE
自定义设置：添加HTTPS iP DNS 参数无效 ?!

### ISSUE THREAD

**Issue by 57382** [pymumu/smartdns#724]
**问题现象**  
网站DNS解析失败，找不到DNS

**运行环境**
固件型号  OpenWrt Official

**重现步骤**
1. 复制粘贴如下内容至自定义设置：
server-https https://104.16.248.249/dns-query -host-name cloudflare-dns.com
server-https https://146.112.41.2/dns-query -host-name doh.opendns.com
（PS：在GUI填入上面两个DOH iP服务器测试DNS解析都是成功的，网站成功打开
2. 网站DNS解析失败，找不到DNS

https://github.com/pymumu/smartdns/issues/149
新版smartdns参数改了？

Thanks♪(･ω･)ﾉ

**Comment by pymumu** [comment]
参考https://pymumu.github.io/smartdns/config/basic-config/
