### ISSUE TITLE
最新smartdns的HTTPS(DOH)支持DNSSEC吗？

### ISSUE THREAD

**Issue by 57382** [pymumu/smartdns#725]
https://DNSSEC.vs.uni-due.de/
如题，用上面测试HTTPS(DOH)是支持的。实际支持吗？

https://github.com/pymumu/smartdns/issues/19 不会支持DNSSEC

Thanks♪(･ω･)ﾉ

**Comment by pymumu** [comment]
支持PROXY_DNSSEC功能。关闭测速的时候会启用。
