### ISSUE TITLE
openwrt系统  人在国外   打开smartdns以后line就发不出去消息  关了才可以

### ISSUE THREAD

**Issue by fayswing** [pymumu/smartdns#728]
openwrt系统  人在国外   打开smartdns以后line就发不出去消息  关了才可以

有大佬碰到同等情况吗

有大佬能给出解决方法不     小白跪谢

**Comment by chunlee8189** [comment]
你是不是用openwrt 做旁路由？
如果是的话应该是只有设定一个LAN网路，透过openwrt旁路由上网对吧！
我也是这样！ 手机可以收发很诡异，但电脑版一直无法登入或者发消息会延迟。

解决办法： 到openwrt的预设防火墙的wan口全部改成lan口就可以了。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
