### ISSUE TITLE
Win10环境（非WSL）下运行

### ISSUE THREAD

**Issue by railjty** [pymumu/smartdns#729]
**需求应用场景**
Win10环境（非WSL）下运行（.exe文件），而不是在WSL环境中运行

**建议的方案**
让代码可以在cygwin中编译
![image](https://user-images.githubusercontent.com/30927889/124297959-47b7d100-db8e-11eb-8027-845a611c61eb.png)
目前cygwin是做不到编译smartdns的，而mingw64没有Linux头文件，更不可能
**设备信息**
1. 设备信息（CPU，厂家）  
x86_64
2. 固件信息
Windows 10 x64

**Comment by railjty** [comment]
cygwin模拟linux运行环境，理论上可以编译的，个人曾经在cygwin中编译出haproxy（有SSL支持的）

**Comment by pymumu** [comment]
cygwin可以直接编译才对。你可以尝试。

**Comment by DreamChaser-luzeyu** [comment]
> cygwin可以直接编译才对。你可以尝试。

`dns_client.c`中使用了Linux的epoll，cygwin不支持。无法在不修改源代码的情况下编译为Windows版本。
