### ISSUE TITLE
ipset 使用疑问

### ISSUE THREAD

**Issue by anglabace** [pymumu/smartdns#731]
之前看到一个issue
您回复了个用法
#ipset /xxx/-   ignore rules for all 
#ipset /xxx/name   ipset with ipset name, try both ipv4 and ipv6 with ipset name
#ipset /xxx/#4:name   ipv4 with ipset name, ipv6 is not set, and rules inherit from parent ipv6 rules。
#ipset /xxx/#6:name   ipv6 with ipset name, ipv4 is not set, and rules inherit from parent ipv4 rules.
#ipset /xxx/#4:name1,#6:name2  ipv4 with name1, ipv6 with name2.
#ipset /xxx/#4:-,#6:name   ignore ipv4 rules, ipv6 with name.
#ipset /xxx/#4:name,#6:-   ipv4 with ipset name, ignore ipv6 rules.

我今天试了下
ipset /xxx/#4:name,#6:-
这个用法导致smartDns 无法启动

**Comment by zonyitoo** [comment]
https://github.com/pymumu/smartdns/pull/718

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
