### ISSUE TITLE
很长时间没有更新维护了，是这个项目完结了么

### ISSUE THREAD

**Issue by haidaoyy** [pymumu/smartdns#732]
RT

**Comment by vpei** [comment]
RT

**Comment by namebuhtig** [comment]
更了一下

**Comment by vpei** [comment]
openwrt编译好像还没有更新。

**Comment by LsnmxNB** [comment]
> 反正5.10内核的不能用了

呵呵，怎么我的5.10内核就行？

**Comment by namebuhtig** [comment]
> > 反正5.10内核的不能用了
> 
> 呵呵，怎么我的5.10内核就行？

呵呵，这他妈都会有优越感？

**Comment by LsnmxNB** [comment]
> > > 反正5.10内核的不能用了
> > 
> > 
> > 呵呵，怎么我的5.10内核就行？
> 
> 呵呵，这他妈都会有优越感？

你自己开车又不学驾照，能怪谁，别人都能在5.10内核下运行，自己不找原因，在这发劳骚有用？

**Comment by namebuhtig** [comment]
> > > > 反正5.10内核的不能用了
> > > 
> > > 
> > > 呵呵，怎么我的5.10内核就行？
> > 
> > 呵呵，这他妈都会有优越感？
> 
> 你自己开车又不学驾照，能怪谁，别人都能在5.10内核下运行，自己不找原因，在这发劳骚有用？

你能运行别人就都能运行？不找原因来issues？呵呵智障

**Comment by LsnmxNB** [comment]
> > > > > 反正5.10内核的不能用了
> > > > 
> > > > 
> > > > 呵呵，怎么我的5.10内核就行？
> > > 
> > > 
> > > 呵呵，这他妈都会有优越感？
> > 
> > 
> > 你自己开车又不学驾照，能怪谁，别人都能在5.10内核下运行，自己不找原因，在这发劳骚有用？
> 
> 你能运行别人就都能运行？不找原因来issues？呵呵智障

@pymumu 大佬麻烦关了这种没营养的issues，人身功鸡就算了，净在这发劳骚，连log都不发上来

**Comment by namebuhtig** [comment]
> > > > > > 反正5.10内核的不能用了
> > > > > 
> > > > > 
> > > > > 呵呵，怎么我的5.10内核就行？
> > > > 
> > > > 
> > > > 呵呵，这他妈都会有优越感？
> > > 
> > > 
> > > 你自己开车又不学驾照，能怪谁，别人都能在5.10内核下运行，自己不找原因，在这发劳骚有用？
> > 
> > 你能运行别人就都能运行？不找原因来issues？呵呵智障
> 
> @pymumu 大佬麻烦关了这种没营养的issues，人身功鸡就算了，净在这发劳骚，连log都不发上来

呵呵
