### ISSUE TITLE
大佬们帮我看下这个是什么问题

### ISSUE THREAD

**Issue by shinegod** [pymumu/smartdns#735]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
openwrt lede  x86
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
![image](https://user-images.githubusercontent.com/22977415/127610096-e04c8d3b-17a7-4148-8ced-e7d28563988b.png)

2. 访问的域名。  
![local-file--3752399969474164950](https://user-images.githubusercontent.com/22977415/127610073-527e977a-bee4-41ab-a431-143edac829fb.jpg)

**Comment by bdzwater** [comment]
看上去像是IPV6有问题，无法联网，试试直接PING运营商的IPV6 DNS地址看能不能PING通（不要用域名）
