### ISSUE TITLE
IPset 使用问题

### ISSUE THREAD

**Issue by anglabace** [pymumu/smartdns#736]
当smartdns 作为 dnsmasq上级dns时 ipset 并不会命中
ipset /cgbchina.com.cn/#4:bank
ipset /cebbank.com/#4:bank
ipset /hsbc.com.cn/#4:bank
ipset /icbc.com.cn/#4:bank
ipset /ccb.com/#4:bank
ipset /abchina.com/#4:bank
ipset /boc.cn/#4:bank
ipset /ecitic.com/#4:bank
ipset /cmbchina.com/#4:bank
ipset /cebbank.com/#4:bank
ipset /psbc.com/#4:bank
ipset /pingan.com/#4:bank
ipset /spdb.com.cn/#4:bank
ipset /cib.com.cn/#4:bank
ipset /signix.net/#4:bank
ipset /95559.com.cn/#4:bank
ipset /hxb.com.cn/#4:bank
ipset /cmbc.com.cn/#4:bank
ipset /chinaums.com/#4:bank

root@Router:~# ipset list bank
Name: bank
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 456
References: 1
Number of entries: 0
Members:

root@TRC-MainRouter:~# 

@zonyitoo

**Comment by zonyitoo** [comment]
为什么要AT我呢？

会不会命中，你可以实验一下直接用`dig`来访问smartdns的IP和端口，然后打开smartdns的debug日志，看看有没有`IPSET`开头的日志不就好了。

**Comment by anglabace** [comment]
> 为什么要AT我呢？
> 
> 会不会命中，你可以实验一下直接用`dig`来访问smartdns的IP和端口，然后打开smartdns的debug日志，看看有没有`IPSET`开头的日志不就好了。

因为您不是参与维护开发的嘛。

**Comment by zonyitoo** [comment]
从你的日志看很明显用的不是master编译的版本，重新编译一个吧
https://github.com/pymumu/smartdns/blob/b77cea63e9eecd45ab257906868c77baec27e6b7/src/dns_server.c#L713-L715

感觉可以close了。

**Comment by zonyitoo** [comment]
@pymumu Please consider make a new release.

**Comment by VergilGao** [comment]
目前openwrt-package 21.02 还是很老的版本
https://github.com/openwrt/packages/blob/openwrt-21.02/net/smartdns/Makefile
而且并没有包含luci界面

**Comment by anglabace** [comment]
> 从你的日志看很明显用的不是master编译的版本，把`#4:bank` 作为ipset名字了。重新编译一个吧
> https://github.com/pymumu/smartdns/blob/b77cea63e9eecd45ab257906868c77baec27e6b7/src/dns_server.c#L713-L715
> 
> 感觉可以close了。

是的我手动合并的一个版本。因为那个时候还未正式合并到master

**Comment by ixmu** [comment]
请问，这个问题最终如何解决
ipset /google.com/gfwlist
ipset /youtube.com/gfwlist
并没有自动加入gfwlist

**Comment by recall704** [comment]
需要注意的是，smartdns 运行的账号如果不是 root，需要有 ipset 权限才能正常将解析后的 ip 加入到 ipset 中

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
