### ISSUE TITLE
希望可以增加Windows客户端版本

### ISSUE THREAD

**Issue by KelvinSoh8** [pymumu/smartdns#739]
**需求应用场景**
用户在没有open wrt设备下
可以直接在电脑里使用本地的Smart DNS客户端

**建议的方案**
希望Smart DNS可以让我们增加经常访问的网址
这样就可以定时进行更新，刷新了

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by pymumu** [comment]
用WSL，具体看ReadMe
