### ISSUE TITLE
解析结果出现污染现象

### ISSUE THREAD

**Issue by shikkoku** [pymumu/smartdns#74]
重启SmartDNS后，得出正确的解析，但是过了几分钟后结果就出现污染

nslookup www.google.com
Server:  smartdns
Address:  fd8b:78c5:a68a::1

Non-authoritative answer:
Name:    www.google.com
Addresses:  2404:6800:4005:80f::2004
          216.58.197.100

nslookup www.google.com
Server:  smartdns
Address:  fd8b:78c5:a68a::1

Non-authoritative answer:
Name:    www.google.com.lan
Address:  31.13.83.1

附上设置
``
config smartdns
	option server_name 'smartdns'
	option port '5335'
	option rr_ttl_min '300'
	option coredump '0'
	option enabled '1'
	option dualstack_ip_selection '0'
	option tcp_server '1'
	option ipv6_server '1'
	option cache_size '4096'
	option redirect 'redirect'
	list old_redirect 'redirect'
	list old_port '5335'
	list old_enabled '1'

config server
	option enabled '1'
	option name 'Public DNS Plus'
	option ip '119.29.29.29'
	option type 'udp'
	option port '53'
	option blacklist_ip '1'
	option check_edns '0'

config server
	option enabled '1'
	option name 'Google DNS'
	option ip '8.8.8.8'
	option port '53'
	option type 'tcp'

config server
	option enabled '1'
	option type 'udp'
	option name 'CHN-CT DNS'
	option ip '202.96.128.86'
	option port '53'
	option blacklist_ip '1'
	option check_edns '0'

config server
	option enabled '1'
	option name 'Cloudflare DNS'
	option ip '1.1.1.1'
	option port '53'
	option type 'tcp'

config server
	option enabled '1'
	option name 'OpenDNS'
	option ip '208.67.222.123'
	option port '53'
	option type 'tcp'

config server
	option enabled '1'
	option name '114DNS'
	option ip '114.114.114.114'
	option port '53'
	option type 'tcp'

config server
	option enabled '1'
	option name 'AliDNS'
	option ip '223.5.5.5'
	option port '53'
	option type 'udp'
	option blacklist_ip '1'
	option check_edns '0'
`

**Comment by shikkoku** [comment]
> 配置不合理，使用要这样：
> 
> 1. 国外的UDP接口的DNS，要开启“反回答伪造”
> 2. 国内的要配置启用-blacklist_ip，单独使用blacklist_ip配置指定黑名单IP。ip黑名单列表，可以github搜索一下。
> 
> 比如8.8.8.8，启用反回答伪造。
> 114.114.114.114， 启用IP黑名单。
> 
> 如果不想用IP黑名单，也是可以的。多配置几个国外的服务器，都启用"反回答伪造"

好的我开启反回答伪造再试试，但我的国外服务器没有使用UDP查询，全部都是TCP模式的，我已经设置了3组国外DNS服务器。

**Comment by shikkoku** [comment]
讲海外DNS换成53端口UDP查询，并开启反回答伪造（check_edns），依然会产生污染结果，是否和SR服务影响？但是SR服务里我已经设置使用本地5335的DNS服务/

**Comment by pymumu** [comment]
要确保是真的国外DNS，移动的劫持比较厉害，ping小于20ms的都是假的。
SR服务是什么？

**Comment by shikkoku** [comment]
> 要确保是真的国外DNS，移动的劫持比较厉害，ping小于20ms的都是假的。
> SR服务是什么？

![7a7e79b8-3343-4110-bc46-803252f1b1f9 png](https://user-images.githubusercontent.com/4697177/51786369-4785a100-219e-11e9-88e3-c8dab5da169d.jpg)

我是中国电信线路，海外DNS我尝试用TCP查询(dig www.google.com @1.1.1.1 +tcp)，可以解析出正确地址。

`; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.google.com @1.1.1.1 +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24368
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         271     IN      A       216.58.199.228

;; Query time: 6273 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sat Jan 26 19:13:06 DST 2019
;; MSG SIZE  rcvd: 59`

**Comment by pymumu** [comment]
server 1.1.1.1 -check-edns
server 1.0.0.1 -check-edns
server 8.8.8.8 -check-edns
server 8.8.4.4 -check-edns
server 114.114.114.114
server 208.67.222.222 -check-edns
server 202.96.134.133 
server 202.141.178.13:5353 
server 202.141.162.123:53 
server 101.6.6.6
server 80.80.80.80  -check-edns

我的配置，基本没有污染，你可以试试。

**Comment by pymumu** [comment]
最保险的还是使用blacklist-ip参数，直接过滤掉污染IP。这样100%不会污染了。

**Comment by pymumu** [comment]
搜“污染IP”

**Comment by fonlan** [comment]
> 可以自己构造：
> windows用下面的命令：
> nslookup [www.google.com](http://www.google.com) 8.8.8.8
> 
> 将返回的结果增加子网/22，假设返回1.2.3.4
> 那规则就是
> 1.2.3.4/22
> 
> 依次类推：
> 多查询几次，直到没有新的网段出现（前2个数字）。

应该是增加掩码/32吧？掩码必须填吗？还是可以不填默认/32？

**Comment by pymumu** [comment]
掩码不是必须，这里/22就是屏蔽整个子网

**Comment by fonlan** [comment]
> 掩码不是必须，这里/22就是屏蔽整个子网

这么确定这个22位掩码的子网都是污染的吗？

**Comment by ztjal** [comment]
有个严重问题，tls真的加密了吗？
我用1.1.1.1 853 tls还是返回被污染的结果。当然每次dig之前已经smartdns restart了。

**Comment by pymumu** [comment]
只保留1.1.1.1配置，还有污染结果？

现在tls只是没做证书校验，加密是肯定的。如果1.1.1.1是仿冒的，那么现在是检查不到的。

**Comment by ztjal** [comment]
是的，只留一个四个1都是一样，像被针对一样，不管怎么搞都是返回31、173之类的假地址，咋天气得放弃路由用回WIN版的dnscrypt-proxy，但今天又好了。

**Comment by pymumu** [comment]
@ztjal 最近在优化稳定性和性能，可以先试一下这个版本。
[smartdns.1.2019.02.10-2329.mipsel_1004kc_dsp.ipk.zip](https://github.com/pymumu/smartdns/files/2849061/smartdns.1.2019.02.10-2329.mipsel_1004kc_dsp.ipk.zip)

**Comment by ztjal** [comment]
@pymumu 
关于稳定性和性能我有个想法，因为这个天平要符合所有人的情况有点难调节，但你可以增加一个“模式”来让人选择。
例如你最初的想法就是“取最快的结果”，这个可以为“性能模式”
平衡调节的结果就叫“稳定模式”
还有个想法，就是不管如何先返回一个解释结果（TTL同样返回10秒，只要临时存在一下就够了），然后再进入找最快的过程，这样用户体验相对较好，也能提升稳定性。

**Comment by pymumu** [comment]
@ztjal 
TLS确认有BUG，0008那个还有，你用下面这个试一下。这个TLS应该没有问题。
[smartdns.1.2019.02.11-1132.mipsel_1004kc_dsp.ipk.zip](https://github.com/pymumu/smartdns/files/2850848/smartdns.1.2019.02.11-1132.mipsel_1004kc_dsp.ipk.zip)

**Comment by ztjal** [comment]
smartdns.1.2019.02.11-1132.mipsel_1004kc_dsp
感觉不错，回来一看带下载连接的回复没了？

**Comment by pymumu** [comment]
sorry，删除是因为TLS异常那个问题没有解决掉。
我重新给你一个。这个TLS应该正常了。但原因不明确，SSL内部异常，所以不排除还会crash
[smartdns.1.2019.02.13-0013.mipsel_1004kc_dsp.ipk.zip](https://github.com/pymumu/smartdns/files/2856611/smartdns.1.2019.02.13-0013.mipsel_1004kc_dsp.ipk.zip)
。

**Comment by ztjal** [comment]
smartdns.1.2019.02.13-0022.mipsel_1004kc_dsp
这个出现解释不了域名的情况更加严重，刷新五次才正常，全部用UDP的了。

**Comment by pymumu** [comment]
你用telnet链接一下返回的那些IP地址，看看能否连接成功。

telnet [IP] 80

**Comment by ztjal** [comment]
不是污染问题，感觉是“没去执行解释过程”的问题，是“马上”就直接返回无效域名，smartdns是没崩溃的。
我给你统计一下
smartdns.1.2018.11.03-2215.mipsel_1004kc_dsp，这个是没问题，用得很久了，两小时前装回去了。
smartdns.1.2019.01.07-2334.mipsel_1004kc_dsp，一两个小时内肯定会出现一次“马上”就直接返回无效域名，浏览器刷新三次后至第四次正常解释了。
smartdns.1.2019.01.26-0014.mipsel_1004kc_dsp，同上。
smartdns.1.2019.02.13-0022.mipsel_1004kc_dsp，更严重了，要刷新五次才行了。

**Comment by pymumu** [comment]
你是不是开启了IPV6优选了？
优选的情况下，IPV4比IPV6快的话，请求IPV6地址的时候，会返回无效域名的。

如果开启，你可以尝试关闭

**Comment by ztjal** [comment]
路由我wan口关了ipv6的，lan口还是有的。我WIN10上边也是关了ipv6的。
smartdns设置全部都是不启用和没填的，只有“启用”，“服务器名称”，“本地端口”这三个都是默认的。没有再额外其它配置。
之前在 https://github.com/pymumu/smartdns/issues/82 ，最后我提供的两个日志都是“马上”就直接返回无效域名时的日志。

**Comment by pymumu** [comment]
有没有明确的复现场景。

**Comment by gzelvis** [comment]
> 配置不合理，使用要这样：
> 
> 1. 国外的UDP接口的DNS，要开启“反回答伪造”
> 2. 国内的要配置启用-blacklist_ip，单独使用blacklist_ip配置指定黑名单IP。ip黑名单列表，可以github搜索一下。
> 
> 比如8.8.8.8，启用反回答伪造。
> 114.114.114.114， 启用IP黑名单。
> 
> 如果不想用IP黑名单，也是可以的。多配置几个国外的服务器，都启用"反回答伪造"

是不是如果TLS的国外服务器，就不用那个option check_edns '1' 设置了？

我这里装了smartdns后出现一个问题，某些域名，譬如dropbox.com的，或者google.com.hk的，有时候load很久都load不出来，但大概过几分钟后就很快，然后又一段时间后偶尔又load不出来。。。

**Comment by 2660230880** [comment]
> server 1.1.1.1 -check-edns
> server 1.0.0.1 -check-edns
> server 8.8.8.8 -check-edns
> server 8.8.4.4 -check-edns
> server 114.114.114.114
> server 208.67.222.222 -check-edns
> server 202.96.134.133
> server 202.141.178.13:5353
> server 202.141.162.123:53
> server 101.6.6.6
> server 80.80.80.80 -check-edns
> 
> 我的配置，基本没有污染，你可以试试。

请问下这些配置是填在哪里，可否告知

**Comment by pymumu** [comment]
可以直接放到自定义配置界面
配合blacklist-ip效果更佳

2660230880 <notifications@github.com>于2019年12月3日 周二12:21写道：

**Comment by yeezylife** [comment]
> server 1.1.1.1 -check-edns
> server 1.0.0.1 -check-edns
> server 8.8.8.8 -check-edns
> server 8.8.4.4 -check-edns
> server 114.114.114.114
> server 208.67.222.222 -check-edns
> server 202.96.134.133
> server 202.141.178.13:5353
> server 202.141.162.123:53
> server 101.6.6.6
> server 80.80.80.80 -check-edns
> 
> 我的配置，基本没有污染，你可以试试。

请问已经走doh或者dot了，还有必要开启-check-edns吗 @pymumu
