### ISSUE TITLE
WSL1版本安装时出现问题（Debian与Ubuntu子系统均为此问题）

### ISSUE THREAD

**Issue by xyl23333** [pymumu/smartdns#744]
**问题现象**  
安装好Ubuntu WSL1后，运行‪D:\smartdns\package\windows\install.bat出现：

[sudo] password for aipc:
install: cannot stat 'usr/sbin/smartdns': No such file or directory
Install smartdns failed.
请按任意键继续. . .

**运行环境**

1. 固件型号  

Windows 10 21H1  19043.1110

**Comment by pymumu** [comment]
已经修复
