### ISSUE TITLE
luci界面没中文

### ISSUE THREAD

**Issue by PikuZheng** [pymumu/smartdns#745]
**问题现象**  
luci界面没中文

**运行环境**
1. 固件型号  
OpenWrt 19.07.8 x86_64
已经安装了包 luci luci-base luci-compat luci-i18n-base-zh-cn
luci-app-smartdns.1.2021.08.07-1628.all-luci-all

**重现步骤**

**Comment by pymumu** [comment]
安装包应该没有问题，如果是从release获取的安装包，不需要单独安装语言文件。

**Comment by PikuZheng** [comment]
Chrome缓存的锅
