### ISSUE TITLE
在debian11源上的deb包会覆盖最新版本

### ISSUE THREAD

**Issue by betaxab** [pymumu/smartdns#748]
**问题现象**  
在debian11源上的deb包会覆盖最新版本，debian11源上目前版本为33，而最新版本为34。

**Comment by betaxab** [comment]
@pymumu 您好，该问题都快一年了，这个 debian 包是谁负责维护的呢？能否帮忙反馈一下！

目前源中的还是 33+dfsg-2.1 版本，而最新版本都 36.1 了，dpkg -i 手动安装完了还是会被覆盖。

**Comment by pymumu** [comment]
@cdluminate

**Comment by cdluminate** [comment]
这是软件包版本号问题。以这个包为例：
https://github.com/pymumu/smartdns/releases/download/Release36.1/smartdns.1.2022.04.05-2046.x86_64-debian-all.deb
其中changelog文件的版本为
```
smartdns (1.2018.7.9) stable; urgency=low
```
Debian的版本在 https://tracker.debian.org/pkg/smartdns，stable是 [33+dfsg-2.1]。
安装上游deb包之后因为这个包的版本号会一直被判定为很老
```
~ ❯❯❯❯ dpkg --compare-versions 33+dfsg-2.1 gt 1.2018.7.9; echo $?                              10:46:02
0
```
然后就导致apt/dpkg会决定下载“新版本”来覆盖老版本。

两种解决方式，选一种就好：
1. 上游debian打包可以在changelog里采取和release同步的版本号。可以使用上边dpkg来验证版本号新旧判定。这种情况下，debian的 `33+dfsg-2.1` 仍然会覆盖上游的 `33` 版本，但是就不会覆盖 `34` 了。
2. 如果不想修改debian包的version scheme,可以bump epoch,使得上游debian包永远大于debian的任何版本号。

```
~ ❯❯❯❯ dpkg --compare-versions 33+dfsg-2.1 gt 1:1.2018.7.9; echo $?                            10:46:06
1
```

**Comment by pymumu** [comment]
那编译的时候，改一下changlog里面的版本，应该就可以了吧。

如果是这样，我后面编译脚本刷新下changlog版本号。

**Comment by cdluminate** [comment]
只要changelog的版本能通过dpkg的大小判定即可。我看了一圈其他打包脚本，其实你可以把脚本涉及版本号的地方都改成template。比如 DEBAIN/changelog 版本号为 `@SMARTDNS_VER@`. 然后在build package的脚本里 build之前统一生成一下最新版本号
```shell
export SMARTDNS_VER=xxx
sed -e "s/@SMARTDNS_VER@/${SMARTDNS_VER}/g" -i ...
```
各发行版的内部版本号一致。
