### ISSUE TITLE
某分组DNS全部强制走代理，有个墙外网址开始解析正常，过一阵后会被解析到 a.gtld-servers.net. nstld.verisign-grs.com

### ISSUE THREAD

**Issue by 2eronia** [pymumu/smartdns#749]
**问题现象**  
chinadigitaltimes.net 的解析时不时出问题，service smartdns reload后，解析正常，过一阵后，会返回 NOERROR。

**运行环境**
x86 OpenWrt
SmartDNS Releash 34

**重现步骤**
1. 上游DNS配置。  

```
bind-tcp :7053 -group gfwlist  -blacklist-ip speed-check-mode tcp:443,tcp:80
bind :7053 -group gfwlist  -blacklist-ip speed-check-mode tcp:443,tcp:80

server-https https://8.8.8.8/dns-query -group gfwlist -exclude-default-group -blacklist-ip
server-https https://8.8.4.4/dns-query -group gfwlist -exclude-default-group -blacklist-ip
server-https https://1.1.1.1/dns-query -group gfwlist -exclude-default-group -blacklist-ip
server-https https://1.0.0.1/dns-query -group gfwlist -exclude-default-group -blacklist-ip
```
Passwall 版本为 4-33，已把上面4个IP强制走代理

2. 访问的域名。  
chinadigitaltimes.net

**信息收集**  
日志中偶有
```
Handshake with 8.8.8.8 failed, Connection reset by peer
Handshake with 1.1.1.1 failed, Connection reset by peer
```
这类的错误，平时不影响使用

```
root@OpenWrtLite:~# dig chinadigitaltimes.net @10.10.10.1 -p 7053

; <<>> DiG 9.17.12 <<>> chinadigitaltimes.net @10.10.10.1 -p 7053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6329
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;chinadigitaltimes.net.		IN	A

;; AUTHORITY SECTION:
chinadigitaltimes.net.	0	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 10.10.10.1#7053(10.10.10.1) (UDP)
;; WHEN: Mon Aug 16 20:11:06 HKT 2021
;; MSG SIZE  rcvd: 136
```

如果 service smartdns reload，一段时间内能解析正常

```
root@OpenWrtLite:~# service smartdns reload
root@OpenWrtLite:~# dig chinadigitaltimes.net @10.10.10.1 -p 7053

; <<>> DiG 9.17.12 <<>> chinadigitaltimes.net @10.10.10.1 -p 7053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17209
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;chinadigitaltimes.net.		IN	A

;; ANSWER SECTION:
chinadigitaltimes.net.	720	IN	A	104.22.43.172

;; Query time: 291 msec
;; SERVER: 10.10.10.1#7053(10.10.10.1) (UDP)
;; WHEN: Mon Aug 16 20:12:25 HKT 2021
;; MSG SIZE  rcvd: 76
```

大概10来分钟后，dig chinadigitaltimes.net，
又会解析到 SOA a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400

用AdGuardHome套娃，只把10.10.10.1:7053作为DNS上游，
开始AGH解析正常，10来分钟后，QueryLog 显示 chinadigitaltimes.net 是 Response code: NOERROR

**Comment by z1790** [comment]
ipv6.google.com也是这个情况，我试过要把国内的网址放到一个组，然后国内dns解析这个组。。国内的dns全部排除默认分组，国外的dns不要排除默认分组，这样设置就不会出现你说的这个情况，就是要过一段时间手动更新cn网址的列表比较麻烦。。。所以现在我是smartdns之管国内的。。国外的直接交给passwall了。。

**Comment by 2eronia** [comment]
大概知道什么原因了：
This website chinadigitaltimes.net/ is currently offline. Cloudflare's Always Online™ shows a snapshot of this web page from the Internet Archive's Wayback Machine. To check for the live version, click Refresh.

估计最近网站出了些问题，我猜测根证书服务器解析不到了，解析到也是之前缓存的结果，所以返回了NOERROE

**Comment by 1klakla1** [comment]
你这样设置ip只有谷歌的生效，别的都不会生效。doh最好设个ip的服务器前置解析下

**Comment by Deleted-Account** [comment]
> 你这样设置ip只有谷歌的生效，别的都不会生效。doh最好设个ip的服务器前置解析下

我有在AdGuardHome里面试过
https://8.8.8.8/dns-query
https://8.8.4.4/dns-query
https://1.1.1.1/dns-query
https://1.0.0.1/dns-query
都是可以的
