### ISSUE TITLE
支持将日志打印到 stdout

### ISSUE THREAD

**Issue by poscat0x04** [pymumu/smartdns#753]
目前 smartdns 只支持将日志写到 log-file, 希望能支持将日志打印到 stdout, 这样用 systemd 运行 smartdns 时可以用 journald 查看和管理 smartdns 的日志

**Comment by pymumu** [comment]
修改配置文件：/etc/default/smartdns如下
SMART_DNS_OPTS=“-f -x”

**Comment by PikuZheng** [comment]
> 修改配置文件：/etc/default/smartdns如下
> SMART_DNS_OPTS=“-f -x”
将`'/usr/sbin/smartdns' '-f'` 修改为`'/usr/sbin/smartdns' '-f -x'`
报以下错误：
```
/usr/sbin/smartdns: invalid option -- ' '
/usr/sbin/smartdns: invalid option -- '-'
```

**Comment by nuzar** [comment]
添加`-f`参数后，systemd service 中需要修改 `Type=simple`
