### ISSUE TITLE
address的忽略或直接返回SOA不生效

### ISSUE THREAD

**Issue by 523860169** [pymumu/smartdns#76]
下面规则不生效，www.joram.it还是可以获取到aaaa规则
`address /.joram.it/-6
`
`address /.joram.it/#6
`
`address /www.joram.it/-6
`
`address /www.joram.it/#6
`

**Comment by pymumu** [comment]
忽略规则不支持单独对A，AAAA地址。并且忽略的规则是最高优先级的

所以，你的配置，等于没有配置任何规则。

**Comment by 523860169** [comment]
@pymumu 没看懂。所以如果要实现这个，规则应该是怎么样的

**Comment by fonlan** [comment]
关于这个功能我就遇到一个坑，Chrome浏览器如果是通过代理去访问某个网页的那么DNS解析也是由那个代理来完成的，本地的DNS解析屏蔽是无效的。

**Comment by pymumu** [comment]
address是指定域名对应的IP地址，#号表示域名返回SOA，-表示按常规模式测速返回。

-的用途主要是排查规则。

比如
address /example.com/#

但想放开open.example.com，那配置如下。
address /open.example.com/-

**Comment by 523860169** [comment]
@pymumu #是直接返回SOA，而不向上游查询对吗？

**Comment by 523860169** [comment]
我要功能就是不返回指定域名的AAAA，比如www.joram.it，这条规则并不能实现只返回SOA
`address /www.joram.it/#6
`

**Comment by pymumu** [comment]
我测试是OK的，你是不是有其他什么忽略的规则？

**Comment by 523860169** [comment]
没有。你可以试试https://drive.google.com/open?id=1BNSqQWRf4erExA0rl1P-DuORp6e4Wm3J

**Comment by 523860169** [comment]
@pymumu 更新最新版并重启路由器后，正常了，不过更新后只重启smartdns而没重启路由器的话，似乎并不能正常，难道openwrt更新ipk后需要重启路由器新的程序才能生效？而重启路由器后，我在测试address /www.joram.it/#6功能正常的情况下，删掉这条规则，A和AAAA也能返回。
