### ISSUE TITLE
是否可以将最新代码提交到openwrt package

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#761]
openwrt代码库里面都是去年的代码了 太旧了

**Comment by wyjtm** [comment]
对 就是这个  仓库那边现在还是2020年的

**Comment by openips** [comment]
手工更新吧 目前仓库里的版本功能虽少 但是很稳

**Comment by fonlan** [comment]
这个咋手工更新？我在我自己的feed里加入了SmartDNS的Makefile，但不管我怎么改里面的版本，最后编译出来的都是2020年的版本

**Comment by cc9014** [comment]
> 这个咋手工更新？我在我自己的feed里加入了SmartDNS的Makefile，但不管我怎么改里面的版本，最后编译出来的都是2020年的版本

下载release里的版本，手动opkg安装。我是这么做的。

**Comment by fonlan** [comment]
> > 这个咋手工更新？我在我自己的feed里加入了SmartDNS的Makefile，但不管我怎么改里面的版本，最后编译出来的都是2020年的版本
> 
> 下载release里的版本，手动opkg安装。我是这么做的。

因为经常编译新版lede更新，不想每次升级后还需要手动安装
