### ISSUE TITLE
edns-client-subnet参数怎么用？

### ISSUE THREAD

**Issue by 15108428326** [pymumu/smartdns#762]
edns-client-subnet 参数该怎么设置？
应该填入什么ip?能给个实例么？

**Comment by PikuZheng** [comment]
···
edns-client-subnet 192.168.1.1/24
server 8.8.8.8 -check-edns
···
这样向8.8.8.8发出的dns请求会带上edns client数据（但我试了并不好用，按照文档配置好，smartdns直接不启动

**Comment by 15108428326** [comment]
我的也是设置后启动不了，不知道该填啥ip

**Comment by 15108428326** [comment]
找到原因了，好像是这个功能作者没弄完。没法用
