### ISSUE TITLE
baidu.com和www.baidu.com 一个正常一个异常

### ISSUE THREAD

**Issue by for5million** [pymumu/smartdns#766]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  
HomeLede v2021.03.20 based on OpenWrt R21.2.1 / LuCI Master
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
![image](https://user-images.githubusercontent.com/1744294/131280558-db662129-90d6-43b6-b390-105fe2a7f6ac.png)

2. 访问的域名。  
nslookup www.baidu.com 127.0.0.1#6053 返回空，这个非常奇怪，不知道为什么返回空的
nslookup baidu.com 127.0.0.1#6053 返回正常，为什么去掉www正常

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
你的dhcp规定了域名查询后缀。请 `nslookup www.baidu.com. 127.0.0.1#6053`

**Comment by for5million** [comment]
我试一下，这个问题导致我用浏览器打开百度就打不开，dns解析失败了

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
