### ISSUE TITLE
你好请问下我这报180s应该怎样处理??

### ISSUE THREAD

**Issue by CJM88888** [pymumu/smartdns#767]
**问题现象**  
简要描述问题出现的现象

**运行环境**
1. 固件型号  梅林改版装的entware

2. 运营商  中国电信

**重现步骤**
1. 上游DNS配置。  默认
[smartdns.log](https://github.com/pymumu/smartdns/files/7074421/smartdns.log)

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
只有系统待机才会这样。

**Comment by CJM88888** [comment]
> 只有系统才会这样。
就是还要装一个luci是吗？

**Comment by CJM88888** [comment]
待机需要怎么重新开启呢？我这路由器有时候重启后就这样

**Comment by CJM88888** [comment]
> 只有系统待机才会这样。
你好这样的话需要怎么处理呢 ，我这路由器重启后就会这样。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
