### ISSUE TITLE
来自 wireguard vpn 网络中的其他机器的 udp 查询无法收到响应

### ISSUE THREAD

**Issue by dr-MengmingLi** [pymumu/smartdns#768]
**问题现象**  
来自 wireguard vpn 网络中的其他机器的 udp 查询的响应无法到达发起请求的机器
但是 SmartDNS 可以正常收到查询请求并处理(日志中可以看到)，但响应没有正常到达请求客户端
也就是说:

PeerB ------> PeerA 看起来正常
PeerB <------ PeerA 异常

  - 只有访问 SmartDNS 监听的 UDP 服务收不到响应, 在两个 Peer 之间, 其它 UDP 的互相通信是正常的
  - 让 SmartDNS 监听的 TCP 端口, 通过 TCP 访问也是正常的

**运行环境**
1. 固件型号 
    PeerA - SmartDNS Server, Archlinux, IP: 10.1.0.1) 
    PeerB - Ubuntu, IP: 10.1.0.15)

2. 运营商
    中国电信

**重现步骤**
1. PeerA 与 PeerB 通过 wireguard 组成内网
2. 在 PeerB 向 PeerA 的 SmartDNS 监听的 UDP 端口发起 DNS 查询

2. 访问的域名。  
任何

**信息收集**  
SmartDNS 服务日志中没有任何异常, 可以看到查询请求打过来了
```
[2021-08-31 10:42:44,512][ INFO][     dns_server.c:2792] query server www.baidu.com from 10.1.0.15, qtype = 1
```

**Comment by ihotte** [comment]
WireGuard 接口防火墙开启 IP 动态伪装 (MASQUERADE) 试试
