### ISSUE TITLE
如何在LEDE里集成最新版的SmartDNS？

### ISSUE THREAD

**Issue by fonlan** [pymumu/smartdns#769]
不管我怎么折腾编译出来的LEDE里的SmartDNS版本号都是1.2020.30，不想每次升级都重新安装SmartDNS的ipk，正确的食用方法应该是怎么样的才能保证是最新版？

**Comment by eightsheep67** [comment]
这个有方法吗？

**Comment by fonlan** [comment]
> 这个有方法吗？

现在已经是最新版了，有人更新了

**Comment by eightsheep67** [comment]
> > 这个有方法吗？
> 
> 现在已经是最新版了，有人更新了

为啥我编译出来的luci还是1.2020.30-1，smartdns版本也是1.2019.28-1

我云编译添加代码：
git clone -b lede https://github.com/pymumu/luci-app-smartdns.git package/luci-app-smartdns
git clone https://github.com/pymumu/smartdns.git package/smartdns

哪里出了问题呢

**Comment by fonlan** [comment]
> 

你第二行别加试试，lean的源码里已经带了smartdns的，缺个luci-app-smartdns而已

**Comment by eightsheep67** [comment]
不过最新的不是已经是2021.08.27吗，有办法直接编译这个版本吗？

**Comment by fonlan** [comment]
> 不过最新的不是已经是2021.08.27吗，有办法直接编译这个版本吗？

lean的源码里带的smartdns就是release 35，也就是2021.08.27 release的那个版本啊
