### ISSUE TITLE
支持导出SmartDNS的配置文件

### ISSUE THREAD

**Issue by fonlan** [pymumu/smartdns#77]
**需求应用场景**
LEDE上希望支持导出配置文件，按照先remove再安装的方式会导致配置文件丢失，而且LEDE上通过luci界面配置生成的配置文件会分成好几个且存在于不同的目录，手动备份/恢复多个文件很麻烦

**建议的方案**
luci界面上增加一个导出/导入配置的按钮，可以把配置导出为一个文件，也可以导入配置文件

**设备信息**
1. 设备信息（CPU，厂家）  
X86_64

2. 固件信息
LEDE 软路由

**Comment by pymumu** [comment]
卸载软件，配置是会保留的。

**Comment by cjameslynn** [comment]
楼主为了v2ray？

**Comment by fonlan** [comment]
> 卸载软件，配置是会保留的。

我上次卸载重装的时候配置丢了，下次新版本出来的时候我再试试

**Comment by fonlan** [comment]
> 楼主为了v2ray？
> LEDE的conf文件配置的信息非常少，都保存在etc/config里了，只能对照[配置参数]自己写conf

不是，我不用V2ray

**Comment by pymumu** [comment]
ipkg安装包里面已经指定配置文件了。
/etc/config/smartdns
/etc/smartdns/address.conf
/etc/smartdns/custom.conf
/etc/smartdns/blacklist-ip.conf

上述文件已经加入到配置列表里面了

ipkg卸载的时候，这些文件是会保留的。
