### ISSUE TITLE
建议增加一个监听 PassWall /SSR PLUS 关闭或重启的功能

### ISSUE THREAD

**Issue by z826540272** [pymumu/smartdns#771]
开启smartdns,手动重启或关闭翻墙服务后,SmartDNS的 缓存池并不会更新.可能会引入DNS污染
我不想用加密DNS服务,因为TCP查询足够简单了.
希望增加一个监听进程功能,当XX进程关闭时自动清空smartdns缓存,或自动关闭/重启 SmartDNS自身.

**Comment by 15108428326** [comment]
自己用脚本写个就好
