### ISSUE TITLE
移动网络 百度dns 经常不通 请注意

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#773]
180.76.76.76
也不知道移动网络怎么回事
百度dns经常性不能用
请注意

**Comment by rampageX** [comment]
移动是劫持所有 udp 53 端口，换普通 dns 无任何意义，除非换 tcp，非 53 端口，DoH，DOT

**Comment by lalasou** [comment]
好吧 求推荐 国内doh dot tcp  tls
目前在用的  就这两个
https://1.1.1.1/dns-query
https://223.5.5.5/dns-query

**Comment by lalasou** [comment]
> ```
> 
> server-tcp 114.114.114.114 -group china -exclude-default-group
> 
> server-tcp 119.29.29.29 -group china -exclude-default-group
> 
> server-tcp 223.5.5.5 -group china -exclude-default-group
> 
> server-tcp 162.14.21.178 -group china -exclude-default-group
> 
> server-https https://doh.360.cn/dns-query -group china -exclude-default-group
> 
> server-https https://i.233py.com/dns-query -group china -exclude-default-group
> 
> server-tls 223.6.6.6:853 -host-name dns.alidns.com -group china -exclude-default-group
> 
> server-tls 162.14.21.178:853 -host-name dns.pub -group china -exclude-default-group
> 
> ```

老哥
把你完整 配置发个吧
谢谢 
😃😀
