### ISSUE TITLE
无法查询pop.163.com

### ISSUE THREAD

**Issue by yaott2020-666** [pymumu/smartdns#775]
**问题现象**  
简要描述问题出现的现象

使用smartdns无法查询
而直接使用223.5.5.5则ok

**运行环境**
1. 固件型号  

2. 运营商  

CMCC

**重现步骤**
1. 上游DNS配置。  

223.5.5.5
180.76.76.76
119.29.29.29

2. 访问的域名。  
pop.163.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by 15108428326** [comment]
你设置的3个上游服务器，经验证都是能解析pop.163.com的，鉴于你的运营商是cmcc，故考虑到53端口劫持，你可以将上游换为doh或者dot，当然不排除小概率是去广告或者是hots屏蔽了pop.163.com

**Comment by yaott2020-666** [comment]
现在又行了

**Comment by lalasou** [comment]
国内  最好 tcp tls doh dot或者 非53端口   udp不行
