### ISSUE TITLE
CentOS6.6-x86_64 boot-log  dns_server.c:509 ] send failed, Bad file descriptor

### ISSUE THREAD

**Issue by boy6585948** [pymumu/smartdns#776]
**问题现象**  
CentOS6.6-x86_64 boot-log  dns_server.c:509 ] send failed, Bad file descriptor

**运行环境**
1. CentOS-6.6- 2.6.32-504.el6.x86_64
2. smartdns.1.2021.08.27-1923.x86_64-linux-all.tar.gz

2. 运营商  
广东电信-116.6.106.x
**重现步骤**
1. 上游DNS配置。  
bind :53
#bind [::]:53
cache-size 40960
server 114.114.114.114
server 223.5.5.5
server 180.76.76.76

2. 访问的域名。  
www.qq.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  

2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
