### ISSUE TITLE
需要nonegcache功能

### ISSUE THREAD

**Issue by kousyougi** [pymumu/smartdns#777]
**需求应用场景**
国内某些DNS解析太慢会直接用Non-existent domain抢答，之后的60秒(rr-ttl-min)都无法解析域名。

**建议的方案**
没有解析出IP就不要处理，当 time out

**Comment by lalasou** [comment]
这个 可以有

**Comment by pymumu** [comment]
用最新代码试试

**Comment by lalasou** [comment]
> 用最新代码试试

大佬 更新了啊

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
