### ISSUE TITLE
华硕路由器最新版本安装后不能正常使用

### ISSUE THREAD

**Issue by AckywOw** [pymumu/smartdns#779]
**问题现象**  
华硕路由器最新版本smartdns.1.2021.08.27-1923.arm-optware-all.ipk安装后不能正常使用，重启后，nslookup命令无响应；smartdns.1.2020.09.08-2235.arm-optware-all.ipk版本是没有问题的

**运行环境**
1. 固件型号 AX86U 3.0.0.4.386_45375

**重现步骤**
安装后无法使用，必现的

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
