### ISSUE TITLE
使用TCP测速

### ISSUE THREAD

**Issue by fonlan** [pymumu/smartdns#78]
**需求应用场景**
公司内网出口需要通过代理，且禁止ICMP到外网，所以希望SmartDNS支持TCP测速，且能支持配置代理

**建议的方案**
#30 说是先ICMP测速，失败后再TCP测速，不过我实际Wireshark抓包发现ping了一次，失败后并没有看到有TCP报文发出去，是这个功能又被禁用了吗？
另外顺便提一个小bug，Win10 WLS（Ubuntu18.04）下安装SmartDNS会失败，因为虽然是Ubuntu18.04但并没有使用systemctl。手动把文件复制到指定位置还是可以用的。

**设备信息**
1. 设备信息（CPU，厂家）  
X86_64

2. 固件信息
Win10 WSL Ubuntu18.04

**Comment by pymumu** [comment]
现在先icmp，后tcp是固定的模式。
只有所有ping超时后（300ms内没有回应），才启用tcp测速的。

**Comment by fonlan** [comment]
那能不能config里加个开关禁止ping直接tcp测速？另外SmartDNS在TCP测速的时候似乎是忽略环境变量里的代理信息的，所以之前没抓到。能否在配置文件里支持配置http代理服务器？

**Comment by pymumu** [comment]
tcp测速是为了避免某些网站禁止ping的保证机制。
所以，关闭tcp测速没有意义。

tcp测速是直接连接的，类似ping，不会走代理。

**Comment by fonlan** [comment]
> tcp测速是为了避免某些网站禁止ping的保证机制。
> 所以，关闭tcp测速没有意义。
> 
> tcp测速是直接连接的，类似ping，不会走代理。

我是说关闭ping，不是说关闭tcp测速。那如果这种环境下没法走代理测速的话应该就用不了SmartDNS了吧。

**Comment by pymumu** [comment]
这种场景smartdns不合适。

关闭ping检测的，后面还有加进去吧

**Comment by fonlan** [comment]
> 这种场景smartdns不合适。
> 
> 关闭ping检测的，后面还有加进去吧

那是不是可以再加一种http测速的方式？http测速就可以方便的配置代理了，http测速比较慢，但prefetch的时候可以用啊。也就是如果第一次query的时候还是按照ping和tcp的方式测速，如果开启了prefetch则prefetch的时候支持通过http测速。
