### ISSUE TITLE
[ERROR][     dns_server.c:3361] dns server process failed.

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#780]
**问题现象**  
简要描述问题出现的现象
日志里经常一堆`[ERROR][     dns_server.c:3361] dns server process failed.`
![1](https://user-images.githubusercontent.com/38558065/132974431-fead621c-a88b-493d-8e85-554257cafaa5.png)

**运行环境**
1. 固件型号  AX3600(OpenWrt R21.9.5 / LuCI Master (git-21.242.58622-7c82358)) 内核版本 5.10.62

2. 运营商  电信

**重现步骤**
1. 上游DNS配置。  
![2](https://user-images.githubusercontent.com/38558065/132974326-9012a702-745b-40fa-926e-c2b4ec4b69a7.png)

2. 访问的域名。  没有访问任何域名，启动后日志里就会刷出一堆

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[smartdns.log](https://github.com/pymumu/smartdns/files/7149097/smartdns.log)

**Comment by fangjia052** [comment]
我觉得可能是设置的DNS服务器问题吧，好像国内的公共DNS一般不支持TCP查询的，你可以把国内服务器就只设置一个TCP查询的DNS，看看能不能查询，如果不能上网就说明查询不了

**Comment by devioa** [comment]
> 我觉得可能是设置的DNS服务器问题吧，好像国内的公共DNS一般不支持TCP查询的，你可以把国内分组就只设置一个TCP查询的DNS，看看能不能查询，如果不能上网就说明查询不了

找到原因了，好像是speed-check-mode 设置成tcp:443就会这样，我改成tcp:80就没有这个log了

**Comment by devioa** [comment]
> 我觉得可能是设置的DNS服务器问题吧，好像国内的公共DNS一般不支持TCP查询的，你可以把国内分组就只设置一个TCP查询的DNS，看看能不能查询，如果不能上网就说明查询不了

我单独试过，都能正常查询，最近把log-level改为debug发现了这个日志：

> [2021-09-23 16:22:01,112][DEBUG][     dns_server.c:2323] recv query packet from 127.0.0.1, len = 156
> [2021-09-23 16:22:01,112][DEBUG][            dns.c:973 ] length is not enough 156:15228, 0x7fd57caef6, 0x7fd57caee8
> [2021-09-23 16:22:01,112][DEBUG][            dns.c:1070] decode domain failed.
> [2021-09-23 16:22:01,112][DEBUG][            dns.c:1800] decode qd failed.
> [2021-09-23 16:22:01,112][DEBUG][            dns.c:1949] decode body failed.
> [2021-09-23 16:22:01,112][DEBUG][     dns_server.c:2326] decode failed.
> [2021-09-23 16:22:01,112][ERROR][     dns_server.c:2965] dns server process failed.

**Comment by devioa** [comment]
这是我现在的配置
![1](https://user-images.githubusercontent.com/38558065/134494794-abbee144-e918-403f-ba9a-0f2c9b1e24cb.png)

**Comment by lalasou** [comment]
我这边也是 这样

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
