### ISSUE TITLE
反馈一个小BUG，开域名预加载，全DOH环境下会导致莫名其妙的解析失灵，拿不到目标域名IP地址

### ISSUE THREAD

**Issue by 1klakla1** [pymumu/smartdns#781]
**问题现象**  
开域名预加载，全DOH环境下会导致莫名其妙的解析失灵，拿不到目标域名IP地址

**运行环境**
1. 固件型号  
最新版SmartDns

2. 运营商  
中国联通

**重现步骤**
1. 上游DNS配置。  
#域名结果缓存个数
cache-size 5000
#是否持久化缓存yes/no
cache-persist yes
#缓存持久化文件路径
cache-file /tmp/smartdns.cache
#域名预先获取功能yes/no
prefetch-domain yes
#过期缓存服务功能yes/no
serve-expired no
#双栈IP优选yes/no
dualstack-ip-selection no
#允许的最小TTL值
rr-ttl-min 5
#允许的最大TTL值
rr-ttl-max 600

#############################DoH前置###############################

#添加前置DoH前置DNS
server 223.6.6.6 -group cndoh -exclude-default-group
server 119.29.29.29 -group cndoh -exclude-default-group

#############################墙内###################################

bind-tcp :6054 -group cn speed-check-mode tcp:443
bind :6054 -group cn speed-check-mode tcp:443

#添加 DNS 给 6054 端口绑定的 cn 分组
server-https https://doh.pub/dns-query -group cn -exclude-default-group
server-https https://dns.alidns.com/dns-query -group cn -exclude-default-group

#设置DoH专用前置DNS
nameserver /doh.pub/cndoh
nameserver /dns.alidns.com/cndoh

#############################墙外###################################

bind-tcp :6554 -group overseas speed-check-mode tcp:443
bind :6554 -group overseas speed-check-mode tcp:443

#添加前置DoH前置DNS

#添加 DNS 给 6554 端口绑定的 overseas 分组

server-https https://dns.google/dns-query -group overseas -exclude-default-group
server-https https://cloudflare-dns.com/dns-query -group overseas -exclude-default-group
server-https https://doh.dns.sb/dns-query -group overseas -exclude-default-group

#设置DoH专用前置DNS
nameserver /dns.google/cndoh
nameserver /cloudflare-dns.com/cndoh
nameserver /doh.dns.sb/cndoh

2. 访问的域名。  
国外域名出现频率比较高。

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by 1klakla1** [comment]
补充：
刚测试完全TLS环境，也是一样，只要打开预加载，就会莫名其妙DNS失效，国内国外均如此。

**Comment by 1klakla1** [comment]
貌似找到问题了。。。最小ttl设置的太小了

**Comment by GreatMichaelLee** [comment]
另外系统时间也很重要，如果系统时间跟真实时间相差太多，如果只配置doh不配置非ssl类的dns, ssh handshake会有问题，dns会工作不了，一样会上不了网
