### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by PussAzuki** [pymumu/smartdns#79]
**需求应用场景**
在 中国电信公网IPv4+6in4提供的公网IPv6 这样的网络环境下首次进行dns查询服务不会报错
**建议的方案**
先tcping/ping测试到设定的服务器的链路畅通之后再进行之后的操作或者说稍等一会儿再提供dns查询服务，目前貌似是在6in4提供的IPv6网络下还没初始化完成前就开始发送数据了，导致开头几个域名结果都是IPv4 dns查询获得的
**设备信息**
1. 设备信息（CPU，厂家）  
Phicomm PSG1218 rev.A
MediaTek MT7620A ver:2 eco:6
2. 固件信息
自编译的 Lean 的 LEDE
OpenWrt R9.1.1 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)

**Comment by pymumu** [comment]
我这里测试了6to4的情况，没有这个问题。
你可以先用cron调用ping命令周期ping google的IPV6dns来规避。

**Comment by PussAzuki** [comment]
emmmm，我是说那个tls握手需要时间...而目前的设置导致设定的tls dns被忽略，目前来看是约15分钟没有动作就会断开tls连接，希望加个1.首次启动先等待tls dns 2.闲置15分钟后主动断开并隔3秒后再连接

**Comment by pymumu** [comment]
tls握手时间在Release 20做了优化，你可以先看看。
如果是4.1x的内核的话，开启了TCP Fastopen，会更快。

**Comment by PussAzuki** [comment]
release 20昨天刚试过...可能是6in4的网况太特殊，之前的毛病还都在...关于fast open 不是得服务器，客户端支持才行么？我目前设置的是cloudflare的tls dns，内核是4.14.94 lean大的lede

**Comment by pymumu** [comment]
1.1.1.1服务器是支持fast open的。
1.1.1.1的话，直接IPV4 TLS效果最好。

我测试1.1.1.1在4.1x内核下查询等待时间之比UDP慢一个rtt时间。大约140ms。
基本查询不会超时查不到。

**Comment by PussAzuki** [comment]
emmmmm但我6in4的ipv6连到cloudflare更快，而且解析都是基于6in4的地址的，不会多一个从美国回来的路线....我待会再试试看，如果可行就使用了

**Comment by pymumu** [comment]
最新版本增加了重试机制，可以尝试看看，有问题再reopen issue。
