### ISSUE TITLE
无法生成持久化缓存文件

### ISSUE THREAD

**Issue by devioa** [pymumu/smartdns#791]
**问题现象**  
无法生成持久化缓存文件
即使在自定义配置中手动添加 `cache-persist yes` 
`/etc/init.d/smartdns stop`后再`/etc/init.d/smartdns start`也没有生成`/tmp/smartdns.cache`

**运行环境**
1. 固件型号  
AX3600 `OpenWrt R21.9.18 / LuCI Master (git-21.238.35254-83494a9) Kernel 5.10.64`
2. 运营商  
电信

**Comment by PikuZheng** [comment]
版本不同吧。之前有个版本就是无法生成缓存文件的。后来的代码更新了（但并没有提交release

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
