### ISSUE TITLE
建议添加对域名通配符的支持

### ISSUE THREAD

**Issue by betaxab** [pymumu/smartdns#792]
**需求应用场景**
在某些不确定子域名的情况下，需要域名通配符的支持。如果没有这个功能的话，大概要写 800 多行规则才能全部匹配到。

**建议的方案**

目前 dnsmasq 已经支持了该功能。

请参考该提交：
https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=5e95c16c322afde473c2838d64700e6363df3e4

示例：
nameserver /*-a.example.com/warp

**Comment by Somalia0932** [comment]
正则匹配不是更舒服 ^.*(cpu|ubmcmm|dup|eclick|wangmeng|su|cpro|pos|ecma|crop|entry|znsv|hm)\.(baidu|baidustatic)\.com.*

**Comment by PikuZheng** [comment]
smartdns就是从右到左匹配的，规则中写nameserver /-a.example.com/ 应该可以匹配到 something-a.example.com 之类的

**Comment by yrway** [comment]
> smartdns就是从右到左匹配的，规则中写nameserver /-a.example.com/ 应该可以匹配到 something-a.example.com 之类的



> 正则匹配不是更舒服 ^\.*(cpu|ubmcmm|dup|eclick|wangmeng|su|cpro|pos|ecma|crop|entry|znsv|hm)\.(baidu|baidustatic)\.com\.*
目前
支持正则表达嘛

**Comment by PikuZheng** [comment]
> 目前
> 支持正则表达嘛

作者表示不计划支持 https://github.com/pymumu/smartdns/issues/580#issuecomment-678563074

**Comment by pymumu** [comment]
简单修改了一下，支持前缀通配。也就是*号只能在开头。

```
// 通配
*-a.example.com 
// 仅匹配子域名
*.example.com
// 仅匹配主域名
-.example.com
```
