### ISSUE TITLE
docker中运行要怎么生成缓存？

### ISSUE THREAD

**Issue by Somalia0932** [pymumu/smartdns#793]
大佬，请问在docker中运行的smartdns要怎么生成缓存？
配置文件中已经开启缓存，并且指定缓存文件。

**Comment by Somalia0932** [comment]
> 看了一下我的docker中自动生成了smartdns.cache，位于/tmp

试了一下，通过仓库里那个dockerfile编译的容器可以生成缓存。 通过smartdns.1.2021.08.27-1923.x86_64-linux-all.tar.gz 打包的容器不会生成缓存。

**Comment by PikuZheng** [comment]
> > 把缓存挂载到实体机，docker储存不是持久化的
> 
> 这我当然知道，关键问题是 smartdns.1.2021.08.27-1923.x86_64-linux-all.tar.gz 打包的容器不会生成缓存

用dockerfile实时编译一下吧。之前有一个发布版本的缓存部分有问题。
另外缓存文件没必要映射到实体

**Comment by Youkii-Chen** [comment]
缓存不映射的话，容器重启就没有了

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
