### ISSUE TITLE
无法生成smartdns.cache缓存文件

### ISSUE THREAD

**Issue by hululu1068** [pymumu/smartdns#795]
**问题现象**  
官方源码编译的openwrt x86_64固件，选择编译了源码中的smartdns
自定义配置中也添加了“持久化缓存”，/tmp目录有200多M的空间
cache-persist yes
cache-file /tmp/smartdns.cache

![image](https://user-images.githubusercontent.com/68652362/137089482-4149b2bb-27d3-4c88-a330-0b8c785f2624.png)

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue

**Comment by hululu1068** [comment]
> 最新版本验证，有问题reopen issue

今天拉取的源码。。。。这个问题确实还在，默认不生成cache文件，restart后就有了。

—— OpenWrt 22.03.2, r19803

**Comment by pymumu** [comment]
就是这样设计的。一直写cache是不现实的。
