### ISSUE TITLE
高手来看看设置的有没有错误

### ISSUE THREAD

**Issue by chenyajunai** [pymumu/smartdns#797]
我的初衷就是大陆白名单IP段走国内cn组dns，白名单之外走国外us组dns
我在自定义设置里添加了指定了cn组和us组端口
bind :6666 -group cn 
bind :7777 -group us
又在自定义设置里，添加了下面的，我的大概意思是下面的us组指定了-blacklist-ip黑名单，是不是就是说黑名单里面的ip段就走cn组里的dns了，黑名单里面没有的就走us组的dns了，下面也不知道设置的对不对
server-https https://cloudflare-dns.com/dns-query -group us -exclude-cn-group -blacklist-ip
server-https https://dns.google/dns-query -group us -exclude-cn-group -blacklist-ip
然后我在黑名单添加了像下面这样的，下面添加的是大陆白名单IP段
blacklist-ip 1.0.1.0/24
blacklist-ip 1.0.2.0/23
blacklist-ip 1.0.32.0/19
blacklist-ip 1.0.8.0/21
blacklist-ip 1.1.0.0/24
blacklist-ip 1.1.10.0/23
blacklist-ip 1.1.12.0/22
blacklist-ip 1.1.16.0/20
blacklist-ip 1.1.2.0/23
blacklist-ip 1.1.32.0/19
blacklist-ip 1.1.4.0/22
blacklist-ip 1.1.8.0/21
blacklist-ip 1.1.8.0/24
blacklist-ip 1.1.9.0/24
blacklist-ip 1.10.0.0/21
blacklist-ip 1.10.11.0/24
blacklist-ip 1.10.12.0/22
blacklist-ip 1.10.16.0/20
blacklist-ip 1.10.32.0/19
blacklist-ip 1.10.64.0/18
blacklist-ip 1.10.8.0/23
反正国内外都能打开用，就是搞不懂对不对，怎么测试，高手来看看指教一下了

**Comment by hululu1068** [comment]
你这个issues太简洁了，不知道你其它的插件是如何设置的。
建议你多看几遍README，看懂就清楚了
