### ISSUE TITLE
Docker 容器网络下 UDP 协议的一个问题

### ISSUE THREAD

**Issue by aeiougo** [pymumu/smartdns#798]
**问题现象**  
通过bind UDP 端口将服务运行在装有 Docker 服务的主机上（或者运行在网络模型为 Host 的 Docker 容器里），并且监听所地址（bind :53），从运行在 docker bridge 网络的容器运行客户端访问服务，两者通信有问题。

在宿主机上访问解析：
![image](https://user-images.githubusercontent.com/47635948/137240123-d1ccd11a-7e67-4e8f-8694-fe26f4d68872.png)

在本机的Docker容器内解析：
![image](https://user-images.githubusercontent.com/47635948/137240034-ad1a7688-2cf5-49a6-a7bb-ef1071553466.png)

**运行环境**
所有 x86_64 Linux

这几天一直在研究使用大佬的 smartdns，非常好用，非常棒，必须点赞！
在测试过程中发现上述问题，这个问题严格来讲不算是软件的bug，只是在 Docker 宿主机上使用会遇到问题。
我也一直在使用 bind9、dnsmasq 工具作为内网 dns 服务器，也是在相同运行环境下，一直没有遇到过类似问题，经过查找资料，找到一篇相同的[案例](https://cizixs.com/2017/08/21/docker-udp-issue/)，据作者研究可以通过修改应用解决，希望大佬能修复下，感激不尽！
![image](https://user-images.githubusercontent.com/47635948/137241499-54543b64-a73c-4aa8-96d3-24f0d8162bb3.png)
![image](https://user-images.githubusercontent.com/47635948/137241406-57024b36-7089-4051-a631-2483c20f0e47.png)

**Comment by PikuZheng** [comment]
不对啊，我在docker里用了几个月了，没这个问题啊

**Comment by PikuZheng** [comment]
> 你没有搞明白 docker 网络的机制，这不能算是bug。 docker bridge的实现原理是在系统中创建一块虚拟网卡(docker0)用snat把eth0当做网关来上网，而且docker0和eth0并不在同一个网段，不在同一个网段你自然是访问不了的，连ping都ping不通。

它这个其实就是路由器的内网回流问题

**Comment by gumpjt** [comment]
> 你可以ifconfig看一下docker0网卡拿到的地址，在容器中使用这个ip作为dnsip

老哥想请教一个问题。
我在win10中，使用docker运行smartdns。希望win10本地所有的DNS请求都通过docker里的smartdns来完成。
运行镜像的时候，通过-p "53:53" 来暴露的端口，服务也正常起来了。但是在修改win10DNS服务器地址到127.0.0.1后，发现smartdns并没有起作用. 排查smartdns的日志文件也没有什么信息。win10 本地执行nslookup -querytype=ptr smartdns，返回的是服务器：unknow


请问这可能是什么问题呢。win10 docker要如何跑smartdns呢？

**Comment by PikuZheng** [comment]
> 但是在修改win10DNS服务器地址到127.0.0.1后

容器有自己的ip地址。127.0.0.1指向的是windows的网卡地址，并不是容器的

**Comment by PikuZheng** [comment]
> 请问这可能是什么问题呢。win10 docker要如何跑smartdns呢？

安装docker后，windows自身应该会多出一个docker的网卡。你可以这么理解，windows是个路由器，docker网卡对应lan口，物理网卡对应wan口。容器是lan口下的其他设备，和docker网卡处于同一网段且拥有独立的ip。
其他设备访问容器是通过wan到lan的端口映射来访问的。windows自身访问容器应该使用容器的内部ip。

**Comment by gumpjt** [comment]
> > 请问这可能是什么问题呢。win10 docker要如何跑smartdns呢？
> 
> 安装docker后，windows自身应该会多出一个docker的网卡。你可以这么理解，windows是个路由器，docker网卡对应lan口，物理网卡对应wan口。容器是lan口下的其他设备，和docker网卡处于同一网段且拥有独立的ip。 其他设备访问容器是通过wan到lan的端口映射来访问的。windows自身访问容器应该使用容器的内部ip。

谢谢老哥回复，根据你的反馈进行了相关配置，就是找了下docker所在的网卡IP，配完还是不行。我醉了。。。

我新起了一个issue，里面贴了本机的一些详细信息，老哥如有空，还请能帮忙看下，谢谢了。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
