### ISSUE TITLE
linux-all.tar.gz 安装脚本的一个小问题

### ISSUE THREAD

**Issue by aeiougo** [pymumu/smartdns#799]
**问题现象**  
在软件发布页面下载：
smartdns.1.2021.08.27-1923.x86-linux-all.tar.gz

解压安装报错：
![image](https://user-images.githubusercontent.com/47635948/137243173-2a116b82-f7a8-4d34-befb-075bed4934f8.png)

分析原因：
smartdns 安装脚本名为 **install**，脚本在运行过程中会使用系统的 **install** 命令
从下图可以看出，安装过程显示进入 smartdns 目录，执行系统的 **install** 命令失败，原因就是执行此命令调用的其实是 smartdns  的安装脚本 **install**（优先调用了当前目录下同名可执行文件，并未从$PATH取），从而导致安装失败。
![image](https://user-images.githubusercontent.com/47635948/137243330-4808dd62-afaa-4736-aa1e-315cff045f5d.png)

解决方法：
重命名 smartdns 安装脚本 **install**  避免和脚本内需要调用的系统命令名字冲突即可，如修改为 **install.sh** 可以顺利安装

**运行环境**
测试了下面两种发行版，都会复现问题，修改脚本名后问题都可以得到解决
CentOS7 x86_64
Ubuntu 18.04 x86_64

**Comment by Somalia0932** [comment]
sh install -i  没遇到问题

**Comment by aeiougo** [comment]
经过测试发现，在新装的系统上是可以安装成功的，是我测试环境的linux系统安装了什么东西导致的，先关闭了
