### ISSUE TITLE
 ExecStart=/usr/sbin/smartdns $SMART_DNS_OPTS (code=exited, status=127)

### ISSUE THREAD

**Issue by Auska** [pymumu/smartdns#80]
**问题现象**  
● smartdns.service - smart dns server
   Loaded: loaded (/lib/systemd/system/smartdns.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-02-01 09:59:17 CST; 1s ago
  Process: 11655 ExecStart=/usr/sbin/smartdns $SMART_DNS_OPTS (code=exited, status=127)
      CPU: 5ms

Feb 01 09:59:17 orangepioneplus systemd[1]: smartdns.service: Unit entered failed state.
Feb 01 09:59:17 orangepioneplus systemd[1]: smartdns.service: Failed with result 'exit-code'.

**运行环境**
1. aarch64 开发板 armbian

**重现步骤**
1. /usr/sbin/smartdns -h

**信息收集**  
error while loading shared libraries: libssl.so.1.1

**解决方案**
安装libssl-dev:armhf解决

**建议**
希望提供arm64的deb包

**Comment by pymumu** [comment]
已经增加支持。
