### ISSUE TITLE
A Bug for Bind Port 一个关于绑定端口的bug

### ISSUE THREAD

**Issue by 610312586** [pymumu/smartdns#802]
Hello, I was using SmartDNS  with 1.2021.08.27-1923 version find this bug in smartdns.conf :
bind [::]:53 -no-rule-ipset
bind-tcp [::]:53 -no-rule-ipset
bind 0.0.0.0:53 -no-rule-ipset
bind-tcp 0.0.0.0:53 -no-rule-ipset
I got a ERROR in logs :
[ERROR][     dns_server.c:3508] bind service 0.0.0.0:53 failed, Address in use
It mens SmartDNS can not Listen IPV4 and IPV6 on 0.0.0.0:53 and [::]:53 .

我在用1.2021.08.27-1923版本的SmartDNS时候遇到一个bug，
我配置SmartDNS监听IPV4和IPV6的所有53端口，但却提示冲突。

**Comment by PikuZheng** [comment]
如果是linux的话，[::]:53是包含0.0.0.0:53的

**Comment by mingmeng** [comment]
I meet the same issue and my previous conf is:

```conf
bind [::]:53
bind :53
cache-size 4096                       
prefetch-domain yes                   
speed-check-mode tcp:80,tcp:443,ping  
rr-ttl-min 60                         
rr-ttl-max 86400
log-level warn
```
after delete the `bind :53`, it works

**Comment by PikuZheng** [comment]
> [::]:

[::]:53 includ 0.0.0.0:53, check AP_ENABLE_V4_MAPPED config of your system first, please.
