### ISSUE TITLE
每次重启路由器都要手动开关一次才生效

### ISSUE THREAD

**Issue by ywyha** [pymumu/smartdns#804]
**问题现象**  
1.2020.30-1版本每次重启路由器都要手动开关一次才生效，重启后显示运行中，但是实际上没生效，需要手动开关一次

**运行环境**
1. 固件型号  OpenWrt R21.10.1

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by hululu1068** [comment]
我这边的情况跟你一样。https://github.com/pymumu/smartdns/issues/795#issuecomment-944227889

**Comment by 57382** [comment]
OpenWrt官方版
21.02.0升级到21.02.1
我出现了一样的问题，
没安装任何其它东西，
只安装了smartdns。
这是一个BUG

**Comment by ywyha** [comment]
> 关于不生效的问题，这边猜测你启用了别的同样带dns服务的插件，譬如openclash，而且启动顺序在smartdns之后，覆盖了smartdns的iptables规则。导致服务失效。你重新启用之后smartdns又覆盖了openclash的iptables规则，所以就生效了。
> 
> openclash真的很恶心，就算你不启动dns服务也会强行给iptables加上几条dns拦截规则(默认会拦截8.8.8.8到clash的dns端口，不管有没有开启dns服务)
> 
> 所以理论上是无解的.... 除非让smartdns比openclash晚一点启动

你好，我固件编译的时候没有加入openclash和其他东西，只加了大屌默认的55R这一种，而且这个问题困扰依旧，我之前刷其他大佬的成品固件也是有这种问题，重启路由器的时候手动关开一次就会正常了。

**Comment by Youkii-Chen** [comment]
那尝试卸载重装一次

**Comment by Youkii-Chen** [comment]
或者看一下日志文件

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
