### ISSUE TITLE
日志帮忙看看有什么错误吗

### ISSUE THREAD

**Issue by chenyajunai** [pymumu/smartdns#806]
日志里出现很多这样的，说失败，连接超时，关闭
[smartdns.log](https://github.com/pymumu/smartdns/files/7393789/smartdns.log)

recv ping packet from 192.168.2.2 failed.

server 119.29.29.29 connect timeout.
server 119.29.29.29 closed.

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
