### ISSUE TITLE
效果很好特来感谢

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#81]
我使用的是老毛子的固件，用的是移动的宽带
自己修改了ss和chinadns的脚本，用v2ray域名嗅探替代了ss和dns的转发解决了污染，用smartdns替代了 dnsmasq的gfwlist ipset，貌似将这些域名直接写个固定ip也行，反正有域名嗅探，还能防止dns泄露，
感觉dnsmasq的gfwlist列表查询并不是很快，但是这个不是问题，问题是默认的dns是174.174.174.174,就很迷的一个地址，no cache查询700多毫秒，有时候夸张的一秒多，尝试用dns benchmark，结果最快的dns是联通的，查询是快了，打开网页却慢了，有时候感觉跟断网一样，于是花了一天折腾了一下dns，只用了最基本的功能，v6选优+五个server，效果很好，特来鼓励

opkg安装的时候走了一点弯路
默认是这个
src/gz entware http://bin.entware.net/mipselsf-k3.4
dest root /
lists_dir ext /opt/var/opkg-lists
arch all 100
arch mipsel-3x 150
arch mipsel-3.4 160
cpu是mt7621
cpu model               : MIPS 1004Kc V2.15
几乎都下来来都没成功
最后自己加了一行，建议写在readme里吧
arch mipselsf 170

**Comment by Masstone** [comment]
老毛子不是应该用padavan么，我跟你的机器一样的架构 我可以装padavan

**Comment by Masstone** [comment]
@pymumu 大佬，我的设备是MI3，固件是padavan，但是安装padavan的固件不成功，安装mips 3.4可以成功，但是workmode=2的话就无法正常restart，一个是重启dnsmasq的方式不匹配，一个是修改的dnsmasq的conf路径不是user conf路径的文件

![image](https://user-images.githubusercontent.com/1457421/58567335-c7af3680-8264-11e9-9fe2-45fd419aec2c.png)

**Comment by Masstone** [comment]
我现在是自己手动修改了dnsmasq的port=0，通过restart_dhcpd命令重启的
而且我看smartdns没有默认监听53，我手动添加了port 53后重启才监听

**Comment by pymumu** [comment]
从截图看，是没找到dnsmasq服务导致的。
smartdns mode 2执行的时候，要确保dnsmasq服务运行。

你ps看一下dnsmasq服务是否在执行。

**Comment by Masstone** [comment]
4324 nobody    1000 S    /usr/sbin/dnsmasq

**Comment by pymumu** [comment]
你把/opt/etc/init.d/S50smartdns的55行改成下面的
```
CMD="`ps | grep "dnsmasq" | grep -v grep 2>/dev/null`"
```

删除多余空格

**Comment by Masstone** [comment]
> 你把/opt/etc/init.d/S50smartdns的55行改成下面的
> 
> ```
> CMD="`ps | grep "dnsmasq" | grep -v grep 2>/dev/null`"
> ```
> 
> 删除多余空格

OK 另外就是dnsmasq有附加的conf文件，你脚本好像没有对这个文件添加port=0  会有影响么

**Comment by pymumu** [comment]
smartdns会重启dnsmasq，
但可能dnsmasq自动重启，那么dnsmasq可能就启动不了了，

所以，手工加一下port=0

**Comment by Masstone** [comment]
> smartdns会重启dnsmasq，
> 但可能dnsmasq自动重启，那么dnsmasq可能就启动不了了，
> 
> 所以，手工加一下port=0

这个就是谁先占了端口，后面启动的就起不来么

**Comment by pymumu** [comment]
对，所以你可以先设置dnsmasq关闭DNS
后面会增加不同位置配置文件的处理
