### ISSUE TITLE
无法解析，cmd显示request timed out

### ISSUE THREAD

**Issue by ForeverBRS** [pymumu/smartdns#82]
**问题现象**  
配置成dnsmasq的上游服务器后，无法解析

**运行环境**

1. 固件型号  
OpenWrt R9.1.1 By Lean / LuCI Master (git-18.296.11678-2bbc1e3)
小米路由器mini

2. 运营商  
移动

**重现步骤**

1. 上游DNS配置。  
server 1.1.1.1 -check-edns
server 1.0.0.1 -check-edns
server 8.8.8.8 -check-edns
server 8.8.4.4 -check-edns
server 114.114.114.114
server 208.67.222.222 -check-edns
server 202.96.134.133
server 202.141.178.13:5353
server 202.141.162.123:53
server 101.6.6.6
server 80.80.80.80 -check-edns

2. 访问的域名。  
Baidu.com

blacklist-ip.conf 配置

blacklist-ip 4.36.66.178
blacklist-ip 8.7.198.45
blacklist-ip 37.61.54.158
blacklist-ip 46.82.174.68
blacklist-ip 59.24.3.173
blacklist-ip 64.33.88.161
blacklist-ip 64.33.99.47
blacklist-ip 64.66.163.251
blacklist-ip 65.104.202.252
blacklist-ip 65.160.219.113
blacklist-ip 66.45.252.237
blacklist-ip 72.14.205.99
blacklist-ip 72.14.205.104
blacklist-ip 78.16.49.15
blacklist-ip 93.46.8.89
blacklist-ip 128.121.126.139
blacklist-ip 159.106.121.75
blacklist-ip 169.132.13.103
blacklist-ip 192.67.198.6
blacklist-ip 202.106.1.2
blacklist-ip 202.181.7.85
blacklist-ip 203.98.7.65
blacklist-ip 203.161.230.171
blacklist-ip 207.12.88.98
blacklist-ip 208.56.31.43
blacklist-ip 209.36.73.33
blacklist-ip 209.145.54.50
blacklist-ip 209.220.30.174
blacklist-ip 211.94.66.147
blacklist-ip 213.169.251.35
blacklist-ip 216.221.188.182
blacklist-ip 216.234.179.13
blacklist-ip 243.185.187.39

**Comment by pymumu** [comment]
配置没问题，timeout一般都是IP不通，或服务未启动导致的。

排除一下网络问题和服务问题。

可以登录路由器在配置界面看一下进程是否运行正常。

**Comment by ForeverBRS** [comment]
服务是正常的，但是仍解析超时。我将DNS协议类型设置成tcp就通了，可能是我这边udp协议不通。

**Comment by pymumu** [comment]
是不是UDP协议被重定向到其他无效端口了？

看看有没有安装chinadns吧。

**Comment by ForeverBRS** [comment]
并没有安装chinadns，如何查udp重定向？

**Comment by pymumu** [comment]
用iptable -L -t nat命令查询下53端口的记录

**Comment by ztjal** [comment]
同样有这个问题，但只是有时同现，而且均为打开新域名时才出现，例如浏览器打开收藏夹里的某个，一打开就马上出现找不到域名，点刷新一次不行，二次不行，三次不行，第四次就行了，问题不是固定出现，不知什么时候就出现，一出现【都是】刷新至第四次才正常。
-------------
用nslookup时会出现3个DNS request timed out.
-------------
路由用的固件是PandoraBox 18.07 2018-07-25-git-4a7f2b2
以前用的smartdns.1.2018.11.03-2215.mipsel_1004kc_dsp，这个版本没问题。
但因tls都没法解决污染，试更新新版，但下边两个都一样有同样的问题。
smartdns.1.2019.01.07-2334.mipsel_1004kc_dsp
smartdns.1.2019.01.26-0014.mipsel_1004kc_dsp

@pymumu

**Comment by rufengsuixing** [comment]
dnsmasq 配置文件将smartdns配置成唯一dns来源
eg:smartdns 监听8053
no-resolv
server=127.0.0.1#8053

**Comment by pymumu** [comment]
@ztjal 把/var/log/smartdns.log日志发一下，看看是不是进程挂了之后又重启了。

**Comment by ztjal** [comment]
重新装回smartdns.1.2019.01.26-0014.mipsel_1004kc_dsp
自定义设置打开了
 log-level error
 log-size 128k
 log-file /var/log/smartdns.log
 log-num 2
我用FIREFOX的，打开新域名时左下角有“正在解释”的提示的，偶尔一打开就连“正在解释”的提示都未看清楚就显示找不到域名的页面了。
打开outlook，收件进度连接马上断，有两个服务器域名显示为找不到。
回去看smartdns.log，没异常，日志修改时间也不是那个时候的。
上游服务器我填了五个，三个UDP，两个TLS。均没使用黑名单和反回答伪造。
现在试smartdns.1.2019.02.11-0008.mipsel_1004kc_dsp，看看情况怎么样。

**Comment by rufengsuixing** [comment]
smartdns.1.2019.02.11-0008 没找到这个releases

**Comment by pymumu** [comment]
@ztjal @rufengsuixing 
之前的版本TLS模式有概率进程异常，最近在修复这个问题。
所以，只是临时版本，没有release。

如果愿意帮忙验证，那我可以临时给你们一个。

**Comment by ztjal** [comment]
@pymumu 
[smartdns.log-20190212-153603.gz](https://github.com/pymumu/smartdns/files/2854615/smartdns.log-20190212-153603.gz)
提交一个debug日志，就是先失败，后成功的。
搜索一下“img30.imagetwist.com”。
然后我自己也研究了一下，发现udp的DNS会集体失败？

**Comment by ztjal** [comment]
[smartdns.zip](https://github.com/pymumu/smartdns/files/2854795/smartdns.zip)
现来多个，打开“www.v2ex.com”时刷了三次都失败，是第四次时才成功的。

**Comment by pymumu** [comment]
用新版本验证下，有问题再reopen issue
