### ISSUE TITLE
请问如何引入系统的hosts文件？

### ISSUE THREAD

**Issue by qiumzh** [pymumu/smartdns#822]
**需求应用场景**
Linux系统中使用smartdns后，`/etc/hosts`的自定义域名解析不生效了，请问如何引入host文件呢？

**Comment by Somalia0932** [comment]
看看文档说明，有一个额外配置文件。

**Comment by leetking** [comment]
@qiumzh 请问是通过转换 `/etc/hosts` 为 SmartDNS 格式后引入，还是可以直接引入 hosts 文件呢？

**Comment by qiumzh** [comment]
> @qiumzh 请问是通过转换 `/etc/hosts` 为 SmartDNS 格式后引入，还是可以直接引入 hosts 文件呢？

转换格式引入
```
address /www.myjd.com/192.168.1.2
address /develop.com/192.168.1.2
```

**Comment by leetking** [comment]
哦哦，谢谢啦。

为何不直接支持 hosts，是不是有其他的考虑呢？
@pymumu
