### ISSUE TITLE
openwrt中开启smartdns会造成内网ping软路由延迟变大

### ISSUE THREAD

**Issue by sokingshen** [pymumu/smartdns#826]
正常来说内网网线ping软路由无论如何都应该显示<1ms的，我测试跑coremark全核跑分即使100%cpu占用也不会影响ping的延迟.可以排除cpu占用率的问题，而开启smartdns后则会出现最大内网15ms的延迟，基本最小也会=1ms。
![image](https://user-images.githubusercontent.com/37776230/139590580-99cb8996-aae8-4324-b112-a707a6f6bec6.png)

**Comment by pymumu** [comment]
smartdns没有占资源的地方。不应该出现上述问题。
你可以问题出现的时候，将smartdns进程kill后看看，问题是否存在。
