### ISSUE TITLE
希望可以實現recursive的解析

### ISSUE THREAD

**Issue by yangzhaofeng** [pymumu/smartdns#828]
**需求应用场景**
在機器有多個network interface的情況下，僅轉發query到緩存服務器可能無法滿足多網卡分流等需求。因此可能需要在本地開recursive服務。目前的workaround是開多個bind9 recursive server用 query-source 選項來確定走哪個網卡然後轉發給這幾個bind9，資源開銷較大。

**建议的方案**
增加 recursive 及 recursuve-source 選項，來讓smartdns可以使用多個interface來recursive解析，再挑選最快的結果。

**设备信息**
1. 设备信息（CPU，厂家）  
Intel(R) Xeon(R) CPU E5620 @ 2.40GHz

2. 固件信息

**Comment by PikuZheng** [comment]
没懂是同进同出问题还是上游查询选路问题。前者可以通过开多个进程绑定不同的接口处理，后者是网络路由表问题和dns无关

**Comment by yangzhaofeng** [comment]
recursive查詢定義在rfc1034和rfc1035中。目前smartdns是 forward only 的，需要指定上游。而recursive不需要指定上游，而是從（預定義的）root DNS開始一級一級向下查詢。
我的feature request是讓smartdns可以同時綁定在不同接口，不指定上游，使用每一個接口進行recursive查詢。
可能會根據接口的不同查詢到若干個地址，就像指定多個上游的時候一樣。接下來的過程就一模一樣了，根據默認的路由對這些IP進行測試（一般有多個出口的都會根據目標網段進行分流），從中挑選出最快的返回給查詢者。

**Comment by PikuZheng** [comment]
也就是说，客户端发来一个查询，服务端返回“你去找另一个dns服务器”？

**Comment by yangzhaofeng** [comment]
不是。而是客戶端發來查詢，smartdns就從根開始去找那些“你去找另一個dns服務器”的節點，直到最終從authoritative dns server查到要的結果。
而這個過程可以從不同的網卡發出。比如從eth0和eth1同時進行兩個完整的過程，再對最後從authoritative dns拿到的結果進行比較，來選出最好的返回給客戶端的查詢結果。

**Comment by PikuZheng** [comment]
那就是自身路由表问题了，根据不同目的ip进行eth0或eth1的选路，或负载均衡
