### ISSUE TITLE
支持hosts文件读取

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#83]
支持域名后缀匹配应该会比dnsmasq的搜索速度快，我想用它完全代替dnsmasq的dns部分功能，因为路由器性能较低，希望能够添加支持

**Comment by pymumu** [comment]
host格式是一对一的，并没有通配的支持。

性能差的路由器支持hosts，会需要占用比hosts文件大2倍的内存。

建议是先用命令将hosts转换为smartdns认识的格式。
```sh
grep -v -e "^ *$" /etc/hosts | awk '{print "address /"$2"/" $1}'
```
hosts支持后面考虑增加。

**Comment by xiaoxinpro** [comment]
smartdns格式的性能不行，我添加了8000行直接卡死luci界面，dnsmasq的Hosts是正常的。

**Comment by VanDeAnna** [comment]
> smartdns格式的性能不行，我添加了8000行直接卡死luci界面，dnsmasq的Hosts是正常的。

是Luci的性能不行，
/etc/smartdns/custom.conf
 添加
`conf-file [conf-file-path]`
來包含外部文件

**Comment by enihcam** [comment]
when will smartdns support hinting by /etc/hosts?
