### ISSUE TITLE
建议在luci增加一个结果返回显示界面

### ISSUE THREAD

**Issue by wenpo1975** [pymumu/smartdns#830]
**需求应用场景**
1、应对域名污染
2、分析网络使用中出现的问题

**建议的方案**
直接明了地显示：
1、请求查询的主机、查询的域名、返回的IP、各组DNS返回的结果、整体查询的延迟

现审计功能不足以实现上述问题

**Comment by pymumu** [comment]
开启audit-syslog后，在luci的系统日志界面查看。
