### ISSUE TITLE
增加被dns污染域名检测

### ISSUE THREAD

**Issue by loutelecom** [pymumu/smartdns#834]
需求应用场景
请描述需求应用的场景和方式。
被dns污染的域名走国外加密dns分组，正常域名走国内dns，既保证解析准确，又避免把有国内cdn/服务器的网站解析到国外
建议的方案
实现上述场景建议的方案。
读取指定位置的GFWlist列表，收到查询请求后查看是否在列表中如果在，使用国外分组dns
设备信息

设备信息（CPU，厂家）
i5-7200u 英特尔，mipsel mt7621 联发科
固件信息
openwrt padavan

**Comment by PikuZheng** [comment]
配置文件中的nameserver 不就是干这个用的？

**Comment by yaott2020-666** [comment]
可以尝试chinadns-ng

**Comment by loutelecom** [comment]
> 配置文件中的nameserver 不就是干这个用的？

这个只能一个域名一个域名添加把

**Comment by loutelecom** [comment]
> 可以尝试chinadns-ng

chinadns不支持加密dns

**Comment by yaott2020-666** [comment]
> > 可以尝试chinadns-ng
> 
> chinadns不支持加密dns

前面套个smartdns不就行了
