### ISSUE TITLE
Permit multiple runtime instances

### ISSUE THREAD

**Issue by jtbr** [pymumu/smartdns#837]
I'm limited to English may not have the latest version so my apologies in advance if this is no longer relevant. Thank you for the useful software.

I would like to suggest that smartdns allow running multiple simultaneous instances, each with their own caches. In my version, smartdns will not run more than once. 

I am aware that it is possible to bind to multiple ports with different features. However it can be useful to have different caches as well, for example when traffic for that DNS is via different interfaces. For example, one interface may only use a VPN, or a different internet provider than the first interface. We would want different cache entries for the two interfaces.

**Comment by PikuZheng** [comment]
Yes.
with “cache-file”,  you can assign different caches for different processes. Just specify different configuration files for different processes at startup.

**Comment by jtbr** [comment]
> with “cache-file”, you can assign different caches for different processes. Just specify different configuration files for different processes at startup.

That is what I'd like to do, but when I try to run smartdns a second time, I find that it exits immediately. Perhaps this is not the case with the newest version of smartdns (?), as I did not build it myself.

**Comment by PikuZheng** [comment]
I don't think so. maybe you specified the same port, configuration, or log file. Check the log for the reason why the program exited.
Some version has bugs with cache-file, but I'm not very sure.

**Comment by jtbr** [comment]
> I don't think so. maybe you specified the same port, configuration, or log file. Check the log for the reason why the program exited. Some version has bugs with cache-file, but I'm not very sure.

To test I'm using two config files with different bind ports, cache files, and log files. Either one will run fine on its own. Whichever one I start second while the other one is still running does not create or write to the log file and immediately, silently exits, even with `log-level debug`. So unfortunately I have no error to work with.

**Comment by jtbr** [comment]
I found the problem. SmartDNS defaults to using a pid file at `/var/run/smartdns.pid`. This is locked by the first instance, and trying to run again with the same pid file will fail. There is a command line-only option to modify the pid file, however. Specifying a different file for each instance solves the problem!

ie: 
```
smartdns -c config1.conf -p /var/run/smartdns1.pid
smartdns -c config2.conf -p /var/run/smartdns2.pid
```

This should probably be documented in the Readme file. But since I can only edit the English version, I'll leave this to others.
