### ISSUE TITLE
[Feature Request] 不同上游服务器、服务器组使用不同的 speed-check-mode

### ISSUE THREAD

**Issue by SukkaW** [pymumu/smartdns#839]
**需求应用场景**

1. Office 组上游只用于解析内网域名，可以不设置测速
2. 只为 Domestic 组的上游服务器设置测速、禁用 Default 的测速，避免 smartdns 向非 Domestic 域名发送 ICMP 报文、进行 TCP 握手

**建议的方案**

- domain-rules 已经支持 speed-check-mode，但是需要为数条域名重复设置相同的 speed-check-mode
- 在 Server 组中设置 speed-check-mode，避免为每条 domain-rules 设置 speed-check-mode

**Comment by pymumu** [comment]
最新代码已经支持

group-begin group
speed-check-mode xxx
group-end
