### ISSUE TITLE
增加代理dns选优

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#84]
**需求应用场景**
能够主动通过代理tcp测速，如果代理网速较好，则加入ipset，适当配置iptables 可以做到代理和本地共同选优

**建议的方案**
现在实现的是，
所有dns查询---ipcm测速---300ms fallback tcp---     返回最先结果
改为
所有dns查询---icmp测速---300ms fallback tcp---     &emsp;&emsp;&emsp;&emsp;双选优（代理快则加指定ipset）
&emsp;&emsp;&emsp;&emsp;&emsp; ---via代理tcp测速（透明代理可以ipset解决）
可能的bug就是300ms fallback tcp 和 代理tcp可能会有时间冲突

有实现的可能么

**Comment by pymumu** [comment]
可能的方案是所有检测超时后，加入ipset。

这样带来的问题是，解析时间延长，增大域名缓存时间能优化影响。
但还要细化考虑。

**Comment by rufengsuixing** [comment]
所有检测超时加入ipset我觉得可以
tcp测速的话因为ss或者v2ray的socks5实现不标准，会直接本地返回，http header也不是所有都能用
两种方式都超时的话也就意味着用户已经连不上了，加入代理ipset反而能防止直接返回超时页面
