### ISSUE TITLE
Support local domains for nameserver option

### ISSUE THREAD

**Issue by jtbr** [pymumu/smartdns#840]
As far as I can tell, smartdns does not support forwarding to a specific nameserver group for local domains; i.e. domains with no extension. I suggest adding support for an empty domain in the `nameserver` config option.

Imagine a setup where we want to forward local hosts to a local dns resolver; this is not possible without including a top level domain.

```
server 8.8.8.8
server 127.0.0.1:6053 -group local -exclude-default-group
nameserver /.mylocalnet/local
#these apparently have no effect:
nameserver //local
nameserver /./local
```

```
# succeeds NOERROR with ANSWER section:
dig myserver.mylocalnet
# fails NXDOMAIN with AUTHORITY section, recursively querying top-level DNS servers via 8.8.8.8:
dig myserver
# returns the correct address, along with SERVFAIL (it looks like it's returning the result from both name servers in both the ANSWER and the AUTHORITY sections):
nslookup myserver
```

If both `myserver.mylocalnet` and `myserver` were both forwarded to `127.0.0.1:6053` (only), they would both succeed.

I am testing with Release 30 but I don't notice anything in new releases that would have changed this functionality.

**Comment by PikuZheng** [comment]
It works for me.
```
server 172.17.2.172 -group test -exclude-default-group
nameserver /mikrotik/test
```

```
C:\Users\Administrator>nslookup mikrotik. 11.20.3.103
服务器:  smartdns
Address:  11.20.3.103

非权威应答:
名称:    mikrotik
Addresses:  172.17.2.172
          11.20.3.96
```

**Comment by jtbr** [comment]
So, I haven't tested yet, but from your comment it looks like a workaround is to create a nameserver line for every host you want to resolve on the local network.

It would be convenient to be able to redirect all top level domains (ie, local hosts having no '.' in them) with a single nameserver line though.

**Comment by PikuZheng** [comment]
> 

well, I believe a single host name without suffix is illegal for dns system. Maybe you need a wins server.

**Comment by pymumu** [comment]
add mdns support. enable by `mdns-lookup yes`

**Comment by jtbr** [comment]
Can you shed some light onto how this would be used? By mdns I guess you mean multicast DNS. So this would be an alternative approach to access local network devices rather than relying on a local DNS server like dnsmasq which has entries for local devices? If so, how does it work with smartdns caching etc? If you enable `mdns-lookup`, is smartdns always monitoring the local multicast packets then? Many thanks

**Comment by pymumu** [comment]
The functions implemented are your needs,

After mdns-lookup yes is turned on, the local host query will be sent to mDNS for query and returned.

like
```
dig -x 192.168.1.1
dig macbookpro
dig raspberrypi.local
```
