### ISSUE TITLE
无法从外网使用DNS

### ISSUE THREAD

**Issue by xiao-gy** [pymumu/smartdns#841]
**问题现象**  
Centos系统下搭建，无法从外网使用DNS，服务器本地可以正常使用dns。
![image](https://user-images.githubusercontent.com/45650719/142514367-47d4ef59-6ed4-4681-b01a-c700a3d731d5.png)

**运行环境**
1. 固件型号  

Centos7.6

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

无关

2. 访问的域名。  

所有

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by lalasou** [comment]
看看防火墙 还有 最好外网tcp
Padavan关闭防火墙 后 外网正常使用tcp udp 都可  udp 偶尔错误
