### ISSUE TITLE
OpenWrt 安装遇到Segmentation fault

### ISSUE THREAD

**Issue by hq26825** [pymumu/smartdns#842]
**问题现象**  
root@OpenWrt:/data/workspace# opkg install smartdns.11.2021.08.07-1628.x86_64-openwrt-all.ipk 
Segmentation fault
root@OpenWrt:/data/workspace# opkg install smartdns.1.2021.08.27-1923.x86_64-openwrt-all.ipk 
Segmentation fault
root@OpenWrt:/data/workspace# cat /proc/version 
Linux version 5.4.150 (esir@u18) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r3790-13792caf1)) #0 SMP Fri Oct 8 08:50:43 2021
root@OpenWrt:/data/workspace# opkg print-architecture
arch all 1
arch noarch 1
arch x86_64 10

安装smartdns时出现段错误segmentation fault，两个版本都是这样，请问如何解决，谢谢。

**运行环境**
1. 固件型号  
OpenWrt Buddha V10 [2021] Compiled by eSir / LuCI Master (git-21.280.14233-9b796b1)
kernel：5.4.150
x86_64
2. 运营商  
电信

**重现步骤**
1. wget下载或本地下载再winscp上传都会出现这个问题。  

2. 直接运行opkg install smartdns.xx.ipk就出错。

3.问题出现在安装过程  

**信息收集**  
logread有如下两行信息
Fri Nov 19 11:11:22 2021 kern.info kernel: [496335.759260] opkg[13066]: segfault at 7fdbf8764000 ip 00007fdbf87406b6 sp 00007fdbf86cca38 error 4 in libc.so[7fdbf8704000+49000]
Fri Nov 19 11:11:22 2021 kern.info kernel: [496335.771116] Code: e9 c7 ff ff ff 90 48 89 f8 48 83 fa 08 72 14 f7 c7 07 00 00 00 74 0c a4 48 ff ca f7 c7 07 00 00 00 75 f4 48 89 d1 48 c1 e9 03 <f3> 48 a5 83 e2 07 74 05 a4 ff ca 75 fb c3 48 89 f8 48 29 f0 48 39

**Comment by PikuZheng** [comment]
请问系统内存有多少

**Comment by hq26825** [comment]
> 

总内存4GB，可用3GB以上。
后面还是没解决，换OP版本就没问题了。
