### ISSUE TITLE
ipset使用问题

### ISSUE THREAD

**Issue by ixmu** [pymumu/smartdns#843]
**问题现象**  
ipset并没有讲记录添加到表中

**运行环境**
1. 固件型号  
openwrt x86路由，smartdns作为dnsmasq上游
配置：
nameserver /google.com/GFW
ipset /google.com/gfwlist
nameserver /youtube.com/GFW
ipset /youtube.com/gfwlist

ipset list gfwlist是空的，没有ip

**Comment by PikuZheng** [comment]
```
ipset /taobao.com/gfwlist
```

```
root@OpenWrt:~# ipset list gfwlist
Name: gfwlist
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 0
Number of entries: 0
Members:
root@OpenWrt:~#
```

```
C:\Users\Administrator>nslookup www.taobao.com. 11.20.3.103
服务器:  smartdns
Address:  11.20.3.103

非权威应答:
名称:    www.taobao.com.danuoyi.tbcache.com
Addresses:  2408:8630:2090:1:3::3ed
          2408:8630:2090:1:3::3ee
          42.7.48.209
          42.7.48.208
Aliases:  www.taobao.com
```

```
root@OpenWrt:~# ipset list gfwlist
Name: gfwlist
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 472
References: 0
Number of entries: 2
Members:
42.7.48.208
42.7.48.209
```

**Comment by whiler** [comment]
可以贴一下这两个命令的输出：

1.  内核版本 `uname -r`
2. 内核日志 `dmesg -w | grep smartdns` 

如果是 **5.10.y** 及以上的内核，会有类似 `netlink: 'smartdns': attribute type 6 has an invalid length.` 的日志。
这个问题已经在 https://github.com/pymumu/smartdns/pull/848 中修复了，目前有三种方法可以解决这个问题：

1. 尝试自行编译最新的 master 分支，并安装
2. 将内核降级到 **5.10.y** 以下的版本
3. 等待下一个版本发布

**Comment by crysislinux** [comment]
我自己编译了master的代码，配置了ipset-timeout yes, 确实能正常添加了到ipset了
