### ISSUE TITLE
华硕ac86u问题

### ISSUE THREAD

**Issue by trigsoft** [pymumu/smartdns#844]
麻烦问下系统日志一直出这样得log正常嘛？
Nov 22 10:05:29 kernel: Hardware name: Broadcom-v8A (DT)
Nov 22 10:05:29 kernel: task: ffffffc01e887480 ti: ffffffc007bf4000 task.ti: ffffffc007bf4000
Nov 22 10:05:29 kernel: PC is at 0x125b68
Nov 22 10:05:29 kernel: LR is at 0x1e2d7
Nov 22 10:05:29 kernel: pc : [<0000000000125b68>] lr : [<000000000001e2d7>] pstate: 00000030
Nov 22 10:05:29 kernel: sp : 00000000f71eeee8
Nov 22 10:05:29 kernel: x12: 00000000f71eeef8 
Nov 22 10:05:29 kernel: x11: 00000000001aac64 x10: 00000000f71eef8c 
Nov 22 10:05:29 kernel: x9 : 00000000f71efc1c x8 : 00000000f71efc1c 
Nov 22 10:05:29 kernel: x7 : 0000000000000193 x6 : 00000000001a6670 
Nov 22 10:05:29 kernel: x5 : 00000000001aac64 x4 : 0000000000000193 
Nov 22 10:05:29 kernel: x3 : 00000000f71eeef8 x2 : 0000000000000001 
Nov 22 10:05:29 kernel: x1 : 00000000f71eeef8 x0 : 0000000000000001 

选用得是arm-optware得版本

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
