### ISSUE TITLE
怎么设置能让他同时监听v4和v6端口

### ISSUE THREAD

**Issue by apnic** [pymumu/smartdns#85]
同时配置
bind :53
bind [::]:53
只会监听v6端口，怎么设置能让他同时监听v4和v6端口
谢谢

**Comment by rufengsuixing** [comment]
我这边测试是同时监听的
bind [::]:8053

router /opt/etc/smartdns]# dig www.bilibili.com @::1 -p 8053

; <<>> DiG 9.11.5 <<>> www.bilibili.com @::1 -p 8053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32936
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.bilibili.com.              IN      A

;; ANSWER SECTION:
www.bilibili.com.       209     IN      CNAME   interface.biliapi.com.
interface.biliapi.com.  116     IN      A       106.75.74.76

;; Query time: 22 msec
;; SERVER: ::1#8053(::1)
;; WHEN: Sat Feb 09 23:53:46 UTC 2019
;; MSG SIZE  rcvd: 122

[router /opt/etc/smartdns]# dig www.bilibili.com @127.0.0.1 -p 8053

; <<>> DiG 9.11.5 <<>> www.bilibili.com @127.0.0.1 -p 8053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52355
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.bilibili.com.              IN      A

;; ANSWER SECTION:
www.bilibili.com.       209     IN      CNAME   interface.biliapi.com.
interface.biliapi.com.  104     IN      A       106.75.74.76

;; Query time: 0 msec
;; SERVER: 127.0.0.1#8053(127.0.0.1)
;; WHEN: Sat Feb 09 23:53:58 UTC 2019
;; MSG SIZE  rcvd: 122

**Comment by apnic** [comment]
我的为什么就不行，安装的smartdns.1.2019.01.26-0014.armhf.deb
系统是armbian，配置bind [::]:53时只监听v6的

**Comment by fonlan** [comment]
是不是你的V4的53口已经被别的进程占了？

**Comment by pymumu** [comment]
sysctl net.ipv6.bindv6only
看看这个是多少。

如果是1的话，改成0。

**Comment by apnic** [comment]
net.ipv6.bindv6only = 0

**Comment by pymumu** [comment]
这个为0的话，就表示绑定了ipV4和ipv6

dig命令测试一下ipv4是否可以连接，可以的话就不用在意配置和netstat看到的
