### ISSUE TITLE
如何配置能够实现双栈域名仅返回IPv4地址，对于IPv6 only域名直接返回IPv6地址？

### ISSUE THREAD

**Issue by tpishere** [pymumu/smartdns#852]
**需求应用场景**
有访问部分IPv6 only的网站需求，对于双栈网站更希望直接IPv4访问。
双栈IP优选虽然能一定程度上满足该需求，但也会遇到部分双栈网站的IPv6地址延迟测试响应更快，但无法联通的情况（可能是运营商的IPv6线路问题），从而导致网站无法访问。

**建议的方案**
双栈域名仅返回IPv4地址，对于IPv6 only域名直接返回IPv6地址

**Comment by 1phalley** [comment]
自定义设置里添加conf-file /etc/smartdns/smartdns.more.conf
在里面屏蔽掉常用网站的ipv6地址解析就可以仅解析ipv4
格式是
address /000webhost.com/#6
address /030buy.com/#6
address /0rz.tw/#6
ipv6 only似乎直接能打开
