### ISSUE TITLE
增加支持DoQ（Dns Over HTTPS/3）和DnsCrypt V2

### ISSUE THREAD

**Issue by asterriya** [pymumu/smartdns#854]
你能增加对DoQ（Dns Over HTTPS/3）和DnsCrypt V2的支持吗？

如果你能添加更多的缓存选项，如Unbound，并改进选择最快服务器的算法，我也很感激。

**Comment by jkle112** [comment]
HTTP Strict Transport Security (HSTS) 希望可以增加这个安全功能，这样也是防止伪造和欺骗

**Comment by pymumu** [comment]
跟踪参考：
https://github.com/pymumu/smartdns/issues/1570
