### ISSUE TITLE
无通信超时配置和 tcp-idle-time 重用连接导致 server-tcp 查询请求卡死

### ISSUE THREAD

**Issue by asbai** [pymumu/smartdns#855]
**问题现象**  
`tcp-idle-time N` 导致只要最近 N 秒内有查询就会重用连接。
而 server-tcp 请求没有可配置的通信超时，同时 tcp 协议栈重传和故障检测机制相当迟缓。导致一些看似健康实则已断开的 TCP 连接不断被尝试重用，但总是无法成功。

**运行环境**
1. 固件型号  
Ubuntu Linux 20.04 on ARM64

2. 运营商  
CT

**重现步骤**
1. 上游DNS配置: `server-tcp x.x.x.x:53; tcp-idle-time 120;`

2. 访问的域名: google.com

3. 在网络正常时 `nslookup google.com` 查询成功，同时可以看到查询所用 TCP 连接处于空闲保持状态。

4. 120秒内 `poff` 断开 pppoe 拨号；然后重复 `nslookup google.com`，此时 nslookup 命令超时，tcpdump 抓包可以看到 smartdns 在向之前的空闲连接发请求。

5. 此时立刻 `pon dsl-provider` pppoe 重新拨号；然后重复 `nslookup google.com`，**此时 nslookup 命令仍然超时**，tcpdump 抓包可以看到 **smartdns 仍然在尝试使用 `poff` 之前的那个 TCP 连接发请求**。

因此，在 smartdns 中需要增加一个查询超时或出错即断开对应 tcp 连接，下次请求重建新连接的机制。

**Comment by asbai** [comment]
另外我想再补充一下：在使用 tcp based query 时，如果发现当前连接的上一个请求还没返回，则应该考虑限制继续使用该连接发送下一个查询请求（pipelining），否则也可能出现上述的 head of line blocking 问题。

所以最好是用户可配置的查询请求超时 + pipelining 控制 + 多并发查询三者结合效果才最好。

**Comment by PikuZheng** [comment]
我记得这个问题在好久之前就修理过了。刚我测试发现虽然重用了连接，但大约6秒后就（因为无应答）超时断开然后重新连接了。
以我的经验很有可能你的server用的域名，或者有循环查询问题。

**Comment by PikuZheng** [comment]
#529 #679

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
