### ISSUE TITLE
x86无法安装？

### ISSUE THREAD

**Issue by cicai1631** [pymumu/smartdns#858]
**问题现象**  
手动上传ipk，服务中没有出现smartdns

**运行环境**
1. OpenWrt R21.6.1 GDQ v6.1[2021] Compiled by eSir / LuCI Master (git-21.114.56541-974fb04)

**Comment by cicai1631** [comment]
内核版本 | 5.4.122

**Comment by LD-KiLLer** [comment]
同样的问题，试了compat版本的luci也是出不来，安装也没有报错

**Comment by ttyycool** [comment]
我也是同样的问题，刚尝试了一下好像是lean固件的原因，换了其他版本的openwrt是可以显示的

**Comment by LD-KiLLer** [comment]
装了34版本的可以正常显示，大家伙可以临时解决下

**Comment by hpcex** [comment]
> **问题现象** 手动上传ipk，服务中没有出现smartdns
> 
> **运行环境**
> 
> 1. OpenWrt R21.6.1 GDQ v6.1[2021] Compiled by eSir / LuCI Master (git-21.114.56541-974fb04)

重启一下就有了。

**Comment by pymumu** [comment]
一般是luci的刷新问题，compat版本会有这些问题，最好用openwrt官方最新的UI。
