### ISSUE TITLE
centos下不加 -f 程序无法启动

### ISSUE THREAD

**Issue by rekey** [pymumu/smartdns#859]
**问题现象**  
centos下不加 -f 程序无法启动

**运行环境**
1. 虚拟机 centos

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
这两种启动方式，没有什么区别，看看日志里面有什么。

可能是权限问题。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
