### ISSUE TITLE
Default Domain Supports

### ISSUE THREAD

**Issue by snowyu** [pymumu/smartdns#861]
**需求应用场景**

在局域网查询内部主机名称自动添加设置的默认域名.

**建议的方案**

增加配置默认域名: `default-domain`, 以便访问本地机器.

配置及用法:

```conf
default-domain=lan
server 192.168.0.1 -group home -exclude-default-group
nameserver /.lan/home
```

```bash
ping hostname
PING hostname.lan (192.168.0.3) 56(84) bytes of data.
```

See Also: #840

**Comment by PikuZheng** [comment]
这个默认域名是dns客户端查询时提供的，应通过DHCP Server的Option 15（RFC2132）提供给DHCP 客户端，或在网卡配置中手动指定（对应 Windows 网卡设置中的“此连接的DNS后缀”。
另一方面本地主机间使用主机名访问不一定是用的DNS，可能用的是WINS。

**Comment by snowyu** [comment]
Also see the DNSMASQ CONFIG : https://wiki.archlinux.org/title/dnsmasq#Adding_a_custom_domain

**Comment by pymumu** [comment]
dnsmasq-lease-file是否足够。如果不行，可以细化说明一下方案。

**Comment by mokeyish** [comment]
嗯，你们看看什么方案好。我后面也加到这个 rust 版里去 😅
https://github.com/mokeyish/smartdns-rs

**Comment by pymumu** [comment]
增加了mdns，可以通过mdns-lookup开启。
