### ISSUE TITLE
有没有Windows版本的

### ISSUE THREAD

**Issue by KelvinSoh8** [pymumu/smartdns#865]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. X86-64 Intel英特尔，AMD 家用电脑

2. Windows系统

**Comment by PikuZheng** [comment]
要不试试yogadns？windows，有界面，走winsocks接口

**Comment by LsnmxNB** [comment]
> yogadns

[29.95 USD]
