### ISSUE TITLE
大佬能否有空修复下TTL不变的问题？

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#867]
反馈这个问题的人已经不少了，#787  #630 ，简单说就是如果关闭了测速，TTL就不会变。

希望大佬能抽空修复下这个BUG，非常感谢！

测试方法很简单：
domain-rules /www.163.com/ -speed-check-mode none
直接解析www.163.com这个域名就可以看到TTL不会变。

关闭测速的原因是：gfwlist域名解析出的IP测速没有什么意义，反而会拖慢解析速度。

**Comment by w22gb8** [comment]
+1

**Comment by pymumu** [comment]
当前非测速模式，缓存的数据包，并没有接口修改TTL值。这一部分要支持有一些工作量。

TTL不变有什么影响吗

**Comment by PHCSJC** [comment]
有影响呢，大佬，主要是动态域名的ip一直不更新

**Comment by pymumu** [comment]
这个TTL值，电脑，手机端是有缓存的，会自己倒计时的。理论上smartdns返回的不变也没有多大影响。

是不是问题可能是缓存一直不过期导致，而不是你说的TTL值不变化。

**Comment by PHCSJC** [comment]
大佬我可能描述不清，是这个意思：TTL值不变导致smartdns里缓存的动态域名对应的ip地址一直不变，即便域名商那ip已经改变了，但从smartdns获取的ip依然是旧的

家里的宽带是adsl，用的动态域名，我在公司连家里就连不上了（旧ip），把smartdns进程kill再启动就好了。

**Comment by w22gb8** [comment]
有些时候会相当于延长ttl值，如域名ttl为600，smartdns缓存时ttl为600，500秒后客户端通过smartdns取ttl为缓存值600，这就变相将ttl延长为1100。

**Comment by pymumu** [comment]
延长情况是已知的情况，最多延长2倍。

但一直不刷新，那就是问题。

**Comment by pymumu** [comment]
刚刚基本测试了一下，虽然返回的TTL不变，但TTL到期后，smartdns会从缓存里面删除
这时再次请求的话，就会更新数据了。

**Comment by PHCSJC** [comment]
如果这个参数启用，ip就不会变了，大佬你试试
serve-expired yes

**Comment by pymumu** [comment]
我编译个版本给你看看吧。你啥系统？

**Comment by PHCSJC** [comment]
arm64或amd64都可以的

**Comment by PHCSJC** [comment]
还有个cname ttl不变的bug，大佬有空看看：#787

**Comment by pymumu** [comment]
[smartdns-aarch64.zip](https://github.com/pymumu/smartdns/files/8067872/smartdns-aarch64.zip)
测试看看

**Comment by PHCSJC** [comment]
好的，感谢，我试试

**Comment by PHCSJC** [comment]
大佬你好，测试已经没问题了，关闭测速动态域名的ip已经可以正常更新了

再说下发现的二个问题，也不知道有没有什么影响。
1.动态域名ip虽然会更新了，但ttl值还是不变，不过好像也没啥影响
2.dig www.baidu.com，这个解析是有cname的，cname的ttl也不会变，不知道有没有什么影响，比如域名商那cname发现变动了
再次感谢！

**Comment by pymumu** [comment]
[smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/8078405/smartdns-x86_64.zip)
[smartdns-aarch64.zip](https://github.com/pymumu/smartdns/files/8078406/smartdns-aarch64.zip)

**Comment by PHCSJC** [comment]
非常感谢，实测cname的ttl会变了
