### ISSUE TITLE
请问能否开源呢

### ISSUE THREAD

**Issue by zanzhz1101** [pymumu/smartdns#87]
请问能否开源呢，可以扩大使用范围

**Comment by pymumu** [comment]
关于开源：
软件本身属于个人爱好，自己也在使用，从开始就没有考虑过从这个软件上获取利润。在目前情况下，也希望小范围使用，避免不必要的麻烦。
没开源只是为了避免某些人利用软件做损害我个人利益的事情。后面时机成熟会开源的。
