### ISSUE TITLE
有些游戏在使用Smartdns之后会出现无法加载的问题

### ISSUE THREAD

**Issue by tobycroft** [pymumu/smartdns#873]
**问题现象**  
简要描述问题出现的现象

在需要EDNS环境的情况下使用smartdns会导致出错。

我从17年就开始用Smartdns了，2021年《微软模拟飞行2020》的秋季版更新了，差不多在8-9月份，这次软件的更新后，微软对DNS返回进行验证，我发现会在查询到微软的游戏（content-deliver）服务器地址后，在正常的dns的基础上有一些关于edns的内容，关于edns技术我也不是太懂。

在我使用dig之后，我发现无论是谷歌dns还是本地电信的dns或者114的，在查询后都会返回edns信息，但是这些信息在经过了smartdns处理之后，edns信息就丢失了。

起初我以为是smartdns的解析结果和微软的实际cdn服务器的ip不一样，但是经过多次验证后发现并不是ip解析错误导致的问题，所以所有的问题就全部落在edns上面了。

然后我查询了大量资料后发现微软系的很多游戏凡是走了微软cdn的，都加入了对edns的检查，没有edns标签的游戏就会显示you are offline什么什么的。

所以对于这个我暂时没有能力解决了，我查询了smartdns的文档后发现对于edns这块，介绍几乎没有，相关的edns配置也与这个问题无关，所以在将近半年后将这个问题反馈给开发者，希望可以加入诸如"fake edns"返回的功能，或者直接把上级的edns返回。

**运行环境**
1. 固件型号  
linux_x64
2. 运营商  
三网都有接入

**重现步骤**
1. 上游DNS配置。  
8.8.8.8
114.114.114.114
129.29.29.29（腾讯那个dns）

2. 访问的域名。  
www.qq.com(不管啥域名都有edns)
微软的游戏cdn：pf-cdn-content-prod.azureedge.net

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
用wireshark抓包看了 smartdns正确的返回了edns信息 怀疑你配置的上游就没返回edns信息

**Comment by tobycroft** [comment]
> 用wireshark抓包看了 smartdns正确的返回了edns信息 怀疑你配置的上游就没返回edns信息

我用dig看了，确实没有，我查了上游，8.8.8.8有的，然后114也是有的，所以这个很奇怪过了smartdns之后就没了

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/151133594-3c7297cc-b092-45b2-b17d-35d055af1434.png)

**Comment by PikuZheng** [comment]
左边的是开了测速的。关掉就有了

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/151153013-a011f632-5714-44e4-bc49-ee78592c3c15.png)
![image](https://user-images.githubusercontent.com/24893075/151153012-a7bc5c32-d936-42eb-9e22-20e82f7d64b2.png)

没有测速然后返回多了一些，还是没有edns

**Comment by PikuZheng** [comment]
您这结果里都有AUTHORITY SECTION了 请务必考虑一下上游问题

**Comment by PHCSJC** [comment]
就个人了解，smartdns会把edns信息给过滤了，所以返回的是无edns的

**Comment by tobycroft** [comment]
> 就个人了解，smartdns会把edns信息给过滤了，所以返回的是无edns的

上面那位说的对，就是如果你不用测速，确实是可以支持edns的，可是……我用smartdns不就为了测速呢，可太难了

**Comment by Chan0001** [comment]
真专业，最近频繁刷了多个openwrt系统。R4S只要开启smartdns插件，就会出现qq.com腾讯系所有网站一直转圈无法加载完成。看完楼主发的才知道确实是smartdns的问题，请问楼主现在有解决或者替代方案吗

**Comment by PikuZheng** [comment]
> qq.com腾讯系所有网站一直转圈无法加载完成

如果只是腾讯系网站，考虑配置问题。请单独开issue讨论
已知微信调用的域名如下：
```
.qq.com
.qq.com.cn
.qpic.cn
.servicewechat.com
.wechat.com
.qlogo.cn
```

**Comment by pymumu** [comment]
最近新增结果返回模式，测速后，返回的不是单个IP，而是IP所属的整个回应，等代码整理好后，可以测试。

也可以临时编译个版本，你们测试下看看，能不能解决问题。

**Comment by tobycroft** [comment]
> 

因为我用smartdns，我希望解决最大的问题，是ipv6和ipv4的切换问题，例如我访问一些站点，明明使用Ipv4更快，但是因为有ipv6，系统会自动选择ipv6，我认为这样是不对的，所以使用smartdns就能解决这个问题，所以我希望可以做一个降级模式，速度的匹配仅针对aaaa，如果aaaa速度更快，则返回整个aaaa的内容，如果aaa更快，则返回aaa的原文，这样就保留了测速+edns的信息

我现在的解决方案是使用dns2sock+dns选择器，如果是部分域名，则直接使用国外dns解析，否则使用国内的，但是就会遇到ipv6的问题，因为有些国外的地址就会解析成ipv6的，所以还是要依赖smartdns的测速功能来解决这个问题

**Comment by tobycroft** [comment]
> 

还有就是淘宝方面的，使用ipv6后会经常触发拉取验证，非常烦，所以整个淘宝系的aaaa我都屏蔽了，所以我希望整个系统里面是保留aaaa的，因为有些地址只有aaaa，如果把forceaaaa给他开了，那所有的aaaa都解析不出来了，难受……

这块只能靠作者来修

然后很不幸的是，整个微软系列的游戏，全部需要验证edns，如果dns不符，连xbox都打不开，非常难受，之前只是模拟飞行这一款游戏没办法联机，现在是打开游戏就会直接提示“需要插入光盘”，这是因为联网鉴权失效了，另外不知道从什么时候起，在smartdns环境下，现在连xbox都无法打开了，使用了上面说的直接通过“切换dns服务器通道”的程序，就能正常，但是ipv6也有墙，有些地址无法访问，还……挺吐血的

这个问题目前也比较严重了，作者这块可能需要关注下了呢

**Comment by PikuZheng** [comment]
> > 
> 
> 还有就是淘宝方面的，使用ipv6后会经常触发拉取验证，非常烦，所以整个淘宝系的aaaa我都屏蔽了，所以我希望整个系统里面是保留aaaa的，因为有些地址只有aaaa，如果把forceaaaa给他开了，那所有的aaaa都解析不出来了，难受……
> 
> 这块只能靠作者来修
> 
> 然后很不幸的是，整个微软系列的游戏，全部需要验证edns，如果dns不符，连xbox都打不开，非常难受，之前只是模拟飞行这一款游戏没办法联机，现在是打开游戏就会直接提示“需要插入光盘”，这是因为联网鉴权失效了，另外不知道从什么时候起，在smartdns环境下，现在连xbox都无法打开了，使用了上面说的直接通过“切换dns服务器通道”的程序，就能正常，但是ipv6也有墙，有些地址无法访问，还……挺吐血的
> 
> 这个问题目前也比较严重了，作者这块可能需要关注下了呢

是说双栈ip优选这个功能吗 一个月只开两三天ipv6的我表示问题不大 :)

**Comment by PHCSJC** [comment]
@PikuZheng 不能这么说，楼主的问题绝不是极个别人才遇到的，而是普通的需求，而且遇到这样问题的人肯定会越来越多

**Comment by PikuZheng** [comment]
> @PikuZheng 不能这么说，楼主的问题绝不是极个别人才遇到的，而是普通的需求，而且遇到这样问题的人肯定会越来越多

对，其实我觉得我才是用法特殊。。。

**Comment by pymumu** [comment]
取response-whole分支代码验证下看看啊

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/161533472-abd3d1ca-355e-4219-a7b4-de5ea754693d.png)

@pymumu 

编译编不动啊，不然……作者直接发布版本吧

**Comment by PikuZheng** [comment]
> 

#891 编译的时候设置CFLAG=-std=c99
CFLAG=-std=c99 make all

**Comment by tobycroft** [comment]
![image](https://user-images.githubusercontent.com/24893075/161671629-8c40f982-4092-4b81-baea-f8d6ddc45d69.png)

依旧不行啊

@PikuZheng

**Comment by PikuZheng** [comment]
> 

您用的是 GNU 。。。需要 CFLAGS=-std=c99

**Comment by pymumu** [comment]
[smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/8418327/smartdns-x86_64.zip)

**Comment by tobycroft** [comment]
> [smartdns-x86_64.zip](https://github.com/pymumu/smartdns/files/8418327/smartdns-x86_64.zip)

谢谢

**Comment by tobycroft** [comment]
这边其实用smartdns是为了解决几个问题（在whole-repsonse模式开的情况下）：

1.对多个dns进行测试，最终返回最快的某个dns的结果群完整复制返回：，不同的运营商之间可能对某个域名有不同的返回，例如国内ping某个网址，联通会返回联通的地址群，电信会返回电信的地址群，这个时候使用smartdns对联通和电信的ip进行测试，就能知道联通的dns的ip快还是电信的快，如果电信的快，就将电信的整个ip组返回即可

2.针对特定dns服务器开启whole-response：有些IP需要走国外的IP，所以如果可以针对特定的dns服务器开启whole-response模式也是特别不错的

3.针对特定网址开启whole-response：这点最靠谱，目前也仅仅只有微软的全部应用需要检测edns，steam那些都没有，所以如果可以针对特定网址开启，其他的地址不开启，其实是对浏览影响最小的方案

所以以上3点，希望作者和开发者们可以从功能上参考下

**Comment by pymumu** [comment]
你先看能不能用吧，后面优化后面再说。

**Comment by tobycroft** [comment]
> 

经过测试，不行

**Comment by pymumu** [comment]
完全将speecheck关闭，看看功能正不正常

**Comment by tobycroft** [comment]
##IPV4
###Reserved IP
bogus-nxdomain 0.0.0.0/8
bogus-nxdomain 10.0.0.0/8
bogus-nxdomain 127.0.0.0/8
bogus-nxdomain 100.64.0.0/10
bogus-nxdomain 169.254.0.0/16
bogus-nxdomain 172.16.0.0/12
bogus-nxdomain 192.0.0.0/24
bogus-nxdomain 192.0.2.0/24
bogus-nxdomain 192.31.196.0/24
bogus-nxdomain 192.52.193.0/24
bogus-nxdomain 192.88.99.0/24
bogus-nxdomain 192.168.0.0/16
bogus-nxdomain 192.175.48.0/24
bogus-nxdomain 198.18.0.0/15
bogus-nxdomain 198.51.100.0/24
bogus-nxdomain 203.0.113.0/24
bogus-nxdomain 224.0.0.0/4
bogus-nxdomain 240.0.0.0/4
###Level3
bogus-nxdomain 104.239.213.7
bogus-nxdomain 198.105.254.11
###IP of DoD
bogus-nxdomain 6.0.0.0/7
bogus-nxdomain 11.0.0.0/8
bogus-nxdomain 21.0.0.0/7
bogus-nxdomain 26.0.0.0/8
bogus-nxdomain 28.0.0.0/7
bogus-nxdomain 30.0.0.0/8
bogus-nxdomain 33.0.0.0/8
bogus-nxdomain 55.0.0.0/8
bogus-nxdomain 214.0.0.0/7
###IP of Prudential plc
bogus-nxdomain 48.0.0.0/8
###IP of USPS
bogus-nxdomain 56.0.0.0/8
##IPV6
###Reserved IP
bogus-nxdomain ::/8
bogus-nxdomain ::1/8
bogus-nxdomain FE80::/10
bogus-nxdomain FC00::/7
bogus-nxdomain FF00::/8
bogus-nxdomain FF02::/8
bogus-nxdomain 2001::/23
bogus-nxdomain 2001:2::/48
bogus-nxdomain 2001:3::/32
bogus-nxdomain 2001:4:112::/48
bogus-nxdomain 2001:5::/32
bogus-nxdomain 2001:20::/28
bogus-nxdomain 2001:01F8::/29
bogus-nxdomain 2001:DB8::/32
bogus-nxdomain 2620:4F:8000::/48
bogus-nxdomain 3FFE::/16
bogus-nxdomain 4000::/3
bogus-nxdomain 5F00::/8
bogus-nxdomain 6000::/3
bogus-nxdomain 8000::/3
bogus-nxdomain A000::/3
bogus-nxdomain C000::/3
bogus-nxdomain E000::/4
bogus-nxdomain F000::/5
bogus-nxdomain F800::/6
bogus-nxdomain FC00::/7
bogus-nxdomain FE00::/9
bogus-nxdomain FF00::/8
bogus-nxdomain 2002::/16
bogus-nxdomain 2001:DB8::/32
bogus-nxdomain FEC0::/10
bogus-nxdomain ::FFFF:0:0/96
bogus-nxdomain 64:FF9B::/96
bogus-nxdomain 64:FF9B:1::/48
bogus-nxdomain 0100::/8
bogus-nxdomain 100::/64
bogus-nxdomain 0200::/7
bogus-nxdomain 0400::/6
bogus-nxdomain 0800::/5
bogus-nxdomain 1000::/4

##IPV4
blacklist-ip 10.10.10.10
blacklist-ip 101.226.10.0/24
blacklist-ip 103.205.240.0/24
blacklist-ip 104.239.213.0/24
blacklist-ip 108.160.0.0/16
blacklist-ip 110.249.209.0/24
blacklist-ip 1.1.1.1
blacklist-ip 111.11.208.0/24
blacklist-ip 111.175.220.0/23
blacklist-ip 112.132.230.0/24
blacklist-ip 114.112.163.0/24
blacklist-ip 122.218.101.0/24
blacklist-ip 123.125.81.0/24
blacklist-ip 123.126.249.0/24
blacklist-ip 123.129.254.0/24
blacklist-ip 1.2.3.4
blacklist-ip 123.50.49.0/24
blacklist-ip 124.14.8.0/24
blacklist-ip 124.232.132.0/24
blacklist-ip 125.211.213.0/24
blacklist-ip 125.230.148.0/24
blacklist-ip 125.76.239.0/24
blacklist-ip 128.121.126.0/24
blacklist-ip 12.87.133.0/24
blacklist-ip 159.106.121.0/24
blacklist-ip 159.24.3.0/24
blacklist-ip 16.63.155.0/24
blacklist-ip 169.132.13.0/24
blacklist-ip 173.201.216.0/24
blacklist-ip 180.153.103.0/24
blacklist-ip 180.168.41.0/24
blacklist-ip 183.207.232.0/24
blacklist-ip 185.85.13.0/24
blacklist-ip 188.5.4.0/24
blacklist-ip 189.163.17.0/24
blacklist-ip 197.4.4.0/24
blacklist-ip 198.105.254.0/24
blacklist-ip 20.139.56.0
blacklist-ip 20.20.20.20
blacklist-ip 202.100.220.0/24
blacklist-ip 202.100.68.0/24
blacklist-ip 202.102.110.0/24
blacklist-ip 202.106.1.0/24
blacklist-ip 202.106.199.0/24
blacklist-ip 202.181.7.0/24
blacklist-ip 202.98.24.0/24
blacklist-ip 202.99.254.0/24
blacklist-ip 203.161.230.0/24
blacklist-ip 203.199.57.0/24
blacklist-ip 203.98.7.0/24
blacklist-ip 204.155.147.0/24
blacklist-ip 207.12.88.0/24
blacklist-ip 208.109.138.0/24
blacklist-ip 208.56.31.0/24
blacklist-ip 208.69.32.0/24
blacklist-ip 208.69.34.0/24
blacklist-ip 209.145.54.0/24
blacklist-ip 209.220.30.0/24
blacklist-ip 209.36.73.0/24
blacklist-ip 209.85.229.0/24
blacklist-ip 210.242.125.0/24
blacklist-ip 211.136.113.0/24
blacklist-ip 211.137.130.0/24
blacklist-ip 211.138.102.0/24
blacklist-ip 211.138.34.0/24
blacklist-ip 211.138.74.0/24
blacklist-ip 211.139.136.0/24
blacklist-ip 2.1.1.2
blacklist-ip 211.5.133.0/24
blacklist-ip 211.8.69.0/24
blacklist-ip 211.94.66.0/24
blacklist-ip 211.98.70.0/23
blacklist-ip 213.169.251.0/24
blacklist-ip 213.186.33.0/24
blacklist-ip 216.139.213.0/24
blacklist-ip 216.221.188.0/24
blacklist-ip 216.234.179.0/24
blacklist-ip 216.239.179.0/16
blacklist-ip 218.241.116.0/24
blacklist-ip 218.28.144.0/24
blacklist-ip 218.30.64.0/24
blacklist-ip 218.68.250.0/24
blacklist-ip 218.93.250.0/24
blacklist-ip 219.146.13.0/24
blacklist-ip 220.165.8.0/24
blacklist-ip 220.250.64.0/24
blacklist-ip 221.179.46.0/24
blacklist-ip 221.192.153.0/24
blacklist-ip 221.204.244.0/24
blacklist-ip 221.8.69.0/24
blacklist-ip 222.221.5.0/24
blacklist-ip 223.82.248.0/24
blacklist-ip 23.89.5.0/24
blacklist-ip 243.185.187.0/24
blacklist-ip 24.51.184.0
blacklist-ip 249.129.46.0/24
blacklist-ip 253.157.14.0/24
blacklist-ip 255.255.255.255
blacklist-ip 28.121.126.0/24
blacklist-ip 28.13.216.0
blacklist-ip 31.13.0.0/16
blacklist-ip 37.61.54.0/24
blacklist-ip 4.193.80.0
blacklist-ip 42.123.125.0/24
blacklist-ip 4.36.66.0/24
blacklist-ip 46.20.126.0/24
blacklist-ip 46.38.24.0/24
blacklist-ip 46.82.174.0/24
blacklist-ip 49.2.123.0/24
blacklist-ip 54.76.135.0/24
blacklist-ip 58.53.211.0/24
blacklist-ip 59.24.3.0/24
blacklist-ip 60.191.124.0/24
blacklist-ip 60.19.29.0/24
blacklist-ip 61.131.208.0/24
blacklist-ip 61.139.8.0/24
blacklist-ip 61.183.1.0/24
blacklist-ip 61.191.206.0/24
blacklist-ip 61.54.28.0/24
blacklist-ip 64.33.88.0/24
blacklist-ip 4.33.99.0/24
blacklist-ip 64.66.163.0/24
blacklist-ip 65.104.202.0/24
blacklist-ip 65.160.219.0/24
blacklist-ip 65.49.2.0/24
blacklist-ip 66.206.11.0/24
blacklist-ip 66.220.0.0/16
blacklist-ip 66.45.252.0/24
blacklist-ip 67.215.65.0/24
blacklist-ip 67.215.77.0/24
blacklist-ip 72.14.205.0/24
blacklist-ip 74.117.182.0/24
blacklist-ip 74.117.57.0/24
blacklist-ip 77.4.7.0/24
blacklist-ip 78.16.49.0/24
blacklist-ip 8.105.84.0/24
blacklist-ip 8.7.198.0/24
blacklist-ip 89.31.55.0/24
blacklist-ip 92.242.144.0/24
blacklist-ip 93.46.8.0/24
blacklist-ip 95.211.189.0/24
blacklist-ip 208.101.0.0/16
blacklist-ip 74.86.0.0/16
blacklist-ip 69.63.0.0/16
blacklist-ip 75.126.0.0/16
blacklist-ip 199.59.0.0/16
blacklist-ip 67.228.0.0/16
blacklist-ip 88.191.0.0/16
blacklist-ip 199.16.0.0/16
blacklist-ip 172.217.24.0/24
blacklist-ip 172.217.161.0/24
blacklist-ip 88.191.249.0/24
blacklist-ip 103.207.229.0/24
blacklist-ip 120.196.0.0/24
blacklist-ip 101.110.118.0/24
blacklist-ip 113.12.83.0/24
blacklist-ip 125.88.131.0/24
blacklist-ip 120.52.72.0/23
blacklist-ip 69.171.0.0/16
blacklist-ip 67.15.0.0/16
blacklist-ip 173.252.0.0/16
blacklist-ip 174.36.0.0/16
blacklist-ip 174.36.0.0/15
blacklist-ip 205.186.152.0/24
blacklist-ip 208.43.0.0/16
blacklist-ip 64.13.0.0/16
blacklist-ip 120.192.83.0/24
blacklist-ip 183.221.242.0/24
blacklist-ip 183.221.250.0/24
blacklist-ip 183.224.40.0/24
blacklist-ip 152.0.0.0/8
blacklist-ip 74.0.0.0/8
blacklist-ip 103.0.0.0/8
blacklist-ip 87.0.0.0/8
balcklist-ip 13.0.0.0/8
balcklist-ip 52.0.0.0/8
balcklist-ip 203.208.50.164/16
##IPV6
blacklist-ip ::9000:0:0:0/72
blacklist-ip 101::1234
blacklist-ip 10::2222
blacklist-ip 2001:1::1
blacklist-ip 2001:1::2
blacklist-ip 2001::212
blacklist-ip 2001:DA8:112::21AE
blacklist-ip 200:2:253D:369E::
blacklist-ip 200:2:2E52:AE44::
blacklist-ip 200:2:3B18:3AD::
blacklist-ip 200:2:4E10:310F::
blacklist-ip 200:2:5D2E:859::
blacklist-ip 200:2:807:C62D::
blacklist-ip 200:2:9F6A:794B::
blacklist-ip 200:2:CB62:741::
blacklist-ip 200:2:F3B9:BB27::
blacklist-ip 2003:FF:1:2:3:4:5FFF:0/112
blacklist-ip 21:2::2
blacklist-ip 2123::3E12
blacklist-ip 50A7:26E::64:CEEF:0:0

好像是这里的问题，blacklist-ip.conf这个不加载后，居然恢复正常了？？why？

这是我的设置，也就是即使不是黑名单，依然会有114的地址能对应上，也就是一定会有IP返回的，想不通为啥会这样
server 114.114.114.114
server 223.5.5.5 -blacklist-ip 
server 119.29.29.29 -blacklist-ip 
server-tls 10.0.0.240:1154
server 218.85.157.99 -blacklist-ip -group china
server 2408:8888::8 -blacklist-ip -group china
server 223.5.5.5 -blacklist-ip -group china
server 119.29.29.29 -blacklist-ip -group china
server-tls 10.0.0.240:1154 -group ssr

首先我怀疑的是外网ip的问题，因为ip被解析到104的一个美国地址上面，后来我只开了114，关闭speedcheck那些，都关了，唯独开启nss列表（里面的设置与微软的cdn无关），和blacklist-ip，这些黑名单好像是smartdns很早以前自带的，我一直沿用下来，因为当时有些地址会被转到facebook的ip上面去

后来……有一天，微软的模拟飞行炸了，后来……xbox中所有的单机联网游戏也炸了，我没找到原因

后来经过观察我发现是edns问题，关闭speed测试后，也无法解决。

我怀疑可能是我dns服务器的问题，于是我直接用dnsmasq转发114，居然就成功了

今天我测试还是不行，突然发现114他会直接使用ipv6来连接微软服务器而不是ipv4，我就在想是不是微软有些地址就是ipv6的，于是forceaaaa关闭，speedcheck关闭，dualstack关闭，这样只要是ipv6，均会返回ipv6，于是……还是不行

后来终于有wholeip模式了，测试后返回很漂亮，但是依然没用，我就在想是不是speed那些问题，于是在经历了一下午的测试后（主要是更换server的dns地址，比如只用国外的dns2sock，或者只用114），均不能解决问题

最后我索性摆烂了，我把所有的设置全部恢复，包括取消了nss.conf和blackipconf，最后居然奇迹般的恢复了

然后我又把speedcheck那些全部再次开起来，居然依旧可以？于是我关闭了wholeip……

于是……我就沉默了，这么久了，居然……是blacklistip捣的鬼，但是我不理解啊，blacklistip这个里面的ip触发后只是这个dns的优先级被排除掉了，假设没有开启bip的dns地址，应该依然拥有返回dns地址的优先级啊，不可能说这个ip段完全没有dns服务器负责回传ip数据才对

我不了解这个逻辑，但是……确实是感觉绕了一个大弯

最后……

关于smartdns，我想是不是应该转一下战场了，我在今天的测试中发现了一些新的产品需求：

例如我关闭了双栈优选，那么这个时候ipv6拥有顶级优先级，但是我发现现在的cdn，例如微软的会提供多个ipv6的地址，这些地址的速度差距特别大，有些ping上230多还会掉包，有些才60多而且稳定，但是smartdns在这块的返回状态不是很固定，有的时候是180多的那个有些时候是60多的（正确的）那个，有些时候是最慢的230多的那个。

所以能不能测速功能针对ipv6来开放呢？例如在ipv6优先的情况下（不考虑v4速度），对ipv6来进行测速，返回最快的服务器地址，我感觉这样就好很多了，另外一些特殊地址的测速是否可以加入到配置文件里面，例如有些是走80的有些是443的，有些可能我只想ping一下（因为他可能是udp数据端口）

所以在功能方面能不能考量下这个？

**Comment by PikuZheng** [comment]
blacklist-ip会导致这样一个问题：比如查询dns.alidns.com返回了223.5.5.5**和**2400:3200::1，当223.5.5.5**或**2400:3200::1存在于 blacklist-ip时，smartdns会丢弃整个查询结果（而不是结果中匹配的单一ip）

**Comment by tobycroft** [comment]
但是如果某个dns服务器没有开启 -blacklist-ip功能，那这个dns服务器应该是clean的吧，就是即使其他的blacklist-ip的服务器的返回都被deny掉，这个没有开黑名单匹配的dns服务器因该还能回传数据吧？

还是smartdns是在出口匹配blacklist-ip的？就算有dns没开blacklistip但是最终输出的dns与blacklistip相撞，就会整个丢弃？

> blacklist-ip会导致这样一个问题：比如查询dns.alidns.com返回了223.5.5.5**和**2400:3200::1，当223.5.5.5**或**2400:3200::1存在于 blacklist-ip时，smartdns会丢弃整个查询结果（而不是结果中匹配的单一ip）

**Comment by PikuZheng** [comment]
有数据，但是运营商劫持（？）

**Comment by pymumu** [comment]
测速的这个是瞬时速度，国外的IP，有时候会遭遇到丢包，如果在测速的时候，被丢包了，那就会用了另外一个速度慢的。

最近优化了一个版本，之前返回的是一个速度最快的IP，优化后，返回一组最佳IP。避免某个IP地址访问丢包的异常情况。也能保证下载类软件的并发速度。

代码提交到all-best-ip分支了，两位可以取用。@PikuZheng @tobycroft 
配置上，基本上不用额外配置，考虑打开serve-expired。

测试的话，可以用www.baidu.com测试，第一次回返回1个IP，TTL为5s，然后再查询的话，应该会返回多个IP地址。

**Comment by PikuZheng** [comment]
> 

这个分支包含response-mode吗

**Comment by pymumu** [comment]
没有，那个功能现在还没想好怎么处理比较好。

**Comment by PikuZheng** [comment]
> 没有，那个功能现在还没想好怎么处理比较好。 现在感觉后面这种方式，多个优选IP这种，可能是最佳方案。
> 
> whole-response有个问题就是，比如qq.com域名，返回的IP地址，包含了国内外的，3个地址，有快有慢，whole-response这种情况下就不太好了
> 
> 多优选IP方案的话，第一次是一个IP，后面再查询，就是多个最佳IP地址了。效果上更好。
> 
> 可以对比下方案看看，给一下处理建议。

我不是很在意测速，我只是希望上游的查询结果能够“原样”返回，避免附加数据丢失

**Comment by tobycroft** [comment]
> 没有，那个功能现在还没想好怎么处理比较好。 现在感觉后面这种方式，多个优选IP这种，可能是最佳方案。
> 
> whole-response有个问题就是，比如qq.com域名，返回的IP地址，包含了国内外的，3个地址，有快有慢，whole-response这种情况下就不太好了
> 
> 多优选IP方案的话，第一次是一个IP，后面再查询，就是多个最佳IP地址了。效果上更好。
> 
> 可以对比下方案看看，给一下处理建议。

另外我发现一个问题：
1.例如使用科学的时候，ping不可用，但是ipv6可能会返回ping，ping会出现不可靠，测速如果开了80ping，443ping或者ping，很多时候会导致外网地址的ipv6的优先级被提上来（因为ipv6有些没被x），所以如果可以对分组，例如ssr分组下所有的测速方式均为80，443，国内分组下默认ping

**Comment by PikuZheng** [comment]
所以最终结论是和edns信息无关，但和双栈ip优选有关？@tobycroft

**Comment by tobycroft** [comment]
> 所以最终结论是和edns信息无关，但和双栈ip优选有关？@tobycroft

最终的结论是与blacklist-ip有关，目前游戏已经能进去了，服务器才80多ms，看上去很快，但是加载的速度极慢（因为他需要用网络），用114原生dns会好很多，这就需要我调查下原因了
