### ISSUE TITLE
恳请支持配置热加载

### ISSUE THREAD

**Issue by enihcam** [pymumu/smartdns#875]
**需求应用场景**
在阻止广告的上下文中，域名变动相对略显频繁（至少一天一次），希望能在不重启smartdns服务的情况下生效。

**建议的方案**
使用`inotify()`监听配置，如果相关选项支持不重启生效，则直接应用此选项配置。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息

**Comment by jkle112** [comment]
三个方案供选择：
第一，自己编译或下载adbyby，这个到处都有。
第二，自己添加anti-ad-smartdns.conf，giihub.com有现成的，定期下载更新就可以了，如果再找更大的包，占用内存大，会导致smartdns运行效率低下。
第三，我自己用的，编译ikoolproxy，广告过滤功能强大，它是最新且支持网页广告过滤的。

**Comment by enihcam** [comment]
> 

你说的这三种我当然知道，但不是最轻方案。这个feature request的原因就是为了减少依赖。关于第二个建议，没看出来怎么解决了热加载问题。

**Comment by jkle112** [comment]
如果我没有猜错，你之所以要最轻方案是由于路由器硬件限制，对吧？
 /etc/hosts，我也用过，不过你如果要最轻，那么可以直接自己修改，不用官方改，将配置的所有服务器全部改为加密的，因为加密的就已经起到了一层广告过滤，如果还有内存可以升级，再添加anti-ad-smartdns.conf，二级防护。
如果内存够，用smartdns+ikoolproxy，可以自己升级的。

**Comment by enihcam** [comment]
> 

咱们说的不是一个问题。

**Comment by amitbha** [comment]
除了广告，还有github 访问难题啊
不考虑fq的话，就是改hosts简便了，支持此FR

**Comment by sklohk** [comment]
/etc/hosts 里面的配置是可以在 /etc/smartdns/address. conf里配置，至于smartdns重启生效，我的实践经验是简单，作为service，经常重启是正常的，每天重启一次也是正常的，设置cron，想怎么重启都简单

**Comment by sklohk** [comment]
但，如果smartdns 的运行模式是redirect的话，经常重启可能需要做一定的工作，redirect模式重启时，smartdns启动程序没有删除之前的iptables nat 表，PREROUTING链里的rule，每次启动都会新添加，不喜欢太多重复rule，就得在重启时先删除多余的rule

**Comment by enihcam** [comment]
> /etc/hosts 里面的配置是可以在 /etc/smartdns/address. conf里配置，至于smartdns重启生效，我的实践经验是简单，作为service，经常重启是正常的，每天重启一次也是正常的，设置cron，想怎么重启都简单

考虑下容器场景，重启smartdns意味着重新分配容器节点。在节点资源紧张的情况下，分配失败意味着整个集群收到牵连。我只是随便举个例子，单就这一个case当然有workaround，即“加法”提议。而本FR建议设计上支持热加载，从架构上避免重启，即“减法”提议。

**Comment by pymumu** [comment]
场景是啥，smartdns重启应该是很快的。也是最有效的。

**Comment by enihcam** [comment]
> 场景是啥，smartdns重启应该是很快的。也是最有效的。

试了几天，好像没什么问题。close issue.

**Comment by Vastxiao** [comment]
已测试，确实支持热重载
sudo kill -HUP $(pidof smartdns)
