### ISSUE TITLE
静态编译

### ISSUE THREAD

**Issue by g3ne** [pymumu/smartdns#88]
1、建议编译为静态程序：
很多系统没有 libssl.so.1.0.0 和 libcrypto.so.1.0.0，
官方仓库只有新版本如 libcrypto.so.1.1，新版本还没有 OPENSSL_add_all_algorithms_noconf 等，
导致运行前必须手动patch rpath和ld很麻烦，故建议默认编译为静态程序，没有依赖就没有伤害。

2、开源建议：
产品用户群很小众，目前版本的功能重现也只需几天，会员费/二开定制都不太可能有高盈利，
何不趁着还有先发优势开源让大伙一起完善呢，何况服务端闭源程序大多薄命。

**Comment by pymumu** [comment]
静态编译会导致进程增大到2M，体积增大太多。
目前发布的版本都是和对应的固件配套的。如果有不配套的情况，可以反馈。所以，目前暂时不考虑静态编译。

关于开源：
软件本身属于个人爱好，自己也在使用，从开始就没有考虑过从这个软件上获取利润。
所以没有开源的目的并不是盈利的原因。

没开源只是为了避免某些人利用软件做损害我个人利益的事情。
后面时机成熟会开源的。
