### ISSUE TITLE
电信移动双线接入如何设置呢？

### ISSUE THREAD

**Issue by goukey** [pymumu/smartdns#882]
默认的设置是返回一个最快的dns响应，这样一定会造成这样的结果：
响应最快的是电信ip，而访问的时候却用移动线路去访问。
请问如果设置才能规避这样的问题？上游dns里把电信移动的本地dns都填上的话会更加剧这种冲突，请问作者有什么解决方案吗？
多谢。

**Comment by PikuZheng** [comment]
开启测速（但不是最好的方法。

理论上从电信出口向上游DNS发出的请求，上游不应返回移动的结果。所以您问题当中的 电信IP 却使用移动线路访问 是怎么造成的呢？建议先从负载均衡角度考虑一下。

**Comment by goukey** [comment]
> 开启测速（但不是最好的方法。

默认不就是开启测速的？

> 理论上从电信出口向上游DNS发出的请求，上游不应返回移动的结果。所以您问题当中的 电信IP 却使用移动线路访问 是怎么造成的呢？建议先从负载均衡角度考虑一下。

因为缓存啊，smartdns会缓存上一次查询结果。

**Comment by goukey** [comment]
一个大网站的cdn每次查询返回的不一定是同一个线路的ip，所以可能会出现这种问题

**Comment by PikuZheng** [comment]
比如要访问163.com，smartdns（从缓存中）返回了一个59.46.x.x（电信）的结果。为什么会通过移动的线路去访问。我认为这是负载均衡的调度问题。

**Comment by goukey** [comment]
也有道理，在爱快里面设一下线路分流看看

**Comment by PikuZheng** [comment]
比如要访问163.com。smartdns通过电信的线路向上游发起查询。如果得到了一个移动的结果。那原因应该是这个移动节点（物理）距离比电信的节点更近。那么实际访问这个移动的IP，应该（通过负载均衡）走移动的线路。
一般情况下，移动的节点会随机分给联通和电信。但联通发起的查询不会获得电信的结果，电信的查询也不会获得联通的结果。
DNS查询数据走的线路，和实际访问网站走的线路不相关。

**Comment by goukey** [comment]
关键在于，第一次查询的时候走什么线路是如何指定的呢？

**Comment by PikuZheng** [comment]
> 关键在于，第一次查询的时候走什么线路是如何指定的呢？

这个由路由器的负载均衡策略决定

**Comment by bubbleatgit** [comment]
> 

通常情况下，使用 cdn 的域名，在电信用户解析时，基本不会返回其他运营商的 ip （除非是一些野鸡DNS运营商）。

**Comment by bubbleatgit** [comment]
> 比如要访问163.com。smartdns通过电信的线路向上游发起查询。如果得到了一个移动的结果。那原因应该是这个移动节点（物理）距离比电信的节点更近。那么实际访问这个移动的IP，应该（通过负载均衡）走移动的线路。 一般情况下，移动的节点会随机分给联通和电信。但联通发起的查询不会获得电信的结果，电信的查询也不会获得联通的结果。 DNS查询数据走的线路，和实际访问网站走的线路不相关。

通常情况下，使用 cdn 的域名，在电信用户解析时，基本不会返回其他运营商的 ip （除非是一些野鸡DNS运营商）。
