### ISSUE TITLE
Question about KillMode=process in systemd unit 关于systemd unit文件中KillMode=process的疑问

### ISSUE THREAD

**Issue by reallyimeric** [pymumu/smartdns#885]
I saw `KillMode=process` setting from https://github.com/pymumu/smartdns/blob/d7d7ef48cd71f9c13358859d2c6137eae7462415/systemd/smartdns.service.in#L12
I wonder why we need this?

我看到这里设置了 `KillMode=process` 
https://github.com/pymumu/smartdns/blob/d7d7ef48cd71f9c13358859d2c6137eae7462415/systemd/smartdns.service.in#L12 
请问为什么需要这样指定？

**Comment by PHCSJC** [comment]
我也提一个小小问题吧，如果用下面的命令重启会提示进程已经存在
killall smartdns ; smartdns

在中间加个sleep就可以了
killall smartdns ; sleep 1; smartdns

arm64和amd64都有这个问题

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
