### ISSUE TITLE
消除address/nameserver项中多余域名的问题

### ISSUE THREAD

**Issue by enihcam** [pymumu/smartdns#886]
**需求应用场景**
假设`address`选项涉及`a.b.c`和`b.c`两个域名指向`0.0.0.0`或`#`，在smartdns进程里是1个entry还是2个entries？

我在考虑有没有必要写域名合并的脚本以减少内存使用，例如：

输入
```
address /a.b.c/#
address /b.c/#

nameserver /w.x.y.z/direct
nameserver /y.z/direct
```

输出
```
address /b.c/#
nameserver /y.z/direct
```

如果smartdns能内置类似功能更佳：
https://github.com/felixonmars/dnsmasq-china-list/blob/master/find_redundant.py

还请作者建议，感谢。 @pymumu

**Comment by PikuZheng** [comment]
从右向左逐字符匹配。也就是说 /b.c/包含/a.b.c/。但是有顺序问题，按照上面的写法，如果匹配到/a.b.c/便不会继续向下匹配/b.c/，适用于匹配后需要进行不同处理的环境

**Comment by pymumu** [comment]
a.b.c，b.c是算作两条规则的。这个是不能合并的
比如a.b.c是广告，要屏蔽，但b.c不是，不能屏蔽，但需要设置nameserver。
这种情况下，就需要两条同时生效。

另外，a.b.c和b.c的内存占用，不是成倍的。算法用的是树结构，多占用的内存，也就是多出来的a字符和一些控制结构，占用多不了多少内存的。

**Comment by enihcam** [comment]
了解。
