### ISSUE TITLE
有没有一个类似 adguard bootstrap dns 的参数？

### ISSUE THREAD

**Issue by ihotte** [pymumu/smartdns#887]
现在 OpenWrt 上使用 smartdns 的环境多为 DNS 套娃。
DoH、DoT 上游包含域名的情况下可能存在无法正常解析域名的情况。
不知能否添加一个 bootstrap dns 参数以供 smartdns 初始化时解析 DoH、DoT 域名用？

**Comment by PikuZheng** [comment]
#567 #677 
有两个方法可以处理这个问题。一是对于IP固定的（比如阿里、腾讯），可以直接使用ip并声明域名。例 `server-tls 119.29.29.29  -tls-host-verify dot.pub`。二是对这些域名指定一个单独的组并为这个组赋予一个udp上游服务

**Comment by ihotte** [comment]
曲线救国临时救急也可以，但是还是有一个参数比较合理，毕竟将一个上游地址拆分成两个参数极大增加了用户出错的概率。

**Comment by PikuZheng** [comment]
把这个对应关系写入系统hosts吧

**Comment by lalasou** [comment]
@pymumu 还是加个参数比较方便些

**Comment by pymumu** [comment]
一般情况域名地址是会自动使用Ip的dns服务器解析的，不需要什么bootstrap dns

**Comment by ihotte** [comment]
> 一般情况域名地址是会自动使用Ip的dns服务器解析的，不需要什么bootstrap dns

然而我国内只保留了域名的 DoT DoH ，没 IP

**Comment by PikuZheng** [comment]
> 一般情况域名地址是会自动使用Ip的dns服务器解析的，不需要什么bootstrap dns

我观测到的是 域名地址走系统默认dns  然后系统默认dns的指向smartdns 就会导致循环

> 然而我国内只保留了域名的 DoT DoH ，没 IP

支持 我国内也是用阿里和腾讯的dot 由于运营商劫持严重

**Comment by lalasou** [comment]
![image](https://user-images.githubusercontent.com/7440313/155839998-28ca631e-25c5-421f-9752-054b36aa421c.png)



这边移动宽带 udp53全劫持随便编个ip都能当dns
