### ISSUE TITLE
ECS现在还是不支持吗? readme里写了支持ecs

### ISSUE THREAD

**Issue by lix5027** [pymumu/smartdns#888]
在介绍也里写了ecs支持如下:

支持最新的TLS, HTTPS协议，提供安全的DNS查询能力。
ECS支持，是查询结果更佳准确。
IP黑名单，忽略IP机制，使域名查询更佳准确。
域名预查询，访问常用网站更加快速。
域名TTL可指定，使访问更快速。
高速缓存机制，使访问更快速。

**Comment by PikuZheng** [comment]
参数是有了 实际不工作。

**Comment by pymumu** [comment]
ECS一直没想到本地服务的使用的场景。ECS是用于远端两个DNS服务间使用，并不是用在本地

smartdns是本地服务，没有ECS的诉求。唯一的场景是，你在A地，想要B地解析后的IP，那才需要ECS。

@sammimk830 你说的问题，应该是你配置的DNS不支持ECS

**Comment by sammimk830** [comment]
我用的DNS就是google的8.8.8.8吖，他支持ECS的，我出現的問題是，在購買的VPS是香港的，但因為IP網段有部份被用到美國去，所以被誤認為是美國的，所以我需要用到香港的IP加進去設置EDNS，這樣才能得到最近的CDN 的IP地址。

**Comment by pymumu** [comment]
"但因為IP網段有部份被用到美國去"，这个什么概念？通过代理转发？IP上IANA分配的，位置信息一般都不会出错。

**Comment by sammimk830** [comment]
應該這麼說吧，供應商是在US購買的IP，那他在IANA上的地區也是US的，但他自己可以分配到全球不同的地區來使用
以下這圖就是我所使用的VPS網段的IANA上的資料，所以每當我向8.8.8.8查IP時，他會誤以為我是美國的，所以都是去了不同的地方，另一張圖是IANA上是香港買的，就沒有這個問題了。
地址是: mirrors.aliyun.com
![image](https://user-images.githubusercontent.com/34807325/166086161-a9d6ceed-442c-42bb-9720-186bac8752e6.png)
![image](https://user-images.githubusercontent.com/34807325/166086261-0a89f3b9-a5c6-4592-9436-d2bfbdf5940e.png)

沒有修改EDNS的traceroute
![image](https://user-images.githubusercontent.com/34807325/166086275-e61edee4-54b7-47aa-9aee-61c2a61e2701.png)

修改過EDNS為我另一個VPS用的是HGC的IP後的traceroute
![image](https://user-images.githubusercontent.com/34807325/166086299-f1ba34e1-4435-4cd6-ba3a-33da725987af.png)

**Comment by PikuZheng** [comment]
> "但因為IP網段有部份被用到美國去"，这个什么概念？通过代理转发？IP上IANA分配的，位置信息一般都不会出错。

很多vps用的广播地址，识别到的ip位置与实际物理位置不同。这个往往需要向google报告，然后经过几个月甚至几年才能纠正过来

**Comment by sammimk830** [comment]
> > "但因為IP網段有部份被用到美國去"，这个什么概念？通过代理转发？IP上IANA分配的，位置信息一般都不会出错。
> 
> 很多vps用的广播地址，识别到的ip位置与实际物理位置不同。这个往往需要向google报告，然后经过几个月甚至几年才能纠正过来

對的，所以才希望能有這個功能就可以靠自己了，不然都不知道要等到什麼時候才能正確回來，然後你也沒有供應商哪一個網段用到哪個地方去了，所以也很難搞。

**Comment by PikuZheng** [comment]
> 對的，所以才希望能有這個功能就可以靠自己了，不然都不知道要等到什麼時候才能正確回來，然後你也沒有供應商哪一個網段用到哪個地方去了，所以也很難搞。

我是在vps上打dot服务作为smartdns的上游，总体来说比从本地经链路直接到dns服务器好些

**Comment by pymumu** [comment]
push代码到ecs分支，可做测试验证。最终版本可能会与测试版本不一致。

# edns client subnet
# edns-client-subnet [ip/subnet]
# edns-client-subnet 192.168.1.1/24
# edns-client-subnet [8::8]/56

**Comment by zsy5172** [comment]
现在ecs设置是全局的，似乎有问题。
应该是能为每个server指定一个ecs的值才对。

**Comment by Xymmh** [comment]
最新的pre-release是已经支持了吗？
为什么我添加edns client subnet参数后没有效果呜呜

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
