### ISSUE TITLE
ipset 开启ttl作为timeout功能无法添加

### ISSUE THREAD

**Issue by xiang7chu** [pymumu/smartdns#889]
**问题现象**  
简要描述问题出现的现象
ipset 开启ttl作为timeout功能无法添加

**信息收集**  
``` c
        if (timeout > 0 && _ipset_support_timeout(ipsetname) == 0) {
                timeout = htonl(timeout);
                _ipset_add_attr(netlink_head, IPSET_ATTR_TIMEOUT | NLA_F_NET_BYTEORDER, sizeof(timeout), &timeout);
        }
```

这段代码在5.4内核上会出现如下dmesg错误信息
`
[1017333.247586] netlink: 'smartdns': attribute type 6 has an invalid length.
`
sizeof(timeout)应改为4，因为timeout在ipset_operate函数定义为unsigned long

**Comment by pymumu** [comment]
最新代码不是这个了，应该没有问题了，你看看吧。
