### ISSUE TITLE
写了一个用于老毛子固件的替换dnsmasq的脚本

### ISSUE THREAD

**Issue by rufengsuixing** [pymumu/smartdns#89]
#!/bin/sh
#smartdns 全面替换dnsmasq功能，放到/etc/storage/script/dm2smd.sh下运行
#自行加入server=127.0.0.1#port 在/etc/storage/dnsmasq/dnsmasq.conf，或者修改本脚本加入
#最好是替换chinadns脚本里的的启动命令，这样也有watchdog，也不用手动修改端口
[ -s /etc/storage/bin/restart_dhcpd ] || ln -s /etc/storage/script/dm2smd.sh /etc/storage/bin/restart_dhcpd
sed -i '/address=/d' $file.smd
sed -i '/#programaddconfig/,$d' /opt/etc/smartdns/smartdns.conf 
echo "#programaddconfig" >> /opt/etc/smartdns/smartdns.conf 

sed -i 's/^conf-dir=/\#conf-dir=/' /etc/storage/dnsmasq/dnsmasq.conf
grep '#conf-dir' /etc/storage/dnsmasq/dnsmasq.conf | awk -F = '{print $2}' > /tmp/sddc
while read line
do
    for file in `ls -d $line/*[!.][!s][!m][!d]`
    do
        cp -f $file $file.smd
        sed -i '/address=/d' $file.smd
        sed -i '/server=/d' $file.smd
        sed -i 's/ipset=/ipset /' $file.smd
        echo conf-file $file.smd >> /opt/etc/smartdns/smartdns.conf
    done
done < /tmp/sddc

sed -i 's/^conf-file=/\#conf-file=/' /etc/storage/dnsmasq/dnsmasq.conf
grep '#conf-file=' /etc/storage/dnsmasq/dnsmasq.conf | awk -F = '{print $2}' > /tmp/sddc
while read line
do
    cp -f $line $line.smd
    sed -i '/address=/d' $line.smd
    sed -i '/server=/d' $line.smd
    sed -i 's/ipset=/ipset /' $line.smd
    echo conf-file $line.smd >> /opt/etc/smartdns/smartdns.conf
done < /tmp/sddc

sed -i '/min-cache-ttl/d' /etc/storage/dnsmasq/dnsmasq.conf

if [ -s /tmp/dmsize ] ; then
    oldsize=`cat /tmp/dmsize`
else
    oldsize=0
fi
nowsize=`wc -c /etc/storage/dnsmasq/dnsmasq.conf | awk '{print $1}'`
echo $nowsize > /tmp/dmsize
killall smartdns
/opt/usr/sbin/smartdns -c /opt/etc/smartdns/smartdns.conf
if [ "$oldsize" -ne "$nowsize" ] ; then
/sbin/restart_dhcpd
fi

**Comment by pymumu** [comment]
补充一下：
optware的文件，支持替换dnsmasq作为主DNS的。只要修改一个配置：
把下面文件的
/opt/etc/smartdns/smartdns-opt.conf
```
# workmode 
# 0: run as port only
# 1: redirect port
# 2: replace 
SMARTDNS_WORKMODE="1"
```
修改为2.

**Comment by rufengsuixing** [comment]
replace是指直接读取dnsmasq的配置文件么，我这里有很多ipset规则需要加载
如果是的话，我觉得是个挺好的特性，也不用我辛辛苦苦的改兼容了
如果只是单纯iptables redirect 53 的话，我觉得没啥用

**Comment by Avantyjw** [comment]
这个脚本怎么用啊

**Comment by Masstone** [comment]
> 补充一下：
> optware的文件，支持替换dnsmasq作为主DNS的。只要修改一个配置：
> 把下面文件的
> /opt/etc/smartdns/smartdns-opt.conf
> 
> ```
> # workmode 
> # 0: run as port only
> # 1: redirect port
> # 2: replace 
> SMARTDNS_WORKMODE="1"
> ```
> 
> 修改为2.

如果用2的模式，smartdns的dns监听端口还能修改么

**Comment by pymumu** [comment]
模式2，端口只能时53

**Comment by Masstone** [comment]
那如果模式设为0 dns端口设为127.0.0.1:6053
在dnsmasq的server里面添加127.0.0.1#6053
会出现回环么？

**Comment by pymumu** [comment]
你目的是什么？

模式0，表示，smartdns单独启动，不做重定向，也不改dnsmasq，主要是配合某些软件使用。
模式1，表示，重定向53端口的请求到smartdns。用来替换默认的dns服务。
模式2，和模式1目的一样，但区别是smartdns绑定53端口，关闭dnsmasq的DNS服务，也是做主DNS服务。

所以，其实就两种功能，一种是独立运行，一种是做主DNS服务。
模式1，2只是不同的实现方式，推荐使用是模式2。

**Comment by Masstone** [comment]
我把客户机53请求重定向给了clash dns
clash dns指向了smartdns的端口6053
clash的节点域名还是要通过本机dns解析，
我保留了dnsmasq 监听53，Smartdns用的模式0，也是担心smartdns会当掉，因为我的固件是padavan，现在我想让smartdns 作为dnsmasq的上游，是不是在dnsmasq的server列表里添加127.0.0.1#6053就可以了

还是说直接用模式2就是这个效果

**Comment by Masstone** [comment]
另一个问题是 关闭dnsmasq的情况下，如果smartdns的server 是个域名，那会出现回环么，这个域名是谁来解析呢

**Comment by pymumu** [comment]
你的场景，dnsmasq基本没用，smartdns可以替换dnsmasq。
server是域名的场景，有两种办法。
1. smartdns有延迟解析机制，只要保证smartdns的server配置，不全是域名就可以。
2. 配置路由的/etc/resov.conf，指定DNS IP。

**Comment by Masstone** [comment]
所以用模式2替换掉dnsmasq？

那smartdns还会经过resov.conf么

**Comment by pymumu** [comment]
只有server没有配置IP地址的上游时，才会使用resolv.conf解析。

所以，你就配置至少一个带IP地址的server就好了

**Comment by Masstone** [comment]
> 只有server没有配置IP地址的上游时，才会使用resolv.conf解析。
> 
> 所以，你就配置至少一个带IP地址的server就好了

好的，谢谢大佬解答。另外，有沟通群啥的么

**Comment by dunmengjun** [comment]
老毛子直接把dnsmasq的端口改为0就好了，就是把port=0这个配置加进去，参考[wiki](https://wiki.archlinux.org/title/Dnsmasq_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E5%AE%89%E8%A3%85). 本质上来说dnsmasq一个东西干了两个服务，一个是dhcp服务，一个是dns服务，port=0相当于禁用了dns服务，只剩下dhcp服务。这样改之后，smartdns直接就可以以53端口启动，完成替代了，根本不用做什么上游服务器。
此方法在hanwckf老毛子上测试成功，爽的飞起。 @pymumu @Masstone @rufengsuixing

**Comment by lhuanyun** [comment]
> 老毛子直接把dnsmasq的端口改为0就好了，就是把port=0这个配置加进去，参考[wiki](https://wiki.archlinux.org/title/Dnsmasq_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E5%AE%89%E8%A3%85). 本质上来说dnsmasq一个东西干了两个服务，一个是dhcp服务，一个是dns服务，port=0相当于禁用了dns服务，只剩下dhcp服务。这样改之后，smartdns直接就可以以53端口启动，完成替代了，根本不用做什么上游服务器。
> 此方法在hanwckf老毛子上测试成功，爽的飞起。 @pymumu @Masstone @rufengsuixing

老哥，没有编译到固件里头，没有启用entware环境，怎么使用smartdns呢。有启动文件和配置，用命令来启动smartdns的相关文件吗。感谢

**Comment by dunmengjun** [comment]
> > 老毛子直接把dnsmasq的端口改为0就好了，就是把port=0这个配置加进去，参考[wiki](https://wiki.archlinux.org/title/Dnsmasq_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E5%AE%89%E8%A3%85). 本质上来说dnsmasq一个东西干了两个服务，一个是dhcp服务，一个是dns服务，port=0相当于禁用了dns服务，只剩下dhcp服务。这样改之后，smartdns直接就可以以53端口启动，完成替代了，根本不用做什么上游服务器。
> > 此方法在hanwckf老毛子上测试成功，爽的飞起。 @pymumu @Masstone @rufengsuixing
> 
> 老哥，没有编译到固件里头，没有启用entware环境，怎么使用smartdns呢。有启动文件和配置，用命令来启动smartdns的相关文件吗。感谢

我这样做了之后，很久没关注我的路由器了😂，我应该是用的启动文件和配置，自己上传到路由器，然后用命令启动的，目前来说运行是良好的
