### ISSUE TITLE
第二dns服务器访问部分网站会解析到IPv6

### ISSUE THREAD

**Issue by bilibilimrlei** [pymumu/smartdns#890]
**问题现象**  
简要描述问题出现的现象
第二dns服务器访问部分网站会解析到IPv6，第二dns服务器已经开启停止IPv6地址解析
**运行环境**
1. 固件型号  
OpenWrt R21.11.11 / LuCI Master (git-21.320.49600-21168d4)
2. 运营商  
中国电信
**重现步骤**

![QQ截图20220227193903](https://user-images.githubusercontent.com/56494512/155880894-a5a19d9a-81f4-4c58-8db7-50590719570b.png)
![QQ截图20220227193819](https://user-images.githubusercontent.com/56494512/155880898-327d1c64-02d5-4104-ae68-4c841597f134.png)

1. 上游DNS配置。  
![QQ截图20220227193121](https://user-images.githubusercontent.com/56494512/155880809-2435aaee-c698-4351-a5ad-70e7950e37e3.png)

2. 访问的域名。  
www.netflix.com
yiyo.io
**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
[smartdns.log](https://github.com/pymumu/smartdns/files/8148574/smartdns.log)

2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
从日志上看。您的第二DNS服务器压根就没启动

**Comment by bilibilimrlei** [comment]
> 从上日志看你的DNS服务器压根启动的第二个。

但我确实有启动，也让他默认走第二个DNS服务器了
![QQ截图20220227212541](https://user-images.githubusercontent.com/56494512/155884310-46737060-43bd-4bb7-a4d2-7af413bc2a13.png)
![QQ截图20220227212558](https://user-images.githubusercontent.com/56494512/155884314-4e875c38-d817-431b-b66b-108169337cc6.png)

**Comment by PikuZheng** [comment]
您这两个截图无法证实第二dns服务器在正常运行

**Comment by bilibilimrlei** [comment]
> 您这两个截图无法证实第二dns服务器在正常运行

我这已经在那开了快一个月了，一直没出日志，就只看到日志上面有个error说ssl读取失败，然后上面都没显示了
日志：
[smartdns.log](https://github.com/pymumu/smartdns/files/8334547/smartdns.log)

**Comment by PikuZheng** [comment]
这次的日志说配置的上游 adguard doh 设置错误（不允许直接用ip）；开启了测速但自身没有ipv6所以无法给 dns.msftncsi.com 测速，这个地址是用于win10/11自身用来判断网络连接状况的。

日志在一段时间后会自动清理旧的。

**Comment by PikuZheng** [comment]
这次的日志说配置的上游 adguard doh 设置错误（不允许直接用ip）；开启了测速但自身没有ipv6所以无法给 dns.msftncsi.com 测速，这个地址是用于win10/11自身用来判断网络连接状况的。

日志在一段时间后会自动清理旧的。

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
