### ISSUE TITLE
使用最新的commit编译openwrt的包时报错

### ISSUE THREAD

**Issue by fox85** [pymumu/smartdns#891]
util.c: In function 'print_stack':
util.c:1061:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int idx = 0; idx < frame_num; ++idx) {
  ^
util.c:1061:2: note: use option -std=c99 or -std=gnu99 to compile your code

请大佬协助修正一下，谢谢~~~

**Comment by pymumu** [comment]
CFLAG=-std=c99 make all

**Comment by HiGarfield** [comment]
idx的变量声明直接放到block最前面就行了。

**Comment by pymumu** [comment]
最新代码已经修改。
