### ISSUE TITLE
R4S，smartDNS奔溃后无法正常启动 

### ISSUE THREAD

**Issue by luchendi100** [pymumu/smartdns#893]
**问题现象**  
smartdns日志日常报错：
[2022-03-09 08:36:19,370][ERROR][ fast_ping.c:503 ] sendto 115.231.32.104, id 24592, No buffer space available
[2022-03-09 08:36:19,370][ERROR][ fast_ping.c:503 ] sendto 115.231.32.105, id 24593, No buffer space available
[2022-03-09 08:36:19,370][ERROR][ fast_ping.c:503 ] sendto 115.231.32.101, id 24594, No buffer space available
间断性崩溃：
前台显示smartdns运行正常，后台nslookup命令检测不正常，重定向选择的是“作为dnamasq的上游服务器”，后台日志提示smartdns启动失败，被占用，无法启动dns服务器
[2022-03-09 15:23:06,106][ERROR][ smartdns.c:292 ] start dns server failed.
[2022-03-09 15:23:11,359][ERROR][ dns_server.c:3508] bind service :6051 failed, Address in use
[2022-03-09 15:23:11,359][ERROR][ dns_server.c:3751] create server socket failed.

**运行环境**
1. 固件型号  
最新版本

**Comment by pymumu** [comment]
6051端口被其他程序占用了，你netstat -anp看看是那个程序吧，找到后关闭对应的服务。

**Comment by luchendi100** [comment]
smartdns.log的内容基本上就是我上面发的，只不过把重复的去掉了，openwrt的日志提示“smartdns  in a crash loop”，反复崩溃，可能有残留进程未正常结束，导致重启smartdns提示端口被占用，kill进程后页面重启服务可以正常启动smartdns，但是隔几天就出现崩溃情况，也不知道触发条件是啥。

**Comment by pymumu** [comment]
netstat -anp看一下那个进程占用了端口啊。
并且你那个log里面，并没有smartdns异常的情况，有可能是被其他进程kill了

**Comment by PikuZheng** [comment]
smartdns作为dnsmasq的上游时，存在死线程的情况 #757 。
如果没有必要，建议不要作为dnsmasq的上游使用。

另外您用的“最新版本”是release35还是最新代码自己编译的（后面更新过很多次

**Comment by luchendi100** [comment]
Release 35的版本也尝试过，作为dnsmasq的上游时，程序会莫名崩溃。建议重定向不选择，还是选择重定向53端口到smartdns的模式呢？

**Comment by luchendi100** [comment]
选择重定向53端口到smartdns
![Snipaste_2022-03-16_18-54-37](https://user-images.githubusercontent.com/33189796/158577194-779be315-c1d9-4c2c-9099-bf49faf72d06.png)
![Snipaste_2022-03-16_18-54-23](https://user-images.githubusercontent.com/33189796/158577216-7e13c9c7-7c91-47fb-98f8-2f07e4971fe9.png)

**Comment by PikuZheng** [comment]
从图2来看smartdns正在运行。从图1来看smartdns无法启动，与#757的情况一致。
另外您用的“最新版本”是release35还是最新代码自己编译的？

**Comment by luchendi100** [comment]
我用的是骷髅头编译的固件https://github.com/DHDAXCW/NanoPi-R4S，smartdns版本如下
![image](https://user-images.githubusercontent.com/33189796/158916143-dd90a0c9-9be4-4a15-ba77-83cd817c761a.png)

**Comment by PikuZheng** [comment]
> 我用的是骷髅头编译的固件https://github.com/DHDAXCW/NanoPi-R4S ，smartdns版本如下 ![image](https://user-images.githubusercontent.com/33189796/158916143-dd90a0c9-9be4-4a15-ba77-83cd817c761a.png)

您这个是已知bug，后面修复了

**Comment by luchendi100** [comment]
最新的版本是Release 35，等待大佬更新

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
