### ISSUE TITLE
只配置https和tls over dns 不断重启

### ISSUE THREAD

**Issue by warrenhoo** [pymumu/smartdns#896]
**问题现象**  
smartdns作为dnsmasq的上游服务器， 在不配置udp查询服务器诸如223.5.5.5的情况下， 只单纯配置https和tls查询服务器，luci 界面显示smartdns不断重启和停止运行，查询dns失败，  我猜测是不是应该像adguardhome一样，如果只配置https和tls的dns服务器，应该要加入“Bootstrap DNS 服务器”
Bootstrap DNS 服务器用于解析您指定为上游的 DoH / DoT 解析器的 IP 地址。

**运行环境**
1. 固件型号  
x86 openwrt
2. 运营商  

**重现步骤**
1. 上游DNS配置。  
dnsmasq
2. 访问的域名。  
baidu.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。 
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
这应该是两个不同的故障。一个是 #567 #677 #887 ，另一个是[#893](https://github.com/pymumu/smartdns/issues/893#issuecomment-1072269203)

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
