### ISSUE TITLE
发个APM821的固件呗，官方的还是2020年的

### ISSUE THREAD

**Issue by tqangxl** [pymumu/smartdns#897]
**需求应用场景**
请描述需求应用的场景和方式。

**建议的方案**
实现上述场景建议的方案。

**设备信息**
1. 设备信息（CPU，厂家）  

2. 固件信息
2) 路由器型号和固件版本
A：root@OpenWrt:~# cat /proc/cpuinfo
processor : 0
cpu : APM821XX
clock : 1000.000010MHz
revision : 28.131 (pvr 12c4 1c83)
bogomips : 2000.00

timebase : 1000000010
platform : PowerPC 44x Platform
model : Netgear WNDR4700/WNDR4720 Series
Memory : 256 MB
查看当前路由器的架构
root@OpenWrt:~# opkg print-architecture | awk '{print $2}'
all
noarch
powerpc_464fp

smartdns | 1.2020.30-1 | 82.3 KB | SmartDNS is a local DNS server which accepts DNS query requests from local network clients,…

**Comment by PikuZheng** [comment]
ppc 的 好罕见 自己编译试试

**Comment by PikuZheng** [comment]
叫github编译了一下 没有测试环境不确定能不能用 先试试吧
[smartdns-openwrt-powerpc-static.zip](https://github.com/pymumu/smartdns/files/8355380/smartdns-openwrt-powerpc-static.zip)

**Comment by tqangxl** [comment]
谢谢，我先试试
