### ISSUE TITLE
请问这样算不算正常运行？

### ISSUE THREAD

**Issue by smdx** [pymumu/smartdns#898]
LEDE系统设置重定向53端口，nslookup -querytype=ptr smartdns命令超时，iptables -t nat -L PREROUTING | grep REDIRECT查看有规则。这样算不算正常运行了？谢谢

![2022-03-27_191323](https://user-images.githubusercontent.com/9279217/160278927-dca8816a-9d2a-4344-aa2b-12f8d42cf1d2.jpg)

**Comment by PikuZheng** [comment]
只能看出重定向正确 不能确定smartdns是否正常运行
