### ISSUE TITLE
关于一些小意见

### ISSUE THREAD

**Issue by ziojacky** [pymumu/smartdns#899]
是否可以增加转发ptr记录到上游的功能或者自定义ptr记录 还有是否可以增加除A记录以外的缓存功能?

**Comment by PikuZheng** [comment]
#763 自定义ptr记录功能是缺失的 
#883 ptr查询的确会转发到上游 但如果上游应答了不存在ptr记录 smartdns会返回超时（因为需要等所有上游都应答或不应答）

**Comment by PikuZheng** [comment]
A记录 AAAA记录和CNAME记录都是有缓存的 #787 
MX NS SRV TXT 据我观察是没有缓存但这几种查询不频繁 没缓存也能接受吧？

**Comment by PikuZheng** [comment]
#525

**Comment by pymumu** [comment]
非A，AAAA记录都会上游转发，也不会缓存。
