### ISSUE TITLE
试用反馈

### ISSUE THREAD

**Issue by g3ne** [pymumu/smartdns#9]
1、
经试用smartdns不能防御投毒，测试youtube.com会出现大量随机毒ip，建议增加毒ip过滤，
参考ChinaDNS： https://github.com/shadowsocks/ChinaDNS/blob/master/iplist.txt
2、
是否考虑增加缓存的落地/重载机制？
3、
编译时建议去掉libgcc_s.so，即 -static-libgcc 。
4、
rpath建议清理太不美观。

**Comment by pymumu** [comment]
1. 
这里防御是通过检测来完成的，投毒的IP地址是检测不通的，并不会返回给终端。
所以，也算是投毒检测的一种方案。chinaDNS的IP过滤，考虑过，但chinaDNS已经支持了。
考虑后续smartDNS会开源，所以，不光国内用户使用。

2.
理论可以增加，但这个是基于检测的，落地后，就没机会检测速度了。这个还没考虑清楚场景。

3. 
现在也头疼openwrt的N多版本，编译器都有N个，维护比较麻烦，集成libgcc静态编译虽好，要强制开源，现在暂时没考虑，开源会在一段时间后看情况开源。现在这样配套发版本，暂时应该没问题吧 。

4.
之前没注意这个，openwrt的toolchain居然有些是带rpath的，release 8用chrpath命令去掉了rpath。

**Comment by g3ne** [comment]
1、
【投毒的IP地址是检测不通的，并不会返回给终端】这里逻辑错误。
不知道你实现ip检测的方法，实测中smartdns仍返回如59.24.3.173这样的毒ip。
假设你使用 SYN+ACK 对ip进行活检，此ip是会响应的，且会动态改变响应延时，故 通过检测ip存活和响应速度无法过滤毒ip。

【目前有两个方案，1是通过EDNS，2是通过DNS后缀。】
EDNS防御投毒的方案出处请告知一下谢谢。
这里的“通过DNS后缀”是指什么？是查PTR？

**仍然建议优先增加黑名单功能，如果并不打算支持毒ip黑名单过滤，请告知谢谢。**

2、
ReadMe里写smartdns能过滤广告，如果是通过 address /www.example.com/1.2.3.4 字段设置实现，建议增加外联其他HOSTS文件功能，因为HOSTS需要经常更新/文件较大/存放于不同路径。

3、
实测时配置文件里的 log-level 、 log-file 无效，甚至都没有创建日志文件。

**Comment by pymumu** [comment]
1. 在所有IP都检测不通的情况下，会返回第一个响应的IP地址。所以，即使投毒的IP，也会返回。
    所以，上游无污染DNS必须配置。现在检测是ping+tcp，并没有SYN+ACK，原因就是投毒。虽然TCP性能消耗大。

2. EDNS加ECS扩展。DNS后缀，可以google搜一下就有。

3. address功能是对标dnsmasq的，是后缀匹配的模式，相比hosts维护简单，比如google的，配置.google.com就可以了；hosts的支持，可能到时会提供一个工具，将hosts转换到address的后缀匹配。这样效率更高。 单独路径后面会增加。

日志这个：是luci脚本问题，脚本过滤了address；后面解决。

**Comment by pymumu** [comment]
这里edns用来做投毒检测。

**Comment by laggardkernel** [comment]
@pymumu  目前smartdns防污染存在很大问题。

一、IP黑名单早就已经不是一种靠谱方案，应该弃用。

现在污染结果内并非全是无效IP，防火墙可能随机扔给你其他网站的IP。例如，查询google返回你一个Twitter地址。黑名单不可能解决这个问题，因为它不能去涵盖twitter的IP，如果包含了就会出现误杀。

二、检查edns也不是一种完全有效的方案。

这只对于境外DNS返回结果有效。境内DNS返回的污染解析结果依然会带有edns option，不知道为什么境内DNS会添加上这个。

总之，目前两种方案都不能保证防污染，应该尽早进入chinadns的IP分流，即要求境内DNS返回解析结果必须为境内IP，境外DNS返回解析结果必须为境外IP。

**Comment by pymumu** [comment]
国内DNS应用黑名单，国外DNS应用DOT，DOH，或EDNS

**Comment by laggardkernel** [comment]
我上面已经说过了。GFW返回的虚假IP列表根本不靠谱，这早就是过时的方案了。

https://github.com/chengr28/Pcap_DNSProxy/issues/288

https://github.com/nagae-memooff/gfw-ip-list

https://chinadigitaltimes.net/chinese/2015/01/gfw升级dns污染策略-殃及无辜网站/

**Comment by pymumu** [comment]
虚假IP也是一个范围的，有人遍历过了。可以参考：
https://github.com/pymumu/smartdns/issues/91

smartdns要获取正确的结果是很容易，但由于一些不可抗原因，smartdns并没有做到开箱即用，也不能在这里写太清楚。

总之，需要自己动手配置才能达到希望的效果，只是简单使用的话，只有加速作用。
可以多看看FAQ，配置参数的地方，还有ISSUE里面的其他人的经验。

**Comment by laggardkernel** [comment]
虚假IP段问题在于，在15年和17年其都出现过变动，并不靠谱。谁都不能保证GFW总是返回这么个规律的IP端。我只是希望smartdns能引入一种100%准确鉴别出正确IP的方案。
> GFW 用被墙网站服务器的 IP 地址做投毒污染其实不算新了，应该是属于中等级别。低一级的就是平时的，高一级的是 2016 年头那时直接用随机有效的。这次起码也还是在墙内无效的地址，只是 IP 地址的名单每次都不一样。

**Comment by pymumu** [comment]
[smartdns.1.2019.06.15-1159.x86_64.tar.gz](https://github.com/pymumu/smartdns/files/3292683/smartdns.1.2019.06.15-1159.x86_64.tar.gz)

无非就是route列表，你可以在x86的机器或wsl上验证
accept-ip指定可接受IP范围。server指定-accept-ip启动对特定服务器的IP范围检查。
```
server 1.2.3.4 -accept-ip
accept-ip  1.2.3.4/24
```

**Comment by pymumu** [comment]
请使用release 26 special版本， accept-ip，名称改为whitelist-ip
具体看参数说明。

**Comment by zanzhz1101** [comment]
> 虚假IP段问题在于，在15年和17年其都出现过变动，并不靠谱。谁都不能保证GFW总是返回这么个规律的IP端。我只是希望smartdns能引入一种100%准确鉴别出正确IP的方案。
> 
> > GFW 用被墙网站服务器的 IP 地址做投毒污染其实不算新了，应该是属于中等级别。低一级的就是平时的，高一级的是 2016 年头那时直接用随机有效的。这次起码也还是在墙内无效的地址，只是 IP 地址的名单每次都不一样。

哈哈，其实没必要的啦，在一段时间内可用就很棒了
