### ISSUE TITLE
域名列表通过指定 dns 来查询

### ISSUE THREAD

**Issue by onion83** [pymumu/smartdns#90]
对标 dnsmasq 的 server 功能

> server=/.google.com/8.8.8.8
> server=/.twitter.com/8.8.8.8#443
> ...

符合列表的域名，直接走指定的 dns 查询（超时就超时，污染就污染，不管），不再走默认的dns查询和优选，结合 gfwlist 生成黑名单应该会有很大用途。

**Comment by pymumu** [comment]
为什么不能直接用dnsmasq

**Comment by onion83** [comment]
现在 smartdns adderss 已经实现了，server 功能再实现就可以完全取代 dnsmasq 了

**Comment by pymumu** [comment]
要取代dnsmasq还有很长路要走。还有不少功能都缺少。dhcp是其中一个大头，简单dhcp虽然代码不多。
smartdns目前的功能都和dnsmasq有差异。
就address来说，比dnsmasq多了，高性能匹配，SOA返回，忽略特定域名等。
ipset也有差异，高性能匹配，超时等。

对于server，现在能想到的差异，就是指定group来批量发送到上游。
这个后面增加吧。

**Comment by onion83** [comment]
既然叫 smartdns，dhcp 的功能自然没必要关注了，还是专注 dns 的解析吧.

既然都指定了 server 说明用户已经解决上游的 dns 污染和可用性的问题，这个无需再关注了。

这个其实有一个关键点就是，域名解析的分流和 dns 服务器的分组管理。

可不可以设置一个 dns 组的概念，例如：

default -> 114.114.114.114、223.5.5.5 
free      -> 8.8.8.8、1.1.1.1
office  -> 172.16.1.1、172.16.1.2

默认走 default、符合 gfwlist 的走 free、公司、开发域名走 office。优选、测速的逻辑不变。

为什么要做域名和 dns 服务器组的映射？因为既然已经名明知到域名是被污染的，再发给国内的运营上的 dns 是无意义的，加上测速逻辑甚至是危险的，有被请喝饮茶可能。既然已经有社区成果知道哪些是被污染域名，且用户已自行解决 dns 污染问题（自建 dnsproxy 加密代理，走本地 udp 加密隧道等），加入域名和dns 的组映射也是很自然的事情了。

**Comment by pymumu** [comment]
@onion83 
你用的是哪个安装包，我给你给版本，你验验看看。

**Comment by onion83** [comment]
x86_64 / onion83[at]gmail.com （谢谢）

**Comment by pymumu** [comment]
[smartdns_build.zip](https://github.com/pymumu/smartdns/files/2901182/smartdns_build.zip)

x86-64有两个版本，都打包了，你自己选下。

使用方法：
上游服务配置项`-group [office]`指定属组,`-group`可重复多次。default默认加入。
```
nameserver /domain/office
```
指定解析的组

**Comment by onion83** [comment]
很棒，已经验证过可实现分组功能、域名按分组来解析了，现在直接通过 remote tls 直连 8.8.8.8 / 1.1.1.1 查询，完全代替了 dnsmasq 和一个本地加密代理，现在已经开 debug 模式 跑几天看看会不会 crash。

这个功能我觉得实现的差不多了，合并到主干公测吧。

我的配置下，其他朋友可以参考下

`smartdns.conf`

> ……
> conf-file /etc/smartdns/gfwlist.conf
> ……
> server-tls 8.8.4.4 -group free -exclude-default-group
> server-tls 1.1.1.1 -group free -exclude-default-group
> ……

`gfwlist.conf` 

> ……
> nameserver /.google.com.hk/free
> nameserver /.google.com.sg/free
> nameserver /.google.com.jp/free
> nameserver /.google.com.sg/free
> nameserver /.googlevideo.com/free
> ……

另外发现 include 进来的文件 conf-file 必须写完整路径，否者貌似配置没有读入.

**Comment by pymumu** [comment]
release 21已经支持此特性，conf-file支持相对路径，可以获取验证

**Comment by 0064Unknown** [comment]
> 
> 另外发现 include 进来的文件 conf-file 必须写完整路径，否者貌似配置没有读入.

@pymumu 请问自定义conf-file规则加在具体哪个文件里？我加在/var/etc/smartdns/smartdns.conf后重启会消失，加在custom.conf不起作用

**Comment by pymumu** [comment]
在界面的自定义配置tab页中添加
