### ISSUE TITLE
serve-expired-reply-ttl 这个参数是什么意思呢

### ISSUE THREAD

**Issue by InspoOnU** [pymumu/smartdns#900]
Wiki里说开启缓存过期服务后，会返回TTL=0的结果并尝试再次请求。同时又说serve-expired-reply-ttl=0会禁用过期缓存，但是这个参数的默认值是5，也就是返回TTL=5的结果。
怎么设置才能让过期缓存返回TTL=0的结果呢？

**Comment by PikuZheng** [comment]
```
同时又说serve-expired-reply-ttl=0会禁用过期缓存
```
以我的理解，这里应该是“serve-expired-ttl=0”会禁用过期缓存。

**Comment by PikuZheng** [comment]
> > 
> 
> wiki里的serve-expired-reply-ttl说的是”秒，0 表示停用超时，大于 0 表示指定的超时的秒数“

所以 serve-expired-reply-ttl=0 不会导致过期缓存禁用。那么现在还有什么问题呢？

**Comment by pymumu** [comment]
wiki描述有问题，这个值就是缓存过期后，客户端查询时返回的TTL值。
设置为5比较合理。这个是RFC里面推荐的值。
