### ISSUE TITLE
killall smartdns; smartdns 重启不成功

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#901]
killall smartdns; smartdns
上面的命令相当于重启，但实际执行完smartdns并没有启动，看日志，没有产生任何新的日志信息，如果在中间加个sleep 1，就可以正常的重启成功
killall smartdns; sleep 1; smartdns

用的最新的Release 36测试的，x64和arm64上都有这个问题，配置文件我试了最简单的配置也会有这个问题。
bind :53
bind-tcp :53
server 223.5.5.5

又试了下，如果这样执行，会看到Server is already running.的报错
killall smartdns; smartdns -f
说明killall在smartdns进程真正结束前就结束了，就开始执行下条命令了，正常来说，killall一定是执行完了再去执行下一条命令的，所以好奇怪的问题。

我记得以前的版本是可以的，不知道从哪个版本开始就不行了，必须加个sleep等待1秒才可以，虽然不是什么大bug，但也反馈给大佬，希望大佬有时间可以修复下。

**Comment by pymumu** [comment]
killall的时候，会通知smartdns退出，在退出的时候，会持久化缓存，所以需要时间。

如果要重启服务，推荐是使用/etc/init.d/smartdns命令。里面做了处理。

**Comment by PHCSJC** [comment]
好的，非常感谢，我是只下载了一个smartdns bin文件
