### ISSUE TITLE
启动后会挂掉

### ISSUE THREAD

**Issue by Baojun-Chen** [pymumu/smartdns#904]
**问题现象**  

简要描述问题出现的现象
配置了之后 重启了下就不行了，一起动就挂
下面是日志
[smartdns.log](https://github.com/pymumu/smartdns/files/8455766/smartdns.log)

**运行环境**
1. 固件型号  
openwrt arm

3. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
请问用的是什么cpu，环境是arm还是arm64

**Comment by pymumu** [comment]
看错误是硬件兼容问题，最好是你自己编译一个版本。

**Comment by Baojun-Chen** [comment]
> 请问用的是什么cpu，环境是arm还是arm64

你好，我用的是S905D arm64位的cpu 系统也一样64

**Comment by pymumu** [comment]
看你用的是arm版本的，不是64位版本安装包

**Comment by pymumu** [comment]
[smartdns.1.2022.04.09-1104.aarch64-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/8456134/smartdns.1.2022.04.09-1104.aarch64-optware-all.ipk.zip)

**Comment by Baojun-Chen** [comment]
> [smartdns.1.2022.04.09-1104.aarch64-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/8456134/smartdns.1.2022.04.09-1104.aarch64-optware-all.ipk.zip)

这个文件是标准版的liunx用的吧，安装会报错段落问题，我的服务器uname信息（Linux OpenWrt  #394 SMP PREEMPT Sat Mar 12 03:09:55 CST 2022 aarch64 GNU/Linux
）**我用（smartdns.1.yyyy.MM.dd-REL.arm-optware-all.ipk）**

破案了，查来查去是那个上游服务器配置那里，如果配置的加密的DNS（dns.google/dns-query ）链接就会一直报错权限问题，使用8.8.8.8 这种就不会报错能够正常使用

这是我的配置文件，加密的上游服务器我把启用关掉了
[smartdns.txt](https://github.com/pymumu/smartdns/files/8456828/smartdns.txt)

**Comment by PikuZheng** [comment]
> > [smartdns.1.2022.04.09-1104.aarch64-optware-all.ipk.zip](https://github.com/pymumu/smartdns/files/8456134/smartdns.1.2022.04.09-1104.aarch64-optware-all.ipk.zip)
> 
> 这个文件是标准版的liunx用的吧，安装会报错段落问题，我的服务器uname信息（Linux OpenWrt #394 SMP PREEMPT Sat Mar 12 03:09:55 CST 2022 aarch64 GNU/Linux ）**我用（smartdns.1.yyyy.MM.dd-REL.arm-optware-all.ipk）**
> 
> 破案了，查来查去是那个上游服务器配置那里，如果配置的加密的DNS（dns.google/dns-query ）链接就会一直报错权限问题，使用8.8.8.8 这种就不会报错能够正常使用
> 
> 这是我的配置文件，加密的上游服务器我把启用关掉了 [smartdns.txt](https://github.com/pymumu/smartdns/files/8456828/smartdns.txt)

从架构上来说你应该用 aarch64-openwrt-all.ipk 另外怀疑您没有安装libopenssl
