### ISSUE TITLE
Release36.1 运行一段时间后不再工作

### ISSUE THREAD

**Issue by martincz** [pymumu/smartdns#905]
**问题现象**  
Release36.1 运行一段时间后无法进行 DNS 查询请求

**运行环境**
1. 设备：群晖 DS918+
2. 系统：DSM 7.0.1-42218 Update 3
3. 处理器：CPU INTEL Celeron J3455
4. Docker 版本：20.10.3, build b455053 （群晖套件中心提供）
5. docker-smartdns 来源：https://github.com/martincz/docker-smartdns

**重现步骤**
1. 运行一段时间后自己就挂掉了，执行dig www.xxxx.com @ip -p port 没有响应。
2. 回撤到 Release35 可以稳定运行。

**信息收集**  
1. 日志没体现出任何有价值的信息，唯一能确定的是网炸掉了，因为 ping 任何网站都不通了。
2. 应该和Release36.1版本有关，因为除了版本切换，其它都没有变。
3. 我能做些什么来协助定位问题？
![smartdns](https://user-images.githubusercontent.com/351434/162591557-45f21719-7a20-48ef-a174-fa5776836d08.png)

**Comment by PikuZheng** [comment]
我在docker里跑，哪个版本都没有问题啊

**Comment by PikuZheng** [comment]
上面图片中有一个“终端机” 可以进docker的命令行检查docker自身的网络问题。我感觉是docker自身网不通了

**Comment by pymumu** [comment]
二分法排查下代码看看36的那个commit引发的。或者看看有没有对应调用栈打印。

**Comment by martincz** [comment]
> 上面图片中有一个“终端机” 可以进docker的命令行检查docker自身的网络问题。我感觉是docker自身网不通了
smartdns 容器本身是以 docker 的 host 网络模式运行的，出现问题后，我用docker exec -it [CONTAINER ID] /bin/sh 进入到smartdns的容器里去发现 ping 外网不通了。
我之前 35 版本稳定运行了几个月，36.1 运行没几分钟就外网不通无法进行 DNS 查询了，回退到35睡了一觉起来还是好好的。
因此我敢肯定的说是 36.1 的问题 。

**Comment by martincz** [comment]
> 二分法排查下代码看看36的那个commit引发的。或者看看有没有对应调用栈打印。

谢谢，熬夜脑子有点懵，35 到 36.1 这也没差几个commit，我应该回撤下commit看看的，晚点我试试。

**Comment by martincz** [comment]
我换了个思路解决了这个问题，因为 @pymumu 大佬没有制作并发布 docker hub 的镜像，所以之前我从 docker hub 下载的是别人制作的 35 版本镜像，随后我 fork 其项目修改并制作了 36.1 版本镜像。

该镜像中 smartdns 是跑在 alpine linux 上的，而我方才留意到 @pymumu 虽然没有在docker hub 发布镜像，但是有提供Dockerfile。我注意到 @pymumu 的 Dockerfile 默认配置是跑在 debian 上的，了解到这个差异后，我使用该 Dockerfile 制作了个新的镜像并进行尝试。。

随后问题神奇的消失了，至今它仍然正常工作。所以我认为是 36.1 版本和 alpine 之前有什么小毛病，既然问题解决了，那么具体原因对我来说，就不重要了，毕竟大佬的参考配置是 debian。^ ^

**Comment by PikuZheng** [comment]
并没有。。。上午九点我在群晖上启了alpine的smartdns（用的[martincz/docker-smartdns](https://github.com/martincz/docker-smartdns)，但是36.1），到目前仍正常运行。
docker本身网络问题，还是要考虑群晖和环境的情况

**Comment by martincz** [comment]
> 并没有。。。上午九点我在群晖上启了alpine的smartdns（用的[martincz/docker-smartdns](https://github.com/martincz/docker-smartdns)，但是36.1），到目前仍正常运行。 docker本身网络问题，还是要考虑群晖和环境的情况

那可真就见了鬼了，我试了几次都是没过多久就崩。。。不管它了，反正用debian好了。。。
