### ISSUE TITLE
关于speed-check设置问题

### ISSUE THREAD

**Issue by tufu9441** [pymumu/smartdns#906]
请问一下，如果在`bind`中设置了`-no-speed-check`参数，那么再在`domain-rule`中设置的`speed-check-mode`是不是也就不起作用，不会再测速了？

**Comment by PikuZheng** [comment]
正确

**Comment by tufu9441** [comment]
> 正确

那么我看`speed-check-mode`的默认值是`none`，如果没有在配置文件中特别设置的话，是不是也就不会测速？

**Comment by tufu9441** [comment]
明白了，多谢！

**Comment by tufu9441** [comment]
> 正确，默认是不测速

再次请教确认一下，如果我在`bind`中不加`-no-speed-check`参数，然后也不设置`speed-check-mode`，就保持默认的`none`，这样的话是不是就只有在`domain-rules`中设置有`speed-check-mode`类型的域名才会开启测速？

**Comment by sxml** [comment]
bind :7053 -group GFW -no-speed-check  
这分组 -no-speed-check 为什么国外分组要不测速不缓存呢？ 难道开启不好？
smartdns有没有电报群

**Comment by PikuZheng** [comment]
> bind :7053 -group GFW -no-speed-check 这分组 -no-speed-check 为什么国外分组要不测速不缓存呢？ 开启有什么不好？ smartdns有没有电报群

这个看个人环境吧。就我自己来说，国外组icmp不通，tcp会代理抢答，测速=减速器。另一方面常用的google连哪里的ip都差不多，cf默认给出的两个ip都在同一个数据中心，测速没有意义。
如果你是隧道的梯子，那么测速可能有必要。
