### ISSUE TITLE
请问华硕梅林路由器KoolCenter_Merlin386 armV7应该下载哪一个版本？

### ISSUE THREAD

**Issue by tiujejauci** [pymumu/smartdns#907]
**应用场景**
华硕路由器AX3000 ArmV7

**[列表](https://github.com/pymumu/smartdns#%E4%B8%8B%E8%BD%BD)**没有详细说明，请问华硕梅林路由器armV7应该下载哪一个版本？
![image](https://user-images.githubusercontent.com/31369434/163320376-1c1fb175-d0f0-46bb-bcb0-29b429b4218c.png)

我应该选择哪一个[版本](https://github.com/pymumu/smartdns/releases/tag/Release36.1)呢？
![image](https://user-images.githubusercontent.com/31369434/163321096-ab13e2e2-d854-4880-a493-a5d3ac79b6c5.png)

**Comment by PikuZheng** [comment]
请进路由器命令行界面输入uname -a按回车看一下系统架构和软件版本

**Comment by tiujejauci** [comment]
> 請進路由器命令行界面輸入uname -a按回車看一下系統架構和軟件版本

![image](https://user-images.githubusercontent.com/31369434/163330295-5af78a27-aac7-4b85-9076-047e252c2fca.png)

**Comment by PikuZheng** [comment]
需要arm-optware 另外koolshare内置软件商店应该有吧

**Comment by tiujejauci** [comment]
> 需要arm-optware 另外koolshare內置軟件商店應該有吧

並沒有
![image](https://user-images.githubusercontent.com/31369434/163341856-4e303e28-0d37-4f18-9364-49492dd2c762.png)

**Comment by tiujejauci** [comment]
目前koolshare并没有smart dns扩充元件

![image](https://user-images.githubusercontent.com/31369434/163684296-1f50d984-7abf-4fd0-a29e-c9eeac986c13.png)

**Comment by cary-sas** [comment]
> 请进路由器命令行界面输入uname -a按回车看一下系统架构和软件版本

armv7l Merlin-Koolshare
