### ISSUE TITLE
Support for hosts file

### ISSUE THREAD

**Issue by clustor** [pymumu/smartdns#908]
Can smartdns support reading hosts file?  This will help me use smartdns exclusively for DNS resolution without relying on dnsmasq at all.

**Comment by PikuZheng** [comment]
no but use address rules or domain rules instead.
`address /www.example.com/1.2.3.4`
`domain-rules /www.example.com/ -a 1.2.3.4`
A or AAAA only, no PTR

**Comment by clustor** [comment]
Sure. That's exactly what I did with address rule. 

On my router, I have some static reservations for IPs and hostnames with DHCP using DNSMASQ and these get exported to to hosts file. It would be convenient to read from the file directly. May be you consider this as a feature request with config options "hosts-file".

**Comment by PikuZheng** [comment]
#354 support dhcp lease of dnsmasq
