### ISSUE TITLE
36.1无法使用

### ISSUE THREAD

**Issue by jkle112** [pymumu/smartdns#909]
**问题现象**  
简要描述问题出现的现象
2021版本的配置，一直使用正常，未改动。
安装后，界面和以前的配置文件严重不兼容，于是重新写配置，luci-app-smartdns.1.2022.04.05-2046.all-luci-compat-all.ipk的界面点添加无法弹出选项，换装[luci-app-smartdns.1.2022.04.05-2046.all-luci-all.ipk]终于可以编辑了，写了几个结果无法启动运行。
自定义配置拷贝过去后，一保存界面还是空白的，文件还是有保存。
**运行环境**
1. 固件型号  MV1000W 3.212 BETA3

2. 运营商  
电信

**Comment by PikuZheng** [comment]
```
安装步骤：
卸载原有安装包

opkg remove luci-app-smartdns
opkg remove smartdns

安装新软件包

opkg install smartdns.xxxxxxxx.xxxx.ipk
opkg install luci-app-smartdns.xxxxxxxx.xxxx.all.ipk
```

**Comment by jkle112** [comment]
是按照上面的步骤操作的，还是不行。
后来恢复出厂，重装固件，在安装应用，恢复正常了。
期待进一步更新，非常感谢！

**Comment by PikuZheng** [comment]
> 是按照上面的步骤操作的，还是不行。 后来恢复出厂，重装固件，再安装应用，恢复正常了。 期待进一步更新，非常感谢！

旧版有卸载后配置文件残留问题，按说再卸一次再装一次就好了
