### ISSUE TITLE
提供一个自用的blacklist

### ISSUE THREAD

**Issue by zanzhz1101** [pymumu/smartdns#91]
这些是我自己归纳的ip，主要是一些众所周知上不去的网站的污染ip，欢迎新增和修改
blacklist-ip 8.7.198.45
blacklist-ip 31.13.64.1
blacklist-ip 31.13.64.33
blacklist-ip 31.13.64.49
blacklist-ip 31.13.65.1
blacklist-ip 31.13.65.17
blacklist-ip 31.13.65.18
blacklist-ip 31.13.66.1
blacklist-ip 31.13.66.6
blacklist-ip 31.13.66.23
blacklist-ip 31.13.68.1
blacklist-ip 31.13.68.22
blacklist-ip 31.13.69.33
blacklist-ip 31.13.69.86
blacklist-ip 31.13.69.129
blacklist-ip 31.13.69.160
blacklist-ip 31.13.70.1
blacklist-ip 31.13.70.20
blacklist-ip 31.13.71.7
blacklist-ip 31.13.71.23
blacklist-ip 31.13.72.1
blacklist-ip 31.13.72.17
blacklist-ip 31.13.72.23
blacklist-ip 31.13.72.34
blacklist-ip 31.13.72.54
blacklist-ip 31.13.73.1
blacklist-ip 31.13.73.17
blacklist-ip 31.13.73.23
blacklist-ip 31.13.74.1
blacklist-ip 31.13.74.17
blacklist-ip 31.13.75.17
blacklist-ip 31.13.75.18
blacklist-ip 31.13.76.8
blacklist-ip 31.13.76.16
blacklist-ip 31.13.77.33
blacklist-ip 31.13.77.55
blacklist-ip 31.13.78.65
blacklist-ip 31.13.78.66
blacklist-ip 31.13.79.1
blacklist-ip 31.13.79.17
blacklist-ip 31.13.80.1
blacklist-ip 31.13.80.17
blacklist-ip 31.13.81.1
blacklist-ip 31.13.81.17
blacklist-ip 31.13.82.1
blacklist-ip 31.13.82.17
blacklist-ip 31.13.82.23
blacklist-ip 31.13.83.1
blacklist-ip 31.13.83.8
blacklist-ip 31.13.83.16
blacklist-ip 31.13.84.1
blacklist-ip 31.13.84.8
blacklist-ip 31.13.84.16
blacklist-ip 31.13.85.1
blacklist-ip 31.13.85.8
blacklist-ip 31.13.85.16
blacklist-ip 31.13.86.1
blacklist-ip 31.13.86.8
blacklist-ip 31.13.86.16
blacklist-ip 31.13.97.245
blacklist-ip 31.13.97.248
blacklist-ip 46.82.174.68
blacklist-ip 59.24.3.173
blacklist-ip 64.13.192.74
blacklist-ip 64.13.192.76
blacklist-ip 64.13.232.149
blacklist-ip 66.220.146.94
blacklist-ip 66.220.147.11
blacklist-ip 66.220.147.44
blacklist-ip 66.220.147.47
blacklist-ip 66.220.149.18
blacklist-ip 66.220.149.32
blacklist-ip 66.220.149.99
blacklist-ip 66.220.151.20
blacklist-ip 66.220.152.17
blacklist-ip 66.220.152.28
blacklist-ip 66.220.155.12
blacklist-ip 66.220.155.14
blacklist-ip 66.220.158.32
blacklist-ip 67.15.100.252
blacklist-ip 67.15.129.210
blacklist-ip 67.228.37.26
blacklist-ip 67.228.74.123
blacklist-ip 67.228.102.32
blacklist-ip 67.228.126.62
blacklist-ip 67.228.221.221
blacklist-ip 67.228.235.91
blacklist-ip 67.228.235.93
blacklist-ip 69.63.176.15
blacklist-ip 69.63.176.59
blacklist-ip 69.63.176.143
blacklist-ip 69.63.178.13
blacklist-ip 69.63.180.173
blacklist-ip 69.63.181.11
blacklist-ip 69.63.181.12
blacklist-ip 69.63.184.14
blacklist-ip 69.63.184.30
blacklist-ip 69.63.184.142
blacklist-ip 69.63.186.30
blacklist-ip 69.63.186.31
blacklist-ip 69.63.187.12
blacklist-ip 69.63.189.16
blacklist-ip 69.63.190.26
blacklist-ip 69.171.224.12
blacklist-ip 69.171.224.40
blacklist-ip 69.171.224.85
blacklist-ip 69.171.225.13
blacklist-ip 69.171.227.37
blacklist-ip 69.171.228.20
blacklist-ip 69.171.228.74
blacklist-ip 69.171.229.11
blacklist-ip 69.171.229.28
blacklist-ip 69.171.229.73
blacklist-ip 69.171.230.18
blacklist-ip 69.171.232.21
blacklist-ip 69.171.233.24
blacklist-ip 69.171.233.33
blacklist-ip 69.171.233.37
blacklist-ip 69.171.234.18
blacklist-ip 69.171.234.29
blacklist-ip 69.171.234.48
blacklist-ip 69.171.235.16
blacklist-ip 69.171.235.64
blacklist-ip 69.171.235.101
blacklist-ip 69.171.237.16
blacklist-ip 69.171.237.26
blacklist-ip 69.171.239.11
blacklist-ip 69.171.240.27
blacklist-ip 69.171.242.11
blacklist-ip 69.171.242.30
blacklist-ip 69.171.244.11
blacklist-ip 69.171.244.12
blacklist-ip 69.171.244.15
blacklist-ip 69.171.245.49
blacklist-ip 69.171.245.53
blacklist-ip 69.171.245.84
blacklist-ip 69.171.246.9
blacklist-ip 69.171.247.20
blacklist-ip 69.171.247.32
blacklist-ip 69.171.247.71
blacklist-ip 69.171.248.65
blacklist-ip 69.171.248.112
blacklist-ip 69.171.248.128
blacklist-ip 74.86.3.208
blacklist-ip 74.86.12.172
blacklist-ip 74.86.12.173
blacklist-ip 74.86.17.48
blacklist-ip 74.86.118.24
blacklist-ip 74.86.142.55
blacklist-ip 74.86.151.162
blacklist-ip 74.86.151.167
blacklist-ip 74.86.226.234
blacklist-ip 74.86.228.110
blacklist-ip 74.86.235.236
blacklist-ip 75.126.2.43
blacklist-ip 75.126.33.156
blacklist-ip 75.126.115.192
blacklist-ip 75.126.124.162
blacklist-ip 75.126.135.131
blacklist-ip 75.126.150.210
blacklist-ip 75.126.164.178
blacklist-ip 75.126.215.88
blacklist-ip 78.16.49.15
blacklist-ip 88.191.249.182
blacklist-ip 88.191.249.183
blacklist-ip 88.191.253.157
blacklist-ip 93.46.8.89
blacklist-ip 173.252.73.48
blacklist-ip 173.252.100.21
blacklist-ip 173.252.100.32
blacklist-ip 173.252.102.16
blacklist-ip 173.252.102.241
blacklist-ip 173.252.103.64
blacklist-ip 173.252.110.21
blacklist-ip 174.36.196.242
blacklist-ip 174.36.228.136
blacklist-ip 174.37.54.20
blacklist-ip 174.37.154.236
blacklist-ip 174.37.175.229
blacklist-ip 199.16.156.7
blacklist-ip 199.16.156.40
blacklist-ip 199.16.158.190
blacklist-ip 199.59.148.14
blacklist-ip 199.59.148.97
blacklist-ip 199.59.148.140
blacklist-ip 199.59.148.209
blacklist-ip 199.59.149.136
blacklist-ip 199.59.149.244
blacklist-ip 199.59.150.11
blacklist-ip 199.59.150.49
blacklist-ip 205.186.152.122
blacklist-ip 208.43.170.231
blacklist-ip 208.43.237.140
blacklist-ip 208.101.21.43
blacklist-ip 208.101.48.171
blacklist-ip 208.101.60.87
blacklist-ip 243.185.187.39

**Comment by ziyuedi** [comment]
自己整理了一份比较全的列表
包括几乎不可能有人用的IP和污染IP，可能误杀比较多，不喜勿用
PS：现在屏蔽单个IP作用已经不大了
##IPV4
bogus-nxdomain 0.0.0.0/8
bogus-nxdomain 10.0.0.0/8
bogus-nxdomain 127.0.0.0/8
bogus-nxdomain 100.64.0.0/10
bogus-nxdomain 169.254.0.0/16
bogus-nxdomain 172.16.0.0/12
bogus-nxdomain 192.0.0.0/24
bogus-nxdomain 192.0.2.0/24
bogus-nxdomain 192.31.196.0/24
bogus-nxdomain 192.52.193.0/24
bogus-nxdomain 192.88.99.0/24
bogus-nxdomain 192.168.0.0/16
bogus-nxdomain 192.175.48.0/24
bogus-nxdomain 198.18.0.0/15
bogus-nxdomain 198.51.100.0/24
bogus-nxdomain 203.0.113.0/24
bogus-nxdomain 224.0.0.0/4
bogus-nxdomain 240.0.0.0/4
###IP of DoD
bogus-nxdomain 6.0.0.0/7
bogus-nxdomain 11.0.0.0/8
bogus-nxdomain 21.0.0.0/7
bogus-nxdomain 26.0.0.0/8
bogus-nxdomain 28.0.0.0/7
bogus-nxdomain 30.0.0.0/8
bogus-nxdomain 33.0.0.0/8
bogus-nxdomain 55.0.0.0/8
bogus-nxdomain 214.0.0.0/7
###IP of Prudential plc
bogus-nxdomain 48.0.0.0/8
###IP of USPS
bogus-nxdomain 56.0.0.0/8
##IPV6
bogus-nxdomain ::/8
bogus-nxdomain ::1/8
bogus-nxdomain FE80::/10
bogus-nxdomain FC00::/7
bogus-nxdomain FF00::/8
bogus-nxdomain FF02::/8
bogus-nxdomain 2001::/23
bogus-nxdomain 2001:2::/48
bogus-nxdomain 2001:3::/32
bogus-nxdomain 2001:4:112::/48
bogus-nxdomain 2001:5::/32
bogus-nxdomain 2001:20::/28
bogus-nxdomain 2001:01F8::/29
bogus-nxdomain 2001:DB8::/32
bogus-nxdomain 2620:4F:8000::/48
bogus-nxdomain 3FFE::/16
bogus-nxdomain 4000::/3
bogus-nxdomain 5F00::/8
bogus-nxdomain 6000::/3
bogus-nxdomain 8000::/3
bogus-nxdomain A000::/3
bogus-nxdomain C000::/3
bogus-nxdomain E000::/4
bogus-nxdomain F000::/5
bogus-nxdomain F800::/6
bogus-nxdomain FC00::/7
bogus-nxdomain FE00::/9
bogus-nxdomain FF00::/8
bogus-nxdomain 2002::/16
bogus-nxdomain 2001:DB8::/32
bogus-nxdomain FEC0::/10
bogus-nxdomain ::FFFF:0:0/96
bogus-nxdomain 64:FF9B::/96
bogus-nxdomain 64:FF9B:1::/48
bogus-nxdomain 0100::/8
bogus-nxdomain 100::/64
bogus-nxdomain 0200::/7
bogus-nxdomain 0400::/6
bogus-nxdomain 0800::/5
bogus-nxdomain 1000::/4

blacklist-ip 10.10.10.10
blacklist-ip 101.226.10.0/24
blacklist-ip 103.205.240.0/24
blacklist-ip 104.239.213.0/24
blacklist-ip 108.160.0.0/16
blacklist-ip 110.249.209.0/24
blacklist-ip 1.1.1.1
blacklist-ip 111.11.208.0/24
blacklist-ip 111.175.220.0/23
blacklist-ip 112.132.230.0/24
blacklist-ip 114.112.163.0/24
blacklist-ip 122.218.101.0/24
blacklist-ip 123.125.81.0/24
blacklist-ip 123.126.249.0/24
blacklist-ip 123.129.254.0/24
blacklist-ip 1.2.3.4
blacklist-ip 123.50.49.0/24
blacklist-ip 124.14.8.0/24
blacklist-ip 124.232.132.0/24
blacklist-ip 125.211.213.0/24
blacklist-ip 125.230.148.0/24
blacklist-ip 125.76.239.0/24
blacklist-ip 128.121.126.0/24
blacklist-ip 12.87.133.0/24
blacklist-ip 159.106.121.0/24
blacklist-ip 159.24.3.0/24
blacklist-ip 16.63.155.0/24
blacklist-ip 169.132.13.0/24
blacklist-ip 173.201.216.0/24
blacklist-ip 180.153.103.0/24
blacklist-ip 180.168.41.0/24
blacklist-ip 183.207.232.0/24
blacklist-ip 185.85.13.0/24
blacklist-ip 188.5.4.0/24
blacklist-ip 189.163.17.0/24
blacklist-ip 197.4.4.0/24
blacklist-ip 198.105.254.0/24
blacklist-ip 20.139.56.0
blacklist-ip 20.20.20.20
blacklist-ip 202.100.220.0/24
blacklist-ip 202.100.68.0/24
blacklist-ip 202.102.110.0/24
blacklist-ip 202.106.1.0/24
blacklist-ip 202.106.199.0/24
blacklist-ip 202.181.7.0/24
blacklist-ip 202.98.24.0/24
blacklist-ip 202.99.254.0/24
blacklist-ip 203.161.230.0/24
blacklist-ip 203.199.57.0/24
blacklist-ip 203.98.7.0/24
blacklist-ip 204.155.147.0/24
blacklist-ip 207.12.88.0/24
blacklist-ip 208.109.138.0/24
blacklist-ip 208.56.31.0/24
blacklist-ip 208.69.32.0/24
blacklist-ip 208.69.34.0/24
blacklist-ip 209.145.54.0/24
blacklist-ip 209.220.30.0/24
blacklist-ip 209.36.73.0/24
blacklist-ip 209.85.229.0/24
blacklist-ip 210.242.125.0/24
blacklist-ip 211.136.113.0/24
blacklist-ip 211.137.130.0/24
blacklist-ip 211.138.102.0/24
blacklist-ip 211.138.34.0/24
blacklist-ip 211.138.74.0/24
blacklist-ip 211.139.136.0/24
blacklist-ip 2.1.1.2
blacklist-ip 211.5.133.0/24
blacklist-ip 211.8.69.0/24
blacklist-ip 211.94.66.0/24
blacklist-ip 211.98.70.0/23
blacklist-ip 213.169.251.0/24
blacklist-ip 213.186.33.0/24
blacklist-ip 216.139.213.0/24
blacklist-ip 216.221.188.0/24
blacklist-ip 216.234.179.0/24
blacklist-ip 218.241.116.0/24
blacklist-ip 218.28.144.0/24
blacklist-ip 218.30.64.0/24
blacklist-ip 218.68.250.0/24
blacklist-ip 218.93.250.0/24
blacklist-ip 219.146.13.0/24
blacklist-ip 220.165.8.0/24
blacklist-ip 220.250.64.0/24
blacklist-ip 221.179.46.0/24
blacklist-ip 221.192.153.0/24
blacklist-ip 221.204.244.0/24
blacklist-ip 221.8.69.0/24
blacklist-ip 222.221.5.0/24
blacklist-ip 223.82.248.0/24
blacklist-ip 23.89.5.0/24
blacklist-ip 243.185.187.0/24
blacklist-ip 24.51.184.0
blacklist-ip 249.129.46.0/24
blacklist-ip 253.157.14.0/24
blacklist-ip 255.255.255.255
blacklist-ip 28.121.126.0/24
blacklist-ip 28.13.216.0
blacklist-ip 31.13.0.0/16
blacklist-ip 37.61.54.0/24
blacklist-ip 4.193.80.0
blacklist-ip 42.123.125.0/24
blacklist-ip 4.36.66.0/24
blacklist-ip 46.20.126.0/24
blacklist-ip 46.38.24.0/24
blacklist-ip 46.82.174.0/24
blacklist-ip 49.2.123.0/24
blacklist-ip 54.76.135.0/24
blacklist-ip 58.53.211.0/24
blacklist-ip 59.24.3.0/24
blacklist-ip 60.191.124.0/24
blacklist-ip 60.19.29.0/24
blacklist-ip 61.131.208.0/24
blacklist-ip 61.139.8.0/24
blacklist-ip 61.183.1.0/24
blacklist-ip 61.191.206.0/24
blacklist-ip 61.54.28.0/24
blacklist-ip 64.33.88.0/24
blacklist-ip 4.33.99.0/24
blacklist-ip 64.66.163.0/24
blacklist-ip 65.104.202.0/24
blacklist-ip 65.160.219.0/24
blacklist-ip 65.49.2.0/24
blacklist-ip 66.206.11.0/24
blacklist-ip 66.220.0.0/16
blacklist-ip 66.45.252.0/24
blacklist-ip 67.215.65.0/24
blacklist-ip 67.215.77.0/24
blacklist-ip 72.14.205.0/24
blacklist-ip 74.117.182.0/24
blacklist-ip 74.117.57.0/24
blacklist-ip 74.125.0.0/16
blacklist-ip 77.4.7.0/24
blacklist-ip 78.16.49.0/24
blacklist-ip 8.105.84.0/24
blacklist-ip 8.7.198.0/24
blacklist-ip 89.31.55.0/24
blacklist-ip 92.242.144.0/24
blacklist-ip 93.46.8.0/24
blacklist-ip 95.211.189.0/24
blacklist-ip 208.101.0.0/16
blacklist-ip 74.86.0.0/16
blacklist-ip 69.63.0.0/16
blacklist-ip 75.126.0.0/16
blacklist-ip 199.59.0.0/16
blacklist-ip 67.228.0.0/16
blacklist-ip 88.191.0.0/16
blacklist-ip 199.16.0.0/16
blacklist-ip 172.217.24.0/24
blacklist-ip 172.217.161.0/24
blacklist-ip 88.191.249.0/24
blacklist-ip 103.207.229.0/24
blacklist-ip 120.196.0.0/24
blacklist-ip 211.98.70.0/24
blacklist-ip 101.110.118.0/24
blacklist-ip 113.12.83.0/24
blacklist-ip 125.88.131.0/24
blacklist-ip 120.52.72.0/23
blacklist-ip 69.171.0.0/16
blacklist-ip 67.15.0.0/16
blacklist-ip 173.252.0.0/16
blacklist-ip 174.36.0.0/16
blacklist-ip 174.36.0.0/15
blacklist-ip 205.186.152.0/24
blacklist-ip 208.43.0.0/16
blacklist-ip 64.13.0.0/16
##IPV6
blacklist-ip ::9000:0:0:0/72
blacklist-ip 101::1234
blacklist-ip 10::2222
blacklist-ip 2001:1::1
blacklist-ip 2001:1::2
blacklist-ip 2001::212
blacklist-ip 2001:DA8:112::21AE
blacklist-ip 200:2:253D:369E::
blacklist-ip 200:2:2E52:AE44::
blacklist-ip 200:2:3B18:3AD::
blacklist-ip 200:2:4E10:310F::
blacklist-ip 200:2:5D2E:859::
blacklist-ip 200:2:807:C62D::
blacklist-ip 200:2:9F6A:794B::
blacklist-ip 200:2:CB62:741::
blacklist-ip 200:2:F3B9:BB27::
blacklist-ip 2003:FF:1:2:3:4:5FFF:0/112
blacklist-ip 21:2::2
blacklist-ip 2123::3E12
blacklist-ip 50A7:26E::64:CEEF:0:0

**Comment by rufengsuixing** [comment]
感觉这个列表不错，去掉这里面的本地地址后
如果开了v2ray的域名嗅探
直接将这些ip重定向到v2ray
就不用折腾gfwlist和dns了
相当于被污染的dns服务器主动提供了列表

**Comment by zanzhz1101** [comment]
> 感觉这个列表不错，去掉这里面的本地地址后
> 如果开了v2ray的域名嗅探
> 直接将这些ip重定向到v2ray
> 就不用折腾gfwlist和dns了
> 相当于被污染的dns服务器主动提供了列表

我那个比较精简，ziyuedi的比较全面,但实际上好像wall用的ip并不是一个段，而是有限的200左右条，起码在我这里测试的是这样的

**Comment by Iy204** [comment]
用段的误杀太多了。
比如`blacklist-ip 31.13.0.0/16`
香港Facebook Ins的图片香港CDN`scontent-hkg3-1.cdninstagram.com`

**Comment by smdx** [comment]
不止fb，用段的话win系统的市场也打不开了
