### ISSUE TITLE
最新的是否已经支持配置三个？我也想知道。

### ISSUE THREAD

**Issue by zhaoliang1224** [pymumu/smartdns#912]
> 目前只支持配置两个，是先用第一个，第一个失效才使用第二个。
> 
> 对于明确想忽略某些IP地址，可以使用
> ignore-ip 1.2.3.4/16

您好，想请教一下，现在支持3个检测方式了吗？如果配置了3个，会发生什么问题？比如speed-check-mode tcp:443,tcp:80,ping。如果只能配置2个的话，建议配置哪2个呢？

_Originally posted by @yyysuo in https://github.com/pymumu/smartdns/issues/209#issuecomment-655826750_

**Comment by PikuZheng** [comment]
就我所知测速是先尝试第一个设置，如果不成功再尝试第二个，如果还不成功就放弃。
建议不开启测速。相对来说双栈ip优选可能比测速更有意义。
对于大陆网站，建议使用tcp/443。ping的话部分网站不支持，且由于运营商qos，ping得到的结果可能并不准确。

**Comment by hpcex** [comment]
> > 目前只支持配置两个，是先用第一个，第一个失效才使用第二个。
> > 对于明确想忽略某些IP地址，可以使用
> > ignore-ip 1.2.3.4/16
> 
> 您好，想请教一下，现在支持3个检测方式了吗？如果配置了3个，会发生什么问题？比如speed-check-mode tcp:443,tcp:80,ping。如果只能配置2个的话，建议配置哪2个呢？
> 
> _Originally posted by @yyysuo in [#209 (comment)](https://github.com/pymumu/smartdns/issues/209#issuecomment-655826750)_

建议 443 和 ping

**Comment by PikuZheng** [comment]
最新代码似乎已经支持三个了

**Comment by ZYB14** [comment]
![QQ截图20220705131617](https://user-images.githubusercontent.com/107764315/177254584-c6095dca-f863-410f-bfc2-1f1552a49859.png)
应该已经支持了
