### ISSUE TITLE
Host specific black list

### ISSUE THREAD

**Issue by clustor** [pymumu/smartdns#915]
Is it possible to configure a blacklist based on the host IP address? For example, DNS query for "xyz.com" would return 0.0.0.0 from IP address "X" but all other IPs would return the correct address.

**Comment by PikuZheng** [comment]
not clear what you want. 
query xyz.com, expect get 0.0.0.0?
query xyz.com, expect get cname X?

**Comment by clustor** [comment]
Host with IP address 10.10.10.1 queries xyz.com, gets 0.0.0.0
Host with IP address 10.10.10.2 queries xyz.com, gets 52.8.203.22

**Comment by PikuZheng** [comment]
Like other dns servers, smartdns doesn't care about the downstream origin that initiates dns queries.
Maybe you need two dns servers to handle this, or add a firewall to filter data from specific sources.

**Comment by pymumu** [comment]
Parental controls?

**Comment by clustor** [comment]
I need couple of adblocking sites to be allowed from Android TV for streaming app to work but block from every other device.

**Comment by pymumu** [comment]
Try latest code.

https://pymumu.github.io/smartdns/en/config/client-rule/
