### ISSUE TITLE
某个上游dns服务器延迟过大会拖垮整体的dns查询速度吗？

### ISSUE THREAD

**Issue by z836454898** [pymumu/smartdns#916]
**需求应用场景**
我添加的有些上游dns服务器的延迟高达50ms+的，smart会不会等最慢的dns服务器返回查询结果才结束查询。

**Comment by pymumu** [comment]
影响可以忽略。

**Comment by PikuZheng** [comment]
我觉得有影响，如果开启了测速功能。

**Comment by pymumu** [comment]
有测速相比没有的情况，是有延迟的，这个时延最大600ms。
所以，推荐开启cache和过期缓存功能，避免等待。

但就你的问题来说，某个上游异常，并不会导致查询时间再次变长。
