### ISSUE TITLE
all-best-ip  branch 有什么新特性吗

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#917]
RT

**Comment by pymumu** [comment]
增加了返回所有最优IP的功能，使结果对下载软件，视频类播放软件更加友好。
排在第一的结果仍然是 最快的，保持对浏览器支持最佳。

**Comment by openips** [comment]
master配置完参数不也是一样的效果吗 有什么特殊增强？

**Comment by pymumu** [comment]
无新增配置项，默认是启用的

**Comment by openips** [comment]
好的 编译一个试试 谢谢

**Comment by jasonding121205** [comment]
all-best-ip是否不返回唯一地址了？

**Comment by ZYB14** [comment]
难怪呢
我nslookup返回多个ip地址
我还以为出问题了
