### ISSUE TITLE
能向openwrt仓库推送下最新版吗？

### ISSUE THREAD

**Issue by wyjtm** [pymumu/smartdns#918]
能向openwrt仓库推送下新版吗？
有旧的路由器 静态编译的装不下了 今天去openwrt仓库下的版本装上重启也找不到ui界面  又装回了以前下的旧版

**Comment by pymumu** [comment]
done

**Comment by wyjtm** [comment]
> 完毕

感谢

**Comment by VergilGao** [comment]
> done

请问能向21.02分支也提一下pr吗？
