### ISSUE TITLE
能否编译一个可在n1 小钢炮固件下工作的包

### ISSUE THREAD

**Issue by zanzhz1101** [pymumu/smartdns#92]
n1已经安装debian
root@phicomm-n1:/# cat /etc/issue
Debian GNU/Linux 8 \n \l
root@phicomm-n1:/# uname -a
Linux phicomm-n1 4.9.76 #1 SMP PREEMPT Sun Sep 9 13:25:35 CST 2018 aarch64 GNU/Linux

**Comment by pymumu** [comment]
已经增加支持。
