### ISSUE TITLE
配置行中未正确解析注释“#”

### ISSUE THREAD

**Issue by asbai** [pymumu/smartdns#922]
**问题现象**  
在 smartdns.conf 中的普通配置行内，未能正确解析注释符“#”

**重现步骤**
配置行
````
bind 127.0.0.1:53 -no-speed-check #-no-cache
````
中的 “# -no-cache” 会作为配置参数 `-no-cache` 被识别。在其它几乎所有 Linux Daemon 中，一般这都会被识别为注释。

**Comment by pymumu** [comment]
不支持行内注释，#在smartdns中，对address是有意义的。

**Comment by asbai** [comment]
> 不支持行内注释，#在smartdns中，对address是有意义的。

收到，那是每行首字符？或首个非空字符必须是 # 才算注释？
希望在文档里写一下

**Comment by nidbCN** [comment]
同时也不支持行尾的 `\t` 制表符
