### ISSUE TITLE
希望可以兼容geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by PHCSJC** [pymumu/smartdns#924]
用到的场景：
已经的国内域名走国内DNS解析，已知的国外域名走国外DNS解析，其他未知域名先用国内DNS解析，再对比IP，如果返回的是国内IP直接给客户端，如果是国外IP，再用国外域名解析一次，然后返回给客户端

https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by openips** [comment]
手动分组就可以 这不是smartdns负责的
