### ISSUE TITLE
基于all-best-ip ，alpine打包的容器运行在ikuai上报错/bin/smartdns: line 1: syntax error: unexpected ")" 

### ISSUE THREAD

**Issue by Somalia0932** [pymumu/smartdns#925]
**问题现象**  
基于alpine 镜像使用 all-best-ip 打包docker 容器镜像，在centos7上运行好像没问题，但是在www.ikuai8.com的x86路由的容器中会报错  /bin/smartdns: line 1: syntax error: unexpected ")"  ，基于r36.1打包的镜像运行在centos7 或ikuai路由的容器插件上都没有问题。

**Comment by pymumu** [comment]
已经刷新。

**Comment by Somalia0932** [comment]
> 已经刷新。

大佬威武，已经重新打包并运行起来了。谢谢
