### ISSUE TITLE
openwrt开启passwall之后所有tcping都给劫持到本地了,导致SmartDNS测速不准

### ISSUE THREAD

**Issue by wutongskype** [pymumu/smartdns#929]
具体的请看下面的连接, 我在PW那边也发了个Issues
https://github.com/xiaorouji/openwrt-passwall/issues/1960

之前发那个Issues希望增加个使用socks\http前置代理的功能也是处于这种原因, 
因为采用透明代理和前置网关, 在有些时候就有一些莫名其妙的问题和安全性考虑
https://github.com/pymumu/smartdns/issues/928

**Comment by PikuZheng** [comment]
请问您pw的“路由器自身代理模式”怎么设置的

**Comment by InspoOnU** [comment]
OpenClash可以解决你的问题。可以排除路由器自身代理；也自带TCP并发，替代测速功能。

**Comment by wutongskype** [comment]
> OpenClash可以解决你的问题。可以排除路由器自身代理；也自带TCP并发，替代测速功能。

其实我到希望路由器走自身代理, 对于上面这个问题我发现可能是tcping的问题, 因为只要端口开着它ping过去以后就默认地址可用并返回ping包. 而普通的icmp ping又因为无法走路由器代理通道, 如果国外域名解析出的是被墙的IP(通常这发生在谷狗系网站)它就无法测速了. 其实smartDNS测速这里可以改一下,增加一个选择, 对国内域名IP采用ICMPping或者TCPing, 对于远程解析出来国外那些域名, 最好测速的时候能走代理通道并采用httpPing而不是tcpping(如果tcpping能走代理通道发出去不被劫持,又能绕过墙返回正确的延迟到也可以哈).

**Comment by PikuZheng** [comment]
tcpping就是http的连接阶段。走不走代理取决于openwrt自身的路由选择。
我更倾向smartdns只负责做dns解析，不要参与联网方式问题

**Comment by pymumu** [comment]
测试模式改成ping

**Comment by wutongskype** [comment]
> 测试模式改成ping

opwrt里怎么改成ping 好像默认的tcpping,没找到有地方可以改.

**Comment by PikuZheng** [comment]
> > 测试模式改成ping
> 
> opwrt里怎么改成ping 好像默认的tcpping,没找到有地方可以改.

自定义配置：speed-check-mode ping
或者写到域名规则里去
