### ISSUE TITLE
有没有增加Windows支持的计划

### ISSUE THREAD

**Issue by ziyuedi** [pymumu/smartdns#93]
如题，这样就可以不依赖路由器了。
适配复杂吗？

**Comment by pymumu** [comment]
工具完全是为linux开发的，不支持windows。

如果你要在windows下使用，可能的办法是在windows10下，使用Windows Subsystem for Linux来使用。

**Comment by ziyuedi** [comment]
实测wsl不能用
wsl不支持systemd
log:
``
user@NOTEBOOK:~/smartdns$ sudo ./install -i
install: creating directory '/etc/smartdns'
'src/smartdns' -> '/usr/sbin/smartdns'
'etc/smartdns/smartdns.conf' -> '/etc/smartdns/smartdns.conf'
'etc/default/smartdns' -> '/etc/default/smartdns'
removed '/etc/init.d/smartdns'
'etc/init.d/smartdns' -> '/etc/init.d/smartdns'
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
Failed to connect to bus: No such file or directory
smartdns.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable smartdns
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
Failed to connect to bus: No such file or directory
``

**Comment by pymumu** [comment]
直接解压二进制使用。

**Comment by ziyuedi** [comment]
src/smartdns: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
缺lib

**Comment by pymumu** [comment]
WSL是哪个系统

**Comment by ziyuedi** [comment]
debian
已apt upgrade到最新

**Comment by fonlan** [comment]
我用Ubuntu的WSL可以运行

**Comment by pymumu** [comment]
给一个临时版本吧。

[smartdns.zip](https://github.com/pymumu/smartdns/files/2865169/smartdns.zip)

**Comment by ziyuedi** [comment]
问题已解决，谢谢

**Comment by ziyuedi** [comment]
但是不指定前台运行参数时无法运行
没有日志

**Comment by pymumu** [comment]
在给你刷新一个吧，如果用到prefetch功能的话。下面这个工作正常。
[smartdns.zip](https://github.com/pymumu/smartdns/files/2865874/smartdns.zip)

**Comment by pymumu** [comment]
@ziyuedi @fonlan 
Release 20新增 Windows WSL的支持，可以尝试。
