### ISSUE TITLE
希望主分支能尽早支持ECS

### ISSUE THREAD

**Issue by Xymmh** [pymumu/smartdns#934]
**需求应用场景**
Smartdns在校园网等多出口网络中对CDN IP的优选一直效果不错，对于这种网络，能获取到更多运营商的CDN IP是非常重要的。而目前移动和电信等运营商，对自家DNS做了限制，对于网外用户，几乎无法解析或速度很慢。

所以如果Smartdns支持添加的每个DNS服务器单独指定不同的ECS参数，那么就可以仅使用一家的DNS（例如阿里、dnspod，这些都支持ECS），添加多个，每个写不同的ECS参数（分别电信联通移动教育网），那么就可以实现用最快的DNS解析出不同运营商的地址，从而解析到不同的CDN IP，加上优选，就可以获得无敌的效果。

相比之前的方案（直接添加很多不同的DNS），这个方案有延迟低、自由度高的优点，且校园网非教育网的出口一般都为NAT出口，这种网络遇到支持ECS的DNS一般默认解析到的都是教育网的IP（所以添加很多DNS实际上没有什么用处），所以更加需要自定义ECS参数。

目前all-best-ip分支已经支持ECS，但体验效果极差，原因：
①参数格式严格，稍有错误Smartdns便无法启动，而配置文档里却没有给出格式范围。
②无法独立给每个DNS服务器设置ECS参数，且如果全局设置，不支持ECS的DNS服务器貌似会停止解析。这样的话几乎没有什么用处。
③all-best-ip分支返回的结果乱七八糟，一会只有一个ipv4地址，一会有多个ipv4地址，一会又ipv4和ipv6地址都有，让我误以为Smartdns并未生效，搞得我晕头转向，只想撞墙。

**建议的方案**
在主分支每个DNS服务器的设置中单独加入一个输入ECS参数的地方。

如果SmartDNS实现了以上功能，那么一定会是一个创新的壮举！

**设备信息**
1. 设备信息（CPU，厂家）  
n3710 x64 intel
2. 固件信息
Immortalwrt 21.02

**Comment by pymumu** [comment]
1.给出你的例子
2.那个服务器在配置ecs后不响应
3.次特性如其名，会返回所有最佳ip，不会在只返回一个地址，缓存未命中时，为了查询性能会只返回一个地址，后面缓存命中时会返回所有最佳ip，多ip时，第一个ip仍然是最快

**Comment by Xymmh** [comment]
1.例如文档中给出的示例是
# edns-client-subnet 192.168.1.1/24
# edns-client-subnet [8::8]/56
对于ipv4，我按照格式配置
edns-client-subnet 120.245.24.1/24 可用
而对于ipv6，
首先我按照示例配置
edns-client-subnet [240c:xxxx:xxxx::1]/56
SmartDNS根本无法运行
然后我又尝试了
edns-client-subnet 240c:xxxx:xxxx::1/56
edns-client-subnet 240c:xxxx:xxxx::1
SmartDNS可以运行，但ECS参数并未起效

2.可能是可以起效的，但由于all-best-ip的特性，返回的IP一会只有一个，一会又有多个，我对于哪个DNS起了作用有点混乱

3.我不太喜欢这种机制，因为它很可能导致很长一段时间的查询没有ipv6地址(即使关闭双栈优选)，所以希望主分支能支持ECS

**Comment by pymumu** [comment]
done
