### ISSUE TITLE
debian下怎么对smartdns进行升级

### ISSUE THREAD

**Issue by eeolive** [pymumu/smartdns#935]
**问题现象**  
在debian系统下安装的要怎么升级，需要卸载之前版本在安装新版本还是直接安装新版本，可以给个代码示例吗，对linux系统不是很熟悉

**运行环境**
1. 固件型号  debian

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by hpcex** [comment]
直接替换/usr/sbin/smartdns，然后重启一下smartdns.

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
