### ISSUE TITLE
短时间内随机性断网

### ISSUE THREAD

**Issue by No06** [pymumu/smartdns#936]
**问题现象**  
短时间内随机性断网，基本都在5~20分钟内，之前可能要几小时断一次
尝试升级、重置固件无果，作为上游或重定向无果，全切换Doh & Dot至udp无果，log也看不到致错，进程也无崩溃现象

**运行环境**
1. 固件型号  
OpenWrt R22.5.5 / LuCI Master (git-22.121.65028-2a5da72)

2. 运营商  
中国移动

**重现步骤**
1. 上游DNS配置。  

119.29.29.29
1.2.4.8
114.114.114.114
dns.alidns.com
https://1.0.0.1/dns-query
dns.google
208.67.222.222

2. 访问的域名。  
不定

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
[smartdns.log](https://github.com/pymumu/smartdns/files/8701365/smartdns.log)

2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by PikuZheng** [comment]
看日志像是有两个独立的问题。一是设备本身断网，二是smartdns作为dnsmasq的上游。
建议不要这么用，smartdns作为dnsmasq的上游会出现奇怪的问题

**Comment by aNoo6** [comment]
> 看日志像是有两个独立的问题。一是设备本身断网，二是smartdns作为dnsmasq的上游。 建议不要这么用，smartdns作为dnsmasq的上游会出现奇怪的问题

日志我忘记清了，断网那是当时我在做调试，我后面是用的重定向，我晚点再传一次完整的log

**Comment by PikuZheng** [comment]
> 断网的现象也比较奇怪，玩游戏的时候瞬间中断，但又没断，人不受控制，但是这时如果受攻击还能接受反馈，包括挂的语音也能听到声，但我没法发话，接着过几秒语音和游戏才会完全断开

游戏是因为有预测机制，然后彻底网断后会回滚进度。
另一方面dns断不会导致游戏断，由于缓存

**Comment by aNoo6** [comment]
> 

所以我一开始发现断网的时候并不是去排查dns，而是在各种调试之后得出的，只要没开smartdns就不会出现，包括开adg或者pdnsd

**Comment by aNoo6** [comment]
> > 断网的现象也比较奇怪，玩游戏的时候瞬间中断，但又没断，人不受控制，但是这时如果受攻击还能接受反馈，包括挂的语音也能听到声，但我没法发话，接着过几秒语音和游戏才会完全断开
> 
> 游戏是因为有预测机制，然后彻底网断后会回滚进度。 另一方面dns断不会导致游戏断，由于缓存

所以我一开始发现断网的时候并不是去排查dns，而是在各种调试之后得出的，只要没开smartdns就不会出现，包括开adg或者pdnsd

**Comment by aNoo6** [comment]
很不能理解为什么会因为smartdns导致，这份log在将近43分的时候断网
[smartdns.log](https://github.com/pymumu/smartdns/files/8705247/smartdns.log)

**Comment by rampageX** [comment]
最近在 N1 旁路机器上用 SmartDNS 做解析，OW 居然也不定时断线，我得试试关掉是否是这个原因...

**Comment by PikuZheng** [comment]
> 很不能理解为什么会因为smartdns导致，这份log在将近44分的时候断网 [smartdns.log](https://github.com/pymumu/smartdns/files/8705247/smartdns.log)

怀疑tcp半连接导致并发连接数满了，关闭tcp测速试试。另外icmp似乎前端有防火墙阻挡了

**Comment by pymumu** [comment]
出问题的时候，用dig，nslookup查询下域名看看是否工作。
还有可以在配置中指定address /openwrt.lan/[路由IP]看看，以及增加force-qtype-SOA 65

**Comment by aNoo6** [comment]
> > 很不能理解为什么会因为smartdns导致，这份log在将近44分的时候断网 [smartdns.log](https://github.com/pymumu/smartdns/files/8705247/smartdns.log)
> 
> 怀疑tcp半连接导致并发连接数满了，关闭tcp测速试试。另外icmp似乎前端有防火墙阻挡了

关闭tcp测速还是不行

**Comment by aNoo6** [comment]
不过这次我在看log的时候看了差不多有5分钟左右网从断开中自己恢复了

**Comment by pymumu** [comment]
看log，没有看到特别的异常情况，只有
1. ping功能无法工作。
2. TYPE65的查询记录。这个可以关闭。
3. openwrt.lan的地址请求。

3可能是问题，但不应该影响网络通断。

下次出问题的时候，看看
1. 域名查询，ping功能是否正常。
2. 出问题时在windows下执行ping www.baidu.com看是否正常。

**Comment by aNoo6** [comment]
> 

ping功能不正常，我刚刚用路由器试着ping了1.1.1.1不通
还会自己恢复
![屏幕截图 2022-05-17 212225](https://user-images.githubusercontent.com/72285529/168821005-6873afd2-c9e6-400a-9d80-49d2a46a7c19.png)
了

**Comment by aNoo6** [comment]
恢复刚好是20分钟，这是为什么

**Comment by aNoo6** [comment]
系统日志出现这一段
Tue May 17 21:24:12 2022 daemon.notice netifd: AP (21904): udhcpc: sending renew to server 10.248.0.1
Tue May 17 21:24:12 2022 daemon.notice netifd: AP (21904): udhcpc: lease of 10.240.141.129 obtained from 10.248.0.1, lease time 1800

**Comment by PikuZheng** [comment]
> 3\. openwrt.lan的地址请求

查询 openwrt.lan 是因为使用nslookup命令时，须先查询dns服务器的名称。这个不影响。

> 2\. 运营商
>     中国移动

看到移动我突然想起来。您如果把移动猫改桥接了，可能会出现不时断网的问题（一般晚上9点到11点比较严重）。请问openwrt是主要路由器吗？上层是否还有其他路由器（比如ros）

**Comment by aNoo6** [comment]
> > 3. openwrt.lan的地址请求
> 
> 查询 openwrt.lan 是因为使用nslookup命令时，须先查询dns服务器的名称。这个不影响。
> 
> > 2. 运营商
> > 中国移动
> 
> 看到移动我突然想起来。您如果把移动猫改桥接了，可能会出现不时断网的问题（一般晚上9点到11点比较严重）。请问openwrt是主要路由器吗？上层是否还有其他路由器（比如ros）

主路由，我这里是校园网

**Comment by PikuZheng** [comment]
> 在恢复的时候看到系统日志有租约到期的消息，网络恢复会不会跟这有关 

目前还是感觉网络在上层被阻断，并发连接在一段时间内超过一定数量（也可能是同时计算tcp和icmp连接数量）触发的。
有没有试过关闭测速？另外在断网和恢复时，ping网关（10.248.0.1）是否可以通？ping内网其他设备（比如隔壁的电脑）是否可以通？

**Comment by pymumu** [comment]
ping 国内ip

**Comment by aNoo6** [comment]
> ping 国内ip
一样不行


> > 在恢复的时候看到系统日志有租约到期的消息，网络恢复会不会跟这有关
> 
> 目前还是感觉网络在上层被阻断，并发连接在一段时间内超过一定数量（也可能是同时计算tcp和icmp连接数量）触发的。 有没有试过关闭测速？另外在断网和恢复时，ping网关（10.248.0.1）是否可以通？ping内网其他设备（比如隔壁的电脑）是否可以通？

网关也不通，可能确实是让上层掐了

**Comment by aNoo6** [comment]
> > > 在恢复的时候看到系统日志有租约到期的消息，网络恢复会不会跟这有关
> > 
> > 
> > 目前还是感觉网络在上层被阻断，并发连接在一段时间内超过一定数量（也可能是同时计算tcp和icmp连接数量）触发的。 有没有试过关闭测速？另外在断网和恢复时，ping网关（10.248.0.1）是否可以通？ping内网其他设备（比如隔壁的电脑）是否可以通？
> 
> 网关也不通，可能确实是让上层掐了

有没有可能是某个网络服务程序崩溃造成的

**Comment by PikuZheng** [comment]
> 有没有可能是某个网络服务程序崩溃造成的

服务崩溃和恢复会产生系统日志，严重的话甚至从pc连不上路由器了

**Comment by frankilla1987** [comment]
> 看日志像是有两个独立的问题。一是设备本身断网，二是smartdns作为dnsmasq的上游。 建议不要这么用，smartdns作为dnsmasq的上游会出现奇怪的问题

哈？不要作为上游？是选择重定向到smartdns吗？

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
