### ISSUE TITLE
AC68U无法安装成功，安装过程参看log

### ISSUE THREAD

**Issue by dongyaosen** [pymumu/smartdns#94]
**问题现象**  
AC68U无法安装成功

**运行环境**
1. 固件型号  
RT-AC68U
当前版本 : 3.0.0.4.384_45149-g467037b
2. 运营商  
电信

admin@RT-AC68U:/tmp/mnt/sda1/Download2# ipkg install smartdns.1.2019.01.26-0014.mipsel.ipk 
Clearing state_want and state_flag for pkg=smartdns (arch_priority=0 flag=16 want=2)
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package smartdns.
Check the spelling or perhaps run 'ipkg update'
admin@RT-AC68U:/tmp/mnt/sda1/Download2# ipkg update
Downloading http://ipkg.nslu2-linux.org/feeds/optware/mbwe-bluering/cross/stable/Packages.gz
Inflating http://ipkg.nslu2-linux.org/feeds/optware/mbwe-bluering/cross/stable/Packages.gz
Updated list of available packages in /opt/lib/ipkg/lists/optware.mbwe-bluering
Downloading http://nw-dlcdnet.asus.com/asusware/arm/stable/Packages.gz
Inflating http://nw-dlcdnet.asus.com/asusware/arm/stable/Packages.gz
Updated list of available packages in /opt/lib/ipkg/lists/optware.asus
Successfully terminated.
admin@RT-AC68U:/tmp/mnt/sda1/Download2# ipkg install smartdns.1.2019.01.26-0014.mipsel.ipk 
Clearing state_want and state_flag for pkg=smartdns (arch_priority=0 flag=16 want=2)
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package smartdns.
Check the spelling or perhaps run 'ipkg update'
admin@RT-AC68U:/tmp/mnt/sda1/Download2# nslookup -querytype=ptr 0.0.0.0
BusyBox v1.17.4 (2018-11-26 15:10:49 CST) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server

admin@RT-AC68U:/tmp/mnt/sda1/Download2# ipkg install smartdns.1.2019.01.07-2334.mipsbig.ipk
Clearing state_want and state_flag for pkg=smartdns (arch_priority=0 flag=16 want=2)
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package smartdns.
Check the spelling or perhaps run 'ipkg update'
admin@RT-AC68U:/tmp/mnt/sda1/Download2# ipkg install smartdns.1.2019.01.07-2334.arm.ipk
Installing smartdns (1.2019.01.07-2334) to /opt/...
Configuring smartdns
Successfully terminated.
admin@RT-AC68U:/tmp/mnt/sda1/Download2# 
admin@RT-AC68U:/tmp/mnt/sda1/Download2# 
admin@RT-AC68U:/tmp/mnt/sda1/Download2# nslookup -querytype=ptr 0.0.0.0
BusyBox v1.17.4 (2018-11-26 15:10:49 CST) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server

admin@RT-AC68U:/tmp/mnt/sda1/Download2# Connection closing...Socket close.
admin@RT-AC68U:/tmp/home/root# nslookup -querytype=ptr 0.0.0.0
BusyBox v1.17.4 (2018-11-26 15:10:49 CST) multi-call binary.

Usage: nslookup [HOST] [SERVER]

Query the nameserver for the IP address of the given HOST
optionally using a specified DNS server

admin@RT-AC68U:/tmp/home/root# ps
  PID USER       VSZ STAT COMMAND
    1 admin     5464 S    /sbin/preinit
    2 admin        0 SW   [kthreadd]
    3 admin        0 SW   [ksoftirqd/0]
    4 admin        0 SW   [kworker/0:0]
    5 admin        0 SW   [kworker/u:0]
    6 admin        0 SW   [migration/0]
    7 admin        0 SW   [migration/1]
    8 admin        0 SW   [kworker/1:0]
    9 admin        0 SW   [ksoftirqd/1]
   10 admin        0 SW<  [khelper]
   11 admin        0 SW   [sync_supers]
   12 admin        0 SW   [bdi-default]
   13 admin        0 SW<  [kblockd]
   14 admin        0 SW   [kswapd0]
   15 admin        0 SW   [fsnotify_mark]
   16 admin        0 SW<  [crypto]
   24 admin        0 SW   [mtdblock0]
   25 admin        0 SW   [mtdblock1]
   26 admin        0 SW   [mtdblock2]
   27 admin        0 SW   [mtdblock3]
   28 admin        0 SW   [kworker/u:1]
   35 admin        0 SW   [kworker/0:1]
   36 admin        0 SW   [kworker/1:1]
   37 admin        0 SW   [mtdblock4]
   38 admin        0 SW   [mtdblock5]
   40 admin      664 S    hotplug2 --persistent --no-coldplug
   87 admin     5452 S    console
   93 admin        0 SWN  [jffs2_gcd_mtd4]
  101 admin     1532 S    /sbin/syslogd -m 0 -S -O /tmp/syslog.log -s 256 -l 6
  103 admin     1532 S    /sbin/klogd -c 5
  181 admin     5460 S    /sbin/wanduck
  186 admin     5080 S    nt_monitor
  187 admin     2044 S    protect_srv
  191 admin     2044 S    protect_srv
  192 admin     2044 S    protect_srv
  193 admin     1096 S    dropbear -p 192.168.50.254:22 -a
  195 admin     5080 S    nt_monitor
  196 admin     5080 S    nt_monitor
  198 admin     5228 S    nt_center
  201 admin     5228 S    nt_center
  202 admin     5228 S    nt_center
  203 admin     1244 S    /bin/eapd
  205 admin     5456 S    wpsaide
  206 admin     2052 S    /usr/sbin/wlc_nt
  209 admin     1812 S    nas
  216 admin     2172 S    /usr/sbin/wlceventd
  217 admin     5080 S    nt_monitor
  219 admin     1608 S    nt_actMail
  220 admin     1608 S    nt_actMail
  221 admin     1608 S    nt_actMail
  223 admin     1420 S    /usr/sbin/acsd
  226 nobody    1088 S    dnsmasq --log-async
  227 admin     1080 S    dnsmasq --log-async
  234 admin     1544 S    crond
  237 admin     5324 S    httpds -s -i br0 -p 8443
  238 admin     5592 S    httpd -i br0
  239 admin     1216 S    /usr/sbin/infosvr br0
  241 admin     1212 S    sysstate
  242 admin     5456 S    watchdog
  247 admin     2800 S    rstats
  260 admin     1536 S    avahi-daemon: running [RT-AC68U-2338.local]
  263 admin     6380 S    networkmap --bootwait
  265 admin     1256 S    lld2d br0
  267 admin     5096 S    mastiff
  268 admin     5456 S    bwdpi_check
  275 admin     5480 S    roamast
  303 admin     1488 S    lldpd -L /usr/sbin/lldpcli -I vlan1,eth1,eth2,wds0.*,wds1.*,wds2.* -s RT-AC68U
  307 nobody    1460 S    lldpd -L /usr/sbin/lldpcli -I vlan1,eth1,eth2,wds0.*,wds1.*,wds2.* -s RT-AC68U
  309 admin     3948 S    cfg_server
  324 admin     5480 S    amas_lib
  337 admin        0 SW   [khubd]
  341 admin        0 SW   [flush-mtd-unmap]
  349 admin     5480 S    roamast
  353 admin     5480 S    roamast
  379 admin     5096 S    mastiff
  380 admin     5096 S    mastiff
  381 admin     5096 S    mastiff
  383 admin     1392 S    /usr/sbin/pppd file /tmp/ppp/options.wan0
  393 admin     1548 S    /sbin/udhcpc -i vlan2 -p /var/run/udhcpc0.pid -s /tmp/udhcpc -O33 -O249
  437 admin        0 SW   [scsi_eh_0]
  438 admin        0 SW   [usb-storage]
  474 admin     3948 S    cfg_server
  475 admin     3948 S    cfg_server
  504 admin      688 S    hotplug2 --persistent --no-coldplug
  506 admin     5456 S    /sbin/asus_sd sda1 add
  543 admin     5456 S    usbled
  544 admin     2412 S    u2ec
  546 admin     1284 S    lpd br0
  552 admin     2412 S    u2ec
  553 admin     2412 S    u2ec
  557 admin     5480 S    amas_lib
  573 admin     5520 D    hotplug block
  641 admin        0 DW   [flush-8:0]
  674 admin     5456 S    ntp
  738 admin     5456 S    disk_monitor
  785 admin        0 DW   [tntfsiupdated]
 1148 admin     9024 S    aaews --sdk_log_dir=/tmp
 1194 admin     1164 R    dropbear -p 192.168.50.254:22 -a
 1217 admin     5256 S    ./asus_lighttpd -Df /opt/etc/asus_lighttpd.conf
 1662 admin     9024 S    aaews --sdk_log_dir=/tmp
 1663 admin     9024 S    aaews --sdk_log_dir=/tmp
 1689 admin     1548 S    -sh
 1730 admin     9024 S    aaews --sdk_log_dir=/tmp
 1731 admin     9024 S    aaews --sdk_log_dir=/tmp
 1732 admin     9024 S    aaews --sdk_log_dir=/tmp
 1733 admin     9024 S    aaews --sdk_log_dir=/tmp
 2043 admin     2852 S    wred -B
 2045 admin     1788 S    dcd -i 3600 -p 43200 -b -d /tmp/bwdpi/
 2046 admin     1788 S    dcd -i 3600 -p 43200 -b -d /tmp/bwdpi/
 2047 admin     1788 S    dcd -i 3600 -p 43200 -b -d /tmp/bwdpi/
 2049 admin     1788 S    dcd -i 3600 -p 43200 -b -d /tmp/bwdpi/
 2050 admin     1788 S    dcd -i 3600 -p 43200 -b -d /tmp/bwdpi/
 2051 admin     1788 S    dcd -i 3600 -p 43200 -b -d /tmp/bwdpi/
 2052 admin     2852 S    wred -B
 2053 admin     2852 S    wred -B
 2077 admin     2852 S    wred -B
 2078 admin     2852 S    wred -B
 2079 admin     2852 S    wred -B
 2080 admin     2852 S    wred -B
 2081 admin     2852 S    wred -B
 2082 admin     2852 S    wred -B
 2083 admin     2852 S    wred -B
 2084 admin     2852 S    wred -B
 2109 admin     5456 S    bwdpi_wred_alive
 2157 admin        0 Z N  [dm2_snarfmaster]
 2158 admin        0 Z N  [dm2_transmissio]
 2169 admin        0 Z    [getrealip.sh]
 2175 admin     5456 S    pc_block
 2177 admin     5480 S    amas_lib
 2182 admin        0 Z N  [dm2_amuled]
 2184 admin        0 Z N  [dm2_amuled]
 2187 admin        0 Z N  [dm2_amuled]
 2188 admin        0 Z N  [dm2_nzbget]
 2194 admin        0 Z N  [dm2_transmissio]
 2197 admin        0 Z N  [dm2_transmissio]
 2198 admin        0 Z N  [dm2_transmissio]
 2199 admin        0 Z N  [dm2_transmissio]
 2245 admin     9024 S    aaews --sdk_log_dir=/tmp
 2670 admin     1536 R    ps
 2672 admin     1532 S    sh -c nvram get ehci_ports
admin@RT-AC68U:/tmp/mnt/sda1/asusware.arm/etc/downloadmaster/downloadmaster# /opt/usr/sbin/smartdns -h
Program uses unsupported TLS data!

**Comment by pymumu** [comment]
要装arm那个

**Comment by dongyaosen** [comment]
> 要装arm那个


华硕原生固件(optware) | smartdns.xxxxxxx.mipsel.ipk | 支持MIPS小端架构的系统，如RT-AC68U
不是说要装这个嘛？

**Comment by pymumu** [comment]
资料写的不正确，已经更新，你这个应该是arm的。
