### ISSUE TITLE
NETGEAR R6300V2 openwrt固件刷入smartdns出错

### ISSUE THREAD

**Issue by wkingnet** [pymumu/smartdns#940]
**问题现象**  
我有一个r6300v2，目前是openwrt固件，刷入smartdns.1.2022.04.05-2046.arm-openwrt-all.ipk失败。虽然R6300V2可以刷梅林固件，但是我看readme里，梅林固件需要配合U盘使用，而openwrt固件不需要，所以想用openwrt固件。

**运行环境**
1. 固件型号  
网件NETGEAR r6300v2 路由器 charter美版
Hostname | OpenWrt
Model | Netgear R6300 V2 (BCM4708)
Architecture | ARMv7 Processor rev 0 (v7l)
Target Platform | bcm53xx/generic
Firmware Version | OpenWrt 21.02.3 r16554-1d4dea6d4f / LuCI openwrt-21.02 branch git-22.083.69138-0a0ce2a
Kernel Version | 5.4.188

**重现步骤**
```
#将smartdns.1.2022.04.05-2046.arm-openwrt-all.ipk改名为smartdns.ipk
/root$ opkg install smartdns.ipk
Unknown package 'smartdns'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libopenssl for smartdns
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package smartdns.
```

**信息收集**  
```
/root$ opkg print_architecture
arch all 1
arch noarch 1
arch arm_cortex-a9 10
```

**Comment by PikuZheng** [comment]
>cannot find dependency libopenssl for smartdns

请先更新opkg库

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
