### ISSUE TITLE
旁路由上用127.0.0.1：端口查询失效

### ISSUE THREAD

**Issue by kob** [pymumu/smartdns#941]
**问题现象**  
旁路由上用127.0.0.1：端口查询失效，用lanip:端口查询正常
`root@OpenWrt:/etc# nslookup www.qq.com 127.0.0.1:6053
;; connection timed out; no servers could be reached

root@OpenWrt:/etc# nslookup www.qq.com 192.168.6.254:6053
Server:         192.168.6.254:6053
Address:        192.168.6.254:6053

Non-authoritative answer:
www.qq.com      canonical name = e6156.dscf.akamaiedge.net
Name:   e6156.dscf.akamaiedge.net
Address: 23.56.24.92

Non-authoritative answer:
www.qq.com      canonical name = e6156.dscf.akamaiedge.net
Name:   e6156.dscf.akamaiedge.net
Address: 2600:1406:3a00:496::180c
`

**运行环境**
1. 固件型号  
OpenWrt R22.3.13
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
114.114.114.114
8.8.8.8
2. 访问的域名。  
www.qq.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
[2022-05-19 19:21:15,569][ERROR][      fast_ping.c:460 ] sendto 2402:4e00:1020:1404:0:9227:71ab:2b74, id 33, Permission denied
[2022-05-19 19:27:34,302][ERROR][      fast_ping.c:460 ] sendto 2001::43e6:a9b6, id 60, Permission denied
[2022-05-19 19:57:38,952][ERROR][      fast_ping.c:460 ] sendto 2402:4e00:1020:1404:0:9227:71a3:83d2, id 3, Permission denied

3. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by pymumu** [comment]
打开debug日志看看吧。

**Comment by PikuZheng** [comment]
看起来是iptables或nftables对smartdns做了端口重定向。建议不要这么用。

**Comment by PikuZheng** [comment]
#695

**Comment by kob** [comment]
> 打开debug日志看看吧。
> 
> 还有就是发一下配置，看看绑定的地址是否是 0.0.0.0

绑定地址确定是0.0.0.0
tcp        0      0 0.0.0.0:6053            0.0.0.0:*               LISTEN      13193/smartdns
udp        0      0 0.0.0.0:6053            0.0.0.0:*                           13193/smartdn

两个同样得固件，在另一个旁路上却没问题
root@OpenWrt:~# nslookup www.qq.com 127.0.0.1:6053
Server:         127.0.0.1:6053
Address:        127.0.0.1:6053

Non-authoritative answer:
www.qq.com      canonical name = ins-r23tsuuf.ias.tencent-cloud.net
Name:   ins-r23tsuuf.ias.tencent-cloud.net
Address: 121.14.77.201

Non-authoritative answer:
www.qq.com      canonical name = ins-r23tsuuf.ias.tencent-cloud.net
Name:   ins-r23tsuuf.ias.tencent-cloud.net
Address: 2402:4e00:1020:1404:0:9227:71ab:2b74

**Comment by pymumu** [comment]
最新版本验证，有问题reopen issue
