### ISSUE TITLE
Master 测速失效

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#942]
master版本号 dbfe9063e48d793ff78e77eb13f3ac49a6af7b7b
固件为openwrt master x64

测速参数speed-check-mode tcp:443,tcp:80
实际使用中返回一列IP并非之前版本的一个最优IP 感觉是测速参数为生效
请调查一下

**Comment by PikuZheng** [comment]
1. 已知passwall会对测速做抢答，请检查设备自身路由问题；
2. 目前新版会返回“包含测速最快的结果”的完整结果。也就是说，如果测速返回两个ip，其中一个很快另一个很慢，还是会同时返回两个ip，具体连接哪个取决于终端设备。

**Comment by openips** [comment]
@PikuZheng 不是用的passwall 用的clash 同样的系统和配置 smartdns_master 出现一列IP smartdns_1.2022.2046 一切正常

**Comment by openips** [comment]
重启后不启动clash 问题依旧 所以才提bug

**Comment by openips** [comment]
> 1. 已知passwall会对测速做抢答，请检查设备自身路由问题；
> 2. 目前新版会返回“包含测速最快的结果”的完整结果。也就是说，如果测速返回两个ip，其中一个很快另一个很慢，还是会同时返回两个ip，具体连接哪个取决于终端设备。

第二点 会造成终端设备无法连接最快的IP 这样的设计会造成测速失效 无法返回终端最快ip 就没必要测速了 不知道为什么会改成 这是我发现的bug

**Comment by pymumu** [comment]
设计就是这样，后续版本会返回一组优选IP，排在第一的仍然是最快，其他地址相比10%的时间差。
这样设计的目的是对下载软件，视频播放软件更加友好。
具体可以用ping测试下返回的地址速度是否相同。

**Comment by openips** [comment]
考虑过多运营商分流的情况吗 这么做域名没变 目的IP会变 不如之前测速后给个唯一的IP

**Comment by openips** [comment]
加个参数吧 控制返回测速后IP数量

**Comment by pymumu** [comment]
给一下具体分流的方案，看看如何避免配置参数。

**Comment by PikuZheng** [comment]
> @PikuZheng 不是用的passwall 用的clash 同样的系统和配置 smartdns_master 出现一列IP smartdns_1.2022.2046 一切正常

clash也有同样问题，看看自身如何代理的

**Comment by openips** [comment]
> 给一下具体分流的方案，看看如何避免配置参数。

一般企业应用都会采用多运营商线路，为了避免域名访问web导致运营商绕道问题 解决方法为：
1、ipset中配置各运营商IP地址库别名
2、mwan3对运营商ip段指定wan口分流
3、采用smartdns配置各运营商dns 测速后筛选出速度最快的唯一IP 返回给客户端访问
以上措施可以解决客户端由于域名对应多运营商IP  导致从不同wan口IP访问域名的问题

目前改成返回最优的一列IP后 无法保证返回的一列IP同属于同一运营商 还会导致多wan口IP访问同一域名的问题

**Comment by openips** [comment]
> > @PikuZheng 不是用的passwall 用的clash 同样的系统和配置 smartdns_master 出现一列IP smartdns_1.2022.2046 一切正常
> 
> clash也有同样问题，看看自身如何代理的

这是all_best_ip 后引入的新特性 和其他软件无关了

**Comment by pymumu** [comment]
我理解分流应该是使用ipset功能，某些域名用那个出口。
smartdns在设置ipset时，无论单IP，还是多IP，都会将这些ip地址设置到对应的ipset中。
那客户端无论使用这些IP的哪一个，都会走对应ipset设置的规则。

这个地方没有理解你说的。如果你说的成立，那在没有smartdns的单IP机制前，不同运营商分流是怎么做的？

还有一点要说明一下：
即使返回多个IP地址给客户端，客户端也是优选使用第一个IP地址的，并不会使用其他地址。除非第一个地址无法访问。
视频类软件，下载软件才会解析多IP地址使用。

**Comment by Xymmh** [comment]
一个网站不止一个域名，无论是返回一个IP还是返回一组IP，都没法保证连接一个网站用的是同一个运营商。
![图片](https://user-images.githubusercontent.com/45114927/169634120-5060f657-cf81-4be1-a761-698a475e3211.png)
如果你说的是那种按访问主站域名判断你IP的网站，SmartDNS每次返回的结果也不太可能始终相同的，除非你多个运营商网络质量的差距特别大。

**Comment by openips** [comment]
> 

smartdns测速后会缓存域名对应响应最快的IP 缓存过期之前 返回个客户端的就是同样的IP 同一IP不会属于两家运营商 所以就可以保证客户端始终通过同一运营商的网络访问网址

**Comment by openips** [comment]
> 我理解分流应该是使用ipset功能，某些域名用那个出口。 smartdns在设置ipset时，无论单IP，还是多IP，都会将这些ip地址设置到对应的ipset中。 那客户端无论使用这些IP的哪一个，都会走对应ipset设置的规则。
> 
> 这个地方没有理解你说的。如果你说的成立，那在没有smartdns的单IP机制前，不同运营商分流是怎么做的？
> 
> 加开关很简单，但要看开关加的是否合理和有必要。所以烦请细化描述一下分流的机制。
> 
> 还有一点要说明一下： 即使返回多个IP地址给客户端，客户端也是优选使用第一个IP地址的，并不会使用其他地址。除非第一个地址无法访问。 视频类软件，下载软件才会解析多IP地址使用。

1、多个IP无法保证都同属于同一家运营商 不同运营商的目的IP就会通过不同的ipset 分配到不同的wan口进行通讯
2、在smartdns的单IP机制前，不同运营商web分流有两种
    A 强制内网IP走固定wan端口,很不灵活
    B 增加tcp 80 443端口的wan端口地址粘滞，保证来自相同源内网 IP 的流量，匹配规则后并且在粘滞超时时间内，将会使用相同的 wan 接口通讯，也可以解决，但是会增加路由器本身负载

另外 即使返回多个IP地址给客户端，客户端也是优选使用第一个IP地址的，并不会使用其他地址。除非第一个地址无法访问。
视频类软件，下载软件才会解析多IP地址使用。

smartdns的测速优选过程，本身就可以提供优选后可访问的IP给客户端，何必再让客户端自己选择目的IP
视频类软件 对多IP需求不大 下载软件确实多IP会有效果

总之各有各的好 加个参数开关最好 谢谢

**Comment by openips** [comment]
> 一个网站不止一个域名，无论是返回一个IP还是返回一组IP，都没法保证连接一个网站用的是同一个运营商。 ![图片](https://user-images.githubusercontent.com/45114927/169634120-5060f657-cf81-4be1-a761-698a475e3211.png) 如果你说的是那种按访问主站域名判断你IP的网站，SmartDNS每次返回的结果也不太可能始终相同的，除非你多个运营商网络质量的差距特别大。

smartdns测速后会缓存域名对应响应最快的IP 缓存过期之前 返回个客户端的就是同样的IP 同一IP不会属于两家运营商 所以就可以保证客户端始终通过同一运营商的网络访问网址

**Comment by pymumu** [comment]
那是不是可以认为，只要是同一个网段，比如C类地址的，就没有问题？

比如www.baidu.com的两个地址？都是C类地址。

**Comment by openips** [comment]
> 那是不是可以认为，只要是同一个网段，比如C类地址的，就没有问题？
> 
> 比如www.baidu.com的两个地址？都是C类地址。

一般来说同一个C属于同一个运营商 所以没问题

**Comment by pymumu** [comment]
最新代码，增加配置参数，设置返回IP个数
···
max-reply-ip-num
···

**Comment by openips** [comment]
好的 编译试一下 等会反馈 谢啦

**Comment by PikuZheng** [comment]
我理解了。all_best_ip设计初衷是由于测速过滤后返回单个最快ip，丢失了部分（扩展）信息；另一方面对于多线程类的软件，返回一组ip更有利于并发和负载均衡。
对于一组ip，终端每次是选择第一个去连接，连不上才会去选择第二个。但是dns有轮询机制，第一次查询的第二个ip，会上浮到第二次查询的第一个ip。
但是吧。的确有个别的网站，会同时给出两个相距甚远的IP。只能说这种网站是压根就没有考虑过要做优化。对于大牌CDN应该不存在这个问题。

对于本地多线接入来说，1. 理论上发起查询时走的线路，即应由上游返回对应线路的最优IP（段）；2. 测速时的路由，应与客户端实际访问路由一致。我认为这个过程应该在测速前即应确定不变，而不是测速后加入到ipset后决定；3. 国内各大运营商在省出口已经达到互通并取消了人为网间限制，根据目标ip区分出口线路并无明显优势。

**Comment by openips** [comment]
> 



> 我理解了。all_best_ip设计初衷是由于测速过滤后返回单个最快ip，丢失了部分（扩展）信息；另一方面对于多线程类的软件，返回一组ip更有利于并发和负载均衡。 对于一组ip，终端每次是选择第一个去连接，连不上才会去选择第二个。但是dns有轮询机制，第一次查询的第二个ip，会上浮到第二次查询的第一个ip。 但是吧。的确有个别的网站，会同时给出两个相距甚远的IP。只能说这种网站是压根就没有考虑过要做优化。对于大牌CDN应该不存在这个问题。
> 
> 对于本地多线接入来说，1. 理论上发起查询时走的线路，即应由上游返回对应线路的最优IP（段）；2. 测速时的路由，应与客户端实际访问路由一致。我认为这个过程应该在测速前即应确定不变，而不是测速后加入到ipset后决定；3. 国内各大运营商在省出口已经达到互通并取消了人为网间限制，根据目标ip区分出口线路并无明显优势。



> 我理解了。all_best_ip设计初衷是由于测速过滤后返回单个最快ip，丢失了部分（扩展）信息；另一方面对于多线程类的软件，返回一组ip更有利于并发和负载均衡。 对于一组ip，终端每次是选择第一个去连接，连不上才会去选择第二个。但是dns有轮询机制，第一次查询的第二个ip，会上浮到第二次查询的第一个ip。 但是吧。的确有个别的网站，会同时给出两个相距甚远的IP。只能说这种网站是压根就没有考虑过要做优化。对于大牌CDN应该不存在这个问题。
> 
> 对于本地多线接入来说，1. 理论上发起查询时走的线路，即应由上游返回对应线路的最优IP（段）；2. 测速时的路由，应与客户端实际访问路由一致。我认为这个过程应该在测速前即应确定不变，而不是测速后加入到ipset后决定；3. 国内各大运营商在省出口已经达到互通并取消了人为网间限制，根据目标ip区分出口线路并无明显优势。

1、运营商的省级透传或者机房bgp肯定有效果 但是有带宽限制 效率方面肯定同一运营商内部网络更高一些
2、由于smartdns可以设置多运营商dns 发起查询时走的线路 与运营商dns IP有关系 正确设置ipset的前提下 肯定不会跨运营商网络进行域名解析
3、解析的结果IP测速后 根据多wan线路质量或者繁忙程度 结果会产生变化 可以做到基于dns的内网流量均衡 避免产生有的线路撑死 有的线路饿死的情况 
4、至于给出两个距离甚远的IP 这个情况可能少见 但是给出不同运营商的IP应该是常见情况 大厂CDN确实好一些 但是目前人人pcdn的情况下 结果不是很乐观
5、亲测过 www.189.cn 联通IP线路优于电信线路 导致都是通过联通线路访问该网址

**Comment by PikuZheng** [comment]
> 1、运营商的省级透传或者机房bgp肯定有效果 但是有带宽限制 效率方面肯定同一运营商内部网络更高一些 

赞同 我觉得和以前相比 现在的情况已经好太多了

>2、由于smartdns可以设置多运营商dns 发起查询时走的线路 与运营商dns IP有关系 正确设置ipset的前提下 肯定不会跨运营商网络进行域名解析 3、解析的结果IP测速后 根据多wan线路质量或者繁忙程度 结果会产生变化 可以做到基于dns的内网流量均衡 避免产生有的线路撑死 有的线路饿死的情况

我的错。我从没想过在国内使用运营商dns（由于劫持等问题

 >4、至于给出两个距离甚远的IP 这个情况可能少见 但是给出不同运营商的IP应该是常见情况 大厂CDN确实好一些 但是目前人人pcdn的情况下 结果不是很乐观 

pcdn这个 觉得目前主要还是用于视频分发 觉得影响不大

>5、亲测过 [www.189.cn](http://www.189.cn) 联通IP线路优于电信线路 导致都是通过联通线路访问该网址

看了下我这边189用的白山云cdn，这边联通线路给出联通ip（我单线，对双线甚至多线考虑不周

**Comment by openips** [comment]
> > 1、运营商的省级透传或者机房bgp肯定有效果 但是有带宽限制 效率方面肯定同一运营商内部网络更高一些
> 
> 赞同 我觉得和以前相比 现在的情况已经好太多了
> 
> > 2、由于smartdns可以设置多运营商dns 发起查询时走的线路 与运营商dns IP有关系 正确设置ipset的前提下 肯定不会跨运营商网络进行域名解析 3、解析的结果IP测速后 根据多wan线路质量或者繁忙程度 结果会产生变化 可以做到基于dns的内网流量均衡 避免产生有的线路撑死 有的线路饿死的情况
> 
> 我的错。我从没想过在国内使用运营商dns（由于劫持等问题
> 
> > 4、至于给出两个距离甚远的IP 这个情况可能少见 但是给出不同运营商的IP应该是常见情况 大厂CDN确实好一些 但是目前人人pcdn的情况下 结果不是很乐观
> 
> pcdn这个 觉得目前主要还是用于视频分发 觉得影响不大
> 
> > 5、亲测过 [www.189.cn](http://www.189.cn) 联通IP线路优于电信线路 导致都是通过联通线路访问该网址
> 
> 看了下我这边189用的白山云cdn，这边联通线路给出联通ip（我单线，对双线甚至多线考虑不周

多wan下dns能起到更好的作用 是标准的企业级应用场景 现在smartdns已经挺完善的了  国人之光！

**Comment by openips** [comment]
master最新代码已经测试 max-reply-ip-num 参数 
暂时没有发现问题 多谢开发者的支持
