### ISSUE TITLE
domain-rules 配置项在 CNAME 存在时 ipset 无效

### ISSUE THREAD

**Issue by vincascm** [pymumu/smartdns#944]
**问题现象**  
1. 例如配置  `domain-rules /github.com/ -nameserver vps -ipset vps`
2. github.com CNAME 结果 xxx.fastly.net
3. xxx.fastly.net 没有配置 domain-rules
4. 最终 github.com -> xxx.fastly.net -> A 1.2.3.4 没有在 ipset vps group 中

这或许是个优化特性，但是在越来越多网站采用CDN技术的情况下，需要找出 域名到ip 之间所有CNAME的域名并逐一添加domain-rules，也是件很麻烦的事，希望作者能够增加一个全局或者 domain-rules的配置子项， 可以自动跟随解析(CNAME following)

**Comment by pymumu** [comment]
我验证没有问题，在确认下吧。

ipset只有在第一次获取到结果的时候会设置，缓存命中是不会设置的。
ipset默认的超时时间是缓存超时的2倍

**Comment by pymumu** [comment]
我验证没有问题，在确认下吧。

ipset只有在第一次获取到结果的时候会设置，缓存命中是不会设置的。
ipset默认的超时时间是缓存超时的2倍

**Comment by vincascm** [comment]
> 我验证没有问题，在确认下吧。
> 
> ipset只有在第一次获取到结果的时候会设置，缓存命中是不会设置的。 ipset默认的超时时间是缓存超时的2倍

感谢您非常快的回复，您是说在没有额外配置的情况下，像上面所说的情况，xxx.fastly.net 仍会使用 nameserver vps 去解析？

**Comment by pymumu** [comment]
Nameserver 和 ipset是两个独立功能，参数也不是一个意思，nameserver参数对应的是server参数的group

**Comment by vincascm** [comment]
> Nameserver 和 ipset是两个独立功能，参数也不是一个意思，nameserver参数对应的是server参数的group

是这样的，但我希望通过某个配置，能实现将某域名通过某名字服务器，解析到的某IP设置到ipset group上，无论该域名经过了多少次CNAME，现在的情况是，CNAME的域名解析不会使用这里指定的名字服务器

**Comment by PikuZheng** [comment]
> > Nameserver 和 ipset是两个独立功能，参数也不是一个意思，nameserver参数对应的是server参数的group
> 
> 是这样的，但我希望通过某个配置，能实现将某域名通过某名字服务器，解析到的某IP设置到ipset group上，无论该域名经过了多少次CNAME，现在的情况是，CNAME的域名解析不会使用这里指定的名字服务器。 所以是说自动跟随解析(CNAME following)，也就是CNAME的域名解析时名字服务器仍然使用配置中指定的那个

你是说，比如一个域名在解析为CNAME后，这个CNAME没有使用原域名设定的group去解析？这个问题似乎存在，我一直是把对应的cname也加到group去的。。。。
@pymumu

**Comment by vincascm** [comment]
> > > Nameserver 和 ipset是两个独立功能，参数也不是一个意思，nameserver参数对应的是server参数的group
> > 
> > 
> > 是这样的，但我希望通过某个配置，能实现将某域名通过某名字服务器，解析到的某IP设置到ipset group上，无论该域名经过了多少次CNAME，现在的情况是，CNAME的域名解析不会使用这里指定的名字服务器。 所以是说自动跟随解析(CNAME following)，也就是CNAME的域名解析时名字服务器仍然使用配置中指定的那个
> 
> 你是说，比如一个域名在解析为CNAME后，这个CNAME没有使用原域名设定的group去解析？这个问题似乎不存在，但我一直是把对应的cname也加到group去的。。。。
> 
> 测了一下cname的解析会跟随原域名的group。这块是没问题。但是吧，有的app不这么想，它会对获取到的cname重新发起解析。。。

这或许是个优化特性，但是在越来越多网站采用CDN技术的情况下，需要找出 域名到ip 之间所有CNAME的域名并逐一添加domain-rules，也是件很麻烦的事，希望作者能够增加一个全局或者 domain-rules的配置子项， 可以自动跟随解析(CNAME following)

所以最好可以提供一个选项

**Comment by PikuZheng** [comment]
我不确定你说的是不是我理解的情况。比如你的例子：
github.com -> cname: xxx.fastly.net

如果 nslookup -qt=a github.com，那么实际是会查询好几次：github.com -> cname: xxx.fastly.net，xxx.fastly.net -> IP。这几次查询都会用 github.com 的group。

如果 nslookup -qt=cname github.com，那么实际是会查询一次：github.com -> cname: xxx.fastly.net。终端拿到xxx.fastly.net 后，会再次发起查询 nslookup -qt=a xxx.fastly.net。这个 xxx.fastly.net 就是没有domain rule的了

**Comment by vincascm** [comment]
> 我不确定你说的是不是我理解的情况。比如你的例子： github.com -> cname: xxx.fastly.net
> 
> 如果 nslookup -qt=a github.com，那么实际是会查询好几次：github.com -> cname: xxx.fastly.net，xxx.fastly.net -> IP。这几次查询都会用 github.com 的group。
> 
> 如果 nslookup -qt=cname github.com，那么实际是会查询一次：github.com -> cname: xxx.fastly.net。终端拿到xxx.fastly.net 后，会再次发起查询 nslookup -qt=a xxx.fastly.net。这个 xxx.fastly.net 就是没有domain rule的了

但我这里是第一种情况，也确实没有没到 github.com 的group 。
一个实际的例子，
```
 ~ % drill pbs.twimg.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 58890
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; pbs.twimg.com.	IN	A

;; ANSWER SECTION:
pbs.twimg.com.	151	IN	CNAME	cs45.wac.edgecastcdn.net.
cs45.wac.edgecastcdn.net.	3451	IN	A	72.21.91.70
```
我配置里有 
```
domain-rules /pbs.twimg.com/ -nameserver vps -ipset vps
```
没有 `edgecastcdn.net` 的 `domain-rules` 配置，用 `ipset list vps | grep 72.21.91.70` 确实查不到，
配置了 

```
domain-rules /edgecastcdn.net/ -nameserver vps -ipset vps
```
用 `ipset list vps | grep 72.21.91.70` 就能查到。

**Comment by pymumu** [comment]
用的master最新代码吗？

**Comment by PikuZheng** [comment]
> 用的master最新代码吗？

他遇到的问题，是当ipset不存在时，用查询域名->cname->ip 出来的ip无法新建ipset。我记得这个地方修理过一次。

**Comment by vincascm** [comment]
> 用的master最新代码吗？

用的是 ArchLinux 预编译，看编译日期对应的是这个版本 <https://github.com/pymumu/smartdns/releases/tag/Release36.1>

**Comment by pymumu** [comment]
用master代码测试下吧。

猜测可能是CNAME记录的TTL超时时间比较长，导致客户端使用CNAME来请求。

**Comment by PikuZheng** [comment]
> 用master代码测试下吧。
> 
> 猜测可能是CNAME记录的TTL超时时间比较长，导致客户端使用CNAME来请求。

测过了(摊手) 当ipset不存在时，加不到ipset。如果ipset存在，那么是正常的

**Comment by vincascm** [comment]
用master版本测试，
出现了这种情况，

```
 ~ % drill pbs.twimg.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 32839
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; pbs.twimg.com.	IN	A

;; ANSWER SECTION:
pbs.twimg.com.	60	IN	CNAME	twimg.twitter.map.fastly.net.
twimg.twitter.map.fastly.net.	60	IN	A	151.101.52.159

```

这时 `151.101.52.159` 会添加到ipset中；

多次查询(pbs.twimg.com 会随机到多个CNAME中的一个）

```
~ % drill pbs.twimg.com                                                          
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 5680
;; flags: qr rd ra ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; pbs.twimg.com.	IN	A

;; ANSWER SECTION:
pbs.twimg.com.	502	IN	CNAME	cs45.wac.edgecastcdn.net.
cs45.wac.edgecastcdn.net.	502	IN	A	72.21.91.70
```
CNAME	是 `cs45.wac.edgecastcdn.net` 时， `72.21.91.70` 不会添加到 ipset 中

**Comment by vincascm** [comment]
master版本,

刚测试，不是CNAME，只是A记录的域名，也会出现这种情况，第一次返回的ip设置ipset成功，第二次返回的不同的ip，设置失败

**Comment by pymumu** [comment]
最新版本用这个先看看能不能规避。

```
force-no-CNAME yes
```

另外，打开DEBUG日志，把出问题的DEBUG日志发一下。

**Comment by PikuZheng** [comment]
> 另外，打开DEBUG日志，把出问题的DEBUG日志发一下。

他说的问题我这没有测出，但有这样的猜想：
当多个上游服务器解出不同的ip时，smartdns只将最快获取到的结果（ip）添加到ipset中了。但是由于测速，客户端最终获取到的ip可能不是同一个。

我说的是另一个问题，就是当ipset不存在时，无法自动新建。。

**Comment by pymumu** [comment]
ipset要自己手动创建

**Comment by xcyll** [comment]
> > 用的master最新代码吗？
> 
> 他遇到的问题，是当ipset不存在时，用查询域名->cname->ip 出来的ip无法新建ipset。我记得这个地方修理过一次。

与这个提交有关吗？
https://github.com/pymumu/smartdns/commit/d0305f60f6074d2555f10f7888764b6eb3b8edef

**Comment by PikuZheng** [comment]
> > 他遇到的问题，是当ipset不存在时，用查询域名->cname->ip 出来的ip无法新建ipset。我记得这个地方修理过一次。
> 
> 与这个提交有关吗？ [d0305f6](https://github.com/pymumu/smartdns/commit/d0305f60f6074d2555f10f7888764b6eb3b8edef)
他遇到的问题，不是这个

**Comment by pymumu** [comment]
用最新代码，有问题重新提交PR
