### ISSUE TITLE
如何让PPPoE拨号用户使用上SmartDNS

### ISSUE THREAD

**Issue by openwrtdiy** [pymumu/smartdns#945]
**使用需求**
当前编译的固件集成了PPPoE服务器插件rp-pppoe、mwan3和smartdns，不集成dnsmasq、odhcpd、odhcp6c。
PPPoE用户使用是多WAN线路和主备两个DNS：1.1.1.1和8.8.8.8，X86软路由网关是192.168.254.1和PPPoE服务器网关10.0.0.1。
现如何让所有PPPoE用户的域名解释使用上SmartDNS功能？

**Comment by openips** [comment]
防火墙转发所有udp53端口流量至smartdns端口

**Comment by PikuZheng** [comment]
pppoe相当于先拨ppp，然后通过dhcp获取到ip和dns。配置pppoe服务使客户端获取到dns 是smartdns的ip就行了？

**Comment by openwrtdiy** [comment]
> pppoe相当于先拨ppp，然后通过dhcp获取到ip和dns。配置pppoe服务使客户端获取到dns 是smartdns的ip就行了？

PPPoE客户端的DNS可以是SmartDNS的IP，就像无线路由器DHCP自动分配了网关和DNS一样，然后所有DNS解析全部走SmartDNS。

**Comment by PikuZheng** [comment]
那么现在究竟出了什么问题？

**Comment by openwrtdiy** [comment]
> 那么现在究竟出了什么问题？

现在的问题出在DNS解析上！在电脑上手动设置PPPoE自定义DNS 192.168.254.1后再拨号，无法浏览网页，PING不通Google。改回PPPoE服务器默认的DNS 1.1.1.1和8.8.8.8就可以正常访问网站。但这样电脑端DNS解析使用不到SmartDNS功能

**Comment by pymumu** [comment]
发一下smartdns的log日志，改成DEBUG

**Comment by openwrtdiy** [comment]
> 发一下smartdns的log日志，改成DEBUG

**刚刚发现是我在OpenWrt的防火墙 - 通信规则中设置：pppoe用户禁止访问X86软路由设备造成无法使用SmartDNS解析功能！**

# 防火墙区域设置 接受PPPoE出入站数据 拒绝PPPoE之间转发数据 #
uci add firewall zone
uci set firewall.@zone[-1].name=pppoe
uci set firewall.@zone[-1].input=ACCEPT
uci set firewall.@zone[-1].output=ACCEPT
uci set firewall.@zone[-1].forward=DROP
uci add_list firewall.@zone[-1].device=ppp+
uci add firewall forwarding
uci set firewall.@forwarding[-1].src=pppoe
uci set firewall.@forwarding[-1].dest=wan
uci commit firewall

# 防火墙通信规则 禁止PPPoE访问路由器设备 #
uci add firewall rule
uci set firewall.@rule[-1].name=Disable-Access-Gateway
uci add_list firewall.@rule[-1].proto=all
uci set firewall.@rule[-1].src=*
uci set firewall.@rule[-1].device=ppp+
uci set firewall.@rule[-1].direction=in
uci set firewall.@rule[-1].target=DROP
uci commit firewall

**Comment by openwrtdiy** [comment]
smartdns.log

[2022-05-11 15:07:13,002][ERROR][      fast_ping.c:462 ] sendto 2001:4860:4860::8844, id 3, Permission denied
[2022-05-11 15:13:27,171][ERROR][     dns_server.c:3450] dns server process failed.
[2022-05-22 11:59:10,525][ERROR][      fast_ping.c:462 ] sendto 2001:4860:4860::8844, id 3, Permission denied
[2022-05-22 12:13:33,827][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 8, Permission denied
[2022-05-22 12:16:34,230][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 3, Permission denied
[2022-05-22 12:17:20,734][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 4, Permission denied
[2022-05-22 12:18:45,335][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 4, Permission denied
[2022-05-22 12:20:02,196][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 6, Permission denied
[2022-05-22 12:21:23,395][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 3, Permission denied
[2022-05-22 12:23:33,298][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 11, Permission denied
[2022-05-22 12:26:28,702][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 7, Permission denied
[2022-05-22 12:31:49,904][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 8, Permission denied
[2022-05-22 12:32:32,206][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 10, Permission denied
[2022-05-22 12:34:27,811][ERROR][      fast_ping.c:462 ] sendto 2620:119:fc::2, id 6, Permission denied

**Comment by openwrtdiy** [comment]
smartdns.config

config smartdns
	option server_name 'smartdns'
	option port '6053'
	option tcp_server '1'
	option ipv6_server '0'
	option dualstack_ip_selection '0'
	option prefetch_domain '1'
	option serve_expired '1'
	option redirect 'redirect'
	option cache_size '20000'
	option rr_ttl_min '5'
	option seconddns_port '7053'
	option seconddns_tcp_server '1'
	option seconddns_no_speed_check '0'
	option seconddns_no_rule_addr '0'
	option seconddns_no_rule_nameserver '0'
	option seconddns_no_rule_ipset '0'
	option seconddns_no_rule_soa '0'
	option seconddns_no_dualstack_selection '0'
	option seconddns_no_cache '0'
	option force_aaaa_soa '0'
	option coredump '0'
	option enabled '1'
	list old_redirect 'redirect'
	list old_port '6053'
	list old_enabled '1'

config server
	option type 'udp'
	option name '114DNS'
	option ip '114.114.114.114'
	option enabled '0'

config server
	option type 'udp'
	option name 'AliDNS'
	option ip '223.5.5.5'
	option enabled '1'

config server
	option type 'udp'
	option name 'DNSPod'
	option ip '119.29.29.29'
	option enabled '1'

config server
	option type 'udp'
	option name 'BaiduDNS'
	option ip '180.76.76.76'
	option enabled '1'

config server
	option name 'Cloudflare'
	option ip '1.1.1.1'
	option type 'udp'
	option enabled '1'

config server
	option name 'Google'
	option ip '8.8.8.8'
	option type 'udp'
	option enabled '1'

config server
	option type 'udp'
	option name 'OpenDNS'
	option ip '208.67.222.222'
	option enabled '1'

config server
	option name 'Quad9'
	option ip '9.9.9.9'
	option type 'udp'
	option enabled '1'

config server
	option name 'NextDNS'
	option ip '45.90.28.49'
	option type 'udp'
	option enabled '1'

config server
	option name '114DNS'
	option ip '114.114.115.115'
	option type 'tcp'
	option enabled '0'

config server
	option name 'AliDNS'
	option ip '223.6.6.6'
	option type 'tcp'
	option enabled '1'

config server
	option name 'DNSPod'
	option ip '119.28.28.28'
	option type 'tcp'
	option enabled '1'

config server
	option name 'OpenDNS'
	option ip '208.67.220.220'
	option type 'tcp'
	option enabled '1'

config server
	option name 'NextDNS'
	option ip '45.90.30.49'
	option type 'tcp'
	option enabled '1'

config server
	option name 'Cloudflare'
	option ip '1.0.0.1'
	option type 'tcp'
	option enabled '1'

config server
	option name 'Google'
	option ip '8.8.4.4'
	option type 'tcp'
	option enabled '1'

config server
	option name 'Quad9'
	option ip '149.112.112.112'
	option type 'tcp'
	option enabled '1'

config server
	option name 'AliDNS-DoT'
	option ip 'dns.alidns.com'
	option type 'tls'
	option enabled '1'

config server
	option name 'DNSPod-DoT'
	option ip 'dot.pub'
	option type 'tls'
	option enabled '1'

config server
	option ip '1.1.1.1'
	option type 'tls'
	option no_check_certificate '0'
	option host_name '1dot1dot1dot1.cloudflare-dns.com'
	option blacklist_ip '0'
	option name 'Cloudflare-DoT'
	option enabled '1'

config server
	option name 'Google-DoT'
	option ip 'dns.google'
	option type 'tls'
	option no_check_certificate '0'
	option host_name 'dns.google'
	option blacklist_ip '0'
	option enabled '1'

config server
	option name 'NextDNS-DoT'
	option ip 'dns.nextdns.io'
	option type 'tls'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option host_name 'dns.nextdns.io'
	option enabled '1'

config server
	option name 'AliDNS-DoH'
	option type 'https'
	option ip 'dns.alidns.com/dns-query'
	option enabled '1'

config server
	option name 'DNSPod-DoH'
	option type 'https'
	option ip 'doh.pub/dns-query'
	option enabled '1'

config server
	option name 'Google-DoH'
	option type 'https'
	option no_check_certificate '0'
	option host_name 'dns.google'
	option http_host 'dns.google'
	option blacklist_ip '0'
	option ip 'dns.google/dns-query'
	option enabled '1'

config server
	option name 'Quad9-DoH'
	option type 'https'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option ip 'dns9.quad9.net/dns-query'
	option enabled '1'

config server
	option name 'OpenDNS-DoH'
	option type 'https'
	option no_check_certificate '0'
	option host_name 'doh.opendns.com'
	option http_host 'doh.opendns.com'
	option blacklist_ip '0'
	option ip 'doh.opendns.com/dns-query'
	option enabled '1'

config server
	option name 'NextDNS-DoH'
	option type 'https'
	option no_check_certificate '0'
	option blacklist_ip '0'
	option ip 'dns.nextdns.io'
	option host_name 'dns.nextdns.io'
	option enabled '1'

**Comment by PikuZheng** [comment]
所以你现在遇到的问题是pppoe服务的问题，和smartdns无关。
pppoe是单播口（点对点口），客户端不能直接访问pppoe子网下的其他设备。

**Comment by openwrtdiy** [comment]
现在可以正常解析到SmartDNS，打开网页NextDNS.io查询DNS解析状态显示：
该设备未使用 NextDNS。
该设备正在使用“Quad9”作为 DNS 服务器。

**Comment by openwrtdiy** [comment]
> 所以你现在遇到的问题是pppoe服务的问题，和smartdns无关。 pppoe是单播口（点对点口），客户端不能直接访问pppoe子网下的其他设备。

现在找到原因了！我等待一年多的问题总算解决，谢谢大家的帮忙！
