### ISSUE TITLE
接入中国特色的多ISP运营商的情况下，预检测功能

### ISSUE THREAD

**Issue by bubbleatgit** [pymumu/smartdns#946]
### 背景
当用户接入中国电信、中国移动两条线路的时候，遇到最难的问题就是`智能DNS解析`的问题。如何让 localDNS 服务器返回最优的 IP 给客户端，是一个很棘手的问题。

### 需求
当用户接入的两条线路在价格、质量上旗鼓相当时，用户可能会需求两条线路的流量负载基本相等，即可以最大化利用带宽，又想获取到最优的目标服务器 IP。

### 方案一：轮询所有上游DNS
SmartDNS 配置上游 DNS 时，分别配置电信、移动本地运营商的 DNS 服务器，在客户端第一次对某个域名发起查询时轮询两个 ISP 的DNS服务器，并使用 SmartDNS 的 check 功能检测所有 IP ，返回最佳 IP 给客户端，同时写入 DNS 缓存。

### 方案二：公共DNS负载到不同线路
SmartDNS 上游DNS使用阿里云或者腾讯云的公共DNS，并针对这几个 IP 使用负载均衡的策略路由到不同线路。SmartDNS 的仅需要开启检测功能即可。

假设配置 `119.29.29.29` 为上游DNS，在MikroTik RouterOS中配置PCC策略，分流 DNS 服务的请求连接到不同的路由上。

> 以上方案的前提是：负载均衡策略已配置完成，可实现电信IP走电信网关，移动IP走移动网关。 
>目前 SmartDNS 的 DNS 请求应该不是每次查询时，轮询所有服务器 ，并对每个服务器返回的 IP 进行质量检测。

## 补充说明

看到的另外一个 Issue：#882 ，该问题主要是因为楼主未配置多运营商的策略路由，从而导致的问题。

**Comment by PikuZheng** [comment]
和我的环境类似，Mikrotik作网关，smartdns在单独的服务器上。

我觉得这两个方案，主要的问题在于Mikrotik和smartdns无法高效率沟通协作。

重点在于，smartdns请求上游（或测速）所使用的线路，要与客户端实际连接的线路一致。 至于负载或分流，对于大多数带宽跑不满的情况下不是很重要。

**Comment by bubbleatgit** [comment]
> 和我的环境类似，Mikrotik作网关，smartdns在单独的服务器上。
> 
> 我觉得这两个方案，主要的问题在于Mikrotik和smartdns无法高效率沟通协作。
> 
> 重点在于，smartdns请求上游（或测速）所使用的线路，要与客户端实际连接的线路一致。 至于负载或分流，对于大多数带宽跑不满的情况下不是很重要。


如果是方案一的话，不需要 SmartDNS请求上游和客户端线路一致，只需要DNS告诉客户端一个IP，客户端访问这个 IP 走对应线路的路由出即可。

**Comment by bubbleatgit** [comment]
这个是网上看到别人产品的方案，感觉 SmartDNS 应该也可以实现。

![e8ff92c712214b2cd30aefc63db26b8](https://user-images.githubusercontent.com/7858776/169809305-f12f7875-72bf-40fc-a0c5-3f808eebaf5c.jpg)

**Comment by openips** [comment]
我的方案是
https://github.com/pymumu/smartdns/issues/942#issuecomment-1133496857

个人觉得不需要预检测功能
> 方案二：公共DNS负载到不同线路
这个只需要配置上游不通运营商的dns+公共DNS就可以了 配合IPset+mwan3就可以自动选择解析线路 筛选出最优的IP

如果要做到更合理的使用多wan带宽，可以降低缓存时间，定时测速一下使用的域名，判断哪里返回IP响应最快就可以了

目前的商业方案是防火墙和DNS单独部署 dns通过snmp获取防火墙端口带宽使用情况 从而返回客户端带宽使用少的端口对应运营商的CDN IP 比较麻烦 smartdns测速就可以解决多线路负载平衡

**Comment by PikuZheng** [comment]
> 
> 目前的商业方案是防火墙和DNS单独部署 dns通过snmp获取防火墙端口带宽使用情况 从而返回客户端带宽使用少的端口对应运营商的CDN IP 比较麻烦 smartdns测速就可以解决多线路负载平衡

这个方案妙啊 基于这个原理，使用公共dns，由上级路由自行觉得路径就可以了

顺便问下smartdns对“预加载缓存”的域名是怎么实施测速的？如果这部分也测速，会不会导致连接线路一直保持或一直变化？

**Comment by openips** [comment]
> > 目前的商业方案是防火墙和DNS单独部署 dns通过snmp获取防火墙端口带宽使用情况 从而返回客户端带宽使用少的端口对应运营商的CDN IP 比较麻烦 smartdns测速就可以解决多线路负载平衡
> 
> 这个方案妙啊 基于这个原理，使用公共dns，由上级路由自行觉得路径就可以了
> 
> 顺便问下smartdns对“预加载缓存”的域名是怎么实施测速的？如果这部分也测速，会不会导致连接线路一直保持或一直变化？

1、判断线路变不变化的判断依据是时间 
2、缓存中存在域名解析结果直接返回 缓存中没有就会测速后保存在缓存中
3、缓存数据有过期时间

smartdns直接就解决了 snmp方案不见得好
