### ISSUE TITLE
关于dot配置方案求教

### ISSUE THREAD

**Issue by 15108428326** [pymumu/smartdns#949]
本人用的是阿里，腾讯和360的dot解析，老是遇见解析服务器连接失败，debug发现是解析服务器的域名ip解析不成功或者获得的ip不能成功连接。于是用domain-rules -a x.y.z -a a.b.c配置了域名主、备用ip，这样来规避这种问题，最初是会连接x.y.z和a.b.c的，后面改了下测速设置就只会用a.b.c了，现在想问下大家该怎么去实现主、备用ip的设置。

**Comment by PikuZheng** [comment]
```
domain-rules /dns.alidns.com/ -a 223.5.5.5 -a 223.6.6.6 -speed-check-mode none
```
另外根据我的经验，直接在server-tls指定其中一个ip即可，既不需要使用域名，也没必要配置成两个ip

**Comment by 15108428326** [comment]
用domain连续两个-a不能做到两个ip都使用，不能还原之前是咋做到的了，现在改为把同一dns解析的2个ip都单独写了句

**Comment by 15108428326** [comment]
> ```
> domain-rules /dns.alidns.com/ -a 223.5.5.5 -a 223.6.6.6 -speed-check-mode none
> ```
> 
> 另外根据我的经验，直接在server-tls指定其中一个ip即可，既不需要使用域名，也没必要配置成两个ip

一个dns服务商只配置1个ip，由于国内dot就3家，会出现3家的都连不上，然后解析不了

**Comment by 15108428326** [comment]
全用udp上游就从来没报过warn，用dot或者doh老是warn error或者直接程序死掉

**Comment by 15108428326** [comment]
这是我之前的配置文件，出现错误的几率不小
![Screenshot_2022-05-27-17-28-17-64](https://user-images.githubusercontent.com/74700165/170672505-f9258632-89bc-41fb-8c08-a65346095373.png)
### 2022-5-27
# 新增配置
force-qtype-SOA 65
# 118.113.158.158，请修改为自己的外部公网ip后，再启用
edns-client-subnet 118.113.158.158/24
max-reply-ip-num 6
# Padavan固件路径/tmp/dnsmasq.leases
dnsmasq-lease-file /tmp/dnsmasq.leases
### 可为UDP上游添加-check-edns参数

###【基础 DNS】
server-tcp 114.114.114.114:53 -group Base_DNS -exclude-default-group
server-tcp 1.2.4.8:53 -group Base_DNS -exclude-default-group

### ①【Ali_DNS】
domain-rules /dns.alidns.com/ -c none -a 223.5.5.5 -a 223.6.6.6 -n Base_DNS -d no
# server-https https://dns.alidns.com/dns-query -blacklist-ip -group Safe
server-tls dns.alidns.com:853 -blacklist-ip -group Safe

### ② 【Tencent_DNS】
domain-rules /doh.pub/ -c none -a 1.12.12.12 -a 120.53.53.53 -n Base_DNS -d no
domain-rules /dot.pub/ -c none -a 1.12.12.12 -a 120.53.53.53 -n Base_DNS -d no
# server-https https://doh.pub/dns-query -blacklist-ip -group Safe
server-tls dot.pub:853 -blacklist-ip -group Safe

### ③【360_DNS】
domain-rules /doh.360.cn/ -c none -a 112.65.69.15 -a 101.198.198.198 -n Base_DNS -d no
domain-rules /dot.360.cn/ -c none -a 112.65.69.15 -a 101.198.198.198 -n Base_DNS -d no
# server-https https://doh.360.cn/dns-query -blacklist-ip -group Safe
server-tls dot.360.cn:853 -blacklist-ip -group Safe

### ④【台湾 DNS】为了解析github而加入
server-tcp 101.101.101.101:53 -blacklist-ip -group Over -exclude-default-group
server-tcp 168.95.1.1:53 -blacklist-ip -group Over -exclude-default-group

### 域名分流
domain-rules /github.com/ -c none -n Over -d no
domain-rules /githubapp.com/ -c none -n Over -d no
domain-rules /github.io/ -c none -n Over -d no
domain-rules /githubusercontent.com/ -c none -n Over -d no
domain-rules /githubassets.com/ -c none -n Over -d no
domain-rules /github-cloud.s3.amazonaws.com/ -c none -n Over -d no
domain-rules /github.global.ssl.fastly.net/ -c none -n Over -d no
domain-rules /assets-cnd.github.com/ -c none -n Over -d no

### ip黑名单
blacklist-ip 127.0.0.1/16
blacklist-ip 0.0.0.0/16
# 20.205.243.166 为 github.com 不可用地址
blacklist-ip 20.205.243.166/32

### 测速模式默认为ping，对于不响应ping的可以设置tcp:80以及tcp:443
### 测速方式最多设置2种，多的则为无效，前者不响应则使用后面的。
speed-check-mode tcp:443,ping

### 日志级别 fatal,error,warn,notice,info,debug
log-level warn
log-size 1024K
log-num 1

#audit-enable yes
#audit-SOA  yes
#audit-size 1024K
#audit-num 1

**Comment by PikuZheng** [comment]
我就是全用dot和doh的 如果三大家同时挂 那是网真的挂了把。。
另一方面建议dot和doh混用，由于dot连接快，doh二次连接快

**Comment by 15108428326** [comment]
> 
3家是有可能同时timeout连接不上的，后续会修改为每家2个tls和https试试

**Comment by PikuZheng** [comment]
之前有报告说由于同时连接和测速，并发连接数满导致断网的。须留意

**Comment by 15108428326** [comment]
> 之前有报告说由于同时连接和测速，并发连接数满导致断网的。须留意

嗯，感谢你的解答。
由于我用的是padavan固件，是否可以：把dnsmasq改为6053端口，smartdns用53端口，再把dot.pub之类的解析指定交给127.0.0.1:6053 -group Base -exclude-default-group，在dnsmasq里配置dot.pub 1.12.12.12与dot.pub 120.53.53.53

**Comment by 15108428326** [comment]
我现在用的套娃是，dnsmasq用53端口: all-servers，cache-size=0，smartdns用6053端口，作为dnsmasq的上游之一，开启缓存。这样一般来说smartdns只要没崩溃就是相应最快的，崩溃了也因为它只是上游之一，不会造成断网

**Comment by PikuZheng** [comment]
对于在上游服务中配置的域名，smartdns走系统自身的dns查询，配置address之类的不起作用（除非查询被回环，但容易导致其他问题，可以参考#567和#887
 
早先版本如果将smartdns设为dnsmasq的上游，或重定向，可能会导致奇怪的无法启动问题。虽然新版做了一些修正，但我建议smartdns配到53，独立处理所有业务。
