### ISSUE TITLE
最新代码会引起个别网址打不开 总体感觉页面打开速度没有1.2022.2046版本快

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#950]
**问题现象** 
个别网址打不开 (https://passport.jd.com/new/login.aspx?ReturnUrl=https%3A%2F%2Fwww.jd.com%2F)

**运行环境**

1. 固件型号  
openwrt  x64 master
smartdns代码  commit b5a531197617e0dd82a9fdf5f0416ca1db6a7df7
2. 运营商  
联通+电信
3、IP检测机制
speed-check-mode tcp:443,tcp:80
4、其他
查看日志发现只有ping 没有tcp检测443端口记录 是否是功能去掉了或者是bug

**重现步骤**
1. 上游DNS配置。  
>/etc/config/smartdns

>>config smartdns
        option dualstack_ip_selection '0'
        option seconddns_no_speed_check '0'
        option seconddns_no_rule_addr '0'
        option seconddns_no_rule_ipset '0'
        option seconddns_no_rule_soa '0'
        option seconddns_no_dualstack_selection '0'
        option seconddns_no_rule_nameserver '0'
        option prefetch_domain '1'
        option seconddns_port '7913'
        option seconddns_server_group 'us'
        option seconddns_no_cache '0'
        option seconddns_tcp_server '0'
        option ipv6_server '0'
        option server_name 'smartdns'
        option port '6054'
        option tcp_server '0'
        option serve_expired '0'
        option force_aaaa_soa '0'
        option rr_ttl_max '36000'
        option rr_ttl_min '3000'
        option cache_size '50000'
        option enabled '1'
        option redirect 'dnsmasq-upstream'
        option coredump '1'
        list old_redirect 'dnsmasq-upstream'
        list old_port '6054'
        list old_enabled '1'
config server
        option type 'udp'
        option blacklist_ip '0'
        option enabled '1'
        option server_group 'china'
        option name 'unicom'
        option ip '202.102.224.68'
config server
        option type 'udp'
        option ip '219.141.136.10'
        option blacklist_ip '0'
        option enabled '1'
        option server_group 'china'
        option name 'chinanet'
config server
        option type 'udp'
        option ip '221.179.155.161'
        option blacklist_ip '0'
        option enabled '1'
        option server_group 'china'
        option name 'cmcc'
config server
        option type 'udp'
        option name 'baidu'
        option ip '114.114.114.114'
        option blacklist_ip '0'
        option enabled '1'
        option server_group 'china'
config server
        option type 'udp'
        option name 'dnspod'
        option ip '223.5.5.5'
        option blacklist_ip '0'
        option enabled '1'
        option server_group 'china'
config server
        option name 'rubyfish'
        option ip 'rubyfish.cn'
        option type 'tls'
        option blacklist_ip '0'
        option enabled '1'
        option server_group 'china'
config server
        option enabled '1'
        option name '360'
        option ip 'dot.360.cn'
        option type 'tls'
        option server_group 'china'
        option blacklist_ip '0'
config server
        option enabled '1'
        option name 'ali'
        option ip 'https://223.5.5.5/dns-query'
        option type 'https'
        option server_group 'china'
        option blacklist_ip '0'
config server
        option name 'google'
        option ip '8.8.8.8'
        option type 'tcp'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'google'
        option ip '8.8.8.8'
        option type 'tls'
        option blacklist_ip '0'
        option server_group 'us'
        option enabled '0'
config server
        option name 'google'
        option type 'https'
        option server_group 'us'
        option blacklist_ip '0'
        option ip 'https://dns.google/dns-query'
        option enabled '0'
config server
        option name 'google'
        option ip '8.8.4.4'
        option type 'tcp'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'google'
        option ip '8.8.4.4'
        option type 'tls'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'google'
        option ip '8.8.4.4'
        option type 'https'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'opendns'
        option ip '208.67.222.222'
        option type 'tcp'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'opendns'
        option ip '208.67.222.222'
        option type 'tls'
        option blacklist_ip '0'
        option server_group 'us'
        option enabled '0'
config server
        option name 'opendns'
        option type 'https'
        option blacklist_ip '0'
        option ip 'https://doh.opendns.com/dns-query'
        option server_group 'us'
        option enabled '1'
config server
        option name 'Quad9'
        option ip '9.9.9.9'
        option type 'tcp'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'Quad9'
        option ip '9.9.9.9'
        option type 'tls'
        option blacklist_ip '0'
        option server_group 'us'
        option enabled '1'
config server
        option name 'Quad9'
        option type 'https'
        option server_group 'us'
        option blacklist_ip '0'
        option ip 'https://dns.quad9.net/dns-query'
        option enabled '0'
config server
        option enabled '1'
        option name 'tiar'
        option ip 'jp.tiar.app/dns-query        '
        option type 'https'
        option server_group 'us'
        option blacklist_ip '0'
config server
        option name 'tiar'
        option ip 'jp.tiar.app  '
        option type 'tls'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'
config server
        option name 'tiarap.org'
        option ip 'jp.tiarap.org/dns-query'
        option type 'https'
        option server_group 'us'
        option blacklist_ip '0'
        option enabled '0'

>custom.conf

>>bind :7054 -group us
bind :7055 -group china
cache-persist yes
cache-file /tmp/smartdns.cache
speed-check-mode tcp:443,tcp:80
force-AAAA-SOA yes
max-reply-ip-num 1

3. 访问的域名。  
https://passport.jd.com/new/login.aspx?ReturnUrl=https%3A%2F%2Fwww.jd.com%2F
打不开
**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  

[smartdns.log](https://github.com/pymumu/smartdns/files/8790377/smartdns.log)

[smartdns.log](https://github.com/pymumu/smartdns/files/8790380/smartdns.log)
[smartdns.log-20220528-104033.gz](https://github.com/pymumu/smartdns/files/8790381/smartdns.log-20220528-104033.gz)
[smartdns.log-20220528-104319.gz](https://github.com/pymumu/smartdns/files/8790382/smartdns.log-20220528-104319.gz)

**Comment by pymumu** [comment]
可能是ip个数导致的，吧ip个数设置2看看

**Comment by openips** [comment]
> 可能是ip个数导致的，吧ip个数设置2看看

之前用版本没这个问题 IP的测速有问题了吗？

**Comment by pymumu** [comment]
[smartdns.1.2022.05.28-1953.x86_64-openwrt-all.zip](https://github.com/pymumu/smartdns/files/8791076/smartdns.1.2022.05.28-1953.x86_64-openwrt-all.zip)

修改了ip个数的逻辑

ping测速，一直都是正常的，你看一下你配置是不是有多个

**Comment by openips** [comment]
> [smartdns.1.2022.05.28-1953.x86_64-openwrt-all.zip](https://github.com/pymumu/smartdns/files/8791076/smartdns.1.2022.05.28-1953.x86_64-openwrt-all.zip)
> 
> 修改了ip个数的逻辑
> 
> 测速机制一直都是正常的，你看一下你配置是不是有多个，覆盖了
> 

好的 我试一下 测速我看日志都是ping ip 没有测试tcp相应端口

**Comment by PikuZheng** [comment]
1. 请设置log-level debug 以便查看测速情况
2. 
```[2022-05-28 10:22:06,446][ INFO][     dns_server.c:3642] query server passport.jd.com from 127.0.0.1, qtype = 1
[2022-05-28 10:22:06,446][ INFO][     dns_server.c:3642] query server passport.jd.com from 127.0.0.1, qtype = 1
[2022-05-28 10:22:06,447][ INFO][     dns_server.c:3642] query server passport.jd.com from 127.0.0.1, qtype = 1
[2022-05-28 10:22:06,447][ INFO][     dns_server.c:3642] query server passport.jd.com from 127.0.0.1, qtype = 1
[2022-05-28 10:22:06,788][ WARN][     dns_client.c:2126] http server query from 172.104.93.80:443 failed, server return http code : 400, Bad Request
```
这个上游有问题
3. 看一下jd.com的域名规则怎么写的

**Comment by openips** [comment]
>1.请设置log-level debug 以便查看测速情况
正在编译 等会编译好了我试试
>2.
我上游套了个openclash
>3.看一下jd.com的域名规则怎么写的
jd.com可以正常打开 就是国内IP直连 
passport.jd.com 我没有发现规则 应该也是直连的

**Comment by PikuZheng** [comment]
```
[2022-05-28 22:26:04,713][DEBUG][     dns_server.c:3880] recv query packet from 127.0.0.1, len = 29
[2022-05-28 22:26:04,713][DEBUG][     dns_server.c:3888] request qdcount = 1, ancount = 0, nscount = 0, nrcount = 0, len = 29, id = 5057, tc = 0, rd = 1, ra = 0, rcode = 0
[2022-05-28 22:26:04,713][ INFO][     dns_server.c:3904] query server cart.jd.com from 127.0.0.1, qtype = 1
[2022-05-28 22:26:04,713][DEBUG][     dns_client.c:500 ] send query to group us
[2022-05-28 22:26:04,713][DEBUG][     dns_client.c:2798] send query to server 172.104.93.80
[2022-05-28 22:26:04,713][DEBUG][     dns_client.c:2798] send query to server 146.112.41.2
[2022-05-28 22:26:04,714][DEBUG][     dns_client.c:2798] send query to server 8.8.4.4
[2022-05-28 22:26:04,714][DEBUG][     dns_client.c:2798] send query to server 8.8.8.8
```
jd 在 us 组。

```
option seconddns_port '7913'
option seconddns_server_group 'us'
option port '6054'
...
bind :7054 -group us
bind :7055 -group china
```
所以你起了4个smartdns服务？可以在运行时看一下 `/var/etc/smartdns/smartdns.conf` 最终生成的配置是什么

>我上游套了个openclash

说反了吧，看配置smartdns是clash的上游，clash是dnsmasq的上游？

**Comment by openips** [comment]
> 1.jd 在 us 组。

应该是在缓存里面吧 配置了dns jd在哪里看IP检测机制和最后测速的结果吧

>2.所以你起了4个smartdns服务？可以在运行时看一下 /var/etc/smartdns/smartdns.conf 最终生成的配置是什么

起了两个smartdns的子服务 7054 7055两个upd

>3. /var/etc/smartdns/smartdns.conf
server-name smartdns
bind :6054
dualstack-ip-selection no
prefetch-domain yes
cache-size 50000
rr-ttl-min 3000
rr-ttl-max 36000
log-size 64K
log-num 1
log-level error
server 202.102.224.68  -group china
server 222.85.85.85  -group china
server 211.138.24.66  -group china
server 114.114.114.114  -group china
server 223.5.5.5  -group china
server-tls rubyfish.cn  -group china
server-tls dot.360.cn  -group china
server-https https://223.5.5.5/dns-query  -group china
server-tcp 8.8.8.8  -group us
server-https https://dns.google/dns-query  -group us
server-https https://doh.opendns.com/dns-query  -group us
server-https jp.tiar.app/dns-query  -group us
conf-file /etc/smartdns/address.conf
conf-file /etc/smartdns/blacklist-ip.conf
conf-file /etc/smartdns/custom.conf

>4.说反了吧，看配置smartdns是clash的上游，clash是dnsmasq的上游？

dnsmasq->clash->smartdns
clash劫持DNSMASQ 交给smartdns分组解析
应该算是smartdns是clash的上游

**Comment by PikuZheng** [comment]
>应该是在缓存里面吧 配置了dns jd在哪里看IP检测机制和最后测速的结果吧

日志有它自己的想法。缓存没走组规则的bug已经修正了。

>bind :6054
>bind :7054 -group us
>bind :7055 -group china

所以总共起了三个口。猜测clash把jd.com查询送到7054口了，这样就走的us。

**Comment by openips** [comment]
> >应该是在缓存里面吧 配置了dns jd在哪里看IP检测机制和最后测速的结果吧
> 
> 日志有它自己的想法。缓存没走组规则的bug已经修正了。
> 
> >bind :6054
> >bind :7054 -group us
> >bind :7055 -group china
> 
> 所以总共起了三个口。猜测clash把jd.com查询送到7054口了，这样就走的us。
> 

jd的查询走那个端口无所谓 关键是返回IP测速后的结果返回给客户端的是什么

**Comment by PikuZheng** [comment]
我测试了一下，证实在speed-check-mode 里配置了两个tcp时，只有最后一个端口号生效 @pymumu

**Comment by frankilla1987** [comment]
我最初用最新的pre版本的时候，用yytd运行nslookup不筛选ip了。然后我就退回36.1，目前感觉各种好。

**Comment by pymumu** [comment]
最新代码已经修正。

目前best-ip修改比较多，会有不少BUG，个人能力时间有限，请谅解。
也请各位发现问题，第一时间提交issue，同时给出具体的复现方法。

**Comment by frankilla1987** [comment]
啊，我是小白不知道怎么排查只能退回前版本，等大佬发布新的我在用，不好意思啊，我不是那个意思。_(:з)∠)_

**Comment by PikuZheng** [comment]
> 目前best-ip修改比较多，会有不少BUG，个人能力时间有限，请谅解。 也请各位发现问题，第一时间提交issue，同时给出具体的复现方法。

各功能模块紧密联系相互配合，牵一发动全身。希望以修复bug和优化运行速度为主，谨慎引入新功能

**Comment by openips** [comment]
> > 目前best-ip修改比较多，会有不少BUG，个人能力时间有限，请谅解。 也请各位发现问题，第一时间提交issue，同时给出具体的复现方法。
> 
> 各功能模块紧密联系相互配合，牵一发动全身。希望以修复bug和优化运行速度为主，谨慎引入新功能
> 


+1

**Comment by openips** [comment]
> 最新代码已经修正。
> 
> 目前best-ip修改比较多，会有不少BUG，个人能力时间有限，请谅解。 也请各位发现问题，第一时间提交issue，同时给出具体的复现方法。

最近已经明显感觉smartdns在进步成长 这些bug都是成长的代价 发现问题及时反馈和修改 现在做的已经挺不错的了 别泄气

**Comment by openips** [comment]
commit 3b526d2ff66fb8ad1efde67671b20b9fc93653f2
测试了一下暂时没有发现什么问题 查看日志tcp 80和443检测都有了
暂时没有什么问题 有问题再反馈
[smartdns_1.2022.0529-1_x86_64.zip](https://github.com/pymumu/smartdns/files/8793430/smartdns_1.2022.0529-1_x86_64.zip)
这是我根据最新代码编译的ipk 大家也可以测试一下
