### ISSUE TITLE
luci-app-smartdns 是否可以同步更新为最新版本

### ISSUE THREAD

**Issue by openips** [pymumu/smartdns#951]
[luci-app-smartdns](https://github.com/pymumu/luci-app-smartdns)
已经两年没更新了 是否可以同步更新一下 谢谢

**Comment by PikuZheng** [comment]
uci没有需要更新的地方啊？是说把最近几个新参数加进去吗？

**Comment by openips** [comment]
> uci没有需要更新的地方啊？是说把最近几个新参数加进去吗？

加点参数提示也好啊

**Comment by openwrtdiy** [comment]
> > uci没有需要更新的地方啊？是说把最近几个新参数加进去吗？
> 
> 加点参数提示也好啊

新增功能：自动/手动/定时选项 更新国内外路由列表 黑名单 去广告等
新增功能：可以在线查看当天日志，省去进入SSH后台。

**Comment by openips** [comment]
> > > uci没有需要更新的地方啊？是说把最近几个新参数加进去吗？
> > 
> > 
> > 加点参数提示也好啊
> 
> 新增功能：自动/手动/定时选项 更新国内外路由列表 黑名单 去广告等 新增功能：可以在线查看当天日志，省去进入SSH后台。

可以提交到https://github.com/pymumu/luci-app-smartdns吗 smartdns的master树包含东西太多了 没办法整合到编译的openwrt固件中

**Comment by openwrtdiy** [comment]
RPCError
RPC call to uci/get failed with ubus code 4: 未找到资源
  at ClassConstructor.handleCallReply (http://192.168.95.1/luci-static/resources/rpc.js?v=git-22.158.25210-d5e8241:15:3)

![下载](https://user-images.githubusercontent.com/57249132/173028112-18846761-8f07-45f7-9d4a-d985dbd3a6f2.jpg)

主机名	OpenWrt
型号	Default string Default string/SKYBAY - Intel(R) Celeron(R) CPU 3865U @ 1.80GHz : 2 Core 2 Thread
目标平台	x86/64
固件版本	OpenWrt 21.02-SNAPSHOT r16650-2d66b18598 / LuCI openwrt-21.02 branch git-22.158.25210-d5e8241

我正在学习更新luci-app-smartdns，但编译出错了。  使用的代码是OpenWrt-21.02的LUCI界面

**Comment by pymumu** [comment]
用openwrt官网的版本，那个库的都不更新了。
