### ISSUE TITLE
ERROR日志：connect 2001::, id 1, Cannot assign requested address

### ISSUE THREAD

**Issue by 15108428326** [pymumu/smartdns#952]
**问题现象**  
简要描述问题出现的现象
设置force-AAAA-SOA yes禁用ipv6解析后还是会出现connect 2001::, id 1, Cannot assign requested 
 address错误。
![Screenshot_2022-05-30-08-23-10-82](https://user-images.githubusercontent.com/74700165/170897673-41a339bf-4042-472b-8357-a5c769f25f32.png)
![Screenshot_2022-05-30-08-22-54-89](https://user-images.githubusercontent.com/74700165/170897678-b57db10b-e024-4b9e-aba8-f0508f5cff3d.png)
![Screenshot_2022-05-30-08-22-46-11](https://user-images.githubusercontent.com/74700165/170897695-9ce8ee7d-d743-4740-950c-01ad0193072f.png)
![Screenshot_2022-05-30-08-22-33-15](https://user-images.githubusercontent.com/74700165/170897709-c1e257bd-9d08-4322-adba-e2e204cc6ff9.png)

**运行环境**
1. 固件型号  

2. 运营商  

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by 15108428326** [comment]
用的 May 29版的源码： Readme: add readme for DNS TYPE65 & DNSMASQ hostname 编译的

**Comment by PikuZheng** [comment]
[2001::]是本机地址吧，日志不完整，看看是把什么域名解出来的ipv6

**Comment by 15108428326** [comment]
不知道咋发文件，用的网盘
https://wwd.lanzouq.com/i8TEe05ndmfe

**Comment by PikuZheng** [comment]
这个是36.7版本新增的特性，smartdns自身的ipv6环境检测。如果检测没有ipv6环境，会自动禁用关闭双栈IP优选和IPv6测速

**Comment by 15108428326** [comment]
哦，那就是不管它了，强迫症还以为有啥问题呢

**Comment by PikuZheng** [comment]
建议在 force-AAAA-SOA 时  _dns_server_check_ipv6_ready() 直接返回0 @pymumu

**Comment by pymumu** [comment]
已经修正。

**Comment by 15108428326** [comment]
重新编译，已不再提示
