### ISSUE TITLE
smartdns有多个服务器同步解析,发现国外IP放弃国内dns的解析记录,采用国外服务器的结果功能吗?

### ISSUE THREAD

**Issue by blog2i2j** [pymumu/smartdns#954]
**需求应用场景**
类似于chinadns, 采用一国内,一国外服务器同步解析, 得到的IP是国外的, 放弃国内dns的结果, 返回国外dns的结果.

请问smartdns有这个功能吗?

**Comment by pymumu** [comment]
whitelist-ip
blacklist-ip

**Comment by blog2i2j** [comment]
谢谢, 学习一下这个参数, 这个参数也没用过

**Comment by blog2i2j** [comment]
> whitelist-ip blacklist-ip

请教一下blacklist-ip的含义, 比如 server 114.114.114.114 -blacklist-ip, 这个时候如果114解析回来的IP命中blacklist的话, 是直接丢弃吗?

**Comment by PikuZheng** [comment]
你的理解正确。但需要注意：

如果一个查询返回多个ip的结果，只要其中一个在blacklist中，该结果整个丢弃；
如果一个查询返回多个ip的结果，但没有任何结果符合whitelist，该结果整个丢弃
