### ISSUE TITLE
屏蔽广告可以订阅链接吗

### ISSUE THREAD

**Issue by SuernWU** [pymumu/smartdns#955]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by PikuZheng** [comment]
crontab定时下载配置然后重启？

**Comment by cresky-github** [comment]
可以。
但，是有条件的。
语法得符合smartdns要求，若不符，自行写脚本处理，使之符合。

**Comment by SuernWU** [comment]
可以指导下嘛

**Comment by cresky-github** [comment]
> 可以指导下嘛
> […](#)
> cresky-github ***@***.***>於2022年6月8日 17:27寫道： ﻿ 可以。 但，是有条件的。 语法得符合smartdns要求，若不符，自行写脚本处理，使之符合。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

你得会写 Linux Shell 脚本。

**Comment by SuernWU** [comment]
那我并不会 我找到了一个链接想在里边使用

https://anti-ad.net/anti-ad-for-smartdns.conf

**Comment by cresky-github** [comment]
> 那我并不会 我找到了一个链接想在里边使用 https://anti-ad.net/anti-ad-for-smartdns.conf
> […](#)
> cresky-github ***@***.***>於2022年6月8日 17:43寫道： ﻿ 可以指导下嘛 … cresky-github @.***>於2022年6月8日 17:27寫道： ﻿ 可以。 但，是有条件的。 语法得符合smartdns要求，若不符，自行写脚本处理，使之符合。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. 你得会写 Linux Shell 脚本。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

这个源，我也在用。
与其它源合并成一个.conf文件

**Comment by PikuZheng** [comment]
这个我也在用，我是这么写的:
自定义配置增加
```
conf-file /etc/smartdns/anti-ad-for-smartdns.conf
```
计划任务增加
```
0 2 * * * wget https://anti-ad.net/anti-ad-for-smartdns.conf -O /etc/smartdns/anti-ad-for-smartdns.conf && /etc/init.d/smartdns restart
```

**Comment by SuernWU** [comment]
好的 谢谢你

**Comment by naoki66** [comment]
要是luci界面可以直观的设置就好了

**Comment by cresky-github** [comment]
> > 要是luci界面可以直观的设置就好了
> 
> OpenWRT-21.02的LUCI界面有问题。 [pymumu/luci-app-smartdns#17](https://github.com/pymumu/luci-app-smartdns/issues/17)

现在，
基本用 不预装 luci 的 Openwrt。

**Comment by openwrtdiy** [comment]
> 



> > > 要是luci界面可以直观的设置就好了
> > 
> > 
> > OpenWRT-21.02的LUCI界面有问题。 [pymumu/luci-app-smartdns#17](https://github.com/pymumu/luci-app-smartdns/issues/17)
> 
> 现在， 基本用 不预装 luci 的 Openwrt。

主要是为了方便页面上进行管理

**Comment by cresky-github** [comment]
> > 
> 
> 
> 
> > > > 要是luci界面可以直观的设置就好了
> > > 
> > > 
> > > OpenWRT-21.02的LUCI界面有问题。 [pymumu/luci-app-smartdns#17](https://github.com/pymumu/luci-app-smartdns/issues/17)
> > 
> > 现在， 基本用 不预装 luci 的 Openwrt。
> 
> 主要是为了方便页面上进行管理

其实，也不方便多少。
因为，没必要总去动。

**Comment by pymumu** [comment]
release 40的luci已经支持，具体参考40对于的帮助。

**Comment by umlearn** [comment]
### 保存为 update-smartdns-configs.sh 放到 /etc/smartdns/ 下
`#!/bin/sh

# 下载配置文件
wget https://anti-ad.net/anti-ad-for-smartdns.conf -O /etc/smartdns/anti-ad-smartdns.conf
wget https://adrules.top/smart-dns.conf -O /etc/smartdns/adrules-smartdns.conf
wget https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_smartdns.conf -O /etc/smartdns/neodevhost-smartdns.conf

# 重启 SmartDNS 服务
/etc/init.d/smartdns restart`

### 添加计划任务（每周六上午8点更新）
`0 8 * * 6 /etc/smartdns/update-smartdns-configs.sh`
