### ISSUE TITLE
SRV没有正常返回，导致Windows Server RD许可证服务器连接异常

### ISSUE THREAD

**Issue by glintyang** [pymumu/smartdns#957]
**问题现象**  
Windows Server RD许可证服务器连接异常
可能是srv记录的问题

docker image ghostry/smartdns:v2021.08.27
smartdns.1.2021.08.27-1923.x86_64-linux-all.tar.gz 这个版本正常
之后的版本都没有响应srv

**运行环境**
1. 固件型号  
docker
image: [ghostry/smartdns](https://hub.docker.com/r/ghostry/smartdns)

2. 运营商  
私有网络

**重现步骤**
1. 上游DNS配置。  
server 10.67.72.159

2. 访问的域名。  
type srv _ldap._tcp.dc._msdcs.local.com

**信息收集**  

异常版本
[v2022.04.05.txt](https://github.com/pymumu/smartdns/files/8875000/v2022.04.05.txt)

正常版本
[v2021.08.27.txt](https://github.com/pymumu/smartdns/files/8874996/v2021.08.27.txt)

**Comment by pymumu** [comment]
最新代码呢？

**Comment by glintyang** [comment]
[commit 7e985e7d113405030f5ee59fed9d709fb784a685](https://github.com/pymumu/smartdns/commit/7e985e7d113405030f5ee59fed9d709fb784a685)
[master.txt](https://github.com/pymumu/smartdns/files/8875222/master.txt)

用master的代码试了试也是没有正确返回srv

**Comment by pymumu** [comment]
务必设置上有，有服务能返回SRV信息，设置缓存为0，重新跑一下，把第一次查询的log发出来。

**Comment by pymumu** [comment]
另外，可以修改下dns_server.c的2427行，将is_result_discard=1改为is_result_discard=0

**Comment by glintyang** [comment]
上游为Windows AD的DNS，有SRV能力，在可用的2021.08.27版本可以返回

缓存设置为0
is_result_discard=0
重新build，试了试还是不行

附，配置文件、请求、可用版本日志和master日志
[dnslog.txt](https://github.com/pymumu/smartdns/files/8875455/dnslog.txt)

**Comment by pymumu** [comment]
看log，最新版本也应该正确回应了结果。
log里面也看到只有一个上游，这个比较奇怪。

用dig命令查询下看看。

**Comment by glintyang** [comment]
[dig1.txt](https://github.com/pymumu/smartdns/files/8877159/dig1.txt)

**Comment by pymumu** [comment]
看样子是查询结果被丢弃了，返回了SRV-Fail
我这里简单尝试了下SRV，是可以的，没复现出来。
没找到哪里丢弃结果了。


加了点打印，替换编译下，发现运行日志。
[smartdns.zip](https://github.com/pymumu/smartdns/files/8878527/smartdns.zip)

**Comment by glintyang** [comment]
![image](https://user-images.githubusercontent.com/3461158/173111721-fcdd2a75-68e0-4aef-a2fd-32bfa36cafab.png)

是只有这一个文件吗，看了一下内容和master的一致，可能没保存好？

**Comment by pymumu** [comment]
[dns_server.zip](https://github.com/pymumu/smartdns/files/8882073/dns_server.zip)
弄错文件了

**Comment by glintyang** [comment]
build后，日志没生效，检查了一下，才注意到，之前build的一直是没修改的master
我用的repo中的Dockerfile，build时一直是clone master的内容，我前面改了is_result_discard=0也没生效
重新修改了is_result_discard=0，修改了Dockerfile，build本地修改的版本，正常返回了SRV
问题解决，感谢👍
https://github.com/pymumu/smartdns/blob/7e985e7d113405030f5ee59fed9d709fb784a685/Dockerfile#L3-L7
是否考虑将git clone调整为COPY使用当前工程目录中的代码进行编译

**Comment by pymumu** [comment]
修改了下代，用最新代码看看

**Comment by glintyang** [comment]
最新代码，测试正常

https://github.com/pymumu/smartdns/blob/c0f4c72626829ee273e66c911ca1ec7702138ea4/Dockerfile#L4-L7
缩进或许多了一个空格
