### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by Eay5** [pymumu/smartdns#962]
什么时候编译一版最新的,已经一个多月没更新啦!

**Comment by PikuZheng** [comment]
可以试试我编译的版本 https://github.com/PikuZheng/smartdns/releases

**Comment by LsnmxNB** [comment]
> 可以试试我编译的版本 https://github.com/PikuZheng/smartdns/releases

谢谢大佬

**Comment by iamyangyiok** [comment]
> 可以试试我编译的版本 https://github.com/PikuZheng/smartdns/releases

你好 我章鱼星求，卸载了老版本 用你的ARM-OPENWRT版本，安装一直提示Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest. Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.  这个怎么解决，谢谢

**Comment by PikuZheng** [comment]
> k

您这个openwrt可能不是官方的版本，需要用对应的源码自己编译smartdns。当然也不一定会出问题，如果能安装成功可以不用管这个报错

**Comment by iamyangyiok** [comment]
> > k
> 
> 您这个openwrt可能不是官方的版本，需要用对应的源码自己编译smartdns。当然也不一定会出问题，如果能安装成功可以不用管这个报错

就是安装不成功

**Comment by iamyangyiok** [comment]
> > k
> 
> 您这个openwrt可能不是官方的版本，需要用对应的源码自己编译smartdns。当然也不一定会出问题，如果能安装成功可以不用管这个报错

提示这个安不上去

**Comment by PikuZheng** [comment]
> 
> 提示这个安不上去

试试先更新 libgcc1 并解决冲突问题

**Comment by PikuZheng** [comment]
> 提示这个安不上去

```
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
```
这些个不影响安装。如果安装不能，应该有其他报错

**Comment by jin3014test1** [comment]
> 可以试试我编译的版本 https://github.com/PikuZheng/smartdns/releases

Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package smartdns.

**Comment by iamyangyiok** [comment]
> > 提示这个安不上去
> 
> 试试先更新 libgcc1 并解决冲突问题

更新了没有用，安装还是不成功 。LUCI可安

**Comment by kiligone** [comment]
> * compati

我是HC5962，选了mipsel-openwrt也是这个错误

**Comment by kiligone** [comment]
> > > 可以试试我编译的版本 https://github.com/PikuZheng/smartdns/releases
> > 
> > 
> > Collected errors:
> > 
> > * pkg_hash_fetch_best_installation_candidate: Packages for smartdns found, but incompatible with the architectures configured
> > * opkg_install_cmd: Cannot install package smartdns.
> 
> cpu架构错误，请选用正确的包

我是HC5962，下载了mipsel-openwrt的版本也是这个错误，迷茫

**Comment by PikuZheng** [comment]
https://github.com/pymumu/smartdns/releases/tag/Release37-RC1
