### ISSUE TITLE
如何通过debug找出已解析出国外直连的ip地址及对应解析dns？

### ISSUE THREAD

**Issue by 4thanks** [pymumu/smartdns#964]
**问题现象**  

1.**国内外直连，无科学上网环境。**
2.大杂烩tcp udp dot doh多组dns服务器能测速并解析并连接到平常很难连接的GitHub、v2ex和任天堂手游FE Hero
3.虽然精简、分组、黑名单，但反而连不上。

之前看过一个[issue #919](https://github.com/pymumu/smartdns/issues/919)](https://github.com/pymumu/smartdns/issues/919) ，作者详解了speed-check-mode测速的应用场景及优势，于是开折腾拼拼凑凑了很多组dns服务器，tcp udp dot doh一起上，测试意外发现还是有10%~20%能连接到平常很难上或登录的网站，如GitHub、v2ex和任天堂手游FE Hero，但解析后再连也会有概率连不上，应该是又被污染了。

虽然勉强够用，但强迫症想精简一些可能多余的dns服务组，穷尽自己一知半解的上网知识去精简、分组、黑名单后反而连不上，无奈还是转回大杂烩dns服务组。

如下是自己在debug抓取Nintendo关键词上下5行的日志，麻烦大神们看一下，有没有办法精简dns组及优化直连速度？

**运行环境**
1. 固件型号  
immortalwrt 18.06-k5.4 armv7-cm520
2. 运营商  
上海联通

**重现步骤**
1. 上游DNS配置。  

2. 访问的域名。  
任天堂手游火纹、GitHub、v2ex

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
2. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下
[nintendo-debug.txt](https://github.com/pymumu/smartdns/files/8924881/nintendo-debug.txt)

**Comment by PikuZheng** [comment]
啥意思，你已经写了规则

**Comment by 4thanks** [comment]
> 
精简已有冗长的dns组来改善和优化连接速度，不想每次测速找出能连接的ip后，过了1个小时或半天又失效了，然后继续等smartdns重新测速找出可连接的IP

**Comment by 4thanks** [comment]
> 啥意思，你已经写了规则 nintendo.com，它会匹配以 nintendo.com 结尾的所有域名。 但是根据我自己的经验，nintendo 使用的 amazonaws.com 忽快忽慢或被墙才是原因。可以考虑使用 edns 把它们解到 hk的pccw或jp去。如果解到 sg 大概率是连不上的

精简已有冗长的dns组来改善和优化连接速度，不想每次测速找出能连接的ip后，过了1个小时或半天又失效了，然后继续等smartdns重新测速找出可连接的IP

**Comment by 4thanks** [comment]
> 啥意思，你已经写了规则 nintendo.com，它会匹配以 nintendo.com 结尾的所有域名。 但是根据我自己的经验，nintendo 使用的 amazonaws.com 忽快忽慢或被墙才是原因。可以考虑使用 edns 把它们解到 hk的pccw或jp去。如果解到 sg 大概率是连不上的

edns怎么使用？36.1版本有没？

**Comment by 4thanks** [comment]
> 

为什么想找出解析对应的dns呢？我的理解是精简dns组≈ 就减少污染干扰≈ 测速更快≈ 连接更快，但可能只是我的浅薄理解😂
有盲测试过通过分组国内udp,国外tls，但如果分组排除默认，就很难难测速找到可以连接IP，尤其是任天堂手游的那个，精简分组盲测了几次还是把-exclude-default-group去掉，大杂烩反而容易测速找到可连接IP，目前是以下的配置。
`# Add custom settings here.

# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
log-level debug

# log-size k,m,g
log-size 1024k

# log-file /var/log/smartdns.log
log-num 6

# List of hosts that supply bogus NX domain results
# bogus-nxdomain [ip/subnet]

prefetch-domain yes
serve-expired yes
serve-expired-ttl 360
serve-expired-reply-ttl 30

# ttl用于所有资源记录
# rr-ttl: 所有记录的ttl
# rr-ttl-min: 资源记录的最小ttl
# rr-ttl-max: 资源记录的最大ttl
# example:
rr-ttl 300
rr-ttl-min 60
rr-ttl-max 86400
rr-ttl-reply-max 60

# Add custom settings here.
conf-file /etc/smartdns/anti-ad-for-smartdns.conf
conf-file /etc/smartdns/chnroute.conf
conf-file /etc/smartdns/whitelist_full-mod.conf
conf-file /etc/smartdns/blacklist_full-mod.conf

ca-file /etc/ssl/certs/ca-certificates.crt
ca-path /etc/ssl/certs

#speed-check-mode tcp:443,tcp:80,ping
force-qtype-SOA 65

#dualstack-ip-selection yes
#dualstack-ip-selection-threshold 30

bind :5678 -group domestic -no-cache speed-check-mode ping,tcp:80,tcp:443
bind :5689 -group foreign -blacklist-ip  -exclude-default-group dualstack-ip-selection yes dualstack-ip-selection-threshold 30 speed-check-mode tcp:443,tcp:80,ping

##cn-DoH

#dnspod+
server-tls dot.pub -tls-host-verify *.dot.pub -host-name *.dot.pub -http-host *.dot.pub -group domestic
server-https https://doh.pub/dns-query -tls-host-verify *.doh.pub -host-name *.doh.pub -http-host *.doh.pub -group domestic
#alidns
domain-rules /dns.alidns.com/ -a 223.5.5.5 -a 223.6.6.6 -speed-check-mode none
server-tls dns.alidns.com -tls-host-verify dns.alidns.com -host-name dns.alidns.com -http-host dns.alidns.com -group domestic
server-https https://dns.alidns.com/dns-query -tls-host-verify dns.alidns.com -host-name dns.alidns.com -http-host dns.alidns.com -group domestic
#360pai
domain-rules /dot.360.cn/ -a 101.226.4.6 -a 123.125.81.6 -speed-check-mode none
domain-rules /doh.360.cn/ -a 101.226.4.6 -a 123.125.81.6 -speed-check-mode none
server-tls dot.360.cn -tls-host-verify doh.360.cn -host-name doh.360.cn -http-host doh.360.cn -group domestic
server-https https://doh.360.cn/dns-query -tls-host-verify doh.360.cn -host-name doh.360.cn -http-host doh.360.cn -group domestic


##out-DoH
#ipv6dns
#domain-rules /dns.ipv6dns.com/ -a 210.22.70.225 -a 119.29.29.29 -speed-check-mode none
domain-rules /dns.ipv6dns.com/ -aaaa server 240C::6666 -aaaa server 240C::6644 -speed-check-mode none
server-tls dns.ipv6dns.com -tls-host-verify dns.ipv6dns.com -host-name dns.ipv6dns.com -http-host dns.ipv6dns.com -check-edns -group foreign
#server-https https://dns.ipv6dns.com/dns-query -tls-host-verify dns.ipv6dns.com -host-name dns.ipv6dns.com -http-host dns.ipv6dns.com -check-edns -group foreign

#taiwan101
#nameserver /dns.twnic.tw/quad101
server-tls 101.101.101.101 -tls-host-verify 101.101.101.101 -host-name 101.101.101.101 -http-host 101.101.101.101 -check-edns -group foreign
domain-rules /dns.twnic.tw/ -a 101.102.103.104 -a 168.95.1.1 -speed-check-mode none
#server-https https://dns.twnic.tw/dns-query -tls-host-verify 101.101.101.101 -host-name 101.101.101.101 -http-host 101.101.101.101

#google

#domain-rules /dns.google/ -a 8.8.4.4 -a 101.102.103.104 -speed-check-mode none
#domain-rules /dns64.dns.google/ -aaaa 2001:4860:4860::64 -aaaa 240C::6666  -speed-check-mode none
#server-tls 8.8.8.8 -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign
server-tls dns.google -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign
#server-https https://dns64.dns.google/dns-query{?dns} -check-edns -group foreign
server-tls dns64.dns.google -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign
#server-https https://dns.google/dns-query -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign

#server-tls 1.1.1.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -check-edns -group foreign
#server-tls 2606:4700:4700::1111 -host-name 1dot1dot1dot1.cloudflare-dns.com -check-edns -group foreign
server-tls 1dot1dot1dot1.cloudflare-dns.com -check-edns -group foreign


##backup
server-tcp 2001:de4::101 -check-edns -group foreign
server 2001:de4::102 -check-edns -group foreign
server 101.101.101.101 -check-edns -group foreign
server-tcp 101.102.103.104 -check-edns -group foreign
server 1.1.1.1 -check-edns -group foreign
server-tcp 1.0.0.1 -check-edns -group foreign
server 2606:4700:4700::1111 -check-edns -group foreign
##dns.sb&Hurricane Electric
server 185.222.222.222 -check-edns -group foreign
server 185.184.222.222 -check-edns -group foreign
#server 2a09:: -group foreign
#server 2a09::1 -group foreign
server 74.82.42.42 -check-edns -group foreign
server 2001:470:20::2 -check-edns -group foreign
#server 85.150.99.255 -check-edns -group foreign
server 5.1.66.255 -check-edns -group foreign

server 208.67.222.222:5353 -check-edns -group foreign
server 208.67.220.220:5353 -check-edns -group foreign
server-https https://doh.opendns.com/dns-query -check-edns -group foreign
#server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group foreign

server 9.9.9.9 -check-edns -group foreign
server 149.112.112.112 -check-edns -group foreign
#server-tcp 149.112.112.112 -check-edns -group foreign
server-https https://9.9.9.9/dns-query -check-edns -group foreign
#server-https https://dns11.quad9.net/dns-query -group foreign`

**Comment by 4thanks** [comment]
> 配置国内udp,国外tls的就可以了，国外的配置港澳台的，韩国的。
> 
> 我这边switch玩游戏还行，至于v2ex，github smartdns是无法改善的

为什么想找出解析对应的dns呢？我的理解是精简dns组≈ 就减少污染干扰≈ 测速更快≈ 连接更快，但可能只是我的浅薄理解😂
有盲测试过通过分组国内udp,国外tls，但如果分组排除默认，就很难难测速找到可以连接IP，尤其是任天堂手游的那个，精简分组盲测了几次还是把-exclude-default-group去掉，大杂烩反而容易测速找到可连接IP，目前是以下的配置。

```
# Add custom settings here.

# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
log-level debug

# log-size k,m,g
log-size 1024k

# log-file /var/log/smartdns.log
log-num 6

# List of hosts that supply bogus NX domain results
# bogus-nxdomain [ip/subnet]

prefetch-domain yes
serve-expired yes
serve-expired-ttl 360
serve-expired-reply-ttl 30

# ttl用于所有资源记录
# rr-ttl: 所有记录的ttl
# rr-ttl-min: 资源记录的最小ttl
# rr-ttl-max: 资源记录的最大ttl
# example:
rr-ttl 300
rr-ttl-min 60
rr-ttl-max 86400
rr-ttl-reply-max 60

# Add custom settings here.
conf-file /etc/smartdns/anti-ad-for-smartdns.conf
conf-file /etc/smartdns/chnroute.conf
conf-file /etc/smartdns/whitelist_full-mod.conf
conf-file /etc/smartdns/blacklist_full-mod.conf

ca-file /etc/ssl/certs/ca-certificates.crt
ca-path /etc/ssl/certs

#speed-check-mode tcp:443,tcp:80,ping
force-qtype-SOA 65

#dualstack-ip-selection yes
#dualstack-ip-selection-threshold 30

bind :5678 -group domestic -no-cache speed-check-mode ping,tcp:80,tcp:443
bind :5689 -group foreign -blacklist-ip  -exclude-default-group dualstack-ip-selection yes dualstack-ip-selection-threshold 30 speed-check-mode tcp:443,tcp:80,ping

##cn-DoH

#dnspod+
server-tls dot.pub -tls-host-verify *.dot.pub -host-name *.dot.pub -http-host *.dot.pub -group domestic
server-https https://doh.pub/dns-query -tls-host-verify *.doh.pub -host-name *.doh.pub -http-host *.doh.pub -group domestic
#alidns
domain-rules /dns.alidns.com/ -a 223.5.5.5 -a 223.6.6.6 -speed-check-mode none
server-tls dns.alidns.com -tls-host-verify dns.alidns.com -host-name dns.alidns.com -http-host dns.alidns.com -group domestic
server-https https://dns.alidns.com/dns-query -tls-host-verify dns.alidns.com -host-name dns.alidns.com -http-host dns.alidns.com -group domestic
#360pai
domain-rules /dot.360.cn/ -a 101.226.4.6 -a 123.125.81.6 -speed-check-mode none
domain-rules /doh.360.cn/ -a 101.226.4.6 -a 123.125.81.6 -speed-check-mode none
server-tls dot.360.cn -tls-host-verify doh.360.cn -host-name doh.360.cn -http-host doh.360.cn -group domestic
server-https https://doh.360.cn/dns-query -tls-host-verify doh.360.cn -host-name doh.360.cn -http-host doh.360.cn -group domestic


##out-DoH
#ipv6dns
#domain-rules /dns.ipv6dns.com/ -a 210.22.70.225 -a 119.29.29.29 -speed-check-mode none
domain-rules /dns.ipv6dns.com/ -aaaa server 240C::6666 -aaaa server 240C::6644 -speed-check-mode none
server-tls dns.ipv6dns.com -tls-host-verify dns.ipv6dns.com -host-name dns.ipv6dns.com -http-host dns.ipv6dns.com -check-edns -group foreign
#server-https https://dns.ipv6dns.com/dns-query -tls-host-verify dns.ipv6dns.com -host-name dns.ipv6dns.com -http-host dns.ipv6dns.com -check-edns -group foreign

#taiwan101
#nameserver /dns.twnic.tw/quad101
server-tls 101.101.101.101 -tls-host-verify 101.101.101.101 -host-name 101.101.101.101 -http-host 101.101.101.101 -check-edns -group foreign
domain-rules /dns.twnic.tw/ -a 101.102.103.104 -a 168.95.1.1 -speed-check-mode none
#server-https https://dns.twnic.tw/dns-query -tls-host-verify 101.101.101.101 -host-name 101.101.101.101 -http-host 101.101.101.101

#google

#domain-rules /dns.google/ -a 8.8.4.4 -a 101.102.103.104 -speed-check-mode none
#domain-rules /dns64.dns.google/ -aaaa 2001:4860:4860::64 -aaaa 240C::6666  -speed-check-mode none
#server-tls 8.8.8.8 -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign
server-tls dns.google -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign
#server-https https://dns64.dns.google/dns-query{?dns} -check-edns -group foreign
server-tls dns64.dns.google -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign
#server-https https://dns.google/dns-query -tls-host-verify dns.google -host-name dns.google -http-host dns.google -check-edns -group foreign

#server-tls 1.1.1.1 -host-name 1dot1dot1dot1.cloudflare-dns.com -check-edns -group foreign
#server-tls 2606:4700:4700::1111 -host-name 1dot1dot1dot1.cloudflare-dns.com -check-edns -group foreign
server-tls 1dot1dot1dot1.cloudflare-dns.com -check-edns -group foreign


##backup
server-tcp 2001:de4::101 -check-edns -group foreign
server 2001:de4::102 -check-edns -group foreign
server 101.101.101.101 -check-edns -group foreign
server-tcp 101.102.103.104 -check-edns -group foreign
server 1.1.1.1 -check-edns -group foreign
server-tcp 1.0.0.1 -check-edns -group foreign
server 2606:4700:4700::1111 -check-edns -group foreign
##dns.sb&Hurricane Electric
server 185.222.222.222 -check-edns -group foreign
server 185.184.222.222 -check-edns -group foreign
#server 2a09:: -group foreign
#server 2a09::1 -group foreign
server 74.82.42.42 -check-edns -group foreign
server 2001:470:20::2 -check-edns -group foreign
#server 85.150.99.255 -check-edns -group foreign
server 5.1.66.255 -check-edns -group foreign

server 208.67.222.222:5353 -check-edns -group foreign
server 208.67.220.220:5353 -check-edns -group foreign
server-https https://doh.opendns.com/dns-query -check-edns -group foreign
#server-https https://146.112.41.2/dns-query -host-name doh.opendns.com -http-host doh.opendns.com -group foreign

server 9.9.9.9 -check-edns -group foreign
server 149.112.112.112 -check-edns -group foreign
#server-tcp 149.112.112.112 -check-edns -group foreign
server-https https://9.9.9.9/dns-query -check-edns -group foreign
#server-https https://dns11.quad9.net/dns-query -group foreign
```

**Comment by pymumu** [comment]
配置这么多作用不大，一般10个一下比较合适，超过，大部分IP地址都是重复的，耗费了查询时间。

如果要再更多地址，要使用edns，但目前edns是全局一个，不支持每个服务器单独edns，所以，edns也无法达到你要的。

我自己配置大约10个，都是直接连接国外服务器的，速度还是不错的。
当然，被block的网站是无法通过smartdns就能上的。

**Comment by 4thanks** [comment]
我也觉得太多了，所以才想清理一下，之前精简的思路，就是把国外和国外backup组分2两批加-exclude-default-group分别测试，但过了很久甚至一个晚上都过去了都没查询到可用IP，去掉-exclude-default-group反而能上，去掉了就大杂烩也就无法分组进一步精简，所以才试着来发帖问问。
当然不是想通过smartens来上被和谐的网站，自己也有代理。几个常用国外直连的测试是为了以防代理失效，一些不是被和谐网站还能dns测速暂时缓解一下。

> 配置这么多作用不大，一般10个一下比较合适，超过，大部分IP地址都是重复的，耗费了查询时间。
> 
> 如果要再更多地址，要使用edns，但目前edns是全局一个，不支持每个服务器单独edns，所以，edns也无法达到你要的。
> 
> 我自己配置大约10个，都是直接连接国外服务器的，速度还是不错的。 当然，被block的网站是无法通过smartdns就能上的。
> 
> 还有，你的 serve-expired-ttl 配置是不合理的，这个值都是按天配置的，推荐是1～3天。
> 
> 当前smartdns的默认值应该是最佳的配置，一般都不用修改，只需要添加服务器地址。 非特别需求，不建议修改这些值。

**Comment by pymumu** [comment]
不用配置太复杂。太复杂反而适得其反。
smartdns适合解析能直接连接的网站。对标的是dnsmasq，不是china-dns之类的软件。
具体可以仔细看smartdns功能说明那几个特性。
