### ISSUE TITLE
DNS服务器数量是否有限制

### ISSUE THREAD

**Issue by HX-Technology-LLC** [pymumu/smartdns#965]
**问题现象**  
简要描述问题出现的现象
添加过多的DNS服务器时会无法启动
**运行环境**
1. 固件型号  
hiboy padavan
2. 运营商  
电信
**重现步骤**
1. 上游DNS配置。  
配置超过30个DNS
2. 随后在log中提示无法启动

**Comment by pymumu** [comment]
上限是64个，并且超过上限不应该无法启动，除非是bug
