### ISSUE TITLE
求大佬帮助 怎么禁止返回::1 地址

### ISSUE THREAD

**Issue by lalasou** [pymumu/smartdns#969]
怎么能禁止 返回::1 ipv6地址？
![image](https://user-images.githubusercontent.com/7440313/175772115-c1e7b43b-819b-49a9-b4b1-174841827156.jpeg)

所用配置文件如下

小白  主要是 国内解析 还有tmmdb  之类的能连上
还有这个blacklist-ip  有没有更新的地方需不需要更新？ 

bind-tcp [::]:53
bind [::]:53
tcp-idle-time 3
cache-size 4096000
prefetch-domain yes
serve-expired yes
serve-expired-ttl 0
speed-check-mode tcp:80,tcp:443,ping
rr-ttl-min 60
rr-ttl-max 86400
log-level error
server 223.5.5.5:53 -blacklist-ip
server 119.29.29.29:53 -blacklist-ip
server 114.114.114.114:53 -blacklist-ip
server 1.1.1.1 -check-edns
server 1.0.0.1 -check-edns
server 8.8.8.8 -check-edns
server 8.8.4.4 -check-edns
server 208.67.222.222 -check-edns
server-tcp 119.29.29.29
server-tcp 64.6.64.6
server-tcp 8.8.4.4:53
server-tcp 208.67.222.222:443
server-tls 8.8.8.8:853
server-tls 8.8.4.4:853
server-tls 1.1.1.1:853
server-tls 1.0.0.1:853
server-https https://cloudflare-dns.com/dns-query
server-https https://dns.google/dns-query

bogus-nxdomain 127.0.0.0/8
bogus-nxdomain 169.254.0.0/16
bogus-nxdomain 255.255.255.255
bogus-nxdomain 123.125.81.12
bogus-nxdomain 101.226.10.8
bogus-nxdomain 198.105.254.11
bogus-nxdomain 104.239.213.7
bogus-nxdomain 61.191.206.4
bogus-nxdomain 218.30.64.194
bogus-nxdomain 61.139.8.101
bogus-nxdomain 61.139.8.102
bogus-nxdomain 61.139.8.103
bogus-nxdomain 61.139.8.104
bogus-nxdomain 42.123.125.237
bogus-nxdomain 202.100.68.117
bogus-nxdomain 113.12.83.4
bogus-nxdomain 113.12.83.5
bogus-nxdomain 202.100.220.54
bogus-nxdomain 60.191.124.236
bogus-nxdomain 60.191.124.252
bogus-nxdomain 222.221.5.204
bogus-nxdomain 124.232.132.94
bogus-nxdomain 202.102.110.204
bogus-nxdomain 61.131.208.210
bogus-nxdomain 61.131.208.211
bogus-nxdomain 202.102.110.203
bogus-nxdomain 202.102.110.205
bogus-nxdomain 219.146.13.36
bogus-nxdomain 180.168.41.175
bogus-nxdomain 180.153.103.224
bogus-nxdomain 111.175.221.58
bogus-nxdomain 61.183.1.186
bogus-nxdomain 125.76.239.244
bogus-nxdomain 125.76.239.245
bogus-nxdomain 222.221.5.252
bogus-nxdomain 222.221.5.253
bogus-nxdomain 220.165.8.172
bogus-nxdomain 220.165.8.174
bogus-nxdomain 112.132.230.179
bogus-nxdomain 202.106.199.34
bogus-nxdomain 202.106.199.35
bogus-nxdomain 202.106.199.36
bogus-nxdomain 202.106.199.37
bogus-nxdomain 202.106.199.38
bogus-nxdomain 221.192.153.41
bogus-nxdomain 221.192.153.42
bogus-nxdomain 221.192.153.43
bogus-nxdomain 221.192.153.44
bogus-nxdomain 221.192.153.45
bogus-nxdomain 221.192.153.46
bogus-nxdomain 221.192.153.49
bogus-nxdomain 125.211.213.130
bogus-nxdomain 125.211.213.131
bogus-nxdomain 125.211.213.132
bogus-nxdomain 125.211.213.133
bogus-nxdomain 125.211.213.134
bogus-nxdomain 218.28.144.36
bogus-nxdomain 218.28.144.37
bogus-nxdomain 218.28.144.38
bogus-nxdomain 218.28.144.39
bogus-nxdomain 218.28.144.40
bogus-nxdomain 218.28.144.41
bogus-nxdomain 218.28.144.42
bogus-nxdomain 202.98.24.121
bogus-nxdomain 202.98.24.122
bogus-nxdomain 202.98.24.123
bogus-nxdomain 202.98.24.124
bogus-nxdomain 202.98.24.125
bogus-nxdomain 60.19.29.21
bogus-nxdomain 60.19.29.22
bogus-nxdomain 60.19.29.23
bogus-nxdomain 60.19.29.24
bogus-nxdomain 60.19.29.25
bogus-nxdomain 60.19.29.26
bogus-nxdomain 60.19.29.27
bogus-nxdomain 220.250.64.18
bogus-nxdomain 220.250.64.19
bogus-nxdomain 220.250.64.20
bogus-nxdomain 220.250.64.21
bogus-nxdomain 220.250.64.22
bogus-nxdomain 220.250.64.23
bogus-nxdomain 220.250.64.24
bogus-nxdomain 220.250.64.25
bogus-nxdomain 220.250.64.26
bogus-nxdomain 220.250.64.27
bogus-nxdomain 220.250.64.28
bogus-nxdomain 220.250.64.29
bogus-nxdomain 220.250.64.30
bogus-nxdomain 220.250.64.225
bogus-nxdomain 220.250.64.226
bogus-nxdomain 220.250.64.227
bogus-nxdomain 220.250.64.228
bogus-nxdomain 202.99.254.231
bogus-nxdomain 202.99.254.232
bogus-nxdomain 202.99.254.230
bogus-nxdomain 123.129.254.11
bogus-nxdomain 123.129.254.12
bogus-nxdomain 123.129.254.13
bogus-nxdomain 123.129.254.14
bogus-nxdomain 123.129.254.15
bogus-nxdomain 123.129.254.16
bogus-nxdomain 123.129.254.17
bogus-nxdomain 123.129.254.18
bogus-nxdomain 123.129.254.19
bogus-nxdomain 221.204.244.36
bogus-nxdomain 221.204.244.37
bogus-nxdomain 221.204.244.38
bogus-nxdomain 221.204.244.39
bogus-nxdomain 221.204.244.40
bogus-nxdomain 221.204.244.41
bogus-nxdomain 218.68.250.117
bogus-nxdomain 218.68.250.118
bogus-nxdomain 218.68.250.119
bogus-nxdomain 218.68.250.120
bogus-nxdomain 218.68.250.121
bogus-nxdomain 120.209.138.64
bogus-nxdomain 211.139.136.73
bogus-nxdomain 221.179.46.190
bogus-nxdomain 221.179.46.194
bogus-nxdomain 183.207.232.253
bogus-nxdomain 223.82.248.117
bogus-nxdomain 211.138.74.132
bogus-nxdomain 211.137.130.101
bogus-nxdomain 211.136.113.1
bogus-nxdomain 211.138.102.198
bogus-nxdomain 120.192.83.163
bogus-nxdomain 183.221.242.172
bogus-nxdomain 183.221.250.11
bogus-nxdomain 111.11.208.2
bogus-nxdomain 183.224.40.24
bogus-nxdomain 211.98.70.226
bogus-nxdomain 211.98.70.227
bogus-nxdomain 211.98.71.195
bogus-nxdomain 114.112.163.232
bogus-nxdomain 114.112.163.254
blacklist-ip 4.36.66.178
blacklist-ip 8.7.198.45
blacklist-ip 31.13.64.1
blacklist-ip 31.13.64.33
blacklist-ip 31.13.64.49
blacklist-ip 31.13.65.1
blacklist-ip 31.13.65.17
blacklist-ip 31.13.65.18
blacklist-ip 31.13.66.1
blacklist-ip 31.13.66.23
blacklist-ip 31.13.66.6
blacklist-ip 31.13.68.1
blacklist-ip 31.13.68.22
blacklist-ip 31.13.69.129
blacklist-ip 31.13.69.160
blacklist-ip 31.13.69.33
blacklist-ip 31.13.69.86
blacklist-ip 31.13.70.1
blacklist-ip 31.13.70.20
blacklist-ip 31.13.71.23
blacklist-ip 31.13.71.7
blacklist-ip 31.13.72.1
blacklist-ip 31.13.72.17
blacklist-ip 31.13.72.23
blacklist-ip 31.13.72.34
blacklist-ip 31.13.72.54
blacklist-ip 31.13.73.1
blacklist-ip 31.13.73.17
blacklist-ip 31.13.73.23
blacklist-ip 31.13.74.1
blacklist-ip 31.13.74.17
blacklist-ip 31.13.75.17
blacklist-ip 31.13.75.18
blacklist-ip 31.13.76.16
blacklist-ip 31.13.76.8
blacklist-ip 31.13.77.33
blacklist-ip 31.13.77.55
blacklist-ip 31.13.78.65
blacklist-ip 31.13.78.66
blacklist-ip 31.13.79.1
blacklist-ip 31.13.79.17
blacklist-ip 31.13.80.1
blacklist-ip 31.13.80.17
blacklist-ip 31.13.81.1
blacklist-ip 31.13.81.17
blacklist-ip 31.13.82.1
blacklist-ip 31.13.82.17
blacklist-ip 31.13.82.23
blacklist-ip 31.13.83.1
blacklist-ip 31.13.83.16
blacklist-ip 31.13.83.8
blacklist-ip 31.13.84.1
blacklist-ip 31.13.84.16
blacklist-ip 31.13.84.8
blacklist-ip 31.13.85.1
blacklist-ip 31.13.85.16
blacklist-ip 31.13.85.8
blacklist-ip 31.13.86.1
blacklist-ip 31.13.86.16
blacklist-ip 31.13.86.8
blacklist-ip 31.13.97.245
blacklist-ip 31.13.97.248
blacklist-ip 37.61.54.158
blacklist-ip 46.82.174.68
blacklist-ip 59.24.3.173
blacklist-ip 64.13.192.74
blacklist-ip 64.13.192.76
blacklist-ip 64.13.232.149
blacklist-ip 64.33.88.161
blacklist-ip 64.33.99.47
blacklist-ip 64.66.163.251
blacklist-ip 65.104.202.252
blacklist-ip 65.160.219.113
blacklist-ip 66.45.252.237
blacklist-ip 66.220.146.94
blacklist-ip 66.220.147.11
blacklist-ip 66.220.147.44
blacklist-ip 66.220.147.47
blacklist-ip 66.220.149.18
blacklist-ip 66.220.149.32
blacklist-ip 66.220.149.99
blacklist-ip 66.220.151.20
blacklist-ip 66.220.152.17
blacklist-ip 66.220.152.28
blacklist-ip 66.220.155.12
blacklist-ip 66.220.155.14
blacklist-ip 66.220.158.32
blacklist-ip 67.15.100.252
blacklist-ip 67.15.129.210
blacklist-ip 67.228.37.26
blacklist-ip 67.228.74.123
blacklist-ip 67.228.102.32
blacklist-ip 67.228.126.62
blacklist-ip 67.228.221.221
blacklist-ip 67.228.235.91
blacklist-ip 67.228.235.93
blacklist-ip 69.63.176.143
blacklist-ip 69.63.176.15
blacklist-ip 69.63.176.59
blacklist-ip 69.63.178.13
blacklist-ip 69.63.180.173
blacklist-ip 69.63.181.11
blacklist-ip 69.63.181.12
blacklist-ip 69.63.184.14
blacklist-ip 69.63.184.142
blacklist-ip 69.63.184.30
blacklist-ip 69.63.186.30
blacklist-ip 69.63.186.31
blacklist-ip 69.63.187.12
blacklist-ip 69.63.189.16
blacklist-ip 69.63.190.26
blacklist-ip 69.171.224.12
blacklist-ip 69.171.224.40
blacklist-ip 69.171.224.85
blacklist-ip 69.171.225.13
blacklist-ip 69.171.227.37
blacklist-ip 69.171.228.20
blacklist-ip 69.171.228.74
blacklist-ip 69.171.229.11
blacklist-ip 69.171.229.28
blacklist-ip 69.171.229.73
blacklist-ip 69.171.230.18
blacklist-ip 69.171.232.21
blacklist-ip 69.171.233.24
blacklist-ip 69.171.233.33
blacklist-ip 69.171.233.37
blacklist-ip 69.171.234.18
blacklist-ip 69.171.234.29
blacklist-ip 69.171.234.48
blacklist-ip 69.171.235.101
blacklist-ip 69.171.235.16
blacklist-ip 69.171.235.64
blacklist-ip 69.171.237.16
blacklist-ip 69.171.237.26
blacklist-ip 69.171.239.11
blacklist-ip 69.171.240.27
blacklist-ip 69.171.242.11
blacklist-ip 69.171.242.30
blacklist-ip 69.171.244.11
blacklist-ip 69.171.244.12
blacklist-ip 69.171.244.15
blacklist-ip 69.171.245.49
blacklist-ip 69.171.245.53
blacklist-ip 69.171.245.84
blacklist-ip 69.171.246.9
blacklist-ip 69.171.247.20
blacklist-ip 69.171.247.32
blacklist-ip 69.171.247.71
blacklist-ip 69.171.248.112
blacklist-ip 69.171.248.128
blacklist-ip 69.171.248.65
blacklist-ip 72.14.205.104
blacklist-ip 72.14.205.99
blacklist-ip 74.86.118.24
blacklist-ip 74.86.12.172
blacklist-ip 74.86.12.173
blacklist-ip 74.86.142.55
blacklist-ip 74.86.151.162
blacklist-ip 74.86.151.167
blacklist-ip 74.86.17.48
blacklist-ip 74.86.226.234
blacklist-ip 74.86.228.110
blacklist-ip 74.86.235.236
blacklist-ip 74.86.3.208
blacklist-ip 75.126.115.192
blacklist-ip 75.126.124.162
blacklist-ip 75.126.135.131
blacklist-ip 75.126.150.210
blacklist-ip 75.126.164.178
blacklist-ip 75.126.2.43
blacklist-ip 75.126.215.88
blacklist-ip 75.126.33.156
blacklist-ip 78.16.49.15
blacklist-ip 88.191.249.182
blacklist-ip 88.191.249.183
blacklist-ip 88.191.253.157
blacklist-ip 93.46.8.89
blacklist-ip 128.121.126.139
blacklist-ip 159.106.121.75
blacklist-ip 169.132.13.103
blacklist-ip 173.252.73.48
blacklist-ip 173.252.100.21
blacklist-ip 173.252.100.32
blacklist-ip 173.252.102.16
blacklist-ip 173.252.102.241
blacklist-ip 173.252.103.64
blacklist-ip 173.252.110.21
blacklist-ip 174.36.196.242
blacklist-ip 174.36.228.136
blacklist-ip 174.37.54.20
blacklist-ip 174.37.154.236
blacklist-ip 174.37.175.229
blacklist-ip 192.67.198.6
blacklist-ip 199.16.156.40
blacklist-ip 199.16.156.7
blacklist-ip 199.16.158.190
blacklist-ip 199.59.148.14
blacklist-ip 199.59.148.140
blacklist-ip 199.59.148.209
blacklist-ip 199.59.148.97
blacklist-ip 199.59.149.136
blacklist-ip 199.59.149.244
blacklist-ip 199.59.150.11
blacklist-ip 199.59.150.49
blacklist-ip 202.106.1.2
blacklist-ip 202.181.7.85
blacklist-ip 203.98.7.65
blacklist-ip 203.161.230.171
blacklist-ip 205.186.152.122
blacklist-ip 207.12.88.98
blacklist-ip 208.43.170.231
blacklist-ip 208.43.237.140
blacklist-ip 208.56.31.43
blacklist-ip 208.101.21.43
blacklist-ip 208.101.48.171
blacklist-ip 208.101.60.87
blacklist-ip 209.36.73.33
blacklist-ip 209.145.54.50
blacklist-ip 209.220.30.174
blacklist-ip 211.94.66.147
blacklist-ip 213.169.251.35
blacklist-ip 216.221.188.182
blacklist-ip 216.234.179.13
blacklist-ip 243.185.187.39

**Comment by PikuZheng** [comment]
感觉是运营商污染 打debug log看看是哪个上游返回的1

**Comment by lalasou** [comment]
> 感觉是运营商污染 打debug log看看是哪个上游返回的1

搭配了一个 运营商dns ....


这个 怎么忽略 ::1

**Comment by pymumu** [comment]
打开debug log看一下什么原因。
或者可以配置
ignore-ip [::1]

**Comment by lalasou** [comment]
谢谢大佬

加了一个运营商dns  就这样了  
去掉运营商dns就没有了
加运营商dns 是因为 运营商dns 快些....
