### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by softeduscn** [pymumu/smartdns#97]
**问题现象**  
简要描述问题出现的现象
无法启动
**运行环境**
1. 固件型号  
主机型号	NETGEAR WNDR4300
架构	Atheros AR9344 rev 2
固件版本	OpenWrt SNAPSHOT r9358-ca13820 / LuCI Master (git-19.043.27122-eda8f02)
内核版本	4.14.101
系统由https://github.com/openwrt/openwrt编译
2. 安装成功 
smartdns.1.2019.02.16-0936.mips_24kc.ipk
luci-app-smartdns.1.2019.02.16-0936.all.ipk
3. 但无法启动，系统日志  
daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 seconds since last crash
4. 内核版本4.14.99版本前都可正常使用。

**Comment by pymumu** [comment]
打开debug日志，看看/var/log/smartdns.log有什么

**Comment by softeduscn** [comment]
系统重启后 系统日志
Sat Feb 16 14:25:45 2019 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Sat Feb 16 14:25:45 2019 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Sat Feb 16 14:25:46 2019 daemon.info procd: Instance smartdns::smartdns s in a crash loop 6 crashes, 0 
seconds since last crash
目录下无此文件 /var/log/smartdns.log
# ls /var/log
ddns          lastlog       log.nmbd      log.smbd      minidlna.log  samba         wtmp

**Comment by pymumu** [comment]
/usr/sbin/smartdns -h
看看

**Comment by softeduscn** [comment]
/usr/sbin/smartdns -h

Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/sbin/smartdns)
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/sbin/smartdns)
Error relocating /usr/sbin/smartdns: X509_NAME_get_text_by_NID: symbol not found
Error relocating /usr/sbin/smartdns: SSL_get_error: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_write: symbol not found
Error relocating /usr/sbin/smartdns: SSLv23_client_method: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_malloc: symbol not found
Error relocating /usr/sbin/smartdns: SSL_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_set_fd: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_num_locks: symbol not found
Error relocating /usr/sbin/smartdns: X509_get_subject_name: symbol not found
Error relocating /usr/sbin/smartdns: ERR_reason_error_string: symbol not found
Error relocating /usr/sbin/smartdns: SSL_library_init: symbol not found
Error relocating /usr/sbin/smartdns: SSL_get1_session: symbol not found
Error relocating /usr/sbin/smartdns: SSL_read: symbol not found
Error relocating /usr/sbin/smartdns: SSL_SESSION_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_new: symbol not found
Error relocating /usr/sbin/smartdns: OPENSSL_add_all_algorithms_noconf: symbol not found
Error relocating /usr/sbin/smartdns: SSL_shutdown: symbol not found
Error relocating /usr/sbin/smartdns: EVP_cleanup: symbol not found
Error relocating /usr/sbin/smartdns: ERR_free_strings: symbol not found
Error relocating /usr/sbin/smartdns: SSL_CTX_new: symbol not found
Error relocating /usr/sbin/smartdns: EVP_get_digestbyname: symbol not found
Error relocating /usr/sbin/smartdns: SSL_get_peer_certificate: symbol not found
Error relocating /usr/sbin/smartdns: SSL_ctrl: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_set_id_callback: symbol not found
Error relocating /usr/sbin/smartdns: X509_free: symbol not found
Error relocating /usr/sbin/smartdns: X509_digest: symbol not found
Error relocating /usr/sbin/smartdns: SSL_connect: symbol not found
Error relocating /usr/sbin/smartdns: SSL_CTX_free: symbol not found
Error relocating /usr/sbin/smartdns: SSL_load_error_strings: symbol not found
Error relocating /usr/sbin/smartdns: SSL_set_session: symbol not found
Error relocating /usr/sbin/smartdns: ERR_get_error: symbol not found
Error relocating /usr/sbin/smartdns: CRYPTO_set_locking_callback: symbol not found

**Comment by softeduscn** [comment]
是否与内核版本4.14.99以后升级了
openssl: update to version 1.1.1a  …有关

**Comment by pymumu** [comment]
是的，现在用的是openssl1.0.0

**Comment by softeduscn** [comment]
谢谢

**Comment by softeduscn** [comment]
将文件原来可用的文件
libssl.so.1.0.0
libcrypto.so.1.0.0
复制到/usr/lib
问题解决
