### ISSUE TITLE
dualstack-ip-allow-force-AAAA参数是干什么用的？

### ISSUE THREAD

**Issue by Xymmh** [pymumu/smartdns#971]
如题，感觉yes or no都没什么变化

**Comment by pymumu** [comment]
这个功能是是否允许smartdns在检测到域名的ipv6比ipv4快时强制客户端用ipv6访问的能力

但这有风险是如果客户端只支持ipv4的话，将导致客户端连不了网

目前发现不支持的软件有典型营业厅app，糖豆人反作弊软件
这两个可以通过domain-rule -d关闭双栈优选规避

所以现在默认情况下确保一定有ipv4地址，有ipv6的，会折腾的用户可以启用此功能
