### ISSUE TITLE
all-best-ip 版本存在内存泄漏

### ISSUE THREAD

**Issue by shiyunjin** [pymumu/smartdns#972]
**问题现象**  
https://github.com/pymumu/smartdns/releases/tag/all-best-ip
这个版本存在内存泄漏

**运行环境**
1. 固件型号  Koolshare lede v3.2

2. 运营商  电信

**重现步骤**
![image](https://user-images.githubusercontent.com/3510035/176390032-39559d6d-48e1-46ac-a732-08d1bf2deaaa.png)

**Comment by pymumu** [comment]
用master分支

**Comment by shiyunjin** [comment]
master分支的版本无此问题
