### ISSUE TITLE
smartdns 返回的 ip 是最慢的 ip

### ISSUE THREAD

**Issue by gitduk** [pymumu/smartdns#976]
**问题现象**  
smartdns 返回的 ip， time=200ms +
本地 dns 返回的 ip ， time=6ms +

**运行环境**
1. ubuntu

2. 运营商  电信

**重现步骤**
1. 上游DNS配置。  

_smartdns.conf 文件_
```
# https://github.com/pymumu/smartdns/blob/master/etc/smartdns/smartdns.conf
bind-tcp [::]:53
bind [::]:53
tcp-idle-time 3
cache-size 4096
prefetch-domain yes
serve-expired yes
serve-expired-ttl 0
speed-check-mode tcp:80,tcp:443,ping
rr-ttl-min 60
rr-ttl-max 86400
log-level warn
server 192.168.1.1
server 8.8.8.8 -blacklist-ip -check-edns
server-tcp 119.29.29.29
server-tcp 64.6.64.6
server-tcp 114.114.114.119
server-tcp 223.5.5.5
server-tls 1.1.1.1
server-tls 8.8.4.4
server-tls 9.9.9.9
server-https https://cloudflare-dns.com/dns-query
```

3. 访问的域名。  
www.baidu.com

**信息收集**  
1. 将/var/log/smrtdns.log日志作为附件上传。  
3. 如进程异常，请将coredump功能开启，上传coredump信息文件。  
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

*smartdns 解析结果*
![image](https://user-images.githubusercontent.com/48339766/177135056-9df9c813-3817-4e20-a9e8-d514a201c31c.png)

*本地 dns 解析结果*
![image](https://user-images.githubusercontent.com/48339766/177135213-868a9cff-af3c-4c6f-ab76-04e8b09ab4dc.png)

*smartdns.log*
![image](https://user-images.githubusercontent.com/48339766/177135385-2aa7cbf7-41c9-49a0-91ff-e778d853457f.png)

用的 docker 
```
#!/usr/bin/env bash

docker run -d \
    --name smartdns \
    -p 53:53/udp \
    --restart=always \
    -v $HOME/.smartdns:/smartdns \
    ghostry/smartdns
```

*/etc/resolv.conf*
```
nameserver 127.0.0.1
nameserver 192.168.70.1
nameserver 8.8.8.8

```

**Comment by PikuZheng** [comment]
另外开debug日志看一下是哪个上游返回的这个结果

**Comment by gitduk** [comment]
> 另外开debug日志看一下是哪个上游返回的这个结果

`64.6.64.6` 这个上游返回的这个结果

![image](https://user-images.githubusercontent.com/48339766/177231996-1447e48d-97d9-4a55-b101-a92d74594c54.png)

但是，今天又正常了！！！

什么情况，有大佬解释一下吗，以后遇到了也有解决措施。

**Comment by gitduk** [comment]
> 进docker看一下路由 感觉是从国外代理出去了

![image](https://user-images.githubusercontent.com/48339766/177232308-cfa61294-9ecc-4995-9471-22db6de20da1.png)

路由在此。

**Comment by PikuZheng** [comment]
>64.6.64.6 这个上游返回的这个结果

那结果符合预期啊

**Comment by gitduk** [comment]
> > 64.6.64.6 这个上游返回的这个结果
> 
> 那结果符合预期啊

`64.6.64.6` 这个上游返回的结果比较慢
`114.114.114.119` 这个上游返回结果快

为什么不给我 `114.114.114.119` 的结果，反而给我 `64.6.64.6` 的结果，是我的配置有问题吗。

**Comment by gitduk** [comment]
刚刚又实验了一下
第一条命令（smartdns）：
![image](https://user-images.githubusercontent.com/48339766/177245232-642b165f-1857-43dc-84d4-ea45c507ebcd.png)

第二条命令（223.5.5.5）：
![image](https://user-images.githubusercontent.com/48339766/177245346-5169c374-ae60-4e99-96f8-b53593b4e53f.png)

再重复第一条命令（smartdns）：
![image](https://user-images.githubusercontent.com/48339766/177245406-19682dea-e29a-47b9-b49b-432d865015a9.png)

为什么会出现这个情况。是正常的吗。

**Comment by PikuZheng** [comment]
没有debug日志，看不出来中间究竟是怎么走的。目前我猜是docker访问外网，被代理或路由到国外转了一圈。最快应答的应该是192.168.1.1，很有可能首次测速超时，于是随便返回了个最快应答。二次查询是从缓存拿到的结果，此时测速已经完成了。
这个表现倒是像6月初的某个版本，请先升级到最新版看一下。

**Comment by gitduk** [comment]
> 没有debug日志，看不出来中间究竟是怎么走的。目前我猜是docker访问外网，被代理或路由到国外转了一圈。最快应答的应该是192.168.1.1，很有可能首次测速超时，于是随便返回了个最快应答。二次查询是从缓存拿到的结果，此时测速已经完成了。 这个表现倒是像6月初的某个版本，请先升级到最新版看一下。

好的好的，请问一下最新版有 docker 版本吗。目前用的 docker 镜像是 ghostry/smartdns

**Comment by PikuZheng** [comment]
可以试试我的 pikuzheng/smartdns 或用dockerfile自己生成

**Comment by gitduk** [comment]
> 可以试试我的 pikuzheng/smartdns 或用dockerfile自己生成

你好，我放弃使用 docker 了，直接安装 *.deb 包，安装完成后，我在网上找了一个广告屏蔽配置

![image](https://user-images.githubusercontent.com/48339766/177293791-158b9e43-7d09-4723-8ce5-fc6b2f9ebd1e.png)

一开始运行正常，突然某一刻，电脑非常卡，我一看，smartdns 内存占用到了 60%

*log 文件*
![image](https://user-images.githubusercontent.com/48339766/177294399-473a43ee-204c-4aab-902d-0acdcf6f0adb.png)

想请教两个问题
1. 内存占用过多是配置文件过长的导致的吗
2. 这个 log 文件全是 failed 正常吗

**Comment by gitduk** [comment]
> 5月3日的版本有内存泄漏的问题。请使用最新版本

抱歉抱歉，我以为安装的是最新版本。

![image](https://user-images.githubusercontent.com/48339766/177296922-90a2ff2d-f589-40a9-a2f9-e2307f958db3.png)

没经验，以为这个 latest 就是最新版本，结果安装的是 1.2022.04.05-2046

**Comment by gitduk** [comment]
> 5月3日的版本有内存泄漏的问题。请使用最新版本

大佬大佬

遇到一个很奇怪的问题，由于我书写的广告屏蔽规则失败
`address /sohu.com/#`
还是能打开搜狐

于是我对电脑进行重启。
address /sohu.com/#

开启服务的时候会遇到这种情况
![image](https://user-images.githubusercontent.com/48339766/177307026-d3587489-f20b-4a68-809c-55722115d333.png)

`/etc/smartdns` 文件权限
![image](https://user-images.githubusercontent.com/48339766/177307185-5992d90d-886a-45e5-8b15-89ac60eb5f46.png)

`journalctl -xeu smartdns`
![image](https://user-images.githubusercontent.com/48339766/177307460-f01fc596-785b-4912-a3d4-6720ecbf28e5.png)

为什么会遇到权限问题，就很奇怪。

**Comment by PikuZheng** [comment]
这里看不出有什么问题。如果smartdns无法启动，请查看smartdns的日志

**Comment by gitduk** [comment]
> 这里看不出有什么问题。如果smartdns无法启动，请查看smartdns的日志

大佬牛批，已经可以正常启动了
就是有一个无伤大雅的小问题。

规则太多会导致启动失败
就我那 5w + 条的广告屏蔽规则: https://anti-ad.net/anti-ad-for-smartdns.conf

在配置文件里面加: `conf-file /home/wukaige/.smartdns/anti-ad-for-smartdns.conf`

就会导致启动失败

log 日志好像也看不出什么

![image](https://user-images.githubusercontent.com/48339766/177529260-37b69266-eb7c-49f8-8c20-ed97bc9577eb.png)

**Comment by PikuZheng** [comment]
不会啊 我也用这个anti-ad 54923行目前
最后这个日志 18:18:07 看起来是人工停止的

**Comment by pymumu** [comment]
systemctl status smartdns
看一次报错原因。

**Comment by gitduk** [comment]
> systemctl status smartdns 看一下报错原因。

![image](https://user-images.githubusercontent.com/48339766/177670431-7b557fa8-f62a-4b66-a2a3-100c4f3e0f4c.png)

错误码是 1

**Comment by pymumu** [comment]
smartdns -f -x -c /etc/smartdns/smartdns.conf 
看看log是什么

**Comment by gitduk** [comment]
> smartdns -f -x -c /etc/smartdns/smartdns.conf 看看log是什么

![image](https://user-images.githubusercontent.com/48339766/177672651-e1c45e4e-0150-4469-a185-0c812c92c0cd.png)

是这个，我用的 https://anti-ad.net/anti-ad-for-smartdns.conf
按理说规则没问题

**Comment by PikuZheng** [comment]
`/etc/smartdns/smartdns.conf` 你看下这个文件219行是什么 感觉是配置文件嵌套循环了

**Comment by gitduk** [comment]
> `/etc/smartdns/smartdns.conf` 你看下这个文件219行是什么 感觉是配置文件嵌套循环了

![image](https://user-images.githubusercontent.com/48339766/177674844-1cede5ad-de17-44a0-b4a4-82fcb7614915.png)

好像没有，
`/etc/smartdns/smartdns.conf` 加载本地配置文件 `~/.smartdns/smartdns.conf`
本地配置文件加载广告过滤配置文件 `~/.smartdns/anti-ad-for-smartdns.conf`

**Comment by gitduk** [comment]
> > `/etc/smartdns/smartdns.conf` 你看下这个文件219行是什么 感觉是配置文件嵌套循环了
> 
> ![image](https://user-images.githubusercontent.com/48339766/177674844-1cede5ad-de17-44a0-b4a4-82fcb7614915.png)
> 
> 好像没有， `/etc/smartdns/smartdns.conf` 加载本地配置文件 `~/.smartdns/smartdns.conf` 本地配置文件加载广告过滤配置文件 `~/.smartdns/anti-ad-for-smartdns.conf`

好像配置文件不能写 `$HOME` 我只能把路径写死

**Comment by PikuZheng** [comment]
`/home/wukaige/.smartdns/smartdns.conf` 可以把这个文件完整的传上来？

**Comment by gitduk** [comment]
> 

当然可以，文件内容并不多

```
server 192.168.70.1
server 8.8.8.8

server-tcp 119.29.29.29
server-tcp 64.6.64.6
server-tcp 114.114.114.119
server-tcp 223.5.5.5

server-tls 1.1.1.1
server-tls 8.8.4.4
server-tls 9.9.9.9

server-https https://cloudflare-dns.com/dns-query

# custom
conf-file /home/wukaige/.smartdns/block.conf

# https://anti-ad.net/anti-ad-for-smartdns.conf
# conf-file /home/wukaige/.smartdns/anti-ad-for-smartdns.conf
```

最后一行，如果取消注释，就会启动不成功。

**Comment by gitduk** [comment]
> `/home/wukaige/.smartdns/smartdns.conf` 可以把这个文件完整的传上来？

> 

当然可以，文件内容并不多

```
server 192.168.70.1
server 8.8.8.8

server-tcp 119.29.29.29
server-tcp 64.6.64.6
server-tcp 114.114.114.119
server-tcp 223.5.5.5

server-tls 1.1.1.1
server-tls 8.8.4.4
server-tls 9.9.9.9

server-https https://cloudflare-dns.com/dns-query

# custom
conf-file /home/wukaige/.smartdns/block.conf

# https://anti-ad.net/anti-ad-for-smartdns.conf
# conf-file /home/wukaige/.smartdns/anti-ad-for-smartdns.conf
```

最后一行，如果取消注释，就会启动不成功。

**Comment by pymumu** [comment]
/home/wukaige/.smartdns/anti-ad-for-smartdns.conf
这个文件里面有什么？

**Comment by gitduk** [comment]
> /home/wukaige/.smartdns/anti-ad-for-smartdns.conf 这个文件里面有什么？

这可就太长了，有 5w + 行，你可以从这里看到:  https://anti-ad.net/anti-ad-for-smartdns.conf

**Comment by pymumu** [comment]
这个我加载了，是好的。

**Comment by gitduk** [comment]
> /home/wukaige/.smartdns/anti-ad-for-smartdns.conf 这个文件里面有什么？

抱歉抱歉，花费你那么多时间，我重新下载了一下这个配置文件，然后加载成功了

**Comment by gitduk** [comment]
> 这个我加载了，是好的。你要不重新下载那个文件。

应该是出于某种原因，配置文件被修改
基于这点，能不能提点建议：

1, 配置文件加载出错，给个提醒，因为服务无法启动，在不知道配置出现问题的情况下，并不清楚排查方向。
2, 对于非必要配置出错的，例如 address /xxx.xxx.com/# 这种域名过滤配置，有办法忽略这种错误，使服务正常运行吗。

**Comment by pymumu** [comment]
这个log应该打印在了/var/log/message文件中了，可以加一个FAQ

**Comment by gitduk** [comment]
> 这个log应该打印在了/var/log/message文件中了，可以加一个FAQ

我尝试 `cat /var/log/message` 
提示并没有这个文件

**Comment by PikuZheng** [comment]
标准linux应该是journal日志了 试试 `journalctl -a /usr/sbin/smartdns`

**Comment by gitduk** [comment]
我尝试复现配置文件错误，加了一行错误配置
![image](https://user-images.githubusercontent.com/48339766/177684151-afafbe25-d9c6-4eed-8759-7ea92c01d9b6.png)

然后 `journalctl -a /usr/sbin/smartdns`
![image](https://user-images.githubusercontent.com/48339766/177684413-12fae401-1160-4ebd-ae03-a35aa8c7a3e2.png)

是我的系统问题吗
![image](https://user-images.githubusercontent.com/48339766/177684491-e327431b-023d-4c29-8425-ac7d286b111f.png)

**Comment by pymumu** [comment]
cat /var/log/messages  | grep smartdns

**Comment by gitduk** [comment]
> cat /var/log/messages | grep smartdns

抱歉，是我的问题，高版本系统默认关闭  /var/log/messages 记录，所以我没有这个文件。
