### ISSUE TITLE
关闭ipset-timeout后会导致smartdns崩溃

### ISSUE THREAD

**Issue by shiyunjin** [pymumu/smartdns#978]
**问题现象**  
```
ipset-timeout no
```
会导致smartdns运行一会后崩溃(可能也不是这个选项的原因,但是我开之前没遇到过崩溃)

**运行环境**
1. 固件型号  
Koolshare lede
2. 运营商  
电信

**信息收集**  

[coredump.zip](https://github.com/pymumu/smartdns/files/9048411/coredump.zip)

**Comment by pymumu** [comment]
意思是开启ipset超时会异常？

**Comment by shiyunjin** [comment]
> 意思是开启ipset超时会异常？

强制设置为no会崩溃，不写这行就行了，现在没崩过，但是不确定是不是这个原因，我去掉这行之后也是重启了很多次，删除了好像是/tmp/smartdns.less这个文件后才稳定跑起来

**Comment by shiyunjin** [comment]
看来和上面的选项没关系,今天上午更新了最新master代码之后,晚上发现内存满了,原因是core文件占满了/tmp分区
![image](https://user-images.githubusercontent.com/3510035/178030182-af4b09bd-11f7-4701-8e90-424527c247d0.png)

手快直接删除了,没下下来core文件,仅反馈一下崩溃情况还存在

**Comment by PikuZheng** [comment]
https://github.com/pymumu/smartdns/issues/979#issuecomment-1177018487
这个方法试试 最新代码3961行

**Comment by shiyunjin** [comment]
刚刚又发生了连续的崩溃,启动后1分钟之后就会崩溃,需要删除`/tmp/smartdns.cache` 后才能稳定启动(没有尝试https://github.com/pymumu/smartdns/issues/979#issuecomment-1177018487 的方法)

附上core文件
[smartdns.1657380722.18747.11.zip](https://github.com/pymumu/smartdns/files/9077437/smartdns.1657380722.18747.11.zip)

**Comment by pymumu** [comment]
你用的版本是什么时候的。
如果可以的话，用这个测试下。
[Uploading smartdns.1.2022.07.09-1048.x86_64-openwrt-all.ipk.zip…]()

**Comment by shiyunjin** [comment]
> 你用的版本是什么时候的。 如果可以的话，用这个测试下。
> 
> [smartdns.1.2022.07.10-1018.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/9078291/smartdns.1.2022.07.10-1018.x86_64-openwrt-all.ipk.zip)
> 
> 另外，core以后，麻烦发一下。

安装上了,可能要等14个小时之后看结果,我感觉这几次崩溃都是在凌晨附近

**Comment by shiyunjin** [comment]
> 你用的版本是什么时候的。 如果可以的话，用这个测试下。
> 
> [smartdns.1.2022.07.10-1018.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/9078291/smartdns.1.2022.07.10-1018.x86_64-openwrt-all.ipk.zip)
> 
> 另外，core以后，麻烦发一下。

这个版本出现了一个特别逼的情况,他不崩溃,但是完全不响应任何dns事件,没有core文件,而且查看日志整个日志文件就两行
```
root@LEDE:~# cat /var/log/smartdns.log
[2022-07-10 14:52:36,111][ INFO][     dns_client.c:3388] retry query tracker.pow7.com, type: 1, id: 20249 failed
[2022-07-10 14:52:36,111][DEBUG][     dns_client.c:1398] result: tracker.pow7.com, qtype: 1, hasresult: 0, id 20249
```

而且启动很慢,我现在即使重启也得等很久才能看到启动信息(刷日志),(在刷日志之前完全收不到任何dns请求,大约一分钟), 然后过一会就卡死了(大概不到一分钟), 删除/tmp/smartdns.cache也没有用

看下面日志的时间
```
[2022-07-10 17:01:22,040][ INFO][     dns_client.c:3388] retry query ns1.mindcraft.si.eu.org, type: 1, id: 539 failed
[2022-07-10 17:01:22,040][DEBUG][     dns_client.c:1398] result: ns1.mindcraft.si.eu.org, qtype: 1, hasresult: 0, id 539[2022-07-10 17:04:19,301][ INFO][       smartdns.c:411 ] stop smartdns by signal 15
tail: /var/log/smartdns.log has been replaced; following end of new file
[2022-07-10 17:05:19,556][NOTICE][       smartdns.c:344 ] smartdns starting...(Copyright (C) Nick Peng <pymumu@gmail.com>, build:Jul 10 2022 10:19:26)
[2022-07-10 17:05:19,561][ INFO][     dns_server.c:3613] ICMP ping is disabled, no ipv6 icmp check feature
[2022-07-10 17:05:19,561][ INFO][     dns_server.c:5156] IPV6 is not ready, disable IPV6 features

........

[2022-07-10 17:06:34,246][DEBUG][     dns_client.c:1398] result: subscribe.insight.synology.com, qtype: 1, hasresult: 1, id 906
[2022-07-10 17:07:24,996][ INFO][       smartdns.c:411 ] stop smartdns by signal 15
```

已经回退版本了,这个版本完全用不了,一分钟左右就会卡死

**Comment by shiyunjin** [comment]
切到旧版本马上开始夺命连环core
![image](https://user-images.githubusercontent.com/3510035/178138794-8a5e1b03-a9dc-46a9-a578-34141b682742.png)

我这个版本是8号打包的也就是`4e2161c6fc51f8f6ee233a52c9b6eed82b816370`这个commit的版本

[core.zip](https://github.com/pymumu/smartdns/files/9078777/core.zip)

时间表现和上面的基本一直,唯一不同的是

> 你用的版本是什么时候的。 如果可以的话，用这个测试下。
> 
> [smartdns.1.2022.07.10-1018.x86_64-openwrt-all.ipk.zip](https://github.com/pymumu/smartdns/files/9078291/smartdns.1.2022.07.10-1018.x86_64-openwrt-all.ipk.zip)
> 
> 另外，core以后，麻烦发一下。
这个版本完全不会崩溃,会永久卡死

我8号打包的版本会在卡死的时候崩溃

**Comment by pymumu** [comment]
没找到这个commit

**Comment by shiyunjin** [comment]
> 没找到这个commit

https://github.com/pymumu/smartdns/commit/4e2161c6fc51f8f6ee233a52c9b6eed82b816370

**Comment by shiyunjin** [comment]
> 你那个log，能否发一个完整的。就是很慢的那个，还有就是配置发一下。

配置可以参考 https://github.com/pymumu/smartdns/issues/975#issue-1292760529 ,log我看过了是突然卡住的,没有任何错误和异常的信息

**Comment by pymumu** [comment]
能否看一下cpu占用率的情况，还有看一下这个命令的结果

ps -mlLp [pid]

**Comment by pymumu** [comment]
我这里没法复现，所以比较难定位，最好是能找到复现方法。

**Comment by shiyunjin** [comment]
> 我这里没法复现，所以比较难定位，最好是能找到复现方法。
命令无效
```
root@LEDE:~# ps -mlLp 6921
ps: unrecognized option: m
BusyBox v1.35.0 (2022-04-13 03:37:18 UTC) multi-call binary.

Usage: ps

Show list of processes

        w       Wide output
        l       Long output
        T       Show threads
```

顺带一提,我没有开任何测速,没有出现过断网或者重播换ip的情况, 而且一但崩溃是可以稳定复现的,唯一的问题就在于他一崩溃我这里github就打不开了,反馈很麻烦

**Comment by shiyunjin** [comment]
你可以提供一个打满log的版本,最好能从log上显现出来,core文件可能不太好找出问题

**Comment by pymumu** [comment]
那个命令不支持看线程的。
你用这个命令
cat /proc/[pid]/task/*/stat

多执行几次，第14列是cpu执行时间。

**Comment by shiyunjin** [comment]
> 卡主的时候，CPU占用率有看过吗？
> 
> 那个命令不支持看线程的。 你用这个命令 cat /proc/[pid]/task/*/stat
> 
> 多执行几次，第14列是cpu执行时间。

```
root@LEDE:~# cat /proc/6921/task/*/stat
6921 (smartdns) S 1 1 1 0 -1 4194560 19090 156560 0 0 830 955 376 72 20 0 4 0 66735574 32354304 7624 18446744073709551615 4198400 6451108 140722728629888 0 0 0 0 4096 16386 1 0 0 17 1 0 0 0 0 0 7101248 7324688 37486592 140722728636217 140722728636277 140722728636277 140722728636389 0
6922 (smartdns) S 1 1 1 0 -1 1077936448 256 156560 0 0 186 448 376 72 20 0 4 0 66735598 32354304 7624 18446744073709551615 4198400 6451108 140722728629888 0 0 0 0 4096 16386 1 0 0 -1 0 0 0 0 0 0 7101248 7324688 37486592 140722728636217 140722728636277 140722728636277 140722728636389 0
6923 (smartdns) S 1 1 1 0 -1 4194368 0 156560 0 0 85 132 376 72 20 0 4 0 66735598 32354304 7624 18446744073709551615 4198400 6451108 140722728629888 0 0 0 0 4096 16386 1 0 0 -1 1 0 0 0 0 0 7101248 7324688 37486592 140722728636217 140722728636277 140722728636277 140722728636389 0
6924 (smartdns) S 1 1 1 0 -1 4194624 7913 156560 0 0 693 542 376 72 20 0 4 0 66735598 32354304 7624 18446744073709551615 4198400 6451108 140722728629888 0 0 0 0 4096 16386 1 0 0 -1 1 0 0 0 0 0 7101248 7324688 37486592 140722728636217 140722728636277 140722728636277 140722728636389 0
root@LEDE:~#
```

**Comment by pymumu** [comment]
配置发一下吧，吧server相关的去掉。

**Comment by shiyunjin** [comment]
> 配置发一下吧，吧server， address相关的去掉。

ipset的也去掉的话就是这个

```
bind [::]:6053
bind-tcp [::]:6053
dualstack-ip-selection no
prefetch-domain yes
serve-expired yes
cache-size 50000
rr-ttl 60
rr-ttl-min 10
rr-ttl-max 60
rr-ttl-reply-max 10
log-size 64K
log-num 1
log-level error
bind [::]:6553  -no-speed-check -no-dualstack-selection -no-cache
bind-tcp [::]:6553  -no-speed-check -no-dualstack-selection -no-cache

# Add custom settings here.

# set log level
# log-level [level], level=fatal, error, warn, notice, info, debug
log-level debug

# log-size k,m,g
# log-size 128k

# log-file /var/log/smartdns.log
# log-num 2

# List of hosts that supply bogus NX domain results
# bogus-nxdomain [ip/subnet]

# edns
edns-client-subnet ***.***.**.0/24

# dis ipv6
force-AAAA-SOA yes

speed-check-mode none
dualstack-ip-selection-threshold 100

max-reply-ip-num 50
```

**Comment by PikuZheng** [comment]
> 现在进程状态是正常的 卡住的时候cpu较高, 13-30%左右,当时看过

4核的嘛？30%就是单线程跑满了

**Comment by pymumu** [comment]
[smartdns.1.2022.07.10-2249.x86_64-openwrt-all.ipk.gz](https://github.com/pymumu/smartdns/files/9079284/smartdns.1.2022.07.10-2249.x86_64-openwrt-all.ipk.gz)

有空的话，验证下这个

**Comment by shiyunjin** [comment]
> [smartdns.1.2022.07.10-2249.x86_64-openwrt-all.ipk.gz](https://github.com/pymumu/smartdns/files/9079284/smartdns.1.2022.07.10-2249.x86_64-openwrt-all.ipk.gz)
> 
> 有空的话，验证下这个

已经装上了

**Comment by pymumu** [comment]
这个什么配置的什么类型的dns，ip地址类型的DNS配置项，不应该进入pending server添加流程。
看一下对应位置的配置是不是格式上有问题

**Comment by shiyunjin** [comment]
> 这个什么配置的什么类型的dns，ip地址类型的DNS配置项，不应该进入pending server添加流程。 看一下对应位置的配置是不是格式上有问题

```
#省略一大堆server-https的服务器
server-https https://1.12.12.12/dns-query  -group china -exclude-default-group
server-https https://101.6.6.6:8443/dns-query
server [127.0.0.1:7913]  -check-edns
```

**Comment by pymumu** [comment]
把中括号去掉，中括号是用在ipv6的地址的。

**Comment by shiyunjin** [comment]
> 把中括号去掉，中括号是用在ipv6的地址的。

luci自动加的
![image](https://user-images.githubusercontent.com/3510035/178150787-cf1ac1be-34a9-4592-b0f0-c7e43d50763e.png)

**Comment by pymumu** [comment]
这个肯定不能工作的。要写也是这样

server [127.0.0.1]:7913  -check-edns

**Comment by shiyunjin** [comment]
> 这个肯定不能工作的。要写也是这样
> 
> server [127.0.0.1]:7913 -check-edns
> 
> 端口要写到default那里。不是写IP地址那里。

额,那是不是会产生循环,然后被cache捕获消除了循环

**Comment by pymumu** [comment]
没有ip地址的DNS的话，会使用系统的dns请求解析。
但如果你系统的也指向smartdns，那就死循环了。

**Comment by PikuZheng** [comment]
ip地址里带冒号 当成ipv6了 luci上ip和端口是分成两个不同的框框

**Comment by shiyunjin** [comment]
> > [smartdns.1.2022.07.10-2249.x86_64-openwrt-all.ipk.gz](https://github.com/pymumu/smartdns/files/9079284/smartdns.1.2022.07.10-2249.x86_64-openwrt-all.ipk.gz)
> > 有空的话，验证下这个
> 
> 已经装上了
> 
> 一眼看见了好几个failed, 这个影不影响(这是server中的唯一一个udp服务器) 后面的14看了一下区间是1-20
> 
> ```
> add pending DNS server 127.0.0.1:7913 failed, retry 14...
> ```

看top进程运行了6个小时,可是我早上9点并没有做过任何重启和修改配置操作
![image](https://user-images.githubusercontent.com/3510035/178213489-ddcac777-2b82-47a7-9d30-da70bc909bbe.png)

没有产生core文件,日志时间太长看不到了

**Comment by pymumu** [comment]
[smartdns.1.2022.07.14-2341.x86_64-openwrt-all.zip](https://github.com/pymumu/smartdns/files/9113245/smartdns.1.2022.07.14-2341.x86_64-openwrt-all.zip)

有空的话，帮忙验证下这个看看有无问题。

**Comment by shiyunjin** [comment]
> [smartdns.1.2022.07.14-2341.x86_64-openwrt-all.zip](https://github.com/pymumu/smartdns/files/9113245/smartdns.1.2022.07.14-2341.x86_64-openwrt-all.zip)
> 
> 有空的话，帮忙验证下这个看看有无问题。

存在内存泄漏
![image](https://user-images.githubusercontent.com/3510035/179363610-0d16de97-890f-4894-ac2c-6b439a1c726f.png)

**Comment by pymumu** [comment]
kill -15 停止下进程，然后就看看/tmp/smartdns.cache文件有多大。
