### ISSUE TITLE
smartdns[20164]: segfault at 7fa61c473058 ip 0000000000412068 sp 00007fff7d8bbaf0 error 6 in smartdns[404000+1f000]

### ISSUE THREAD

**Issue by GreatMichaelLee** [pymumu/smartdns#986]
**问题现象**  
Sat Jul 16 13:51:51 2022 kern.info kernel: [81934.232997] smartdns[20164]: segfault at 7fa61c473058 ip 0000000000412068 sp 00007fff7d8bbaf0 error 6 in smartdns[404000+1f000]
Sat Jul 16 13:51:51 2022 kern.info kernel: [81934.234934] Code: df e8 20 bf ff ff 49 8b 85 38 01 00 00 48 8d 53 28 49 8d 8d 30 01 00 00 4c 89 ef 49 89 95 38 01 00 00 48 89 4b 28 48 89 43 30 <48> 89 10 ff 15 5f ee 01 00 bf 50 2b 43 00 ff 15 54 ee 01 00 45 85

**运行环境**
1. LEDE X86 latest repo k-5.18.11

2. 运营商  
CT+CM

3. smartdns来源以及版本
git repo here,latest commit

4. 涉及的配置(注意去除个人相关信息)
NA

**重现步骤**
1. openwrt log
Sat Jul 16 13:51:51 2022 kern.info kernel: [81934.232997] smartdns[20164]: segfault at 7fa61c473058 ip 0000000000412068 sp 00007fff7d8bbaf0 error 6 in smartdns[404000+1f000]
Sat Jul 16 13:51:51 2022 kern.info kernel: [81934.234934] Code: df e8 20 bf ff ff 49 8b 85 38 01 00 00 48 8d 53 28 49 8d 8d 30 01 00 00 4c 89 ef 49 89 95 38 01 00 00 48 89 4b 28 48 89 43 30 <48> 89 10 ff 15 5f ee 01 00 bf 50 2b 43 00 ff 15 54 ee 01 00 45 85

2. gdb dump, smartdns非-g编译，所以没有堆栈，看不出什么卵来
![image](https://user-images.githubusercontent.com/20067401/179345122-e349ac5c-dc8e-43c2-8672-01fed82f588e.png)

3. debug log
![image](https://user-images.githubusercontent.com/20067401/179345155-eef23b73-c414-425a-8d19-d27fe1f785cb.png)

**Comment by PikuZheng** [comment]
今天上午（16日9点至12点之间）更新的刚修正崩溃问题 #978 #979

**Comment by GreatMichaelLee** [comment]
OK, 我这个版本应该是没有编译进进今天上午的fix, 我等下编译进去并且加上-g参数，再验证一下。多谢
