### ISSUE TITLE
安装在archLinux上出错

### ISSUE THREAD

**Issue by shanjiayi** [pymumu/smartdns#989]
在arch上安装会显示'etc/default/smartdns' -> '/etc/default/smartdns'
install: failed to access '/etc/init.d': No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
19年有大佬提过，那个我试了一下还是老样子。希望能帮我解决一下，谢谢
![QQ截图20220718122721](https://user-images.githubusercontent.com/98953455/179445394-a654595e-4cc1-48dc-bad9-45c5236d2d25.png)

**Comment by PikuZheng** [comment]
`ln -s /etc/rc.d /etc/init.d`
安装后编辑 `/etc/rc.conf` 将smartdns设置为自启动

**Comment by pymumu** [comment]
sh -x ./install -i
发一下输出的log

**Comment by shanjiayi** [comment]
不用了，arch太折腾人了，已经换成Ubuntu。谢谢
