### ISSUE TITLE
esir、sirpdboy编译的openwrt卸载预装的smartdns手动安装37 RC2版本报错无法启动

### ISSUE THREAD

**Issue by zsbstephen** [pymumu/smartdns#992]
RT，试过用esir和sirpdboy发布的openwrt，卸载预装的36版本，手动装37 RC2版本，安装完之后smartdns没有出现在左边的服务列表里面，手动打开smartdns网址，结果就是报错。

`No page is registered at '/admin/services/smartdns'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.`

请问该如何解决？

想装37版原因无他，改进太大了。

**Comment by PikuZheng** [comment]
请先卸载luci-app......ipk，然后再安装luci-app.....-compat-all.ipk。顺便问一下这个openwrt不会是像coolsnowwolf那样强制隐藏菜单的吧？

**Comment by zsbstephen** [comment]
> 请先卸载luci-app......ipk，然后再安装luci-app.....-compat-all.ipk。顺便问一下这个openwrt不会是像coolsnowwolf那样强制隐藏菜单的吧？

是按这个顺序卸载和安装的，compat-all.ipk也装了，但就是没有在左边出现，打开网址还是报错。
那两位大佬编译的openwrt是不是隐藏菜单就不清楚了。

**Comment by PikuZheng** [comment]
> 是按这个顺序卸载和安装的，compat-all.ipk也装了，但就是没有在左边出现，打开网址还是报错。 那两位大佬编译的openwrt是不是隐藏菜单就不清楚了。

compat不能覆盖安装。必须在卸载完了的情况下安装。

**Comment by pymumu** [comment]
不要更换luci，更新smartdns主程序就可以了。
有些特别的配置可以在custom里面设置好。

**Comment by zsbstephen** [comment]
> > 是按这个顺序卸载和安装的，compat-all.ipk也装了，但就是没有在左边出现，打开网址还是报错。 那两位大佬编译的openwrt是不是隐藏菜单就不清楚了。
> 
> compat不能覆盖安装。必须在卸载完了的情况下安装。

不是已经说了就是按先卸载luci-app-smart再卸载smart之后才安装github release这里发布的ipk顺序么……

**Comment by zsbstephen** [comment]
> 不要更换luci，更新smartdns主程序就可以了。 有些特别的配置可以在custom里面设置好。

这招试过，不行，提示not downgrading不允许降级……两个大佬编译发布的openwrt都是这样，有点诡异。

**Comment by PikuZheng** [comment]
用的 `20220721-Ipv6-Plus-5.4-x86-64-generic-squashfs-combined-efi.img` 这个镜像，安装后发现自带smartdns。在 系统-软件包 中移除了 `smartdns 36.1-42` (看提示，同时自动移除了luci-app-smartdns、bypass、luci-i18n-bypass-zh-cn)。
然后先安装了`smartdns.1.2022.07.16-1236.x86_64-openwrt-all.ipk`，再安装了`luci-app-smartdns.1.2022.07.16-1236.all-luci-compat-all.ipk`。刷新网页并观察服务菜单，有SmartDNS（在 动态 DNS 和 迅雷快鸟 中间）。

此前用 coolsnowwolf 试过，luci-app......ipk 和 luci-app.....-compat-all.ipk 可以同时安装，不提示冲突。但安装了 luci-app......ipk，菜单里是没有的。此时再安装compat，或安装compat后再卸载非compat，菜单里都没有。**必须在确保没有 luci-app......ipk 的情况下新装 luci-app.....-compat-all.ipk** 才可以。

**Comment by openips** [comment]
https://t.me/mwan3 这里面的固件直接集成最新的SMARTDNS
