### ISSUE TITLE
怎么配置以不发送sni

### ISSUE THREAD

**Issue by HX-Technology-LLC** [pymumu/smartdns#993]
部分dns服务器受到sni阻断,切其不支持IP证书,若要不发送sni是server-tls 8.8.8.8:853 -host-name *还是server-tls 8.8.8.8:853 -host-name  这样直接打空格

**Comment by pymumu** [comment]
```shell
server-tls 8.8.8.8
```

**Comment by pymumu** [comment]
那个是证书，没法去掉。
