### ISSUE TITLE
请问edns是默认开启的吗？

### ISSUE THREAD

**Issue by ZYB14** [pymumu/smartdns#998]
还是需要像这样在后面加上-check-edns
server 114.114.114.114 -check-edns

**Comment by 4thanks** [comment]
[checkedns不用对国内设置，会导致国内解析失效。](https://github.com/pymumu/smartdns/issues/666#issuecomment-757094739)

**Comment by ZYB14** [comment]
> [checkedns不用对国内设置，会导致国内解析失效。](https://github.com/pymumu/smartdns/issues/666#issuecomment-757094739)

thanks
